### ISSUE TITLE
Requested array size exceeds VM limit - no logs or warnings outside of DBeaver CLI

### ISSUE THREAD

**Issue by Darker** [dbeaver/dbeaver#10023]
#### System information: 
- Windows 10d
- 6.0.4

#### Connection specification:
- .sqlite

#### Describe the problem you're observing:
DBeaver shows splash screen, then dissapears. The process is still running but with no UI. No logs are generated at the folder described in the wiki or next the dbeavers executable.

Only after running the CLI version, I found it has something to do with memory. I tried to set the memory limits to this:
```
-Xms256m
-Xmx4096m
```
It did not resolve the issue.
#### Steps to reproduce, if exist:
I do not know why this started happening. Dbeaver has several .sqlite DBs open.

#### Include any warning/errors/backtraces from the logs
```
2020-10-08 20:32:44.108 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.8.201905052017]
2020-10-08 20:32:49.707 - Internal error in workbench lifecycle
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:569)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.setDocumentContent(FileStoreTextFileBuffer.java:538)
        at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.initializeFileBufferContent(FileStoreTextFileBuffer.java:319)
        at org.eclipse.core.internal.filebuffers.FileStoreFileBuffer.create(FileStoreFileBuffer.java:66)
        at org.eclipse.core.internal.filebuffers.TextFileBufferManager.connectFileStore(TextFileBufferManager.java:150)
        at org.eclipse.ui.editors.text.TextFileDocumentProvider.createFileInfo(TextFileDocumentProvider.java:571)
        at org.eclipse.ui.editors.text.TextFileDocumentProvider.connect(TextFileDocumentProvider.java:481)
        at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4169)
        at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:260)
        at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1477)
        at org.eclipse.ui.editors.text.TextEditor.doSetInput(TextEditor.java:153)
        at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3136)
        at org.eclipse.ui.texteditor.AbstractTextEditor$$Lambda$266/852547563.run(Unknown Source)
        at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2193)
        at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3153)
        at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3178)
        at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:365)
        at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:345)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1001)
        at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:966)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)
```

**Comment by uslss** [comment]
Hi @Darker ,
could you try if the issue is reproducible against the recent version (7.2.3)?

**Comment by Darker** [comment]
Unfortunately, I did not have the option to maintain the reproducible state. I needed dbeaver so I deleted my settings and installed the latest version.
