### ISSUE TITLE
libreadline.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by azim-delphis** [dbeaver/dbeaver#10066]
#### System information: 
- Operating system (distribution) and version : Ubuntu 20.04.1 LTS
- DBeaver version : 7.2.2.202010041557

#### Connection specification:
- Database name and version : MySQL 8
- Driver name : MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
While trying to **Restore database** (import) new database .sql file (from production database) into my local database, I received this error:-
`/snap/dbeaver-ce/80/usr/bin/mysql: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory`

Same thing happen if I tried to use **Execute script** (Execute script with native client).

#### Steps to reproduce, if exist:
1) Right click on database, Go to **Tools**, then click **Restore database**.
2) **Database import** window shows up, input database .sql file.
3) Click **Start** button.
4) **Task error** window shows up with errors.

#### Include any warning/errors/backtraces from the logs

1) Error logs in **Database import** window:-
```
Task 'MySQL restore' started at Thu Oct 15 12:25:22 MYT 2020
/snap/dbeaver-ce/80/usr/bin/mysql: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory

Task 'MySQL restore' finished at Thu Oct 15 12:25:22 MYT 2020
2020-10-15 12:25:22.553 - IO error: Process failed (exit code = 127). See error log.
2020-10-15 12:25:22.554 - java.io.IOException: Process failed (exit code = 127). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:188)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
2) Error log (**Broken pipe**):-

a) Exception stack trace:-
```
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler$BinaryFileTransformerJob.run(AbstractNativeToolHandler.java:426)
```

b) Session data:-
```
eclipse.buildId=unknown
java.version=1.8.0_265
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

```

**Comment by Sean-Y-X** [comment]
have the same issue here.

**Comment by nickstock** [comment]
me too, been searching for this for hours.

**Comment by tmldoc** [comment]
been searching for this fix for days. Export\dump works fine, but can't restore it.
Using dbeaver Version 7.3.1.202012201616 on ubunuto 20.04.

**Comment by jon14four** [comment]
Still an issue with pop_OS and Version 21.1.0.202105300349

**Comment by devotoare** [comment]
Still an issue with pop_OS and Version 21.1.0.202105300349

**Comment by RuiGuilherme** [comment]
Have the same issue here... But I'm trying to run the bin's from within the docker (overlay2)


```bash
Task 'MySQL restore' started at Fri Oct 29 22:32:27 BRT 2021
/var/lib/docker/overlay2/8fcfa9857a5bewqeiwqou456969da0c17f8489ddasdasdas452950a14056798a7d8e6bf5241/merged/bin/mysql: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory

Task 'MySQL restore' finished at Fri Oct 29 22:32:27 BRT 2021
2021-10-29 22:32:28.058 - IO error: Process failed (exit code = 127). See error log.
2021-10-29 22:32:28.059 - java.io.IOException: Process failed (exit code = 127). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:230)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:210)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:270)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:76)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by skydiablo** [comment]
snap install also broken with same error...

**Comment by Matvey16** [comment]
This was the problem with snap confinement. The latest package 22.0.5 should have resolved the issue
