### ISSUE TITLE
Operations on Postgres array columns (like `text[]`) fail with error

### ISSUE THREAD

**Issue by mogzol** [dbeaver/dbeaver#10079]
#### System information: 
- OS Version: macOS 10.15.7
- DBeaver version: 7.2.1
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 11.9 (Debian 11.9-1.pgdg90+1)
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No 

#### Describe the problem you're observing:

Most operations on columns with a Postgres array type (such as `text[]`) fail with the error:

```
Error creating struct
  Unable to find server array type for provided name _text.
```

This happens when trying to edit such columns (the column editor also doesn't work properly, you can't edit the array values), and when trying to export such tables to another database (through the right-click -> export data wizard). I would assume it also happens with other operations, those are just the two places I've noticed it.

Note that the recent comments on issue #8845 seem to describe this same problem, however that issue is closed and I'm not sure the initial problem was the same as this.

#### Steps to reproduce, if exist:

1. create a table with a postgres array type:
```
CREATE TABLE test (
    str text,
    str_arr text[]
);
```

2. Open the data view for the table in DBeaver and create a new row. Enter whatever values you want (notice that the value editor for the array works properly here, you can add and modify the values without issue).
3. Save the changes. This works fine and creates the column.
4. Try to modify the row, notice now that the array editor for the column doesn't work properly, you can't edit the values of the array and the only thing you can insert is `[NULL]`
5. Try to save changes to the row, you will get the error mentioned above:
<img src="https://user-images.githubusercontent.com/11789801/96185917-823de880-0eef-11eb-8dc6-1e38e75631cf.png" width=500 />

You will also get the same error trying to export that table to another database table table through the "Export Data" right click menu

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-15 14:10:28.996
!MESSAGE Unable to find server array type for provided name _text.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-15 14:10:28.996
!MESSAGE Unable to find server array type for provided name _text.
!STACK 0
org.postgresql.util.PSQLException: Unable to find server array type for provided name _text.
	at org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1347)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createArrayOf(JDBCConnectionImpl.java:664)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.getArrayValue(JDBCCollection.java:174)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.bindParameter(JDBCArrayValueHandler.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:64)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:466)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:797)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:683)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:682)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:620)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by tkorach** [comment]
A workaround: create a primary key for the table. This solved the issue when updating the table.

**Comment by mogzol** [comment]
Adding a primary key does allow you to update other columns in the table, but the array column itself is still uneditable, and other operations like exporting the table to another DB still fail.

**Comment by tkorach** [comment]
@mogzol Can confirm: the array column is uneditable. Other columns are editable.

**Comment by uslss** [comment]
thanks for the report
It seems this issue duplicates #9965
