### ISSUE TITLE
Database Connection Error in Maridb after upgrade to 7.2.3 CE

### ISSUE THREAD

**Issue by prast1007** [dbeaver/dbeaver#10115]
![Screenshot from 2020-10-20 17-15-45](https://user-images.githubusercontent.com/11723160/96573152-f1547c00-12f7-11eb-9c53-33bdb810462d.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Include any warning/errors/backtraces from the logs

After upgrading from 7.2.2 CE to 7.2.3 I have difficulties to connect to all of my Mariadb Database Servers (they are mostly MariaDb 10.x), it seems connected to the databases, but everytime I want to browse the database contents (browse for tables, views, etc, it is always failed with following error messages :+1: SQL Error [1220] [08000]: (conn=284626) (conn=284626) Connection is closed
  (conn=284626) (conn=284626) Connection is closed
  (conn=284626) (conn=284626) Connection is closed
    (conn=284626) Connection is closed
    (conn=284626) Connection is closed

What should I do ? How to rollback to previous DBeaver version (7.2.2) ? 
 
I'm using the dbeaver on Linux Mint 19.1 and it is just happened after I upgrade dbeaver to the latest version (7.2.3)

**Comment by prast1007** [comment]
below is the error log 

!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-20 17:33:52.001
!MESSAGE (conn=8752614) Connection is closed
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-20 17:33:52.002
!MESSAGE (conn=8752614) Connection is closed
!STACK 0
java.sql.SQLNonTransientConnectionException: (conn=8752614) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:187)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1926)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initialize(MySQLDataSource.java:328)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.refreshObject(MySQLDataSource.java:355)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.refreshObject(DataSourceDescriptor.java:645)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:329)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:327)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:280)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:154)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by prast1007** [comment]
Maybe the problems was because when I upgraded DBeaver , there were also some system updates I run via Linux Mint Update Manager and it just eventually need me to restart the laptop, which I just did it this morning. After I restart my laptop, everything works fine.
