### ISSUE TITLE
Netezza JDBC error

### ISSUE THREAD

**Issue by tikala** [dbeaver/dbeaver#10247]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.1, 7.1.5, 7.2.3 and 7.2.4 ce (all this tried)
- Additional extensions

#### Connection specification:
- Database name and version: Netezza 7.2.1
- Driver name: JDBC from IBM
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: no

#### Describe the problem you're observing:
When testing connection, getting this error:

Unexpected driver error occurred while connecting to database
java.lang.NullPointerException

Driver and connection works fine from SQuirreL.

Same probleam as this: https://github.com/dbeaver/dbeaver/issues/5392

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2020-11-05 11:08:24.188
!MESSAGE 
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-11-05 11:08:24.188
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.netezza.sql.NzConnection$Initializer.handshake(NzConnection.java:2163)
	at org.netezza.sql.NzConnection$Initializer.init(NzConnection.java:2091)
	at org.netezza.sql.NzConnection.open(NzConnection.java:298)
	at org.netezza.datasource.NzDatasource.getConnection(NzDatasource.java:719)
	at org.netezza.datasource.NzDatasource.getConnection(NzDatasource.java:706)
	at org.netezza.Driver.connect(Driver.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:192)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:89)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:855)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

<img width="265" alt="event_details" src="https://user-images.githubusercontent.com/39048328/98239553-cd886b80-1f70-11eb-86b5-2013fed23df4.PNG">

**Comment by tikala** [comment]
Enterprise Edition's Netezza driver helped.
It works with that.
