### ISSUE TITLE
DB2 - Dbeaver unable to load table and other information

### ISSUE THREAD

**Issue by aekoise** [dbeaver/dbeaver#10260]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version -  Tested with 7.2.x,  7.1.x  running on jdk8 and jdk11
- Additional extensions -  None

#### Connection specification:
- Database name and version : DB2 z/OS, DB2 LUW (Old 8.x)
- Driver name - DB2 z/OS, DB2 LUW (Old 8.x) db2jcc.jar and db2jcc-4.19.26.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
I cannot access DB2 Tables, Views etc of a database instance, but I am able to test connection to the DB. 
**DB2 SQL Error: SQLCODE=-471, SQLSTATE=55023, SQLERRMC=SYSIBM.SQLTABLES;00E7900C, DRIVER=3.69.56**
Using IBM data studio I am not seeing the same error.

#### Steps to reproduce, if exist:
Create a connection to DB2 instance using DB2 z/OS or DB2 LUW (Old 8.x) profiles. I am able to test connection to the database. When I expand the Table view I am getting the following error 

DB2 SQL Error: SQLCODE=-471, SQLSTATE=55023, SQLERRMC=SYSIBM.SQLTABLES;00E7900C, DRIVER=3.69.56

Editor autocompletion is not working and it appears Dbeaver is unable to read DB2 schema information

#### Include any warning/errors/backtraces from the logs

com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-471, SQLSTATE=55023, SQLERRMC=SYSIBM.SQLTABLES;00E7900C, DRIVER=3.69.56
	at com.ibm.db2.jcc.am.gd.a(Unknown Source)
	at com.ibm.db2.jcc.am.gd.a(Unknown Source)
	at com.ibm.db2.jcc.am.gd.a(Unknown Source)
	at com.ibm.db2.jcc.am.yo.b(Unknown Source)
	at com.ibm.db2.jcc.am.yo.c(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.l(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.f(Unknown Source)
	at com.ibm.db2.jcc.t4.p.e(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.k(Unknown Source)
	at com.ibm.db2.jcc.am.yo.lb(Unknown Source)
	at com.ibm.db2.jcc.am.zo.b(Unknown Source)
	at com.ibm.db2.jcc.am.CallableStatement.hc(Unknown Source)
	at com.ibm.db2.jcc.am.CallableStatement.executeQuery(Unknown Source)
	at com.ibm.db2.jcc.am.DatabaseMetaData.executeCatalogQuery(Unknown Source)
	at com.ibm.db2.jcc.am.DatabaseMetaData.getTablesX(Unknown Source)
	at com.ibm.db2.jcc.am.DatabaseMetaData.getTables(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:507)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:68)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:127)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:111)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:358)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:871)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:852)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:914)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:538)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:428)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:205)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment]
Could you please open the connection (select **Edit connection** in the database context menu in DB Navigator or click and press F4), press **Test connection** button and send the screenshot what is written there?

**Comment by aekoise** [comment]
![image](https://user-images.githubusercontent.com/662401/99399888-444c2f80-28b4-11eb-9546-ca933b00ec6a.png)

**Comment by Sargul** [comment]
Hi,

issue here is on DB2 for zOS.

Meta data queries are executed by the jdbc driver using stored procedures on the DB2 for zOS.

It seems that the WLM address space is that is used to execute the procedures is either not defined or not usable.

Please forward this error code to your DBA or zos-system departement

[00e7900c](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/codes/src/tpc/00e7900c.html) on SYSIBM.SQLTABLES

**Comment by aekoise** [comment]
K.. Thanks! I will have a DBA look into it

**Comment by aekoise** [comment]
Issue resolved. You can mark as closed. Thanks again for the feedback.

**Comment by kseniiaguzeeva** [comment]
@Sargul Thanks for the help with the answer!
