### ISSUE TITLE
posgresql with login-dialog throws "Null value for 'password'" Exception.

### ISSUE THREAD

**Issue by marcmuel** [dbeaver/dbeaver#10319]
### System information: 
- Win10Pro Version 2004
- DBeaver version 7.2.4 and 7.2.5

#### Connection specification:
- Database PostgreSQL 12.4
- Driver postgresql-42.2.16.jar

#### Describe the problem you're observing:
We don't save the password locally in the connection settings for security reasons. So on connect a login dialog appears and we have to enter the password manually. But since the actual version 7.2.4 this results in an exception. But if the password is saved locally within the connection configuration all works very well.

#### Include any warning/errors/backtraces from the logs
-----------------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Fehler
Thu Nov 12 10:23:31 CET 2020
Null value for 'password'
---------------------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Fehler
Thu Nov 12 10:23:31 CET 2020
Null value for 'password'

java.lang.IllegalArgumentException: Null value for 'password'
	at org.postgresql.shaded.com.ongres.scram.common.util.Preconditions.checkNotNull(Preconditions.java:41)
	at org.postgresql.shaded.com.ongres.scram.common.util.Preconditions.checkNotEmpty(Preconditions.java:55)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ServerFirstProcessor.clientFinalProcessor(ScramSession.java:128)
	at org.postgresql.jre7.sasl.ScramAuthenticator.processServerFirstMessage(ScramAuthenticator.java:147)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:778)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)
------------------------------------------------------------------------------------------------------------

**Comment by serge-rider** [comment]
Fixed.

Workaround: it works after second attempt to enter password.

**Comment by d2a-sveurink** [comment]
Hi, 

To add to this issue: 
The password that you enter the first attempt seems to be used for the next attempt in version 7.2.4. It seems to be saved somewhere in the background. I just tested this by entering the correct password the first attempt and entering random input for password in the second attempt, and succeeded to connect to my db.

**Comment by andale82** [comment]
there is same problem with Oracle.

**Comment by uslss** [comment]
verified

**Comment by dstj** [comment]
Good to hear there's a fix coming. for the sake of completeness (and the search box), this is the error that I get, but it's the same issue I think.

```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-11-14 10:35:05.493
!MESSAGE The server requested password-based authentication, but no password was provided.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-11-14 10:35:05.493
!MESSAGE The server requested password-based authentication, but no password was provided.
!STACK 0
org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:192)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:341)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:205)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:131)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:90)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:78)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:112)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:877)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
