### ISSUE TITLE
[clickhouse] DBCException while execution simple query

### ISSUE THREAD

**Issue by NAlexandrov** [dbeaver/dbeaver#10334]
#### System information: 
- Operating system (distribution) and version: macOS Catalina 10.15.7
- DBeaver version: Версия 7.2.4.202011011603
- Additional extensions: No

#### Connection specification:
- Database name and version: ClickHouse version 20.9.4.76 (official build)
- Driver name: https://github.com/ClickHouse/clickhouse-jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc): No

#### Describe the problem you're observing:

```bash
org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from JDBC array
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:62)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:717)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:540)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3093)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4462)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:247)
	... 18 more
Caused by: java.sql.SQLFeatureNotSupportedException
	at ru.yandex.clickhouse.ClickHouseArray.getResultSet(ClickHouseArray.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromResultSet(JDBCCollection.java:363)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:245)
	... 18 more
```

#### Steps to reproduce:

```sq;
SELECT arrayZip(['a', 'b', 'c'], [5, 2, 1])
```

**Comment by serge-rider** [comment]
This looks like Clickhouse JDBC driver bug:
```
Caused by: java.sql.SQLFeatureNotSupportedException
	at ru.yandex.clickhouse.ClickHouseArray.getResultSet(ClickHouseArray.java:65)
```
What data type function `arrayZip` returns?

**Comment by NAlexandrov** [comment]
[arrayZip](https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/#arrayzip) combine multiple Array type columns into one Array[Tuple(…)] column

**Comment by NAlexandrov** [comment]
> This looks like Clickhouse JDBC driver bug

DataGrip use Clickhouse JDBC driver too and all is ok:

<img width="969" alt="Снимок экрана 2020-11-13 в 19 32 19" src="https://user-images.githubusercontent.com/157640/99072616-f3ec7d80-25e6-11eb-8398-f26cb4667576.png">

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.2
https://github.com/dbeaver/dbeaver/issues/14255

![2022-04-12 19_04_16-Window](https://user-images.githubusercontent.com/45152336/163005741-da0e89a2-3227-4fde-8f61-7be8d018ccb7.png)
