### ISSUE TITLE
Cell edit doesn't work for text values

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10349]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 7.2.5 EA

#### Steps to reproduce, if exist:
Open a table in data editor (e.g. MySQL sakila.language)
Select an numeric value and presscell edit or shift+enter > Cell editor opened
Try to open the cell editor for varchar value
Expected: cell editor opened
Actual result:
the editor is not displayed
error in log:
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.ByteBuffer.wrap(Unknown Source)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.redrawTextAreas(HexEditControl.java:1547)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.setContentProvider(HexEditControl.java:1814)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.setContent(HexEditControl.java:1835)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditControl.setContent(HexEditControl.java:1823)
	at org.jkiss.dbeaver.ui.editors.binary.HexEditorService.setHexContent(HexEditorService.java:63)
	at org.jkiss.dbeaver.ui.data.dialogs.TextViewDialog.setBinaryContent(TextViewDialog.java:225)
	at org.jkiss.dbeaver.ui.data.dialogs.TextViewDialog.primeEditorValue(TextViewDialog.java:309)
	at org.jkiss.dbeaver.ui.data.dialogs.TextViewDialog.createDialogArea(TextViewDialog.java:175)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:767)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.open(ValueViewDialog.java:234)
	at org.jkiss.dbeaver.ui.data.dialogs.ValueViewDialog.showValueEditor(ValueViewDialog.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.lambda$3(SpreadsheetPresentation.java:1122)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3793)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:235)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

**Comment by kseniiaguzeeva** [comment]
verified
