### ISSUE TITLE
Oracle view DDL incorrect for new created view

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#10420]
DBeaver 7.2.5

Error in view tab "Declaration" appears, when creating new view.
![2020-11-18 18_23_05-DBeaver Enterprise 7 3 0 - NEWVIEW_3](https://user-images.githubusercontent.com/45152336/99549945-3c32e380-29cb-11eb-88f7-a7a5c9cde56b.png)

java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleUtils.getDDL(OracleUtils.java:91)
	at org.jkiss.dbeaver.ext.oracle.model.OracleView.getObjectDefinitionText(OracleView.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:85)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.lambda$0(SQLEditorNested.java:273)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:271)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
also dummy select for new created Oracle view changed

**Comment by uslss** [comment]
verified
