### ISSUE TITLE
"Null statement" error while counting record count

### ISSUE THREAD

**Issue by alexvulpe** [dbeaver/dbeaver#10457]
#### System information: 
- Windows 10
- 7.2.5.202011152110

#### Connection specification:
- Custom JDBC driver

#### Describe the problem you're observing:
Getting "Null statement" error when clicking "Calculate total row count" button

#### Steps to reproduce, if exist:
Run any select, ex. SELECT * FROM F_ACCOUNT
200 records are returned
Click "Calculate total row count" button

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sat Nov 21 11:55:22 EET 2020
Null statement

java.lang.IllegalArgumentException: Null statement
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createPreparedStatementImpl(JDBCConnectionImpl.java:719)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:405)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1374)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1321)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3137)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3564)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3559)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3552)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1668)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Can't reproduce in Oracle, PostgreSQL, SQLite and MySQL in SQLEditor.
Need more information.
What database you use? Connection type?
May be, you can make video?

**Comment by alexvulpe** [comment]
I have developed a custom JDBC driver of Temenos T24 banking system. And because my source code is not a part of callstack, I was is wondering what is requested (and apparently missing) in line JDBCConnectionImpl.java:719, which causes "Null statement".

**Comment by LonwoLonwo** [comment]
Usually, it's just SELECT COUNT(*) FROM tableName

![2020-11-23 13_00_05-Window](https://user-images.githubusercontent.com/45152336/99949481-2a1ac180-2d8c-11eb-99d5-e2c640b87349.png)

![2020-11-23 13_02_01-](https://user-images.githubusercontent.com/45152336/99949484-2ab35800-2d8c-11eb-9e51-5354a373f5a3.png)

Can you take a look at your Query Manager?

**Comment by alexvulpe** [comment]
No extra calls in Query Manager after clicking "Calculate total row count"

![image](https://user-images.githubusercontent.com/10166357/100005090-1a719c00-2dd1-11eb-82e2-3f2cfbdf84f6.png)

![image](https://user-images.githubusercontent.com/10166357/100005123-24939a80-2dd1-11eb-8b8b-6ea8ff7e6148.png)

**Comment by alexvulpe** [comment]
Is it possible to let me know what is missing in line JDBCConnectionImpl.java:719?
Perhaps my initial SELECT did not provide all requested data, so I can fix by jdbc driver.

**Comment by LonwoLonwo** [comment]
Oh, I'm afraid it's not that easy, unfortunately. The conversion of the counting expression occurs first in this method. Perhaps this will help you.
https://github.com/dbeaver/dbeaver/blob/9156d4617dca0ad17d3e5e789d93586b711f0e3c/plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java#L3123
