### ISSUE TITLE
TLS 1.2 not supported?

### ISSUE THREAD

**Issue by mjgio** [dbeaver/dbeaver#10504]
We made some changes which required us to use TLS 1.2 when connecting to our mysql dB. Using dBeaver 7.2.5 I can't seem to connect afterward, getting an error saying: "TLS version used does not meet minimal requirements for this server". Worked like a charm in Workbench and could not seem to find an solution on how to make it work with dBeaver.

Is there some option I'm missing or isn't TLS 1.2 supported yet?

![bild](https://user-images.githubusercontent.com/38317745/100338589-12844880-2fd9-11eb-8391-3b80986d2b78.png)

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files. 
What OS do you use?
What do you need TLS for?

**Comment by WheelsForReals** [comment]
I was having the same issue but have figured out a workaround. I had to modify the ``enabledTLSProtocols`` property in the driver properties (it was blank before):
![image](https://user-images.githubusercontent.com/6102222/103913222-f2fb3800-50cd-11eb-8fbb-61db86b8019e.png)

There are some more details about this property here that might explain what's going on: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html

OS: Windows 10
DBeaver version: 7.3.2
MySQL driver: mysql:mysql-connector-java:RELEASE [8.0.17]
MySQL version: 8.0.15 (hosted in Azure with the TLS option enabled, making it required for connecting)

dbeaver-debug.log from when it was broken:
```
2021-01-07 15:28:03.243 - Create display
2021-01-07 15:28:03.370 - DBeaver 7.3.2.202101032114 is starting
2021-01-07 15:28:03.371 - OS: Windows 10 10.0 (amd64)
2021-01-07 15:28:03.371 - Java version: 11.0.5 by AdoptOpenJDK (64bit)
2021-01-07 15:28:03.372 - Install path: 'C:\Users\bhohler\Downloads\dbeaver'
2021-01-07 15:28:03.372 - Instance path: 'file:/C:/Users/bhohler/AppData/Roaming/DBeaverData/workspace6/'
2021-01-07 15:28:03.372 - Memory available 254Mb/4056Mb
2021-01-07 15:28:03.385 - Starting RMI server at 44296
2021-01-07 15:28:03.469 - Run workbench
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.900.v20201102-2031]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.15.0.v20201103-0952]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.500.v20200928-2213]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.4.0.v20201014-0944]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.21.0.v20200917-1439]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.900.v20201021-1339]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.0.v20201119-1132]
> Start Expression Language [org.eclipse.core.expressions 3.7.0.v20200720-1126]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.0.v20201103-0952]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.63.202101032114]
2021-01-07 15:28:05.035 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-01-07 15:28:05.537 - Create actions
2021-01-07 15:28:05.539 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-01-07 15:28:05.542 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-01-07 15:28:07.887 - Initialize workbench window
2021-01-07 15:28:07.894 - Finish initialization
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.5.0.v20201012-1421]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.5.100.v20200908-1020]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.38.202101032114]
> Start DBeaver Firebird Support [org.jkiss.dbeaver.ext.firebird 1.0.149.202101032114]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.133.202101032114]
> Start DBeaver Oracle Support [org.jkiss.dbeaver.ext.oracle 2.1.133.202101032114]
> Start DBeaver PostgreSQL Support [org.jkiss.dbeaver.ext.postgresql 2.1.121.202101032114]
> Start DBeaver SQLite Support [org.jkiss.dbeaver.ext.sqlite 1.0.97.202101032114]
2021-01-07 15:28:10.011 - Loading user drivers configuration from 'C:\Users\bhohler\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2021-01-07 15:28:10.022 - Total database drivers: 86 (86)
> Start Default Text Editor [org.eclipse.ui.editors 3.13.400.v20200923-1238]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.15.100.v20201116-1727]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.48.202101032114]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.48.202101032114]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.48.202101032114]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.85.202101032114]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.54.202101032114]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.8.202101032114]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.8.202101032114]
> Start DBeaver SQL Server Support [org.jkiss.dbeaver.ext.mssql 1.0.142.202101032114]
2021-01-07 15:28:12.726 - Open [https://dbeaver.io/product/version.xml]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.700.v20200511-1530]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.0.v20201013-0853]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.6.100.v20200731-1005]
2021-01-07 15:28:47.409 - Connect with 'DM (Dev)' (mysql8-176d38a3da6-6d52a7eb705d40f3)
2021-01-07 15:28:47.436 - Execution context opened (DM (Dev); Main; 0)
2021-01-07 15:28:48.430 - Connection failed (mysql8-176d38a3da6-6d52a7eb705d40f3)
2021-01-07 15:28:48.431 - org.jkiss.dbeaver.model.exec.DBCConnectException: TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.
org.jkiss.dbeaver.model.exec.DBCConnectException: TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:222)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:419)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:90)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:90)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:880)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:65)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:203)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: TLS version used does not meet minimal requirements for this server. Please use a higher TLS version and retry.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:196)
	... 24 more
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the workaround. We will add the setting to SSL tab of MySQL connection settings.

**Comment by mjgio** [comment]
Works now with the workaround from @bhohler. Many thx

**Comment by Matvey16** [comment]
Verified
