### ISSUE TITLE
REFCURSOR - DBCException: Attribute index out of range (0/0) 

### ISSUE THREAD

**Issue by jscantamburlo** [dbeaver/dbeaver#10564]
#### System information: 
- Operating system (distribution) and version:  Ubuntu 18.04
- DBeaver version: 7.3.0
- No additional extensions

#### Connection specification:
- Database name and version: Oracle 12.1.0.2
- Driver name: ojdbc8
- Ni tunnels nor proxies

#### Problem description

I'm gettting the following error after upgrade to 7.3.0.  When I execute an Oracle SP with a REFCURSOR parameter I get "DBCException: Attribute index out of range (0/0)".

#### Standard Output

2020-11-30 19:06:51.151 - Error binding callable statement parameters from metadata: Unsupported feature: checkValidIndex
2020-11-30 19:06:51.223 - Can't read column 'P_CURSOR' value
org.jkiss.dbeaver.model.exec.DBCException: Attribute index out of range (0/0)
	at org.jkiss.dbeaver.model.impl.local.LocalResultSet.getAttributeValue(LocalResultSet.java:47)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:718)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3101)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4466)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

#### Versions

I've tested on following releases:
7.3.0:  Issue described above.
7.2.5:  Same result.
7.1.0:  No issue. I can retrieve the resultset and show its content with shift+enter.

Thanks.

**Comment by kseniiaguzeeva** [comment]
Is it possible to give a query example?

**Comment by Boksh** [comment]
Same error on 7.3.4 version. I try `call myProcedure(1,2,3,?);` Where ? is OUT REFCURSOR parameter.

**Comment by kseniiaguzeeva** [comment]
Could you give a full script to reproduce?

**Comment by Boksh** [comment]
```
CREATE OR REPLACE PROCEDURE myProcedure(a IN NUMBER, b IN NUMBER, c IN NUMBER, oRefCursor OUT SYS_REFCURSOR) AS
BEGIN
    OPEN oRefCursor
      FOR SELECT a FROM dual UNION ALL SELECT b FROM dual UNION ALL SELECT C FROM dual;
END myProcedure;

-- this throw error 'DBCException: Attribute index out of range (0/0)' in OREFCURSOR Cell on Result Tab
CALL myProcedure(1, 2, 3, ?);

-- output 1,2,3 values
DECLARE
  v_cur SYS_REFCURSOR;
  v_a   NUMBER;
BEGIN
  myProcedure(1, 2, 3, v_cur);
  LOOP
    FETCH v_cur INTO v_a;
    EXIT WHEN v_cur%NOTFOUND;
    dbms_output.put_line(v_a);
  END LOOP;
  CLOSE v_cur;
END;
```

**Comment by serge-rider** [comment]
Oracle ref cursors support fixed

**Comment by kseniiaguzeeva** [comment]
verified
