### ISSUE TITLE
sec_to_time shows incorrect value

### ISSUE THREAD

**Issue by davesabourfc** [dbeaver/dbeaver#10575]
**System information:**

- Operating system: Windows 10
- DBeaver version: 7.2.4
- Additional extensions

**Connection specification:**

- Database: MySQL
- Driver name: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no
- Describe the problem you're observing:
running the query SELECT sec_to_time(127122) as time; shows wrong value (returns NULL should be 35:18:42)

Connecting directly through terminal shows correct value

Updating preferences to use native date/time does not resolve (as suggested here: https://github.com/dbeaver/dbeaver/issues/8648)

**Comment by LonwoLonwo** [comment]
@davesabourfc Thanks for the bug report

It works for MariaDB fine, but doesn't work with MySQL (5.5 version tested)

2020-12-02 14:01:02.173 - Can't read date/time value as string: Illegal hour value '35' for java.sql.Time type in value '35:18:42.
2020-12-02 14:01:02.177 - Can't retrieve datetime object
java.sql.SQLException: Illegal hour value '35' for java.sql.Time type in value '35:18:42.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.TimeUtil.fastTimeCreate(TimeUtil.java:288)
	at com.mysql.jdbc.ResultSetImpl.fastTimeCreate(ResultSetImpl.java:970)
	at com.mysql.jdbc.ResultSetImpl.getTimeFromString(ResultSetImpl.java:5515)
	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5274)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5127)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getString(JDBCResultSetImpl.java:334)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:129)
	at org.jkiss.dbeaver.ext.mysql.data.MySQLDateTimeValueHandler.fetchValueObject(MySQLDateTimeValueHandler.java:70)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:718)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3101)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4472)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
Hello @davesabourfc,

Unfortunately we can't do much here because the problem hides inside MySQL 5 driver.

As a workaround I can suggest:
* Try upgrading to newer driver (MySQL 8+) if there's no backward compatibility issues
* Use explicit conversion into `timestamp`: `SELECT timestamp(sec_to_time(127122)) as time;`

I hope these solutions will help.
