### ISSUE TITLE
Execution plan fails with an error if a condition is used in a query

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10611]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.0 EA
- Additional extensions

#### Connection specification:
- Database name and version SQL Server

#### Steps to reproduce, if exist:
1. Open SQL Editor and run a query with a filter (e.g. select * from _database.schema.table_ where _column_ >1)
2. Press Execution plan button

Expected: execution plan appears:
Actual result: 
![eimEunnEUL](https://user-images.githubusercontent.com/51405061/101166132-d724f200-3648-11eb-9d7f-5590d9099241.gif)

1. no content in execution plan window
2. error appears
org.jkiss.dbeaver.model.exec.DBCException: Unable to find plan
	at com.dbeaver.db.mssql.model.plan.SQLServerPlanParser.parse(SQLServerPlanParser.java:304)
	at com.dbeaver.db.mssql.model.plan.SQLServerExecutionPlan.explain(SQLServerExecutionPlan.java:88)
	at com.dbeaver.db.mssql.model.plan.SQLServerQueryPlanner.planQueryExecution(SQLServerQueryPlanner.java:60)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:401)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
P.S. the plan is opened for simple select (select * from _database.schema.table)

**Comment by LonwoLonwo** [comment]
Fixed

**Comment by Matvey16** [comment]
Verified
