### ISSUE TITLE
Progress sub task without start

### ISSUE THREAD

**Issue by jgrocha** [dbeaver/dbeaver#10632]
#### System information: 
- Ubuntu 20.04
- DBeaver Version 7.3.0.202012062025

#### Connection specification:
- Postgresql 13
- org.postgresql:postgresql:RELEASE[42.2.5]
- Local Client: `/usr/bin`

#### Describe the problem you're observing:

Restore operations are working.

![Captura de ecrã de 2020-12-08 14-25-05](https://user-images.githubusercontent.com/163681/101496129-49574880-3961-11eb-93c7-82f72463f569.png)

But at the end an exception is raised: **Progress sub task without start**

As far as I know, this started to happen after upgrading to 7.3.0, but I'm not sure.

The restore command issued was:

```
/usr/bin/pg_restore --verbose --host=pg.geomaster.pt --port=5432 --username=postgres --no-owner --format=c --dbname=homologacao_teste
```

#### Steps to reproduce, if exist:

Contect menu → Tools → Restore...

#### Include any warning/errors/backtraces from the logs

```java
Task 'PostgreSQL restore' finished at Tue Dec 08 13:26:35 WET 2020
2020-12-08 13:26:35.725 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.startBlock(DefaultProgressMonitor.java:127)
	at org.jkiss.dbeaver.model.impl.AbstractSession.<init>(AbstractSession.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.<init>(JDBCConnectionImpl.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createConnection(JDBCDataSource.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:209)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.readDatabaseInfo(PostgreDatabase.java:167)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.refreshObject(PostgreDatabase.java:658)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:331)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:259)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-12-08 13:26:35.787 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.startBlock(DefaultProgressMonitor.java:127)
	at org.jkiss.dbeaver.model.impl.AbstractSession.<init>(AbstractSession.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.<init>(JDBCConnectionImpl.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createConnection(JDBCDataSource.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:209)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:1)
	at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1684)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:104)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getSchemas(PostgreDatabase.java:556)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:583)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.refreshObject(PostgreDatabase.java:672)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:331)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:259)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-12-08 13:26:35.788 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getSchemas(PostgreDatabase.java:556)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:583)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.refreshObject(PostgreDatabase.java:672)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:331)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:259)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-12-08 13:26:35.842 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.startBlock(DefaultProgressMonitor.java:127)
	at org.jkiss.dbeaver.model.impl.AbstractSession.<init>(AbstractSession.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.<init>(JDBCConnectionImpl.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createConnection(JDBCDataSource.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:209)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:1)
	at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1684)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:104)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getDataTypes(PostgreSchema.java:459)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:585)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.refreshObject(PostgreDatabase.java:672)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:331)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:259)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-12-08 13:26:35.843 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getDataTypes(PostgreSchema.java:459)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:585)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.refreshObject(PostgreDatabase.java:672)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:331)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:259)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
thanks for the report

**Comment by leolird** [comment]
i meet the same issue,  when i use pgadmin4 to restore the same backup file, it's works fine, but in dbeaver it's throw the exception as above

**Comment by amatosg** [comment]
also present in the mac version using postgres 12

**Comment by serge-rider** [comment]
These exception are just warnings, they don't affect restore itself.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
