### ISSUE TITLE
Table cannot be created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#10726]
#### System information: 
- Operating system (distribution) and version win10 
- DBeaver version 7.3.1

#### Connection specification:
- Database name and version clickhouse
#### Describe the problem you're observing:
Table creation couldn't be performed via UI. Also, it is blocking table import from CSV and DB to the new table.
```java
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\37529\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2020-12-17 14:51:16.794

org.jkiss.dbeaver.model
Error
Fri Dec 18 14:34:43 MSK 2020
ClickHouse exception, code: 62, host: 127.0.0.1, port: 55878; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 173 (line 7, col 5): value Float32 CODEC(Delta, ZSTD)
). Expected one of: token, ClosingRoundBracket, Comma, e.what() = DB::Exception


ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 62, host: 127.0.0.1, port: 55878; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 173 (line 7, col 5): value Float32 CODEC(Delta, ZSTD)
). Expected one of: token, ClosingRoundBracket, Comma, e.what() = DB::Exception

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:226)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4512)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.Throwable: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 173 (line 7, col 5): value Float32 CODEC(Delta, ZSTD)
). Expected one of: token, ClosingRoundBracket, Comma, e.what() = DB::Exception

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 22 more

```
Seems it is connected to an incorrect query generated by dbeaver
https://clickhouse.tech/docs/ru/sql-reference/statements/create/table/

**Comment by uslss** [comment]
#10699 
#10718

**Comment by iambudi** [comment]
I don't see the UI to create database and table from popup menu on Big Sur.
![image](https://user-images.githubusercontent.com/31809529/104883065-b3b6cc00-5996-11eb-9f73-61a39686aef9.png)

Should i create separate issue or can be put here?

Thanks.

**Comment by LonwoLonwo** [comment]
I've added default as default Engine on the end of statement - https://clickhouse.tech/docs/en/engines/table-engines/log-family/log/
Because it is understandable and does not require columns as parameters.

**Comment by uslss** [comment]
verified
