### ISSUE TITLE
Update Job Exception on startup

### ISSUE THREAD

**Issue by cygnim** [dbeaver/dbeaver#10768]
#### System information: 
- Operating system (distribution) and version: **Windows 10 Pro x64 Build 19042.685**
- DBeaver version **7.3.1.202012201616**
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **no**

#### Describe the problem you're observing:
After this most recent update, every time I start DBeaver after a few seconds I get the following error alert dialog.
![image](https://user-images.githubusercontent.com/57690369/102957792-a2ae9400-4498-11eb-9328-7b927ba54f28.png)
I can close the dialog and everything works fine so this is just a minor annoyance. I'm guessing this is the check for newer versions of dbeaver that is failing? At any rate, I've been using DBeaver for well over a year with regular updates and have never encountered this problem before. It seems to have been introduced with this version.  I have tried reinstalling the software but the problem does not go away.

#### Steps to reproduce, if exist:
This happens every time I start the application. If I close the application and restart it, the error will always appear a few seconds after dbeaver launches. Dismissing the dialog seems to allow for normal operation afterward so it's just a minor annoyance.

#### Include any warning/errors/backtraces from the logs
This is being logged as an error in the application as follows:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.core.jobs
Error
Tue Dec 22 20:57:30 MST 2020
An internal error occurred during: "Update Job".

java.lang.IllegalStateException: Registry Directory not available: C:\Users\John Doe\.eclipse\org.jkiss.dbeaver.product_7.3.0_1535670467_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry.
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.restore(SimpleProfileRegistry.java:523)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfileMap(SimpleProfileRegistry.java:378)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.internalGetProfile(SimpleProfileRegistry.java:261)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfile(SimpleProfileRegistry.java:190)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.performMigration(MigrationSupport.java:72)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.lambda$0(AutomaticUpdateScheduler.java:68)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kseniiaguzeeva** [comment]
Please send also log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by cygnim** [comment]
I have provided relevent logging information in my original ticket. I'm not sure what other useful log data you want. The remainder of the log is full of query errors unrelated to this problem. The version I am running was downloaded and installed from this link: https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe.

**Comment by uslss** [comment]
@cygnim can you try to reset workspace using main menu: File - Reset workspace state or [this guide](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

**Comment by RiadySantoso82** [comment]
> @cygnim can you try to reset workspace using main menu: File - Reset workspace state or [this guide](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

i have same issue. and this also doesn't fix it.

**Comment by UlrichDemlehner** [comment]
Same problem here with dBeaver v7.3.2 at first start after update. The problem has appeared for the first time at the very first start of dBeaver after updating to v7.3.1. I have never seen it before v7.3.1.

**Comment by serge-rider** [comment]
It seems to be a bug in Eclipse P2 update system. We have upgraded Eclipse platform in dbeaver 7.3.1 so this must be it.

Workaround is to delete directory `.eclipse` in your user home (%HOMEPATH%).

**Comment by UlrichDemlehner** [comment]
That was it indeed -- thx

**Comment by cygnim** [comment]
Confirmed. Deleting the .eclipse directory fixes the issue. I assume this issue will be corrected in a future version now that the problem has been identified.

**Comment by nilton-medeiros** [comment]
In version 7.3.3 it is the same problem, not only when you open the help / update menu, but also when changing the language in Windows Menu / Preferences / General User Interface / Language.
I solved this "Access Denied" issue by changing the permissions on the dbeaver folder:
# cd /usr/share
# sudo chmod -R 777 dbeaver

**Comment by cygnim** [comment]
Re-opening because I encountered this problem again after upgrading to 7.3.3. Deleting the .Eclipse folder once again fixes the issue, but I hope this can be fixed once and for all. Fixing after every upgrade is doable, but not a great user experience.

**Comment by luizwhite** [comment]
Everytime I update dbeaver i have to delete the folder to remove the error..

**Comment by izno33** [comment]
I had the same issue on Windows. It seems related to the path to user data containing certain characters (non-ASCII, space...).
In my case, it was a "`é`" that got transated into "`%C3%A9`".
As a workaround, I created a symlink to my user folder using the "expected" name (`C:\Users\xxx%C3%A9` => `C:\Users\xxxé`). It seems to do the trick with last version (21.0.2).

**Comment by UlrichDemlehner** [comment]
> I had the same issue on Windows. It seems related to the path to user data containing certain characters (non-ASCII, space...).
> In my case, it was a "`é`" that got transated into "`%C3%A9`".
> As a workaround, I created a symlink to my user folder using the "expected" name (`C:\Users\xxx%C3%A9` => `C:\Users\xxxé`). It seems to do the trick with last version (21.0.2).

I guess it would help if you give more details for your workaround e.g. in which directory specifically did you create the symlink? I have a lot of directories where I could create it ...

**Comment by cygnim** [comment]
This would definitely explain the problem as my username has a space in it. Hopefully this will be fixed as these characters are valid.

**Comment by digitaldutch** [comment]
Same here. After every upgrade I have to delete .eclipse. I too have a name with a space in it which is replaced with %20 and the message:

Registry Directory not available: C:\Users\Jan%20Derk\.eclipse\org.jkiss.dbeaver.product_21.0.1_1535670467_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry.

And yes indeed the directory "C:\Users\Jan%20Derk" does not exist. It must be "C:\Users\Jan Derk".

Looks like the path is url encoded when it should not.

**Comment by Jonathan-Martin1** [comment]
I get this message every time I open DBeaver. I'm on windows 10.

An internal error occurred during: "Update Job".
Registry Directory not available: C:\Users\Jonathan%20Martin\.eclipse\org.jkiss.dbeaver.product_21.0.1_1535670467_win32_win32_x86_64\p2\org.eclipse.equinox.p2.engine\profileRegistry.

**Comment by serge-rider** [comment]
I've excluded p2 scheduler/update checker plugins. We don't need them in DBeaver standalone.

Error "Registry Directory not available" was produced by P2 scheduler plugin.

**Comment by cygnim** [comment]
Cool. I will check if this resolves the issue in the next release.

**Comment by uslss** [comment]
verified
