### ISSUE TITLE
MYSQL 8 Edit Errors on columns of defined default functions

### ISSUE THREAD

**Issue by hamlet-main** [dbeaver/dbeaver#10797]
#### System information: 
OS: OS Name	Microsoft Windows 10 Pro (Version	10.0.19042 Build 19042)
DBeaver version: 7.3.1.202012201616

#### Connection specification:
MySQL DB Version: 8.0.21
Driver Name: MySQL (Driver for MySQL 8 and later)
No tunnels or proxies

#### Describe the problem you're observing:
The issue is described exactly here in this closed ticket: https://github.com/dbeaver/dbeaver/issues/7850 
Simply put, when an item which contains a function default value (such as CURRENT_TIMESTAMP for DATETIME data types), will automatically fill the "Extra" value for that column to be DEFAULT_GENERATED (as is expected for MySQL 8+). However, any subsequent edits made on this column, such as creating comment or adjusting the default value, will result in a syntax error. 

I am not sure yet if this is simply a MySQL bug or Dbeaver bug. 

#### Steps to reproduce, if exist:

Create new table, create datetime(6) column with Default value as CURRENT_TIMESTAMP(6).
Everything works great. 
Now, try editing this column by adding a comment. Attempt to persist these changes, will result in a 1064 error as seen below:

<img width="887" alt="query" src="https://user-images.githubusercontent.com/10842619/103125698-eb617b00-4659-11eb-8a37-f250eecb3a84.png">
<img width="895" alt="query_result" src="https://user-images.githubusercontent.com/10842619/103125699-ebfa1180-4659-11eb-8944-9fbdf710c191.png">

Query:

ALTER TABLE estate.`user` MODIFY COLUMN date_created datetime(6) DEFAULT CURRENT_TIMESTAMP(6) DEFAULT_GENERATED NULL COMMENT 'Test';

Error Log: 

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED NULL COMMENT 'Test'' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:311)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:40)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:186)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:116)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:343)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:341)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:316)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.4
DEFAULT_GENERATED is removed from alter statements.

**Comment by uslss** [comment]
verified
