### ISSUE TITLE
Error with mysql while Dumping or Restoring DB on Pop_OS 20.10 with Flatpak

### ISSUE THREAD

**Issue by seth100** [dbeaver/dbeaver#10845]
#### System information: 
- Operating system (distribution) and version: `Pop_OS 20.10`
- DBeaver version: **Flatpak** `Version 7.3.1.202012201616`
- Additional extensions: `io.dbeaver.DBeaverCommunity.Client.mariadb` and `io.dbeaver.DBeaverCommunity.Client.pgsql`

#### Connection specification:
- Database name and version: `MySQL 5.7`
- Driver name: `com.mysql.jdbc.Driver 5.1.49`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:

I'm not able to both dump or restore a DB on a local MySQL Docker instance connected on `127.0.0.1:3310`.

#### Steps to reproduce, if exist:

I select a database and then try to run either `Tools` -> `Dump database` or `Restore database` (more important for me) and I get an error (see below).

I tried by setting one of the following path for the `Local Client` in the connection configuration:

1. `/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin` (or `/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/c787e1de2bf4.../files/bin`)
2. `/run/user/1000/doc/5553e05/usr` (generated from `/usr` on my host system)
3. `/run/user/1000/doc/bdc7b70f/bin` (generated from `/bin` on my host system)

DBeaver was installed via:

```sh
flatpak install -y --user flathub io.dbeaver.DBeaverCommunity && \
	flatpak install -y --user flathub io.dbeaver.DBeaverCommunity.Client.mariadb && \
	flatpak install -y --user flathub io.dbeaver.DBeaverCommunity.Client.pgsql
```

but I tried also without `--user`, even if it should be the same!

#### Include any warning/errors/backtraces from the logs

When using local client on path 1. I get:

```
2021-01-01 12:08:20.143 - IO error: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
2021-01-01 12:08:20.143 - java.io.IOException: Utility 'mysql' not found in client home '/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin' (/home/MYHOME/.local/share/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.mariadb/x86_64/stable/active/files/bin)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:121)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:55)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.fillProcessParameters(MySQLScriptExecuteHandler.java:1)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.getCommandLine(MySQLNativeToolHandler.java:73)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:42)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLScriptExecuteHandler.getCommandLine(MySQLScriptExecuteHandler.java:1)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:165)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

When using local client on path 2. or 3. I get:

```
/run/user/1000/doc/5553e05/usr/bin/mysql -u root --host=127.0.0.1 --port=3310 MY_DB
Task 'MySQL restore' started at Fri Jan 01 12:10:15 CET 2021
/run/user/1000/doc/5553e05/usr/bin/mysql: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory

Task 'MySQL restore' finished at Fri Jan 01 12:10:15 CET 2021
2021-01-01 12:10:15.249 - IO error: Process failed (exit code = 127). See error log.
2021-01-01 12:10:15.249 - java.io.IOException: Process failed (exit code = 127). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:188)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by j0eii** [comment]
try this

https://github.com/dbeaver/dbeaver/issues/5008

**Comment by altsalt** [comment]
Just ran into this issue and the advice from the linked issue did resolve it. Basically, the problem is a mission filesystem permission request. The suggestion there is to install Flatseal and add the filepath. However, I suspect this can be added to the flatpak itself.

**Comment by Matvey16** [comment]
Still reproducible

![VirtualBoxVM_rSvPoUTmar](https://user-images.githubusercontent.com/82543000/164309539-3df8ed5f-c8d0-42ac-8aa7-7a720f9bac2e.png)
![VirtualBoxVM_VD2EYjRP63](https://user-images.githubusercontent.com/82543000/164309563-f69a8d0a-65bf-4459-b7e3-3fb37777ca5a.png)

**Comment by riednyko** [comment]
Hi @seth100. Sorry for the long answer. 
Did this https://github.com/dbeaver/dbeaver/issues/5008#issuecomment-754070017 solution help you?

**Comment by E1izabeth** [comment]
Does it still reproducible in the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
