### ISSUE TITLE
DBeaver hangs on "Collect database statistics: Read relation statistics" from Azure Postgres

### ISSUE THREAD

**Issue by Marshall-Davey** [dbeaver/dbeaver#10880]
#### System information: 
- Windows 10 Pro
- DBeaver version 7.3.0 (also tested on 7.2.1)
- Extensions: PostGIS 2.5.0

#### Connection specification:
- Database name : Azure Database for PostgreSQL server
- Database version: PostgreSQL version 11
- Driver name: PostgreSQL  - postgresql-42.2.18.jar, checker-qual-3.5.0.jar
- Driver name: postgis-jdbc-2.2.1.jar
- Driver name: postgis-geometry-2.5.0.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  - No

#### Describe the problem you're observing:
The most technical and direct way i can report the issue is the description directly below, but more supporting evidence is provided below that may hint to where this is breaking down.

Description: DBeaver hangs on "Collect database statistics: Read relation statistics" when attempting to view a table by double clicking it in the table tree. The progress percentage stays at 0% while the green progress bar cycles. 

![hang1](https://user-images.githubusercontent.com/32579986/103682782-5151da80-4f57-11eb-934f-61f24f1606cf.PNG)

If I instead use SELECT * from schema.table a few additional messages are generated which also hang at 0%
Other background tasks messages that hang are: Refresh Objects, Load Database Info, Load TableCache, Load Child Objects
![hang on select star](https://user-images.githubusercontent.com/32579986/103682906-7c3c2e80-4f57-11eb-9698-5093f1c456ce.PNG)

This happens on a table with 1 row, and other tables with thousands of rows. 

Attempting to cancel the task with the red STOP button in the background tasks pane generates a "Operation Cancel has encountered a problem. Cancel Error" error message.

If I leave it running, it will return the data after a very long time (10-15minutes) YET the bottom of the data pane will report that the data was fetched within a reasonable time frame on the range of milliseconds to a few seconds depending on the size.

This is only happening with my connections to Azure Database for PostgreSQL server. The very same Dbeaver (7.3.0) installation is having no trouble at all with a separate, local instance of postgres. 
 This exact scenario is also playing out on a completely separate windows system that is running DBeaver 7.2.1 ( hangs fetching from Azure but has zero issues with the local postgres)

This issue began one day, seemingly out of the blue, nothing changed on the client side or the server side. 

FURTHER HINTS:
- the table size statistics that normally load to the right of the table names in the tree do not populate until after the very long load time. but double clicking to view new tables still results in long load times even if their size stats have been populated. 
![tablestats wont load](https://user-images.githubusercontent.com/32579986/103682930-852d0000-4f57-11eb-9f5e-a0a105d287b8.PNG)

- Connection tests succeed, schema names load, table names load - data doesn't load.

THINGS I HAVE TRIED:
Rolling back DBeaver version up to two steps - no change
Rolling back JDBC driver up to two versions - no change

Thank you
#### Steps to reproduce, if exist:
1) successfully remotely connect to a Azure Database for PostgreSQL server via Dbeaver and attempt to load a table

#### Include any warning/errors/backtraces from the logs
!SESSION 2021-01-05 09:26:04.761 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2021-01-05 10:45:20.430
!MESSAGE Error reading schema relation statistics
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-01-05 10:45:20.430
!MESSAGE An I/O error occurred while sending to the backend.
!STACK 0
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:350)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.collectObjectStatistics(PostgreSchema.java:594)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer$StatReadJob.run(StatisticsNavigatorNodeRenderer.java:477)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.net.ssl.SSLException: Socket closed
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:441)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2057)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	... 9 more
Caused by: java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	... 17 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-01-05 10:45:20.430
!MESSAGE Socket closed
!STACK 0
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:441)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2057)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.collectObjectStatistics(PostgreSchema.java:594)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer$StatReadJob.run(StatisticsNavigatorNodeRenderer.java:477)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-01-05 10:56:37.482
!MESSAGE Error reading schema relation statistics
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-01-05 10:56:37.482
!MESSAGE An I/O error occurred while sending to the backend.
!STACK 0
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:350)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.collectObjectStatistics(PostgreSchema.java:594)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer$StatReadJob.run(StatisticsNavigatorNodeRenderer.java:477)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:223)
	at org.postgresql.core.PGStream.receive(PGStream.java:600)
	at org.postgresql.core.PGStream.receiveTupleV3(PGStream.java:560)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2252)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	... 9 more
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
		at java.base/java.net.SocketOutputStream.write(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source)
		... 22 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	... 18 more

**Comment by kseniiaguzeeva** [comment]
Please try to disable show statistics info (select **Connection view** in the database context menu in DB Navigator). It should help.
![dbeaver_SYnyZ7EB5H](https://user-images.githubusercontent.com/51405061/104454752-61049b00-55b7-11eb-8a87-74beb6f6eb25.png)

**Comment by Marshall-Davey** [comment]
Your suggestion worked!  Thank you very much. The tables and data load at a normal speed now (very quickly) 
Thanks again.
