### ISSUE TITLE
Add string to number value transformer

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#10972]
Some databases don't have a distinct type for numbers, so this kind of transformer would be super handy. Available settings are up to discussion.

**Comment by ShadelessFox** [comment]
Default|Transformed
:-:|:-:
![image](https://user-images.githubusercontent.com/35821147/132491506-dad5d622-c65e-40cd-b88f-276614ddb0ad.png)|![image](https://user-images.githubusercontent.com/35821147/132491475-ec8b33f0-548e-4557-9365-1cbc1274016a.png)

![image](https://user-images.githubusercontent.com/35821147/132491660-6ca54881-de20-4dc4-bde9-7f7c368fb6b5.png)

**Comment by uslss** [comment]
error appears if column has non-numeric symbols

![image](https://user-images.githubusercontent.com/31996417/132827936-258bfe12-9568-4c33-baea-e64f6b7f8e1e.png)

```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Fri Sep 10 11:51:43 MSK 2021
Unhandled event loop exception

java.lang.NumberFormatException: For input string: "ww"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
	at java.base/java.lang.Double.parseDouble(Unknown Source)
	at org.jkiss.dbeaver.model.impl.data.transformers.NumericAttributeTransformer$NumericValueHandler.parseValue(NumericAttributeTransformer.java:109)
	at org.jkiss.dbeaver.model.impl.data.transformers.NumericAttributeTransformer$NumericValueHandler.getValueDisplayString(NumericAttributeTransformer.java:84)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellState(SpreadsheetPresentation.java:1919)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridCellRenderer.isOverLink(GridCellRenderer.java:198)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleCellHover(LightGrid.java:3972)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleHovering(LightGrid.java:3558)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseMove(LightGrid.java:3397)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

```

**Comment by ShadelessFox** [comment]
I believe that's the expected behavior. What'd you suggest?
