### ISSUE TITLE
Bug in driver class selector UI

### ISSUE THREAD

**Issue by fokot** [dbeaver/dbeaver#11083]
#### System information: 
- Operating system (distribution) and version
macOS Catalina 10.15.6
- DBeaver version
7.3.3 (but I noticed the problem on 6.2.x version too)
- Additional extensions

#### Connection specification:
- Database name and version
Coralogix
- Driver name
driver being developed
- Do you use tunnels or proxies (SSH, SOCKS, etc)?
No

#### Describe the problem you're observing:

I add new driver via Driver manager create connection and if I try to connect I get "No suitable driver found error"
I also noticed that this was the case with older DBeaver on mac (6.2.x). I also tried to add mysql jdbc driver and it worked the same. There is maybe a problem that "Driver class" is not stored. If I reopen driver the class is not stored.
I didn't have this problem on Linux.

#### Steps to reproduce, if exist:

Look above.

**Comment by fokot** [comment]
I looked into the logs and it seems the problem is with inability to set the Driver class
```
2021-01-21 19:45:49.674 - Can't load driver properties
org.jkiss.dbeaver.DBException: Error creating driver 'Coralogix' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class ''
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1013)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:988)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:591)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSourceProvider.getConnectionProperties(JDBCDataSourceProvider.java:63)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.getConnectionProperties(GenericDataSourceProvider.java:115)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.loadDriverProperties(ConnectionPropertiesControl.java:154)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.makeProperties(ConnectionPropertiesControl.java:76)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage.lambda$0(DriverPropertiesDialogPage.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: 
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1011)
	... 9 more
> Start GEF (MVC) [org.eclipse.gef 3.11.0.201606061308]
```
Class is found when I clink on "Find Class" but it is not stored after I click on "OK" and reopen driver. As I said it looks to be specifically macOS issue. Linux is fine.

Also if driver supports `SPI` or old static registration to `DriverManager` does not matter. Neither if I check or uncheck `Use legacy JDBC instantiation` matters, it behaves the same.

**Comment by fokot** [comment]
The issue is also on macOS Big Sur.

**Comment by kseniiaguzeeva** [comment]
Thank you for the report. Could you please send log file completely? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by kseniiaguzeeva** [comment]
Also I need a sample of driver configuration.

**Comment by vllama** [comment]
I am seeing the Exact same issue on windows with the denodo jdbc driver. The class is not saved. 
and I sometimes get a random Nullpointer exception as I move through the driver dialogs.
Version 7.3.4.202101311042

**Comment by serge-rider** [comment]
I can't reproduce this as well.
Did you follow the instruction (https://github.com/dbeaver/dbeaver/wiki/Database-drivers)?

You need to change Class Name field (not just click on Find  Class button).
![image](https://user-images.githubusercontent.com/6398845/107124637-20e2c080-68b6-11eb-88b4-d47391e5d172.png)

**Comment by vllama** [comment]
I can confirm that picking a driver from find class does populate the Class Name at the top of the dialog. The bottom Driver Class dropdown is empty after re-opening the edit driver catalog.
Even though, the error still persists:
No suitable driver found for jdbc:vdb://denodo:9996/bi_analytics

**Comment by serge-rider** [comment]
@kseniiaguzeeva seems to be macos-specific

**Comment by kseniiaguzeeva** [comment]
Yes, it is one of Mac specific focus issues.

**Comment by flambchap** [comment]
Fixed.

**Comment by kseniiaguzeeva** [comment]
verified
