### ISSUE TITLE
Binary-Geometry transformer not working in special cases

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#11129]
#### System information: 
- DBeaver version 7.3.3

#### Steps to reproduce, if exist:

1. Execute query like SELECT st_asbinary(st_point(-0.090508461, 51.511680)) for example, in postgres with postgis extension
2. Try to set Geometry format to result cell in ResultSet
3. Error appears 

![2021-01-27 16_34_16-DBeaver Enterprise 7 3 3 - _gis_ Script-28](https://user-images.githubusercontent.com/45152336/105998597-e01cc780-60bd-11eb-954e-f889cb80e295.png)

```
org.locationtech.jts.io.ParseException: Unknown WKB type 256
	at org.locationtech.jts.io.WKBReader.readGeometry(WKBReader.java:235)
	at org.locationtech.jts.io.WKBReader.read(WKBReader.java:156)
	at org.jkiss.dbeaver.data.gis.handlers.GeometryConverter.fromWKB(GeometryConverter.java:70)
	at org.jkiss.dbeaver.data.gis.handlers.GISGeometryValueHandler.convertGeometryFromBinaryFormat(GISGeometryValueHandler.java:147)
	at org.jkiss.dbeaver.data.gis.handlers.GISGeometryValueHandler.getValueDisplayString(GISGeometryValueHandler.java:163)
	at org.jkiss.dbeaver.data.gis.handlers.GeometryAttributeTransformer$GISValueHandler.getValueDisplayString(GeometryAttributeTransformer.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellState(SpreadsheetPresentation.java:1801)
```

**Comment by ShadelessFox** [comment]
Geometry transformer for most databases where geometry data is stored as WKB (binary) should be working now.

Also MySQL geometry handler was refactored, so take a look how geometry behaves.

**Comment by kseniiaguzeeva** [comment]
Closed with nuances
