### ISSUE TITLE
SQL Error [22021]: ERROR: invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by redpawn96** [dbeaver/dbeaver#11139]
The error occurs when I open a table with data that has special characters.
The database have a default encoding of **SQL_ASCII**;
Collate: **C**
Ctype: **C**

I think when Dbeaver retrieves the data it uses the UTF-8 as the default charset, as the database have SQL_ASCII character encoding the JDBC can't transform the special character into UTF-8

Here are the logs generated by Dbeaver itself:

```
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0xd1 0x4f
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
```

Here are the character encoding both server and client

```
 server_encoding 
-----------------
 UTF8
(1 row)
```

```
 client_encoding 
-----------------
 UTF8
(1 row)
```

**Comment by kseniiaguzeeva** [comment]
Please tell DBeaver version, the database and steps to reproduce. Also full logs can help us https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by redpawn96** [comment]
Dbeaver version is **7.3.0**
**Steps to reproduce the error.**
1. Create a database with default encoding of SQL_ASCII, a Collate Type of C and Ctype of C.
2. Create a dummy table with a dummy varchar data type column.
3. Insert a data with special characters such as Ñ/ñ using a different database manager such as pgAdmin.
4. Go to dbeaver and open the data of the created dummy table.

**Here is the log file.**
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5964482/dbeaver-debug.log)

**Comment by ShadelessFox** [comment]
Hello @dollarsign143,

The characters from sample data you're provided is not ascii-compatible.

In fact, they're available in `latin1` encoding, also known as extended ascii. 

Perhaps you should change encoding of your database to `latin1`.

**Comment by redpawn96** [comment]
> Hello @dollarsign143,
> 
> The characters from sample data you're provided is not ascii-compatible.
> 
> In fact, they're available in `latin1` encoding, also known as extended ascii.
> 
> Perhaps you should change encoding of your database to `latin1`.

Hello @ShadelessFox,

I am very sorry for the late response. 
I understand what you are suggesting but changing the encoding of the database in a production-grade environment is impossible.
I am confused now because in PgAdmin I can read the characters even if I didn't change the encoding. 

I read some articles pointing that the problem may rest on the Postgresql JDBC driver - that is why I open this issue hoping that the developers of this project may test the JDBC drivers.

**Comment by sistemas17peru** [comment]
Same issue, PgAdmin read ok. But dbeaver show me that wrong.

**Comment by gitleo1987** [comment]
I had the same issue. This is what worked for me:

1. Right click on the connection > "Edit Connection"
2. Go to "Initialization", then click on "Configure..." (Bootstrap queries field)
3. Add SQL Query: **SET client_encoding = 'LATIN1';**
4. Save and reconnect
