### ISSUE TITLE
Database Dashboard blank

### ISSUE THREAD

**Issue by nullaegy** [dbeaver/dbeaver#11136]
HI! The Database Dashboard is completely blank.
I've tried to uninstall clean the settings, and reinstall completely the DBeaver and start from fresh, but that does help.

#### System information: 
- Microsoft Windows [Version 10.0.19042.746]
- Version 7.3.3.202101161839

#### Connection specification:
- MariaDB JDBC driver
- ssh tunnel

log:
!SESSION 2021-01-28 06:54:35.148 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2021-01-28 06:56:02.028
!MESSAGE Error initializing dashboard view
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-01-28 06:56:02.028
!MESSAGE Assistive Technology not found: com.sun.java.accessibility.AccessBridge
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-01-28 06:56:02.028
!MESSAGE com.sun.java.accessibility.AccessBridge
!STACK 0
java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/javax.swing.UIManager.<clinit>(Unknown Source)
	at org.jfree.chart.JFreeChart.<clinit>(JFreeChart.java:264)
	at org.jfree.chart.ChartFactory.createXYLineChart(ChartFactory.java:2002)
	at org.jkiss.dbeaver.ui.dashboard.histogram.DashboardRendererTimeseries.createDashboard(DashboardRendererTimeseries.java:64)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.createChartRenderer(DashboardItem.java:105)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.<init>(DashboardItem.java:92)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardList.addDashboard(DashboardList.java:246)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardList.createDefaultDashboards(DashboardList.java:233)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardListViewer.createDashboardsFromConfiguration(DashboardListViewer.java:104)
	at org.jkiss.dbeaver.ui.dashboard.view.DashboardView.createDashboardControls(DashboardView.java:96)
	at org.jkiss.dbeaver.ui.dashboard.view.DashboardView.lambda$0(DashboardView.java:67)
	at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:52)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:235)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by kseniiaguzeeva** [comment]
I see Maria dashboards in the latest version.
![dbeaver_CUYRPQtUOj](https://user-images.githubusercontent.com/51405061/106718776-8d3d9580-6612-11eb-890f-0609dd33c6a4.png)
Do you use preconfigured or custom dashboards? Is it possible to send dashboard settings, if it is a custom one?
Can you send steps to reproduce?

**Comment by nullaegy** [comment]
I've tried to completely uninstall the DBeaver, removed everything from AppData, and reinstalled it, I want to use only the default dashboard, but it's giving me the exact same error.

It's the default dashboard. A colleague is still running 7.1.1 with the proper working dashboard so I've tried to use that one, but the problem still exists for me. It seems the problem is on my end. I'll try to discover more info. I'll get back to you when I solve the problem.

**Comment by nullaegy** [comment]
uninstalled again. (made an export from projects)
deleted C:\Users\<username>\AppData\Roaming\DBeaverData
deleted c:\Users\<username>\.dbeaver4
deleted c:\Users\<username>\.dbeaver-drivers
deleted C:\Users\<username>.eclipse folder
deleted C:\Users\<username>.accessibility.properties file
reinstalled with dbeaver-ce-21.0.0-x86_64-setup.exe
import project.
everything works, event the dashboard :)

So the problem was on my side with the old dbeaver and eclipse confs, as far I can tell. I hope this helps others. ;)
