### ISSUE TITLE
Sqlite update with "from" does not recognize the validity of rowid column

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#11172]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 7.3.2
- Additional extensions -none

#### Connection specification:
- sqlite local file
- sqlite-jdbc-3.34.0.jar   SQLite JDBC driver by Taro L. Saito (extension of Zentus driver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Steps to reproduce, if exist:
My table is called p_usage_2 and I need to do an update that involves a self-join. The self-join select itself works just fine and returns results which means the rowid is recognized just fine as being part of that table (which it is), eg this works:
```sql
select p1.rowid p1r, p2.rowid p2r, p1.title p1t, p1.isbn p1i, p2.isbn p2i, p1.callnumber p1c, p2.callnumber p2c 
from p_usage_2 p1 join p_usage_2 p2 on (p1.title = p2.title) 
where p1.title is not NULL and p1.callnumber is not NULL and p2.callnumber is NULL and p1.rowid > p2.rowid;
```

and also very simple updates involving rowid also work fine, eg:
```sql
update p_usage_2 set callnumber = NULL where rowid = 11662;  -- this updates the record, no error
```

However, when I try to use this select as the basis for an update, I get the error below:

```sql
update p_usage_2 set callnumber = s.p1c from 
(select p1.rowid p1r, p2.rowid p2r, p1.title p1t, p1.isbn p1i, p2.isbn p2i, p1.callnumber p1c, p2.callnumber p2c from p_usage_2 p1 join p_usage_2 p2 on (p1.title = p2.title) 
where p1.title is not NULL and p1.callnumber is not NULL and p2.callnumber is NULL and p1.rowid > p2.rowid) as s
where s.p1i = isbn and s.p2r = rowid and callnumber is NULL;
```

I get the error message:  SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: rowid)

#### Include any warning/errors/backtraces from the logs
Here's everything from the log file relating to this event:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-01-29 19:39:39.834
!MESSAGE SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: rowid)
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-01-29 19:39:39.834
!MESSAGE SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: rowid)
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-01-29 19:39:39.834
!MESSAGE [SQLITE_ERROR] SQL error or missing database (no such column: rowid)
!STACK 0
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: rowid)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:45)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3181)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4514)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

(P.S. table `p_usage_2` is created to reproduce)

**Comment by LonwoLonwo** [comment]
Hello @mbelvadi2 
Have you try use alias for rowid when using subqueries?
https://stackoverflow.com/questions/8682398/sqlite-says-no-such-column-rowid-when-using-sub-queries

This quote is very similar to the answer you need:

> I'm guessing the reason you have to alias it in the outer query is that in that context, ROWID is ambiguous -- it could refer to a column in m1, or a column in the subquery results. But in the subquery, there's no such ambiguity. If that's the reason, then the error message is misleading, as you thought.

**Comment by LonwoLonwo** [comment]
So, this error not from DBeaver side. It is from SQLite side. And I convert this ticket into discussion.
