### ISSUE TITLE
Database Import Error

### ISSUE THREAD

**Issue by reya276** [dbeaver/dbeaver#11215]
Running DBeaver Enterprise Version 7.0
OS = Ubuntu 20.04LTS
16GB of RAM

For some weird reason I'm getting this error which have never seen before.

Maximum resident set size 482652, Integral resident set size 0
Non-physical pagefaults 419, Physical pagefaults 0, Swaps 0
Blocks in 0 out 0, Messages in 0 out 0, Signals 0
Voluntary context switches 2, Involuntary context switches 0
Task 'MySQL script' finished at Wed Feb 03 09:38:26 EST 2021
2021-02-03 09:38:26.759 - IO error: Process failed (exit code = 1). See error log.
2021-02-03 09:38:26.760 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

How can I fix this issue. I can import individual csv files and tables but not an entire restore of a database.

**Comment by kseniiaguzeeva** [comment]
Could you please give more details to reproduce the issue? Do you try to restore MySQL database? Which way do you use?
A screenshot with the problem and full logs https://github.com/dbeaver/dbeaver/wiki/Log-files will help us to fix it.

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
