### ISSUE TITLE
Redshift - JDBC driver version 2.0 Throwing Connection Error: Portal Does Not Exist

### ISSUE THREAD

**Issue by bryan7087** [dbeaver/dbeaver#11277]
#### System information: 
- Windows 10
- DBeaver 7.3.4

#### Connection specification:
- AWS Redshift
- JDBC driver version 2.0 - redshift-jdbc42-2.0.0.1
- NA - VPN only

#### Describe the problem you're observing:
When attempting to connect to Reddshift with the AWS JDBC drive V2 I get the following error:
![image](https://user-images.githubusercontent.com/72870070/107408094-1bf95900-6ad0-11eb-8755-3ed5777c55a8.png)
I suspect this is a configuration issue, and would love to know what I'm missing.

#### Steps to reproduce, if exist:
1. Edit Connection
2. Edit Driver Settings
3. Use "Add Folder" to point to the V2 driver - C:\Program Files\redshift-jdbc42-2.0.0.1
5. Remove Default Driver
6. Test Connection
![image](https://user-images.githubusercontent.com/72870070/107407691-94134f00-6acf-11eb-939c-f429cb09ebf9.png)

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2021-02-09 12:09:31.365
!MESSAGE ERROR: portal "c_22-2310134922275400" does not exist
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-02-09 12:09:31.365
!MESSAGE ERROR: portal "c_22-2310134922275400" does not exist
!STACK 0
com.amazon.redshift.util.RedshiftException: ERROR: portal "c_22-2310134922275400" does not exist
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2576)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2250)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1878)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2474)
	at com.amazon.redshift.jdbc.RedshiftResultSet.fetchMoreInQueueFromSuspendedPortal(RedshiftResultSet.java:2039)
	at com.amazon.redshift.jdbc.RedshiftResultSet.next(RedshiftResultSet.java:1954)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:112)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.loadObjects(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getDataTypes(PostgreSchema.java:459)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:585)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:297)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:894)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment]
Unfortunately we do not support 2.0 driver. Could you try another driver version?

**Comment by bryan7087** [comment]
Sure, we can continue to use the 1.x driver.  Is this on the roadmap?

**Comment by uslss** [comment]
The driver was downgraded in the scope of #11264
