### ISSUE TITLE
Informix SSL connection

### ISSUE THREAD

**Issue by wolverline** [dbeaver/dbeaver#11285]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64
- DBeaver version: Version 7.3.4.202101311042
- Additional extensions: Informix DB

#### Connection specification:
- Database name and version: Informix  Dynamic 12
- Driver name: jdbc 4.10.10.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
SSL Connection fails although I set SSLCONNECTION as true.
The same driver and exact same settings work with DbVisualizer v12.0.1.

#### Steps to reproduce, if exist:
N/A

#### Include any warning/errors/backtraces from the logs

com.informix.asf.IfxASFException: Attempt to connect to database server (my_db) failed.
  Attempt to connect to database server (my_db) failed.
  Attempt to connect to database server (my_db) failed.

**Comment by kseniiaguzeeva** [comment]
Please tell, how (and where) do you set SSL connection in DBeaver?
Also logs can be helpful https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by wolverline** [comment]
Not allowed to add Driver properties. So I added a user property as the following:

![Capture](https://user-images.githubusercontent.com/460865/110698225-5fbcac80-81bb-11eb-92ae-d8dcf13b043e.PNG)

I'm using Informix JDBC v4.10.10. I have no issues with other TCP informix connection. But SSL connection doesn't work. The error message in the log is:

!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-10 16:09:28.069
!MESSAGE 
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-10 16:09:28.069
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at com.informix.util.AdvancedProperties.getProperty(AdvancedProperties.java:94)
	at com.informix.util.AdvancedUppercaseProperties.getProperty(AdvancedUppercaseProperties.java:52)
	at com.informix.util.AdvancedProperties.asString(AdvancedProperties.java:89)
	at com.informix.asf.Connection.openSocket(Connection.java:1561)
	at com.informix.asf.Connection.connect(Connection.java:333)
	at com.informix.asf.Connection.<init>(Connection.java:327)
	at com.informix.jdbc.IfxSqliConnect.<init>(IfxSqliConnect.java:1257)
	at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:169)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:89)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
SSL for Informix is not supported by now. 

Marked as feature request

**Comment by thefamouseric** [comment]
Informix supports SSL, and work happily with Java (various applications) and Informix JDBC 4.10 and 4.50. If you are not using a CM group then the standard format connection string will work. If you are connecting to a group of CM you need to use the SQLH_TYPE syntax.

Where are these being set javax.net.ssl.trustStore and javax.net.ssl.trustStorePassword?


Attempt to connect to database server is error 908  so you are not getting a connection, look in the informix logs and I suspect you will be seeing a 28014 error. The actual error string will point you in the right direction.

**Comment by kseniiaguzeeva** [comment]
Could you please send how SSL configaration looks in another database client? It will help us to find the best way to implement the option.

**Comment by thefamouseric** [comment]
From my test harness 

System.setProperty("javax.net.ssl.trustStore", "someplace"); 
System.setProperty("javax.net.ssl.trustStorePassword", "somepassword");

/* Std SSL */
url[0] ="jdbc:informix-sqli://INFORMIXSERVER=db_ssl;DATABASE=db;USER=informix;PASSWORD=xxxx;SQLH_TYPE=FILE;SQLH_FILE=sqlhosts;SSLCONNECTION=true;";

/* SSL and CM */
url[1] ="jdbc:informix-sqli://INFORMIXSERVER=db_cm;database=db;user=informix;password=xxx;SQLH_TYPE=FILE;SQLH_FILE=sqlhosts;SSLCONNECTION=true;";

/* SSL and Group of CM*/

url[2] ="jdbc:informix-sqli://INFORMIXSERVER=g_db;database=db;user=informix;password=xxxx;SQLH_TYPE=FILE;SQLH_FILE=sqlhosts;SSLCONNECTION=true;";

/* STD java connection format will will work for all of above expect group of CM */
url[3] ="jdbc:informix-sqli://dbhost:9088/db:INFORMIXSERVER=db;user=informix;password=xxxx;";
url[4] ="jdbc:informix-sqli://dbhost:9089/db:INFORMIXSERVER=db_ssl;user=informix;password=xxxx;SSLCONNECTION=true;";


The only 'special' format that is needed is for a group of connection managers, that must use the SQLH_FILE approach.  Software such as Server Studio can request the cert from the database server, AFAIK they are java classes to enable that.  But my test harness expects the certs to already imported to the local keystore.

**Comment by wolverline** [comment]
SSL connection works with the following walkaround:

![Screenshot 2023-09-27 081602](https://github.com/dbeaver/dbeaver/assets/460865/4fc31476-8773-4f9f-a5af-1ca01b98a15f)

**Comment by LonwoLonwo** [comment]
Hello @wolverline 

I do not have a test environment now to test, but, probably, you can put this setting in your URL pattern (and not in the Schema field):

![2023-09-27 19_09_43-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/1a8760f0-1ace-49ba-abd3-f29a8fc71393)
