### ISSUE TITLE
SQL Server driver issue 7.3.4

### ISSUE THREAD

**Issue by Bartman0** [dbeaver/dbeaver#11303]
#### System information: 
- macOS Catalina 10.15.7 
- DBeaver version 7.3.4
- Additional extensions: none

#### Connection specification:
- Azure SQL
- Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
My Azure SQL connections do not work anymore, saying that the driver is missing.
Tried to download the drivers again.
Quit and restarted DBeaver. No change.

#### Steps to reproduce, if exist:
Install DBeaver 7.3.4 with existing Azure SQL connections.
Open these connections, or at least try to.

Reinstalling DBeaver 7.3.3 solves this problem, connections work as before.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2021-02-11 15:37:45.703
!MESSAGE Error creating driver 'Azure / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-02-11 15:37:45.703
!MESSAGE Error creating driver 'Azure / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-02-11 15:37:45.703
!MESSAGE com.microsoft.sqlserver.jdbc.SQLServerDriver
!STACK 0
java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1011)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:988)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:591)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:661)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:121)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:90)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:69)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment]
Please tell what do you have in driver settings?
![Screenshot 2021-02-18 at 12 46 12](https://user-images.githubusercontent.com/51405061/108338484-5c9b5580-71e7-11eb-80fe-d0658f206d56.png)

**Comment by Bartman0** [comment]
I have:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6528994/109080963-c04ee280-7701-11eb-8522-e526e69020a1.png">

**Comment by Bartman0** [comment]
I tried 7.3.5 today. That version works also. So maybe my problem was/is specific for 7.3.4 .

**Comment by kseniiaguzeeva** [comment]
Nice to hear! Please ask to reopen the ticket if you face the issue again.
