### ISSUE TITLE
Authentification/Password: value contains character '' which is non US-ASCII

### ISSUE THREAD

**Issue by bkolb249** [dbeaver/dbeaver#11320]
#### System information: 
- Windows 10
- DBeaver version 7.3.4

#### Connection specification:
- Database name and version: Postgres
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Not relevant

#### Describe the problem you're observing:
My database password contains a non-ascii string. If I try to connect, I get the following error:
"value contains character '§' which is non US-ASCII."
Is there a way to log into the database via DBeaver without needing to change the password? Are there some settings that can be changed?

#### Include any warning/errors/backtraces from the logs
'value contains character '§' which is non US-ASCII'

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by bkolb249** [comment]
heres the exception-Stacktrace:

> `java.lang.IllegalArgumentException: value contains character '§' which is non US-ASCII
	at org.postgresql.shaded.com.ongres.scram.common.util.UsAsciiUtils.toPrintable(UsAsciiUtils.java:45)
	at org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations$1.doNormalize(StringPreparations.java:43)
	at org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations.normalize(StringPreparations.java:53)
	at org.postgresql.shaded.com.ongres.scram.common.ScramFunctions.saltedPassword(ScramFunctions.java:62)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:198)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:165)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ServerFirstProcessor.clientFinalProcessor(ScramSession.java:132)
	at org.postgresql.jre8.sasl.ScramAuthenticator.processServerFirstMessage(ScramAuthenticator.java:131)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:678)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at java.base/java.lang.Thread.run(Unknown Source)`


Session data:

> `eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de
Command-line arguments:  -os win32 -ws win32 -arch x86_64`

**Comment by kseniiaguzeeva** [comment]
Thank you for logs. The problem should be in ongres driver. Could you report them?

**Comment by bkolb249** [comment]
I don't think I understand. What do you mean by "reporting them"?

**Comment by kseniiaguzeeva** [comment]
We cannot fix it from our side. It is a problem of Ongres and has to be fixed from its side.

**Comment by bkolb249** [comment]
The problem can be solved by using the newest JDBC driver; _PostgreSQL JDBC Driver version 42.2.19_

I was using Version 42.2.5
