### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/tools/JavaFileManager when creating H2 aliases

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#11428]
#### System information: 

- **Operating system (distribution) and version**: Microsoft Windows [Version 10.0.19042.804]
- **DBeaver version**: 7.3.5.202102151746
- **Java version**: openjdk version "11.0.9.1" 2020-11-04

#### Connection specification:

- **Database name and version**: H2 1.4.200
- **Driver name**: org.h2.Driver
- **Do you use tunnels or proxies (SSH, SOCKS, etc)?** No

#### Describe the problem you're observing:

I can no longer create or load H2 aliases ("stored procedures") referencing runtime compiled Java code

#### Steps to reproduce, if exist:

Create this in an H2 connection:

```sql
CREATE ALIAS REVERSE AS $$ String reverse(String s) { return new StringBuilder(s).reverse().toString(); } $$;
```

#### Include any warning/errors/backtraces from the logs

```
SQL Error [50000] [HY000]: General error: "java.lang.NoClassDefFoundError: javax/tools/JavaFileManager"; SQL statement:
CREATE ALIAS REVERSE AS $$ String reverse(String s) { return new StringBuilder(s).reverse().toString(); } $$ [50000-200]
```

It appears that despite pointing my `%JAVA_HOME%` to the JDK, a JRE is used to run DBeaver. A workaround is to specify this in the `dbeaver.ini` file:

```
-vm 
C:\Program Files\Java\jdk-11.0.9.1+1\bin
```

I think this is a recent regression as I recently upgraded DBeaver, and I don't remember having to specify the `vm` parameter

**Comment by kseniiaguzeeva** [comment]
Please send log files https://github.com/dbeaver/dbeaver/wiki/Log-files.
Why do you use your own Java? DBeaver goes already with it.

**Comment by lukaseder** [comment]
> Why do you use your own Java? DBeaver goes already with it.

As I said, this H2 feature requires a JDK, not a JRE, as H2 uses the JDK's in-memory Java compilation classes. Dbeaver ships only with a JRE, from what I can tell?

The log files don't contain anything magical other than a hint at H2 requiring classes from the JDK, which aren't included in the JRE:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-02-25 14:49:52.771
!MESSAGE javax.tools.JavaFileManager
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-02-25 14:49:52.771
!MESSAGE javax.tools.JavaFileManager
!STACK 0
java.lang.ClassNotFoundException: javax.tools.JavaFileManager
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.h2.engine.Database.getCompiler(Database.java:2736)
	at org.h2.engine.FunctionAlias.loadFromSource(FunctionAlias.java:119)
	at org.h2.engine.FunctionAlias.load(FunctionAlias.java:112)
	at org.h2.engine.FunctionAlias.init(FunctionAlias.java:99)
	at org.h2.engine.FunctionAlias.newInstanceFromSource(FunctionAlias.java:91)
	at org.h2.command.ddl.CreateFunctionAlias.update(CreateFunctionAlias.java:50)
	at org.h2.engine.MetaRecord.execute(MetaRecord.java:60)
	at org.h2.engine.Database.open(Database.java:759)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.ext.h2.model.H2DataSource.openConnection(H2DataSource.java:74)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.h2.model.H2DataSource.<init>(H2DataSource.java:43)
	at org.jkiss.dbeaver.ext.h2.model.H2MetaModel.createDataSourceImpl(H2MetaModel.java:47)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

My recommendation here is to either ship the JDK, or to use the JDK that `%JAVA_HOME%` points to, if available.

**Comment by LonwoLonwo** [comment]
That's because DBeaver does not include "javax.tools". "javax.tools" package is heavy, so we will think about - include or not include this package.

**Comment by lukaseder** [comment]
Why do you have to include it if I'm running DBeaver on a JDK?
