### ISSUE TITLE
Case insensitive in ENUM

### ISSUE THREAD

**Issue by Quiquoqua48** [dbeaver/dbeaver#11421]
Hi. I'm working on a database where often i see **enum** fields with, in example, two choices:
>enum('dbeaver', 'dBeaver')
seems it's done for words that people can write in both ways..

In any case, a get error on Dbeaver because it doesn't recognize the case difference (while I can do it, in example, on phpMyAdmin).

Is there a way to bypass this?
Thanks

**Comment by ShadelessFox** [comment]
Hello @Quiquoqua48,

What database are you using?

Please follow our issue templates, this would help avoiding unnecessary questions.

**Comment by Quiquoqua48** [comment]
Hi, I'm sorry for have not used the template before!

#### System information: 
- Operating system (distribution) and version => Linux OpenSuse Tumbleweed updated
- DBeaver version => 7.3.2.202101032114 (have to install last update)

#### Connection specification:
- Database name and version => version seems to be Mysql 5.5.68 on Plesk server. I've not understood which name I have to write (not the name of database choosed arbitrarily when it was created i suppose...)
- Driver name => MySql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? => No

#### Steps to reproduce, if exist:
- edit a Data Type to enum('dbeaver','dBeaver')
- click on save
- get error 'Errore SQL [1291] [HY000]: Column 'tipo' has duplicated value 'dbeaver' in ENUM'

#### Include any warning/errors/backtraces from the logs

```
java.sql.SQLException: Column 'tipo' has duplicated value 'dbeaver' in ENUM
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:311)
        at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:40)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:186)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:116)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:343)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:341)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:316)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1151)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ShadelessFox** [comment]
This is a database-related error.

I'm not quite sure what you're trying to achieve, can you provide a suggestion?

Thanks.

**Comment by Quiquoqua48** [comment]
Hi,
what drove me to ask here is that I can execute a query to modify the structure of a table having a field for example with ENUM('iOS', 'IOS') from phpMyAdmin, but I can't do this using Dbeaver.

I wish it was possible to differentiate capital letters in the case of enum.

Thanks

**Comment by ShadelessFox** [comment]
Again, this is a database-related error. There may be a plenty of different reasons why this exact action in phpMyAdmin succeeds, but fails in DBeaver. You can even preview generated DDL and try to execute it manually. Are you sure you're operating on the same database and table in both cases?
