### ISSUE TITLE
Met "Connection attempt timed out" issue when connect to heroku-postgresql

### ISSUE THREAD

**Issue by zoetang** [dbeaver/dbeaver#11572]
#### System information: 
- MacOS big sur version 11.2.2
- DBeaver version: 21.0.0

#### Connection specification:
- Heroku Postgres  Stander version
- Driver name : Postgres SQL 11.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  socks (the socks is working )

#### Describe the problem you're observing:
1. The connection is working well before I do the update
2. After the update , the "Connection attempt timed out"

#### Steps to reproduce, if exist:
The strange thing is I can still access to the Heroku Postgres  (Hobby Dev) version 

#### Include any warning/errors/backtraces from the logs
2021-03-02 20:59:09.265 - Connection attempt timed out.
org.postgresql.util.PSQLException: Connection attempt timed out.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:418)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:392)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:215)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:131)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:81)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
Hi @zoetang ,
sorry for the late response.
Could you check if it reproducible in case of downgrade to previous version?

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info
