### ISSUE TITLE
Getting actual row count fails with Sybase ASE

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#11576]
#### System information: 
- Windows 10
- DBeaver 21.0.0 (log entries below are from 7.3.5)
- No extensions

#### Connection specification:
- Sybase Adaptive Server Enterprise/12.0.0.7/P/EBF 10869 ROLLUP/Sun_svr4/OS 5.6/1996/32bit/FBO/Fri Feb 21 03:19:58 2003
- Driver: jTDS 1.3.1

#### Describe the problem you're observing:
Getting total row count fails with SQL syntax error

#### Steps to reproduce, if exist:
- Try to get total row count using the icon below the result set
![grafik](https://user-images.githubusercontent.com/515302/109678094-96227800-7b7a-11eb-9b80-d6f485e40c60.png)
![grafik](https://user-images.githubusercontent.com/515302/109678347-d1bd4200-7b7a-11eb-8f34-14d5519a79ec.png)

#### Include any warning/errors/backtraces from the logs
Log:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.794
!MESSAGE Error executing row count
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.794
!MESSAGE SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

!STACK 0
org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 11 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.794
!MESSAGE Incorrect syntax near the keyword 'select'.

!STACK 0
java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.794
!MESSAGE Incorrect syntax near ')'.


!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.806
!MESSAGE SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.806
!MESSAGE SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.806
!MESSAGE Incorrect syntax near the keyword 'select'.

!STACK 0
java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2021-03-02 17:16:20.806
!MESSAGE Incorrect syntax near ')'.
```

Debug log:
```
2021-03-02 17:16:20.792 - org.jkiss.dbeaver.model.exec.DBCException: Error executing row count
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3306)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	... 10 more
Caused by: java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 11 more
2021-03-02 17:16:20.793 - Incorrect syntax near ')'.
2021-03-02 17:16:20.802 - org.jkiss.dbeaver.model.exec.DBCException: Error executing row count
org.jkiss.dbeaver.model.exec.DBCException: Error executing row count
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3306)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	... 10 more
Caused by: java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 11 more
2021-03-02 17:16:20.804 - Incorrect syntax near ')'.
2021-03-02 17:16:20.805 - SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'select'.

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3268)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$37(ResultSetViewer.java:3625)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3620)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$27(ResultSetViewer.java:3613)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1714)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near the keyword 'select'.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 11 more
2021-03-02 17:16:20.805 - Incorrect syntax near ')'.
```

Above those entries I found this in the debug log:
```
2021-03-02 16:33:48.580 - Can't get column 'schema_id': Invalid column name schema_id.
2021-03-02 16:34:46.059 - org.jkiss.dbeaver.model.exec.DBCException: Error executing row count
```

**Comment by uslss** [comment]
Could you provide a query example and check in the query manager which query failed?

**Comment by maffe** [comment]
When I try to get the row count for
```
SELECT *
FROM registries;
```
the query manager shows
```
SELECT COUNT(*) FROM (SELECT *
FROM registries
) dbvrcnt
```
This query fails with the message “SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'SELECT'.”.

I don’t know if there’s another way to get the row count.

**Comment by LonwoLonwo** [comment]
Have you try execute this query in SQLEditor manually?
```

SELECT COUNT(*) FROM (SELECT *
FROM registries
) dbvrcnt
```

**Comment by maffe** [comment]
Yes I have, the syntax is not valid:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [156] [S1000]: Incorrect syntax near the keyword 'SELECT'.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3233)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4520)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near the keyword 'SELECT'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeImpl(JtdsStatement.java:809)
	at net.sourceforge.jtds.jdbc.JtdsStatement.execute(JtdsStatement.java:1282)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
```

**Comment by LonwoLonwo** [comment]
Have you try another driver?
Seems to be driver issue, unfortunately.

![2021-04-08 10_51_15-Connect to a database](https://user-images.githubusercontent.com/45152336/113988772-77d62900-9858-11eb-9d06-a285d442be56.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
