### ISSUE TITLE
System notification not showed for long operations, Make is completed dialog always on top

### ISSUE THREAD

**Issue by 452** [dbeaver/dbeaver#11594]
#### System information: 
- Ubuntu 20.04.2 LTS, GNOME 3.36.8, X11
- DBeaver IDE	21.0.0.202103021012
- Additional extensions: Spring Tool Suite 4 Version: 4.9.0.RELEASE Build Id: 202012132054

#### Connection specification:
- PostgreSQL 9.6
- PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
For long operations, you try to show system notification, and I receive an exception in the backup window
Dialog with a message must be always on top, because several times this dialog was after the Backup window, and I waiting for infinity because see no dialog)

**Expected:**
- Make is completed dialog **always on top**(because this window hides and confuse), and more informative
- Please show spent time in seconds if more than 10 seconds, and in minutes with seconds, if more than 1 minute
- Remove box brackets [ ] - is confusing, because harder to see 'is completed' or make 'is completed' bold font

#### Steps to reproduce, if exist:
Go to Tool -> Backup -> select more than 10 tables with data more than 1 GB from remote DB

#### Include any warning/errors/backtraces from the logs
```
pg_dump: creating FK CONSTRAINT "public.tenant ​​FK_tenant2property"

Task 'PostgreSQL dump' finished at Thu Mar 04 11:32:59 EET 2021
2021-03-04 11:32:59.620 - Can't show tray item
java.lang.UnsupportedOperationException
	at java.desktop/java.awt.TrayIcon.<init>(TrayIcon.java:145)
	at java.desktop/java.awt.TrayIcon.<init>(TrayIcon.java:169)
	at org.jkiss.dbeaver.ui.TrayIconHandler.show(TrayIconHandler.java:56)
	at org.jkiss.dbeaver.ui.TrayIconHandler.notify(TrayIconHandler.java:127)
	at org.jkiss.dbeaver.core.DBeaverUI.notifyAgent(DBeaverUI.java:160)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.notifyToolFinish(AbstractNativeToolHandler.java:221)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:280)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
![image](https://user-images.githubusercontent.com/1583753/109946304-c2f09f80-7ce0-11eb-9a85-74f809924965.png)
![image](https://user-images.githubusercontent.com/1583753/109946439-e9163f80-7ce0-11eb-8362-553ccdfef6ca.png)
![image](https://user-images.githubusercontent.com/1583753/109945760-3f36b300-7ce0-11eb-823f-5fd5b29be0b9.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
We must show In-process notifications for OSes which do not support native agent notifications

**Comment by uslss** [comment]
verified
