### ISSUE TITLE
SSH Tunnel - Cannot run program ssh-keygen error

### ISSUE THREAD

**Issue by lpossamai** [dbeaver/dbeaver#11613]
I have SSHJ `1.0.73` installed and I'm running Dbeaver version `21.0.0`.

When trying to set up a DB connection using an SSH tunnel, I get the following error:

`Cannot run program "ssh-keygen": error=13,Permission denied error=13,Permission denied`

My SSH key is already in OPENSSH format:

```
-----BEGIN OPENSSH PRIVATE KEY-----

[...]

-----END OPENSSH PRIVATE KEY-----
```

What should I do here? Thanks!

Edit: Found the error log

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-05 10:43:36.928
!MESSAGE error=13, Permission denied
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-05 10:43:36.928
!MESSAGE error=13, Permission denied
!STACK 0
java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey(SSHImplementationJsch.java:189)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:60)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:216)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1657)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by lpossamai** [comment]
I have uninstalled DBeaver from SNAP and have installed the version from the website. 

Now, I get the following error:

```
Cannot establish tunnel
  Auth fail
  Auth fail
```

Using the same SSH key via ssh command it works.

**Comment by ShadelessFox** [comment]
Hello @lpossamai,

Your issue may be a duplicate of #8863. **TL;DR: give the required permissions for `ssh-keygen`, so DBeaver could use it.**

Also the full log (snap version) would be helpful.

**Comment by cbcoutinho** [comment]
I have this same problem. I just updated to dbeaver 21.0 today and immediately ran into this problem with connecting to a database server using an SSH tunnel (agent).

Launching the DBeaver desktop app on openSUSE (rpm install) results in the `Auth fail` error that @lpossamai mentioned above.

Strangely, if I launch `dbeaver` from my terminal then I'm able to use SSH tunnel as normal. Where can I find the runtime logs for  DBeaver when launched as a desktop app?

On the server I see the following error:

```
error: Received disconnect from 192.168.2.11 port 47582:3: com.jcraft.jsch.JSchException: Auth fail [preauth]
```

**Comment by ShadelessFox** [comment]
Hello @cbcoutinho,

https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by cbcoutinho** [comment]
Got the debug logs @ShadelessFox, thanks for the link. I'm not comfortable listing the entire log here, but I'd be happy to send you them elsewhere (desktop vs terminal usage).

I found the problem. DBeaver wasn't able to locate the SSH socket on my client machine to access the agent because I don' t use the normal ssh socket - I use GPG authentication (via gpg-agent) for SSH access, and the appropriate variable is set in my shell whereas it isn't available to GUI applications

I had to append the SSH_AUTH_SOCK variable to the desktop file as follows:

```diff
--- /usr/share/applications/dbeaver.desktop	2021-03-02 11:22:21.000000000 +0100
+++ /home/chris/.local/share/applications/dbeaver.desktop	2021-03-10 18:00:12.485750751 +0100
@@ -6,7 +6,7 @@
 GenericName=UniversaL Database Manager
 Comment=Universal Database Manager and SQL Client.
 Path=/usr/share/dbeaver/
-Exec=/usr/share/dbeaver/dbeaver
+Exec=env SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh /usr/share/dbeaver/dbeaver
 Icon=/usr/share/dbeaver/dbeaver.png
 Categories=IDE;Development
 WMCLASS=DBeaver
```

SSH tunnel access used to work, so I'm not sure why I had to make this change.

**Comment by ShadelessFox** [comment]
Thanks @cbcoutinho, you can email me at yan@jkiss.org.

**Comment by cbcoutinho** [comment]
@ShadelessFox email sent

**Comment by lpossamai** [comment]
> Thanks @cbcoutinho, you can email me at [yan@jkiss.org](mailto:yan@jkiss.org).

The issue is still happening to me. Should I also send you an email with the logs @ShadelessFox?

**Comment by ShadelessFox** [comment]
Hello again @lpossamai,

Yes, please.

Also I would be glad to receive summary about the original issue about permission error, because currently we're talking about another issue

**Comment by lpossamai** [comment]
> Hello again @lpossamai,
> 
> Yes, please.
> 
> Also I would be glad to receive summary about the original issue about permission error, because currently we're talking about another issue

I get the below error when using SSH Tunnel via DBeaver:

```
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-03-14 16:04:18.587
!MESSAGE Auth fail
!STACK 0
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:93)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:875)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:105)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:65)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:203)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Note that if I use the same SSH-KEY to directly ssh into the ssh server, it works. I have emailed you the full log.

**Comment by ametad** [comment]
Hi, I got this exact problem too: Cannot run program "ssh-keygen": error=13, Permission denied

From the error log:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-10-05 13:42:54.512
!MESSAGE error=13, Permission denied
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-10-05 13:42:54.513
!MESSAGE error=13, Permission denied
!STACK 0
java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey(SSHImplementationJsch.java:207)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:68)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This is with a fresh installed DBeaver instance from snap on Ubuntu 20.04.3. I was trying to make a connection with SSH tunnel.

**Comment by Ernuken** [comment]
you can use this solution, it helped me https://github.com/dbeaver/dbeaver/issues/3917#issuecomment-410616717

**Comment by lpossamai** [comment]
I no longer have this issue so will close this ticket.

**Comment by dargueta** [comment]
This is happening again with 22.2.0 on Ubuntu 22.04 on a fresh install from the snap.

**Comment by timnolte** [comment]
I just updated to 22.3.4 on Pop!_OS 22.04 and now this problem is occurring. I didn't have this problem with 22.3.0.

**Comment by timnolte** [comment]
I downgraded back to 22.3.0 and everything is working as it should.

**Comment by AidanJHMurphy** [comment]
Ditto timnolte. Just ran into this after upgrading to 22.3.4. I downgraded to 22.3.3 and I'm not seeing the issue there, so it must only just be in the last minor version.

I'm currently on Ubuntu 20.04

**Comment by dylanmaurits** [comment]
> Ditto timnolte. Just ran into this after upgrading to 22.3.4. I downgraded to 22.3.3 and I'm not seeing the issue there, so it must only just be in the last minor version.
> 
> I'm currently on Ubuntu 20.04

@AidanJHMurphy 

To fix this set the 'Implementation' of your connection to SSHJ. You can find this under SSH -> Advanced Settings.

**Comment by AidanJHMurphy** [comment]
@dylanmaurits, this seems to have worked for me. Thanks!
> To fix this set the 'Implementation' of your connection to SSHJ. You can find this under SSH -> Advanced Settings.
