### ISSUE TITLE
'SQL Error [8152] String or binary data would be truncated.' happens in SQL-Server

### ISSUE THREAD

**Issue by FelixxShin** [dbeaver/dbeaver#11667]
#### System information: 
- Operating system (distribution) and version: macOS Big Sur 11.2.2
- DBeaver version: 21.0.0.202103021012
- Java version 
- Additional extensions:  With Docker 3.2.1

#### Connection specification:
- Database name and version: 
   Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64) 
	Nov  2 2020 18:35:09 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Hello.

I have a problem about using the Dbeaver with T-SQL.
When I create a procedure, It always says that '**SQL Error [8152] [22001]: String or binary data would be truncated.**'
There is nothing to use any insert/update statement.

but, Microsoft Azure Data Studio for Mac (v1.26.1) is fine and Microsoft SQL Server Management Studio works as well.

I don't know whether it's a bug or not.
I think there is some option in Dbeaver Preference but I can't find it.

Has anyone experienced the same problem?
I couldn't find any article on Google...
Please I really need to help from everyone.

Thank you for hearing me.

#### Steps to reproduce, if exist:
* SQL
--------------------------------------------------------
CREATE TYPE tbl_UserDefinedTable AS TABLE   
(
    pk int,
    id VARCHAR(50)  
);  
  
CREATE PROCEDURE sp_UserDefinedTable  
    @TVP tbl_UserDefinedTable READONLY  
AS   
    SET NOCOUNT ON  
    
    SELECT * FROM @TVP; 
--------------------------------------------------------

#### Include any warning/errors/backtraces from the logs

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [8152] [22001]: String or binary data would be truncated.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3233)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4517)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more

<img width="1214" alt="스크린샷 2021-03-10 09 23 14" src="https://user-images.githubusercontent.com/80367796/110560987-418a8880-818a-11eb-9b69-7447c1d32298.png">

**Comment by LonwoLonwo** [comment]
Can't reproduce with Microsoft SQL Server 2014

![2021-03-10 10_39_20-DBeaver Enterprise 21 0 0 - _master_ Script-10](https://user-images.githubusercontent.com/45152336/110594592-0db16200-818e-11eb-804d-0852bf25f401.png)

![2021-03-10 10_38_52-](https://user-images.githubusercontent.com/45152336/110594616-15710680-818e-11eb-942a-441ea7351870.png)
Could you check please which script is executed in the Query Manager?

And also, do you work in other DBMS with the same base as in ticket? Because the Internet says that sometimes this problems depends on the version of the base.

**Comment by FelixxShin** [comment]
Thank you for your reply.

I attach a screen shot from the Query Manager.
It's executed in other DBMS that is SQL Server 2008 on Window NT (not Docker)

Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (Intel X86) 
    Jun 28 2012 08:42:37 
    Copyright (c) Microsoft Corporation
    Express Edition with Advanced Services on Windows NT 5.2 <X86> (Build 3790: Service Pack 2)

PS. It seems like you executed on Window version. Could you execute it on Mac?
     and when I execute 'drop procedure', It's same.

<img width="1071" alt="스크린샷 2021-03-11 11 19 05" src="https://user-images.githubusercontent.com/80367796/110726307-84b52c00-825c-11eb-8c22-a46868e710b9.png">
<img width="1071" alt="스크린샷 2021-03-11 11 38 59" src="https://user-images.githubusercontent.com/80367796/110727430-9c8daf80-825e-11eb-8af2-60fa45a1facd.png">
