### ISSUE TITLE
Strip comment when executing statements

### ISSUE THREAD

**Issue by fusukevn** [dbeaver/dbeaver#11661]
**Is your feature request related to a problem? Please describe.**
I have the code like below
>select acn,STAT,boo  from  cif WHERE 
acn=100001431
--AND stat=1
AND boo=64098; 
>
it's can be running correctly if database is Oracle but if database diff ( in my case is M-database with external jdbc driver).
I have only 2 kinds of database above so I'm not sure the issue happens with the others db type or not!
The issue happen because Dbeaver sent exactly 100% code block to database server instead of removed comments line/block first. Oracle database server running support to automatic removed comments before executing but M-database is not (so it should happen with the others database type also if the database server not automatic removed comments codes)

ps: the others tools can run the query above with M-database

> error log: 

null
org.jkiss.dbeaver.model
Error
Tue Mar 09 19:56:58 ICT 2021
Query Parsing Error :-
java.sql.SQLException: Query Parsing Error :-
	at fisglobal.jdbc.dbaccess.ScDBError.check_error(Unknown Source)
	at fisglobal.jdbc.driver.ScStatement.executeQuery(Unknown Source)
	at fisglobal.jdbc.driver.ScStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.run(SQLQueryJob.java:219)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

> 

**Describe the solution you'd like**
Should have option for the user to choose "**strip comments when executing**".
if user **choosed** this option then Dbeaver **will be removed** all comments code ( event using single line code like -- or comments block /* comm*/ ) **before** sent to database server.
Otherwise if user do not choose the option then keep all selected statements sent to database server for executing.

**Describe alternatives you've considered**
I'm using DBvisualizer tools and it have the same solution.

**Additional context**
error code
[https://2.pik.vn/2021ff0e8975-3d67-4f16-b7c2-0ed6ce8fd8f6.jpg](url)

**Comment by ShadelessFox** [comment]
We don't strip comments from query because they may contain sensitive for the server information.

The issue is related to the driver you're using - it does not conform the _SQL specification_ - so use the other driver instead.
