### ISSUE TITLE
PostgreSQL array type does not have a component type

### ISSUE THREAD

**Issue by omobus** [dbeaver/dbeaver#11717]
#### System information: 
- MacOS 11.2.3
- DBeaver 21.0.0.202103021012

#### Connection specification:
- PostgreSQL 9.6
- SSH tunel

#### Describe the problem you're observing:
An exception is thrown when displaying an array.

#### Steps to reproduce, if exist:
create domain uids_t as varchar(48) array;

create table users (
user_id varchar(48) not null primary key,
pids uids_t
);

insert into  users (user_id, pids) values('1', '{1,2,3}'::uids_t);

select user_id, pids from users;

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.model.exec.DBCException: Array type uids_t doesn't have a component type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:67)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:52)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:717)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:540)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.run(SQLQueryJob.java:219)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hm, I see. We are reading information about component type (typelem column) from "uids_t", but we need to read the necessary component information from "_uids_t". 

Thanks for the bug report!

**Comment by Matvey16** [comment]
Verified

**Comment by javed125** [comment]
> Verified

Bot

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.1
