### ISSUE TITLE
JSON exporter fails for table with virtual columns in it

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#11752]
#### Steps to reproduce, if exist:
1. Open table that contains data
2. Create a virtual column with any expression
3. In navigator tree open context menu and press <kbd>Export</kbd>
4. Choose JSON as a target
5. Continue to the end, try to execute

#### Include any warning/errors/backtraces from the logs
```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterJSON.exportRow(DataExporterJSON.java:115)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:203)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:240)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:161)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by rharri** [comment]
`DBUtils.getAttributeBindings(session, dataContainer, resultSet.getMeta());` on line 118 internally calls `DBUtils.injectAndFilterAttributeBindings` which results in `columnBindings` having duplicate references to the virtual column. This in itself does not cause this particular problem, though it is probably not intended behaviour.

https://github.com/dbeaver/dbeaver/blob/434253ee861c1a577318ae3cd3a4a2512c51dd21/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java#L110-L150

The `java.lang.ArrayIndexOutOfBoundsException` itself is caused by the fetched row not having the same number of elements as the expected number of columns. The `DataExporterJSON.columns` includes virtual columns, and the `StreamTransferConsumer.fetchRow` method returns a row without the virtual column values.

I'm unsure if this is intentional or not as the `columnCount` in `StreamTransferConsumer.fetchRow` does not include virtual columns.

It seems the fix would be to have:

- `columnCount` include virtual columns (e.g. `int columnCount = attributes.length`)
- `StreamTransferConsumer.fetchRow` set a value for virtual columns

To address the earlier comment about the `columnBindings`, it would also seem that reverting to the earlier behaviour of setting `columnBindings` equal to `columnMetas` would resolve the duplicate references.

The relevant history:
- https://github.com/dbeaver/dbeaver/commit/c670f0031c58bf87e81c173bd6566bfe0046114d
- #6725

**Comment by uslss** [comment]
not reproducible in 23.0.3
