### ISSUE TITLE
Can't view DynamoDB table in grid view

### ISSUE THREAD

**Issue by parthipank** [dbeaver/dbeaver#11772]
#### System information: 
- Windows 10
- DBeaver Enterprise 21.0 

#### Connection specification:
- AWS DynamoDB

#### Describe the problem you're observing:
I'm getting an error, when I try to load a dynamoDB table data. On the left plane in Data tab, JSON is the only available data representation option which is visible for this particular table. When I click on the JSON button to toggle the view I get "Can't switch presentation".  The exact error message is below.

![image](https://user-images.githubusercontent.com/10793238/111525405-97ab8d00-8783-11eb-9b71-57ed1e83a66b.png)

Moreover, the JSON view is also broken, where it only shows the first record and not allowing to scroll further.
I don't have a clear idea of what is causing this error.

**Comment by uslss** [comment]
Hi @parthipank ,
could you provide table DDL?
Is there something in the [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by parthipank** [comment]
Hi @uslss ,
How do I get the table DDL?
Here is the error log.
![image](https://user-images.githubusercontent.com/10793238/112106417-a8b92b80-8bd3-11eb-8a74-f07953faa9a3.png)

**Comment by parthipank** [comment]
@uslss 
This is the Java version that I'm currently running.
```
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

**Comment by kseniiaguzeeva** [comment]
Please:
1. send a screenshot what do you see instead of a table
2. send log and debug log files completely https://github.com/dbeaver/dbeaver/wiki/Log-files
3. do you open a table in Data Editor or SQL Editor? If it is SQL Editor, tell the query which you execute.

**Comment by parthipank** [comment]
Here's the error log
`java.lang.NumberFormatException: For input string: "1008901015118442374100"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at com.dbeaver.db.dynamodb.DynamoDBUtils.getRawNumber(DynamoDBUtils.java:154)
	at com.dbeaver.db.dynamodb.DynamoDBUtils.getRawAttributeValue(DynamoDBUtils.java:63)
	at com.dbeaver.db.dynamodb.DynamoDBUtils.makeDocumentMap(DynamoDBUtils.java:185)
	at com.dbeaver.db.dynamodb.data.DynamoDocument.makeRawMap(DynamoDocument.java:127)
	at com.dbeaver.ee.model.document.data.DBAbstractDocument.getRootNode(DBAbstractDocument.java:62)
	at com.dbeaver.ee.model.document.data.DBAbstractDocument.getRootNode(DBAbstractDocument.java:1)
	at com.dbeaver.ee.runtime.ui.resultset.document.TextRenderer.computeSize(TextRenderer.java:107)
	at com.dbeaver.ee.runtime.ui.resultset.document.DocumentFrame.updateSizes(DocumentFrame.java:149)
	at com.dbeaver.ee.runtime.ui.resultset.document.AbstractDocumentPresentation.updateMeasures(AbstractDocumentPresentation.java:502)
	at com.dbeaver.ee.runtime.ui.resultset.document.AbstractDocumentPresentation.lambda$2(AbstractDocumentPresentation.java:191)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1042)
	at org.eclipse.swt.widgets.Control.sendResize(Control.java:3068)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1011)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3309)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3305)
	at org.eclipse.swt.custom.SashFormLayout.layout(SashFormLayout.java:110)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:697)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:216)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3309)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3305)
	at org.eclipse.swt.custom.CTabFolderLayout.layout(CTabFolderLayout.java:119)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1015)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1060)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:216)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1729)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4839)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5694)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3276)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1054)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:231)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1729)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4839)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5694)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3276)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1054)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3309)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3305)
	at org.eclipse.swt.custom.CTabFolderLayout.layout(CTabFolderLayout.java:119)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1729)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4839)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5694)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3276)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1054)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:216)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1729)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4839)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5694)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3276)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1054)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3237)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3233)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3228)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:216)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1328)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1729)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4839)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5694)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4852)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:986)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:963)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1159)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1329)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1334)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1334)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1334)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1334)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1334)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1313)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1120)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4050)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3619)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:243)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
`

**Comment by parthipank** [comment]
@kseniiaguzeeva Here is the complete log file
[.log](https://github.com/dbeaver/dbeaver/files/6250948/default.log)

**Comment by parthipank** [comment]
@serge-rider serge-rider @kseniiaguzeeva  @uslss 
Also when I click the metadata It's showing "##document" only. (See screenshot below)
![image](https://user-images.githubusercontent.com/10793238/114144907-74fc3680-9933-11eb-9015-86d3c07e3815.png)

and then when I click the "##document" the error below is getting populated in the error log window.
![image](https://user-images.githubusercontent.com/10793238/114145161-c1e00d00-9933-11eb-97d1-5c9739a945c6.png)

**Comment by kseniiaguzeeva** [comment]
Thank you.

**Comment by ShadelessFox** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35821147/117039089-0bdcc880-ad11-11eb-9fef-5c0dfcad4cf3.png)

The problem is that DynamoDB supports arbitrary-length numbers, and DBeaver was not-aware of that.
[https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes)

**Comment by parthipank** [comment]
> Fixed:
> 
> ![image](https://user-images.githubusercontent.com/35821147/117039089-0bdcc880-ad11-11eb-9fef-5c0dfcad4cf3.png)
> 
> The problem is that DynamoDB supports arbitrary-length numbers, and DBeaver was not-aware of that.
> [https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes)

Thank you! I appreciate the team for fixing this. It works fine now. :)

**Comment by parthipank** [comment]
Thank you @ShadelessFox. I appreciate the team for fixing this. It works fine now. :)

**Comment by parthipank** [comment]
Hi @ShadelessFox, Just want to know whether this fix will be applied to the cloudbeaver version too?
We are planning on using cloudbeaver for some projects.

**Comment by ShadelessFox** [comment]
I can't answer this question right away, unfortunately.

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
Now we can show big numbers. We still can't edit them.

**Comment by ShadelessFox** [comment]
Works as expected (limit is up to 38 digits of precision).
