### ISSUE TITLE
NPE appears in reference panel for ref table

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#11807]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 21.0.1 EA

#### Connection specification:
- Database name and version Sybase
- Driver name jconnect

#### Describe the problem you're observing:
Two tables exists:
```sql
-- master.dbo.NewTable definition

-- Drop table

-- DROP TABLE master.dbo.NewTable GO

CREATE TABLE master.dbo.NewTable (
	c_nchar nchar(100) NOT NULL,
	c_varchar varchar(100) NULL,
	CONSTRAINT NewTable_PK PRIMARY KEY (c_nchar)
) GO;


-- master.dbo.NewTable_to definition

-- Drop table

-- DROP TABLE master.dbo.NewTable_to GO

CREATE TABLE master.dbo.NewTable_to (
	c_nchar nchar(100) NULL,
	c_varchar varchar(100) NULL,
	CONSTRAINT NewTable_to_FK FOREIGN KEY (c_nchar) REFERENCES master.dbo.NewTable(c_nchar) ON DELETE RESTRICT ON UPDATE RESTRICT
) GO;
```
Open NewTable and check reference panel - NPE appears, nothing is shown at ref panel

```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sun Mar 21 10:24:23 MSK 2021


java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$RefKeyLabelProvider.getText(ReferencesResultsContainer.java:463)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.createTableItems(CSmartCombo.java:575)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.createPopup(CSmartCombo.java:550)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.dropDown(CSmartCombo.java:620)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.arrowEvent(CSmartCombo.java:802)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.lambda$0(CSmartCombo.java:136)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

```

**Comment by LonwoLonwo** [comment]
I can't reproduce in DBeaver 21.0.2
Waiting for steps.

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
Error appears on table opening.
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Apr 07 11:27:08 MSK 2021
Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4870)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.custom.StyledText.setText(StyledText.java:10556)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.select(CSmartCombo.java:400)
	at org.jkiss.dbeaver.ui.controls.CSmartCombo.addItem(CSmartCombo.java:230)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer.fillKeysCombo(ReferencesResultsContainer.java:308)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer.access$8(ReferencesResultsContainer.java:299)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$2.lambda$0(ReferencesResultsContainer.java:286)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)


```
