### ISSUE TITLE
Cannot load and save scripts

### ISSUE THREAD

**Issue by sk-dataocean-online** [dbeaver/dbeaver#11925]
#### System information: 
- Operating system (distribution) and version: Linux Mint 18.3 Cinnamon 64-bit (Kernel 4.15.0-128-generic)
- DBeaver version: 21.0.1.202103220618

#### Connection specification:
- Database name and version: PostgreSQL 10.16 (Ubuntu 10.16-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit

#### Describe the problem you're observing:
Error message when trying to open or save any script - "Problem occured - Unhandled event loop exception. No more handles"

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2021-03-30 18:29:11.988
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-03-30 18:29:11.988
!MESSAGE No more handles
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4901)
	at org.eclipse.swt.SWT.error(SWT.java:4790)
	at org.eclipse.swt.SWT.error(SWT.java:4761)
	at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
	at org.eclipse.swt.widgets.FileDialog.openNativeChooserDialog(FileDialog.java:345)
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:329)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:85)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:73)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:239)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:218)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5785)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5048)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4526)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

**Comment by kseniiaguzeeva** [comment]
Please restart DBeaver and try again. Does it help?

**Comment by sk-dataocean-online** [comment]
> Please restart DBeaver and try again. Does it help?

It doesn't. I have updated it to 21.0.2 but the issue remains. I also have some other strange issues that happened a few months ago and still persist:

1. An attempt to select part of a text or part of a table by mouse (dragging) results in the selection from the very beginning to the start of the selection. The only workaround is to hold shift and make a second click.
2. Click at the column header to order it doesn't work at all. The workaround is to right click - order - order by ...
3. Typing some text in the "name-value" kind of controls (like create new column dialog) is invisible until Enter is pressed or the focus is blurred. This is really annoying - blind typing.

I believe these are all eclipse issues but have no idea how to check or fix this.

**Comment by uslss** [comment]
@sk-dataocean-online could you try to update to 21.0.3?
seems, at least, first issue should be fixed in it (#10914)

**Comment by sk-dataocean-online** [comment]
> @sk-dataocean-online could you try to update to 21.0.3?
> seems, at least, first issue should be fixed in it (#10914)

Unfortunately, this update didn't resolve those issues...

**Comment by uslss** [comment]
duplicates #9206
