### ISSUE TITLE
SQL Error HY001: PWS00001 function did not complete successfully on IBMi DB2

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#11942]
#### System information: 
- Operating system (distribution) and version
Windows 10.
- DBeaver version
21.0.1
- Additional extensions
None

#### Connection specification:
- Database name and version
IBMi DB2 V7R3
- Driver name
Db2 iSeries (com.ibm.as400.access.AS400JDBCDriver) / JT400.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:

When selecting data from a file that has BLOB data you are unable to save the blob data to a file.

#### Steps to reproduce, if exist:

Double click a blob field on IBMi DB2 database. It will show the hex / byte data in the "Value" tab in DBEaver.

Now hit save to file button.

When it attempts to save to file you get this error:

![image](https://user-images.githubusercontent.com/6610039/113162776-306eed80-9205-11eb-8a84-afdd4284fd8d.png)

**Comment by xantari** [comment]
Figured it out.

You need to set this to fix this issue:

![image](https://user-images.githubusercontent.com/6610039/113163626-f4885800-9205-11eb-8e3a-6fb599c7c38b.png)

**Comment by xantari** [comment]
Reopening this issue.

Using 21.1.4 and this no longer works. Getting the function did not complete error PWS0001:

![image](https://user-images.githubusercontent.com/6610039/154775534-3cc3ee86-5fb6-4c72-9bc1-9e79600c4846.png)

**Comment by xantari** [comment]
Log:

2022-02-18 17:47:47.850 - Connected (db2_iseries-15946833307-1eb6d2776c993fc2, AS/400 Toolbox for Java JDBC Driver [12.7])
2022-02-18 17:47:47.866 - Execution context opened (DB2 - SERVERNAME; SQLEditor <Script-93.sql>; 5)
2022-02-18 17:47:48.208 - Duplicate object name 'VARGRAPHIC' in cache GenericDataTypeCache. Last value: VARGRAPHIC
2022-02-18 17:47:53.480 - Skip statistics index 'MYFILE_#DBOBJ' in 'ARRTFLIB.MYFILE'
2022-02-18 17:47:53.658 - Schema '*USRLIBL' not found
2022-02-18 17:47:53.698 - PK table TESTMST.*USRLIBL.MYFILE was taken from FK container.
2022-02-18 17:48:00.545 - Can't detect image type: SQL Error [HY001]: [PWS0001] Function did not complete successfully.
2022-02-18 17:48:00.653 - [PWS0001] Function did not complete successfully.
java.sql.SQLException: [PWS0001] Function did not complete successfully.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:985)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:745)
	at com.ibm.as400.access.JDLobLocator.getLength(JDLobLocator.java:122)
	at com.ibm.as400.access.AS400JDBCBlobLocator.length(AS400JDBCBlobLocator.java:163)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getLOBLength(JDBCContentBLOB.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentLOB.getContentLength(JDBCContentLOB.java:48)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getContents(JDBCContentBLOB.java:85)
	at org.jkiss.dbeaver.ui.data.BinaryPanelEditor.primeEditorValue(BinaryPanelEditor.java:80)
	at org.jkiss.dbeaver.ui.data.BinaryPanelEditor.primeEditorValue(BinaryPanelEditor.java:1)
	at org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor$StreamValueLoadService.evaluate(ContentPanelEditor.java:497)
	at org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor$StreamValueLoadService.evaluate(ContentPanelEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by xantari** [comment]
Re-closing this. So I found out that if you put in too large of a value for "lob threshold", such as 32769999999 viewing of the blob data stops working. However a value of 32679999 (32 megabytes) seems to work fine. 

So I guess the moral of the story here, is don't put an unreasonably high value.
