### ISSUE TITLE
Error downloading installation file during automatic version upgrade

### ISSUE THREAD

**Issue by ducklingasa** [dbeaver/dbeaver#11996]
#### System information: 
- Windows 10 Enterprise, 1909
- DBeaver version 21.0.1.202103211229 (portable zip)
- Java (built-in): openjdk version "11.0.5" 2019-10-15
- Additional extensions: DBeaver Office Support

#### Describe the problem you're observing:
During the Upgrade to version 21.0.2 the new version seems to be downloading (the percentage is going up), then the following error message appears: "Error downloading installation file: Tag mismatch!".

#### Steps to reproduce, if exist:
Check for Updates then choose Upgrade ...

#### Include any warning/errors/backtraces from the logs
javax.crypto.AEADBadTagException: Tag mismatch!
	at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(Unknown Source)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(Unknown Source)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.net.www.MeteredStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at org.jkiss.dbeaver.runtime.WebUtils.downloadRemoteFile(WebUtils.java:162)
	at org.jkiss.dbeaver.runtime.WebUtils.downloadRemoteFile(WebUtils.java:123)
	at org.jkiss.dbeaver.ui.app.standalone.update.VersionUpdateDialog$1.run(VersionUpdateDialog.java:268)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ducklingasa** [comment]
Also, based on the debug log it tries to download the "https://dbeaver.io/files/dbeaver-ce-latest-x86_64-setup.exe" file, which is not really useful to upgrade the portable zip version.

**Comment by ShadelessFox** [comment]
Hello @ducklingasa,

Thanks for the report. I cannot reproduce this issue, maybe it was a temporary error.

I agree, we download installation file and run it, not respecting the type of current DBeaver installation.

I don't know what solution for zip would be better. You can create a separate issue based on https://github.com/dbeaver/dbeaver/issues/11996#issuecomment-813942251.

**Comment by ducklingasa** [comment]
Hi @ShadelessFox,

Thanks for checking this out, I did several tests in the morning when I had the issue all the time, but now it's gone.
Though, will create a separate feature request for [#11996 (comment)](https://github.com/dbeaver/dbeaver/issues/11996#issuecomment-813942251).
