### ISSUE TITLE
cannot create a database in DB2 Z/OS connection for "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by June11227** [dbeaver/dbeaver#12033]
#### System information: 
- Operating system (distribution) and version
- DBeaver version **21.0.1**
- Additional extensions
 
![image](https://user-images.githubusercontent.com/82075280/113963970-2714ff00-985d-11eb-9007-3feff8b5d59a.png)
![image](https://user-images.githubusercontent.com/82075280/113963988-3005d080-985d-11eb-92d8-0dc20b89136c.png)
![image](https://user-images.githubusercontent.com/82075280/113964009-3a27cf00-985d-11eb-9853-19caf77338c9.png)
![image](https://user-images.githubusercontent.com/82075280/113964022-401db000-985d-11eb-8986-21e62d4f9cd1.png)

#### Connection specification:
- Database name and version  DB2 Z/OS
- Driver name  db2jcc.jar/db2jcc_license_cisuz.jar/db2jcc_license_cu.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  

#### Describe the problem you're observing:
I am trying to connect a database named BIGSQL
URL: jdbc:db2://hdp-master-7.datalake-hdp.zc2.ibm.com:52000/BIGSQL
ssLConnection: True
ssLTrustStoreLocation: C:\Users\YeLingZhou\Desktop\NewCo\files\ibm-truststore.jks
ssLTrustStorePassword: vLYpWnJoi27ir7ZM/vLYpWnJoi27ir7ZM

#### Steps to reproduce, if exist:
I am update the URL to : jdbc:db2://hdp-master-7.datalake-hdp.zc2.ibm.com:52000/BIGSQL:sslConnection=true;
as it has SSL, but it still meet the error "unable to find valid certification path to requested target"

#### Include any warning/errors/backtraces from the logs

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
	at com.ibm.db2.jcc.t4.eb.b(eb.java:1735)
	at com.ibm.db2.jcc.t4.eb.a(eb.java:1683)
	at com.ibm.db2.jcc.t4.a.h(a.java:482)
	at com.ibm.db2.jcc.t4.a.flush_(a.java:413)
	at com.ibm.db2.jcc.am.Agent.flowOutsideUOW(Agent.java:261)
	at com.ibm.db2.jcc.t4.b.b(b.java:1255)
	at com.ibm.db2.jcc.t4.b.b(b.java:813)
	at com.ibm.db2.jcc.t4.b.a(b.java:784)
	at com.ibm.db2.jcc.t4.b.a(b.java:430)
	at com.ibm.db2.jcc.t4.b.a(b.java:403)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:341)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:234)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:200)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:472)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:113)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.db2.zos.model.DB2ZOSDataSource.<init>(DB2ZOSDataSource.java:33)
	at org.jkiss.dbeaver.ext.db2.zos.model.DB2ZOSMetaModel.createDataSourceImpl(DB2ZOSMetaModel.java:49)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:896)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64
![image](https://user-images.githubusercontent.com/82075280/113963923-14022f00-985d-11eb-9b13-1b27617dcfbf.png)

**Comment by uslss** [comment]
Seems it could be related to incorrect SSL certificates
https://www.ibm.com/support/pages/complete-guide-set-ssl-using-ibm-data-server-driver-jdbc-and-sqlj

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual for you, feel free to reopen an issue
