### ISSUE TITLE
cant start dbeaver

### ISSUE THREAD

**Issue by dddeveloperrr** [dbeaver/dbeaver#12072]
hi everyone
Installed dbeaver from snap store but got error when launching program.

OS: Linux (manjaro) kernel   5.11.6-1-MANJARO
DE: XFCE 
snap version: 
snap     2.49.1-1
snapd    2.49.1-1
series   16
 below is the output of this commande :  snap run dbeaver-ce

output:
Gtk-Message: 21:04:51.288: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:04:51.288: Failed to load module "xapp-gtk3-module"
Picked up _JAVA_OPTIONS: -Duser.home=/home/farhad/snap/dbeaver-ce/108
Gtk-Message: 21:04:51.831: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:04:51.831: Failed to load module "xapp-gtk3-module"
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.0.2.202104042040]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.900.v20201102-2031]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.12.0.v20201119-1132]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.900.v20201014-0742]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.1000.v20200909-1312]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.18.0.v20201119-1132]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 21.0.2.202104042040]
2021-04-11 21:04:53.955 - Initializing DBeaver 21.0.2
2021-04-11 21:04:53.957 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 21.0.2.202104042040
2021-04-11 21:04:53.957 - Initialize Core...
2021-04-11 21:04:53.958 - Can't find BC security provider. Use default JCE.
2021-04-11 21:04:53.958 - BouncyCastle not registered, using the default JCE provider
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.900.v20201105-1507]
2021-04-11 21:04:54.277 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.54.202104042040]
2021-04-11 21:04:54.322 - Core initialized (365ms)
2021-04-11 21:04:54.324 - Create display
2021-04-11 21:04:54.548 - DBeaver 21.0.2.202104042040 is starting
2021-04-11 21:04:54.549 - OS: Linux 5.11.6-1-MANJARO (amd64)
2021-04-11 21:04:54.549 - Java version: 11.0.9.1 by AdoptOpenJDK (64bit)
2021-04-11 21:04:54.550 - Install path: '/snap/dbeaver-ce/108/usr/share/dbeaver'
2021-04-11 21:04:54.550 - Instance path: 'file:/home/farhad/snap/dbeaver-ce/108/.local/share/DBeaverData/workspace6/'
2021-04-11 21:04:54.550 - Memory available 64Mb/1024Mb
2021-04-11 21:04:54.574 - Starting RMI server at 49778
2021-04-11 21:04:54.671 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.15.0.v20201103-0952]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.500.v20200928-2213]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.4.0.v20201014-0944]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.21.0.v20200917-1439]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.900.v20201021-1339]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.0.v20201119-1132]
> Start Expression Language [org.eclipse.core.expressions 3.7.0.v20200720-1126]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.0.v20201103-0952]
2021-04-11 21:04:56.315 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4875)
	at org.eclipse.swt.SWT.error(SWT.java:4790)
	at org.eclipse.swt.SWT.error(SWT.java:4761)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:487)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:124)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:69)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1759)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5895)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1753)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1607)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2759)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:637)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
2021-04-11 21:04:56.334 - DBeaver is stopping
2021-04-11 21:04:56.336 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.69.202104042040]
2021-04-11 21:04:56.362 - DBeaver shutdown completed
2021-04-11 21:04:56.452 - Shutdown Core...
2021-04-11 21:04:56.642 - Total database drivers: 89 (89)
2021-04-11 21:04:56.733 - Shutdown completed in 281ms

**Comment by riednyko** [comment]
Try to update your xapp version.
https://forum.manjaro.org/t/failed-to-load-module-xapp-gtk3-module/46039/10

**Comment by uslss** [comment]
@dddeveloperrr is your issue solved?

**Comment by dddeveloperrr** [comment]
> @dddeveloperrr is your issue solved?

Unfortunately not. I just updated Manjaro but still get error

[farhad@farhad-hp ~]$ snap run dbeaver-ce
Gtk-Message: 12:01:28.932: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:01:28.933: Failed to load module "xapp-gtk3-module"
Picked up _JAVA_OPTIONS: -Duser.home=/home/farhad/snap/dbeaver-ce/111
Gtk-Message: 12:01:29.467: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:01:29.468: Failed to load module "xapp-gtk3-module"
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.0.4.202105021514]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.0.v20210122-1423]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.12.100.v20210122-1731]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.1000.v20210111-0958]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.1100.v20210111-0815]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.18.100.v20210122-1536]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 21.0.4.202105021514]
2021-05-12 12:01:31.500 - Initializing DBeaver 21.0.4
2021-05-12 12:01:31.501 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 21.0.4.202105021514
2021-05-12 12:01:31.502 - Initialize Core...
2021-05-12 12:01:31.502 - Can't find BC security provider. Use default JCE.
2021-05-12 12:01:31.503 - BouncyCastle not registered, using the default JCE provider
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.14.0.v20210215-0934]
2021-05-12 12:01:31.826 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.56.202105021514]
2021-05-12 12:01:31.869 - Core initialized (368ms)
2021-05-12 12:01:31.871 - Create display
2021-05-12 12:01:32.104 - DBeaver 21.0.4.202105021514 is starting
2021-05-12 12:01:32.106 - OS: Linux 5.11.6-1-MANJARO (amd64)
2021-05-12 12:01:32.106 - Java version: 11.0.9.1 by AdoptOpenJDK (64bit)
2021-05-12 12:01:32.106 - Install path: '/snap/dbeaver-ce/111/usr/share/dbeaver'
2021-05-12 12:01:32.106 - Instance path: 'file:/home/farhad/snap/dbeaver-ce/111/.local/share/DBeaverData/workspace6/'
2021-05-12 12:01:32.107 - Memory available 64Mb/1024Mb
2021-05-12 12:01:32.143 - Starting RMI server at 38904
2021-05-12 12:01:32.221 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
2021-05-12 12:01:34.024 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:487)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:124)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:69)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1759)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5941)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1753)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1607)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2759)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:637)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
2021-05-12 12:01:34.058 - DBeaver is stopping
2021-05-12 12:01:34.061 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.71.202105021514]
2021-05-12 12:01:34.105 - DBeaver shutdown completed
2021-05-12 12:01:34.262 - Shutdown Core...
2021-05-12 12:01:34.464 - Total database drivers: 90 (90)
2021-05-12 12:01:34.551 - Shutdown completed in 289ms

**Comment by riednyko** [comment]
@dddeveloperrr try to update dbeaver-ce snap package, we updated the gtk module in the build, this may help.

**Comment by dddeveloperrr** [comment]
dbeaver snap updated. it didn't help. still get a bunch of errors

[farhad@farhad-hp ~]$ snap run dbeaver-ce
Gtk-Message: 23:33:33.042: Failed to load module "xapp-gtk3-module"
Gtk-Message: 23:33:33.043: Failed to load module "xapp-gtk3-module"

(dbeaver:9867): dbind-WARNING **: 23:33:33.085: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-HprshhAM92: No such file or directory
Picked up _JAVA_OPTIONS: -Duser.home=/home/farhad/snap/dbeaver-ce/112
Gtk-Message: 23:33:33.580: Failed to load module "xapp-gtk3-module"
Gtk-Message: 23:33:33.580: Failed to load module "xapp-gtk3-module"

(java:9934): dbind-WARNING **: 23:33:33.621: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-HprshhAM92: No such file or directory
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.0.4.202105021514]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.12.100.v20210122-1731]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.0.v20210122-1423]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.1000.v20210111-0958]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.1100.v20210111-0815]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.18.100.v20210122-1536]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 21.0.4.202105021514]
2021-05-14 23:33:35.307 - Initializing DBeaver 21.0.4
2021-05-14 23:33:35.308 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 21.0.4.202105021514
2021-05-14 23:33:35.308 - Initialize Core...
2021-05-14 23:33:35.309 - Can't find BC security provider. Use default JCE.
2021-05-14 23:33:35.309 - BouncyCastle not registered, using the default JCE provider
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.14.0.v20210215-0934]
2021-05-14 23:33:35.613 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.56.202105021514]
2021-05-14 23:33:35.653 - Core initialized (345ms)
2021-05-14 23:33:35.655 - Create display
2021-05-14 23:33:35.873 - DBeaver 21.0.4.202105021514 is starting
2021-05-14 23:33:35.874 - OS: Linux 5.11.18-1-MANJARO (amd64)
2021-05-14 23:33:35.875 - Java version: 11.0.9.1 by AdoptOpenJDK (64bit)
2021-05-14 23:33:35.875 - Install path: '/snap/dbeaver-ce/112/usr/share/dbeaver'
2021-05-14 23:33:35.875 - Instance path: 'file:/home/farhad/snap/dbeaver-ce/112/.local/share/DBeaverData/workspace6/'
2021-05-14 23:33:35.875 - Memory available 64Mb/1024Mb
2021-05-14 23:33:35.898 - Starting RMI server at 56747
2021-05-14 23:33:35.992 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
2021-05-14 23:33:37.510 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:487)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:124)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:69)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1759)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5941)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1753)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1607)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2759)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:637)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
2021-05-14 23:33:37.553 - DBeaver is stopping
2021-05-14 23:33:37.554 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.71.202105021514]
2021-05-14 23:33:37.591 - DBeaver shutdown completed
2021-05-14 23:33:37.677 - Shutdown Core...
2021-05-14 23:33:37.881 - Total database drivers: 90 (90)
2021-05-14 23:33:37.954 - Shutdown completed in 277ms



Note: 
I also tried to run snap-store. 

[farhad@farhad-hp ~]$ snap run snap-store
19:04:49:0685 Gtk Failed to load module "xapp-gtk3-module"
19:04:49:0685 Gtk Failed to load module "xapp-gtk3-module"
19:04:49:0685 Gtk Failed to load module "canberra-gtk-module"
19:04:49:0685 Gtk Failed to load module "canberra-gtk-module"

Although I got same error, but snap-store runs perfectly and I can use it. but in the case of dbeaver, it shuts down.
![image](https://user-images.githubusercontent.com/11577640/118317469-56c6bf00-b50d-11eb-9a37-fd2e72819de1.png)

**Comment by IT-Tool** [comment]
@dddeveloperrr 
As a temporary solution, you can try to run app without installation from this archive (I checked, it works and runs on Manjaro XFCE).

1. Download the archive https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
2. Right-click on the downloaded archive and choose "Extract here"
3. Run the "dbeaver file" in the unpacked folder through the terminal (in my case just insert the full path to the file) /home/manjaro/Downloads/dbeaver/dbeaver

To check if the program runs

**Comment by Matvey16** [comment]
there is no update on issue for a long time. if it is still actual for you - feel free to reopen it with additional info.
