### ISSUE TITLE
Reorganize PostgreSQL server-level nodes

### ISSUE THREAD

**Issue by yonisade** [dbeaver/dbeaver#12071]
**Is your feature request related to a problem? Please describe.**
Currently, server-level entities show up under all databases of a PostgreSQL server, which is redundant and confusing.

**Describe the solution you'd like**
Create "Databases" node under server name and show all databases under it.
Move "Roles","Administer","Storage","System Info" nodes to under the Server name.

**Comment by uslss** [comment]
thanks for the suggestion

**Comment by serge-rider** [comment]
Done. Extensions and system variables remain on database level, the rest moved to root folders.

**Comment by uslss** [comment]
Target container in data transfer could be chosen only for pg-like database with simple view enabled. No catalogs are shown for connections with Advanced view
![image](https://user-images.githubusercontent.com/31996417/142377868-5cb1af84-a98a-4584-ac8e-45538d0325a0.png)

**Comment by uslss** [comment]
Create role is available in Roles catalog, but Role cannot be created
![image](https://user-images.githubusercontent.com/31996417/142378416-415e89e1-9a09-4e3f-aa72-0ecfced395c4.png)
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\Dziyana\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2021-11-18 10:54:33.140

org.jkiss.dbeaver.model
Error
Thu Nov 18 11:21:31 MSK 2021
Can't create object here.
Wrong container type: PostgreDataSource

org.jkiss.dbeaver.DBException: Can't create object here.
Wrong container type: PostgreDataSource
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:90)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:336)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
objects permissions cannot be opened
![image](https://user-images.githubusercontent.com/31996417/142384731-b0d0b921-b051-4a86-8d8d-054b5a4ca220.png)

**Comment by serge-rider** [comment]
All fixed

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
```
2021-11-19 02:26:04.600 - java.lang.NullPointerException
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getChildFolder(DBNUtils.java:61)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$PageControl$1.completeLoading(PostgresRolePrivilegesEditor.java:538)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$PageControl$1.completeLoading(PostgresRolePrivilegesEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:130)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
```

Roles -> Permissions

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
