### ISSUE TITLE
PK/index/column cannot be created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12117]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.3 EA

#### Connection specification:
- Database name and version PrestoDB
- Driver name PrestoSQL - Presto JDBC 350, PrestoDB - PrestoJDBC 0.250

#### Describe the problem you're observing:
Error appears in case of attempt to create index or primary key

Primary Key 
```
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -clearPersistedState
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/37529/AppData/Roaming/DBeaverData/workspace6/ -clearPersistedState

org.jkiss.dbeaver.model
Error
Fri Apr 16 14:54:23 MSK 2021
org.antlr.v4.runtime.InputMismatchException

org.antlr.v4.runtime.InputMismatchException
	at com.facebook.presto.sql.parser.SqlParser$2.recoverInline(SqlParser.java:133)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2095)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:243)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:97)
	at com.facebook.presto.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:342)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)
	at com.facebook.presto.$gen.Presto_0_229_d7f1fc5____20210416_093258_1.run(Unknown Source)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
Index:
```
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -clearPersistedState
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/37529/AppData/Roaming/DBeaverData/workspace6/ -clearPersistedState

org.jkiss.dbeaver.model
Error
Fri Apr 16 14:55:22 MSK 2021
org.antlr.v4.runtime.NoViableAltException

org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2028)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1645)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:243)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:97)
	at com.facebook.presto.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:342)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)
	at com.facebook.presto.$gen.Presto_0_229_d7f1fc5____20210416_093258_1.run(Unknown Source)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Column:
```
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -clearPersistedState
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/37529/AppData/Roaming/DBeaverData/workspace6/ -clearPersistedState

org.jkiss.dbeaver.model
Error
Fri Apr 16 14:57:37 MSK 2021
org.antlr.v4.runtime.InputMismatchException

org.antlr.v4.runtime.InputMismatchException
	at com.facebook.presto.sql.parser.SqlParser$2.recoverInline(SqlParser.java:133)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2095)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:243)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:97)
	at com.facebook.presto.execution.QueryPreparer.prepareQuery(QueryPreparer.java:56)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:342)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)
	at com.facebook.presto.$gen.Presto_0_229_d7f1fc5____20210416_093258_1.run(Unknown Source)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ShadelessFox** [comment]
Fixed DDL for creating columns, but FKs and PKs are not supported, so they are no longer modifiable.

**Comment by uslss** [comment]
verified
