### ISSUE TITLE
Import from CSV fails due to error

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12119]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.0.3 EA

#### Connection specification:
- Database name and version PrestoDB
- Driver name PrestoSQL - Presto JDBC 350, PrestoDB - PrestoJDBC 0.250

#### Describe the problem you're observing:
Error appears when trying to import [csv file](https://github.com/dbeaver/dbeaver/files/6325086/actor_1_202103181132.csv.txt)
to postgresql.public to non-existing table

```
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Apr 16 15:36:21 MSK 2021
Object parameter [ANGELA] binding not supported

org.jkiss.dbeaver.model.exec.DBCException: Object parameter [ANGELA] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$1.bindStatement(JDBCTable.java:392)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:164)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:327)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:297)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:259)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:135)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by serge-rider** [comment]
Presto may not support data edit for certain engines.
Generally it is no a DBeaver bug.
