### ISSUE TITLE
[Vertica] columns can not be created via UI

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#12144]
DBeaver 21.0.3

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetBoolean(JDBCUtils.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetBoolean(JDBCUtils.java:254)
	at org.jkiss.dbeaver.ext.vertica.model.VerticaMetaModel.createTableColumnImpl(VerticaMetaModel.java:119)
	at org.jkiss.dbeaver.ext.generic.edit.GenericTableColumnManager.createDatabaseObject(GenericTableColumnManager.java:63)
	at org.jkiss.dbeaver.ext.generic.edit.GenericTableColumnManager.createDatabaseObject(GenericTableColumnManager.java:1)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:88)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:318)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Steps:
1. Create new table or choose persisted one
2. Choose "Create column" in table viewer
3. Error occurs

**Comment by LonwoLonwo** [comment]
Fixed. Now you can create columns via UI in Vertica again.

**Comment by uslss** [comment]
verified
