### ISSUE TITLE
IP-Address Gets Translated to Hostname

### ISSUE THREAD

**Issue by vermgit** [dbeaver/dbeaver#12203]
#### System information: 
- Windows 7
- DBeaver version 21.0.2

#### Connection specification:
- Oracle-driver 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
I [asked this on stackoverflow](https://stackoverflow.com/q/67057935/483113), but maybe this is more a bug than something I could fix. For your convenience I copy the question from there:

For some weird reason DBeaver 21.0.2 with Oracle-driver 12.2.0.1 seems to take a configured IP-address as the host, turn it into a hostname and then use that hostname for further usage to connect to the database.

That clearly is undesired as I access that database from an external workplace and with all the additional networking going on the IP-address clearly would be the way to go for me.

To make this even weirder, that resolution seems to take place _after_ the connection was established. I mean I had a typo in the service name at one point and I got an ORA-12514 instead. As soon as I fixed that typo I got back to the hostname resolution problem, which has no ORA-number. So this might be something in DBeaver then.

#### Steps to reproduce, if exist:
Uhh, tough one probably. I use the base configuration tab, an IP-address as the host and somewhere between the server and my computer something translates the IP-address to a hostname. That's definitely not me as the hostname may change as I try to make it work in DBeaver.

#### Include any warning/errors/backtraces from the logs
```
java.net.UnknownHostException: myunknowndbhost.sjngm.com
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:126)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:161)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:521)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:660)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:639)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:189)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:150)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:84)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:896)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kseniiaguzeeva** [comment]
As I see it is not on DBeaver side. I convert the ticket to Discussions. Maybe other users can advise something.
