### ISSUE TITLE
Active catalog/schema NOT working as expected.

### ISSUE THREAD

**Issue by techlock77** [dbeaver/dbeaver#12354]
System information: 
- Operating system (distribution) and version - WIN 10
- DBeaver version - 21.0.3
- Additional extensions

Connection specification:
Database name and version- Netezza

The problem:
When catalog/schema is switched to any catalog other than default catalog in connection settings. Dbeaver is till taking the default catalog/schema, instead of picking the changed catalog/schema.

Steps to reproduce:
Connect to any database.
Open an editor.
On the same screen, switch the active catalog to something else.
Run a query and it still picksup the same catalog/schema that is in the connection details.
But, in ideal scenario, the newly changed schema should be used while running the query.

![image](https://user-images.githubusercontent.com/66756251/117081961-01b9ca80-ad0f-11eb-8ed6-f98b5d8e6829.png)

**Comment by LonwoLonwo** [comment]
Hello @techlock77 

Did you use special dialog from above?

![2021-05-19 16_01_07-DBeaver Enterprise 21 0 5 - _TEST 3 1_ Script-118](https://user-images.githubusercontent.com/45152336/118817111-8b46cc00-b8bb-11eb-96df-f870d42cb323.png)

May be, you can make a video of incorrect behaviour? 
I can't reproduce this issue if I change default database with "Choose catalog/schema" dialog (Ctrl+0)
But i can reproduce this behaviour if I change default Database in Object Tree.

**Comment by PENGCHENGLIN007** [comment]
I had the same problem，yesterday it worked well,but today some database can't change schema,and I restart dbeaver,all database can't change schema

**Comment by LonwoLonwo** [comment]
Hello @PENGCHENGLIN007 
What database do you use? And What DBeaver version do you use?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.

**Comment by PENGCHENGLIN007** [comment]
> Hello @PENGCHENGLIN007
> What database do you use? And What DBeaver version do you use?

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

**Comment by PENGCHENGLIN007** [comment]
> Hello @PENGCHENGLIN007
> What database do you use? And What DBeaver version do you use?

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
DBeaver21.0.3.202104181339

**Comment by LonwoLonwo** [comment]
Hello @PENGCHENGLIN007 
We have many updates from version 21.0.3
Can you please test new DBeavers versions? 
https://dbeaver.io/

**Comment by PENGCHENGLIN007** [comment]
> Hello @PENGCHENGLIN007
> We have many updates from version 21.0.3
> Can you please test new DBeavers versions?
> https://dbeaver.io/

OK,I will try it.

**Comment by PENGCHENGLIN007** [comment]
!ENTRY org.jkiss.dbeaver.model 2 0 2021-10-21 14:21:59.856
!MESSAGE Error while initializing context state
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2021-10-21 14:21:59.856
!MESSAGE Active schema can't be changed for this kind of datasource!
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Active schema can't be changed for this kind of datasource!
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:311)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.refreshDefaults(GenericExecutionContext.java:331)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:201)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:896)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
