### ISSUE TITLE
Error refreshing Exasol node

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#12379]
#### System information: 
- Operating system (distribution) and version: Windows 10 / Debian Buster (4.19.0-16-amd64)
- DBeaver version: 21.0.4
- Additional extensions: -

#### Connection specification:
- Database name and version: Exasol (EXASolution 6.2.7)
- Driver name: EXASolution JDBC Driver 7.0.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: -

#### Describe the problem you're observing:

In prior versions, all nodes of a connection to Exasol (connections, schemas, tables, etc.) in Dbeaver could be refreshed. This is no longer the case. Trying a right click -> refresh results in the exception below. This issue does not occur when refreshing another type of database (e.g. MariaDb). Tried to fix it by enabling Keepalive but to no avail - also in DBeaver releases before the major version bump this wasn't an issue.

`2021-05-07 10:38:44.166 - 
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.exasol.model.ExasolDataSource.refreshObject(ExasolDataSource.java:472)
	at org.jkiss.dbeaver.ext.exasol.model.ExasolSchema.refreshObject(ExasolSchema.java:279)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:340)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:338)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

#### Steps to reproduce, if exist:

Create a connection to an Exasol server and try to refresh any of the server's nodes in the Database Navigator.

Thanks for looking into this!

**Comment by JoepvandenHoven-Bluemine** [comment]
To reproduce the user must not have "SELECT ANY DICTIONARY" rights.

**Comment by JoepvandenHoven-Bluemine** [comment]
Likely culprit is commit d63b3510d67e943c8e0dbf045ce43299684f41cd which removed the nullchecks for baseTableGrantCache (which is only initialized when user has "SELECT ANY DICTIONARY" rights).

**Comment by LonwoLonwo** [comment]
On any schema refresh 

```
!ENTRY org.eclipse.jface 4 2 2021-05-25 13:33:19.143
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.exasol.model.ExasolTableColumn.getTypeName(ExasolTableColumn.java:123)
	at org.jkiss.dbeaver.model.DBValueFormatting.getDefaultTypeImage(DBValueFormatting.java:82)
	at org.jkiss.dbeaver.model.DBValueFormatting.getTypeImage(DBValueFormatting.java:77)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCAttribute.getObjectImage(JDBCAttribute.java:51)
	at org.jkiss.dbeaver.model.DBValueFormatting.getObjectImage(DBValueFormatting.java:141)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getNodeIcon(DBNDatabaseNode.java:170)
	at org.jkiss.dbeaver.model.navigator.DBNNode.getNodeIconDefault(DBNNode.java:118)
	at org.jkiss.dbeaver.ui.navigator.itemlist.NodeListControl.getObjectImage(NodeListControl.java:280)
	at org.jkiss.dbeaver.ui.navigator.itemlist.NodeListControl.getObjectImage(NodeListControl.java:1)
```

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
