### ISSUE TITLE
Unable to update data with inline editor: getUpdateRowCount error message

### ISSUE THREAD

**Issue by stophe72** [dbeaver/dbeaver#12377]
#### System information: 
- Operating system (distribution) and version : Windows7, Archlinux
- DBeaver version 2021.0.4, 2021.0.5
- Java version WIndows : 11, Archlinux OpenJDK 11
- Additional extensions Darkest Dark

#### Connection specification:
- Database name and version:  MariaDb 15.1, MySql 8, Informix 12.70
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
After change value with inline editor, get 'int org.jkiss.dbeaver.model.exec.DBCStatement.getUpdateRowCount()' error on Save button lick
#### Steps to reproduce, if exist:
Double-click on a value (inline editor), change the value and click on then Save button: Popup with 'int org.jkiss.dbeaver.model.exec.DBCStatement.getUpdateRowCount()' message

#### Include any warning/errors/backtraces from the logs
Message :
'int org.jkiss.dbeaver.model.exec.DBCStatement.getUpdateRowCount()'

Exception Stack Trace:
java.lang.NoSuchMethodError: 'int org.jkiss.dbeaver.model.exec.DBCStatement.getUpdateRowCount()'
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:175)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:811)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:697)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:634)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Session Data:
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Command-line arguments:  -os linux -ws gtk -arch x86_64

**Comment by panla** [comment]
## same error

### System information:

- DBeaver: 21.0.4
- OS: CentOS 8
- Java: Oracle 1.11.9

```text
update or insert data in the select query results

if update or insert data, need to choose not to modify the data after the error
```

**Comment by uslss** [comment]
unfortunately, cannot reproduce it.

@stophe72 @panla probably, you can provide a video with an issue? thanks in advance

**Comment by stophe72** [comment]
When using pre-compiled binary 21.0.4 on fedora (34) or windows (7), it's working normally (no error popup).
Problem occurs with using compiled version with "mvn package".

**Comment by ShadelessFox** [comment]
Cannot reproduce when building with `mvn package`. Try running `mvn clean package` instead.

**Comment by panla** [comment]
now, it is ok.

> @uslss @ShadelessFox

- branch: devel
- commit `fe6d20e27e`
- `mvn clean package`

**Comment by panla** [comment]
- tag 21.0.4
- commit 7b4885389f
- `mvn clean package`

it is ok

**Comment by stophe72** [comment]
ok with "mvn clean package"

Thank's
