### ISSUE TITLE
SSH Algorithm negotiation fail

### ISSUE THREAD

**Issue by DevDorrejo** [dbeaver/dbeaver#12386]
#### System information: 
- OpenSUSe Tumbleweed (Latest Snapshot)
- DBeaver version:  21.0.4.202105021514
- Additional extensions: None

#### Connection specification:
- Database name and version: MariaDB 10.5.9
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:

Hello, i did a setting to strengthening the ssh service on the server which is the next:
```

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr 

KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256

MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256

HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com

PermitRootLogin no
StrictModes yes
MaxAuthTries 3

AuthorizedKeysFile          .ssh/authorized_keys

X11Forwarding no
PermitEmptyPasswords no

ClientAliveInterval 30
ClientAliveCountMax 6 
```

when i tried to setup the connection to a mariadb, using ssh tunnel will give me the next message
![image](https://user-images.githubusercontent.com/7697566/117551248-e69ed180-b012-11eb-906e-d428fb01b3c2.png)

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-08 15:35:15.293
!MESSAGE Cannot establish tunnel
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-08 15:35:15.293
!MESSAGE Cannot establish tunnel
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-05-08 15:35:15.293
!MESSAGE Algorithm negotiation fail
!STACK 0
com.jcraft.jsch.JSchException: Algorithm negotiation fail
        at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
        at com.jcraft.jsch.Session.connect(Session.java:320)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:93)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:885)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
Thank you for the report. Have you tried SSHJ implementation for this connection? It is not included by default so for it to work you need to download [SSHJ Extension](https://marketplace.eclipse.org/content/dbeaver-sshj-support) for DBeaver.

**Comment by DevDorrejo** [comment]
> Thank you for the report. Have you tried SSHJ implementation for this connection? It is not included by default so for it to work you need to download [SSHJ Extension](https://marketplace.eclipse.org/content/dbeaver-sshj-support) for DBeaver.

Thanks i install the extension, but how do i use?

still the same error:
![image](https://user-images.githubusercontent.com/7697566/119023583-1b464d80-b970-11eb-95af-a8f179bc5994.png)

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-20 13:35:10.528
!MESSAGE Cannot establish tunnel
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-20 13:35:10.528
!MESSAGE Cannot establish tunnel
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-05-20 13:35:10.528
!MESSAGE Algorithm negotiation fail
!STACK 0
com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
	at com.jcraft.jsch.Session.connect(Session.java:320)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:93)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:141)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:890)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
To use SSHJ instead of JSch you need to change it in SSH settings
![1](https://user-images.githubusercontent.com/82543000/119025410-c543cb00-b9ac-11eb-8c02-6eae77424519.png)

**Comment by DevDorrejo** [comment]
> To use SSHJ instead of JSch you need to change it in SSH settings
> ![1](https://user-images.githubusercontent.com/82543000/119025410-c543cb00-b9ac-11eb-8c02-6eae77424519.png)

Thank you!!!, Finally can stop doing everything from console XD!!>

thank you very much for the help.

If would be a good idea change the default to SSHJ.
