### ISSUE TITLE
very long "Load DB2TableCache" during query execution

### ISSUE THREAD

**Issue by franciskittu** [dbeaver/dbeaver#12425]
#### System information: 
- MS Windows 10
- DBeaver 21.0.4 (but also in earlier version)
- Additional extensions: no

#### Connection specification:
- Database name and version -> DB2 LUW v11.1
- Driver name -> com.ibm.db2.jcc.DB2Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? I'm working under a CISCO VPN and the db2 servers are available there.

#### Describe the problem you're observing:
Every time I connect to a DB2 DB and submit queries DBeaver remain for a very long time to the status "Load DB2TableCache". Often, it will never exit from this status until I click to the cancel button. After that, it shows the query results. A "workaround" for this is to use always the uncommitted read isolation level, but that doesn't always address the problems.
After some time of working on the DB, the problem "disappear". It seems like DBeaver needs to load metadata from the connected DB before working properly. However, everytime I click on the cancel button when in "Load DB2TableCache" it always shows immediately the results set, as if it already had it available underneath. Furthermore, when this occur it is not possible to use the Generate SQL feature after.

#### Steps to reproduce, if exist:
Connect to a DB2 DB.
Submit a simple query like select * from <schemaname>.<tablename> (with any number of records to fetch).

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-12 09:08:18.703
!MESSAGE Operation failed. Retry count remains = 1
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-12 09:08:18.704
!MESSAGE SQL Error [08003]: [jcc][t4][10335][10366][4.26.14] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-05-12 09:08:18.704
!MESSAGE [jcc][t4][10335][10366][4.26.14] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
!STACK 0
com.ibm.db2.jcc.am.SqlNonTransientConnectionException: [jcc][t4][10335][10366][4.26.14] Invalid operation: Connection is closed. ERRORCODE=-4470, SQLSTATE=08003
	at com.ibm.db2.jcc.am.b7.a(b7.java:800)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:133)
	at com.ibm.db2.jcc.am.Connection.checkForClosedConnection(Connection.java:6163)
	at com.ibm.db2.jcc.am.Connection.nativeSQLX(Connection.java:1155)
	at com.ibm.db2.jcc.am.Connection.escape(Connection.java:9058)
	at com.ibm.db2.jcc.am.Connection.prepareStatementX(Connection.java:2438)
	at com.ibm.db2.jcc.am.Connection.prepareStatement(Connection.java:1005)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2AliasCache.prepareObjectsStatement(DB2AliasCache.java:92)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2AliasCache.prepareObjectsStatement(DB2AliasCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.db2.model.DB2Schema.getChildren(DB2Schema.java:275)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:952)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:766)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:278)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:98)
		at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:82)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-12 09:13:49.273
!MESSAGE SQL Error: [jcc][t4][10120][10898][4.26.14] Invalid operation: result set is closed. ERRORCODE=-4470, SQLSTATE=null
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-12 09:13:49.273
!MESSAGE [jcc][t4][10120][10898][4.26.14] Invalid operation: result set is closed. ERRORCODE=-4470, SQLSTATE=null
!STACK 0
com.ibm.db2.jcc.am.SqlException: [jcc][t4][10120][10898][4.26.14] Invalid operation: result set is closed. ERRORCODE=-4470, SQLSTATE=null
	at com.ibm.db2.jcc.am.b7.a(b7.java:794)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:116)
	at com.ibm.db2.jcc.am.ResultSet.checkForClosedResultSet(ResultSet.java:4773)
	at com.ibm.db2.jcc.am.ResultSet.nextX(ResultSet.java:399)
	at com.ibm.db2.jcc.am.ResultSet.next(ResultSet.java:378)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:112)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.db2.model.DB2Schema.getChildren(DB2Schema.java:275)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:952)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:774)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:278)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:98)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:82)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Matvey16** [comment]
Thank you for the report. It didn't reproduce on my DB2 database. Does it happen with every table in every schema or with specific tables?

**Comment by franciskittu** [comment]
Thank you for your reply, it happens with every table and schema, including
syscat ones.

Il Ven 21 Mag 2021, 09:43 Matvey16 ***@***.***> ha scritto:

**Comment by kseniiaguzeeva** [comment]
Please  try to disable **Show system objects** and **Show statistic info** in the connection view
![Screenshot 2021-05-26 at 14 35 44](https://user-images.githubusercontent.com/51405061/119653292-d4ed6480-be2f-11eb-9668-cb4cefbac092.png)
Then you can try to disable these option in the connection properties
![Screenshot 2021-05-26 at 14 34 54](https://user-images.githubusercontent.com/51405061/119653349-e6cf0780-be2f-11eb-97ac-ca1b9904eec5.png)

It would be great to know, what queries are displayed in Query manager (you should enable all query types for this).
![119644806-fcd7ca80-be25-11eb-94ab-a9a47073747f](https://user-images.githubusercontent.com/51405061/119653719-52b17000-be30-11eb-8e9f-fd0e7785fd38.png)

Then double-click a query to see it completely.
![2](https://user-images.githubusercontent.com/51405061/119653742-5cd36e80-be30-11eb-8b18-47881ded492f.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
