### ISSUE TITLE
Saved BLOB data isn't shown in Value panel

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12463]
#### System information, DBs: 
Windows 10, Dbeaver EE 21.0.5. derby server 

#### Describe the problem you're observing:
After saving data after editing BLOB value and open-close "Value" tab the value disappear. Refreshing, reopen DBeaver isn't helps.
In DB2 was the same problem, but I cant reproduce it
#### Steps to reproduce:
Create table with BLOB type column, add new row, press enter to open Value editor and type hex value. Save new row , close Value tab, enter on created BLOB value - then Value tab with empty content will open, but in Data editor in cell I can see "[BLOB]" label talking about the fact that there is already something there. if you try to overwrite the value now in BLOB view (because of typing in Text view no text is entered at all and no errors appear), then these errors will be thrown:
"Event loop exception"
and 
"java.lang.IllegalArgumentException: Index out of bounds"

full stack trace: 
```
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4870)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.custom.StyledText.getLineHeight(StyledText.java:4123)
	at org.eclipse.swt.custom.StyledText.setCaretLocation(StyledText.java:8721)
	at org.eclipse.swt.custom.StyledText.setCaretLocation(StyledText.java:8709)
	at org.eclipse.swt.custom.StyledText.showCaret(StyledText.java:10816)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7440)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8308)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2512)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6075)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6106)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5795)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1094)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1519)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4882)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4760)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:258)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

```

**Comment by ShadelessFox** [comment]
Note: to view BLOBs in Derby you need to switch to manual commit mode.

**Comment by Matvey16** [comment]
Verified
