### ISSUE TITLE
Lost connection inconvience - postgres

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#12559]
Hi! I'm using dbeaver for year or two and some bug constantly remains - if the connection is lost (even if "for now" it was refsreshed and "good") and we have some (many) windows open, the behaviour is as follows:

1. I try to run script in the old windows;
2. A number of "reconnecting" windows appears (and reconnect finished happily);
3. But whe windows says: "connection was closed".

The only thing helps - copy script to clipboard, then instantly open new windows (ctrl+]), then paste and run. It works perfectly.

**Comment by Matvey16** [comment]
Please clarify some things so we could look deeper into it.
1. What Database are you using? Postgres? 
2. What version of DBeaver are you using (You can click `Help -> About` to look for it)
3. What is disconnecting from the internet? PC with DBeaver or Database server?
4. What script are you executing before encountering this problem?

**Comment by plotn** [comment]
1. Postges :) as written in title (version 12, 13)
2. Always maximally fresh
3. Database (vpn swithces off, so db become unreachable)
4. It doesnt matter (select).

**Comment by Matvey16** [comment]
Please attach logs that are presented after you encounter this problem.
I tried to reproduce it and while the initial run of the script was not possible after loosing connection. Clicking invalidate/reconnect button fixed it, and I was able to run this script in the same window.

**Comment by plotn** [comment]
[copy.log](https://github.com/dbeaver/dbeaver/files/6661990/copy.log)
here the log

**Comment by uslss** [comment]
there is no update on the issue for a long time. if it is still actual - feel free to reopen it

**Comment by plotn** [comment]
@uslss, why did you close the issue? I gave all that you asked from me, problem is still exists, whats wrong?

**Comment by Matvey16** [comment]
@plotn Hello, I was reviewing this issue, and the error `This connection has been closed` can be constantly reproduced, but I need to know if you have tried to use Invalidate/reconnect button. Also useful would be to know your connection specifications. Do you use SSH tunnel, proxy, SSL?

**Comment by plotn** [comment]
@Matvey16 , got this again. Version: 21.2.2.202110030714
Steps:
1. Run query in sql editor. Result: SQL Error [08003]: Соединение уже было закрыто
2. Refresh connection (right click in tree, select "Refresh"
3. Run query again. Same result.
4. Open new tab (Ctrl + ]). Run query inside it. All ok.

No tunnels, no ssh, direct connection (via enterprise VPN).

**Comment by Matvey16** [comment]
@plotn I see. The refresh button is used to read the metadata of the database if it was changed (for example DDL was executed in SQL editor). The button you are looking for is `Invalidate/reconnect` or in russian version `Проверить соединение`. It is used to invalidate reconnection after network changes or session close.

![3cywczqyQE](https://user-images.githubusercontent.com/82543000/141734715-fd614cb7-2b5c-4133-951a-d5a36d4c7f7b.png)

**Comment by plotn** [comment]
Ok, I'll check it. But the situation is still incorrect - the "orphaned" windows tries to reconnect, successfully reconnect, but cannot run query saing "the connection was closed"

**Comment by plotn** [comment]
The situation happened.
I press "Invalidate/reconnect" - message appears "Datasource was invalidated"
I go to problem window, run sql. "Datasource was invalidated" blinking 6 times, then "Connection was closed" written.

"Сведения >>" says:
org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error [08003]: Соединение уже было закрыто
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:197)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:1303)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1271)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:489)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:146)
	... 15 more

"Панель журнала ошибок" says (multiple times these two lines):
Operation failed. Retry count remains = 1
SQL Error [09003]: Соединение уже было закрыто

**Comment by Destrolaric** [comment]
@plotn, Hi, can you tell me more details about your VPN, does it have firewall or proxy? I tried to reproduce this issue with multiple VPN setups and it worked correctly.

**Comment by plotn** [comment]
Hi! Did logs help or not? I use Check Point mobile software

**Comment by Destrolaric** [comment]
In logs, there is information that the connection was spoiled. But it's hard to determine why it couldn't reconnect.

**Comment by Destrolaric** [comment]
@plotn Problem may be related to the proxy. Does your VPN has a proxy server configured?

**Comment by flambchap** [comment]
I think this issue is PG-specific and related to its unique connection handling.

**Comment by flambchap** [comment]
> @plotn Problem may be related to the proxy. Does your VPN has a proxy server configured?

I've discussed it privately. They do not use proxy nor PGBouncer.

**Comment by Matvey16** [comment]
Found a way to reproduce this consistently. To reproduce it
1. Generate a DDL for any table (it will be generated correctly)
2. Diconnect from VPN or disrupt you connection in any other way
3. Reconnect it
4. Generate a DDL for this table again

This will lead to errors, even though the DDL can still be generated correctly. The errors would be recorded to log until the connection is disconnected/reconnected or invalidated through UI

**Comment by E1izabeth** [comment]
@plotn, Is it reproducible on the latest DBeaver version?

**Comment by arhayka** [comment]
The only problem we can reproduce now is an error that the user sees, even though it shouldn't be shown to him. We want to remove this error.
Steps to reproduce: https://github.com/dbeaver/dbeaver/issues/12559#issuecomment-1441661558
