### ISSUE TITLE
Check for update does not recognise new versions

### ISSUE THREAD

**Issue by mwalter** [dbeaver/dbeaver#12556]
#### System information: 
- Windows 10
- DBeaver version 21.0.0.202103021012

#### Describe the problem you're observing:
If I check for updates I always get the information that there are no new updates.
![DBeaver Check for updates](https://i.ibb.co/NSsy6Vs/DBeaver-Update-Dialog.png)

If I use the Install new software command from the main menu DBeaver recognizes that there is a new version but it is unable to install the new version.
![DBeaver Install new software](https://i.ibb.co/pXjs3VG/DBeaver-Install-New-Software.png)

There are no entries in the error log.

#### Steps to reproduce, if exist:
Open DBeaver. Check for updates.

**Comment by kseniiaguzeeva** [comment]
As I see you use standalone DBeaver and I cannot reproduce it. Could you please use this way to check for updates:

![dbeaver_7ReUNJ3Ifb](https://user-images.githubusercontent.com/51405061/120615237-be16c580-c460-11eb-9cb5-1fbfabb4a2f7.png)

If the issue still persists, please send me [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files). It will help us to provide you with a solution to your issue.

**Comment by mwalter** [comment]
Hmm... seems to be a company firewall issue:

`
2021-06-10 14:22:27.330 - java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:102)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:47)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:42)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:53)
	at org.jkiss.dbeaver.ui.app.standalone.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:102)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

**Comment by kseniiaguzeeva** [comment]
Could you please confirm your suggestion with your system administrator?
Thank you in advance.

**Comment by mwalter** [comment]
Okay, I managed to configure our proxy in the DBeaver settings. But I still get the same error. No updates and if I choose to update manually, I get "Cannot perform update because of a conflicting dependency. Only one of the following can be installed at once." (See screenshot above). Why?

**Comment by uslss** [comment]
@mwalter standalone dbeaver cannot be updated this way.
You should download updated version [here](https://dbeaver.io/download/) manually, 
Another way is - Main menu:Help - Check for Updates - Update dialog opens(pic attached) - If new version is available, click Upgrade button
![image](https://user-images.githubusercontent.com/31996417/123620339-c8836f80-d812-11eb-838d-1f51960e8e8b.png)
