### ISSUE TITLE
Dont open DBF file

### ISSUE THREAD

**Issue by MaximKutovoy** [dbeaver/dbeaver#12588]
Error on open DBF file:

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Syntax error: DANS DBF Library error: java.lang.reflect.InvocationTargetException
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:188)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4577)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Syntax error: DANS DBF Library error: java.lang.reflect.InvocationTargetException
	at org.relique.jdbc.csv.CsvStatement.execute(CsvStatement.java:625)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 7 more

[KVSSCH.zip](https://github.com/dbeaver/dbeaver/files/6538915/KVSSCH.zip)

**Comment by ShadelessFox** [comment]
Hello @MaximKutovoy,

Please provide more information: what database are you using, what are you trying to do?

**Comment by MaximKutovoy** [comment]
![image](https://user-images.githubusercontent.com/57235732/119503088-44514e80-bd73-11eb-96d4-763cd3fb9f2f.png)


Some files open, some files don't. The one that doesn't open, I attached in the previous message.

**Comment by ShadelessFox** [comment]
I see, thanks. I was able to reproduce your issue. Unfortunately, I can't suggest any solution right now.

**Comment by ShadelessFox** [comment]
Update:

It actually says that the specified .dbf file is corrupted or invalid. Can you try loading another file?

**Comment by MaximKutovoy** [comment]
[DOM1.zip](https://github.com/dbeaver/dbeaver/files/6540299/DOM1.zip)


Here is another file. I opened it in another program. http://joxi.ru/BA085aMCvP5LPA

**Comment by ShadelessFox** [comment]
Thanks, but unfortunately this one fails too. We'll try to resolve the problem in the future.

**Comment by MaximKutovoy** [comment]
[TARIFS.zip](https://github.com/dbeaver/dbeaver/files/6540639/TARIFS.zip)

This file open good

**Comment by ShadelessFox** [comment]
Actually, it depends on the file's version. This one's probably supported, but previous don't.

**Comment by MaximKutovoy** [comment]
Close issue?

**Comment by ShadelessFox** [comment]
No, keep it opened for now.

**Comment by CarlossDMC** [comment]
In the latest version, I have the same problem when I try to open a .dbf file. ):

![image](https://github.com/dbeaver/dbeaver/assets/83795819/b6f07895-5b34-4379-b9a1-9224d2c1eb48)
