### ISSUE TITLE
PostgreSQL 13 backup function error (DBeaver 21.0.5)

### ISSUE THREAD

**Issue by cleeh** [dbeaver/dbeaver#12582]
We have used postgreSQL 13 backup function in DBeaver but, error occured From April.

Error log is like this.
```
Task 'PostgreSQL dump' started at Tue May 25 15:12:44 KST 2021
pg_dump: error: server version: 13.2 (Ubuntu 13.2-1.pgdg18.04+1); pg_dump version: 12.2

pg_dump: error: aborting because of server version mismatch

Task 'PostgreSQL dump' finished at Tue May 25 15:12:44 KST 2021
2021-05-25 15:12:44.305 - IO error: Process failed (exit code = 1). See error log.
2021-05-25 15:12:44.305 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

My environment is as follows.
  - DBeaver: 21.0.5
  - DBeaver Executing OS: Windows 10 Enterprise 19042.985 (x64)
  - DB Server OS: Linux tms-web 4.15.0-143-generic (Ubuntu 18.04 LTS)

**Comment by LonwoLonwo** [comment]
Connected with https://github.com/dbeaver/dbeaver/issues/8069

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by QuanTran91** [comment]
Are there any work around on it?

**Comment by LonwoLonwo** [comment]
> Workaround: specify local native PG client compatible with your server version. You can do this in connection settings.

**Comment by serge-rider** [comment]
Native tools version upgraded to 13.3

**Comment by Matvey16** [comment]
Verified

**Comment by pablofuenzalidadf** [comment]
How do I upgrade to those native tools?
I upgraded DBeaver to last version (21.1.3) but upgrading driver/libraries still gets me version 12.2 instead of 13.3.
Thank you in advance. 
Sorry for newbie question.

Working on windows 10 pro 19042.1110 (x64)

**Comment by LonwoLonwo** [comment]
Hello @pablofuenzalidadf 
This improvement will be available in Dbeaver 21.1.4 on 2021-08-02 [here](https://dbeaver.io). You can see it in the "Milestone" section of this page.

**Comment by victorcarvalhosp** [comment]
I installed DBeaver version Version 21.3.4.202202061313 and then I start to see this same error whenever I try to create a backup. Someone can explain how to make this work?

I have version 21.2.0.202 running in another computer and it works fine

**Comment by LonwoLonwo** [comment]
Hello @victorcarvalhosp 

What PostgreSQL version do you use?
What error exactly do you have? Can you provide more info?

Also, you can find a native client list in your connection setting. 

![2022-02-11 00_48_40-Connect to a database](https://user-images.githubusercontent.com/45152336/153502515-2758ed13-eea9-4a94-808b-0a2755c9388d.png)

I hope it can help you.

**Comment by victorcarvalhosp** [comment]
Hi @LonwoLonwo first of all thanks for answering so quickly! 
On this Local Client option, I just have one option: "PostgreSQL Binaries". How can I add these other options? If I click on "Browse..." all I can see is this:
![image](https://user-images.githubusercontent.com/4266657/153509645-7e66be99-9b7b-4d87-ab9e-63e88d4e3eb3.png)

I'm using PostgreSQL 12.9 and the error I get is the same from the initial message:

```
C:\Users\victo\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\13\pg_dump.exe --verbose --host=localhost --port=5432 ****** --format=c --encoding=UTF-8 --inserts --file C:\Users\victo\Downloads\dump-streamline-test-202202101949 -n "public" streamline-test
Task 'PostgreSQL dump' started at Thu Feb 10 19:49:22 BRT 2022
Task 'PostgreSQL dump' finished at Thu Feb 10 19:49:22 BRT 2022
2022-02-10 19:49:22.345 - IO error: Process failed (exit code = -1073741515). See error log.
2022-02-10 19:49:22.346 - java.io.IOException: Process failed (exit code = -1073741515). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:233)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:213)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:273)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:78)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by victorcarvalhosp** [comment]
If I try to restore a backup I get the same error too(The same backup works on my other laptop with version 21.2.0.202)

```
C:\Users\victo\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\13\pg_restore.exe --verbose --host=localhost --port=5432 ****** --clean --format=c --dbname=streamline-staging-copy C:\Users\victo\Downloads\dump-staging-february-11
Task 'PostgreSQL restore' started at Fri Feb 11 17:04:38 BRT 2022
Task 'PostgreSQL restore' finished at Fri Feb 11 17:04:38 BRT 2022
2022-02-11 17:04:38.646 - IO error: Process failed (exit code = -1073741515). See error log.
2022-02-11 17:04:38.646 - java.io.IOException: Process failed (exit code = -1073741515). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:233)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseRestoreHandler.validateErrorCode(PostgreDatabaseRestoreHandler.java:141)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:213)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:273)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:78)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by victorcarvalhosp** [comment]
In my case the entire `C:\Users\victo\AppData\Roaming\DBeaverData\` folder was non-existent, I thought this was created automatically in a fresh installation. 
I copied it from my working installation that I had on another computer and pasted it here and then it worked. 
I have no clue why this folder didn't exist though, I'm 100% sure I didn't remove it.

**Comment by LonwoLonwo** [comment]
> and then it worked.

Hello @victorcarvalhosp. So the issue is solved for now?

**Comment by victorcarvalhosp** [comment]
> > and then it worked.
> 
> Hello @victorcarvalhosp. So the issue is solved for now?

Yes, it's working for me after doing this

**Comment by pavlexander** [comment]
I have posted a solution here https://github.com/dbeaver/dbeaver/issues/8069#issuecomment-1086670163

**Comment by swats-the-floran** [comment]
have the same error but hello from the future.
cannot connect to database 14 because pg_dump version is 13

**Comment by LonwoLonwo** [comment]
You can create a feature request ticket about this (update pg_dump) @swats-the-floran 

I hope that pg dump 14 is compatible with the previous PG versions.

**Comment by sryze** [comment]
Getting the same error with PostgreSQL 15. @LonwoLonwo 's solution worked for me.

```
C:\Users\myuser\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14\pg_dump.exe --verbose --host=localhost --port=5432 ****** --format=c --file C:\Users\myuser\Desktop\dump-ertugrulalert-202303231358 -n "public" ertugrulalert
Task 'PostgreSQL dump' started at Thu Mar 23 13:58:50 GMT+06:00 2023
pg_dump: error: server version: 15.1; pg_dump version: 14.2

pg_dump: error: aborting because of server version mismatch

Task 'PostgreSQL dump' finished at Thu Mar 23 13:58:51 GMT+06:00 2023
2023-03-23 13:58:51.114 - IO error: Process failed (exit code = 1). See error log.
2023-03-23 13:58:51.114 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by UsabilitySpace** [comment]
Getting the same error under MacOs: 


Task 'PostgreSQL dump' finished at Tue Jul 09 15:12:51 NOVT 2024
2024-07-09 15:12:51.190 - IO error: Process failed (exit code = 1). See error log.
2024-07-09 15:12:51.190 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

**Comment by romavz** [comment]
Have the same problem after update dBeaver Community. My solution is:

1 - fully Uninstall dBeaver
2 - remove folder %AppData%\Roaming\DBeaverData\drivers
3 - install latest dBeaver Community version
4 - when configuring Postgres db connection drivers manually chose latest versions
