### ISSUE TITLE
Dropped attributes in postgres composite types prevent records from being saved

### ISSUE THREAD

**Issue by another-repo** [dbeaver/dbeaver#12636]
Hi,

When using composite types (postgres), we've noticed that after dropping attributes, any table that uses this composite type is not always editable.

Here's the minimum example we could derive:

```
CREATE SCHEMA test_schema;

CREATE TYPE test_schema.test_enum AS ENUM ('a', 'b', 'c');

CREATE TYPE test_schema.test_composite_type AS (
   field_1 test_schema.test_enum,
   field_2 int4,
   field_to_drop_1 int4,
   field_to_drop_2 int4,
   field_3 int4,
   field_4 int4
);

-- drop two attributes from the above type
alter type test_schema.test_composite_type drop attribute field_to_drop_1;
alter type test_schema.test_composite_type drop attribute field_to_drop_2;

-- create a table which uses this type
CREATE TABLE test_schema.test_table (
   column_1 text NOT NULL,
   column_2 text NULL,
   column_3 test_schema.test_composite_type NULL,
   PRIMARY KEY (column_1)
);

-- set up some test data
insert into test_schema.test_table (values
('v1', null, ('a', 1, 2, 3)),
('v2', null, null)
);
```

After this, the schema needs to be refreshed (F5), or the table refreshed. Or a restart. Then the issue will become apparent.

If a select is then performed in the following way:

```
select * from test_schema.test_table;
```

Then we will get this:

![image](https://user-images.githubusercontent.com/58380228/119902381-6d2a3d00-bf47-11eb-8aab-d8c9b32c9c64.png)

Also, when editing any column in the grid view:

![image](https://user-images.githubusercontent.com/58380228/119902576-b4b0c900-bf47-11eb-994c-dee209d48f4d.png)

However, the following select allows editing (but note: here we _exclude_ the composite type from the query):

```
select column_1, column_2 from test_schema.test_table;
```

For example:

![image](https://user-images.githubusercontent.com/58380228/119902681-e45fd100-bf47-11eb-874c-5d2114bca8db.png)

#### System information: 
Windows 10 Enterprise
10.0.18363 Build 18363
DBeaver Version 7.2.0.202008302047
No extensions

#### Connection specification:
PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3), 64-bit
PostgreSQL JDBC Driver 42.2.17
No tunnels (etc)

#### Logfile snippet:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-27 23:48:28.094
!MESSAGE SQL Error [42846]: ERROR: cannot cast type record to test_schema.test_comp
  Detail: Input has too few columns.
  Position: 58
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-27 23:48:28.094
!MESSAGE SQL Error [42846]: ERROR: cannot cast type record to test_schema.test_comp
  Detail: Input has too few columns.
  Position: 58
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-05-27 23:48:28.094
!MESSAGE ERROR: cannot cast type record to test_schema.test_comp
  Detail: Input has too few columns.
  Position: 58
!STACK 0
org.postgresql.util.PSQLException: ERROR: cannot cast type record to test_schema.test_comp
  Detail: Input has too few columns.
  Position: 58
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:342)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:132)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:505)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:436)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:423)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:804)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3008)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:120)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4425)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by fvannee** [comment]
This reproduces on DBeaver 21.0.5

**Comment by fvannee** [comment]
Reproduces on version 21.1.0 too

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by Matvey16** [comment]
Verified
