### ISSUE TITLE
NPE when trying to open a picture, if any is already open

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12657]
#### System information: 
- Windows 10, DBeaver 21.1.0 CE, Oracle 12

#### Describe the problem you're observing:
If you click on the BLOB by double-clicking, the picture opens, but an NPE appears. The error does not occur when BLOB displayed in text or binary format
#### Steps to reproduce, if exist:
![2021-05-31_10h36_04](https://user-images.githubusercontent.com/43252954/120157954-3f215300-c1fc-11eb-877d-a66c50b99ada.gif)

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/43252954/120157586-db972580-c1fb-11eb-8c06-b76f1c3d4a54.png)

**Comment by ShadelessFox** [comment]
Can you please provide log files?

**Comment by DariaMarkaryan** [comment]
sorry, I forgot to do this
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.data.managers.image.ImagePanelEditor.primeEditorValue(ImagePanelEditor.java:58)
	at org.jkiss.dbeaver.ui.data.managers.image.ImagePanelEditor.primeEditorValue(ImagePanelEditor.java:1)
	at org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor$StreamValueLoadService.evaluate(ContentPanelEditor.java:497)
	at org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor$StreamValueLoadService.evaluate(ContentPanelEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

And еру 2nd error:
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:438)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:357)
	at org.eclipse.swt.widgets.Control.redraw(Control.java:2444)
	at org.jkiss.dbeaver.ui.controls.imageview.ImageViewCanvas.syncScrollBars(ImageViewCanvas.java:185)
	at org.jkiss.dbeaver.ui.controls.imageview.ImageViewCanvas.showOriginal(ImageViewCanvas.java:308)
	at org.jkiss.dbeaver.ui.controls.imageview.ImageViewCanvas.loadImage(ImageViewCanvas.java:255)
	at org.jkiss.dbeaver.ui.controls.imageview.ImageViewer.loadImage(ImageViewer.java:92)
	at org.jkiss.dbeaver.ui.data.managers.image.ImagePanelEditor$1.runTask(ImagePanelEditor.java:56)
	at org.jkiss.dbeaver.ui.data.managers.image.ImagePanelEditor$1.runTask(ImagePanelEditor.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:260)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
