### ISSUE TITLE
TLS 1.0 and TLS 1.1 support

### ISSUE THREAD

**Issue by azmau** [dbeaver/dbeaver#12668]
#### System information: 
- Operating system (distribution) and version:  Windows 10 20H2 (build 19042.985)
- DBeaver version: Community 21.1.0.202105300349
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server 2008 10.50.6000.34
- Driver name: Microsoft JDBC Driver for SQL Server 8.2.0.jre11
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
After upgrading DBeaver to the most recent version, the connection to a SQL Server 2008 DB is no longer working. When I try to connect I get the error message

> The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]

It worked fine in the previous minor release, v21.0.1??? something like this from memory. I usually keep DBeaver up to date to the latest version offered. The latest upgrade works just fine for other connections to SQL Server 2016 for example.

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-05-31 15:44:02.645
!MESSAGE The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-05-31 15:44:02.645
!MESSAGE The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]
!STACK 0
javax.net.ssl.SSLHandshakeException: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1802)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2558)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:69)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:914)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:217)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by sroui** [comment]
I have the same issue after upgrading to the latest release

**Comment by ShadelessFox** [comment]
Hello @azmau @sroui,

I believe that's the result of upgrading the version of bundled JRE to 11.0.11 (#12067).

Starting from this version, support for TLS 1.0/1.1 was disabled by default, as mentioned in the roadmap:
https://java.com/en/jre-jdk-cryptoroadmap.html

You can try using previous JRE versions or refer to this article on how to enable support for TLS 1.0 manually:
https://java.com/en/configure_crypto.html#DisableTLS

Let me know if your problem was solved.

**Comment by sroui** [comment]
Hi @ShadelessFox, Thank you, It worked now.

As you have mentioned,  TLS 1.0/1.1 are disabled by default in the bundled JRE

To fix the problem in my ubuntu machine,  I have modified the file `/usr/share/dbeaver/jre/conf/security/java.security` by deleting the `TLSv1` and `TLSv1.1` from the value of property `jdk.tls.disabledAlgorithms`

**Comment by rubenflorez** [comment]
same problem here (windows 10)..solved using the above solution by editing \jre\conf\security\java.security . Thanks

**Comment by timofas** [comment]
or reinstall DBeaver 21.0.5, free.. Thanks

**Comment by tomboe311** [comment]
Same problem with 21.1.0.202105300349 (installed via snap)

**Comment by ricgavira** [comment]
Eu também removi os protocolos como o @sroui falou ali acima, e funcionou.

Neste arquivo: "C:\Program Files\DBeaver\jre\conf\security\java.security"

![image](https://user-images.githubusercontent.com/11458628/120345210-44e46a80-c2c8-11eb-84b7-6c2480bf7a2a.png)

**Comment by serge-rider** [comment]
We will update java.security in the bundled JDK in the next version to enable TLS1.0/1.1

**Comment by Matvey16** [comment]
Verified

**Comment by azmau** [comment]
Thanks @ShadelessFox and sorry for the late confirmation but indeed the fix works.
Seems like the same solution still applies to Java 16 (https://www.oracle.com/java/technologies/javase/16-relnotes.html#JDK-8202343), if anyone is interested.

**Comment by kafene** [comment]
In my case the file was located at `/usr/share/dbeaver/jre/conf/security/java.security` - removing `TLSv1, TLSv1.1,` from `jdk.tls.disabledAlgorithms` worked.

**Comment by silvestreR** [comment]
In my case the file was located at /etc/java-openjdk/security/java.security - removing TLSv1, TLSv1.1, from jdk.tls.disabledAlgorithms worked.

Distro OS: Manjaro - Pahvo 21.1.1

**Comment by Kokolokoli** [comment]
In my case the file was located at /etc/java11-openjdk/security/java.security. The fix - removing TLSv1 and TLSv1.1 from jdk.tls.disabledAlgorithms -  worked!

DBeaver version: 21.1.5
OS: Arch Linux 5.13.13

**Comment by puvi7722** [comment]
@kafene - Thanks Man. Removing TLSv1, TLSv1.1 from jdk.tls.disabledAlgorithms helped me to fix my issue.

**Comment by dmetzler1988** [comment]
Same issue on MacOS 11.6 with the latest DBeaver Community Edition (Version 21.2.2.202110030714).
Removing `TLSv1` and `TLSv1.1` from property `jdk.tls.disabledAlgorithms` in file `/Applications/DBeaver.app/Contents/Eclipse/jre/Contents/Home/conf/security/java.security` helped me to fix my issue.

**Comment by moonpole** [comment]
I am using snap version of dbeaver-ce.

In version 21.2.2.202110030714 which is the latest one the TLS1.0 and TLS1.1 are disabled by default.
But in previous version 21.2.1.202109181446 they are not disabled.

The corresponding config file is /snap/dbeaver-ce/147/usr/share/dbeaver-ce/jre/conf/security/java.security but it is readonly, I cannot modify it.

**Comment by pfrozi** [comment]
> I am using snap version of dbeaver-ce.
> 
> In version 21.2.2.202110030714 which is the latest one the TLS1.0 and TLS1.1 are disabled by default. But in previous version 21.2.1.202109181446 they are not disabled.
> 
> The corresponding config file is /snap/dbeaver-ce/147/usr/share/dbeaver-ce/jre/conf/security/java.security but it is readonly, I cannot modify it.

Could you try to open the file with "sudo" privileges? This works fine for me.

**Comment by moonpole** [comment]
> > I am using snap version of dbeaver-ce.
> > In version 21.2.2.202110030714 which is the latest one the TLS1.0 and TLS1.1 are disabled by default. But in previous version 21.2.1.202109181446 they are not disabled.
> > The corresponding config file is /snap/dbeaver-ce/147/usr/share/dbeaver-ce/jre/conf/security/java.security but it is readonly, I cannot modify it.
> 
> Could you try to open the file with "sudo" privileges? This works fine for me.

Not works, it seems snap mounted the "package" as readonly fs.

```
df -ah
/dev/loop5      249M  249M     0 100% /snap/dbeaver-ce/147

cat /proc/mounts  | grep -i dbeaver
/dev/loop5 /snap/dbeaver-ce/147 squashfs ro,nodev,relatime 0 0
```

The squashfs is a compressed read-only filesystem for Linux. So I can't edit this file.

**Comment by flambchap** [comment]
`java.security` needs to be updated again for our new version of JRE.

**Comment by Matvey16** [comment]
Verified

**Comment by lucastafarelbs** [comment]
> In my case the file was located at /etc/java-openjdk/security/java.security - removing TLSv1, TLSv1.1, from jdk.tls.disabledAlgorithms worked.
> 
> Distro OS: Manjaro - Pahvo 21.1.1

Saved my life, thanks a lot!

**Comment by fabianMendez** [comment]
The `java.security` file might need to be updated again.

For those using flatpak it's located at `/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/current/active/files/jre/conf/security/java.security`

**Comment by kred-jon** [comment]
> I am using snap version of dbeaver-ce.
> 
> In version 21.2.2.202110030714 which is the latest one the TLS1.0 and TLS1.1 are disabled by default. But in previous version 21.2.1.202109181446 they are not disabled.
> 
> The corresponding config file is /snap/dbeaver-ce/147/usr/share/dbeaver-ce/jre/conf/security/java.security but it is readonly, I cannot modify it.

yes! same experience cannot editing any files in snap version.

**Comment by yajo** [comment]
If you do https://github.com/dbeaver/dbeaver/issues/12668#issuecomment-865327462, you'll lower security of connections for all java applications. There is a better way.

1. [Download this file](https://github.com/dbeaver/dbeaver/issues/12668#issuecomment-865327462).
2. Execute it, to generate a new java security configuration that doesn't disable older TLS protocols: `java OverrideSecurity.java > lower.security`
3. Run DBeaver with `env JAVA_TOOL_OPTIONS=-Djava.security.properties=lower.security dbeaver`
