### ISSUE TITLE
Version 21.1 permissions features errors on Redshift

### ISSUE THREAD

**Issue by mkosater** [dbeaver/dbeaver#12691]
Version 21.1.0.202105300349

Errors are thrown in dbeaver on redshift connection when viewing the details of a object (table, view, schema, database). 

Error:
  java.lang.reflect.InvocationTargetException
    SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
    SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
      [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
      [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;

Error shows when using the 'View Table' (view on any object too) from the Database Navigator. pg_roles is not in the redshift pg_catalog views (there are a few differences as related to permissions).

**Comment by kseniiaguzeeva** [comment]
Could you please provide me with more details:
- what permitions do you have?
- Error logs could be very useful too https://github.com/dbeaver/dbeaver/wiki/Log-files.
I will then be able to assess the situation and be able to better help you.

**Comment by mkosater** [comment]
Permission are superuser.

If you choose 'View Schema' on the public schema. You will see this message over and over as it loops through the objects in the public schema.

root cause is that redshift does not have the pg_role view.

2021-06-01 11:23:00.975 - Error reading property 'owner' from public
org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:228)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:223)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:172)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:363)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	... 9 more
Caused by: org.jkiss.dbeaver.DBException: SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	... 15 more
Caused by: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getParameterDescription(Unknown Source)
	at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.<init>(Unknown Source)
	at com.amazon.redshift.dataengine.PGDataEngine.prepare(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42ObjectFactory.createPreparedStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:940)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:223)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:172)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:363)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	... 39 more
2021-06-01 11:23:01.128 - org.jkiss.dbeaver.DBException
org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:228)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:368)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	... 7 more
Caused by: org.jkiss.dbeaver.DBException: SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	... 13 more
Caused by: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getParameterDescription(Unknown Source)
	at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.<init>(Unknown Source)
	at com.amazon.redshift.dataengine.PGDataEngine.prepare(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42ObjectFactory.createPreparedStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:940)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:368)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	... 37 more
2021-06-01 11:23:01.139 - SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
org.jkiss.dbeaver.DBException: SQL Error [500310] [42P01]: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:368)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getParameterDescription(Unknown Source)
	at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.<init>(Unknown Source)
	at com.amazon.redshift.dataengine.PGDataEngine.prepare(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc42.PGJDBC42ObjectFactory.createPreparedStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:940)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase$RoleCache.prepareObjectsStatement(PostgreDatabase.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:374)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getOwner(PostgreSchema.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:394)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:368)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: relation "pg_catalog.pg_roles" does not exist;
	... 37 more

**Comment by LonwoLonwo** [comment]
Thanks for the bug report!

**Comment by kseniiaguzeeva** [comment]
Fixed and verified. Thank you for your prompt bug report.
We made a hotfix this morning. Could you please download [the latest version ](https://dbeaver.io/download/) again?
