### ISSUE TITLE
mongo db.getCollection() error

### ISSUE THREAD

**Issue by Korov** [dbeaver/dbeaver#12696]
#### System information: 
- Operating system (distribution) and version:`Windows 10`
- DBeaver version: `Version 21.1.0.202106010550`
- Additional extensions

#### Connection specification:
- Database name and version:`Mongo 4.4.6`
- Driver name:`Mongo`
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Include any warning/errors/backtraces from the logs

```
db.getCollection("kafka-key-count").find();

org.jkiss.dbeaver.model.exec.DBCException: TypeError: Cannot find function getCollection in object {aaa={}, kafka-key-count={}, kafka-name-count={}, system.users={}, system.version={}, value-record={}}. (js#1)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:65)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3278)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4589)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot find function getCollection in object {aaa={}, kafka-key-count={}, kafka-name-count={}, system.users={}, system.version={}, value-record={}}. (js#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4280)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4258)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4291)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4310)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4382)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2584)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2566)
	at org.mozilla.javascript.gen.js_2._c_script_0(js:1)
	at org.mozilla.javascript.gen.js_2.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.js_2.call(js)
	at org.mozilla.javascript.gen.js_2.exec(js)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1234)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.runInRhino(MongoJSProcessor.java:115)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.eval(MongoJSProcessor.java:90)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:55)
	... 12 more

```

**Comment by serge-rider** [comment]
We need to add extra MG database commands support.

Workaround: use `db.get("kafka-key-count").find();` syntax.

**Comment by DariaMarkaryan** [comment]
Verified
