### ISSUE TITLE
An error occurs when saving a changes to a line in which there is an XML field 

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#12710]
#### System information: 
- Windows 10, DBeaver CE 21.1.0, PostgreSQL 10

#### Describe the problem you're observing:
Even if the field with XML itself hasn't been changed, when you press **Save** btn an error occurs
#### Steps to reproduce, if exist:
Open a table with XML data -> try to change XML column or other fields -> error
![image](https://user-images.githubusercontent.com/43252954/120509803-814fbd80-c3d1-11eb-8ee3-5e33e6f9dee5.png)

Editing works fine if the table has (virtual) key

#### Include any warning/errors/backtraces from the logsv
```
org.postgresql.util.PSQLException: ERROR: operator does not exist: xml = xml
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 47
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:304)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:172)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:811)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:697)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:634)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by DariaMarkaryan** [comment]
Related to #11704

**Comment by DariaMarkaryan** [comment]
Table creation DDL 
```
CREATE TABLE "XML" (
	"XML" xml NULL,
	column1 timestamp(0) NULL DEFAULT 'infinity'::timestamp without time zone
);
```

**Comment by LonwoLonwo** [comment]
Fixed in the scope of: https://github.com/dbeaver/dbeaver/issues/11704

**Comment by uslss** [comment]
verified
