### ISSUE TITLE
Test connection: Null connection returned : Bad Url

### ISSUE THREAD

**Issue by ranjithkr06** [dbeaver/dbeaver#12716]
I am getting  the error below while doing a Test Connectin to a SAP successfactors database for a url.

org.jkiss.dbeaver.model.exec.DBCException: Null connection returned
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:914)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

---------------------------------------------------------
  !ENTRY org.jkiss.dbeaver.model 4 0 2021-06-03 17:02:00.373
!MESSAGE Bad URL: jdbc:vjdc:servlet: https://abcd-stage.plateau.com/vjdbc/vjdbc,db10g
---------------------------------------------

 Steps to reproduce:
New connection :-->select SAP HANA-> enter the details below 
Host : https://abcd-stage.plateau.com/vjdbc/vjdbc,db10g
Port : 30015
user name and password
 Edit driver properties 
Driver Type : HANA
class name : de.simplicit.vjdbc.VirtualDriverBirtWrapper
URL template : jdbc:vjdc:servlet: {host}
Drivers : birtvjdbcdriver.jar
            : ojdbc6-11.2.0.3.jar

The jar files are from Plateue Report Designer  by BIRT    which is used to modify  sap successfactors reports.

OS  Windows 10 64 bit
DBeaver : CE 21.1.0
 JRE (build 1.8.0_291-b10)
JDK latest
The same connection details works in an  another system where DBeaver 7.3.1 is installed

Really appreciate any help on this.

**Comment by ranjithkr06** [comment]
its working now .the b was missing in the template   jdbc:vjd**b**c:servlet: {host}
