### ISSUE TITLE
Data export: check box for new connections is unlocked when it should not be

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#12733]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.0

#### Describe the problem you're observing:
If an option to export only selected rows/columns is saved from the previous export, the option to open new connections will be unlocked.

#### Steps to reproduce, if exist:
1. Perform an export of select columns.
2. Open an export window for the same target type again.
3. Try to check `Open new connection(s)`

**Expected:** It is locked from editing
**Actual:** Option can be turned on.

![2021-06-04_12h55_32](https://user-images.githubusercontent.com/82543000/120785448-cf7dd180-c535-11eb-825f-fc8d6f7fba28.gif)

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
reopened.
Export isn't possible for now due to error
```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.jkiss.dbeaver.model
Error
Tue Jul 06 19:40:03 MSK 2021
java.lang.NullPointerException
    at org.jkiss.dbeaver.tools.transfer.ui.pages.database.DatabaseProducerPageExtractSettings.enableNewConnectionCheckbox(DatabaseProducerPageExtractSettings.java:176)
    at org.jkiss.dbeaver.tools.transfer.ui.pages.database.DatabaseProducerPageExtractSettings.activatePage(DatabaseProducerPageExtractSettings.java:206)
    at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferPageSettings.createSettingsPages(DataTransferPageSettings.java:92)
    at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferPageSettings.activatePage(DataTransferPageSettings.java:121)
    at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1252)
    at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1222)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1222)
    at org.jkiss.dbeaver.ui.dialogs.ActiveWizardDialog.showPage(ActiveWizardDialog.java:101)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:917)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:468)
    at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:146)
    at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
    at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
    at org.eclipse.jface.window.Window.open(Window.java:799)
    at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.openWizard(DataTransferWizard.java:578)
    at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.openWizard(DataTransferWizard.java:551)
    at org.jkiss.dbeaver.tools.transfer.ui.handlers.DataTransferHandler.execute(DataTransferHandler.java:63)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
    at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

**Comment by flambchap** [comment]
Fixed NPE.

**Comment by Matvey16** [comment]
Verified
