### ISSUE TITLE
unable to start dbeaver 

### ISSUE THREAD

**Issue by wangpeng0824** [dbeaver/dbeaver#12751]
![image](https://user-images.githubusercontent.com/21004513/120954578-0ea06280-c782-11eb-9aa3-f1ebb6852d4f.png)
!SESSION 2021-06-07 10:28:49.767 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product
Command-line arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product -data D:\eclipse-rcp\eclipse-workspace/../runtime-DBeaver.product -dev file:D:/eclipse-rcp/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

This is a continuation of log file D:\eclipse-rcp\runtime-DBeaver.product\.metadata\.bak_0.log
Created Time: 2021-06-07 10:28:56.860

!ENTRY org.jkiss.dbeaver.ext.import_config 4 0 2021-06-07 10:28:56.860
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Error loading bundle activator. org.jkiss.dbeaver.ext.import_config_2.1.110.qualifier [1216]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:757)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1012)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:366)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassNotFoundException: org.jkiss.dbeaver.ext.import_config.Activator cannot be found by org.jkiss.dbeaver.ext.import_config_2.1.110.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:796)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:749)
	... 13 more
Root exception:
java.lang.ClassNotFoundException: org.jkiss.dbeaver.ext.import_config.Activator cannot be found by org.jkiss.dbeaver.ext.import_config_2.1.110.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:796)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:749)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1012)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:366)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by wangpeng0824** [comment]
[error.zip](https://github.com/dbeaver/dbeaver/files/6605643/error.zip)
and this is my attach files，i can build it successfully，but i can not run it，with the debug configurations above， i guess maybe the develop environment have some problems  that i can not found

**Comment by kseniiaguzeeva** [comment]
Could you please provide me with more details:
- Do you run DBeaver in Eclipse?
- Steps how do you install and run DBeaver?
- A video with the problem can be also helpful.
- Did you try to [reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

**Comment by LonwoLonwo** [comment]
Also can you please check plug-in dependencies?

![2021-06-07 10_30_21-Window](https://user-images.githubusercontent.com/45152336/120977261-d007a980-c77b-11eb-98cf-a43b40e9ecbc.png)

Sometimes button "Add Required Plug-ins" helps.

And try to clean the project first (Project-> Clean)

**Comment by wangpeng0824** [comment]
> Could you please provide me with more details:
> 
> * Do you run DBeaver in Eclipse?
> * Steps how do you install and run DBeaver?
> * A video with the problem can be also helpful.
> * Did you try to [reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)?

i‘m run dbeaver in eclipse，and i also follow the wiki instructions ，it was build successfully  by maven3.8，but  when i run it ，some errors  happened，I saved a record of my operations step by step to the attach file @LonwoLonwo @kseniiaguzeeva 
 @serge-rider
 eclipse version：eclipse-rcp-2021-03-R-win32-x86_64
jdk：java.version=11.0.11   java.vendor=AdoptOpenJDK
[step-by-step.zip](https://github.com/dbeaver/dbeaver/files/6612963/step-by-step.zip)
