### ISSUE TITLE
NPE appears when trying to set parameter value using @set

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#12773]
#### System information: 
- Operating system (distribution) and version win10x64
- DBeaver version 21.1.0

#### Connection specification:
- Database name and version postgresql

#### Describe the problem you're observing:
NPE appears when trying to set parameter value using @set

![2021-06-08_11h44_18](https://user-images.githubusercontent.com/31996417/121155496-85a42c80-c850-11eb-9b8f-d0862fca7421.gif)

```
null
org.jkiss.dbeaver.model
Error
Tue Jun 08 11:44:13 MSK 2021


java.lang.NullPointerException
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.extractTableName(SQLCompletionAnalyzer.java:848)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.getTableFromAlias(SQLCompletionAnalyzer.java:822)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:255)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:98)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:82)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
verified
