### ISSUE TITLE
Cannot connect to Postgres after connecting to Oracle with kerberos for both

### ISSUE THREAD

**Issue by skibida** [dbeaver/dbeaver#12871]
#### System information: 
- Operating system : Windows 10.0.18363
- DBeaver version: 21.0.4.202105021514
- Additional extensions

#### Connection specification:
- Database names and versions  Oracle 19.10 and PostgreSQL 12.4
- Driver names: oracle.jdbc.OracleDriver and org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
I can connect using kerberos (MIT) to either database.  However, if I connect to Oracle with kerberos first and then try to connect to PostgreSQL, I get the dreaded "No LoginModules configured for pgjdbc"

#### Steps to reproduce, if exist:
Create a connect to Oracle.  Need to specify KERBEROS5 in the driver properties to get it to work at all.
Create connection to PostgreSQL using kerberos
Open the PostgreSQL connection:  success
Open the Oracle connection: success
Close the Oracle connection
Close the PostgreSQL connection
Reopen the PostgreSQL connection: Failure

#### Include any warning/errors/backtraces from the logs

2021-06-16 15:46:31.459 - Connection failed (postgres-jdbc-17a162907ae-1a1454fed2959c1e)
org.jkiss.dbeaver.model.exec.DBCConnectException: GSS Authentication failed
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:437)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:114)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:223)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:82)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:897)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: GSS Authentication failed
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	... 26 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for pgjdbc
	at java.base/javax.security.auth.login.LoginContext.init(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.<init>(Unknown Source)
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:56)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:641)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-16 15:46:31.459 - org.jkiss.dbeaver.model.exec.DBCConnectException: GSS Authentication failed
org.jkiss.dbeaver.model.exec.DBCConnectException: GSS Authentication failed
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:437)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:114)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:223)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:82)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:897)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:71)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: GSS Authentication failed
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	... 26 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for pgjdbc
	at java.base/javax.security.auth.login.LoginContext.init(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.<init>(Unknown Source)
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:56)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:641)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-06-16 15:46:31.459 - No LoginModules configured for pgjdbc
javax.security.auth.login.LoginException: No LoginModules configured for pgjdbc
	at java.base/javax.security.auth.login.LoginContext.init(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.<init>(Unknown Source)
	at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:56)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:641)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at java.base/java.lang.Thread.run(Unknown Source

**Comment by Matvey16** [comment]
Hello @skibida sorry for the late response. Can you specify how are you connecting to databases. Are you using Kerberos authentication method in connection's main settings or through driver properties?

**Comment by skibida** [comment]
Thanks for the response!
There is no option for kerberos in the main settings.  I just leave it at "Database Native".
For Postgres, I did not change any driver properties.
For Oracle, I had to specify KERBEROS5 for the oracle.net.authentication.services property.

**Comment by Matvey16** [comment]
Ok, so how exactly did you set up the authentication for kerberos? It is important because there are more than one way to do it, including changing driver properties, or through main settings in EE version. So to see where something breaks we need to know how your kerberos authentication is set up.

**Comment by skibida** [comment]
Ok.
We are using MIT kerberos 4.1 on Windows 10.  We create a ticket using the gui where we enter our AD password.

The principal our ticket specifies is a login for both Postgres and Oracle databases.  In Aurora Postgres, the rds_ad role is granted.  For Oracle the account is IDENTIFIED EXTERNALLY.

The krb5.conf with the proper realms and pgjdbc.conf files are setup  in c:\ProgramData\Kerberos.
The cache is c:\temp\krb5cc_1

contents of pgjdbc.conf:

pgjdbc {
com.sun.security.auth.module.Krb5LoginModule required
doNotPrompt=true
useTicketCache=true
renewTGT=true
refreshKrb5Config=true
debug=true;
};

These values are present in the dbeaver.ini:

-Djava.security.auth.login.config=C:\ProgramData\Kerberos\pgjdbc.conf
-Djava.security.krb5.conf=C:\ProgramData\Kerberos\krb5.conf

Incidently, if I open two Dbeaver instances using different workspaces (-data <ws> in the shortcuts) one can connect to PG and the other one to Oracle without any problems, so the problem is buried somewhere in the workspace I think.

**Comment by Matvey16** [comment]
This is caused by the use of a standalone kerberos client and how it interacts with java. For now we can't fix it because we use built-in kerberos in Enterprise versions. But we will look if anything can be done in one of the future updates.

**Comment by LonwoLonwo** [comment]
Hello @skibida

Does this issue still actual for you in the latest DBeaver version? We changed included JAVA version. It may help.
https://dbeaver.io/

**Comment by uslss** [comment]
There has been no update for a long time. If the issue is still actual for you - feel free to reopen it.
