### ISSUE TITLE
restore database failed for the following reason

### ISSUE THREAD

**Issue by tuchengxiaoweidu** [dbeaver/dbeaver#12886]
Task 'MySQL restore' started at Fri Jun 18 12:28:12 CST 2021
ERROR 1064 (42000) at line 2118: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*/' at line 1

Task 'MySQL restore' finished at Fri Jun 18 12:28:23 CST 2021
2021-06-18 12:28:23.997 - IO error: Process failed (exit code = 1). See error log.
2021-06-18 12:28:23.998 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:188)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:248)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:54)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by uslss** [comment]
@tuchengxiaoweidu ,
Please, provide steps to reproduce and a more clear description of the issue. What DBeaver version do you use?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
