### ISSUE TITLE
NPE when autocompleting table names in CTE

### ISSUE THREAD

**Issue by vrozkovec** [dbeaver/dbeaver#12909]
#### System information: 
- Operating system (distribution) and version: Linux 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux, Linux Mint 20.1
- DBeaver version: 21.1.0

#### Connection specification:
- Database name and version:  10.5.8-MariaDB-1:10.5.8+maria~focal
- Driver name: MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
NPE when autocompleting table name when inside a CTE

#### Steps to reproduce, if exist:
Does not happen always, but only sometimes when trying to autocomplete a table name inside a CTE definition.

#### Include any warning/errors/backtraces from the logs

```
java.lang.NullPointerException
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:144)
	at net.sf.jsqlparser.statement.select.WithItem.accept(WithItem.java:71)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:127)
	at net.sf.jsqlparser.statement.select.Select.accept(Select.java:28)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1186)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1153)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:1067)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:780)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:278)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:98)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:82)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

Session data:
```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

**Comment by uslss** [comment]
@vrozkovec could you provide a query example?

**Comment by vrozkovec** [comment]
@uslss I wanted to but could not reproduce it on demand, seems like it happens randomly. I'll keep an eye on this bug and give you more details when that happens again.

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If it is still actual - feel free to reopen it with additional info to reproduce the issue.
