### ISSUE TITLE
Connect to redis failed

### ISSUE THREAD

**Issue by xiaobiaozhao** [dbeaver/dbeaver#12900]
#### System information: 
- Operating system Macos
- DBeaver 21.1.0.202106090921
- Additional extensions

#### Connection specification:
- Database pika 3.4.0  https://github.com/OpenAtomFoundation/pika

#### Describe the problem you're observing:
I have checked and found that PIKA does not support Client Zege Redis command. I have set the connection not to do client authentication, but it has not taken effect
![image](https://user-images.githubusercontent.com/52393536/122576490-4f528280-d084-11eb-9499-ffbdbbab680e.png)

```
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:330)
	at com.dbeaver.db.redis.model.RedisDataSource.acquireClient(RedisDataSource.java:297)
	at com.dbeaver.db.redis.exec.RedisSession.<init>(RedisSession.java:52)
	at com.dbeaver.db.redis.exec.RedisExecutionContext.openSession(RedisExecutionContext.java:80)
	at com.dbeaver.db.redis.exec.RedisExecutionContext.openSession(RedisExecutionContext.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:110)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4589)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Syntax error, try CLIENT (LIST [order by [addr|idle]| KILL ip:port)
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:201)
	at redis.clients.jedis.Jedis.clientSetname(Jedis.java:3325)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:159)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 9 more
```

**Comment by xiaobiaozhao** [comment]
PIKA is compatible with the Redis protocol

**Comment by Matvey16** [comment]
We need to implement support for Pika.

**Comment by tati-kru** [comment]
I'm not sure that Jedis support Pika. While it looks Pika doesn't support standard Redis commands.

**Comment by serge-rider** [comment]
Pika (and maybe some other Redis forks) doesn't support CLIENT command.
We made it optional, just disable "Send client name" option on the connections page:

![image](https://user-images.githubusercontent.com/6398845/136687143-9dc9a689-fdf7-4636-a1ae-88f9d6373827.png)

**Comment by Matvey16** [comment]
Verified
