### ISSUE TITLE
Unable to query in snowflake connection after java update in arch linux

### ISSUE THREAD

**Issue by kishvanchee** [dbeaver/dbeaver#12918]
#### System information: 
- Operating system (distribution) and version - Arch Linux
- DBeaver version - 21.1.0
- Additional extensions

#### Connection specification:
- Database name and version - Snowflake
- Driver name - net.snowflake:snowflake-jdbc:RELEASE - 3.13.4
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Dbeaver does not return results from a query. Gives the following error.

```
SQL Error [200001] [XX000]: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
```
I notice that this problem goes away if I set my java version to 11 and not 16.

#### Steps to reproduce, if exist:
Setting my default java version to 16 produces this error.
```
❯ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)
```

#### Include any warning/errors/backtraces from the logs

```
2021-06-21 13:59:37.760 - Create display
2021-06-21 13:59:37.918 - DBeaver 21.1.0.202106021338 is starting
2021-06-21 13:59:37.920 - OS: Linux 5.10.45-1-lts (amd64)
2021-06-21 13:59:37.920 - Java version: 16.0.1 by N/A (64bit)
2021-06-21 13:59:37.920 - Install path: '/usr/lib/dbeaver'
2021-06-21 13:59:37.920 - Instance path: 'file:/home/kishore/.local/share/DBeaverData/workspace6/'
2021-06-21 13:59:37.920 - Memory available 94Mb/1024Mb
2021-06-21 13:59:37.957 - Starting RMI server at 49038
2021-06-21 13:59:38.091 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.73.202106021338]
2021-06-21 13:59:40.868 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-06-21 13:59:41.093 - Create actions
2021-06-21 13:59:41.100 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-06-21 13:59:41.101 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-06-21 13:59:41.967 - Initialize workbench window
2021-06-21 13:59:41.988 - Finish initialization
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.58.202106021338]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.48.202106021338]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.58.202106021338]
> Start Team Support Core [org.eclipse.team.core 3.8.1100.v20200806-0621]
> Start Core Compare Support [org.eclipse.compare.core 3.6.1000.v20201020-1107]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1000.v20200715-0827]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.5.0.v20201012-1421]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.5.100.v20200908-1020]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
2021-06-21 13:59:44.582 - Loading user drivers configuration from '/home/kishore/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-06-21 13:59:44.599 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.58.202106021338]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.95.202106021338]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.64.202106021338]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.18.202106021338]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.18.202106021338]
> Start Console [org.eclipse.ui.console 3.10.100.v20201211-1511]
> Start Debug Core [org.eclipse.debug.core 3.18.0.v20210222-1101]
2021-06-21 13:59:46.096 - Connect with 'TEST_DB' (snowflake_jdbc-179e2d770ce-19ec78aa518fc109)
> Start DBeaver Snowflake Extension core [org.jkiss.dbeaver.ext.snowflake.core 1.0.78.202106021338]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.144.202106021338]
2021-06-21 13:59:46.229 - Execution context opened (TEST_DB; Main; 0)
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
2021-06-21 13:59:55.804 - Exception caught when refreshing defaults for Snowflake execution context
net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1054)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:544)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:461)
	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:216)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:131)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:737)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:635)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeQuery(JDBCStatementImpl.java:346)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeExecutionContext.refreshDefaults(SnowflakeExecutionContext.java:134)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.initializeContextState(SnowflakeDataSource.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:42)
	at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:914)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2021-06-21 13:59:55.806 - Error while initializing context state
org.jkiss.dbeaver.DBException: Unable to refresh defaults for Snowflake execution context
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeExecutionContext.refreshDefaults(SnowflakeExecutionContext.java:143)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.initializeContextState(SnowflakeDataSource.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:42)
	at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:914)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1054)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:544)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:461)
	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:216)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:131)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:737)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:635)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeQuery(JDBCStatementImpl.java:346)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeExecutionContext.refreshDefaults(SnowflakeExecutionContext.java:134)
	... 12 more
2021-06-21 13:59:55.823 - Error getting sqlStateType: null
2021-06-21 13:59:57.413 - Connected (snowflake_jdbc-179e2d770ce-19ec78aa518fc109, Snowflake [3.13.4])
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.700.v20200511-1530]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.500.v20210108-0738]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.0.v20201013-0853]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.7.0.v20210114-1216]
2021-06-21 14:00:15.192 - SQL Error [200001] [XX000]: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [200001] [XX000]: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3278)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4589)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1054)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:544)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:461)
	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:216)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:131)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:737)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:635)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:337)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.49.202106021338]
2021-06-21 14:08:21.835 - Open [https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/maven-metadata.xml]
2021-06-21 14:16:14.624 - DBeaver is stopping
2021-06-21 14:16:14.625 - Stop RMI server
2021-06-21 14:16:14.626 - DBeaver shutdown completed

```

**Comment by kishvanchee** [comment]
Weirdly I was able to fix this using [this stackoverflow answer](https://stackoverflow.com/a/67415091/5675288). I'm not sure if this is good idea since I'm don't understand what `-Djdk.module.illegalAccess=permit` means. I have added it to my `dbeaver.ini` file.

Here are the logs now.
```
2021-06-21 15:50:07.699 - Create display
2021-06-21 15:50:07.879 - DBeaver 21.1.0.202106021338 is starting
2021-06-21 15:50:07.880 - OS: Linux 5.10.45-1-lts (amd64)
2021-06-21 15:50:07.880 - Java version: 16.0.1 by N/A (64bit)
2021-06-21 15:50:07.881 - Install path: '/usr/lib/dbeaver'
2021-06-21 15:50:07.882 - Instance path: 'file:/home/kishore/.local/share/DBeaverData/workspace6/'
2021-06-21 15:50:07.882 - Memory available 64Mb/1024Mb
2021-06-21 15:50:07.920 - Starting RMI server at 21251
2021-06-21 15:50:08.017 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.73.202106021338]
2021-06-21 15:50:10.860 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-06-21 15:50:11.089 - Create actions
2021-06-21 15:50:11.095 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-06-21 15:50:11.095 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-06-21 15:50:11.968 - Initialize workbench window
2021-06-21 15:50:11.984 - Finish initialization
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.58.202106021338]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.48.202106021338]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.58.202106021338]
> Start Team Support Core [org.eclipse.team.core 3.8.1100.v20200806-0621]
> Start Core Compare Support [org.eclipse.compare.core 3.6.1000.v20201020-1107]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1000.v20200715-0827]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.5.0.v20201012-1421]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.5.100.v20200908-1020]
2021-06-21 15:50:14.850 - Loading user drivers configuration from '/home/kishore/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-06-21 15:50:14.870 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.58.202106021338]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.95.202106021338]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.64.202106021338]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.18.202106021338]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.18.202106021338]
> Start Console [org.eclipse.ui.console 3.10.100.v20201211-1511]
> Start Debug Core [org.eclipse.debug.core 3.18.0.v20210222-1101]
2021-06-21 15:50:16.266 - Connect with 'TEST_DB' (snowflake_jdbc-179e2d770ce-19ec78aa518fc109)
> Start DBeaver Snowflake Extension core [org.jkiss.dbeaver.ext.snowflake.core 1.0.78.202106021338]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.144.202106021338]
2021-06-21 15:50:16.359 - Execution context opened (TEST_DB; Main; 0)
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
2021-06-21 15:50:27.824 - Error getting sqlStateType: null
2021-06-21 15:50:30.049 - Connected (snowflake_jdbc-179e2d770ce-19ec78aa518fc109, Snowflake [3.13.4])
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.700.v20200511-1530]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.500.v20210108-0738]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.0.v20201013-0853]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.7.0.v20210114-1216]
2021-06-21 15:57:35.489 - DBeaver is stopping
2021-06-21 15:57:35.491 - Stop RMI server
2021-06-21 15:57:35.491 - DBeaver shutdown completed
```

Please feel free to close this issue. I hope you can provide a sufficient explanation than myself regarding this.
