### ISSUE TITLE
After upgrading to 21.1.1 all views are broken

### ISSUE THREAD

**Issue by jlmoya** [dbeaver/dbeaver#12960]
#### System information: 
- Big Sur 11.4
- DBeaver version 21.1.1
- Eclipse 2021-06 4.20
- Oracle JDK:
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
- Additional extensions
  DBeaver Debug	6.1.49.202106210824	org.jkiss.dbeaver.debug.feature.feature.group	JKISS
    DBeaver Desktop UI	21.1.1.202106210824	org.jkiss.dbeaver.ui.feature.feature.group	JKISS
      DBeaver Runtime	21.1.1.202106210824	org.jkiss.dbeaver.runtime.feature.feature.group	JKISS
  DBeaver Git support	1.0.47.202106210824	org.jkiss.dbeaver.git.feature.feature.group	DBeaver Corp
  DBeaver IDE	21.1.1.202106210824	org.jkiss.dbeaver.ide.feature.feature.group	JKISS
    DBeaver Databases	1.0.50.202106210824	org.jkiss.dbeaver.db.feature.feature.group	JKISS
    DBeaver Databases UI	1.0.50.202106210824	org.jkiss.dbeaver.db.ui.feature.feature.group	JKISS
    DBeaver Desktop UI Extras	21.1.1.202106210824	org.jkiss.dbeaver.ui.extra.feature.feature.group	JKISS
  DBeaver Office Support	1.1.96.202106210824	org.jkiss.dbeaver.ext.office.feature.feature.group	JKISS
  DBeaver SSHJ	1.0.80.202106210824	org.jkiss.dbeaver.net.sshj.feature.feature.group	JKISS
  DBeaver SVG Extension	1.0.95.202106210824	org.jkiss.dbeaver.ext.ui.svg.feature.feature.group	DBeaver Corp

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
After upgrading to 21.1.1 all views are broken.

#### Steps to reproduce, if exist:
I have uninstalled and reinstalled, same outcome.  Also, I uninstalled and installed 7.1.5 from archives and same result.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-06-23 06:58:49.868
!MESSAGE Failed to evaluate: WithExpression [variable=activePart, children=[<test property="hasActiveProject" plug-in activation: lazy/>]]
!STACK 0
org.eclipse.core.runtime.CoreException: Error evaluating Property [org.jkiss.dbeaver.core.global.hasActiveProject, type=class org.eclipse.ui.internal.ErrorViewPart, tester=org.jkiss.dbeaver.ui.actions.GlobalPropertyTester@5f0b09a4]
	at org.eclipse.core.internal.expressions.Property.test(Property.java:68)
	at org.eclipse.core.expressions.TestExpression.evaluate(TestExpression.java:107)
	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
	at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:79)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:109)
	at org.eclipse.ui.internal.services.EvaluationReference.changed(EvaluationReference.java:103)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.services.EvaluationService$1.changed(EvaluationService.java:79)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activate(EclipseContext.java:683)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activateBranch(EclipseContext.java:692)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener$1.run(ShellActivationListener.java:99)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener.processWindow(ShellActivationListener.java:95)
	at org.eclipse.e4.ui.internal.workbench.swt.ShellActivationListener.handleEvent(ShellActivationListener.java:65)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1108)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4436)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1516)
	at org.eclipse.swt.widgets.Shell.windowDidBecomeKey(Shell.java:2314)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6166)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:228)
	at org.eclipse.swt.widgets.Widget.becomeKeyWindow(Widget.java:389)
	at org.eclipse.swt.widgets.Shell.becomeKeyWindow(Shell.java:533)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5885)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSWindow.makeKeyAndOrderFront(NSWindow.java:201)
	at org.eclipse.swt.widgets.Shell.makeKeyAndOrderFront(Shell.java:1337)
	at org.eclipse.swt.widgets.Shell.setWindowVisible(Shell.java:2104)
	at org.eclipse.swt.widgets.Shell.open(Shell.java:1397)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.postProcess(WBWRenderer.java:747)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
Caused by: java.lang.IllegalStateException: No DBeaver application was defined
	at org.jkiss.dbeaver.model.impl.app.ApplicationRegistry.getApplication(ApplicationRegistry.java:100)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductName(GeneralUtils.java:286)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductTitle(GeneralUtils.java:281)
	at org.jkiss.dbeaver.core.DBeaverCore.createInstance(DBeaverCore.java:93)
	at org.jkiss.dbeaver.core.DBeaverCore.getInstance(DBeaverCore.java:85)
	at org.jkiss.dbeaver.core.DBeaverCoreAdapterFactory.getAdapter(DBeaverCoreAdapterFactory.java:33)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:339)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:366)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:739)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:718)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:733)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.actions.GlobalPropertyTester.test(GlobalPropertyTester.java:42)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:65)
	... 64 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-06-23 07:03:46.252
!MESSAGE Failed to evaluate: WithExpression [variable=selection, children=[<test property="hasMultipleProjects" plug-in activation: lazy/>]]
!STACK 0
org.eclipse.core.runtime.CoreException: Error evaluating Property [org.jkiss.dbeaver.core.global.hasMultipleProjects, type=class org.eclipse.jface.viewers.StructuredSelection, tester=org.jkiss.dbeaver.ui.actions.GlobalPropertyTester@5f0b09a4]
	at org.eclipse.core.internal.expressions.Property.test(Property.java:68)
	at org.eclipse.core.expressions.TestExpression.evaluate(TestExpression.java:107)
	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
	at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:79)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:109)
	at org.eclipse.ui.internal.services.EvaluationReference.changed(EvaluationReference.java:103)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.services.EvaluationService$1.changed(EvaluationService.java:79)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handleSelectionChanged(SelectionService.java:85)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$0(SelectionService.java:72)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$1.run(SelectionAggregator.java:123)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyListeners(SelectionAggregator.java:120)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$5.lambda$0(SelectionAggregator.java:220)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$5.changed(SelectionAggregator.java:220)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:108)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.runAndTrack(EclipseContext.java:346)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.track(SelectionAggregator.java:205)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.setPart(SelectionAggregator.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:95)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activate(EclipseContext.java:683)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.activateBranch(EclipseContext.java:692)
	at org.eclipse.e4.ui.internal.workbench.PartActivationHistory.activate(PartActivationHistory.java:58)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:760)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:679)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:674)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1251)
	at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1252)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1240)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:4249)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4247)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4229)
	at org.eclipse.ui.internal.progress.ProgressManagerUtil.openProgressView(ProgressManagerUtil.java:154)
	at org.eclipse.ui.internal.progress.ProgressRegion.processDoubleClick(ProgressRegion.java:209)
	at org.eclipse.ui.internal.progress.ProgressAnimationItem.doAction(ProgressAnimationItem.java:139)
	at org.eclipse.ui.internal.progress.ProgressAnimationItem.lambda$2(ProgressAnimationItem.java:319)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
Caused by: java.lang.IllegalStateException: No DBeaver application was defined
	at org.jkiss.dbeaver.model.impl.app.ApplicationRegistry.getApplication(ApplicationRegistry.java:100)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductName(GeneralUtils.java:286)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductTitle(GeneralUtils.java:281)
	at org.jkiss.dbeaver.core.DBeaverCore.createInstance(DBeaverCore.java:93)
	at org.jkiss.dbeaver.core.DBeaverCore.getInstance(DBeaverCore.java:85)
	at org.jkiss.dbeaver.core.DBeaverCoreAdapterFactory.getAdapter(DBeaverCoreAdapterFactory.java:33)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:339)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:366)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:739)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:718)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:733)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.actions.GlobalPropertyTester.test(GlobalPropertyTester.java:40)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:65)
	... 82 more

<img width="1792" alt="Screen Shot 2021-06-23 at 8 38 01 AM" src="https://user-images.githubusercontent.com/1294464/123119068-6dabdb80-d400-11eb-8a07-0e4f610fce5a.png">

<img width="1012" alt="Screen Shot 2021-06-23 at 6 45 04 PM" src="https://user-images.githubusercontent.com/1294464/123186520-8a263300-d455-11eb-8c83-bfe345b4ea41.png">

**Comment by uslss** [comment]
could you provide an [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?
looks like the installation was broken. Probably you could try to reinstall eclipse

**Comment by uslss** [comment]
there is no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
