### ISSUE TITLE
Can not open new SQL editor

### ISSUE THREAD

**Issue by caohenghui** [dbeaver/dbeaver#12986]
#### System information: 
- Operating system (distribution) and version: win10 64
- DBeaver version: dbeaver-ce-21.1.1-win32.win32.x86_64
- Additional extensions: AdoptOpenJDK OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9

#### Connection specification:
- Database name and version: Mysql 5.6
- Driver name: com.mysql.cj.jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:  no

#### Describe the problem you're observing:
Can not open new SQL editor
#### Include any warning/errors/backtraces from the logs
2021-06-25 11:49:25.672 - -344728521
java.lang.NegativeArraySizeException: -344728521
        at org.eclipse.swt.program.Program.getKeyValue(Program.java:164)
        at org.eclipse.swt.program.Program.getProgram(Program.java:196)
        at org.eclipse.swt.program.Program.getPrograms(Program.java:228)
        at org.eclipse.ui.internal.registry.EditorRegistry.getSortedEditorsFromOS(EditorRegistry.java:462)
        at org.eclipse.ui.internal.registry.EditorRegistry.addExternalEditorsToEditorMap(EditorRegistry.java:302)
        at org.eclipse.ui.internal.registry.EditorRegistry.initializeFromStorage(EditorRegistry.java:578)
        at org.eclipse.ui.internal.registry.EditorRegistry.<init>(EditorRegistry.java:183)
        at org.eclipse.ui.internal.WorkbenchPlugin$15.compute(WorkbenchPlugin.java:1366)
        at org.eclipse.e4.core.internal.contexts.ValueComputation.get(ValueComputation.java:70)
        at org.eclipse.e4.core.internal.contexts.EclipseContext.internalGet(EclipseContext.java:271)
        at org.eclipse.e4.core.internal.contexts.EclipseContext.get(EclipseContext.java:237)
        at org.eclipse.e4.core.internal.contexts.EclipseContext.get(EclipseContext.java:608)
        at org.eclipse.ui.internal.WorkbenchPlugin.getEditorRegistry(WorkbenchPlugin.java:464)
        at org.eclipse.ui.internal.Workbench.getEditorRegistry(Workbench.java:1499)
        at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3133)
        at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3051)
        at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenObjectConsole.openAndExecuteSQLScript(SQLEditorHandlerOpenObjectConsole.java:122)
        at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenObjectConsole.openConsole(SQLEditorHandlerOpenObjectConsole.java:103)
        at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenObjectConsole.execute(SQLEditorHandlerOpenObjectConsole.java:91)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)

**Comment by uslss** [comment]
@caohenghui 
unfortunately, cannot reproduce. Could you provide steps to reproduce or video with the issue?

**Comment by uslss** [comment]
there is no update on an issue for a long time.
If the issue is still actual - feel free to reopen it
