### ISSUE TITLE
Firebird connection refused

### ISSUE THREAD

**Issue by zcatav** [dbeaver/dbeaver#12995]
Hi,

#### System information: 
- Operating system (distribution) and version Pop! _OS 20.04 LTS
- DBeaver version 21.1.1
- Additional extensions 

#### Connection specification:
- Database name and version Firebird 3.0.5.33220.ds4-1build2
- Driver name jaybird 4.0.0 java8 jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Dbeaver works as expected other than Firebird. When try to connect firebird database it is fail with following error:
"Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
  Connection refused (Connection refused)"
Btw Flamerobin connects same db without an issue.
Thanks for your attention.

This issue not occurs on other PC run with Ubuntu 20.04 LTS.
#### Include any warning/errors/backtraces from the logs

> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.12.100.v20210122-1731]
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 21.1.1.202106210824]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.0.v20210122-1423]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.1000.v20210111-0958]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.1100.v20210111-0815]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.18.100.v20210122-1536]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 21.1.1.202106210824]
2021-06-25 13:24:02.019 - Initializing DBeaver 21.1.1
2021-06-25 13:24:02.019 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 21.1.1.202106210824
2021-06-25 13:24:02.019 - Initialize Core...
2021-06-25 13:24:02.020 - Can't find BC security provider. Use default JCE.
2021-06-25 13:24:02.020 - BouncyCastle not registered, using the default JCE provider
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.14.0.v20210215-0934]
2021-06-25 13:24:02.207 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.59.202106210824]
2021-06-25 13:24:02.274 - Core initialized (255ms)
2021-06-25 13:24:02.279 - Create display
2021-06-25 13:24:02.445 - DBeaver 21.1.1.202106210824 is starting
2021-06-25 13:24:02.445 - OS: Linux 5.11.0-7614-generic (amd64)
2021-06-25 13:24:02.446 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
2021-06-25 13:24:02.446 - Install path: '/app/dbeaver'
2021-06-25 13:24:02.446 - Instance path: 'file:/home/catav/.local/share/DBeaverData/workspace6/'
2021-06-25 13:24:02.446 - Memory available 64Mb/1024Mb
2021-06-25 13:24:02.483 - Starting RMI server at 50649
2021-06-25 13:24:02.541 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.74.202106210824]
2021-06-25 13:24:04.699 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-06-25 13:24:04.781 - Create actions
2021-06-25 13:24:04.785 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-06-25 13:24:04.786 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-06-25 13:24:05.305 - Initialize workbench window
2021-06-25 13:24:05.313 - Finish initialization
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1000.v20200715-0827]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.49.202106210824]
2021-06-25 13:24:06.503 - Loading user drivers configuration from '/home/catav/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-06-25 13:24:06.512 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.59.202106210824]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.59.202106210824]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.59.202106210824]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.96.202106210824]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.65.202106210824]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.19.202106210824]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.19.202106210824]
2021-06-25 13:24:12.555 - Connect with 'employee.fdb' (jaybird-17a4274845a-fc09f11dfe18731)
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.145.202106210824]
> Start DBeaver Firebird Support [org.jkiss.dbeaver.ext.firebird 1.0.160.202106210824]
2021-06-25 13:24:12.617 - Execution context opened (employee.fdb; Main; 0)
2021-06-25 13:24:12.762 - Connection failed (jaybird-17a4274845a-fc09f11dfe18731)
org.jkiss.dbeaver.model.exec.DBCConnectException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataSource.<init>(FireBirdDataSource.java:71)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createDataSourceImpl(FireBirdMetaModel.java:63)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:217)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLNonTransientConnectionException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$5.createSQLException(FbExceptionBuilder.java:598)
	at org.firebirdsql.gds.ng.FbExceptionBuilder$ExceptionInformation.toSQLException(FbExceptionBuilder.java:492)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toSQLException(FbExceptionBuilder.java:223)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:236)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.performConnect(FbWireDatabaseFactory.java:50)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:39)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:32)
	at org.firebirdsql.jca.FBManagedConnection.<init>(FBManagedConnection.java:143)
	at org.firebirdsql.jca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:591)
	at org.firebirdsql.jca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:65)
	at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:109)
	at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	... 24 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:226)
	... 34 more
2021-06-25 13:24:12.766 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
org.jkiss.dbeaver.model.exec.DBCConnectException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataSource.<init>(FireBirdDataSource.java:71)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createDataSourceImpl(FireBirdMetaModel.java:63)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:217)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLNonTransientConnectionException: Unable to complete network request to host "localhost". [SQLState:08006, ISC error code:335544721]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$5.createSQLException(FbExceptionBuilder.java:598)
	at org.firebirdsql.gds.ng.FbExceptionBuilder$ExceptionInformation.toSQLException(FbExceptionBuilder.java:492)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toSQLException(FbExceptionBuilder.java:223)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:236)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.performConnect(FbWireDatabaseFactory.java:50)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:39)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:32)
	at org.firebirdsql.jca.FBManagedConnection.<init>(FBManagedConnection.java:143)
	at org.firebirdsql.jca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:591)
	at org.firebirdsql.jca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:65)
	at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:109)
	at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	... 24 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:226)
	... 34 more
2021-06-25 13:24:12.774 - Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.firebirdsql.gds.ng.wire.WireConnection.socketConnect(WireConnection.java:226)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.performConnect(FbWireDatabaseFactory.java:50)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:39)
	at org.firebirdsql.gds.ng.wire.FbWireDatabaseFactory.connect(FbWireDatabaseFactory.java:32)
	at org.firebirdsql.jca.FBManagedConnection.<init>(FBManagedConnection.java:143)
	at org.firebirdsql.jca.FBManagedConnectionFactory.createManagedConnection(FBManagedConnectionFactory.java:591)
	at org.firebirdsql.jca.FBStandAloneConnectionManager.allocateConnection(FBStandAloneConnectionManager.java:65)
	at org.firebirdsql.jdbc.FBDataSource.getConnection(FBDataSource.java:109)
	at org.firebirdsql.jdbc.FBDriver.connect(FBDriver.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataSource.<init>(FireBirdDataSource.java:71)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createDataSourceImpl(FireBirdMetaModel.java:63)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:217)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by zcatav** [comment]
![Screenshot from 2021-06-25 13-07-36](https://user-images.githubusercontent.com/25180767/123412097-e1ddaf00-d5b9-11eb-8e0b-1674689d90e2.png)

screenshots of driver

**Comment by uslss** [comment]
could you check the similar issue [here ](https://superuser.com/questions/1374476/connecting-dbeaver-to-a-firebird-file-gives-error-code-335544721)and check if answers can solve your issue?

**Comment by zcatav** [comment]
It didn't work.  I changed the operating system from LMDE4 to Ubuntu 20.04
LTS. Now it's work as expected.
Thanks for your attention.

Zeki Çatav
zekicatav.com

28 Haz 2021 Pzt 12:00 tarihinde Dziyana ***@***.***> şunu
yazdı:
