### ISSUE TITLE
SQLite doesn't execute sql statement anymore since last update

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#13029]
#### System information: 
- Operating system (distribution) and version: Linux ice-ubuntu 5.11.0-22-generic 23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version:  Version 21.1.1.202106210923
- Additional extensions : none

#### Connection specification:
- Database name and version: SQLIte. In system:
sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1

- Driver name:  SQLite / org.xerial:sqlite-jdbc:RELEASE, file : <home>/.local/share/DBeaverData/drivers/maven/maven-central/org.xerial/sqlite-jdbc-3.36.0.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO 

#### Describe the problem you're observing:
error while selecting from DB
#### Steps to reproduce, if exist:

1) open db . Connect to it => success. Metadata is read properly i.e. tables, indexes
2) execute simple statement e.g. select * from table

Expected result: see results
Actual result: error below ==>

#### Include any warning/errors/backtraces from the logs
```
org.jkiss.dbeaver.model.exec.DBCException: org/locationtech/jts/io/InStream
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:818)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3280)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4624)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: org/locationtech/jts/io/InStream
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:230)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/io/InStream
	at org.jkiss.dbeaver.ext.sqlite.model.data.SQLiteValueHandlerProvider.getValueHandler(SQLiteValueHandlerProvider.java:42)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:792)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:765)
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingMeta.<init>(DBDAttributeBindingMeta.java:62)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeBinding(DBUtils.java:615)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeBindings(DBUtils.java:624)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:110)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:678)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.io.InStream cannot be found by org.jkiss.dbeaver.ext.sqlite_1.0.108.202106210923
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
```

**Comment by icegood** [comment]
java installed:

dpkg -l "*jre*" | grep ii
ii  default-jre                   2:1.11-72          amd64        Standard Java or Java compatible Runtime
ii  default-jre-headless          2:1.11-72          amd64        Standard Java or Java compatible Runtime (headless)
ii  openjdk-11-jre:amd64          11.0.11+9-0ubuntu2 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64 11.0.11+9-0ubuntu2 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-8-jre:amd64           8u292-b10-0ubuntu1 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64  8u292-b10-0ubuntu1 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

**Comment by ShadelessFox** [comment]
Hello @icegood,

Looks like something went wrong with your installed version of DBeaver.

Can you try performing clean installation (delete old version and install a new one)?

**Comment by icegood** [comment]
re-installed. Same effect. i'm installing from repo 
https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce
with 'hirsute' ubuntu

**Comment by icegood** [comment]
The issue is localized. Tried to install directly from
 https://dbeaver.io/ - everything works fine, while from repo above doesn't work. Is repo above your repo?

**Comment by Matvey16** [comment]
@icegood Yes, this is the correct repo. I tried to reproduce it on 20.04 Focal, and it works normal when installing from this repo. Maybe there is something specific with a way that you are installing it?

**Comment by icegood** [comment]
simple apt install. My files in /etc/apt are:

/etc/apt/sources.list.d/serge-rider-ubuntu-dbeaver-ce-hirsute.list:

deb http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu/ hirsute main
\# deb-src http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu/ hirsute main

and binary in 

/etc/apt/trusted.gpg.d/serge-rider-ubuntu-dbeaver-ce.gpg

**Comment by icegood** [comment]
My apt install log:

apt install dbeaver-ce 


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  dbeaver-ce
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 93,6 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu **hirsute**/main amd64 dbeaver-ce amd64 21.1.2\~ubuntu**16.04** [93,6 MB]
Fetched 93,6 MB in 10s (9.751 kB/s)                                                                                                                                                                          
Selecting previously unselected package dbeaver-ce.
(Reading database ... 292831 files and directories currently installed.)
Preparing to unpack .../dbeaver-ce_21.1.2\~ubuntu16.04_amd64.deb ...
Unpacking dbeaver-ce (21.1.2\~ubuntu**16.04**) ...
Setting up dbeaver-ce (21.1.2\~ubuntu**16.04**) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mailcap (3.68ubuntu1) ...

**Comment by icegood** [comment]
bold text looks strange...
Reproducible since of today as well

**Comment by Matvey16** [comment]
@icegood We updated a package on this repository. If it is possible for you, please can you check it again and confirm if the issue is still there for your version of Ubuntu.

**Comment by icegood** [comment]
doesn't help at all. For now my java config is:

update-alternatives --get-selections | grep jvm
jar                            auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jar
jarsigner                      auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner
java                           auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/java
javac                          auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
javadoc                        auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/javadoc
javap                          auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/javap
jcmd                           auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jcmd
jconsole                       auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole
jdb                            auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jdb
jdeps                          auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jdeps
jexec                          auto     /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec
jfr                            auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jfr
jinfo                          auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jinfo
jjs                            auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs
jmap                           auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jmap
jps                            auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jps
jrunscript                     auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jrunscript
jstack                         auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jstack
jstat                          auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jstat
jstatd                         auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/jstatd
keytool                        auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
pack200                        auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200
rmic                           auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/rmic
rmid                           auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid
rmiregistry                    auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry
serialver                      auto     /usr/lib/jvm/java-8-openjdk-amd64/bin/serialver
unpack200                      auto     /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200

**Comment by Matvey16** [comment]
@icegood while we are looking for a solution can you try deleting `/home/user/.local/share/DBeaverData/drivers/maven/maven-central/org.xerial` and redownloading the driver. Also have you tried executing SQL statements on other databases other than SQLite and does this happen only in SQL Editor or the same error appears when you try to open a table in data editor?

**Comment by uslss** [comment]
@icegood is it still actual for you?

**Comment by Matvey16** [comment]
Verified on early access versions from devel branch. Needs to be tested on release version

**Comment by Matvey16** [comment]
Still reproducible for Databases with gis extension. Reproducible only when installing a version from dbeaver.io on top of a newer version.

**Comment by Matvey16** [comment]
```
org.jkiss.dbeaver.DBException: org/locationtech/jts/io/ParseException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:230)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/io/ParseException
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreValueHandlerProvider.getValueHandler(PostgreValueHandlerProvider.java:81)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:796)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:769)
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingMeta.<init>(DBDAttributeBindingMeta.java:62)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeBinding(DBUtils.java:618)
	at org.jkiss.dbeaver.model.DBUtils.getAttributeBindings(DBUtils.java:627)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:196)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.io.ParseException cannot be found by org.jkiss.dbeaver.ext.postgresql_2.1.138.202109181446
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by Matvey16** [comment]
This is a third party issue with Java. Bug happens when downgrading DBeaver version. For now this can't be fixed and the only workaround is the delete the `.eclipse` folder before install.
