### ISSUE TITLE
Can't open new SQL Editor in some occations

### ISSUE THREAD

**Issue by petr-hybler** [dbeaver/dbeaver#13173]
#### System information: 
- Ubuntu 20.04.2 LTS 64-bit, GNOME 3.36.8
- 21.1.2.202107041908
- no extensions

#### Connection specification:
- there is no problem with any DB connection

#### Describe the problem you're observing:
Sometimes happens (I haven't really figured out the pattern yet - but I suspect switching between different DBs) that when I open the DBeaver and close all previous tabs (table details, sql editor windows, ...) and open connection to a different DB (one is behind VPN and the other one is running locally) I cannot open new SQL Editor  (SQL Editor -> New SQL Script) .. it prompts with

![image](https://user-images.githubusercontent.com/17429498/125394199-9abd2f80-e3a9-11eb-958b-456588faff11.png)

The only fix for this I found is to close all tabs (table details, sql editor windows, ...) so the right side is completely empty and then it opens the editor without a problem. But that's kinda boring and annoying :( 

I am suspecting it's somehow trying to open the connection related to the closed session instead of the current one. Previously I was connected to the local database Postgresql and now I am connected to another (PG as well via VPN) and this happens.

#### Steps to reproduce, if exist:
see above

#### Include any warning/errors/backtraces from the logs
here are some suspicious parts from the logs I found:

```
2021-07-13 06:42:53.258 - Create display
  2 SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this re    cipient; type="method_call", sender=":1.134" (uid=1000 pid=11723 comm="/snap/dbeaver-ce/137/usr/share/dbeaver/jre/bin/jav" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface=    "org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.23" (uid=1000 pid=1882 comm="/usr/libexec/gnome-session-binary --system    d-servic" label="unconfined")
  3 2021-07-13 06:42:53.445 - DBeaver 21.1.2.202107041908 is starting
```

```
2021-07-13 07:10:08.871 - null argument:
337 org.eclipse.core.runtime.AssertionFailedException: null argument:
338         at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
339         at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
340         at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:293)
341         at org.jkiss.dbeaver.utils.RuntimeUtils.getObjectAdapter(RuntimeUtils.java:59)
342         at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getSelectedNode(NavigatorUtils.java:100)
343         at org.jkiss.dbeaver.ui.actions.AbstractDataSourceHandler.getActiveObject(AbstractDataSourceHandler.java:70)
344         at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLNavigatorContext.<init>(SQLNavigatorContext.java:35)
345         at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.getCurrentContext(SQLEditorHandlerOpenEditor.java:191)
346         at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openNewEditor(SQLEditorHandlerOpenEditor.java:179)
347         at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.execute(SQLEditorHandlerOpenEditor.java:116)
348         at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
349         at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
350         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
351         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
352         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
353         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
354         at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
355         at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
356         at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
357         at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
358         at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
359         at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
360         at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
361         at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
362         at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
363         at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
364         at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
365         at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
366         at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
367         at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
368         at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
369         at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
370         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
371         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
372         at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
373         at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
374         at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
375         at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
376         at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
377         at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
378         at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
379         at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
380         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
381         at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
382         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
383         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
384         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
385         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
386         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
387         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
388         at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
389         at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
390         at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
391         at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```

**Comment by Matvey16** [comment]
@petr-hybler Thank you for the report

**Comment by uslss** [comment]
verified
