### ISSUE TITLE
ClassCastException when setting column data type when creating new column

### ISSUE THREAD

**Issue by lgraham1** [dbeaver/dbeaver#13227]
#### System information: 
- Operating system (distribution) and version macOS 11.2.3
- DBeaver version Community Version 21.1.2.202107041908
- Additional extensions None

#### Connection specification:
- Database name and version MariaDB mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2 (running in Docker container)
- Driver name MariaDB Java Client 2.7.1 (automatically downloaded by DBeaver)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
When adding a column to a table, in the 'Edit attribute Column 1' dialog, if you open to data type dropdown and the click off it inside the properties area (if you click elsewhere in the dialog it doesn't happen), you get an error message. If you do the same thing on the 'View table' view for the table, it doesn't happen.

I've [searched the issues](https://github.com/dbeaver/dbeaver/issues?q=ObjectPropertyDescriptor+cannot+be+cast), but couldn't find anything. This is a very minor problem, but I only installed DBeaver today so it caught my attention. Otherwise DBeaver has been very good so far.

#### Steps to reproduce, if exist:
1. In Database Navigator, 'right click Tables folder' and choose 'Create new table'
2. In the bottom right, click the 'Create new column' button
3. In the 'Edit attribute Column 1' dialog click the 'varchar(100)' value
4. Open the dropdown
5. Click one of the other properties in the dialog box. Note if you click outside of the properties area (e.g. the 'Name' input), the error doesn't happen
6. Get an error dialog, 'Problem Occurred' with the message:
    ```
    An error has occurred. See error log for more details.
    class org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor cannot be cast to class org.jkiss.dbeaver.model.DBPNamedObject2 (org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor and org.jkiss.dbeaver.model.DBPNamedObject2 are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3328061e)
    ```

#### Include any warning/errors/backtraces from the logs

<details>
<summary>Session from .log</summary>

```
!SESSION 2021-07-16 14:08:13.537 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -keyring /Users/l.graham/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/l.graham/.eclipse_keyring

!ENTRY org.eclipse.jface 4 2 2021-07-16 14:08:42.269
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.ClassCastException: class org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor cannot be cast to class org.jkiss.dbeaver.model.DBPNamedObject2 (org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor and org.jkiss.dbeaver.model.DBPNamedObject2 are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @61e3a1fd)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer$4.applyEditorValue(PropertyTreeViewer.java:516)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:335)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:332)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.applyEditorValueAndDeactivate(ComboBoxCellEditor.java:273)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.focusLost(ComboBoxCellEditor.java:280)
	at org.jkiss.dbeaver.ui.controls.CustomComboBoxCellEditor.focusLost(CustomComboBoxCellEditor.java:140)
	at org.eclipse.jface.viewers.ComboBoxCellEditor$3.focusLost(ComboBoxCellEditor.java:171)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:147)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.custom.CCombo.handleFocus(CCombo.java:986)
	at org.eclipse.swt.custom.CCombo.lambda$2(CCombo.java:152)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1108)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4436)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1516)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:3433)
	at org.eclipse.swt.widgets.Display.checkFocus(Display.java:684)
	at org.eclipse.swt.widgets.Shell.makeFirstResponder(Shell.java:1319)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6281)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1146)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2172)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1138)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2625)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2139)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6079)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2150)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2487)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6203)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5442)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5585)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3834)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:121)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:116)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.edit(BaseObjectEditPage.java:108)
	at org.jkiss.dbeaver.ui.editors.object.config.BaseTableColumnConfigurator.lambda$0(BaseTableColumnConfigurator.java:34)
	at org.jkiss.dbeaver.ui.UITask$1.runTask(UITask.java:42)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4179)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3839)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$7(WorkbenchWindow.java:2345)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2343)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.run(RunnableContextDelegate.java:39)
	at org.jkiss.dbeaver.ui.UIUtils.runInProgressService(UIUtils.java:1665)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase.createDatabaseObject(NavigatorHandlerObjectCreateBase.java:186)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase.createNewObject(NavigatorHandlerObjectCreateBase.java:167)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:118)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.jkiss.dbeaver.ui.ActionUtils.runCommand(ActionUtils.java:338)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:111)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3837)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```
</details>

<details>
<summary>dbeaver-debug.log</summary>

```
2021-07-16 14:06:58.309 - Create display
2021-07-16 14:06:58.725 - DBeaver 21.1.2.202107041908 is starting
2021-07-16 14:06:58.727 - OS: Mac OS X 11.2 (x86_64)
2021-07-16 14:06:58.727 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
2021-07-16 14:06:58.727 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2021-07-16 14:06:58.727 - Instance path: 'file:/Users/l.graham/Library/DBeaverData/workspace6/'
2021-07-16 14:06:58.728 - Memory available 64Mb/1024Mb
2021-07-16 14:06:58.753 - Starting RMI server at 57534
2021-07-16 14:06:58.881 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.75.202107041908]
2021-07-16 14:07:02.072 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-07-16 14:07:02.529 - Create actions
2021-07-16 14:07:02.535 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-07-16 14:07:02.536 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-07-16 14:07:03.223 - Initialize workbench window
2021-07-16 14:07:03.236 - Finish initialization
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.60.202107041908]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1000.v20200715-0827]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.50.202107041908]
2021-07-16 14:07:04.949 - Loading user drivers configuration from '/Users/l.graham/Library/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-07-16 14:07:04.967 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.60.202107041908]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.60.202107041908]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.97.202107041908]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.66.202107041908]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.20.202107041908]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.20.202107041908]
2021-07-16 14:07:05.705 - Connect with 'salus_dev' (mariaDB-17aae6f23c4-1e4710286586a20b)
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.145.202107041908]
2021-07-16 14:07:05.770 - Execution context opened (salus_dev; Main; 0)
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.84.202107041908]
2021-07-16 14:07:05.988 - Execution context opened (salus_dev; Metadata; 1)
2021-07-16 14:07:06.172 - Connected (mariaDB-17aae6f23c4-1e4710286586a20b, MariaDB Connector/J [2.7.1])
> Start GEF (MVC) [org.eclipse.gef 3.11.0.201606061308]
> Start Draw2d [org.eclipse.draw2d 3.10.100.201606061308]
> Start Team Support Core [org.eclipse.team.core 3.8.1100.v20200806-0621]

2021-07-16 14:08:00.836 - DBeaver is stopping
2021-07-16 14:08:00.837 - Stop RMI server
2021-07-16 14:08:00.842 - DBeaver shutdown completed
```
</details>

**Comment by Matvey16** [comment]
@lgraham1 Thank you for the report. Issue is specific to Mac OS, we will look into it in future updates

**Comment by flambchap** [comment]
Accidentally fixed by [this](https://github.com/dbeaver/dbeaver/commit/c1a785a26bd47f5781b847a2ae469840cec15227) commit. Love this kind of stuff.
