### ISSUE TITLE
CE 21.1.3 breaks the GUI, launching dbeaver .exe as a background process but cannot interact

### ISSUE THREAD

**Issue by jennybrown8** [dbeaver/dbeaver#13260]
#### System information: 
Windows 10, Version 20H2, OS Build 19042.1083 from 2021-03-19
DBeaver Community Edition 21.1.3 
No additional extensions

#### Describe the problem you're observing:

I try to launch the DBeaver GUI from the desktop icon.  I see a splash screen start.  Then it vanishes, and the task bar icon vanishes with it, as if it crashed during loading.  When I check with Task Manager, I can see a background dbeaver.exe process running, but not using any cpu.  There is no visible gui for me to use and no task shown on my task bar.

I also tried uninstalling 21.1.3 completely and reinstalling 21.1.2 but the GUI display problem persisted, breaking the older version as well.  I did not upgrade any other software during this period of time.  I had been running 21.1.2 successfully for quite a while, and took the .3 upgrade when the prompt appeared, and that broke it.

#### Steps to reproduce, if exist:

Install CE 21.1.3 and then try to run it.

Possibly relevant to the 'out of heap space' error below, the dbeaver.ini configuration caps at 1 gig, which I definitely have available on my 16 G system fresh after a reboot:  -Xms64m  -Xmx1024m.  However, increasing from 1024 to 2048 still doesn't solve the GUI launch problem.

#### Include any warning/errors/backtraces from the logs

2021-07-20 02:27:12.076 - Create display
2021-07-20 02:27:12.150 - DBeaver 21.1.2.202107041908 is starting
2021-07-20 02:27:12.151 - OS: Windows 10 10.0 (amd64)
2021-07-20 02:27:12.151 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
2021-07-20 02:27:12.152 - Install path: 'file:/C:/Program Files/DBeaver/'
2021-07-20 02:27:12.152 - Instance path: 'file:/C:/Users/jenny/AppData/Roaming/DBeaverData/workspace6/'
2021-07-20 02:27:12.152 - Memory available 61Mb/989Mb
2021-07-20 02:27:12.162 - Starting RMI server at 58233
2021-07-20 02:27:12.232 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start Expression Language [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start Java Native Access [com.sun.jna 4.5.1.v20190425-1842]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.75.202107041908]
2021-07-20 02:27:14.776 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2021-07-20 02:27:15.489 - Create actions
2021-07-20 02:27:15.494 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-07-20 02:27:15.494 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-07-20 02:27:15.886 - Initialize workbench window
2021-07-20 02:27:15.894 - Finish initialization
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.60.202107041908]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start Team Support Core [org.eclipse.team.core 3.8.1100.v20200806-0621]
2021-07-20 02:27:17.310 - Internal error in workbench lifecycle
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.setDocumentContent(FileStoreTextFileBuffer.java:536)
	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.initializeFileBufferContent(FileStoreTextFileBuffer.java:319)
	at org.eclipse.core.internal.filebuffers.FileStoreFileBuffer.create(FileStoreFileBuffer.java:66)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.connectFileStore(TextFileBufferManager.java:150)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.createFileInfo(TextFileDocumentProvider.java:571)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.connect(TextFileDocumentProvider.java:481)
	at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4182)
	at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:262)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1479)
	at org.eclipse.ui.editors.text.TextEditor.doSetInput(TextEditor.java:153)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3172)
	at org.eclipse.ui.texteditor.AbstractTextEditor$$Lambda$470/0x000000004f5d34a8.run(Unknown Source)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2290)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3189)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3214)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:353)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:344)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:405)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:332)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
2021-07-20 02:27:17.313 - DBeaver is stopping
2021-07-20 02:27:17.314 - Stop RMI server
2021-07-20 02:27:17.346 - DBeaver shutdown completed

**Comment by uslss** [comment]
@jennybrown8 could you try to [reset workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) and write back if it helps or not?

**Comment by jennybrown8** [comment]
From %APPDATA%\Roaming\ I deleted the entire DBeaverData directory, relaunched 21.1.2, and it worked.  It prompted me to upgrade.  I told it yes, and let it upgrade.  21.1.3 worked as well.  Resetting the workspace appears to have solved the problem.  Thank you.
