### ISSUE TITLE
Counting occurrences via a SQL query

### ISSUE THREAD

**Issue by anderagakura** [dbeaver/dbeaver#13276]
#### System information: 
- Operating system (distribution) and version : macOS Big Sur Version 11.2.2
- DBeaver version 21.1.3.202107181810
- Additional extensions : No

#### Connection specification:
- Database name and version : CSV file
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I'd like to count occurrences in a string via a SQL query but TRANSLATE() and REPLACE() are not available. In addition, I'd like to see the list of SQL functions available in DBeaver but I did not find it.

**Comment by Matvey16** [comment]
@anderagakura Hello, can you please clarify where are you trying to execute this functions? What Database are you using?
Regarding SQL functions: available functions depend on the database you are using, if they are available in your database, they are eligible to be written in DBeaver SQL editor. Any function that you write for SQL query will be executed on the server side. Client side commands can be found here [Wiki link](https://github.com/dbeaver/dbeaver/wiki/Client-Side-Scripting)

**Comment by anderagakura** [comment]
@Matvey16 My database is just a CSV file contain more than 40GB of data and I'm happy that DBeaver can handle it. What I want now is running a sql query (`Select`) to count number of occurrences of a character per each string. When I try **TRANSLATE()** (by the way, the SQL editor highlights this word but no explanation) function I got _SQL Error: SQL function not found: TRANSLATE_, same for **REPLACE()** with _SQL Error: SQL function not found: REPLACE_. 
> Hello, can you please clarify where are you trying to execute this functions? What Database are you using?
> Regarding SQL functions: available functions depend on the database you are using, if they are available in your database, they are eligible to be written in DBeaver SQL editor. Any function that you write for SQL query will be executed on the server side. Client side commands can be found here [Wiki link](https://github.com/dbeaver/dbeaver/wiki/Client-Side-Scripting)


If you're interested in, below is more detailed from the console about TRANSLATE() not found : 
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error: SQL function not found: TRANSLATE
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:210)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:101)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:681)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3435)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4686)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: SQL function not found: TRANSLATE
	at org.relique.jdbc.csv.SQLUserFunction.eval(SQLUserFunction.java:50)
	at org.relique.jdbc.csv.CsvResultSet.getMetaData(CsvResultSet.java:1496)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:48)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1681)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:208)

```

**Comment by Matvey16** [comment]
@anderagakura If you are using a JDBC driver that opens CSV files as tables then unfortunately it is very limited in functionality, it can only run basic Selects with primitive expressions, and doesn't support any functions. [Documentation](https://github.com/simoc/csvjdbc/blob/master/docs/doc.md) for this driver. If you want to use anything more complex than basic select, you need to at least use some embedded database like SQLite and export your table there.

**Comment by anderagakura** [comment]
@Matvey16 That makes sense. Thanks for your help. I can close this issue. Best
