### ISSUE TITLE
NPE when trying to export numeric column from Postgres to SQL Server

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13291]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 21.1.3

#### Connection specification:
- Database name and version SQL Server

#### Describe the problem you're observing:
When trying to export a table with numeric column from Postgres to SQL Server NPE is thrown both if trying to view a DDL or after starting the export

#### Steps to reproduce, if exist:
1. Create a table in PostgreSQL with numeric column
2. Start export into SQL Server database

#### Include any warning/errors/backtraces from the logs
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDialect.getColumnTypeModifiers(SQLServerDialect.java:235)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.mapTargetDataType(DBStructUtils.java:389)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseMappingAttribute.getTargetType(DatabaseMappingAttribute.java:259)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.generateStructTableDDL(DatabaseTransferUtils.java:240)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.generateTargetTableDDL(DatabaseTransferUtils.java:95)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetTable(DatabaseTransferConsumer.java:602)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetDatabaseObjects(DatabaseTransferConsumer.java:561)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:530)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:108)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.1.4

**Comment by Matvey16** [comment]
Verified
