### ISSUE TITLE
Can't use LIKE or REGEX to set row colors on numeric columns

### ISSUE THREAD

**Issue by marszysz** [dbeaver/dbeaver#13302]
#### System information: 
- Operating system (distribution) and version: Manjaro Linux 21.1.0
- DBeaver version: 21.1.2.202107071042
- Java version: java-11-openjdk 11.0.11+9
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL 5.5.5-10.3.10-MariaDB-1:10.3.10+maria~stretch
- Driver name: MySQL Connector/J mysql-connector-java-8.0.17
- Do you use tunnels or proxies (SSH, SOCKS, etc)? tunnel over standalone SSH client instance

#### Describe the problem you're observing:
In the Row Colors dialog box the value field won't accept non-numeric values even with the LIKE or REGEX operator if trying to set colors based on the value of a numeric field.
#### Steps to reproduce, if exist:
Open the Row Colors dialog, select a numeric field in the left column, add a condition, select the REGEX operator, enter the sample from the manual (`^\d*[13579]$`) into the Value input field. Now clicking the OK button doesn't have any effect. Clicking the condition in the condition list clears the value field.
#### Include any warning/errors/backtraces from the logs

Clicking the OK button causes these log entries to appear:

!ENTRY org.eclipse.ui 4 0 2021-07-23 10:23:23.421
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.exec.DBCLogicalOperator$14.evaluate(DBCLogicalOperator.java:117)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel$AttributeColorSettings.evaluate(ResultSetModel.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateRowColors(ResultSetModel.java:764)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateColorMapping(ResultSetModel.java:718)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.okPressed(ColorSettingsDialog.java:664)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.buttonPressed(ColorSettingsDialog.java:656)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.open(ColorSettingsDialog.java:644)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.CustomizeColorsAction.run(CustomizeColorsAction.java:42)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-07-23 10:23:23.428
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-07-23 10:23:23.428
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.exec.DBCLogicalOperator$14.evaluate(DBCLogicalOperator.java:117)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel$AttributeColorSettings.evaluate(ResultSetModel.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateRowColors(ResultSetModel.java:764)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateColorMapping(ResultSetModel.java:718)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.okPressed(ColorSettingsDialog.java:664)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.buttonPressed(ColorSettingsDialog.java:656)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.open(ColorSettingsDialog.java:644)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.CustomizeColorsAction.run(CustomizeColorsAction.java:42)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

**Comment by ShadelessFox** [comment]
Hello @marszysz,

Thanks for the report.

Unfortunately, I cannot reproduce your issue using provided description. Can you record a video instead?

**Comment by marszysz** [comment]
No problem.

https://user-images.githubusercontent.com/19807080/126940655-3a2abd45-430b-4b3b-8489-a1db7ae9b7eb.mp4

**Comment by ShadelessFox** [comment]
I was able to reproduce the issue. Thanks!

**Comment by Matvey16** [comment]
Verified
