### ISSUE TITLE
DBeaver cannot detect the end of user defined snowflake functions which use count(distinct case...)

### ISSUE THREAD

**Issue by MichaelFishmanOD** [dbeaver/dbeaver#13307]
# dbeaver-cannot-detect-end-of-snowflake-function-issue

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.3
- Additional extensions

#### Connection specification:
- Database name and version: Snowflake 5.29.1
- Driver name: snowflake-jdbc-3.13.6.jar

#### Describe the problem you're observing:

DBeaver is unable to detect the end of a `Create function` statement if the statment uses `count(distinct case `

#### Steps to reproduce, if exist:

This sql runs correctly in the Snowflake webapp, but throws an error in DBeaver when creating the function tempdb.aa_udtf_count_distinct_case_test:

```sql
    --Create table of data
    CREATE OR replace TABLE tempdb.aa_udtf_count_distinct_case_test_source_table AS (
        SELECT 'cat' AS species, 'meow' AS sound
        UNION
        SELECT 'cat' AS species, 'purr' AS sound
        UNION
        SELECT 'dog' AS species, 'bark' AS sound
    );

    --Count how many different sounds cats make
    SELECT count(DISTINCT CASE WHEN species = 'cat' THEN sound end) AS sound_cnt FROM tempdb.aa_udtf_test_source_table;

    --Create a function that counts how many sounds a species makes. Using 'WHERE' instead of 'count(distinct case..' lets the function be created
    CREATE OR REPLACE FUNCTION tempdb.aa_udtf_count_distinct_case_test_with_where(species varchar)
    RETURNS TABLE (sound_cnt int)
    AS
    $$
        SELECT count(DISTINCT a.sound) AS sound_cnt
        FROM tempdb.aa_udtf_count_distinct_case_test_source_table a
        WHERE a.species = species
    $$
    ;

    --Create a function that counts how many sounds a species makes. This throws an error in DBeaver because DBeaver does not detect the end of this statement
    --This statement works correctly in Snowflake
    CREATE OR REPLACE FUNCTION tempdb.aa_udtf_count_distinct_case_test(species varchar)
    RETURNS TABLE (sound_cnt int)
    AS
    $$
        SELECT count(DISTINCT CASE WHEN a.species = species THEN a.sound end) AS sound_cnt
        FROM tempdb.aa_udtf_count_distinct_case_test_source_table a
    $$
    ;


    SELECT 1 AS n;
```

#### Include any warning/errors/backtraces from the logs

    !ENTRY org.jkiss.dbeaver.model 4 0 2021-07-23 14:05:12.697
    !MESSAGE SQL Error [8] [0A000]: Actual statement count 2 did not match the desired statement count 1.
    !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-07-23 14:05:12.697
    !MESSAGE Actual statement count 2 did not match the desired statement count 1.
    !STACK 0
    net.snowflake.client.jdbc.SnowflakeSQLException: Actual statement count 2 did not match the desired statement count 1.
        at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
        at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
        at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:442)
        at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:345)
        at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:486)
        at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:197)
        at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:134)
        at net.snowflake.client.core.SFStatement.execute(SFStatement.java:743)
        at net.snowflake.client.core.SFStatement.execute(SFStatement.java:639)
        at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:287)
        at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:337)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.run(SQLQueryJob.java:220)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Matvey16** [comment]
@MichaelFishmanOD Hello, this is a normal Snowflake behavior to protect from SQL injections. This statement to create a function tries to run multiple statements and by default Snowlake limits statement count to 1. To execute it you either need to run the whole script with `Alt + X`, or if you don't want to execute the whole script, you need to firstly execute  
`alter session set MULTI_STATEMENT_COUNT = 0;` to disable this lock for the current session or  
`alter account set MULTI_STATEMENT_COUNT = 0;` to disable it for user  
or you can use another number instead of 0 if you want to run multiple statements but still have a limit

**Comment by MichaelFishmanOD** [comment]
@Matvey16 Thanks for the response! Changing this setting allows me to run the whole script, solving my practical issue.

However, there is still an issue with how DBeaver parses the sql. For most SQL statements, if I place my cursor on the statement and run it with `ctrl + enter`, DBeaver attempts to run that single statement. For this statement which creates `tempdb.aa_udtf_count_distinct_case_test`, if I place my cursor on it and press `ctrl + enter`, DBeaver attempts to run this statement, along with all subsequent statements.

If I select the entire function creation statement, then `ctrl + enter` runs that single statement, as expected.
