### ISSUE TITLE
DBCException: Error converting string to composite type (PostgreSQL)

### ISSUE THREAD

**Issue by thyringer** [dbeaver/dbeaver#13368]
DBeaver – Version 21.1.3.202107181810 (under Linux / Ubuntu) – fails to display composite data type values in a PostgreSQL database. This error affects the display within the table view as well as with select queries:

![Screenshot_20210729_161757](https://user-images.githubusercontent.com/30962753/127508757-926b0239-e327-4bc9-ad66-1158156aa44f.png)

![Screenshot_20210729_162009](https://user-images.githubusercontent.com/30962753/127508784-b6ea2551-421a-4e73-9321-2118288b520c.png)

It should be noted that I get the values displayed in the command line program psql. So it must be up to DBeaver.

The following error message has been copied from the data field:

```
org.jkiss.dbeaver.model.exec.DBCException: Error converting string to composite type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:203)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4686)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Composite type 'delivery_address' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:109)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:96)
	... 10 more
```

**Comment by Matvey16** [comment]
@Thyringer Hello, thank you for the report. I reproduced this issue. Can you verify if `country_code` type is a custom enum type, because I assumed that it is for my test.

For a future reference here is a script to reproduce.
  
```sql

create type "country_code" as enum (
    'UK',
    'US',
    'RU'
);

create type __delivery_address__ as (
	street varchar(50),
	house_nr int,
	house_nr_letter varchar(1),
	house_nr_fraction int,
	zip varchar(10),
	district varchar(50),
	city varchar(50),
	country country_code
	);

create domain delivery_address as __delivery_address__ check (
		(
		((value).street is not null
		and
		(value).house_nr is not null)
		or 
		((value).street is null
		and
		(value).house_nr is null
		and 
		(value).house_nr_letter is null
		and 
		(value).house_nr_fraction is null)
		)
		and 
		(value).zip is not null
		and 
		(value).city is not null
		and 
		(value).country is not null 
);

create table test_address (addr delivery_address primary key);

insert into test_address (addr) values (('Lenina',5,'A',2,'123456','Leningradskaya','SPB','US'::country_code));

select
	*
from
	test_address ta ;
```

**Comment by thyringer** [comment]
@Matvey16  
Thanks for your answer and the effort!
I downloaded the latest version of DBeaver today and created two test tables: The first table is very simple and the second one quite complex. But there were no display errors in either.

I suspect the bug was fixed in the last update?

Nevertheless I have attached my two test examples here.

```
create type x as (a int, b int);

create table test (composite_value x not null primary key);

insert into test (composite_value) values (row (1, 2)), (row (2, 3)), (row (4, 5));


-- more complex example:

create type country_code as enum (
	'AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'IT', 'LI', 'LU', 'NL', 'PL'
);


create type __street_address__ as (
	name varchar(50),
	nr int,
	letter varchar(1),
	fraction int,
	unit int
		-- In the case of private addresses, simply the apartment number.
);


create domain street_address as __street_address__ constraint
	"valid street address with a name and street number at least"
check (
	(value).name is not null and (value).nr is not null
);


create table if not exists address (
	id serial,
	street street_address null,
	po_box varchar(10) default null,
		-- Post office box (DE: Postfach)
	zip varchar(10) not null,
	district varchar(50) default null,
	city varchar(50) not null,
	country country_code not null default 'DE',

	constraint "internally used surrogate key to an address" primary key (id),

	constraint "street address, post office box or just zipcode and city name" check (
		street is null or po_box is null
	)
);

insert into address(street, zip, city, country) values
	(row ('Birkenweg', 16, 'b', null, null), 38855, 'Wernigerode', 'DE');
```

If the error occurs again, I will contact you here. but seems to be resolved! :)

**Comment by Matvey16** [comment]
@Thyringer Can you check the error log? For me the error is visible inside the table, when opened in resultset of SQL Editor by executing a select. When opened in data viewer the table field looks normal, but an error still appears in error log.

![dbeaver_8aMD5LThkY](https://user-images.githubusercontent.com/82543000/127970374-b4813601-a973-4a12-ad8e-4f5c087abc66.png)

**Comment by thyringer** [comment]
Oh ok, I can confirm that. The view of the table entries through the GUI works, but the error still occurs with select queries:

```
!ENTRY org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:32.995
!MESSAGE Error resolving attribute 'street' values
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:32.995
!MESSAGE Error converting string to composite type
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:32.995
!MESSAGE Composite type 'street_address' has no attributes
!STACK 0
org.jkiss.dbeaver.DBException: Composite type 'street_address' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:109)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:96)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:760)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:164)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:737)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3435)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:44.037
!MESSAGE Error resolving attribute 'street' values
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:44.038
!MESSAGE Error converting string to composite type
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2021-08-03 15:33:44.038
!MESSAGE Composite type 'street_address' has no attributes
!STACK 0
org.jkiss.dbeaver.DBException: Composite type 'street_address' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:109)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:96)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:760)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:217)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
@Thyringer Ok, thank you, we will work on that

**Comment by uslss** [comment]
verified
