### ISSUE TITLE
ssh connected but not connect database via VPS

### ISSUE THREAD

**Issue by duri0214** [dbeaver/dbeaver#13388]
#### System information: 
- OS CentOS7
- DBeaver version 21.1.3.202107181810

#### Connection specification:
- Database name and version: MySQL8.0
- Driver name: MySQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: SSH

#### Describe the problem you're observing:
it's ok "Test tunnel configuration".
![image](https://user-images.githubusercontent.com/19668980/127774388-4204d9ea-06f6-4dc1-a628-e146225c9a27.png)
but not working connection.
![image](https://user-images.githubusercontent.com/19668980/127774488-049e6f0e-5757-4f55-ad82-5c6f5d1296cd.png)

I can connected if MySQLWorkbench, so I don't know more

#### Steps to reproduce, if exist:
every time. maybe the probrem of environment

#### Include any warning/errors/backtraces from the logs
Can not read response from server. Expected to read 4,739,923 bytes, read 17 bytes before connection was unexpectedly lost.

**Comment by uslss** [comment]
@duri0214 could you provide [debug log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by duri0214** [comment]
@uslss 
thank you for reply.
![image](https://user-images.githubusercontent.com/19668980/127876635-e6417e78-0436-4cc6-8cda-a8b2aee85e99.png)

`dbeaver-debug.log`
```
2021-08-02 23:21:04.887 - Create display
2021-08-02 23:21:04.980 - DBeaver 21.1.4.202108020335 is starting
2021-08-02 23:21:04.981 - OS: Windows 10 10.0 (amd64)
2021-08-02 23:21:04.981 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
2021-08-02 23:21:04.981 - Install path: 'C:\Users\yoshi\AppData\Local\DBeaver'
2021-08-02 23:21:04.982 - Instance path: 'file:/C:/Users/yoshi/AppData/Roaming/DBeaverData/workspace6/'
2021-08-02 23:21:04.982 - Memory available 104Mb/989Mb
2021-08-02 23:21:04.988 - Starting RMI server at 55225
2021-08-02 23:21:05.037 - Run workbench
> Start Eclipse e4 ワークベンチ SWT [org.eclipse.e4.ui.workbench.swt 0.16.0.v20201230-1610]
> Start Eclipse アプリケーション・サービス [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Eclipse コンテキスト [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI アプリケーション・サービス [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF 共通 [org.eclipse.emf.common 2.22.0.v20210114-1734]
> Start EMF Ecore [org.eclipse.emf.ecore 2.23.0.v20200630-0516]
> Start EMF XML/XMI 永続化 [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI 依存性注入 [org.eclipse.e4.ui.di 1.3.0.v20210222-1018]
> Start CSS SWT テーマ・サポート [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start e4 ワークベンチ・アドオン [org.eclipse.e4.ui.workbench.addons.swt 1.4.100.v20201221-2332]
> Start 式言語 [org.eclipse.core.expressions 3.7.100.v20210203-1000]
> Start Eclipse e4 ワークベンチ SWT レンダラー [org.eclipse.e4.ui.workbench.renderers.swt 0.15.0.v20201125-0918]
> Start バインディング・サポート [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse 依存性注入拡張 [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start CSS SWT サポート [org.eclipse.e4.ui.css.swt 0.14.100.v20201217-1340]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.77.202108020335]
> Start Eclipse SDK Themes [org.eclipse.ui.themes 1.2.1300.v20210108-1832]
2021-08-02 23:21:06.070 - Configure workbench window
> Start ヘルプシステムコア [org.eclipse.help 3.8.800.v20200525-0755]
2021-08-02 23:21:06.119 - Create actions
2021-08-02 23:21:06.123 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-08-02 23:21:06.123 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-08-02 23:21:06.123 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2021-08-02 23:21:06.584 - Initialize workbench window
2021-08-02 23:21:06.589 - Finish initialization
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.62.202108020335]
> Start ログ・ビュー [org.eclipse.ui.views.log 1.2.1400.v20210122-1423]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start インターネット接続管理 UI [org.eclipse.ui.net 1.3.800.v20200422-1935]
> Start インターネット接続管理 [org.eclipse.core.net 1.3.1000.v20200715-0827]
Warning: NLS unused message: model_connection_events_wevent_before_disconnect in: org.jkiss.dbeaver.model.messages.ModelResources
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.52.202108020335]
2021-08-02 23:21:07.563 - Loading user drivers configuration from 'C:\Users\yoshi\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2021-08-02 23:21:07.571 - Total database drivers: 91 (91)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.62.202108020335]
> Start 既定のテキスト・エディター [org.eclipse.ui.editors 3.14.0.v20210215-0846]
> Start ワークベンチ [org.eclipse.ui.workbench.texteditor 3.16.0.v20210120-0733]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.62.202108020335]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.99.202108020335]
> Start DBeaverの今日のヒント [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.68.202108020335]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.22.202108020335]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.22.202108020335]
```

`.log`
```
!SESSION 2021-08-02 23:15:53.461 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2021-08-02 23:20:15.939
!MESSAGE Can not read response from server. Expected to read 4,739,923 bytes, read 17 bytes before connection was unexpectedly lost.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-08-02 23:20:15.939
!MESSAGE Can not read response from server. Expected to read 4,739,923 bytes, read 17 bytes before connection was unexpectedly lost.
!STACK 0
java.io.EOFException: Can not read response from server. Expected to read 4,739,923 bytes, read 17 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:108)
	at com.mysql.cj.protocol.a.SimplePacketReader.readMessage(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:536)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:493)
	at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:383)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1346)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:423)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:90)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:217)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by uslss** [comment]
@duri0214 is it still actual for you?

**Comment by duri0214** [comment]
Thank you for your reply. I'm still using MYSQLworkbenchi because I still have symptoms, but I'd like to move to beaver completely if possible.

**Comment by uslss** [comment]
seems something wrong with the connection settings. What value do you use as a host?

**Comment by duri0214** [comment]
I recently moved CentOS8 to Ubuntu20.04.
![image](https://user-images.githubusercontent.com/19668980/133610513-dbeb016e-4383-43dc-8b55-129f44855e95.png)
It's OK connection well.

## my setting
![image](https://user-images.githubusercontent.com/19668980/133610759-1a30b5a8-73cf-4959-96a3-9cde31b13e9b.png)
```
ip: 153.126.200.229
port: 22
auth: public key
```

## MySQL Workbench
it's ok connected.
![image](https://user-images.githubusercontent.com/19668980/133611133-8686b987-f302-47ee-bb9e-25b1e5da17fe.png)

**Comment by uslss** [comment]
Does it seem the issue is resolved?

**Comment by duri0214** [comment]
no, doesn't connect by DBeaver

**Comment by uslss** [comment]
could you check if SSL is enabled if used and that the main tab in connection settings is filled in with correct values?

**Comment by duri0214** [comment]
solved! Oh, I was misunderstanding.
![image](https://user-images.githubusercontent.com/19668980/133627779-3389bb27-733a-4c4e-aa77-eb1a557c9135.png)
rewrite...
ip: 127.0.0.1
port: 3306

![image](https://user-images.githubusercontent.com/19668980/133628097-b8cb5899-d445-484c-9783-c195be547d2a.png)

Thank you for taking care of me
