### ISSUE TITLE
Mongo can not use sort

### ISSUE THREAD

**Issue by Korov** [dbeaver/dbeaver#13472]
#### System information: 
- Operating system (distribution) and version: `Windows 10`
- DBeaver version: `21.1.0.202106090921`
- Additional extensions

#### Connection specification:
- Database name and version： `Mongo 4.4.6`
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ：`NO`

#### Steps to reproduce, if exist:

sql:`db.getCollection("kafka-name-count").find().sort({"timestamp":-1});`

result: 

``` java
org.jkiss.dbeaver.model.exec.DBCException: Error fetching Mongo cursor
	at com.dbeaver.db.mongodb.exec.MongoResultSet.nextRow(MongoResultSet.java:180)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:717)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3280)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4589)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:154)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:67)
	at org.bson.BsonDocumentWrapper.getUnwrapped(BsonDocumentWrapper.java:195)
	at org.bson.BsonDocumentWrapper.isEmpty(BsonDocumentWrapper.java:115)
	at com.mongodb.operation.DocumentHelper.putIfNotNullOrEmpty(DocumentHelper.java:43)
	at com.mongodb.operation.FindOperation.getCommand(FindOperation.java:1022)
	at com.mongodb.operation.FindOperation.access$1600(FindOperation.java:90)
	at com.mongodb.operation.FindOperation$6.create(FindOperation.java:1101)
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:219)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:194)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:175)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:989)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:172)
	at com.dbeaver.db.mongodb.exec.MongoResultSet.nextRow(MongoResultSet.java:169)
	... 13 more
```

**Comment by Matvey16** [comment]
@Korov thank you for the report, I reproduced this issue and got an NPE
```java
java.lang.NullPointerException
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:154)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:67)
	at org.bson.BsonDocumentWrapper.getUnwrapped(BsonDocumentWrapper.java:195)
	at org.bson.BsonDocumentWrapper.isEmpty(BsonDocumentWrapper.java:115)
	at com.mongodb.operation.DocumentHelper.putIfNotNullOrEmpty(DocumentHelper.java:43)
	at com.mongodb.operation.FindOperation.getCommand(FindOperation.java:1022)
	at com.mongodb.operation.FindOperation.access$1600(FindOperation.java:90)
	at com.mongodb.operation.FindOperation$6.create(FindOperation.java:1101)
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:219)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:194)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:175)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:989)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:172)
	at com.dbeaver.db.mongodb.exec.MongoResultSet.nextRow(MongoResultSet.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:720)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3435)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by tati-kru** [comment]
Thanks for the report

**Comment by ShadelessFox** [comment]
Implemented `max`, `min`, `partial`, `sort`, `skip`, `count`, `one`, `length`, and `size` functions of cursor.

**Comment by Matvey16** [comment]
`find()` function behavior has changed

![dbeaver_LI4J584iqU](https://user-images.githubusercontent.com/82543000/138449031-6b6644be-5f30-4e81-b63a-7ad364c20be6.png)

**Comment by Matvey16** [comment]
Navigator stopped showing objects

**Comment by Matvey16** [comment]
Verified
