### ISSUE TITLE
Athena: column header filtering error

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13549]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5

#### Connection specification:
- Database name and version Athena

#### Describe the problem you're observing:
Filtering in column header is impossible because of the error. 

#### Steps to reproduce, if exist:
1. Open filter in column header
2. Start typing a needed value

**Expected:** Values are filtered
**Actual:** Error is thrown and filter result is blank

![BimdlmQBO5](https://user-images.githubusercontent.com/82543000/129530352-d04d3eab-d39c-4d6f-ad88-2d44f7797762.gif)

#### Include any warning/errors/backtraces from the logs:

```java
com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 1:1: Incorrect number of parameters: expected 1 but found 0 [Execution ID: 85c9bad2-6e07-4bd2-a65c-2eb4a3ad7195]
	at com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.<init>(Unknown Source)
	at com.simba.athena.athena.dataengine.AJDataEngine.prepare(Unknown Source)
	at com.simba.athena.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.simba.athena.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.athena.jdbc42.AJ42PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.athena.jdbc42.AJJDBC42ObjectFactory.createPreparedStatement(Unknown Source)
	at com.simba.athena.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:406)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:231)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.lambda$0(GenericFilterValueEdit.java:344)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.readEnumeration(GenericFilterValueEdit.java:342)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:633)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
```

**Comment by LonwoLonwo** [comment]
It seems that the Athena driver updating solved this issue too. Can't reproduce in DBeaver 22.0.0 
https://github.com/dbeaver/dbeaver/issues/13784

**Comment by Matvey16** [comment]
Verified
