### ISSUE TITLE
Netezza Performance Server 'infinity' value is not properly handled

### ISSUE THREAD

**Issue by KrzysztofDusko** [dbeaver/dbeaver#13557]
#### System information: 
- Windows 10
- DBeaver 21.1.5.202108160727

#### Connection specification:
- Netezza Performance Server Release 11.2.1.0 [Build 30]
- Driver name : NZJDBC 11.1.0.0.jar

#### Describe the problem you're observing:
run query 
```sql
SELECT 'infinity'::datetime;
```
leads to 'org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1019] [HY000]: netezza.res.bad.timestamp ...'
(same with -infinity)

**Comment by LonwoLonwo** [comment]
Thanks for the bug report

```
org.netezza.error.NzSQLException: netezza.res.bad.timestamp
	at org.netezza.sql.NzResultSet.getPgTimestamp(NzResultSet.java:3381)
	at org.netezza.sql.NzResultSet.getPgObject(NzResultSet.java:3245)
	at org.netezza.sql.NzResultSet.getObject(NzResultSet.java:1205)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:627)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3435)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4686)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
Verified
