### ISSUE TITLE
PostgreSQL: Array type varchar doesn't have a component type

### ISSUE THREAD

**Issue by sizzlorox** [dbeaver/dbeaver#13657]
#### System information: 
- Operating system (distribution) and version
Windows 10 Pro Version 20H2 build 19042.1110
- DBeaver version
2.1.15.202108160727
- Additional extensions
None

#### Connection specification:
- Database name and version
Postgres v13.3
- Driver name
PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
None

#### Describe the problem you're observing:
Having data type of varchar[] causes table column cell to have stacktrace as value although text[] works fine

`Array type varchar doesn't have a component type`

#### Steps to reproduce, if exist:
Create a table with a column containing varchar[]

#### Include any warning/errors/backtraces from the logs

`org.jkiss.dbeaver.model.exec.DBCException: Array type varchar doesn't have a component type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:72)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
![image](https://user-images.githubusercontent.com/16759711/130719849-595621b0-fcbf-4303-9d87-903ce6c3ce0a.png)

**Comment by LonwoLonwo** [comment]
Hello @sizzlorox 
Thanks for the bug report.

Please provide table DDL.
I can't reproduce for now.

![2021-08-25 10_06_30-DBeaver Ultimate 21 2 0 - array_types_varchar](https://user-images.githubusercontent.com/45152336/130742794-fb67a829-7c79-4528-93e6-b52bcaccf9d9.png)

**Comment by sizzlorox** [comment]
Hello @LonwoLonwo 

Thank you for looking into this!
Unfortunately I've already dropped the table and changed it into text[].

After seeing that you're unable to reproduce it I've tried reproducing it myself and strange enough it appears to be working.
My ORM appears to have set the column type as `character varying array`.  Where the DDL is set as:
`status_description varchar NULL, -- Status Description`

It appears the root cause of this issue potentially may be the migration script my ORM has generated and not due to DBeaver. Although I cannot say for sure the reason as to why it happened as I tried running the same migration script again which appears to not be having this issue.

Sorry to have wasted you time!

**Comment by LonwoLonwo** [comment]
Ok. Thanks for the quick response!

**Comment by deostroll** [comment]
Can we re-open this?

I have tried the following in postgresql. (db version 12.10.2). Using dbeaver 23.2.0.202309041200 (on windows 11).

```
-- Step 1.
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    attributes JSONB
);


-- Step 2.
INSERT INTO products (name, attributes) VALUES
('Laptop', '{"brand": "Dell", "specs": {"ram": "16GB", "storage": "512GB SSD"}}'),
('Phone', '{"brand": "Samsung", "specs": {"ram": "8GB", "storage": "128GB"}}'),
('Tablet', '{"brand": "Apple", "specs": {"ram": "4GB", "storage": "64GB"}}');

-- Step 3. (this select works)
select * from products;


-- Step 4. 

-- Step 4.1: Add a new column of type jsonb[]
ALTER TABLE products ADD COLUMN attributes_array JSONB[];

-- Step 4.2: Copy existing jsonb data into the new array column
UPDATE products
SET attributes_array = ARRAY[attributes];

-- Step 4.3: Drop the old column (optional)
ALTER TABLE products DROP COLUMN attributes;

-- Step 4.4: Rename the new column to the original name (optional)
ALTER TABLE products RENAME COLUMN attributes_array TO attributes;

-- Step 5 (this fails)
select * from products;
```

Per code above step 5 fails. All the columns have the following exception:

```
org.jkiss.dbeaver.model.exec.DBCException: Array type jsonb doesn't have a component type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:74)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:56)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3940)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5142)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by E1izabeth** [comment]
@deostroll try the latest DBeaver version. If the bug is still present there, then you can create a new issue
