### ISSUE TITLE
NPE when trying to save blank regex coloring

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13706]
#### System information: 
- DBeaver version 21.2.0
- Additional extensions

#### Describe the problem you're observing:
NPE is thrown when trying to save regex coloring with blank value. Filter is saved anyway

#### Steps to reproduce, if exist:
1. Open row coloring and pick regex operator
2. Leave the value field blank and click ok

**Expected:** Filter is saved and window is closed
**Actual:** Filter is saved but window stays open and NPE is thrown

![vHvUClWBdr](https://user-images.githubusercontent.com/82543000/131114148-0f4a643e-9319-4a63-870d-661179154c07.gif)

```java
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.exec.DBCLogicalOperator$14.evaluate(DBCLogicalOperator.java:117)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel$AttributeColorSettings.evaluate(ResultSetModel.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateRowColors(ResultSetModel.java:761)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateColorMapping(ResultSetModel.java:715)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.okPressed(ColorSettingsDialog.java:678)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.buttonPressed(ColorSettingsDialog.java:670)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.ColorSettingsDialog.open(ColorSettingsDialog.java:658)
	at org.jkiss.dbeaver.ui.controls.resultset.colors.CustomizeColorsAction.run(CustomizeColorsAction.java:42)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

**Comment by ShadelessFox** [comment]
Not reproducible anymore
