### ISSUE TITLE
一会不操作 就断开连接了，必须重新打开才行

### ISSUE THREAD

**Issue by tomuGo** [dbeaver/dbeaver#13719]
#### System information: 
- Operating system (distribution) and version     ubuntu18
- DBeaver version      21.1.5
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误: Statement cancelled due to client request
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.mysql.cj.jdbc.exceptions.MySQLStatementCancelledException: Statement cancelled due to client request
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:110)
	at com.mysql.cj.jdbc.StatementImpl.checkCancelTimeout(StatementImpl.java:2191)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1028)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:895)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1111)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:724)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 7 more

**Comment by ShadelessFox** [comment]
Hello @tomuGo,

Please use English. Can you provide steps to reproduce your issue?

**Comment by TimZhang13579** [comment]
Hi all, the headline means:
DBeaver cannot establish a permanent connection, the session will be broken off within minutes if user don't input any more command.

**Comment by ShadelessFox** [comment]
Hello @TimZhang13579,

Thanks for clarification. But we still need steps to reproduce the issue, otherwise we can't do nothing.

**Comment by TimZhang13579** [comment]
> Hi all, the headline means:
> DBeaver cannot establish a permanent connection, the session will be broken off within minutes if user don't input any more command.

I just translate Chinese to English, I am not the owner of the question. Thanks.

**Comment by Jackxiaojiahuo** [comment]
Hello  @ShadelessFox 
The problem recurrence steps are as follows:
1.Open a database connection session and let it stand for half an hour or an hour
2. If you try to enter a command to execute in this session, an error will be reported(Similar to the above error report)
3. At this point, you must try the connection again and open it again
The session will not automatically attempt to reconnect
 I often encounter this problem

**Comment by uslss** [comment]
@Jackxiaojiahuo you can change keep-alive value in connection properties to non-null. If it will be set e.g. to 30, than keepalive signal will be sent every 30 seconds
![image](https://user-images.githubusercontent.com/31996417/131522605-a7d9a446-8fef-4fea-a4b7-243dce688ad6.png)

**Comment by Jackxiaojiahuo** [comment]
Thanks, I got it
