### ISSUE TITLE
Unable to SSL connect to MySQL

### ISSUE THREAD

**Issue by saleyn** [dbeaver/dbeaver#13721]
#### System information: 
- Operating system (distribution) and version: Manjaro Linux 5.10.59
- DBeaver version: 21.1.5.202108172303
- Additional extensions: None
- Java: jdk-openjdk-16.0.2.u7-1  jre-openjdk-16.0.2.u7-1  jre-openjdk-headless-16.0.2.u7-1  openjdk-doc-16.0.2.u7-1  openjdk-src-16.0.2.u7-1

#### Connection specification:
- Database name and version: MySQL Server version: 10.5.10-MariaDB Arch Linux
- Driver name: com.mysql.cj.jdbc.Driver; mysql-connector-java.8.0.17.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Getting an error in connecting to MySQL with SSL.

#### Steps to reproduce, if exist:
- Configure MySQL connection with SSL
- Click on the connection
- The following error is reported
![image](https://user-images.githubusercontent.com/272543/131218289-e5aeac0c-46f7-4a9d-a392-cc00e8d0de8e.png)

#### Include any warning/errors/backtraces from the logs
```
(DBeaver:968480): Gtk-CRITICAL **: 08:37:10.067: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
2021-08-28 08:37:33.449 - Connect with 'epps' (mysql8-17b8cb4cead-4ffea6ee6f712eeb)
2021-08-28 08:37:33.450 - Execution context opened (epps; Main; 1)
2021-08-28 08:37:33.458 - Connection failed (mysql8-17b8cb4cead-4ffea6ee6f712eeb)
org.jkiss.dbeaver.model.exec.DBCException: Error configuring SSL certificates
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.getInternalConnectionProperties(MySQLDataSource.java:122)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:251)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:136)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:438)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:91)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Error adding certificate to keystore
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:141)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initSSL(MySQLDataSource.java:197)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.getInternalConnectionProperties(MySQLDataSource.java:120)
        ... 26 more
Caused by: java.lang.IllegalAccessError: class org.jkiss.dbeaver.model.impl.app.PKCS1Util (in unnamed module @0x49dbaaf3) cannot access class sun.security.util.DerInputStream (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x49dbaaf3
        at org.jkiss.dbeaver.model.impl.app.PKCS1Util.loadPrivateKeyFromPKCS1(PKCS1Util.java:36)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.loadPrivateKeyFromPEM(DefaultCertificateStorage.java:252)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:135)
        ... 28 more
2021-08-28 08:37:33.459 - org.jkiss.dbeaver.model.exec.DBCException: Error configuring SSL certificates
org.jkiss.dbeaver.model.exec.DBCException: Error configuring SSL certificates
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.getInternalConnectionProperties(MySQLDataSource.java:122)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:251)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:136)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:438)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:91)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Error adding certificate to keystore
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:141)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initSSL(MySQLDataSource.java:197)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.getInternalConnectionProperties(MySQLDataSource.java:120)
        ... 26 more
Caused by: java.lang.IllegalAccessError: class org.jkiss.dbeaver.model.impl.app.PKCS1Util (in unnamed module @0x49dbaaf3) cannot access class sun.security.util.DerInputStream (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x49dbaaf3
        at org.jkiss.dbeaver.model.impl.app.PKCS1Util.loadPrivateKeyFromPKCS1(PKCS1Util.java:36)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.loadPrivateKeyFromPEM(DefaultCertificateStorage.java:252)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:135)
        ... 28 more
2021-08-28 08:37:33.460 - Error adding certificate to keystore
org.jkiss.dbeaver.DBException: Error adding certificate to keystore
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:141)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initSSL(MySQLDataSource.java:197)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.getInternalConnectionProperties(MySQLDataSource.java:120)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getAllConnectionProperties(JDBCDataSource.java:251)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:136)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:438)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:91)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:919)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalAccessError: class org.jkiss.dbeaver.model.impl.app.PKCS1Util (in unnamed module @0x49dbaaf3) cannot access class sun.security.util.DerInputStream (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x49dbaaf3
        at org.jkiss.dbeaver.model.impl.app.PKCS1Util.loadPrivateKeyFromPKCS1(PKCS1Util.java:36)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.loadPrivateKeyFromPEM(DefaultCertificateStorage.java:252)
        at org.jkiss.dbeaver.model.impl.app.DefaultCertificateStorage.addCertificate(DefaultCertificateStorage.java:135)
        ... 28 more
> Start Team Support Core [org.eclipse.team.core 3.8.1100.v20200806-0621]
2021-08-28 08:37:47.005 - DBeaver is stopping
2021-08-28 08:37:47.007 - Stop RMI server
2021-08-28 08:37:47.015 - DBeaver shutdown completed
2021-08-28 08:37:47.036 - Shutdown Core...
2021-08-28 08:37:47.143 - Shutdown completed in 107ms
```

**Comment by ShadelessFox** [comment]
Hello @saleyn,

DBeaver requires Java 11. As of now, we depend on some internal classes from JDK that are unavailable in newer versions of Java.

**Comment by saleyn** [comment]
That works. Thanks!
