### ISSUE TITLE
Error -4461 calling stored procedure

### ISSUE THREAD

**Issue by Cris70** [dbeaver/dbeaver#13747]
#### System information: 
- Linux openSuse Tumbleweed 20210830
- DBeaver 21.2.0.202108291732

#### Connection specification:
- Database name and version: DB/2 for z/OS v12
- Driver name: jdbc version 4.26.14
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, ssh

#### Describe the problem you're observing:
When I call the ADBGDDL stored procedure I get this error:
Errore SQL [42815]: [jcc][10143][10845][4.26.14] parametro non valido 5: il parametro non è impostato né registrato. ERRORCODE=-4461, SQLSTATE=42815
which, translated, should sound more or less as:
SQL Error [42815]: [jcc][10143][10845][4.26.14] parameter 5 is invalid: parameter is not set nor registered. ERRORCODE=-4461, SQLSTATE=42815

According to [documentation](https://www.ibm.com/docs/en/db2admintool/12.1.0?topic=engineering-adbgddl-stored-procedure), parameter 5 should be an output parameter.

#### Steps to reproduce, if exist:
`CALL ADBGDDL('IX','<qualifier>','<table_name>','',?,?,'');`
Where `<qualifier>` and `<table_name>` should be replaced with values that match a qualifier and table_name existing in your environment.
Keep in mind that the ADBGDDL stored procedure is installed by the "DB2 Administration Tool" software, which is not part of standard z/OS DB/2 installations.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-01 12:20:59.042
!MESSAGE Errore SQL [42815]: [jcc][10143][10845][4.26.14] parametro non valido 5: il parametro non è impostato né registrato. ERRORCODE=-4461, SQLSTATE=42815
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-01 12:20:59.042
!MESSAGE Errore SQL [42815]: [jcc][10143][10845][4.26.14] parametro non valido 5: il parametro non è impostato né registrato. ERRORCODE=-4461, SQLSTATE=42815
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-09-01 12:20:59.042
!MESSAGE [jcc][10143][10845][4.26.14] parametro non valido 5: il parametro non è impostato né registrato. ERRORCODE=-4461, SQLSTATE=42815
!STACK 0
com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10143][10845][4.26.14] parametro non valido 5: il parametro non è impostato né registrato. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:116)
	at com.ibm.db2.jcc.am.k5.bH(k5.java:6382)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4219)
	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
	at com.ibm.db2.jcc.am.d0.execute(d0.java:273)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:339)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Cris70** [comment]
Sorry, the stored procedure is not defined in the system (I thought it was).
Nevertheless, the error returned is weird. QMF correctly returns "The stored procedure STSDB2.ADBGDDL could not be found."
