### ISSUE TITLE
"No procedure found" (sqlcode=-440) error executing stored procedure

### ISSUE THREAD

**Issue by Cris70** [dbeaver/dbeaver#13770]
#### System information: 
- Linux openSuse Tumbleweed 20210830
- DBeaver 21.2.0.202108291732

#### Connection specification:
- Database name and version: DB/2 for z/OS v12
- Driver name: jdbc version 4.26.14
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, ssh

#### Describe the problem you're observing:
When I call the STSDB2.ADB2RE stored procedure I get this error:
Errore SQL [42884]: NO AUTHORIZED PROCEDURE NAMED STSDB2.ADB2RE HAVING COMPATIBLE ARGUMENTS WAS FOUND. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14

The procedure does exist, and it works correctly when called from QMF with the same invocation.

#### Steps to reproduce, if exist:
`CALL STSDB2.ADB2RE('db2sys=''DB2T'',db2serv=''REMT'',gendb=''N'',gents=''N'',gentable=''Y'',genindex=''Y'';',
            'type=''TB'',own=''ANA'',name=''TXMANSI''',
            'SQL_OUTFLAG=''RS'';',
            'RPT_OUTFLAG=''RS'';',
            '', ?);`
You have to change parameters with something that makes sense in your environment.
Keep in mind that the ADB2RE stored procedure is installed by the "DB2 Administration Tool" software, which is not part of standard z/OS DB/2 installations.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-02 13:11:01.485
!MESSAGE Errore SQL [42884]: NO AUTHORIZED PROCEDURE NAMED STSDB2.ADB2RE HAVING COMPATIBLE ARGUMENTS WAS FOUND. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-02 13:11:01.485
!MESSAGE Errore SQL [42884]: NO AUTHORIZED PROCEDURE NAMED STSDB2.ADB2RE HAVING COMPATIBLE ARGUMENTS WAS FOUND. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-09-02 13:11:01.485
!MESSAGE NO AUTHORIZED PROCEDURE NAMED STSDB2.ADB2RE HAVING COMPATIBLE ARGUMENTS WAS FOUND. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14
!STACK 0
com.ibm.db2.jcc.am.SqlSyntaxErrorException: NO AUTHORIZED PROCEDURE NAMED STSDB2.ADB2RE HAVING COMPATIBLE ARGUMENTS WAS FOUND. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.b(k4.java:2471)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2452)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:914)
	at com.ibm.db2.jcc.t4.ab.f(ab.java:156)
	at com.ibm.db2.jcc.t4.p.e(p.java:81)
	at com.ibm.db2.jcc.t4.av.k(av.java:175)
	at com.ibm.db2.jcc.am.k4.ao(k4.java:2413)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4686)
	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
	at com.ibm.db2.jcc.am.d0.execute(d0.java:273)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:339)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
#13747

**Comment by Cris70** [comment]
> #13747

I'm sorry @uslss I don't think I get what you're saying.
Why did you mention my other issue?
They are two different things, otherwise I would have simply added a comment to the other issue.
Would you mind elaborating?

**Comment by uslss** [comment]
The issues were linked due to their relation to db2 z/os. 
unfortunately, we've got no env to test and investigate the issue.
Probably, you could check possible causes for this error
https://www.ibm.com/docs/en/db2-for-zos/11?topic=sec-440

**Comment by Cris70** [comment]
Thank you @uslss 
I believe -440 is not the real error, as QMF can correctly invoke the stored procedure with the exact same call.
Is there something peculiar in the way DBeaver invokes the stored procedure?
If you need a tester on z/OS I am available.
