### ISSUE TITLE
Athena: search field in header filter returns an error

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13784]
#### System information: 
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version Athena

#### Steps to reproduce, if exist:
1. Open column value filter
2. Type anything in search field

**Expected:** Values are filtered according to search
**Actual:** Error is returned

![GlHI10TrDV](https://user-images.githubusercontent.com/82543000/131959023-a0a33666-2fa1-40ce-bec7-8bbf2f438842.gif)

#### Include any warning/errors/backtraces from the logs
```
com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. [ErrorCategory:USER_ERROR, ErrorCode:SYNTAX_ERROR], 
Detail:SYNTAX_ERROR: line 1:1: Incorrect number of parameters: expected 1 but found 0 [Execution ID: ddbd9812-d8e2-4129-9075-10e56dffa668]
	at com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.<init>(Unknown Source)
	at com.simba.athena.athena.dataengine.AJDataEngine.prepare(Unknown Source)
	at com.simba.athena.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.simba.athena.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.athena.jdbc42.AJ42PreparedStatement.<init>(Unknown Source)
	at com.simba.athena.athena.jdbc42.AJJDBC42ObjectFactory.createPreparedStatement(Unknown Source)
	at com.simba.athena.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:406)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:231)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.lambda$0(GenericFilterValueEdit.java:344)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.readEnumeration(GenericFilterValueEdit.java:342)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:633)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
```

**Comment by Matvey16** [comment]
Verified
