### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication

### ISSUE THREAD

**Issue by liyk-dev** [dbeaver/dbeaver#13790]
#### System information: 
- Windows10 x86*64
- DBeaver 21.2.0
- eclipse rcp 202103

#### Describe the problem you're observing:
i use eclipse run dbeaver source code is not work, org.jkiss.dbeaver.ui.app.standalone was unable to load class org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.

#### Include any warning/errors/backtraces from the logs

!SESSION 2021-09-03 17:22:41.543 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product
Command-line arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product -data C:\Users\*\eclipse-workspace/../runtime-DBeaver.product(1) -dev file:C:/Users/*/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product (1)/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2021-09-03 17:22:44.661
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.jkiss.dbeaver.ui.app.standalone was unable to load class org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
Caused by: java.lang.ClassNotFoundException: org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication cannot be found by org.jkiss.dbeaver.ui.app.standalone_21.2.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 16 more
An error has occurred. See the log file

**Comment by ShadelessFox** [comment]
Hello @liyk-dev,

Something is wrong with your development environment.

Please refer to our technical documentation:
https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

**Comment by liyk-dev** [comment]
still no work， I use the following button to debug，but the message is missing packages.
<img width="803" alt="capture_20210906102135402" src="https://user-images.githubusercontent.com/16267209/132151664-8754e991-05a9-4fb8-8a06-d47a068180d7.png">
After I added the package to the Contents TAB, I didn't notice that the package was missing, but the program failed.  
<img width="793" alt="capture_20210906102600075" src="https://user-images.githubusercontent.com/16267209/132151921-029b5211-4746-414e-b5ea-24d1a62851ea.png">
Have the latest document to email 343015913@qq.com

**Comment by ShadelessFox** [comment]
Have you installed software from our repo http://dbeaver.io/eclipse-repo/? Looks like you're missing dependencies.
