### ISSUE TITLE
Comment for foreign table can't be deleted

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13805]
As a continuation of #13406

#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.0

#### Connection specification:
- Database name and version PostgreSQL 12

#### Steps to reproduce, if exist:
1. Create a foreign table with a comment
2. Erase a comment through the UI
3. Save changes

**Expected:** Comment is deleted
**Actual result:** Error is returned

![aXUuyouxp8](https://user-images.githubusercontent.com/82543000/132200952-d5d26324-0438-40fe-8a5b-e70922b41833.gif)

```
Couldn't generate alter script

Reason:
class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableForeign cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular (org.jkiss.dbeaver.ext.postgresql.model.PostgreTableForeign and org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2309c88e)

java.lang.ClassCastException: class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableForeign cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular (org.jkiss.dbeaver.ext.postgresql.model.PostgreTableForeign and org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @658f1261)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableManager.generateAlterActions(PostgreTableManager.java:154)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableManager.addObjectModifyActions(PostgreTableManager.java:145)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectChangeCommand.getPersistActions(SQLObjectEditor.java:295)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$4(EntityEditor.java:509)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
