### ISSUE TITLE
Composite Type values cannot be added via UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13804]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.1

#### Connection specification:
- Database name and version postgresql

#### Describe the problem you're observing:
Composite Type values cannot be changed via UI
1. Create a table with composite type column
```sql
create type x as (a int, b int);

create table test (composite_value x not null primary key);

insert into test (composite_value) values (row (1, 2)), (row (2, 3)), (row (4, 5));
```
2. Disable Show Complex column structure option
3. Try to add new element to composite value using value panel

```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Mon Sep 06 12:03:51 MSK 2021
Unhandled event loop exception

java.lang.ClassCastException: class org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$CompositeField cannot be cast to class org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$ArrayItem (org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$CompositeField and org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$ArrayItem are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1ec5e85e)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$AddElementAction.run(ComplexObjectEditor.java:858)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

**Comment by uslss** [comment]
verified
