### ISSUE TITLE
DBeaver doesn't work with OpenSSH keys

### ISSUE THREAD

**Issue by logicalup** [dbeaver/dbeaver#13801]
#### System information: 
- Operating system (distribution) and version: MacOs 11.5.2
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version: 
- Driver name: JSCH
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSH

#### Describe the problem you're observing:
When using ED25519 Open SSH key, the default JSCH errors out with message "Invalid key". Continuing from #5845 

#### Steps to reproduce, if exist:
Create an openssh ed25519 key pair, put the public key on server, try using dbeaver to connect to server using the private key.
Now try again after installing SSHJ and switching to it in advanced settings on the ssh tab, or just ssh command in terminal, and it will work just fine. 

#### Include any warning/errors/backtraces from the logs
```
2021-09-05 12:39:33.262 - Connect with 'digitalocean' (mariaDB-17b45a6f0cc-44e7a9a411fcc46b)
2021-09-05 12:39:33.267 - Adding identity key
2021-09-05 12:39:33.271 - Attempting to convert an unsupported key into suitable format
2021-09-05 12:39:33.322 - Connection failed (mariaDB-17b45a6f0cc-44e7a9a411fcc46b)
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:911)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Cannot add identity key
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:70)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	... 14 more
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@419d3174
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey0(SSHImplementationJsch.java:243)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey(SSHImplementationJsch.java:226)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:68)
	... 17 more
2021-09-05 12:39:33.379 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:911)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Cannot add identity key
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:70)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	... 14 more
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@419d3174
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey0(SSHImplementationJsch.java:243)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey(SSHImplementationJsch.java:226)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:68)
	... 17 more
2021-09-05 12:39:33.417 - Cannot add identity key
org.jkiss.dbeaver.DBException: Cannot add identity key
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:70)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:223)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@419d3174
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey0(SSHImplementationJsch.java:243)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.addIdentityKey(SSHImplementationJsch.java:226)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:68)
	... 17 more
```

**Comment by logicalup** [comment]
Continuing from #5845
the current workaround and solution of using the ssh-keygen to convert openssh key to rsa key doesn't work because it doesn't convert elliptical keys like ED25519 which is one of the standard/recommended type of keys now.
(Example Gitlab recommendation of ED25519 keys: https://docs.gitlab.com/ee/ssh/index.html#ed25519-ssh-keys)

**Workaround**
Install SSHJ (and reinstall it every DBeaver update)

**Proposed solution**
include SSHJ with dbeaver by default, so that user doesn't have to install SSHJ every single update.

**Comment by logicalup** [comment]
@ShadelessFox please add if i missed anything.

**Comment by pedzed** [comment]
Installing SSHJ worked for me (I followed the steps described in https://devimalplanet.com/how-to-dbeaver-remote-database-ssh#method-2-dbeaver-with-encrypted-openssh-private-key-file).

Is there something wrong with using SSHJ as default? If not, it would be nice to finally add it after having people bringing this issue up for at least two years.

If not, at the very minimum, the error message "`invalid privatekey: [B@7696c31f`" should be clearer.

**Comment by ShadelessFox** [comment]
Hello @DevJackSmith,

Can you please provide the very first line contained inside your private key file? The line contains a special header describing format in which key is stored.

**Comment by pedzed** [comment]
@ShadelessFox Using `ssh-keygen -t ed25519`:
```
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by ShadelessFox** [comment]
Thanks.

**Comment by ShadelessFox** [comment]
@pedzed can you try converting it manually using `ssh-keygen -p -f path/to/your/key -m pem` to see if it helps? Make sure you're using JSCH implementation.

**Comment by pedzed** [comment]
Perhaps the original poster would be willing.

I am satisfied with SSHJ, which solved my problem. All I would like to see is that it would be installed and preferably chosen by default.

**Comment by ShadelessFox** [comment]
Thanks anyway.

Unfortunately, we can't ship SSHJ by default because it depends on several libraries that are just too big to include.

**Comment by logicalup** [comment]
so then we need to find another way for dbeaver to use ED25519 format, which is quickly becoming the default format for ssh keys. It's very easy to create one in case you want to experiment with it: `ssh-keygen -t ed25519` (then add the new public key to any of your servers and try to connect to it using dbeaver with new private key). See my steps to reproduce in the description of this issue.

**Comment by logicalup** [comment]
the other way to ~fix~ workaround this is not to delete SSHJ when installing new version, or reinstall it automatically and make it default upon first run. (but this would still be a workaround rather than a fix, since new users will still get this error and not be able to use ssh keys by default)

**Comment by logicalup** [comment]
converting it as you asked for doesn't work, i also mention that in the description: https://github.com/dbeaver/dbeaver/issues/13801#issuecomment-913205219

**Comment by ShadelessFox** [comment]
Ah, missed that, sorry. Thanks for reply. Seems like JSCH does not support ED25519 (some googling confirmed that).

The idea of backing up installed extensions is really cool and we want to implement it in the future, and looks like this is the one real solution of this problem.

For now, the workaround is already known.

**Comment by logicalup** [comment]
1. backing up installed extension is not a solution, as it won't fix the issue for new installs
2. the current workaround is **really really really annoying**, one has to reinstall (which takes good 20 steps) every single time there's an update to DBeaver.

Not sure how to explain the weight of breaking DBeaver every single time there's an update.
Every release that doesn't include a fix for this is a broken release.

**Comment by ShadelessFox** [comment]
I created a separate issue about bundling SSHJ by default. See #14635
