### ISSUE TITLE
Raise an UnsupportedOperationException when write a sql of create materialzed view

### ISSUE THREAD

**Issue by inpool** [dbeaver/dbeaver#13834]
When I write a sql as below:

```sql
create materialized view view_name as select id from m -- raise exception now!
```

Exception info:
```
java.lang.UnsupportedOperationException: Not supported yet.
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:751)
	at net.sf.jsqlparser.statement.create.view.CreateView.accept(CreateView.java:36)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1205)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1172)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:1086)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:785)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:283)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:98)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:82)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:330)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

while the session data as:
```
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```

DBeaver version is 21.2.0.202108310918. I had tried the Oracle jdk and the exception remain.

**Comment by ShadelessFox** [comment]
Hello @inpool,

Thanks for report. Is this only affects the auto-completion feature?

**Comment by inpool** [comment]
It is, so far. in fact, I just update from version 20.0.0 one hour ago which has no problem.

**Comment by ShadelessFox** [comment]
Did the auto-completion feature work in this exact case before the update?

**Comment by inpool** [comment]
yes, it works before the update.

**Comment by ShadelessFox** [comment]
We'll look into it.

**Comment by LonwoLonwo** [comment]
Still reproducible in DBeaver 21.3.3
