### ISSUE TITLE
Connection error on SSHJ tunnel

### ISSUE THREAD

**Issue by dsimon-dev** [dbeaver/dbeaver#13873]
#### System information: 
- Operating system (distribution) and version: Arch Linux
- DBeaver version: 21.2.0.202109041934
- Additional extensions:
  - dbeaver-plugin-sshj 1.0.78.202105160657-1
  - dbeaver-plugin-sshj-lib 0.27.3-2
  - dbeaver-plugin-bouncycastle 1.64.0.v20191109.0815-2

All installed from arch community repo.

openjdk version 16.0.2.u7-1

#### Connection specification:
- ~Database name and version~
- ~Driver name~
- Do you use tunnels or proxies (SSH, SOCKS, etc): SSHJ

#### Describe the problem you're observing:

Error when testing simple ssh connection:

![Screenshot_20210911_110946](https://user-images.githubusercontent.com/73468772/132942908-6063f7b7-3f40-4b07-b39c-b01b32c46bd4.png)

I remember the exact same connection working a few months ago, but I don't know what the dbeaver version was.

#### Include any warning/errors/backtraces from the logs

Error message:

```
Receiver class org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj does not define or inherit an implementation of the resolved method 'abstract void setupTunnel(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, org.jkiss.dbeaver.model.net.DBWHandlerConfiguration, org.jkiss.dbeaver.model.net.ssh.config.SSHHostConfiguration[], org.jkiss.dbeaver.model.net.ssh.config.SSHPortForwardConfiguration)' of abstract class org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.
```

Log file with stacktrace:

```
> Start DBeaver SSH tunnels UI [org.jkiss.dbeaver.net.ssh.ui 1.0.85.202109041934]
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.85.202109041934]
2021-09-11 11:19:53.502 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
> Start DBeaver SSH implementation (SSHJ) [org.jkiss.dbeaver.net.ssh.sshj 1.0.78.202105160657]
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.74.202109041934]
2021-09-11 11:19:57.068 - Receiver class org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj does not define or inherit an implementation of the resolved method 'abstract void setupTunnel(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, org.jkiss.dbeaver.model.net.DBWHandlerConfiguration, org.jkiss.dbeaver.model.net.ssh.config.SSHHostConfiguration[], org.jkiss.dbeaver.model.net.ssh.config.SSHPortForwardConfiguration)' of abstract class org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.
java.lang.AbstractMethodError: Receiver class org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj does not define or inherit an implementation of the resolved method 'abstract void setupTunnel(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, org.jkiss.dbeaver.model.net.DBWHandlerConfiguration, org.jkiss.dbeaver.model.net.ssh.config.SSHHostConfiguration[], org.jkiss.dbeaver.model.net.ssh.config.SSHPortForwardConfiguration)' of abstract class org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:218)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1682)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by ShadelessFox** [comment]
Hello @dsimon-dev,

Please update an SSHJ extension.

Go to <kbd>Help</kbd> &rArr; <kbd>Install New Software...</kbd>, then choose <kbd>DBeaver CE update site</kbd> from drop-down menu.

**Comment by dsimon-dev** [comment]
Hi!

Thanks for the suggestion, I uninstalled all dbeaver plugins from arch repos and tried to install the SSHJ extension like you described. Unfortunately I'm hit by another error:

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver SSHJ 1.0.85.202108291732 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.85.202108291732)
  Software currently installed: DBeaver 21.2.0 (org.jkiss.dbeaver.core.product 21.2.0)
  Only one of the following can be installed at once: 
    DBeaver Model Plug-in 1.0.51 (org.jkiss.dbeaver.model 1.0.51)
    DBeaver Model 1.0.153.202108291732 (org.jkiss.dbeaver.model 1.0.153.202108291732)
  Cannot satisfy dependency:
    From: DBeaver 21.2.0 (org.jkiss.dbeaver.ce.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [21.2.0,21.2.0]
  Cannot satisfy dependency:
    From: DBeaver Core 21.2.0 (org.jkiss.dbeaver.core.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.model [1.0.51,1.0.51]
  Cannot satisfy dependency:
    From: DBeaver 21.2.0 (org.jkiss.dbeaver.core.product 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [21.2.0,21.2.0]
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.85.202108291732 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.85.202108291732)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group 0.0.0
  Cannot satisfy dependency:
    From: DBeaver Runtime 21.2.0.202108291732 (org.jkiss.dbeaver.runtime.feature.feature.group 21.2.0.202108291732)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.model [1.0.153.202108291732,1.0.153.202108291732]
  Cannot satisfy dependency:
    From: DBeaver Standalone 21.2.0 (org.jkiss.dbeaver.standalone.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.core.feature.feature.group [21.2.0,21.2.0]
```

**Comment by ShadelessFox** [comment]
Try upgrading to early access version: https://dbeaver.io/files/ea/

**Comment by bradmccormack** [comment]
I don't really understand why, but a recent update must have broken my SSHJ tunnel too.

What fixed it for me was simply uninstalling the OS packages

> sudo pacman -Rs dbeaver-plugin-sshj dbeaver-plugin-sshj-lib

In my case. I didn't look into it deeply, but it might help.

**Comment by ShadelessFox** [comment]
Hello @bradmccormack,

Thanks for the info.

The SSHJ extension is not broken, we have updated our codebase to support jump servers and this also affected SSHJ extension. Since it's not bundled, it caused compatibility errors and thus it was important to update it.

**Comment by ghost** [comment]
Hello I have the same problem after update, I follow the steps but can't fixed it, any suggestion?

Also I unistall dbeaver-plugin-sshj dbeaver-plugin-sshj-lib but it's the same

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver SSHJ 1.0.85.202108291732 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.85.202108291732)
  Software currently installed: DBeaver 21.2.0 (org.jkiss.dbeaver.core.product 21.2.0)
  Only one of the following can be installed at once: 
    DBeaver Model Plug-in 1.0.51 (org.jkiss.dbeaver.model 1.0.51)
    DBeaver Model 1.0.153.202108291732 (org.jkiss.dbeaver.model 1.0.153.202108291732)
  Cannot satisfy dependency:
    From: DBeaver 21.2.0 (org.jkiss.dbeaver.ce.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.standalone.feature.feature.group [21.2.0,21.2.0]
  Cannot satisfy dependency:
    From: DBeaver Core 21.2.0 (org.jkiss.dbeaver.core.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.model [1.0.51,1.0.51]
  Cannot satisfy dependency:
    From: DBeaver 21.2.0 (org.jkiss.dbeaver.core.product 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.ce.feature.feature.group [21.2.0,21.2.0]
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.85.202108291732 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.85.202108291732)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.runtime.feature.feature.group 0.0.0
  Cannot satisfy dependency:
    From: DBeaver Runtime 21.2.0.202108291732 (org.jkiss.dbeaver.runtime.feature.feature.group 21.2.0.202108291732)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.model [1.0.153.202108291732,1.0.153.202108291732]
  Cannot satisfy dependency:
    From: DBeaver Standalone 21.2.0 (org.jkiss.dbeaver.standalone.feature.feature.group 21.2.0)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.core.feature.feature.group [21.2.0,21.2.0]
```

**Comment by dsimon-dev** [comment]
I don't know, I'll just wait for the Arch maintainer to update the plugins since I don't urgently need the functionality.

**Comment by dsimon-dev** [comment]
Arch Linux upgraded the packages which fixed this issue.

**Comment by MartinMCodazzi** [comment]
This just happened to me, trying to connect to a container. I have the lastest version (25.1.0.202506011722) available on windows 11 24H2 running on a week old notebook (I didn't tweak it too much).
**I just turned off the wifi card** (I'm also connected by a LAN cable to the same network). Seems like DBeaver doesn't like to have more than one way to reach a host (I know, probably it's a windows route thing)
