### ISSUE TITLE
Access Postgres database object without permissions causes lockup in DBeaver 

### ISSUE THREAD

**Issue by rnemana** [dbeaver/dbeaver#13918]
#### System information: 
- Operating system (distribution) and version: 
-- OS Name	Microsoft Windows Server 2016 Datacenter
-- Version	10.0.14393 Build 14393

- DBeaver version: 21.2.0.202108291732
- Additional extensions: None

#### Connection specification:
- Database name and version:  Postgres 11.12
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

If I double click on a database object for which I have no permissions, DBeaver hangs and cannot recover. No message etc. seems to pop up and I have to reboot DBeaver.  Also, works does not get saved. (quite frustrating).

#### Steps to reproduce, if exist:

- Create a database object as a superuser (e.g. create table)
- logout and login as a different account with NO privileges on the object
- attempt to access the database object by double-clicking on it in the navigation pane on the left
- you should see that DBeaver hangs
- It must be forced to close and rebooted to get back to the DB

#### Include any warning/errors/backtraces from the logs
```java
!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-15 14:05:56.020
!MESSAGE SQL Error [42501]: ERROR: permission denied for materialized view mv_procedure
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-15 14:05:56.020
!MESSAGE SQL Error [42501]: ERROR: permission denied for materialized view mv_procedure
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-09-15 14:05:56.020
!MESSAGE ERROR: permission denied for materialized view mv_procedure
!STACK 0
org.postgresql.util.PSQLException: ERROR: permission denied for materialized view mv_procedure
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
@rnemana unfortunately, cannot reproduce an issue. permission denied error is shown, but dbeaver doesn't hang. probably some special steps are needed?
![image](https://user-images.githubusercontent.com/31996417/133576494-d7c3d45c-88db-4b0f-9b35-7d2143306007.png)

**Comment by rnemana** [comment]
hmm.... interesting. Let me see if I can reproduce and I'll get back to  you.  Meanwhile, I'll close this. I don't want it to pollute your open ticket  queue.
