### ISSUE TITLE
[HANA] Wrong schema used on update table data

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#13956]
#### System information: 
- Win10, DBeaver CE 21.2.1

#### Connection specification:
- SAP HANA
- 
#### Describe the problem you're observing:
Can't add new data in non-default schema - query for adding a new row always contains the name of the default scheme

#### Steps to reproduce, if exist:
Try to save new data in schema that is not default and you'll get an error

#### Include any warning/errors/backtraces from the logs
```
Error synchronizing data with database

Reason:
SQL Error [461] [HY000]: SAP DBTech JDBC: [461]: foreign key constraint violation: TrexColumnUpdate failed on table 'SYSTEM:NEWTABLE' with error: Only found 0 of 1 rows from SYSTEM:NEWTABLE(COLUMN1) in SYSTEM:NEWTABLE_1(COLUMN1), rc=1535
```

```
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [461]: foreign key constraint violation: TrexColumnUpdate failed on table 'SYSTEM:NEWTABLE' with error: Only found 0 of 1 rows from SYSTEM:NEWTABLE(COLUMN1) in SYSTEM:NEWTABLE_1(COLUMN1), rc=1535
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4692)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:2010)
	at com.sap.db.jdbc.PreparedStatementSapDB._execute(PreparedStatementSapDB.java:3169)
	at com.sap.db.jdbc.PreparedStatementSapDB._execute(PreparedStatementSapDB.java:2286)
	at com.sap.db.jdbc.PreparedStatementSapDB.execute(PreparedStatementSapDB.java:636)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:310)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:178)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:775)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:697)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:634)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified.
related issue #14046
