### ISSUE TITLE
Virtual foreign keys break when changing project navigator view preset from advanced to simple

### ISSUE THREAD

**Issue by ivanlonel** [dbeaver/dbeaver#13981]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 20H2
- DBeaver version: 21.2.1
- Additional extensions: Office support, git support, SSHJ, Debug and SVG

#### Connection specification:
- Database name and version: Postgresql 12.4
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
If I create virtual foreign keys on views while on advanced database navigator preset, they work as intended until I change the preset to simple. After that, they seem to lose the reference to the target table.

Upon examining .dbeaver/data-sources.json, I believe I found the reason. The entity URI is different for virtual foreign keys created on advanced and on simple. On advanced, the "entity" json element inside "foreign-keys" has this format:

`database://postgres-jdbc-17c0a78e57b-204d1f0a81d345ce/ajustes2021sbt/org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema/restrito/org.jkiss.dbeaver.ext.postgresql.model.PostgreTable/municipio`

Creating the same virtual key on simple, it ends up looking like this:

`database://postgres-jdbc-17c0a78e57b-204d1f0a81d345ce/ajustes2021sbt/restrito/municipio`

So, if I'm guessing it right, the virtual key breaks because DBeaver doesn't expect to find the names of the Java classes in the entity URI when the simple navigator preset is active.

#### Steps to reproduce, if exist:

1. Edit an existing connection and change its navigator view to the "advanced" preset, if it isn't already (it might work the same on custom by leaving both "Show only schemas and tables" and "Hide folders" unchecked)
2. Open a database view from that connection and, inside the "Properties" upper tab, go to the "Virtual" lateral tab
3. Click on "Add" in the Virtual Foreign Keys quadrant and create a valid virtual foreign key to another table.
4. Edit the connection again and change its navigator view to the "simple" preset, (it might work the same on custom by checking both "Show only schemas and tables" and "Hide folders")
5. Open the view where you created the virtual foreign key. You should be able to verify it doesn't point to the target table.

#### Include any warning/errors/backtraces from the logs

`!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-22 09:46:11.233
!MESSAGE Can't find reference node database://postgres-jdbc-17c0a78e57b-204d1f0a81d345ce/ajustes2021sbt/org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema/restrito/org.jkiss.dbeaver.ext.postgresql.model.PostgreTable/municipio for virtual foreign key
!STACK 0
org.jkiss.dbeaver.DBException: Can't find reference node database://postgres-jdbc-17c0a78e57b-204d1f0a81d345ce/ajustes2021sbt/org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema/restrito/org.jkiss.dbeaver.ext.postgresql.model.PostgreTable/municipio for virtual foreign key
	at org.jkiss.dbeaver.model.virtual.DBVEntityForeignKey.getRealReferenceConstraint(DBVEntityForeignKey.java:158)
	at org.jkiss.dbeaver.model.virtual.DBVEntityForeignKey.getReferencedConstraint(DBVEntityForeignKey.java:95)
	at org.jkiss.dbeaver.ui.editors.data.VirtualStructureEditor.createForeignKeyItem(VirtualStructureEditor.java:389)
	at org.jkiss.dbeaver.ui.editors.data.VirtualStructureEditor.refreshVisuals(VirtualStructureEditor.java:124)
	at org.jkiss.dbeaver.ui.editors.data.VirtualStructureEditor$1.lambda$0(VirtualStructureEditor.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)`

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
Hello @ivanlonel,

Thanks for the investigation.

As you can see, we store the absolute path to a node that represents a given object in the navigator tree. Without that, it might be impossible to locate an object a relative or, let's say, a more lenient path points to.

Moreover, the connection view can be configured for your desire, making node paths even more unpredictable.

Unfortunately, there is no easy way to resolve this issue.

**Comment by ivanlonel** [comment]
Hi @ShadelessFox,

I thought the URI created from the simple preset was just an abbreviated form of the one created from the advanced preset, but somehow pointing to the same entity, and that this was dissociated from the actual path shown in the navigator tree. So I had the wrong impression it was just a matter of standardizing the URIs to always look the same, even on custom connection views.

Thanks for your analysys and your explanation!
