### ISSUE TITLE
support 64 bit mysqldump

### ISSUE THREAD

**Issue by tiny-pangolin** [dbeaver/dbeaver#14041]
#### System information: 
- Operating system (distribution) and version windows
- DBeaver version 21.2
- Java version bundled
- Additional extensions none

#### Connection specification:
- Database name and version percona mysql 8.0
- Driver name mysql mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
Cannot use mysqldump with mysql 8 with default password setup because of caching_sha2_password is the default and isn't supported with the built in mysqldump.exe and it appears that you cannot download the mysql 8 binaries and use those because they are 64 bit. I attempted to add in newer mysqldump.exes but they were not recognized

#### Steps to reproduce, if exist:
1. connect to percona for mysql 8 database with default password setup 
2. dump a database from that server

#### Include any warning/errors/backtraces from the logs

Task 'MySQL dump' started at Mon Sep 27 11:44:06 CDT 2021
mysqldump: Got error: 2059: Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.

when trying to connect

Task 'MySQL dump' finished at Mon Sep 27 11:44:06 CDT 2021
2021-09-27 11:44:06.880 - IO error: Process failed (exit code = 2). See error log.
2021-09-27 11:44:06.881 - java.io.IOException: Process failed (exit code = 2). See error log.
at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by Matvey16** [comment]
@tiny6996 Can you please describe how were you adding you own local mysql binaries? I tried reproducing your issue and 64bit mysql client worked for me.

**Comment by uslss** [comment]
there is no update on the issue. If it is still actual for you - feel free to reopen it with additional info
