### ISSUE TITLE
Public schema cannot be set as a default

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14046]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.2

#### Connection specification:
- Database name and version SAP Hana

#### Describe the problem you're observing:
Cannot save Public schema as a default or create some object in it.

Set as default:
![image](https://user-images.githubusercontent.com/31996417/135241525-ea864ef1-5d35-4034-bec6-eaa8e53e2571.png)

On table create:
![image](https://user-images.githubusercontent.com/31996417/135241483-32978bd8-6431-4150-b0f5-fcc145aec1b1.png)

```
eclipse.buildId=unknown
java.version=16.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Sep 29 12:25:05 MSK 2021
SAP DBTech JDBC: [362]: invalid schema name: PUBLIC: line 1 col 12 (at pos 11)

com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [362]: invalid schema name: PUBLIC: line 1 col 12 (at pos 11)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4692)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:2010)
	at com.sap.db.jdbc.PreparedStatementSapDB._prepare(PreparedStatementSapDB.java:3031)
	at com.sap.db.jdbc.PreparedStatementSapDB._doParse(PreparedStatementSapDB.java:2911)
	at com.sap.db.jdbc.PreparedStatementSapDB.<init>(PreparedStatementSapDB.java:166)
	at com.sap.db.jdbc.PreparedStatementSapDB9.<init>(Unknown Source)
	at com.sap.db.jdbc.HanaPreparedStatement.<init>(Unknown Source)
	at com.sap.db.jdbc.HanaPreparedStatementClean.<init>(Unknown Source)
	at com.sap.db.jdbc.HanaPreparedStatementClean.newInstance(Unknown Source)
	at com.sap.db.jdbc.ConnectionSapDB9._prepareStatement(Unknown Source)
	at com.sap.db.jdbc.ConnectionSapDB.prepareStatement(ConnectionSapDB.java:357)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:312)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:294)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:1)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerSetDefaultObject.lambda$1(NavigatorHandlerSetDefaultObject.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerSetDefaultObject.lambda$0(NavigatorHandlerSetDefaultObject.java:81)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:58)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by LonwoLonwo** [comment]
That's because the PUBLIC schema in HANA is not the usual schema.
We have a special ticket for this case: https://github.com/dbeaver/dbeaver/issues/10263
I will add them in next releases.
