### ISSUE TITLE
error in post connect step should not lead to unusable connection

### ISSUE THREAD

**Issue by kai-morich** [dbeaver/dbeaver#14064]
at 09:16 I connected with recent DBeaver to a HANA instance. As the test licence was expired, some of the post connect SQL statement failed, as shown in dbeaver log:

```
!ENTRY org.jkiss.dbeaver.model 2 0 2021-09-30 09:16:19.713
!MESSAGE Can't fetch database data types: SQL-Fehler [437] [HY000]: SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state

!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.799
!MESSAGE Can't read schema list
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.799
!MESSAGE SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
!STACK 0
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4573)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1944)
	at com.sap.db.jdbc.PreparedStatementSapDB._prepare(PreparedStatementSapDB.java:3031)
	at com.sap.db.jdbc.PreparedStatementSapDB._doParse(PreparedStatementSapDB.java:2911)
	at com.sap.db.jdbc.PreparedStatementSapDB.<init>(PreparedStatementSapDB.java:166)
	at com.sap.db.jdbc.CallableStatementSapDB.<init>(CallableStatementSapDB.java:51)
	at com.sap.db.jdbc.CallableStatementSapDB9.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.newInstance(Unknown Source)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5075)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5069)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB.getSchemas(DatabaseMetaDataSapDB.java:3373)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:1125)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:186)
	at org.jkiss.dbeaver.ext.hana.model.HANAMetaModel.loadSchemas(HANAMetaModel.java:75)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:550)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.810
!MESSAGE Error initializing datasource
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.810
!MESSAGE SQL-Fehler [437] [HY000]: SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.810
!MESSAGE SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
!STACK 0
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4573)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1944)
	at com.sap.db.jdbc.PreparedStatementSapDB._prepare(PreparedStatementSapDB.java:3031)
	at com.sap.db.jdbc.PreparedStatementSapDB._doParse(PreparedStatementSapDB.java:2911)
	at com.sap.db.jdbc.PreparedStatementSapDB.<init>(PreparedStatementSapDB.java:166)
	at com.sap.db.jdbc.CallableStatementSapDB.<init>(CallableStatementSapDB.java:51)
	at com.sap.db.jdbc.CallableStatementSapDB9.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.newInstance(Unknown Source)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5075)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5069)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB.getSchemas(DatabaseMetaDataSapDB.java:3373)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:1125)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:186)
	at org.jkiss.dbeaver.ext.hana.model.HANAMetaModel.loadSchemas(HANAMetaModel.java:75)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:550)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.997
!MESSAGE SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-09-30 09:16:19.997
!MESSAGE SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
!STACK 0
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [437]: only commands for license handling are allowed in current state
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4573)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1944)
	at com.sap.db.jdbc.PreparedStatementSapDB._prepare(PreparedStatementSapDB.java:3031)
	at com.sap.db.jdbc.PreparedStatementSapDB._doParse(PreparedStatementSapDB.java:2911)
	at com.sap.db.jdbc.PreparedStatementSapDB.<init>(PreparedStatementSapDB.java:166)
	at com.sap.db.jdbc.CallableStatementSapDB.<init>(CallableStatementSapDB.java:51)
	at com.sap.db.jdbc.CallableStatementSapDB9.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.<init>(Unknown Source)
	at com.sap.db.jdbc.InternalCallableStatementSapDB.newInstance(Unknown Source)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5075)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB._newCallableStatement(DatabaseMetaDataSapDB.java:5069)
	at com.sap.db.jdbc.DatabaseMetaDataSapDB.getSchemas(DatabaseMetaDataSapDB.java:3373)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:1125)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:186)
	at org.jkiss.dbeaver.ext.hana.model.HANAMetaModel.loadSchemas(HANAMetaModel.java:75)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:550)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
when trying to execute some SQL to set new license (e.g. `SELECT * FROM M_LICENSE`) at 09:18 it fails with:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-09-30 09:18:30.862
!MESSAGE Disconnected from database
```
I would prefer if errors from post connect actions are shown, but leave the connection in a usable state.
If I remember correctly, this worked in the past.

**Comment by kai-morich** [comment]
To reproduce this issue you can recreate a user, where these post connect statements will fail for other reason (intentionally missing privilege on SCHEMAS view):
```
CREATE RESTRICTED USER TEST1234 PASSWORD Abcd1234 NO FORCE_FIRST_PASSWORD_CHANGE;
ALTER USER TEST1234 ENABLE CLIENT CONNECT;
```

**Comment by Matvey16** [comment]
@kai-morich  Thank you for the report
