### ISSUE TITLE
some mongo query syntax not support

### ISSUE THREAD

**Issue by Korov** [dbeaver/dbeaver#14062]
#### System information: 
- Operating system (distribution) and version: `Windows 10 Pro`
- DBeaver version: `Version 21.2.0.202109061154`
- Additional extensions

#### Connection specification:
- Database name and version: `Mongo 4.4.8`
- Driver name: 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : `NO`

#### Describe the problem you're observing:

query syntax: `db.getCollection("seen_urls").stats(1024*1024);`

error info:
```
org.jkiss.dbeaver.model.exec.DBCException: FROM keyword missing
	at com.dbeaver.db.mongodb.exec.sql.MongoCustomStatement.parseSelect(MongoCustomStatement.java:196)
	at com.dbeaver.db.mongodb.exec.sql.MongoCustomStatement.makeQueryFromString(MongoCustomStatement.java:156)
	at com.dbeaver.db.mongodb.exec.sql.MongoCustomStatement.executeStatement(MongoCustomStatement.java:78)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

query syntax: `db.getCollection("seen_urls").skip(db.getCollection("seen_urls").count() - 20);`

error info:
```
org.jkiss.dbeaver.model.exec.DBCException: TypeError: Cannot find function skip in object {}. (js#1)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:65)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3440)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot find function skip in object {}. (js#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4280)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4258)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4291)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4310)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4382)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2584)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2566)
	at org.mozilla.javascript.gen.js_7._c_script_0(js:1)
	at org.mozilla.javascript.gen.js_7.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.js_7.call(js)
	at org.mozilla.javascript.gen.js_7.exec(js)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1234)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.runInRhino(MongoJSProcessor.java:115)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.eval(MongoJSProcessor.java:90)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:55)
	... 12 more

```

**Comment by uslss** [comment]
it wasn't implemented yet.
Thanks for the suggestion

**Comment by ShadelessFox** [comment]
Hello @Korov,

1. I cannot reproduce this problem.
2. There's no `skip` function on collection object, it's a function of cursor. You have to retrieve results first (e.g. using `.find()`)

Can you please test against the early access version? https://dbeaver.com/files/ea/

**Comment by Skydiveroid** [comment]
We still cannot reproduce this problem.
