### ISSUE TITLE
Setting format for string column as "Numeric" breaks the data editor

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14084]
#### System information: 
- Win 10, DBeaver CE 21.2.2

#### Describe the problem you're observing, steps to reproduce:
1. Open table with String column
2. Open context menu and set Numeric formatting (View/Format -> Set "column" format -> Numeric)

And now some actions like expanding Panels or clicking in data editor may cause this:
![image](https://user-images.githubusercontent.com/43252954/135580233-62adbb50-2b7f-455e-8b64-c077bf5a03f3.png)

https://user-images.githubusercontent.com/43252954/135581501-8b6947ef-29a4-49fb-929f-f63233b77bfa.mp4

#### Include any warning/errors/backtraces from the logs
```
java.lang.NumberFormatException: For input string: "2007-02-03 00:00:00"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at org.jkiss.dbeaver.model.impl.data.transformers.NumericAttributeTransformer$NumericValueHandler.parseValue(NumericAttributeTransformer.java:119)
	at org.jkiss.dbeaver.model.impl.data.transformers.NumericAttributeTransformer$NumericValueHandler.getValueDisplayString(NumericAttributeTransformer.java:93)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellState(SpreadsheetPresentation.java:1941)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridCellRenderer.isOverLink(GridCellRenderer.java:198)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleCellHover(LightGrid.java:3972)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleHovering(LightGrid.java:3558)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseMove(LightGrid.java:3397)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
```

**Comment by uslss** [comment]
verified
