### ISSUE TITLE
Git extension error

### ISSUE THREAD

**Issue by Philippe-M** [dbeaver/dbeaver#14092]
#### System information: 
- Fedora 33 64bits
- DBeaver version : 21.2.1202109181446 
- Additional extensions : Dbeaver git support

#### Describe the problem you're observing:
When I click on a view linked to git (git staging for example) I have this error:

```
java.lang.Exception
	at org.eclipse.ui.internal.ViewReference.createErrorPart(ViewReference.java:115)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:101)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:304)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:405)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:332)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:109)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5996)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.showStack(TrimStack.java:994)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.lambda$3(TrimStack.java:402)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5996)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.workbench.UIEvents.publishEvent(UIEvents.java:388)
	at org.eclipse.e4.ui.workbench.UIEvents.publishEvent(UIEvents.java:356)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:626)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:786)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:679)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:674)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack$2.widgetSelected(TrimStack.java:510)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5879)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5121)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4599)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
```

```
#### Include any warning/errors/backtraces from the logs
2021-10-01 12:16:14.753 - Create display
2021-10-01 12:16:14.893 - DBeaver 21.2.1.202109181446 is starting
2021-10-01 12:16:14.894 - OS: Linux 5.13.16-100.fc33.x86_64 (amd64)
2021-10-01 12:16:14.894 - Java version: 11.0.11 by AdoptOpenJDK (64bit)
2021-10-01 12:16:14.894 - Install path: '/app/dbeaver'
2021-10-01 12:16:14.894 - Instance path: 'file:/home/xxxxx/.local/share/DBeaverData/workspace6/'
2021-10-01 12:16:14.894 - Memory available 64Mb/1024Mb
2021-10-01 12:16:14.913 - Starting RMI server at 32897
2021-10-01 12:16:14.970 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.100.v20210315-1604]
> Start Services d’application d’Eclipse [org.eclipse.e4.core.services 2.2.600.v20210110-1654]
> Start Services Eclipse UI Application [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start XMI EMF [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Prise en charge de Thème CSS SWT d’Eclipse [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Add-ons du Workbench Eclipse e4 [org.eclipse.e4.ui.workbench.addons.swt 1.4.200.v20210321-1910]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.100.v20210515-1815]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.0.v20201119-1132]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.200.v20210401-1241]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.80.202109181446]
2021-10-01 12:16:16.650 - Configure workbench window
> Start Noyau du système d'aide [org.eclipse.help 3.9.0.v20210507-0822]
2021-10-01 12:16:16.736 - Create actions
2021-10-01 12:16:16.742 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-10-01 12:16:16.743 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-10-01 12:16:16.743 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
Warning: NLS unused message: actions_ContentAssistProposal_description in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_dangerous_sql_message in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_dangerous_sql_title in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_dangerous_sql_toggleMessage in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_mass_parallel_sql_message in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_mass_parallel_sql_title in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_mass_parallel_sql_toggleMessage in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_fetch_all_rows_message in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_fetch_all_rows_title in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_fetch_all_rows_toggleMessage in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_keep_statement_open_message in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_keep_statement_open_title in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: confirm_keep_statement_open_toggleMessage in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_connection_driver in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_connection_edit_driver_button in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_connection_wizard_final_checkbox_save_password_locally in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: pref_page_database_general_group_navigator in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_connection_edit_connection_settings_variables_hint_label in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_connection_edit_wizard_conn_conf_network_link in: org.jkiss.dbeaver.core.CoreResources
2021-10-01 12:16:17.282 - Initialize workbench window
2021-10-01 12:16:17.289 - Finish initialization
Warning: NLS unused message: pref_page_database_general_label_sync_editor_connection_with_navigator in: org.jkiss.dbeaver.ui.internal.UINavigatorMessages
Warning: NLS unused message: pref_page_database_general_label_sync_editor_connection_with_navigator_tip in: org.jkiss.dbeaver.ui.internal.UINavigatorMessages
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.65.202109181446]
> Start Java Authentication and Authorization Service (JAAS) Equinox [org.eclipse.equinox.security 1.3.600.v20210126-1005]
> Start IHM de gestion des connexions Internet [org.eclipse.ui.net 1.4.0.v20210426-0838]
> Start Gestion des connexions Internet [org.eclipse.core.net 1.3.1100.v20210424-0724]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.55.202109181446]
2021-10-01 12:16:18.032 - Loading user drivers configuration from '/home/xxxxxx/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2021-10-01 12:16:18.041 - Total database drivers: 90 (90)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.65.202109181446]
> Start Éditeur de texte par défaut [org.eclipse.ui.editors 3.14.100.v20210513-1110]
> Start Cadre applicatif d’édition de texte [org.eclipse.ui.workbench.texteditor 3.16.100.v20210512-1009]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.65.202109181446]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.102.202109181446]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.71.202109181446]
Warning: NLS unused message: Voir in: org.eclipse.ui.internal.editors.text.TextEditorMessages
> Start Application principale (core) du support d'équipe [org.eclipse.team.core 3.9.0.v20210510-1748]
> Start Interface utilisateur du composant de collaboration [org.eclipse.team.ui 3.9.0.v20210426-0837]
> Start Support de l’interface graphique d’approvisionnement Equinox [org.eclipse.equinox.p2.ui 2.7.100.v20210426-1115]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.7.0.v20210315-2042]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.6.0.v20210315-2228]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.7.0.v20210328-0514]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.6.0.v20210331-1610]
> Start Support de la mise à jour de la plateforme par approvisonnement Equinox [org.eclipse.equinox.p2.ui.sdk 1.2.0.v20210114-1214]
> Start Equinox Provisioning Director [org.eclipse.equinox.p2.director 2.5.0.v20210325-0750]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.4.0.v20210315-2228]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.5.100.v20210329-1206]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.25.202109181446]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20210910133426]
> Start Interface utilisateur par défaut de la sécurité Equinox [org.eclipse.equinox.security.ui 1.3.0.v20210121-0947]
> Start Moteur du support de comparaison [org.eclipse.compare.core 3.6.1000.v20201020-1107]
> Start Support de comparaison [org.eclipse.compare 3.8.0.v20210415-0713]
> Start Vue journal [org.eclipse.ui.views.log 1.2.1500.v20210315-1034]

```

**Comment by Matvey16** [comment]
@Philippe-M Can you provide more clear steps to reproduce this issue?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info.
