### ISSUE TITLE
SQL script editor bug when delete

### ISSUE THREAD

**Issue by lutischan-ferenc** [dbeaver/dbeaver#14187]
#### System information: 
- Win 10
- 21.2.2.202110030714
- Additional extensions -

#### Connection specification:
- Postgresql 13
- org.postgresql.Driver (42.2.20)

#### Describe the problem you're observing:
1. E.g. "SELECT id, c1, c2, c3 FROM table;" from SQL script window.
2. select a row and mark it for delete.
3. browse over the row limit (e.g. 200)
4. press "save"
5. the row doesn't deleted

**Comment by Matvey16** [comment]
@lutischan-ferenc Thank you for the report

**Comment by Matvey16** [comment]
Happens not only with row deletion, but also if value in any cell was changed. After fetching additional rows, all of the changes are automatically reverted and the script with changes appears empty, so saving it does nothing. Reproducible in data editor.

**Comment by ShadelessFox** [comment]
1. The confirmation dialog pops up after data is fetched:
![image](https://user-images.githubusercontent.com/35821147/146428242-cb3b5e02-9846-417d-9c3a-9049061290dd.png)

2. The confirmation dialog can't be closed by pressing `Cancel`:
![jexsbXi5f8](https://user-images.githubusercontent.com/35821147/146428471-8355d801-492e-4aba-9c1f-71530c20097e.gif)

**Comment by ShadelessFox** [comment]
1. The confirmation dialog pops up several times after pressing `Yes`, effectively performing `UPDATE` every time:
![R7aF1Ngqr7](https://user-images.githubusercontent.com/35821147/147105603-6eb6fa2f-d9d4-451a-a36a-74b4ba6515b3.gif)

2. The confirmation dialog pops up for the second time after pressing either `No` or `Cancel`:
![hekEjf85kZ](https://user-images.githubusercontent.com/35821147/147105707-709bd3a3-6795-47ed-ba5e-b4d53b1039e3.gif)

3. After pressing `Cancel` no more data could be loaded, refresh doesn't do anything:
![zKpzb7yiYs](https://user-images.githubusercontent.com/35821147/147106207-26cb9c5e-c5db-4e00-a50d-d2a3dbcd0db9.gif)

**Comment by Matvey16** [comment]
1. Pressing cancel in a prompt leads to errors in fetch buttons
```
org.eclipse.core.commands.NotEnabledException: Trying to execute the disabled command org.jkiss.dbeaver.core.resultset.fetch.page
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:479)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:268)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```
2. Resultset can't be refreshed (refresh button will do nothing) if there are pending changes
3. `Fetch all rows` opens another prompt (that it is expensive operation) and when accepted fetches all rows canceling any changes

**Comment by Matvey16** [comment]
Now cancelling the prompt disables any ability to fetch more rows. Only refresh resets this
After pressing fetch all rows no matter if the changes are saved or not, nothing will be fetched
![dbeaver_Ax1DwzFusz](https://user-images.githubusercontent.com/82543000/150159436-92cfb951-420e-436e-a185-0c8c917fb398.gif)
![dbeaver_Fl2KDYBELQ](https://user-images.githubusercontent.com/82543000/150159456-320bc40e-1a2d-47f4-b877-30835fa1cd3a.gif)

**Comment by Matvey16** [comment]
Verified
