### ISSUE TITLE
Can't step maven plugin connectors.

### ISSUE THREAD

**Issue by Constantine9527** [dbeaver/dbeaver#14256]
![image](https://user-images.githubusercontent.com/20188341/137419713-d0f9ae7d-f54c-436e-b5a7-61c3a0a6fa94.png)

In the refences [https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse](url)  Step 10, It's get errors ,
`No marketplace entries found to handle maven-clean-plugin:2.5:clean in Eclipse.  Please see Help for more information.`

If I ignore these errors, When I run app like :
![image](https://user-images.githubusercontent.com/20188341/137419425-642bba7f-7356-4310-bac4-03f8f689ddb1.png)
It is not work , 

> !SESSION 2021-10-15 09:48:11.793 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.7
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=zh_CN_#Hans
Framework arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product
Command-line arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product -data /Users/blank/dev/eclipse-workspace/../runtime-DBeaver.product -dev file:/Users/blank/dev/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog
........
!ENTRY org.eclipse.osgi 4 0 2021-10-15 09:48:14.199
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:246)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

Does anyone know how to solve it? Thank you very much!

**Comment by ShadelessFox** [comment]
Hello @Constantine9527,

What's the Eclipse version?

**Comment by Constantine9527** [comment]
> Hello @Constantine9527,
> 
> What's the Eclipse version?
The version is  
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

Thank you for your help.

![image](https://user-images.githubusercontent.com/20188341/137652124-d6908e5c-cb21-48d8-9ea0-f5b10e977e81.png)

**Comment by ShadelessFox** [comment]
Try following:

Go to <kbd>Window</kbd> &rArr; <kbd>Preference</kbd> &rArr; <kbd>Maven</kbd> &rArr; <kbd>Installation</kbd> and choose your own maven installation folder there.
