### ISSUE TITLE
Improve array support

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#14255]
**Is your feature request related to a problem? Please describe.**
When `ResultSet.getObject(...)` returns a nested array like `new int[][] {new int[] {1,2,3}, new int[] {1,2}}`(instead of wrapper `java.sql.Array`), DBeaver will report below error. Similar issue happens when you try array of Map/Collection etc.
```
org.jkiss.dbeaver.model.exec.DBCException: Can't resolve array element data type
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:326)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:68)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3462)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Describe the solution you'd like**
Support nested array and arbitrary types, for examples: wrapper objects in addition to primitives, and containers like Map/Collection etc.

**Describe alternatives you've considered**
Fall back to String using `Arrays.deepToString(Object[])`?

**Additional context**
I'm testing new version of JDBC driver for ClickHouse. Most of nested structures are supported now, but some of them are not displayed correctly on DBeaver.

**Comment by ShadelessFox** [comment]
Hello @zhicwu,

I'm confused by the information provided in the <kbd>Additional context</kbd> block.

Is problem with array types present in new version of driver? Please provide up-to-date information.

**Comment by zhicwu** [comment]
Hi @ShadelessFox, I mean most of nested data types like `Nested`, `Tuple`, `Map`, `Array`, Geo types, and mixed use of them(e.g. `Tuple(Array(Map(String, UInt8)))` etc.) are all supported in the upcoming new version of ClickHouse JDBC driver. However, I met two issues when testing on DBeaver 21.2:
1) when a column's type is `java.sql.Types.Array`, returning an array(primitive or not) from `resultSet.getObject` will end up with above exception
   Yes, the value has to be wrapped as `java.sql.Array`, or the mapped type should be changed to `Other` so that DBeaver will call `getString` method instead. But why not call `getArray` instead of `getObject`?
2) even with a wrapper, `Array(Map(String, UInt8))` won't work, because the value is `Map[]` in this case, and apparently it could be more complex than that... I think below two are similar cases:
   - #10334
   - #14010

From what I observed, DataGrip uses `getString`, but we know that it's inefficient. I'm wondering if DBeaver should be enhanced to support these scenarios, or maybe you have different thought/suggestion?

**Comment by ShadelessFox** [comment]
Thanks for both technical and detailed explanation.

We use `getObject` instead of `getArray` because some drivers simply don't like the latter and prefer returning array via `getObject`.

**Comment by zhicwu** [comment]
FYI, despite from the version, ClickHouse JDBC driver 0.3.2 is a complete rewrite with some features(e.g. more metadata, fake transaction support, and standard UPDATE/DELTE statements etc.) for better JDBC compliance.

In v[0.3.2-test1](https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-test1), the first test build for public testing, `ResultSet.getObject()` returns a `java.sql.Array`, so that DBeaver can recognize. However, in a formal release, actually starting from next test build, it will return array object directly. As I mentioned above, it's better to call `getArray()` instead in DBeaver.

Update: there are two connection properties can be used to change the driver's behavior:
1. `wrapperObject` - whether to use wrapper object like java.sql.Array or java.sql.Struct, default to `false`. This impacts `ResultSet.getObject()`
2. `typeMappings` - comma separated mappings betweeen ClickHouse data type and fully qualified Java class name. This impacts `ResultSet.getObject(Class<?>)`.

**Comment by ShadelessFox** [comment]
That's a useful information, thank you.

**Comment by zhicwu** [comment]
Please check below example for array of tuple:

https://github.com/ClickHouse/clickhouse-jdbc/blob/179527258d8456f10d9ea96512c0345500325eb5/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L199-L224

It's somehow rendered as below in DBeaver Version 21.3.2.202112261636:
![image](https://user-images.githubusercontent.com/4270380/147750506-2b057764-7ed6-49d8-9077-e424225ba627.png)

It should be `[('a', 'b')]`.

**Comment by ShadelessFox** [comment]
Looks a bit better now against the new driver:
![java_ap7bFYYqq9](https://user-images.githubusercontent.com/35821147/158810829-45a2ec0b-2570-47f9-95e8-f84fc7d3cc2b.png)

**Comment by Matvey16** [comment]
It doesn't work when complex column is set to compact view

https://user-images.githubusercontent.com/82543000/160625925-b9891978-af11-4774-86f2-359cb95b71d7.mp4

**Comment by Matvey16** [comment]
Enhancement added in #16010
