### ISSUE TITLE
function pg_get_functiondef(oid) does not exist

### ISSUE THREAD

**Issue by robert-kuropkat** [dbeaver/dbeaver#14297]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: Version 21.2.3.202110151816
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 7.4.19 on i686-redhat-linux-gnu, compiled by GCC gcc (GCC) 4.1.2 20070626 (Red Hat 4.1.2-14)
- Driver name: PostgreSQL (old)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

When I select a Store Procedure and try to view the source I get the following display in the source window:

/* ERROR WHILE READING SOURCE:

SQL Error [42883]: ERROR: function pg_get_functiondef(oid) does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.
*/

If I try selecting Procedure Parameters I get a pop-dialog with the following message:

SQL Error [0A000]: Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.
  Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.
  Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.

If I try looking at Triggers, I get the following:

SQL Error [42703]: ERROR: column "action_timing" does not exist
  ERROR: column "action_timing" does not exist
  ERROR: column "action_timing" does not exist

#### Steps to reproduce, if exist:

1. Find a really, stupidly old database badly in need of upgrading (eg. PostgreSQL 7.4)
2.  Create connection with PostgreSQL (Old) driver (fewer errors)
3. Attempt to view Procedures or Triggers

#### Include any warning/errors/backtraces from the logs

Trying to view Source of a Stored Procedure (the log file for just this action was almost 4,000 lines long and I don't see how to add an attachment.  Tell me if you need more than the snippet below):

!ENTRY org.jkiss.dbeaver.model 4 0 2021-10-19 16:01:55.423
!MESSAGE Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-10-19 16:01:55.423
!MESSAGE Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.
!STACK 0
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunctionColumns(String, String, String, String) is not yet implemented.
	at org.postgresql.Driver.notImplemented(Driver.java:714)
	at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getFunctionColumns(AbstractJdbc4DatabaseMetaData.java:88)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctionColumns(JDBCDatabaseMetaDataImpl.java:238)
	at org.jkiss.dbeaver.ext.generic.model.GenericProcedure.loadProcedureColumns(GenericProcedure.java:134)
	at org.jkiss.dbeaver.ext.generic.model.GenericProcedure.getParameters(GenericProcedure.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:935)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:978)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:587)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:457)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:226)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:269)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
@robert-kuropkat what driver version do you use?

**Comment by robert-kuropkat** [comment]
@uslss I am using Version 9,2-1004-jdbc41.  I saw that recommendation in issue #6609

**Comment by robert-kuropkat** [comment]
The pg_get_functiondef() function seems to have not appeared in PostgreSQL until v8.4.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the info. 
This is not a bug, this is enhancement. We just do not support so old PostgreSQL version now. We can try to support it in the future.

**Comment by LonwoLonwo** [comment]
Query for procedures/functions definitions reading changed for old PG driver old PG database version.

![2022-03-14 22_49_17-DBeaver 22 0 0 - insert_data](https://user-images.githubusercontent.com/45152336/158250123-7870f80a-86db-4dda-b184-7318f4bca818.png)

"action_timing" column removed for the old PG database versions from the triggers reading statement.

**Comment by uslss** [comment]
verified
