### ISSUE TITLE
Unable to execute any Update statement on MS SQL Server (XML parsing error)

### ISSUE THREAD

**Issue by gregid** [dbeaver/dbeaver#14306]
#### System information: 
- Win 10 Pro
- DBeaver version: 21.2.3.202110151816
- Additional extensions
  - Darkest Dark Theme
  - DBeaver Debug extension
  - DBeaver Git integration
  - DBeaver Office integration
  - DBeaver SSHJ extension
  - DBeaver SVG format support

#### Connection specification:
- Database name and version: MS SQL Server 2019 (15.0 RTM)
- Driver name: MS SQL Server / SQL Server (mssql-jdbc:RELEASE [9.2.0.jre8])
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Unable to execute any Update statement - it errors with:
```
SQL Error [9436] [S0001]: XML parsing: line 1, character 54, end tag does not match start tag
```
#### Steps to reproduce, if exist:

Any update statement that runs in SQL Server Management Studio, like:
```sql
UPDATE [MYDB].[MYSCHEMA].[MyTable]
SET [MyColumn] = 'New Text' 
WHERE [MyId] = 119
```

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-10-20 10:17:14.220
!MESSAGE SQL Error [9436] [S0001]: XML parsing: line 1, character 54, end tag does not match start tag
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-10-20 10:17:14.220
!MESSAGE SQL Error [9436] [S0001]: XML parsing: line 1, character 54, end tag does not match start tag
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-10-20 10:17:14.220
!MESSAGE XML parsing: line 1, character 54, end tag does not match start tag
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: XML parsing: line 1, character 54, end tag does not match start tag
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3462)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
@gregid does this happen on any table? Can you give a DDL of the table on which you get this error?

**Comment by uslss** [comment]
there is no update on issue. If it is still actual - feel free to reopen it with additional info
