### ISSUE TITLE
postgresql custom types (nested composite, enum) not supported in various editor functions

### ISSUE THREAD

**Issue by fvannee** [dbeaver/dbeaver#14314]
DBeaver 21.2.3

Recent DBeaver versions have improved composite type support for Postgresql quite a bit, but there are still broken things unfortunately.
The following features in the editor do not work for nested composite types:
- 'Generate SQL -> INSERT'
- 'Duplicate Row'
In previous versions, this didn't work for any composite type, so there's definitely been an improvement here already (#13351, #13102) but the nested composite types seem to have been overlooked in these improvements.

To reproduce:
```
create schema test;
create type test.ct as (a int, b int);
create type test.ct2 as (a test.ct, b int);
create table test.t1 (a int, b test.ct2);
insert into test.t1 (a, b.a.a) (values (1, 1));
-- now disconnect and connect so that dbeaver refreshes the metadata cache
select * from test.t1;
-- now right click on a row and choose 'Generate SQL -> INSERT'
```

This still generates incorrect syntax (array syntax for a composite type):
```
INSERT INTO test.t1
(a, b)
VALUES(1, '("[1, null]",)');
```

A second problem arises when using enums inside a schema. Consider the following:
```
create type test.en as enum ('ab', 'bc');
create table test.t3 (a int, b test.en);
insert into test.t3 (values (1, 'ab'));
-- now disconnect and connect so that dbeaver refreshes the metadata cache
select * from test.t3;
-- now right click on a row and choose 'Generate SQL -> INSERT'
```

This generates the following SQL (note the missing schema qualifier before `en`):
```
INSERT INTO test.t3
(a, b)
VALUES(1, 'ab'::en);
```

**Comment by uslss** [comment]
thanks for the report

**Comment by fvannee** [comment]
Thanks! I have one additional bug that I'm posting in the same thread as it's about the same problems with composite types. This test case is about arrays inside composite types:

```
create type ct1 as (a int[]);
create table t1 (a int, b ct1);
insert into t1 (a, b.a) (values (1, array[1]));
-- disconnect & connect so that dbeaver refreshes metadata cache

select * from t1;
-- now right click on a row and choose 'Generate SQL -> INSERT'
-- dbeaver generates the following, which errors
INSERT INTO public.t1
(a, b)
VALUES(1, '("[''1'']")');

SQL Error [22P02]: ERROR: malformed array literal: "['1']"
  Detail: "[" must introduce explicitly-specified array dimensions.
  Position: 42
```

**Comment by phillip-haydon** [comment]
I just upgraded to the latest version (21.2.5.202111141807)

```
org.jkiss.dbeaver.model.exec.DBCException: Error converting string to composite type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Composite type 'providertype' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:130)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:104)
	... 16 more
```

Can no longer see postgresql enums in the output. 

![image](https://user-images.githubusercontent.com/895629/141722383-4d6529e9-67c7-43c3-94f3-820208c0311d.png)

Reproduced it by creating new enum, table with id / name, insert some records, select it back out, get the above error.

**Comment by LonwoLonwo** [comment]
Hello @phillip-haydon 

> Can no longer see postgresql enums in the output.

Can you provide type and table DDL examples, please?

**Comment by phillip-haydon** [comment]
```
drop table if exists public.test_table;
drop type if exists public.test_enum;

create type public.test_enum as enum ('One', 'Two');

create table public.test_table (
	id serial,
	name public.test_enum
);

insert into public.test_table(name) values ('One');

select * from public.test_table;
```

That's all I did to reproduce it. Just checked, happened with I ran it.

**Comment by LonwoLonwo** [comment]
@phillip-haydon 

Unfortunately, can't reproduce.

![2021-11-24 15_14_44-DBeaver Ultimate 21 3 0 - _postgres12local_ Script-176](https://user-images.githubusercontent.com/45152336/143236717-85399d66-1fb6-4785-8224-8c2a9f8af862.png)

And what about data presentation for test_table in the Data Viewer? Is there a problem there?

**Comment by phillip-haydon** [comment]
Hmmm, let me re-install tomorrow (it's 8:30pm and I'm tired). I upgraded from a very old version of DBeaver. Maybe it's just bunged. 

Will let you know. Thanks for checking.

**Comment by phillip-haydon** [comment]
OK Sorry, been busy and slipped my mind.

I completely wiped DBeaver off the computer, re-installed from scratch, and it turns out it works fine.

So I fired up my laptop, I haven't used DBeaver in like 2 years on there (I should have got the version I upgraded from, but I didn't think about it), it worked fine, I upgraded to latest, it broke... So I completely uninstalled, and re-installed, and it works fine again.

So.... I've never had something like this happen before.

**Comment by LonwoLonwo** [comment]
@phillip-haydon 

Ok, Thanks for the investigation.

**Comment by LonwoLonwo** [comment]
- SQL Insert statement for custom types fixed (data wrapping)
- Fully qualified names returned for custom data types

**Comment by fvannee** [comment]
Thanks a lot! This is awesome. Am I correct that this fixes the "composite inside another composite" (first case) and "schema-qualified enum" (second case), but that the third case (quoted below) is still open?


> Thanks! I have one additional bug that I'm posting in the same thread as it's about the same problems with composite types. This test case is about arrays inside composite types:
> 
> ```
> create type ct1 as (a int[]);
> create table t1 (a int, b ct1);
> insert into t1 (a, b.a) (values (1, array[1]));
> -- disconnect & connect so that dbeaver refreshes metadata cache
> 
> select * from t1;
> -- now right click on a row and choose 'Generate SQL -> INSERT'
> -- dbeaver generates the following, which errors
> INSERT INTO public.t1
> (a, b)
> VALUES(1, '("[''1'']")');
> 
> SQL Error [22P02]: ERROR: malformed array literal: "['1']"
>   Detail: "[" must introduce explicitly-specified array dimensions.
>   Position: 42
> ```

**Comment by ShadelessFox** [comment]
Hello @fvannee,

Yes, it is still open.

**Comment by Matvey16** [comment]
Verified
