### ISSUE TITLE
Connection to Amazon EC2 cloud with an existing PostgreSQL, An I/O error occured while sending to the backend

### ISSUE THREAD

**Issue by SiHaoShen** [dbeaver/dbeaver#14345]
#### System information: 
- Ubuntu 20.04
- DBeaver 21.2.3

#### Connection specification:
- MacOpsTestDb
- PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes I use Putty and tunnels to access EC2 and RDS

#### Describe the problem you're observing:
I have tried to connect the databank under Linux VM and also Win10, and unfortunately, it throws out the I/O error see below.
It fails to connect and force to close the connection when it starts to read database meta data.
My other colleague has the same setup and configuration, and can successfully connect to the database. 

#### Include any warning/errors/backtraces from the logs
```
2021-10-21 21:00:36.351 - Connect with 'MacOpsTestDb' (postgres-jdbc-17ca406b8e3-79ec4d46ef895155)
2021-10-21 21:00:36.352 - Execution context opened (MacOpsTestDb; Main <MacOpsTestDb>; 12)
2021-10-21 21:00:36.352 - Initiate connection to PostgreSQL database [MacOpsTestDb@localhost] for Main <MacOpsTestDb>
2021-10-21 21:00:36.810 - Execution context opened (MacOpsTestDb; Metadata <MacOpsTestDb>; 13)
2021-10-21 21:00:36.811 - Initiate connection to PostgreSQL database [MacOpsTestDb@localhost] for Metadata <MacOpsTestDb>
2021-10-21 21:00:49.768 - Context [MacOpsTestDb::Main <MacOpsTestDb>] check failed: Connection is dead
2021-10-21 21:00:49.825 - Execution context closed (MacOpsTestDb, 12)
2021-10-21 21:00:49.825 - Initiate connection to PostgreSQL database [MacOpsTestDb@localhost] for Main <MacOpsTestDb>
2021-10-21 21:00:56.508 - Error reading SQL keywords: An I/O error occurred while sending to the backend.
2021-10-21 21:00:56.510 - Error reading PostgreSQL version: This connection has been closed.
2021-10-21 21:00:56.512 - Error initializing datasource
org.jkiss.dbeaver.DBException: SQL Error [08003]: This connection has been closed.
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:659)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:381)
               at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
               at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
               at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
               at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1734)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:635)
               ... 5 more
2021-10-21 21:00:56.513 - Connection failed (postgres-jdbc-17ca406b8e3-79ec4d46ef895155)
org.jkiss.dbeaver.DBException: SQL Error [08003]: This connection has been closed.
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:659)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:381)
               at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
               at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
               at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
               at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1734)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:635)
               ... 5 more
2021-10-21 21:00:56.560 - Execution context closed (MacOpsTestDb, 13)
2021-10-21 21:00:56.560 - Initiate connection to PostgreSQL database [MacOpsTestDb@localhost] for Metadata <MacOpsTestDb>
2021-10-21 21:00:56.568 - Datasource MacOpsTestDb invalidate failed: [ERROR, ERROR]
2021-10-21 21:00:56.619 - Execution context closed (MacOpsTestDb, 12)
2021-10-21 21:00:56.620 - Execution context closed (MacOpsTestDb, 13)
2021-10-21 21:00:56.620 - org.jkiss.dbeaver.DBException: SQL Error [08003]: This connection has been closed.
org.jkiss.dbeaver.DBException: SQL Error [08003]: This connection has been closed.
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:659)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:381)
               at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
               at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
               at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
               at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1734)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:635)
               ... 5 more
2021-10-21 21:00:56.620 - This connection has been closed.
org.postgresql.util.PSQLException: This connection has been closed.
               at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1734)
               at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428)
               at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:635)
               at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initialize(PostgreDataSource.java:381)
               at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:925)
               at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
               at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
               at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
@SiHaoShen Are you and your colleague using the same user when trying to connect?

**Comment by SiHaoShen** [comment]
@Matvey16 Yes, indeed we are using the same aws account, due to security reasons the rds is not set as public.

**Comment by Matvey16** [comment]
@SiHaoShen Please, check that you have the same driver version and communicate with your system administraror to check that you firewall is not interrupting the connection.
