### ISSUE TITLE
localhost connection through ssh tunnel stop to work

### ISSUE THREAD

**Issue by williamespindola** [dbeaver/dbeaver#14365]
#### System information: 
- Ubuntu 20.04.3 LTS
- DBeaver 21.2.3.202110151816

#### Connection specification:
- mysql 5.7.29
- SSH 

#### Describe the problem you're observing:
The connection to mysql with user that works only via localhost via ssh tunner is returning "Access denied for user 'root'@'localhost' (using password: YES)"

This seems to be wrong password but not, from the server via localhost the username and pass works.

Previouslly this works. I had a connection set uped like this a long time ago I just delete this connection and at the new configuration using localhost through ssh tunnel don't work any more.

The ssh connection works fine the Test tunnel configuration returns success.

#### Steps to reproduce, if exist:
With user the connect only via localhost on the server create a new connection and at ssh tab configure the host/ip, username and the path for private key. 
![image](https://user-images.githubusercontent.com/794521/138579503-dc02196d-c041-4f91-a681-aaf7de5c6aa4.png)
At the main tab configure localhost for the server host default port and the user an password
![image](https://user-images.githubusercontent.com/794521/138579569-246825f0-cc35-4e7e-8940-d11ac15a53c1.png)
Test connection will return
Access denied for user 'root'@'localhost' (using password: YES)

#### Include any warning/errors/backtraces from the logs
<details>
<summary>Click to expand</summary>

```log
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Sun Oct 24 00:41:35 BRT 2021
Access denied for user 'root'@'localhost' (using password: YES)

java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:183)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:202)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:438)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:91)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:91)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:918)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
</details>

**Comment by Matvey16** [comment]
@williamespindola Can you try not typing anything in password tab and see what error will return?

**Comment by williamespindola** [comment]
Thanks guys it's working fine. Other person of the team changes root password.
