### ISSUE TITLE
Can't use SSH tunnel with RSA key without passphrase

### ISSUE THREAD

**Issue by vincentjdc** [dbeaver/dbeaver#14393]
#### System information: 
- Operating system (distribution) and version : Linux Mint 19.3 (Ubuntu 18.04)
- DBeaver version :  21.2.3.202110151816
- Additional extensions : no one

#### Connection specification:
- Driver name : MySQL & Maria DB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
I'm trying to connect to remote database through SSH with an RSA private key (~/.ssh/id_sa) without passphrase.
I'm getting the following error : `SSH_MSG_DISCONNECT: 2 Too many authentication failures`

NB : connecting using terminal or mysql workbench is working fine.
NB2 : Using "Password authentication" method to the same server is working in DBeaver

#### Steps to reproduce, if exist:
- Create a new connection to Maria DB or Mysql
    - setting the path to the id_rsa file `/home/<user>/.ssh/id_rsa`
    - leaving the passphrase empty with "save password" checked
- Try the connection and getting a popup that display the SSH_MSG_DISCONNECT error.

#### Include any warning/errors/backtraces from the logs

```!ENTRY org.jkiss.dbeaver.model 4 0 2021-10-26 11:47:26.177
!MESSAGE Cannot establish tunnel to ******:22
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-10-26 11:47:26.177
!MESSAGE Cannot establish tunnel to *******:22
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-10-26 11:47:26.177
!MESSAGE SSH_MSG_DISCONNECT: 2 Too many authentication failures 
!STACK 0
com.jcraft.jsch.JSchException: SSH_MSG_DISCONNECT: 2 Too many authentication failures 
	at com.jcraft.jsch.Session.read(Session.java:1004)
	at com.jcraft.jsch.UserAuthPassword.start(UserAuthPassword.java:91)
	at com.jcraft.jsch.Session.connect(Session.java:470)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:111)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)```

**Comment by Matvey16** [comment]
@vincentjdc Have you tried to use SSHJ implementation
![TuQBrqkFHT](https://user-images.githubusercontent.com/82543000/138863107-f9b61014-1dd9-4e3e-8a3c-42c934bbb3bd.png)
![dbeaver_tJfXLK0mE0](https://user-images.githubusercontent.com/82543000/138863123-ee10bac1-8bc3-4139-abd6-29a4b5bd2989.png)
![dbeaver_DXZWVKs2yd](https://user-images.githubusercontent.com/82543000/138863128-0ec2af92-5c35-40bc-a5a5-b158634b370b.png)
