### ISSUE TITLE
Exception when Query Sequence Nextval

### ISSUE THREAD

**Issue by qiqingli** [dbeaver/dbeaver#14406]
#### System information: 
- Operating system (distribution) and version: macOS 12.0.1
- DBeaver version: 21.2.3
- Additional extensions

#### Connection specification:
- Database name and version: MySQL 5.7.21
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Exception when executing statement to query sequence.nextval.
select T_BFM_AD_ID_SEQ.nextval;

The Exception Message  is as follows:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: 172.31.28.242:8921/O3PORTALDB_1 | Unknown table 'T_BFM_AD_ID_SEQ' in field list
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3462)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4718)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: 172.31.28.242:8921/O3PORTALDB_1 | Unknown table 'T_BFM_AD_ID_SEQ' in field list
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more

But querying with other database tools can return sequence.nextval normally!
![image](https://user-images.githubusercontent.com/20805098/139007351-3d296b8e-644e-41c6-be8e-4e8766718b5d.png)

**Comment by Matvey16** [comment]
@qiqingli Sorry, to me it looks like you are using Oracle function in MySQL database. Can you elaborate why you want to use NEXTVAL in MySQL?

**Comment by qiqingli** [comment]
@Matvey16 Need to get a serial value and use this value in multiple different tables as associated fields.

**Comment by LonwoLonwo** [comment]
@qiqingli 
What serial value? Can you provide your table DDL?

**Comment by Matvey16** [comment]
@qiqingli I think you need to use LAST_INSERT_ID() function in MySQL or `SELECT Auto_increment FROM information_schema.tables WHERE table_name='name_of_your_table';`

Also what is T_BFM_AD_ID_SEQ in your query? It can't be a sequence cause you can't create a sequence in MySQL. Can you show a DDL of that object?

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info
