### ISSUE TITLE
DBeaver unable to connect to Snowflake using external browser as authenticator

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14407]
It raises the error `!390400!`.

Sample stacktrace:

``` Java
net.snowflake.client.jdbc.SnowflakeSQLException: !390400!
        at net.snowflake.client.core.SessionUtilExternalBrowser.getSSOUrl(SessionUtilExternalBrowser.java:196)
        at net.snowflake.client.core.SessionUtilExternalBrowser.authenticate(SessionUtilExternalBrowser.java:221)
        at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:371)
        at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:284)
        at net.snowflake.client.core.SFSession.open(SFSession.java:446)
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:104)
        at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
        at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
        at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
        at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:172)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:183)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:202)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:135)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:107)
        at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:43)
        at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:95)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:918)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
Verified
