### ISSUE TITLE
Can't perform bulk import for files with Json data

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14411]
#### System information: 
- DBeaver version 21.2.3

#### Connection specification:
- Database name and version PostgreSQL 12

#### Steps to reproduce, if exist:
1. Export json data to csv file
2. Start import of this file with bulk load option

**Expected:** Data is imported
**Actual:** Data can't be exported because of error

```
org.postgresql.util.PSQLException: ERROR: extra data after last expected column
  Where: COPY json_data, line 1: "1,{ 'track': { 'segments': [ { 'location': [ 47.763, 13.4034 ], 'start time': '2018-10-14 10:05:14',..."

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1212)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1017)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:189)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:459)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:283)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:143)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by ShadelessFox** [comment]
JSON can't be serialized to CSV property

**Comment by robaidsahil** [comment]
Thanks for the great post. I would like to visit again your site.
[DBeaver Download](https://offlinesetups.com)

**Comment by hktalent** [comment]
Sad, can export json, but can't import json @tati-kru @dbeaver @Skydiveroid

**Comment by aamsur-933** [comment]
hai @tati-kru and teams.

why there is no milestone on this issue?

**Comment by arhayka** [comment]
Hi @aamsur-933 
There is no milestone on this issue because we are not planning to close it in the near future.
However, we will try to pay more attention to it. This seems like a useful feature.
