### ISSUE TITLE
Auto-refresh stops working but looks like it is still working

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14428]
#### System information: 
- DBeaver version 21.2.4

#### Describe the problem you're observing:
1. When auto-refresh stops because of error the icon doesn't change and still looks the same as if it is still working
2. Customizing auto-refresh to stop on error doesn't matter because it stops regardless.

#### Steps to reproduce, if exist:
1. Start autorefresh with custom time and `stop on error` unchecked
2. Enter invalid data (e.g. letters in timestamp column)
3. Agree to save changes when prompted

**Actual result:** Auto-refresh stops but refresh icon doesn't change
**Expected:** Auto-refresh doesn't stop if `stop on error` is unchecked. If it is checked the icon should change on auto-refresh stop.

![05aa3RFbGb](https://user-images.githubusercontent.com/82543000/139270173-8a0c391c-e4e1-48c4-9254-77941b22e6ea.gif)

**Comment by Matvey16** [comment]
Looks like a similar problem occurs when cancel is pressed after a prompt
![dbeaver_sDfC4GQOVT](https://user-images.githubusercontent.com/82543000/157910066-d74692e2-3437-4ee8-861f-3b86ffafcf5f.gif)

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:445)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:365)
	at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3671)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateToolbar(ResultSetViewer.java:1568)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateEditControls(ResultSetViewer.java:1551)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePanelsContent(ResultSetViewer.java:3459)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.checkForChanges(ResultSetViewer.java:3577)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.refreshData(ResultSetViewer.java:3673)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$1(ResultSetViewer.java:265)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshJob.run(AutoRefreshJob.java:42)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ShadelessFox** [comment]
This is a side-effect of #14187.

**Comment by Matvey16** [comment]
Verified
