### ISSUE TITLE
Fail to import maven project and debug in Eclipse

### ISSUE THREAD

**Issue by Cynyard999** [dbeaver/dbeaver#14450]
#### System information: 
- MacOS Big Sur 11.6 
- Eclipse IDE for RCP and RAP Developers Version: 2021-09 (4.21.0) Build id: 20210910-1417
- Apache Maven 3.6.3 
- Java SE 11.0.12

#### Describe the problem you're observing:

> `mvn package` can execute as expected and generate the right runnable application
>  And in Eclipse -> Preferences -> Maven -> Installations, the installation has been changed to local maven path

I followed the steps 1 to 10 in section [**Opening workspace in Eclipse**] on [Develop in Eclipse](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse)

But I could not get the corresponding window shown in the step 10. Instead, the Action parts were all set as **Resolve Later**. 

<img width="1092" alt="Screen Shot 2021-10-31 at 3 25 43 PM" src="https://user-images.githubusercontent.com/55020801/139630171-77886a40-acee-4351-baaf-353aaf6cf93b.png">

And if I ignored this step and continued importing, the project got plenty of **Errors** showing [**Plugin execution not covered by lifecycle configuration: ….**]. 

<img width="1779" alt="Screen Shot 2021-11-01 at 2 24 37 PM" src="https://user-images.githubusercontent.com/55020801/139630450-4030efcc-1d71-4812-a3ea-be689c9cfdb2.png">

And **debug** could not work properly, notifying [**The application could not start.**]

<img width="599" alt="Screen Shot 2021-11-01 at 2 28 52 PM" src="https://user-images.githubusercontent.com/55020801/139630921-93551201-6a9b-47b6-8233-d16a81e6fc94.png">

#### Include any warning/errors/backtraces from the logs

After debug failed, I got ~/runtime-DBeaver.product/.metadata/.log shown as below 

```
!SESSION 2021-11-01 11:36:34.423 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CN
Framework arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product
Command-line arguments:  -product org.jkiss.dbeaver.ui.app.standalone.product -data /Users/cynyard/eclipse-workspace/../runtime-DBeaver.product -dev file:/Users/cynyard/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

!ENTRY org.eclipse.m2e.core 4 0 2021-11-01 11:36:36.569
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.core [325]
  Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[30.1.0,32.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.m2e.core.ui 4 0 2021-11-01 11:36:36.573
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.m2e.core.ui [326]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.core; bundle-version="[1.16.0,2.0.0)"
    -> Bundle-SymbolicName: org.eclipse.m2e.core; bundle-version="1.18.1.20210614-1604"; singleton:="true"
       org.eclipse.m2e.core [325]
         Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[30.1.0,32.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.m2e.logback.appender 2 0 2021-11-01 11:36:36.604
!MESSAGE Could not resolve module: org.eclipse.m2e.logback.appender [327]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.core.ui; bundle-version="[1.16.0,2.0.0)"
    -> Bundle-SymbolicName: org.eclipse.m2e.core.ui; bundle-version="1.18.1.20210614-1604"; singleton:="true"
       org.eclipse.m2e.core.ui [326]
         Unresolved requirement: Require-Bundle: org.eclipse.m2e.core; bundle-version="[1.16.0,2.0.0)"
           -> Bundle-SymbolicName: org.eclipse.m2e.core; bundle-version="1.18.1.20210614-1604"; singleton:="true"
              org.eclipse.m2e.core [325]
                Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[30.1.0,32.0.0)"


!ENTRY org.eclipse.m2e.core 2 0 2021-11-01 11:36:36.605
!MESSAGE Could not resolve module: org.eclipse.m2e.core [325]
  Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[30.1.0,32.0.0)"


!ENTRY org.eclipse.m2e.core.ui 2 0 2021-11-01 11:36:36.606
!MESSAGE Could not resolve module: org.eclipse.m2e.core.ui [326]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.core; bundle-version="[1.16.0,2.0.0)"
    -> Bundle-SymbolicName: org.eclipse.m2e.core; bundle-version="1.18.1.20210614-1604"; singleton:="true"
       org.eclipse.m2e.core [325]
         Unresolved requirement: Require-Bundle: com.google.guava; bundle-version="[30.1.0,32.0.0)"


!ENTRY org.eclipse.osgi 4 0 2021-11-01 11:36:36.608
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.jkiss.dbeaver.ui.app.standalone was unable to load class org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication cannot be found by org.jkiss.dbeaver.ui.app.standalone_21.2.4.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:506)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 16 more
```

**Comment by LonwoLonwo** [comment]
So the problem is with Maven. Looks like your Eclipse can't recognize the right path to maven. Are you sure, that you changed your Maven version in Eclipse?

![2021-11-02 18_20_47-eclipse-workspace2021 - org jkiss dbeaver ui editors sql_src_org_jkiss_dbeaver_u](https://user-images.githubusercontent.com/45152336/139876624-5bc4c359-56fa-46d4-a2d4-7d91bb0c725a.png)
