### ISSUE TITLE
Active schema can't be changed for this kind of datasource

### ISSUE THREAD

**Issue by PENGCHENGLIN007** [dbeaver/dbeaver#14459]
#### System information: 
- Operating system (distribution) and version
  Windows 10 education edition
- DBeaver version
  21.0.3.202104181339

#### Connection specification:
- Database name and version
calcite avatica 1.21.0
- Driver name
org.apache.calcite.avatica.remote.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No
#### Describe the problem you're observing:
I use calcite avatica server proxy other database service,for example oracle,mysql,sqlserver,dameng and so on.
But I  can't change schema for mysql.

!ENTRY org.jkiss.dbeaver.model 2 0 2021-10-21 14:21:59.856
!MESSAGE Error while initializing context state
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2021-10-21 14:21:59.856
!MESSAGE Active schema can't be changed for this kind of datasource!
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Active schema can't be changed for this kind of datasource!
at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:311)
at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.refreshDefaults(GenericExecutionContext.java:331)
at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:201)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:148)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.(JDBCRemoteInstance.java:59)
at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:109)
at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.(GenericDataSource.java:107)
at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:896)
at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @PENGCHENGLIN007 

`org.jkiss.dbeaver.model.exec.DBCException: Active schema can't be changed` message means that DBeaver does not know query for default schema/catalog changing.

You can add it manually id Driver Properties:

![2021-11-02 10_04_18-DBeaver 21 2 4 - _MySQL - localhost_ Script-32](https://user-images.githubusercontent.com/45152336/139801008-feb74d19-5136-414a-891f-833fc7e7a6df.png)

**Comment by uslss** [comment]
there is no update on the ticket for a long time.
If it is still actual for you - feel free to reopen it with additional info
