### ISSUE TITLE
Unable to copy scripts into empty Scripts folder

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14519]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.2.5 UE devel
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:
1. As a prerequisite, suppose we have a project `dbeaver-dev` with some script `Script.sql` in the _Scripts_ folder.
2. Switch to the _Projects_ tab in the navigator. Create a new project with the name let's say `dbeaver-dev-copy`.
3. Attempt to copy the `Script.sql` file into the new project. An exception will be thrown and nothing will be copied.

#### Include any warning/errors/backtraces from the logs
```Java
!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-10 13:39:35.317
!MESSAGE Resource '/dbeaver-dev-copy/Scripts' does not exist.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-10 13:39:35.317
!MESSAGE Resource '/dbeaver-dev-copy/Scripts' does not exist.
!STACK 0
java.lang.Exception: Resource '/dbeaver-dev-copy/Scripts' does not exist.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:330)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:204)
	at org.eclipse.core.internal.resources.File.create(File.java:110)
	at org.eclipse.core.internal.resources.File.create(File.java:179)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateCopy.copyResource(NavigatorHandlerObjectCreateCopy.java:162)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateCopy$1.run(NavigatorHandlerObjectCreateCopy.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$run$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by Matvey16** [comment]
Verified
