### ISSUE TITLE
NPE appears when the incorrect parameter is used in the command line

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14542]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.5

#### Describe the problem you're observing:
NPE appears when the incorrect parameter is used in the command line.
#### Steps to reproduce, if exist:
1. Try to execute dbeaver-cli.exe -closetabs instead of -closeTabs
#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 2 0 2021-11-12 10:11:40.567
!MESSAGE Presentation 'json' not found. 
!SESSION 2021-11-12 10:11:56.279 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -closetabs
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -closetabs

!ENTRY org.jkiss.dbeaver.model 2 0 2021-11-12 10:11:57.313
!MESSAGE Error parsing command line: Unrecognized option: -closetabs

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-12 10:11:57.824
!MESSAGE Can't start RMI server
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-12 10:11:57.824
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverCommandLine.getRemoteParameterHandlers(DBeaverCommandLine.java:133)
	at org.jkiss.dbeaver.ui.app.standalone.rpc.DBeaverInstanceServer.startInstanceServer(DBeaverInstanceServer.java:206)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:256)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
