### ISSUE TITLE
[Greenplum] Permissions can't be shown

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14564]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.2.5

#### Connection specification:
- Database name and version Greenplum Database 6.16.0
- Driver name PostgreSQL JDBC Driver 42.2.20

#### Steps to reproduce, if exist:
1. Open a role from navigator
2. Open Permissions tab

**Expected:** Permissions for schemas are shown
**Actual:** All permissions are blank

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-15 17:18:14.135
!MESSAGE Error reading role privileges
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-15 17:18:14.135
!MESSAGE ERROR: could not identify an ordering operator for type aclitem[]
  Hint: Use an explicit ordering operator or modify the query.
  Position: 69
!STACK 0
org.postgresql.util.PSQLException: ERROR: could not identify an ordering operator for type aclitem[]
  Hint: Use an explicit ordering operator or modify the query.
  Position: 69
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreRole.getPrivileges(PostgreRole.java:418)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreRole.getPrivileges(PostgreRole.java:1)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$8.evaluate(PostgresRolePrivilegesEditor.java:463)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$8.evaluate(PostgresRolePrivilegesEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

![image](https://user-images.githubusercontent.com/82543000/141797370-a02f6497-2712-44d8-946e-555584f4e7ac.png)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Still can't read permissions, but with another error

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-17 12:32:02.650
!MESSAGE Error reading role privileges
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-17 12:32:02.650
!MESSAGE ERROR: function aclexplode(aclitem[]) does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.
  Position: 70
!STACK 0
org.postgresql.util.PSQLException: ERROR: function aclexplode(aclitem[]) does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.
  Position: 70
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreRole.getPrivileges(PostgreRole.java:419)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreRole.getPrivileges(PostgreRole.java:1)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$8.evaluate(PostgresRolePrivilegesEditor.java:463)
	at org.jkiss.dbeaver.ext.postgresql.ui.editors.PostgresRolePrivilegesEditor$8.evaluate(PostgresRolePrivilegesEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LonwoLonwo** [comment]
Ok. Function `aclexplode(aclitem[])` is very helpful, but doesn't work for old PostgreSQL versions. 
Fixed.
Reading sequences and materialized views permissions removed for old (<9) PG versions.

**Comment by Matvey16** [comment]
Verified
