### ISSUE TITLE
<0x200b> (Unicode zero width space) in SQL editor cannot be seen in UI but results in syntax error

### ISSUE THREAD

**Issue by Landwand** [dbeaver/dbeaver#14582]
#### System information: 
- Operating system (distribution) and version
- Catalina 10.15.7 (19H1519)
- DBeaver version Version 21.2.4.202111011351
- Additional extensions: none

#### Connection specification:
- Database name and version 
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Copy-pasted code throws an error when trying to run in DBeaver.

#### Steps to reproduce, if exist:

1. paste this code into DBeaver
```
SELECT
	i.invoice_number,
	i.invoiceid,
	i.organization,
	i.fname AS first_name,
	i.lname AS last_name,
	i.created_at AS issue_date,
	DATE_ADD(i.created_at, INTERVAL due_offset_days day) AS due_date,
	i.display_status as current_status,
	i.amount,
	i.currency_code
FROM
	live100.invoice i
WHERE
	i.systemid = 1031075
	AND i.active = 1
	AND i.payment_status != 'paid'
	and i.invoiceid
 in 
 (
	select
		al.invoiceid
	from
		live100.invoice_audit_log al
	where
		systemid = 1031075
		AND al.event = 'Viewed by client'
 )​
ORDER BY
	i.created_at DESC
;
```

2. attempt to run the code
3. there are no programmatic errors, but the SQL does show a syntax error (see quote)

> SQL Error [1064] [42000]: (conn=3077236) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '​
> 
> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1064] [42000]: (conn=3077236) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '​
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.sql.SQLSyntaxErrorException: (conn=3077236) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '​
> 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
> 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
> 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
> 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
> 	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
> 	... 12 more
> Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '​
> 	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
> 	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
> 	... 15 more
> Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '​
> ORDER BY
> 	i.created_at DESC' at line 28
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1683)
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1545)
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1508)
> 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
> 	... 16 more

The SQL should run normally, but wouldn't.  I pasted into Sublime text to look for any invisible characters.  There is a value of "<0x200b>" (Unicode "Zero Width Space" that causes this error.  If you remove it, re-paste it back into DBeaver, the SQL runs fine.  However, there is no way of seeing this symbol or value in DBeaver's SQL editor.  The value has been highlighted in this screenshot.

![image](https://user-images.githubusercontent.com/56357681/142087870-6b0e4838-de96-4fd6-ad5d-2b047c5c6206.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578213
