### ISSUE TITLE
DBeaver crashes when opening up existing/creating new SQL Editor,  connecting thru ODBC connection to Impala

### ISSUE THREAD

**Issue by maxzmiz** [dbeaver/dbeaver#14593]
#### System information: 
- Operating system (distribution) and version
***Windows 10 Enterprise version Version 10.0.18363***
- DBeaver version
***Community Edition 21.2.5***
- Additional extensions

#### Connection specification:
- Database name and version 
***ODBC connection to Impala (DSN 64bit set as datalake_prod in this case) ***
- Driver name 
***Cloudera ODBC Driver for Impala 2.6.10 64bit***
***Cloudera ODBC Driver for Impala 2.6.23 64bit was also tried and had a similar result***
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
***no***
#### Describe the problem you're observing:
After upgrading to 21.2.5 from 20.0.2, the connection I had setup before seemed to be fine, but when I tried to load a previous SQL file and connect the sql editor to the datalake_prod connection I setup, DBeaver just completely crashed. Now when I try to open it, it seems the file is still in the workspace and it will open and start to load then crashes again unless i use the -closeTabs CLI option to open again.
#### Steps to reproduce, if exist:

1. setup odbc connection to impala as 64bit dsn, 
2. test to make sure dsn works fine and connects succesfully. 
3. setup odbc connection for datalake_prod in DBeaver using dsn, 
4. open connection, click on IMPALA to list schemas, making sure connection is actually getting out to server. 
5. Then setup new SQL Editor to query database/schema other than default over connection. Once attempted, it will crash. This also happened after attempting to open an existing sql file

#### Include any warning/errors/backtraces from the logs

***last 2 sessions from .log:***
!SESSION 2021-11-17 12:27:24.957 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -closeTabs
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -closeTabs

!ENTRY org.eclipse.e4.ui.workbench 2 0 2021-11-17 12:27:40.980
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.gef.ui.palette_view" id and the "Palette" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-17 12:27:52.667
!MESSAGE Error determining server version
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-17 12:27:52.667
!MESSAGE 
!STACK 0
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:447)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:420)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:472)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2021-11-17 12:29:19.496 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.e4.ui.workbench 2 0 2021-11-17 12:29:34.374
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.gef.ui.palette_view" id and the "Palette" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-17 12:29:38.764
!MESSAGE 

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-17 12:29:40.484
!MESSAGE Error determining server version
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-17 12:29:40.485
!MESSAGE 
!STACK 0
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:447)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:420)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:472)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:223)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:133)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	
#########################################
***from dbeaver-debug.log***

2021-11-17 12:29:23.743 - Create display
2021-11-17 12:29:23.959 - DBeaver 21.2.5.202111141807 is starting
2021-11-17 12:29:23.961 - OS: Windows 10 10.0 (amd64)
2021-11-17 12:29:23.961 - Java version: 11.0.12 by Eclipse Foundation (64bit)
2021-11-17 12:29:23.961 - Install path: 'C:\Users\mchart\AppData\Local\DBeaver21.2.5_2'
2021-11-17 12:29:23.962 - Instance path: 'file:/C:/Users/mchart/AppData/Roaming/DBeaverData/workspace6/'
2021-11-17 12:29:23.962 - Memory available 64Mb/1024Mb
2021-11-17 12:29:23.989 - Starting RMI server at 51824
2021-11-17 12:29:26.114 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.200.v20210723-1326]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.0.v20210723-1034]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.300.v20210813-1521]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.200.v20210816-1658]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.100.v20210722-1426]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.0.v20210625-1052]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.300.v20210723-0837]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.84.202111141807]
2021-11-17 12:29:28.717 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
2021-11-17 12:29:30.073 - Create actions
2021-11-17 12:29:30.082 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2021-11-17 12:29:30.083 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2021-11-17 12:29:30.084 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2021-11-17 12:29:31.116 - Initialize workbench window
2021-11-17 12:29:31.126 - Finish initialization
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.69.202111141807]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.200.v20210622-1002]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.200.v20210724-2153]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.59.202111141807]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.69.202111141807]
> Start Team Support Core [org.eclipse.team.core 3.9.100.v20210604-1207]
> Start Core Compare Support [org.eclipse.compare.core 3.6.1000.v20201020-1107]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.700.v20210726-0943]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.4.0.v20210426-0838]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1100.v20210424-0724]
2021-11-17 12:29:35.274 - Loading user drivers configuration from 'C:\Users\mchart\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2021-11-17 12:29:35.304 - Total database drivers: 91 (91)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.69.202111141807]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.106.202111141807]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.75.202111141807]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20211006155649]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20211006155649]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.29.202111141807]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.29.202111141807]
> Start Console [org.eclipse.ui.console 3.11.100.v20210721-1355]
> Start Debug Core [org.eclipse.debug.core 3.18.200.v20210721-1355]
2021-11-17 12:29:38.622 - Connect with 'datalake_prod' (odbc-17d2ef62121-1d1118711c04bd49)
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.155.202111141807]
2021-11-17 12:29:38.729 - Can't connect - connect/disconnect is in progress
2021-11-17 12:29:38.762 - 
2021-11-17 12:29:38.765 - Execution context opened (datalake_prod; Main; 0)
2021-11-17 12:29:39.854 - Execution context opened (datalake_prod; Metadata; 1)
2021-11-17 12:29:40.482 - Error determining server version
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:447)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:420)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:472)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:223)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:133)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2021-11-17 12:29:40.488 - Can't determine database version. Use default
2021-11-17 12:29:40.515 - Can't get column 'TABLE_CAT': Column not found
2021-11-17 12:29:40.524 - Connected (odbc-17d2ef62121-1d1118711c04bd49, JDBC-ODBC Bridge (Cloudera ODBC Driver for Impala) [2.0001 (2.6.10.1010)])
2021-11-17 12:29:40.569 - Execution context opened (datalake_prod; SQLEditor <SF_RX_Genesys2021-09-30.sql>; 2)
2021-11-17 12:29:41.828 - Error reading schemas in catalog 'IMPALA' - UnsupportedOperationException - null

########################################
see attached for crash logs 
[hs_err_pid197060.log](https://github.com/dbeaver/dbeaver/files/7557553/hs_err_pid197060.log)
[hs_err_pid198192.log](https://github.com/dbeaver/dbeaver/files/7557554/hs_err_pid198192.log)

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
