### ISSUE TITLE
both versions 21.2.4.202111011413 AND 21.2.5.202111141807  trying to check for updates OR add any driver sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by gthbusr0** [dbeaver/dbeaver#14627]
#### System information: 
- Operating system (distribution) and version
- DBeaver version: Version 21.2.4.202111011413
- Java version : jdk1.8.0_202/jre1.8.0_202
- Additional extensions: none

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Steps to reproduce, if exist:

install the .exe for  Versions Version 21.2.5.202111141807 & 21.2.4.202111011413 & try to download drivers for oracle/ms sql server or click check for updates

**error:**
Cannot obtain version information. Perhaps the network connection is down?

Reason:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

#### Include any warning/errors/backtraces from the logs

!SESSION 2021-11-21 03:08:04.612 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:17.963
!MESSAGE unable to find valid certification path to requested target
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:17.963
!MESSAGE unable to find valid certification path to requested target
!STACK 0
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:105)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:50)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:45)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:54)
	at org.jkiss.dbeaver.ui.app.standalone.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:126)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 2 0 2021-11-21 03:08:37.563
!MESSAGE Maven artifact 'com.sap.cloud.db.jdbc:ngdbc:RELEASE' not found in any available repository.

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:37.566
!MESSAGE Error resolving library 'com.sap.cloud.db.jdbc:ngdbc:RELEASE' dependencies
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:37.566
!MESSAGE Maven artifact 'maven:/com.sap.cloud.db.jdbc:ngdbc:RELEASE' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/com.sap.cloud.db.jdbc:ngdbc:RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:335)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:241)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:37.735
!MESSAGE Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-11-21 03:08:37.735
!MESSAGE Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
!STACK 0
org.jkiss.dbeaver.DBException: Network unavailable:
javax.net.ssl.SSLHandshakeException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.checkNetworkAccessible(DriverDependenciesTree.java:190)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.handleDownloadError(DriverDependenciesTree.java:176)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.resolveLibraries(DriverDownloadAutoPage.java:134)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadWizard.pageActivated(DriverDownloadWizard.java:93)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.lambda$1(DriverDownloadDialog.java:47)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.downloadDriverFiles(DriverDownloadDialog.java:128)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadDialog.downloadDriverFiles(DriverDownloadDialog.java:122)
	at org.jkiss.dbeaver.core.DBeaverUI$2.runTask(DBeaverUI.java:188)
	at org.jkiss.dbeaver.core.DBeaverUI$2.runTask(DBeaverUI.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by flambchap** [comment]
Hello @iDeepMind. Do you work under a corporate network behind some proxy?

**Comment by gthbusr0** [comment]
yes & the same installation on another company machine has no issues updating. java home is set & even is the 1st in path. 

even explicitly added dbeaver.io/dbeaver.com cert directly to cd C:\Program Files\Java\jdk1.8.0_202\jre\lib\security\ via keytool
& still encountering the same issue.

keytool -import -trustcacerts -keystore cacerts -file C:\Users\EUKJG\Downloads\dbeaver.cer
keytool -import -trustcacerts -keystore cacerts -file C:\Users\EUKJG\Downloads\dbeaverio.cer

**Comment by flambchap** [comment]
This happens because DBeaver comes with bundled JRE and uses it to run. To bypass this issue, you need to import the cert to this JRE. You can find it in the `jre` folder inside the DBeaver installation. 

FYI: DBeaver requires Java 11 to run, so using your jdk 1.8 is not an option.

**Comment by Matvey16** [comment]
#5704

**Comment by serge-rider** [comment]
@iDeepMind Please test the latest Early Access version ()https://dbeaver.io/files/ea). Perhaps the problem was fixed there.

**Comment by gthbusr0** [comment]
yes, @serge-rider this is fixed in EA.

@akilovich here are my java & dbeaver details. so far working ok.

Version 21.3.0.202111231354

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
