### ISSUE TITLE
Unable to cancel multiple heavy queries running at the same time

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14672]
#### System information: 
- Operating system (distribution) and version Win 11
- DBeaver version 21.2.0 UE

#### Steps to reproduce, if exist:
1. In the SQLEditor, write a long-running query, such as 
```SQL
SELECT pg_sleep(10);
```
2. Execute a lot of these queries at the same time.
3. Try to cancel several queries.

You need to wait quite some time for the statement to cancel. You also will receive a lot of errors popups. Possibly, you won't be able to cancel queries at all as well to disconnect.

#### Include any warning/errors/backtraces from the logs
```Java
org.postgresql.util.PSQLException: This statement has been closed.
	at org.postgresql.jdbc.PgStatement.checkClosed(PgStatement.java:727)
	at org.postgresql.jdbc.PgStatement.getWarnings(PgStatement.java:608)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getWarnings(JDBCStatementImpl.java:568)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getStatementWarnings(JDBCStatementImpl.java:598)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:594)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by flambchap** [comment]
Fixed.

**Comment by uslss** [comment]
verified
