### ISSUE TITLE
Snowflake is basically unusable when DBeaver runs with Java 17

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#14691]
When DBeaver runs with Java 17, it's pretty much impossible to read any result set returned by the Snowflake driver. This means that most queries in SQL Editor don't work, the navigator doesn't show objects such as tables, views, etc. I'm aware of only one query that successfully runs: `SHOW TABLES`.

The exceptions thrown when trying to use DBeaver for Snowflake access indicate that this is caused by the fact that the current Snowflake driver we use (3.13.6) is not compatible with Java 17.

We need to wait for Snowflake to update their driver. We need to keep in mind though that we use the aforementioned version because the latest one (3.13.10) doesn't work with authentication via an external browser.

**Comment by deep750** [comment]
Not sure if it is related or separate issue, but after upgrading to 21.3.0 DBeaver won't connect to snowflake. It doesn't seem to trying. Error message is !390400!. I have authentication in external browser, but nothing happens at all, except for the error message that comes instantly when trying to connect to the database.

**Comment by flambchap** [comment]
Hello @deep750. This is a related issue (see the last paragraph in my OP). But that's really odd considering that we didn't change our preferred driver version for Snowflake. Could you please tell me what driver version do you use?

**Comment by deep750** [comment]
@akilovich I'm currently using snowflake-jdbc-3.6.12 - at least that's the one in my personal folder\.dbeaver-drivers-folder

**Comment by flambchap** [comment]
@deep750 Please change to 3.13.6. To do that, select your Snowflake connection in the navigator -> F4 -> Edit driver settings -> Libraries -> Download/Update, then follow the instructions from the gif below.

![snow 730](https://user-images.githubusercontent.com/26031301/143866917-d42a2727-656f-4206-a07b-83d7a3b75642.gif)

Also, when doing that, what version of the driver is displayed before changing it to 3.13.6? Have you changed the version of your driver manually before?

**Comment by deep750** [comment]
@akilovich will updating the driver solve anything with latest version of DBeaver? Understood the initial comment that 3.13.6 doesn't work with the latest version of DBeaver, as it is using Java 17 (?) The suggested version (default) is 3.13.6, in the update driver-wizard.
According to Snowflake's driver page, latest version is 3.13.11 - maybe that fixes it? I haven't tried it yet.

**Comment by deep750** [comment]
upgrading to 3.13.11 didn't solve anything-

**Comment by flambchap** [comment]
@deep750 3.13.6 works just fine with the latest version of DBeaver if DBeaver runs on Java 11. Most of the distributions of DBeaver run on that version, this should work for you.

**Comment by flambchap** [comment]
Unfortunately, there is no version of the Snowflake driver that works with Java 17. At the same time, we package our version for macs on AArch64 with Java 17. This results in the inability to work with Snowflake with this distribution.

**Comment by flambchap** [comment]
It will be fixed alongside #17303

**Comment by flambchap** [comment]
Nevermind, we'll do that independently.

**Comment by flambchap** [comment]
With Java 17 and 3.13.6 driver, if you open a connection to Snowflake, the default database and schema aren't highlighted in the navigator. In the logs we see

```Java
2022-10-25 13:11:27.390 - Exception caught when refreshing defaults for Snowflake execution context
net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1061)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:550)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:467)
	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:219)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:134)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:743)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:639)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeQuery(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeExecutionContext.refreshDefaults(SnowflakeExecutionContext.java:144)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.initializeContextState(SnowflakeDataSource.java:76)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:162)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:43)
	at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:97)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:988)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The same exception appears when we open a data editor.

It's a Snowflake JDBC driver [issue](https://github.com/snowflakedb/snowflake-jdbc/issues/589), which is in turn an issue of Apache Arrow. Unfortunately, they haven't migrated to Java 9 modules.
