### ISSUE TITLE
[Trino] Can't select active catalog/schema in SQL editor

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14693]
#### System information: 
- Win10
- DBeaver CE 21.3.0

#### Connection specification:
- Trino

#### Describe the problem you're observing:
Active catalog/schema is always <N/A> and you can't select any Trino db as active

**Comment by wgong** [comment]
I encountered the same issue with v 23.0.1 on Win 11 Home Version 22H2 when using duckdb (no issue for SQLite)

From AppData\Roaming\DBeaverData\workspace6\.metadata\.log
```
!ENTRY org.jkiss.dbeaver.model 2 0 2023-04-09 18:05:48.717
!MESSAGE org.jkiss.dbeaver.DBException: SQL Error: Actual catalog argument is not supported, got faculty-Cornell-CS
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2023-04-09 18:05:48.717
!MESSAGE SQL Error: Actual catalog argument is not supported, got faculty-Cornell-CS
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2023-04-09 18:05:48.717
!MESSAGE Actual catalog argument is not supported, got faculty-Cornell-CS
!STACK 0
java.sql.SQLException: Actual catalog argument is not supported, got faculty-Cornell-CS
	at org.duckdb.DuckDBDatabaseMetaData.getTables(DuckDBDatabaseMetaData.java:676)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findTablesByMask(GenericStructureAssistant.java:105)
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:94)
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:71)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:1)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$TablesFinderJob.findTables(SQLContextInformer.java:391)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$TablesFinderJob.lambda$0(SQLContextInformer.java:283)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$TablesFinderJob.run(SQLContextInformer.java:281)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```
screenshot below when clicking in table navigation of duckdb 
![ERROR-2023-04-09-182942](https://user-images.githubusercontent.com/329928/230799562-23a5ce6b-ac4a-40df-9c90-9b5be3a92248.jpg)
