### ISSUE TITLE
NPE when viewing results from Elasticsearch/OpenSearch sources

### ISSUE THREAD

**Issue by placaze** [dbeaver/dbeaver#14715]
#### System information: 
- Operating system (distribution) and version : Windows 10
- DBeaver version : 21.2.5
- Additional extensions : no

#### Connection specification:
- Database name and version : OpenSearch 1.1
- Driver name :
-- Elasticsearch : https://mvnrepository.com/artifact/org.elasticsearch.plugin/x-pack-sql-jdbc
-- Open Distro : https://mvnrepository.com/artifact/com.amazon.opendistroforelasticsearch.client/opendistro-sql-jdbc
-- OpenSearch : https://github.com/opensearch-project/sql/actions/runs/1496687698
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
There are some NullPointerException when viewing results from Elasticsearch/OpenSearch:
![image](https://user-images.githubusercontent.com/57751243/143781538-c46656a0-24fa-4bed-aec2-ed32099a79e5.png)

Here is the stacktrace:
```
java.lang.NullPointerException
	at com.amazon.opendistroforelasticsearch.jdbc.ResultSetImpl.getObjectX(ResultSetImpl.java:589)
	at com.amazon.opendistroforelasticsearch.jdbc.ResultSetImpl.getObjectX(ResultSetImpl.java:583)
	at com.amazon.opendistroforelasticsearch.jdbc.ResultSetImpl.getObjectX(ResultSetImpl.java:579)
	at com.amazon.opendistroforelasticsearch.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:562)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:627)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4796)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Here is the data of a line:
```json
{
  "_index": "test1234",
  "_type": "_doc",
  "_id": "E052C60031",
  "_version": 1,
  "_score": 0,
  "_source": {
    "id": "E052C60031",
    "nomFichier": "INPUT.csv",
    "dateCreation": {
      "month": "OCTOBER",
      "dayOfWeek": "WEDNESDAY",
      "dayOfYear": 293,
      "nano": 292000000,
      "year": 2021,
      "monthValue": 10,
      "dayOfMonth": 20,
      "hour": 16,
      "minute": 6,
      "second": 10,
      "chronology": {
        "calendarType": "iso8601",
        "id": "ISO"
      }
    },
    "dateTraitement": {
      "month": "OCTOBER",
      "dayOfWeek": "WEDNESDAY",
      "dayOfYear": 293,
      "nano": 296682000,
      "year": 2021,
      "monthValue": 10,
      "dayOfMonth": 20,
      "hour": 16,
      "minute": 6,
      "second": 10,
      "chronology": {
        "calendarType": "iso8601",
        "id": "ISO"
      }
    },
    "dureeTraitement": 4,
    "statut": "OK",
    "message": "",
    "ligne": {
      "numeroContrat": "E052C60031",
      "dateDebutValidite": {
        "year": 2006,
        "month": "OCTOBER",
        "chronology": {
          "calendarType": "iso8601",
          "id": "ISO"
        },
        "leapYear": false,
        "dayOfWeek": "FRIDAY",
        "dayOfYear": 293,
        "era": "CE",
        "monthValue": 10,
        "dayOfMonth": 20
      },
      "dateFinValidite": {
        "year": 2008,
        "month": "DECEMBER",
        "chronology": {
          "calendarType": "iso8601",
          "id": "ISO"
        },
        "leapYear": true,
        "dayOfWeek": "WEDNESDAY",
        "dayOfYear": 366,
        "era": "CE",
        "monthValue": 12,
        "dayOfMonth": 31
      },
      "societe": "0323",
      "vide": "",
      "id": "E052C60031"
    }
  }
}
```

#### Steps to reproduce, if exist:

View Elasticsearch/OpenSearch data containing arrays, with an Elasticsearch/OpenSearch/OpenDistro JDBC driver.

**Comment by Skydiveroid** [comment]
Thanks for the bug report!

**Comment by placaze** [comment]
Hi @Skydiveroid, @serge-rider,

Is there any way I can help you to fix this? (I'm not a developer unfortunately.)
It used to work with some 2 or 3 years old versions of DBeaver.

I can make a small donation, or contribute to a bounty for this issue.

Thanks :)
