### ISSUE TITLE
Querying empty string without specifying alias causes an error rendering the result

### ISSUE THREAD

**Issue by feeva** [dbeaver/dbeaver#14729]
#### System information: 
- Operating system (distribution) and version - **Windows 11**
- DBeaver version - **21 and later**
- Java version  - **11.0.12**

#### Connection specification:
- Database name and version - **mysql**

#### Describe the problem you're observing:
Querying empty string without specifying alias causes an error rendering the result. For example, `select name, created_date, '' from my_table` doesn't render the result table and then the ctrl+enter shortcut won't work.

#### Include any warning/errors/backtraces from the logs

```
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4874)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.SWT.error(SWT.java:4779)
	at org.eclipse.swt.graphics.GC.drawStringInPixels(GC.java:2159)
	at org.eclipse.swt.graphics.GC.drawString(GC.java:2154)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumnRenderer.paint(GridColumnRenderer.java:144)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnsHeader(LightGrid.java:2519)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnHeader(LightGrid.java:2506)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintHeader(LightGrid.java:2475)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onPaint(LightGrid.java:2212)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1536)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4810)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4966)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by LonwoLonwo** [comment]
@feeva Thanks for the bug report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.1

**Comment by uslss** [comment]
The query cannot be executed if some symbol was highlighted during execution
![6FEEbxIoyJ](https://user-images.githubusercontent.com/31996417/144396141-96d163f9-a012-452b-95fc-06decb0053b7.gif)
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Dec 02 12:36:35 MSK 2021


org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:230)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.model.sql.SQLUtils.removeExtraSpaces(SQLUtils.java:903)
	at org.jkiss.dbeaver.model.sql.SQLUtils.compareAliases(SQLUtils.java:899)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.equalAttributes(DBExecUtils.java:572)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateMetaData(ResultSetModel.java:546)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.setMetaData(ResultSetModel.java:524)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setMetaData(ResultSetViewer.java:2211)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:112)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:681)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	... 9 more

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Dec 02 12:36:35 MSK 2021


java.lang.NullPointerException
	at org.jkiss.dbeaver.model.sql.SQLUtils.removeExtraSpaces(SQLUtils.java:903)
	at org.jkiss.dbeaver.model.sql.SQLUtils.compareAliases(SQLUtils.java:899)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.equalAttributes(DBExecUtils.java:572)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.updateMetaData(ResultSetModel.java:546)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.setMetaData(ResultSetModel.java:524)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setMetaData(ResultSetViewer.java:2211)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:112)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:681)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by uslss** [comment]
verified
