### ISSUE TITLE
PostgreSQL backup/restore task can't be executed if the wizard is opened from a tasks window

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#14739]
#### System information: 
- DBeaver version 21.3.0

#### Connection specification:
- Database name and version PostgreSQL 12/14

#### Steps to reproduce, if exist:
1. Create a backup task
2. Double click on that task in **Database tasks** window
3. Immidiately click `Proceed`

**Expected:** Backup task is executed
**Actual:** Nothing changes and NPE is thrown

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizardPageObjects.saveState(PostgreBackupWizardPageObjects.java:313)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizard.saveTaskState(PostgreBackupWizard.java:61)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveConfigurationToTask(TaskConfigurationWizard.java:307)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveTask(TaskConfigurationWizard.java:302)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.performFinish(TaskConfigurationWizard.java:234)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeToolWizard.performFinish(AbstractNativeToolWizard.java:210)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeExportWizard.performFinish(AbstractNativeExportWizard.java:75)
	at org.jkiss.dbeaver.ui.dialogs.MultiPageWizardDialog.buttonPressed(MultiPageWizardDialog.java:353)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:225)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerEdit.execute(TaskHandlerEdit.java:56)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)


...
```

**Comment by ShadelessFox** [comment]
Looks like a side-effect of #14556.

**Comment by Matvey16** [comment]
This way the user won't be able to click proceed, but because it's task editor and not standard backup wizard they won't be able to know what is the problem. It needs to work like a standard wizard where you can't skip any step and need to click next on every page before proceeding

![dbeaver_pDJ5PluUQN](https://user-images.githubusercontent.com/82543000/158197926-aef62802-6508-4f68-97c2-83df5d50a478.gif)

**Comment by Matvey16** [comment]
Verified
