### ISSUE TITLE
Table Property editing: Removable fields.

### ISSUE THREAD

**Issue by SSSDNSY** [dbeaver/dbeaver#14750]
**Is your feature request related to a problem? Please describe.**
When I edit the fields of the table, a new field needs to be put in front, and I can only click on the build up of dozens of fields one by one

**Describe the solution you'd like**
Removable or draggable

**Describe alternatives you've considered**
input the sorted number I  want

**Additional context**
I hate one by one click up or down button...
![image](https://user-images.githubusercontent.com/15624361/144176901-618bc2de-dfb8-456a-aa72-586fa953115c.png)

**Comment by Skydiveroid** [comment]
Thank you for the future request!

**Comment by SSSDNSY** [comment]
OK, looking forward to it!

**Comment by uslss** [comment]
1. After moving last column to the top, only "down" buttons are available for the "new" last column
![dbeaver_Eq1nDZc5NG](https://user-images.githubusercontent.com/31996417/153058059-1e571e32-6be8-4014-9619-686380fd6e64.gif)
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Tue Feb 08 22:03:15 MSK 2022
Failed to execute item null

org.eclipse.core.commands.NotEnabledException: Trying to execute the disabled command org.jkiss.dbeaver.core.object.move.bottom
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:479)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:268)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

2. Move object to the very bottom button doesn't work for the first column
![dbeaver_x64pOgNx9y](https://user-images.githubusercontent.com/31996417/153058352-49ce2bb0-c6b3-4d31-8489-de5394e34ef5.gif)

3. Move object to the very bottom button works incorrectly for the non-top column - it doesn't become the last 
![dbeaver_5zpLvlybjv](https://user-images.githubusercontent.com/31996417/153058934-74bed8eb-b5ed-4bdf-9552-9430923652a1.gif)

**Comment by ShadelessFox** [comment]
The first one looks like an Eclipse issue.

Commands are not correctly refreshed. It's not related to this ticket since the issue occurs in other places too.

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by uslss** [comment]
verified
