### ISSUE TITLE
Can't initialize database consumer. No target object and no target container

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#14763]
Mssql -> PostgreSQL
when working on a task

"
2021-12-02 14:25:59.810 - Connect with 'MssqlDB' (microsoft-17d04707f16-57f1c7983e7a4ab8)
2021-12-02 14:25:59.810 - Connect to jdbc:sqlserver://;serverName=192.168.67.192;databaseName=MssqlDB
2021-12-02 14:25:59.811 - 	Connect to data source
2021-12-02 14:25:59.824 - Execution context opened (MssqlDB; Main; 3)
2021-12-02 14:25:59.865 - 	Connecting Main
2021-12-02 14:25:59.930 - 	Set connection defaults
2021-12-02 14:25:59.962 - 	Initialize data source
2021-12-02 14:25:59.963 - Execution context opened (MssqlDB; Metadata; 4)
2021-12-02 14:25:59.963 - 	Connecting Metadata
2021-12-02 14:26:00.005 - 	Set connection defaults
2021-12-02 14:26:00.028 - 	Load SystemDataTypeCache
2021-12-02 14:26:00.035 - 	Load DatabaseCache
2021-12-02 14:26:00.043 - 	Load SchemaCache
2021-12-02 14:26:00.108 - Connected (microsoft-17d04707f16-57f1c7983e7a4ab8, Microsoft JDBC Driver 9.2 for SQL Server [9.2.0.0])
2021-12-02 14:26:00.124 - Connect with 'psql_local' (postgres-jdbc-17d046f9601-24674d0ddd82bfa8)
2021-12-02 14:26:00.124 - Connect to jdbc:postgresql://localhost:5432/psql
2021-12-02 14:26:00.124 - 	Connect to data source
2021-12-02 14:26:00.125 - Execution context opened (psql_local; Main <psql>; 5)
2021-12-02 14:26:00.125 - Initiate connection to PostgreSQL database [psql@localhost] for Main <psql>
2021-12-02 14:26:00.125 - 	Connecting Main <psql>
2021-12-02 14:26:00.155 - 	Set connection defaults
2021-12-02 14:26:00.157 - 	Load SchemaCache
2021-12-02 14:26:00.164 - Execution context opened (psql_local; Metadata <psql>; 6)
2021-12-02 14:26:00.164 - Initiate connection to PostgreSQL database [psql@localhost] for Metadata <psql>
2021-12-02 14:26:00.164 - 	Connecting Metadata <psql>
2021-12-02 14:26:00.197 - 	Set connection defaults
2021-12-02 14:26:00.202 - 	Initialize data source
2021-12-02 14:26:00.226 - Connected (postgres-jdbc-17d046f9601-24674d0ddd82bfa8, PostgreSQL JDBC Driver [42.2.20])
2021-12-02 14:26:00.247 - Load items ...
2021-12-02 14:26:00.247 - 	Load  Databases
2021-12-02 14:26:00.248 - 	Load  Roles
2021-12-02 14:26:00.248 - 	Load  Administer
2021-12-02 14:26:00.248 - 	Load  System Info
2021-12-02 14:26:00.380 - Task fatal error
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize database consumer. No target object and no target container
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.checkTargetContainer(DatabaseTransferConsumer.java:5
2021-12-02 14:26:00.380 - Task fatal error
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize database consumer. No target object and no target container
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.checkTargetContainer(DatabaseTransferConsumer.java:5
2021-12-02 14:26:00.319 - Can't get column 'is_hidden': 열 이름 is_hidden이(가) 잘못되었습니다.
2021-12-02 14:26:00.379 - Initialize pipes
2021-12-02 14:26:00.379 - Create necessary database objects
2021-12-02 14:26:00.380 - Post transfer work
2021-12-02 14:26:00.380 - Task fatal error
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize database consumer. No target object and no target container
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.checkTargetContainer(DatabaseTransferConsumer.java:524)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:573)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:108)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:124)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.initializePipes(DTTaskHandlerTransfer.java:101)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeWithSettings(DTTaskHandlerTransfer.java:75)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:66)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:119)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
"

An error occurs.

It seems to be a problem after the update.

All the scheduler tasks I manage are not working...

**Comment by ghost** [comment]
Databases -> Schemas -> public
After selection, setting is complete.
