### ISSUE TITLE
Display nanoseconds in ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#14772]
**Is your feature request related to a problem? Please describe.**
DBeaver does not display nanoseconds for below query in ClickHouse:
```sql
select toDateTime64('2021-11-12 12:34:56.123456789', 9) t1,
	toDateTime64('2021-11-12 12:34:56.123456789', 9, 'Asia/Chongqing') t2
```
![image](https://user-images.githubusercontent.com/4270380/144459933-22bce33a-da66-4c0c-9ed3-9d588ed676d7.png)

**Describe the solution you'd like**
Display nanoseconds according to returned `LocalDateTime` or `OffsetDateTime`.

**Describe alternatives you've considered**
Convert to string works but the preferred solution is `resultSet.getObject()`( or `resultSet.getTimestamp()` before JDBC 4.2).

**Additional context**
[DataGrip] - `getObject()` and then toString()?
![image](https://user-images.githubusercontent.com/4270380/144460180-bc8b52fb-f2de-4457-92f2-aded67895de3.png)

[SQuirreL SQL] - does not support timestamp with timezone(OffsetDateTime)
![image](https://user-images.githubusercontent.com/4270380/144460296-386a4da0-2508-4a98-bfcb-27056a4b49ee.png)

**Comment by LonwoLonwo** [comment]
Hello @zhicwu 

Have you try to change the data formatting in the Preferences? https://dbeaver.com/docs/wiki/Managing-Data-Formats/#changing-data-formats

![2021-12-03 00_54_16-DBeaver Ultimate 21 3 0 - _default_Script-95](https://user-images.githubusercontent.com/45152336/144509316-78443c87-9def-4f3a-9818-637ad575451b.png)

**Comment by zhicwu** [comment]
> Have you try to change the data formatting in the Preferences? https://dbeaver.com/docs/wiki/Managing-Data-Formats/#changing-data-formats

Thank you @LonwoLonwo! It's a great feature, but ClickHouse can define DateTime64 with scale from 0 to 9 and it has DateTime32.
```sql
select toDateTime32('2021-11-12 12:34:56') t0,
	toDateTime64('2021-11-12 12:34:56.123456789', 9) t1,
	toDateTime64('2021-11-12 12:34:56.123456789', 9, 'Asia/Shanghai') t2,
	toDateTime64('2021-11-12 12:34:56.123456789', 3, 'Asia/Shanghai') t3
```
![image](https://user-images.githubusercontent.com/4270380/144522915-587661e9-fb09-46fb-8b49-93edd7b8e0e1.png)

I'm not sure how to make nanoseconds part optional(the format I'm using is `yyyy-MM-dd HH:mm:ss.SSSSSSSSS`). In Java, it's something like below. Moreover, is there any default configuration can be customized for specific type of database(ClickHouse in this case)?
```java
public static final DateTimeFormatter DATETIME_FORMATTER = new DateTimeFormatterBuilder()
    .appendPattern("yyyy-MM-dd HH:mm:ss").appendFraction(ChronoField.NANO_OF_SECOND, 0, 9, true).toFormatter();
```

**Comment by LonwoLonwo** [comment]
@zhicwu Yes, you can change Data Format settings only for Clickhouse Datasource. Just click on the "Edit connection" in the Database Navigator Tree.

![2021-12-03 11_38_13-DBeaver Ultimate 21 3 0 - test_db](https://user-images.githubusercontent.com/45152336/144585271-2d6c7265-8456-4fb2-8f23-ee8dec5d2db5.png)

Also, you can try to enable "Disable data format settings". Maybe it helps.

**Comment by zhicwu** [comment]
Cool, thanks again. Disable date/time format helped, but the time zone part is gone. Would be nice if the date format can support optional nanoseconds(tried `yyyy-MM-dd HH:mm:ss[.SSSSSSSSS]` but ended up with NPE :p).

**Comment by LonwoLonwo** [comment]
Auch. Do you have NPE stack trace?

**Comment by zhicwu** [comment]
> Auch. Do you have NPE stack trace?

Try change date format to `yyyy-MM-dd HH:mm:ss[.SSSSSSSSS]` and you'll get below NPE:
```
java.lang.NullPointerException
	at org.jkiss.utils.time.ExtendedDateFormat.<init>(ExtendedDateFormat.java:72)
	at org.jkiss.dbeaver.model.impl.data.formatters.DateTimeDataFormatter.init(DateTimeDataFormatter.java:59)
	at org.jkiss.dbeaver.ui.editors.data.preferences.PrefPageDataFormat.reloadSampleThrowable(PrefPageDataFormat.java:351)
	at org.jkiss.dbeaver.ui.editors.data.preferences.PrefPageDataFormat.saveFormatterProperties(PrefPageDataFormat.java:373)
	at org.jkiss.dbeaver.ui.editors.data.preferences.PrefPageDataFormat$VerifyingPropertySourceCustom.setPropertyValue(PrefPageDataFormat.java:587)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer$4.applyEditorValue(PropertyTreeViewer.java:534)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:335)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:332)
	at org.jkiss.dbeaver.ui.controls.CustomTextCellEditor.fireApplyEditorValue(CustomTextCellEditor.java:69)
	at org.eclipse.jface.viewers.TextCellEditor.handleDefaultSelection(TextCellEditor.java:286)
	at org.eclipse.swt.events.SelectionListener$2.widgetDefaultSelected(SelectionListener.java:102)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:58)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.runCommand(CocoaUIHandler.java:421)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.access$0(CocoaUIHandler.java:407)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler$1.widgetSelected(CocoaUIHandler.java:281)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by uslss** [comment]
Close this issue as resolved.
Ticket for NPE is created
