### ISSUE TITLE
Include "java.net.http" module in bundled JRE

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#14771]
**Is your feature request related to a problem? Please describe.**
With default DBeaver setup, I ran into below error when testing a driver uses JDK 11 HttpClient:
```
java.lang.ClassNotFoundException: java.net.http.HttpResponse$BodySubscriber
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:42)
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:24)
	at com.clickhouse.client.AbstractClient.getConnection(AbstractClient.java:144)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:75)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:116)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1364)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:189)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:898)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Describe the solution you'd like**
Include `java.net.http` module in bundled JRE. Is there any specific reason exclude the module?

**Describe alternatives you've considered**
I had to manually switch to JDK11 located in a different directory.

**Additional context**
N/A

**Comment by flambchap** [comment]
>Is there any specific reason exclude the module?

To shrink the size of the distribution.

**Comment by flambchap** [comment]
We've decided to include it in our JRE. Thank you.

**Comment by flambchap** [comment]
@zhicwu Could you please tell me what driver you use? I want to replicate this issue to be able to test the fix.

**Comment by zhicwu** [comment]
> @zhicwu Could you please tell me what driver you use? I want to replicate this issue to be able to test the fix.

Please use clickhouse-jdbc [v0.3.2-test2](https://github.com/ClickHouse/clickhouse-jdbc/releases/download/v0.3.2-test2/clickhouse-jdbc-0.3.2-test2-http.jar) for testing purpose. It's a multi-release jar file, HttpClient will be used when you're using JDK 11 or above.

**Comment by flambchap** [comment]
I'll fix this issue simultaneously with https://github.com/dbeaver/dbeaver/issues/14749

**Comment by flambchap** [comment]
Module added.

**Comment by Matvey16** [comment]
Verified
