### ISSUE TITLE
Tasks: an exception is thrown while reading task statistics

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#14785]
#### Steps to reproduce, if exist:
Create a new task, save it. Observe an exception in the error log

#### Include any warning/errors/backtraces from the logs

```
java.nio.file.NoSuchFileException: C:\Users\ShadelessFox\AppData\Roaming\DBeaverData\workspace6\.metadata\task-stats\f9fb4de9-2368-4edf-bc6f-37e218188c83\meta.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2955)
	at org.jkiss.dbeaver.registry.task.TaskImpl.loadRunStatistics(TaskImpl.java:264)
	at org.jkiss.dbeaver.registry.task.TaskImpl.getRunStatistics(TaskImpl.java:165)
	at org.jkiss.dbeaver.tasks.ui.view.DatabaseTasksView.loadTaskRuns(DatabaseTasksView.java:342)
	at org.jkiss.dbeaver.tasks.ui.view.DatabaseTasksView.lambda$createTaskTree$1(DatabaseTasksView.java:115)
```

**Comment by uslss** [comment]
verified
