### ISSUE TITLE
Better support of END IF/END REPEAT/END WHILE/END FOR (DB2)

### ISSUE THREAD

**Issue by IL2** [dbeaver/dbeaver#14800]
#### System information: 
- Windows 10 x64
- DBeaver 2.1.3
- Office Integration

#### Connection specification:
- DB2 AS/400 7.4
- jt400 10.7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? none

#### Describe the problem you're observing:
Compound SQL statements fail if include "END IF"/ "END WHILE" keywords with default delimiter settings
https://www.ibm.com/docs/en/i/7.4?topic=routines-dynamic-compound-statement
![image](https://user-images.githubusercontent.com/1766789/144763331-d9ece295-422c-4a80-9fe1-f3f61d78fff2.png)
1) Query 1 below runs fine with the default delimiter (with the settings above)
2) Query 2 and Query fail with
`SQL Error [42601]: [SQL0104] Token <END-OF-STATEMENT> was not valid. Valid tokens: ;. Cause . . . . . :   A syntax error was detected at token <END-OF-STATEMENT>.  Token <END-OF-STATEMENT> is not a valid token.  A partial list of valid tokens is ;.  This list assumes that the statement is correct up to the token.  The error may be earlier in the statement, but the syntax of the statement appears to be valid up to this point. Recovery  . . . :   Do one or more of the following and try the request again: -- Verify the SQL statement in the area of the token <END-OF-STATEMENT>. Correct the statement.  The error could be a missing comma or quotation mark, it could be a misspelled word, or it could be related to the order of clauses. -- If the error token is <END-OF-STATEMENT>, correct the SQL statement because it does not end with a valid clause.`
**because end of the statement is not detected properly, i.e. "END IF" is the last statement which is sent to server instead of the last "END"**
![image](https://user-images.githubusercontent.com/1766789/144763451-10537644-cdbb-4973-a3bf-a7e48ed5d4bc.png)
3) Query runs fine if executed block is selected without closing ";" after the last "END"
![image](https://user-images.githubusercontent.com/1766789/144763635-47151f97-ed75-4241-be30-ef87daeb60bb.png)
4) Example in the document doesn't have closing ";" after the last "END"
![image](https://user-images.githubusercontent.com/1766789/144763766-49c4ce85-ced3-4f08-b4bd-f965da49400f.png)
**But in that case two compound SQL statements are executed, because block end is not properly ended with ";"**
`SQL Error [42601]: [SQL0199] Keyword BEGIN not expected. Valid tokens: <END-OF-STATEMENT>. Cause . . . . . :   The keyword BEGIN was not expected here.  A syntax error was detected at keyword BEGIN.  The partial list of valid tokens is <END-OF-STATEMENT>. This list assumes that the statement is correct up to the unexpected keyword.  The error may be earlier in the statement but the syntax of the statement seems to be valid up to this point. Recovery  . . . :   Examine the SQL statement in the area of the specified keyword.  A colon or SQL delimiter may be missing. SQL requires reserved words to be delimited when they are used as a name. Correct the SQL statement and try the request again.`
5) if Statements Delimiter is changed to "@", Ignore native delimiter checked, and ";" at the end of blocks are replaced with "@" all queries runs fine

Desired behavior would be proper detection of the last "END;" in the SQL compound statements block with
IF..END IF https://www.ibm.com/docs/en/i/7.4?topic=pl-if-statement
REPEAT..END REPEAT https://www.ibm.com/docs/en/i/7.4?topic=pl-repeat-statement
WHILE..END WHILE https://www.ibm.com/docs/en/i/7.4?topic=pl-while-statement
FOR..END FOR https://www.ibm.com/docs/en/i/7.4?topic=pl-statement

#### Steps to reproduce, if exist:
DECLARE GLOBAL TEMPORARY TABLE SESSION.List (seq int GENERATED ALWAYS AS IDENTITY) WITH REPLACE;
-- Query 1
BEGIN
    DECLARE i int DEFAULT 0;
    SET i = (SELECT COUNT(*) FROM SESSION.List);
    SET i = i + 1;
    INSERT INTO SESSION.List
    DEFAULT VALUES;
END;
-- Query 2
BEGIN
    DECLARE i int DEFAULT 0;
    SET i = (SELECT COUNT(*) FROM SESSION.List);
    SET i = i + 1;
    IF i < 10 THEN
        INSERT INTO SESSION.List
        DEFAULT VALUES;
    END IF;
END;
-- Query 3
BEGIN
    DECLARE i int DEFAULT 0;
    SET i = (SELECT COUNT(*) FROM SESSION.List);
    WHILE i < 10 DO
        INSERT INTO SESSION.List
        DEFAULT VALUES;
        SET i = i + 1;
    END WHILE;
END;
SELECT * FROM SESSION.List;

**Comment by ShadelessFox** [comment]
Hello @IL2,

Thank you for the report.

**Comment by ShadowNev** [comment]
it's again not work properly
earlier I workaround this by selecting whole procedure block and hitting CTRL+ENTER
but in 23.2.5 it's broken again

**Comment by ShadelessFox** [comment]
Hello @ShadowNev,

Please provide footage showing your issue. Unfortunately, the provided description "broken again" is not very descriptive.

**Comment by ShadowNev** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/42059626/2d963a22-996f-4f6c-b4b2-84845ab6e559)
![image](https://github.com/dbeaver/dbeaver/assets/42059626/c2f8298a-8bd7-4ab7-87d7-9e43df145d81)

**Comment by E1izabeth** [comment]
That's a separate issue. Please create a new one.

**Comment by ShadowNev** [comment]
looks like it catch 'END IF' as 'END' for  BEGIN/END

due to it return message
`SQL Error [42601]: An unexpected token "END-OF-STATEMENT" was found following "TE stmt".  Expected tokens may include:  "  
   END IF".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.31.10
`

**Comment by ShadowNev** [comment]
> That's a separate issue. Please create a new one.

I'm pretty sure that's same issue with how DBeaver work with 'END IF' because if I change delimiter to anything else and suppress native delimiter it works perfectly

**Comment by dolphinotaku** [comment]
seems the End of Statement having the similar issue. below SQL worked in Data Studio 4.1.1 Client, but not work in dbeaver 24.0.2

```
select
                            sdc.sdcCode,
                            sdc.sdcName,
                            sdc.sdcNameInChinese,

                            s.nameInENGLISH,
                            s.nameInCHINESE,
                            s.SDCSNO,

                            REQUESTID,
                            APPLICATIONREFNUM,
                            SERVICEYEAR,
                            --SDCCODE,
                            --SDCSNO,
                            DOCTYPE,
                            DOCEXPIREDATE,
                            SUPDOC,
                            SUPDOCTHUMBNAIL,
                            REQUESTTYPE,
                            REQUESTSTATUS,
                            CREATEDON,
                            REASON,
                            REVIEWEDBY,
                            REVIEWEDON
                            
                            from
                            EP_APPEALWAIVEREQUEST awr
                            left join student s on awr.SDCSNO = s.SDCSNO
                            left join sdcprofile sdc on awr.sdcCode = sdc.sdcCode
                            where
                            awr.createdon >= '2024-02-01' and awr.createdon < '2024-04-10-23.59.59.000000'
                            AND (awr.sdcCode in ('AS1') OR 'ALL' = 'AS1')
                            AND (SUBSTRING(UPPER(awr.requestType),1,1) = 'A' OR SUBSTRING('ALL',1,1) = 'A')
                            AND (SUBSTRING(UPPER(awr.requestStatus),1,1) = 'S' OR SUBSTRING('ALL',1,1) = 'S')
```

The Error Shows

SQL Error [42601]: An unexpected token "END-OF-STATEMENT" was found following "NG('ALL',1,1) = 'S')".  Expected tokens may include:  "<select_clause>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.33.31

The Error Details Shows
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: An unexpected token "REQUESTID" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<values>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.33.31
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:614)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:505)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:524)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:976)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4155)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5152)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: An unexpected token "REQUESTID" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<values>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.33.31
	at com.ibm.db2.jcc.am.b4.a(b4.java:810)
	at com.ibm.db2.jcc.am.b4.a(b4.java:66)
	at com.ibm.db2.jcc.am.b4.a(b4.java:140)
	at com.ibm.db2.jcc.am.kn.c(kn.java:2868)
	at com.ibm.db2.jcc.am.kn.d(kn.java:2852)
	at com.ibm.db2.jcc.am.kn.b(kn.java:2212)
	at com.ibm.db2.jcc.t4.aa.k(aa.java:442)
	at com.ibm.db2.jcc.t4.aa.c(aa.java:100)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.au.h(au.java:124)
	at com.ibm.db2.jcc.am.kn.ak(kn.java:2207)
	at com.ibm.db2.jcc.am.kn.a(kn.java:3412)
	at com.ibm.db2.jcc.am.kn.e(kn.java:1138)
	at com.ibm.db2.jcc.am.kn.execute(kn.java:1117)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```
