### ISSUE TITLE
Athena connections broken in DBeaver 21.3.0

### ISSUE THREAD

**Issue by robmoss2k** [dbeaver/dbeaver#14825]
#### System information: 
- Windows 11
- 21.3.0
- AWS Athena driver extension

#### Connection specification:
- AWS Athena
- Standard driver
- No tunnels or proxies

#### Describe the problem you're observing:

Athena connections are broken by the following commit: https://github.com/dbeaver/dbeaver/commit/77ae18807fe7d07a3adaa8c2a16ff93ee4980c6b

This commit was included in DBeaver 21.3.0 via issue #13654.

Rolling back to DBeaver 21.2.5 allows me to connect to Athena. Rolling forward to 21.3.0 breaks it again with an "Invalid JDBC URL" message.

#### Steps to reproduce, if exist:

Install DBeaver 21.3.0
Attempt to connect to Athena
Receive a JDBC URL error

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-07 15:33:16.814
!MESSAGE Invalid JDBC URL: jdbc:athena://AWSRegion=us-east-1;
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-07 15:33:16.814
!MESSAGE Invalid JDBC URL: jdbc:athena://AWSRegion=us-east-1;
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Invalid JDBC URL: jdbc:athena://AWSRegion=us-east-1;
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:219)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.athena.model.AthenaDataSource.<init>(AthenaDataSource.java:39)
	at org.jkiss.dbeaver.ext.athena.AthenaDataSourceProvider.openDataSource(AthenaDataSourceProvider.java:57)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:898)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Could you try to create a new Athena connection and test it?
Or just change something in existing Athena connection settings (this will re-generate URL) and try to connect?

**Comment by Matvey16** [comment]
@robmoss2k Can you check what URL Template you have in driver settings and if it is not like in the picture, try to reset it to default?

![image](https://user-images.githubusercontent.com/82543000/145208818-d0125893-3595-4bcb-9cae-afeb79529ee3.png)

**Comment by robmoss2k** [comment]
This doesn't work:

`jdbc:athena://AWSRegion=us-east-1;`

But this does:

`jdbc:athena://AWSRegion={region};`
