### ISSUE TITLE
Keyword "STRICT" in SQLite 3.37.0 results in an error

### ISSUE THREAD

**Issue by Roenbaeck** [dbeaver/dbeaver#14844]
#### System information: 
- Windows 10 - Operating system (distribution) and version
- 21.3.0.202111281534 - DBeaver version

#### Connection specification:
- File generated by SQLite 3.37.0 - Database name and version
- org.xerial:sqlite-jdbc:RELEASE 3.36.0.3 - Driver name

#### Describe the problem you're observing:
The new keyword "STRICT" introduced in 3.37.0 results in an error: 
`[SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (Thing) - near "STRICT": syntax error)`

#### Steps to reproduce, if exist:
Use SQLite 3.37.0 to create a strict table in a database file: 
```
                create table if not exists Thing (
                    Thing_Identity integer not null, 
                    constraint unique_and_referenceable_Thing_Identity primary key (
                        Thing_Identity
                    )
                ) STRICT;
```

The file can be accessed by DBeaver, but tables cannot be browsed. This is likely due to the JDBC driver being one version behind the generated file. There is, however, no new version of the driver supporting 3.37.0 (https://github.com/xerial/sqlite-jdbc/issues). I am not sure if DBeaver can ignore the keyword or if a new driver has to come first.

**Comment by flambchap** [comment]
Hi @Roenbaeck. Could you please send the [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by Roenbaeck** [comment]
```
!SESSION 2021-12-08 12:36:38.855 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2021-12-08 12:38:56.325
!MESSAGE Datasource 'sqlite_jdbc-17d99c5d65f-5a0ee15b1ad5d7d8' not found

!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-08 15:48:46.484
!MESSAGE [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (Thing) - near "STRICT": syntax error)
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-08 15:48:46.484
!MESSAGE [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (Thing) - near "STRICT": syntax error)
!STACK 0
org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (Thing) - near "STRICT": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:56)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getTables(JDBC3DatabaseMetaData.java:1844)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:576)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:67)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:146)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:130)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:948)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1020)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:589)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:458)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by flambchap** [comment]
Thank you. There is nothing we can do other than wait for the new driver version.

**Comment by mkgrgis** [comment]
Look like there is `STRICT` support in SQL console.  @Roenbaeck, can you verify a new driver version and close this issue?

**Comment by Roenbaeck** [comment]
Verified. It works as it should. Tried two drivers 3.40.0.0 and the latest 3.41.2.1 and it works with both.
