### ISSUE TITLE
mongo function createCollection

### ISSUE THREAD

**Issue by Korov** [dbeaver/dbeaver#14876]
command: `db.createCollection("book_info", {storageEngine: {wiredTiger: {configString: "block_compressor=zstd"}}});`

result:

```java
org.jkiss.dbeaver.model.exec.DBCException: TypeError: Cannot find function createCollection in object {}. (js#1)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:65)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot find function createCollection in object {}. (js#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4280)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4258)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4291)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4310)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4382)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2584)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2566)
	at org.mozilla.javascript.gen.js_2._c_script_0(js:1)
	at org.mozilla.javascript.gen.js_2.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.js_2.call(js)
	at org.mozilla.javascript.gen.js_2.exec(js)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1234)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.runInRhino(MongoJSProcessor.java:115)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.eval(MongoJSProcessor.java:90)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:55)
	... 12 more
```

**Comment by flambchap** [comment]
Thank you for the report. We support some subset of valid mongo shell queries. We need to make it bigger.

Here is the list of the queries we need to take care of:
```JS
db.createCollection()
db.collectionName.drop()
db.collectionName.deleteMany()
db.collectionName.updateOne()
db.collectionName.deleteOne()
cursor.allowDiskUse()
```

**Comment by ShadelessFox** [comment]
Following functions were implemented:

```javascript
db.createCollection(name)
db.collectionName.updateOne(filter, update)
db.collectionName.updateMany(filter, update)
db.collectionName.deleteOne(filter)
db.collectionName.deleteMany(filter)
db.collectionName.drop()
```

Other functions are not available in the SDK we're using.

**Comment by uslss** [comment]
all mentioned functions works ok with mongo 3.4.10 (db1).

Functions mentioned below aren't working against 4.4.10 (atlas) and 4.4.3(db6).
```javascript
db.createCollection(name)
db.collectionName.updateOne(filter, update)
db.collectionName.updateMany(filter, update)
```
an attempt to execute them ends up with an error like:

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -runTask @General:exp1
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -runTask @General:exp1

org.jkiss.dbeaver.model
Error
Tue Dec 14 16:20:21 MSK 2021
Can't find method com.dbeaver.db.mongodb.exec.js.MongoJSCollection.updateMany(object,object,object). (js#1)

org.mozilla.javascript.EvaluatorException: Can't find method com.dbeaver.db.mongodb.exec.js.MongoJSCollection.updateMany(object,object,object). (js#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:972)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1025)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:988)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:145)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:65)
	at org.mozilla.javascript.gen.js_22._c_script_0(js:1)
	at org.mozilla.javascript.gen.js_22.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.js_22.call(js)
	at org.mozilla.javascript.gen.js_22.exec(js)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1234)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.runInRhino(MongoJSProcessor.java:115)
	at com.dbeaver.db.mongodb.exec.js.MongoJSProcessor.eval(MongoJSProcessor.java:90)
	at com.dbeaver.db.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:55)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3477)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
works ok in case of functions execution without options
