### ISSUE TITLE
Missing parentheses on generated query when filtering/sorting by composite type subfields (Postgres)

### ISSUE THREAD

**Issue by ivanlonel** [dbeaver/dbeaver#14945]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.3.1
- Additional extensions: Office support, git support, SSHJ, Debug and SVG

#### Connection specification:
- Database name and version: Postgresql 14.1
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When using the data editor to filter or sort by a field from a composite type, DBeaver doesn't enclose the name of the composite column in parentheses, causing Postgres to interpret it as the name of a table.

For example, it generates this query:
```pgsql
SELECT x.* FROM public.on_hand x
WHERE x.item."name" IN ('Item 10')
```

Instead of this:
```pgsql
SELECT x.* FROM public.on_hand x
WHERE (x.item)."name" IN ('Item 10')
```

When sorting, the generated query looks like this:
```pgsql
SELECT * FROM public.on_hand
ORDER BY item.price
```

But it also needs the parentheses to work:
```pgsql
SELECT * FROM public.on_hand
ORDER BY (item).price
```

In both cases, Postgres gives the following error:
```
SQL Error [42P01]: ERROR: missing FROM-clause entry for table "item"
```

#### Steps to reproduce, if exist:

1. Create an example set on Postgres:

```pgsql
CREATE TYPE inventory_item AS (
	name text,
	supplier_id integer,
	price numeric(5,2)
);

CREATE TABLE on_hand (
	item inventory_item,
	count integer
);

INSERT INTO on_hand
	SELECT
		ROW('Item ' || n, random() * 100, random() * 100)::inventory_item,
		random() * 10000
	FROM generate_series(1, 1000) as n;
```

2. Open table `on_hand` in the data editor and try to filter it by `name`, using the filter button from the column header:

![image](https://user-images.githubusercontent.com/15915901/146618941-7a0a5fc7-ad80-4562-a276-ffa7fa85b093.png)

Alternatively, just try to sort by any of the 3 fields of composite column `item`.

3. Enjoy your `SQL Error [42P01]: ERROR: missing FROM-clause entry for table "item"` :)

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-17 20:31:18.578
!MESSAGE SQL Error [42P01]: ERROR: missing FROM-clause entry for table "item"
  Position: 40
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-17 20:31:18.578
!MESSAGE SQL Error [42P01]: ERROR: missing FROM-clause entry for table "item"
  Position: 40
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2021-12-17 20:31:18.578
!MESSAGE ERROR: missing FROM-clause entry for table "item"
  Position: 40
!STACK 0
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "item"
  Position: 40
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LonwoLonwo** [comment]
Hello @ivanlonel 
Thanks for the bug report!
