### ISSUE TITLE
Filter dialog doesn't show all options for Postgres composite type subfields, even with "Read from server" checked

### ISSUE THREAD

**Issue by ivanlonel** [dbeaver/dbeaver#14998]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.3.1
- Additional extensions: Office support, git support, SSHJ, Debug and SVG

#### Connection specification:
- Database name and version: Postgresql 14.1
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I click on the funnel icon at the header of a subfield of Postgres composite column, the filter window that appears for me to select the values only shows those that are already loaded in the data editor. Keeping "Read from server" checked doesn't seem to make a difference.

#### Steps to reproduce, if exist:

1. Create testing set:
```pgsql
CREATE TYPE inventory_item AS (
	name text,
	supplier_id integer,
	price numeric(5,2)
);

CREATE TABLE test (
	id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	item inventory_item
);

INSERT INTO test (item)
	SELECT ROW('Item ' || n, n / 10 + 1, random() * 100)::inventory_item
	FROM generate_series(1, 1000) as n;
```

2. Open table `test` in the data editor with the result-set fetch size set to 200. Make sure it didn't load more than the first 200 rows.

3. Click on the filter icon of column `item.supplier_id`. Make sure "Read from server" is checked. You should see only values 1 to 21, like this:
![image](https://user-images.githubusercontent.com/15915901/147128438-06000303-bd74-4c07-9449-26fd2f153f05.png)

4. If you scroll to the bottom of the currently loaded rows in order to load the next 200, repeating step 3 will show values 1 to 41. And so on.

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-22 14:05:24.613
!MESSAGE SQL Error [42809]: ERROR: "inventory_item" is a composite type
  Position: 35
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-22 14:05:24.613
!MESSAGE ERROR: "inventory_item" is a composite type
  Position: 35
!STACK 0
org.postgresql.util.PSQLException: ERROR: "inventory_item" is a composite type
  Position: 35
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:240)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.lambda$0(GenericFilterValueEdit.java:344)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.readEnumeration(GenericFilterValueEdit.java:342)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:633)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
thanks for the report
