### ISSUE TITLE
[Derby] Incorrect query sent when searching in column value filter

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#15003]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.3.2 CE

#### Connection specification:
- Database name and version Derby 10.15.1.3
- Driver name Apache Derby Network Client JDBC Driver 10.15.2.0
- SSH

#### Describe the problem you're observing:
Searching in column filter can't be performed without `Show row count`

#### Steps to reproduce, if exist:
1. Open filter in column header
2. Enter a valid value
3. Enable `Read from server` and disable `show row count`

**Expected:** Data is found

**Actual:** Incorrect syntax leads to error and blank window

![7d9ROZXB26](https://user-images.githubusercontent.com/82543000/147259920-4d74345b-08ff-4b24-b451-aa4356e662cd.gif)

```
ERROR 42X01: Syntax error: Encountered "NULL" at line 1, column 26.
	at org.apache.derby.client.am.ClientStatement.completeSqlca(ClientStatement.java:2116)
	at org.apache.derby.client.net.NetStatementReply.parsePrepareError(NetStatementReply.java:579)
	at org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(NetStatementReply.java:145)
	at org.apache.derby.client.net.NetStatementReply.readPrepareDescribeOutput(NetStatementReply.java:54)
	at org.apache.derby.client.net.StatementReply.readPrepareDescribeOutput(StatementReply.java:41)
	at org.apache.derby.client.net.NetStatement.readPrepareDescribeOutput_(NetStatement.java:156)
	at org.apache.derby.client.am.ClientStatement.readPrepareDescribeOutput(ClientStatement.java:1702)
	at org.apache.derby.client.am.ClientPreparedStatement.readPrepareDescribeInputOutput(ClientPreparedStatement.java:1914)
	at org.apache.derby.client.am.ClientPreparedStatement.flowPrepareDescribeInputOutput(ClientPreparedStatement.java:1977)
	at org.apache.derby.client.am.ClientPreparedStatement.prepare(ClientPreparedStatement.java:315)
	at org.apache.derby.client.am.ClientConnection.prepareStatementX(ClientConnection.java:1956)
	at org.apache.derby.client.am.ClientConnection.prepareStatement(ClientConnection.java:1466)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:406)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:231)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.lambda$0(GenericFilterValueEdit.java:344)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$5.readEnumeration(GenericFilterValueEdit.java:342)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:633)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by Matvey16** [comment]
Verified
