### ISSUE TITLE
Elasticsearch no tables

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#15028]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/18223385/147403647-1c200c91-0e71-4156-8e3a-7fdfee49e08b.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/18223385/147403638-718f6e02-7a96-417a-88b0-c8b3df28b2a4.png">
<img width="984" alt="image" src="https://user-images.githubusercontent.com/18223385/147403652-45628b0a-8dc0-4140-87f1-4c805b81a913.png">
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/18223385/147403662-82ed03b2-c447-4676-a7cc-0a9507a9e459.png">

**Comment by hktalent** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/18223385/147403943-64c21bba-e78a-4988-ac87-080fcd476da7.png">
docker ps -a
17a25bffa763   elasticsearch:7.16.2             "/bin/tini -- /usr/l…"   27 hours ago   Up About an hour            0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                                                                         es
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/18223385/147403991-c361a174-f5a5-4283-b17f-4a2d83e17ffd.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/18223385/147403996-43fdba83-68f7-466c-b9c5-f2d6fadfa054.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/18223385/147404005-86fa101c-961e-4423-83eb-838439ebd5b6.png">

**Comment by uslss** [comment]
It seems jdbc connect requires Platinum subscription
https://www.elastic.co/downloads/jdbc-client

**Comment by hktalent** [comment]
@uslss  I tried every version of the driver, but all failed

**Comment by LonwoLonwo** [comment]
Can you provide more [error logs](https://github.com/dbeaver/dbeaver/wiki/Log-files), please?

**Comment by uslss** [comment]
error appears after driver update e.g. to 7.16.2.
At first attempt of the Test connection:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/

org.jkiss.dbeaver.model
Error
Mon Dec 27 15:35:03 MSK 2021
shadow.org.elasticsearch.xcontent.XContentBuilderExtension: org.elasticsearch.xpack.sql.jdbc.XContentSqlExtension not a subtype

java.util.ServiceConfigurationError: shadow.org.elasticsearch.xcontent.XContentBuilderExtension: org.elasticsearch.xpack.sql.jdbc.XContentSqlExtension not a subtype
	at java.base/java.util.ServiceLoader.fail(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
	at shadow.org.elasticsearch.xcontent.XContentBuilder.<clinit>(XContentBuilder.java:113)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:177)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:119)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:90)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:80)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.execute(JdbcStatement.java:151)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:41)
	at org.elasticsearch.xpack.sql.jdbc.JdbcDatabaseMetaData.getTypeInfo(JdbcDatabaseMetaData.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTypeInfo(JDBCDatabaseMetaDataImpl.java:1235)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache.prepareObjectsStatement(JDBCBasicDataTypeCache.java:55)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:478)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Second attempt:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/

org.jkiss.dbeaver.model
Error
Mon Dec 27 15:35:07 MSK 2021
Could not initialize class shadow.org.elasticsearch.xcontent.XContentBuilder

java.lang.NoClassDefFoundError: Could not initialize class shadow.org.elasticsearch.xcontent.XContentBuilder
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:177)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:119)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:90)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:80)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.execute(JdbcStatement.java:151)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:41)
	at org.elasticsearch.xpack.sql.jdbc.JdbcDatabaseMetaData.getTypeInfo(JdbcDatabaseMetaData.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTypeInfo(JDBCDatabaseMetaDataImpl.java:1235)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache.prepareObjectsStatement(JDBCBasicDataTypeCache.java:55)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:478)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by hktalent** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/18223385/147522181-db5f78df-6a2d-4e27-a801-3c403bef2bad.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/18223385/147522198-df5c9fc0-483d-4d09-80fe-c2ddf0c3bc9a.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/18223385/147522246-70327524-a18f-40d8-b187-9c6685ab3d74.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/18223385/147522337-0976f708-59ce-44b2-a959-e292a3fa289b.png">
```
java.util.ServiceConfigurationError: shadow.org.elasticsearch.xcontent.XContentBuilderExtension: org.elasticsearch.xpack.sql.jdbc.XContentSqlExtension not a subtype
	at java.base/java.util.ServiceLoader.fail(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
	at shadow.org.elasticsearch.xcontent.XContentBuilder.<clinit>(XContentBuilder.java:113)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:177)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:119)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:90)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:80)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.execute(JdbcStatement.java:151)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:41)
	at org.elasticsearch.xpack.sql.jdbc.JdbcDatabaseMetaData.getTypeInfo(JdbcDatabaseMetaData.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTypeInfo(JDBCDatabaseMetaDataImpl.java:1235)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCBasicDataTypeCache.prepareObjectsStatement(JDBCBasicDataTypeCache.java:55)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:478)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:905)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:108)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:50)
	at org.jkiss.dbeaver.runtime.WebUtils.downloadRemoteFile(WebUtils.java:128)
	at org.jkiss.dbeaver.runtime.WebUtils.downloadRemoteFile(WebUtils.java:123)
	at org.jkiss.dbeaver.ui.app.standalone.update.VersionUpdateDialog$1.run(VersionUpdateDialog.java:275)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by hktalent** [comment]
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CN
Framework arguments:  -keyring /.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/51pwn/.eclipse_keyring

java.sql.SQLInvalidAuthorizationSpecException: current license is non-compliant for [jdbc]
	at shadow.org.elasticsearch.xpack.sql.client.JreHttpUrlConnection$SqlExceptionType.asException(JreHttpUrlConnection.java:354)
	at shadow.org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.parserError(JreHttpUrlConnection.java:231)
	at shadow.org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:177)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$1(HttpClient.java:126)
	at shadow.org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.http(JreHttpUrlConnection.java:75)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$2(HttpClient.java:122)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:121)
	at shadow.org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:90)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:80)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:67)
	at org.elasticsearch.xpack.sql.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:774)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:574)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:67)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:146)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:130)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:948)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1020)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:589)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:458)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:78)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by hktalent** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/18223385/147528155-eeb71e4a-569b-4375-905a-042218d36dff.png">
Apparently does not support 7.16.2

**Comment by hktalent** [comment]
http://0.0.0.0:9200/_xpack/license
<img width="666" alt="image" src="https://user-images.githubusercontent.com/18223385/147528919-cfbf9c91-4471-44ac-9bb0-bcbd0f7a9c5b.png">
copy to file
~/.eclipse_keyring

**Comment by uslss** [comment]
@hktalent please, provide steps to reproduce the issue and what should be fixed in your opinion

**Comment by hktalent** [comment]
@uslss 
I gave up, because this jdbc needs official authorization to be used, and there is currently no version authorization of 7.16.2, so I gave up

**Comment by uslss** [comment]
Unfortunately, we cannot fix elasticsearch issues.

**Comment by hktalent** [comment]
@uslss  @Skydiveroid Thank you very much, welcome to China and invite you to drink
