### ISSUE TITLE
Invalid column name 'is_external'

### ISSUE THREAD

**Issue by tianke3477** [dbeaver/dbeaver#15036]
Hello,

#### System information: 
Win10, DBeaver CE 21.3.2

#### Connection specification:
Microsoft SQL Server 2014
-
#### **Error Info**

!ENTRY org.jkiss.dbeaver.model 4 0 2021-12-27 09:05:55.594
!MESSAGE Invalid column name 'is_external'.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-12-27 09:05:55.594
!MESSAGE Invalid column name 'is_external'.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'is_external'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:86)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema.getTables(SQLServerSchema.java:216)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:954)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1026)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:589)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:458)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:79)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @tianke3477 
Thanks for the bug report.
At what moment does the error occur?

**Comment by jason6822** [comment]
> 
when Loading Tables, Microsoft SQL Server 2016 has no this bug

**Comment by tianke3477** [comment]
Hello @LonwoLonwo 

![1640587885](https://user-images.githubusercontent.com/613854/147443386-5eb35e89-404e-4df2-a099-8e3e6624d4cb.png)

**Comment by timotirta** [comment]
Same here. got it on Microsoft SQL Server 2016 when loading the table.

**Comment by damianozucconi** [comment]
Got the same on SQLServer 2008 R2

**Comment by uslss** [comment]
verified

**Comment by serge-rider** [comment]
DBeaver 21.3.2 was re-published.
You can download new fixed binaries from dbeaver.io or from GitHub

**Comment by mreschke** [comment]
Not bumping the version breaks other automated services from detecting an update.  Should bump to 21.3.3 so downstream linux package managers get this fix

**Comment by Exanime4Ever** [comment]
Seriously appreciate if the version can be bumped so the wheels turn for Linux updates again... DBeaver is my daily driver for work and I had to fall back to my hated backup Aqua because of this issue

**Comment by pswilde** [comment]
The re-published 21.3.2 works - Thanks

But until that becomes mainstream in Linux package managers (ideally by bumping the version number), a manual download from Early Access https://dbeaver.io/files/ea/ will have to do!
I suspect a new release is due, so the version number will be bumped then.

**Comment by cyberbeat** [comment]
I experience this problem with 21.3.4 (Eclipse Package from https://dbeaver.io/update/ce/latest/)

**Comment by ShadelessFox** [comment]
Hello @cyberbeat,

Please provide more information about the database you're trying to connect to.

**Comment by cyberbeat** [comment]
@[ShadelessFox](https://github.com/ShadelessFox)

```
Microsoft SQL Server 12.00.4100
Microsoft SQL Server 2014 - 12.0.4100.1 (X64) 
	Apr 20 2015 17:29:27 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
```

Now on: DBeaver IDE, 22.0.0.202203060510

**Comment by ShadelessFox** [comment]
@cyberbeat,

Could you please also provide a screenshot of Query Manager showing the failing query (one involves the `is_external` column)?

You can find more information here: https://github.com/dbeaver/dbeaver/wiki/Query-Manager.

**Comment by cyberbeat** [comment]
This is from the query manager log:
```
März-11 13:01:13	SQL / Meta	SELECT o.*,ep.value as description,t.is_external FROM XXX.sys.all_objects o
LEFT OUTER JOIN XXX.sys.extended_properties ep ON ep.class=1 AND ep.major_id=o.object_id AND ep.minor_id=0 AND ep.name='MS_Description'
LEFT OUTER JOIN XXX.sys.tables t ON t.object_id=o.object_id
WHERE o.type IN ('U','S','V','TT') AND o.schema_id = 5	63		[207] Ungültiger Spaltenname 'is_external'. XXX	Metadata
```

**Comment by ShadelessFox** [comment]
@cyberbeat,

Are you sure you are running against the newest version of DBeaver?

Perhaps reinstallation would help.

**Comment by cyberbeat** [comment]
"DBeaver IDE, 22.0.0.202203060510", this is what eclipse installation-details shows me. Maybe there is some update-server problem. Is there another way to show the "real" version number? I'll try a reinstall the next days..

**Comment by ShadelessFox** [comment]
That's the real version.

I guess that the plugin has failed to update somehow, but that seems weird.

Reinstallation might not help, but at least we will know that the issue lies somewhere else.

**Comment by cyberbeat** [comment]
I now downloaded dbeaver 22 standalone. The issue still exists. Perhaps it would be better to directly test on that column, before query it?

**Comment by cyberbeat** [comment]
Here are the exception logs from starting dbeaver from shell:

```
2022-03-14 14:29:08.117 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [207] [S0001]: Ungültiger Spaltenname 'is_external'.
org.jkiss.dbeaver.model.sql.DBSQLException: SQL-Fehler [207] [S0001]: Ungültiger Spaltenname 'is_external'.
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
        at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:86)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema.getTables(SQLServerSchema.java:216)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:961)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1033)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Ungültiger Spaltenname 'is_external'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        ... 24 more
2022-03-14 14:29:08.122 - Ungültiger Spaltenname 'is_external'.
com.microsoft.sqlserver.jdbc.SQLServerException: Ungültiger Spaltenname 'is_external'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
        at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:86)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema.getTables(SQLServerSchema.java:216)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:961)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1033)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2022-03-14 14:30:39.589 - Error closing active transaction
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4568)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$2(JDBCDataSource.java:307)
        at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:423)
        at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:220)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by cyberbeat** [comment]
I checked out your branch, and built, still did not work. I then commented out these lines:

```
             if (SQLServerUtils.isDriverAzure(driver)) {
                 return supportsExternalTables = true;
             }
```

Now it works!

**Comment by ShadelessFox** [comment]
Despite all the possible fixes, I want to find the real reason why DBeaver thinks that your SQL Server does support external tables. We check if the server version is greater than SQL Server 2016, but your version is definitely older.

Can you please provide the output of the `select @@version` query?

**Comment by ShadelessFox** [comment]
Also, what driver do you use? Isn't it the `Azure SQL Server`, by any chance?

Update: according to your previous comment, it's definitely Azure.

Are you sure you need this driver over the regular one?

**Comment by cyberbeat** [comment]
I used Azure driver. I am quite sure, when I searched for an alternative in DBeaver driver selection dialog before a few months, I could not find any. But now I also found alternatives like "Microsoft SQL Server" (although they seem use the same jdbc driver jars?). Would this fix all my problems?

**Comment by ShadelessFox** [comment]
The code snippet mentioned in https://github.com/dbeaver/dbeaver/issues/15036#issuecomment-1068913032 checks for the Azure driver, so it happened to be your case. It doesn't depend on the driver's jars in this particular situation.

So, it would fix your issue, yes. Although, we can avoid such problems entirely by not relying on the driver used.

**Comment by LonwoLonwo** [comment]
Ok, now we will first ask the database about the `is_external` column in the `sys.tables` and then use this column or not.

![2022-03-16 15_24_33-DBeaver Ultimate 22 0 0 - _postgres 13 3_Script-81](https://user-images.githubusercontent.com/45152336/158589441-faa04a0c-fbdf-43ee-bd49-99ccb601c29c.png)

**Comment by cyberbeat** [comment]
Thanks, great
