### ISSUE TITLE
Import GIT project using the New Project wizard throws coreException

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15046]
#### System information: 
- Win10, DBeaver CE 21.3.2

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/43252954/147456427-20559465-eb7b-41a9-b108-6f26376a8c28.png)

#### Steps to reproduce, if exist:
open projects tab and start cloning project from GIT (e.g. https://github.com/dbeaver/dbeaver-qa.git). 
On this step select Import using the New Project wizard and click finish
![image](https://user-images.githubusercontent.com/43252954/147456647-3ed15027-1f10-4b0e-b219-c115704c14d6.png)
Select Project wizard and click next
Type project name and click Finish.
Here you can see the error
#### Include any warning/errors/backtraces from the logs
```
Connecting Git team provider failed. See log for details.
Connecting Git team provider failed. See log for details.
Error connecting project testing, no Git repositories found
```
```
!ENTRY org.eclipse.egit.ui 4 0 2021-12-26 19:42:48.270
!MESSAGE Connecting Git team provider failed. See log for details.
!STACK 1
org.eclipse.core.runtime.CoreException: Connecting Git team provider failed. See log for details.
	at org.eclipse.egit.core.op.ConnectProviderOperation.execute(ConnectProviderOperation.java:118)
	at org.eclipse.egit.ui.internal.clone.GitImportWizard$8.run(GitImportWizard.java:289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2333)
	at org.eclipse.egit.ui.internal.clone.GitImportWizard.importProjects(GitImportWizard.java:296)
	at org.eclipse.egit.ui.internal.clone.GitImportWizard.access$2(GitImportWizard.java:236)
	at org.eclipse.egit.ui.internal.clone.GitImportWizard$4.run(GitImportWizard.java:206)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Contains: Error connecting project lalala, no Git repositories found
!SUBENTRY 1 org.eclipse.egit.core 4 0 2021-12-26 19:42:48.270
!MESSAGE Connecting Git team provider failed. See log for details.
!SUBENTRY 2 org.eclipse.egit.core 4 0 2021-12-26 19:42:48.270
!MESSAGE Error connecting project lalala, no Git repositories found
```

**Comment by serge-rider** [comment]
`dbeaver-qa` already contains Eclipse project definition (.project file).

Thus you must import it as Import existing Eclipse Projects.
Import New Project or general project works in target repository doesn't contain .project file.
