### ISSUE TITLE
data lost when copying result as html with some column hidden

### ISSUE THREAD

**Issue by dafuzzz** [dbeaver/dbeaver#15097]
#### System information: 
- Operating system (distribution) and version: ubuntu 20.04
- DBeaver version: 21.3.2.202112271055
- Additional extensions

#### Connection specification:
- Database name and version: postgres (PostgreSQL) 10.19 (Debian 10.19-1.pgdg90+1)
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Lost data when advanced copying the whole line but hidding some column.

#### Steps to reproduce, if exist:

0. I have a table with structure and value shown below:
![image](https://user-images.githubusercontent.com/23740013/147739302-b43df968-320c-409b-8432-42e74f32aa2c.png)

1. filter some column(here, `column3`) with filter setting
![image](https://user-images.githubusercontent.com/23740013/147739392-0c15f94c-bd3c-40e3-bff7-7a60457a5d63.png)
![image](https://user-images.githubusercontent.com/23740013/147740191-65102e1d-45f6-4894-bef1-b595e78789d9.png)

2. right click the line num and select `Advanced Copy -> Copy ad HTML`

3. got html, but lost data of column4
![image](https://user-images.githubusercontent.com/23740013/147740780-c5a64976-c68c-49d8-877b-bec3fa6013e2.png)

4. Also, try to copy as JSON, got error
![image](https://user-images.githubusercontent.com/23740013/147740955-24d92432-c7b8-4293-a5a8-c311783db57c.png)

#### Include any warning/errors/backtraces from the logs

here is the log file tail output

```
2021-12-30 17:41:37.521 - Error fetching 'column4' value: Index 3 out of bounds for length 3
2021-12-30 17:41:37.521 - Bad attribute 'column4' index: 3 is out of row values' bounds (3)
2021-12-30 17:48:30.730 - Error fetching 'column4' value: Index 3 out of bounds for length 3
2021-12-30 17:48:30.730 - Bad attribute 'column4' index: 3 is out of row values' bounds (3)
2021-12-30 17:53:09.860 - Error fetching 'column4' value: Index 3 out of bounds for length 3
2021-12-30 17:53:09.865 - Index 3 out of bounds for length 3
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterJSON.exportRow(DataExporterJSON.java:117)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:233)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:107)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:252)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.ResultSetHandlerCopyAs$1.run(ResultSetHandlerCopyAs.java:182)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

English is not my native language. More information, please comment.

**Comment by uslss** [comment]
thanks for the report

**Comment by serge-rider** [comment]
Fixed.
Now data export respects visual columns order.

Note: when exporting __virtual__ columns + selected columns then virtual columns must be in the end of list.
We need another ticket for virtual columns handling. In data export virtual columns are handled on a model level and do not "know" about their visual position.

**Comment by Matvey16** [comment]
Can't copy as source code if a column is hidden.

![dbeaver_iMY74cSYjC](https://user-images.githubusercontent.com/82543000/162766579-9d59ecd6-57cf-4c7b-861e-aa9f7423ed26.gif)

```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterSourceCode.exportRow(DataExporterSourceCode.java:129)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:229)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:125)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.ResultSetHandlerCopyAs$1.run(ResultSetHandlerCopyAs.java:182)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by serge-rider** [comment]
Fixed. 
Also please test 16148

**Comment by Matvey16** [comment]
Verified
