### ISSUE TITLE
Dbeaver 21.3.2 not loading

### ISSUE THREAD

**Issue by aravindhansps** [dbeaver/dbeaver#15117]
Application not loading at startup itself. BELOW IS THE DATA FROM LOG. 

!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".

**Comment by andrematzke** [comment]
same here.

**Comment by andrematzke** [comment]
!STACK 0
java.lang.IllegalArgumentException: URI has an authority component
	at java.base/java.io.File.<init>(File.java:425)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getLocalFileFromURL(RuntimeUtils.java:197)
	at org.jkiss.dbeaver.utils.GeneralUtils.getMetadataFolder(GeneralUtils.java:661)
	at org.jkiss.dbeaver.core.DesktopPreferencesInitializer.initializeDefaultPreferences(DesktopPreferencesInitializer.java:71)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:310)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:134)
	at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:374)
	at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:225)
	at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:279)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:370)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:624)
	at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:767)
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:41)
	at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:77)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.<init>(BundlePreferenceStore.java:35)
	at org.jkiss.dbeaver.ModelPreferences.setMainBundle(ModelPreferences.java:161)
	at org.jkiss.dbeaver.core.DBeaverActivator.start(DBeaverActivator.java:63)

**Comment by andrematzke** [comment]
with 21.2.5 (https://dbeaver.io/files/21.2.5/) thus is not happening.

Machine: Windows 8.1 JRE 11 Temurin and JRE 17 Temurin

**Comment by Matvey16** [comment]
@aravindhansps Can you please provide more info. What OS do you use, how did you install DBeaver? Do you see any error message when launching Dbeaver?

**Comment by aravindhansps** [comment]
Hi,

 

I have downloaded the ZIP folder and running it on my Work Citrix machine.

**Comment by Matvey16** [comment]
@aravindhansps Please attach the full log file, it contains information needed for investigation

**Comment by aravindhansps** [comment]
PSA..

https://github.com/dbeaver/dbeaver/files/7952023/log.txt

**Comment by Matvey16** [comment]
@aravindhansps This should have been fixed in the newest version, please say if it wasn't resolved for you

**Comment by DodgeDeBoulet** [comment]
Sorry @Matvey16 , it's not.

[dbeaverCitrix-20220209.log](https://github.com/dbeaver/dbeaver/files/8033636/dbeaverCitrix-20220209.log)

EDIT: I've reverted to 21.3.0 and it is working.

**Comment by andrematzke** [comment]
[log.txt](https://github.com/dbeaver/dbeaver/files/8060088/log.txt)

Hello @Matvey16 , like DodgeDeBoulet I also still having the same errornous starting behaviour.. log.txt attached.

BR,
A.

**Comment by flambchap** [comment]
Hi guys. Could you please check out the latest (21.3.5) version and see is everything is ok?

**Comment by DodgeDeBoulet** [comment]
> Hi guys. Could you please check out the latest (21.3.5) version and see is everything is ok?

No @akilovich, there's still a problem. Log attached.
[DBeaverCitrixException.log](https://github.com/dbeaver/dbeaver/files/8124427/DBeaverCitrixException.log)

**Comment by andrematzke** [comment]
also here.


![2022-02-24 15_24_26-dbeaver](https://user-images.githubusercontent.com/33298027/155543350-169f46ba-7124-4bca-9504-6a4940872579.jpg)

[log2022024.txt](https://github.com/dbeaver/dbeaver/files/8133212/log2022024.txt)

**Comment by fwatteau** [comment]
My issue due to my workspace is on a network share (expl : \\\\myserver\user$\appdata\roaming\dbeaverdata)

I've solved with mapping a letter U on \\myserver\user$ and add argument -data U:\appdata\roaming\dbeaverdata\workspace6 to dbeaver.exe)

**Comment by andrematzke** [comment]
Dear @akilovich, 
@fwatteau mentioned a work around, which fwatteau figured out is working for him. Could this be a usable hint for a possible solution for one of the next releases ?

BR,André

**Comment by DodgeDeBoulet** [comment]
> Dear @akilovich, @fwatteau mentioned a work around, which fwatteau figured out is working for him. Could this be a usable hint for a possible solution for one of the next releases ?
> 
> BR,André

This workaround seems to work for me as well, although the path is slightly different (no "roaming" subdirectory). Not sure if it will persist across a reboot of the VDI, but I'm sure I'll find out at some point.

**Comment by andrematzke** [comment]
fwatteau's workaround is working for me also, even with 22.01. I still hope this can lead to the change, which is causing since >=21.3.1 this new (imho errornous) behaviour in Citrix/VDI environments.. and then invent a fix.

**Comment by Matvey16** [comment]
Verified
