### ISSUE TITLE
NullPointer in explain plan for postgres

### ISSUE THREAD

**Issue by eperrone-kercher** [dbeaver/dbeaver#15131]
Getting Error on Explain Plans

#### System information: 
- Operating system (distribution) and version Windows 10 Enterprise 20H2
- DBeaver version 21.3.1.202112130652
- Additional extensions: Office Extension

#### Connection specification:
- Database name and version PostgreSQL 9.5.20 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23), 64-bit
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

Getting a NullPointer when trying to do explain.  Seems to be any query.

This particular one was a simple select * from a table called action_user  the table itself is unremarkable and the error seems to occur against any table I use.

**select * from action_user;**

here is the stack trace.

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\PER97076\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2022-01-07 08:30:52.776

org.jkiss.dbeaver.model
Error
Fri Jan 07 08:43:52 EST 2022

java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgrePlanNodeBase.setAttributes(PostgrePlanNodeBase.java:110)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgrePlanNodeXML.<init>(PostgrePlanNodeXML.java:41)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgreExecutionPlan.parsePlanXML(PostgreExecutionPlan.java:157)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgreExecutionPlan.explain(PostgreExecutionPlan.java:130)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgreQueryPlaner.planQueryExecution(PostgreQueryPlaner.java:68)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:408)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:402)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @eperrone-kercher 

Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.3.3.

**Comment by Matvey16** [comment]
Verified
