### ISSUE TITLE
Adding DB2 tables to ERD diagram result in Null pointer exception

### ISSUE THREAD

**Issue by pperejonf** [dbeaver/dbeaver#15173]
#### System information: 
- Operating system (distribution) and version:  Windows 10 Home
- DBeaver version: Versión21.3.2.202112271055
- Additional extensions: Git

#### Connection specification:
- Database name and version: DB2 v10.5.0.11
- Driver name: com.ibm.db2.jcc.DB2Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: VPN Connection

#### Describe the problem you're observing:

For some unknown reason, when I try to add some specific tables to an ERD diagram I get a "Null pointer exception" error. Sometimes (1 of 20) it works, but then it get backs to error. Because of the erratic results I'm thinking if DBeaver isn't trying to get any kind of lock over the tables, and that's the reason I get this unmanaged error sporadically for certain objects, depending on if it could adquire the lock or not. 🤔 

DBeaver doesn't store table structures, so it retrieves them from the connection every time you open an ERD or try to add a table to an ERD. The problem is that if it can't find that table, it disappears from your diagram.

I've tried with different versions, under Windows, Mac, and the Eclipse plugin. All with the same result. I've also changed the timeout properties from the connection, but no luck.

#### Steps to reproduce, if exist:

Drag a DB2 table from the schema directly into a diagram... it works for some, but not all.

#### Include any warning/errors/backtraces from the logs

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.db2.model.DB2TableForeignKey.<init>(DB2TableForeignKey.java:68)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2TableForeignKeyCache.fetchObject(DB2TableForeignKeyCache.java:110)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2TableForeignKeyCache.fetchObject(DB2TableForeignKeyCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:341)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.db2.model.DB2Table.getAssociations(DB2Table.java:266)
	at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllAssociations(DBVUtils.java:321)
	at org.jkiss.dbeaver.erd.model.ERDContentProviderDefault.fillEntityFromObject(ERDContentProviderDefault.java:67)
	at org.jkiss.dbeaver.erd.ui.model.ERDContentProviderDecorated.fillEntityFromObject(ERDContentProviderDecorated.java:56)
	at org.jkiss.dbeaver.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:121)
	at org.jkiss.dbeaver.erd.model.DiagramObjectCollector.addDiagramEntity(DiagramObjectCollector.java:170)
	at org.jkiss.dbeaver.erd.model.DiagramObjectCollector.generateDiagramObjects(DiagramObjectCollector.java:155)
	at org.jkiss.dbeaver.erd.model.DiagramObjectCollector.lambda$1(DiagramObjectCollector.java:241)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.erd.model.DiagramObjectCollector.generateEntityList(DiagramObjectCollector.java:239)
	at org.jkiss.dbeaver.erd.ui.dnd.NodeDropTargetListener$1$1.run(NodeDropTargetListener.java:82)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Complete DBeaver log: [dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7864254/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Hello @pperejonf 

What do you mean by specific tables? Maybe we can fix the issue with these tables because I'm not sure that DBeaver should show an incorrect ERD diagram without not-downloaded tables or connections between tables (foreign keys).

**Comment by pperejonf** [comment]
Hello @LonwoLonwo!  Thanks for your response.

I mean that there are many tables I can add to my ERD inmediately and without any problem, but here are other that I simply can't, getting in 90% of cases a "Null pointer exception". That's why I'm thinking it could be a dymamic issue (table lock or something...). Why does it work sometimes and other not? Why only specific tables from the same scheme?... 

I agree DBeaver shouldn't show tables which fields or relations don't match the existing database. The problem is the opposite, the table exists but DBeaver isn't able to show it in ERD. I can get the fields and data view of the table, but not the ERD 🤷‍♀️

![ERD_Error](https://user-images.githubusercontent.com/91885025/149488317-d4185bf2-b91a-455e-b08b-fe6253b3934c.png)
