### ISSUE TITLE
GUI doesn't support Clickhouse UUID type 

### ISSUE THREAD

**Issue by TomskDiver** [dbeaver/dbeaver#15196]
#### System information: 
- Operating system (distribution) and version  - Windows 10
- DBeaver version - 21.3.2.202112271055 (27 Dec 2021)
- Additional extensions

#### Connection specification:
- Database name and version  - ClickHouse 21.3.19.1
- Driver name - ru.yandex.clickhouse-jdbc clickhouse-jdbc 0.3.2 (revision: 567e14d)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - SSH tunnel

#### Describe the problem you're observing:
GUI does not allow working with data if there is a column with type UUID. SQL query work fine.
On edit, or add new row i get:
![image](https://user-images.githubusercontent.com/2425151/149727517-46d5bb20-9d2d-4bf4-aed2-022f91d4109b.png)
But if run SQL query all be fine.
```
INSERT INTO TestTable
(UUID_Column)
VALUES('47b2db3a-738f-11ec-807a-b4fe6d2cdeda');
```

#### Steps to reproduce, if exist:

Create table:
```
CREATE TABLE TestTable (
	UUID_Column UUID
) ENGINE = MergeTree()
ORDER BY UUID_Column;
```
Try add row in GUI with any UUID, i.e. '47b2db3a-738f-11ec-807a-b4fe6d2cdeda'

#### Include any warning/errors/backtraces from the logs
```
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [47b2db3a-738f-11ec-807a-b4fe6d2cdeda] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.data.ExecuteInsertBatchImpl.bindStatement(ExecuteInsertBatchImpl.java:102)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:169)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.generatePersistActions(ExecuteBatchImpl.java:87)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:773)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:697)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:634)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.execute(ResultSetPersister.java:450)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.applyChanges(ResultSetPersister.java:174)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.generateChangesScript(ResultSetViewer.java:4060)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.SaveScriptDialog.lambda$1(SaveScriptDialog.java:211)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
[.log](https://github.com/dbeaver/dbeaver/files/7879937/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/7879938/dbeaver-debug.log)

**Comment by uslss** [comment]
thanks for the report

**Comment by zhicwu** [comment]
Works for me on DBeaver 22.0.0.202203060510.

**Comment by LonwoLonwo** [comment]
Hello @zhicwu 

It works fine with the latest Clickhouse driver?

**Comment by zhicwu** [comment]
> It works fine with the latest Clickhouse driver?

Yes, it works fine with the new driver(>=0.3.2) but not legacy driver(<=0.3.1-patch).
