### ISSUE TITLE
org.jkiss.dbeaver.model.exec.DBCException: Array type inet doesn't have a component type

### ISSUE THREAD

**Issue by veqryn** [dbeaver/dbeaver#15205]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.1.5.202108160727

#### Connection specification:
- Database name and version: PostgreSQL 14
- Driver name: default PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
`select * mytable` gives this error for a column:
```
org.jkiss.dbeaver.model.exec.DBCException: Array type inet doesn't have a component type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:72)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3434)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4711)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

#### Steps to reproduce, if exist:
Create a column of type `inet[]`

example:
```
CREATE TABLE mytable (
    ip INET NULL
);

alter table mytable alter column ip type inet[] using array[ip];
```

#### Include any warning/errors/backtraces from the logs
Can't read column 'ip' value
  Array type inet doesn't have a component type

**Comment by uslss** [comment]
@veqryn cannot reproduce it against 21.3.2. Could you check if issue is reproducible for you against 21.3.2?

**Comment by veqryn** [comment]
It seems that closing dbeaver and and starting it up again and reconnecting solved the problem

**Comment by ngrhadi** [comment]
I have same problem here, when I open on QGIS, both of data works, with difference geometry
![img](https://snipboard.io/bakxjZ.jpg)
here is full text when I copy from that column 
org.jkiss.dbeaver.model.exec.DBCException: Invalid hex digit: 'P'
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromPGGeometry(PostgreGeometryValueHandler.java:200)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.getValueFromObject(PostgreGeometryValueHandler.java:122)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.fetchColumnValue(PostgreGeometryValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:200)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Invalid hex digit: 'P'
	at org.locationtech.jts.io.WKBReader.hexToInt(WKBReader.java:96)
	at org.locationtech.jts.io.WKBReader.hexToBytes(WKBReader.java:84)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromWKB(PostgreGeometryValueHandler.java:145)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromWKT(PostgreGeometryValueHandler.java:226)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromPGGeometry(PostgreGeometryValueHandler.java:197)
	... 11 more
