### ISSUE TITLE
SQL Script parser can't restore after error with Chinese input

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#15222]
#### System information: 
- Windows 10 Pro
- DBeaver version 21.3.3
- Input method: Microsoft Pinyin (Simplified, China)

#### Describe the problem you're observing:
After parsing error the errors are continuing in infinite loop even when script is closed. 
It breaks all other functionality because of high RAM usage.
 

https://user-images.githubusercontent.com/28875055/150172760-017a18f8-a725-46eb-9fa2-5477f74a7029.mp4

#### Steps to reproduce, if exist:
1. Write something in Chinese in SQL Script editor.

#### Include any warning/errors/backtraces from the logs
```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.get(AbstractDocument.java:967)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.get(SynchronizableDocument.java:130)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.parseQuery(SQLScriptParser.java:189)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.extractScriptQueries(SQLScriptParser.java:714)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.extractScriptQueries(SQLEditorBase.java:717)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.extractQueries(SQLReconcilingStrategy.java:243)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:187)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:84)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)

```

**Comment by DariaMarkaryan** [comment]
No longer reproduced
