### ISSUE TITLE
启动DBeaver时，默认打开的数据库SQL编辑器连接数据库报错

### ISSUE THREAD

**Issue by Long-Tu** [dbeaver/dbeaver#15259]
# 启动DBeaver时，上次关闭打开的数据库SQL编辑器连接数据库报错
## 1、启动时连接数据库报错
![图片](https://user-images.githubusercontent.com/37840939/150732414-de37faac-077e-4312-9095-1166539c6c9f.png)

## 2、第二次连接数据库报错
![图片](https://user-images.githubusercontent.com/37840939/150733252-2e67d0d5-7bdf-4ad1-b574-c53ad37ca6bb.png)

## 3、第二次相同的报错，确认后数据库默认表正常连接
![图片](https://user-images.githubusercontent.com/37840939/150732636-d16b8176-6812-4b3c-a24a-6c3a75a816f0.png)

## 4、.log日志报错
!SESSION 2022-01-24 14:34:35.607 -----------------------------------------------
eclipse.buildId=unknown
java.version=14.0.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-01-24 14:34:38.203
!MESSAGE Unable to retrieve the bundle from the URI: bundleclass://com.dbeaver.ee.runtime.ui/com.dbeaver.ee.runtime.internal.ui.LicenseStartupAddon

!ENTRY org.eclipse.ui 4 4 2022-01-24 14:34:39.883
!MESSAGE Plug-in 'org.eclipse.team.ui' contributed an invalid Menu Extension (Path: 'project' is invalid): org.eclipse.team.ui.ConfigureProject

!ENTRY org.eclipse.ui 4 4 2022-01-24 14:34:39.884
!MESSAGE Plug-in 'org.eclipse.team.ui' contributed an invalid Menu Extension (Path: 'project' is invalid): org.eclipse.team.ui.ApplyPatchAction

!ENTRY org.eclipse.ui 4 4 2022-01-24 14:34:39.900
!MESSAGE Plug-in 'org.eclipse.ui.ide' contributed an invalid Menu Extension (Path: 'navigate/goTo' is invalid): goToResource

!ENTRY org.jkiss.dbeaver.model 4 0 2022-01-24 14:34:44.027
!MESSAGE Empty command specified
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-01-24 14:34:44.027
!MESSAGE Empty command specified
!STACK 0
org.jkiss.dbeaver.DBException: Empty command specified
	at org.jkiss.dbeaver.model.runtime.DBRProcessDescriptor.execute(DBRProcessDescriptor.java:109)
	at org.jkiss.dbeaver.core.DesktopUI.executeProcess(DesktopUI.java:382)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.processEvents(DataSourceDescriptor.java:980)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:777)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-01-24 14:34:46.072
!MESSAGE Empty command specified
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-01-24 14:34:46.072
!MESSAGE Empty command specified
!STACK 0
org.jkiss.dbeaver.DBException: Empty command specified
	at org.jkiss.dbeaver.model.runtime.DBRProcessDescriptor.execute(DBRProcessDescriptor.java:109)
	at org.jkiss.dbeaver.core.DesktopUI.executeProcess(DesktopUI.java:382)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.processEvents(DataSourceDescriptor.java:980)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:917)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
@Long-Tu please, provide issue description in English
thanks in advance

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it with additional info.
