### ISSUE TITLE
Cannot perform SSPI Authentication with DBeaver due to class com.sun.jna.Pointer constraints

### ISSUE THREAD

**Issue by srnsomu** [dbeaver/dbeaver#15289]
#### System information: 
- Operating system (distribution) and version: Windows 10 Enterprise
- DBeaver version: Version 21.3.3.202201221033
- Additional extensions

#### Connection specification:
- Database name and version: Postgres Version 14
- Driver name: 
org.postgressql:  Version 42.2..20
waffle-jna: Version 3.1.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When I add the waffle-jna artifact, it displays the below error

loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @5522d8f wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @5a989f45. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5a989f45, parent loader 'platform')

I noticed a similar issue ( https://github.com/dbeaver/dbeaver/issues/8247). The fix suggested was to check the "Ignore transient dependencies". While I enabled the option, it still gives out the error.

#### Steps to reproduce, if exist:

DBeaver -> Edit Driver Settings -> Libraries -> Add Artifact -> Add waffle-jna artifact with
Artifact Id: waffle-jna
group id: com.github.waffle
Version: 3.1.1
Fallback Version: RELEASE

Check Ignore transient dependencies. Click Okay and Test Connection

#### Include any warning/errors/backtraces from the logs
2022-01-25 12:24:56.695 - Connect with 'CIM Collector Postgres' (postgres-jdbc-17cb875eddc-1d48f9023bb465bc)
2022-01-25 12:24:56.743 - Execution context opened (CIM Collector Postgres; Main <postgres>; 2)
2022-01-25 12:24:56.743 - Initiate connection to PostgreSQL database [postgres@localhost] for Main <postgres>
2022-01-25 12:24:56.809 - Execution context opened (CIM Collector Postgres; Metadata <postgres>; 3)
2022-01-25 12:24:56.809 - Initiate connection to PostgreSQL database [postgres@localhost] for Metadata <postgres>
2022-01-25 12:24:56.882 - Connected (postgres-jdbc-17cb875eddc-1d48f9023bb465bc, PostgreSQL JDBC Driver [42.2.20])
2022-01-25 12:25:02.800 - Execution context closed (CIM Collector Postgres, 2)
2022-01-25 12:25:02.851 - Execution context closed (CIM Collector Postgres, 3)
2022-01-25 12:25:02.851 - Disconnected (postgres-jdbc-17cb875eddc-1d48f9023bb465bc)
2022-01-25 12:25:03.809 - Error evaluating expression 'object.dataSource.serverType.supportsRoles()' on node 'CIM Collector Postgres': 1:1 undefined variable object.dataSource.serverType
2022-01-25 12:25:03.809 - org.apache.commons.jexl3.JexlException$Variable: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@1:1 undefined variable object.dataSource.serverType
org.apache.commons.jexl3.JexlException$Variable: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@1:1 undefined variable object.dataSource.serverType
	at org.jkiss.dbeaver.model.navigator.meta.DBXTreeNode.isVisible(DBXTreeNode.java:248)
	at org.jkiss.dbeaver.model.navigator.meta.DBXTreeFolder.isVisible(DBXTreeFolder.java:195)
	at org.jkiss.dbeaver.model.navigator.meta.DBXTreeNode.getChildren(DBXTreeNode.java:225)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.addDatabaseNodeCreateItems(NavigatorHandlerObjectCreateNew.java:342)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.fillCreateMenuItems(NavigatorHandlerObjectCreateNew.java:233)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.updateElement(NavigatorHandlerObjectCreateNew.java:154)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:434)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:123)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:45)
	at org.eclipse.ui.internal.commands.CommandService.registerElement(CommandService.java:313)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElement(SlaveCommandService.java:239)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForCommand(SlaveCommandService.java:231)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForUpdate(SlaveCommandService.java:285)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.postMenuFill(HandledContributionItem.java:198)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.fill(AbstractContributionItem.java:266)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:729)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:806)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:673)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.scheduleManagerUpdate(MenuManagerRenderer.java:1227)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processContents(MenuManagerRenderer.java:655)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.subscribeTopicChildAdded(MenuManagerRenderer.java:325)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4779)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:64)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.emf.ecore.util.EcoreEList.dispatchNotification(EcoreEList.java:249)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.addUnique(NotifyingListImpl.java:356)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:340)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.mergeIntoModel(ContributionRecord.java:253)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processAddition(MenuManagerRenderer.java:551)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.generateContributions(MenuManagerRenderer.java:531)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processContributions(MenuManagerRenderer.java:499)
	at org.eclipse.ui.internal.PopupMenuExtender.addMenuContributions(PopupMenuExtender.java:380)
	at org.eclipse.ui.internal.PopupMenuExtender.menuAboutToShow(PopupMenuExtender.java:355)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5150)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4782)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5002)
	at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:237)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:4101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:268)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by Matvey16** [comment]
Thank you for the report, it should be fixed in #15286

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue still persists - feel free to reopen it
