### ISSUE TITLE
Dbeaver Can't Open and Shows Error An error has occured

### ISSUE THREAD

**Issue by arif98741** [dbeaver/dbeaver#15290]
I am using Dbeaver latest version. Yesterday and previously I used it smoothly without any issues. But today I can't open Dbeaver software. I checked the metadata log file. Below is the exception. I previously connected at 5 servers with ssh and local server also. 
I am using windows 10. 

```
!ENTRY org.eclipse.ui.win32.nls 2 0 2022-01-26 01:01:43.355
!MESSAGE Could not resolve module: org.eclipse.ui.win32.nls [357]
  Unresolved requirement: Fragment-Host: org.eclipse.ui.win32
  Unresolved requirement: Fragment-Host: org.eclipse.ui.win32


!ENTRY org.eclipse.core.filesystem.win32.x86_64.nls 2 0 2022-01-26 01:01:43.363
!MESSAGE Could not resolve module: org.eclipse.core.filesystem.win32.x86_64.nls [347]
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64


!ENTRY org.eclipse.equinox.security.win32.x86_64.nls 2 0 2022-01-26 01:01:43.364
!MESSAGE Could not resolve module: org.eclipse.equinox.security.win32.x86_64.nls [299]
  Unresolved requirement: Fragment-Host: org.eclipse.equinox.security.win32.x86_64
  Unresolved requirement: Fragment-Host: org.eclipse.equinox.security.win32.x86_64


!ENTRY org.eclipse.osgi.compatibility.state.nls 2 0 2022-01-26 01:01:43.365
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nls [390]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi 4 0 2022-01-26 01:01:43.372
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Error initializing desktop platform
	at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:109)
	at org.jkiss.dbeaver.core.DesktopPlatform.getInstance(DesktopPlatform.java:85)
	at org.jkiss.dbeaver.core.DesktopAdapterFactory.getAdapter(DesktopAdapterFactory.java:33)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$13(AdapterManager.java:302)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:743)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:718)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:733)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.initDebugWriter(DBeaverApplication.java:631)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
	at org.jkiss.dbeaver.core.DesktopPlatform.initialize(DesktopPlatform.java:155)
	at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:105)
	... 34 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.core.resources (46).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:384)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:471)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:403)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.core.resources.ResourcesPlugin.start() of bundle org.eclipse.core.resources.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:828)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 44 more
Caused by: org.eclipse.core.internal.resources.ResourceException: Incompatible file format. Workspace was saved with an incompatible version: 0.
	at org.eclipse.core.internal.resources.WorkspaceTreeReader.getReader(WorkspaceTreeReader.java:62)
	at org.eclipse.core.internal.resources.WorkspaceTreeReader.getReader(WorkspaceTreeReader.java:70)
	at org.eclipse.core.internal.resources.SaveManager.restoreTree(SaveManager.java:1038)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:708)
	at org.eclipse.core.internal.resources.SaveManager.startup(SaveManager.java:1555)
	at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2480)
	at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2231)
	at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:475)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
	... 51 more
Caused by: java.lang.Exception: Incompatible file format. Workspace was saved with an incompatible version: 0.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	... 62 more

```

**Comment by Matvey16** [comment]
@arif98741 Hello, how did you install Dbeaver?

**Comment by arif98741** [comment]
I downloaded Dbeaver from official site and run the exe file. That's all

**Comment by Matvey16** [comment]
@arif98741 It looks like something happened with your workspace. Please, try to copy a backup of your workspace in `%APPDATA%/DBeaverData` into another directory and then delete it from AppData. Will Dbeaver launch if you don't have a previously saved workspace?

**Comment by arif98741** [comment]
> 

thanks I will try to follow it

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue still persists - feel free to reopen it

**Comment by arif98741** [comment]
> There have been no updates for a long time. If the issue still persists - feel free to reopen it

its working after I reinstalling in my pc. I didn't get any clue why it works :D

**Comment by henkterharmsel** [comment]
I know this topic is closed, but I had the same problem. For me, the solution was to delete the %APPDATA%/Roaming/DBeaverData/workspace6/.metadata/.plugins folder. (Or I actually renamed it) The issue seemed to be in one of the plugins. On startup, it will redownload the plugins.

**Comment by azier33** [comment]
great!!

**Comment by davidlam-at-home** [comment]
@pkmelee337 life saver!

**Comment by arcesoftware** [comment]
> I know this topic is closed, but I had the same problem. For me, the solution was to delete the %APPDATA%/Roaming/DBeaverData/workspace6/.metadata/.plugins folder. (Or I actually renamed it) The issue seemed to be in one of the plugins. On startup, it will redownload the plugins.

This solution resolved an issue in a huge production environment affecting 1700 users.

I can only say THANK YOU!!!

**Comment by 7PH** [comment]
> %APPDATA%/Roaming/DBeaverData/workspace6/.metadata/.plugins

Just a note that on W11 for me, it was
`%APPDATA%/DBeaverData/workspace6/.metadata/.plugins`
