### ISSUE TITLE
Data transfer task ignores the skipped columns after saving it

### ISSUE THREAD

**Issue by Matwolf08** [dbeaver/dbeaver#15365]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 19044.1503
- DBeaver version 21.3.3.202201221033

#### Describe the problem you're observing:

When I create a data export task and set to "skip" some tables and some columns of some other tables, only the skipped tables are preserved when saving. Running the saved task (or even editing it) remaps with "existing" or "create" the previusly skipped columns.

#### Steps to reproduce, if exist:

Create a new data transfer task. Set to skip some columns. Close the task ad reopen it in edit mode. You'll see that no more skipped columns are present.

#### Include any warning/errors/backtraces from the logs
No error while opening the task in edit mode after save.

Please note that the task.json file within the %APPDATA% folder of DBeaver still contains the correct mapping types for the skipped columns.

**Comment by uslss** [comment]
thanks for the report

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.0

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.1

**Comment by uslss** [comment]
1. NPE appears if there was export of more then one table, and table was skipped
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Mar 14 11:29:46 MSK 2022
NullPointerException

java.lang.NullPointerException
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:277)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:196)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:115)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:131)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.runDataTransferJobs(DTTaskHandlerTransfer.java:146)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeWithSettings(DTTaskHandlerTransfer.java:83)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:71)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:126)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:94)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
2. Table is skipped in new task in case there was created task with more than one table and this table was skipped. Its mapping cannot be changed to create.
![image](https://user-images.githubusercontent.com/31996417/158134189-b4ae788b-3deb-432b-9a9e-27e154887fee.png)

**Comment by LonwoLonwo** [comment]
NPE fixed.

**Comment by uslss** [comment]
verified
