### ISSUE TITLE
Cannot use pgdump in Dbeaver CE (from Windows Store)

### ISSUE THREAD

**Issue by Sa1Gur** [dbeaver/dbeaver#15361]
#### System information: 
- Windows 11 Enterprise 21H2 build 22000.469
- DBeaver version 21.3.3.202201221029

#### Connection specification:
- PostgreSQL 13.4 (Debian 13.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- PostgreSQL JDBC Driver 42.2.20
- no 

#### Describe the problem you're observing:
I cannot create a backup in Windows Store version of the app. I guess the problem is in the wrong path C:\Users\Guriy Samarin\AppData\Roaming\DBeaverData. This path was created in Win32 version, but non existing in Windows Store case

#### Steps to reproduce, if exist:
Tools -> Backup -> choose schema -> Next -> Start
#### Include any warning/errors/backtraces from the logs
Error executing process
  Process failed (exit code = -1073741515). See error log.
C:\Users\Guriy Samarin\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\13\pg_dump.exe --verbose --host=172.17.127.101 --port=5432 --username=platform --format=c --file C:\Users\Guriy Samarin\Desktop\dump-mdp02-202202021016 -n "dbo" mdp02
Task 'PostgreSQL dump' started at Wed Feb 02 10:16:30 MSK 2022
Task 'PostgreSQL dump' finished at Wed Feb 02 10:16:30 MSK 2022
2022-02-02 10:16:30.851 - IO error: Process failed (exit code = -1073741515). See error log.
2022-02-02 10:16:30.852 - java.io.IOException: Process failed (exit code = -1073741515). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:233)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:213)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:273)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:78)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by uslss** [comment]
thanks for the report

**Comment by Sa1Gur** [comment]
You are welcome. Thank you for the ultimate tool. It truly rocks!

**Comment by Destrolaric** [comment]
Temporary workaround: setup your workspace outside of appdata, windows store virtualizes that folder, preventing any binary launch from it.

**Comment by Matvey16** [comment]
Verified
