### ISSUE TITLE
General SalesForce connectivity

### ISSUE THREAD

**Issue by alexsanabria** [dbeaver/dbeaver#15381]
I'm trying to connect to salesForce by the new driver salesforce CDP, but I got this error: "the requested scope is invalid, unknown, or malformed"
My data is:
 JDBC URL = jdbc:queryService-jdbc:https://login.salesforce.com
Database/Schema = https://login.salesforce.com
User = MyUser
Password = MyPassword

Thaks for all

**Comment by Skydiveroid** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by stephen-philippou-cengage** [comment]
@Skydiveroid Hey sorry to jump in but I'm getting the exact same issue. Here's my log file if that helps. The last entry is an example of this issue
[salesforceJDBCissue.log](https://github.com/dbeaver/dbeaver/files/8091710/salesforceJDBCissue.log).

**Comment by alexsanabria** [comment]
Hi @Skydiveroid 

This is my log for the issue.

Thank you for your answer and your help

################################ LOG ############################
!ENTRY org.jkiss.dbeaver.model 4 0 2022-02-19 03:30:46.654
!MESSAGE the requested scope is invalid, unknown, or malformed
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-02-19 03:30:46.654
!MESSAGE the requested scope is invalid, unknown, or malformed
!STACK 0
com.salesforce.cdp.queryservice.util.TokenException: the requested scope is invalid, unknown, or malformed
	at com.salesforce.cdp.queryservice.util.TokenHelper.exchangeToken(TokenHelper.java:179)
	at com.salesforce.cdp.queryservice.util.TokenHelper.retrieveTokenWithPasswordGrant(TokenHelper.java:127)
	at com.salesforce.cdp.queryservice.util.TokenHelper.getToken(TokenHelper.java:72)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.lambda$getTokenWithTenantUrl$2(QueryExecutor.java:182)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getTokenWithTenantUrl(QueryExecutor.java:181)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.executeQuery(QueryExecutor.java:92)
	at com.salesforce.cdp.queryservice.core.QueryServiceAbstractStatement.executeQuery(QueryServiceAbstractStatement.java:72)
	at com.salesforce.cdp.queryservice.core.QueryServicePreparedStatement.execute(QueryServicePreparedStatement.java:158)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.isValid(QueryServiceConnection.java:344)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.<init>(QueryServiceConnection.java:59)
	at com.salesforce.cdp.queryservice.QueryServiceDriver.connect(QueryServiceDriver.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:79)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
##############################################################################

**Comment by topkamal** [comment]
I'm getting the same error too

**Comment by bedub63** [comment]
It seems that there is a difference between Salesforce and Salesforce CDP. Promoting “Salesforce” connection drivers is misleading.

**Comment by kevinquillen** [comment]
Getting this same error.

**Comment by flambchap** [comment]
It seems like the SalesForce CDP driver doesn't work with general SalesForce instances.

**Comment by flambchap** [comment]
We've asked folks from SalesForce for assistance. Stay tuned.

**Comment by kevinquillen** [comment]
I don't see a way to add JWT/Oauth/SSL cert into the auth, is it possible this is why it is failing? My app is setup to require this.

**Comment by kevinquillen** [comment]
Update: I was able to get connected using Jetbrains DataGrip and using this driver: http://reliersoft.com/download/salesforce-jdbc-driver/

The only difference with this driver is that the URL is sforce:// instead of https:// when setting up the connection.

So it must be a bug with this particular driver for dbeaver.

Edit: this driver above works in any JetBrains IDE (PHPStorm, etc, any with the Database Tools https://www.jetbrains.com/help/idea/connecting-to-a-database.html), not just DataGrip.

![Screenshot from 2022-03-26 10-44-11](https://user-images.githubusercontent.com/362176/160253892-441e06ba-eb07-4c5d-95c7-6dca59d0ac22.png)

Hopefully its only a small bug because I prefer to be in dbeaver!

**Comment by flambchap** [comment]
@kevinquillen It is not a bug. We made this particular driver for use with SalesForce CDP specifically. We need a new driver for general SalesForce instances.

Meanwhile, you can create a custom driver via [the Driver Manager](https://github.com/dbeaver/dbeaver/wiki/Database-drivers).

**Comment by LonwoLonwo** [comment]
Unfortunately, I can find an open-source JDBC driver for Salesforce for now. And yes, I can\t connect to my Salesforce database with the Salesforce CDP driver.

**Comment by sou-gui-monteiro** [comment]
Any news here? I'm facing the same issue.

**Comment by Griffo-Hub** [comment]
another one having this issue...owuld love tok now if anyone has been able to resolve this. Also - the link for reliersoft is broken. The website appears to be having issues

**Comment by LonwoLonwo** [comment]
And again - we can't add a driver without a driver. Still waiting for the open-source driver.

**Comment by javidiazllobet** [comment]
same problem here, not working

**Comment by arhayka** [comment]
We have supported Salesforce in our commercial products since version 23.2. 
You can try a free two-week trial version: https://dbeaver.com/trial/

**Comment by karancan** [comment]
Hi team - I am trying to understand the final resolution here? I think this may be related to the issue I am experiencing but I am not certain...

https://github.com/orgs/dbeaver/discussions/21505

**Comment by flambchap** [comment]
@karancan We added support for Salesforce (non-CDP) in our commercial versions. You can try a free two-week trial version: https://dbeaver.com/trial/

**Comment by karancan** [comment]
@n5a5 - I was able to get it working using the trial version. Is it possible to get just this specific driver so we can use it with our own tools (i.e. outside Dbeaver)?

**Comment by kevinquillen** [comment]
I have followed every guide for the Salesforce CDP connector for DBeaver as well as the one here for this driver https://github.com/forcedotcom/Salesforce-CDP-jdbc 

In neither case will Dbeaver connect to Salesforce even when other apps can via OAuth. It only errors with "end user denied authorization" - despite being able to authenticate the same way from other apps with the same credentials and certificate. I can't afford to pay a few hundred dollars to just occassionally use SOQL and validate objects are updated (the Salesforce site admin is just awful).

**Comment by serge-rider** [comment]
@karancan 
> I was able to get it working using the trial version. Is it possible to get just this specific driver so we can use it with our own tools (i.e. outside Dbeaver)?

We do not sell JDBC drivers separately from DBeaver (yet). We plan to start doing it next year.

**Comment by serge-rider** [comment]
@kevinquillen
> In neither case will Dbeaver connect to Salesforce even when other apps can via OAuth.

We plan to add OAuth authentication for Salesforce driver in version 23.3

**Comment by javidiazllobet** [comment]
Yeah, IT DOESN'T WORK.
I spend a lot of hours and there is no way this driver work. :(

**Comment by serge-rider** [comment]
@javidiazllobet Could you write a bit more details?
What exactly doesn't work, maybe there are some error messages?

**Comment by javidiazllobet** [comment]
Hi @serge-rider 
The error message I always get is "end-user denied authorization":
![image](https://github.com/dbeaver/dbeaver/assets/23526673/ce25be21-1cb0-4671-8a22-c980a6dcc634)

I followed all docs and I ensured that the user was properly working and I even contacted with Salesforce support but no way, we couldn't find the source of the error,

Aby help will be appreciated.

**Comment by serge-rider** [comment]
@javidiazllobet It is Salesforce CDP driver. It requires different authentication.
The one you are looking for is Salesforce driver, it is included only in [PRO products](https://dbeaver.com)

**Comment by Yaswi** [comment]
Hi, I'm using the dbeaver Ultimate trail version. I'm trying to access the salesforce database.
I'm getting the following error:
<img width="636" alt="Screenshot 2024-10-09 at 7 14 07 PM" src="https://github.com/user-attachments/assets/f4855850-b45f-4531-afb8-33d81d156229">

Any help will be appreciated.

**Comment by javidiazllobet** [comment]
hi

it simply doesn't work in the free version.
You must pay if you want access to Salesforce.



--

Javi Diaz

________________________________
De: 19121A0534 ***@***.***>
Enviado: miércoles, 9 de octubre de 2024 15:45
Para: dbeaver/dbeaver ***@***.***>
Cc: Javi Diaz ***@***.***>; Mention ***@***.***>
Asunto: Re: [dbeaver/dbeaver] General SalesForce connectivity (Issue #15381)


*Caution: This email comes from a source external to MSF. Please, verify the sender and avoid opening unexpected URLs or files, as they may not be secure.
*Atención: Este correo proviene de una fuente externa a MSF. Por favor, comprueba el emisor y evita abrir URLs o archivos no esperados, podrían no ser seguros.
*Attention: Cet email provient d’une source externe à MSF. Veuillez vérifier l’expéditeur et éviter d’ouvrir des URL ou des fichiers inattendus, car ils pourraient contenir du contenu malveillant.


Hi, I'm using the dbeaver Ultimate trail version. I'm trying to access the salesforce database.
I'm getting the following error:
Screenshot.2024-10-09.at.7.14.07.PM.png (view on web)<https://github.com/user-attachments/assets/f4855850-b45f-4531-afb8-33d81d156229>

Any help will be appreciated.
