### ISSUE TITLE
Invalid thread access is thrown if you click Cancel in save result dialog

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15403]
#### System information: 
- Win10
- DBeaver CE 21.3.4

#### Describe the problem you're observing:
Error 'Invalid thread access' is thrown when you press Cancel in the dialog that asks if you want to save changes in the data grid. Actually, it's not clear for what purpose button cancel is here

#### Steps to reproduce, if exist:
1. In the data grid enter invalid data (set to a null value that is not allowed to be null, for example)
2. start auto-refresh (it doesn't matter if the Stop on error checkbox is on or off)
3. In the appeared dialog click on the Cancel button
![image](https://user-images.githubusercontent.com/43252954/152782976-5f26b00e-5a41-4e77-a72d-7be8ba76a8fb.png)

As the result, a terrible incomprehensible message is thrown with an SWT error
![image](https://user-images.githubusercontent.com/43252954/152783314-903198b5-2df0-42b8-8cb8-c0a4e1f7e20d.png)

#### Include any warning/errors/backtraces from the logs
```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:445)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:365)
	at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3671)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateToolbar(ResultSetViewer.java:1555)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateEditControls(ResultSetViewer.java:1538)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePanelsContent(ResultSetViewer.java:3446)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.checkForChanges(ResultSetViewer.java:3564)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.refreshData(ResultSetViewer.java:3660)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$1(ResultSetViewer.java:264)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshJob.run(AutoRefreshJob.java:42)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
not reproducible against 21.3.5
