### ISSUE TITLE
Data editor fails to display composite type columns that include a PostGIS geometry field

### ISSUE THREAD

**Issue by ivanlonel** [dbeaver/dbeaver#15426]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro 21H1
- DBeaver version: 21.3.0
- Additional extensions: Office support, git support, SSHJ, Debug and SVG

#### Connection specification:
- Database name and version: Postgresql 12.8
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When a Postgres composite type includes a subfield of type `geometry` (PostGIS), the data editor displays all subfields with the wrong value (a text representation of the entire record in parentheses) in a magenta background.

#### Steps to reproduce, if exist:

1. Create testing set:
```pgsql
CREATE TABLE test0 (
	id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	geom geometry
);

INSERT INTO test0 (geom)
	SELECT st_point((random() - 0.5) * 360, (random() - 0.5) * 180) 
	FROM generate_series(1, 1000) AS n;

CREATE TABLE test1 (
	id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	composite test0
);

INSERT INTO test1 (composite)
	SELECT (id, geom)::test0
	FROM test0;
```

2. Open table `test1` in data editor. You should see something like this:
![image](https://user-images.githubusercontent.com/15915901/153035296-15c787cc-33b4-48d3-9c6a-0908c7a5eb6b.png)

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 2 0 2022-02-08 13:24:47.697
!MESSAGE Error resolving attribute 'composite' values
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2022-02-08 13:24:47.697
!MESSAGE Error converting string to composite type
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2022-02-08 13:24:47.697
!MESSAGE Expected word but found End-of-Stream (line 1)
!STACK 0
org.locationtech.jts.io.ParseException: Expected word but found End-of-Stream (line 1)
	at org.locationtech.jts.io.WKTReader.parseErrorWithLine(WKTReader.java:736)
	at org.locationtech.jts.io.WKTReader.parseErrorExpected(WKTReader.java:724)
	at org.locationtech.jts.io.WKTReader.getNextWord(WKTReader.java:705)
	at org.locationtech.jts.io.WKTReader.lookAheadWord(WKTReader.java:645)
	at org.locationtech.jts.io.WKTReader.getNextOrdinateFlags(WKTReader.java:618)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:795)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:788)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:231)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:212)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromWKT(PostgreGeometryValueHandler.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.getValueFromObject(PostgreGeometryValueHandler.java:120)
	at org.jkiss.dbeaver.ext.postgresql.PostgreValueParser.convertStringToSimpleValue(PostgreValueParser.java:157)
	at org.jkiss.dbeaver.ext.postgresql.PostgreValueParser.convertStringToValue(PostgreValueParser.java:87)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:141)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:104)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:768)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:217)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
It looks like that geometries are stored in WKB format but as hex. This behavior makes sense for composites.

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by uslss** [comment]
verified
