### ISSUE TITLE
Failed to connect with AD-MFA in SQL Server on Azure

### ISSUE THREAD

**Issue by joelrosa21** [dbeaver/dbeaver#15446]
Failed to connect with AD-MFA in SQL Server on Azure with error:

`The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Failed to validate the server name in a certificate during Secure Sockets Layer (SSL) initialization.".`

#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 21.3.2

#### Connection specification:
- Database name and version: Microsoft SQL Azure (RTM) - 12.0.2000.8
- Driver name: Microsoft JDBC Driver for SQL Server 9.2.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

**Comment by ShadelessFox** [comment]
Hello @joelrosa21,

Have you tried enabling this option? Please see the attached image.

![image](https://user-images.githubusercontent.com/35821147/154268360-4de60152-6ba1-4de5-a228-7598686ce3af.png)

**Comment by joelrosa21** [comment]
Hello @ShadelessFox !

It was not enabled, but after enabling, this error occurs:

`Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.`

<img width="226" alt="erro_db_mfa" src="https://user-images.githubusercontent.com/88491194/154317651-3206fee1-954c-40b6-8354-f19c763d9275.PNG">

**Comment by ShadelessFox** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by joelrosa21** [comment]
.log:

```!ENTRY org.jkiss.dbeaver.model 4 0 2022-02-16 14:00:21.112
!MESSAGE Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-02-16 14:00:21.112
!MESSAGE Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4629)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4497)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4460)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5332)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4006)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:91)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:73)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-02-16 14:03:45.344
!MESSAGE Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-02-16 14:03:45.344
!MESSAGE Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryInteractive authentication.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4629)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4497)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4460)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5332)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4006)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:91)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:73)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)```

**Comment by archenroot** [comment]
any progress on this, I am also stuck, but for sure I cannot find on my local system anywhere library called msal4j... so it seems dbeaver doesn't download it on its own... I will try to add it to classpath...

**Comment by archenroot** [comment]
so I added to the driver of sql server another jar like this:
![image](https://user-images.githubusercontent.com/553512/159869218-7449399f-f87f-4711-8216-c87b3c572cb8.png)

now getting other error:
![image](https://user-images.githubusercontent.com/553512/159869312-79ca0981-3a48-4752-803f-b3509d81a80c.png)

**Comment by ktr** [comment]
Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:

`
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
    <version>1.11.3</version>
</dependency>
`

Hope this helps!

**Comment by joelrosa21** [comment]
@ktr It worked! thank you so much!!

**Comment by amagee-willow** [comment]
> Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:
> 
> `<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> `
> 
> Hope this helps!

This also worked for me, but note you also need to click the "Download/Update" button after adding the artifact.

**Comment by DenisUes** [comment]
> Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:
> 
> `<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> `
> 
> Hope this helps!

Thanks a lot!
I was looking for a solution in hundreds of threads and sites.
That's great and powerful declaration. It was work for me, even in a portable version of DBeaver!
Regards

**Comment by ShivnarenSrinivasan** [comment]
The guidance above worked--thank you so much.

However, can we add this dependency to the predefined list? I'm sure I (and others) may forget if we have a new installation of DBeaver

**Comment by sambarza** [comment]
> > Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:
> > `<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> `
> > Hope this helps!
> 
> This also worked for me, but note you also need to click the "Download/Update" button after adding the artifact.

Today I got an error using version 1.11.3 and the last version 1.15.0, version 1.14.3 it's good:
`<dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.14.3</version> </dependency> `

**Comment by webartoli** [comment]
> Today I got an error using version 1.11.3 and the last version 1.15.0, version 1.14.3 it's good:

Today latest version is good:

```xml
<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> 
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>msal4j</artifactId>
  <version>1.17.3</version>
</dependency> 
```

**Comment by adaptiv-rsarangan** [comment]
1.19.1 as of 27 Feb 2025 is also good.

` 
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>msal4j</artifactId>
  <version>1.17.3</version>
</dependency>`

**Comment by Loetfi** [comment]
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
    <version>1.21.0</version>
</dependency>

**Comment by Loetfi** [comment]
`
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>msal4j</artifactId>
    <version>1.21.0</version>
</dependency>`

**Comment by davideprevosto** [comment]
1.23.0 is also good
```
<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.23.0</version> </dependency>
```
