### ISSUE TITLE
Bug: Google cloud sql connector does not work after last update

### ISSUE THREAD

**Issue by e-compagno** [dbeaver/dbeaver#15526]
#### System information: 
- Operating system (distribution) and version: MacOS Catalina 10.15.7 
- DBeaver version: 21.3.4

#### Connection specification:
- Database name and version: PostgreSQL 13 
- Driver name: Google Cloud SQL - PostgreSQL

#### Describe the problem you're observing:
Since the driver update I cannot connect anymore to the sql database. The error is 

```
Something unusual has occurred to cause the driver to fail. Please report this exception.
  com/google/cloud/sql/core/CoreSocketFactory
  com/google/cloud/sql/core/CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
    com.google.cloud.sql.core.CoreSocketFactory
```
These are the drivers installed: 

<img width="675" alt="Screenshot 2022-02-17 at 10 35 27" src="https://user-images.githubusercontent.com/49021750/154458340-e44ae06b-5a78-4cef-b28e-e596a5ec10e0.png">

#### Steps to reproduce, if exist:
Just install last version of DBeaver and try to connect. This was working before the update of the driver libraries.

#### Include any warning/errors/backtraces from the logs
<img width="919" alt="Screenshot 2022-02-17 at 10 38 16" src="https://user-images.githubusercontent.com/49021750/154458832-c277085f-d2a8-4a39-a278-2977c66b074f.png">

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by e-compagno** [comment]
```
2022-02-17 10:34:27.803 - Connect with 'jdbc:postgresql:///postgres?cloudSqlInstance=<MYINSTANCE>' (postgres-gcloud-jdbc-17f073f5e29-57e722d893e5ffa8)
2022-02-17 10:34:27.804 - Execution context opened (jdbc:postgresql:///postgres?cloudSqlInstance=<MYINSTANCE>; Main <postgres>; 10)
2022-02-17 10:34:27.804 - Initiate connection to Google Cloud SQL PostgreSQL database [postgres@<MYINSTANCE>] for Main <postgres>
2022-02-17 10:34:27.821 - Connection failed (postgres-gcloud-jdbc-17f073f5e29-57e722d893e5ffa8)
org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:457)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:222)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:115)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:240)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:420)
	at org.postgresql.Driver.connect(Driver.java:271)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/sql/core/CoreSocketFactory
	at com.google.cloud.sql.postgres.SocketFactory.<clinit>(SocketFactory.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:46)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:182)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.core.CoreSocketFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
2022-02-17 10:34:27.822 - org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:457)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:222)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:115)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:240)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:904)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:420)
	at org.postgresql.Driver.connect(Driver.java:271)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/sql/core/CoreSocketFactory
	at com.google.cloud.sql.postgres.SocketFactory.<clinit>(SocketFactory.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:46)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:182)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.core.CoreSocketFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
2022-02-17 10:34:27.870 - com.google.cloud.sql.core.CoreSocketFactory
java.lang.ClassNotFoundException: com.google.cloud.sql.core.CoreSocketFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.google.cloud.sql.postgres.SocketFactory.<clinit>(SocketFactory.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:46)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:182)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)
> Start Log View [org.eclipse.ui.views.log 1.3.100.v20210927-1100]
```

**Comment by LonwoLonwo** [comment]
Hello @e-compagno 

Thanks for the bug report. We will fix it here soon: https://github.com/dbeaver/dbeaver/issues/15459

**Comment by e-compagno** [comment]
> Hello @e-compagno
> 
> Thanks for the bug report. We will fix it here soon: #15459

I've had a look at the issue in that link. Unfortunately, it is not clear how to solve the `Maven artifact 'maven:/com.google.cloud.sql:jdbc-socket-factory-core:RELEASE' not found` issue. Could you please write more information about it?

**Comment by e-compagno** [comment]
I have finally solved it. First up reset DBeaver via (to avoid loosing all connections export the project first)
```
rm -rf ~/Library/DBeaverData
brew reinstall --cask dbeaver-community
```
1. Install manually the dependencies for the cloud sql driver as 
```
<dependency>
    <groupId>com.google.cloud.sql</groupId>
    <artifactId>postgres-socket-factory</artifactId>
    <version>1.0.15</version>
</dependency>
```
2. Install 
```
<dependency>
    <groupId>com.google.cloud.sql</groupId>
    <artifactId>jdbc-socket-factory-core</artifactId>
    <version>1.4.3</version>
</dependency>
```

3. Modify the file (in MacOS)
```
~/Library/DBeaverData/drivers/maven/maven-central/com.google.cloud.sql/postgres-socket-factory-1.4.3.pom
```
replacing `${project.parent.version}` with `1.4.3`.  

4. Finally force the download of all libraries in edit driver settings -> download/Update

**Comment by LonwoLonwo** [comment]
Thanks for the feedback @e-compagno
