### ISSUE TITLE
[PostgreSQL] Filter doesn't work in special case.

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#15626]
DBeaver 21.3.5, DBeaver 21.3.3

Data filtering doesn't work correctly in SQL Editor for columns with custom quoted data types for PostgreSQL.

Steps:

1. Create data type with quoted name. Like

```sql
CREATE TYPE "Test_enum" AS ENUM (
	'TEST1',
	'TEST2',
	'TEST3'); 
```

2. Create a table with columns with the created earlier data type.

```sql
CREATE TABLE test_table_enum (
	f1_enum "Test_enum" NULL,
	f2_text text NULL
);
```

3. Insert some data into the table.
4. Open the table from SQL Editor
5. Try to use a filter on any data on column `f1_enum`

![2022-02-25 09_18_09-Filter by 'f1_enum'](https://user-images.githubusercontent.com/45152336/155665411-a54a4d45-b73c-4938-923b-23ce65f08d3f.png)

Expected result: table data filtered
Actual result: an error appears

```
org.postgresql.util.PSQLException: Error: the WHERE design argument should have a BOOLEAN type, not "test_enum"
  Position: 48
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
```

And this is the query from the query manager:

`SELECT x.* FROM public.test_table_enum x WHERE x.f1_enum`

The condition returns without IN part.

It works fine for the types without quotes in their names:
`
SELECT x.* FROM public.test_table_enum x WHERE f1_enum IN ('TEST1'::public.test_enum)`

**Comment by LonwoLonwo** [comment]
The original issue for tracking: https://github.com/JSQLParser/JSqlParser/issues/1482

**Comment by LonwoLonwo** [comment]
This issue was fixed in the JSQLParser. Will waiting for the official release of 4.4

**Comment by Matvey16** [comment]
Verified
