### ISSUE TITLE
PostgreSQL: anycompatiblearray aggregate function: DBeaver fails to show source code

### ISSUE THREAD

**Issue by fjf2002** [dbeaver/dbeaver#15743]
#### System information: 
- Windoze 10
- DBeaver version 22.0.0

#### Connection specification:
- PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Driver name: postgresql 42.3.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:
The database contains the function
```sql
CREATE OR REPLACE AGGREGATE tools.array_cat_agg(anycompatiblearray) (
    SFUNC = array_cat,
    STYPE = anycompatiblearray ,
    FINALFUNC_MODIFY = READ_ONLY,
    MFINALFUNC_MODIFY = READ_ONLY
);
```
DBeaver fails to show the source code, instead shows
```
/* ERROR WHILE READING SOURCE:
Error reading procedure body
*/
```

Maybe this is about relatively newly introduced polymorphic data types https://www.postgresql.org/docs/14/extend-type-system.html#EXTEND-TYPES-POLYMORPHIC-TABLE ?

**Comment by LonwoLonwo** [comment]
Hello @fjf2002 

Thanks for the bug report.

As I can see, the problem is not in the polymorphic data type (but thanks for the helpful link!).

We use pg_get_functiondef(oid) for routines definition reading. 
And pg_get_functiondef() does not work on aggregate functions - [link](https://stackoverflow.com/questions/48709614/error-array-agg-is-an-aggregate-function-while-getting-function-definitions)

We must read aggregate functions definition another way.

This is the log:
```
org.postgresql.util.PSQLException: ERROR: "array_cat_agg" is an aggregate function
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:665)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:420)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:92)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.lambda$0(SQLEditorNested.java:279)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:277)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by eckmanca-caremore** [comment]
This also occurs when trying to use Generate DDL - Show full DDL on a schema. Message:

Error ready procedure body
ERROR: "array_accum" is an aggregate function
