### ISSUE TITLE
"Illegal character in hostname" error when using Git Support plugin on WSL2

### ISSUE THREAD

**Issue by lackovic** [dbeaver/dbeaver#15757]
#### System information: 
- Operating system and version: Windows 10 21H1
- DBeaver version: `22.0.0`
- Additional extensions: **Git Support plugin**

#### Connection specification:
- Database name and version: irrelevant
- Driver name: irrelevant
- The Git Support plugin repository files are stored in the WSL2 file system, under the path `\\wsl$\Ubuntu-20.04\home\marco\src\b2b-db\`

#### Describe the problem you're observing:

Everything was working perfectly fine on DBeaver `21.3.5`. After upgrading DBeaver to `22.0.0` the Git Support plugin was gone. I reinstalled it. DBeaver was working fine for some time, then it crashed and after that when I try to open it the following dialog appears:

![2022-03-08_154500](https://user-images.githubusercontent.com/1663053/157251006-1ee63f3a-db22-4ab5-882a-db98dc496bac.png)

#### The last entry from the \.metadata\.log file:
```
!ENTRY org.eclipse.osgi 4 0 2022-03-08 15:41:41.694
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Error initializing desktop platform
	at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:109)
	at org.jkiss.dbeaver.core.DesktopPlatform.getInstance(DesktopPlatform.java:85)
	at org.jkiss.dbeaver.core.DesktopAdapterFactory.getAdapter(DesktopAdapterFactory.java:33)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$13(AdapterManager.java:302)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:743)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:718)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:733)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.initDebugWriter(DBeaverApplication.java:631)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:238)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
	at org.jkiss.dbeaver.core.DesktopPlatform.initialize(DesktopPlatform.java:155)
	at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:105)
	... 34 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.core.resources (46).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:384)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:471)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:403)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.core.resources.ResourcesPlugin.start() of bundle org.eclipse.core.resources.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:828)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 44 more
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in hostname at index 19: egit-internal://WSL$/Ubuntu-20.04/home/marco/src/b2b-db/.git/$7$WORKTREE:o7/.dbeaver/project-metadata.json
	at org.eclipse.egit.core.internal.efs.EgitFileSystem$UriComponents.toUri(EgitFileSystem.java:327)
	at org.eclipse.egit.core.internal.efs.FilteredWorktreeFileStore.toURI(FilteredWorktreeFileStore.java:136)
	at org.eclipse.core.filesystem.provider.FileStore.getFileSystem(FileStore.java:316)
	at org.eclipse.core.internal.filesystem.FileStoreUtil.compareFileStore(FileStoreUtil.java:138)
	at org.eclipse.core.filesystem.IFileStore.compareTo(IFileStore.java:583)
	at java.base/java.util.TreeMap.getEntryUsingComparator(Unknown Source)
	at java.base/java.util.TreeMap.getEntry(Unknown Source)
	at java.base/java.util.TreeMap.get(Unknown Source)
	at org.eclipse.core.internal.resources.AliasManager$LocationMap.add(AliasManager.java:139)
	at org.eclipse.core.internal.resources.AliasManager.addToLocationsMap(AliasManager.java:378)
	at org.eclipse.core.internal.resources.AliasManager.addToLocationsMap(AliasManager.java:368)
	at org.eclipse.core.internal.resources.AliasManager.buildLocationsMap(AliasManager.java:406)
	at org.eclipse.core.internal.resources.AliasManager.startup(AliasManager.java:611)
	at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2494)
	at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2231)
	at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:475)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
	... 51 more
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 19: egit-internal://WSL$/Ubuntu-20.04/home/marco/src/b2b-db/.git/$7$WORKTREE:o7/.dbeaver/project-metadata.json
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.parseHostname(Unknown Source)
	at java.base/java.net.URI$Parser.parseServer(Unknown Source)
	at java.base/java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at org.eclipse.egit.core.internal.efs.EgitFileSystem$UriComponents.toUri(EgitFileSystem.java:325)
	... 69 more
```

**Comment by lackovic** [comment]
I fixed it by:
1. uninstalling DBeaver
1. deleting `C:\Users\Marco\AppData\Roaming\DBeaverData`
1. installing DBeaver

**Comment by Matvey16** [comment]
Most of the time it can be fixed with less losses. You don't necessarily need to delete the whole DBeaverData folder, just one `workbench.xmi` file and sometimes `.metadata/.plugins/org.eclipse.core.resources` folder.

https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
