### ISSUE TITLE
Can't restore dump for MySQL

### ISSUE THREAD

**Issue by serhiikartashov** [dbeaver/dbeaver#15795]
#### System information: 
- Operating system - Microsoft Windows 10 Pro
- DBeaver version - DBeaver Enterprise Version 21.3.0.202112052011
- Additional extensions - no

#### Connection specification:
- Database name and version - MySQL [8.0.27]
- Driver name - MySQL Connector/J [mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - no, connecting local database from https://hub.docker.com/_/mysql 

#### Describe the problem you're observing:
I have dump from this particular version, but I can restore it to the local environment.

driver properties:
**defaultAuthenticationPlugin**: com.mysql.cj.protocol.a.authentication.MysqlNativePasswordPlugin
**allowPublicKeyRetrieval**: TRUE

I can connect to the database as well, but can't restore the dump!

#### Steps to reproduce, if exist:
Tools->Restore Database->choose dump in SQL format->receive error message

#### Include any warning/errors/backtraces from the logs
`C:\Users\<user>\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe -u ****** --host=localhost --port=3308 vdp
Task 'MySQL restore' started at Thu Mar 10 16:45:18 EET 2022
ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.

Task 'MySQL restore' finished at Thu Mar 10 16:45:18 EET 2022
2022-03-10 16:45:18.866 - IO error: Process failed (exit code = 1). See error log.
2022-03-10 16:45:18.867 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:230)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:210)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:270)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:76)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
`

**Comment by LonwoLonwo** [comment]
Hello @serhiikartashov 

Thanks for the bug report.

You can find some workarounds here: https://github.com/dbeaver/dbeaver/issues/15319

And we will investigate this issue further

**Comment by BlackDahlia313** [comment]
I'm using Digital Ocean managed databases and this doesnt help. Please fix
