### ISSUE TITLE
Invalid thread access on "Edit cell" on jsonb and json field

### ISSUE THREAD

**Issue by virtualdxs** [dbeaver/dbeaver#15815]
#### System information: 
- OS: Arch Linux (systemd 250, kernel 5.16.12)
- DBeaver version: 22.0.0
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 13.5
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH tunnel, but reproducible without SSH tunnel

#### Describe the problem you're observing:
When trying to edit a jsonb or json field in a table with shift+enter or right click -> edit -> edit cell, I get a popup error "Invalid thread access", with the following in command line output:

```
2022-03-12 17:05:23.933 - Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:561)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:477)
	at org.eclipse.swt.widgets.Scrollable.getClientArea(Scrollable.java:248)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.getMaxVisibleRows(LightGrid.java:2187)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$ContentProvider.getCellValue(SpreadsheetPresentation.java:2009)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$SpreadsheetValueController.getValue(SpreadsheetPresentation.java:2438)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditorInput.getValue(ContentEditorInput.java:181)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditorInput.prepareContent(ContentEditorInput.java:196)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditorInput.<init>(ContentEditorInput.java:89)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditor$LOBInitializer.run(ContentEditor.java:195)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

AFAICT this only happens on the last row of a table that has at least 2 rows.

#### Steps to reproduce, if exist:

1. Create table with schema:

```
CREATE TABLE public.test (
	jbtest jsonb,
	jtest json
);
```

2. Open Data tab of table
3. Click "Add new row" twice
4. Select either of the fields on the second row of the table
5. Press shift+enter

#### Include any warning/errors/backtraces from the logs
Backtrace above; session information:

```
eclipse.buildId=unknown
java.version=17.0.3
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

**Comment by uslss** [comment]
thanks for the report
