### ISSUE TITLE
Oracle sequence DDL

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#15829]
We need to add DDL tab for Oracle sequences

**Comment by LonwoLonwo** [comment]
![2022-03-15 01_06_17-DBeaver Ultimate 22 0 0 - TESTAS4](https://user-images.githubusercontent.com/45152336/158269322-3bf1b423-3ce8-467b-9eb3-6fe00694090c.png)

Implemented in DBeaver 22.0.1

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Indexes DDL stopped working
```
java.lang.ClassCastException: class org.jkiss.dbeaver.ext.oracle.model.OracleTableIndex cannot be cast to class org.jkiss.dbeaver.model.struct.DBSObjectWithScript (org.jkiss.dbeaver.ext.oracle.model.OracleTableIndex is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6ae73197; org.jkiss.dbeaver.model.struct.DBSObjectWithScript is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @290ee433)
	at org.jkiss.dbeaver.ext.oracle.ui.editors.OracleSourceDeclarationEditor.isReadOnly(OracleSourceDeclarationEditor.java:56)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider.isModifiable(SQLEditorNested.java:258)
	at org.eclipse.ui.texteditor.AbstractTextEditor.isEditorInputModifiable(AbstractTextEditor.java:6763)
	at org.eclipse.ui.texteditor.TextEditorAction.canModifyEditor(TextEditorAction.java:120)
	at org.eclipse.ui.texteditor.TextOperationAction.update(TextOperationAction.java:146)
	at org.eclipse.ui.texteditor.TextOperationAction.<init>(TextOperationAction.java:76)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createActions(AbstractTextEditor.java:5642)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createActions(AbstractDecoratedTextEditor.java:1139)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.createActions(SQLEditorBase.java:529)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3471)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:454)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.createPartControl(BaseTextEditor.java:140)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.createPartControl(SQLEditorBase.java:286)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested.createPartControl(SQLEditorNested.java:134)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageEditor.createControl(TabbedFolderPageEditor.java:98)
	at org.jkiss.dbeaver.ui.controls.folders.TabbedFolderComposite$FolderPane.onFolderSwitch(TabbedFolderComposite.java:153)
	at org.jkiss.dbeaver.ui.controls.folders.TabbedFolderComposite$FolderPane$2.widgetSelected(TabbedFolderComposite.java:136)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
	at org.jkiss.dbeaver.ui.controls.folders.TabbedFolderList.select(TabbedFolderList.java:639)
	at org.jkiss.dbeaver.ui.controls.folders.TabbedFolderList.select(TabbedFolderList.java:611)
	at org.jkiss.dbeaver.ui.controls.folders.TabbedFolderList$ListElement$1.mouseUp(TabbedFolderList.java:126)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:268)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
