### ISSUE TITLE
[Firebird] Error when sorting by function column in the grouping panel

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#15911]
#### System information: 
- Win11
- DBeaver CE 21.0.1

#### Connection specification:
- Firebird

#### Describe the problem you're observing:
Can't sort column in the grouping panel that is represent grouping panel's functions such as COUNT(), SUM(), MAX(), etc..

#### Steps to reproduce, if exist:
1. Open table in the firebird db
2. Open grouping panel
3. Draag and drop one column from the data editor to the grouping panel
4. Press sorting button at the column header
![image](https://user-images.githubusercontent.com/43252954/159310624-e5cfcaff-a06b-4c60-be2b-5b16cefeecf3.png)

Then you can see  this
![image](https://user-images.githubusercontent.com/43252954/159310443-7fc459a7-480c-4025-951e-649879638cab.png)

#### Include any warning/errors/backtraces from the logs
```
SQL Error [335544851] [42000]: Dynamic SQL Error; SQL error code = -104; Unexpected end of command - line 5, column 10 [SQLState:42000, ISC error code:335544851]
```

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [335544851] [42000]: Dynamic SQL Error; SQL error code = -104; Unexpected end of command - line 5, column 10 [SQLState:42000, ISC error code:335544851]
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingDataContainer.readData(GroupingDataContainer.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: Dynamic SQL Error; SQL error code = -104; Unexpected end of command - line 5, column 10 [SQLState:42000, ISC error code:335544851]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:534)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:140)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:204)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:171)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:155)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readGenericResponse(AbstractWireOperations.java:257)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readGenericResponse(AbstractFbWireDatabase.java:201)
	at org.firebirdsql.gds.ng.wire.version11.V11Statement.prepare(V11Statement.java:89)
	at org.firebirdsql.jdbc.FBStatement.prepareFixedStatement(FBStatement.java:881)
	at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:868)
	at org.firebirdsql.jdbc.FBStatement.executeImpl(FBStatement.java:496)
	at org.firebirdsql.jdbc.FBStatement.execute(FBStatement.java:482)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: Dynamic SQL Error

```

**Comment by LonwoLonwo** [comment]
It seems that the FireBird does not support sorting by COUNT column.

![2022-03-22 12_28_41-Event](https://user-images.githubusercontent.com/45152336/159449899-b97f96cf-e319-4551-8e45-7a82a8af8969.png)

![2022-03-22 12_29_26-DBeaver Ultimate 22 0 1 - ALBUM](https://user-images.githubusercontent.com/45152336/159449917-5dbe92e1-1c78-427a-b6c4-3ff903857f91.png)

**Comment by LonwoLonwo** [comment]
Connected with https://github.com/dbeaver/dbeaver/issues/19769

**Comment by Matvey16** [comment]
Fixed in https://github.com/dbeaver/dbeaver/pull/20475
