### ISSUE TITLE
Impossible to launch Dbeaver for some users

### ISSUE THREAD

**Issue by Cornis777** [dbeaver/dbeaver#15948]
Hello some users can't launch Dbeaver. When they try to launch Dbeaver they receive this error : 

!SESSION 2022-03-23 10:25:31.907 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_321
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2022-03-23 10:25:33.122
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

They use a Windows Server, it's works on some user and not in some other users.
We tried to kill the user local session without more success.

Do you've an idea about the problem ?

**Comment by Destrolaric** [comment]
@Cornis777, Hi, I see you use Java 8 to launch DBeaver. The currently supported Java version for DBeaver is 11. Can I ask, which installation method was used?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
