### ISSUE TITLE
Data isn't shown in Data editor and Incorrect query is generated fo Read data in SQL editor action

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#15959]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 22.0.1

#### Connection specification:
- Database name and version Apache Druid
#### Describe the problem you're observing:
Data editor:
![image](https://user-images.githubusercontent.com/31996417/159901285-53d6c451-8ee1-4190-aef0-85120156aae8.png)

Read data in SQL editor:
Generated Query:
```sql
SELECT "__time", "count", "id", "unique_users", "user_last_login", "user_name", "user_password", "venue_category_name", "venue_latitude", "venue_longitude", "venue_name", "venue_price"
FROM "druid"."druid"."checkins";
```

Works ok:
```sql
SELECT "__time", "count", "id", "unique_users", "user_last_login", "user_name", "user_password", "venue_category_name", "venue_latitude", "venue_longitude", "venue_name", "venue_price"
FROM "checking";
````
Error: 
<details>

```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Mar 24 13:37:36 MSK 2022
Error -1 (00000) : Error while executing SQL "SELECT "__time", "count", "id", "unique_users", "user_last_login", "user_name", "user_password", "venue_category_name", "venue_latitude", "venue_longitude", "venue_name", "venue_price"
FROM "druid"."druid"."checkins"": Remote driver error: RuntimeException: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> SqlValidatorException: Object 'druid' not found within 'druid'

org.apache.calcite.avatica.AvaticaSqlException: Error -1 (00000) : Error while executing SQL "SELECT "__time", "count", "id", "unique_users", "user_last_login", "user_name", "user_password", "venue_category_name", "venue_latitude", "venue_longitude", "venue_name", "venue_price"
FROM "druid"."druid"."checkins"": Remote driver error: RuntimeException: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid' -> SqlValidatorException: Object 'druid' not found within 'druid'
	at org.apache.calcite.avatica.Helper.createException(Helper.java:54)
	at org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:163)
	at org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:217)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3505)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
java.lang.RuntimeException: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid'
	at org.apache.druid.sql.avatica.DruidStatement.closeAndPropagateThrowable(DruidStatement.java:377)
	at org.apache.druid.sql.avatica.DruidStatement.prepare(DruidStatement.java:181)
	at org.apache.druid.sql.avatica.DruidMeta.prepareAndExecute(DruidMeta.java:191)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:206)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:927)
	at org.apache.calcite.avatica.remote.Service$PrepareAndExecuteRequest.accept(Service.java:879)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:133)
	at org.apache.druid.sql.avatica.DruidAvaticaHandler.handle(DruidAvaticaHandler.java:59)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid'
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:217)
	at org.apache.druid.sql.calcite.planner.DruidPlanner.prepare(DruidPlanner.java:103)
	at org.apache.druid.sql.SqlLifecycle.prepare(SqlLifecycle.java:155)
	at org.apache.druid.sql.avatica.DruidStatement.prepare(DruidStatement.java:162)
	... 27 more
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 2, column 6 to line 2, column 31: Object 'druid' not found within 'druid'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:834)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:819)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4867)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:166)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:177)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3125)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3107)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3379)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:940)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:647)
	at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:215)
	... 30 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'druid' not found within 'druid'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
	... 49 more
```
</details>

**Comment by uslss** [comment]
Could be fixed by enabling Omit Catalog names in queries in driver properties. Actual for Druid and Kylin
![image](https://user-images.githubusercontent.com/31996417/159921763-8a906c8b-0588-43c7-b2a4-3f8e76bf37f9.png)

**Comment by LonwoLonwo** [comment]
"Omit catalog names in queries" is now enabled by default for the Apache Kylin and Druid databases.

**Comment by uslss** [comment]
verified
