### ISSUE TITLE
Dbeaver: Cannot export or import csv, No transaction in progress/ Object parameter binding not supported

### ISSUE THREAD

**Issue by Gsquaree** [dbeaver/dbeaver#15967]
#### System information: 
- Operating system (distribution) and version: MacOS Big Sur version 11.6.5
- DBeaver version: Version 22.0.1.202203181646
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

I can't seem to export my data results to csv, or import csv to table.

For exporting, I can't seem to export anything. It will give me the error of 'No transaction in progress' after Proceeding. However dbeaver has no issues querying the data and giving me results normally. I tried multiple setting changes, and the default settings, and different queries and it still fails.

> Task execution failed
> 
> Reason:
> SQL Error [21]: Query failed (#20220324_154406_01848_ppm98): No transaction in progress

For importing, I tried multiple times to import a simple csv file into an existing table with the same number of columns. The preview looks good and the column mapping seems to have no issue. However it keeps producing this error, where 'Amplomp' is the first text in the first cell of the results. Disabling batching does not help. Choosing to 'skip' or 'stop' will give me the 'No transaction in progress' error

> Error occurred during batch insert
> (you can disable batch insert in order to skip particular rows).
> 
> Reason:
> Object parameter [Amplomp] binding not supported

#### Steps to reproduce, if exist:

Same issue occurs for everything i try to export or import

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-24 23:44:07.142
!MESSAGE io.prestosql.spi.PrestoException: No transaction in progress
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-03-24 23:44:07.142
!MESSAGE io.prestosql.spi.PrestoException: No transaction in progress
!STACK 0
io.prestosql.spi.PrestoException: No transaction in progress
	at io.prestosql.execution.RollbackTask.execute(RollbackTask.java:45)
	at io.prestosql.execution.RollbackTask.execute(RollbackTask.java:31)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.prestosql.$gen.Presto_350_1_0_0_4_g41a7bbc____20220324_141156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-24 23:47:26.423
!MESSAGE Can't close statement
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-03-24 23:47:26.423
!MESSAGE Query failed (#20220324_154726_00654_9hifi): Prepared statement not found: statement1
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-03-24 23:47:26.423
!MESSAGE io.prestosql.spi.PrestoException: Prepared statement not found: statement1
!STACK 0
io.prestosql.spi.PrestoException: Prepared statement not found: statement1
	at io.prestosql.execution.QueryStateMachine.removePreparedStatement(QueryStateMachine.java:760)
	at io.prestosql.execution.DeallocateTask.execute(DeallocateTask.java:40)
	at io.prestosql.execution.DeallocateTask.execute(DeallocateTask.java:27)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.prestosql.$gen.Presto_350_1_0_0_4_g41a7bbc____20220324_144036_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-24 23:47:26.425
!MESSAGE Error inserting row
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-03-24 23:47:26.425
!MESSAGE Object parameter [Amplop] binding not supported
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [Amplop] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.data.ExecuteInsertBatchImpl.bindStatement(ExecuteInsertBatchImpl.java:106)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:169)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.lambda$0(DatabaseTransferConsumer.java:417)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:415)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:363)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:281)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:143)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:115)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:33.542
!MESSAGE Error transfering data from online_learning_semantic_results_202203232215_intent.csv to hive.product_analytics.online_learning_intent_test [Existing]
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:33.542
!MESSAGE SQL Error [21]: Query failed (#20220324_154927_01947_ppm98): No transaction in progress
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:33.542
!MESSAGE Query failed (#20220324_154927_01947_ppm98): No transaction in progress
!STACK 0
java.sql.SQLException: Query failed (#20220324_154927_01947_ppm98): No transaction in progress
	at io.prestosql.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1839)
	at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1749)
	at io.prestosql.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:118)
	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
	at io.prestosql.jdbc.PrestoConnection.commit(PrestoConnection.java:175)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.commit(JDBCExecutionContext.java:421)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:462)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:471)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:293)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:143)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:115)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: io.prestosql.spi.PrestoException: No transaction in progress
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:44)
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:30)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.prestosql.$gen.Presto_350_1_0_0_4_g41a7bbc____20220324_141156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:33.542
!MESSAGE io.prestosql.spi.PrestoException: No transaction in progress
!STACK 0
io.prestosql.spi.PrestoException: No transaction in progress
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:44)
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:30)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.prestosql.$gen.Presto_350_1_0_0_4_g41a7bbc____20220324_141156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:34.412
!MESSAGE io.prestosql.spi.PrestoException: No transaction in progress
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-03-24 23:49:34.412
!MESSAGE io.prestosql.spi.PrestoException: No transaction in progress
!STACK 0
io.prestosql.spi.PrestoException: No transaction in progress
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:44)
	at io.prestosql.execution.CommitTask.execute(CommitTask.java:30)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.prestosql.$gen.Presto_350_1_0_0_4_g41a7bbc____20220324_141156_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by LonwoLonwo** [comment]
Hello @Gsquaree 

What database do you use?
What DDL has target table?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
