### ISSUE TITLE
Error connecting to GBQ - "Could not initialize class sun.font.SunFontManager"

### ISSUE THREAD

**Issue by asitmonty** [dbeaver/dbeaver#16026]
Hi, 

I am trying to connect to Google Big query using DBeaver, but I keep on getting this error message:
"Unexpected driver error occurred while connecting to the database
  Could not initialize class sun.font.SunFontManager"

I was able to connect to GBQ earlier using DBeaver, although from a different laptop. So, I know that the connection worked fine before.

My system:
Windows 11 Pro 21H2, 22000.556
DBeaver CE 22.0.1.202203201503
Java version 8 update 311 (build 1.8.0_311-b11)

#### Connection specification:
- Database - Google Big Query
- Driver name : Google BigQuery driver provided by DBeaver
- not using any tunnel or proxies
I am using oAuth type - user based. 

![image](https://user-images.githubusercontent.com/18743366/161038696-bdbd272b-94d7-401e-8e5c-aeb289ed9282.png)

#### Describe the problem you're observing:
Trying to connect to Google Big Query gives this error.

#### Steps to reproduce, if exist:
When i click on test connection after filling up the details, i get this error

#### warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Mar 31 16:18:29 IST 2022
Could not initialize class sun.font.SunFontManager

java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(Unknown Source)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(Unknown Source)
	at java.desktop/javax.swing.JComponent.getFontMetrics(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getMinimumSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI.installUI(Unknown Source)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.setUI(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.updateUI(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.<init>(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.showInputDialog(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.userAccountOAuth(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.core.BQConnection.connect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.AbstractDriver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:185)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:204)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:202)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:112)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.bigquery.model.BigQueryDataSource.<init>(BigQueryDataSource.java:36)
	at org.jkiss.dbeaver.ext.bigquery.BigQueryDataSourceProvider.openDataSource(BigQueryDataSourceProvider.java:53)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:981)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:918)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @asitmonty 

What driver do you use for connecting?

![2022-03-31 14_40_50-DBeaver Ultimate 22 0 2 - _PUB400 COM_Script-143](https://user-images.githubusercontent.com/45152336/161047126-38cbd515-18e3-4386-ac9b-b759a40cc417.png)

**Comment by uslss** [comment]
There has been no update on issue for a long time.  If it is still reproducible - feel free to reopen it
