### ISSUE TITLE
DynamoDB SQL queries update and delete error

### ISSUE THREAD

**Issue by Nik-dot** [dbeaver/dbeaver#16043]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: DBeaver Ultimate 22.0.0

#### Connection specification:
- Database name and version: Amazon DynamoDB

#### Describe the problem you're observing:
When I execute SQL statements from script on DyanamoDB tables, the SELECT does work, but UPDATE and DELETE statements does not work and this error is given as output: 
Expected ':' at line 1 column 10 path $.

#### Steps to reproduce, if exist:
It occurs if I try to execute a statement like:
`UPDATE table
SET option='true'
WHERE id='username'`

#### Include any warning/errors/backtraces from the logs
Expected ':' at line 1 column 10 path $.
org.jkiss.dbeaver.model.exec.DBCException: Expected ':' at line 1 column 10 path $.
at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.executeStatement(DynamoQueryStatement.java:145)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3504)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4841)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 10 path $.
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:55)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
at com.google.gson.Gson.fromJson(Gson.java:932)
at com.google.gson.Gson.fromJson(Gson.java:897)
at com.google.gson.Gson.fromJson(Gson.java:846)
at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.createJsonQueryRequest(DynamoQueryStatement.java:366)
at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.parseQueryText(DynamoQueryStatement.java:159)
at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.executeStatement(DynamoQueryStatement.java:113)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3504)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4841)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Matvey16** [comment]
@Nik-dot Thank you for the report

**Comment by E1izabeth** [comment]
Linked PR: https://github.com/dbeaver/dbeaver-ee/pull/1632
