### ISSUE TITLE
Connection with SSH 

### ISSUE THREAD

**Issue by gvaleika** [dbeaver/dbeaver#16066]
#### System information: 
- Archlinux
- DBeaver version 22.0.1

#### Connection specification:
- Postgresql, MySQL
- SSH tunel

#### Describe the problem you're observing:
While conncting to connection with configured ssh tunel I get error. 

![image](https://user-images.githubusercontent.com/23062169/161549761-1087936f-5c22-4e7e-a8f8-c56e00917ad8.png)

#### Steps to reproduce, if exist:

connect to ssh tunel connection

#### Include any warning/errors/backtraces from the logs

2022-04-04 16:09:12.005 - Connect with 'PostgreSQL - newprod - pg - db1  ssh' (postgres-jdbc-17dfb715719-5955c05824f912cf)
2022-04-04 16:09:12.007 - Adding identity key
2022-04-04 16:09:12.007 - Configure tunnel
2022-04-04 16:09:12.072 - Connection failed (postgres-jdbc-17dfb715719-5955c05824f912cf)
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:911)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel to 91.199.55.223:1422
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:76)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:906)
	... 3 more
Caused by: com.jcraft.jsch.JSchException: fromBase64: invalid base64 data
	at com.jcraft.jsch.Util.fromBase64(Util.java:63)
	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:219)
	at com.jcraft.jsch.KnownHosts.setKnownHosts(KnownHosts.java:55)
	at com.jcraft.jsch.JSch.setKnownHosts(JSch.java:316)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:110)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 385 out of bounds for length 385
	at com.jcraft.jsch.Util.fromBase64(Util.java:51)
	... 10 more

**Comment by serge-rider** [comment]
Probably something is wrong with known_hosts file in your home directory.

Try to enable option "Bypass host verification" in advanced SSH settings.

**Comment by gvaleika** [comment]
ssh and dbeaver 21 with current known_hosts file works. dbeaver 22 - fails.

**Comment by gvaleika** [comment]
Actually turning off "Bypass host verification" workaround works. Meanwhile dbeaver 21 works as is.

It is not clear 22 fails while verifying host configured for that connection or fails on random known host. Because same failure happens on different connections(mysql and pg) using different ssh hosts.

**Comment by E1izabeth** [comment]
Host verification was implemented in dbeaver 21.3.5. known_hosts file was not used earlier

**Comment by gvaleika** [comment]
Can confirm that my known_hosts file had 1 corrupted record. After I corrected this record 22 version works.

May be this can be feature request - check known_hosts line by line and ignore(log with info) corrupted lines instead of failing to connect using any ssh tunel.

**Comment by E1izabeth** [comment]
Thank you for investigation! We will think about how to improve this behavior.

**Comment by Matvey16** [comment]
Verified
