### ISSUE TITLE
ssh tunnel with mongo driver throwing exception with v4.0.5

### ISSUE THREAD

**Issue by robinson-scott** [dbeaver/dbeaver#1608]
Windows 10
Dbeaver version 4.0.5
MongoDB Extension 1.4.29
mongo-java-driver 3.2.2

Other Info:
cassandra ssh tunnel works fine.

Log snippet:
2017-04-25 15:56:25.287 - SSH INFO: Authentications that can continue: password
2017-04-25 15:56:25.288 - SSH INFO: Next authentication method: password
2017-04-25 15:56:25.336 - SSH INFO: Authentication succeeded (password).
2017-04-25 15:56:25.340 - > Start com.dbeaver.ent.mongodb [1.4.29]
2017-04-25 15:56:25.610 - MONGO INFO: Cluster created with settings {hosts=[127.0.0.1:56157], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, description='DBeaver Enterprise 4.0.5'}
Apr 25, 2017 3:56:25 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[127.0.0.1:56157], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, description='DBeaver Enterprise 4.0.5'}
2017-04-25 15:56:25.622 - MONGO INFO: Adding discovered server 127.0.0.1:56157 to client view of cluster
Apr 25, 2017 3:56:25 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Adding discovered server 127.0.0.1:56157 to client view of cluster
2017-04-25 15:56:25.685 - MONGO INFO: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=MULTIPLE, all=[ServerDescription{address=127.0.0.1:56157, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
Apr 25, 2017 3:56:25 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=MULTIPLE, all=[ServerDescription{address=127.0.0.1:56157, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2017-04-25 15:56:26.140 - MONGO INFO: Opened connection [connectionId{localValue:1, serverValue:13758}] to 127.0.0.1:56157
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:1, serverValue:13758}] to 127.0.0.1:56157
2017-04-25 15:56:26.202 - MONGO INFO: Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56157, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=56451765, setName='ipm', canonicalAddress=10.250.16.72:27017, hosts=[10.250.16.72:27017], passives=[], arbiters=[], primary='10.250.16.72:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000003, setVersion=1}
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:56157, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 0]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=56451765, setName='ipm', canonicalAddress=10.250.16.72:27017, hosts=[10.250.16.72:27017], passives=[], arbiters=[], primary='10.250.16.72:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000003, setVersion=1}
2017-04-25 15:56:26.219 - MONGO INFO: Discovered cluster type of REPLICA_SET
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Discovered cluster type of REPLICA_SET
2017-04-25 15:56:26.224 - MONGO INFO: Adding discovered server 10.250.16.72:27017 to client view of cluster
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Adding discovered server 10.250.16.72:27017 to client view of cluster
2017-04-25 15:56:26.230 - MONGO INFO: Server 127.0.0.1:56157 is no longer a member of the replica set.  Removing from client view of cluster.
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Server 127.0.0.1:56157 is no longer a member of the replica set.  Removing from client view of cluster.
2017-04-25 15:56:26.237 - MONGO INFO: Canonical address 10.250.16.72:27017 does not match server address.  Removing 127.0.0.1:56157 from client view of cluster
Apr 25, 2017 3:56:26 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Canonical address 10.250.16.72:27017 does not match server address.  Removing 127.0.0.1:56157 from client view of cluster
2017-04-25 15:56:46.232 - MONGO INFO: Exception in monitor thread while connecting to server 10.250.16.72:27017
Apr 25, 2017 3:56:46 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Exception in monitor thread while connecting to server 10.250.16.72:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 more

2017-04-25 15:56:55.685 - Connection failed (cql-158decea4c5-5ea7942874e19618)
2017-04-25 15:56:55.688 - SSH INFO: Disconnecting from 10.250.16.72 port 22
2017-04-25 15:56:55.691 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2017-04-25 15:56:55.738 - org.jkiss.dbeaver.model.exec.DBCException: Error connecting to Mongo instance [127.0.0.1]
org.jkiss.dbeaver.model.exec.DBCException: Error connecting to Mongo instance [127.0.0.1]
	at com.dbeaver.ent.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:77)
	at com.dbeaver.ent.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:65)
	at com.dbeaver.ent.mongodb.model.MongoDataSource.<init>(MongoDataSource.java:89)
	at com.dbeaver.ent.mongodb.MongoDataSourceProvider.openDataSource(MongoDataSourceProvider.java:104)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:719)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:645)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:121)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Error connecting to Mongo instance [127.0.0.1]
	at com.dbeaver.ent.mongodb.exec.MongoExecutionContext.reconnect(MongoExecutionContext.java:229)
	at com.dbeaver.ent.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:74)
	... 18 more
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=10.250.16.72:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:89)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:84)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:130)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:124)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:114)
	at com.dbeaver.ent.mongodb.exec.MongoExecutionContext.reconnect(MongoExecutionContext.java:226)
	... 19 more

**Comment by serge-rider** [comment]
Maybe problem is in mongo host name. It has to be recognizable from tunnel target machine (sometimes it has to be IP address or FQ domain name, maybe from another subnet, etc).

**Comment by robinson-scott** [comment]
I did use a straight IPv4 address. I thought it might be something in our setup, but nothing has changed recently (famous last words). I did try'localhost', 127.0.0.1 and the external interfaces that mongo was listening on. same effect. Mongo is listening on 127.0.0.1 and 10.250.16.149. I did try the same ssh localhost:27017 configuration with Robomongo 1.0 and MongoDB Compass 1.6.2, they both connected without any issues.

I also set up an ssh tunnel via the command line to rule out ssh driver problems.
ssh -L 27017:localhost:27017 username@10.250.16.149
I could connect to 27017 (local connection - no ssh) using robomongo. Get the same time out from DBeaver.

I found an issue logged on the mongodb java driver project that seems related.
https://jira.mongodb.org/browse/JAVA-2211
Looks like there are complexities when connecting to a replica set. If I'm following correctly, the far end address must be mapped (in the replica set). I tried the IP (10.250.16.149) that is the host according to the replicaset configuration.

Any other ideas of what to try, or debug to gather?

**Comment by serge-rider** [comment]
Need to try this with SSHJ (#2202 )

**Comment by serge-rider** [comment]
Can't reproduce this anymore.
Please reopen if you still have this issue.

**Comment by serge-rider** [comment]
Not possible to solve this problem with current Mongo driver. It uses target host name to open replica set connections, in case of standard SSH tunnel it is localhost (or resolved domain name of local host).

We'll upgrade Mongo driver in the next release (also to support Mongo transactions). Maybe it'll help.
