### ISSUE TITLE
Unable to Authenticate to Azure SQL with Active Directory MFA 

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#16130]
#### System information: 
- Operating system (distribution) and version: Windows 10 PRO
- DBeaver version: CE 22.0.2 (EA) , but also with stable version
- Additional extensions: none

#### Connection specification:
- Database name and version: Micosoft SQL Azure 
- Driver name: com.microsoft.sqlserver.jdbc.SQLServerDriver 9.2.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I try to connect to the database, DBeaver return this the error:

Unexpected driver error occurred while connecting to the database
  com.microsoft.aad.msal4j.MsalClientException: java.net.UnknownHostException: login.windows.net
  com.microsoft.aad.msal4j.MsalClientException: java.net.UnknownHostException: login.windows.net
    java.net.UnknownHostException: login.windows.net
    java.net.UnknownHostException: login.windows.net
      login.windows.net
      login.windows.net

![image](https://user-images.githubusercontent.com/26387091/162437684-0117b66e-715d-4023-8989-8d72f6fdaed3.png)

This is my driver configuration:
![image](https://user-images.githubusercontent.com/26387091/162437779-47679af0-6a77-4b7a-9393-5e178460e93e.png)

![image](https://user-images.githubusercontent.com/26387091/162437828-e5ed78ad-2e90-4ca9-acf2-4745776b4bc6.png)

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2022-04-08 14:41:24.021
!MESSAGE login.windows.net
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-04-08 14:41:24.021
!MESSAGE login.windows.net
!STACK 0
java.net.UnknownHostException: login.windows.net
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:107)
	at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpGet(DefaultHttpClient.java:47)
	at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:35)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:221)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:56)
	at com.microsoft.aad.msal4j.AccountsSupplier.get(AccountsSupplier.java:26)
	at com.microsoft.aad.msal4j.AccountsSupplier.get(AccountsSupplier.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by geuss** [comment]
Hi,I installed the last version of DBEAVER ( 22.3.4.202302060909), tryed to reinstall all drivers... and the error is changed. 

Here's all steps, after requesting a Connection from DBEAVER:

Inserting my credential:
![Immagine1](https://user-images.githubusercontent.com/26387091/217484969-be73aa90-51bb-42a2-975d-1ce7cf8e3d38.png)

Authenticate with Microsoft Authenticator:
![Immagine2](https://user-images.githubusercontent.com/26387091/217485007-0d354dae-e58e-4f6b-9285-7b9138b6e683.png)

There no response from server:
![Immagine3](https://user-images.githubusercontent.com/26387091/217485537-36348fda-7499-461d-b83e-24e354e53c80.png)

If I open Microsoft Edge Dev Tools there's this problem:
![Immagine4](https://user-images.githubusercontent.com/26387091/217485906-a356f4ad-329b-43c1-8c5f-83feb6a0b65d.png)

..and Dbeaver shows me this error:
![Immagine5](https://user-images.githubusercontent.com/26387091/217486070-2eaf8400-c848-47a8-baa9-ad6d3f66581f.png)

Here's debug logs:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10683765/dbeaver-debug.log)

Thanks!

**Comment by E1izabeth** [comment]
Thank you for update.

**Comment by LonwoLonwo** [comment]
Hello @geuss 

Please try to do this:

```
Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:

<!-- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j --> <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> 
```

https://github.com/dbeaver/dbeaver/issues/15446#issuecomment-1097140996

**Comment by geuss** [comment]
Thanks Anastasiya, It worked!! Only I had to specify a fixed address of "login.windows.net" on my hosts file:

20.190.159.69   login.windows.net

Without this configuration I had this error:

!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-27 14:39:57.544
!MESSAGE java.net.UnknownHostException: login.windows.net
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-27 14:39:57.544
!MESSAGE java.net.UnknownHostException: login.windows.net
!STACK 0
java.lang.RuntimeException: java.net.UnknownHostException: login.windows.net
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:230)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenInteractive(SQLServerMSAL4JUtils.java:195)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5569)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5419)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5306)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:306)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:126)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6299)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4911)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4849)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:80)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:137)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1195)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1060)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


(perhaps a proxy issue...)

**Comment by geuss** [comment]
I close this issue.

**Comment by geuss** [comment]
![image](https://user-images.githubusercontent.com/26387091/221582602-e3c373d0-e485-40de-b213-18212af7b090.png)

Here my driver artifacts configuration (for all those with the same problem)

**Comment by LonwoLonwo** [comment]
Thanks for the answer @geuss

**Comment by paulstegmann** [comment]
I still get the error. What else can I do?

![](https://user-images.githubusercontent.com/26387091/217486070-2eaf8400-c848-47a8-baa9-ad6d3f66581f.png)

**Comment by LonwoLonwo** [comment]
Hello @paulstegmann 

Please provide the screen of your drivers. You can find this window in your connections settings -> Driver settings -> Libraries

**Comment by paulstegmann** [comment]
HI @LonwoLonwo,

sure: 
![image](https://user-images.githubusercontent.com/14310061/227974508-82c5a288-9d5e-4f12-b3c5-767aa1e29036.png)

**Comment by LonwoLonwo** [comment]
Hello @paulstegmann 

Could you please try to update the msal4j library version? To 1.12.0

Additionally, you can try our DBeaver PRO version, which has special support for the Azure MFA. Try for free: https://dbeaver.com/trial/

**Comment by paulstegmann** [comment]
Hi @LonwoLonwo,

thanks a lot, thats it! dbeaver is working again now.

Best!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @paulstegmann

**Comment by 84drizzt** [comment]
Got the same problem in May, update the msal4j library version to 1.13.8, then problem is resolved.

**Comment by paleo** [comment]
> Hello @geuss
> 
> Please try to do this:
> 
> ```
> Go to "Edit Driver Settings," click the "Libraries" tab, then click "Add Artifact," then add the Maven dependency declaration:
> 
>  <dependency> <groupId>com.microsoft.azure</groupId> <artifactId>msal4j</artifactId> <version>1.11.3</version> </dependency> 
> ```
> 
> [#15446 (comment)](https://github.com/dbeaver/dbeaver/issues/15446#issuecomment-1097140996)

Thanks a lot, you save me.
