### ISSUE TITLE
Can't connect to MongoDB Atlas

### ISSUE THREAD

**Issue by Loizzus** [dbeaver/dbeaver#16168]
#### System information: 
- Windows 11
- DBeaver Enterprise 22.0.0

#### Connection specification:
- MongoDB Atlas
- MongoDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When trying to connect to a MongoDB Atlas server with a URL I get the error:
_"Error connecting to MongoDB instance [localhost]
A TXT record is only permitted to contain the keys [authsource, replicaset], but the TXT record for 'timeclockdb.gxirr.mongodb.net' contains the keys [loadbalanced, authsource]"_

According to [this forum post](https://www.mongodb.com/community/forums/t/atlas-serverless-and-dns-txt-record/117967/9) the driver that DBBeaver uses is too old, the issue was resolved in version 4.1 or higher. 

I tried replacing the file "org.mongodb.mongo-java-driver_3.12.7.jar" with the latest "mongodb-driver-core-4.5.1.jar" renamed to the same but that did not work. 

Also it seems that there is no way to manually upgrade or install a new MongoDB driver in DBeaver. 

#### Steps to reproduce, if exist:
Sign up to a serverless instance of MongoDB [here ](https://www.mongodb.com/cloud/atlas/serverless)and use the URL to connect to your instance.

**Comment by serge-rider** [comment]
MongoDB Java driver 4.x API significantly differs from 3.x API.
We need to migrate to the new API in the next DBeaver EE version.

**Comment by uslss** [comment]
export db-db isn't possible
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/

org.jkiss.dbeaver.model
Error
Mon Apr 25 13:51:44 CEST 2022
class com.mongodb.BasicDBObject cannot be cast to class org.bson.Document (com.mongodb.BasicDBObject and org.bson.Document are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1370db3f)

java.lang.ClassCastException: class com.mongodb.BasicDBObject cannot be cast to class org.bson.Document (com.mongodb.BasicDBObject and org.bson.Document are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1370db3f)
	at com.dbeaver.db.mongodb.exec.sql.MGInsertStatement.executeStatement(MGInsertStatement.java:74)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:310)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:178)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.lambda$0(DatabaseTransferConsumer.java:416)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:414)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:362)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:300)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by uslss** [comment]
column filter isn't working for resultset (ok in data editor)
![image](https://user-images.githubusercontent.com/31996417/165084458-9a966450-2555-430b-bb3b-aee4552edd5f.png)

**Comment by serge-rider** [comment]
Fixed
