### ISSUE TITLE
Oracle: the error appears on a table partition opening

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#16207]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 22.0.3.202204140515

#### Connection specification:
- Database name and version Oracle
#### Steps to reproduce, if exist:

1. Open a table with partitions (e.g. INTERVAL_SALES)
2. Open a partition

**Expected:** the partition is opened in a separate tab
**Actual result**: the error appears:

https://user-images.githubusercontent.com/51405061/163661739-487cede8-4c97-460e-8978-eca00d8e5849.mp4

**Comment by LonwoLonwo** [comment]
Error:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2022-04-18 09:36:42.842
!MESSAGE Missing IN or OUT parameter at index:: 3
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-04-18 09:36:42.842
!MESSAGE Missing IN or OUT parameter at index:: 3
!STACK 0
java.sql.SQLException: Missing IN or OUT parameter at index:: 3
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:2086)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3772)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical.getSubPartitions(OracleTablePhysical.java:189)
	at org.jkiss.dbeaver.ext.oracle.model.OracleTablePartition.getSubPartitions(OracleTablePartition.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:292)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LonwoLonwo** [comment]
Fixed

![2022-04-18 09_47_29-DBeaver Ultimate 22 0 3 - SALES_JAN2000](https://user-images.githubusercontent.com/45152336/163768040-7d7a5a81-d125-4965-b099-0ee8cc3cbbca.png)

**Comment by Matvey16** [comment]
Verified
