### ISSUE TITLE
DBeaver SSHJ install error

### ISSUE THREAD

**Issue by dmamchyts** [dbeaver/dbeaver#16285]
#### System information: 
- Operating system (distribution) and version - Linux dmamchyts-m16 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- DBeaver version - Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 22.0.3.202204170718]
- Additional extensions - try to install sshj

#### Describe the problem you're observing:
Can not install sshj:

#### Steps to reproduce, if exist:
Follow this instruction https://github.com/dbeaver/dbeaver/issues/5845#issuecomment-541593022

#### Include any warning/errors/backtraces from the logs

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
  Missing requirement: Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs 1.69.0.v20210713-1924 (org.bouncycastle.bcpkix 1.69.0.v20210713-1924) requires 'java.package; org.bouncycastle.asn1.bsi [1.69.0,1.70.0)' but it could not be found
  Cannot satisfy dependency:
    From: DBeaver SSHJ 1.0.93.202112211454 (org.jkiss.dbeaver.net.sshj.feature.feature.group 1.0.93.202112211454)
    To: org.eclipse.equinox.p2.iu; org.bouncycastle.bcpkix [1.69.0.v20210713-1924,1.69.0.v20210713-1924]
```

**Comment by Matvey16** [comment]
Hello @dmamchyts You don't need to install SSHJ anymore, it is included in a base installer. Simply select it in advanced settings of SSH for the connection

**Comment by dmamchyts** [comment]
Hi @Matvey16 ,

Thank you, for your answer.
But can you explain why I can't connect to server by *privatekey* and without *passphrase*.

I am select SSHJ:

```

2022-04-22 16:16:13.285 - Generating random seed from SecureRandom.
2022-04-22 16:16:13.286 - No such algorithm: IDEA/CBC/NoPadding
2022-04-22 16:16:13.286 - No such algorithm: IDEA/CTR/NoPadding
2022-04-22 16:16:13.288 - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
2022-04-22 16:16:13.336 - Client identity string: SSH-2.0-SSHJ_0.27.0
2022-04-22 16:16:13.389 - Server identity string: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
2022-04-22 16:16:13.580 - Read key type: ssh-rsa
2022-04-22 16:16:13.718 - Exhausted available authentication methods
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
        at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345)
        at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:393)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:95)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:134)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:76)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$7.execute(SSHTunnelConfiguratorUI.java:247)
        at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:590)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by dbeaver-pm** [comment]
Duplicate of #16852
