### ISSUE TITLE
Very slow download speeds from debian repository

### ISSUE THREAD

**Issue by sandermarechal** [dbeaver/dbeaver#16296]
I am using the https://dbeaver.io/debs/dbeaver-ce debian repository to install dbeaver. Problem is that the download speed from that repository is very slow, usually around or below 200 kbps. I am on gigabit fiber so I am pretty sure that the problem is not on my end. Other downloads are fast for me. With the dbeaver package being well over 100mb and getting frequent updates, this often means very long wait times during system updates.

Can download speeds for the debian repository be improved?

**Comment by LonwoLonwo** [comment]
Hello @sandermarechal 

Could you please clarify your location?
Do you use VPN?

**Comment by sandermarechal** [comment]
I am in The Netherlands. At work we have Ziggo Business 1 gbps internet. At home I use Ziggo Giganet (also 1 gbps). I do not use a VPN.

**Comment by mayerro** [comment]
@sandermarechal could you please send [traceroute](https://en.wikipedia.org/wiki/Traceroute) result from your PC to our [dbeaver.io](http://dbeaver.io/) site:
windows: `tracert dbeaver.io`
linux/macos: `traceroute dbeaver.io`

**Comment by sandermarechal** [comment]
Sure. From my work:
```
$ traceroute dbeaver.io
traceroute to dbeaver.io (104.131.190.124), 30 hops max, 60 byte packets
 1  D57DBDC5.static.ziggozakelijk.nl (213.125.189.197)  10.319 ms  10.281 ms  10.246 ms
 2  tb-rc0001-cr101-ae40-0.core.as9143.net (213.51.158.66)  11.312 ms  11.251 ms  11.237 ms
 3  asd-rc0001-cr101-be152-2.core.as33915.net (213.51.5.12)  15.086 ms asd-tr0021-cr101-be152-2.core.as33915.net (213.51.5.14)  17.410 ms asd-rc0001-cr101-be152-2.core.as33915.net (213.51.5.12)  15.027 ms
 4  nl-ams04a-ri3-ae51-0.core.as9143.net (213.51.64.194)  17.299 ms  22.757 ms nl-ams04a-ri3-ae50-0.core.as9143.net (213.51.64.66)  16.161 ms
 5  ix-ae-30-0.tcore1.ad1-amsterdam.as6453.net (80.231.80.30)  16.113 ms  18.109 ms  16.989 ms
 6  if-ae-2-33.tcore1.av2-amsterdam.as6453.net (195.219.150.114)  102.835 ms if-ae-11-2.tcore2.av2-amsterdam.as6453.net (80.231.152.25)  90.622 ms *
 7  * if-ae-2-2.tcore2.av2-amsterdam.as6453.net (195.219.194.6)  97.120 ms  102.352 ms
 8  * * *
 9  * * if-ae-2-2.tcore1.l78-london.as6453.net (80.231.131.2)  91.917 ms
10  if-be-2-2.ecore1.n75-newyork.as6453.net (66.110.96.62)  101.495 ms if-ae-66-2.tcore3.nto-newyork.as6453.net (80.231.130.106)  102.073 ms if-ae-66-7.tcore3.nto-newyork.as6453.net (80.231.130.23)  93.722 ms
11  if-be-2-2.ecore1.n75-newyork.as6453.net (66.110.96.62)  106.890 ms if-ae-1-3.tcore4.njy-newark.as6453.net (216.6.57.6)  109.423 ms *
12  if-ae-57-2.tcore1.n75-newyork.as6453.net (66.110.96.58)  101.395 ms  101.261 ms 66.110.96.26 (66.110.96.26)  91.356 ms
13  * * 66.110.96.26 (66.110.96.26)  87.284 ms
14  138.197.244.33 (138.197.244.33)  100.542 ms 138.197.248.55 (138.197.248.55)  104.116 ms 138.197.244.41 (138.197.244.41)  104.035 ms
15  66.110.96.22 (66.110.96.22)  99.302 ms * 66.110.96.26 (66.110.96.26)  86.889 ms
16  * * *
17  138.197.248.61 (138.197.248.61)  113.875 ms * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

And from home:
```
$ traceroute dbeaver.io
traceroute to dbeaver.io (104.131.190.124), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.929 ms  0.972 ms  0.991 ms
 2  * * *
 3  ht-rc0001-cr102-et111-251.core.as33915.net (213.51.194.85)  17.034 ms  18.490 ms  18.433 ms
 4  asd-tr0021-cr101-be152-10.core.as9143.net (213.51.158.12)  23.348 ms  23.326 ms  23.275 ms
 5  nl-ams04a-ri3-ae51-0.core.as9143.net (213.51.64.194)  19.984 ms  19.895 ms  21.442 ms
 6  ix-ae-30-0.tcore1.ad1-amsterdam.as6453.net (80.231.80.30)  23.004 ms  13.639 ms  18.282 ms
 7  if-ae-2-33.tcore1.av2-amsterdam.as6453.net (195.219.150.114)  98.930 ms if-ae-11-2.tcore2.av2-amsterdam.as6453.net (80.231.152.25)  103.855 ms if-ae-7-2.tcore1.av2-amsterdam.as6453.net (195.219.194.45)  103.880 ms
 8  if-ae-2-2.tcore2.av2-amsterdam.as6453.net (195.219.194.6)  95.329 ms *  97.145 ms
 9  if-ae-14-2.tcore2.l78-london.as6453.net (80.231.131.160)  97.201 ms * *
10  * * *
11  * * *
12  * * *
13  if-ae-57-2.tcore1.n75-newyork.as6453.net (66.110.96.58)  110.251 ms if-ae-14-2.tcore3.nto-newyork.as6453.net (63.243.186.16)  102.666 ms if-ae-57-2.tcore1.n75-newyork.as6453.net (66.110.96.58)  95.849 ms
14  138.197.244.47 (138.197.244.47)  106.574 ms * 66.110.96.26 (66.110.96.26)  104.367 ms
15  138.197.244.43 (138.197.244.43)  112.377 ms if-ae-57-2.tcore1.n75-newyork.as6453.net (66.110.96.58)  97.357 ms *
16  * 66.110.96.26 (66.110.96.26)  100.841 ms 66.110.96.22 (66.110.96.22)  90.574 ms
17  * * *
18  138.197.248.55 (138.197.248.55)  101.281 ms * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

**Comment by LonwoLonwo** [comment]
Thanks for the report @sandermarechal

**Comment by LonwoLonwo** [comment]
You can try to use the PPA: https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce

**Comment by sandermarechal** [comment]
It appears I can't use that PPA because it's not signed:
```
# add-apt-repository ppa:serge-rider/dbeaver-ce
 DBeaver Community Edition
Universal Database Tool and SQL Client
https://dbeaver.io/
 More info: https://launchpad.net/~serge-rider/+archive/ubuntu/dbeaver-ce
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp53087qy_/pubring.gpg' created
gpg: /tmp/tmp53087qy_/trustdb.gpg: trustdb created
gpg: key 4A71B51882788FD2: public key "Launchpad PPA for Serge Rider" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'

root@ws44:~# apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease                                                                                                          
Hit:3 http://ftp.debian.org/debian buster-backports InRelease                                                                                                                      
Hit:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                       
Hit:5 http://deb.debian.org/debian buster-updates InRelease                                                                                                                        
Hit:6 https://packages.microsoft.com/repos/ms-teams stable InRelease                                                                                                               
Hit:7 https://repo.skype.com/deb stable InRelease                                                                                                                  
Hit:8 https://packages.sury.org/php buster InRelease                                                  
Get:10 http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu kinetic InRelease [18.1 kB]
Hit:9 https://debian.qgis.org/debian buster InRelease                              
Err:10 http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu kinetic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4A71B51882788FD2
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu kinetic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4A71B51882788FD2
E: The repository 'http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu kinetic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by sandermarechal** [comment]
~I updated dbeaver using the original URL at https://dbeaver.io/debs/dbeaver-ce but it appears to be a lot faster than it was a month ago.~

Scratch that. It's back to ~380 kbps

**Comment by LonwoLonwo** [comment]
Please try to use

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 30ece325`

**Comment by LonwoLonwo** [comment]
Oh, sorry, this is the correct command:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 30ECE32520D438C21E16BF884A71B51882788FD2`

**Comment by sandermarechal** [comment]
Thanks, that command worked. I can confirm that the PPA version has much, much faster download speeds.

**Comment by LonwoLonwo** [comment]
Thanks for the answer and for the investigation @sandermarechal 

Can I close this ticket?

**Comment by sandermarechal** [comment]
Yes :-)
