### ISSUE TITLE
"Check for Updates" fails with bundled JVM due to certificate issues

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#16333]
#### System information: 
- Operating system (distribution) and version Linux, Debian/SID
- DBeaver version 22.0.3
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Installed from deb, using bundled JVM the "Check for Updates" fails with
```
Cannot obtain version information. Perhaps the network connection is down?

Reason:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Funnily enough (see #14321), once I switch to my locally installed JVM the check goes through flawlessly.
 
#### Steps to reproduce, if exist:
- install deb
- start DBeaver
- Help -> Check for Updates
- error

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 4 0 2022-04-27 14:10:18.687
!MESSAGE unable to find valid certification path to requested target
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-04-27 14:10:18.687
!MESSAGE unable to find valid certification path to requested target
!STACK 0
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
at java.base/sun.security.validator.Validator.validate(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:105)
at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:50)
at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:45)
at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:54)
at org.jkiss.dbeaver.ui.app.standalone.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:126)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ShadelessFox** [comment]
Hello @2019-05-10,

Is your network private?

Our bundled Java may not have the required certificates installed.

**Comment by 2019-05-10** [comment]
Define "private", please.

> Our bundled Java may not have the required certificates installed.

Well, that just strengthens my point about bundling not being a good idea.

**Comment by emironovDB** [comment]
Hello @2019-05-10,

We have Linux distributions of DBeaver that don't have bundled Java in them: https://dbeaver.io/download/

Can you please try these?

**Comment by 2019-05-10** [comment]
> We have Linux distributions of DBeaver that don't have bundled Java in them: https://dbeaver.io/download/

The ZIP archives? Those are not an option, since they completely defeat the purpose of a package management. 
And there's not really something to test, the issue is obviously once again the certificate management of the bundled JVM, since it works once I fix the `dbeaver.ini` to use the local JVM :shrug:
