### ISSUE TITLE
ava.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by stefanLarie** [dbeaver/dbeaver#16349]
Hello community , I appreciate your product , and I have this NoSuchFileException  when the application starts 

Unable to save backed up workspaces
java.nio.file.NoSuchFileException: /MYPATH/dbeaver-ce/180/.local/share/DBeaverData/.workspaces
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.write(Unknown Source)
	at java.base/java.nio.file.Files.write(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.saveWorkspacesToBackup(DBeaverApplication.java:399)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:379)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:325)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:194)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

I`m using Ubuntu version 20.0  

file: dbeaver-ce/180/.local/share/DBeaverData/.workspaces dose not exists on my local so that`s the reason. could you please fix this?
Thank you!

#### Steps to reproduce, if exist:

I run: sudo snap install dbeaver-ce
dbeaver-ce

**Comment by flambchap** [comment]
Hi @stefanLarie. Thank you for your report. Can you work with DBeaver despite this exception, or DBeaver fails to start completely?

**Comment by serge-rider** [comment]
Seems to be a side effect of some specific deployment (snap?).
Although this error shouldn't block DBeaver start we must check .workspaces directory existence before save.

**Comment by serge-rider** [comment]
Please test thee fix in the Early Access version (https://dbeaver.io/files/ea) or wait 22.0.5 release.
