### ISSUE TITLE
Azure Synapse Serverless: cannot read view definition

### ISSUE THREAD

**Issue by dr-1** [dbeaver/dbeaver#16368]
#### System information: 
- Windows 10
- DBeaver 22.0.3

#### Connection specification:
- Database type: Azure Synapse "serverless"
- Driver name: Azure SQL Server
- No tunnels or proxies

#### Describe the problem you're observing:
Trying to get the DDL of a view produces a NullPointerException and the definition pane shows:
```
/* ERROR WHILE READING SOURCE:

null
*/
```

In version 22.0.0, view definitions could be obtained, see #15490.

#### Steps to reproduce, if exist:
- Open a view object in this type of database
- Go to Properties -> Definition

#### Include any warning/errors/backtraces from the logs
Exception stack trace:

java.lang.NullPointerException
	at org.jkiss.dbeaver.model.DBUtils.getQuotedIdentifier(DBUtils.java:78)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerViewManager.createOrReplaceViewQuery(SQLServerViewManager.java:115)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerViewManager.addObjectDeleteActions(SQLServerViewManager.java:91)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectDeleteCommand.getPersistActions(SQLObjectEditor.java:401)
	at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.getTableDDL(SQLTableManager.java:224)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableDDL(DBStructUtils.java:89)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.getTableDDL(DBStructUtils.java:116)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableListDDL(DBStructUtils.java:176)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:95)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.lambda$0(SQLEditorNested.java:279)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:277)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Session data:

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

Connection test shows:

Server:
    Microsoft SQL Server 12.00.214
    Microsoft SQL Azure (RTM) - 12.0.2000.8 
    Mar 31 2022 08:13:33 
Driver:
    Microsoft JDBC Driver 9.2 for SQL Server 9.2.0.0

Output of `SELECT SERVERPROPERTY('EngineEdition')`: 11

`SELECT definition FROM sys.sql_modules WHERE object_id = (OBJECT_ID(N'your_shema_name.your_view_name'))` (adapted to existing schemas and views, obviously) gives no results.

**Comment by LonwoLonwo** [comment]
Hello @dr-1 

Sorry, I do not understand.

You said me here, what statement `FROM sys.sql_modules WHERE object_id = (OBJECT_ID(N'your_shema_name.your_view_name'))` did work for you:
https://github.com/dbeaver/dbeaver/issues/15490#issuecomment-1041347435

And now:

> SELECT definition FROM sys.sql_modules WHERE object_id = (OBJECT_ID(N'your_shema_name.your_view_name')) (adapted to existing schemas and views, obviously) gives no results.

This statement did not work for you now? What changed?

**Comment by LonwoLonwo** [comment]
Also, do you open the "definition" view tab for the default database? Or for the other?

**Comment by dr-1** [comment]
Hi @LonwoLonwo, that is correct, at that time querying sys.sql_modules returned the view definitions, but not anymore. When removing the WHERE condition, I see a few other objects recorded in sys.sql_modules, but none of the views.

**Comment by dr-1** [comment]
I had not set a default database in the connection I was using. When I do specify the database in the connection settings, the view definitions can be read! For me this solves the issue, although I suppose the expected behavior is that the definitions can be read regardless of which database is set as default, so I would still consider it an open issue.

**Comment by LonwoLonwo** [comment]
We do not have a test environment, unfortunately. So we can fix this issue only a blind way. 
And the main problem is with the incorrect current database definition. For this reason, your query didn't work also - you must add a database prefix if you want to find a view from another database.
Anyway, thanks for the bug report @dr-1
