### ISSUE TITLE
Oracle connect error ,when change the user interface language to a language other than English.

### ISSUE THREAD

**Issue by LjzMorn** [dbeaver/dbeaver#16419]
#### System information: 
- Operating system (distribution) and version：Windows 10
- DBeaver version：22.0.4.202205011839
- Additional extensions：No

#### Connection specification:
- Database name and version：Oracle Database 10g Release 10.2.0.1.0 - Production
- Driver name：Oracle JDBC driver 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ： No

#### Describe the problem you're observing:
Change the user interface language to taiwan,it shows 'Locale not recognized'.
When I change back to English,the connect turn to success.

**Comment by LonwoLonwo** [comment]
Hello @LjzMorn 

It shows 'Locale not recognized' where?
Can you please check the error logs? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by LjzMorn** [comment]
Hi @LonwoLonwo 

In "New Database Connection"→"Choose Oracle"→Enter My Database → push the button 'Test Connection'。
<img width="858" alt="dbeaver oracle" src="https://user-images.githubusercontent.com/104968827/167056861-32ef890d-48cd-418f-a5c2-e1fcfa1a5ed9.png">

But if user interface language in English,it will success.↓
<img width="847" alt="dbeaver oracle-2" src="https://user-images.githubusercontent.com/104968827/167057155-0defaf2d-92d8-496b-a25a-985c7d5d54b2.png">



**error Logs↓**
!ENTRY org.jkiss.dbeaver.model 4 0 2022-05-06 10:13:09.414
!MESSAGE Locale not recognized
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-05-06 10:13:09.414
!MESSAGE Locale not recognized
!STACK 0
java.sql.SQLException: Locale not recognized
	at oracle.jdbc.driver.T4CTTIoauthenticate.setSessionFields(T4CTTIoauthenticate.java:1493)
	at oracle.jdbc.driver.T4CTTIoauthenticate.<init>(T4CTTIoauthenticate.java:291)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:599)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:204)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:168)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:86)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
Hello @LjzMorn,

Does changing these settings help?

![image](https://user-images.githubusercontent.com/35821147/167870534-191e25c6-428c-4bb0-b8cd-89a52f56c104.png)

**Comment by LjzMorn** [comment]
Hi @ShadelessFox ,
Before report this issue,I tried it .
But it didn't help.
↓
![image](https://user-images.githubusercontent.com/104968827/167979582-d70950f0-67be-4c19-ba9a-76c7822ed44d.png)
![image](https://user-images.githubusercontent.com/104968827/167979939-aec97b89-e93b-4c32-b12a-849ac827ccc6.png)
![image](https://user-images.githubusercontent.com/104968827/167980015-46eb6a47-38ac-49b6-a595-22e8c1d83e07.png)
![image](https://user-images.githubusercontent.com/104968827/167980066-fe7544b4-77f4-4e3e-bd9d-c60cc4865774.png)

**Comment by ShadelessFox** [comment]
Thanks for the bug report.

**Comment by LonwoLonwo** [comment]
Hello @LjzMorn 

Can you please check? Is this issue actually in the current DBeaver release? https://dbeaver.io/download/

**Comment by LjzMorn** [comment]
> 

Hi @LonwoLonwo ,
![image](https://user-images.githubusercontent.com/104968827/203194828-7a8f6be3-8900-42c0-a0b9-fcfe5249ad73.png)
Yes,Same as report.

Log↓
!ENTRY org.jkiss.dbeaver.model 4 0 2022-11-22 09:39:04.175
!MESSAGE Locale not recognized
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-11-22 09:39:04.175
!MESSAGE Locale not recognized
!STACK 0
java.sql.SQLException: Locale not recognized
	at oracle.jdbc.driver.T4CTTIoauthenticate.setSessionFields(T4CTTIoauthenticate.java:1493)
	at oracle.jdbc.driver.T4CTTIoauthenticate.<init>(T4CTTIoauthenticate.java:291)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:599)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:172)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:90)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1025)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by habufly** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/100653977/f2a51a1e-30d4-4253-8687-cf16695ac2d3)
![image](https://github.com/dbeaver/dbeaver/assets/100653977/c054b27d-9e9d-48c6-9122-f6865e2eb246)

I got the same problem with the latest version.
Please help to fix it, thanks.

**Comment by jacky7788** [comment]
After changing to English and remove this fixed the problem.
![image](https://github.com/dbeaver/dbeaver/assets/28256291/e838d436-960d-4fbf-917f-9422678bd7c8)

**Comment by NikolozKuridze** [comment]
Set the Timezone correctly and that's it , It works for me
