### ISSUE TITLE
Cannot create new columns via gui

### ISSUE THREAD

**Issue by pkExec** [dbeaver/dbeaver#16476]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **22.0.4.202205011839**
- Additional extensions: **No**

#### Connection specification:
- Database name and version: 
**PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit**
- Driver name: **postgres-jdbc** 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
Trying to create a column (to a table with geometry if that matters) via the UI displays this error:

`class org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput cannot be cast to class org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput (org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @45062219; org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @767191b1)`

#### Steps to reproduce, if exist:
- Right click table, select "View Table"
- Go to Properties->Columns.
- Right click, select "Create new column"

#### Include any warning/errors/backtraces from the logs
Stack trace:
`
java.lang.ClassCastException: class org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput cannot be cast to class org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput (org.jkiss.dbeaver.tasks.ui.DataSourceToolsContributor$DataSourceEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @45062219; org.jkiss.dbeaver.ui.editors.IDatabaseEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @767191b1)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectBase.getCommandTarget(NavigatorHandlerObjectBase.java:117)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase.createNewObject(NavigatorHandlerObjectCreateBase.java:155)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:119)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.jkiss.dbeaver.ui.ActionUtils.runCommand(ActionUtils.java:356)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:112)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
`

Session Data:
`
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
`

**Comment by pkExec** [comment]
Workaround: Restart dbeaver and try again.

Maybe it's the same as [this bug? ](https://github.com/dbeaver/dbeaver/issues/14626)

**Comment by ShadelessFox** [comment]
Hello @pkExec,

Thanks for the bug report.

I was able to find the steps required to reproduce the issue:
1. Connect to a database that supports tools
2. From the `Database` menu, open any tool, such as session manager, lock manager, etc.
3. Expand any table in the navigator and try to create a new column by clicking on the `Columns` folder

**Comment by pkExec** [comment]
@ShadelessFox, I cannot reproduce it consistently either. It may have to do with the time the editor remains idle. I had left it open overnight, with locked PC. I resumed this morning, to encounter this error. I believe the same is mentioned in #14626

**Comment by ShadelessFox** [comment]
Sorry, I meant that I **was able** to reproduce it. Please look at the provided steps.
