### ISSUE TITLE
Can't select active catalog/schema in SQL editor - SQL Server

### ISSUE THREAD

**Issue by steepdescend** [dbeaver/dbeaver#16471]
#### System information: 
- Operating system (distribution) and version: Win 10 Enterprise
- DBeaver version 22.0.4
- Additional extensions

#### Connection specification:
- Database name and version: MS SQL Server
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: Named pipe 

#### Describe the problem you're observing:
I have the same problem at work when I am connected to MS SQL Server. Active catalog/schema shows N/A, even when I explicitly select the database. Previously, when I worked for another company that uses Vertica, the Active catalog/schema was working fine (I was using Macbook pro at that company) and working as expected.

This is the same issue as https://github.com/dbeaver/dbeaver/issues/14693

**Comment by uslss** [comment]
@steepdescend unfortunately, cannot reproduce it. Could you provide some video or screenshots of the issue?

**Comment by steepdescend** [comment]
Here's a screenshot of what I see. Even when I selected the database, it showed only N/A. I can query the database, but have to use fully qualified reference.

![20220513_144530](https://user-images.githubusercontent.com/45262395/168393652-f6f64af9-aea1-4018-b569-1d2709f386f7.png)

**Comment by LonwoLonwo** [comment]
Can you please check the error logs? You can find the instruction here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by steepdescend** [comment]
> 

Yes, here is the error log when I clicked on the Active catalog/schema. It is the only error in the log, no other type of error.

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue May 17 09:33:47 PDT 2022
USE statement is not supported to switch between databases. Use a new connection to connect to a different Database.

com.microsoft.sqlserver.jdbc.SQLServerException: USE statement is not supported to switch between databases. Use a new connection to connect to a different Database.
                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
                at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
                at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
                at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
                at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
                at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
                at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
                at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeSQL(JDBCUtils.java:598)
                at org.jkiss.dbeaver.ext.mssql.SQLServerUtils.setCurrentDatabase(SQLServerUtils.java:89)
                at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setCurrentDatabase(SQLServerExecutionContext.java:214)
                at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setCurrentDatabase(SQLServerExecutionContext.java:209)
                at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setDefaultCatalog(SQLServerExecutionContext.java:117)
                at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setDefaultCatalog(SQLServerExecutionContext.java:1)
                at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:401)
                at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:358)
                at org.jkiss.dbeaver.ui.actions.datasource.SelectActiveSchemaHandler$2.run(SelectActiveSchemaHandler.java:210)
                at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Can you please check the aswer from `SELECT SERVERPROPERTY('EngineEdition')`? Or what exactly MSSQL version do you use?

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If it is still actual - feel free to reopen it.

**Comment by Jasonliu68** [comment]
Same error when connection to Azure Synapse Dedicated SQL Pool.

DBeaver 23.2.3
Windows 10 Enterprise

I think the root cause is, the Azure Synapse (or Azure SQL) doesn't support use 'Use' statement to swtich database.

So the 'Choose category/schema' is always 'N/A'.


![image](https://github.com/dbeaver/dbeaver/assets/38401780/b0aa89c5-db34-4630-a634-2513299c149e)





com.microsoft.sqlserver.jdbc.SQLServerException: USE statement is not supported to switch between databases. Use a new connection to connect to a different Database.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:518)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeSQL(JDBCUtils.java:569)
	at org.jkiss.dbeaver.ext.mssql.SQLServerUtils.setCurrentDatabase(SQLServerUtils.java:89)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setCurrentDatabase(SQLServerExecutionContext.java:216)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setCurrentDatabase(SQLServerExecutionContext.java:211)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setDefaultCatalog(SQLServerExecutionContext.java:119)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerExecutionContext.setDefaultCatalog(SQLServerExecutionContext.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:449)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:406)
	at org.jkiss.dbeaver.ui.actions.datasource.SelectActiveSchemaHandler$2.run(SelectActiveSchemaHandler.java:210)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
