### ISSUE TITLE
When using SSH Tunnel, password retrieval from .pgpass looks for 127.0.0.1 instead of the DB host name

### ISSUE THREAD

**Issue by tomsafekeep** [dbeaver/dbeaver#16499]
#### System information: 
- Operating system (distribution) and version Mac OS X 12.2
- DBeaver version 22.0.4
- Additional extensions Remote System Explorer

#### Connection specification:
- Database name and version Postgresql 14
- Driver name Standard
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH

#### Describe the problem you're observing:
When using "PostgreSQL PgPass" authentication method with SSH Tunnel, dbeaver searches for a host name 127.0.0.1 (instead of the host name of the database, e.g. pg.example.com).

#### Steps to reproduce, if exist:
1. Create new connection with host name, port and username.
2. Select "PostgreSQL pgPass" authentication method. 
3. Put the credentials for this connection in ~/.pgpass
4. Set up SSH tunnel. 
5. Try to connect.

A workaround is:
In the .pgpass file, replace all host names with 127.0.0.1 and specify the database name. However, this will break if:
1. Two different hosts use the same database name.
2. A wildcard matching is needed for the database (e.g. in case the DB name changes frequently).

#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=17
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/user/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/user/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Mon May 16 18:26:14 EDT 2022
No matches in pgpass

org.jkiss.dbeaver.DBException: No matches in pgpass
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadPasswordFromPgPass(AuthModelPgPass.java:140)
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadCredentials(AuthModelPgPass.java:53)
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadCredentials(AuthModelPgPass.java:1)
	at org.jkiss.dbeaver.model.impl.auth.AuthModelDatabaseNative.loadCredentials(AuthModelDatabaseNative.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:171)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:467)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:223)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:116)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:250)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by jsemrovdlabs** [comment]
I've found another issue when connecting to a database over an ssh tunnel. If connection to the database is using TLS, DBeaver checks if there exists record "127.0.0.1" in SAN section of the TLS certificate, instead of database host name. I'm using Neo4j database in this case, but I think the problem might occur on all types of databases, though I  am not sure if it is not just neo4j's driver issue. Don't know if these two issues are actually related. 


![image](https://user-images.githubusercontent.com/81411058/169051249-fbc392b5-2a7e-4790-8b65-b9c2536232b5.png)

**Comment by Destrolaric** [comment]
@jsemrovdlabs Hi, I think this one looks different and I think a new issue needs to be opened.

**Comment by jsemrovdlabs** [comment]
@Destrolaric Ok, I will  open another issue.

**Comment by DariaMarkaryan** [comment]
The text "Override pgpass hostname" is replaced by the value of inserted hostname

https://user-images.githubusercontent.com/43252954/177704608-f034e657-12ba-4dbe-ae45-b79396ce90de.mp4

**Comment by DariaMarkaryan** [comment]
the checkbox 'override pgpass' is always return to the enabled state
https://user-images.githubusercontent.com/43252954/178727300-ea0f12ad-677c-472e-9635-618157a8c0cc.mp4
