### ISSUE TITLE
[SQL Server] select sequence error

### ISSUE THREAD

**Issue by Cisnocxie** [dbeaver/dbeaver#16526]
#### System information: 
- Operating system (distribution) and version: windows 10 (19044.1645)
- DBeaver version: 22.0.4
- Additional extensions

#### Connection specification:
- Database name and version: sql server
- Driver name: Microsoft JDBC Driver for SQL Server (MSSQL)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
select sequence with this clause 'select next value for seq_name' will produce this error:
SQL Error [11739] [S0001]: NEXT VALUE FOR function cannot be used if ROWCOUNT option has been set, or the query contains TOP or OFFSET.

But if use sequence in a insert clause 'insert into table (col1) values (next value for seq_name)', it is normal.

**Comment by Cisnocxie** [comment]
sql server version is 2019

**Comment by LonwoLonwo** [comment]
Hello @Cisnocxie 

Please provide the error log. You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

Also please provide clear steps to error.

**Comment by Cisnocxie** [comment]
this is the error log:
!ENTRY org.jkiss.dbeaver.model 4 0 2022-05-20 09:11:03.767
!MESSAGE SQL Error [11739] [S0001]: NEXT VALUE FOR function cannot be used if ROWCOUNT option has been set, or the query contains TOP or OFFSET.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-05-20 09:11:03.767
!MESSAGE SQL Error [11739] [S0001]: NEXT VALUE FOR function cannot be used if ROWCOUNT option has been set, or the query contains TOP or OFFSET.
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-05-20 09:11:03.767
!MESSAGE NEXT VALUE FOR function cannot be used if ROWCOUNT option has been set, or the query contains TOP or OFFSET.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: NEXT VALUE FOR function cannot be used if ROWCOUNT option has been set, or the query contains TOP or OFFSET.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3515)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Cisnocxie** [comment]
steps to error:
Just execute a select sequence sql like 'select next value for seq_name'.

**Comment by Cisnocxie** [comment]
Additionally, I roll back dbeaver to 21.0.5 ver, and this issue doesn't show.

**Comment by LonwoLonwo** [comment]
Ok, I see the problem.

QueryTransformerTop.

![2022-05-23 12_26_58-Window](https://user-images.githubusercontent.com/45152336/169790452-457f3df0-b1ec-4dbc-abb2-60240a40b5e3.png)

Thanks for the bug report.

You can set the fetch size for this type of statement as a small workaround to -1. In this case, "TOP 100" will not be added to your statement,

![2022-05-23 12_30_35-Window](https://user-images.githubusercontent.com/45152336/169790635-2569e774-5175-4004-a847-0573d2e4c77f.png)

**Comment by ATikadze** [comment]
Hey, everyone
Did this issue get fixed or is there a workaround?

<img width="511" alt="Screenshot 2022-07-12 at 6 56 32 PM" src="https://user-images.githubusercontent.com/47458137/178520517-14b5b5bb-b4b1-45ca-b891-3cafd25c140a.png">

**Comment by E1izabeth** [comment]
@ATikadze, it's not fixed for the moment, but you can find workaround here https://github.com/dbeaver/dbeaver/issues/16526#issuecomment-1134432763

**Comment by ghost** [comment]
still with the error in SQL Server.

![image](https://user-images.githubusercontent.com/88109095/191545712-2dfddef0-91d6-4d3a-b3e0-d3c96b919d63.png)

> You can set the fetch size for this type of statement as a small workaround to -1. In this case, "TOP 100" will not be added to your statement

this work for me

**Comment by E1izabeth** [comment]
Fix will be available in the nearest release.
