### ISSUE TITLE
Cannot connect to SQL Server Db which I used to earlier before updating to new version.

### ISSUE THREAD

**Issue by nmadham** [dbeaver/dbeaver#1655]

**Comment by nmadham** [comment]
I could connect through SSMS though

**Comment by serge-rider** [comment]
Please post more details: error messages, error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files) and/or steps to reproduce.

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/26003067/a474c1ec-36ff-11e7-911f-fea1b3ff6936.png)

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/26003276/3a578b04-3700-11e7-848a-6bde1e653012.png)

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/26003292/48ac9870-3700-11e7-8d88-8cb36119bc66.png)

**Comment by nmadham** [comment]
also i am unable to change passwords for different instances,why?

**Comment by nmadham** [comment]
2017-05-12 11:03:25.058 - DBeaver 4.0.6 is starting
2017-05-12 11:03:25.062 - Install path: 'file:/C:/Program Files/DBeaver/'
2017-05-12 11:03:25.063 - Instance path: 'file:/C:/Users/nitesh_madham/.dbeaver4/'
2017-05-12 11:03:25.066 - Memory available 61Mb/910Mb
2017-05-12 11:03:25.082 - Starting RMI server at 37648
2017-05-12 11:03:25.177 - Create display
2017-05-12 11:03:25.218 - Run workbench
2017-05-12 11:03:27.466 - Initializing DBeaver 4.0.6
2017-05-12 11:03:27.477 - Host plugin: org.jkiss.dbeaver.core.application 4.0.6
2017-05-12 11:03:27.483 - Initialize Core...
2017-05-12 11:03:27.801 - Core initialized (318ms)
2017-05-12 11:03:27.805 - Configure workbench window
2017-05-12 11:03:27.879 - Create actions
2017-05-12 11:03:27.883 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-05-12 11:03:27.889 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-05-12 11:03:28.688 - Initialize workbench window
2017-05-12 11:03:28.724 - Finish initialization
2017-05-12 11:03:37.630 - Connect with 'SV - Staging Server' (mssql_ms-15a6635f8b7-422cdec9c1c4562)
2017-05-12 11:03:38.248 - Connection failed (mssql_ms-15a6635f8b7-422cdec9c1c4562)
2017-05-12 11:03:38.251 - org.jkiss.dbeaver.model.exec.DBCConnectException: Login failed for user 'nmadham'. ClientConnectionId:ed3848ab-e1ed-4220-b092-3265be775570
org.jkiss.dbeaver.model.exec.DBCConnectException: Login failed for user 'nmadham'. ClientConnectionId:ed3848ab-e1ed-4220-b092-3265be775570
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:104)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:130)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:719)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:645)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:121)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'nmadham'. ClientConnectionId:ed3848ab-e1ed-4220-b092-3265be775570
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:254)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:84)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:2908)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:2234)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:41)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:2220)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1326)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:991)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:827)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1012)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
	... 21 more

**Comment by uslss** [comment]
cannot reproduce the issue. ticket closed
