### ISSUE TITLE
Redshift Keep-Alive not working JDBC42

### ISSUE THREAD

**Issue by lyndavandermerwe** [dbeaver/dbeaver#16558]
#### System information: 
- Operating system (distribution) and version - OS Name -> Microsoft Windows 10 Enterprise, Version	10.0.19044 Build 19044
- DBeaver version -> Community Edition 22.0.4.202205011839
- Additional extensions -> None

#### Connection specification:
- Database name and version -> Redshift [1.0.38361]
- Driver name -> AWS Redshift JDBC driver (redshift-jdbc42-2.1.0.7.jar)
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  HTTP/HTTPS

#### Describe the problem you're observing:
JDBC driver configured with TCP keepalives (https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-install.html#configure-tcp-keepalives-jdbc20)
DBeaver connection initialization keep-alive set to 60
HTTP/HTTPS configured in network connections in preferences and Use Proxy set on connection settings

Query executed and is disconnected after 5min

#### Include any warning/errors/backtraces from the logs
<img width="629" alt="DBeaver_JDBCDriverClass" src="https://user-images.githubusercontent.com/105920847/169544453-e4f29868-ce9e-4126-8426-d50ab4432219.PNG">
<img width="541" alt="DBeaver_JDBCDriverProperties" src="https://user-images.githubusercontent.com/105920847/169544476-890cfc4d-c494-4c3c-a29a-7a555732868c.PNG">
<img width="471" alt="DBeaver_keepalive" src="https://user-images.githubusercontent.com/105920847/169544495-9f38f921-9683-4ddf-b42e-b31edd7aea5b.PNG">
<img width="671" alt="DBeaver_querydisconnect" src="https://user-images.githubusercontent.com/105920847/169544519-2d6195ea-394c-4e4f-8a1b-dfcbed301245.PNG">

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_ZA
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri May 20 13:28:42 CAT 2022
An I/O error occurred while sending to the backend.

com.amazon.redshift.util.RedshiftException: An I/O error occurred while sending to the backend.
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:395)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3515)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at com.amazon.redshift.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at com.amazon.redshift.core.VisibleBufferedInputStream.scanCStringLength(VisibleBufferedInputStream.java:330)
	at com.amazon.redshift.core.RedshiftStream.receiveString(RedshiftStream.java:474)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveFields(QueryExecutorImpl.java:2523)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2314)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	... 22 more

**Comment by Matvey16** [comment]
@lyndavandermerwe Can you specify at which moment you get diconnected. During query execution or some time after idle time? And also do you use the default driver or its copy?

**Comment by lyndavandermerwe** [comment]
Hi @Matvey16, I get disconnected during the query execution, after 5min. 
If I use the tool and let it idle the session stays connected, however consistently whilst executing a query/process which takes longer than 5min it disconnects.
I created a new driver manger using the Redshift provided JDBC driver 2.1.0.7 (we require 2.1.0.4 or later) in order to utilize the Redshift native IdP integration

**Comment by Matvey16** [comment]
Is idle transactions close disabled in your preferences?

![image](https://user-images.githubusercontent.com/82543000/181226078-59ab8cdf-b6de-4895-9894-6caf25562d03.png)

**Comment by lyndavandermerwe** [comment]
Hi @Matvey16 ,

Yes, closure of Idle transactions is disabled in my settings
![image](https://user-images.githubusercontent.com/105920847/181233994-6b85932b-eddd-4824-88f3-3c2392338be8.png)

**Comment by emironovDB** [comment]
@lyndavandermerwe 
Do you have only one connection to a database or multiple?

**Comment by lyndavandermerwe** [comment]
Hi @emironovDB ,
Sorry for not responding sooner. I was using multiple connections.
I have since change to one connection and retested and this appears to resolve the query timeout issue
