### ISSUE TITLE
Unhandled Event Loop Exception: Unable to Save Confirmation Preferences

### ISSUE THREAD

**Issue by Xylandor** [dbeaver/dbeaver#16572]
#### System information: 
- OS:  MacOS Big Sur v11.4
- DBeaver version:  22.0.5.202205220912
- Additional extensions:  None

#### Connection specification:
- AWS connection to MySQL v5.7
- Driver name: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No.

#### Describe the problem you're observing:
I'm no longer able to save changes in the Confirmations Preferences. I can change the value, click Apply and Close, open the preferences again and changes I make were reverted back. See video. An **Event loop exception** error is produced.

https://user-images.githubusercontent.com/24617679/169827529-4772df9d-d749-4b9c-92c0-16100158b3af.mov

#### Steps to reproduce, if exist:

1. Open Preferences.
2. Navigate to `User Interface` > `Confirmations`.
3. Change any of the confirmation values.
4. Click `Apply and Close`.
5. Open Preferences again and notice how the values set in step 3 are reverted back.

#### Include any warning/errors/backtraces from the logs

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/micheal/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/micheal/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Mon May 23 08:10:51 CDT 2022
Widget is disposed

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
	at org.eclipse.swt.widgets.TableItem.setText(TableItem.java:1075)
	at org.jkiss.dbeaver.ui.preferences.PrefPageConfirmations$1.saveEditorValue(PrefPageConfirmations.java:105)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.onFocusLost(CustomTableEditor.java:113)
	at org.jkiss.dbeaver.ui.controls.CustomTableEditor.lambda$1(CustomTableEditor.java:107)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$21(UIUtils.java:2139)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:127)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.custom.CCombo.comboEvent(CCombo.java:452)
	at org.eclipse.swt.custom.CCombo.lambda$0(CCombo.java:125)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1528)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1356)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Table.releaseChildren(Table.java:2192)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:994)
	at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:352)
	at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:409)
	at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:1442)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1363)
	at org.eclipse.swt.widgets.Control.release(Control.java:2970)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:695)
	at org.eclipse.jface.window.Window.close(Window.java:335)
	at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:988)
	at org.eclipse.jface.preference.PreferenceDialog.close(PreferenceDialog.java:305)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:651)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:125)
	at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:927)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:461)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4365)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3941)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:58)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.runCommand(CocoaUIHandler.java:421)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler.access$0(CocoaUIHandler.java:407)
	at org.eclipse.e4.ui.workbench.renderers.swt.cocoa.CocoaUIHandler$1.widgetSelected(CocoaUIHandler.java:281)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4365)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3941)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by LonwoLonwo** [comment]
Yep, reproducible on Mac (not reproduicible on Windows). Thanks for the bug report @Xylandor
