### ISSUE TITLE
Process failed (exit code = 2) when dumping MySQL database

### ISSUE THREAD

**Issue by LietzP** [dbeaver/dbeaver#16580]
#### System information: 
- Windows 10 
- DBeaver: 21.2.3
- Additional extensions: none

#### Connection specification:
- MySQL
- Driver name: I'm not sure what you need here?
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I dumb a database, I get the error "Error execution failed - Error executing process (Process failed (exit code = 2). See error log.)
[I'm not sure where I find the error logs] 

#### Steps to reproduce, if exist:
dumb a database, but I also got it only with one specific database. 

#### Include any warning/errors/backtraces from the logs
2022-05-24 16:58:19.515 - IO error: Process failed (exit code = 2). See error log.
2022-05-24 16:58:19.515 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:230)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:210)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:270)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:76)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by LonwoLonwo** [comment]
What MySQL server and driver version do you use?

**Comment by emironovDB** [comment]
Could you update DBeaver to the most recent version - this issue may be resolved

**Comment by LietzP** [comment]
I did update, but that did not resolve the issue. 

But my Work colleague told me that we have a problem with that database, so its not DBeavers fault.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer @LietzP 
I'm closing this ticket now.
If this problem occurs again - feel free to reopen this issue.
