### ISSUE TITLE
Databricks: Specific valid SQL query generates SQL Error [500051] [HY000]

### ISSUE THREAD

**Issue by stegus64** [dbeaver/dbeaver#16588]
#### System information: 
- Windows 11
- DBeaver version 22.0.5

#### Connection specification:
- Azure Databricks
- [SimbaSparkJDBC42-2.6.22.1040.zip](https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/jdbc/2.6.22/SimbaSparkJDBC42-2.6.22.1040.zip)

#### Describe the problem you're observing:

A valid SQL query somehow gets transformed to an invalid format which then generates an unexpected error

#### Steps to reproduce, if exist:

* Connect to an azure databricks sql endpoint
* Run the following script:

```
create or replace table temptest (
Email varchar(100),
name varchar(100)
)
;

SELECT Email, COUNT(*) as c FROM (
SELECT * FROM temptest
) src
GROUP BY Email
HAVING COUNT(*) > 1
ORDER BY c
;

```
This generates the following error:

```
SQL Error [500051] [HY000]: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:47)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:423)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:123)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:52)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:223)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:208)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:415)
	... 16 more
, Query: SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC.
```

Note that the original query has been transformed to an invalid format:
```
SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC
```

#### Include any warning/errors/backtraces from the logs

dbeaver-debug.log:

```
2022-05-25 09:55:06.492 - Create display
2022-05-25 09:55:06.525 - DBeaver 22.0.5.202205220912 is starting
2022-05-25 09:55:06.525 - OS: Windows 10 10.0 (amd64)
2022-05-25 09:55:06.525 - Java version: 11.0.12 by Eclipse Foundation (64bit)
2022-05-25 09:55:06.525 - Install path: 'C:\Program Files\DBeaver'
2022-05-25 09:55:06.525 - Instance path: 'file:/C:/Users/larss/AppData/Roaming/DBeaverData/workspace6/'
2022-05-25 09:55:06.525 - Memory available 64Mb/1024Mb
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.82.202205220912]
2022-05-25 09:55:06.550 - Starting RMI server at 50741
2022-05-25 09:55:06.578 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.400.v20220222-1128]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.100.v20210910-0640]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.0.v20201026-1147]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.400.v20211102-0453]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.400.v20220308-0630]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.100.v20210722-1426]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.100.v20210910-0640]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.400.v20211026-1534]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.97.202205220912]
2022-05-25 09:55:07.495 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
2022-05-25 09:55:07.584 - Create actions
2022-05-25 09:55:07.587 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2022-05-25 09:55:07.587 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2022-05-25 09:55:07.587 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2022-05-25 09:55:07.830 - Initialize workbench window
2022-05-25 09:55:07.834 - Finish initialization
> Start Default Text Editor [org.eclipse.ui.editors 3.14.300.v20210913-0815]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.400.v20220218-1619]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.82.202205220912]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.72.202205220912]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.82.202205220912]
> Start Team Support Core [org.eclipse.team.core 3.9.300.v20220204-0611]
> Start Core Compare Support [org.eclipse.compare.core 3.6.1000.v20201020-1107]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.900.v20220108-1321]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.4.0.v20210426-0838]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1100.v20210424-0724]
2022-05-25 09:55:08.767 - Script dialect 'databricks' not found in registry (for data source provider databricks). Use default.
2022-05-25 09:55:08.783 - Loading user drivers configuration from 'C:\Users\larss\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2022-05-25 09:55:08.783 - Total database drivers: 100 (99)
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.119.202205220912]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.88.202205220912]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20220506142945]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20220506142945]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.42.202205220912]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.42.202205220912]
> Start Console [org.eclipse.ui.console 3.11.100.v20210721-1355]
> Start Debug Core [org.eclipse.debug.core 3.19.0.v20220125-2302]
2022-05-25 09:55:09.229 - Connect with 'Databricks' (27E81889-13DC-3D0B-F7ED-3E756E5237F5-180fa1495fb-1c17cef665e5af07)
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.168.202205220912]
> Start DBeaver Azure Databricks Support [org.jkiss.dbeaver.ext.databricks 1.0.4.202205220912]
2022-05-25 09:55:09.245 - Execution context opened (Databricks; Main; 0)
2022-05-25 09:55:09.655 - Execution context opened (Databricks; Metadata; 1)
2022-05-25 09:55:09.937 - Connected (27E81889-13DC-3D0B-F7ED-3E756E5237F5-180fa1495fb-1c17cef665e5af07, SparkJDBC [02.06.22.1040])
2022-05-25 09:55:09.937 - Execution context opened (Databricks; SQLEditor <Script-33.sql>; 2)
2022-05-25 09:55:20.806 - Execution context closed (Databricks, 2)
2022-05-25 09:55:37.223 - Connect with 'Liseberg LUDDE' (databricks-1806feb3316-77234562fd385595)
2022-05-25 09:55:37.223 - Execution context opened (Liseberg LUDDE; Main; 3)
2022-05-25 09:55:37.647 - Execution context opened (Liseberg LUDDE; Metadata; 4)
2022-05-25 09:55:37.914 - Connected (databricks-1806feb3316-77234562fd385595, SparkJDBC [02.06.22.1040])
2022-05-25 09:55:37.930 - Execution context opened (Liseberg LUDDE; SQLEditor <Script-30.sql>; 5)
2022-05-25 09:55:43.142 - SQL Warning (DataSource: Liseberg LUDDE; Code: 0; State: 01000): [Simba][SparkJDBCDriver](500100) Error getting table information from database.
2022-05-25 09:55:43.351 - SQL Error [500051] [HY000]: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:47)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:423)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:123)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:52)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:223)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:208)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:415)
	... 16 more
, Query: SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC.
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [500051] [HY000]: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:47)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:423)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:123)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:52)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:223)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:208)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:415)
	... 16 more
, Query: SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3519)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:47)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:423)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:123)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:52)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:223)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:208)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:415)
	... 16 more
, Query: SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC.
	at com.simba.spark.hivecommon.api.HS2Client.pollForOperationCompletion(Unknown Source)
	at com.simba.spark.hivecommon.api.HS2Client.executeStatementInternal(Unknown Source)
	at com.simba.spark.hivecommon.api.HS2Client.executeStatement(Unknown Source)
	at com.simba.spark.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeNonRowCountQueryHelper(Unknown Source)
	at com.simba.spark.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeQuery(Unknown Source)
	at com.simba.spark.hivecommon.dataengine.HiveJDBCDSIExtQueryExecutor.execute(Unknown Source)
	at com.simba.spark.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.spark.jdbc.common.BaseStatement.execute(Unknown Source)
	at com.simba.spark.hivecommon.jdbc42.Hive42Statement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3519)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4855)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Caused by: com.simba.spark.support.exceptions.GeneralException: [Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [MISSING_COLUMN] org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:47)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:423)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties(ThriftLocalProperties.scala:123)
	at org.apache.spark.sql.hive.thriftserver.ThriftLocalProperties.withLocalProperties$(ThriftLocalProperties.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:52)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:223)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:208)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:257)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Column 'src.default_temp_testEmail' does not exist. Did you mean one of the following? [src.Email, src.name]; line 1 pos 7
	at org.apache.spark.sql.AnalysisException.copy(AnalysisException.scala:71)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:415)
	... 16 more
, Query: SELECT `src`.`default_temp_testEmail`, COUNT(*) `c` FROM (SELECT * FROM `hive_metastore`.`default`.`temp_test` `default_temp_test`) `src` GROUP BY `src`.`default_temp_testEmail` HAVING COUNT(*)>1 ORDER BY c ASC.
	... 24 more

```

**Comment by stegus64** [comment]
I managed to solve this problem myself. The problem is in the databricks jdbc driver. Not in DBeaver.
I solved the problem by adding the setting UseNativeQuery=1 in the jdbc connectionstring.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @stegus64
