### ISSUE TITLE
DBeaver cannot automatically download drivers or cannot use explicitly specified drivers in Mac mini M1

### ISSUE THREAD

**Issue by yanxg** [dbeaver/dbeaver#16641]
DBeaver cannot work in my Mac mini M1, the system information is as follows

ignite: ignite 2.12.0 
beaver: DBeaver 22.0.4 
os: Mac mini M1 11.5.

The settings about drivers are shown in images:
<img width="1493" alt="bug0" src="https://user-images.githubusercontent.com/11605569/171071688-23bf82e8-6128-4daa-a3e5-0fb032da28ef.png">

![Uploading bug1.png…]()

Following is the log information complaining about driver

```
!SESSION 2022-05-17 12:05:53.560 -----------------------------------------------
eclipse.buildId=unknown
java.version=17
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_NZ
Framework arguments:  -keyring /Users/username/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/username/.eclipse_keyring

!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-05-17 12:05:54.627
!MESSAGE Unable to retrieve the bundle from the URI: bundleclass://com.dbeaver.ee.runtime.ui/com.dbeaver.ee.runtime.internal.ui.LicenseStartupAddon

!ENTRY org.jkiss.dbeaver.model 4 0 2022-05-17 12:06:31.683
!MESSAGE Error creating driver 'Apache Ignite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.ignite.IgniteJdbcThinDriver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-05-17 12:06:31.683
!MESSAGE Error creating driver 'Apache Ignite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.ignite.IgniteJdbcThinDriver'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-05-17 12:06:31.683
!MESSAGE ExceptionInInitializerError
!STACK 0
java.lang.ExceptionInInitializerError
	at org.apache.ignite.internal.util.IgniteUtils.<clinit>(IgniteUtils.java:878)
	at org.apache.ignite.lang.IgniteProductVersion.fromString(IgniteProductVersion.java:312)
	at org.apache.ignite.internal.IgniteVersionUtils.<clinit>(IgniteVersionUtils.java:94)
	at org.apache.ignite.IgniteJdbcThinDriver.<clinit>(IgniteJdbcThinDriver.java:140)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1121)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1059)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:687)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:124)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer.address field is unavailable.
	at org.apache.ignite.internal.util.GridUnsafe$2.run(GridUnsafe.java:1570)
	at org.apache.ignite.internal.util.GridUnsafe$2.run(GridUnsafe.java:1557)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.apache.ignite.internal.util.GridUnsafe.bufferAddressOffset(GridUnsafe.java:1557)
	at org.apache.ignite.internal.util.GridUnsafe.<clinit>(GridUnsafe.java:109)
	... 25 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @7ef0519f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at org.apache.ignite.internal.util.GridUnsafe$2.run(GridUnsafe.java:1562)
	... 29 more

```

Interestingly, the java here shows the java.version = 17 and it comes from Eclipse Adoption. But when I go to terminal `java --version`, it shows openjdk `11.0.15 2022-04-19 LTS`  which is assumed to use since the ignite uses java 11. Meanwhile, wondering whether a downloaded community beaver is kinda of bounded to a computer? Since when I uninstall the DBeaver in /Applications and redownload the community version and install, it is surprising that it does not attempt to download driver and the driver settings the same as the uninstalled one, and it throws the error immediately.

_Originally posted by @yanxg in https://github.com/dbeaver/dbeaver/discussions/15211#discussioncomment-2763693_

**Comment by E1izabeth** [comment]
@yanxg does this issue still actual for the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual, please let me know and provide additional information.
