### ISSUE TITLE
DB2: procedure auto-completion is broken

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#16643]
```
java.lang.ClassCastException: class org.jkiss.dbeaver.model.impl.struct.RelationalObjectType cannot be cast to class org.jkiss.dbeaver.ext.db2.editors.DB2ObjectType (org.jkiss.dbeaver.model.impl.struct.RelationalObjectType is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @59036c7b; org.jkiss.dbeaver.ext.db2.editors.DB2ObjectType is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @62f91c59)
	at org.jkiss.dbeaver.ext.db2.editors.DB2StructureAssistant.findObjectsByMask(DB2StructureAssistant.java:112)
	at org.jkiss.dbeaver.ext.db2.editors.DB2StructureAssistant.findObjectsByMask(DB2StructureAssistant.java:49)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromAssistant(SQLCompletionAnalyzer.java:1207)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProceduresProposals(SQLCompletionAnalyzer.java:488)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:313)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:101)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:85)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:64)
```

**Comment by uslss** [comment]
verified
