### ISSUE TITLE
databases not visible after upgrade to 22.0.5

### ISSUE THREAD

**Issue by bvl-lc** [dbeaver/dbeaver#16657]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version 22.0.5
- Additional extensions

#### Connection specification:
- Database name and version: SQL Server in docker image on local VM
- Driver name: standard SQL Server driver in DBeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
After upgrading to 22.0.5 the databases were not visible anymore. I could connect to the SQL server, but no databases were visible anymore.
After re-installing 22.0.4 all was ok again!

**Comment by LonwoLonwo** [comment]
Can you please check the error log? https://github.com/dbeaver/dbeaver/wiki/Log-files

Also, what connection view do you have?

![2022-06-01 10_54_57-](https://user-images.githubusercontent.com/45152336/171355832-9a73052d-340b-49b5-858d-86d5ba2af074.png)

**Comment by bvl-lc** [comment]
I'm sorry, but I installed the previous version again so I lost these logs.
The connection view is Custom and then all checkboxes are unchecked. I never changed this, so it is all default...

**Comment by LonwoLonwo** [comment]
I can't reproduce your issue on DBeaver 22.0.5

Maybe reinstalling of DBeaver will help in your case.
Or [Reset Workspace](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace) can help

**Comment by bvl-lc** [comment]
[dbeaver-22.0.5.log](https://github.com/dbeaver/dbeaver/files/8812817/dbeaver-22.0.5.log)
I tried to upgrade again with the same result. In attachment the logs.

I will now try your other advice (reset workspace)...
1) I don't have a workspace.xmi file
2) had to remove the complete .metadata file, but nothing changes. The Databases don't show up (see other attachment).
![Capture](https://user-images.githubusercontent.com/105451305/171372715-94576d82-37de-4b51-9cf5-855709c961b6.JPG)
 
Bottomline, I have to go back to previous version! (and the only option I have is to close this issue even though it is NOT solved).

**Comment by LonwoLonwo** [comment]
Hm, I see.

```
!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-01 08:29:25.900
!MESSAGE Operation failed. Retry count remains = 1
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-01 08:29:25.900
!MESSAGE SQL Error [08S01]: SQL Server did not return a response. The connection has been closed.
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-06-01 08:29:25.900
!MESSAGE SQL Server did not return a response. The connection has been closed.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2998)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2987)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6453)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7610)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:598)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.getDatabases(SQLServerDataSource.java:390)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:835)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:501)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:835)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:394)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:369)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:281)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:188)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

But do not understand yet.

**Comment by LonwoLonwo** [comment]
Can you please check your Query Manager? https://github.com/dbeaver/dbeaver/wiki/Query-Manager
With enabled Properties.
Maybe something strange about database loading you can find there?

**Comment by bvl-lc** [comment]
Jun-01 15:03:00	SQL / Meta	SELECT DISTINCT s.*,ep.value as description FROM master.sys.schemas s
LEFT OUTER JOIN master.sys.extended_properties ep ON ep.class=3 AND ep.major_id=s.schema_id AND ep.minor_id=0 AND ep.name='MS_Description'
INNER JOIN master.sys.all_objects o ON s.schema_id=o.schema_id	37	3	Success	master	Metadata


Seems all normal to me...

**Comment by bvl-lc** [comment]
I guess it doesn't make any difference if I am using the Community Edition...

**Comment by LonwoLonwo** [comment]
Ok. Maybe DBeaver 22.1.0 release will help. We will be waiting for it.

**Comment by bvl-lc** [comment]
Unfortunately the same issue after upgrade to 22.1.0.

**Comment by LonwoLonwo** [comment]
Ok. Can you please first clear you log and then try to open your SQL Server databases list in DBeaver? And then provide me log again. It's too many different errors in your log right now.

**Comment by bvl-lc** [comment]
[dbeaver-debug-22.1.0.log](https://github.com/dbeaver/dbeaver/files/8862812/dbeaver-debug-22.1.0.log)

Don't see any error, but none of the databases is displayed!

**Comment by LonwoLonwo** [comment]
Strange.
Ok.
Is this issue occurs in all your SQL Server connections? I see few connections in your screen.
Does "Database" tab has arrow in the left (like Security, or Administer tabs) after connection opening or arrow disappears after clicking on it?

**Comment by bvl-lc** [comment]
Once you click the arrow, it disappears.

It seems to be only to this database (which is a SQL Server db on a docker container on my VM), meaning that for the SQL Server db I have connected besides it, which is on Azure, it seems to work... no clue what is the difference though...

**Comment by Destrolaric** [comment]
@bvl-lc Hi, can you tell me the names of the databases? It may be possible they were hidden as system ones due to https://github.com/dbeaver/dbeaver/commit/78ba81ef0695bf06380265e5eb36152f11451a61

**Comment by bvl-lc** [comment]
![db-screenshot](https://user-images.githubusercontent.com/105451305/174240526-3ddda42b-a331-49e9-b390-13fbbaa28f98.JPG)

Indeed, the databases I expected to see (that I see in previous versions) are "master", "model" and "tempdb"...

On the other hand, changing the database name is not helping making it possible to view the databases, nor does checking the "Show all schemas"... Bottomline is that I will not be able to use the new version of DBeaver anymore...

Thx

**Comment by Destrolaric** [comment]
@bvl-lc you can make them visible by ticking "Show system objects" in connection view

**Comment by bvl-lc** [comment]
Yes! that works! Thanks, George!
