### ISSUE TITLE
Full DDL can't be shown for a PostgreSQL schema containing earthdistance extension

### ISSUE THREAD

**Issue by RohanHart** [dbeaver/dbeaver#16655]
#### System information: 
- Operating system (distribution) and version: NixOS 22.05
- DBeaver version: 22.0.5
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 14.3
- Driver name: PostgreSQL JDBC Driver [42.2.5]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

After installing the earthdistance and cube extensions into a schema the full DDL for that schema can no longer be shown due to a SQL query exception.

#### Steps to reproduce, if exist:

1. As the db superuser: `CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public CASCADE;`
2. In DBeaver right click the public schema and select: Generate SQL -> DDL
3. Tick "Show full DDL"

#### Include any warning/errors/backtraces from the logs

```
ERROR: more than one row returned by a subquery used as an expression
org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:665)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getConstraint(PostgreDataType.java:492)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getObjectDefinitionText(PostgreDataType.java:650)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getObjectDefinitionText(PostgreSchema.java:518)
	at org.jkiss.dbeaver.model.sql.generator.SQLGeneratorDDL.generateSQL(SQLGeneratorDDL.java:81)
	at org.jkiss.dbeaver.model.sql.generator.SQLGeneratorDDL.generateSQL(SQLGeneratorDDL.java:1)
	at org.jkiss.dbeaver.model.sql.generator.SQLGenerator.run(SQLGenerator.java:176)
	at org.jkiss.dbeaver.model.sql.generator.SQLGeneratorDDL.run(SQLGeneratorDDL.java:57)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$17(UIUtils.java:1740)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$7(WorkbenchWindow.java:2345)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2343)
	at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1117)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$27(ProgressManager.java:996)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:6012)
	at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:996)
	at org.jkiss.dbeaver.ui.UIUtils.runInUI(UIUtils.java:1739)
	at org.jkiss.dbeaver.ui.UIUtils.runInUI(UIUtils.java:1752)
	at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorDialog$7.widgetSelected(SQLGeneratorDialog.java:215)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorContributor$2.run(SQLGeneratorContributor.java:180)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by LonwoLonwo** [comment]
Yes, I see. The problem is with the "earth" data type. We thought that data types can have only one constraint, but the "earth" data type has 3 constraints.

Thanks for the report @RohanHart
