### ISSUE TITLE
Update the Athena JDBC Driver to version 2.0.30

### ISSUE THREAD

**Issue by jasraja** [dbeaver/dbeaver#16663]
I have tried updating the Athena JDBC Driver in DBeaver, to version 2.0.30 however the connection could not be established as it does not accept the template settings of region in the JDBC String.

The present JDBC driver for Athena that comes with the default installation of DBeaver is SimbaAthena version 2.0.25, which was released in Nov' 2021. There has been class name changes in the JDBC driver since then.

It will be great if we can have the default version of Simba Athena JDBC Driver updated to the latest 2.0.30 which has been released in May' 2022. The links to the Official version of JDBC driver with SDK and without SDK are available on the webpage - [Using Athena with JDBC Driver](https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html)

**Comment by emironovDB** [comment]
Hello @jasraja,

Thanks for the suggestion

**Comment by jasraja** [comment]
Hello @emironovDB and @LonwoLonwo 

Thanks for considering this case and taking it up. Would just like to add that the current version of Athena JDBC driver is 2.0.32 which was updated in early August https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.32.1000/docs/release-notes.txt

**Comment by LonwoLonwo** [comment]
Thanks for the clarification @jasraja

**Comment by LonwoLonwo** [comment]
Hello @jasraja 

Can you please check your Athena connection with this driver? https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.32.1000/AthenaJDBC42.jar

Is it working fine?

**Comment by jasraja** [comment]
> Hello @jasraja
> 
> Can you please check your Athena connection with this driver? https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.32.1000/AthenaJDBC42.jar
> 
> Is it working fine?

Sure @LonwoLonwo , I will check and let you know. Pls allow me time till tomorrow as I am travelling atm.

Regards,

**Comment by LonwoLonwo** [comment]
Thanks @jasraja

**Comment by jasraja** [comment]
Hi @LonwoLonwo , 

I have checked the Athena connection with the new driver (  https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.32.1000/AthenaJDBC42.jar ) and it is working fine with the last milestone release - 22.2.1 on Windows 10.

Thanks a lot!

Regards,

**Comment by LonwoLonwo** [comment]
Thanks for your answer @jasraja

**Comment by jasraja** [comment]
Hello @LonwoLonwo,

Thanks for making and pushing the changes.

Just came to found out that Athena driver has been further updated to 2.0.**33** version.

The changelog/release notes for the newly released driver is available at https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.33.1000/docs/release-notes.txt

Seems like the direct link for driver jar file is not updated/uploaded however the master zip file which contains the .jar files for JDBC 4.1 and 4.2 and includes the AWS SDK.
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.33.1000/SimbaAthenaJDBC-2.0.33.1000.zip

I have tested checked the Athena connection with the latest jar - AthenaJDBC42-2.0.33.jar available inside the subfolder of the above zip file, and it is working fine with DBeaver. 

Also noticed that propertiesURL parameter of the driver in the code is set to older version i.e. https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.25.1001/doc/Simba+Athena+JDBC+Connector+Install+and+Configuration+Guide.pdf

which can be now updated to 
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.33.1000/docs/Simba+Amazon+Athena+JDBC+Connector+Install+and+Configuration+Guide.pdf

OR updated to

https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.32.1000/docs/Simba+Amazon+Athena+JDBC+Connector+Install+and+Configuration+Guide.pdf

Both the Guide links are working.

It will be great if we can update the driver to the latest available version 2.0.33

Thanks and Regards,

**Comment by LonwoLonwo** [comment]
Hello @jasraja 

Thanks for your suggestion. But we can't change driver version every release. For this reason you can do it manually as a workaround. 

You can create ticket about another driver update. And it will be added in the end of our development queue.

**Comment by jasraja** [comment]
Thanks @LonwoLonwo for your revert.

I suggested since the release was due early next week.

Regards,

**Comment by johanjvrens** [comment]
Hi I get the following error on the new version of DBeaver([DBeaver 22.2.2](https://dbeaver.io/2022/10/10/dbeaver-22-2-2/)
October 10th, 2022) and after being forced to download the new driver (Athena: driver version updated to 2.0.30):
`org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [HY000]: Error message not found: ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.messages, locale en_ZA
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3710)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Error message not found: ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.messages, locale en_ZA
	at com.simba.athena.athena.api.AJClient.checkAndThrowException(Unknown Source)
	at com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.BaseStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3710)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
Caused by: com.simba.athena.support.exceptions.GeneralException: Error message not found: ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.messages, locale en_ZA
	... 20 more
Caused by: com.simba.athena.amazonaws.services.athena.model.InvalidRequestException: line 19:5: mismatched input 'AS'. Expecting: ')', ',' (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 63839934-0442-4410-9d01-f8b7f381f8a2; Proxy: null)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.doInvoke(AmazonAthenaClient.java:2377)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2344)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2333)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.executeStartQueryExecution(AmazonAthenaClient.java:1917)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.startQueryExecution(AmazonAthenaClient.java:1886)
	at com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.BaseStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3710)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by LonwoLonwo** [comment]
Hello @johanjvrens 
And you can not connect?

**Comment by johanjvrens** [comment]
Hi, @LonwoLonwo I can make the connection, but the same error has been thrown for any syntax or missing value or anything wrong in the SQL I'm trying to run so debugging is really hard.

**Comment by johanjvrens** [comment]
I fixed this by replacing the driver with my manually downloaded AthenaJDBC42-2.0.33.jar driver and this seems to give the same error feedback that I'm used to. Think this is the important part of the error message above with the old driver: `Caused by: java.sql.SQLException: Error message not found: ATHENA_CLIENT_ERROR. ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.message`

**Comment by dm11111** [comment]
Hi @johanjvrens - I'm suffering some the same issue as you and have tried to update to AthenaJDBC42-2.0.33.jar so that I can get useful descriptive error mesages back.  However I have not been as successful as you.  

If have tried both the `com.simba.athena.jdbc.driver` and `com.simba.athena.jdbc42.driver` class names but both give an `"Unexpected driver error occurred while connecting to the database com/amazonaws/auth/AWSCredentialsProvider com/amazonaws/auth/AWSCredentialsProvider com/amazonaws/auth/AWSCredentialsProvider"` error.  

Did you get this also and find a work around?  What URL Template are you using?

**Comment by johanjvrens** [comment]
Hi @dm11111  - Open Driver Manager under the Database -> Driver Manager Menu:
Select AWS -> Athena this wil open Edit Driver 'Athena' menu 
Then click on Add File and point to your AthenaJDBC42-2.0.33.jar file Then click on ok you can then resolve the class path and restart DBeaver This should work.

**Comment by b-gale** [comment]
Since upgrading to DBeaver 22.3.0 on 10/17/2022, it installed JDBC driver 'SimbaAthenaJDBC-2.0.32.1000/AthenaJDBC42.jar' which cannot display SQL errors as noted: 

SQL Error [HY000]: Error message not found: ATHENA_CLIENT_ERROR. Can't find bundle for base name com.simba.athena.athena.jdbc42.messages, locale en_US.

* Manually downloaded the latest AWS driver (with SDK): https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.34.1000/SimbaAthenaJDBC-2.0.34.1000.zip
* Unzip to a local location, eg: ~ /Drivers in my case

@johanjvrens instructions worked, will give the exact steps that worked for me.  Not sure if I needed a global classpath though, new to Java world.

DBeaver > Database > Driver Manager > AWS > Athena > Edit...
Edit Driver 'Athena' Dialog > Libraries > Add File > pick jar (~ /Drivers/SimbaAthenaJDBC42-2.0.34.1000/AthenaJDBC42-2.0.34.1000.jar)
Classpath > Global libraries > + > pick jar (~ /Drivers/SimbaAthenaJDBC42-2.0.34.1000/AthenaJDBC42-2.0.34.1000.jar) > Apply

Restart DBeaver

Syntax errors are now working:

SQL Error [100071] [HY000]: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. line 1:1: mismatched input '#'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'PREPARE', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'UNLOAD', 'UPDATE', 'USE', <query> [Execution ID not available]

**Comment by LonwoLonwo** [comment]
Athena driver upgraded in this ticket https://github.com/dbeaver/dbeaver/issues/18090
Fix will be available [here](https://dbeaver.io/) on 2022-12-26 in DBeaver 22.3.1
