### ISSUE TITLE
Can't switch to spatial view or open Value panel with spatial view

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#16759]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 22,1,0

#### Connection specification:
- Database name and version PostgreSQL, oracle 

#### Describe the problem you're observing:
Error appears when trying to open Spatial view
#### Steps to reproduce, if exist:
![dbeaver_jaP9dxwNjn](https://user-images.githubusercontent.com/31996417/172802830-5a0b5c37-c507-47c9-9158-cfb00b880771.gif)

#### Include any warning/errors/backtraces from the logs
Error on spatial View opening:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -clearPersistedState
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/ -clearPersistedState

org.jkiss.dbeaver.model
Error
Thu Jun 09 10:33:07 CEST 2022
NullPointerException

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.gis.panel.SelectTilesAction.getActionText(SelectTilesAction.java:44)
	at org.jkiss.dbeaver.ui.gis.panel.SelectTilesAction.<init>(SelectTilesAction.java:38)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.updateToolbar(GISLeafletViewer.java:549)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.reloadGeometryData(GISLeafletViewer.java:274)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.refresh(GISLeafletViewer.java:231)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.preferenceChange(GISLeafletViewer.java:239)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:37)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.setValue(BundlePreferenceStore.java:255)
	at org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry.setDefaultLeafletTilesNonSynchronized(GeometryViewerRegistry.java:232)
	at org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry.autoAssignDefaultLeafletTiles(GeometryViewerRegistry.java:101)
	at org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry.<init>(GeometryViewerRegistry.java:93)
	at org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry.<clinit>(GeometryViewerRegistry.java:44)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.lambda$1(GISLeafletViewer.java:394)
	at org.jkiss.dbeaver.utils.GeneralUtils.replaceVariables(GeneralUtils.java:490)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.generateViewScript(GISLeafletViewer.java:375)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.reloadGeometryData(GISLeafletViewer.java:266)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.setGeometryData(GISLeafletViewer.java:243)
	at org.jkiss.dbeaver.ui.gis.presentation.GeometryPresentation.refreshData(GeometryPresentation.java:150)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.switchPresentation(ResultSetViewer.java:1053)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$3.widgetSelected(ResultSetViewer.java:828)
	at org.jkiss.dbeaver.ui.controls.VerticalButton.lambda$5(VerticalButton.java:297)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1087)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1072)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:775)
	at org.jkiss.dbeaver.ui.controls.VerticalButton.runAction(VerticalButton.java:134)
	at org.jkiss.dbeaver.ui.controls.VerticalButton$2.mouseUp(VerticalButton.java:110)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:270)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```
Error on value panel opening:
```
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -clearPersistedState
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/ -clearPersistedState

org.jkiss.dbeaver.model
Error
Thu Jun 09 10:33:14 CEST 2022
Could not initialize class org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry

java.lang.NoClassDefFoundError: Could not initialize class org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.setDefaultViewer(GISPanelEditor.java:198)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.<init>(GISPanelEditor.java:57)
	at org.jkiss.dbeaver.ui.gis.GeometryValueManager.createEditor(GeometryValueManager.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:235)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:210)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$1(ValueViewerPanel.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:238)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$2(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:226)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1087)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1072)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:775)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseDown(LightGrid.java:3231)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid$1.mouseDown(LightGrid.java:2930)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:270)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

**Comment by KoalaGeo** [comment]
I'm getting the same issue 
Running on Win10
Connected to Postgres + PostGIS 3.2.1

First time I try I get:
![image](https://user-images.githubusercontent.com/33657876/174114289-7c9cee21-60b1-4920-a405-15dc81d17791.png)

Subsequent tries = 
```
Can't switch presentation

Reason:
Could not initialize class org.jkiss.dbeaver.ui.gis.registry.GeometryViewerRegistry
```

**Comment by luispoliveira** [comment]
Getting the same issue.
Running on macOS Monterey
DBeaver version: 22.1.0

![Captura de ecrã 2022-06-21, às 13 15 59](https://user-images.githubusercontent.com/25667635/174796964-f93ed84c-cd2b-4469-b4e6-507ec3b7f7c8.png)
