### ISSUE TITLE
Not able to copy from dbeaver to gnome text editor (and vice versa)

### ISSUE THREAD

**Issue by SimoneD89** [dbeaver/dbeaver#16766]
#### System information: 
- Operating system: Linux 5.17.6-300.fc36.x86_64 (Fedora 36, gnome session, Wayland)
- DBeaver version: dbeaver-ce.x86_64 22.1.0
- Gnome text editor: gnome-text-editor.x86_6 42.1

Update: the bug still exists in dbeaver-ce 22.2.3 and gnome-text-editor 43.1

#### Describe the problem you're observing:
I'm not able to copy any text from dbeaver (sql console, tables, ...) to gnome text editor. Vice versa I'm not able to copy any text from gnome text editor to dbeaver (e.g. into the sql console). In gnome text editor the paste option is also grayed out in the context menu. More details can be found in the parallel [gtk bug report](https://gitlab.gnome.org/GNOME/gtk/-/issues/4974).

#### Steps to reproduce, if exist:
- open dbeaver and copy a query from sql console
- paste the text in gnome text editor (doesn't work)

**Comment by bartelemi** [comment]
I think it might be a regression of https://github.com/dbeaver/dbeaver/issues/8129.
Myself and some other users seem to have the same problem with clipboard no working on Arch Linux running Wayland.

**Comment by NickLion** [comment]
I'm using KDE — KWin wayland. Same problems with copy-paste in dbeaver. As I understand correctly, dbeaver (or Java) supports only UTF8_STRING, but not text/plain clipboard type. After coping from dbeaver:

```
# wl-paste -l
UTF8_STRING
STRING
SAVE_TARGETS
```

After coping from KDE apps:

```
# wl-paste -l
text/plain
text/plain;charset=utf-8
```

As a workaround, it's possible to use `wl-copy "$(wl-paste)"` (or longer variant `wl-copy "$(wl-paste --type UTF8_STRING || wl-paste --type text/plain)"` when rtf is copied from dbeaver).

**Comment by michal-bartak** [comment]
With recent versions of DBeaver I lost the possibility to copy-paste between DBEaver and Meld or even gedit.
But copy&paste still works while copying from DBeaver to Skype or web page (Confluence).

The strange thing that my colleagues running the same OS (Fedora/Wayland) with the same versions of DBeaver and Meld can do copy without problems. Possibly I have my Fedora more up-to-date.

**Comment by NickLion** [comment]
It seems, for now simplest workaround is to run it under XWayland: `env GDK_BACKEND=x11 /path/to/dbeaver`

**Comment by michal-bartak** [comment]
Thank you. It's indeed a working workaround. I didn't know that Wayland affects a clipboard.  Till now I thought the consequence was an inability to share the application window for video calls.

**Comment by ghost** [comment]
On the Fedora 37 Workstation operating system, the problem is reproduced. The temporary solution `env GDK_BACKEND=x11 /path/to/dbeaver` is currently valid.

**Comment by andreas-hartmann** [comment]
When I try to run that workaround under KDE Plasma/Wayland I get this stack trace/crash:
`sudo flatpak override --env=GDK_BACKEND=x11 run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity io.dbeaver.DBeaverCommunity`

`flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity

(process:20): Gtk-WARNING **: 21:29:14.127: Locale not supported by C library.
        Using the fallback 'C' locale.
Dbeaver: Cannot open display: 
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.600.v20221024-2137]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.13.200.v20221102-1024]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.20.0.v20221027-2208]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 23.0.0.202303040621]
2023-03-06 21:29:15.553 - DBeaver 23.0.0.202303040621 is starting
2023-03-06 21:29:15.554 - OS: Linux 6.2.2-zen1-1-zen (amd64)
2023-03-06 21:29:15.554 - Java version: 11.0.18 by Flathub (64bit)
2023-03-06 21:29:15.554 - Install path: '/app/dbeaver'
2023-03-06 21:29:15.554 - Instance path: 'file:/home/andreas/.local/share/DBeaverData/workspace6/'
2023-03-06 21:29:15.554 - Memory available 64Mb/1024Mb
2023-03-06 21:29:15.566 - Create display
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4944)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
        at org.eclipse.swt.widgets.Display.create(Display.java:1123)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:632)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:623)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:473)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Error updating splash shell
2023-03-06 21:29:15.598 - Initializing DBeaver 23.0.0
2023-03-06 21:29:15.599 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621
2023-03-06 21:29:15.599 - Initialize desktop platform...
2023-03-06 21:29:15.799 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> Start Core Resource Management [org.eclipse.core.resources 3.18.100.v20221025-2047]
> Start Team Support Core [org.eclipse.team.core 3.9.600.v20220902-2219]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.101.202303040621]
2023-03-06 21:29:16.063 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
2023-03-06 21:29:16.088 - Platform initialized (489ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.101.202303040621]
2023-03-06 21:29:16.098 - Starting RMI server at 29697
2023-03-06 21:29:16.143 - Run workbench
2023-03-06 21:29:16.143 - Create display

(java:20): Gdk-CRITICAL **: 21:29:16.143: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed
2023-03-06 21:29:16.143 - Internal error in workbench lifecycle
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4944)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
        at org.eclipse.swt.widgets.Display.create(Display.java:1123)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:632)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:623)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:298)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
2023-03-06 21:29:16.145 - DBeaver is stopping
2023-03-06 21:29:16.150 - Stop RMI server
2023-03-06 21:29:16.152 - RMI controller has been stopped
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.116.202303040621]
2023-03-06 21:29:16.206 - DBeaver shutdown completed
2023-03-06 21:29:16.251 - Shutdown desktop platform...
java.lang.ExceptionInInitializerError
        at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadDriver(DataSourceProviderDescriptor.java:657)
        at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadExtraConfig(DataSourceProviderDescriptor.java:158)
        at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.loadExtensions(DataSourceProviderRegistry.java:167)
        at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.getInstance(DataSourceProviderRegistry.java:63)
        at org.jkiss.dbeaver.core.DesktopPlatform.dispose(DesktopPlatform.java:216)
        at org.jkiss.dbeaver.core.DBeaverActivator.shutdownCore(DBeaverActivator.java:114)
        at org.jkiss.dbeaver.core.DBeaverActivator.stop(DBeaverActivator.java:78)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
        at org.eclipse.osgi.container.Module.doStop(Module.java:660)
        at org.eclipse.osgi.container.Module.stop(Module.java:521)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
        at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
        at org.eclipse.osgi.container.Module.doStop(Module.java:660)
        at org.eclipse.osgi.container.Module.stop(Module.java:521)
        at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getCustomDriversHome(DriverDescriptor.java:1744)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.<clinit>(DriverDescriptor.java:223)
        ... 24 more
Internal error after shutdown process:null

(process:2): Gtk-WARNING **: 21:29:16.774: Locale not supported by C library.
        Using the fallback 'C' locale.
Dbeaver: Cannot open display: 
Dbeaver:
An error has occurred. See the log file
`

**Comment by NickLion** [comment]
@andreas-hartmann  that's seems like some flatpak issue, it detects wayland and doesn't pass `$DISPLAY` variable.

I'm not using flatpak so, can't really help you, but check this:
https://www.reddit.com/r/gnome/comments/mdmqj9/comment/gsa52e5/?utm_source=share&utm_medium=web2x&context=3
maybe it'll work for you.

**Comment by andreas-hartmann** [comment]
> @andreas-hartmann  that's seems like some flatpak issue, it detects wayland and doesn't pass `$DISPLAY` variable.
> 
> I'm not using flatpak so, can't really help you, but check this:
> https://www.reddit.com/r/gnome/comments/mdmqj9/comment/gsa52e5/?utm_source=share&utm_medium=web2x&context=3
> maybe it'll work for you.

Thanks, combining the two works with the flatpak!

**Comment by michal-bartak** [comment]
Currently, I found the copy&paste between DBeaver (23.0.0) and Meld (see my report a few posts above) works again.
Thank you.

**Comment by NickLion** [comment]
For me (openSUSE Tumbleweed, KDE Wayland) it still doesn't work, so keep using XWayland workaroud.

**Comment by SimoneD89** [comment]
In my case with the last updates half of the problem is solved.
Copying a dbeaver SQL query and pasting into gnome-text-editor works
Copying something from gnome-text-editor and pasting into dbeaver SQL editor doesn't work

**System information**
* Operating system: Linux 6.1.13-200.fc37.x86_64 (Fedora 37, gnome session, Wayland)
* DBeaver version: dbeaver-ce.x86_64 23.0.0
* Gnome text editor: gnome-text-editor.x86_6 43.1.2

**Comment by mutenroid** [comment]
> In my case with the last updates half of the problem is solved. Copying a dbeaver SQL query and pasting into gnome-text-editor works Copying something from gnome-text-editor and pasting into dbeaver SQL editor doesn't work
> 
> **System information**
> 
> * Operating system: Linux 6.1.13-200.fc37.x86_64 (Fedora 37, gnome session, Wayland)
> * DBeaver version: dbeaver-ce.x86_64 23.0.0
> * Gnome text editor: gnome-text-editor.x86_6 43.1.2

Same problem with flatpak version and Fedora 37
Impossible to copy/paste from both directions, from dbeaver to external program or from external program to dbeaver

**Comment by DAKExDUCK** [comment]
6.3.2-arch1-1, Hyprland (wayland), kitty + zsh (oh-my-zsh)
Dbeaver 22.1.5.202208211008

Copy from any sources paste to terminal, copy this and then paste to Dbeaver works, but another ways don't work

**Comment by scippio** [comment]
> 6.3.2-arch1-1, Hyprland (wayland), kitty + zsh (oh-my-zsh) Dbeaver 22.1.5.202208211008
> 
> Copy from any sources paste to terminal, copy this and then paste to Dbeaver works, but another ways don't work

that works for me too.

**Comment by golgor** [comment]
> When I try to run that workaround under KDE Plasma/Wayland I get this stack trace/crash: `sudo flatpak override --env=GDK_BACKEND=x11 run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity io.dbeaver.DBeaverCommunity`
> 
> `flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity
> 
> (process:20): Gtk-WARNING **: 21:29:14.127: Locale not supported by C library. Using the fallback 'C' locale. Dbeaver: Cannot open display:
> 
> > Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621]
> > Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.4.600.v20221024-2137]
> > Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.13.200.v20221102-1024]
> > Start Eclipse IDE UI [org.eclipse.ui.ide 3.20.0.v20221027-2208]
> > Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 23.0.0.202303040621]
> > 2023-03-06 21:29:15.553 - DBeaver 23.0.0.202303040621 is starting
> > 2023-03-06 21:29:15.554 - OS: Linux 6.2.2-zen1-1-zen (amd64)
> > 2023-03-06 21:29:15.554 - Java version: 11.0.18 by Flathub (64bit)
> > 2023-03-06 21:29:15.554 - Install path: '/app/dbeaver'
> > 2023-03-06 21:29:15.554 - Instance path: 'file:/home/andreas/.local/share/DBeaverData/workspace6/'
> > 2023-03-06 21:29:15.554 - Memory available 64Mb/1024Mb
> > 2023-03-06 21:29:15.566 - Create display
> > org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
> > at org.eclipse.swt.SWT.error(SWT.java:4944)
> > at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
> > at org.eclipse.swt.widgets.Display.create(Display.java:1123)
> > at org.eclipse.swt.graphics.Device.(Device.java:167)
> > at org.eclipse.swt.widgets.Display.(Display.java:632)
> > at org.eclipse.swt.widgets.Display.(Display.java:623)
> > at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
> > at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
> > at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554)
> > at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:473)
> > at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
> > at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> > at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
> > at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> > at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
> > at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> > at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> > at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
> > at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
> > at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
> > Error updating splash shell
> > 2023-03-06 21:29:15.598 - Initializing DBeaver 23.0.0
> > 2023-03-06 21:29:15.599 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621
> > 2023-03-06 21:29:15.599 - Initialize desktop platform...
> > 2023-03-06 21:29:15.799 - BounceCastle bundle found. Use JCE provider BC
> > Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> > Start Core Resource Management [org.eclipse.core.resources 3.18.100.v20221025-2047]
> > Start Team Support Core [org.eclipse.team.core 3.9.600.v20220902-2219]
> > Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.101.202303040621]
> > 2023-03-06 21:29:16.063 - Initialize base platform...
> > Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
> > 2023-03-06 21:29:16.088 - Platform initialized (489ms)
> > Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.101.202303040621]
> > 2023-03-06 21:29:16.098 - Starting RMI server at 29697
> > 2023-03-06 21:29:16.143 - Run workbench
> > 2023-03-06 21:29:16.143 - Create display
> 
> (java:20): Gdk-CRITICAL **: 21:29:16.143: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed 2023-03-06 21:29:16.143 - Internal error in workbench lifecycle org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed] at org.eclipse.swt.SWT.error(SWT.java:4944) at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199) at org.eclipse.swt.widgets.Display.create(Display.java:1123) at org.eclipse.swt.graphics.Device.(Device.java:167) at org.eclipse.swt.widgets.Display.(Display.java:632) at org.eclipse.swt.widgets.Display.(Display.java:623) at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741) at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183) at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554) at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:298) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596) at org.eclipse.equinox.launcher.Main.run(Main.java:1467) at org.eclipse.equinox.launcher.Main.main(Main.java:1440) 2023-03-06 21:29:16.145 - DBeaver is stopping 2023-03-06 21:29:16.150 - Stop RMI server 2023-03-06 21:29:16.152 - RMI controller has been stopped
> 
> > Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.116.202303040621]
> > 2023-03-06 21:29:16.206 - DBeaver shutdown completed
> > 2023-03-06 21:29:16.251 - Shutdown desktop platform...
> > java.lang.ExceptionInInitializerError
> > at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadDriver(DataSourceProviderDescriptor.java:657)
> > at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadExtraConfig(DataSourceProviderDescriptor.java:158)
> > at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.loadExtensions(DataSourceProviderRegistry.java:167)
> > at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.getInstance(DataSourceProviderRegistry.java:63)
> > at org.jkiss.dbeaver.core.DesktopPlatform.dispose(DesktopPlatform.java:216)
> > at org.jkiss.dbeaver.core.DBeaverActivator.shutdownCore(DBeaverActivator.java:114)
> > at org.jkiss.dbeaver.core.DBeaverActivator.stop(DBeaverActivator.java:78)
> > at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
> > at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
> > at java.base/java.security.AccessController.doPrivileged(Native Method)
> > at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
> > at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
> > at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
> > at org.eclipse.osgi.container.Module.doStop(Module.java:660)
> > at org.eclipse.osgi.container.Module.stop(Module.java:521)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
> > at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
> > at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
> > at org.eclipse.osgi.container.Module.doStop(Module.java:660)
> > at org.eclipse.osgi.container.Module.stop(Module.java:521)
> > at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
> > at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
> > at java.base/java.lang.Thread.run(Thread.java:829)
> > Caused by: java.lang.NullPointerException
> > at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getCustomDriversHome(DriverDescriptor.java:1744)
> > at org.jkiss.dbeaver.registry.driver.DriverDescriptor.(DriverDescriptor.java:223)
> > ... 24 more
> > Internal error after shutdown process:null
> 
> (process:2): Gtk-WARNING **: 21:29:16.774: Locale not supported by C library. Using the fallback 'C' locale. Dbeaver: Cannot open display: Dbeaver: An error has occurred. See the log file `

I had the same issue in Fedora KDE/Plasma as you and it started working for me by just removing permissions to use Wayland.

I just unchecked the box in Settings->Applications->Flatpak Permission Settings->DBeaver Community. This would most likely also work if you are using Flatseal or running from terminal.
![image](https://github.com/dbeaver/dbeaver/assets/10995838/ad501777-d7f1-4929-a790-ef465572f081)

I guess I will keep it running on the X11-fallback for a while and give it a try a bit later to check the status of this issue. It is mighty annoying when you are working in several different systems.

**Comment by TheParthMaru** [comment]
Couple of workarounds are as follows:
1. Use vscode to open the text file and we can directly copy and paste to Dbeaver (Best method)
2. On terminal use, `cat filename`, copy the text and paste in Dbeaver.
3. Copy the text and paste in any browser and again copy and paste it in Dbeaver.

**Comment by albx79** [comment]
I've just bumped against this bug. The workaround is working, but is there a timeline for a proper fix? Thanks

**Comment by sandermarechal** [comment]
The X11/XWayland fallback has stopped working for me. DBeaver seems to freeze often when running under XWayland, at least visually. Clicking on an open tab does not change DBeaver itself, but it does update the application window title.
