### ISSUE TITLE
SSH tunnel requires username

### ISSUE THREAD

**Issue by mdb983** [dbeaver/dbeaver#16775]
#### System information: 
- Operating system (distribution) and version
- MacOS 11.6.6
- DBeaver version
- Version 22.1.0.202206051253
- Additional extensions

#### Connection specification:
- Database name and version
- MariaDB 10.3.34
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH tunnel
#### Describe the problem you're observing:
Unable to set up a connection to SQL server via SSH tunnel. The Config screen requires a user name and password. This should not be required with authentication mode set to Public Key, and private key selected 
#### Include any warning/errors/backtraces from the logs

2022-06-10 14:40:50.291 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:913)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: SSH user not specified
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.loadConfiguration(SSHImplementationAbstract.java:203)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:98)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:76)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:908)
        ... 4 more
2022-06-10 14:40:50.345 - SSH user not specified

**Comment by emironovDB** [comment]
Hi, @mdb983! 
Thanks for your request! 

Do you mean something like that: https://askubuntu.com/questions/692460/logging-to-remote-server-without-specifying-username/692463#692463 ? 
We need more details for understanding your vision.

**Comment by mdb983** [comment]
Not exactly, let me see if I can clarify:-

In a cloud environment such as AWS, you may have several EC2 instances and  RDS instance. RDS instances are, for security reasons, generally configured without public access. This results in the RDS only being accessible via an ECS instance. This is where ssh tunneling comes into play.

Again for security reasons, when configuring an EC2 instance, it's common to set ssh access only via encryption key. To fully accomplish this an additional step is to disable ssh password authentication, this protects against brute force intrusion, as your only means of access is via encryption key. I can't begin to tell you how many brute force ssh attempts I see every day, all using password.  

Below is a guide to setting up shh key-based authentication, should you need it. The relevant part, and the point of my initial issue, being turning off password authentication for ssh (step 4).

 https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-centos7

EDIT:

The issue I was having was that with ssh tunneling configuration would not proceed further without entering a user name and password. This should not be required, either based on a "disable password authentication" switch/checkbox  in the configuration screen. It should be sufficient to allow the host field to be configured as root@mydomain.com or root@192.168.100.1 and a selection field for the encryption key, or alternatively, you can separate the host address and require a username. Either way, there should be the ability to turn off password authentication for the ssh tunnel and not force the user to enter a password.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.
