### ISSUE TITLE
Maven Artifact not found in any available repository - Redshift

### ISSUE THREAD

**Issue by elliotsteene** [dbeaver/dbeaver#16806]
#### System information: 
- Windows 11
- 22.1
- Additional extensions

#### Connection specification:
- Redshift
- 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST'
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
DBeaver can no longer find Redshift driver. Previously could connect and then suddenly couldn't. 

#### Include any warning/errors/backtraces from the logs
!SESSION 2022-06-15 16:06:34.008 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2022-06-15 16:07:28.850
!MESSAGE Maven artifact 'redshift-jdbc42:com.amazon.redshift:RELEASE' not found in any available repository.

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:28.863
!MESSAGE Error resolving library 'redshift-jdbc42:com.amazon.redshift:LATEST' dependencies
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:28.863
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:335)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:241)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:29.120
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:29.120
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:335)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:241)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:34.263
!MESSAGE Error creating driver 'AWS / Redshift' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.amazon.redshift.jdbc42.Driver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:34.263
!MESSAGE Error creating driver 'AWS / Redshift' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.amazon.redshift.jdbc42.Driver'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:34.263
!MESSAGE com.amazon.redshift.jdbc42.Driver
!STACK 0
java.lang.ClassNotFoundException: com.amazon.redshift.jdbc42.Driver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1121)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1059)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:159)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:473)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.loadAvailableDatabases(PostgreDataSource.java:164)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:149)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:48.149
!MESSAGE Error resolving library 'redshift-jdbc42:com.amazon.redshift:LATEST' dependencies
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:48.149
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:335)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:241)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:48.504
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:07:48.504
!MESSAGE Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:335)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:241)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:124)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-15 16:08:15.083
!MESSAGE Error creating driver 'AWS / Redshift' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.amazon.redshift.jdbc42.Driver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-15 16:08:15.084
!MESSAGE Error creating driver 'AWS / Redshift' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.amazon.redshift.jdbc42.Driver'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-06-15 16:08:15.084
!MESSAGE com.amazon.redshift.jdbc42.Driver
!STACK 0
java.lang.ClassNotFoundException: com.amazon.redshift.jdbc42.Driver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1121)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1059)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:159)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:473)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:226)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:119)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:250)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @DanGeekyWorld 

Often this "Maven artifact 'maven:/redshift-jdbc42:com.amazon.redshift:LATEST' not found" issue occurs, then DBeaver can not download driver because of Internet or security problems.

In this case you can download drivers by your own from the wendor web-site:

![2022-06-17 00_31_07-DBeaver 22 1 0 - Playlist](https://user-images.githubusercontent.com/45152336/174169610-f314422e-8193-4ace-842c-64a6c5d117b9.png)

**Comment by nnickolaev** [comment]
Just run DBeaver as administrator. It will helps.
