### ISSUE TITLE
I failed to connect to laravel 8 / homestead under kubuntu 20

### ISSUE THREAD

**Issue by sergeynilov** [dbeaver/dbeaver#16815]
I have laravel 8 app under homestead with  Vagrant 2.2.6/virtualbox 6.1.32 under Kubuntu 20.
I want to connect with dbeaver 22.0.4 to this database
Here https://laravel.com/docs/8.x/homestead#ports
I found a hint that I need to use port 33060 instead of 3306 in MySQL connection.
I try to do it, but got error : Index 5 out of bounds for length 5
https://prnt.sc/KWtdoQPp-tOK
vagrant is running in this time...

What is wrong is my config options?

Thanks!

**Comment by LonwoLonwo** [comment]
Can you provide the full [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files) please?

**Comment by PetroGromovo** [comment]
```

!SESSION 2022-06-18 15:01:37.445 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /home/master/.local/share/DBeaverData/Landigator

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-18 15:01:47.429
!MESSAGE Index 5 out of bounds for length 5
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-18 15:01:47.429
!MESSAGE Index 5 out of bounds for length 5
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:369)
	at com.mysql.cj.protocol.a.NativeCapabilities.setInitialHandshakePacket(NativeCapabilities.java:68)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:501)
	at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:383)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1346)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:947)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:817)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:204)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:438)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:91)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

**Comment by LonwoLonwo** [comment]
What MySQL driver are you using? Now it looks like a driver limitation.

**Comment by PetroGromovo** [comment]
where I can check MySQL driver ?

**Comment by ShadelessFox** [comment]
Hello @PetroGromovo,

You can use the `Test Connection` button found in the connection configuration dialog.

**Comment by PetroGromovo** [comment]
I got : 

`MySQL Connector/J mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)
`
and : 
`MySQL 8.0.29-0ubuntu0.20.04.3`

**Comment by emironovDB** [comment]
Looks like a driver issue.

@PetroGromovo is your issue related to @sergeynilov's issue?

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If the issue is still actual for you, feel free to reopen it.
