### ISSUE TITLE
Scripts with select queries finish with an error

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16884]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.1.1

#### Steps to reproduce, if exist:
1. Create a script with a select query
2. Create a task to run this script
3. Run that task

**Expected:** Task is finished successfully
**Actual:** Task finished with error.

```java
2022-06-26 17:37:17.477 - Execute queries (1)
2022-06-26 17:37:17.479 - -----------------> Execute query
select * from actor a 
2022-06-26 17:37:17.692 - 	Fetch result set
2022-06-26 17:37:17.799 - -----------------> Time: 214ms
2022-06-26 17:37:17.799 - org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:231)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeSingleQuery(SQLScriptProcessor.java:193)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.runScript(SQLScriptProcessor.java:119)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.processScript(SQLScriptExecuteHandler.java:156)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:129)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.lambda$0(SQLScriptExecuteHandler.java:79)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:133)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeWithSettings(SQLScriptExecuteHandler.java:77)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeTask(SQLScriptExecuteHandler.java:66)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:128)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:95)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptDataReceiver.fetchStart(SQLScriptDataReceiver.java:47)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.fetchQueryData(SQLScriptProcessor.java:321)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeStatement(SQLScriptProcessor.java:244)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.lambda$0(SQLScriptProcessor.java:196)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	... 12 more
2022-06-26 17:37:17.802 - 	Set JDBC connection auto-commit true
2022-06-26 17:37:17.903 - org.jkiss.dbeaver.DBException: Error executing script '/General/Scripts/Script-11.sql'
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:137)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.lambda$0(SQLScriptExecuteHandler.java:79)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:133)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeWithSettings(SQLScriptExecuteHandler.java:77)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeTask(SQLScriptExecuteHandler.java:66)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:128)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:95)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Script execute failed
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.runScript(SQLScriptProcessor.java:168)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.processScript(SQLScriptExecuteHandler.java:156)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:129)
	... 8 more
Caused by: org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:231)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeSingleQuery(SQLScriptProcessor.java:193)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.runScript(SQLScriptProcessor.java:119)
	... 10 more
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptDataReceiver.fetchStart(SQLScriptDataReceiver.java:47)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.fetchQueryData(SQLScriptProcessor.java:321)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeStatement(SQLScriptProcessor.java:244)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.lambda$0(SQLScriptProcessor.java:196)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	... 12 more
2022-06-26 17:37:17.904 - SQL script execute completed
```

**Comment by serge-rider** [comment]
Fixed.
It was a side effect of #16335
