### ISSUE TITLE
Click explain plan button: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by ailibibi** [dbeaver/dbeaver#16892]
#### System information: 
- Operating system (distribution) and version：macOS Monterey 12.2.1
- DBeaver version: 22.1.1.202206261508
- Additional extensions：None

#### Connection specification:
- Database name and version：mysql 5.6.29-TDDL-5.4.10-16219368 
- Driver name: com.mysql.cj.jdbc.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

show warning whlie click explain plan button !
<img width="845" alt="image" src="https://user-images.githubusercontent.com/22117522/175913864-3d2a11c6-ce55-40e6-9ac2-d0394d2c96d8.png">

#### Steps to reproduce, if exist:

But local mysql(8.0.28) is fine.

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2022-06-27 17:54:58.948
!MESSAGE Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-06-27 17:54:58.949
!MESSAGE Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
!STACK 0
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:869)
        at com.google.gson.Gson.fromJson(Gson.java:963)
        at com.google.gson.Gson.fromJson(Gson.java:928)
        at com.google.gson.Gson.fromJson(Gson.java:877)
        at com.google.gson.Gson.fromJson(Gson.java:848)
        at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanJSON.<init>(MySQLPlanJSON.java:57)
        at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser.explain(MySQLPlanAnalyser.java:63)
        at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser.planQueryExecution(MySQLPlanAnalyser.java:85)
        at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:408)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
        at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:402)
        at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
Hello @Simon0910,

Can you please execute the following query and provide the results of execution?

```sql
EXPLAIN FORMAT=JSON <YOUR ORIGINAL QUERY HERE>

-- Example:
-- EXPLAIN FORMAT=JSON SELECT * FROM MyTable
```

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it with additional info

**Comment by ailibibi** [comment]
> Hello @Simon0910,
> 
> Can you please execute the following query and provide the results of execution?
> 
> ```sql
> EXPLAIN FORMAT=JSON <YOUR ORIGINAL QUERY HERE>
> 
> -- Example:
> -- EXPLAIN FORMAT=JSON SELECT * FROM MyTable
> ```

This execution is good, only click the small icon button will still popover, my version is: 22.1.3.202207240747, thank you

**Comment by baojiahui** [comment]
这个没解决呀
