### ISSUE TITLE
Installing Eclipse's DBeaver plugin doesn't find https://dbeaver.io/update/ce/latest/content.xml

### ISSUE THREAD

**Issue by regseb** [dbeaver/dbeaver#16975]
#### System information: 
- Operating system (distribution) and version: Windows 10 Entreprise
- DBeaver Eclipse plugin version: 22.0.5
- Eclipse version: 2022-06 (4.24.0)

#### Describe the problem you're observing:

Installing Eclipse's DBeaver plugin (from marketplace) doesn't work: file https://dbeaver.io/update/ce/latest/content.xml doesn't exist.

#### Steps to reproduce, if exist:

- On Eclipse, open _Help_ > _Eclipse Marketplace..._
- Search `dbeaver`
- _Install_ _DBeaver 22.0.5_
- _Confirm_ with only required features
- A popup opens with the error: _Unable to read repository at https://dbeaver.io/update/ce/latest/content.xml. Stream already closed_

#### Include any warning/errors/backtraces from the logs

```
eclipse.buildId=4.24.0.I20220607-0700
java.version=18.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.p2.transport.ecf
Error
Wed Jul 06 09:53:08 CEST 2022
Unable to read repository at https://dbeaver.io/update/ce/latest/content.xml.

org.apache.hc.core5.http.StreamClosedException: Stream already closed
	at org.apache.hc.core5.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:162)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:176)
	at java.base/java.io.Reader.read(Reader.java:250)
	at org.apache.hc.core5.http.io.entity.EntityUtils.toCharArrayBuffer(EntityUtils.java:178)
	at org.apache.hc.core5.http.io.entity.EntityUtils.toString(EntityUtils.java:221)
	at org.apache.hc.core5.http.io.entity.EntityUtils.toString(EntityUtils.java:361)
	at org.apache.hc.core5.http.io.entity.EntityUtils.toString(EntityUtils.java:341)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.createTunnelToTarget(ConnectExec.java:258)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:145)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:251)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by regseb** [comment]
The problem came from my company's proxy. After configuring the proxy correctly, the installation worked.
