### ISSUE TITLE
idea debug error, not found dev.properties

### ISSUE THREAD

**Issue by cnscottluo** [dbeaver/dbeaver#16997]
!SESSION 2022-07-07 13:27:51.771 -----------------------------------------------
eclipse.buildId=4.22.0.I20211124-1800
java.version=11.0.14.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en

!ENTRY org.eclipse.osgi 4 0 2022-07-07 13:27:52.118
!MESSAGE /Users/scottluo/eclipse-workspace/dbeaver-ce/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties (No such file or directory)
!STACK 0
java.io.FileNotFoundException: /Users/scottluo/eclipse-workspace/dbeaver-ce/eclipse/workspace/.metadata/.plugins/org.eclipse.pde.core/DBeaver.product/dev.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.eclipse.osgi.internal.location.LocationHelper.getStream(LocationHelper.java:94)
	at org.eclipse.osgi.internal.framework.EquinoxConfiguration.<init>(EquinoxConfiguration.java:589)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:99)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:53)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:46)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:315)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by flambchap** [comment]
Hi @cnscottluo. It seems like you need to adjust the path to dev.properties. Please find this file in your eclipse workspace, then open the Edit Configurations dialog in IDEA -> Alt + R -> Shift + Enter and adjust the value of the -dev flag.
