### ISSUE TITLE
Unable to open user interface preferences

### ISSUE THREAD

**Issue by ssttaarr** [dbeaver/dbeaver#16999]
* Fresh Eclipse 2022-06 (4.24.0) installation
* DBeaver feature 22.1.1.202206261508
* openjdk version "17.0.3" 2022-04-19 (bundled with Eclipse)
* Linux Mint 20.3 x86_64

All org.jkiss settings were removed from ${WORKSPACE}/.metadata/.plugins/ folder prior DBeaver installation.

Attempt to navigate to Preferences -> Database -> User Interface (or any settings below) results in `The currently displayed page contains invalid values` error message. The NPE is logged to the workspace ${WORKSPACE}/.metadata/.log:
```
!ENTRY org.eclipse.jface 4 2 2022-07-07 13:12:48.436
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Combo.setText(String)" because "this.clientTimezone" is null
        at org.jkiss.dbeaver.ui.preferences.PrefPageDatabaseUserInterface.performDefaults(PrefPageDatabaseUserInterface.java:197)
        at org.jkiss.dbeaver.ui.preferences.PrefPageDatabaseUserInterface.createPreferenceContent(PrefPageDatabaseUserInterface.java:179)
        at org.jkiss.dbeaver.ui.preferences.AbstractPrefPage.createContents(AbstractPrefPage.java:32)
        at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
        at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1433)
        at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1196)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
        at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1188)
```

**Comment by E1izabeth** [comment]
Connected to https://github.com/dbeaver/dbeaver/issues/16912

**Comment by MerlinYoda** [comment]
This bug has reappeared under Eclipse 2023-06 but only for the settings under Preferences -> Database -> User Interface. Expanding the User Interface tree first allows for access to the other sections under it. Any attempt to navigate away from the User Interface section is met with the same error message as originally posted

Issue needs to be reopened.

**Comment by E1izabeth** [comment]
@MerlinYoda thank you for letting us know. Please create a new issue.

**Comment by MerlinYoda** [comment]
Issue #20902 opened as a new issue for this error.
