### ISSUE TITLE
NPE on apply formatting settings

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17023]
1. Select text in SQL Editor
2. Open formatting settings
3. Change indent size

```
java.lang.NullPointerException
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.handlePreferenceStoreChanged(AbstractDecoratedTextEditor.java:848)
	at org.eclipse.ui.texteditor.AbstractTextEditor$PropertyChangeListener.propertyChange(AbstractTextEditor.java:717)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:325)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:322)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:576)
	at org.jkiss.dbeaver.ui.editors.sql.preferences.format.tokenized.SQLTokenizedFormatterConfigurationPage.saveSettings(SQLTokenizedFormatterConfigurationPage.java:140)
	at org.jkiss.dbeaver.ui.editors.sql.preferences.PrefPageSQLFormat.lambda$2(PrefPageSQLFormat.java:310)
	at org.jkiss.dbeaver.ui.editors.sql.preferences.format.tokenized.SQLTokenizedFormatterConfigurationPage$1.widgetSelected(SQLTokenizedFormatterConfigurationPage.java:53)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	...
```

**Comment by serge-rider** [comment]
Problem was caused by panel editors (text editors) which remained undisposed (old listeners were still listening for events while UI widgets were alread ydestroyed).
It also caused memory leaks in data editor.

Fixed.

**Comment by serge-rider** [comment]
Steps to reproduce:
- Open SQL editor and execute "select * from film"
- Open value panel and view string values in it (e.g. column description)
- Open preferences for SQL formatting and change indent size. Or change theme in Appearance or any other UI setting which affects text editors.
