### ISSUE TITLE
Authentication failed with Salesforce CDP

### ISSUE THREAD

**Issue by ManoharPamula** [dbeaver/dbeaver#17038]
Hi all Looking for help to resolve this issue, I am getting Authentication Failure Errors while connecting to Salesforce Sandbox via dbeaver.  I have OAuth Policies setup for this user with Certificate linked in Account Manager and IP Relaxation set as Relax IP Restrictions along with all required Application Permissions in Sandbox.  Error details are

!ENTRY org.jkiss.dbeaver.model 4 0 2022-07-10 14:00:59.530
!MESSAGE authentication failure
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-07-10 14:00:59.530
!MESSAGE authentication failure
!STACK 0
java.io.IOException: authentication failure
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:45)
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:36)
	at com.salesforce.cdp.queryservice.util.TokenHelper.un_pw_login(TokenHelper.java:269)
	at com.salesforce.cdp.queryservice.util.TokenHelper.retrieveTokenWithPasswordGrant(TokenHelper.java:112)
	at com.salesforce.cdp.queryservice.util.TokenHelper.getToken(TokenHelper.java:72)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.lambda$getTokenWithTenantUrl$2(QueryExecutor.java:182)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getTokenWithTenantUrl(QueryExecutor.java:181)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.executeQuery(QueryExecutor.java:92)
	at com.salesforce.cdp.queryservice.core.QueryServiceAbstractStatement.executeQuery(QueryServiceAbstractStatement.java:72)
	at com.salesforce.cdp.queryservice.core.QueryServicePreparedStatement.execute(QueryServicePreparedStatement.java:158)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.isValid(QueryServiceConnection.java:344)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.<init>(QueryServiceConnection.java:59)
	at com.salesforce.cdp.queryservice.QueryServiceDriver.connect(QueryServiceDriver.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:191)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:208)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
#

**Comment by LonwoLonwo** [comment]
Can be connected #16652

**Comment by emironovDB** [comment]
@Manosfdc 
Hi! 
Could you provide a screenshot with driver connection settings? 
And did you try connecting to SalesForce with another tool?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it.
