### ISSUE TITLE
NPE appears in case of VFK creation in ERD was cancelled

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#17052]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.2

#### Describe the problem you're observing:
NPE appears in case of VFK creation in ERD was cancelled
#### Steps to reproduce, if exist:
1. Connect two tables in ERD with VFK
2. Cancel VFK creation

![dbeaver_rkikbSpCYz](https://user-images.githubusercontent.com/31996417/178428902-8eb0265f-c5d2-4f44-bea1-a81f5c4dfc4b.gif)
```

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.jkiss.dbeaver.model
Error
Mon Jul 11 16:31:41 MSK 2022
NullPointerException
java.lang.NullPointerException
    at org.jkiss.dbeaver.erd.ui.command.AssociationCreateCommand.createAssociation(AssociationCreateCommand.java:190)
    at org.jkiss.dbeaver.erd.ui.command.AssociationCreateCommand.execute(AssociationCreateCommand.java:102)
    at org.eclipse.gef3.commands.CommandStack.execute(CommandStack.java:228)
    at org.eclipse.gef3.tools.AbstractTool.executeCommand(AbstractTool.java:427)
    at org.eclipse.gef3.tools.AbstractTool.executeCurrentCommand(AbstractTool.java:440)
    at org.eclipse.gef3.tools.AbstractConnectionCreationTool.handleCreateConnection(AbstractConnectionCreationTool.java:256)
    at org.eclipse.gef3.tools.ConnectionCreationTool.handleButtonDown(ConnectionCreationTool.java:77)
    at org.eclipse.gef3.tools.AbstractTool.mouseDown(AbstractTool.java:1093)
    at org.eclipse.gef3.EditDomain.mouseDown(EditDomain.java:245)
    at org.eclipse.gef3.ui.parts.DomainEventDispatcher.dispatchMousePressed(DomainEventDispatcher.java:348)
    at org.eclipse.draw2dl.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:523)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
    at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:270)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by uslss** [comment]
not reproducible anymore (22.3.0)
