### ISSUE TITLE
Can't read tables: null   ConcurrentModificationException   java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by gsthorat** [dbeaver/dbeaver#17175]
I am getting below error message when I open/refresh the connection.

```
Can't read tables: null
  ConcurrentModificationException
  java.util.ConcurrentModificationException
```

![image](https://user-images.githubusercontent.com/29622633/180963482-362173b8-b811-4adf-92e6-abf47419780f.png)

**Steps to Replicate:**
1. Open connect in Dbeaver
2. Now connect to same database using another database client. e.g sqldeveloper in my case
3. Do some modifications to database using sqldeveloper 
4. Now try to refresh the connection in Dbeaver 
5. You will get ConcurrentModificationException exception.

It was working fine earlier. I was able to use both the database clients parallely 

**Database**: Oracle 19c
**Os**: Windows
**Version**: 22.1.1.202206261508

**Comment by LonwoLonwo** [comment]
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by gsthorat** [comment]
Thanks @LonwoLonwo for quick turnaround on this.

I have attached [log.txt](https://github.com/dbeaver/dbeaver/files/9197135/log.txt) log file

**Comment by gsthorat** [comment]
**Update:**

I got the exact steps to replicate the above issue.

1. Create two connection pointing to same database but to different schema.
In my case, **TEST_SCHEMA1** and **TEST_SCHEMA2** are the two schema.

2. Now open/view data of the available table or perform any operation.
3. Now navigate to another connection 
4. Now right-click on the schema → **tables** option and select refresh option
5. You will see _Can't read tables: null_ error message

**Screenshot:**

![image](https://user-images.githubusercontent.com/29622633/182890955-60721a03-ecb8-4ebe-961a-4585bee51822.png)

Please let me know if you need any further information.

Thanks

**Comment by Destrolaric** [comment]
Thank for the information.

**Comment by E1izabeth** [comment]
Does it still reproducible on the latest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know.

**Comment by naknak987** [comment]
@E1izabeth I'm getting this error when I change the Tables filter while connected to a MariaDB 10.11 database server. Any help would be greatly appreciated. 

Database: MariaDB 10.11.9
DBeaver: 24.2.3.202410201725
OS: Ubuntu Linux 22.04 with Kernel 6.8.0-47-generic

Information from log:
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/redacted/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Sun Oct 20 09:31:15 EDT 2024
ConcurrentModificationException

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:81)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getTables(MySQLCatalog.java:338)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:1045)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1117)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:664)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:475)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:912)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:512)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:912)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:398)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:373)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:189)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Some additional information that is most likely related: this only seems to happen for large databases with many tables being accessed through a read-only database user. The database I'm experiencing the issue with has over 45,000 database tables. It also takes a long time to load the list of tables on the latest version of DBeaver, but version 23.2.5  did not have either problem. It would be great if you could make the program load the table list faster or have the option to disable whatever metadata it's loading while fetching the table listing. That might solve both problems.
