### ISSUE TITLE
running query exception

### ISSUE THREAD

**Issue by xcxcxz** [dbeaver/dbeaver#17211]
#### System information: 
- Operating system (distribution) and version : Mac os m1
- DBeaver version : 22.1.3
- Additional extensions : none

#### Connection specification:
- Database name and version : mysql
- Driver name : Default one it made me download
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
it throws exceptions like attach log when running this query.

```
SET @SEARCH_DATE := '20220301';
SET @STD_DATE_STR := DATE_FORMAT(@SEARCH_DATE, '%Y-%m-%d');

SELECT LST.AGENT_NO
			,LST.BID
			,''
      ,BIZ.BIZ_NAME
      ,IF(IFNULL(CUS.CUST_NAME, '') = '', '익명', CUS.CUST_NAME) CUST_NAME
      ,LST.USE_DATE
      ,LST.START_OLD_ADDRESS
      ,''
      ,CONCAT(LST.STOP1_OLD_ADDRESS
              ,IF(IFNULL(LST.STOP2_OLD_ADDRESS, '') <> '', CONCAT(' 외 '
															  ,IF(IFNULL(LST.STOP2_OLD_ADDRESS, '') <> '', 1, 0) + IF(IFNULL(LST.STOP3_OLD_ADDRESS, '') <> '', 1, 0)
                                                              ,'건')
													 , '')
             ) STOP_OLD_ADDRESS
       ,LST.DEST_OLD_ADDRESS
       ,''
       ,''
       ,''
       ,LST.UPDATED_DATE
       ,CONCAT(ROUND(CONVERT(LST.DISTANCE, SIGNED) / 1000, 1), 'km') DISTANCE
       ,LST.CALL_AMOUNT
       ,CONVERT(LST.CALL_AMOUNT * 0.1, SIGNED) VAT_AMOUNT
       ,CONVERT(LST.CALL_AMOUNT * 1.1, SIGNED) SUMMARY
       ,'법인후불'
       ,CUS.MDN
FROM   TB_KDTF_APP_CALL_LIST LST
      ,TB_APP_BRAND_CUSTOMER CUS
      ,TB_APP_BIZ_CONTRACT BIZ
WHERE  LST.STD_DATE >= @SEARCH_DATE
AND    LST.CALL_STATUS = '07'
AND    LST.BIZ_CALL_YN = 'Y'
AND    LST.STL_TYPE = '02'
AND    LST.IS_DELETE = 'N'
AND    CUS.BID = LST.BID
AND    CUS.UID = LST.UID
AND    CUS.IS_DELETE = 'N'
AND    BIZ.BID = LST.BID
AND    BIZ.STL_TYPE = '02'
AND    BIZ.BIZ_CODE = LST.BIZ_CODE
AND    BIZ.IS_DELETE = 'N'
ORDER BY LST.USE_DATE
;
```

#### Steps to reproduce, if exist:

It just happened when i run the query.
I restarted my mac, reinstalled, deleted everything in in the Library/DBeaverData, still happening with fresh install.

#### Include any warning/errors/backtraces from the logs

```
eclipse.buildId=unknown
java.version=17
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=ko_KR
Framework arguments:  -keyring /Users/zzosuke/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/zzosuke/.eclipse_keyring

org.jkiss.dbeaver.model
오류
Mon Aug 01 10:50:24 KST 2022
Event loop exception
```

```
eclipse.buildId=unknown
java.version=17
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=ko_KR
Framework arguments:  -keyring /Users/zzosuke/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/zzosuke/.eclipse_keyring

org.jkiss.dbeaver.model
오류
Mon Aug 01 10:51:16 KST 2022
Argument cannot be null

java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.graphics.GC.drawText(GC.java:1777)
	at org.eclipse.swt.graphics.GC.drawString(GC.java:1677)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumnRenderer.paint(GridColumnRenderer.java:147)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnsHeader(LightGrid.java:2637)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnHeader(LightGrid.java:2624)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintHeader(LightGrid.java:2593)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onPaint(LightGrid.java:2326)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4604)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1270)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Canvas.java:176)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:777)
	at org.eclipse.swt.widgets.Canvas.drawRect(Canvas.java:170)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6248)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5526)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5926)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1147)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2191)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1139)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2625)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2158)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6281)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2162)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2487)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6405)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5653)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5792)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3963)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

**Comment by LonwoLonwo** [comment]
Hello @xcxcxz 

Is this issue occurs only for provided query? Or not?
Maybe you can provide a more simple query example instead of this? I can't reproduce without all these tables from your query, which I do not have.

**Comment by xcxcxz** [comment]
Unfortunatly, Others are working well.
But after i run that provide query, other query also not works and 'cmd + enter' also not working...
It just change the line.

**Comment by LonwoLonwo** [comment]
SQL Editor result tab will not work after this kind of issue. Better to close the resultset and SQL Editor too.

Maybe you can test it in the new SQL Editor? Cut the query for our test? Or provide us please dependent objects DDLs.

**Comment by xcxcxz** [comment]
I tried in mysql workbench and it working well.
I give you DDLs.

```
-- KDTF.TB_KDTF_APP_CALL_LIST definition

CREATE TABLE `TB_KDTF_APP_CALL_LIST` (
  `CALL_ID` varchar(20) NOT NULL COMMENT '콜 ID',
  `BID` varchar(20) NOT NULL COMMENT '제휴사 ID',
  `SID` varchar(20) NOT NULL COMMENT '제휴사 매장 ID',
  `UID` varchar(100) NOT NULL COMMENT '사용자 ID',
  `MDN` varchar(20) DEFAULT NULL COMMENT '사용자 전화번호',
  `CALL_STATUS` varchar(2) NOT NULL DEFAULT '00' COMMENT '콜 상태\\n00 : 접수요청\\n01 : 접수중\\n02 : 접수완료\\n03 : 배차진행중\\n04 : 배차완료\\n05 : 기사이동중\\n06 : 운행중\\n07 : 운행완료\\n90 : 고객센터 취소\\n91 : 고객 취소',
  `CALL_TYPE` varchar(2) DEFAULT '01' COMMENT '호출 유형\\n01 : Call driver (대리기사 부르기)\\r\\n02 : Reservation (예약 호출)\\r\\n03 : Call other driver (대신 부르기)\\r\\n04 : Send only car (차만 보내기)\\r\\n05 : Call whole day worker (일일기사 신청)',
  `CALL_AMOUNT` int(11) DEFAULT '0' COMMENT '콜 총 비용',
  `AMC_COUNT` int(11) DEFAULT NULL COMMENT '모바일쿠폰 사용갯수',
  `TOTAL_AMC_AMOUNT` int(11) DEFAULT '0' COMMENT '모바일쿠폰 총 사용금액',
  `TRANSACTION_ID` varchar(30) DEFAULT NULL COMMENT '거래 트랜젝션 ID',
  `BIZ_CARD_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '법인카드여부',
  `CARD_TRANSACTION_ID` varchar(30) DEFAULT NULL COMMENT '카드 결제 트랜젝션 ID',
  `USE_MILEAGE_AMOUNT` int(11) DEFAULT '0' COMMENT '사용 마일리지',
  `PAYCOIN_AMOUNT` int(11) DEFAULT '0' COMMENT 'Paycoin 결제금액',
  `COUPON_CODE` varchar(30) DEFAULT NULL COMMENT '쿠폰 코드값',
  `COUPON_AMOUNT` int(11) NOT NULL DEFAULT '0',
  `APP_PAY_METHOD` varchar(2) DEFAULT NULL COMMENT '추가 결제수단',
  `ADD_PAY_AMOUNT` int(11) DEFAULT '0' COMMENT '추가 결제금액',
  `STANDARD_PRICE` int(11) NOT NULL DEFAULT '0',
  `START_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '출발지 주소',
  `START_LATITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '출발지 위도',
  `START_LONGTITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '출발지 경도',
  `START_OLD_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '출발지 구 주소',
  `START_SPOT_NAME` varchar(1000) DEFAULT NULL COMMENT '출발지 장소명',
  `STOP1_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 주소',
  `STOP1_LATITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '경유지 위도',
  `STOP1_LONGTITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '경유지 경도',
  `STOP1_OLD_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 구주소',
  `STOP1_SPOT_NAME` varchar(1000) DEFAULT NULL,
  `STOP2_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 주소',
  `STOP2_LATITUDE` decimal(16,10) DEFAULT NULL COMMENT '경유지 위도',
  `STOP2_LONGTITUDE` decimal(16,10) DEFAULT NULL COMMENT '경유지 경도',
  `STOP2_OLD_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 구주소',
  `STOP2_SPOT_NAME` varchar(1000) DEFAULT NULL,
  `STOP3_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 주소',
  `STOP3_LATITUDE` decimal(16,10) DEFAULT NULL COMMENT '경유지 위도',
  `STOP3_LONGTITUDE` decimal(16,10) DEFAULT NULL COMMENT '경유지 경도',
  `STOP3_OLD_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '경유지 구주소',
  `STOP3_SPOT_NAME` varchar(1000) DEFAULT NULL,
  `DEST_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '도착지 주소',
  `DEST_LATITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '목적지 위도',
  `DEST_LONGTITUDE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '목적지 경도',
  `DEST_OLD_ADDRESS` varchar(1000) DEFAULT NULL COMMENT '도착지 구 주소',
  `DEST_SPOT_NAME` varchar(1000) DEFAULT NULL COMMENT '도착지 장소명',
  `DISTANCE` decimal(16,10) DEFAULT '0.0000000000' COMMENT '직선거리(m)',
  `NEEDED_TIME` int(11) DEFAULT '0' COMMENT '소요시간(min)',
  `SEND_MSG` text,
  `DRIVER_NO` varchar(50) DEFAULT NULL COMMENT '대리기사 번호',
  `DRIVER_NAME` varchar(100) DEFAULT NULL COMMENT '대리기사 이름',
  `PG_CODE` varchar(10) DEFAULT NULL,
  `AGENT_NO` varchar(100) DEFAULT NULL COMMENT '대리운전 연동 시스템 Key',
  `BIZ_CALL_YN` varchar(1) DEFAULT 'N' COMMENT '법인 콜 여부',
  `BIZ_CODE` varchar(30) DEFAULT NULL COMMENT '법인 코드',
  `STL_TYPE` varchar(2) DEFAULT '01' COMMENT '정산 유형\\n01 : 선불\\n02 : 후불',
  `USE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '시작일시',
  `STD_DATE` varchar(8) DEFAULT NULL COMMENT '마감기준 일자',
  `STL_DATE` varchar(8) DEFAULT NULL COMMENT '정산 일자',
  `OUTER_CASH` int(11) NOT NULL DEFAULT '0',
  `USER_CASH` int(11) NOT NULL DEFAULT '0',
  `RECOMMENDER_CASH` int(11) NOT NULL DEFAULT '0',
  `CANCEL_YN` varchar(1) DEFAULT NULL COMMENT '취소 여부(Y/N)',
  `CANCEL_REASON` varchar(1000) DEFAULT '' COMMENT '취소 사유',
  `VIEW_YN` varchar(1) DEFAULT 'Y' COMMENT '노출여부',
  `NOTE` text COMMENT '메모',
  `IS_DELETE` varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `INSERTED_ID` varchar(20) DEFAULT NULL COMMENT '등록자 ID',
  `INSERTED_DATE` timestamp NULL DEFAULT NULL COMMENT '등록일자',
  `UPDATED_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `UPDATED_DATE` timestamp NULL DEFAULT NULL COMMENT '변경일자',
  PRIMARY KEY (`CALL_ID`,`BID`,`SID`,`UID`),
  KEY `I01_KDTF_APP_CALL_LIST` (`BID`,`UID`),
  KEY `I02_KDTF_APP_CALL_LIST` (`BID`,`CALL_STATUS`,`STD_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```
-- KDTF.TB_APP_BRAND_CUSTOMER definition

CREATE TABLE `TB_APP_BRAND_CUSTOMER` (
  `UID` varchar(100) NOT NULL COMMENT '제휴사 고객 관리 ID',
  `BID` varchar(20) NOT NULL COMMENT '제휴사 ID',
  `LOGIN_ID` varchar(100) NOT NULL COMMENT '로그인 ID',
  `KAKAO_AUTH_YN` varchar(1) DEFAULT 'N',
  `KAKAO_TOKEN` varchar(1000) DEFAULT NULL COMMENT '카카오 Token',
  `APPLE_AUTH_YN` varchar(1) DEFAULT 'N',
  `APPLE_TOKEN` varchar(100) DEFAULT NULL,
  `CUST_NAME` varchar(100) DEFAULT NULL COMMENT '제휴사 고객명',
  `MDN` varchar(20) DEFAULT NULL COMMENT '제휴사 고객 휴대전화 번호',
  `EMAIL` varchar(200) DEFAULT NULL COMMENT 'Email',
  `SEX_CODE` varchar(1) DEFAULT 'M' COMMENT '제휴사 고객 성별\\nM : 남성\\nF : 여성',
  `BIRTH_DAY` varchar(8) DEFAULT NULL COMMENT '제휴사 고객 생년월일\\nEX) 19880725',
  `CUST_STATUS` varchar(2) NOT NULL DEFAULT '00' COMMENT '제휴사 고객 계정 상태값\\n00 : 정상\\n01 : 일시정지\\n90 : 휴면\\n99 : 탈퇴',
  `CI` varchar(100) DEFAULT NULL,
  `USER_LEVEL` varchar(10) NOT NULL DEFAULT '0000' COMMENT '사용자 등급',
  `DEVICE_TYPE` varchar(1) DEFAULT 'A' COMMENT '제휴사 고객 단말 유형\\nA : 안드로이드\\nI : I Phone',
  `DEVICE_ID` varchar(100) DEFAULT NULL,
  `DEVICE_TOKEN` varchar(500) DEFAULT NULL COMMENT '제휴사 고객 단말 토큰',
  `OS_VERSION` varchar(10) DEFAULT NULL COMMENT '제휴사 고객 단말 OS 버전',
  `APP_VERSION` varchar(10) DEFAULT NULL COMMENT '제휴사 고객 APP 버전',
  `LAST_JOIN_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종 회원 가입 일자',
  `CLOSE_DATE` timestamp NULL DEFAULT NULL COMMENT '제휴사 고객 탈퇴일자',
  `LAST_LOGIN_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '제휴사 고객 마지막 로그인 일시',
  `LOGIN_FAIL_CNT` int(11) NOT NULL DEFAULT '0' COMMENT '제휴사 고객 로그인 실패횟수',
  `FAIL_LOCK_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '제휴사 고객 계정 잠김여부\\nY : 잠김\\nN : 정상',
  `SEND_PUSH_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '제휴사 고객 Push 수신 여부\\nY : 수신허용\\nN : 수신안함',
  `SEND_24PUSH_YN` varchar(1) DEFAULT 'N' COMMENT '24시간 PUSH 수신 여부',
  `SEND_SMS_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '제휴사 고객 SMS/MMS 수신여부\\nY : 수신허용\\nN : 수신안함',
  `SEND_EMAIL_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '제휴사 고객 이메일 수신여부\\nY : 수신허용\\nN : 수신안함',
  `BLOCK_YN` varchar(1) NOT NULL DEFAULT 'N',
  `AUTO_LOGIN_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '제휴사 고객 자동 로그인 기능 사용여부\\nY : 사용\\nN : 사용 안함',
  `PRICE_VIEW_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '요금 노출여부',
  `SERVICE_HIST_VIEW_YN` varchar(1) DEFAULT 'Y' COMMENT '서비스 이용내역 노출 여부\\n(Y : 노출, N : 노출 안 함)',
  `BIZ_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '법인여부',
  `BIZ_CODE` varchar(30) DEFAULT NULL COMMENT '법인 고객일 경우 법인코드',
  `STL_TYPE` varchar(2) DEFAULT NULL,
  `CHANNEL_CODE` varchar(10) NOT NULL DEFAULT 'NONE',
  `COMPANY_NAME` varchar(300) DEFAULT NULL COMMENT '회사명',
  `POSITION_NAME` varchar(300) DEFAULT NULL COMMENT '직책',
  `CAR_NUM` varchar(30) DEFAULT NULL COMMENT '차량 번호',
  `CAR_TYPE` varchar(2) DEFAULT NULL COMMENT '차량 유형\\nAT : 자동\\nMT : 수동',
  `CAR_INFO` varchar(1000) DEFAULT NULL COMMENT '차량 정보',
  `CAR_SPECIES` varchar(3) DEFAULT NULL COMMENT '차종',
  `OUTER_UID` varchar(100) DEFAULT NULL,
  `RECOMMEND_ID` varchar(100) DEFAULT NULL COMMENT '추천인 아이디',
  `REASON_CODE` varchar(2) DEFAULT NULL COMMENT '회원 탈퇴사유 코드',
  `REASON_DESC` text COMMENT '탈퇴사유 설명',
  `IS_DELETE` varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `INSERTED_ID` varchar(20) DEFAULT NULL COMMENT '등록자 ID',
  `INSERTED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  `UPDATED_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '변경일자',
  PRIMARY KEY (`UID`,`BID`),
  KEY `I01_APP_BRAND_CUSTOMER` (`BID`,`CUST_STATUS`,`INSERTED_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```
-- KDTF.TB_APP_BIZ_CONTRACT definition

CREATE TABLE `TB_APP_BIZ_CONTRACT` (
  `BID` varchar(20) NOT NULL COMMENT '제휴사 ID',
  `OUTER_UID` varchar(100) NOT NULL COMMENT 'Outer UID',
  `BIZ_CODE` varchar(30) NOT NULL COMMENT '법인 코드',
  `BIZ_NAME` varchar(300) DEFAULT NULL COMMENT '법인 명',
  `BIZ_NUM` varchar(20) DEFAULT NULL COMMENT '사업자 번호',
  `REPRESENT_NAME` varchar(20) DEFAULT NULL COMMENT '대표자명',
  `CONTACT_TEL` varchar(20) DEFAULT NULL COMMENT '담당자 연락처',
  `STL_TYPE` varchar(2) DEFAULT NULL COMMENT '정산 유형 01 : 선불, 02 : 후불',
  `BIZ_LIMIT_AMOUNT` bigint(20) DEFAULT '0' COMMENT '법인 한도',
  `NOTE` text COMMENT '비고',
  `IS_DELETE` varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `INSERTED_ID` varchar(20) DEFAULT NULL COMMENT '등록자 ID',
  `INSERTED_DATE` timestamp NULL DEFAULT NULL COMMENT '등록일자',
  `UPDATED_ID` varchar(20) DEFAULT NULL COMMENT '변경자 ID',
  `UPDATED_DATE` timestamp NULL DEFAULT NULL COMMENT '변경일자',
  PRIMARY KEY (`BID`,`OUTER_UID`,`BIZ_CODE`),
  UNIQUE KEY `BIZ_CODE_UNIQUE` (`BIZ_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Thank you for your help.
I hope you find this bug and fix smoothly :)
If you need anything else, please let me know. I will support and provide what ever i can.

**Comment by xcxcxz** [comment]
Is it because of `site.xml` is missing on https://dbeaver.io/eclipse-repo/ ?
i just clone codes, and it throw this exception `Error while reading from repository: https://dbeaver.io/eclipse-repo/site.xml.`

**Comment by xcxcxz** [comment]
@LonwoLonwo 
Maybe I found some point.
if I remove or make to comment all the empty columns like ' ',
it works well.

but still not working 'run script' and 'cmd + enter' if i run with  empty columns.

**Comment by xcxcxz** [comment]
I found one more case like what i provide.
If you need query and DDLs, Please let me know :)

**Comment by LonwoLonwo** [comment]
> I found one more case like what i provide.

Yes, provided it, please.

For now, we can't reproduce this issue on Windows and mac m1 too.

**Comment by xcxcxz** [comment]
It comes from I updated to v 22.1.3.


```
SELECT CALL_ID, '', BID FROM TB_KDTF_APP_CALL_LIST 
ORDER BY INSERTED_DATE DESC
;
```

This query also not working.
Everytime, using select query with empty column(' '), Dbeaver is not work.

You can use  `TB_KDTF_APP_CALL_LIST` DDL on my second reply for this query.

**Comment by LonwoLonwo** [comment]
Hello @xcxcxz 

I'm sorry for not getting back to you sooner. Can you please check the newest DBeaver version? https://dbeaver.io/

**Comment by xcxcxz** [comment]
Yeeeeeeeeeeees!!!
It's working well now.
I'm so glad to you care about this issue.
Thank you guys and especially @LonwoLonwo.
Have a great days. :)
