### ISSUE TITLE
Can't add a column to the grouping panel

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#17269]
### Description

Can't use grouping panel. In any database

https://user-images.githubusercontent.com/43252954/182995367-b55576a1-2ce9-442b-b554-4eaf93dc4963.mp4

![image](https://user-images.githubusercontent.com/43252954/182995476-e9037674-8c96-465d-b0ab-51e43cc7ffe5.png)

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingResultsDecorator.getEmptyDataDescription(GroupingResultsDecorator.java:71)
	at org.jkiss.dbeaver.ui.controls.resultset.view.EmptyPresentation.lambda$1(EmptyPresentation.java:80)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1627)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4803)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5034)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1542)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6720)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4782)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6059)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/9265013/dbeaver-debug.log)

[log.txt](https://github.com/dbeaver/dbeaver/files/9265015/log.txt)

### Steps to reproduce

1. open a table in any database
2. Open the grouping panel
3. Try to drag-n-drop some column

### DBeaver Version

22.1.4

### Operating System

win11

**Comment by LonwoLonwo** [comment]
And also:

```java
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setStatusTooltip(ResultSetViewer.java:2044)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateStatusInfo(ResultSetViewer.java:2133)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateStatusMessage(ResultSetViewer.java:2050)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.changeMode(ResultSetViewer.java:1875)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.<init>(ResultSetViewer.java:387)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingResultsContainer.<init>(GroupingResultsContainer.java:72)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingPanel.getGroupingResultsContainer(GroupingPanel.java:88)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingPanel.refresh(GroupingPanel.java:148)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingPanel.activatePanel(GroupingPanel.java:131)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePanel(ResultSetViewer.java:1265)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.activatePanel(ResultSetViewer.java:1223)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.activateDefaultPanels(ResultSetViewer.java:1251)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSetViewer.java:902)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:777)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$1(ResultSetDataReceiver.java:194)
```

**Comment by serge-rider** [comment]
Fixed

**Comment by DariaMarkaryan** [comment]
Verified
