### ISSUE TITLE
Unable to perform SSPI authentication in DBeaver

### ISSUE THREAD

**Issue by srnsomu** [dbeaver/dbeaver#17268]
### Description

I am using version 22.1.2 and SSPI support via waffle-jna was added in 22.0.5 according to release notes. However, when I try to perform SSPi authentication for a user, it fails with the error com.sun.jna.LastErrorException.

I am able to perform SSPi authentication for the same user using pgAdmin.  It however fails with DBeaver.
I have added the waffle-jna artifact in Libraries and downloaded the driver
<dependency>
    <groupId>com.github.waffle</groupId>
    <artifactId>waffle-jna</artifactId>
    <version>3.2.0</version>
</dependency>

After adding the artifact, I enter the username (with SSPI authentication added) in the Authentication section and I leave the password section empty. Upon clicking Test Connection, I get the error com.sun.jna.LastErrorException

### Steps to reproduce

DBeaver -> Edit Driver Settings -> Libraries -> Add Artifact -> Add waffle-jna artifact with
Artifact Id: waffle-jna
group id: com.github.waffle
Version: 3.2.0
Fallback Version: RELEASE

Check Ignore transient dependencies. 
Click Okay and Test Connection. An error box appears saying Connection Error

Workspace Log:
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Aug 04 11:35:37 EDT 2022
com.sun.jna.LastErrorException

java.lang.ClassNotFoundException: com.sun.jna.LastErrorException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.postgresql.core.v3.ConnectionFactoryImpl.createSSPI(ConnectionFactoryImpl.java:82)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:712)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.access$100(Driver.java:62)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:375)
	at java.base/java.lang.Thread.run(Unknown Source)

PostgreSQL log:
2022-08-04 10:46:40.531 EDT [11076] FATAL:  SSPI authentication failed for user "310151160@code1"
2022-08-04 10:46:40.531 EDT [11076] DETAIL:  Connection matched pg_hba.conf line 83: "host    all      "310151160@code1"        127.0.0.1/32           sspi"

### DBeaver Version

22.1.2

### Operating System

Windows 10 Enterprise

**Comment by uslss** [comment]
thanks for the report.
seems SSPI is working with waffle-jna 1.9.1 only.
Could you try to reset driver settings to default and check if it helps?
![image](https://user-images.githubusercontent.com/31996417/183909850-2f8dac7e-0ac9-4dc1-b196-a5bad18b61a0.png)

**Comment by E1izabeth** [comment]
connected to https://github.com/dbeaver/dbeaver/issues/1974

**Comment by srnsomu** [comment]
Hi @uslss I did try the recommendation to use waffle version 1.9.1, but it did not help. After I change to defaults, it beings up a UI to download the drivers. When I click OK on the UI, it goes into an error. I've created a screenshot recording of the same. Also, what is the password box set to when performing SSPI. I've currently set it as empty.

https://user-images.githubusercontent.com/4008861/184228129-41a26d39-adf6-4845-9a6f-22c3c92b9bfb.mp4

**Comment by uslss** [comment]
SSPI authentication is implemented in EE version. Could you check if it works for you?
![image](https://user-images.githubusercontent.com/31996417/185409589-3b3eb737-8b7e-4ba1-81d3-dec8aea7c11f.png)

**Comment by srnsomu** [comment]
Hi @uslss, I am using the Community Edition. Is PostgreSQL SSPI only available in the Enterprise Edition?

**Comment by uslss** [comment]
Cannot reproduce it for now. @srnsomu Is it reproducible for you against 22.2.0 version?

**Comment by srnsomu** [comment]
I was unaware that the SSPI authentication was not available in the Community edition. The issue can be closed
