### ISSUE TITLE
Failed to load existing database connections after update to 22.1.4.202208051447

### ISSUE THREAD

**Issue by 3shv** [dbeaver/dbeaver#17305]
### Description

After the Dbeaver is updated to 22.1.4, it failed to load the existing connections and shows the message `no default storage in registry General`

```
!ENTRY org.jkiss.dbeaver.model 4 0 2022-08-09 14:14:35.883
!MESSAGE Error loading datasource config from file:///Users/rveeranki/Library/DBeaverData/workspace6/General/.dbeaver/data-sources-default.json
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-08-09 14:14:35.883
!MESSAGE no default storage in registry General (DataSourceRegistry)
!STACK 0
java.lang.IllegalStateException: no default storage in registry General (DataSourceRegistry)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.getDefaultStorage(DataSourceRegistry.java:173)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.parseDataSources(DataSourceSerializerModern.java:529)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:701)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:657)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:637)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:93)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:86)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.createDataSourceRegistry(BaseProjectImpl.java:179)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.getDataSourceRegistry(BaseProjectImpl.java:171)
	at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:182)
	at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:197)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getChildren(DBNProject.java:161)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getDatabases(DBNProject.java:62)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorView.getRootNode(DatabaseNavigatorView.java:87)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.lambda$0(NavigatorViewBase.java:110)
	at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:52)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4345)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3968)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

### DBeaver Version

22.1.4.202208051447

### Operating System

macOS Monterey 12.4

### Database and driver

1. Cloudera Impala cloudera_impala
2. Vertica vertica-jdbc-8

**Comment by 3shv** [comment]
Looking at the [commit](https://github.com/dbeaver/dbeaver/commit/46e2f8c88941745b80c08acbcaaae8dad8e54269), the new update discards reading the config `data-sources-default.json`. So after I rename it to `data-sources.json`, all my connections are back.

**Comment by E1izabeth** [comment]
@Rajesh-Veeranki thank you for bug report and investigation.

**Comment by E1izabeth** [comment]
The fix should be available in the future release. Please, let me know if the bug still exists.
