### ISSUE TITLE
Can't edit array of composite types

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17302]
### Description

![image](https://user-images.githubusercontent.com/28875055/183509814-a143978f-19ce-4234-b68e-df7ac1afae0d.png)

Edit as a string is not available, arrays expander can't expand array element, value viewer is empty.

NPE in logs:
```
java.lang.NullPointerException: Cannot read the array length because "parsedValues" is null
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:187)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:107)
	at org.jkiss.dbeaver.ext.postgresql.PostgreValueParser.convertStringToSimpleValue(PostgreValueParser.java:157)
	at org.jkiss.dbeaver.ext.postgresql.PostgreValueParser.convertStringToValue(PostgreValueParser.java:87)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:195)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:107)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.convertStringToCollection(PostgreArrayValueHandler.java:142)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:799)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:165)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:217)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4945)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### DBeaver Version

DBeaver 22.1.4

### Database and driver

PostgreSQL 12

### Steps to reproduce

```
create type vec2i as (x int, y int);
create type recti as (origin vec2i, size vec2i);
create table rects3rects (id serial primary key, rects3 recti[][][]);
insert into rects(id, rect) values (1, row(row(11, 12), row(13, 14)));
insert into rects(id, rect) values (2, row(row(21, 22), row(23, 24)));
insert into rects(id, rect) values (3, row(row(31, 32), row(33, 34)));
insert into rects(id, rect) values (4, row(row(41, 42), row(43, 44)));
insert into rects(id, rect) values (5, row(row(51, 52), row(53, 54)));
```

**Comment by MarcelloPaiva** [comment]
I am currently having the same issue

**Comment by E1izabeth** [comment]
NPE has gone, but the editing is not satisfying.
