### ISSUE TITLE
Unable to create Oracle JDBC connection in DBeaver using Calcite

### ISSUE THREAD

**Issue by kartikkudada** [dbeaver/dbeaver#17317]
### Description

I am trying to connect my Oracle database using calcite JDBC  in DBever. 

Driver class used : org.apache.calcite.jdbc.Driver

URL  - jdbc:oracle:thin:XXXXXXX:1521:<database>

 

But when I use same same URL and driver  with main java program . it works fine .

Connection con= DriverManager.getConnection("jdbc:calcite:schemaType=JDBC; schema.jdbcUser=USERNAME; " +
"schema.jdbcPassword=XXXXXX; schema.jdbcUrl=jdbc:oracle:thin:@XXXXXXXXXXXXX:1521:ORCL; schema.conformance=ORACLE_10; schema.fun=oracle" );

I have cloned calcite project and running main program on that . Please let me know if I have done any mistake .
 
Stacktrace : 
Reason: can't load driver class 'org.apache.calcite.jdbc.Driver'
org.jkiss.dbeaver.DBException: Error creating driver 'Apache Calcite Avatica' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.calcite.jdbc.Driver'
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1123)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1059)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:685)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:112)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.calcite.jdbc.Driver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1121)
	... 18 more

### DBeaver Version

Version 22.0.2.202204041542

### Operating System

Windows 11

### Database and driver

1. Database name : Oracle 
2. Driver : org.apache.calcite.jdbc.Driver 

![Calcite JDBC-DBeaver-connection-Issue](https://user-images.githubusercontent.com/10473037/183671989-a66c4c26-2250-4368-b879-d1b7a378a1be.png)
![JDBC-calcite-connection-Error-Message](https://user-images.githubusercontent.com/10473037/183671999-e3081acf-b435-43fd-80dc-088baf69fb71.png)

### Steps to reproduce

1. right click on Database Navigator > create > connection 
2.  Select Apache Calcite Avatica , click next 
3.  provide below  in Generic JDBC Connection Settings dialog box
     JDBC URL , username , password 
4.  Click on Edit Driver Settings , provide the driver class name (check image) , click ok on Edit Driver dialog box
5. Click on Test Connection on Generic JDBC Connection Settings dialog box .

![Dbeaver-setting](https://user-images.githubusercontent.com/10473037/183673943-3f28cd23-d3b6-4eda-9b46-bb26f237a9d0.png)

![driver-name](https://user-images.githubusercontent.com/10473037/183674941-fc29c694-ca1c-439a-8130-b91111e7efe7.png)

![Error-on-test-connection](https://user-images.githubusercontent.com/10473037/183676047-9d8f9102-1659-4c37-ad78-84af6e1ccd71.png)

**Comment by Destrolaric** [comment]
@kartikkudada 
Hi, could you provide a screenshot of the Libraries tab in Drivers settings?
![image](https://user-images.githubusercontent.com/20579256/183896222-f2307426-ffa1-4afd-951c-67656bd3e159.png)

**Comment by kartikkudada** [comment]
@Destrolaric - Thank you for response . 
Please find screenshot of libraries tab . 

![libraries](https://user-images.githubusercontent.com/10473037/183907196-10808227-09f3-41d3-bae2-b1743356219e.png)

**Comment by kartikkudada** [comment]
I tried Add Artificat option in Edit Driver dialog box .
And provided my dependency details which I used in java program .

    <dependency>
            <groupId>org.apache.calcite</groupId>
            <artifactId>calcite-core</artifactId>
            <version>1.30.0</version>
        </dependency>

It time it asked me to change URL :
Changed to : **jdbc:oracle:thin:@XXXXXXXXXXXX1521:XXXX**
Tried URL :      **jdbc:calcite:@XXXXXXXXXXXX1521:XXXX**

Started getting diff error as below : 
I verified if class **org.apache.calcite.config.CalciteConnectionProperty** is present or not . 
I downloaded jar from maven repo and checked,  found class is present in jar . 


Unexpected driver error occurred while connecting to the database
  Could not initialize class org.apache.calcite.config.CalciteConnectionProperty
  Could not initialize class org.apache.calcite.config.CalciteConnectionProperty
 


Log : 
2022-08-11 16:50:48.997 - Could not initialize class org.apache.calcite.config.CalciteConnectionProperty
java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.config.CalciteConnectionProperty
	at org.apache.calcite.config.CalciteConnectionConfigImpl.typeSystem(CalciteConnectionConfigImpl.java:179)
	at org.apache.calcite.jdbc.CalciteConnectionImpl.<init>(CalciteConnectionImpl.java:133)
	at org.apache.calcite.jdbc.CalciteJdbc41Factory$CalciteJdbc41Connection.<init>(CalciteJdbc41Factory.java:117)
	at org.apache.calcite.jdbc.CalciteJdbc41Factory.newConnection(CalciteJdbc41Factory.java:61)
	at org.apache.calcite.jdbc.CalciteJdbc41Factory.newConnection(CalciteJdbc41Factory.java:46)
	at org.apache.calcite.jdbc.CalciteFactory.newConnection(CalciteFactory.java:55)
	at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:185)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:204)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:202)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:112)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



Driver library after adding of calcite-core artificat 
![calcite-core-library](https://user-images.githubusercontent.com/10473037/184123513-211b126c-4307-4653-9a3e-b6cfa4cdd01c.png)

**Comment by kartikkudada** [comment]
after adding calcite-core artificat 
![calcite-core-library](https://user-images.githubusercontent.com/10473037/184123348-a41d54d0-6ba4-4b36-a9d9-e28ecbfa4f98.png)

**Comment by Destrolaric** [comment]
@kartikkudada, I have a question regarding the usage of the Calcite driver for the Oracle database. Is there any specific reason to use Calcite for interaction with the Oracle database?

**Comment by kartikkudada** [comment]
@Destrolaric - Thanks for response . 
We can connect to variety of database (Oracle/MySql/SQL Server/Postgres) using calcite driver . 
One driver is sufficient for multiple databases . And I would like to modify calcite and use as driver jar in DBeaver/tableau .

**Comment by Destrolaric** [comment]
@kartikkudada Does this mean that provided driver works for other databases in DBeaver?

**Comment by kartikkudada** [comment]
@Destrolaric - yes it will work with changes only in Host ,port ,user credentials . I am able to connect oracle and Mysql using same calcite driver in my java program . 
But I couldn't do in Dbeaver with neither built-in calcite jar nor modified jar.

**Comment by Destrolaric** [comment]
@kartikkudada I have looked into this issue deeper looks like you are using an entirely different driver class name for the driver you are using is `org.apache.calcite.jdbc.Driver` when the default avatica configuration uses `org.apache.calcite.avatica.remote.Driver`. Your driver is part of `org.apache.calcite` not of `org.apache.calcite.avatica`. Its artifact id is `calcite-core`. I tried to connect via it and it does not show oracle schema correctly, I didn't look more into it. Tell me if the information helps.

**Comment by Destrolaric** [comment]
You may look to our documentation about configuring new drivers https://dbeaver.com/docs/wiki/Database-drivers/

**Comment by kartikkudada** [comment]
@Destrolaric 
Thank you .
I deleted downloaded jars by Dbeaver and updated required jars for connection by adding add artifact option in Edit Driver option. 
Yes you are correct my required Driver is part of org.apache.calcite , and part of calcite-core artifact . which I added later. 
now I am able to connect oracle and MySql .

I think when calcite connection is selected in Dbeaver , it should download calcite-core jars , not avatica jars 
(org.apache.calcite.avatica) 
![newConnection](https://user-images.githubusercontent.com/10473037/185596295-02e5d22c-5b22-4db4-8f67-76020f630d1a.png)

**Comment by Destrolaric** [comment]
@kartikkudada I am not sure, your driver is entirely different from calcite avatica. Connection is configured for calcite avatica, which is, for example, used for apache druid. I think It needs its own configuration.
