### ISSUE TITLE
event loop exception (viewing geometries

### ISSUE THREAD

**Issue by JeroenNienhuis** [dbeaver/dbeaver#17332]
### Description

Just updated to new DBeaver version

running 
select st_geometryfromtext('POLYGON ((0 0, 1 1, 2 0, 0 0))') 
gives an event loop exception

details:
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 10 17:07:14 CEST 2022
Event loop exception

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 10 17:07:14 CEST 2022
Failed to execute runnable (org.eclipse.swt.SWTError: Not implemented [WebView2 runtime not found])

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 10 17:07:14 CEST 2022
Not implemented [WebView2 runtime not found]

org.eclipse.swt.SWTError: Not implemented [WebView2 runtime not found]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.browser.Edge.createEnvironment(Edge.java:313)
	at org.eclipse.swt.browser.Edge.create(Edge.java:336)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.setCursor(Spreadsheet.java:230)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.setCurrentAttribute(SpreadsheetPresentation.java:350)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.lambda$1(ResultSetViewer.java:5047)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

### DBeaver Version

Community Version 22.1.4.202208051447

### Operating System

Wn 7

### Database and driver

PostgreSQL 12.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

**Comment by Destrolaric** [comment]
Hi, for Windows 7 and older please remove `-Dorg.eclipse.swt.browser.DefaultType=edge` from dbeaver.ini. The file is located in the DBeaver directory.
Also, Edge is supported for Windows 7, you can install and this will allow you to use it as internal browser for DBeaver

**Comment by JeroenNienhuis** [comment]
Removing the line from the ini-file works. thanks a lot.
I prefer not to use Edge.

**Comment by Destrolaric** [comment]
@JeroenNienhuis Unfortunately, it's the only viable replacement for IE for SWT applications. Chromium support was discontinued due to license issues.

**Comment by kikonen** [comment]
Encountering constant errors in windows 10, which look a bit similar

Removing that line from AppData\Local\DBeaver\dbeaver.ini seemed to help also there

Error was surely rather irritating, not only one error dialog, but *two* of them popping up, next one even more irritating than actual error dialog, suggesting to restart DBeaver.

**Comment by Destrolaric** [comment]
@kikonen Hmm, did you remove Microsoft Edge from your Windows? It looks like DBeaver couldn't find Edge on your PC.

**Comment by E1izabeth** [comment]
@Destrolaric, I reproduced it on windows 7. @kikonen just tell us that after SWTError DBeaver thought that the workspace could be broken and suggested to restart DBeaver.

**Comment by kikonen** [comment]
I definitelly have not uninstalled Edge :)

I think error started appearing with DBeaver 22.14 (did upgrade from 22.13 few days ago). I happen to have anothr win 11 (sorrry meant win 11, when said win 10 :D) machine with 22.13 so testing now does it have similar behaviour... I think 22.13 works fine. 

Upgraded also this second computer to 22.14, and error started to appear, and also in this case, removal of that one line from dbeaver.ini seemed to fix it.

In this second machine, I have clearly used latest version of Edge, since it pops up setup dialogs when opened. Perhaps that is related to problem?

```
Unhandled event loop exception
No more handles [0x80070578]

 org.eclipse.swt.SWTError: No more handles [0x80070578]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.browser.Edge.error(Edge.java:190)
	at org.eclipse.swt.browser.Edge.create(Edge.java:343)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by Destrolaric** [comment]
@kikonen, thank you for the information. Unfortunately, I was unable to reproduce it on my system. Is there a reliable way to do it? Video may help.

**Comment by kikonen** [comment]
Updated to 22.1.5.202208211008 and error is back (naturally since conf file is back to original).

**Comment by Destrolaric** [comment]
Hi, the fix will be available in 22.2.0. If the issue regarding no more handles continues, there will be a new UI preference to use IE as a default browser.

**Comment by kikonen** [comment]
Just tried with  22.2.0.202209051344 and encountering still similar problems; this time seemingly no workaround (?!?)

**Comment by Destrolaric** [comment]
@kikonen Have you tried changing to IE in User Interface -> Web Engine?
The issue with handles is planned to be looked into in the near future.

**Comment by kikonen** [comment]
Meaning this (at least didn't find any other setting DBeaver related to that). Haven't touched that.

*EDIT*
Did few trials of different options on that, and didn't really see any improvement.

![image](https://user-images.githubusercontent.com/478935/189153161-b61aac98-05ad-4373-b885-9300b2ba1b2f.png)

Default web browser in OS is naturally Opera; not sure how it relates into this embedded geo view

**Comment by Destrolaric** [comment]
@kikonen, This is the wrong page. Required page setting is located in User Interface preference(see screenshot below)
![image](https://user-images.githubusercontent.com/20579256/189154579-1427b493-ae35-46c7-82ae-d5d1d14bd6ea.png)

**Comment by kikonen** [comment]
:) I see.

Well, changing that setting did actually improve situation; who says that IE is dead :D

and this is also better workaround than that "edit init file in not easily guessable directory".
