### ISSUE TITLE
Errors on editing multidimensional array

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17413]
### Description

https://user-images.githubusercontent.com/28875055/185877782-d7ef43b7-b126-4c23-95c8-06ddc035d48e.mp4

### DBeaver Version

DBeaver 22.1.5

### Database and driver

PostgreSQL 12

### Steps to reproduce

1. Try to open or modify value of multidimensional array with inline array editing.
2. See in the debug log

```
org.jkiss.dbeaver.model.exec.DBCException: Can't parse numeric value [{{{21,22}},{{233,24}}}] using formatter
	at org.jkiss.dbeaver.model.DBValueFormatting.convertStringToNumber(DBValueFormatting.java:238)
	at org.jkiss.dbeaver.ui.data.editors.NumberInlineEditor.extractEditorValue(NumberInlineEditor.java:111)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.saveValue(BaseValueEditor.java:247)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.saveValue(BaseValueEditor.java:242)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.saveValue(BaseValueEditor.java:238)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.lambda$0(BaseValueEditor.java:135)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:269)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:4260)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:4242)
	at org.eclipse.swt.widgets.Display.translateTraversal(Display.java:4945)
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1280)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:641)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:467)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:896)
	at org.jkiss.dbeaver.model.DBValueFormatting.convertStringToNumber(DBValueFormatting.java:231)
	... 38 more
2022-08-22 11:35:43.734 - Index specified for non-collection attribute
```

**Comment by uslss** [comment]
not actual 24.2.2
