### ISSUE TITLE
Drag&Drop from Navigator

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#17415]
### Description

Is it expected that Drag&Drop of an object pulled from the Navigator to SQL editor doesn't work?
The mouse cursor is being changed during this process indicating d&d operation, but the object name is not pasted to the editor.

### DBeaver Version

22.1.4.202208051447

### Operating System

Fedora 36

### Database and driver

PostgreSQL

### Steps to reproduce

1. hover with mouse pointer over table in the Navigator
2. press left mouse button and pull the cursor into editor
3. release left mouse button

### Additional context
On Windows it works as expected. So I suspect it's Linux version related issue
_No response_

**Comment by michal-bartak** [comment]
Not sure if should I open the issue. I can confirm that drag&drop works if DBeaver is run in the normal way.
However, if I run it forcing X.org (`env GDK_BACKEND=x11 /usr/share/dbeaver-ce/dbeaver&`) drag and drop doesn't work.

Please imagine we, Wayland users, are put into a deadlock. We can have some features working under Wayland, while others don't (copy&paste, sharing screen). Or another way around: Other things work under X while doesn't under Wayland.

**Comment by dimahetman** [comment]
Confirm this bug. After DND from Navigator to SQLEditor I have been log message:
```eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=be_BY
Framework arguments:  -eclipse.keyring /home/hetman/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Thu Jul 04 21:39:47 MSK 2024
Unhandled event loop exception

org.eclipse.swt.SWTException: Data does not have correct format for type
	at org.eclipse.swt.dnd.DND.error(DND.java:291)
	at org.eclipse.swt.dnd.DND.error(DND.java:241)
	at org.eclipse.swt.dnd.FileTransfer.javaToNative(FileTransfer.java:74)
	at org.eclipse.swt.dnd.DragSource.dragGetData(DragSource.java:538)
	at org.eclipse.swt.dnd.DragSource.DragGetData(DragSource.java:322)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_drag_get_data(Native Method)
	at org.eclipse.swt.dnd.DropTarget.drag_drop(DropTarget.java:425)
	at org.eclipse.swt.dnd.DropTarget.Drag_Drop(DropTarget.java:264)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)
	Suppressed: org.eclipse.swt.SWTException: Data does not have correct format for type
		... 34 more

```

**Comment by dimahetman** [comment]
I founded in debug mode that when you try DND from Navigator to SQL Editor in class `NavigatorDragSourceListener.java` (`dragSetData` method) is interpreting this event as `FileTransfer` event. IMHO it's very strange but explains ` Data does not have correct format for type`.
I dumped call stack at moment (before exception):
```
"main@1" prio=6 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.jkiss.dbeaver.ui.navigator.dnd.NavigatorDragSourceListener.dragSetData(NavigatorDragSourceListener.java:89)
	  at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:68)
	  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
	  at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1373)
	  at org.eclipse.swt.dnd.DragSource.dragGetData(DragSource.java:527)
	  at org.eclipse.swt.dnd.DragSource.DragGetData(DragSource.java:322)
	  at org.eclipse.swt.internal.gtk3.GTK3.gtk_drag_get_data(GTK3.java:-1)
	  at org.eclipse.swt.dnd.DropTarget.drag_drop(DropTarget.java:425)
	  at org.eclipse.swt.dnd.DropTarget.Drag_Drop(DropTarget.java:264)
	  at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(GTK3.java:-1)
	  at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	  at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(GTK3.java:-1)
	  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	  at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	  at org.eclipse.ui.internal.Workbench$$Lambda$341/0x000071b7042bb090.run(Unknown Source:-1)
	  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	  at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:568)
	  at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	  at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	  at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
	  at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)

```
And try to found a place where I was able to change the type of event or etc, but I don't understand how to found the real source of this problem. 
By the way, for example, if you open the log window and drag an item from the navigator into the text field of the log filter, then the DND works correctly, which is natural because it is processed as text and not a `FileTransfer` type of event.

My searches ended at `org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)`
because in project, this library doesn't have source codes `I see /* compiled code */`

At the moment it seems to me that the problem is quite deep, because:
* there is no such problem on Windows, but there is a like on Ubuntu and maybe etc Linux like OS.
* there is Navigator hasn't clear link with SQL Editor in the dump
