### ISSUE TITLE
[Edge] no more handles 

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#17489]
```
I definitelly have not uninstalled Edge :)

I think error started appearing with DBeaver 22.14 (did upgrade from 22.13 few days ago). I happen to have anothr win 11 (sorrry meant win 11, when said win 10 :D) machine with 22.13 so testing now does it have similar behaviour... I think 22.13 works fine. 

Upgraded also this second computer to 22.14, and error started to appear, and also in this case, removal of that one line from dbeaver.ini seemed to fix it.

In this second machine, I have clearly used latest version of Edge, since it pops up setup dialogs when opened. Perhaps that is related to problem?


Unhandled event loop exception
No more handles [0x80070578]

 org.eclipse.swt.SWTError: No more handles [0x80070578]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.browser.Edge.error(Edge.java:190)
	at org.eclipse.swt.browser.Edge.create(Edge.java:343)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.swt.browser.Edge.callAndWait(Edge.java:227)
	at org.eclipse.swt.browser.Edge.create(Edge.java:342)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$2(ValueViewerPanel.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$3(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:217)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onKeyDown(LightGrid.java:4033)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1798)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5155)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4778)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```
_Originally posted by @kikonen in https://github.com/dbeaver/dbeaver/issues/17332#issuecomment-1213219453_
Sometimes appears when using Edge, it may happen due to handles being not properly disposed of because of race conditions.
Possibly related to the internal error inside the eclipse: https://github.com/eclipse-platform/eclipse.platform.swt/issues/339. We need to look for workarounds regarding this issue.

**Comment by E1izabeth** [comment]
Probably connected with #18197
