### ISSUE TITLE
Can't use common table expressions (with .. as)

### ISSUE THREAD

**Issue by AlexeyAntipov98** [dbeaver/dbeaver#17526]
### Description

When i run sql request i saw SQL Error 42P01. This request working in pgAdmin

### DBeaver Version

22.1.5

### Operating System

WIN 10

### Database and driver

PostgreSQL 13.2
PostgreSQL JDBC Driver JDBC 42.2.25

### Steps to reproduce

I write this SQL request and run him

with tbl as (
	select 1 
)

select * from tbl

### Additional context

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42P01]: ОШИБКА: отношение "tbl" не существует
  Позиция: 15

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3644)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4937)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: org.postgresql.util.PSQLException: ОШИБКА: отношение "tbl" не существует
  Позиция: 15

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)

	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)

	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)

	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)

	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)

	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)

	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)

	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)

	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)

	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)

	... 12 more

**Comment by LonwoLonwo** [comment]
Hello @AlexeyAntipov98 

I see an empty line in your query. Probably, problem is with this empty line - by default DBeaver recognizes it as delimiter.

So. You can remove an empty line from your query.

![2022-09-01 13_46_39-Window](https://user-images.githubusercontent.com/45152336/187896482-9bbb585f-ad8e-45d8-ae33-09090b2c4145.png)

Or you can highlight all your query and run it

![2022-09-01 13_44_17-Window](https://user-images.githubusercontent.com/45152336/187896559-ac533182-42d0-4d07-8b91-81aa6b128c12.png)

Or you can disable this setting in Preferences

![2022-09-01 13_43_31-Window](https://user-images.githubusercontent.com/45152336/187896620-f0a3f4a3-a136-4c4d-95c3-e350c18e0758.png)

**Comment by AlexeyAntipov98** [comment]
Thank you. Now it working)
