### ISSUE TITLE
Salesforce CDP authentication failure

### ISSUE THREAD

**Issue by kcgreg77** [dbeaver/dbeaver#17542]
### Description

I'm currently connected to Salesforce CDP using Tableau and would like to connect DBeaver as well.   Since Tableau is working,  I believe the prerequisite "Set Up a Connected App" step had been completed.   Authentication with Tableau is working successfully for my logn,  however with DBeaver I'm receiving "authentication failure".   Need help understanding if I'm doing something wrong or if bug related.  

JDBC URL=  jdbc:queryService-jdbc:https://login.salesforce.com
Database/Schema= https://login.salesforce.com
Username=  <my email address for https://login.salesforce.com>
Password=  <my password for https://login.salesforce.com>

!ENTRY org.jkiss.dbeaver.model 4 0 2022-09-02 08:18:46.817
!MESSAGE authentication failure
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-09-02 08:18:46.817
!MESSAGE authentication failure
!STACK 0
java.io.IOException: authentication failure
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:45)
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:36)
	at com.salesforce.cdp.queryservice.util.TokenHelper.un_pw_login(TokenHelper.java:329)
	at com.salesforce.cdp.queryservice.util.TokenHelper.retrieveTokenWithPasswordGrant(TokenHelper.java:123)
	at com.salesforce.cdp.queryservice.util.TokenHelper.getToken(TokenHelper.java:80)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.lambda$getTokenWithTenantUrl$2(QueryExecutor.java:182)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getTokenWithTenantUrl(QueryExecutor.java:181)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.executeQuery(QueryExecutor.java:92)
	at com.salesforce.cdp.queryservice.core.QueryServiceAbstractStatement.executeQuery(QueryServiceAbstractStatement.java:72)
	at com.salesforce.cdp.queryservice.core.QueryServicePreparedStatement.execute(QueryServicePreparedStatement.java:158)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.isValid(QueryServiceConnection.java:339)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.<init>(QueryServiceConnection.java:59)
	at com.salesforce.cdp.queryservice.QueryServiceDriver.connect(QueryServiceDriver.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:191)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:208)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:946)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:880)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

Community Edition 22.1.3.202207240747

### Operating System

Windows 10 Enterprise

### Database and driver

Salesforce-CDP-jdbc-1.12.0.jar
Salesforce-CDP-jdbc-1.12.0-java8.jar

### Steps to reproduce

Clicking "Test Connection" in the Salesforce CDP connection settings

**Comment by LonwoLonwo** [comment]
Related tickets: https://github.com/dbeaver/dbeaver/issues/17038
https://github.com/dbeaver/dbeaver/issues/16652

**Comment by kcgreg77** [comment]
Hopefully this helps others,  but the issue is related to SalesForce Connected App setup. 
The "Salesforce CDP Tableau Connection" app needs to have IP Relaxation set to "Relax IP restrictions"
Now,  I'm able to JDBC connect from DBeaver

**Comment by LonwoLonwo** [comment]
Thanks for clarification @kcgreg77

**Comment by kartas39** [comment]
> Hopefully this helps others, but the issue is related to SalesForce Connected App setup. The "Salesforce CDP Tableau Connection" app needs to have IP Relaxation set to "Relax IP restrictions" Now, I'm able to JDBC connect from DBeaver

not working for me
