### ISSUE TITLE
GIS Viewer broken : Not implemented [WebView2 runtime not found]

### ISSUE THREAD

**Issue by bazmap** [dbeaver/dbeaver#17597]
### Description

When I try to visualize spatial data, I've got an error : 
Not implemented [WebView2 runtime not found]

org.eclipse.swt.SWTError: Not implemented [WebView2 runtime not found]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.browser.Edge.createEnvironment(Edge.java:313)
	at org.eclipse.swt.browser.Edge.create(Edge.java:336)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.jkiss.dbeaver.ui.gis.panel.GISLeafletViewer.<init>(GISLeafletViewer.java:112)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:66)
	at org.jkiss.dbeaver.ui.gis.panel.GISBrowserViewer.createControl(GISBrowserViewer.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.gis.panel.GISPanelEditor.createControl(GISPanelEditor.java:100)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:74)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:244)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:212)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refresh(ValueViewerPanel.java:156)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePanelsContent(ResultSetViewer.java:3527)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.showPanels(ResultSetViewer.java:1323)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$4.widgetSelected(ResultSetViewer.java:913)
	at org.jkiss.dbeaver.ui.controls.VerticalButton.lambda$5(VerticalButton.java:297)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.jkiss.dbeaver.ui.controls.VerticalButton.runAction(VerticalButton.java:134)
	at org.jkiss.dbeaver.ui.controls.VerticalButton$2.mouseUp(VerticalButton.java:110)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:285)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Session data : 
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

### DBeaver Version

Community edition : Version 22.2.0.202209051344

### Operating System

Windows 10

### Database and driver

PostgreSQL 11 (but the same on 9.6 and 13)
PostgreSQL JDBC Driver from DBeaver

**Comment by E1izabeth** [comment]
Thank you for bug report. Please, try switching this setting to Internet Explorer. Does it help?

![image](https://user-images.githubusercontent.com/28875055/189076967-0ccb360d-ed60-483e-b0b8-59494d0cfa6a.png)

**Comment by bazmap** [comment]
Amazing, it works !

Ok thats a little bit awkward to use Internet Explorer but I can make an effort for this wonderfull software that DBeaver is.

Thank you

Best Regards !

**Comment by Destrolaric** [comment]
Linked issue: https://github.com/dbeaver/dbeaver/issues/17520
