### ISSUE TITLE
problem in restore

### ISSUE THREAD

**Issue by soluzione-software** [dbeaver/dbeaver#17602]
### Description

when i try to restore a database i get this error:
Error executing process
  Process failed (exit code = 1). See error log.
  Process failed (exit code = 1). See error log.

ask 'MySQL restore' finished at Thu Sep 08 17:32:32 CEST 2022
2022-09-08 17:32:32.583 - IO error: Process failed (exit code = 1). See error log.
2022-09-08 17:32:32.584 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

someaone could help me please

### DBeaver Version

22.1.0

### Operating System

windows 11 home

### Database and driver

mysql 

### Steps to reproduce

if I try to restore a very small table it work's, but if the table has 5000 record it fails

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by LonwoLonwo** [comment]
Additionally, please provide your MySQL server version.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
