### ISSUE TITLE
NPEs while opening and editing object

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#17607]
### Description

From time to time I see these NPEs in my logs. I can't stable reproduce it to provide some steps.
```
java.lang.NullPointerException
	at org.eclipse.ui.part.MultiPageEditorSite.<init>(MultiPageEditorSite.java:135)
	at org.eclipse.ui.part.MultiPageEditorPart.createSite(MultiPageEditorPart.java:471)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:221)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:203)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.addEditorTab(EntityEditor.java:844)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.createPages(EntityEditor.java:608)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.recreatePages(MultiPageAbstractEditor.java:193)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.recreateEditorControl(EntityEditor.java:1071)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart.initEntityEditor(ProgressEditorPart.java:110)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:155)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.completeLoading(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:130)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
```

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.getPropertyByObject(ObjectListControl.java:751)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl$PaintListener.handleEvent(ObjectListControl.java:1233)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
```

### DBeaver Version

DBeaver 22.2.0

### Operating System

Windows 10

### Database and driver

PostgreSQL 12

**Comment by E1izabeth** [comment]
The second NPE seems to be fixed.

**Comment by E1izabeth** [comment]
Can't reproduce it anymore.
