### ISSUE TITLE
Error in the request execution plan

### ISSUE THREAD

**Issue by dencapitanblack** [dbeaver/dbeaver#17707]
### Description

Hi! I am using db2 luw and after clicking on the "Get Query execution plan" button, nothing is returned. I turned on event monitor and looked at what happens when I receive a request plan. There are question marks everywhere in the queries, what could this be related to? Below is the request log (this is the result of executing the command db2evmon -path /home/db2inst1/db2event/ > filelog.log , cat filelog.log | grep Text) 
` Text     : EXPLAIN PLAN SET QUERYNO = 166421 FOR SELECT * FROM WORKORDER

  Text     : EXPLAIN PLAN SET QUERYNO = 166421 FOR SELECT * FROM WORKORDER

  Text     : EXPLAIN PLAN SET QUERYNO = 166421 FOR SELECT * FROM WORKORDER

  Text     : SELECT * FROM SYSTOOLS.EXPLAIN_STATEMENT WHERE QUERYNO = ? AND EXPLAIN_LEVEL = 'P' WITH UR

  Text     : SELECT * FROM SYSTOOLS.EXPLAIN_STATEMENT WHERE QUERYNO = ? AND EXPLAIN_LEVEL = 'P' WITH UR

  Text     : SELECT * FROM SYSTOOLS.EXPLAIN_STATEMENT WHERE QUERYNO = ? AND EXPLAIN_LEVEL = 'P' WITH UR

  Text     : SELECT * FROM SYSTOOLS.EXPLAIN_STATEMENT WHERE QUERYNO = ? AND EXPLAIN_LEVEL = 'P' WITH UR

  Text     : SELECT *  FROM SYSTOOLS.EXPLAIN_OBJECT WHERE EXPLAIN_REQUESTER = ?   AND EXPLAIN_TIME = ?   AND SOURCE_NAME = ?   AND SOURCE_SCHEMA = ?   AND SOURCE_VERSION = ?   AND EXPLAIN_LEVEL = ?   AND STMTNO = ?   AND SECTNO = ? ORDER BY OBJECT_SCHEMA,OBJECT_NAME WITH UR

  Text     : SELECT *  FROM SYSTOOLS.EXPLAIN_OBJECT WHERE EXPLAIN_REQUESTER = ?   AND EXPLAIN_TIME = ?   AND SOURCE_NAME = ?   AND SOURCE_SCHEMA = ?   AND SOURCE_VERSION = ?   AND EXPLAIN_LEVEL = ?   AND STMTNO = ?   AND SECTNO = ? ORDER BY OBJECT_SCHEMA,OBJECT_NAME WITH UR

  Text     : SELECT *  FROM SYSTOOLS.EXPLAIN_OBJECT WHERE EXPLAIN_REQUESTER = ?   AND EXPLAIN_TIME = ?   AND SOURCE_NAME = ?   AND SOURCE_SCHEMA = ?   AND SOURCE_VERSION = ?   AND EXPLAIN_LEVEL = ?   AND STMTNO = ?   AND SECTNO = ? ORDER BY OBJECT_SCHEMA,OBJECT_NAME WITH UR

  Text     : SELECT *  FROM SYSTOOLS.EXPLAIN_OBJECT WHERE EXPLAIN_REQUESTER = ?   AND EXPLAIN_TIME = ?   AND SOURCE_NAME = ?   AND SOURCE_SCHEMA = ?   AND SOURCE_VERSION = ?   AND EXPLAIN_LEVEL = ?   AND STMTNO = ?   AND SECTNO = ? ORDER BY OBJECT_SCHEMA,OBJECT_NAME WITH UR

  Text     : SELECT *  FROM SYSTOOLS.EXPLAIN_OPERATOR WHERE EXPLAIN_REQUESTER = ?   AND EXPLAIN_TIME = ?   AND SOURCE_NAME = ?   AND SOURCE_SCHEMA = ?   AND SOURCE_VERSION = ?   AND EXPLAIN_LEVEL = ?   AND STMTNO = ?   AND SECTNO = ? ORDER BY OPERATOR_ID WITH UR
`

### DBeaver Version

22.1.5.202208211008

### Operating System

windows 10

### Database and driver

1. Database name DB2 LUW "DB2 v11.1.4.6"
2. JDBC DB2 for Linux/Unix/Windows driver jcc-11.5.0.0.jar

### Steps to reproduce

1. write " select * from table "
2. click the button "Get explain plan" (ctrl + shift + e) on query

**Comment by LonwoLonwo** [comment]
Hi.
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you

**Comment by dencapitanblack** [comment]
Hi! Here is the execution log 
`
2022-09-23 11:07:29.999 - Check EXPLAIN tables in 'MAXIMO'

2022-09-23 11:07:30.145 - EXPLAIN tables with schema MAXIMO found.

2022-09-23 11:07:30.145 - Valid explain tables found in MAXIMO

2022-09-23 11:07:30.145 - Schema=MAXIMO : EXPLAIN PLAN SET QUERYNO = 166423 FOR SELECT * FROM WORKORDER 

2022-09-23 11:07:30.561 - org.eclipse.core.runtime.AssertionFailedException: null argument:
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.jface.viewers.StructuredViewer.assertElementsNotNull(StructuredViewer.java:539)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:948)
	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:704)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1422)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:850)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:638)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:839)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:790)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1610)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:787)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1595)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1589)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.setListData(ObjectListControl.java:496)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.setListData(ObjectListControl.java:374)
	at org.jkiss.dbeaver.ui.editors.sql.plan.simple.PlanNodesTree.showPlan(PlanNodesTree.java:82)
	at org.jkiss.dbeaver.ui.editors.sql.plan.simple.SQLPlanTreeViewer.showPlan(SQLPlanTreeViewer.java:198)
	at org.jkiss.dbeaver.ui.editors.sql.plan.simple.SQLPlanViewProviderSimple.showPlan(SQLPlanViewProviderSimple.java:56)
	at org.jkiss.dbeaver.ui.editors.sql.plan.simple.SQLPlanViewProviderSimple.visualizeQueryPlan(SQLPlanViewProviderSimple.java:42)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer.visualizePlan(ExplainPlanViewer.java:300)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ProgressControl$PlanLoadVisualizer.completeLoading(ExplainPlanViewer.java:360)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ProgressControl$PlanLoadVisualizer.completeLoading(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:130)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:281)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
`

**Comment by LonwoLonwo** [comment]
Can you please check this statement:

`EXPLAIN PLAN SET QUERYNO = 166421 FOR SELECT * FROM WORKORDER`

End send the result of it (screen, maybe)?

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
