### ISSUE TITLE
Data Export in CSV format with custom Header format is impossible (NPE appears)

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#17825]
### Description

Data Export in CSV format with custom Header format is impossible (NPE appears)

### DBeaver Version

22.2.2 CE EA

### Operating System

Win10

### Database and driver

PostgreSQL

### Steps to reproduce

1. Export a table in CSV format with a changed header format

![dbeaver_P7XWpMg7Aw](https://user-images.githubusercontent.com/112612526/194234419-ffb7c787-ba7e-4c33-a2d6-3d923b0f700a.png)

**Expected**: the table is exported
**Actual result**: the table isn't exported and NPE appears

![dbeaver_AWyF7LNV7n](https://user-images.githubusercontent.com/112612526/194234583-23390c19-02f1-4836-9b95-973af9817680.png)

`
  DBException
  org.jkiss.dbeaver.DBException
    NullPointerException
    java.lang.NullPointerException
`

**Comment by LonwoLonwo** [comment]
```
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:788)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterCSV.exportHeader(DataExporterCSV.java:146)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.exportHeaderInFile(StreamTransferConsumer.java:238)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchStart(StreamTransferConsumer.java:175)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:126)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
