### ISSUE TITLE
Valid CREATE TABLE syntax throwing errors

### ISSUE THREAD

**Issue by JessycaFrederick** [dbeaver/dbeaver#17841]
### Description

CREATE TABLE winelcub_wcr2dev.affilimate_links (
  id INTEGER auto_increment NOT NULL,
  link_id INTEGER NOT NULL,
  link_type TINYINT NOT NULL,
  last_mod DATE NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

Validates here: https://www.eversql.com/sql-syntax-check-validator/

DBeaver throws error: 
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1075] [42000]: Incorrect table definition; there can be only one auto column and it must be defined as a key
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:577)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3647)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: Incorrect table definition; there can be only one auto column and it must be defined as a key
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

I tried creating the table with only field and putting an index on it, also failed.

### DBeaver Version

Community Version 22.2.1.202209251341

### Operating System

macOS 12.6

### Database and driver

Database name and version: MySQL Ver 8.0.30 for macos12.5 on arm64 (Homebrew)
Drive: com.mysql.cj.jdbc.Driver mysql8

### Steps to reproduce

Whether I try to do it through the Create Table dialog or via the script editor, I get the same errors.

**Comment by LonwoLonwo** [comment]
Hello @JessycaFrederick 

I suggest, that an increment column should be the part of the primary key in MySQL.

([url](https://www.tutorialspoint.com/fix-mysql-error-1075-42000-incorrect-table-definition-there-can-be-only-one-auto-column-and-it-must-be-defined-as-a-key))
> To fix this error, you need to add PRIMARY KEY to auto_increment field

```sql
CREATE TABLE winelcub_wcr2dev.affilimate_links (
id INTEGER auto_increment NOT NULL,
link_id INTEGER NOT NULL,
link_type TINYINT NOT NULL,
last_mod DATE NOT NULL,
PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
```

![2022-10-07 07_45_03-DBeaver 22 2 2 - _MySQL - localhost_ Script-35](https://user-images.githubusercontent.com/45152336/194469738-0548e38a-fbfc-4f21-9f5f-1aea87352e86.png)

**Comment by JessycaFrederick** [comment]
@LonwoLonwo You make an excellent point. I think the reason I didn't do this is that I can't. 

1. Clicking the Key field doesn't activate it the way it does for Default or Extra.
2. When you create a new column, the dialog doesn't have a field for Key.

Okay, I finally found it — somewhere unexpected. I right-clicked on the column entry and chose New Constraint from Selection.

Maybe the UI could allow you to create/edit Keys (constraints) by clicking on the Key field for each column?

Thank you!
<img width="552" alt="Screen Shot 2022-10-07 at 10 00 42 AM" src="https://user-images.githubusercontent.com/5640068/194611846-a6682ee8-52c6-4618-81cb-0bd55d42a1dc.png">
<img width="1318" alt="Screen Shot 2022-10-07 at 9 59 33 AM" src="https://user-images.githubusercontent.com/5640068/194611850-938bf697-1e71-4c02-8c06-6a681dd831ab.png">
