### ISSUE TITLE
[Redshift] Reference links lead to error in some cases

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#17845]
### Description

Clicking on reference link sometimes lead to error, even though the query works fine if opened in separate tab with `Ctrl + L.click` or manual execution in SQL editor.
**Note:** Some links do work in the same table

### DBeaver Version

22.2.2

### Operating System

Win11

### Database and driver

Redshift 8.0.2
Redshift JDBC 2.1.0.3

### Steps to reproduce

Our test redshift cluster table `public.event`

1. Open a table in the data editor
2. Click on a link in column `dateid` on value more than 1830

**Expected:** Referencing table is opened filtered on a corresponding key
**Actual:** Error is shown

**NOTE:** This bug won't be reproduced if references panel is opened

### Additional context

![dbeaver_qN3lssFnBY](https://user-images.githubusercontent.com/82543000/194543396-8d3e0b14-93ae-4611-9d5d-71c597417697.gif)

```
com.amazon.redshift.util.RedshiftException: ERROR: Invalid protocol sequence 'P' while in PortalSuspended state.
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

![image](https://user-images.githubusercontent.com/82543000/194543478-ee2839d0-b563-4ad6-b489-909e14473c3f.png)

**Comment by LonwoLonwo** [comment]
Can be a driver issue: https://support.tibco.com/s/article/Protocol-errors-with-Amazon-Redshift-database-ERROR-Invalid-protocol-sequence-P-while-in-PortalSuspended-state
