### ISSUE TITLE
Can no longer connect to any DB2 database - "Required property is unknown host"

### ISSUE THREAD

**Issue by 0nehand** [dbeaver/dbeaver#17903]
### Description

I've been pulling my hair out over this issue.  My DBeaver instance (version 22.2.2.202210092258) can no longer connect to any DB2 database hosts/IPs.  I've tried with a variety of driver versions

- DB2 11.1.4 (JDBC 4.0)
- DB2 11.5.5 (JDBC 4.0)
- DB2 11.5.7 (JDBC 4.0)

..and all of these give me the same error:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/23715721/195444933-8ae97dab-41a8-49e3-a344-1dde07d9b2f3.png">

Here is how I've configured the driver:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/23715721/195445102-87a701e3-6ce9-4b0f-b131-b2063faf06d4.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/23715721/195445164-b2cfd59e-4c07-4f85-8fd9-cdce5ef7d299.png">

And the connection:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/23715721/195445639-37d24a2c-efdf-44f0-bde4-52ebcc606966.png">

The Database Navigator appears to display the hostnames and ports correctly:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/23715721/195445533-17fae2eb-8d10-40bd-ace0-86fe80a89260.png">

This is what I have in the `debug.log`:

```
2022-10-12 15:57:44.861 - DBeaver 22.2.2.202210092258 is starting
2022-10-12 15:57:44.862 - OS: Mac OS X 11.5 (x86_64)
2022-10-12 15:57:44.862 - Java version: 11.0.12 by Eclipse Foundation (64bit)
2022-10-12 15:57:44.862 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2022-10-12 15:57:44.862 - Instance path: 'file:/Users/jjXXXXXXXXXXXLibrary/DBeaverData/workspace6/'
2022-10-12 15:57:44.862 - Memory available 64Mb/1024Mb
2022-10-12 15:57:44.869 - Create display
2022-10-12 15:57:45.035 - Initializing DBeaver 22.2.2
2022-10-12 15:57:45.035 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 22.2.2.202210092258
2022-10-12 15:57:45.035 - Initialize desktop platform...
2022-10-12 15:57:45.169 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.400.v20220419-0658]
> Start Core Resource Management [org.eclipse.core.resources 3.17.0.v20220517-0751]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.91.202210092258]
> Start Team Support Core [org.eclipse.team.core 3.9.400.v20220511-1440]
2022-10-12 15:57:45.326 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.100.v20210910-0640]
2022-10-12 15:57:45.335 - Platform initialized (300ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.91.202210092258]
2022-10-12 15:57:45.346 - Starting RMI server at 61983
2022-10-12 15:57:45.409 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.500.v20220506-1520]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.200.v20220513-1235]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.0.v20210115-1333]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.400.v20211102-0453]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.500.v20220511-1638]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.100.v20210722-1426]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.100.v20210910-0640]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.500.v20220511-1639]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.106.202210092258]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.100.v20220310-1056]
2022-10-12 15:57:47.020 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
2022-10-12 15:57:47.073 - Create actions
2022-10-12 15:57:47.077 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2022-10-12 15:57:47.077 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2022-10-12 15:57:47.077 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2022-10-12 15:57:47.362 - Initialize workbench window
2022-10-12 15:57:47.365 - Finish initialization
> Start Log View [org.eclipse.ui.views.log 1.3.200.v20220310-1555]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.91.202210092258]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.900.v20220108-1321]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.4.0.v20210426-0838]
> Start Internet Connection Management [org.eclipse.core.net 1.3.1200.v20220312-1450]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.81.202210092258]
2022-10-12 15:57:48.585 - Total database drivers: 102 (99)
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.128.202210092258]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.97.202210092258]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20220905153936]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20220905153936]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.51.202210092258]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.51.202210092258]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.91.202210092258]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.300.v20210913-0815]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.500.v20220331-0848]
2022-10-12 15:57:56.134 - Connect with 'bigsql (Zurich) (DB2 11.5.7)' (9A61F6D3-44ED-2CEA-A5C8-AE1C93C60FE1-183cdef7b20-6261122479c74ed)
> Start DBeaver DB2 Support [org.jkiss.dbeaver.ext.db2 2.1.176.202210092258]
2022-10-12 15:57:56.172 - Execution context opened (bigsql (Zurich) (DB2 11.5.7); Main; 0)
2022-10-12 15:57:57.455 - Connection failed (9A61F6D3-44ED-2CEA-A5C8-AE1C93C60FE1-183cdef7b20-6261122479c74ed)
org.jkiss.dbeaver.model.exec.DBCConnectException: [jcc][t4][10380][11951][4.31.10] Required property "{hdp-XXXXXXXXXXXm.com}" is unknown host. ERRORCODE=-4222, SQLSTATE=08001
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:257)
	at org.jkiss.dbeaver.ext.db2.model.DB2DataSource.openConnection(DB2DataSource.java:267)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.db2.model.DB2DataSource.<init>(DB2DataSource.java:128)
	at org.jkiss.dbeaver.ext.db2.DB2DataSourceProvider.openDataSource(DB2DataSourceProvider.java:98)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1068)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.SqlNonTransientConnectionException: [jcc][t4][10380][11951][4.31.10] Required property "{hdpXXXXXXXXXXXXXXm.com}" is unknown host. ERRORCODE=-4222, SQLSTATE=08001
	at com.ibm.db2.jcc.am.b7.a(b7.java:800)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:116)
	at com.ibm.db2.jcc.t4.a.<init>(a.java:243)
	at com.ibm.db2.jcc.t4.b.newAgent_(b.java:2173)
	at com.ibm.db2.jcc.am.Connection.initConnection(Connection.java:855)
	at com.ibm.db2.jcc.am.Connection.<init>(Connection.java:800)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:364)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:243)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:200)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:491)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	... 25 more
```

Am I doing something obviously wrong??   I've used DBeaver for years with these same datasources and only now is it giving me this trouble.

### DBeaver Version

Community Edition 22.2.2

### Operating System

macOS Monterey 12.6

### Database and driver

- DB2 11.1.4 (JDBC 4.0)
- DB2 11.5.5 (JDBC 4.0)
- DB2 11.5.7 (JDBC 4.0)

### Steps to reproduce

(above)

### Additional context

Also of note.. I am able to successfully connect to these DBs using the SAME DB2 driver from the command line:

```
% java -cp ~/Documents/Drivers/DB2/11.5.7-Linux-x86-64/db2jcc4.jar com.ibm.db2.jcc.DB2Jcc -url "jdbc:db2://hdp-XXXXXXXXXXXXXXXXXom:52000/bigsql" -user jjrXXXXXXX -password XXXXXXXX


[jcc][10521][13706]Command : java com.ibm.db2.jcc.DB2Jcc -url jdbc:db2://hdp-XXXXXXXXXXXXXom:52000/bigsql -user jjrXXXXXXXXXXXX -password ********


[jcc][10516][13709]Test Connection Successful.

DB product version = SQL110190
DB product name = DB2/LINUXX8664
DB URL = jdbc:db2://9.4.174.214:52000/bigsql
DB Drivername = IBM Data Server Driver for JDBC and SQLJ
DB OS Name = Mac OS X
```

So in that respect, my machine has a good route to the host.

**Comment by LonwoLonwo** [comment]
Hello @0nehand 

Can you please return to version 22.2.1 and check your connections there?

**Comment by 0nehand** [comment]
Hi @LonwoLonwo 
Just tested with 22.2.1.202209251341 -- same exact error.  :(

**Comment by 0nehand** [comment]
I even tested with 22.1.5 just now and still get the same error.  So something on my local setup definitely broke, but I can't tell what.  It's almost like the DB2 driver that DBeaver instantiates can't see my network interface.

**Comment by 0nehand** [comment]
I even tested this using the JRE _inside_ DBeaver's packaged files and the same driver and the connection worked

```
/Applications/DBeaver.app/Contents/Eclipse/jre/Contents/Home/bin/java -cp ~/Documents/Drivers/DB2/11.5.7-Linux-x86-64/db2jcc4.jar com.ibm.db2.jcc.DB2Jcc -url "jdbc:db2://hdXXXXXXXXXXXXXXXX.com:52000/bigsql" -user jjrXXXXXXXXX -password ***************


[jcc][10521][13706]Command : java com.ibm.db2.jcc.DB2Jcc -url jdbc:db2://hdXXXXXXXXXXXXXXXXXXX.com:52000/bigsql -user jjrXXXXXXXXXXXX -password ********


[jcc][10516][13709]Test Connection Successful.

DB product version = SQL110190
DB product name = DB2/LINUXX8664
DB URL = jdbc:db2://9.4.XXX.XXX:52000/bigsql
DB Drivername = IBM Data Server Driver for JDBC and SQLJ
DB OS Name = Mac OS X
```

So why can the actual DBeaver client connect?? 🤔

**Comment by E1izabeth** [comment]
Have you tried to write to the Host field an ip (9.4.XXX.XXX) which you get after testing connection outside the DBeaver UI?

**Comment by 0nehand** [comment]
@E1izabeth Yes, I've tried setting up the connection using an IP instead of the hostname as well and still get the same error.

**Comment by Destrolaric** [comment]
@0nehand Hi, I have looked into your connection pattern. You have a redundant curly bracket in your URL pattern. You can try to change `{{host}}` to `{host}`. Write me if it helps.

**Comment by 0nehand** [comment]
Wow, that was it...  Great catch @Destrolaric !!  Thanks a lot for pointing that out.  Really curious how that ended up happening... but for now I'll chalk it up to user error I suppose!  All is good now.
