### ISSUE TITLE
unable to open Data tag on 100 million record postgres db

### ISSUE THREAD

**Issue by loynoir** [dbeaver/dbeaver#17949]
### Description

https://dba.stackexchange.com/questions/259205/get-a-truly-random-row-from-a-postgresql-table-quickly

```sql
CREATE TABLE rand AS SELECT generate_series(1, 100000000) AS seq, MD5(random()::text);
```

Schemas > public > Tables > rand > Data

1. Long long dbeaver GUI not responding
2. Notify should exit workbench
3. Exit dbeaver GUI
4. Reopen dbeaver GUI

```txt
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space
```

### DBeaver Version

22.2.2

### Operating System

archlinux

**Comment by LonwoLonwo** [comment]
Hello @loynoir 

Probably this issue was fixed here #17865

Please check this workaround: https://github.com/dbeaver/dbeaver/issues/17865#issuecomment-1273928373
