### ISSUE TITLE
View Data option in Database Navigator fails on execution with Timescale Hypertables

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [dbeaver/dbeaver#17955]
### Description

Runs into an out of memory option. This has worked well in all the versions of the last year up to the last two.

!ENTRY org.jkiss.dbeaver.model 4 0 2022-10-17 08:58:26.663
!MESSAGE SQL Error: Internal jdbc driver error
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-10-17 08:58:26.663
!MESSAGE SQL Error: Internal jdbc driver error
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2022-10-17 08:58:26.663
!MESSAGE Internal jdbc driver error
!STACK 0
java.sql.SQLException: Internal jdbc driver error
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
        at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
        at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4949)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.OutOfMemoryError: Java heap space
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2022-10-17 08:58:26.663
!MESSAGE Java heap space
!STACK 0
java.lang.OutOfMemoryError: Java heap space

### DBeaver Version

22.2.2

### Operating System

Windows 11

### Database and driver

PostGreSql Version = 14.5  TimeScaleDb Version = 2.8.0

![dbeaver4](https://user-images.githubusercontent.com/4176416/196475520-218f63ad-ab9f-431a-9330-7c6f8f6dd670.jpg)
![dbeaver3](https://user-images.githubusercontent.com/4176416/196475524-2057126a-831c-4e59-9091-a010393013fb.jpg)
![dbeaver2](https://user-images.githubusercontent.com/4176416/196475526-a1cda1fa-8071-4164-8131-740deca9736f.jpg)
![dbeaver1](https://user-images.githubusercontent.com/4176416/196475528-a9573671-2fd0-418a-b9c4-33498a73210b.jpg)

**Comment by E1izabeth** [comment]
Could you try this workaround https://github.com/dbeaver/dbeaver/issues/17865#issuecomment-1273928373 ?
Please, let me know if it helps.

**Comment by E1izabeth** [comment]
Does this issue still actual for the latest DBeaver version?
