### ISSUE TITLE
NPE for PKCS8 keys

### ISSUE THREAD

**Issue by Destrolaric** [dbeaver/dbeaver#17971]
Using PKC8 keys produces following NPE
```
java.lang.NullPointerException
	at com.jcraft.jsch.KeyPairPKCS8.getPublicKeyBlob(KeyPairPKCS8.java:199)
	at com.jcraft.jsch.IdentityFile.getPublicKeyBlob(IdentityFile.java:71)
	at com.jcraft.jsch.LocalIdentityRepository.add(LocalIdentityRepository.java:63)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:470)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:407)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at org.jkiss.dbeaver.model.net.ssh.SSHUtils.isKeyFileEncrypted(SSHUtils.java:66)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.getRequiredCredentials(SSHTunnelImpl.java:130)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$8.execute(SSHTunnelConfiguratorUI.java:299)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:733)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

_Originally posted by @Matvey16 in https://github.com/dbeaver/dbeaver/issues/17806#issuecomment-1282349650_

**Comment by ljluestc** [comment]
```
package com.jcraft.jsch;

import java.io.*;
import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.interfaces.RSAPrivateCrtKey;

public class KeyPairPKCS8 extends KeyPair {

    // Assuming other fields and methods are here...

    public byte[] getPublicKeyBlob() throws JSchException {
        if (this.privateKey == null) {
            throw new JSchException("Private key not loaded");
        }

        try {
            KeyFactory kf = KeyFactory.getInstance("RSA");
            PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(this.privateKey);
            RSAPrivateCrtKey privKey = (RSAPrivateCrtKey) kf.generatePrivate(keySpec);

            // Here, we ensure that the public key components are available
            if (privKey.getPublicExponent() == null || privKey.getModulus() == null) {
                throw new JSchException("Public key components missing from private key");
            }

            // Construct the public key blob
            byte[] foo = new byte[4];
            foo[0] = (byte) (7 & 0xff);
            foo[1] = (byte) (0 & 0xff);
            foo[2] = (byte) (0 & 0xff);
            foo[3] = (byte) (1 & 0xff);
            byte[] pubArray = privKey.getModulus().toByteArray();
            byte[] expArray = privKey.getPublicExponent().toByteArray();
            byte[] blob = new byte[foo.length + pubArray.length + expArray.length];

            System.arraycopy(foo, 0, blob, 0, foo.length);
            System.arraycopy(pubArray, 0, blob, foo.length, pubArray.length);
            System.arraycopy(expArray, 0, blob, foo.length + pubArray.length, expArray.length);

            return blob;
        } catch (Exception e) {
            throw new JSchException("Failed to get public key blob: " + e.getMessage(), e);
        }
    }

    // Other methods...

}
```
