### ISSUE TITLE
Salesforce CDP SSO Connectivity

### ISSUE THREAD

**Issue by mimo76** [dbeaver/dbeaver#18014]
Trying to establish a connection to Salesforce CDP following the instructions outlined here: https://help.salesforce.com/s/articleView?id=sf.c360_a_set_up_tableau_connected_app.htm&type=5

I have used these instructions on other CDP instances and am able to connect and query data as expected.  Recently tried to integrate with a new CDP instance that is using SSO and am unable to get an established connection.  I have attempted to adjust driver settings for Embedded and No authentication, but all test connections result in an authentication failure.  I should mention that I am connected to the organization through a VPN, in case that is a factor. 

Below is a log excerpt of the authentication failure:
!ENTRY org.jkiss.dbeaver.model 4 0 2022-10-24 10:17:04.576
!MESSAGE authentication failure
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-10-24 10:17:04.576
!MESSAGE authentication failure
!STACK 0
java.io.IOException: authentication failure
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:45)
	at com.salesforce.cdp.queryservice.util.HttpHelper.handleErrorResponse(HttpHelper.java:36)
	at com.salesforce.cdp.queryservice.util.TokenHelper.un_pw_login(TokenHelper.java:269)
	at com.salesforce.cdp.queryservice.util.TokenHelper.retrieveTokenWithPasswordGrant(TokenHelper.java:112)
	at com.salesforce.cdp.queryservice.util.TokenHelper.getToken(TokenHelper.java:72)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.lambda$getTokenWithTenantUrl$2(QueryExecutor.java:182)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getTokenWithTenantUrl(QueryExecutor.java:181)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.executeQuery(QueryExecutor.java:92)
	at com.salesforce.cdp.queryservice.core.QueryServiceAbstractStatement.executeQuery(QueryServiceAbstractStatement.java:72)
	at com.salesforce.cdp.queryservice.core.QueryServicePreparedStatement.execute(QueryServicePreparedStatement.java:158)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.isValid(QueryServiceConnection.java:344)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.<init>(QueryServiceConnection.java:59)
	at com.salesforce.cdp.queryservice.QueryServiceDriver.connect(QueryServiceDriver.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:191)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:208)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:113)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:953)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:887)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @mimo76 

Maybe this advice can help you. https://github.com/dbeaver/dbeaver/issues/17542#issuecomment-1239616214

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
