### ISSUE TITLE
Unexpected driver error occurred while connecting to the database   

### ISSUE THREAD

**Issue by Katy1320** [dbeaver/dbeaver#18078]
### Description

I tried to connect  informix database in mac class java.lang.StringIndexOutOfBoundsException cannot be cast to class java.sql.SQLException (java.lang.StringIndexOutOfBoundsException is in module java.base of loader 'bootstrap'; java.sql.SQLException is in module java.sql of loader 'platform') this error has occured .

### DBeaver Version

Community Edition 22.2.3

### Operating System

macOS Monterey 12.6 

### Database and driver

databse :informix 
driver details : 
ifxjdbc.jar
ifxlang.jar

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Katy1320** [comment]
<img width="1727" alt="Screenshot 2022-10-31 at 9 38 03 AM 1" src="https://user-images.githubusercontent.com/104082981/198929090-75d23c5e-6b49-42bb-8b86-21050559a3fe.png">
these are listed in exception stack trace.
java.lang.ClassCastException: class java.lang.StringIndexOutOfBoundsException cannot be cast to class java.sql.SQLException (java.lang.StringIndexOutOfBoundsException is in module java.base of loader 'bootstrap'; java.sql.SQLException is in module java.sql of loader 'platform')
	at com.informix.jdbc.IfxDriver.connect(IfxDriver.java:274)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:988)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Katy1320** [comment]
can you please provide update on this issue ??

**Comment by E1izabeth** [comment]
Could you provide database version you are trying to connect to?
Do you use the default driver for Influx automatically downloaded by DBeaver?

**Comment by Katy1320** [comment]
No its is not automatically downloaded driver .same driver was  provided for both but  windows users able to login using those drivers but in mac it shows this error.can you please suggest how to use automatically downloaded drivers for informix?? Will it fix this issue.

**Comment by E1izabeth** [comment]
Do you know the version of the driver you are trying to use?

**Comment by Katy1320** [comment]
when i used java com.informix.jdbc.Version this command to find driver version it shows 
Could not find or load main class com.informix.jdbc.Version
Caused by: java.lang.ClassNotFoundException: com.informix.jdbc.Version dont know about other ways to find version.
JDBC drivers are in dwonloads folder in mac does it needs any prerequisite like setting up path.

**Comment by Katy1320** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/104082981/199695409-dcb45d7a-b363-4b09-a116-cbf2c620be1c.png">
is this correct class path shouldn't be the jar file directory ?? should i have to add class path for driver in mac for dbeaver ?/

**Comment by Katy1320** [comment]
@ShadelessFox @E1izabeth  @n5a5  I request to get this issue to be fixed soon.  same issues occurred for mac users at work .

**Comment by Katy1320** [comment]
If i used automatically downloaded informix 4.50.4.1jdbc driver along with bson jar 3.8.0 version .it shows socket connection error. @n5a5 @E1izabeth

**Comment by Katy1320** [comment]
Issue resolved with older versions of dbeaver

**Comment by E1izabeth** [comment]
Thank you for replying to us. We'll try to investigate this issue. It's not good that it can't work on the latest DBeaver version.

**Comment by LonwoLonwo** [comment]
![2022-12-22 17_18_44-Window](https://user-images.githubusercontent.com/45152336/209154180-d48b8a4a-f15f-4201-aa2a-8438ed04325c.png)

Hello @Katy1320 
Please try to use another driver version.
