### ISSUE TITLE
show queries total row count syntax error

### ISSUE THREAD

**Issue by Uniquely6958** [dbeaver/dbeaver#18113]
### Description

When trying to calculate total row count for a "show tables" command, where the total number of tables are greater than what is currently been displayed, I get an syntax error message.

You will get an error message along the following lines:

```
Error executing row count
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show tables
) dbvrcnt' at line 1
```

Relevant logs:
```
eclipse.buildId=unknown
java.version=19.0.1
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_CA
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Nov 03 02:56:43 EDT 2022
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show tables
) dbvrcnt' at line 1

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'show tables
) dbvrcnt' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:3768)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$44(ResultSetViewer.java:3936)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3931)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1745)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$9$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### DBeaver Version

22.2.3

### Operating System

Arch Linux

### Database and driver

Database: MySQL 8.0
Driver: JDBC

### Steps to reproduce

1. Open a MySQL connection to a database with more than 1 table.
2. Reduce "Result-set fetch size" to a number less than the number of tables in database.
3. Enter and execute "show tables" in the query editor.
4. Once you get the result (which will be less than the actual number of tables), click on "Calculate total row count" below the result, on the results pane.

**Comment by Uniquely6958** [comment]
I would like to work on this issue.

I found that for these type of queries (`show tables;`, `show databases;`), the query naturally fails to get injected or transformed into a query that can be used for counting rows. As a fallback, the query is surrounded with `SELECT COUNT(*) FROM` and `) dbvrcnt`. I fail to see which queries would benefit from this fallback method.

So for all queries that are not of the type Select, would it make sense to run them normally without limits and simply return the length of the results?
