### ISSUE TITLE
Doris incompatible connection

### ISSUE THREAD

**Issue by yuanyuan8983** [dbeaver/dbeaver#18189]
### Description

When I use DBeaver to connect to Doris, an error occurs when I change the schema, but there is no problem in Doris. My operation at that time is add column I hope it is compatible with this part, because we use Doris more often.

ALTER TABLE nhm.collect_device ADD COLUMN compute_time bigint  NULL COMMENT "" AFTER out_traffic;

error:
2022-11-11 10:40:31,782 WARN (doris-mysql-nio-pool-277|235758) [ConnectProcessor.handleQuery():226] Process one query failed because.
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Please check your sql, we meet an error when parsing.
 at org.apache.doris.qe.ConnectProcessor.analyze(ConnectProcessor.java:267) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:200) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:349) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:538) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[doris-fe.jar:1.0-SNAPSHOT]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
 at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
Caused by: java.lang.Error: Error: could not match input
 at org.apache.doris.analysis.SqlScanner.zzScanError(SqlScanner.java:1084) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.analysis.SqlScanner.next_token(SqlScanner.java:1432) ~[doris-fe.jar:1.0-SNAPSHOT]
 at java_cup.runtime.lr_parser.scan(lr_parser.java:349) ~[jflex-1.4.3.jar:?]
 at java_cup.runtime.lr_parser.parse(lr_parser.java:578) ~[jflex-1.4.3.jar:?]
 at org.apache.doris.common.util.SqlParserUtils.getMultiStmts(SqlParserUtils.java:59) ~[doris-fe.jar:1.0-SNAPSHOT]
 at org.apache.doris.qe.ConnectProcessor.analyze(ConnectProcessor.java:265) ~[doris-fe.jar:1.0-SNAPSHOT]
 ... 7 more

### DBeaver Version

22.2.3

### Operating System

centos

### Database and driver

doris-1.1.3

### Steps to reproduce

ALTER TABLE nhm.collect_device ADD COLUMN compute_time bigint  NULL COMMENT "" AFTER out_traffic;

**Comment by LonwoLonwo** [comment]
Hello @yuanyuan8983 

Did you try to execute this query in the SQL Editor and it failed?

`ALTER TABLE nhm.collect_device ADD COLUMN compute_time bigint NULL COMMENT "" AFTER out_traffic;`

Or was this query created by DBeaver?

Can you provide steps for your issue?

https://doris.apache.org/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-COLUMN/

**Comment by yuanyuan8983** [comment]
Yes, I succeed in Doris client, but fail in DBeaver

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
