### ISSUE TITLE
DB CE 22.2.4 Linux - Unhandled event loop exception: No more handles

### ISSUE THREAD

**Issue by mj162** [dbeaver/dbeaver#18197]
### Description

**1. Expected Behaviour**
1. Install from dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk.tar.gz
2. Launch dbeaver using existing java version "11.0.9" 2020-10-20 LTS
3. File > Open
4. Able to load source and continue working on it

**2. Observed Behaviour**
1. Install from dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk.tar.gz
2. Launch dbeaver using existing java version "11.0.9" 2020-10-20 LTS
3. File > Open
Alert: Problem Occurred: Unhandled event loop exception: No more handles (or.eclipse.ui, org.jkiss.dbeaver.model)

***3. Java Paths and Arguments***
```bash
JVM terminated. Exit code=127
/media/shared/opt/jdk11/x86_64/bin/java
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-jar /tmp/tmpfs/media/shared/opt/dbeaver/dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /tmp/tmpfs/media/shared/opt/dbeaver/dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk/dbeaver
-name Dbeaver
--launcher.library /tmp/tmpfs/media/shared/opt/dbeaver/dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.600.v20220720-1916/eclipse_11701.so
-startup /tmp/tmpfs/media/shared/opt/dbeaver/dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.overrideVmargs
-exitdata 1820050
-vm /media/shared/opt/jdk11/x86_64/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-jar /tmp/tmpfs/media/shared/opt/dbeaver/dbeaver-ce-22.2.4-linux.gtk.x86_64-nojdk//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
```

**4. Similar/Related Previous Reports**
[[Edge] no more handles #17489](https://github.com/dbeaver/dbeaver/issues/17489)

**5. Attempted Diagnosis & Resolution**
1. Install from dbeaver-ce-22.2.4-linux.gtk.x86_64.tar.gz
2. Launch dbeaver using provided java version openjdk 11.0.12 2021-07-20
3. File > Open.  Crashed in the same way logging to the terminal:

```bash
***WARNING: GTK+ version too old (micro mismatch)
***WARNING: SWT requires GTK 3.22.0
***WARNING: Detected: 3.18.9
```

**6. Resolution Requested**
As a work-around, notification of the last version of DBeaver CE to support GTK 3.18.9.  Thank you.

### DBeaver Version

Community Edition 22.2.4

### Operating System

HP ThinPro 7.1 (Ubuntu 16.04 LTS)

### Database and driver

N/A

### Steps to reproduce

[As above]

### Additional context

[As above]

**Comment by mj162** [comment]
**7. SOLVED**
Uncertain from the Release Notes when the minimum supported version of GTK 3 was bumped.  By trial-and-error the results, tabulated below, were found.

| Version | Crashes | File Open/Save    |
| ------- | ------- | ----------------- |
| 22.2.4  | Yes     | Dialogue fails    |
| 21.2.4  | Yes     | Dialogue fails    |
| 21.1.5  | Yes     | Dialogue fails    |
| 21.1.0  | Yes     | Dialogue fails    |
| 21.0.5  | Yes     | Dialogue fails    |
| 21.0.4  | Yes     | Dialogue fails    |
| 21.0.3  | Yes     | Dialogue fails    |
| 21.0.0  | Yes     | Dialogue fails    |
| 7.3.4   | Yes     | Dialogue fails    |
| 7.3.3   | No      | Dialogue fails    |
| 7.3.2   | No      | Dialogue fails    |
| 7.3.1   | No      | Dialogue fails    |
| 7.3.0   | No      | Dialogue displays |

**Comment by E1izabeth** [comment]
Thank you for bug report and investigation.

**Comment by Destrolaric** [comment]
@mj162 Hi, I see you have a pretty old version of GTK. You can solve it by updating it via your package manager. `apt-get update` should help with that.
 And we should probably add info about min lib requirements in our wiki.

**Comment by Destrolaric** [comment]
Linked ticket about wiki https://github.com/dbeaver/dbeaver/issues/18209

**Comment by mj162** [comment]
@Georgii Hi,

No. Where a thin client or other device where the flash is write-
locked by the manufacturer is being used, nothing can be run that
changes the OS and remain manufacturer-supported.

Will migrate real soon now but with popular apps being published
in formats that defy OS EOL, there's no hurry for the most part.

----- Original Message -----
From: Georgii ***@***.***>
To: dbeaver/dbeaver ***@***.***>
Cc: mj162 ***@***.***>, Mention 
***@***.***>
Subject: Re: [dbeaver/dbeaver] DB CE 22.2.4 Linux - Unhandled event loop exception: 
No more handles (Issue #18197)

@mj162 Hi, I see you have a pretty old version of GTK. You can solve it by updating 
it via you package manager. `apt-get update` should help with that.

**Comment by Destrolaric** [comment]
@mj162 Unfortunately issue with unsupported GTK comes from our framework. We currently use Eclipse 2022/09 for our build, so all libraries are inherited from it.

**Comment by mj162** [comment]
@Georgii, Sure, and I should appreciate that I have other tools that
the developers have built on Eclipse.  Thank you.

----- Original Message -----
Date: Tue, 15 Nov 2022 03:17:48 -0800
From: Georgii ***@***.***>
To: dbeaver/dbeaver ***@***.***>
Cc: mj162 ***@***.***>, Mention 
***@***.***>
Subject: Re: [dbeaver/dbeaver] DB CE 22.2.4 Linux - Unhandled event loop exception: 
No more handles (Issue #18197)

@mj162 Unfortunately issue with unsupported GTK comes from our framework. We 
currently use Eclipse 2022/09 for our build, so all libraries are inherited from 
it.

**Comment by krilim** [comment]
Hi, I am using Fedora 37 with all updates and I am getting same error. App version is **22.2.5**

`org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:151)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2901)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.<init>(DatabaseNavigatorTree.java:151)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.<init>(DatabaseNavigatorTree.java:118)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.createNavigatorTree(NavigatorViewBase.java:116)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.createPartControl(NavigatorViewBase.java:101)
	at org.jkiss.dbeaver.ui.navigator.project.ProjectNavigatorView.createPartControl(ProjectNavigatorView.java:80)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:403)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1209)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:51)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:82)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:64)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
`

**Comment by horvatha** [comment]
I have similar error when I want to export a table

```
ii  dbeaver-ce        23.1.3           amd64        DBeaver Community
ii  libgtk-3-0:amd64  3.24.33-1ubuntu2 amd64        GTK graphical user interface library
ii  libgtk2.0-0:amd64 2.24.33-2ubuntu2 amd64        GTK graphical user interface library - old version
```
on Ubuntu 22.04 running in Hyper-V. It haven't had this problem before. (Maybe before the last update but I'm not sure).

**UPDATE:** I've removed the workspace6 directory from ~/.local/share/DBeaverData and the error messages seem to gone. (But I needed to set the database connections again. :-( )

**UPDATE:** It have not solved the problem. It still exists. It copied a large table (in chunks) from psql to a separate psql instance and the problem started again.

**Comment by E1izabeth** [comment]
Is this issue still relevant for the latest DBeaver version?

**Comment by mj162** [comment]
Hi Elizabeth,

Switched to AppImage 25.3.4 as it was more convenient to deploy in local environment and hadn't run it since then.  Tried now and it prompts to update to 26.0.2.  26.0.0 is available as an AppImage.  Updated to that but it still abends on File->Open.  Could be local issue that will resolve on reboot.

----- Original Message -----
Date: Fri, 17 Apr 2026 23:29:40 -0700

**Comment by mj162** [comment]
Hello Elizabeth,

Recall issue #18197 raised Nov last year in relation to OS: HP ThinPro 7.1 (Ubuntu 16.04 LTS).

OS since upgraded to HP ThinPro 8.1 (Ubuntu 22.04 LTS).

Please note therefore that issue response yesterday (attempt to run AppImage DB 26.0.0) was carried-out on HP ThinPro 8.1 (Ubuntu 22.04 LTS).

Tried DB 26.0.2 from:
https://dbeaver.io/files/26.0.2/dbeaver-ce-26.0.2-linux-x86_64.tar.gz (no, nojdk)

File->Open abends with
```bash
...
(DBeaver:1532995): GLib-GIO-ERROR **: 15:54:52.023: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
```

A SOLVED posted at https://bbs.archlinux.org/viewtopic.php?id=254193 suggested either the settings schema could not be located within `$XDG_DATA_DIRS` or that the schema file is old/broken and needs to be updated.

Here is what I found:

```bash
$ echo $XDG_DATA_DIRS
/writable/etc/:/writable/usr/local/share/:/writable/usr/local/share/applications/:/media/GenericFlash_sdb1/usr/local/share/:/media/GenericFlash_sdb1/usr/share/:/usr/share/:/usr/local/share/

$ grep show-type-column /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
    <key name='show-type-column' type='b'>

$ ls -l /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
-rw-r--r-- 1 root root 6212 May 10  2023 /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml

$ md5sum /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
39d47714b7cf1852146e9019a0746c23  /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
```

Check against up-to-date Debian 6.12.63-1:

```bash
$ ls -l /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
-rw-r--r-- 1 root root 6212 Mar  5  2025 /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml

$ md5sum /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
39d47714b7cf1852146e9019a0746c23  /usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml
```

So HP ThinPro 8.1 (Ubuntu 22.04 LTS) has the latest schema file and it should be locatable from `$XDG_DATA_DIRS`.

Realising that in OS update, apps on removable flash and that allowed local customisations in /writable (OS flash is write-locked) referred to carried-over customisations from HP ThinPro 7.1 (Ubuntu 16.04 LTS), re-ran having removed these paths from `$XDG_DATA_DIRS`:

```bash
$ echo $XDG_DATA_DIRS
/writable/etc/:/writable/usr/local/share/:/writable/usr/local/share/applications/:/media/GenericFlash_sdb1/usr/local/share/:/media/GenericFlash_sdb1/usr/share/:/usr/share/:/usr/local/share/

$ bash

$ export XDG_DATA_DIRS=/usr/share/:/usr/local/share/

$ echo  $XDG_DATA_DIRS
/usr/share/:/usr/local/share/
```

For completeness, re-tried the DB 26.0.0 AppImage.  It also successfully opened the file dialogue box.

Resolution having been achieved for both DB 26.0.0 AppImage and 26.0.2 tar ball binary, happy for the issue to be closed. :)

(Will likely use the AppImage as the maintainer is doing a good job keeping it up to date and it simplifies deployment in an otherwise locked-down environment.)
