### ISSUE TITLE
When developing a new JDBC connector, how to know which functions are called by the DBeaver client and what the required return value is.

### ISSUE THREAD

**Issue by justinSmileDate** [dbeaver/dbeaver#18261]
**I'm working on DBeaver's JDBC connector for a new database. But I don't know which APIs DBeaver's clients need to call.**

I try to print jdbc-api-trace.log, but the content in the log seems to be unable to see which functions are called by the client.
I'm also looking for the function in the error log(main menu Window->Show View->Error Log) , but it doesn't feel right either.

The error log content is as follows:
java.sql.SQLException: ResultSet is closed
	at com.dolphindb.jdbc.JDBCResultSet.checkClosed(JDBCResultSet.java:1445)
	at com.dolphindb.jdbc.JDBCResultSet.next(JDBCResultSet.java:150)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getCatalogsNames(GenericDataSource.java:561)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:512)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.refreshObject(GenericDataSource.java:628)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.refreshObject(DataSourceDescriptor.java:691)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:358)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:356)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:281)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:188)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Another log is as follows:**
!ENTRY org.jkiss.dbeaver.model 1 44 2022-11-18 17:10:27.867
!MESSAGE -- Load catalogs
!SUBENTRY 1 org.jkiss.dbeaver.model 1 0 2022-11-18 17:10:27.868
!MESSAGE SUCCESS [-1]

!ENTRY org.jkiss.dbeaver.model 1 42 2022-11-18 17:10:27.864
!MESSAGE -- Load type info
!SUBENTRY 1 org.jkiss.dbeaver.model 1 0 2022-11-18 17:10:27.867
!MESSAGE SUCCESS [-1]

!ENTRY org.jkiss.dbeaver.model 0 40 2022-11-18 17:10:27.859
!MESSAGE BEGIN SESSION [dolphindbnew]

!ENTRY org.jkiss.dbeaver.model 0 39 2022-11-18 17:10:27.831
!MESSAGE BEGIN SESSION [dolphindbnew]

!ENTRY org.jkiss.dbeaver.model 1 46 2022-11-18 17:10:29.848
!MESSAGE -- Load schemas [system_db, %]
!SUBENTRY 1 org.jkiss.dbeaver.model 1 0 2022-11-18 17:10:29.849
!MESSAGE SUCCESS [-1]

It looks like something is wrong with **Load catalogs()** and **Load schemas()**, but I don't know the correct parameters that the above functions need, where should I look.

**Comment by ShadelessFox** [comment]
Hello @justinSmileDate,

Please take a look [here](https://github.com/dbeaver/dbeaver/tree/devel/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/exec).
