### ISSUE TITLE
unhandled due to prior sendError

### ISSUE THREAD

**Issue by liukekeke** [dbeaver/dbeaver#18310]
### Description

19:12:47.694 [main] INFO  o.e.j.s.s.DefaultSessionIdManager - Session workerName=
19:12:47.765 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@375084c9{/,file:///root/liuke/cloudbeaver/web/,AVAILABLE}
19:12:47.795 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@502a4156{HTTP/1.1, (http/1.1)}{0.0.0.0:8978}
19:12:47.798 [main] INFO  org.eclipse.jetty.server.Server - Started JettyServer@4ea1aa52{STARTING}[10.0.9,sto=0] @11412ms
19:13:20.732 [qtp1595180029-42] WARN  org.eclipse.jetty.server.HttpChannel - /
java.lang.IllegalStateException: Response is committed
	at org.eclipse.jetty.server.Request.getSession(Request.java:1538) ~[na:na]
	at io.cloudbeaver.server.servlets.CBStaticServlet.doPost(CBStaticServlet.java:63) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[na:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[na:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[na:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[na:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[na:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[na:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[na:na]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
19:13:20.759 [qtp1595180029-42] WARN  o.e.jetty.server.HttpChannelState - unhandled due to prior sendError
java.lang.IllegalStateException: Response is committed
	at org.eclipse.jetty.server.Request.getSession(Request.java:1538) ~[na:na]
	at io.cloudbeaver.server.servlets.CBStaticServlet.doPost(CBStaticServlet.java:63) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:508) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[na:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[na:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[na:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[na:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[na:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[na:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[na:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[na:na]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[org.eclipse.jetty.util_10.0.9.jar:10.0.9]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

### DBeaver Version

22.2.2

### Operating System

linux7.9

### Steps to reproduce

1、start server 
2、access

**Comment by LonwoLonwo** [comment]
Hello. Please provide more info about your problem. At least - steps to reproduce.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
