### ISSUE TITLE
Cannot query clickhouse

### ISSUE THREAD

**Issue by strokovnjaka** [dbeaver/dbeaver#18392]
### Description

While I can connect to my clickhouse instance (I can see the databases, their tables, etc.), I cannot get dbeaver to perform any queries, e.g. not even a `select 1`. The error I get is 

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1002] [07000]: Connection reset, server ClickHouseNode [uri=http://192.168.11.12:8123/testdb, options={compress=true,client_name=ClickHouse Java Client}]@-807902090
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:544)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:451)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:847)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3515)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4854)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Connection reset, server ClickHouseNode [uri=http://192.168.11.12:8123/testdb, options={compress=true,client_name=ClickHouse Java Client}]@-807902090
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:96)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:304)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:292)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:162)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:289)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:1972)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:94)
	... 18 more
```

### DBeaver Version

Community Edition 22.0.2.202204041542

### Operating System

Microsoft Windows 10 Enterprise, 10.0.19045 Build 19045

### Database and driver

1. ClickHouse server version 22.11.1.1360 (official build)
2. com.clickhouse.jdbc.ClickHouseDriver = Yandex ClickHouse driver (server version 21.3+)

### Steps to reproduce

1. connect to db, works as expected
2. open new sql script, enter `select 1`, use `Execute SQL statement`
3. error(s) are reported 

### Additional context

From the same client I can successfully query via curl
```
> curl 'http://192.168.11.12:8123/?user=default&query=select+1'
StatusCode        : 200
StatusDescription : OK
Content           : 1
```

**Comment by strokovnjaka** [comment]
Upgraded dbeaver to 22.2.5.202211202223, driver is the same i.e. `com.clickhouse.jdbc.ClickHouseDriver` = Yandex ClickHouse driver (server version 21.3+) version `0.3.2-patch11`

Querying still does not work, but viewing table (e.g. with F4) does.

**Comment by strokovnjaka** [comment]
I tried the `ru.yandex.clickhouse.ClickHouseDriver` version `0.3.2` and it works! I suppose this means the change in switch from `ru.yandex...` to `com.clickhouse...` will show the problem.

**Comment by iraidaa** [comment]
Hello @strokovnjaka,

Thank you for the report and for sharing the results.

Usually, in similar cases, we recommend checking if the database has limits on the number of connections to it. If that is the case, we recommend right-clicking the connection in the navigator, choosing Edit Connection, setting Never in the ‘Open separate connection for each editor’ in the SQL Editor tab, and setting Never in the ‘Open separate connection for metadata read’ in the Metadata tab.

**Comment by strokovnjaka** [comment]
@iraidaa thanks!

As I can control the db, I made sure no connections are made to it, then:
- if I connect with `ru.yandex.clickhouse.ClickHouseDriver` version `0.3.2` query `select 1` does work
- if I connect with `com.clickhouse.jdbc.ClickHouseDriver` version `0.3.2` (or `0.3.2-patch11`) query `select 1` does not work.

Note that browsing data or properties of db object e.g via F4 works in both cases.

Hence, it seems this has nothing to do with the number of connections but something changing from `ru.yandex...` to `com...` variants of the driver.

**Comment by iraidaa** [comment]
@strokovnjaka thank you for sharing the solution!
