### ISSUE TITLE
There is nothing in the dashboard

### ISSUE THREAD

**Issue by fantasy0v0** [dbeaver/dbeaver#18398]
### Description

There is nothing in the dashboard

### DBeaver Version

Version 22.2.4.202211062135

### Operating System

Windows 11 Pro 22H2 22621.819

### Database and driver

PostgreSQL 15.0
PostgreSQL JDBC Driver 42.5

### Steps to reproduce

![01CEE34ZBIS2C6D9DYMWFHM](https://user-images.githubusercontent.com/9549027/205022065-05cd4b59-e32a-4fd7-ac4a-bdfd2ec37467.png)

**Comment by LonwoLonwo** [comment]
Could you please check the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by fantasy0v0** [comment]
Error Log view

[1.log](https://github.com/dbeaver/dbeaver/files/10137276/1.log)

**Comment by LonwoLonwo** [comment]
Ok, I see...

```
!ENTRY org.eclipse.ui 4 0 2022-12-02 08:47:42.865
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.Win32FontManager
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.desktop/sun.font.FontManagerFactory$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(Unknown Source)
	at java.desktop/java.awt.Font.getFont2D(Unknown Source)
	at java.desktop/java.awt.Font.getFamily(Unknown Source)
	at java.desktop/java.awt.Font.getFamily_NoClientCode(Unknown Source)
	at java.desktop/java.awt.Font.getFamily(Unknown Source)
	at org.jfree.swt.SWTUtils.toSwtFontData(SWTUtils.java:116)
	at org.jfree.swt.SWTGraphics2D.getSwtFontFromPool(SWTGraphics2D.java:1417)
	at org.jfree.swt.SWTGraphics2D.setFont(SWTGraphics2D.java:949)
```

Did you change any standard font in the preferences?

**Comment by fantasy0v0** [comment]
I didn't change any fonts. What fonts are used in dbeaver's dashboard?

**Comment by fantasy0v0** [comment]
I found the problem.I installed dbeaver from the Microsoft Store.

**Comment by LonwoLonwo** [comment]
Ok, we can't reproduce it on Windows 10 or 11, but now we will look into the Microsoft Store version to check.

**Comment by E1izabeth** [comment]
Reproducible on DBeaver installed through Microsoft Store

**Comment by E1izabeth** [comment]
It is a bug in openjdk https://bugs.openjdk.org/browse/JDK-8251367 which has been already fixed and should not appear on the java 17. So, maybe it will be fixed with transition to JDK17 dbeaver/pro#1336

**Comment by E1izabeth** [comment]
Still doesn't work on Windows Store version 22.3.4, but with another error
![image](https://user-images.githubusercontent.com/28875055/216942862-719ad333-072e-41ca-9c23-ba922bf88fb1.png)

```
java.lang.UnsatisfiedLinkError: C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\javaaccessbridge.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(AccessBridge.java:122)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(AccessBridge.java:120)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:460)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.initStatic(AccessBridge.java:119)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(AccessBridge.java:86)
	at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(ProviderImpl.java:58)
	at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Toolkit.java:533)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:528)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:605)
	at java.desktop/javax.swing.UIManager.<clinit>(UIManager.java:389)
```

**Comment by flambchap** [comment]
@E1izabeth As you can see from the error, the win store version uses your local Java. In fact, it's a bug in packaging https://github.com/dbeaver/dbeaver/issues/18960

**Comment by E1izabeth** [comment]
Still reproducible on DBeaver 23.0.0
![image](https://user-images.githubusercontent.com/28875055/225102615-c3888ca5-14c5-4266-a86e-f69e3bcfa787.png)

```
java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
	at org.jfree.chart.ChartFactory.createXYLineChart(ChartFactory.java:2002)
	at org.jkiss.dbeaver.ui.dashboard.histogram.DashboardRendererTimeseries.createDashboard(DashboardRendererTimeseries.java:63)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.createChartRenderer(DashboardItem.java:108)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.<init>(DashboardItem.java:93)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardList.addItem(DashboardList.java:218)
	at org.jkiss.dbeaver.ui.dashboard.view.HandlerDashboardAddItem.execute(HandlerDashboardAddItem.java:36)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
        ...
```

**Comment by n5a5** [comment]
@E1izabeth Strangely enough, I cannot reproduce it on any 23.0 release builds on my machine! (mac on AArch64)

**Comment by DidotCepot** [comment]
I have a similar problem, but its just the fonts not showing up
![image](https://github.com/dbeaver/dbeaver/assets/51727407/ca22e0c5-fb36-4ea0-8890-c59e2a24c1e9)
