### ISSUE TITLE
Unable to create new database connection in DBeaver Community 22.2.5 on macOS Ventura 13.0.1 on external display

### ISSUE THREAD

**Issue by zach-betz-hln** [dbeaver/dbeaver#18458]
### Description

See the title 🙂 

### DBeaver Version

Community Edition 22.2.5

### Operating System

macOS Ventura 13.0.1

### Database and driver

I was not able to get this far. See "steps to reproduce"

### Steps to reproduce

1. Click **File**
1. Click **New** 
1. Click **DBeaver** folder
1. Click **Database Connection**
1. Click **Next** (the first click doesn't fire, you have to click **Next** twice)
1. Click **PostgresSQL**
1. Click **Next**
1. Notice the **Connection Settings** dialog is blank

### Additional context

Here's a screenshot of the blank dialog I see

![Screenshot 2022-12-06 at 8 38 55 AM](https://user-images.githubusercontent.com/119352232/205941662-6f26acfe-5a91-4c15-b219-296bc45d4644.png)

**Comment by OlgaChuianovaArammeem** [comment]
The same problem with DBeaver Community 22.3.0 on Intel with macOS Ventura 13.0.1

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by zach-betz-hln** [comment]
@LonwoLonwo - Sure, here you go. 

I zipped up these files:

```
~/Library/DBeaverData/workspace6/.metadata/.log
~/Library/DBeaverData/workspace6/.metadata/dbeaver-debug.log
```

[dbeaver_logs.zip](https://github.com/dbeaver/dbeaver/files/10167931/dbeaver_logs.zip)


This stacktrace looks relevant:

<details>
<summary>Details</summary>

```
2022-12-06 08:31:42.981 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2022-12-06 08:32:09.098 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2022-12-06 08:32:12.781 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2022-12-06 08:38:08.874 - Event loop exception
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSWindow.contentView()" because "window" is null
	at org.eclipse.swt.widgets.Control.calculateVisibleRegion(Control.java:775)
	at org.eclipse.swt.widgets.Control.getVisibleRegion(Control.java:2060)
	at org.eclipse.swt.widgets.Control.isObscured(Control.java:2341)
	at org.eclipse.swt.widgets.Scrollable.scrollClipViewToPoint(Scrollable.java:347)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6754)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSScrollView.setDocumentView(NSScrollView.java:91)
	at org.eclipse.swt.widgets.Scrollable.setZOrder(Scrollable.java:396)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:1026)
	at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:167)
	at org.eclipse.swt.widgets.Text.createWidget(Text.java:596)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:126)
	at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:76)
	at org.eclipse.swt.widgets.Text.<init>(Text.java:140)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.createControl(ConnectionPageGeneral.java:346)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:744)
	at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1182)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1235)
	at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1223)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1223)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:918)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:469)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4577)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4363)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3939)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:263)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:283)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4577)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4363)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3939)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:292)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
2022-12-06 08:38:42.087 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2022-12-06 09:02:39.272 - DBeaver is stopping
2022-12-06 09:02:39.273 - Stop RMI server
2022-12-06 09:02:39.273 - RMI controller has been stopped
2022-12-06 09:02:39.324 - DBeaver shutdown completed
```

</details>

**Comment by LonwoLonwo** [comment]
Looks like an Eclipse issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198

**Comment by zach-betz-hln** [comment]
Per the Eclipse [thread](https://github.com/dbeaver/dbeaver/issues/18458#issuecomment-1339974784) linked by @LonwoLonwo, one comment says:

> I could reproduce this by launching child eclipse and moving it to the secondary monitor. 
In Control.calculateVisibleRegion(), view.window () returns null on secondary monitor, but works fine on primary. Not sure why...

I can confirm this. 

Currently, I'm mirroring my MacBook display to an external monitor.

But, if I repeat my original _steps to reproduce_ only on my MacBook, _with mirroring turned off_, then the dialog shows as normal 🤷‍♂️ 

<img width="674" alt="Screenshot 2022-12-08 at 9 05 34 AM" src="https://user-images.githubusercontent.com/119352232/206482025-a1be6064-56c8-45e9-a522-c45bf27e7dfe.png">

**Comment by LonwoLonwo** [comment]
Ok, thanks for the workaround @zach-betz-hln

**Comment by ShadelessFox** [comment]
I was able to reproduce this issue even with disabled mirroring. Not sure if we can do something about it.
