### ISSUE TITLE
ERROR: operator is not unique: "char" || text

### ISSUE THREAD

**Issue by talski** [dbeaver/dbeaver#18514]
### Description

I'm getting this error when opening Dependencies tab
![image](https://user-images.githubusercontent.com/740549/207710367-0c3c8e88-a01f-40b5-8c8f-b94cad0d9da8.png)

<details>
  <summary>log</summary>

  ```
!ENTRY org.jkiss.dbeaver.model 4 0 2022-12-14 16:50:55.751
!MESSAGE ERROR: operator is not unique: "char" || text
  Dica: Could not choose a best candidate operator. You might need to add explicit type casts.
  PosiÃ§Ã£o: 175
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2022-12-14 16:50:55.751
!MESSAGE ERROR: operator is not unique: "char" || text
  Dica: Could not choose a best candidate operator. You might need to add explicit type casts.
  PosiÃ§Ã£o: 175
!STACK 0
org.postgresql.util.PSQLException: ERROR: operator is not unique: "char" || text
  Dica: Could not choose a best candidate operator. You might need to add explicit type casts.
  PosiÃ§Ã£o: 175
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDependency.readDependencies(PostgreDependency.java:275)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getDependencies(PostgreTableBase.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:292)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.syncRun(LoadingJob.java:112)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.loadData(ObjectListControl.java:365)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ObjectListControl.loadData(ObjectListControl.java:319)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageNode.refreshPart(TabbedFolderPageNode.java:180)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.refreshPart(ObjectPropertiesEditor.java:511)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.refreshPart(EntityEditor.java:939)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.refreshPart(EntityEditor.java:877)
	at org.jkiss.dbeaver.ui.editors.DatabaseEditorListener.nodeChanged(DatabaseEditorListener.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob.lambda$0(DBNModel.java:756)
	at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:68)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:295)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
  ```
</details>

### DBeaver Version

Comunity Edition 22.3.0.202212041619

### Operating System

Windows 11 22H2

### Database and driver

Postgresql 15.1, JDBC 42.5.1

### Steps to reproduce

Open any table and navigate to dependencies, it's only occurring on PG 15, on 14 was fine

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
Fixed.
Fix will be available [here](https://dbeaver.io/) on 2022-12-26 in DBeaver 22.3.1
