### ISSUE TITLE
PostgreSQL Functions With BEGIN ATOMIC is not supported: ERROR: syntax error at end of input

### ISSUE THREAD

**Issue by EldarAgalarov** [dbeaver/dbeaver#18529]
### Description

PostgreSQL 14 added support for SQL-standard bodies in funcs and procs that are using BEGIN ATOMIC clauses.
This function creation statement doesn't work in DBeaver:

```
CREATE OR REPLACE FUNCTION asterisks(n int)
RETURNS SETOF text
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
BEGIN ATOMIC
    SELECT repeat('*', g) FROM generate_series (1, n) g;
END;
```

Producing following exception:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ERROR: syntax error at end of input
  Position: 176
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:581)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:490)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:497)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:916)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3800)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5035)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 176
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

Probably this is JDBC driver issue, because exception stacktrace refers on it:
`Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at end of input`

### DBeaver Version

Community 22.3

### Operating System

Ubuntu 22.10

### Database and driver

PostgreSQL 15.1
postgresql-jdbc 42.5.1

**Comment by ShadelessFox** [comment]
Hello @EldarAgalarov,

You need to select the entire query and execute it.

DBeaver mistakenly thinks that the query ends somewhere before its actual end, presumably just before the `END;` line.

**Comment by EldarAgalarov** [comment]
It was PostgreSQL JDBC driver [issue](https://github.com/pgjdbc/pgjdbc/issues/2702). Fixed in 42.5.3 and DBeaver now is able to run statements with "BEGIN ATOMIC" clause.

**Comment by uhfath** [comment]
Is this really fixed?
I've tried something like this:
```pgsql
CREATE OR REPLACE FUNCTION informer.text_to_tsvector(config regconfig, source text)
 RETURNS tsvector
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE STRICT
BEGIN ATOMIC
 SELECT to_tsvector(config, coalesce(regexp_replace(source, '\W', ' ', 'g'), ''));
end;
```
Using DBeaver 23.2.1 with these:
![image](https://github.com/dbeaver/dbeaver/assets/14792749/420a4f86-e48b-4283-8b3d-35f3d9931370)

And it gives me this:
> SQL Error [42601]: ERROR: syntax error at end of input
  Position: 248
Error position: line: 6 pos: 247

However, if I select entire function code and execute that it works.
Test on PostgreSQL 14.2 (1914) on Windows 10.

**Comment by fedxyz** [comment]
Hi,

I am using `Version 23.2.5.202311191730`  and I am not able to create functions that use `BEGIN ATOMIC` `END`, for example

```
create function foobar ()
    returns table (
      foo int
    )
begin atomic
select 1;
end;
```

it doesn't run with the error mentioned in the previous comments.

As suggested I selected the entire function code and I used `Execute SQL query` but it doesn't work for me.
I am using `SQL Editor` -> `New SQL script` I write/run my sql code.

Thanks for the help.

**Comment by E1izabeth** [comment]
@fedxyz 
It's fixed in the early access version https://dbeaver.io/files/ea/

**Comment by Molochnikov** [comment]
> @fedxyz It's fixed in the early access version https://dbeaver.io/files/ea/

https://dbeaver.io/files/ea/dbeaver-ce-24.2.3-x86_64-setup.exe installed. Checked version 24.2.3.2024. 

```
CREATE OR REPLACE FUNCTION asterisks(n int)
RETURNS SETOF text
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
BEGIN ATOMIC
    SELECT repeat('*', g) FROM generate_series (1, n) g;
END;
```

SQL Error [42601]: ERROR: syntax error at end of input

**Comment by x3x3n0m0rph** [comment]
Works without any troubles on 24.2.2, if executed with "play" button:

![изображение](https://github.com/user-attachments/assets/937c57e9-813a-4d72-a85e-0ce4e807d16a)

PostgreSQL 15.3
Driver:
![изображение](https://github.com/user-attachments/assets/2cee882e-23e0-4963-b7c2-f2bfabe8a962)

**Comment by ask9** [comment]
It should work with Alt + X as well, but it doesn't.
