### ISSUE TITLE
'References' tab shows error (nullPointerException) when selecting more than one row

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#18541]
### Discussed in https://github.com/orgs/dbeaver/discussions/18534

<div type='discussions-op-text'>

<sup>Originally posted by **Amitkad** December 19, 2022</sup>
Few days ago dbeaver asked to make an update - I approved it (and I think it also installed\updated a driver)
I'm not 100% that the issue started than, but I am 90% sure about it.

The issue:

* When I am selecting more than one row, the 'References'  panel show a "NullPointerException" (full details below).
* the References panel works fine when selecting single row.
* It happens on all my DBs and connections

![image](https://user-images.githubusercontent.com/7620041/208439611-b4046aea-7699-4772-87f2-30d85b31089e.png)

**Exception**:
org.jkiss.dbeaver.DBException
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:232)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5035)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.sql.AbstractSQLDialect.isQuotedIdentifier(AbstractSQLDialect.java:400)
	at org.jkiss.dbeaver.model.impl.sql.AbstractSQLDialect.getQuotedIdentifier(AbstractSQLDialect.java:410)
	at org.jkiss.dbeaver.model.DBUtils.getQuotedIdentifier(DBUtils.java:159)
	at org.jkiss.dbeaver.model.DBUtils.getQuotedIdentifier(DBUtils.java:154)
	at org.jkiss.dbeaver.model.impl.sql.StandardSQLDialectQueryGenerator.getConstraintCondition(StandardSQLDialectQueryGenerator.java:344)
	at org.jkiss.dbeaver.model.impl.sql.StandardSQLDialectQueryGenerator.appendConditionString(StandardSQLDialectQueryGenerator.java:171)
	at org.jkiss.dbeaver.model.impl.sql.StandardSQLDialectQueryGenerator.appendConditionString(StandardSQLDialectQueryGenerator.java:107)
	at org.jkiss.dbeaver.model.impl.sql.StandardSQLDialectQueryGenerator.appendConditionString(StandardSQLDialectQueryGenerator.java:92)
	at org.jkiss.dbeaver.model.impl.sql.StandardSQLDialectQueryGenerator.appendQueryConditions(StandardSQLDialectQueryGenerator.java:63)
	at org.jkiss.dbeaver.model.sql.SQLUtils.appendQueryConditions(SQLUtils.java:1052)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:162)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	... 4 more

I tried to:
* look for the issue and solution online
* reset driver to default
* reoper dbeaver 
* and more...

if anyone have an idea i'll be glad!</div>

DBeaver 22.3.0

**Comment by Amitkad** [comment]
@E1izabeth, thank you for opening this issue.

is there any prioritization for it and\or time estimation for the next version?
this issue is limiting most of the users (including me) from one of the most basic actions (browsing the data).

in the meanwhile I will have to downgrade to previous version. any other suggestion?

**Comment by E1izabeth** [comment]
I wasn't able to reproduce this issue for now. Could you provide the ddl of the table on which this error appears?

**Comment by Amitkad** [comment]
the error apears for all tables.
one exmaple would be:
Referencing from table A to B (see below)

**A:**
-- public.time_slot definition

-- Drop table

-- DROP TABLE public.time_slot;

CREATE TABLE public.time_slot (
	uid uuid NOT NULL DEFAULT gen_random_uuid(),
	is_repetitive bool NOT NULL DEFAULT false,
	"rule" varchar(2000) NULL,
	start_time time NOT NULL,
	end_time time NOT NULL,
	"date" timestamptz NULL,
	week_day public."time_slot_week_day_enum" NULL,
	"type" public."time_slot_type_enum" NOT NULL DEFAULT 'work_availability'::time_slot_type_enum,
	max_appointments int4 NULL,
	"name" varchar(100) NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	is_locked bool NOT NULL DEFAULT false,
	"startPoint" jsonb NULL,
	"endPoint" jsonb NULL,
	vet_id uuid NULL,
	CONSTRAINT "PK_650f1b5c483c9c318d2398b8747" PRIMARY KEY (uid)
);


-- public.time_slot foreign keys

ALTER TABLE public.time_slot ADD CONSTRAINT "FK_757a6547ffa20578e186c6b5200" FOREIGN KEY (vet_id) REFERENCES public.vet(uid) ON DELETE CASCADE;

----------------------

**B:**
-- public.vet definition

-- Drop table

-- DROP TABLE public.vet;

CREATE TABLE public.vet (
	uid uuid NOT NULL DEFAULT gen_random_uuid(),
	experience varchar(3) NULL,
	license_number varchar NULL,
	social_number varchar NULL,
	share_id varchar NULL,
	social_number_issues_at timestamp NULL,
	"birthDate" timestamp NULL,
	gender public."vet_gender_enum" NULL,
	max_appointments int4 NULL,
	visits_per_hour float8 NOT NULL DEFAULT '2'::double precision,
	licensed_date timestamptz NULL,
	license_expiration timestamptz NULL,
	commute_method public."vet_commute_method_enum" NULL,
	status public."vet_status_enum" NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	user_id uuid NULL,
	timezone_id uuid NULL,
	start_point_id uuid NULL,
	end_point_id uuid NULL,
	CONSTRAINT "PK_ac243efd75eb5ded4dfd23a2668" PRIMARY KEY (uid),
	CONSTRAINT "REL_1739703ff6afd74ed70d771621" UNIQUE (end_point_id),
	CONSTRAINT "REL_53dab2e3bcc63fa8cbc46914b2" UNIQUE (user_id),
	CONSTRAINT "REL_8cc9fe126608f90265c799a4e9" UNIQUE (start_point_id),
	CONSTRAINT "UQ_1739703ff6afd74ed70d771621a" UNIQUE (end_point_id),
	CONSTRAINT "UQ_53dab2e3bcc63fa8cbc46914b2d" UNIQUE (user_id),
	CONSTRAINT "UQ_8cc9fe126608f90265c799a4e9b" UNIQUE (start_point_id)
);


-- public.vet foreign keys

ALTER TABLE public.vet ADD CONSTRAINT "FK_1739703ff6afd74ed70d771621a" FOREIGN KEY (end_point_id) REFERENCES public.address(uid);
ALTER TABLE public.vet ADD CONSTRAINT "FK_18d5351a86244a73ecfa7728222" FOREIGN KEY (timezone_id) REFERENCES public.timezone(uid) ON DELETE CASCADE;
ALTER TABLE public.vet ADD CONSTRAINT "FK_53dab2e3bcc63fa8cbc46914b2d" FOREIGN KEY (user_id) REFERENCES public."user"(uid) ON DELETE CASCADE;
ALTER TABLE public.vet ADD CONSTRAINT "FK_8cc9fe126608f90265c799a4e9b" FOREIGN KEY (start_point_id) REFERENCES public.address(uid);

**Comment by Amitkad** [comment]
I downgraded dbeaver version to 22.2.5 and issue still happened
than downgraded to 22.1.0 and issue was SOLVED.

before downgrading I tried connecting to some other bases, and didnt see the issue. So I assume the issue it related to version higher than 22.1.0, and specific DB setup\structure.

**Comment by E1izabeth** [comment]
Thank you for your answer and investigation.

**Comment by arhayka** [comment]
Hi @Amitkad,
Unfortunately, we can't reproduce this issue.
Could you please check if it is still actual in the new DBeaver version?

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. If it's still actual, please, let me know.

**Comment by Amitkad** [comment]
@E1izabeth sorry for that. missed your comment, and I used the old version so I didnt feel it.

Today I have updated again, an the issue still happens in the newest version.
but now the error is a bit different (or maybe more descriptive):
org.jkiss.dbeaver.DBException: Cannot invoke "String.startsWith(String)" because "identifier" is null
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:249)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

If you need my help, or screen share for solving it lmk.

**Comment by E1izabeth** [comment]
What version is this log from? Unfortunately it doesn't match with the latest version, as well as the previous log.

**Comment by Amitkad** [comment]
Version 23.1.0.202306041918
Screenshots of the version and the issue.

No issue when selecting single row:
![image](https://github.com/dbeaver/dbeaver/assets/7620041/34bf87c6-44bd-4233-86bf-e66eca9d444e)

An issue when selecting multiple rows:
![image](https://github.com/dbeaver/dbeaver/assets/7620041/078cd318-7987-4a0a-bd3d-8a2e3ec7018d)

**Comment by E1izabeth** [comment]
Thanks. That's strange. We'll look deeper into it.
