### ISSUE TITLE
NPE appears on Test Connection for empty Connection Settings

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18555]
### Description

NPE appears on Test Connection for empty Connection Settings

https://user-images.githubusercontent.com/31996417/208954520-f3ccecf2-0b6f-411d-91c4-f15fd9ddb0e8.mp4

### DBeaver Version

22.3.0, 22.3.1

### Operating System

win10

### Database and driver
 Snowflake 3.13.6

### Additional context
```

eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Dec 21 17:24:42 CET 2022
NullPointerException

java.lang.NullPointerException
	at net.snowflake.client.jdbc.telemetryOOB.TelemetryService.configureDeployment(TelemetryService.java:172)
	at net.snowflake.client.jdbc.telemetryOOB.TelemetryService.updateContext(TelemetryService.java:139)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:98)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:42)
	at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:97)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1153)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1022)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
fixed with https://github.com/dbeaver/pro/issues/1912

![image](https://github.com/dbeaver/dbeaver/assets/31996417/81911c4e-a395-4dd9-ad1f-d59446b20dba)
