### ISSUE TITLE
Driver files missing and can't download

### ISSUE THREAD

**Issue by jasperchen2022** [dbeaver/dbeaver#18677]
### Description

Hello all,
I'm new to DBeaver. Today I downloaded it and try to connect to the DBeaver sample database. Upton clicking the database, it shows SQLite driver files are missing and can't be downloaded. Can anyone provide some suggestion? Thanks a lot.
Best,
Jasper
![1](https://user-images.githubusercontent.com/122055656/210878531-68249557-9926-4904-b58e-7cdc5b50ab3e.png)

### DBeaver Version

22.3.0

### Operating System

windows 10

### Database and driver

Database name: DBeaver Sample Database (SWLite)
Driver: SQLite

**Comment by ShadelessFox** [comment]
Hello @jasperchen2022,

It looks like your network connection was down, or you're behind a firewall that doesn't allow you to access the Maven repository.

Please contact your system administrator if you're working in a corporate environment or using a VPN.

Let me know if your issue was solved.

**Comment by jasperchen2022** [comment]
Hello @ShadelessFox ,
Thanks a lot for your response. I do have internet connection. I'm using a corporate laptop in a corporate network. I will ask the company IT admin whether there is a firewall to prevent the access to the Mave repository.

**Comment by jasperchen2022** [comment]
> Hello @jasperchen2022,
> 
> It looks like your network connection was down, or you're behind a firewall that doesn't allow you to access the Maven repository.
> 
> Please contact your system administrator if you're working in a corporate environment or using a VPN.
> 
> Let me know if your issue was solved.

Hello @ShadelessFox,

I tried my laptop in my home network, it still shows the same issue. Do you have any other suggestion? Thank you.

**Comment by ShadelessFox** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you

**Comment by jasperchen2022** [comment]
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you

I installed DBeaver on my personal computer. It also shows missing driver files for most driver, yet, I was able to see the list of missing files and can download them. I think you're right the corporate laptop has a firewall to prevent access to the Maven respository.

Below is the error code of the DBeaver on my corporate laptop. Does that mean I have to ask the IT admin to temporarily remove the firewall to allow downloading the driver files? If so, can I ask the steps that he can do this? Thanks a lot

Quote error log:
!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-05 18:46:55.821
!MESSAGE Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-05 18:46:55.821
!MESSAGE Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.sqlite.JDBC'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-01-05 18:46:55.821
!MESSAGE org.sqlite.JDBC
!STACK 0
java.lang.ClassNotFoundException: org.sqlite.JDBC
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1186)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1122)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:675)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:682)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:174)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.sqlite.model.SQLiteDataSource.<init>(SQLiteDataSource.java:46)
	at org.jkiss.dbeaver.ext.sqlite.model.SQLiteMetaModel.createDataSourceImpl(SQLiteMetaModel.java:147)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1025)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:110)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:77)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by jasperchen2022** [comment]
> Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you

Maybe I could download the required driver files on my personal laptop and manually add these driver files to the driver manager of my corporate laptop DBeaver? If that works, how I manually install the files? Thank you

**Comment by ShadelessFox** [comment]
I guess DBeaver is trying to access https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/maven-metadata.xml. Does it open in your browser on your corporate laptop? If not, you can provide this URL to your sysadmin, so they can configure the firewall using it as a reference.

Yes, you can download driver files and install them manually:
1. Download [sqlite-jdbc-3.40.0.0.jar](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.40.0.0/sqlite-jdbc-3.40.0.0.jar) and put it somewhere on your disk drive
1. Open DBeaver and go to <kbd>Database</kbd> &rArr; <kbd>Driver Manager</kbd>
1. See the attachment below

![java_T1lfkxpDbD](https://user-images.githubusercontent.com/35821147/210908758-b22380f9-6025-484a-95e7-40ebba758396.png)

**Comment by jasperchen2022** [comment]
Hello @ShadelessFox ,

Thanks for your suggestion. In my corporate laptop, I clicked the link and it goes to a webpage, but it doesn't have any downloadable file. It looks the same in my personal laptop.
This is what it looks like
<img width="793" alt="3" src="https://user-images.githubusercontent.com/122055656/210910235-d412cb14-7c21-46f1-a12f-74a462104adc.png">

I added the jar file to the sqlite driver in the driver manger and restart the software. However, it still pops up the window showing missing driver files and can't access the site and can't download the driver files.

**Comment by ShadelessFox** [comment]
Oh, so Maven is accessible, it seems.

DBeaver also attempts to download the license file: https://www.apache.org/licenses/LICENSE-2.0.txt.

1. Does this file open in your browser?
2. Could you try doing the same you did for the jar file (add that license file to the driver's libraries) to see if it works?

**Comment by jasperchen2022** [comment]
> Oh, so Maven is accessible, it seems.
> 
> DBeaver also attempts to download the license file: https://www.apache.org/licenses/LICENSE-2.0.txt.
> 
> 1. Does this file open in your browser?
> 2. Could you try doing the same you did for the jar file (add that license file to the driver's libraries) to see if it works?

OMG, it works, after I add these two files in the libraries. The driver works! Thanks so so much!

**Comment by ShadelessFox** [comment]
You're welcome!

I still suggest contacting your sysadmin either way.

Since the issue is resolved, I will close the ticket.

**Comment by jasperchen2022** [comment]
@ShadelessFox 
Thanks so much again. Sure, I will talk with the IT admin about this.

**Comment by jasperchen2022** [comment]
> You're welcome!
> 
> I still suggest contacting your sysadmin either way.
> 
> Since the issue is resolved, I will close the ticket.

@ShadelessFox 
By the way, I also deleted all the Maven artifacts in the libraries. Otherwise, it keeps asking to download driver files, which are not allowed due to network configuration.

**Comment by ShadelessFox** [comment]
Yes, I forgot to mention that. Nice catch!

**Comment by agdgb** [comment]
> I guess DBeaver is trying to access https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/maven-metadata.xml. Does it open in your browser on your corporate laptop? If not, you can provide this URL to your sysadmin, so they can configure the firewall using it as a reference.
> 
> Yes, you can download driver files and install them manually:
> 
>     1. Download [sqlite-jdbc-3.40.0.0.jar](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.40.0.0/sqlite-jdbc-3.40.0.0.jar) and put it somewhere on your disk drive
> 
>     2. Open DBeaver and go to Database ⇒ Driver Manager
> 
>     3. See the attachment below
> 
> 
> ![java_T1lfkxpDbD](https://user-images.githubusercontent.com/35821147/210908758-b22380f9-6025-484a-95e7-40ebba758396.png)

This worked for me as well on Linux Mint. Thanks

**Comment by FrankFangsj** [comment]
> I guess DBeaver is trying to access https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/maven-metadata.xml. Does it open in your browser on your corporate laptop? If not, you can provide this URL to your sysadmin, so they can configure the firewall using it as a reference.
> 
> Yes, you can download driver files and install them manually:
> 
> 1. Download [sqlite-jdbc-3.40.0.0.jar](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.40.0.0/sqlite-jdbc-3.40.0.0.jar) and put it somewhere on your disk drive
> 2. Open DBeaver and go to Database ⇒ Driver Manager
> 3. See the attachment below
> 
> ![java_T1lfkxpDbD](https://user-images.githubusercontent.com/35821147/210908758-b22380f9-6025-484a-95e7-40ebba758396.png)

The method works for me.  
system - Mac M2
Thanks a lot!

**Comment by ramon-san** [comment]
Hello @ShadelessFox 

I'm looking into this right now because I'm having the same problem with the following driver: `com.mysql.cj.jdbc.Driver`

The DBeaver error log is the following:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-03-01 17:14:40.636
!MESSAGE Error creating driver 'MySQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.mysql.cj.jdbc.Driver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-03-01 17:14:40.636
!MESSAGE com.mysql.cj.jdbc.Driver
!STACK 0
java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1272)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1205)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:745)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:717)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createDriverInstance(JDBCDataSource.java:282)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:198)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:464)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:104)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:99)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1385)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1229)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1015)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
        at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2488)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I'm trying to find a pattern to identify the file to download, but I'm posting here in case someone can help or knows.

## DBeaver Version
23.3.5.202402181738

## Operating System
macOS 14.3.1 (23D60)

## Other Information
I originally installed DBeaver through `brew`, but I updated DBeaver through the GUI yesterday. Also did an OS update earlier today so not exactly sure which of the two things triggered this problem (I think it was the DBeaver update). Also checked Maven access through my network and it seems to be working just fine.

<img width="1123" alt="image" src="https://github.com/dbeaver/dbeaver/assets/65260209/5132777b-8d6f-4a77-8094-552f19fccd7a">

Here is an image of my _DBeaver > Driver Manger > MySQL_.

# SOLVED

To solve this I simply went to `~/Library/DBeaverData/drivers/maven/maven-central/com.mysql` and changed the `.pom` file name to what DBeaver was expecting. For some reason, there was a discrepancy here.

File name in the directory was `mysql-connector-j-8.2.0.pom` and DBeaver was expecting `mysql-connector-cj-8.2.0.pom`. Also before doing this change I removed all other drivers, not sure if this made any difference (don't think so).

**Comment by ShadelessFox** [comment]
Hello @ramon-san,

Thank you for the report. To me, it looks like it might be a different issue, could you create a new ticket?

**Comment by ramon-san** [comment]
Of course, just created new issue #23034 as requested. Thank you for the support and the awesome product; you guys rock!

**Comment by JimBacon** [comment]
Similar problem for me installing mariadb driver. Dbeaver failed to install https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt although I can browse to that url okay. Saving the file to `~/snap/dbeaver-ce/309/.local/share/DBeaverData/drivers/remote/licenses/old-licenses` from my browser resolved the issue.

![Screenshot from 2024-06-25 07-54-28](https://github.com/dbeaver/dbeaver/assets/2545390/83efa6fb-614e-4426-ade3-18349c44acbe)

**Comment by ducquoc** [comment]
I also met a similar error: 
```
Error creating driver 'SQLite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
```
(DBeaver 22.0.2, sqlite-jdbc-3.46.1.2.jar )

My problem was the jar had been corrupted from an unfinished download: 
```bash
$ jar tf ~/Library/DBeaverData/drivers/maven/maven-central/org.xerial/sqlite-jdbc-3.46.1.2.jar 
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
...
```
So, the solution in my case is simply removing the corrupted jar. After that, DBeaver can download successfully and can connect to SQLite DB. 
Hope this helps,
