### ISSUE TITLE
Office Integration Extension - Office Support

### ISSUE THREAD

**Issue by meachcarnahan** [dbeaver/dbeaver#18680]
### Description

I have followed the instructions to install the P2 extension for Office Support so we can export to XLSX files. This feature seems to only work 1 time but does not export the data. It just export the headers of the columns. When we try to export a second time no file gets generated even though DBeaver says the task completed.

![image](https://user-images.githubusercontent.com/59850648/210892577-8037bd10-64c3-4941-bb08-a8d677bdf8ea.png)

When we try to change the location of where the xlsx files writes to we get the following error. The user running the function has admin privileges on all folders on the computer. 

![image](https://user-images.githubusercontent.com/59850648/210892175-99801624-abb0-4027-bf6d-b55bd6afe9f5.png)

java.lang.NoClassDefFoundError: org/jkiss/dbeaver/model/data/DBDAttributeDecorator
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.exportHeader(DataExporterXLSX.java:335)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.exportHeaderInFile(StreamTransferConsumer.java:238)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchStart(StreamTransferConsumer.java:175)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:757)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:609)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:486)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:493)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:894)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3645)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:125)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### DBeaver Version

Community Edition Version 22.2.0.202209051344

### Operating System

Windows 11 Enterprise

### Database and driver

Database Name : LANDPRD
Database Version: 12.2.0.1.0
Driver: Oracle

### Steps to reproduce

Execute the query, display the data, select the export data option, select the XLSX option, click on next, choose the table settings, click on next, configure options and parameters of output, click on next, check results and click on to finish. When I open the generated file, only column headers are there and not data.

**Comment by ShadelessFox** [comment]
Hello @meachcarnahan,

Try upgrading to a newer version of DBeaver: https://dbeaver.io/files.

Please let me know if it helps.

**Comment by DenisQuan** [comment]
Community Edition Version 22.3.2.202301060755
![image](https://user-images.githubusercontent.com/122078217/211227954-7215dd94-de77-421c-9011-6a1163ce73ec.png)

Hello,another question,
export to XLSX files，"header format" selected both or description, XLSX file doesnot contain "description" row.
![image](https://user-images.githubusercontent.com/122078217/211228415-3eabd542-2da6-444d-b2d2-94642a74314b.png)
![image](https://user-images.githubusercontent.com/122078217/211228606-f26b2c6f-9d98-4675-8554-4d9ff0d77da7.png)
![image](https://user-images.githubusercontent.com/122078217/211228940-821c0d7f-a01f-4a41-8e2d-fb885c605f21.png)

but if "Exported" is a table not "select SQL" ,it can work.
![image](https://user-images.githubusercontent.com/122078217/211228808-d9a99e01-b38e-4bdc-8164-2c8f52123b5b.png)

**Comment by meachcarnahan** [comment]
> Hello @meachcarnahan,
> 
> Try upgrading to a newer version of DBeaver: https://dbeaver.io/files.
> 
> Please let me know if it helps.

Hey @ShadelessFox thanks for the suggestion this does work and we will be upgrading to the latest. THank you so much for your input!

Cheers,
Meach
