### ISSUE TITLE
Unable to switch to certain mysql databases with SQL syntax error

### ISSUE THREAD

**Issue by william00179** [dbeaver/dbeaver#18707]
### Description

Hi there, 

I have a MySQL server with a number of databases, I'm able to access all but two of them without issue in DBeaver. However upon trying to switch, list or do anything with two of these database I'm presented with an SQL syntax error from DBeaver.

In the example below I'm trying to list the tables in this database.

![image](https://user-images.githubusercontent.com/7232534/211445592-3c1f3566-6379-436f-af04-5767ee8c615e.png)

This happens for one other database in this MySQL server also.

### DBeaver Version

Community 22.3.2.202301060755

### Operating System

Windows 10 Pro 19045.2364

### Database and driver

1. MySQL 8.0.18
2. MySQL Connector 8.0.29

### Steps to reproduce

1. Connect to the MySQL database server
2. Attempt to do anything in DBeaver with this specific database like list the tables, or make it the active database.
3. Get SQL syntax error

### Additional context

If I use the mysql cli I'm able to do everything with this database and the tables within it.

**Comment by LonwoLonwo** [comment]
Hello @william00179 

Please open the [Query Manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager), and check all buttons in the "Query type" in properties. This will help to find your falling query. 

Additionally, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
You said that the issue is with two databases, am I correct?
I see one in the picture. What is the second one? Starting from the "66e60ce"?

**Comment by william00179** [comment]
Hi @LonwoLonwo 

The query log shows

SHOW TABLE STATUS FROM 6cd7a8b8166d477f8899ac38f6dfeecf
SHOW FULL TABLES FROM 6cd7a8b8166d477f8899ac38f6dfeecf
SHOW FULL TABLES FROM 6e46ed9d1f9c4ce88e3bf606df52cbb5
SELECT * FROM information_schema.TABLES t
WHERE
	t.TABLE_SCHEMA = 'information_schema'
	AND t.TABLE_NAME = 'CHECK_CONSTRAINTS'
show databases
SHOW VARIABLES LIKE 'lower_case_table_names'
SHOW PLUGINS
SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server
SHOW COLLATION
SHOW CHARSET
SHOW ENGINES
-- Load type info
SELECT DATABASE()
SELECT DATABASE()

![image](https://user-images.githubusercontent.com/7232534/211521737-2bc221dc-d2d2-45c3-9850-9da2483a8791.png)

Very strange as it looks identical to the other that works fine.

The log for the session

```
2023-01-10 17:57:42.643 - DBeaver 22.3.2.202301060755 is starting
2023-01-10 17:57:42.644 - OS: Windows 10 10.0 (amd64)
2023-01-10 17:57:42.644 - Java version: 11.0.12 by Eclipse Foundation (64bit)
2023-01-10 17:57:42.645 - Install path: 'C:\Program Files\DBeaver'
2023-01-10 17:57:42.645 - Instance path: 'file:/C:/Users/redacted/AppData/Roaming/DBeaverData/workspace6/'
2023-01-10 17:57:42.645 - Memory available 64Mb/1024Mb
2023-01-10 17:57:42.659 - Create display
2023-01-10 17:57:42.901 - Initializing DBeaver 22.3.2
2023-01-10 17:57:42.903 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 22.3.2.202301060755
2023-01-10 17:57:42.904 - Initialize desktop platform...
2023-01-10 17:57:43.095 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> Start Core Resource Management [org.eclipse.core.resources 3.18.100.v20221025-2047]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.97.202301060755]
> Start Team Support Core [org.eclipse.team.core 3.9.600.v20220902-2219]
2023-01-10 17:57:43.429 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
2023-01-10 17:57:43.471 - Platform initialized (567ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.97.202301060755]
2023-01-10 17:57:43.484 - Starting RMI server at 23252
2023-01-10 17:57:43.547 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.700.v20221024-2137]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.400.v20220915-1347]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.100.v20221024-2137]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.3.600.v20221024-2137]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.17.0.v20220817-1334]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.200.v20221024-2137]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.500.v20221028-0801]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.700.v20221024-2137]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.200.v20221024-2137]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.200.v20220613-1008]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.700.v20221102-0748]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.112.202301060755]
2023-01-10 17:57:45.762 - Configure workbench window
> Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
2023-01-10 17:57:45.863 - Create actions
2023-01-10 17:57:45.870 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-01-10 17:57:45.871 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-01-10 17:57:45.871 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2023-01-10 17:57:46.645 - Initialize workbench window
2023-01-10 17:57:46.664 - Finish initialization
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.97.202301060755]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.4.100.v20220812-1406]
> Start Internet Connection Management [org.eclipse.core.net 1.4.0.v20220813-1037]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.134.202301060755]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.103.202301060755]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.87.202301060755]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.97.202301060755]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20221221122425]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20221221122425]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.57.202301060755]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.57.202301060755]
2023-01-10 17:57:48.370 - Total database drivers: 101 (101)
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.600.v20220809-1658]
> Start Default Text Editor [org.eclipse.ui.editors 3.14.400.v20220730-1844]
2023-01-10 17:59:01.552 - Connect with 'redacted' (mysql8-17dd59d61e8-39893f36bad92ee0)
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.118.202301060755]
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.107.202301060755]
2023-01-10 17:59:01.596 - Adding identity key
2023-01-10 17:59:01.597 - Attempting to convert an unsupported key into suitable format
2023-01-10 17:59:02.034 - Configure tunnel
> Start DBeaver SSH tunnels UI [org.jkiss.dbeaver.net.ssh.ui 1.0.118.202301060755]
> Start JSch Core [org.eclipse.jsch.core 1.4.0.v20220813-1037]
> Start JSch UI [org.eclipse.jsch.ui 1.4.200.v20220812-1406]
2023-01-10 17:59:02.181 - Connect to tunnel host
2023-01-10 17:59:02.183 - SSH INFO: Connecting to redacted port 22
2023-01-10 17:59:02.201 - SSH INFO: Connection established
2023-01-10 17:59:02.245 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
2023-01-10 17:59:02.245 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2023-01-10 17:59:02.245 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2023-01-10 17:59:02.253 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2023-01-10 17:59:02.338 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2023-01-10 17:59:02.342 - SSH INFO: SSH_MSG_KEXINIT sent
2023-01-10 17:59:02.342 - SSH INFO: SSH_MSG_KEXINIT received
2023-01-10 17:59:02.342 - SSH INFO: kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
2023-01-10 17:59:02.343 - SSH INFO: kex: server: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
2023-01-10 17:59:02.343 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2023-01-10 17:59:02.343 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2023-01-10 17:59:02.343 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2023-01-10 17:59:02.343 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2023-01-10 17:59:02.344 - SSH INFO: kex: server: none,zlib@openssh.com
2023-01-10 17:59:02.344 - SSH INFO: kex: server: none,zlib@openssh.com
2023-01-10 17:59:02.344 - SSH INFO: kex: server: 
2023-01-10 17:59:02.344 - SSH INFO: kex: server: 
2023-01-10 17:59:02.344 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2023-01-10 17:59:02.345 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2023-01-10 17:59:02.345 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2023-01-10 17:59:02.345 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2023-01-10 17:59:02.345 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2023-01-10 17:59:02.346 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2023-01-10 17:59:02.346 - SSH INFO: kex: client: none
2023-01-10 17:59:02.346 - SSH INFO: kex: client: none
2023-01-10 17:59:02.346 - SSH INFO: kex: client: 
2023-01-10 17:59:02.347 - SSH INFO: kex: client: 
2023-01-10 17:59:02.347 - SSH INFO: kex: server->client aes128-ctr hmac-sha1 none
2023-01-10 17:59:02.347 - SSH INFO: kex: client->server aes128-ctr hmac-sha1 none
2023-01-10 17:59:02.349 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2023-01-10 17:59:02.349 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2023-01-10 17:59:02.370 - SSH INFO: ssh_rsa_verify: signature true
2023-01-10 17:59:02.371 - SSH INFO: Host 'redacted' is known and matches the RSA host key
2023-01-10 17:59:02.372 - SSH INFO: SSH_MSG_NEWKEYS sent
2023-01-10 17:59:02.372 - SSH INFO: SSH_MSG_NEWKEYS received
2023-01-10 17:59:02.374 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2023-01-10 17:59:02.421 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2023-01-10 17:59:02.431 - SSH INFO: Authentications that can continue: publickey,keyboard-interactive,password
2023-01-10 17:59:02.432 - SSH INFO: Next authentication method: publickey
2023-01-10 17:59:02.559 - SSH INFO: Authentication succeeded (publickey).
2023-01-10 17:59:02.560 - Set port forwarding :26332 -> localhost:3307
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.182.202301060755]
2023-01-10 17:59:02.604 - Execution context opened (redacted; Main; 0)
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.121.202301060755]
2023-01-10 17:59:03.879 - Execution context opened (redacted; Metadata; 1)
2023-01-10 17:59:04.164 - Connected (mysql8-17dd59d61e8-39893f36bad92ee0, MySQL Connector/J [mysql-connector-java-8.0.29 (Revision: dd61577595edad45c398af508cf91ad26fc4144f)])
2023-01-10 17:59:11.257 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '6e46ed9d1f9c4ce88e3bf606df52cbb5' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '6e46ed9d1f9c4ce88e3bf606df52cbb5' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:87)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getTables(MySQLCatalog.java:336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by E1izabeth** [comment]
It seems that identifiers starting with numbers should be quoted.
