### ISSUE TITLE
Database objects can't be opened with Drag and drop

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#18701]
### Description

Database objects are not opened when draged into working object area. Error is recorded instead.

### DBeaver Version

22.3.2

### Operating System

Win11

### Database and driver

Any

### Steps to reproduce

1. Drag any database object into opened objects area

**Expected:** Object is opened like any non DB object like text files, scripts or diagrams
**Actual:** Nothing happens

### Additional context

![dbeaver_7IE6kHxcLU](https://user-images.githubusercontent.com/82543000/211367136-045bf455-410c-4cfb-8256-cc0679fa4a3d.gif)

```
org.eclipse.swt.SWTException: Data does not have correct format for type
	at org.eclipse.swt.dnd.DND.error(DND.java:291)
	at org.eclipse.swt.dnd.DND.error(DND.java:241)
	at org.eclipse.swt.dnd.FileTransfer.javaToNative(FileTransfer.java:73)
	at org.eclipse.swt.dnd.DragSource$COMIDataObject.GetData(DragSource.java:306)
	at org.eclipse.swt.dnd.DragSource$COMIDataObject.method3(DragSource.java:219)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback3(COMObject.java:93)
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.IDataObject.GetData(IDataObject.java:28)
	at org.eclipse.swt.dnd.Transfer.getData(Transfer.java:47)
	at org.eclipse.swt.dnd.FileTransfer.nativeToJava(FileTransfer.java:135)
	at org.eclipse.swt.dnd.DropTarget.Drop(DropTarget.java:454)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(DropTarget.java:401)
	at org.eclipse.swt.dnd.DropTarget$1.method6(DropTarget.java:265)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:120)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:546)
	at org.eclipse.swt.dnd.DragSource.lambda$0(DragSource.java:380)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:296)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by MashaKorax** [comment]
verified
