### ISSUE TITLE
Can't connect to mariadb database with ssl X509

### ISSUE THREAD

**Issue by Benoit0007** [dbeaver/dbeaver#18749]
### Description

I used dbeaver to connect a mariadb database with ssl and it's not working anymore whereas Mysql workbench or other apps works without issue.
I use pem certificate.

Same issue on 2 mariadb database

Error :
Access denied for user 'USER'@'192.168.0.1' (using password: YES)

i don't remember what version of dbeaver worked before ... but there was no issue with previous dbeaver version

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 10 Pro

### Database and driver

Database name :  10.6.11-MariaDB
Driver : mariadb-java-client-3.1.1.jar

### Steps to reproduce

Try to connect to database with the following SSL settings :
In connection settings => SSL tab

- Use SSL checked
- CA certificate : path to pem file is set
- Client Certificate : path to pem file is set
- Client Private Key : path to pem file is set
- Require SSL checked

**Comment by ShadelessFox** [comment]
Hello @Benoit0007,

Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Benoit0007** [comment]
<details><summary>SQLInvalidAuthorizationSpecException</summary>
java.sql.SQLInvalidAuthorizationSpecException: (conn=1347) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	</details>

**Comment by ShadelessFox** [comment]
Can you please send the entire log instead?

**Comment by Benoit0007** [comment]
<details><summary>Log part</summary>
!SESSION 2023-01-12 17:33:30.907 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-01-12 17:33:37.189
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-12 17:33:57.314
!MESSAGE (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-12 17:33:57.314
!MESSAGE (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
!STACK 0
java.sql.SQLInvalidAuthorizationSpecException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
</details>

**Comment by Benoit0007** [comment]
<details><summary>Whole Log</summary>
2023-01-12 17:33:32.595 - DBeaver 22.3.2.202301060755 is starting
2023-01-12 17:33:32.595 - OS: Windows 10 10.0 (amd64)
2023-01-12 17:33:32.595 - Java version: 11.0.12 by Eclipse Foundation (64bit)
2023-01-12 17:33:32.595 - Install path: 'C:\Users\user\AppData\Local\DBeaver'
2023-01-12 17:33:32.595 - Instance path: 'file:/C:/Users/user/AppData/Roaming/DBeaverData/workspace6/'
2023-01-12 17:33:32.595 - Memory available 64Mb/1024Mb
2023-01-12 17:33:32.611 - Create display
2023-01-12 17:33:32.845 - Initializing DBeaver 22.3.2
2023-01-12 17:33:32.845 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 22.3.2.202301060755
2023-01-12 17:33:32.845 - Initialize desktop platform...
2023-01-12 17:33:33.033 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> Start Core Resource Management [org.eclipse.core.resources 3.18.100.v20221025-2047]
> Start Application principale (core) du support d'équipe [org.eclipse.team.core 3.9.600.v20220902-2219]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.97.202301060755]
2023-01-12 17:33:33.298 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
2023-01-12 17:33:33.314 - Platform initialized (469ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.97.202301060755]
2023-01-12 17:33:33.329 - Starting RMI server at 61255
2023-01-12 17:33:33.720 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.700.v20221024-2137]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.400.v20220915-1347]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.100.v20221024-2137]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.3.600.v20221024-2137]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.17.0.v20220817-1334]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.200.v20221024-2137]
> Start Add-ons du Workbench Eclipse e4 [org.eclipse.e4.ui.workbench.addons.swt 1.4.500.v20221028-0801]
Warning: NLS unused message: WorkbenchPreference_showMultipleEditorTabsButton in: org.eclipse.ui.internal.messages
Warning: NLS unused message: Workbench_zoomChangedRestart in: org.eclipse.ui.internal.messages
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.700.v20221024-2137]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.200.v20221024-2137]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.200.v20220613-1008]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.700.v20221102-0748]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.112.202301060755]
Warning: NLS unused message: BlockedJobsDialog_UserInterfaceTreeElement in: org.eclipse.ui.internal.progress.messages
2023-01-12 17:33:35.564 - Configure workbench window
> Start Noyau du système d'aide [org.eclipse.help 3.9.100.v20210721-0601]
2023-01-12 17:33:35.673 - Create actions
2023-01-12 17:33:35.673 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-01-12 17:33:35.689 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-01-12 17:33:35.689 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
Warning: NLS unused message: actions_ContentAssistProposal_description in: org.jkiss.dbeaver.core.CoreResources
2023-01-12 17:33:36.267 - Initialize workbench window
2023-01-12 17:33:36.267 - Finish initialization
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.97.202301060755]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]
> Start IHM de gestion des connexions Internet [org.eclipse.ui.net 1.4.100.v20220812-1406]
> Start Internet Connection Management [org.eclipse.core.net 1.4.0.v20220813-1037]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.134.202301060755]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.103.202301060755]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.87.202301060755]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.97.202301060755]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20221221122425]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20221221122425]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.57.202301060755]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.57.202301060755]
2023-01-12 17:33:37.751 - Total database drivers: 101 (101)
> Start Éditeur de texte par défaut [org.eclipse.ui.editors 3.14.400.v20220730-1844]
> Start Cadre applicatif d’édition de texte [org.eclipse.ui.workbench.texteditor 3.16.600.v20220809-1658]
Warning: NLS unused message: Voir in: org.eclipse.ui.internal.editors.text.TextEditorMessages
2023-01-12 17:33:39.173 - Connect with 'db' (mariaDB-17aea3c05e9-a3268052f2e8883)
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.88.202301060755]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.182.202301060755]
2023-01-12 17:33:56.689 - Execution context opened (db; Main; 0)
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.121.202301060755]
[ WARN] (DBeaver: Loading) `useSsl` option is deprecated, replaced by option `sslMode`
[ WARN] (DBeaver: Loading) `trustServerCertificate` option is deprecated, replaced by setting option `sslMode=trust`
[ WARN] (DBeaver: Loading) Error: 1045-28000: Access denied for user 'user'@'10.219.178.141' (using password: YES)
2023-01-12 17:33:57.282 - Connection failed (mariaDB-17aea3c05e9-a3268052f2e8883)
org.jkiss.dbeaver.model.exec.DBCConnectException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:257)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	... 25 more
2023-01-12 17:33:57.282 - org.jkiss.dbeaver.model.exec.DBCConnectException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
org.jkiss.dbeaver.model.exec.DBCConnectException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:257)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	... 25 more
2023-01-12 17:33:57.298 - (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
java.sql.SQLInvalidAuthorizationSpecException: (conn=1397) Access denied for user 'user'@'192.168.1.1' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
	at org.mariadb.jdbc.Driver.connect(Driver.java:70)
	at org.mariadb.jdbc.Driver.connect(Driver.java:101)
	at org.mariadb.jdbc.Driver.connect(Driver.java:27)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-01-12 17:34:00.861 - DBeaver is stopping
2023-01-12 17:34:00.861 - Stop RMI server
2023-01-12 17:34:00.861 - RMI controller has been stopped
2023-01-12 17:34:00.861 - DBeaver shutdown completed
</details>

**Comment by LonwoLonwo** [comment]
Hello @Benoit0007 

Can you please check the previous driver version for MariaDB? 2.7.1 was before the last driver update from our side.

![2023-01-13 13_25_56-DBeaver 22 3 2 - products](https://user-images.githubusercontent.com/45152336/212297867-0a13fe88-9117-4ba0-895d-11ff20856302.png)

**Comment by Benoit0007** [comment]
Hello, no same issue with this old driver, it seeem DBeaver ignore ssl settings

**Comment by ShadelessFox** [comment]
Have you tried restarting DBeaver after changing the driver version?

**Comment by Benoit0007** [comment]
i just restarted and nothing change

**Comment by ShadelessFox** [comment]
Can you try downgrading to 22.2.0 to see if it helps? https://dbeaver.io/files/22.2.0/

**Comment by Benoit0007** [comment]
ok but i don't want to loose my current settings, is there an impact ?

**Comment by ShadelessFox** [comment]
No, your settings will be fine. If you want to be extra sure, you can back up the `%appdata%\DBeaverData\workspace6` folder.

**Comment by Benoit0007** [comment]
Same issue, i don't understand ...
i will try older version

**Comment by Benoit0007** [comment]
i will try older version

**Comment by ShadelessFox** [comment]
Are you sure you're unable to log in because of SSL?

SSL is on a network level, whereas the "access denied" error is on a database level.

I suggest you contact your network administrator if you work in a corporate environment.

**Comment by Benoit0007** [comment]
when i use MYSQL Workbench i can connect to database with the same settings ... but i would like to use DBeaver because MYSQL Workbench show potential compatibility issue with mariadbd

**Comment by ShadelessFox** [comment]
We need to find the culprit of your issue. Please make sure that the credentials you've entered are valid.

**Comment by Benoit0007** [comment]
Credential are ok. My SSL settings is the following :
**In connection settings => SSL tab
Use SSL checked
CA certificate : path to pem file is set
Client Certificate : path to pem file is set
Client Private Key : path to pem file is set
Require SSL checked**

**Driver properties everything to default, unless i added user properties :
enabledTLSProtocols TLSv1.2**

I don't know if this settings are rights but it works last time i used DBeaver. 

What parameters would you set for ssl connection with certificate (X509)?

**Comment by ShadelessFox** [comment]
Are you using SSH?

**Comment by Benoit0007** [comment]
No iam using TLS 1.2 with X509

**Comment by ShadelessFox** [comment]
SSH is not the same as SSL. Are you connecting to `localhost`?

It doesn't look like DBeaver anymore since you're claiming it has also stopped working for older versions.

**Comment by Benoit0007** [comment]
As i said i use SSL/TLS not ssh

**Comment by ShadelessFox** [comment]
I'm just trying to understand what is going on.

Sorry, I don't have any other ideas but that your credentials are invalid.

Try performing a clean installation of an older DBeaver version and switch to a new workspace by choosing <kbd>File</kbd> &rArr; <kbd>Switch Workspace</kbd> &rArr; <kbd>Other</kbd> to see if it helps.

**Comment by E1izabeth** [comment]
Does this issue still actual?

**Comment by uslss** [comment]
There has been no update for a long time.
If the issue is still actual for you - feel free to reopen it with additional info.
