### ISSUE TITLE
Lost Connections after upgrading to 22.3.2

### ISSUE THREAD

**Issue by vvrnv** [dbeaver/dbeaver#18814]
### Description

All of my connections disappeared after upgrading 22.3.2

### DBeaver Version

22.3.2

### Operating System

macOS Monterey 12.6

### Database and driver

PostgreSQL

### Steps to reproduce

1. Open DBeaver App
2. Update to latest version from notification popup
3. Open DBeaver new version

### Additional context

<details>
  <summary>Logs</summary>
!ENTRY org.eclipse.ui 2 2 2023-01-19 17:08:25.545
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2023-01-19 17:11:08.395 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_RU
Framework arguments:  -keyring /Users/voronov2/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/voronov2/.eclipse_keyring

!ENTRY org.eclipse.core.resources 4 567 2023-01-19 17:11:11.272
!MESSAGE Workspace restored, but some problems occurred.
!SUBENTRY 1 org.eclipse.core.resources 4 567 2023-01-19 17:11:11.272
!MESSAGE Could not read metadata for 'DBeaver.app'.
!STACK 1
org.eclipse.core.internal.resources.ResourceException(/DBeaver.app)[567]: java.lang.Exception: The project description file (.project) for 'DBeaver.app' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:908)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:895)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:875)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:731)
	at org.eclipse.core.internal.resources.SaveManager.startup(SaveManager.java:1585)
	at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2547)
	at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2252)
	at org.eclipse.core.resources.ResourcesPlugin$WorkspaceInitCustomizer.addingService(ResourcesPlugin.java:571)
	at org.eclipse.core.resources.ResourcesPlugin$WorkspaceInitCustomizer.addingService(ResourcesPlugin.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
	at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:545)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.core.DesktopPlatform.initialize(DesktopPlatform.java:174)
	at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:116)
	at org.jkiss.dbeaver.core.DesktopPlatform.getInstance(DesktopPlatform.java:96)
	at org.jkiss.dbeaver.core.DesktopAdapterFactory.getAdapter(DesktopAdapterFactory.java:33)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$13(AdapterManager.java:302)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:778)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:753)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:768)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
  </details>

**Comment by mkkeems** [comment]
Same thing happened when updating on Mac Ventura 13.1 😭
All of my previous connections are gone.

Is there any way to recover previous connections?

**Comment by ShadelessFox** [comment]
Hello @vvrnv @mkkeems,

Can you please send information from the <kbd>Help</kbd> &rArr; <kbd>Installation Information</kbd> &rArr; <kbd>Configuration</kbd>?

**Comment by vvrnv** [comment]
Hi, @ShadelessFox 

Can't paste to comment cause maximum is 65536 characters, sent via https://pastebin.com/zhU45gqP

**Comment by arhayka** [comment]
Could you please find this file .dbeaver/data-sources.json  following this guide https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections? Let us know if it is empty.

And could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by vvrnv** [comment]
@arhayka yes, file exists, but there is only 1 connection in it. must be at least 6
```sh
➜  ~ cat Library/DBeaverData/workspace6/General/.dbeaver/data-sources.json
{
	"folders": {},
	"connections": {
		"postgres-jdbc-183649eec1b-4b82d7d50b780c8a": {
			"provider": "postgresql",
			"driver": "postgres-jdbc",
			"name": "*SECRET*",
			"save-password": true,
			"read-only": false,
			"configuration": {
				"host": "127.0.0.1",
				"port": "5432",
				"database": "postgres",
				"url": "jdbc:postgresql://127.0.0.1:5432/postgres",
				"configurationType": "MANUAL",
				"home": "/usr/local/Cellar/postgresql@14/14.3",
				"type": "dev",
				"provider-properties": {
					"@dbeaver-show-non-default-db@": "false",
					"@dbeaver-show-template-db@": "false",
					"@dbeaver-show-unavailable-db@": "false",
					"show-database-statistics": "false",
					"@dbeaver-read-all-data-types-db@": "false",
					"read-keys-with-columns": "false",
					"@dbeaver-use-prepared-statements-db@": "false",
					"postgresql.dd.plain.string": "false",
					"postgresql.dd.tag.string": "false"
				},
				"auth-model": "native",
				"handlers": {
					"ssh_tunnel": {
						"type": "TUNNEL",
						"enabled": true,
						"save-password": true,
						"properties": {
							"host": "*SECRET*",
							"port": 22,
							"authType": "PUBLIC_KEY",
							"keyPath": "/Users/voronov2/.ssh/id_rsa_old_format",
							"implementation": "jsch",
							"bypassHostVerification": false,
							"localHost": "",
							"remoteHost": ""
						}
					}
				}
			}
		}
	},
	"connection-types": {
		"dev": {
			"name": "Development",
			"color": "255,255,255",
			"description": "Regular development database",
			"auto-commit": true,
			"confirm-execute": false,
			"confirm-data-change": false,
			"auto-close-transactions": false
		}
	}
}%
```

Log files attached logs attached in first message

**Comment by arhayka** [comment]
Could you remember if you've changed the workspace?
And please try reinstalling DBeaver, this may help.

**Comment by vvrnv** [comment]
@arhayka No, i didn't do it. Already updated to latest version and reinstalled app, didn't help

**Comment by E1izabeth** [comment]
@vvrnv do you have ` }%` at the end of the file or it's just a typo in your comment?

**Comment by vvrnv** [comment]
@E1izabeth, my shell shows EOF

**Comment by E1izabeth** [comment]
So, no `%` character in the file?

**Comment by vvrnv** [comment]
no

**Comment by E1izabeth** [comment]
Thanks for the quick reply.

**Comment by E1izabeth** [comment]
Could you try to resetting workspace? You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings#manual-reset

**Comment by vvrnv** [comment]
only 1 very old connection was restored. didn't help.

**Comment by E1izabeth** [comment]
Which version did you use before update?

Also could you try executing `sudo find / -name "DBeaverData" 2> /dev/null` and show results?

**Comment by mkkeems** [comment]
> Hello @vvrnv @mkkeems,
> 
> Can you please send information from the Help ⇒ Installation Information ⇒ Configuration?

Ah, I ended up manually reconnecting to all the db's I lost before I saw you asked this question 😭 
I don't remember exactly which version it was, but was most likely one of the recent releases of dbeaver that was available in late January 2023 because it happened on a brand new 2021 m1 macbook pro purchased on 1/1/2023 (so the dbeaver that I was updating was already a fairly newer version(stable release at that point from official website), no massive backed up update).
But ever since that one incident, I haven't had the same problem with the newer updates. Thank you.

**Comment by E1izabeth** [comment]
Thank you. I'm asking about version before upgrading to 22.3.2, because there might be an issues while upgrading from very old version like 6.x.x (for example)

**Comment by vvrnv** [comment]
> Which version did you use before update?

idk, 21.x.x or 20.x.x 

> Also could you try executing sudo find / -name "DBeaverData" 2> /dev/null and show results?

`
/System/Volumes/Data/Users/voronov2/Library/DBeaverData
/System/Volumes/Data/Volumes/BACKUP EXT DRIVE/2023-04-07-095539.previous/Macintosh HD - Data/Users/voronov2/Library/DBeaverData
/Users/voronov2/Library/DBeaverData
/Volumes/BACKUP EXT DRIVE/2023-04-07-095539.previous/Macintosh HD - Data/Users/voronov2/Library/DBeaverData
`

**Comment by ShadelessFox** [comment]
Hello @vvrnv,

Can you please switch the workspace to every listed one to see if one of them contains all your connections?

It can be done using <kbd>File</kbd> &rArr; <kbd>Switch Workspace</kbd> &rArr; <kbd>Other...</kbd>

**Comment by vvrnv** [comment]
Hi @ShadelessFox,
yes, I did, but nothing happened, these workspaces are empty, or rather one is empty, and the rest are copies of backup in time machine

**Comment by ShadelessFox** [comment]
I was hoping one of the backups would be your lost workspace. Thanks for your assistance anyways.

**Comment by Destrolaric** [comment]
@vvrnv Unfortunately, We can't do anything to resolve this situation. If the issue happens again, please feel free to reopen the ticket.

**Comment by d8ccdb3c-647c-4b5e-919a-bda3d38d548a** [comment]
Same thing after upgrading community version from 24.2.0 to 24.2.0 . Everything disappeared.
