### ISSUE TITLE
Azure Synapse Serverless: Cannot export data

### ISSUE THREAD

**Issue by dr-1** [dbeaver/dbeaver#18820]
### Description

Data exports from queries on a Azure Synapse "serverless" database fail with this error, although query results are shown.

`SQL Error [15871] [S0006]:  '@@TRANCOUNT' is not supported.`

### DBeaver Version

22.3.1

### Operating System

Windows 10

### Database and driver

Database: Azure Synapse "serverless"
Server: Microsoft SQL Server 12.00.2531, Microsoft Azure SQL Data Warehouse - 10.0.15318.0
Driver: Microsoft JDBC Driver 9.2 for SQL Server 9.2.0.0

### Steps to reproduce

1. Run a SELECT query on a table or view
2. Click "Export data" in the results pane
3. Leaving the default export settings, click "Proceed"
4. Observe error message

**Comment by LonwoLonwo** [comment]
Hello @dr-1 

Could you please provide the log files? You can find instruction here https://dbeaver.com/docs/wiki/Log-files/

**Comment by dr-1** [comment]
Hello @LonwoLonwo, this is the log:

```
!SESSION 2023-01-23 08:35:06.241 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-23 08:41:04.488
!MESSAGE Error transfering data from -- Get list of views and tables.¶-- Used to compare Dev and Prd to identify obsolete objects in Prd.¶SELECT¶    s.name AS schema_name¶    , o.name¶    , o.type_desc¶--    , o.object_id¶--    , o.create_date¶--    , o.modify_date¶--    , m.definition AS object_definition¶--  OBJECT_DEFINITION(v.object_id) AS object_definition¶        -- Works in Serverless but not supported in Dedicated¶FROM¶    sys.objects AS o¶    LEFT JOIN sys.schemas AS s ON s.schema_id = o.schema_id¶    LEFT JOIN sys.sql_modules AS m ON m.object_id = o.object_id¶WHERE o.type_desc IN ('USER_TABLE', 'VIEW')¶ORDER BY¶    s.name¶    , o.name¶--    o.modify_date DESC to 2023-01-23_084103.csv
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-23 08:41:04.488
!MESSAGE SQL Error [15871] [S0006]:  '@@TRANCOUNT' is not supported.
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-01-23 08:41:04.488
!MESSAGE  '@@TRANCOUNT' is not supported.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException:  '@@TRANCOUNT' is not supported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:3316)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:3320)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:3516)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.rollback(JDBCExecutionContext.java:445)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:284)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-23 08:41:04.576
!MESSAGE  '@@TRANCOUNT' is not supported.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-23 08:41:04.576
!MESSAGE  '@@TRANCOUNT' is not supported.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException:  '@@TRANCOUNT' is not supported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:3316)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:3320)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:3516)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.rollback(JDBCExecutionContext.java:445)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:284)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by LonwoLonwo** [comment]
What commit mode did you use for this operation? Autcommit or manual commit?

**Comment by dr-1** [comment]
This was done in autocommit mode. I get the same failure in manual commit (read committed) mode.

**Comment by LonwoLonwo** [comment]
I see this ('@@TRANCOUNT') function in the Microsoft JDBC driver

![2023-01-23 13_44_28-DBeaver  C__Users_anvolka_work_DbeaverP_dbeaver-workspace-idea  - C__Users_anvol](https://user-images.githubusercontent.com/45152336/214021860-42e58deb-afdc-4e0e-b396-8750a4896725.png)

Small workaround for now - to disable this export setting:

![2023-01-23 13_48_53-Data Transfer](https://user-images.githubusercontent.com/45152336/214022052-d4f31523-e84d-424c-b67e-48bd27e6bbda.png)

Looking for other options...

**Comment by LonwoLonwo** [comment]
Report created: https://github.com/microsoft/mssql-jdbc/issues/2071
