### ISSUE TITLE
Hiveserver2 connection failedout

### ISSUE THREAD

**Issue by venkuven** [dbeaver/dbeaver#18850]
### Description

I have a single node MapR cluster there is hive installed in Rhel 8.4 version . so i am trying to connect hive in windows it is showing below error.

Could not open client transport with JDBC Uri: jdbc:hive2://10.10.10.48:10000/default: Invalid status 21
  Invalid status 21
  Invalid status 21
![image](https://user-images.githubusercontent.com/123405529/214117599-6a7f98e8-8051-44ef-b389-6b3f680746b6.png)

### DBeaver Version

DBeaver 22.3.2

### Operating System

windows 11

### Database and driver

1.Hive
2. hive-jdbc-uber-2.6.5.0-292

**Comment by venkuven** [comment]
Please give me a solution as soon as possible I appreciate it.

**Comment by E1izabeth** [comment]
Could you please send the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.
Thank you.

**Comment by venkuven** [comment]
!SESSION 2023-01-19 14:21:16.273 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-01-19 14:21:23.582
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:23:13.670
!MESSAGE Invalid status 21
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:23:13.670
!MESSAGE Invalid status 21
!STACK 0
org.apache.thrift.transport.TTransportException: Invalid status 21
	at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:307)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:244)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:206)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.hive.model.HiveDataSource.<init>(HiveDataSource.java:45)
	at org.jkiss.dbeaver.ext.hive.model.HiveMetaModel.createDataSourceImpl(HiveMetaModel.java:51)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:23:54.852
!MESSAGE mapr.cluster
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:23:54.852
!MESSAGE mapr.cluster
!STACK 0
java.net.UnknownHostException: mapr.cluster
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:266)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:244)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:206)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.hive.model.HiveDataSource.<init>(HiveDataSource.java:45)
	at org.jkiss.dbeaver.ext.hive.model.HiveMetaModel.createDataSourceImpl(HiveMetaModel.java:51)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:24:49.299
!MESSAGE Connection timed out: connect
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:24:49.299
!MESSAGE Connection timed out: connect
!STACK 0
java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:266)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:244)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:206)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.hive.model.HiveDataSource.<init>(HiveDataSource.java:45)
	at org.jkiss.dbeaver.ext.hive.model.HiveMetaModel.createDataSourceImpl(HiveMetaModel.java:51)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:25:32.846
!MESSAGE Connection timed out: connect
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:25:32.846
!MESSAGE Connection timed out: connect
!STACK 0
java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:266)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:244)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:206)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.hive.model.HiveDataSource.<init>(HiveDataSource.java:45)
	at org.jkiss.dbeaver.ext.hive.model.HiveMetaModel.createDataSourceImpl(HiveMetaModel.java:51)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:26:17.586
!MESSAGE Cannot establish tunnel to 43.204.118.220:22
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:26:17.586
!MESSAGE Cannot establish tunnel to 43.204.118.220:22
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-01-19 14:26:17.586
!MESSAGE Could not verify `ssh-ed25519` host key with fingerprint `83:97:cb:bd:70:ac:c3:cc:fb:8f:2f:2a:d8:a9:e1:ea` for `43.204.118.220` on port 22
!STACK 0
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ssh-ed25519` host key with fingerprint `83:97:cb:bd:70:ac:c3:cc:fb:8f:2f:2a:d8:a9:e1:ea` for `43.204.118.220` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:220)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:389)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:485)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-01-19 14:30:43.787
!MESSAGE Cannot establish tunnel to 43.204.118.220:22
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-01-19 14:30:43.787
!MESSAGE Cannot establish tunnel to 43.204.118.220:22
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-01-19 14:30:43.787
!MESSAGE Could not verify `ssh-ed25519` host key with fingerprint `83:97:cb:bd:70:ac:c3:cc:fb:8f:2f:2a:d8:a9:e1:ea` for `43.204.118.220` on port 22
!STACK 0
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ssh-ed25519` host key with fingerprint `83:97:cb:bd:70:ac:c3:cc:fb:8f:2f:2a:d8:a9:e1:ea` for `43.204.118.220` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:220)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:389)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:485)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)

**Comment by E1izabeth** [comment]
Do you use ssh for hive connection?

**Comment by venkuven** [comment]
Yes i tried but no luck, 
before i tried jdbc:hive2://<hostname>:10000/databasename

**Comment by E1izabeth** [comment]
@venkuven could you check if ssh tunnel can be established?
![image](https://user-images.githubusercontent.com/28875055/216346249-d3f43adf-8672-429b-926a-5f0015a77b1c.png)

**Comment by E1izabeth** [comment]
It's a long time since no update on this issue. If it's still actual, please, let me know.
