### ISSUE TITLE
Export data window crashes occasionally

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#18941]
### Description

It happens from time o time. When choosing Export data feature, export window opens and throws exception.
It's not reproducible in 100% cases. Sometimes it works. Siometimes it works after DBeaver restart to throw exception with another try.

![image](https://user-images.githubusercontent.com/7868445/216619843-2a82a2ea-da5d-448c-a664-05d6481385ff.png)

Here are snipets of db log (complete log is too big to include)
```
!ENTRY org.eclipse.ui 4 0 2023-02-03 14:56:30.017
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.StackOverflowError
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:43)
	at org.eclipse.core.commands.Command.fireCommandChanged(Command.java:522)
	at org.eclipse.core.commands.Command.lambda$0(Command.java:1002)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.fireHandlerChanged(HandlerServiceHandler.java:180)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.handlerChanged(E4HandlerProxy.java:115)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.ui.internal.handlers.HandlerProxy.lambda$1(HandlerProxy.java:372)
```

```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-03 14:56:30.065
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-03 14:56:30.065
!MESSAGE StackOverflowError
!STACK 0
java.lang.StackOverflowError
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:43)
	at org.eclipse.core.commands.Command.fireCommandChanged(Command.java:522)
	at org.eclipse.core.commands.Command.lambda$0(Command.java:1002)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.fireHandlerChanged(HandlerServiceHandler.java:180)
```

### DBeaver Version

22.3.3

### Operating System

Fedora 37

### Database and driver

postgres-jdbc

### Steps to reproduce

1. Selected from table (with lot records)
2. right click on left corner of the grid
3. select Export Data
4. At this point window is opening and right after exception might be thrown

### Additional context

The issue was appearing in previous versions of DBeaver (ie half year ago)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by arhayka** [comment]
Could you provide a video with the issue and more details regarding your graphical environment and the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a long time since no update here. If you encounter this issue again, please let me know and provide additional info.

**Comment by MarcusStaile** [comment]
I got the same issue. I'm on 23.1.4 Dbeaver-CE and Ubuntu 20.04. 

Here the logs : 
`(DBeaver:3605184):` Gtk-WARNING **: 15:02:12.518: Negative content width -8 (allocation 5, extents 6x7) while allocating gadget (node separator, owner GtkSeparatorToolItem)
2023-08-10 15:02:14.263 - Event loop exception
java.lang.StackOverflowError
	at org.eclipse.core.commands.NamedHandleObjectWithState.getName(NamedHandleObjectWithState.java:89)
	at org.eclipse.ui.menus.CommandContributionItem.updateMenuItem(CommandContributionItem.java:500)
	at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:484)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$2(CommandContributionItem.java:323)
	at org.eclipse.ui.menus.CommandContributionItem.updateCommandProperties(CommandContributionItem.java:327)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$1(CommandContributionItem.java:294)
	at org.eclipse.core.commands.Command$1.run(Command.java:529)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.commands.Command.fireCommandChanged(Command.java:522)
	at org.eclipse.core.commands.Command.lambda$0(Command.java:1002)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.fireHandlerChanged(HandlerServiceHandler.java:180)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.handlerChanged(E4HandlerProxy.java:115)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.ui.internal.handlers.HandlerProxy.lambda$1(HandlerProxy.java:372)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.core.commands.AbstractHandler.setBaseEnabled(AbstractHandler.java:111)
	at org.eclipse.ui.texteditor.AbstractTextZoomHandler.setEnabled(AbstractTextZoomHandler.java:131)
	at org.eclipse.ui.texteditor.TextZoomInHandler.setEnabled(TextZoomInHandler.java:1)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:229)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.setEnabled(E4HandlerProxy.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:309)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:243)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:84)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:856)
	at org.eclipse.ui.menus.CommandContributionItem.isEnabled(CommandContributionItem.java:916)
	at org.eclipse.ui.menus.CommandContributionItem.updateMenuItem(CommandContributionItem.java:531)
	at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:484)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$2(CommandContributionItem.java:323)
	at org.eclipse.ui.menus.CommandContributionItem.updateCommandProperties(CommandContributionItem.java:327)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$1(CommandContributionItem.java:294)
	at org.eclipse.core.commands.Command$1.run(Command.java:529)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
`

**Comment by inghamn** [comment]
Ubuntu 22.04
DBEaver 23.1.5

I also get this often.  I end up having to force quit and restart.  Right now, it seems to originate in org.jkiss.dbeaver.model or org.eclipse.ui

[exception.log](https://github.com/dbeaver/dbeaver/files/12429760/exception.log)

**Comment by E1izabeth** [comment]
You can vote for the issue with 👍 under the issue description to promote it to a higher priority.

**Comment by danielcwilliams** [comment]
Happening for me in Version 23.3.0.202312031432; traceback log [foo.txt](https://github.com/dbeaver/dbeaver/files/13674379/foo.txt) attached.

**Comment by praesagio** [comment]
[dbeaver export error.log](https://github.com/dbeaver/dbeaver/files/13895270/dbeaver.export.error.log)
Was having this error on 23.1.0, just upgraded to 23.3.2 today and the error is still happening, uploaded log

**Comment by oliba723** [comment]
OpenJDK 21
Ubuntu 22.04
dbeaver 24.3.1

Issue has come up again with latest dbeaver 24.3.1 . This time it happens every time I open the data transfer dialog.

Downgrading back to 24.2.4 solved the problem.

**Comment by michal-bartak** [comment]
I saw it recently in 24.3 or a version before
