### ISSUE TITLE
Cannot open DB connection after upgrading to 22.3.4.202302041940

### ISSUE THREAD

**Issue by i326998** [dbeaver/dbeaver#18975]
### Description

Error 'This method is deprecated and marked for removal. Use the getPeerCertificates() method instead.' happened after upgrading to version 22.3.4.202302041940 when double click db connection

### DBeaver Version

Community Edition 22.3.4.202302041940

### Operating System

macOS Ventura 13.2

**Comment by LonwoLonwo** [comment]
Hello @i326998 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by i326998** [comment]
[DBeaver_ErrorLog.txt](https://github.com/dbeaver/dbeaver/files/10672833/DBeaver_ErrorLog.txt)
Hi @LonwoLonwo  
Please refer to the attached log file.

**Comment by LonwoLonwo** [comment]
https://bugs.openjdk.org/browse/JDK-8241047

```
java.lang.UnsupportedOperationException: This method is deprecated and marked for removal. Use the getPeerCertificates() method instead.
	at java.base/javax.net.ssl.SSLSession.getPeerCertificateChain(Unknown Source)
	at com.sap.db.jdbc.SecureSession._finishSSLInit(SecureSession.java:255)
	at com.sap.db.jdbc.SecureSession.<init>(SecureSession.java:99)
	at com.sap.db.jdbc.SecureSession$1.newInstance(SecureSession.java:37)
	at com.sap.db.jdbc.Session.newInstance(Session.java:116)
	at com.sap.db.jdbc.ConnectionSapDB._connectAnchor(ConnectionSapDB.java:2245)
	at com.sap.db.jdbc.DriverSapDB._connect(DriverSapDB.java:2407)
	at com.sap.db.jdbc.DriverSapDB.connect(DriverSapDB.java:2063)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.hana.model.HANADataSource.<init>(HANADataSource.java:66)
	at org.jkiss.dbeaver.ext.hana.model.HANAMetaModel.createDataSourceImpl(HANAMetaModel.java:64)
```

**Comment by LonwoLonwo** [comment]
Thanks for the report @i326998

**Comment by serge-rider** [comment]
@i326998 could you say what HANA driver version do you use? You can get this info by clicking "Driver settings" in the connection edit dialog -> libraries -> download/update.
Possibly you have an outdated driver which doesn't support new Java versions.

**Comment by i326998** [comment]
@serge-rider Thanks a lot for your help! Connect success after download the latest driver
