### ISSUE TITLE
Can't connect to MS SQL Server using Kerberos

### ISSUE THREAD

**Issue by vpetryaev** [dbeaver/dbeaver#18978]
### Description

Can't connect to MS SQL Server using Kerberos after upgrading to 22.3.4

Integrated authentication failed. ClientConnectionId:4dc878ab-f699-4e09-9c64-8beb561f9f9e
  GSSException: No valid credentials provided (Mechanism level: KDC has no support for encryption type (14))
  No valid credentials provided (Mechanism level: KDC has no support for encryption type (14))
    KrbException: KDC has no support for encryption type (14)
    KDC has no support for encryption type (14)
      Identifier doesn't match expected value (906)
      Identifier doesn't match expected value (906)

After reverting to 22.3.3 - problem disappear

### DBeaver Version

Community Edition 22.3.4

### Operating System

Ubuntu 20.04

### Database and driver

Microsoft JDBC Driver for SQL Server 9.2.0.jre8

### Steps to reproduce

Try to use Kerberos authentication for MS SQL Server.

### Additional context

Kerberos ticket acquired using:
/bin/cat ~/.config/pw | /bin/kinit -F -p -r 7d username
and periodically refreshed using:
/bin/kinit -R

klist -V shown "Kerberos 5 version 1.17"

**Comment by LonwoLonwo** [comment]
Hello @vpetryaev 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

Also, can you provide steps about Kerberos authentication in DBeaver in your case? How did you use it?

**Comment by vpetryaev** [comment]
!ENTRY org.eclipse.ui 2 2 2023-02-07 09:29:39.872
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2023-02-07 09:30:18.698 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-02-07 09:30:25.321
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-07 09:30:43.372
!MESSAGE Identifier doesn't match expected value (906)
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-07 09:30:43.372
!MESSAGE Identifier doesn't match expected value (906)
!STACK 0
KrbException: Identifier doesn't match expected value (906)
        at java.security.jgss/sun.security.krb5.internal.KDCRep.init(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.TGSRep.init(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.TGSRep.<init>(Unknown Source)
        at java.security.jgss/sun.security.krb5.KrbTgsRep.<init>(Unknown Source)
        at java.security.jgss/sun.security.krb5.KrbTgsReq.getReply(Unknown Source)
        at java.security.jgss/sun.security.krb5.KrbTgsReq.sendAndGetCreds(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.serviceCredsSingle(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.serviceCreds(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.serviceCreds(Unknown Source)
        at java.security.jgss/sun.security.krb5.internal.CredentialsUtil.acquireServiceCreds(Unknown Source)
        at java.security.jgss/sun.security.krb5.Credentials.acquireServiceCreds(Unknown Source)
        at java.security.jgss/sun.security.jgss.krb5.Krb5Context.initSecContext(Unknown Source)
        at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
        at java.security.jgss/sun.security.jgss.GSSContextImpl.initSecContext(Unknown Source)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthHandShake(KerbAuthentication.java:158)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.generateClientContext(KerbAuthentication.java:209)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5078)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4068)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4006)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
        at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:80)
        at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:137)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1180)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1049)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by vpetryaev** [comment]
Driver properties (not default only):
authenticationScheme: javaKerberos
integratedSecurity: true
serverSpn: MSSQLSvc/msk-optsql106.corp.suek.ru:1433@CORP.SUEK.RU

**Comment by vpetryaev** [comment]
klist output:
Ticket cache: FILE:/tmp/krb5cc_1001
Default principal: petriaevvv@CORP.SUEK.RU

Valid starting       Expires              Service principal
07.02.2023 11:07:11  07.02.2023 21:07:11  krbtgt/CORP.SUEK.RU@CORP.SUEK.RU
        renew until 14.02.2023 11:07:10

**Comment by LonwoLonwo** [comment]
Please check your connection with the newest SQL Server driver versions.

![2023-02-09 12_43_20-DBeaver 22 3 4](https://user-images.githubusercontent.com/45152336/217777272-f0a6e36c-ecfc-4bea-80b7-94f51cfa92d5.png)

**Comment by vpetryaev** [comment]
Some changed, but still can connect using Kerberos authentication in 22.3.3 and found error in 22.3.4
Looks like it can't obtain user name from Kerberos cache.

!ENTRY org.jkiss.dbeaver.model 4 0 2023-02-09 13:12:48.076
!MESSAGE Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-02-09 13:12:48.076
!MESSAGE Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user
!STACK 0
javax.security.auth.login.LoginException: Cannot get any of properties: [user, USER] from con properties not available to garner  authentication information  from the user
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForName(Unknown Source)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Unknown Source)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext.invoke(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext$4.run(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext.login(Unknown Source)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.intAuthInit(KerbAuthentication.java:77)
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.generateClientContext(KerbAuthentication.java:207)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6030)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4911)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:90)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4849)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
        at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:80)
        at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:137)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1180)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1049)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Your issue is likely connected with the newest version of Java that we added in the last release.
Java was repacked in the Early Access version. Can you please check this version? https://dbeaver.io/files/ea/

**Comment by vpetryaev** [comment]
> Can you please check this version? https://dbeaver.io/files/ea/

Still the same issue as in 22.3.4 release

**Comment by Destrolaric** [comment]
> Kerberos
> Deprecate 3DES and RC4 in Kerberos
> 
> 3DES and RC4 Kerberos encryption types have now been disabled by default. Both 3DES and RC4 are weak encryption algorithms that should not be used. The Kerberos 3DES and RC4 encryption types are officially deprecated in [RFC 8429](https://datatracker.ietf.org/doc/html/rfc8429).
> 
> By default the des3-hmac-sha1 and rc4-hmac encryption types are now disabled, but can be re-enabled, at your own risk, by setting the allow_weak_crypto property to true in the krb5.conf configuration file. However, note that will also re-enable other weak encryption types that are already disabled such as des-cbc-crc and des-cbc-md5. Alternatively, set the default_tkt_enctypes, default_tgs_enctypes, and permitted_enctypes properties to the encryption types that are allowed.
> 
> Issue: [JDK-8139348](https://bugs.openjdk.java.net/browse/JDK-8139348)

Possible reason

**Comment by vpetryaev** [comment]
> > Issue: [JDK-8139348](https://bugs.openjdk.java.net/browse/JDK-8139348)
> 
> Possible reason

Initially I posted:
> klist -V shown "Kerberos 5 version 1.17"

Following your link:
> MIT krb5 has done this in 1.14

Valid starting       Expires              Service principal
09.02.2023 20:00:02  10.02.2023 06:00:02  krbtgt/CORP.SUEK.RU@CORP.SUEK.RU
        renew until 16.02.2023 12:00:01, Etype (skey, tkt): arcfour-hmac, aes256-cts-hmac-sha1-96

**Comment by vpetryaev** [comment]
DBeaver 22.3.5 - still the same issue

**Comment by serge-rider** [comment]
Seems to be related.
https://stackoverflow.com/questions/23801169/kdc-has-no-support-for-encryption-type-14 

In 22.3.3 we upgraded to Java 17, some encryption settings may change.
We still trying to figure out how Java 17 affects Kerberos in SQL Server.

**Comment by serge-rider** [comment]
In the new Java Kerberos authentication is more strict. For instance it validates that realm matches KDC realm exactly (full domain name).

To get more debug info you can add line 
`-Dsun.security.krb5.debug=true` in the end of dbeaver.ini file.

Then restart DBeaver, try to connect and then look at dbeaver-debug.log file.

**Comment by ceresaconsultoria** [comment]
I'm witth same problem

---

Can't create driver instance
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
  Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
    com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

----

![image](https://user-images.githubusercontent.com/56128744/221951440-51e19d84-b863-4674-a7b0-af0c320cd172.png)

**Comment by serge-rider** [comment]
@ceresaconsultoria This issue was fixed in the latest Early Access version.

**Comment by ceresaconsultoria** [comment]
My version is *22.3.5*, what is new version?

Linux mint 21.1 reference Ubuntu 22.04

Atenciosamente,
--


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/03/23,
11:21:08

Em qua., 1 de mar. de 2023 às 05:38, Serge Rider ***@***.***>
escreveu:

**Comment by serge-rider** [comment]
New version is 23.0.
Early Access package can be downloaded at https://dbeaver.io/files/ea

**Comment by ceresaconsultoria** [comment]
I installed it and it worked, thanks for the support
