### ISSUE TITLE
Cannot run program "/usr/lib/postgresql/14/bin/pg_dump" (in directory "/usr/lib/postgresql/14/bin"): error=13, Permission denied

### ISSUE THREAD

**Issue by darrahts** [dbeaver/dbeaver#19055]
### Description

Title says it all. `pg_dump` has full rwx permissions for all users, and I've tried changing ownership (user and group) from `root:root` to `my_user:my_user` and to `postgres:postgres` but still get this error. 

I am able to run `pg_dump` from the command line without problem. This issue happened in 22.1.x, and then I upgraded to 22.3.4 and still persists. I saw some related issues, but found nothing that helped.

Thanks in advance!

### DBeaver Version

22.3.4

### Operating System

Linux 20.04.1 

### Database and driver

1. postgres 14
2. jdbc 4.2.25

### Steps to reproduce

1. right click database --> tools --> backup
2. select objects, click 'next'
3. select format --> tar (issue reproducible regardless of format)
4. select output folder --> `/home/my_user`
5. click start

**Comment by E1izabeth** [comment]
Thank you for bug report. It's a known issue of the last release and we have already fixed it. You can download early access version here https://dbeaver.io/files/ea/.

Closing as a duplicate of #18958

**Comment by RegisSalesRA** [comment]
> Thank you for bug report. It's a known issue of the last release and we have already fixed it. You can download early access version here https://dbeaver.io/files/ea/.
> 
> Closing as a duplicate of #18958

I am still having the same error even with the version I downloaded that you made available,  in my case i still using lixux mint version 21

**Comment by E1izabeth** [comment]
Thank you for feedback.

**Comment by Destrolaric** [comment]
@RegisSalesRA Which installation method was used?

**Comment by RegisSalesRA** [comment]
> @RegisSalesRA Which installation method was used?

I installed it using the linux mint software manager, I love this tool, I ended up installing the 21.0.1 version that is on the site and pg_dump worked perfectly

**Comment by E1izabeth** [comment]
The issue should be solved in 22.3.5.

**Comment by LonwoLonwo** [comment]
Hello

Can you please test the Early Access DBeaver version? https://dbeaver.io/files/ea/ Is the issue solved there?

**Comment by E1izabeth** [comment]
it's been a long time since no update on this issue. Please let me know, if it's still actual.

**Comment by toramanlis** [comment]
@E1izabeth It is still very much actual and I spent all Saturday investigating. I think I can help pinpoint the cause.

First, my setup:
OS: Kubuntu 20.04 (5.15.6-051506-generic)
Dbeaver: 23.0.2.202304091457 (Snap)
External Tool: mysqldump  Ver 10.19 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64)
App Armor: 3.0.4-2ubuntu2.2 amd64

I think you probably know where I'm going with this since I threw the apparmor info in there :)

On this version of dbeaver, when I enter `/usr/bin` in the local client, it converts the path to a runtime path from document portal like `/run/user/1000/doc/91031a16/bin`

When I start the dump, I get this:
```
2023-04-16 12:48:38.019 - IO error: Cannot run program "/run/user/1000/doc/91031a16/bin/mysqldump" (in directory "/run/user/1000/doc/91031a16/bin"): error=13, Permission denied
2023-04-16 12:48:38.020 - java.io.IOException: Cannot run program "/run/user/1000/doc/91031a16/bin/mysqldump" (in directory "/run/user/1000/doc/91031a16/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 8 more
```

I start bash from inside the confinement with:
```
snap run --shell dbeaver-ce
```

output of `ls -l /run/user/1000/doc/91031a16/bin/mysqldump`:
```
lrwxrwxrwx 1 root root 12 Feb 10 09:57 /run/user/1000/doc/91031a16/bin/mysqldump -> mariadb-dump
```

output of `ls -l /run/user/1000/doc/91031a16/bin/mariadb-dump`:
```
-rwxr-xr-x 1 root root 4035360 Feb 10 09:57 /run/user/1000/doc/91031a16/bin/mariadb-dump
```

ouput of `journalctl --since=-1m | grep denied | grep dbeaver`:
```
Apr 16 12:57:35 timucin-desktop audit[98830]: AVC apparmor="DENIED" operation="exec" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/doc/91031a16/bin/mariadb-dump" pid=98830 comm="jspawnhelper" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Apr 16 12:57:35 timucin-desktop kernel: audit: type=1400 audit(1681639055.817:364): apparmor="DENIED" operation="exec" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/doc/91031a16/bin/mariadb-dump" pid=98830 comm="jspawnhelper" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Apr 16 12:57:35 timucin-desktop audit[98831]: AVC apparmor="DENIED" operation="exec" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/doc/91031a16/bin/mariadb-dump" pid=98831 comm="jspawnhelper" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Apr 16 12:57:35 timucin-desktop kernel: audit: type=1400 audit(1681639055.821:365): apparmor="DENIED" operation="exec" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/doc/91031a16/bin/mariadb-dump" pid=98831 comm="jspawnhelper" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

Now that we know that it's apparmor who denies the permission, we can test out hypothesis. On line `862` of `/var/lib/snapd/apparmor/profiles/snap.dbeaver-ce.dbeaver-ce`, I changed this line:
```
/run/user/[0-9]*/doc/*/** rw,
```

to this:
```
/run/user/[0-9]*/doc/*/** mrwklix,
```

I prefered `mrwklix` because it's how other lines in the file do it and I just rolled with it. Now, after I let apparmor know about the change with `sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.dbeaver-ce.dbeaver-ce`, I start the dump again and get this:
```
/run/user/1000/doc/91031a16/bin/mysqldump --skip-lock-tables --routines --add-drop-table --disable-keys --extended-insert -u root --host=127.0.0.1 --port=53523 connect
Task 'MySQL dump' started at Sun Apr 16 13:05:49 TRT 2023
/run/user/1000/doc/91031a16/bin/mysqldump: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

Task 'MySQL dump' finished at Sun Apr 16 13:05:49 TRT 2023
2023-04-16 13:05:49.252 - IO error: Process failed (exit code = 127). See error log.
2023-04-16 13:05:49.252 - java.io.IOException: Process failed (exit code = 127). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

No such file or directory indeed because this is the output of `echo $LD_LIBRARY_PATH` in the confinement:
```
/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/225/lib:/snap/dbeaver-ce/225/usr/lib:/snap/dbeaver-ce/225/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/225/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/225/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/225/gnome-platform/usr/lib:/snap/dbeaver-ce/225/gnome-platform/lib:/snap/dbeaver-ce/225/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/225/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/225/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio
```
However none of those paths have the desired `libssl.so.3` in them. However `core22` does. So I downloaded and adjusted dbeaver snap to use `core22` as the base instead of `core20`. Followed the steps to avoid the permission issue and in the confinement, run the command `/run/user/1000/doc/91031a16/bin/mysqldump`:
```
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases
OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
For more options, use mysqldump --help
```

We have quite a deal of progress. So much that conservatives are against it. We can just pack the necessary shared libraries or just declare them as plugs from the appropriate core snaps and we're done.

The remaining issue is how will you decide what libraries to pack? This one's just for my setup and for mysqldump. You'll need to account for every possible library that every possible external tool could use. If only snap had planned further than just sandboxing and offered a solution like one time permission prompt to the user on running commands as them.

Hope this helps. Dbeaver is a great tool with obviously a great team behind but the issues with snap will just make a lot of people think it simply doesn't work. I'll switch to the deb version now. Hope you consider completely giving up on snap too. Cheers

Edit: Sadly realized that snap doesn't let the package adjust apparmor profile for obvious reasons. Embarrassing misconception on my part. However, we have read access to the file, so maybe it can be transferred to elsewhere temporarily for execution. Idk snap should just do whatever it takes to keep dbeaver on board

**Comment by E1izabeth** [comment]
#7521

**Comment by LonwoLonwo** [comment]
Hello everyone.
Is this issue still relevant to you? Still reproducible?

**Comment by hawkeye64** [comment]
I am still having an issue

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy


![image](https://github.com/dbeaver/dbeaver/assets/10262924/9c94733d-71c1-4cc9-aae0-ca41f6b822d6)

**Comment by NorbertSandor** [comment]
@hawkeye64 I know it's just a workaround but switching from _snap_ to _Debian package_ solved the problem for me.

**Comment by hawkeye64** [comment]
> @hawkeye64 I know it's just a workaround but switching from _snap_ to _Debian package_ solved the problem for me.

I was thinking about trying that. I've had issues with other packages installed as a Snap (like vs code).

**Comment by kabeza** [comment]
Hi. I'm having the same issue, using ElementaryOS (Ubuntu 22.04 based) and have installed with snap.
I have the version 24.0.1 and cannot run mysqldump because it looks for in /run/user/1000/doc/96b0e99d/bin and cannot run it, because it is located in /usr/bin

What stuff should I backup so I can remove snap install and try with deb package?

Thanks

**Comment by ericles-adekz** [comment]
Hi, same problem here, but I've installed by deb package from official website

So It isn't working for me :(

**Comment by ericleselias** [comment]
Hi, same problem here, but I've installed by deb package from official website

I've runned `ls -l /run/user/1000/doc/354c5b8f/bin/mysqldump` and got:
`-rwxr-xr-x 1 root root 6879872 jan 17 17:13 /run/user/1000/doc/354c5b8f/bin/mysqldump`

The error is: `2024-04-02 11:54:11.340 - IO error: Cannot run program "/run/user/1000/doc/354c5b8f/bin/mysqldump" (in directory "/run/user/1000/doc/354c5b8f/bin"): error=13, Permission denied`

Please, I would appreciate any help

**Comment by NorbertSandor** [comment]
@ericleselias the path `/run/user/1000/doc/354c5b8f/bin/mysqldump` path still seems to be "snap environment"-related.
Maybe the _Connection Settings / Main / Local Client_ setting in DBeaver still contains such a "transformed" path, not the direct path of your mysql installation.
Try to use a direct path instead, in my case with postgresql it is: `/usr/lib/postgresql/16`
I hope this makes sense and is helpful :)

**Comment by ericleselias** [comment]
> @ericleselias the path `/run/user/1000/doc/354c5b8f/bin/mysqldump` path still seems to be "snap environment"-related. Maybe the _Connection Settings / Main / Local Client_ setting in DBeaver still contains such a "transformed" path, not the direct path of your mysql installation. Try to use a direct path instead, in my case with postgresql it is: `/usr/lib/postgresql/16` I hope this makes sense and is helpful :)

Thanks, you were right, I kind of had 2 dbeaver installations on ubuntu, I removed the dbeaver folder in the snap folder, and the correct dbeaver icon appeared, with the installation done by deb

**Comment by florisdipt** [comment]
> I am still having an issue
> 
> Distributor ID: Ubuntu Description: Ubuntu 22.04.4 LTS Release: 22.04 Codename: jammy
> 
> ![image](https://private-user-images.githubusercontent.com/10262924/315311917-9c94733d-71c1-4cc9-aae0-ca41f6b822d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjIxOTIsIm5iZiI6MTcxMjMyMTg5MiwicGF0aCI6Ii8xMDI2MjkyNC8zMTUzMTE5MTctOWM5NDczM2QtNzFjMS00Y2M5LWFhZTAtY2E0MWY2YjgyMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEyNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwODhlOGExZWMzOTU0ZjJiMzQ3MjhmMTI2MTU1ODYwOTg1MWIzNTQwNmNkNjE3YjcwNjQxZmY0MjVmNjUyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSY5qStDCeEThPQrVskLchk06shEt67JyW7Zf8NkmW4)

Can confirm this is still present in 24.0.1.202403241413 


Can't seem to find a way to get the snap package accept /usr/bin, it will always prefix /run/user/$UID don't know enough about snap to tell if this is a limitation off snap or some configuration issue. 

If this is (partially) not a bug i think  updating the docs a would seem like a good idea as it doesn't have a snap specific section. Especially since there's so many issues I have trouble keeping track of whats what (https://github.com/dbeaver/dbeaver/issues/8508 https://github.com/dbeaver/dbeaver/issues/7521)

https://dbeaver.com/docs/dbeaver/Local-Client-Configuration/#configure-a-local-client-in-dbeaver-on-mac-and-linux


On another note.
My distro's package version is stale(Arch) hence i used snap, i am still open to a workaround.

**Comment by akksa** [comment]
I still have the same issue 22.04, Jammy.
Dbeaver Version 24.0.2.202404071654

**Comment by akksa** [comment]
IO error: Cannot run program "/run/user/1000/doc/5787f081/bin/mysqldump" (in directory "/run/user/1000/doc/5787f081/bin"): error=13, Permission denied
2024-04-25 12:18:17.944 - java.io.IOException: Cannot run program "/run/user/1000/doc/5787f081/bin/mysqldump" (in directory "/run/user/1000/doc/5787f081/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:226)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 8 more
2024-04-25 12:28:10.283 - IO error: Cannot run program "/run/user/1000/doc/305f5bcd/usr/bin/mysqldump" (in directory "/run/user/1000/doc/305f5bcd/usr/bin"): error=13, Permission denied
2024-04-25 12:28:10.284 - java.io.IOException: Cannot run program "/run/user/1000/doc/305f5bcd/usr/bin/mysqldump" (in directory "/run/user/1000/doc/305f5bcd/usr/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:226)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 8 more

**Comment by caburet** [comment]
Same error version 24.0.3  SO: Ubuntu 22.04

**Comment by Nilad** [comment]
Same error.

Ubuntu : Ubuntu 24.04 LTS
Dbeaver-ce (ubuntu software market) :  24.1.1.202406231636


![image](https://github.com/dbeaver/dbeaver/assets/12897327/8602b90d-75be-48f6-897b-d28cc3f4cf51)

**Comment by bigkrp** [comment]
same error on Fedora while trying to dump. Installed not from snap but from `*.rpm`-package

![Screenshot from 2024-07-18 14-14-44](https://github.com/user-attachments/assets/902372a2-de4b-4916-9b34-ed0776bde17c)

**Comment by fahmihwan** [comment]
this problem appear from instalation from snap, u must trying install dbeaver with dpkg or tar.gz, etc.

**Comment by longhii** [comment]
https://github.com/dbeaver/dbeaver/issues/10320

**Comment by bigkrp** [comment]
> this problem appear from instalation from snap, u must trying install dbeaver with dpkg or tar.gz, etc.

Nope, I've installed it from rpm which was downloaded from website

**Comment by yapsr** [comment]
Would be very nice if mariadb-dump and mysqldump were accessible on Snap installs.
Running into this problem using latest version of Ubuntu 24.04.3 LTS and dbeaver-ce 25.2.5.202511161745.
