### ISSUE TITLE
Exception when browsing PostgreSQL 15 table

### ISSUE THREAD

**Issue by rasputino** [dbeaver/dbeaver#19097]
### Description

We recently upgrade PostgreSQL version from 10 to 15. Some of the tables throw this exception when we try to browse them:

```
Cannot invoke "org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getTypeID()" because "this.dataType" is null

org.jkiss.dbeaver.DBException: Cannot invoke "org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getTypeID()" because "this.dataType" is null
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:232)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5068)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.getTypeID()" because "this.dataType" is null
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:175)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:55)
	at org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerExtensionBase.createTableColumn(PostgreServerExtensionBase.java:328)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:812)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:200)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readRequiredMeta(JDBCTable.java:910)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	... 4 more
```

![image](https://user-images.githubusercontent.com/2887216/219781047-db44e7b5-acaf-4e33-96d7-f7504a3373cf.png)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/10771402/dbeaver-debug.log)
[hidden.log](https://github.com/dbeaver/dbeaver/files/10771405/hidden.log)

### DBeaver Version

DBeaver 22.3.4 Community

### Operating System

Windows 11

### Database and driver

Database:
PostgreSQL 10.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

Driver:
org.postgresql:postgresql:RELEASE 42.5.0

### Steps to reproduce

Trying to browse some tables.

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by LonwoLonwo** [comment]
```
2023-02-17 21:07:38.919 - Can't resolve data type 26
org.jkiss.dbeaver.DBException: Schema 11 not found for data type 26
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.resolveDataType(PostgreDataTypeCache.java:238)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getDataType(PostgreDatabase.java:900)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:159)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:55)
	at org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerExtensionBase.createTableColumn(PostgreServerExtensionBase.java:328)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:812)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:200)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readRequiredMeta(JDBCTable.java:910)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5068)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-02-17 21:07:38.921 - Attribute data type '26' not found. Use varchar
2023-02-17 21:07:38.927 - Can't resolve data type 'varchar' in database 'secoce_d'
```

That's strange. 26 - is oid data type. For now, I can't reproduce it.... 

As a workaround, maybe enabling of this setting will help you:

![2023-02-19 15_20_46-Connection _postgres 15_ configuration](https://user-images.githubusercontent.com/45152336/219947618-7f34254d-a344-4840-b9ec-4d175b8412ae.png)

**Comment by rasputino** [comment]
The problem remains...

![image](https://user-images.githubusercontent.com/2887216/220053363-5cfd203c-e7e0-4aa6-9519-56dfa9df7f0d.png)

Here is the DDL of the table (according to PgAdmin). I can't generate it in DBeaver:

```
CREATE TABLE IF NOT EXISTS public.thetable
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    col1 character varying(255) COLLATE pg_catalog."default",
    col2 character varying(50) COLLATE pg_catalog."default",
    col3 character varying(50) COLLATE pg_catalog."default",
    col4 character varying(255) COLLATE pg_catalog."default",
    col5 character varying(9) COLLATE pg_catalog."default",
    CONSTRAINT entidad_pk PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

Thanks for your help.

**Comment by LonwoLonwo** [comment]
For now, I can't reproduce this issue, unfortunately. 

What connection type do you have? Could you change it to "advanced" if it is not and check "varchar" data type in the "Data types" list in the pg_catalog schema?

**Comment by LonwoLonwo** [comment]
![2023-02-20 14_03_37-DBeaver Ultimate 22 3 5 - _Maria 10 1_ Script-64](https://user-images.githubusercontent.com/45152336/220088162-6de50efc-761c-4a86-aeb8-48b80d7fab27.png)

**Comment by rasputino** [comment]
The table pg_catalog.pg_type contains this row:

```
|oid  |typname|typnamespace|typowner|typlen|typbyval|typtype|typcategory|typispreferred|typisdefined|typdelim|typrelid|typsubscript|typelem|typarray|typinput |typoutput |typreceive |typsend    |typmodin       |typmodout       |typanalyze|typalign|typstorage|typnotnull|typbasetype|typtypmod|typndims|typcollation|typdefaultbin|typdefault|typacl|
|-----|-------|------------|--------|------|--------|-------|-----------|--------------|------------|--------|--------|------------|-------|--------|---------|----------|-----------|-----------|---------------|----------------|----------|--------|----------|----------|-----------|---------|--------|------------|-------------|----------|------|
|1.043|varchar|11          |10      |-1    |false   |b      |S          |false         |true        |,       |0       |-           |0      |1.015   |varcharin|varcharout|varcharrecv|varcharsend|varchartypmodin|varchartypmodout|-         |i       |x         |false     |0          |-1       |0       |100         |             |          |      |

```

**Comment by LonwoLonwo** [comment]
Ok, but can you see this data type under the "Data types" folder in the pg_catalog schema in the Navigator Tree?

**Comment by rasputino** [comment]
![image](https://user-images.githubusercontent.com/2887216/220495566-021bd6b7-7665-48b3-9577-7dc9e0f7ab9f.png)

Yes, but now is suddenly fixed (I didn't restart de program nor the computer), so... I don't know if was visible before.

**Comment by LonwoLonwo** [comment]
Now can you see data in your table? If you can - can you see data after DBeaver restart (without data types opening)?

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. Please let me know, if it's still actual.

**Comment by to3d** [comment]
@E1izabeth i am running into a similar issue caused by a field defined as `character varying(32767)` that was imported from a csv. the csv connection sees it as `String(32767)`, and I meant to transform it to a simple `character varying` of an unspecified length. playing around with my driver properties didn't resolve the bug, so I'm going to delete the table and reload it.

**Comment by E1izabeth** [comment]
@to3d 
Your case sounds like another issue. If you are sure that it has something to do with DBeaver, please create a new issue and provide some minimum example to reproduce.

**Comment by to3d** [comment]
@E1izabeth Sorry for not providing more detail, but I'm getting a very similar stack trace with the ultimate message
```
!MESSAGE Attribute data type '26' not found. Use varchar
```
as rasputino was seeing.

I don't doubt that a tweak to the `pg_catalog` table could resolve this, but I just don't know what to modify. I have two columns in a table with type of `character varying(32767)` , and they are the root of this error. Would be glad to create a new issue at some point if you don't think this is relevant to this issue.

Here is the top of my stack

```!ENTRY org.jkiss.dbeaver.model 4 0
!MESSAGE NullPointerException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:175)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:55)
	at org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerExtensionBase.createTableColumn(PostgreServerExtensionBase.java:328)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:812)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:200)
```

**Comment by E1izabeth** [comment]
Hmm.. now I'm not sure it's another issue with additional info that you provided. We will look deeper at your case. Thank you.

**Comment by LonwoLonwo** [comment]
Hello @to3d 

Can you see the "character varying" data type under the "Data types" folder in the pg_catalog schema in the Navigator Tree?

**Comment by to3d** [comment]
@LonwoLonwo Yes I do

**Comment by LonwoLonwo** [comment]
But the issue still persists for you?

**Comment by arhayka** [comment]
@to3d Thank you for your report.
We want to fix this issue: https://github.com/dbeaver/dbeaver/issues/19097#issuecomment-1535189212

**Comment by to3d** [comment]
@LonwoLonwo @arhayka  It wasn't my intention to import `String(32767)` fields without transforming them to simple varchars, so I removed those and recreated them. I have not run into the error since. I may not be able to provide any more helpful information here.
