### ISSUE TITLE
Error=13 Permission denied

### ISSUE THREAD

**Issue by HoldTheWorld** [dbeaver/dbeaver#19214]
### Description

I am trying to restore a DB from backup file through DBeaver. 
But I get an error (permission denied): 
![image](https://user-images.githubusercontent.com/89628551/221857908-3c56d58d-c226-484e-ac8c-b4f768dda3f0.png)
```
2023-02-28 15:44:13.519 - IO error: Cannot run program "/usr/lib/postgresql/12/bin/pg_restore" (in directory "/usr/lib/postgresql/12/bin"): error=13, Отказано в доступе
2023-02-28 15:44:13.521 - java.io.IOException: Cannot run program "/usr/lib/postgresql/12/bin/pg_restore" (in directory "/usr/lib/postgresql/12/bin"): error=13, Отказано в доступе
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:208)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: error=13, Отказано в доступе
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```

I use DBeaver version  22.3.4 on Linux Mint 20.3 . 

### DBeaver Version

22.3.4

### Operating System

Linux Mint 20.3

### Database and driver

PostgreSQL 12.13 (Ubuntu 12.13-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

### Steps to reproduce

1. RMC on DB ->  tools -> restore 
2. Choosing backup file 
3. Start 
![image](https://user-images.githubusercontent.com/89628551/221860306-7ed0bc8e-5540-45ca-86e8-0ede6ddc44a9.png)

**Comment by Destrolaric** [comment]
@HoldTheWorld Hi, the version 22.3.5 has this bug fixed. Updating your DBeaver version will solve the issue.
