### ISSUE TITLE
Invalid thread access while checking new version release

### ISSUE THREAD

**Issue by fredatgithub** [dbeaver/dbeaver#19224]
### Description

I have just installed Dbeaver community version 23.0.0 and after starting the application I have an error window stating:
"DBeaver new version release checker" has a problem
Invalid thread access
![image](https://user-images.githubusercontent.com/6720055/222087760-97df4a48-e6c5-43e7-ba27-90ed18feacb5.png)

### DBeaver Version

Community Edition 23.0.0

### Operating System

Windows 11 22H2

### Database and driver

PostgreSQL version 14

### Steps to reproduce

1. install DBeaver CE 23.0.0 on Windows 11
2. Start DBeaver CE
3. See the error message

**Comment by LonwoLonwo** [comment]
Thanks for the report.

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:370)
	at org.eclipse.swt.widgets.ToolBar.getItemCount(ToolBar.java:592)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:271)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.preferenceChange(SQLEditor.java:3217)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
	at org.jkiss.dbeaver.registry.BasePlatformImpl.lambda$0(BasePlatformImpl.java:88)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:47)
	at org.jkiss.dbeaver.model.impl.preferences.AbstractPreferenceStore.firePropertyChangeEvent(AbstractPreferenceStore.java:37)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.setValue(BundlePreferenceStore.java:240)
	at org.jkiss.dbeaver.ui.app.standalone.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:110)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

SQL Editor window must be open at the start.

**Comment by LonwoLonwo** [comment]
Can you try to use Reset UI Settings? Instruction is here: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by serge-rider** [comment]
Fixed (in devel and release)

**Comment by fredatgithub** [comment]
After restarting the UI, the error doesn't show up anymore
Thanks

**Comment by LonwoLonwo** [comment]
We need to test changes. Reopened.

**Comment by fredatgithub** [comment]
ok

**Comment by Matvey16** [comment]
Verified

**Comment by WEDq** [comment]
Hi, i have this problem
Invalid thread access
![image](https://github.com/dbeaver/dbeaver/assets/47285149/39093da4-f3c0-499c-a5c6-65e0d97e5fd7)
can u help me

**Comment by asm1x-art** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/103132364/aec309eb-ae1b-42d2-b35d-9c0065dbe7e4)
Hi! I have this error now((( Help, pls

**Comment by olehtsyhulov** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/82095907/5a07c438-5178-45d7-8057-747d025cabfc)
Same problem...

**Comment by E1izabeth** [comment]
Thank you for bug report. Here is a new issue about this bug https://github.com/dbeaver/dbeaver/issues/23352 You can subscribe to this issue to get updates
