### ISSUE TITLE
org.jkiss.dbeaver.model.exec.DBCException: Can't resolve data type ARRAY

### ISSUE THREAD

**Issue by niraj8241** [dbeaver/dbeaver#19239]
### Description

I am using Redshift RA3 cluster and when i try to access a table that has a column with data type as array, DBeaver is unable to run select on the table. Below is the error that i see:

##Stack Trace
```
org.jkiss.dbeaver.model.exec.DBCException: Can't resolve data type ARRAY
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:65)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:56)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3805)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

##Query:
`select * from pg_namespace`

##Error:
![image](https://user-images.githubusercontent.com/13007542/222316853-a32eae6c-0b0e-4be8-97bd-2ddbf919260e.png)

![image](https://user-images.githubusercontent.com/13007542/222316904-1fc7134d-03e3-4a2f-b4ba-d5ddf4e9772a.png)

### DBeaver Version

22.3.5.202302171528

### Operating System

Windows 10 Enterprise

### Database and driver

DatabaseName: `Redshift RA3 4xl`
DriverVersion: `RedshiftJDBC42-1.2.43.1067`

### Steps to reproduce

1. Connect to Redshift Cluster
2. `select * from pg_namespace`

### Additional context

This is working on others laptop so has to do something with my setting. Although i have tried uninstalling DBeaver, resetting UI settings. But i could not get it to work.

**Comment by LonwoLonwo** [comment]
Hello @niraj8241 

I can't reproduce your issue for now

![2023-03-02 13_39_39-DBeaver 23 0 0 - _dev 3_ Script-39](https://user-images.githubusercontent.com/45152336/222406456-fbdf3e95-4967-4b39-a3cf-145cacb82460.png)

Could you please check - what data type has `nspacl` column? You can use ctrl+click on the name of the table in the SQL Editor if Advanced mode is ON

![2023-03-02 13_46_20-DBeaver 23 0 0 - _dev 3_ Script-39](https://user-images.githubusercontent.com/45152336/222406962-b3b6a7da-d10a-4240-8e22-44f26dbda2db.png)

Additionally, please try to update your driver version. 

![2023-03-02 13_43_39-DBeaver 23 0 0 - _dev 3_ Script-39](https://user-images.githubusercontent.com/45152336/222407101-a30fe0b3-9da4-40d4-9607-e95ddfc19678.png)

**Comment by niraj8241** [comment]
@LonwoLonwo Thank you so much for the response. After changing the connection type to Advanced and downloading the latest driver seems to have fixed the problem. We can close the case.

**Comment by LonwoLonwo** [comment]
Thanks for the answer.
