### ISSUE TITLE
Can not connect some SQL server after user latest SQL server jdbc drive

### ISSUE THREAD

**Issue by leezm** [dbeaver/dbeaver#19263]
### Description

In version 22.3.5, Driver version was updated to 11.2.3. Trust server certificate option was moved to the main connection page...
I can't connect to  one of my sqlserver(2008R2),but another sqlserver(2008R2) is OK
Error log:
com.microsoft.sqlserver.jdbc.SQLServerException: 该连接已关闭。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1555)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getMetaData(SQLServerConnection.java:4367)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getMetaData(JDBCConnectionImpl.java:334)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:448)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.initialize(SQLServerDataSource.java:303)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1198)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
![image](https://user-images.githubusercontent.com/24444492/222997502-b56f41fc-4eb0-4496-824e-50eeb924bcf7.png)

### DBeaver Version

22.3.5

### Operating System

win7

### Database and driver

SQL server 2008R2
sqlserver jdbc 11.2.3

### Steps to reproduce

just connect to the database

**Comment by LonwoLonwo** [comment]
Hello @leezm 

Please try to use an older SQL Server driver version. You can change it in the connection settings:

![2023-03-06 11_39_27-DBeaver 23 0 0 - _postgres 2_ Script-18](https://user-images.githubusercontent.com/45152336/223059612-ff80f1f6-0610-4511-9e59-fcc1ef5a5bab.png)


Additionally, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by leezm** [comment]
> Hello @leezm
> 
> Please try to use an older SQL Server driver version. You can change it in the connection settings:
> 
> ![2023-03-06 11_39_27-DBeaver 23 0 0 - postgres 2 Script-18](https://user-images.githubusercontent.com/45152336/223059612-ff80f1f6-0610-4511-9e59-fcc1ef5a5bab.png)
> 
> Additionally, could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

It's ok when I use this version drive:
![image](https://user-images.githubusercontent.com/24444492/223069936-8510a8ce-eecc-4a71-9dfd-2cb64bc469b8.png)
Here is the log file:
[.log](https://github.com/dbeaver/dbeaver/files/10896423/default.log)

**Comment by LonwoLonwo** [comment]
Ok, just continue to use your version driver then.
