### ISSUE TITLE
Can't update attribute ... - attributes of key 'VIRTUAL_PK' are missing in result set

### ISSUE THREAD

**Issue by bkcsfi** [dbeaver/dbeaver#19276]
### Description

Using a remote firebird 2.0 server

I select some rows from db, change the values in the grid. 

When I click "save" I get the error message shown above.

```sql
SELECT o.orgid, cg.SUPPLIER_PARTNUMBER , cg.CASEPACK  FROM customsgoods cg
JOIN CUSTOMSPARTY cp ON (cp.id = cg.CUSTOMS_PARTY_ID)
JOIN org o ON (o.id = cp.ORG_ID)
WHERE  
cg.SUPPLIER_PARTNUMBER IN
('VAR2-PoE-i2-1-S-W',
'VAR2-i2-1-C-DGC',
'10K-OB',
'15K-B'
)
```

change the values in casepack column in the grid view

then click save. The above error appears.

This also happened under version 22.5

### DBeaver Version

CE Version 23.0.0.202303040621

### Operating System

Ubuntu 22.04

### Database and driver

Firebird 2.0

JKISS	DBeaver Firebird Support	1.0.202.202303040621	org.jkiss.dbeaver.ext.firebird

### Steps to reproduce

connect to database

execute query shown above

edit values in casepack column as shown below

![image](https://user-images.githubusercontent.com/6412502/223202687-a10f4b54-f7a6-4a68-8c79-d65472eedc19.png)

click 'save'

error message appears.

### Additional context

error log

```
!SESSION 2023-03-06 12:11:01.304 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-03-06 12:11:07.012
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-03-06 12:11:42.695
!MESSAGE Can't update attribute 'CASEPACK' - attributes of key 'VIRTUAL_PK' are missing in result set
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-03-06 12:11:42.696
!MESSAGE Can't update attribute 'CASEPACK' - attributes of key 'VIRTUAL_PK' are missing in result set
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Can't update attribute 'CASEPACK' - attributes of key 'VIRTUAL_PK' are missing in result set
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.checkEntityIdentifiers(ResultSetPersister.java:598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.createDataPersister(ResultSetViewer.java:4336)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.generateChangesReport(ResultSetViewer.java:4298)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:4216)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.ResultSetHandlerMain.execute(ResultSetHandlerMain.java:298)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:299)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by bkcsfi** [comment]
Closing this issue because I believe its my fault.

I had not selected the primary key from the customsgoods table.

The following query works, where both supplier_partnumber and customs_party_id uniquely identifies a single row in the customsgoods table:

```sql
SELECT o.orgid, cg.SUPPLIER_PARTNUMBER , cg.CASEPACK, cg.CUSTOMS_PARTY_ID  
FROM customsgoods cg
JOIN CUSTOMSPARTY cp ON (cp.id = cg.CUSTOMS_PARTY_ID)
JOIN org o ON (o.id = cp.ORG_ID)
WHERE  
cg.SUPPLIER_PARTNUMBER IN
('VAR2-PoE-i2-1-S-W',
'VAR2-i2-1-C-DGC',
'10K-OB',
'15K-B'
)
```

This query also works, using the customsgoods.id (primary key) column

```sql
SELECT o.orgid, cg.SUPPLIER_PARTNUMBER , cg.CASEPACK, cg.id  
FROM customsgoods cg
JOIN CUSTOMSPARTY cp ON (cp.id = cg.CUSTOMS_PARTY_ID)
JOIN org o ON (o.id = cp.ORG_ID)
WHERE  
cg.SUPPLIER_PARTNUMBER IN
('VAR2-PoE-i2-1-S-W',
'VAR2-i2-1-C-DGC',
'10K-OB',
'15K-B'
)
```

**Comment by mayuresh1007** [comment]
Can't update attribute 'isactive' - attributes of key 'VIRTUAL_PK' are missing in result set
while updating the values from dbeaver

![Screenshot from 2023-04-27 16-13-35](https://user-images.githubusercontent.com/77499509/234840030-72b916bf-92a9-49f5-aae0-23849c6584ed.png)

**Comment by StanleySathler** [comment]
For future reference - I had the same issue, even tho I had my PK column in the results. However, I had my UUID column casted to TEXT, which caused the issue:

```
SELECT id::text FROM assets WHERE ...
```

Then, removing the casting works.

```
SELECT id FROM assets WHERE ...
```
