### ISSUE TITLE
Frequent StringIndexOutOfBoundsException in JDBC driver

### ISSUE THREAD

**Issue by mmoser18** [dbeaver/dbeaver#19280]
### Description

While accessing a MariaDB I am getting an StringIndexOutOfBoundsException - see stack trace below:

![image](https://user-images.githubusercontent.com/17732576/223362842-b2e2f938-d708-42a2-8860-ecf3b646fe2b.png)

Error Details:
  eclipse.buildId=unknown
  java.version=11.0.12
  java.vendor=Eclipse Foundation
  BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
  Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3842)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:294)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:331)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.StringIndexOutOfBoundsException: offset 14820, count 97, length 14848
	at java.base/java.lang.String.checkBoundsOffCount(Unknown Source)
	at java.base/java.lang.String.<init>(Unknown Source)
	at org.mariadb.jdbc.client.impl.StandardReadableByteBuf.readString(StandardReadableByteBuf.java:229)
	at org.mariadb.jdbc.message.server.OkPacket.<init>(OkPacket.java:44)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:126)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
	at org.mariadb.jdbc.Statement.execute(Statement.java:452)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	... 15 more

Any other info I could contribute to locate/analyze the error?

### DBeaver Version

23.0.0.202303040621

### Operating System

Windows 10 - all updates installed

**Comment by LonwoLonwo** [comment]
Hello @mmoser18 

Please provide steps to reproduce your issue.

**Comment by LonwoLonwo** [comment]
Additionally - what database driver version do you use? You can find this info in your connections settings -> "Test connection"

**Comment by E1izabeth** [comment]
It's been a long time since no update on this issue. Please let me know, if it's still actual for you, and provide additional info.
