### ISSUE TITLE
Fix dashboard errors appeared due to java version

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#19314]
### Description

there are two errors that are thrown randomly for a particular connection:
1.
 ```
java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
	at org.jfree.chart.ChartFactory.createXYLineChart(ChartFactory.java:2002)
	at org.jkiss.dbeaver.ui.dashboard.histogram.DashboardRendererTimeseries.createDashboard(DashboardRendererTimeseries.java:63)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.createChartRenderer(DashboardItem.java:108)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardItem.<init>(DashboardItem.java:93)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardList.addDashboard(DashboardList.java:246)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardList.createDefaultDashboards(DashboardList.java:233)
	at org.jkiss.dbeaver.ui.dashboard.control.DashboardListViewer.createDashboardsFromConfiguration(DashboardListViewer.java:104)
	at org.jkiss.dbeaver.ui.dashboard.view.DashboardView.createDashboardControls(DashboardView.java:96)
	at org.jkiss.dbeaver.ui.dashboard.view.DashboardView.lambda$0(DashboardView.java:67)
	at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:68)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:299)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

2. 
```Assistive Technology not found: com.sun.java.accessibility.AccessBridge```

when jre folder is deleted from dbeaver folder, and system version of java is 17, the problem goes away

### DBeaver Version

~22.2.5+

### Operating System

win11

**Comment by serge-rider** [comment]
Java was updatyed in Windows version
