### ISSUE TITLE
about Progress sub task without start

### ISSUE THREAD

**Issue by yangmeng66** [dbeaver/dbeaver#19341]
### Description

Hello, simple operations on oracle on dbeaver will cause this error. What does this error mean?

![image](https://user-images.githubusercontent.com/51857567/224602315-b6342b95-cbbc-413b-b33d-14a1838ec453.png)

```
2023-03-13 11:31:52.718 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:98)
	at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.startBlock(DefaultProgressMonitor.java:127)
	at org.jkiss.dbeaver.model.impl.AbstractSession.<init>(AbstractSession.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.<init>(JDBCConnectionImpl.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createConnection(JDBCDataSource.java:360)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:216)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:1)
	at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1732)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectLookupCache.reloadObject(JDBCObjectLookupCache.java:95)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectLookupCache.getObject(JDBCObjectLookupCache.java:59)
	at org.jkiss.dbeaver.ext.oracle.model.OracleObjectType$9.findObject(OracleObjectType.java:116)
	at org.jkiss.dbeaver.ext.oracle.model.OracleObjectType$9.findObject(OracleObjectType.java:1)
	at org.jkiss.dbeaver.ext.oracle.model.OracleObjectType.findObject(OracleObjectType.java:229)
	at org.jkiss.dbeaver.ext.oracle.model.OracleStructureAssistant$2.resolveObject(OracleStructureAssistant.java:332)
	at org.jkiss.dbeaver.model.DBInfoUtils.makeObjectDescription(DBInfoUtils.java:42)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionHelper.readAdditionalProposalInfo(SQLCompletionHelper.java:50)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionProposalBase.getAdditionalInfo(SQLCompletionProposalBase.java:240)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProposal.getAdditionalProposalInfo(SQLCompletionProposal.java:144)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$2$1.run(AdditionalInfoController.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

22.1.1 ce

### Operating System

WINDOS 10

### Database and driver

ojdbc8.jar

**Comment by E1izabeth** [comment]
Does it connected to your previous question https://github.com/dbeaver/dbeaver/discussions/18830?

**Comment by E1izabeth** [comment]
Please, provide more detailed explanation of steps to reproduce your issue. A video showing of what are you doing and what's happening would be extremely useful.

**Comment by yangmeng66** [comment]
1 Yes, but many places will trigger this error,
`Does it connected to your previous question https://github.com/orgs/dbeaver/discussions/18830?`

2 video show:

https://user-images.githubusercontent.com/51857567/224642579-3465fe56-7268-4feb-973f-e57fc35edb88.mp4

**Comment by E1izabeth** [comment]
Thanks

**Comment by yangmeng66** [comment]
@E1izabeth Hello, can you help us solve this problem first? We need this urgently
https://github.com/dbeaver/dbeaver/discussions/19258

**Comment by E1izabeth** [comment]
@yangmeng66 unfortunately, I personally can't help with building from sources on mac

**Comment by yangmeng66** [comment]
Normally, dbeaver supports building on mac, linux, and mac, but why is there an error only when the mac is opened?

**Comment by E1izabeth** [comment]
Maybe @ShadelessFox might help

**Comment by LonwoLonwo** [comment]
Hello @yangmeng66 

> What does this error mean?

This is just a notification. It does not affect anything.
