### ISSUE TITLE
GRANT EXECUTE ON PROCEDURE to MySQL user breaks user schema privileges screen

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#19455]
### Description

After manually granting  execution privilege on a stored procedure to a user, 
cannot see/choose table/other privileges in the user's Schema privileges UI for a specific schema.

### DBeaver Version

Community Version 23.0.0.202303040621

### Operating System

Windows 10 64 bit

### Database and driver

1. MySQL 5.7/8.0
2. MySQL Connector/J

### Steps to reproduce

1. Create a sample stored procedure :
```
delimiter $$
CREATE PROCEDURE GetUsers()
BEGIN
	SELECT *  FROM mysql.user;
END
$$
```
2. Create sample user:
`CREATE USER testuser IDENTIFIED BY 'testpass';`
3. Run `GRANT EXECUTE ON PROCEDURE GetUsers to testuser`
4. Refresh Users node in Database Navigator
5. Double click on "testuser"
6. Go to "Schema Privileges" tab and see that the privilege lists are empty (unless you click on "% (All)" but still cannot save them them - "Save" button is grayed out)

**Comment by LonwoLonwo** [comment]
Hello @yoni-yad2 

Unfortunately, I'm not able to reproduce your issue.

![2023-03-23 15_52_21-Window](https://user-images.githubusercontent.com/45152336/227210520-719f2550-167e-4c0d-bc9f-f53c57a616e8.png)

Could you please provide footage showing your issue? Thank you.

**Comment by yoni-yad2** [comment]
Hi, you didn't include the privileges part on the right side of the screen which is the empty part in my case (the bug).

![image](https://user-images.githubusercontent.com/103036539/227868421-7c04b55d-57c2-4b4e-a96c-67858d901ecc.png)

**Comment by yoni-yad2** [comment]
Please confirm your test user has a stored procedure privilege:

`select * from mysql.procs_priv `

I have the same issue with another MYSQL user which has an SP execute privilege.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.
```

2023-04-07 10:30:48.515 - java.lang.NullPointerException: Cannot invoke "String.length()" because "like" is null
java.lang.NullPointerException: Cannot invoke "String.length()" because "like" is null
	at org.jkiss.dbeaver.model.sql.SQLUtils.makeLikePattern(SQLUtils.java:171)
	at org.jkiss.dbeaver.model.sql.SQLUtils.matchesLike(SQLUtils.java:225)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLGrant.matches(MySQLGrant.java:183)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorPrivileges.highlightCatalogs(MySQLUserEditorPrivileges.java:350)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorPrivileges.processGrants(MySQLUserEditorPrivileges.java:335)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorAbstract$UserPageControl$1.completeLoading(MySQLUserEditorAbstract.java:81)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLUserEditorAbstract$UserPageControl$1.completeLoading(MySQLUserEditorAbstract.java:1)
```
