### ISSUE TITLE
23.0.1 cannot connect server with ssh tunnel & jump server

### ISSUE THREAD

**Issue by DonnySLau** [dbeaver/dbeaver#19488]
### Description

When I upgrade dbeaver-ce to 23.0.1, I found the ssh tunnel cannot establish.
```Auth fail for methods 'publickey'
Can't initialize tunnel
  Cannot establish tunnel to xxx.com:2222
  Cannot establish tunnel to xxx.com:2222
    Auth fail for methods 'publickey'
```

This is my config which can be use in 23.0.0 version and before. 
I tried to downgrade to 23.0.0, and it can be used again.
![4](https://user-images.githubusercontent.com/21169006/227865804-a366ada8-2237-44ad-97be-2f7c31e28003.png)

This is the log when I try to connect in 23.0.1.
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-03-27 14:56:20.535
!MESSAGE Cannot establish tunnel to xxx.com:2222
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-03-27 14:56:20.535
!MESSAGE Cannot establish tunnel to xxx.com:2222
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-03-27 14:56:20.535
!MESSAGE Auth fail for methods 'publickey'
!STACK 0
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey'
	at com.jcraft.jsch.Session.connect(Session.java:499)
	at com.jcraft.jsch.Session.connect(Session.java:187)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:121)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:135)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:77)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1044)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

23.0.1

### Operating System

Windows 10 22H2

### Database and driver

1. Database name and version: Mysql 5.7.20
2. Driver name and version: Mysql JDBC Driver 8.0.29

### Additional context

1. Tunnels and proxy: SSH with Jump server

**Comment by Destrolaric** [comment]
@DonnySLau Hi, you are currently using JSCH for the connection. Could you try using SSHJ and see if it works?

**Comment by DonnySLau** [comment]
> @DonnySLau Hi, you are currently using JSCH for the connection. Could you try using SSHJ and see if it works?

I tried just now.
```
Cannot establish tunnel to {MyServerIp}:32200
  Exhausted available authentication methods
```

And the log:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-03-27 17:10:23.564
!MESSAGE Exhausted available authentication methods
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-03-27 17:10:23.564
!MESSAGE Exhausted available authentication methods
!STACK 0
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:205)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:291)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:261)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:245)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:107)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:135)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:77)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$8.execute(SSHTunnelConfiguratorUI.java:307)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:734)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I used JSch before this issue open.

Now I downgrade to 23.0.0 and try SSHJ, same wrong as above.

**Comment by SunMar** [comment]
@Destrolaric Had the same problem, but in my case switching to SSHJ worked. My private key is accessed via SSH/GPG agent. Was successfully able to connect using SSHJ. I use an SSH tunnel but not an additional jump server.

**Comment by igorpan** [comment]
I am experiencing the same issue on 23.0.1 on Windows - downgraded to 23.0.0 and it works fine. 
I do not have any jump servers set up, just a simple SSH tunnel

**Comment by Destrolaric** [comment]
Could anyone having this issue look if the server-side error looks similar to the issue below?
https://github.com/dbeaver/dbeaver/issues/19568

**Comment by SunMar** [comment]
@Destrolaric JSc works again for me, though I think I'm on the same version of DBeaver (23.0.1), so not sure why I was getting that error two weeks ago. I did check the algorithms in #19568 and those were not the issue for me. The requested algorithms were available, our SSH server hasn't accepted those older algorithms for a couple years now.

**Comment by Destrolaric** [comment]
@SunMar, I think we will close the ticket for now. If the issue reappears, feel free to reopen it.

**Comment by DonnySLau** [comment]
I upgraded to 23.0.2 just now, and tested the same config. It's OK again. Thanks!
