### ISSUE TITLE
Failed to add a JDBC driver to Dbeaver

### ISSUE THREAD

**Issue by hantmac** [dbeaver/dbeaver#19491]
### Description

I want to add a JDBC driver to Dbeaver according to [this doc](https://dbeaver.com/docs/wiki/Database-drivers/), the JDBC driver is https://github.com/databendcloud/databend-jdbc. I add the jdbc driver jar file to dbeaver and the dbeaver can load the driver class `com.databend.jdbc.DatabendDriver` when I adding it to driver manager:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/7600925/227883628-80f14da8-b359-4936-87b3-5598cadd517f.png">

But when I save it and create a new databend connection, I got the error:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7600925/227886424-5eff149a-1fc1-44bd-bc4a-af1a216b2da1.png">

### DBeaver Version

Community Edition 23.0.1.202303250535

### Operating System

macOS Monterey 12.2.1

### Database and driver

1. Database Name and version: databend, databend-v1.0.17-nightly
2. JDBC driver: https://github.com/databendcloud/databend-jdbc version: 0.0.5 

### Steps to reproduce

According this https://dbeaver.com/docs/wiki/Database-drivers/

**Comment by serge-rider** [comment]
Most likely some dependency jars are missing (i.e. it is not enough to add just one jar file).

Error "Could not initialize class" means that class was found but something went wrong during class load procedure.
databend-jdbc has more than 15 dependencies.

I'd recommend to add it as a Maven artifact but not as a single file (use Add Artifact button)

**Comment by hantmac** [comment]
> 

@serge-rider Thanks for your reply. I add the Maven artifact of databend jdbc as follows:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/7600925/227920224-b25513cb-b9da-4c6b-8f72-fb7054375a92.png">


But still has the same error 😢 :

<img width="821" alt="image" src="https://user-images.githubusercontent.com/7600925/227920273-63457e43-9e7c-4c6e-9ada-524451968cdb.png">

**Comment by serge-rider** [comment]
Did you try to restart dbeaver?
If yes could you send dbeaver-debug.log?

**Comment by hantmac** [comment]
> Did you try to restart dbeaver? If yes could you send dbeaver-debug.log?

Yes, I have restarted the dbveaer.
BTW, where is the dbeaver-debug.log?  I install it on macOS using .dmg file.

**Comment by hantmac** [comment]
> Did you try to restart dbeaver? If yes could you send dbeaver-debug.log?

Yes, I have restarted the dbveaer.
BTW, where is the dbeaver-debug.log?  I install it on macOS using .dmg file.

**Comment by hantmac** [comment]
> Did you try to restart dbeaver? If yes could you send dbeaver-debug.log?

Yes, I have restarted the dbveaer.
BTW, where is the dbeaver-debug.log?  I install it on macOS using .dmg file.

**Comment by serge-rider** [comment]
Please see https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by hantmac** [comment]
I found the error logs and I wonder why there is a `ClassNotFoundException` of `okhttp3`. The detail logs are as following:


!SESSION 2023-03-28 09:18:50.468 -----------------------------------------------
eclipse.buildId=unknown
java.version=17
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=zh_CN_#Hans
Framework arguments:  -keyring /Users/hanshanjie/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/hanshanjie/.eclipse_keyring

!ENTRY org.eclipse.ui 2 2 2023-03-28 09:18:52.815
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-03-28 09:18:55.263
!MESSAGE Error creating driver 'databend' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.databend.jdbc.DatabendDriver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-03-28 09:18:55.263
!MESSAGE Error creating driver 'databend' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.databend.jdbc.DatabendDriver'
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-03-28 09:18:55.263
!MESSAGE okhttp3/OkHttpClient$Builder
!STACK 0
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder
	at com.databend.jdbc.NonRegisteringDatabendDriver.newHttpClient(NonRegisteringDatabendDriver.java:36)
	at com.databend.jdbc.NonRegisteringDatabendDriver.<init>(NonRegisteringDatabendDriver.java:22)
	at com.databend.jdbc.DatabendDriver.<init>(DatabendDriver.java:8)
	at com.databend.jdbc.DatabendDriver.<clinit>(DatabendDriver.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1186)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1122)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:675)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:682)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:174)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient$Builder
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2023-03-28 09:18:55.263
!MESSAGE okhttp3.OkHttpClient$Builder
!STACK 0
java.lang.ClassNotFoundException: okhttp3.OkHttpClient$Builder
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.databend.jdbc.NonRegisteringDatabendDriver.newHttpClient(NonRegisteringDatabendDriver.java:36)
	at com.databend.jdbc.NonRegisteringDatabendDriver.<init>(NonRegisteringDatabendDriver.java:22)
	at com.databend.jdbc.DatabendDriver.<init>(DatabendDriver.java:8)
	at com.databend.jdbc.DatabendDriver.<clinit>(DatabendDriver.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1186)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1122)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:675)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:682)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:174)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by hantmac** [comment]
@serge-rider Thanks for your help! I build a fat jar and fixed this issue.
