### ISSUE TITLE
Connectivity issues with Clickhouse using SSL

### ISSUE THREAD

**Issue by mars9n9** [dbeaver/dbeaver#19497]
### Description

I use Dbeaver 23.0.1
I have Clickhouse in GCP and a tunnel to GCP with redirecting to localhost
I could connect to Clickhouse using login/password and SSL, using clickhouse-client.
Using Dbeaver I am getting connection issues. 
I tried to convert my key using `openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in k.key -out k.der`
but it gives me an Error `Missing key encoding, server ClickHouseNode`

### DBeaver Version

Community Edition 23.0.1

### Operating System

MacOS 13.2.1

### Database and driver

Database: Clickhouse 23.2.4.12

**Comment by LonwoLonwo** [comment]
Hello @mars9n9 

Sorry for the late response.

Please provide more details about your issue.
How exactly do you use SSL parameters in DBeaver and using clickhouse-client? 

Where did you try to convert your key?

**Comment by mars9n9** [comment]
Hello @LonwoLonwo 
Adding some screenshots
I got ssl key and certificates in EC format, tried to use them in Dbeaver:
<img width="691" alt="Screenshot 2023-05-08 at 13 30 58" src="https://user-images.githubusercontent.com/53946303/236813207-1ab4ad9a-e7a5-4b98-abe9-a34e4686cd41.png">
Getting error: 
<img width="972" alt="Screenshot 2023-05-08 at 13 33 17" src="https://user-images.githubusercontent.com/53946303/236813407-13b4acab-8141-485a-bab9-f7058c54af44.png">
I tried to convert key file to .der format with openssl using command above
Gettig error using der key :
<img width="703" alt="Screenshot 2023-05-08 at 13 36 38" src="https://user-images.githubusercontent.com/53946303/236814181-96b173ba-2622-4710-952a-34e973a5d668.png">

<img width="940" alt="Screenshot 2023-05-08 at 13 36 14" src="https://user-images.githubusercontent.com/53946303/236813949-ce2118cb-531b-4322-b1c1-d118afc29afe.png">

 I have a makefile to run clickhouse-client in docker, not sure what info you need from this one

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by mars9n9** [comment]
Hi @LonwoLonwo 
Sorry for the late answer. Here is the debug log 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11634964/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
Does your clickhouse-client have a key encoding parameter field/request? 

As I can see now, java can not recognize your key encoding:

```
2023-06-02 13:46:41.068 - Missing key encoding
java.security.InvalidKeyException: Missing key encoding
	at java.base/sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(Unknown Source)
	at java.base/sun.security.rsa.RSAKeyFactory.generatePrivate(Unknown Source)
	at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(Unknown Source)
	at java.base/java.security.KeyFactory.generatePrivate(Unknown Source)

```

Does your key file have something like this at the start?:

`-----BEGIN RSA PRIVATE KEY-----`

And, could you please try to change the SSL mode on the "None" one?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by mars9n9** [comment]
@E1izabeth @LonwoLonwo  Hi again!
Sorry for the late answer
Looks like I messed up with key convertion. 
I got some help and successfully converted my EC key to PKCS#8  using `openssl pkcs8 -in oldkey  -topk8 -v2 des3 -out newkey -nocrypt` So the error above disappeared, but I'm getting the new 
one now
<img width="1025" alt="Screenshot 2023-08-01 at 17 44 05" src="https://github.com/dbeaver/dbeaver/assets/53946303/ca021304-d3e8-49e6-9c17-bb584fcb7df4">
`Version must be 0, server ClickHouseNode`
My key has `-----BEGIN PRIVATE KEY----` header 
Also adding logs :
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/12231499/dbeaver-debug.log)

Looks like DBeaver is trying to read the key as RSA key, but there is no way to convert EC key to RSA as I know

**Comment by ShadelessFox** [comment]
Hello @mars9n9,

What driver version are you using? Does the issue occur against the latest version?

**Comment by mars9n9** [comment]
Hi @ShadelessFox 
I use clickhouse-jdbc 0.4.6

**Comment by Inasayang** [comment]
I also encountered this problem.

**Comment by jeeva-travtech** [comment]
I believe even with the proper certificates , it will still fail, there is a bug in the Clickhouse JDBC driver itself when you have SSL enabled in 'STRICT' mode as per -> https://github.com/ClickHouse/clickhouse-java/issues/1454
