### ISSUE TITLE
Null pointer exception when I try to open DBeaver via Flatpak

### ISSUE THREAD

**Issue by GabrielLasso** [dbeaver/dbeaver#19517]
### Description

When I try to open, I get the following error:

```
➜  ~ flatpak run io.dbeaver.DBeaverCommunity                            
Gtk-Message: 11:23:01.048: Failed to load module "canberra-gtk-module"
Dbeaver: Não foi possível abrir a tela: 
Warning: NLS unused message: WorkbenchPreference_showMultipleEditorTabsButton in: org.eclipse.ui.internal.messages
Warning: NLS unused message: Workbench_zoomChangedRestart in: org.eclipse.ui.internal.messages
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621]
> Start Aplicativo IDE Eclipse [org.eclipse.ui.ide.application 1.4.600.v20221024-2137]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.13.200.v20221102-1024]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.20.0.v20221027-2208]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 23.0.0.202303040621]
2023-03-28 11:23:02.050 - DBeaver 23.0.0.202303040621 is starting
2023-03-28 11:23:02.051 - OS: Linux 6.2.8-1-default (amd64)
2023-03-28 11:23:02.051 - Java version: 11.0.18 by Flathub (64bit)
2023-03-28 11:23:02.051 - Install path: '/app/dbeaver'
2023-03-28 11:23:02.051 - Instance path: 'file:/home/glasso/.local/share/DBeaverData/workspace6/'
2023-03-28 11:23:02.051 - Memory available 64Mb/1024Mb
2023-03-28 11:23:02.059 - Create display
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
	at org.eclipse.swt.widgets.Display.create(Display.java:1123)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:632)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:623)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:473)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:269)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Error updating splash shell
2023-03-28 11:23:02.077 - Initializing DBeaver 23.0.0
2023-03-28 11:23:02.077 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.0.0.202303040621
2023-03-28 11:23:02.077 - Initialize desktop platform...
2023-03-28 11:23:02.079 - Language for locale 'pt_BR' not found. Use default.
2023-03-28 11:23:02.214 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> Start Core Resource Management [org.eclipse.core.resources 3.18.100.v20221025-2047]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.101.202303040621]
> Start Core de Suporte para Equipe [org.eclipse.team.core 3.9.600.v20220902-2219]
2023-03-28 11:23:02.418 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
2023-03-28 11:23:02.444 - Platform initialized (367ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.101.202303040621]
2023-03-28 11:23:02.452 - Starting RMI server at 43679
2023-03-28 11:23:02.486 - Run workbench
2023-03-28 11:23:02.486 - Create display

(java:20): Gdk-CRITICAL **: 11:23:02.486: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed
2023-03-28 11:23:02.487 - Internal error in workbench lifecycle
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
	at org.eclipse.swt.widgets.Display.create(Display.java:1123)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:632)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:623)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:741)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:554)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:298)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
2023-03-28 11:23:02.488 - DBeaver is stopping
2023-03-28 11:23:02.491 - Stop RMI server
2023-03-28 11:23:02.492 - RMI controller has been stopped
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.116.202303040621]
2023-03-28 11:23:02.548 - DBeaver shutdown completed
2023-03-28 11:23:02.575 - Shutdown desktop platform...
java.lang.ExceptionInInitializerError
	at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadDriver(DataSourceProviderDescriptor.java:657)
	at org.jkiss.dbeaver.registry.DataSourceProviderDescriptor.loadExtraConfig(DataSourceProviderDescriptor.java:158)
	at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.loadExtensions(DataSourceProviderRegistry.java:167)
	at org.jkiss.dbeaver.registry.DataSourceProviderRegistry.getInstance(DataSourceProviderRegistry.java:63)
	at org.jkiss.dbeaver.core.DesktopPlatform.dispose(DesktopPlatform.java:216)
	at org.jkiss.dbeaver.core.DBeaverActivator.shutdownCore(DBeaverActivator.java:114)
	at org.jkiss.dbeaver.core.DBeaverActivator.stop(DBeaverActivator.java:78)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getCustomDriversHome(DriverDescriptor.java:1744)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.<clinit>(DriverDescriptor.java:223)
	... 24 more
Internal error after shutdown process:null
Gtk-Message: 11:23:03.063: Failed to load module "canberra-gtk-module"
Dbeaver: Não foi possível abrir a tela: 
Dbeaver:
An error has occurred. See the log file
/home/glasso/.local/share/DBeaverData/workspace6/.metadata/.log.
```

In `/home/glasso/.local/share/DBeaverData/workspace6/.metadata/.log`:
```
!SESSION 2023-03-28 11:23:00.996 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.18
java.vendor=Flathub
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=pt_BR
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2023-03-28 11:23:02.287
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.osgi 4 0 2023-03-28 11:23:02.560
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:336)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

### DBeaver Version

23.0.0

### Operating System

OpenSuse Thumbleweed

### Additional context

Seems like it started happening after I updated my system with `sudo zypper dup` and `sudo flatpak update`. Maybe GNOME 44 or the deprecation of `GNOME Application Platform version 42 org.gnome.Platform` since Mar 21 at flathub

**Comment by flambchap** [comment]
Hello @GabrielLasso. I cannot reproduce the issue against version 23.0.5. Can you please try reinstalling DBeaver and see if this helps?

**Comment by GabrielLasso** [comment]
@n5a5 After flatpak update it worked... Idk what happened here
