### ISSUE TITLE
 Custom filter does not work in Oracle

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#19522]
### Description

https://user-images.githubusercontent.com/84867187/228314573-2dcc98c7-e6c0-4f5a-9c6d-dab3bf7213df.mp4

Error refreshing node (sometimes without this error, but filter does not work anyway)

### DBeaver Version

ue 23.0.1

### Operating System

windows 10

### Database and driver

Oracle JDBC 

### Steps to reproduce

1. In the Database Navigator, right-click the **Oracle** schema and on the context menu click Filter -> Configure schema filter.
2.  Select the Enable checkbox to activate the fields of the window.
3. Click Add next to the Include field and then, in the field itself, enter the name or combination of symbols to search
4. Press "OK" btn
**Expected resut:** - filter is working
**Actual result** - Error refreshing node  (sometimes without this error, but filter does not work anyway)

**Comment by MashaKorax** [comment]
`ConcurrentModificationException`
`java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.jkiss.dbeaver.model.struct.cache.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:87)
	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema.getTables(OracleSchema.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:173)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:835)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:501)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:835)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:394)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:369)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:189)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`
