### ISSUE TITLE
Connection impala from Kerberos 

### ISSUE THREAD

**Issue by mipi21** [dbeaver/dbeaver#19570]
### Description

Cannot connect to impala with last version with community edition 23.0.1

### DBeaver Version

Community Edition 23.0.1

### Operating System

Window 10

### Database and driver

Impala

### Steps to reproduce

1 correct generate tickets on Kerberos
2 connect to dB impala
3 received error
![image](https://user-images.githubusercontent.com/28875055/229292624-268faedc-d51a-48a7-b105-bfcdda8b97a5.png)

**Comment by mipi21** [comment]
in Community Edition 23.0.0 working correctly

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by mipi21** [comment]
!ENTRY org.jkiss.dbeaver.model 4 0 2023-03-31 14:47:46.426
!MESSAGE GSS initiate failed
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-03-31 14:47:46.426
!MESSAGE GSS initiate failed
!STACK 0
com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TTransportException: GSS initiate failed
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:221)
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:297)
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at com.cloudera.impala.hivecommon.api.HiveServerPrivilegedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createTransport(Unknown Source)
	at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createClient(Unknown Source)
	at com.cloudera.impala.hivecommon.core.HiveJDBCCommonConnection.establishConnection(Unknown Source)
	at com.cloudera.impala.impala.core.ImpalaJDBCConnection.establishConnection(Unknown Source)
	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.connect(Unknown Source)
	at com.cloudera.impala.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.cloudera.impala.jdbc.common.AbstractDriver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
What Java version do you use? Is this DBeaver Java version or yours?

**Comment by LonwoLonwo** [comment]
Additional info about your Kerberos configuration properties also will be helpful.

**Comment by mipi21** [comment]
Now i use Community Edition 23.0.0 and working correctly .

My configuration
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**Comment by LonwoLonwo** [comment]
Did you use the 23.0.1 version with the included Java or with your own? Because Kerberos authentication directly depends on the Java version.

**Comment by mipi21** [comment]
Where can I see in dbeaver which java version I use?

**Comment by LonwoLonwo** [comment]
You can check it in DBeaver Help -> Installation Information -> Configuration

java.home and other properties

**Comment by mipi21** [comment]
C:\Program Files\DBeaver\jre\bin\server\jvm.dll
eclipse.home.location=file:/C:/Program Files/DBeaver/
eclipse.launcher=C:\Program Files\DBeaver\dbeaver.exe
eclipse.launcher.name=Dbeaver
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=DefaultProfile
eclipse.product=org.jkiss.dbeaver.ui.app.standalone.product
eclipse.startTime=1680505502463
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\Program Files\DBeaver\jre\bin\server\jvm.dll
eclipse.vmargs=-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=exe
-Djava.class.path=C:\Program Files\DBeaver\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
equinox.init.uuid=true
file.encoding=Cp1252
file.separator=\
gosh.args=--nointeractive
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\DBeaver\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
java.class.version=55.0
java.home=C:\Program Files\DBeaver\jre
java.rmi.server.hostname=127.0.0.1
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.12+7
java.security.krb5.conf=C:\ProgramData\MIT\Kerberos5\krb5.ini
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=Eclipse Foundation
java.vendor.url=https://adoptium.net/
java.vendor.url.bug=https://github.com/adoptium/adoptium-support/issues
java.vendor.version=Temurin-11.0.12+7
java.version=11.0.12
java.version.date=2021-07-20
java.vm.compressedOopsMode=32-bit
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=Eclipse Foundation
java.vm.version=11.0.12+7
javax.net.ssl.trustStoreType=WINDOWS-ROOT
jdk.debug=release
jna.loaded=true

**Comment by LonwoLonwo** [comment]
`java.home=C:\Program Files\DBeaver\jre` - means included Java. 

You can try to redownload DBeaver and uncheck included Java in the installation settings.

**Comment by mipi21** [comment]
java.home=C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot
Not working

[Cloudera][ImpalaJDBCDriver](500164) Error initialized or created transport for authentication: [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed.
  [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed
  [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed
    GSS initiate failed
    GSS initiate failed

**Comment by mipi21** [comment]
Any news? Also in 23.0.3 not working

**Comment by LonwoLonwo** [comment]
Hello @mipi21 

Connection to Kerberos directly depends on Java. We do not have Kerberos + Impala test environments for now, so I can't test your case. We need more time for it.

I can suggest you - change the Java version on this one:

> Now i use Community Edition 23.0.0 and working correctly .

Or find any other working Java + Kerberos version for your specific configuration.

**Comment by E1izabeth** [comment]
Have you tried jdk-11 instead of jdk-17?

**Comment by mipi21** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/6546228/4a53077c-9602-4f1e-9907-5f3aa629ea0f)

**Comment by E1izabeth** [comment]
Thank you for checking

**Comment by serge-rider** [comment]
@mipi21 We changed minimum Java version requirement to 11. 
You could try the fix (with your own local Java) in 23.0.5

**Comment by LonwoLonwo** [comment]
Hello @mipi21 

Please check it in our Early Access version: https://dbeaver.io/files/ea/
Will be waiting for your answer.

**Comment by mipi21** [comment]
Hi i have try installation with include java and not include and i have some result:
![image](https://github.com/dbeaver/dbeaver/assets/6546228/e6c785ea-0c9b-4a55-bec7-1a636e5806f3)

versione 23.0.5 (15/05 12:00)

**Comment by mipi21** [comment]
Now i have try with version 23.0.5 (16/05 00:00)--> not working

**Comment by LonwoLonwo** [comment]
Have you tried jdk-11 instead of jdk-17?

**Comment by mipi21** [comment]
ah no. When i check notify you

**Comment by mipi21** [comment]
I have checked. Also with jdk11 not working

**Comment by LonwoLonwo** [comment]
Could you please provide your configuration settings? Do you use a specific URL for the Kerberos connection? How do you provide KrbHostFQDN?

**Comment by mipi21** [comment]
jdbc:impala://impala.xxxx.it:yyyyy/default;authMech=1;KrbHostFQDN=impala.xxxx.it;KrbServiceName=impala;ssl=1;SSLTrustStore=C:\\Users\\xxx\\zzzz\\aaa\\jssecacerts;SSLTrustStorePwd=changeit

This is my configuration. I cant insert real address

**Comment by LonwoLonwo** [comment]
And if you will add `KrbRealm=<name>` parameter before `KrbHostFQDN`?

**Comment by LonwoLonwo** [comment]
```
4. If you are using Kerberos Constrained Delegation, set the userGSSCredential property
to your Kerberos GSS Credential.
5. Optionally, specify how the driver obtains the Kerberos Subject by setting the
KrbAuthType property as follows:
l To configure the driver to automatically detect which method to use for obtaining
the Subject, set the KrbAuthType property to 0. Alternatively, do not set the
KrbAuthType property.
l Or, to create a LoginContext from a JAAS configuration and then use the Subject
associated with it, set the KrbAuthType property to 1.
l Or, to create a LoginContext from a Kerberos ticket cache and then use the Subject
associated with it, set the KrbAuthType property to 2.
```

also, did you try to configure KrbAuthType? Or  userGSSCredential

**Comment by mipi21** [comment]
I have tried multiple configurations but none of them solve my problem.

**Comment by LonwoLonwo** [comment]
Hello @mipi21 

Could you please check the latest DBeaver version? https://dbeaver.io/files/ea/
Does the issue still persist?

**Comment by mipi21** [comment]
Sorry but not working.

[Cloudera][ImpalaJDBCDriver](500164) Error initialized or created transport for authentication: [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed.
  [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed
  [Cloudera][ImpalaJDBCDriver](500169) Unable to connect to server: GSS initiate failed
    GSS initiate failed
    GSS initiate failed
[
[stack_Error.txt](https://github.com/dbeaver/dbeaver/files/12066826/stack_Error.txt)
](url)


in 23.0.0 all ok

**Comment by LonwoLonwo** [comment]
Ok, thanks for the answer

**Comment by mipi21** [comment]
any news?

**Comment by LonwoLonwo** [comment]
We cannot reproduce the issue with the Impala Kerberos connection on the last DBeaver build with the included DBeaver JAVA.
You can try to find the Java package from version 23.0.0 and use it in the latest DBeaver version.
Or install the latest version of DBeaver with included JAVA.
For now, it is all ideas.

**Comment by Minutis** [comment]
> java.vendor.version=Temurin-11.0.12+7

I am not sure this is related but it might be: at the moment I am debugging a failure to login to Kerberos via java application. I can not pin point the exact issue but my last test clearly identifies that  Kerberos fails to login if I start the java application using Temurin 11 JRE. In case I use other vendor i.e. the old java.net same application runs successfuly. The only difference is java runtime that is used.

I would suggest to try to install different JRE which will be used to start DBeaver and try then.

Update: finally found the root cause of the issue. JDK 11.0.17 released a change that disables older encryption algorithm support by default. More information here: https://www.oracle.com/java/technologies/javase/11all-relnotes.html#JDK-8139348. Looking at your version it seems that it is not the same problems as I have. Sorry for false hope.

**Comment by mipi21** [comment]
Hil all, afther @Minutis  update , there is a news about fix? Thanks

new test : java.vendor.version=OpenLogic-OpenJDK version 17

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-24 16:44:29.673
!MESSAGE GSS initiate failed
!STACK 0
com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TTransportException: GSS initiate failed
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:221)
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:297)
	at com.cloudera.impala.jdbc41.internal.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at com.cloudera.impala.hivecommon.api.HiveServerPrivilegedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createTransport(Unknown Source)
	at com.cloudera.impala.hivecommon.api.HiveServer2ClientFactory.createClient(Unknown Source)
	at com.cloudera.impala.hivecommon.core.HiveJDBCCommonConnection.establishConnection(Unknown Source)
	at com.cloudera.impala.impala.core.ImpalaJDBCConnection.establishConnection(Unknown Source)
	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.connect(Unknown Source)
	at com.cloudera.impala.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.cloudera.impala.jdbc.common.AbstractDriver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:120)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:90)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1288)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1125)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2486)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by mipi21** [comment]
thanks @Minutis I have set "allow_weak_crypto = true" in my krb5.ini and now connection is done

**Comment by mipi21** [comment]
thanks @Minutis I have set "allow_weak_crypto = true" in my krb5.ini and now connection is done
