### ISSUE TITLE
Connection to Oracle RAC SCAN with SSH tunnel not possible

### ISSUE THREAD

**Issue by tsjam** [dbeaver/dbeaver#19590]
### Description

Due to infrastructure constraints I am forced to connect to various Oracle databases through a SSH server in between.
The functionality in DBeaver is working just fine for standard Oracle databases.

However, when I'm trying to connect to Oracle RAC databases through the SCAN address, the connection attempt is failing with a timeout.

The structure of an Oracle Real Application Cluster ist as follows:
Each database host (in my case two of them) has it's own host-name and -IP (hosta and hostb).
Each database host has it's own virtual name and IP (hosta-vip and hostb-vip), which is meant to fail over in case one of them fails.
There is one Single Client Access Name (SCAN) name (host-scan) with three IPs in round-robin behind it.

When I connect to either of the hostnames or virtual names through the SSH tunnel, everything works fine.
When I connect to the SCAN name through the SSH tunnel, it fails with a timeout on one of the virtual IPs.

With the background information of SCAN instructing the client to connect to a virtual IP, I sniffed the network packets with Wireshark. This confirms that DBeaver is trying to connect to the virtual IP directly. I'd rather expected DBeaver to also use the configured SSH tunnel for the VIP connection, because Oracle mandates that SCAN, VIP and host addresses be on the same subnet. So imo it makes no sense to just tunnel the SCAN connection, but not the VIP connection.

There is the workaround to connect directly to the VIP or host addresses for user db clients, so I don't see a very high priority to fix this here. It just cost me like two hours to figure out why a connection through SCAN was not working.
Please just let me know if I can supply more information! I omitted screenshots and logs so far, because the would only contain private host names and addresses which maybe don't help with understanding the issue.

### DBeaver Version

CE 23.0.1

### Operating System

Windows 11

### Database and driver

Server: Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Client: Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

1. Create new connection to Oracle database through SCAN and SSH tunnel
2. Connect to new connection (or test it)
3. Timeout connecting to VIP is thrown

**Comment by arhayka** [comment]
> I omitted screenshots and logs so far, because the would only contain private host names and addresses which maybe don't help with understanding the issue.

In this case, logs might be useful. Is there any way you could send them? For example, without private information. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by tsjam** [comment]
> In this case, logs might be useful. Is there any way you could send them? For example, without private information.

Sure! No problem at all.

I replaced the VIP in logs and messages with the fictitious IP 10.0.1.2. Also, I redacted username and scan hostname.

Just FYI the versions I'm using (from dbeaver-debug.log)
```
2023-05-15 10:57:23.286 - DBeaver 23.0.4.202305071722 is starting
2023-05-15 10:57:23.286 - OS: Windows 11 10.0 (amd64)
2023-05-15 10:57:23.286 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
```

The Error Dialog that pops up immediately after trying to connect says the following:
```
IO Error: The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
    Connection timed out: connect, socket connect lapse 21032 ms. /10.0.1.2 1521 0 1 true
    Connection timed out: connect, socket connect lapse 21032 ms. /10.0.1.2 1521 0 1 true
      Connection timed out: connect
      Connection timed out: connect
```

The Error Log only has one entry with the following details:
```
org.jkiss.dbeaver.model
Error
Mon May 15 11:01:58 CEST 2023
Connection timed out: connect

java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.base/java.nio.channels.SocketChannel.open(Unknown Source)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:81)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:169)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:161)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:521)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:660)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:639)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:189)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:241)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:254)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:273)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:91)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The .log file doesn't seem to really have anything more:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-15 11:01:58.910
!MESSAGE Connection timed out: connect
!STACK 0
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.base/java.nio.channels.SocketChannel.open(Unknown Source)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:81)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:169)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:161)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:521)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:660)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:639)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:189)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:241)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:254)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:273)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:91)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

dbeaver-debug.log has the following:
```
2023-05-15 11:01:37.361 - Connect with '<REDACTED> (SCAN)' (oracle_thin-1881ea438bc-708087a33b633472)
2023-05-15 11:01:37.362 - SSH: Connected with pageant
2023-05-15 11:01:37.362 - Creating new SecureRandom.
2023-05-15 11:01:37.394 - Client identity string: SSH-2.0-SSHJ_0.34.0
2023-05-15 11:01:37.424 - Server identity string: SSH-2.0-OpenSSH_7.4
2023-05-15 11:01:37.607 - Set port forwarding :53705 -> <REDACTED_SCAN_NAME>:1521
2023-05-15 11:01:37.607 - Listening on localhost/127.0.0.1:53705
2023-05-15 11:01:37.608 - Execution context opened (<REDACTED> (SCAN); Main; 6)
2023-05-15 11:01:58.854 - Closing listener on localhost/127.0.0.1:53705
2023-05-15 11:01:58.855 - Disconnected - BY_APPLICATION
2023-05-15 11:01:58.908 - Connection timed out: connect
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.base/java.nio.channels.SocketChannel.open(Unknown Source)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:81)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:169)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:161)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:521)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:660)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:639)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:189)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:241)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:254)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:273)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:91)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I couldn't find any "emergency logs" or Java fatal logs (hs_err) on my system.
If there's any other information I can provide, please just let me know.

**Comment by arhayka** [comment]
Hi @tsjam, sorry for the late response.
From our investigation, it seems that it's an infrastructure issue and it has nothing to do with the DBeaver, we can't resolve it on our side.
