### ISSUE TITLE
Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by trstn70** [dbeaver/dbeaver#19663]
### Description

try to connect to local docker container database with 127.0.0.1 for dev.
This renders this software unusable.

### DBeaver Version

23.0.2

### Operating System

ubuntu 22.04

### Database and driver

mysql 8
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html

### Steps to reproduce

version: '3'
services:
    mysql:
        image: mysql:8
        ports:
          - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password

### Additional context

If there is a new "feature" for me to take in consideration when doing these simple things, please let me know.
And if so please document this to be a clear show stopper if not done right.

**Comment by E1izabeth** [comment]
Could you explain more detailed, what the issue is for you?

**Comment by E1izabeth** [comment]
Does DBeaver stuck or you can't connect to database? It's not clear.

Also please provide log files https://dbeaver.com/docs/wiki/Log-files/

**Comment by trstn70** [comment]
no dbeaver does not suck, on the contrary. I need to work and it does not connect.
I installed the newest version of dbeaver 22.0.3.
I startet a mysql 8 database, see above docker-compose snippet for the container.
I try to connect dbeaver to this DB (with 127.0.0.1) with a already stored connection. The error message, see title, appears.
Same with a fresh created connection.

I see 2 errors in  the log
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.ui
Warning
Tue Apr 11 09:36:38 CEST 2023
Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

and

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Apr 11 09:41:14 CEST 2023
Public Key Retrieval is not allowed

java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:212)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:244)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:453)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:92)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:148)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment]
Thank you for quick response

**Comment by trstn70** [comment]
https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed

**Comment by trstn70** [comment]
This solved the problem, from the above stackoverflow

Right click your connection, choose "Edit Connection"

On the "Connection settings" screen (main screen) click on "Edit Driver Settings"

Click on "Connection properties", (In recent versions it named "Driver properties")

Right click the "user properties" area and choose "Add new property"

Add two properties: "useSSL" and "allowPublicKeyRetrieval"

Set their values to "false" and "true" by double clicking on the "value" column.

**Comment by E1izabeth** [comment]
Thank you for investigation.

**Comment by E1izabeth** [comment]
We have a setting for this in `Connection settings -> SSL`

![image](https://user-images.githubusercontent.com/28875055/231144672-fe43f1d4-ca56-4b4b-a838-c279df4a6166.png)

**Comment by E1izabeth** [comment]
Could you check, if it works for you?
