### ISSUE TITLE
[Derby] Can't export BLOB to TXT format

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#19698]
### Description

When exporting a table with BLOBs from Derby database to txt format we're getting an error:

![image](https://user-images.githubusercontent.com/43252954/231741150-96ed2c6b-6a5e-4489-a2f1-2d5cb823010a.png)

```txt
2023-04-13 15:10:48.108 - Error while exporting table footer
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [20000] [XJ215]: You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the free() method or after the Blob/Clob's transaction has been committed or rolled back.
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentLOB.handleContentReadingException(JDBCContentLOB.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getContents(JDBCContentBLOB.java:129)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT$ExportTextTarget.append(DataExporterTXT.java:91)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT$CellContentValue.exportTo(DataExporterTXT.java:155)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT.writeRow(DataExporterTXT.java:395)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT.writeQueue(DataExporterTXT.java:373)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT.exportFooter(DataExporterTXT.java:331)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.exportFooterInFile(StreamTransferConsumer.java:258)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.finishTransfer(StreamTransferConsumer.java:608)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.finishTransfer(StreamTransferConsumer.java:602)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:118)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [20000] [XJ215]: You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the free() method or after the Blob/Clob's transaction has been committed or rolled back.
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getLOBLength(JDBCContentBLOB.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentLOB.getContentLength(JDBCContentLOB.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getContents(JDBCContentBLOB.java:92)
	... 12 more
Caused by: java.sql.SQLException: You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the free() method or after the Blob/Clob's transaction has been committed or rolled back.
	at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:123)
	at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:325)
	at org.apache.derby.client.am.Lob.checkValidity(Lob.java:393)
	at org.apache.derby.client.am.ClientBlob.length(ClientBlob.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBLOB.getLOBLength(JDBCContentBLOB.java:71)
	... 14 more
Caused by: ERROR XJ215: You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the free() method or after the Blob/Clob's transaction has been committed or rolled back.
	at org.apache.derby.client.am.Lob.checkValidity(Lob.java:392)
	... 16 more
```
**Auto-commit mode is used**

### DBeaver Version

23.0.2

### Operating System

win10

**Comment by DariaMarkaryan** [comment]
Works as expected. We can't export blobs in auto-commit mode
