### ISSUE TITLE
Authentication failure with SSH - Exhausted available authentication methods error message

### ISSUE THREAD

**Issue by gkimpson** [dbeaver/dbeaver#19749]
### Description

When trying to use a SSH tunnel, I get the following error message : `Exhausted available authentication methods`

I can SSH into my server fine using the same key (note I have to connect to a VPN first), I have checked and my rsa SSH key DOES NOT have a passphrase (so that is one less thing to worry about). My server that I am SSH'ing into is running on Ubuntu 20.04 on an Azure VM.

Below is my DBeaver log
https://gist.github.com/gkimpson/6343fd46b6c20621e42e7402c85b8526

### DBeaver Version

DBeaver version: 23.0.2.202304091457

### Operating System

Ubuntu 22.04 LTS (My machine)
Ubuntu 20.04 (Remote VM)

### Database and driver

DBeaver SSH implementation (SSHJ)	1.0.124.202304091457  org.jkiss.dbeaver.net.ssh.sshj

### Steps to reproduce

1. Setup new connection
2. Click 'SSH tunnel' tab
3. Click 'Edit profile'
4. Input my host, port, username & private key path
5. Click 'Test tunnel configuration'

### Additional context

My SSH Key:
```
-----BEGIN OPENSSH PRIVATE KEY-----

[...]

-----END OPENSSH PRIVATE KEY-----
```

DBeaver error logs:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-04-19 13:44:57.980
!MESSAGE Exhausted available authentication methods
!STACK 0
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:393)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:113)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:135)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:77)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$8.execute(SSHTunnelConfiguratorUI.java:307)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$TunnelConnectionTestJob.run(SSHTunnelConfiguratorUI.java:734)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by Destrolaric** [comment]
@gkimpson Could you see if the key file has required permissions on reading?
```
java.io.FileNotFoundException: /home/gavin/.ssh/id_rsa.pub (Permission denied)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileReader.<init>(Unknown Source)
```

**Comment by gkimpson** [comment]
Ok - I have found the problem, I am using DBeaver installed via Snap so this method works but it doesn't feel very secure copying my .ssh directory another location on my machine, can anyone suggest any other ideas?
https://github.com/dbeaver/dbeaver/issues/7640

**Comment by gkimpson** [comment]
> @gkimpson Could you see if the key file has required permissions on reading?
> 
> ```
> java.io.FileNotFoundException: /home/gavin/.ssh/id_rsa.pub (Permission denied)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(Unknown Source)
> 	at java.base/java.io.FileInputStream.<init>(Unknown Source)
> 	at java.base/java.io.FileReader.<init>(Unknown Source)
> ```

Good spot - I noticed this around the same time and found the fix due to DBeaver installed via Snap not having permissions, so I had to move the .ssh directory but this doesn't feel like a good fix and surely is a bug that DBeaver should fix

**Comment by Destrolaric** [comment]
@gkimpson You could look here at the solutions in this discussion: https://github.com/dbeaver/dbeaver/issues/7640#:~:text=Guys%2C%20I%20had%20the%20same%20problem%20on%20Ubuntu%2020.04%2C%20so%20I%20needed%20to%20change%20the%20permissions%20of%20the%20dbeaver%20application%20as%20the%20image%3A

**Comment by gkimpson** [comment]
thanks I will close this now as I have found a workaround
