### ISSUE TITLE
DBeaver not launching after auto-upgrading to 23.0.3

### ISSUE THREAD

**Issue by edinglasan31** [dbeaver/dbeaver#19783]
### Description

Hello,

We are getting the error below after DBeaver auto aupgraded to 23.0.3

`        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        ... 24 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        no swt-pi4-gtk-4956r13 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/226/lib:/snap/dbeaver-ce/226/usr/lib:/snap/dbeaver-ce/226/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib:/snap/dbeaver-ce/226/gnome-platform/lib:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        no swt-pi4-gtk in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/226/lib:/snap/dbeaver-ce/226/usr/lib:/snap/dbeaver-ce/226/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib:/snap/dbeaver-ce/226/gnome-platform/lib:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        no swt-pi4 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/226/lib:/snap/dbeaver-ce/226/usr/lib:/snap/dbeaver-ce/226/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/226/gnome-platform/usr/lib:/snap/dbeaver-ce/226/gnome-platform/lib:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/226/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        Can't load library: /home/ellai/snap/dbeaver-ce/226/.swt/lib/linux/x86_64/libswt-pi4-gtk-4956r13.so
        Can't load library: /home/ellai/snap/dbeaver-ce/226/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
        Can't load library: /home/ellai/snap/dbeaver-ce/226/.swt/lib/linux/x86_64/libswt-pi4.so

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
        at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:97)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
        at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
        at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
        ... 32 more
                                                                                                                                                             179,7-14      Bot
`

### DBeaver Version

Community DBeaver Community 23.0.3

### Operating System

Ubuntu 18.04.6 LTS  running Xfce Desktop Environment v 4.12 

### Steps to reproduce

Just launching dbeaver from the command line

`dbeaver-ce`

**Comment by edinglasan31** [comment]
We tried https://github.com/dbeaver/dbeaver/issues/15509 but that did not resolve the issue

**Comment by phongvt322** [comment]
I have the same problem.
OS: Ubuntu 20.04.6 LTS.
Version of Dbeaver: 23.0.3.202304222322

**Comment by fbarbeira** [comment]
Same OS, same dbeaver version, same error

**Comment by LonwoLonwo** [comment]
Probably a duplicate of #19779

**Comment by edinglasan31** [comment]
Closing as a duplicate

**Comment by MashaKorax** [comment]
Thanks for your bug report!

**Comment by princeraheja8** [comment]
same issue . very blocker issue , not able to open
![Screenshot from 2023-04-24 14-01-20](https://user-images.githubusercontent.com/29802116/233942653-e3fdf763-ff22-4d0f-ad0c-b6bd827e0e38.png)

**Comment by Emmanuel35** [comment]
Same with Ubuntu 22.04

```
➜  ~ snap list dbeaver-ce   
Name        Version              Rev  Tracking       Publisher     Notes
dbeaver-ce  23.0.3.202304240616  227  latest/stable  dbeaver-corp  -
```

Log is 
```
!SESSION 2023-04-24 11:24:17.395 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2023-04-24 11:24:18.756
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (153).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:381)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:357)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:207)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4958r2 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk-4958r2.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:97)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 31 more
Root exception:
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4958r2 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk-4958r2.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:97)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:381)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:357)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:207)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

!ENTRY org.eclipse.osgi 4 0 2023-04-24 11:24:18.758
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/eclipse/ui/internal/ide/ChooseWorkspaceData
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:381)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:357)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:207)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.ui.ide (153).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 24 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4958r2 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4 in java.library.path: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/dbeaver-ce/227/lib:/snap/dbeaver-ce/227/usr/lib:/snap/dbeaver-ce/227/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/dbeaver-ce/227/gnome-platform/usr/lib:/snap/dbeaver-ce/227/gnome-platform/lib:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/dbeaver-ce/227/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk-4958r2.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	Can't load library: /home/emmanuel/snap/dbeaver-ce/227/.swt/lib/linux/x86_64/libswt-pi4.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:97)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 31 more

```

Package libswt-gtk-4-java is installed.
```
sudo apt install libswt-gtk-4-java                                                                                                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libswt-gtk-4-java is already the newest version (4.20.0-2)
```
