### ISSUE TITLE
dbeaver 23.0.3.202304240616 - Result grid skips displaying anything after \r\n in a string field

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#19807]
### Description

Example : (backend DB : Snowflake)

```SQL
SELECT 'ROW 1 \r\n'
UNION ALL
SELECT 'ROW 2'
```
![image](https://user-images.githubusercontent.com/130557869/234508035-bcfe794e-3be4-474d-a9d8-47cb1fbeccb4.png)
![image](https://user-images.githubusercontent.com/130557869/234508073-a724d2f6-08d4-4179-9c4c-3080a2691a79.png)

### DBeaver Version

Community Edition dbeaver 23.0.3.202304240616

### Operating System

Win11

### Database and driver

Snowflake

### Steps to reproduce

cf description

**Comment by LonwoLonwo** [comment]
Thanks for the report @Thomas-LEILLET-Sanofi

**Comment by LonwoLonwo** [comment]
```
java.lang.StringIndexOutOfBoundsException: begin 8, end 7, length 8
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridCellRenderer.drawCellTextDecorated(GridCellRenderer.java:335)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridCellRenderer.paint(GridCellRenderer.java:217)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onPaint(LightGrid.java:2389)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1536)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4800)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
	at org.eclipse.swt.internal.win32.OS.RedrawWindow(Native Method)
	at org.eclipse.swt.widgets.Sash.WM_MOUSEMOVE(Sash.java:386)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4790)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
```
