### ISSUE TITLE
cannot access class sun.security.action.GetPropertyAction

### ISSUE THREAD

**Issue by meriturva** [dbeaver/dbeaver#19806]
### Description

Error only on first connection then works like a charm!

Here my log file:

```
!SESSION 2023-04-26 09:31:39.567 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data .\workspace

!ENTRY org.eclipse.ui 2 2 2023-04-26 09:31:45.962
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-04-26 09:31:49.538
!MESSAGE class sun.jdbc.odbc.JdbcOdbcDriver (in unnamed module @0x3c9c37ba) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x3c9c37ba
!STACK 0
java.lang.IllegalAccessError: class sun.jdbc.odbc.JdbcOdbcDriver (in unnamed module @0x3c9c37ba) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x3c9c37ba
	at sun.jdbc.odbc.JdbcOdbcDriver.initialize(JdbcOdbcDriver.java:449)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:212)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:244)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:97)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-04-26 09:31:54.003
!MESSAGE Error determining server version
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-04-26 09:31:54.003
!MESSAGE UnsupportedOperationException
!STACK 0
java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.readDatabaseServerVersion(JDBCDataSource.java:493)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:465)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:492)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1198)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:97)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

and here just a gif to show that the error is present only on first connection to a ODBC connection.
![odbc_first_connection_error](https://user-images.githubusercontent.com/5664195/234503031-dc26665e-206f-45dc-90d3-665e64641fd1.gif)

### DBeaver Version

dbeaver-ce-23.0.3-win32.win32.x86_64

### Operating System

Windows 11

**Comment by uslss** [comment]
thanks for the report

**Comment by flambchap** [comment]
Hi @meriturva. Can you please patch your `dbeaver.ini` file and see if this helps? You can find the file in the folder with your DBeaver installation. Specifically, you need to add the `--add-opens=java.base/sun.security.action=ALL-UNNAMED` entry near other similar lines (there is a bunch of lines starting with `--add-opens=java.base/` in the file).

**Comment by meriturva** [comment]
Thanks @n5a5 using `--add-opens=java.base/sun.security.action=ALL-UNNAMED` seems to fix the issue. But it is pretty strange that I have to add that setting on `dbeaver.ini` downloaded from the official site (zip/portable distribution with jre included URL: https://dbeaver.io/files/dbeaver-ce-latest-win32.win32.x86_64.zip).
Is it better to add by default? am I wrong?

**Comment by serge-rider** [comment]
Fix in devel

**Comment by flambchap** [comment]
@meriturva Fair point. We'll fix the issue in one of our upcoming releases.

**Comment by uslss** [comment]
verified.
Fix will be available in 23.0.4

**Comment by JonathanRin** [comment]
Hello,
I have done all the things on dbeaver.ini but still not working.
I have the following error : java.lang.IllegalAccessException: class org.apache.hadoop.security.authentication.util.KerberosUtil cannot access class sun.security.krb5.Config

**Comment by serge-rider** [comment]
@JonathanRin Could you try to add line
`--add-opens=java.base/sun.security.krb5=ALL-UNNAMED`
in dbeaver.ini file?

**Comment by JonathanRin** [comment]
Done, i still have the following error : 2023-07-05 15:44:43.257 - class org.apache.hadoop.security.authentication.util.KerberosUtil cannot access class sun.security.krb5.Config (in module java.security.jgss) because module java.security.jgss does not export sun.security.krb5 to unnamed module @1ab39af

**Comment by serge-rider** [comment]
This happens because database driver is not fully compatible with Java 11+.
Adding extra --add-opens may help but I am not sure which ones are needed.

What database driver do you use?

**Comment by JonathanRin** [comment]
I have tried both Kyuubi and Hive.

**Comment by serge-rider** [comment]
You could try to add lines
```
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
```
However I am not sure that it will help.

I'd wish to reproduce the issue on my side. 
Could you share some details about your Hive connection configuration? I see that you are using Kerberos, what properties you set for the connection? (please mask any non-public connection info)

**Comment by JonathanRin** [comment]
dbeaver.ini : 
![image](https://github.com/dbeaver/dbeaver/assets/98532393/03f7cb12-f0c9-43a7-990e-57aeff7bd90a)

jaas.conf : 
![image](https://github.com/dbeaver/dbeaver/assets/98532393/399dc439-33c1-4d92-ba0e-92706d84ae78)

krb5.ini : 
![image](https://github.com/dbeaver/dbeaver/assets/98532393/5bef39d9-024f-464e-a457-c684c35e3625)

**Comment by serge-rider** [comment]
Thanks, could you also say how you configure it in dbeaver? 
- It is Hive uber driver?
- What URL do you use? 
- What connection properties are set?

**Comment by serge-rider** [comment]
Never mind, I've reproduced it.
The issue will be fixed in the next DBeaver version

**Comment by serge-rider** [comment]
#19023 will be also fixed

**Comment by JonathanRin** [comment]
Ok sorry was on other project this morning.
So ok it will be fixed in the next release, did you know when approximatively ?

**Comment by serge-rider** [comment]
Hopefully next Monday. Otherwise in v23.1.3 (see related issue https://github.com/dbeaver/dbeaver/issues/19023)
