### ISSUE TITLE
Exception reported during startup

### ISSUE THREAD

**Issue by Bzkkk777** [dbeaver/dbeaver#19818]
### Description

!SESSION 2023-04-27 11:11:42.690 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2023-04-27 11:11:58.081
!MESSAGE An error occurred while automatically activating bundle org.eclipse.core.net (339).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.core.internal.net.Activator.start() of bundle org.eclipse.core.net.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.activateProxyService(IDEWorkbenchAdvisor.java:299)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.postStartup(IDEWorkbenchAdvisor.java:277)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.postStartup(ApplicationWorkbenchAdvisor.java:231)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:297)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.IllegalArgumentException: Node path "A_/(©V²þ/V¦1@¾jÇf'¥`Âì¯f)Vó22G9ty2ó¤vìóoøäÎ]#ÞLòpý´pÝü[ÂÁù@b(îº§e£¨[cÁ³ö|99¸Z©ºÜ¾¿_¸ýÁ¿î" is not valid.
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.validatePath(SecurePreferences.java:363)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.node(SecurePreferences.java:101)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.load(SecurePreferencesRoot.java:152)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.<init>(SecurePreferencesRoot.java:88)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.open(SecurePreferencesMapper.java:116)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.getDefault(SecurePreferencesMapper.java:56)
	at org.eclipse.equinox.security.storage.SecurePreferencesFactory.getDefault(SecurePreferencesFactory.java:52)
	at org.eclipse.core.internal.net.ProxyType.getNode(ProxyType.java:545)
	at org.eclipse.core.internal.net.ProxyType.loadProxyAuth(ProxyType.java:555)
	at org.eclipse.core.internal.net.ProxyType.createProxyData(ProxyType.java:145)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:134)
	at org.eclipse.core.internal.net.PreferenceManager.migrateInstanceScopePreferences(PreferenceManager.java:287)
	at org.eclipse.core.internal.net.PreferenceManager.migrate(PreferenceManager.java:256)
	at org.eclipse.core.internal.net.ProxyManager.checkMigrated(ProxyManager.java:386)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:258)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:177)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 40 more
Root exception:
java.lang.IllegalArgumentException: Node path "A_/(©V²þ/V¦1@¾jÇf'¥`Âì¯f)Vó22G9ty2ó¤vìóoøäÎ]#ÞLòpý´pÝü[ÂÁù@b(îº§e£¨[cÁ³ö|99¸Z©ºÜ¾¿_¸ýÁ¿î" is not valid.
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.validatePath(SecurePreferences.java:363)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.node(SecurePreferences.java:101)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.load(SecurePreferencesRoot.java:152)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.<init>(SecurePreferencesRoot.java:88)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.open(SecurePreferencesMapper.java:116)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesMapper.getDefault(SecurePreferencesMapper.java:56)
	at org.eclipse.equinox.security.storage.SecurePreferencesFactory.getDefault(SecurePreferencesFactory.java:52)
	at org.eclipse.core.internal.net.ProxyType.getNode(ProxyType.java:545)
	at org.eclipse.core.internal.net.ProxyType.loadProxyAuth(ProxyType.java:555)
	at org.eclipse.core.internal.net.ProxyType.createProxyData(ProxyType.java:145)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:134)
	at org.eclipse.core.internal.net.PreferenceManager.migrateInstanceScopePreferences(PreferenceManager.java:287)
	at org.eclipse.core.internal.net.PreferenceManager.migrate(PreferenceManager.java:256)
	at org.eclipse.core.internal.net.ProxyManager.checkMigrated(ProxyManager.java:386)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:258)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:177)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.activateProxyService(IDEWorkbenchAdvisor.java:299)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.postStartup(IDEWorkbenchAdvisor.java:277)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.postStartup(ApplicationWorkbenchAdvisor.java:231)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:297)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

### DBeaver Version

23.0.3

### Operating System

win7

### Database and driver

oracle

**Comment by LonwoLonwo** [comment]
Hello @Bzkkk777 

Could you please re-download and restart DBeaver?
Also, what installation do you use?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual for you, please let me know.

**Comment by stephen-zyh** [comment]
> It's been a while since no update here. If the issue is still actual for you, please let me know.

I packaged the source code and verified on my computer that the program worked, and then sent it to my colleagues, some of whom worked correctly, but several of them also got the error. I don't know why it happens.

**Comment by stephen-zyh** [comment]
> It's been a while since no update here. If the issue is still actual for you, please let me know.

@E1izabeth I packaged the source code and verified on my computer that the program worked, and then sent it to my colleagues, some of whom worked correctly, but several of them also got the error. I don't know why it happens.

**Comment by E1izabeth** [comment]
Does it happen on the version from the web site? https://dbeaver.io/download/
