### ISSUE TITLE
SQLITE_CANTOPEN upon opening a 74GB SQLite database

### ISSUE THREAD

**Issue by adrmrv** [dbeaver/dbeaver#19838]
### Description

[SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)

This is while opening a 74GB sqlite file which i can open with DB Browser for SQLite.

> org.sqlite.SQLiteException: [SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1135)
	at org.sqlite.core.DB.newSQLException(DB.java:1146)
	at org.sqlite.core.DB.throwex(DB.java:1106)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:75)
	at org.sqlite.core.DB.open(DB.java:216)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:285)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:104)
	at org.sqlite.JDBC.connect(JDBC.java:77)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:212)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:244)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.sqlite.model.SQLiteDataSource.<init>(SQLiteDataSource.java:49)
	at org.jkiss.dbeaver.ext.sqlite.model.SQLiteMetaModel.createDataSourceImpl(SQLiteMetaModel.java:153)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Session data : 
> eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

### DBeaver Version

Community edition Version 23.0.3.202304240616

### Operating System

Linux magicbook 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Database and driver

org.xerial.sqlite-jdbc

### Steps to reproduce

![image](https://user-images.githubusercontent.com/20116994/235317412-3cc2a528-3e42-4eec-8ac0-fe93ac008ffa.png)
Use this DB :
https://tnt.maiti.info/dhtd/

**Comment by ShadelessFox** [comment]
Hello @adrmrv,

Can you please show the output of the following command?

```sh
hexdump -Cn 512 /mnt/media2to/database.sqlite3
```

**Comment by adrmrv** [comment]
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 02 02 00 40 20 20  00 41 3a 8c 01 14 64 96  |.....@  .A:...d.|
00000020  01 14 64 92 00 00 00 01  00 00 00 17 00 00 00 04  |..d.............|
00000030  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 03  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 41 3a 8c  |.............A:.|
00000060  00 2e 3f d9 0d 0f f8 00  0f 03 98 00 0c cd 0f c7  |..?.............|
00000070  0b 26 0a b1 0a 27 09 ac  09 35 08 d4 08 73 08 14  |.&...'...5...s..|
00000080  07 45 06 8f 05 c2 04 af  03 98 00 00 00 00 00 00  |.E..............|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000200

The db is here :
https://tnt.maiti.info/dhtd/

**Comment by ShadelessFox** [comment]
Is DBeaver installed as a snap package?

**Comment by adrmrv** [comment]
Yes

**Comment by ShadelessFox** [comment]
It can't access files from your filesystem. I'm unfamiliar with snap, but maybe it's possible to allow it to access particular files?

As an ultimate solution, try installing DBeaver as a non-snap package.

**Comment by adrmrv** [comment]
The same problem happens with a small database in the same directory
