### ISSUE TITLE
Support for LIST in duckdb 0.7.1

### ISSUE THREAD

**Issue by Vincenthays** [dbeaver/dbeaver#19892]
**Is your feature request related to a problem? Please describe.**
No support for LIST in `duckdb_jdbc-0.7.1.jar`
```sql
SELECT [1, 2, 3];
```
Output:
```
SQL Error: Unsupported result column type INTEGER[]
```

**Describe the solution you'd like**
I'm uncertain whether the issue comes from DBeaver or the Java driver supplied by DuckDB.

**Comment by LonwoLonwo** [comment]
Hello @Vincenthays 

Thanks for the report.

It looks like we are waiting for the next DuckDB driver release: https://github.com/duckdb/duckdb/pull/7000

**Comment by Vincenthays** [comment]
Thanks for the reply @LonwoLonwo

**Comment by E1izabeth** [comment]
Let's keep it open to update duckdb driver.

**Comment by Vincenthays** [comment]
Hello @E1izabeth 
I just tested the new duckdb driver 8.0.0
And works just fine for this case, but not all cases
```sql
SELECT [1, 2, 3]; -- works
SELECT CAST([1, 2, 3] as UINTEGER[]); -- output below
```
```
java.lang.UnsupportedOperationException: Unimplemented method 'getResultSet'
	at org.duckdb.DuckDBArray.getResultSet(DuckDBArray.java:63)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromResultSet(JDBCCollection.java:388)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:275)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3861)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
