### ISSUE TITLE
ODBC Driver Failure Amazon Redshift  - CE 23.0.4

### ISSUE THREAD

**Issue by MuggleHerder** [dbeaver/dbeaver#19938]
### Description

I am receiving now the following error ""Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null""  when trying to create an ODBC connection to Amazon Redshift via "ODBC -Legacy" Connection

### DBeaver Version

CE 23.0.4.202305071722

### Operating System

Windows 10 

### Database and driver

Database: Amazon Redshift 
Driver: Amazon RedShift ODBC Driver 64-bit 2.0.0.1
Via ODBC Administrator 64-bit -> Test connection is successful including SSO AzureAD Authentication 

### Steps to reproduce

1. Open DBeaver (Fresh Install)
2. Database -> New Database Connection -> ODBC - Legacy -> Database:Scheme = "NAME OF MY ODBC SYSTEM DSN" -> Finish
3.Do not Send (Data Share)
4. Download Driver Files -> Force Download / Overwrite ( tried this force/noforce(fresh Installs)) -> 
![image](https://github.com/dbeaver/dbeaver/assets/62776783/fb19240e-ec5d-4313-8f66-2a2b6a1588f7)

Error:  "Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null"
![image](https://github.com/dbeaver/dbeaver/assets/62776783/77cda323-0cbf-4ff1-8c21-9f931a474610)

### Additional context

Regular LOG:
!SESSION 2023-05-10 18:22:16.945 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2023-05-10 18:22:24.910
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-10 18:24:31.742
!MESSAGE Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null
	at sun.jdbc.odbc.JdbcOdbcDriver.initialize(JdbcOdbcDriver.java:453)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:241)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:254)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:273)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:97)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	
	Debug Log: ( Certain Areas removed with "XXXXX")
	2023-05-10 18:22:18.883 - DBeaver 23.0.4.202305071722 is starting
2023-05-10 18:22:18.885 - OS: Windows 10 10.0 (amd64)
2023-05-10 18:22:18.886 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2023-05-10 18:22:18.886 - Install path: 'C:\Program Files\DBeaver'
2023-05-10 18:22:18.887 - Instance path: 'file:/C:/Users/XXXXXXXXX/AppData/Roaming/DBeaverData/workspace6/'
2023-05-10 18:22:18.887 - Memory available 64Mb/1024Mb
2023-05-10 18:22:18.908 - Create display
2023-05-10 18:22:19.194 - Initializing DBeaver 23.0.4
2023-05-10 18:22:19.197 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.0.4.202305071722
2023-05-10 18:22:19.234 - Initialize desktop platform...
2023-05-10 18:22:19.480 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.9.500.v20220817-1539]
> Start Core Resource Management [org.eclipse.core.resources 3.18.200.v20230209-0754]
> Start Team Support Core [org.eclipse.team.core 3.9.700.v20221201-0946]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.105.202305071722]
2023-05-10 18:22:19.725 - 
2023-05-10 18:22:19.726 - 	Refreshing workspace.
2023-05-10 18:22:19.730 - Refreshing workspace contents
2023-05-10 18:22:20.041 - Initialize base platform...
> Start Expression Language [org.eclipse.core.expressions 3.8.200.v20220613-1047]
2023-05-10 18:22:20.085 - Platform initialized (851ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.105.202305071722]
2023-05-10 18:22:20.103 - Starting RMI server at 64928
2023-05-10 18:22:20.193 - Run workbench
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.120.202305071722]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.16.800.v20230220-0932]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.3.400.v20220915-1347]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.5.200.v20230220-0932]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.3.700.v20230214-1401]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.18.0.v20230211-1150]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.13.300.v20230220-0932]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.4.600.v20230220-0932]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.15.800.v20230214-1401]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.13.300.v20230220-0932]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.17.200.v20220613-1008]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.14.800.v20230220-0932]
> Start Java Native Access [com.sun.jna 5.12.1.v20221103-2317]
2023-05-10 18:22:22.787 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.95.202305071722]
2023-05-10 18:22:22.992 - Total database drivers: 102 (102)
> Start Help System Core [org.eclipse.help 3.9.100.v20210721-0601]
2023-05-10 18:22:23.183 - Create actions
2023-05-10 18:22:23.200 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-05-10 18:22:23.201 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-05-10 18:22:23.201 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2023-05-10 18:22:24.574 - Initialize workbench window
2023-05-10 18:22:24.580 - Finish initialization
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.105.202305071722]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.1000.v20220801-1135]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.4.100.v20220812-1406]
> Start Internet Connection Management [org.eclipse.core.net 1.4.0.v20220813-1037]
> Start Draw2d [org.eclipse.draw2dl 3.12.100.20230428131615]
> Start GEF3 GEF (MVC) [org.eclipse.gef3 3.12.100.20230428131615]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.65.202305071722]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.65.202305071722]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.105.202305071722]
> Start Default Text Editor [org.eclipse.ui.editors 3.15.0.v20221201-1935]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.16.700.v20230210-0941]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.142.202305071722]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.111.202305071722]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.96.202305071722]
2023-05-10 18:22:27.985 - Open [https://dbeaver.io/product/version.xml]
> Start DBeaver Generic UI Plug-in [org.jkiss.dbeaver.ext.generic.ui 1.0.81.202305071722]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.191.202305071722]
2023-05-10 18:22:40.971 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2023-05-10 18:23:21.660 - Connect with 'XXXX-XXXXXXXX' (odbc-18807f95558-6ee9f9303edda3a4)
2023-05-10 18:23:21.686 - Execution context opened (XXXX-XXXXXXXX; Main; 0)
2023-05-10 18:24:30.723 - Open [https://github.com/dbeaver/jdbc-odbc-bridge-jre7/raw/main/jdbc-odbc-bridge-jre7.jar]
2023-05-10 18:24:31.292 - Open [https://github.com/dbeaver/jdbc-odbc-bridge-jre7/raw/main/x64/JdbcOdbc.dll]
2023-05-10 18:24:31.739 - Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null
java.lang.NullPointerException: Cannot invoke "sun.jdbc.odbc.JdbcOdbc.getTracer()" because "sun.jdbc.odbc.JdbcOdbcDriver.OdbcApi" is null
	at sun.jdbc.odbc.JdbcOdbcDriver.initialize(JdbcOdbcDriver.java:453)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:241)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:254)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:273)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:97)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment]
Similar issue #19795

**Comment by E1izabeth** [comment]
Closing this as a duplicate.
