### ISSUE TITLE
Export data feature fails 

### ISSUE THREAD

**Issue by jgrover21** [dbeaver/dbeaver#19992]
### Description

Export data feature fails : it creates new table in cross database but does not add data to it.  fails without error messge

### DBeaver Version

Community Edition 23.0.4

### Operating System

windows

### Database and driver

postgres sql 14.0

### Steps to reproduce

right click a table.
select export data and follow the steps to copy data to another database
it starts exporting and completes.  window goes away
it creates table but does not add data to it.
sometimes it is a success.  sometimes it fails.  it is not consistent

**Comment by jgrover21** [comment]
it is
PostgreSQL 14.6
PostgreSQL JDBC Driver 42.5.0

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by jgrover21** [comment]
Here is log file.  I just tried to export.

Respectfully,

Jyoti Grover

**Comment by jgrover21** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/11499530/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Judging by the log it has something to do with the data in some particular table(s).

**Comment by jgrover21** [comment]
interesting enough...my other colleague was able to export other table that failed for me the same way.  I can check if this one works for him

**Comment by E1izabeth** [comment]
Do you use the same DBeaver version with your colleagues?

**Comment by jgrover21** [comment]
yes, he has same

**Comment by jgrover21** [comment]
yes, he has done it.  table got created in less than a minute

**Comment by jgrover21** [comment]
data is fully loaded

**Comment by E1izabeth** [comment]
Could you check if the driver versions are the same with your colleague? You can find it here
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d2ddd66d-2ca6-4fce-abd2-1169479755ab)

**Comment by jgrover21** [comment]
looks same for both of us

**Comment by jgrover21** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/125315744/57092bff-8a3d-4ca5-9e45-3feb95a69e37)

**Comment by jgrover21** [comment]
we have same version and same driver settings.

**Comment by jgrover21** [comment]
as far as I remember, a few versions back I was able to do about 70-80% of export.  it used to fail sometimes.  now it fails more often.

**Comment by LonwoLonwo** [comment]
```
Caused by: org.postgresql.util.PSQLException: ERROR: missing data for column "pa_d__c"
  Where: COPY patientupdate, line 325: ""a1s16000007a0cLAAQ","","","5001600000xpBwQAAU","","","","","","","BP /, MAP <br>CVP mmHG , RA/CVP ,..."
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1264)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1069)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:212)
	... 10 more
```

As I can see - issue is related with the bulk loading. Did you try to uncheck the "bulk load" setting and use export without it?

![2023-05-19 13_41_39-Window](https://github.com/dbeaver/dbeaver/assets/45152336/f9ef60c6-c79e-4bc0-8398-09e1188436d7)

Also, do you have any ideas about this issue part? 
`ERROR: missing data for column "pa_d__c"`

**Comment by jgrover21** [comment]
Yes.  That seems to work in one case but not other.
How do we know to check bulk load or not?

Respectfully,

Jyoti Grover

**Comment by esilvia** [comment]
I'm having the same issue. Same DBeaver and Postgresql driver versions as the OP.

In my case I'm importing the table from one db to another, and bulk load is failing on some tables and succeeding on others.

Here's the relevant section from the log, which occurred around the time of failure:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-26 15:04:44.815
!MESSAGE Error while finishing result set fetch
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-05-26 15:04:44.815
!MESSAGE Error copying dataset on remote server
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-05-26 15:04:44.815
!MESSAGE ERROR: extra data after last expected column
  Where: COPY project_detail, line 26: ""947122-R040667.00","5/4/2022: client has made some minor changes to the phase4_buff so now we have ..."
!STACK 0
org.postgresql.util.PSQLException: ERROR: extra data after last expected column
  Where: COPY project_detail, line 26: ""947122-R040667.00","5/4/2022: client has made some minor changes to the phase4_buff so now we have ..."
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1224)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1029)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:212)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:495)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:214)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

As with the OP, the import operation appears to succeed, but the table is empty when I try to open it. The only hint of failure is the log.

As I review the tables that fail, one thing they all have in common is that *they all have double-quotes in the original data*. When I tamper with the row called out in the above error message to remove the double-quotes, it fails at a different row. This suggests to me that the parser engine is failing on rows with double-quotes.

**Comment by E1izabeth** [comment]
@esilvia thank you for information!

**Comment by esilvia** [comment]
Here's another log entry that includes the escaped double-quote in the log entry itself (arrows added):

```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-26 14:57:52.137
!MESSAGE Error while finishing result set fetch
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-05-26 14:57:52.137
!MESSAGE Error copying dataset on remote server
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-05-26 14:57:52.137
!MESSAGE ERROR: extra data after last expected column
  Where: COPY project_detail, line 21: ""947122-R039994.00","3\" 4band orthos. Plan update from 2017 project Please assume mobilization from..."
                                                             ^^^
                                                             ^^^
                                                             ^^^
!STACK 0
org.postgresql.util.PSQLException: ERROR: extra data after last expected column
  Where: COPY project_detail, line 21: ""947122-R039994.00","3\" 4band orthos. Plan update from 2017 project Please assume mobilization from..."
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
    at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1224)
    at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1029)
    at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
    at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:212)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:495)
    at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:214)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:259)
    at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:176)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
    at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
    at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
    at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by E1izabeth** [comment]
I tried to reproduce it on table with this data
![image](https://github.com/dbeaver/dbeaver/assets/28875055/d9a6484a-aae1-4bbe-bfc6-f1225ce81df8)

After export with bulk load option I get
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e0dab7bf-411e-4141-9310-ec6a1126e10b)

**Comment by E1izabeth** [comment]
Even simple case 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/47663999-729d-4a4a-b54a-02d3be3a044b)

is not working correct

![image](https://github.com/dbeaver/dbeaver/assets/28875055/0e6fc84d-0c4b-47e9-8e73-68760ad49e69)
