### ISSUE TITLE
Unable to authenticate to MS SQL Azure with MFA

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#20059]
### Description

Hi, I can't authenticate to ms azure sql db server with MFA Authentication (production enviroment). In the past, I got similar problem, due driver configuration issue (msal4j dirver version). 

Now, when I attempt to login, I get a timeout Socket Error:

![image](https://github.com/dbeaver/dbeaver/assets/26387091/0c790b06-fae1-4456-862e-050055358ab8)

I the debug log i can see:
2023-05-23 11:34:06.934 - [Correlation ID: bf87f9e7-fc97-42ee-a76b-9bd0074a7392] **Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.**
com.microsoft.aad.msal4j.MsalClientException: **java.net.SocketTimeoutException: Connect timed out**
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:56)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.executeRequest(AadInstanceDiscoveryProvider.java:286)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:237)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:347)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:90)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:39)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:59)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:193)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:105)
	at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpGet(DefaultHttpClient.java:47)
	at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:35)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:99)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:52)
	... 14 more

Here's my driver configuration:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/1c4b4763-b793-4982-9a20-cfa1416f9155)

I tried to change msal4j driver version, from 1.11.3 to the last version (with the same error). I tried to change mssql-jdbc driver with different version too.

When I attempt to login, I get correctly all login form, I insert username & password and (In my case) random number verification... in the browser I can see the token authentication message... opened in multiple browser tabs:

![image](https://github.com/dbeaver/dbeaver/assets/26387091/bf39256a-8f2f-4b26-9945-10cade2dddad)

I CAN login without problem to any other Azure SQL DB (in the same subnet) without MFA authentication (test and development enviroment)...

 

### DBeaver Version

Community Edition v.23.0.5

### Operating System

Windows 10

### Database and driver

Microsoft MSQL Azure

**Comment by LonwoLonwo** [comment]
Hello @geuss 
For now, it is not clear what we can change in DBeaver. Because all authentication logic is in mssql and msal4j drivers.

What I found about the problem on the Internet: 
https://github.com/microsoft/mssql-jdbc/issues/1707#issuecomment-994051827
https://github.com/Azure/azure-sdk-for-java/issues/26067#issuecomment-997012944

Maybe, you can try with downgraded mssql and msal4j drivers? You can check libraries compatibility [here](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/11.2.1.jre11) under `Compile Dependencies`

**Comment by geuss** [comment]
Hi Anastasiya, i tried and tried (at most with 20 combinations..)...
By now I'm using this combination of drivers version:

![image](https://github.com/dbeaver/dbeaver/assets/26387091/269a9d62-cb74-4a4a-9eff-894ad0363a64)

but I can't connect.... :-(
![image](https://github.com/dbeaver/dbeaver/assets/26387091/1d7e2216-a162-4f66-8bf0-e2a10956659e)

**Comment by LonwoLonwo** [comment]
Hello @geuss 

Please try this set of drivers: https://github.com/dbeaver/dbeaver/issues/19802#issuecomment-1569647746

**Comment by geuss** [comment]
Hello @LonwoLonwo 
Unfortunately it's doesn't works...

Driver configuration:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/e0a2b36b-508b-4179-83e2-ccf93d88952a)

Authentication MFA is good from browser:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/b357a635-e0e8-4902-908f-78dd2a75462f)

Connection Error on DBeaver::
![image](https://github.com/dbeaver/dbeaver/assets/26387091/d77055ae-080e-4b54-97f5-fa24350fff8e)

 
Log:
!ENTRY org.jkiss.dbeaver.model 4 0 2023-05-31 17:15:15.534
!MESSAGE java.net.SocketTimeoutException: Connect timed out
!STACK 0
java.lang.RuntimeException: java.net.SocketTimeoutException: Connect timed out
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:230)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenInteractive(SQLServerMSAL4JUtils.java:195)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5569)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5419)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5306)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:306)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:126)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6299)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4911)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4849)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:80)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:137)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1205)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1070)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:97)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

:-(

**Comment by Destrolaric** [comment]
@geuss 
Could you try checking login host availability via
`Test-NetConnection login.microsoftonline.com -p 443`
In powershell console

**Comment by geuss** [comment]
HI @Destrolaric , it works:

![image](https://github.com/dbeaver/dbeaver/assets/26387091/90e8314d-f5c5-42d1-86e6-8cb68558a522)

**Comment by LonwoLonwo** [comment]
Unfortunately, we do not have more ideas. I can suggest only trying the latest mssql driver and the latest msall4j library for it. 
I'm not sure that this is DBeaver's problem because other users can connect via MFA.

**Comment by ohadyana** [comment]
Hi,
We run into the same issue.
We suspect it is because we are connecting via "Express Route"
@geuss  - do you have this, too?

* if not sure, try resolving the db server url via nslookup. Inside your domain and outside. If the IP adresses don't match, the answer is yes.

**Comment by geuss** [comment]
Thanks ohadyana, I'm not a network expert ^_^' ,  I checked, but it seems there's no ExpressRoute configured on my infrastructure:
![image](https://github.com/dbeaver/dbeaver/assets/26387091/07fee7d7-f1fc-419d-ab67-40630d505676)

I tried to resolve fqdn address with nslookup:

Inside my domain (VPN):
![image](https://github.com/dbeaver/dbeaver/assets/26387091/22363624-2f84-4810-a403-aa2decf86e31)

Outside my domain (Internet):
![image](https://github.com/dbeaver/dbeaver/assets/26387091/27d3fbe6-d96f-412a-b828-1b0e56bfa0c8)

**Comment by Ocherts** [comment]
Hi, I a m a team mate of @ohadyana , I am the DBA,

I see a patern here.
Your case is diferent but has the same features.
The address in NSLOOKUP was resolved by your internal DNS. So the server FQDN you are using, is not resolved outside your domain.
In Azure, you may find a diferent server FQDN for your server. That address may work. Something like xxxx.database.windows.net try that connection instead (if the firewall rules will allow it)

**Comment by E1izabeth** [comment]
Currently it doesn't look like DBeaver issue.

**Comment by geuss** [comment]
I did it...
I added these lines to the Windows host file:

20.190.159.2 login.windows.net
20.190.159.73 login.microsoftonline.com

I got the IP addresses that resolve the aliases "login.windows.net" and "login.microsoftonline.com" outside the VPN.
These addresses were not resolved when my work VPN was connected...so it is mandatory to set them up.

I hope this can be useful to someone else...
