### ISSUE TITLE
Warning/error when selecting from certain tables ClassCastException Integer/Short

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#20075]
### Description

When running a simple select from a table, all columns are read only. Cannot edit data.
A warning appears to the bottom, containing a warning: 6 row(s) fetched - 6ms, on 2023-05-24 at 15:40:31 - 1 warning(s)

Stack trace:
java.lang.ClassCastException: class [Ljava.lang.Integer; cannot be cast to class [Ljava.lang.Short; ([Ljava.lang.Integer; and [Ljava.lang.Short; are in module java.base of loader 'bootstrap')
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.safeGetShortArray(PostgreUtils.java:929)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$ConstraintCache.fetchObjectRow(PostgreSchema.java:925)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$ConstraintCache.fetchObjectRow(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:360)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getTypedObjects(JDBCCompositeCache.java:128)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableReal.getConstraints(PostgreTableReal.java:209)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.getBestIdentifier(DBExecUtils.java:523)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.bindAttributes(DBExecUtils.java:860)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:165)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:845)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3873)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

23.0.5.202305211610

### Operating System

Linux Mint

### Database and driver

Postgres 10

### Steps to reproduce

![image](https://github.com/dbeaver/dbeaver/assets/19900533/c76839c6-cb44-4bf5-a87e-50a72ab0a6bf)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/c0e6dd26-db6b-49cc-bb6d-c145d00fd0ce)

**Comment by E1izabeth** [comment]
Thank you for bug report. Could you provide table DDL?

**Comment by alesc2000** [comment]
I get the same error when accessing DDL:
![image](https://github.com/dbeaver/dbeaver/assets/19900533/4bc4aa34-1f80-4ebc-b7a0-fb83d9a1a90b)

**Comment by alesc2000** [comment]
The table was created by the following statement:
```
CREATE TABLE app_config
(
  id integer NOT NULL DEFAULT nextval('app_config_id_seq'::regclass),
  key text,
  value text,
  CONSTRAINT app_config_pkey PRIMARY KEY (id),
  CONSTRAINT app_config_key_key UNIQUE (key)
)
WITH (
  OIDS=FALSE
);
```

**Comment by E1izabeth** [comment]
Thank you.

**Comment by ShadelessFox** [comment]
Hello @alesc2000,

What's your database version?

**Comment by alesc2000** [comment]
PostgreSQL 12.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit

but I get the same error on:

PostgreSQL 10.23 (Ubuntu 10.23-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

![image](https://github.com/dbeaver/dbeaver/assets/19900533/e0cfb683-b76e-4db4-bf13-60e1ac10cd85)

**Comment by alesc2000** [comment]
It worked just fine until I upgraded dBeaver to the current/final version

**Comment by alesc2000** [comment]
Using the same dBeaver version from Windows works fine!

**Comment by alesc2000** [comment]
More info: ALL postgres tables apper readonly. I rolled back to version 23.0.4 for now, to be able to use dBeaver.
Thanks.

**Comment by ShadelessFox** [comment]
Could you please execute the following query and tell me the data type of the resulting column?

```sql
SELECT conkey FROM pg_catalog.pg_constraint;
```

**Comment by alesc2000** [comment]
@ShadelessFox 
![image](https://github.com/dbeaver/dbeaver/assets/19900533/417afa16-6236-4780-9e5d-55f4bc2d659a)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/b5e1e6e3-16cb-4dd9-892e-d729ed2ba4c2)

**Comment by ShadelessFox** [comment]
Weird.

You said this only happens with certain tables, which might not be the case with the `pg_catalog` catalog.

Can you please take a look at the Query Manager, locate the exact **failing** query involving the `pg_constraint` table, execute it manually in the SQL editor, and check the data type of `conkey` column there?

**Comment by alesc2000** [comment]
@ShadelessFox I mentioned afterwards that all pg tables seem to be readonly (or columns locked).

![image](https://github.com/dbeaver/dbeaver/assets/19900533/67437992-06bf-47e4-85d9-37ffef5ca3e9)

There are 2 identical queries in QManager involving pg_constraint. I ran them each manually:
![image](https://github.com/dbeaver/dbeaver/assets/19900533/ac2cfdc9-1ab4-4342-8652-404e56cfd3a3)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/2d7b0f04-86fe-46c4-aa6f-d5f64c99cc69)

**Comment by ShadelessFox** [comment]
Thank you. I still don't see anything strange.

I'm not sure what's going on, and we can't do anything about it without the steps required to reproduce the issue.

**Comment by alesc2000** [comment]
@ShadelessFox  How can I help you reproduce the issue? 
There were 18 fixes/features added since previous version which worked. My guess is that my problem has to come from one of those code changes... or maybe is a different java version?
Can I help with more info about my system or dBeaver configs?

**Comment by ShadelessFox** [comment]
We are going to resolve this issue blindly. After that, we will publish an early access version you can try.

**Comment by alesc2000** [comment]
Thanks so much!

**Comment by alesc2000** [comment]
I downloaded the early access version and everything is fine now. Thanks!
