### ISSUE TITLE
Null pointer exception with BigQuery 

### ISSUE THREAD

**Issue by russell-magidson** [dbeaver/dbeaver#20145]
### Description

DBeaver v 23.0.5
Simba JDBC driver v1.3.2.1003

The following comes up within some (but not all) of the column values for all rows returned:
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [HY000]: [Simba][JDBC](11380) Null pointer exception.
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3873)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Simba][JDBC](11380) Null pointer exception.
Caused by: java.lang.NullPointerException

My sql is performing a data-comparison between two tables (I've removed my actual project/dataset names):
WITH
  old_table AS ( select * 
except ( insert_datetime) from `<bq project>.<dataset 1>.ps_tbl`
  ),
    new_table AS ( select * 
except ( insert_datetime) from `<bq project>.<dataset 2>.ps_tbl`
  ),
  rows_mismatched AS (
    SELECT 'old not in new' AS source, * FROM ( SELECT * FROM new_table EXCEPT DISTINCT SELECT * FROM old_table )
    UNION ALL
    SELECT 'new not in old' AS source, * FROM ( SELECT * FROM old_table EXCEPT DISTINCT SELECT * FROM new_table )
  )
SELECT distinct * FROM rows_mismatched 
order by emplid, gl_nbr, source

Adding a LIMIT 10000 (or 20000 or 30000) to the final select keeps away the errors but higher values (eg 40000) return with the error.

### DBeaver Version

Community edition 23.0.5

### Operating System

Windows 10 Pro v1909, OS 18363.418

### Database and driver

BigQuery with Simba JDBC driver v1.3.2.1003

### Steps to reproduce

Running the sql provided with and without the LIMIT 

This does not replicate easily as some of my tables work fine and others generate the error.
I've not yet tried to replicate this with any sample data

Adding the LIMIT does seem to remove the error

**Comment by russell-magidson** [comment]
Note that I'm not running any VPN but do have Zscaler enabled per corporate policy.

**Comment by russell-magidson** [comment]
Update: this is the error in one of the columns - something about "<parameter7>": 

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [HY000]: [Simba][JDBC](11380) Null pointer exception.
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3873)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Simba][JDBC](11380) Null pointer exception.
	at com.simba.googlebigquery.googlebigquery.dataengine.BQHTParser.getDataHTAPI(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQHTDataHandler.retrieveData(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQResultSet.getData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SForwardResultSet.getData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SForwardResultSet.getString(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getString(JDBCResultSetImpl.java:334)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:195)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	... 14 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "< parameter7>" is null
	... 22 more

**Comment by LonwoLonwo** [comment]
Hello @russell-magidson 

Please provide the whole log file. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by russell-magidson** [comment]
[dbeaver log 20230531_01.log](https://github.com/dbeaver/dbeaver/files/11614599/dbeaver.log.20230531_01.log)
[dbeaver debug log 20230531_01.log](https://github.com/dbeaver/dbeaver/files/11614600/dbeaver.debug.log.20230531_01.log)

**Comment by LonwoLonwo** [comment]
Could you please retry with the latest driver? 
You can download it here: https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.3.3.1004.zip

Then you need to open your connections settings.
Click on the "Driver settings"
Choose "Libraries"
Delete old jar file
Download a new jar file
Reconnect

![2023-05-17 12_15_09-Window](https://github.com/dbeaver/dbeaver/assets/45152336/a423c921-3bcb-44b4-8ecc-d4052b13f994)

**Comment by russell-magidson** [comment]
Yes that appears to have done the trick. Here I thought I was using the latest driver! 
Great work, thanks for the quick, precise resolution.
