### ISSUE TITLE
Exports all empty

### ISSUE THREAD

**Issue by jacobliu10** [dbeaver/dbeaver#20142]
### Description

All of my exports regardless of file type show up as blank files (0 KB) within file explorer. This was never an issue before and all the data being exported is clearly not blank.

### DBeaver Version

Community Edition 23.0.5

### Operating System

Windows 11

### Database and driver

Snowflake, JDBC Driver

### Steps to reproduce

1. Select any data
2. Press Export data
3. Choose CSV file type (although it doesn't matter which file type, same error), press next
4. Choose extract type: Single query, check select row count, fetch size 110000, press next
5. Choose formatting: <connection's default>, press next
6. Choose directory as downloads, press proceed
7. Check windows explorer in downloads folder - file exists but is 0 KB, empty when opened

**Comment by E1izabeth** [comment]
Could you provide a log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

**Comment by jacobliu10** [comment]
> Could you provide a log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/

[.metadata.zip](https://github.com/dbeaver/dbeaver/files/11604348/default.metadata.zip)

Hope this helps, and thanks in advance.

**Comment by E1izabeth** [comment]
Thanks.

**Comment by Matvey16** [comment]
@jacobliu10 Can you add a screenshot of the output settings tab for an export that fails like this?
Also it would be useful to know from where did you start the export (Navigator/Data editor/Sql editor)
Does it happen only with Snowflake tables and if yes, does it happen with every one of them?

**Comment by jacobliu10** [comment]
> @jacobliu10 Can you add a screenshot of the output settings tab for an export that fails like this? Also it would be useful to know from where did you start the export (Navigator/Data editor/Sql editor) Does it happen only with Snowflake tables and if yes, does it happen with every one of them?

<img width="752" alt="Screenshot 2023-06-01 071537" src="https://github.com/dbeaver/dbeaver/assets/117475765/461da960-bbdb-449a-b411-2d35841ab67b">
I started the export at the bottom tab, although I could also start it by right-clicking the data and it yields the same result.

 Here are the extraction, format, and output settings:
 
<img width="581" alt="image" src="https://github.com/dbeaver/dbeaver/assets/117475765/90a635e6-6f61-4e9b-9fff-51b6e377844d">
<img width="581" alt="image" src="https://github.com/dbeaver/dbeaver/assets/117475765/6c3cf5f6-f000-4872-829b-55af29bea8c5">
<img width="585" alt="image" src="https://github.com/dbeaver/dbeaver/assets/117475765/7bf80f0e-7513-4838-bef1-8ffcf1234b90">

It happens for all of my tables, including the snowflake tables and also PostgreSQL.

**Comment by arhayka** [comment]
@jacobliu10 Could you please see if this issue is reproducible in the new 23.1.0 version? https://dbeaver.io/download/

**Comment by jacobliu10** [comment]
> @jacobliu10 Could you please see if this issue is reproducible in the new 23.1.0 version? https://dbeaver.io/download/

yep, still the same issue :(

**Comment by ShadelessFox** [comment]
Hello @jacobliu10,

1. Does the export finish without any errors?
2. Try exporting data from the navigator tree. Click on a table there and select" Export data". Please let me know if it helps

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by msk-psp** [comment]
I had same experience with bulk load and single query extract type option. 

I was trying to export data about 2,800,000 rows at once with the bulk option. it's so fast that the export finished for about 3mins. but the table has no exported data. without error message

**Comment by msk-psp** [comment]
<img width="864" alt="Screenshot 2024-01-16 at 5 10 43 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/4537af95-d7e6-4a83-a2a3-c91433666a47">
<img width="255" alt="Screenshot 2024-01-16 at 5 11 10 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/a1e79365-e420-4ec5-a702-6972ddf79d68">


these are options I used to export with a export result message. there was no error message

**Comment by LonwoLonwo** [comment]
Hello @msk-psp 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by msk-psp** [comment]
```
2024-01-19 12:30:00.260 - Execution context opened (****; Data transfer producer; 17)
2024-01-19 12:30:00.261 - Initiate connection to PostgreSQL database [****@****] for Data transfer producer
2024-01-19 12:30:00.421 - Execution context opened (****; Data transfer consumer; 18)
2024-01-19 12:30:00.422 - Initiate connection to PostgreSQL database [****@****] for Data transfer consumer
2024-01-19 12:30:00.573 - Error while finishing result set fetch
org.jkiss.dbeaver.model.exec.DBCException: Error copying dataset on remote server
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:227)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:513)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:216)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:270)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:187)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.postgresql.util.PSQLException: ERROR: unterminated CSV quoted field
  Where: COPY *****, line 1: "627,"****","****","\\\","****","****","****..."
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1224)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1029)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:212)
	... 10 more

```


**I masked some information. **
Hello @LonwoLonwo thank you for your response. 

I conducted some tests after investigating the log. the problem was backslash "\\" character present in an arbitrary column.

I discovered that value of the arbitrary column contains this character. I tested with column containing "\\\\\\" value and data transfer didn't work

**Comment by LonwoLonwo** [comment]
What DBeaver version do you use @msk-psp ?

**Comment by LonwoLonwo** [comment]
Because it looks like this fixed case in 23.1.1 https://github.com/dbeaver/dbeaver/issues/19992
Disabling bulk loading can help, btw.

**Comment by msk-psp** [comment]
<img width="455" alt="Screenshot 2024-01-19 at 5 53 10 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/8c28438d-b704-430e-bddc-abc43389818e">

I'm currently using this DBeaver and yes , disabling bulk loading solve the issue

**Comment by LonwoLonwo** [comment]
Could you then provide a table DDL and data examples for tests?

**Comment by msk-psp** [comment]
### from table 

<img width="795" alt="Screenshot 2024-01-19 at 6 02 22 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/f9eb0aff-f16a-4bc8-8730-7ada6cb88c6a">

### to table
<img width="386" alt="Screenshot 2024-01-19 at 6 01 41 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/d12f7277-6cbd-45a8-9d87-6369b9540fd6">

```
-- public.test2 definition

-- Drop table


-- DROP TABLE public.test2;

CREATE TABLE public.test2 (
	test_id int4 NULL,
	title text NULL
);
```

```
test_id, title
627	Jacqueline au Bandeau de Face (Grand Tête de Femme)
627	Jacqueline au Bandeau de Face (Grand Tête de Femme) (Bloch 1069, Baer 1303)\
```

```
INSERT INTO public.test(test_id,title) VALUES
	 (627,'Jacqueline au Bandeau de Face (Grand Tête de Femme)'),
	 (627,'Jacqueline au Bandeau de Face (Grand Tête de Femme) (Bloch 1069, Baer 1303)\');
```
I've just tested with tables of simple version.  It's still not working

**Comment by msk-psp** [comment]
<img width="1140" alt="Screenshot 2024-01-19 at 6 04 43 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/51cedcfb-11b0-4b50-9a44-6e563b3f6e5c">

<img width="1361" alt="Screenshot 2024-01-19 at 6 05 19 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/5d2854c5-aa7e-4fde-8a32-5e87518c06b1">
<img width="1123" alt="Screenshot 2024-01-19 at 6 05 07 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/71d4d292-67da-4c49-b198-46a73b9db9a5">
<img width="1124" alt="Screenshot 2024-01-19 at 6 05 00 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/0f35d4e7-4ff5-4296-b3c4-2487686d5ea2">



<img width="2367" alt="Screenshot 2024-01-19 at 6 09 10 PM" src="https://github.com/dbeaver/dbeaver/assets/23733661/545bfe4c-b06d-4faf-9b6b-cdc9fd3ba674">

**Comment by uslss** [comment]
@msk-psp case fails with error below. Issue with CSV still not reproducible

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jan 30 17:22:29 CET 2024
ERROR: unterminated CSV quoted field
  Where: COPY test2-1, line 3: "627,"Jacqueline au Bandeau de Face (Grand Tête de Femme) (Bloch 1069, Baer 1303)\"
"

org.postgresql.util.PSQLException: ERROR: unterminated CSV quoted field
  Where: COPY test2-1, line 3: "627,"Jacqueline au Bandeau de Face (Grand Tête de Femme) (Bloch 1069, Baer 1303)\"
"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1264)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1069)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreCopyLoader.finishBulkLoad(PostgreCopyLoader.java:212)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:513)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:212)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:270)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:187)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by LonwoLonwo** [comment]
Thanks for the report @msk-psp
