### ISSUE TITLE
Using ODBC to Salesforce server returns duplicate records.

### ISSUE THREAD

**Issue by JungleMonkey** [dbeaver/dbeaver#20194]
### Description

Using DBeaver to connect to our Salesforce Server and running SELECT statements seems to result in every record that is returned is a duplicate of the first record.

The number of records shown is correct, just that they are all the same record.

I used Telerik Fiddler to inspect the traffic between the ODBC driver and Salesforce and can confirm that the data coming back from Salesforce to the ODBC driver is correct.

If I set up Excel to use the ODBC driver, all the records are correct so it looks like the ODBC driver is functioning correctly.

In this video you can see me doing a Query in DBeaver and inspecting the results that came back from Salesforce in Fiddler.

[DBeaver -> Salesforce Video Fiddler Results](https://screenrec.com/share/x3yfh8zvDE)

The log file shows the following error:

`
!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-06-04 11:11:47.497
!MESSAGE Command 'org.jkiss.dbeaver.ui.editors.sql.run.statement' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.jkiss.dbeaver.ui.editors.sql.run.statement': java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
    at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:303)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
    ... 32 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
    at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
    at java.base/java.lang.String.substring(Unknown Source)
    at org.jkiss.dbeaver.model.sql.SQLUtils.trimQueryStatement(SQLUtils.java:388)
    at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.extractActiveQuery(SQLScriptParser.java:683)
    at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.extractActiveQuery(SQLScriptParser.java:660)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.extractActiveQuery(SQLEditorBase.java:774)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2437)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2394)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:2390)
    at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerExecute.execute(SQLEditorHandlerExecute.java:68)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
    ... 36 more
`

### DBeaver Version

Community v23.0.5.202305211610

### Operating System

Windows 10

### Database and driver

Database: Salesforce.  Both test and production servers.

ODBC Driver: Devart ODBC Driver for Salesforce v3.02

### Steps to reproduce

Connect to Salesforce Server via ODBC.
Open a new Script tab.
Enter 'SELECT * FROM Contact' or even something simpler 'SELECT FirstName FROM Contact'
Press the 'Execute SQL Query' button

**Comment by JungleMonkey** [comment]
I just updated DBeaver to the latest version which came out today.  Apparently, you have removed ODBC from the community edition which is a real shame.

I downloaded the trial version of DBeaver Lite v23.0.0.  I'm not sure if I can afford to purchase this at the moment, but I can confirm that even with the new ODBC drivers in DBeaver Lite v23.0.0, I'm still experiencing the same issues with the first record being duplicated.

**Comment by serge-rider** [comment]
Which exactly ODBC driver do you use? (native, cdata, progress, etc). And which version?

Note: you still can use legacy odbc in the Community edition (https://dbeaver.com/docs/wiki/Deprecated-legacy-ODBC-driver/)

**Comment by JungleMonkey** [comment]
I used the Devart ODBC Driver for Salesforce v3.02

In DBeaver Community I created connections with 'ODBC - Legacy'.

In DBeaver Lite, I created connections with both 'ODBC - Legacy' and the one that just says 'ODBC'.

**Comment by LonwoLonwo** [comment]
I can reproduce it with Devart ODBC Driver. I will be looking into it.

**Comment by LonwoLonwo** [comment]
As a workaround - another JDBC driver shows data as expected.

![2023-06-08 19_27_01-DBeaver Ultimate 23 1 0 - Contact](https://github.com/dbeaver/dbeaver/assets/45152336/69694d47-781d-430e-bba9-4a67b294ff5a)

**Comment by quednu** [comment]
As the ticket is closed, will there be a bug fix for this issue?

**Comment by LonwoLonwo** [comment]
Hello @quednu 

The fix is already available for PRO versions in our Early Access versions: https://dbeaver.com/files/ea/

**Comment by quednu** [comment]
Ok, thanks @LonwoLonwo. Is it also planned to roll out this fix for EE and Lite Versions? 
EDIT: Question answered... thank you!
