### ISSUE TITLE
Grouping panel button "Show duplicates" doesn't work in Denodo

### ISSUE THREAD

**Issue by r4lex** [dbeaver/dbeaver#20206]
### Description

Very similar situation that I found it was reported for PostgreSQL a year ago, but not for Denodo:

Use Select in SQL Editor
Open Grouping panel
Drag one column in the Grouping panel
Enable "Show duplicates only" button

```
java.sql.SQLException: Error in group by having conditions: Field not found 'count_' in view with schema:
...
	at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.generateSQLException(DAOVDBProxy.java:497)
	at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.generateSQLException(DAOVDBProxy.java:496)
	at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.executeDeferred(DAOVDBProxy.java:479)
	at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.executeDeferred(DAOVDBProxy.java:401)
	at com.denodo.vdb.jdbcdriver.VDBJDBCStatement.execute(VDBJDBCStatement.java:186)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingDataContainer.readData(GroupingDataContainer.java:120)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### DBeaver Version

Community Edition 23.1.0

### Operating System

Windows 10

### Database and driver

Database: Denodo 8
Driver: Denodo 8 JBDC

### Steps to reproduce

Use Select in SQL Editor
Open Grouping panel
Drag one column in the Grouping panel
Enable "Show duplicates only" button

**Comment by LonwoLonwo** [comment]
Thanks for the report.

**Comment by LonwoLonwo** [comment]
The issue has been fixed and will be available in release 23.1.1.

Could you please check it in our [Early Access version](https://dbeaver.io/files/ea/)?

**Comment by r4lex** [comment]
It's working perfectly! Thank you!

**Comment by LonwoLonwo** [comment]
Thanks for the answer @r4lex !
