### ISSUE TITLE
Troubleshooting "NullPointerException" Error with Legacy JDBC-ODBC Driver

### ISSUE THREAD

**Issue by marcreig** [dbeaver/dbeaver#20320]
### Description

I am experiencing difficulties setting up an ODBC legacy connection in DBeaver on a newly deployed server. This server is an exact clone of another server where the connection is working flawlessly. Here are the details of the setup:

- Operating System: Windows Server 2019 Standard
- DB: 4D Tools environtment through 4D ODBC Driver v19.0
- Java: Latest version 1.8 (x86 and x64) installed from the official website (JRE)
- DBeaver: Version 23.0.5, which is the last version supporting the native creation of connections using the legacy driver. Installed as administrator with default settings, including the embedded Java in the installer
- Dependencies: Same dependencies installed on both servers
- ODBC driver: Same driver installed in the Windows manager, successfully connecting to the database.
- Visual Studio Tools: Same runtimes installed on both servers (2019, 2022, etc.). Runtimes installed "just-in-case", as in the working server those were the last things installed before it started working.

https://i.imgur.com/5flu6ra.png

Previously, I encountered a similar issue on the working server, and after multiple attempts, including installing and uninstalling various versions of Java (JDK, JRE), Visual Studio Tools, and more, it started working without any apparent reason. However, on the new server, even though it's a clone, I cannot achieve a successful connection.

Furthermore, I am aware that relying on the JDBC-ODBC legacy driver is no longer recommended due to its deprecation. **However, in this particular case, the use of the legacy driver is necessary**. The objective is to resolve the connection issue and explore alternative solutions or drivers in the future.

I would appreciate any ideas, suggestions, or troubleshooting steps to resolve this issue. I have exhausted my options and would like guidance on identifying the root cause and finding a solution to overcome the "NullPointerException" error and successfully establish the JDBC-ODBC legacy connection.

Thank you in advance for your support!

### DBeaver Version

23.0.5

### Operating System

Windows Server 2019 Standard

### Database and driver

4D Tools SQL
ODBC Driver v19.0
4D v19 ODBC Driver 64-bit 19.00.00.00 4D SAS
4DODBC.DLL

**Comment by ShadelessFox** [comment]
Hello @marcreig,

Have you tried using the modern ODBC driver available in PRO products? https://dbeaver.com/download/

**Comment by marcreig** [comment]
Good morning!

I've tried both, DBeaver Lite and EE, and both works nicely. So the new ODBC driver works with the 4D environement upon Windows Server 2019 Standard ODBC Data Source administrator.

It retireves all data, types and scripts results fearlessly. Happy with it.
But we wanted to avoid buying licenses and keep on the CE version.

Can't you make the new ODBC mantained driver CE? To open it?

The only problem with this new site is retreiving information with date/hour fields, which got broken:

https://i.imgur.com/iwgYHuU.png

`org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Can't determine Java type for SQL type 11
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:139)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:828)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:924)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3895)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.dbeaver.jdbc.odbc.bridge.util.OdbcException: Can't determine Java type for SQL type 11
	at com.dbeaver.jdbc.odbc.JdbcOdbcResultSet.getObject(JdbcOdbcResultSet.java:365)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:627)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:103)
	... 14 more
`

Data types:

https://i.imgur.com/pHzYCNx.png

https://i.imgur.com/9YZOIzI.png

any ideas?
In CE works nicely, with no errors (remember I've a CE working on a "clone" development machine... which is what I don't understand at all...)

Thanks alot.

**Comment by marcreig** [comment]
I've tried now, instead of selecting an existing Windows ODBC Administrator functioning conection, to create a manual one with the new driver, amd it works too.

The good thing is that it resolves the problem with the DATES, but no HOURS:

https://i.imgur.com/lBdWamS.png

so looks like it's partially related on connection data interpretation through JDBC.

**Comment by ShadelessFox** [comment]
Hello again,

Thanks for the provided information and bug reports.

As of now, we're not going to release the new driver in CE in the near future. Things might change eventually, but unlikely.

**Comment by marcreig** [comment]
Hi, good afternoon.
Ok, so I've bought a EE license to move on, and see how everything responses, and from this, we will see if we move forward or what.

Are you going to solve the errors? DATA and HOUR types from screens?
Do you know where the problem can be? If it's useful, the old JDBC legacy driver was fully functionable. Some times crashed when a lot of data was retireved. But the types came clean. Sometimes something similar happened, but you closed DBeaver and on fresh retart, everything was good back again.

Thanks.

**Comment by ShadelessFox** [comment]
Thank you!

Yes, we know where to dig and will fix the issues mentioned.

**Comment by marcreig** [comment]
Good morning everyone, just want to leave the comment about I've upgraded version this morning and issue was resolved! Thanks for your fine hands people.

Cheers.
