### ISSUE TITLE
'Generating DDL' has encountered a problem (when generating DDL of external table in SQL server)

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#20350]
### Description

I get this error message when I try to generate the DDL for an external table:

```
'Generating DDL' has encountered a problem 

Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "string" is null
Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "string" is null
```

![image](https://github.com/dbeaver/dbeaver/assets/16278437/79d118b0-2b07-478a-bb97-13a5955427ec)

### DBeaver Version

Version 23.1.0.202306041918

### Operating System

Win 10

### Database and driver

Azure SQL

### Steps to reproduce

- Right click an external table in the tree view
- Select Generate SQL => DDL
- Error message pops up.

**Comment by E1izabeth** [comment]
Please, provide log files. You can find instructions here https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by JoseArgueta** [comment]
Hi, Could you reopen this bug? I have the same issue

DBeaver Version = Version 25.2.5
Operating System = Win 11
Database and driver = Azure SQL 12, mssql-jdbc-13.2.1.jre11.jar

`!ENTRY org.jkiss.dbeaver.ui.editors.sql 4 0 2026-04-16 10:20:54.271 !MESSAGE Error running DDL generation !STACK 0 org.jkiss.dbeaver.DBDatabaseException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "string" is null at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:253) at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorDialog$1.run(SQLGeneratorDialog.java:129) at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) Caused by: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "string" is null at org.jkiss.dbeaver.model.impl.sql.BasicSQLDialect.escapeString(BasicSQLDialect.java:220) at org.jkiss.dbeaver.model.impl.sql.AbstractSQLDialect.getQuotedString(AbstractSQLDialect.java:546) at org.jkiss.dbeaver.ext.mssql.model.SQLServerDialect.getQuotedString(SQLServerDialect.java:313) at org.jkiss.dbeaver.model.sql.SQLUtils.quoteString(SQLUtils.java:315) at org.jkiss.dbeaver.model.sql.SQLUtils.quoteString(SQLUtils.java:310) at org.jkiss.dbeaver.ext.mssql.edit.SQLServerExternalTableManager.appendTableModifiers(SQLServerExternalTableManager.java:70) at org.jkiss.dbeaver.ext.mssql.edit.SQLServerExternalTableManager.appendTableModifiers(SQLServerExternalTableManager.java:1) at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.addStructObjectCreateActions(SQLTableManager.java:169) at org.jkiss.dbeaver.model.impl.sql.edit.SQLStructEditor$StructCreateCommand.getPersistActions(SQLStructEditor.java:168) at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.getTableDDL(SQLTableManager.java:352) at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableDDL(DBStructUtils.java:106) at org.jkiss.dbeaver.ext.mssql.model.SQLServerExternalTable.getObjectDefinitionText(SQLServerExternalTable.java:129) at org.jkiss.dbeaver.model.struct.DBStructUtils.getTableDDL(DBStructUtils.java:133) at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableListDDL(DBStructUtils.java:157) at org.jkiss.dbeaver.model.sql.generator.SQLGeneratorDDL.run(SQLGeneratorDDL.java:65) at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorDialog$1.lambda$0(SQLGeneratorDialog.java:130) at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189) ... 3 more`

**Comment by E1izabeth** [comment]
@JoseArgueta thanks
