### ISSUE TITLE
"error while loading shared libraries: libedit.so.0" when trying to restore database

### ISSUE THREAD

**Issue by matiac** [dbeaver/dbeaver#20371]
### Description

I can make a database dump, however I'm not able to restore it later.

Log:
```
/run/user/1000/doc/ffddf574/bin/mysql -u root --host=172.18.0.3 --port=3306 whatever_db
Task 'MySQL restore' started at Fri Jun 23 12:40:03 CLT 2023
/run/user/1000/doc/ffddf574/bin/mysql: error while loading shared libraries: libedit.so.0: cannot open shared object file: No such file or directory

Task 'MySQL restore' finished at Fri Jun 23 12:40:03 CLT 2023
2023-06-23 12:40:03.941 - IO error: Process failed (exit code = 127). See error log.
2023-06-23 12:40:03.941 - java.io.IOException: Process failed (exit code = 127). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**libedit.so.0** is found in various paths in the system. I installed **Flatseal** and under **Filesystem** I enabled _All system libraries, executables and static data_ to no effect.

### DBeaver Version

Community Edition 23.1.0

### Operating System

Fedora 38

### Database and driver

- Database name and version: MariaDB 10.11.3
- Driver name and version: MariaDB JDBC driver 3.1.4

### Steps to reproduce

1. Right click on a database and select **Tools** -> **Restore database**.
2. Load a SQL dump file and click **Start**.

### Additional context

- Installed MariaDB client for DBeaver Community.
- MariaDB is running on a Docker container.
- libedit.so.0 is present at:
    - `/home/matiac/.local/share/containers/storage/overlay/825272b502f7576c113ff02fa772a96ee8c17e2a5ed73ab10b764272c8acdb3e/diff/usr/lib/libedit.so.0`
    - `/var/lib64/libedit.so.0`
    - `/var/lib/flatpak/runtime/org.fedoraproject.Platform/x86_64/f38/ff055122106a07740056f015bd74ba8f4b371cb85b5cfe1583ed6ea739bda35f/files/lib64/libedit.so.0`
    - `/var/lib/docker/overlay2/f944712bca538f1fd1b3fbbeb9dcdaf8bdfac27584ff03584b88e5f82d5f2d21/diff/usr/lib/libedit.so.0`
    - `/var/lib/docker/overlay2/5fc2885fffc7f6a7a208365ed218a067f5ac4c9a8ea2ebde8ee99c74bb71066c/merged/usr/lib/libedit.so.0`

**Comment by lorexp** [comment]
hello @matiac, i had the same problem with flatpak edition, so i installed the .rpm and it works fine.

**Comment by matiac** [comment]
:o thanks @lorexp, it worked for me too!

**Comment by mbnoimi** [comment]
Same issue occurs with me under Linux Mint 21.2 Flatpak Version `23.1.5.202308201919` although I gave DBeaver permissions more than usual!

```ini
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=dri;
features=devel;
filesystems=home;/home/admino/.themes;host-os;/usr/share/themes;/home/admino/Downloads;

[Session Bus Policy]
org.freedesktop.Notifications=talk
org.freedesktop.FileManager1=talk

[Environment]
GTK_THEME=Mint-Y-Dark-Aqua
PATH=/app/clients/bin:/app/jre/bin:/usr/bin
QT_STYLE_OVERRIDE=Adwaita-dark
```

**Comment by Matvey16** [comment]
Thank you for the report

**Comment by aliasbody** [comment]
This issue is quite old. But I found a solution:
1 - I've opened a pull request https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.mariadb/pull/4 for an updated mariadb (I will try to do the same for pgsql) extension for dbeaver, once it's available install it
2 - You need to follow the part from https://github.com/dbeaver/dbeaver/issues/5008#issuecomment-1928038064 where the "drivers.xml" file is edited and set this: 
`<clientHome id="/app/clients/bin" path="/app/clients/bin"/>`

This will work and you'll have a working mariadb install (if you want you can set the ID to MariaDB to separate from any other extension in the menu, like this <clientHome id="MariaDB" path="/app/clients/bin"/>)

There is a need to find a way to easily add this, maybe by taking with the DBeaver team themselves.

**Comment by aliasbody** [comment]
I've just done a PR for pgsql 16.2, waiting to be approved and merged: https://github.com/flathub/io.dbeaver.DBeaverCommunity.Client.pgsql/pull/8

**Comment by wonka929** [comment]
@aliasbody i did almost all the things proposed in the highlighted comment.
I'm still missing libedit.so.
Flatpak installation

**Comment by tomastan** [comment]
Using 26.0.1 Flatpak. Still the same issue
