### ISSUE TITLE
Error refreshing node

### ISSUE THREAD

**Issue by Ruslan-Shevyrev** [dbeaver/dbeaver#20393]
### Description

I am getting error after updating tables 

Error refreshing node

Reason:
Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null

### DBeaver Version

Community Edition 23.1.1.2

### Operating System

Windows 10

### Database and driver

Database: Any

### Steps to reproduce

1. Try to refresh Table (F5)
2. I get an error

Error refreshing node

Reason:
Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null

**Comment by Ruslan-Shevyrev** [comment]
<img width="831" alt="test" src="https://github.com/dbeaver/dbeaver/assets/101332438/e81adb8c-0fe8-48ed-b9ad-175b3db3c411">

**Comment by Ruslan-Shevyrev** [comment]
This issue is not reproducible in version 23.1.0 only in 23.1.1

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/

**Comment by E1izabeth** [comment]
Never mind, I reproduced the issue. Thank you for bug report.
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null
	at org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical.refreshObject(OracleTablePhysical.java:197)
	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.refreshObject(OracleTable.java:358)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:358)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:356)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:189)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Ruslan-Shevyrev** [comment]
Thank you for operating answer!

**Comment by E1izabeth** [comment]
@Ruslan-Shevyrev the fix is available in the early access version https://dbeaver.io/files/ea/
