### ISSUE TITLE
Unable to connect to Oracle XE 21c database in some instances

### ISSUE THREAD

**Issue by pmulgaonkar** [dbeaver/dbeaver#20404]
### Description

We have an application which we install with an Oracle XE 21c database. We have created multiple instances of our application and can connect to the DB over SSH using keys usually with no issues.

However, on some appliance installations, doing a TEST CONNECTION we get: 
```
IO Error: Got minus one from a read call, connect lapse 583 ms., Authentication lapse 0 ms.
```
This seems to affect some of our appliance installations and not others. We are having a tough time figuring our what is causing this issue. SSH connection/connection test succeeds with no issues. Logging in over ssh and doing sqlplus works with the same user id used for the DBeaver connection.

![image](https://github.com/dbeaver/dbeaver/assets/5150672/b1e5c1de-7d29-41dc-a7ee-3db7709ef994)
  
The log file from DBeaver has this:
```
log:
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jun 27 15:20:19 PDT 2023
Got minus one from a read call

oracle.net.ns.NetException: Got minus one from a read call
	at oracle.net.ns.NIOHeader.readHeaderBuffer(NIOHeader.java:100)
	at oracle.net.ns.NIOPacket.readNIOPacket(NIOPacket.java:252)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:118)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:212)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:225)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:244)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:91)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:147)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1191)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

For reference, the DB is running on an Alma Linux 8 server. Disabling SELinux does not have any effect. Cannot determine if there is a permission error difference in any of the files we have looked at between the appliances where it works and where it does not. 

### DBeaver Version

Version 23.0.2.202304091457

### Operating System

Ubuntu 20.04

### Database and driver

Database Oracle XE 21c
Driver from DBeaver:  java-11-oracle/db

**Comment by E1izabeth** [comment]
It doesn't looks like DBeaver issue.
Probably some answers from this question might help you https://stackoverflow.com/questions/19660336/how-to-approach-a-got-minus-one-from-a-read-call-error-when-connecting-to-an-a
