### ISSUE TITLE
Fetching table detail (F4) error since V23.1.1

### ISSUE THREAD

**Issue by dnroldanforwork** [dbeaver/dbeaver#20426]
### Description

Hi,

since V23.1.1 when I am trying to open table detail pushing F4 key over de table name or by schema navigation and I am getting this error "Can't find metadata for name 'TableName'".

With V23.1.0 and earlier it's working perfectly

This is the error trace obtained by log:

!ENTRY org.jkiss.dbeaver.model 2 0 2023-06-29 10:17:20.111
!MESSAGE Can't set session optimizer parameters
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2023-06-29 10:17:20.111
!MESSAGE Error : 1031, Position : 0, Sql = ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE, OriginalSql = ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE, Error Msg = ORA-01031: privilegios insuficientes

!STACK 0
Error : 1031, Position : 0, Sql = ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE, OriginalSql = ALTER SESSION SET "_optimizer_push_pred_cost_based" = FALSE, Error Msg = ORA-01031: privilegios insuficientes

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:636)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1150)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:770)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:497)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:151)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1051)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1530)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1310)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3745)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3940)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1009)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeSQL(JDBCUtils.java:569)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContextState(OracleDataSource.java:337)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:162)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMetaContext(JDBCRemoteInstance.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:491)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initialize(OracleDataSource.java:500)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1217)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1076)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:260)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:172)
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Thanks in advance!

### DBeaver Version

23.1.1

### Operating System

Windows 11

### Database and driver

Oracle autonomous 19c
Driver: ojdbc8-21.7.0.0.jar

### Steps to reproduce

I am connected to de Database and when I push F4 on a specific table I get an error instead of showing popup with the detailed info of the table.

**Comment by E1izabeth** [comment]
Please try turning off this setting
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5389658f-404d-424c-ba6f-4a8d7cc50802)

**Comment by dnroldanforwork** [comment]
Hi,

thans for your fasting reply.


After applying the modification you suggested me, I get this error:
" Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null

This is the log trace:

!ENTRY org.jkiss.dbeaver.model 4 0 2023-06-30 12:37:52.639
!MESSAGE Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical$PartitionCache.clearCache()" because "this.partitionCache" is null
	at org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical.refreshObject(OracleTablePhysical.java:197)
	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.refreshObject(OracleTable.java:358)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:358)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:356)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectOpen.lambda$0(NavigatorHandlerObjectOpen.java:278)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Thanks again!

**Comment by E1izabeth** [comment]
It's a known issue #20393
The fix will be available in the next release. Additionally, I'll send you an early access version with fixed bug within a couple of hours.

**Comment by E1izabeth** [comment]
You can download our early access version here https://dbeaver.io/files/ea/
Please, let me know if it helps.

**Comment by dnroldanforwork** [comment]
Ok, thanks so much @E1izabeth !

I can wait to the next release because I can work with previous version.
I will test the next stable release and if you want, I will post here if works.

**Comment by E1izabeth** [comment]
Yes, please give the feedback after you try the new release.

**Comment by dnroldanforwork** [comment]
Good morning,

I am pleased to inform you that the functionality is currently working flawlessly.

Thank you very much.

Best regards.
