### ISSUE TITLE
opengauss jsonb type error

### ISSUE THREAD

**Issue by noters** [dbeaver/dbeaver#20489]
### Description

2023-07-06 11:27:07.582 - Can't read column 'geom_json' value
org.jkiss.dbeaver.model.exec.DBCException: Error converting string to composite type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:201)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Composite type 'jsonb' has no attributes
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:184)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:107)
	... 10 more

### DBeaver Version

dbeaver-ce-23.1.1

### Operating System

windows10

### Database and driver

opengauss 3.0.0

**Comment by LonwoLonwo** [comment]
Hello @noters 

Partially this issue was discussed here: https://github.com/dbeaver/dbeaver/issues/20053.

Could you please provide a screen from the "Test connection" button result from your connection page?

Example:

![2023-07-06 13_47_25-Connection _postgres_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/132a5822-e449-489e-add6-1b2dad01e087)

**Comment by noters** [comment]
PostgreSQL 9.2.4
(openGauss 3.0.0 build 02c14696) compiled at 2022-04-01 18:12:34 commit 0 last mr   on x86_64-unknown-linux-gnu, compiled by g++ (GCC) 7.3.0, 64-bit

**Comment by noters** [comment]
Server: PostgreSQL 9.2.4
(openGauss 3.0.0 build 02c14696) compiled at 2022-04-01 18:12:34 commit 0 last mr   on x86_64-unknown-linux-gnu, compiled by g++ (GCC) 7.3.0, 64-bit

Driver: PostgreSQL JDBC Driver 42.5.2

**Comment by LonwoLonwo** [comment]
Thanks for the report @noters 

I can reproduce it.
