### ISSUE TITLE
bind issue to extract DDL from DB2 11.5, but only for tables

### ISSUE THREAD

**Issue by mahnya** [dbeaver/dbeaver#20510]
### Description

Hello.
I'm using dbeaver Version 23.1.1.202306251800 and I'm having an issue to extract the ddls of the tables of a database (I tried to extract the DDLs of views and other objects, and it works).

The error message I'm getting is this one:

Error running DDL generation
SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=*RATE_DDL;;SQL0001 Reason code or token: ......../sqllib/bnd/db2, DRIVER=4.11.77

If I login to the server and try to extract the ddls, it works (so it is not a userid permission issue). Seems to me that the issue is on dbeaver.

Is there a way to check how can I run this bind and why it happens only to tables?

### DBeaver Version

Coomunity Edition v23.1.1.202306251800

### Operating System

windows 11

### Database and driver

Database: DB2 v11.5.8
Driver: com.ibm.db2.jcc.DB2Driver

### Steps to reproduce

1.Open the Database lateral toolbar
2. Choose any table to extract the DDL
3. Go to 'Generate SQL'--> 'DDL' (all the other options generates the SQLs)

Then I get the following error message:
Error running DDL generation
SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=*RATE_DDL;;SQL0001 Reason code or token: /home/instance/sqllib/bnd/db2, DRIVER=4.11.77

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/19905

**Comment by mahnya** [comment]
It is not a driver issue.
If it was, I wouldn't be getting to extract other objects' DDLs

**Comment by mahnya** [comment]
Since db2 uses db2look to extract the DDLs, once you have the permission to run the db2look, it doens't restrict per object

**Comment by mahnya** [comment]
if it was a driver issue, would the driver filter per object?

**Comment by LonwoLonwo** [comment]
Hello @mahnya 

Let's get table DDL manually in the SQL Editor. We may find errors during this process.

Step 1.

Execute this query in your SQL Editor in DBeaver for your DB2 connection:

```sql
CALL SYSPROC.DB2LK_GENERATE_DDL('-e -x -xd -td -t <your_schema_name>.<your_table_name>',?)
```

Do not forget to use your schema and table name.
The result from this query (a number), please use in this query:
   
```sql
SELECT SQL_STMT FROM SYSTOOLS.DB2LOOK_INFO WHERE OP_TOKEN = <result_number> ORDER BY OP_SEQUENCE WITH UR
```

Could you see the result of this query? Does it contain your table DDL?

**Comment by mahnya** [comment]
Hello.

I tried to run the call command, but it didn't work.

Below I am attaching a successful select to a table (so the object exists) and the error message I got while trying to get the DDL:

![DBeaver_DDL1](https://github.com/dbeaver/dbeaver/assets/132909582/865e40e3-73cb-45fb-83b2-c42295ed4279)


![DBeaver_DDL2](https://github.com/dbeaver/dbeaver/assets/132909582/a43baf78-ed58-41d3-9a54-c6b5a1276271)


These are the Details: 

> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=SYSPROC.DB2LK_GENERATE_DDL;DB2LK_GENERATE_DDL;Invalid input provided, DRIVER=4.11.77
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:339)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3919)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=SYSPROC.DB2LK_GENERATE_DDL;DB2LK_GENERATE_DDL;Invalid input provided, DRIVER=4.11.77
	at com.ibm.db2.jcc.am.gd.a(gd.java:679)
	at com.ibm.db2.jcc.am.gd.a(gd.java:60)
	at com.ibm.db2.jcc.am.gd.a(gd.java:127)
	at com.ibm.db2.jcc.am.jn.b(jn.java:2230)
	at com.ibm.db2.jcc.am.jn.c(jn.java:2213)
	at com.ibm.db2.jcc.t4.cb.k(cb.java:369)
	at com.ibm.db2.jcc.t4.cb.e(cb.java:97)
	at com.ibm.db2.jcc.t4.q.e(q.java:81)
	at com.ibm.db2.jcc.t4.rb.k(rb.java:160)
	at com.ibm.db2.jcc.am.jn.lb(jn.java:2179)
	at com.ibm.db2.jcc.am.kn.b(kn.java:3920)
	at com.ibm.db2.jcc.am.ln.ic(ln.java:117)
	at com.ibm.db2.jcc.am.ln.execute(ln.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 13 more

And this is the error log view:

![DBeaver_DDL3](https://github.com/dbeaver/dbeaver/assets/132909582/314ecf06-1684-4b46-b3aa-b3459e66c5f2)



Meanwhile, I was also searching for possible solutions and I tried this one (https://github.com/dbeaver/dbeaver/issues/14429), but even after running the grants, I still couldn't get the tables' DDLs (though I continue to get to extract the views' DDLs)

**Comment by LonwoLonwo** [comment]
Could you please try to remove/change parameters in this query and look at the result?

```sql
CALL SYSPROC.DB2LK_GENERATE_DDL('-t <your_schema_name>.<your_table_name>',?)
```

And did you try these grants also?

```sql
grant usage on sequence SYSTOOLS.DB2LOOK_TOKEN to user your-authid;
grant select, update, delete, insert on table SYSTOOLS.DB2LOOK_INFO to user your-authid ;
grant select on table SYSTOOLS.DB2LOOK_INFO_V to user your-authid ;
```

**Comment by LonwoLonwo** [comment]
https://www.ibm.com/docs/en/db2woc?topic=SS6NHC/com.ibm.swg.im.dashdb.admin.cmd.doc/doc/r0002051.htm

**Comment by mahnya** [comment]
Hello.

I ran the 'CALL...' as requested. It didn't work.
Then I ran the grants to my user (instead of my group), and then the error message to the Call command changed:

_Cannot invoke "org.jkiss.dbeaver.ext.db2.model.DB2DataType.getDataKind()" because "this.dataType" is null_

![image](https://github.com/dbeaver/dbeaver/assets/132909582/76a693df-82be-4c03-b6ff-a4ea4d552eba)

**Comment by LonwoLonwo** [comment]
Did you try to reconnect after granting? And restart DBeaver?

**Comment by mahnya** [comment]
Hi!
I restarted dbeaver, refreshed the connection, and the error message I got was the same as the first one:
`org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [38553]: DB2 SQL Error: SQLCODE=-443, SQLSTATE=38553, SQLERRMC=*RATE_DDL;;SQL0001 Reason code or token: /home/instance/sqllib/bnd/db2, DRIVER=4.11.77`

**Comment by LonwoLonwo** [comment]
If you still can not execute 

`CALL SYSPROC.DB2LK_GENERATE_DDL('-t <your_schema_name>.<your_table_name>',?)`

Then I do not know how I can help here. This is a database limitation.

Maybe we need to catch exceptions here and return general table DDL, as we do for PostgreSQL or Generic bundle.

**Comment by mahnya** [comment]
hello.
 Should I do something related to "catch exceptions here and return general table DDL, as we do for PostgreSQL or Generic bundle"?

**Comment by LonwoLonwo** [comment]
Nope. It is a tip for development.
