### ISSUE TITLE
Prohibited character crashes postgres driver

### ISSUE THREAD

**Issue by pablojvarela** [dbeaver/dbeaver#20577]
### Description

Trying to connect to a PostgreSQL database, I get the following error message.

![image](https://github.com/dbeaver/dbeaver/assets/2119094/eca4d40f-f492-49bf-a3c4-ab9fb5339b67)

"Something unusual has occurred to cause the driver to fail. Please report this exception."

## Event details:
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Jul 14 15:39:07 ART 2023
Prohibited character

java.lang.IllegalArgumentException: Prohibited character 

	at org.postgresql.shaded.com.ongres.saslprep.SaslPrep.saslPrep(SaslPrep.java:105)
	at org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations$2.doNormalize(StringPreparations.java:55)
	at org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations.normalize(StringPreparations.java:65)
	at org.postgresql.shaded.com.ongres.scram.common.ScramMechanisms.saltedPassword(ScramMechanisms.java:152)
	at org.postgresql.shaded.com.ongres.scram.common.ScramFunctions.saltedPassword(ScramFunctions.java:59)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:196)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:163)
	at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ServerFirstProcessor.clientFinalProcessor(ScramSession.java:130)
	at org.postgresql.jre7.sasl.ScramAuthenticator.processServerFirstMessage(ScramAuthenticator.java:147)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:863)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
	at java.base/java.lang.Thread.run(Unknown Source)

### DBeaver Version

Community Edition 23.1.2

### Operating System

Linux 5.19.0-46-generic #47~22.04.1-Ubuntu 

### Database and driver

PostgreSQL 42.5.2
Postgis JDBC 2.5.0

### Steps to reproduce

1. Fresh install dbveaver using snap (sudo snap install dbeaver-ce)
2. create new postregsql connection
3. accept installation of needed drivers
4. error occurs.

### Additional context

No tunnels, or SSH activated.
No plugins or addons installed.

**Comment by LonwoLonwo** [comment]
Hello @pablojvarela 

What authentication type do you use for PostgreSQL connection? Password? Do you have special symbols in it?

**Comment by pablojvarela** [comment]
`Authentication: Database Native`

There is one non-alphanumerical character set in the database password.

**Comment by LonwoLonwo** [comment]
Can you connect to your database in DBeaver via the command line? https://github.com/dbeaver/dbeaver/wiki/Command-Line#connection-parameters

Or can you connect to the database with this password in other GUI tools?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by marcinkubica** [comment]
@E1izabeth I've run into the same issue and I possibly found the problem (maybe).

It started to happen when I used to copy-paste existing connection and modify user/pass. Then I had `Prohibited character` error.

But also when modifying further it (changed hostname + db name back and forth) it borked on the database name on the 2nd change. Maybe there's this connection copy-paste problem. When I've created connection from the scratch with the same password failing it worked fine.
![image](https://github.com/dbeaver/dbeaver/assets/1593987/a5b5ddf0-9d35-48ee-b380-6fa1ab1f0df5)

**Comment by E1izabeth** [comment]
@marcinkubica 
Thank you, we will investigate the issue

**Comment by Destrolaric** [comment]
@marcinkubica Hi, are there any non-alphanumerical symbols in the database name?

**Comment by SilverMaster-GT** [comment]
@pablojvarela 

Today I encountered the same error. While searching, I came across this information, but unfortunately, there was no solution. I tried using another database manager, and it didn't throw an error. However, I recalled that the source of my password sometimes adds extra spaces at the beginning or end, similar to when you type alt+0160. I then copied the password, pasted it into VIM, and to my surprise, it contained those extra characters that shouldn't be there. I cleaned up the password according to the correct format, pasted it again, and it worked!

I hope it works for you; apparently, if there are characters with spaces in the password, it triggers that error.

In case you're wondering, I tried again without cleaning the password, and it gave me the same error.
![image](https://github.com/dbeaver/dbeaver/assets/57964012/6953413b-25a4-433d-8386-5407dfc24d0d)

**Comment by arhayka** [comment]
Thank you for the idea!
We decided to add a warning about end spaces  or special whitespace Unicode symbols in username/passwords

**Comment by pablojvarela** [comment]
Hi all,
Many thanks for the support.
I haven't been able to follow since I don't have access to the DB that
caused the problem.

It'll help in the future to have the password warning.

Best,
Pablo

**Comment by marcinkubica** [comment]
> @marcinkubica Hi, are there any non-alphanumerical symbols in the database name?

nope
