### ISSUE TITLE
Teradata connectivity error

### ISSUE THREAD

**Issue by nponnapalli-godaddy** [dbeaver/dbeaver#20581]
### Description

I am having issues connecting to teradata. 

[Teradata JDBC Driver] [TeraJDBC 20.00.00.11] [Error 1014] [SQLState HY000] TeraEncrypt: Error tdgss-stack-trace-begin>>> GSSException: Failure unspecified at GSS-API level (Mechanism level: [TDGSS_ERR_ALL_MECHANISMS_FAILED] All mechanisms failed during credential creation.)
	at com.teradata.tdgss.jtdgss.TdgssCredential.<init>(TdgssCredential.java:120)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:229)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:195)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.initEncrypt(GenericTeraEncrypt.java:326)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.useAuthMech(GenericTeraEncrypt.java:133)
	at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:335)
	at com.teradata.jdbc.jdbc.GenericTeradataConnection.<init>(GenericTeradataConnection.java:343)
	at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:180)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:63)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:53)
	at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:231)
	at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.teradata.model.TeradataMetaModel.createDataSourceImpl(TeradataMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1210)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1076)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2530)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 <<<end-tdgss-stack-trace
[Teradata JDBC Driver] [TeraJDBC 20.00.00.11] [Error 1014] [SQLState HY000] TeraEncrypt: Error tdgss-stack-trace-begin>>> GSSException: Failure unspecified at GSS-API level (Mechanism level: [TDGSS_ERR_ALL_MECHANISMS_FAILED] All mechanisms failed during credential creation.)
	at com.teradata.tdgss.jtdgss.TdgssCredential.<init>(TdgssCredential.java:120)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:229)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:195)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.initEncrypt(GenericTeraEncrypt.java:326)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.useAuthMech(GenericTeraEncrypt.java:133)
	at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:335)
	at com.teradata.jdbc.jdbc.GenericTeradataConnection.<init>(GenericTeradataConnection.java:343)
	at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:180)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:63)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:53)
	at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:231)
	at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.teradata.model.TeradataMetaModel.createDataSourceImpl(TeradataMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1210)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1076)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2530)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 <<<end-tdgss-stack-trace

### DBeaver Version

Version 23.1.2.202307091549

### Operating System

macOS Ventura 13.4.1 (22F62)

### Database and driver

Teradata

### Steps to reproduce

1. I was trying to connect tedata with below configuration
2.Connection configuration:  jdbc:teradaåta://myServer.int.MyServer.com/DATABASE=myWarehouse,DBS_PORT=1025,TMODE=TERA,LOGMECH=LDAP
3. Dbeaver is throwing below error message:
[Teradata JDBC Driver] [TeraJDBC 20.00.00.11] [Error 1014] [SQLState HY000] TeraEncrypt: Error tdgss-stack-trace-begin>>> GSSException: Failure unspecified at GSS-API level (Mechanism level: [TDGSS_ERR_ALL_MECHANISMS_FAILED] All mechanisms failed during credential creation.)
	at com.teradata.tdgss.jtdgss.TdgssCredential.<init>(TdgssCredential.java:120)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:229)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:195)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.initEncrypt(GenericTeraEncrypt.java:326)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.useAuthMech(GenericTeraEncrypt.java:133)
	at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:335)
	at com.teradata.jdbc.jdbc.GenericTeradataConnection.<init>(GenericTeradataConnection.java:343)
	at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:180)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:63)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:53)
	at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:231)
	at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.teradata.model.TeradataMetaModel.createDataSourceImpl(TeradataMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1210)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1076)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2530)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 <<<end-tdgss-stack-trace
[Teradata JDBC Driver] [TeraJDBC 20.00.00.11] [Error 1014] [SQLState HY000] TeraEncrypt: Error tdgss-stack-trace-begin>>> GSSException: Failure unspecified at GSS-API level (Mechanism level: [TDGSS_ERR_ALL_MECHANISMS_FAILED] All mechanisms failed during credential creation.)
	at com.teradata.tdgss.jtdgss.TdgssCredential.<init>(TdgssCredential.java:120)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:229)
	at com.teradata.tdgss.jtdgss.TdgssManager.createCredential(TdgssManager.java:195)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.initEncrypt(GenericTeraEncrypt.java:326)
	at com.teradata.jdbc.jdbc.GenericTeraEncrypt.useAuthMech(GenericTeraEncrypt.java:133)
	at com.teradata.jdbc.jdbc.GenericLogonController.run(GenericLogonController.java:335)
	at com.teradata.jdbc.jdbc.GenericTeradataConnection.<init>(GenericTeradataConnection.java:343)
	at com.teradata.jdbc.jdbc_4.TDSession.<init>(TDSession.java:180)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:63)
	at com.teradata.jdbc.jdbc.ConnectionFactory.createConnection(ConnectionFactory.java:53)
	at com.teradata.jdbc.TeraDriver.doConnect(TeraDriver.java:231)
	at com.teradata.jdbc.TeraDriver.connect(TeraDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.teradata.model.TeradataMetaModel.createDataSourceImpl(TeradataMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1210)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1076)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2530)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 <<<end-tdgss-stack-trace

**Comment by LonwoLonwo** [comment]
Hello @nponnapalli-godaddy 

I see an extra character in your URL:

 jdbc:terada**å**ta://myServer.int.MyServer.com/DATABASE=myWarehouse,DBS_PORT=1025,TMODE=TERA,LOGMECH=LDAP

Could you try to connect without this character?

Also, maybe adding extra data with LOGDATA='' in your URL will help you. 

And I can connect without 'TMODE=TERA' part. It can be also not necessary.

**Comment by nponnapalli-godaddy** [comment]
Hello Anastasiya.
I appreciate your help. Even after following your instructions, I am still getting the same error again. This error started after upgrading the latest version for dbeaver (community edition).

**Comment by LonwoLonwo** [comment]
Could you please check the previous DBeaver version now? 
https://dbeaver.io/files/23.1.1/
Can you connect to Teradata in it?
