### ISSUE TITLE
Postgres: general setting 'show all databases' doesn't work, only the default database is shown

### ISSUE THREAD

**Issue by dbeaverforpostgres** [dbeaver/dbeaver#20602]
### Description

In the preferences under Connections/Drivers/PostgreSQL 'show all databases' and 'show databases not available for connection' is ticked. 
When creating a new connection you would assume that automatically all databases would be shown but that is not the case.
Nevertheless, if I check the connection settings of a connection I just created, under the PostgreSQL tab indeed 'show all databases' is ticked. Why doesn't it become visible? 
So I went to have a look at data-sources.json and saw that the driver properties part is missing.
The strange thing is when I edit the connection , save and reconnect suddenly the driver properties part appears:
e.g.
"provider-properties": {
					"@dbeaver-show-non-default-db@": "true",
					"@dbeaver-show-template-db@": "false",
					"@dbeaver-show-unavailable-db@": "false",
					"show-database-statistics": "true",
					"@dbeaver-read-all-data-types-db@": "false",
					"read-keys-with-columns": "false",
					"@dbeaver-use-prepared-statements-db@": "false",
					"postgresql.dd.plain.string": "false",
					"postgresql.dd.tag.string": "false"
				}
Why do I need to edit the connection to get the provider properties part in the data-sources.json? 
So as a workaround I figured, I could adapt the drivers.xml and add parameter lines in the driver id part. But I don't know if it would help and if so what the syntax would be?
I also checked the debug logging and there it states that it will start up the default database, no errors 

### DBeaver Version

Community edition 23.0.2

### Operating System

windows

### Database and driver

postgresql-42.6.0.jar

### Steps to reproduce

In the preferences under Connections/Drivers/PostgreSQL 'show all databases' and 'show databases not available for connection' is ticked. 
When creating a new connection you would assume that automatically all databases would be shown but that is not the case.
Nevertheless, if I check the connection settings of a connection I just created, under the PostgreSQL tab indeed 'show all databases' is ticked. Why doesn't it become visible? 
So I went to have a look at data-sources.json and saw that the driver properties part is missing.
The strange thing is when I edit the connection , save and reconnect suddenly the driver properties part appears:
e.g.
"provider-properties": {
					"@dbeaver-show-non-default-db@": "true",
					"@dbeaver-show-template-db@": "false",
					"@dbeaver-show-unavailable-db@": "false",
					"show-database-statistics": "true",
					"@dbeaver-read-all-data-types-db@": "false",
					"read-keys-with-columns": "false",
					"@dbeaver-use-prepared-statements-db@": "false",
					"postgresql.dd.plain.string": "false",
					"postgresql.dd.tag.string": "false"
				}
Why do I need to edit the connection to get the provider properties part in the data-sources.json?
So as a workaround I figured, I might need to adapt the drivers.xml and add parameter lines in the driver id part. I don't know if it would help and if so what the syntax would be?

**Comment by LonwoLonwo** [comment]
Hello @dbeaverforpostgres 

Do you have a connection with manual or URL type?

![2023-07-20 09_56_05-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/e85ef5f7-ca66-475e-b43e-7e724c039928)

Additionally, I can't reproduce the issue. If "Show all databases" is ticked in the general preferences -> then "Show all databases" is also ticked for new connections.

**Comment by dbeaverforpostgres** [comment]
Indeed, we connect exactly as indicated above. Some additional information about the drivers. Since I don't have direct access to the open internet I don't use the maven default but put the driver postgresql-42.6.0.jar locally and refer to it in the drivers.xml file

**Comment by dbeaverforpostgres** [comment]
Do you know in which file the general options information like "show all databases" are stored so I can see if there's anything missing?

**Comment by LonwoLonwo** [comment]
Hello @dbeaverforpostgres 

You can take a look on the [workspace](https://github.com/dbeaver/dbeaver/wiki/Workspace-Location) directory under the following path: .metadata/.plugins/org.eclipse.core.runtime/.settings

I have this setting in the `org.jkiss.dbeaver.core.prefs` file

**Comment by dbeaverforpostgres** [comment]
Thank you a lot for your response. I had a look but apparantly the 'show non default db' setting is set. Nevertheless I need to alter a connection before all databases come visible. Here is the list of all the settings in org.jkiss.dbeaver.core.prefs

@dbeaver-read-all-data-types-db@=false
@dbeaver-show-non-default-db@=true
@dbeaver-show-template-db@=false
@dbeaver-show-unavailable-db@=true
database.editor.separate.connection=NEVER
database.meta.separate.connection=NEVER
driver.selector.orderBy=score
eclipse.preferences.version=1
org.jkiss.dbeaver.core.confirm.filter_resultset=always
read-keys-with-columns=false
show-database-statistics=true
swt.client.browser=EDGE
tipOfTheDayInitializer.notFirstRun=true
transaction.auto.close.enabled=true
transaction.auto.close.ttl=10800
ui.auto.update.check=false
ui.auto.update.check.time=1681208255161
ui.drivers.home=C\:\\Users\\u45368\\AppData\\Roaming\\DBeaverData\\drivers
ui.render.boolean.style.checked.align=CENTER
ui.render.boolean.style.checked.color=default
ui.render.boolean.style.checked.font=NORMAL
ui.render.boolean.style.checked.text=[v]
ui.render.boolean.style.mode=TEXT
ui.render.boolean.style.null.align=CENTER
ui.render.boolean.style.null.color=default
ui.render.boolean.style.null.font=NORMAL
ui.render.boolean.style.null.text=[NULL]
ui.render.boolean.style.unchecked.align=CENTER
ui.render.boolean.style.unchecked.color=default
ui.render.boolean.style.unchecked.font=NORMAL
ui.render.boolean.style.unchecked.text=[\u2000]
ui.show.tip.of.the.day.on.startup=false

**Comment by dbeaverforpostgres** [comment]
I thought I got it working when I used an old file instead of the one above but in fact only when editing the connection I get to view all the databases. Same as above

@dbeaver-read-all-data-types-db@=false
@dbeaver-show-non-default-db@=true
@dbeaver-show-template-db@=false
@dbeaver-show-unavailable-db@=false
database.editor.separate.connection=false
database.meta.separate.connection=false
driver.selector.orderBy=score
eclipse.preferences.version=1
org.jkiss.dbeaver.core.confirm.close_result_tabs=prompt
org.jkiss.dbeaver.core.confirm.close_running_query=prompt
org.jkiss.dbeaver.core.confirm.dangerous_sql=prompt
org.jkiss.dbeaver.core.confirm.disconnect_txn=prompt
org.jkiss.dbeaver.core.confirm.driver_download=prompt
org.jkiss.dbeaver.core.confirm.entity_delete=prompt
org.jkiss.dbeaver.core.confirm.entity_reject=prompt
org.jkiss.dbeaver.core.confirm.entity_revert=prompt
org.jkiss.dbeaver.core.confirm.exit=prompt
org.jkiss.dbeaver.core.confirm.fetch_all_rows=prompt
org.jkiss.dbeaver.core.confirm.keep_statement_open=prompt
org.jkiss.dbeaver.core.confirm.mass_parallel_sql=prompt
org.jkiss.dbeaver.core.confirm.order_resultset=prompt
org.jkiss.dbeaver.core.confirm.version_check=prompt
resultset.presentation.active=plaintext
show-database-statistics=true
tipOfTheDayInitializer.notFirstRun=true
transaction.auto.close.enabled=true
transaction.auto.close.ttl=10800
ui.auto.update.check=false
ui.drivers.home=C\:\\Users\\u45368\\AppData\\Roaming\\DBeaverData\\drivers
ui.render.boolean.style.checked.align=CENTER
ui.render.boolean.style.checked.color=default
ui.render.boolean.style.checked.font=NORMAL
ui.render.boolean.style.checked.text=[v]
ui.render.boolean.style.mode=TEXT
ui.render.boolean.style.null.align=CENTER
ui.render.boolean.style.null.color=default
ui.render.boolean.style.null.font=NORMAL
ui.render.boolean.style.null.text=[NULL]
ui.render.boolean.style.unchecked.align=CENTER
ui.render.boolean.style.unchecked.color=default
ui.render.boolean.style.unchecked.font=NORMAL
ui.render.boolean.style.unchecked.text=[\u2000]
ui.show.tip.of.the.day.on.startup=false

**Comment by E1izabeth** [comment]
I reproduced the issue this way:
1. Check Show all databases in preferences, if it's not
2. Create new connection, check that Show all databases checked, but don't delete default database postgres in Database field in Connection settings
3. Connect and see only specified database - postgres

However, if I clean Database field, it works - several databases shown in navigator.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e11b2890-9481-410e-abc7-37b57a7ec967)

**Comment by E1izabeth** [comment]
When I tried to expand database postgres in navigator, I caught several the same errors:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/9fea388f-55e2-4513-b307-31dba6cbe4ad)

```
java.lang.IllegalStateException: No databases found on the server
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:641)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:1)
	at org.jkiss.dbeaver.model.DBUtils.getObjectOwnerInstance(DBUtils.java:2133)
	at org.jkiss.dbeaver.model.DBUtils.getDefaultContext(DBUtils.java:2140)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.isDefaultElement(DBNUtils.java:164)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorLabelProvider.getFont(DatabaseNavigatorLabelProvider.java:152)
	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:45)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:970)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:126)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
```

**Comment by dbeaverforpostgres** [comment]
The above workaround might work for an existing connection but not a new connection because it takes the username as databasename which doesn't work either. I'd rather wait till this issue is solved before upgrading to the new version.
It would be nice to have an update here when there's a new version available tackling this bug.

**Comment by LonwoLonwo** [comment]
> It would be nice to have an update here when there's a new version available tackling this bug.

Hello @dbeaverforpostgres 

This info is unavailable. We do not know also.

If something changes, you will see it in the Milestone section of this ticket.

**Comment by muhmudrik** [comment]
> Hello @dbeaverforpostgres
> 
> Do you have a connection with manual or URL type?
> 
> ![2023-07-20 09_56_05-Connect to a database](https://private-user-images.githubusercontent.com/45152336/254798614-e85ef5f7-ca66-475e-b43e-7e724c039928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYxNDYsIm5iZiI6MTcwNDg3NTg0NiwicGF0aCI6Ii80NTE1MjMzNi8yNTQ3OTg2MTQtZTg1ZWY1ZjctY2E2Ni00NzVlLWI0M2UtN2U3MjRjMDM5OTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjM3ZDQxZTZmZmE0ODhiNDRjMzIyOTY2NTczMDI1NTIxZWY4ZDgyODNmYTIzNTk0Y2I4ZTA2MGRlODUyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZG7C_QFseMAwqNivjbzyHkgG4CXgyTrCZq-lFjtp0bs)
> 
> Additionally, I can't reproduce the issue. If "Show all databases" is ticked in the general preferences -> then "Show all databases" is also ticked for new connections.

Hi, i would like to provide some extra information about this. I can reproduce the issue either when creating new connection or editing existing connection. The issue also happens when i use the Connect by URL without filling the database name.
![image](https://github.com/dbeaver/dbeaver/assets/44206861/156598fa-f92c-4d24-a433-665b2d0518ae)
It can be seen below that it only shows the `postgres` database even though i already checked the `Show all databases` option.
![image](https://github.com/dbeaver/dbeaver/assets/44206861/4d3f4a5a-235b-48de-ab80-fe8bd342a460)

But if i change to Connect by Host an emptying the database field, it will shows all the database.
![image](https://github.com/dbeaver/dbeaver/assets/44206861/afe029cf-53dd-4e3f-aa62-2c5cf36baa4b)
![image](https://github.com/dbeaver/dbeaver/assets/44206861/7e7c633e-f18b-4b64-849c-98fa217325d3)

Hope this helps

**Comment by E1izabeth** [comment]
@muhmudrik thank you

**Comment by LonwoLonwo** [comment]
Hello @muhmudrik 

This is expected behavior (for now).

![2024-01-10 13_18_46-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/5ac6216e-186b-4dc6-9043-237157a906a0)

**Comment by dbeaverforpostgres** [comment]
Hello everyone, first of all, thanks a lot for your input. I haven't had time to play around for a while but I gave it another try now. I'll add some screenshots to make it clearer. Some strange things happen which can hardly be seen as expected behaviour. 
We compare 2 situations: both have the general settings configured

![image](https://github.com/dbeaver/dbeaver/assets/73217571/78a750c7-f8ac-4221-b301-91555f04fe82)

then I configured 2 connections. The only difference between the two is that I opened the PostgreSQL tab (I haven't even changed any option)

![image](https://github.com/dbeaver/dbeaver/assets/73217571/250fdada-b03f-4e0f-97e1-514199766d48)

Here's how I set up the connection for both of them

![image](https://github.com/dbeaver/dbeaver/assets/73217571/e32ba11f-c3ef-466a-a65f-2d4e26e62b10)

The strange thing is that for the connection postgres with opening the PostgreSQL tab is showing all the connections and the other one only the default.

I would expect by ticking show all databases in preferences that it is sufficient to see all databases and that I don't need to open the postgresqltab. This is a bug. It would work if you don't set the general preferences which means you have to set them for each connection individually since you need to open the PostgreSQL tab then to tick the box 'show all databases' but this is not something you would expect and is very confusing.

**Comment by doruiulian** [comment]
I can confirm this behaviour . Even if in the General preferences "Show all databases" is ticked, Connections won't show all the databases in an instance unless we first open the Connection Settings - PostgreSQL tab for new or existing connections.
In the case of the first connection from the picture(postgres) i went to the PostgreSQL tab then was able to see all the other databases  ; for the 2nd connection(postgres2) i didn't do it and left it by default again with the "Show all databases" in preferences ticked.
![image](https://github.com/dbeaver/dbeaver/assets/33911021/7a4fc465-da50-47ac-ae7e-e948cf32d320)
Both DBeaver Community edition and Enterprise edition present the same behaviour.

**Comment by dbeaverforpostgres** [comment]
Could you give me an idea of the next steps and what the timeline is for putting this bugfix in production?

**Comment by arhayka** [comment]
@dbeaverforpostgres We hope to fix this issue in one of the next sprints. But we can't guarantee that it will be fixed.

**Comment by dbeaverforpostgres** [comment]
@arhayka, I see label "blocked" was added but unfortunately there hasn't been any response yet since Mar 4. Any idea how we can get this issue going again?

**Comment by perymerdeka** [comment]
I use M2 Air and Dbeaver Community. ' Show all database` is not found in connection settings. Can anyone help?
<img width="704" alt="image" src="https://github.com/user-attachments/assets/3b25702b-d57e-4117-914f-8f77b0c4891e">

**Comment by E1izabeth** [comment]
@perymerdeka here it is
![image](https://github.com/user-attachments/assets/86fdfe84-2143-4ada-b9c9-e71009db9b43)

**Comment by xLUDIOx** [comment]
I also found out about this behaviour the hard way. If there is any way to get the priority of this higher I have my likes, ups, whines ready.

**Comment by muhmudrik** [comment]
@perymerdeka did you connect by URL or filling the host? can refer to some comments above, if you haven't tried the filling host way
