### ISSUE TITLE
[Greenplum] incorrect DDL for table for Greenplum 7

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#20616]
### Description

Original DDL:

```sql
CREATE TABLE RP_TESTS.RP_DATE
(
    RP_INT      INTEGER,
    RP_DATE DATE,
    RP_TIMESTAMP TIMESTAMP,
    RP_DIST_KEY INTEGER NOT NULL
)
WITH (
     APPENDONLY=TRUE
     ,COMPRESSTYPE=ZLIB
     ,COMPRESSLEVEL=9
     ,ORIENTATION=COLUMN
)
DISTRIBUTED BY (RP_DIST_KEY)
PARTITION BY RANGE(RP_DATE)
(
     START (DATE '2015-06-01') INCLUSIVE
     END (DATE '2016-01-01') EXCLUSIVE EVERY (INTERVAL '1 DAY')
);
```

Looks now in DBeaver like this:

```sql
CREATE TABLE public.rp_date (
	rp_int int4 NULL,
	rp_date date NULL,
	rp_timestamp timestamp NULL,
	rp_dist_key int4 NOT NULL
)
PARTITION BY RANGE (rp_date)
WITH (
	compresstype=zlib,
	compresslevel=9
)
DISTRIBUTED BY (rp_dist_key);
```

The partition part is missing, and some options also.

That's because the function `pg_get_partition_def(regclass, boolean, boolean)` is not available in version 7:

```
org.postgresql.util.PSQLException: ERROR: function pg_get_partition_def(regclass, boolean, boolean) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeQuery(JDBCStatementImpl.java:346)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumUtils.getPartitionData(GreenplumUtils.java:118)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumUtils.addObjectModifiersToDDL(GreenplumUtils.java:150)
	at org.jkiss.dbeaver.ext.greenplum.model.GreenplumTable.appendTableModifiers(GreenplumTable.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.impls.PostgreServerExtensionBase.getTableModifiers(PostgreServerExtensionBase.java:324)
```

And `pg_class.reloptions` also are not full in version 7:

![2023-07-20 10_52_15-DBeaver Ultimate 23 1 3 - _dbeaver_db_ Script-49](https://github.com/dbeaver/dbeaver/assets/45152336/e2daed31-78fd-46ac-abb1-7e601c973e11)

### DBeaver Version

23.1.3

**Comment by LonwoLonwo** [comment]
Ticket created https://github.com/greenplum-db/gpdb/issues/16093

**Comment by LonwoLonwo** [comment]
Waiting for answer by e-mail or on the GitHub
