### ISSUE TITLE
Can't access clickhouse database

### ISSUE THREAD

**Issue by jppo** [dbeaver/dbeaver#20690]
### Description

Hello,
When I try to connect to a local database (new install) I get weird messages : 

Code: 46, e.displayText() = DB::Exception: Unknown function currentUser, e.what() = DB::Exception

### DBeaver Version

CE 23.1.3

### Operating System

Debian 11 Bullseye

### Database and driver

clickhouse version : 18.16.1 rev 54412
Driver : the default one
Complete messages in attached file
[messages.txt](https://github.com/dbeaver/dbeaver/files/12163157/messages.txt)

### Steps to reproduce

1 : try to connect to database

That's all folks.

**Comment by LonwoLonwo** [comment]
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Jul 25 17:28:02 CEST 2023
Code: 46, e.displayText() = DB::Exception: Unknown function currentUser, e.what() = DB::Exception

java.io.IOException: Code: 46, e.displayText() = DB::Exception: Unknown function currentUser, e.what() = DB::Exception

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:128)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:335)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:288)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:157)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseDataSource.<init>(ClickhouseDataSource.java:70)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseMetaModel.createDataSourceImpl(ClickhouseMetaModel.java:55)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1214)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1080)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2530)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Hello @jppo 

Please add more info about your connection. What authentication way did you use? Do you have any special driver properties in your connection settings?

**Comment by jppo** [comment]
Hello,
I was using the "old" version from the Debian repo, I install the last version (23.6.1.1524)  from the yandex repo and I the problem has vanished.
The version was "too old" ...
Thanks for your prompt reply.

Regards

JP P

**Comment by lorenou** [comment]
Has this problem been solved?  This issue does exist in clickhouse version 18

**Comment by LonwoLonwo** [comment]
Hello @lorenou 

Did you try to use the Legacy Clickhouse connector?

**Comment by yassine-safraoui** [comment]
Running into the same issue here, I tried older versions of the Clickhouse driver 0.6, 0.4 and 0.3 and they didn't work. I'm running clickhouse server version 18.16.1 revision 54412

**Comment by jppo** [comment]
Hello,



I use Clickhouse since a while and it was always OK through Dbeaver.

I didn't have any more an old clickhouse server version and I am now at 25.3.2.



Regards





De: "yassine-safraoui" ***@***.***>
À: "dbeaver/dbeaver" ***@***.***>
Cc: "JPPO" ***@***.***>, "State change" ***@***.***>
Envoyé: vendredi 28 mars 2025 16:52
Objet: Re: [dbeaver/dbeaver] Can't access clickhouse database (Issue #20690)



Running into the same issue here, I tried older versions of the Clickhouse driver 0.6, 0.4 and 0.3 and they didn't work. I'm running clickhouse server version 18.16.1 revision 54412

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.

yassine-safraoui left a comment (dbeaver/dbeaver#20690)

Running into the same issue here, I tried older versions of the Clickhouse driver 0.6, 0.4 and 0.3 and they didn't work. I'm running clickhouse server version 18.16.1 revision 54412

**Comment by yassine-safraoui** [comment]
> Running into the same issue here, I tried older versions of the Clickhouse driver 0.6, 0.4 and 0.3 and they didn't work. I'm running clickhouse server version 18.16.1 revision 54412

It's fixed for me, I did so by updating to a more recent clickhouse version(25), for some reason I installed the old 18 version.

**Comment by gioipv** [comment]
It's fixed for me with install latest version of clickhouse. This bug will raise when I install clickhouse version 18.
In my case, i install clickhouse from deb [link](https://clickhouse.com/docs/install#setup-the-debian-repository) and I did not run `apt-get update` so It install version 18 clickhouse.
I remove clickhouse and install again run all cmd, It will install version 25, (reboot server as need), start clickhouse again and It's fixed
