### ISSUE TITLE
[CrateDB] Can't see DDL for tables with PK

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#20788]
### Description

If the table have a primary key an error would be shown instead of a DDL

### DBeaver Version

23.1.4

### Operating System

Any

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/82543000/bf2d71a4-5371-435c-ab7e-da3089df7ca1)

### Steps to reproduce

1. Create a table with primary key e.g. `create table t1 (
   c1 int primary key );`
2. Open object editor
3. Click on DDL tab

**Expected:** A DDL is shown
**Actual:** Error is shown

### Additional context

![dbeaver_55gPB06gtB](https://github.com/dbeaver/dbeaver/assets/82543000/528a8135-4f02-44bc-a896-cd7050d79b6f)

```
java.lang.IllegalArgumentException: Unsupported vector type: org.postgresql.jdbc.PgArray
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getIdVector(PostgreUtils.java:189)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$IndexCache.fetchObjectRow(PostgreSchema.java:1042)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$IndexCache.fetchObjectRow(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:360)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getIndexes(PostgreTable.java:219)
	at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.getTableDDL(SQLTableManager.java:292)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableDDL(DBStructUtils.java:101)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getObjectDefinitionText(PostgreTable.java:224)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.getTableDDL(DBStructUtils.java:123)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableListDDL(DBStructUtils.java:141)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:97)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$SourceObjectDocumentProvider.loadSourceText(SQLEditorNested.java:330)
	at org.jkiss.dbeaver.ui.editors.sql.SQLObjectDocumentProvider$1.lambda$0(SQLObjectDocumentProvider.java:105)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.SQLObjectDocumentProvider$1.run(SQLObjectDocumentProvider.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14321)
