### ISSUE TITLE
Double click a second sqlite *.db file, show warning dialog Can't lock workspace

### ISSUE THREAD

**Issue by JerryJian** [dbeaver/dbeaver#20795]
### Description

I configured .db file open with DBeaver by adding following registry entries:

`C:\Program Files\DBeaver\dbeaver.exe -con "driver=sqlite|database=%1"`

But when I have already opened a db file, and double click to open another one, it shows a warning dialog: Can't lock workspace. This problem appears since version 23.1.3.202307231901, the behavior before this version is that open the file in the opened workspace.

![image](https://github.com/dbeaver/dbeaver/assets/800502/13364c70-e016-4952-8d7a-2e2747ad501b)

### DBeaver Version

23.1.3.202307231901

### Operating System

Windows 11

### Database and driver

1. Database: SQLite Database File
2. Driver: sqlite-jdbc-3.39.2.0.jar

I think this problem is not related to the driver.

### Steps to reproduce

1. Configure the registry, add .db file open with.
2. Double click to open a sqlite db file
3. Double click to open another sqlite db file

**Comment by JerryJian** [comment]
Additional informations:
When I open with command line from db directory:

``` bash
"C:\Program Files\DBeaver\dbeaver-cli.exe" -con "driver=sqlite|database=a.db"

> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 23.1.3.202307231901]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.0.v20230526-1051]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.14.0.v20230317-0901]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.110.202307231901]
> Start Expression Language [org.eclipse.core.expressions 3.9.0.v20230317-0901]
Commands processed. Exit DBeaver.
```

It will open in existing workspace, it behaviors as expected.

But when I us command line with full path, error occured.

``` bash
"C:\Program Files\DBeaver\dbeaver-cli.exe" -con "driver=sqlite|database=D:\Code\Test Release\A\C\a.db"
or
"C:\Program Files\DBeaver\dbeaver-cli.exe" -con "driver=sqlite|database='D:\Code\Test Release\A\C\a.db'"
or
"C:\Program Files\DBeaver\dbeaver-cli.exe" -con "driver=sqlite|database="D:\Code\Test Release\A\C\a.db""

> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 23.1.3.202307231901]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.0.v20230526-1051]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.14.0.v20230317-0901]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.110.202307231901]
2023-08-04 10:47:31.251 - Error while calling remote server
org.jkiss.utils.rest.RestException: java.io.IOException: HTTP/1.1 header parser received no bytes
        at org.jkiss.utils.rest.RestClient$ClientInvocationHandler.invoke(RestClient.java:164)
        at jdk.proxy2/jdk.proxy2.$Proxy3.openExternalFiles(Unknown Source)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverCommandLine.executeCommandLineCommands(DBeaverCommandLine.java:202)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverCommandLine.handleCommandLine(DBeaverCommandLine.java:278)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:175)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
        at org.jkiss.utils.rest.RestClient$ClientInvocationHandler.invoke(RestClient.java:136)
        ... 16 more
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
        at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Unknown Source)
        at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Unknown Source)
        at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Unknown Source)
        at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: EOF reached while reading
        at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
        at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.21.0.v20230526-1500]
2023-08-04 10:47:31.301 - Create display
> Start Expression Language [org.eclipse.core.expressions 3.9.0.v20230317-0901]
```

**Comment by E1izabeth** [comment]
It's not allowed to work with one workspace by two or more DBeaver instances by default. However, you could specify an argument to reuse workspace or set different workspace for different DBeaver instances. See https://dbeaver.com/docs/wiki/Command-Line/#dbeaver-control

**Comment by JerryJian** [comment]
@E1izabeth Yeah, I didn't mean want to open more DBeaver instances, but I want to open two sqlite db in one DBeaver instance by command line , and this works well before version 23.1.3.202307231901.  In my last comment, when I open with full path in command line, an communication exception is thrown. I hope the exception information can be help.

**Comment by E1izabeth** [comment]
Thank you for explaining

**Comment by JerryJian** [comment]
@E1izabeth @uslss  I test it again today, when the directory contains Chinese charactor, open with command line is failed.

My sample db path: "D:\备份\Everything.db"

The dbeaver instance prompt: path to 'D:\澶囦唤\Everything.db': 'D:\澶囦唤' does not exist

I think this problem may be related to text encoding.

Thanks

**Comment by ShadelessFox** [comment]
Hello @JerryJian,

You probably need to use the `-reuseWorkspace` option.

Please see https://github.com/dbeaver/dbeaver/wiki/Command-Line#dbeaver-control

Let me know if it solves your issue.

**Comment by JerryJian** [comment]
@ShadelessFox Thanks for tracking the problem, but the option doesn't work for me.

The problem can be reproduced using the attached databases and batch file. 
Step1. Extract the zip into some directory.
Step2. **Drag** database file `Sqlite数据库1.db` on to the `Open.bat` file, this file will be opened successfully.
Step3. **Drag** database file `Sqlite数据库2.db` on to the `Open.bat` file, now we can see the problem.

I guess maybe some encoding problem occurred during communicating with the existing workspace.
Or, there is encoding problem during windows explorer drag-drop to the batch file.

OS Environment: (Copied from window settings, contains some Chinese words)
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎21
操作系统版本	22621.2215
体验	Windows Feature Experience Pack 1000.22662.1000.0

Windows Language: Chinese (Simplified, China) （中文(简体，中国)）

Thanks very much.

[issue-20795.zip](https://github.com/dbeaver/dbeaver/files/12492014/issue-20795.zip)

**Comment by ShadelessFox** [comment]
Works for me against the following batch script:
```batch
start "DBeaver" "C:\Program Files\DBeaver\dbeaver-cli.exe" -con "driver=sqlite|database=%~1|name=%~nx1" -reuseWorkspace -bringToFront
```

**Comment by JerryJian** [comment]
I think this is related to my system settings:
![image](https://github.com/dbeaver/dbeaver/assets/800502/bfaf6dd9-fae3-4076-9339-5322853cb1c9)

I append the options to the script, but the file name is corrupt, and generate a empty database:
![image](https://github.com/dbeaver/dbeaver/assets/800502/5eff82b3-6651-4749-ba47-0238f2306672)

**Comment by ShadelessFox** [comment]
As a workaround, you can remove Chinese characters from the filename.

**Comment by JerryJian** [comment]
@ShadelessFox Yes, that's exactly what I'm doing now. Hope for some fixes in the future realeases, thanks a lot.

**Comment by JerryJian** [comment]
I tested it and found that the problem has been fixed.
