### ISSUE TITLE
DuckDB to_timestamp display error

### ISSUE THREAD

**Issue by k0rsakov** [dbeaver/dbeaver#20801]
### Description

Similar error as in issue #20721

<img width="668" alt="image" src="https://github.com/dbeaver/dbeaver/assets/81204381/cdef544d-16f1-4e82-a55b-ba6578f56110">

```log
java.lang.NullPointerException: Cannot load from object array because "this.varlen_data" is null
	at org.duckdb.DuckDBVector.getLazyString(DuckDBVector.java:211)
	at org.duckdb.DuckDBVector.getDate(DuckDBVector.java:248)
	at org.duckdb.DuckDBResultSet.getDate(DuckDBResultSet.java:358)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:419)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3928)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5104)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

In Jupyter Lab I checked and everything was correct
<img width="515" alt="image" src="https://github.com/dbeaver/dbeaver/assets/81204381/ab6cb5e2-9ef9-4331-821f-81df20027be4">

### DBeaver Version

CE 23.1.3.202307231901

### Operating System

macOS 13.4.1 (c) (22F770820d)

### Database and driver

duckdb_jdbc-0.8.1.jar

### Steps to reproduce

1. SELECT 1654015008 -> ok
2. SELECT to_timestamp(1654015008) -> Exception

**Comment by E1izabeth** [comment]
Could you try the latest DBeaver version 23.1.4? We made some fixes in the latest release.

**Comment by k0rsakov** [comment]
Everything is working correctly now.
Thank you.

**Comment by k0rsakov** [comment]
> Could you try the latest DBeaver version 23.1.4? We made some fixes in the latest release.

@E1izabeth 
Everything is working correctly now.
Thank you.
