### ISSUE TITLE
postgresql error connect with Algorithm constraints check failed on signature algorithm: SHA1withRSA

### ISSUE THREAD

**Issue by benyaminl** [dbeaver/dbeaver#20856]
### Description

I just want to connect to postgresql server 13 LTS from Fedora 38 XFCE Spins, and got error like this 

```log
at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237) 	
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1569) 	
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1498) 	
at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442) 	
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) 	
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) 	
at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) 	
at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) 	
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) 	
at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) 	
at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201) 	
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) 	
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) 	
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) 	
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) 	
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) 	
at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41) 	
at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:620) 	
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191) 	
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258) 	
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) 	
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253) 	
at org.postgresql.Driver.makeConnection(Driver.java:434) 	
at org.postgresql.Driver.access$100(Driver.java:61) 	
at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
```

![image](https://github.com/dbeaver/dbeaver/assets/2817332/6eb9ca9b-8d12-4c60-9f1d-1ba8767fc532)

This with SSL enabled, using dbeaver 23.1.4.202308061552

On Windows 10 with Eclipse Adoptium JDK, using Eclipse+Dbeaver same version. It can connect, also if I use pgAdmin4 I can connect to the server, or using Jetbrain DataGrip

I tried to disabled the java.security disabledAlgo SHA1, seems not working

java.security
```
jdk.certpath.disabledAlgorithms=MD2, MD5
#,SHA1 jdkCA & usage TLSServer, \
#   RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224


jdk.tls.disabledAlgorithms=SSLv3
#, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
#   DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL

```

Seems no avail.

Java version
```bash
$ java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7, mixed mode, sharing)
```

DBeaver Config 
[dbeaver.config.log](https://github.com/dbeaver/dbeaver/files/12308443/dbeaver.config.log)

Error Log is added.

[dbeaver.log](https://github.com/dbeaver/dbeaver/files/12308414/dbeaver.log)

Any help or pointer is really appreciated. 

### DBeaver Version

Community Edition 23.1.4.202308061552

### Operating System

Fedora 38 XFCE

### Database and driver

Postgresql 13 LTS

### Steps to reproduce

1. Connect to postgresql 13 LTS with cert enabled using Fedora 38
2. error

### Additional context

1. only happen on linux

**Comment by Destrolaric** [comment]
@benyaminl Hi, do you use your Java system for DBeaver launch? 
Edit - Never mind, I see the Java version. You can try installing DBeaver with the included Adoptium java and see if it will work. 
https://dbeaver.io/download/

**Comment by benyaminl** [comment]
@Destrolaric Uhmm.. yes.... Ugh.. does that mean Red Hat Java from Fedora System Package is broken? 

It's strange tbh... I don't use dbeaver java because I don't want have more than one java runner in one system.

Any guess why adoptium works but red hat java aren't? or they have different under laying? 
Other thing is, why the Jetbrain Datagrip with same java can connect?

**Comment by Destrolaric** [comment]
@benyaminl Not sure, but to be certain that is related to the Java client, could you look if using DBeaver Java version will fix it? I think it may still be related to the difference in security configs.

**Comment by benyaminl** [comment]
> @benyaminl Not sure, but to be certain that is related to the Java client, could you look if using DBeaver Java version will fix it? I think it may still be related to the difference in security configs.

Sorry I'm not clear in my answer. After I use the dbeaver Java/Eclipse Adoptium, it does work. Just the java.security seems the same.

That's why I asked again. Sorry for my statement not clear enough.

Anyway this mean that it isn't dbeaver bugs right. Can I close this?

**Comment by Destrolaric** [comment]
@benyaminl https://access.redhat.com/solutions/6992400 Looks like there additional configuration to use that algorithm in this java

**Comment by benyaminl** [comment]
@Destrolaric  Yeah... This is not very common probably, or most dev already know, just I don't. I don't use java daily, only product that use java, like dbeaver. So seems I got left out the news. 

Well there are public posts about this 
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

in short 
```
$ sudo update-crypto-policies --set LEGACY
# or set
$ sudo update-crypto-policies --set DEFAULT:SHA1
```

Either one, but for now I think because it's dev box, I will go with `LEGACY`

Thank you for pointing out. This isn't DBeaver bugs...

I will close this. Thanks!
