### ISSUE TITLE
Pressing one time too often (after its clear) return in data type field of column throws error

### ISSUE THREAD

**Issue by GiantCrocodile** [dbeaver/dbeaver#2088]
Steps to reproduce:
1. create a table
2. create a column
3. type some chars into datatype field
4. notice that you typed wrong chars into it - remove them all and then press once again return
5. see below.

```
java.lang.IllegalArgumentException: Bad data type name specified: 
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute$DataTypeValueTransformer.transform(PostgreAttribute.java:243)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute$DataTypeValueTransformer.transform(PostgreAttribute.java:1)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceEditable.setPropertyValue(PropertySourceEditable.java:89)
	at org.jkiss.dbeaver.ui.editors.object.struct.AttributeEditPage$3.setPropertyValue(AttributeEditPage.java:90)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.setPropertyValue(PropertySourceAbstract.java:285)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer$6.applyEditorValue(PropertyTreeViewer.java:416)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.applyEditorValueAndDeactivate(ComboBoxCellEditor.java:272)
	at org.eclipse.jface.viewers.ComboBoxCellEditor.focusLost(ComboBoxCellEditor.java:279)
	at org.eclipse.jface.viewers.ComboBoxCellEditor$3.focusLost(ComboBoxCellEditor.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:144)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.CCombo.handleFocus(CCombo.java:922)
	at org.eclipse.swt.custom.CCombo$1$1.run(CCombo.java:132)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:103)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.showDialog(EditObjectDialog.java:98)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.edit(BaseObjectEditPage.java:81)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableColumnManager$2.runTask(PostgreTableColumnManager.java:123)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableColumnManager$2.runTask(PostgreTableColumnManager.java:1)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:26)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:167)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

```

**Comment by serge-rider** [comment]
This is expected behavior - as you are trying to data type to empty string.

**Comment by GiantCrocodile** [comment]
But I didn't press enter. The same applies when I type 'serial' and don't press enter. It tells me that this isn't a valid selection of datatype. So somehow DBeaver doesn't get the input correctly and behaves not userfriendly thus.

**Comment by serge-rider** [comment]
Data type value is applied when edit control lose focus. So you don't need to press Enter explicitly.

**Comment by tati-kru** [comment]
This is expected behavior, this ticket will be closed.
