### ISSUE TITLE
When exporting SQL, supports escape configuration for text fields

### ISSUE THREAD

**Issue by hjgeek** [dbeaver/dbeaver#20906]
**Is your feature request related to a problem? Please describe.**

Now I have a TEXT field like this in my mysql
![image](https://github.com/dbeaver/dbeaver/assets/45581788/707b3939-ae1a-4eac-bd3d-75ea251e2c9a)

then i exported it with DBever，It cannot be imported or executed
![image](https://github.com/dbeaver/dbeaver/assets/45581788/21749572-9576-480d-b373-54947508b114)

export with navicat, Found that all text fields were automatically escaped
![image](https://github.com/dbeaver/dbeaver/assets/45581788/2de5aa6e-5e71-4875-8e16-69ae903f9913)

**Describe the solution you'd like**

when I export the sql, I can choose the Fields to escape

**Comment by LonwoLonwo** [comment]
Hello @hjgeek 

Could you please provide clear steps to reproduce your case? It is not clear for now.

**Comment by hjgeek** [comment]
感谢回复 @LonwoLonwo 
为了表述更清楚，我还是用中文吧 ^_^

1、场景描述
我存储了一些代码在 mysql  中一个 LONGTEXT 类型的表字段中，这些代码是包含换行符的。
可以看到下面图片，当鼠标悬浮到单元格上时，显示出来的数据是换行的
![image](https://github.com/dbeaver/dbeaver/assets/45581788/9fd0a2f1-1474-40e0-b8f2-e8d2da1a158d)

2、我导出这条语句
![image](https://github.com/dbeaver/dbeaver/assets/45581788/ed8b932d-2c4f-447c-a8b2-6ff813b798b3)
用vscode打开查看sql，发现此sql换行了
![image](https://github.com/dbeaver/dbeaver/assets/45581788/8af266a1-4c80-40ea-bd7d-75e4c5b50706)

3、右键点击数据库，通过”执行脚本“的方式执行这个sql
![image](https://github.com/dbeaver/dbeaver/assets/45581788/74f040a1-4be1-4753-83cf-aa10e7c7f7f4)

4、发现执行报错
![image](https://github.com/dbeaver/dbeaver/assets/45581788/bcb9528f-b442-47db-b113-373f72d757f2)

详细错误如下
```
C:\Users\Administrator\AppData\Roaming\DBeaverData\drivers\clients\mysql_8\win\mysql.exe -u admin --host=10.74.143.19 --port=30567 geek_lowcode
Task 'MySQL 鑴氭湰' started at Fri Aug 25 10:35:49 CST 2023
Task 'MySQL 鑴氭湰' finished at Fri Aug 25 10:35:49 CST 2023
2023-08-25 10:35:49.835 - IO error: Process failed (exit code = -1073741701). See error log.
2023-08-25 10:35:49.835 - java.io.IOException: Process failed (exit code = -1073741701). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

我的需求：
我有大量的这样的数据，需要做筛选并批量的准确的导出sql，并导入到其他环境（无法访问任何外部网络）的数据库。最好的方式就是通过sql的导入导出来进行操作。但是在面对换行转义字符时，导出的sql无法执行。

我的建议：
我发现 Navicat这款数据库产品，导出SQL时，会自动将文本类型的字段数据做转义（保证sql代码不换行），导入后再取消转义。这种做法确实解决了问题，但却有点强制性。 如果能够在导出SQL的界面中，让用户选择字段来决定是否转义，或许会更好。
![image](https://github.com/dbeaver/dbeaver/assets/45581788/cd336725-8b6d-43ab-9e3c-0636768d818a)
或许有更好的方式，我还不知道。

**Comment by LonwoLonwo** [comment]
Ok. So, some text columns should have to escape, and some not. It can be configurable. Ok.
