### ISSUE TITLE
23.1.4.202308061552 crashes Eclipse

### ISSUE THREAD

**Issue by gnl42** [dbeaver/dbeaver#20905]
### Description

When I install 23.1.4.202308061552 in  Eclipse 2023-06 it crashes on startup.

From the .log file:
`Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.gef (1061).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.jkiss.dbeaver.erd.ui.internal.ERDUIActivator.start(ERDUIActivator.java:75)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$4(AdapterFactoryProxy.java:84)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.loadFactory(AdapterFactoryProxy.java:157)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$11(AdapterManager.java:296)
	... 81 more
Caused by: org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="3.14.0.202305312117"; osgi.identity="org.eclipse.gef"; singleton:="true" [id=1061]
	at org.eclipse.osgi.container.Module.doStart(Module.java:614)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 116 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/draw2d/ColorProvider
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:801)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:753)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	... 119 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.draw2d.ColorProvider cannot be found by org.eclipse.gef_3.14.0.202305312117
`

### DBeaver Version

IDE	23.1.4.202308061552

### Operating System

Windows 11

### Steps to reproduce

Install in 2023-06

**Comment by Destrolaric** [comment]
@gnl42 Hi, are there any other non-standard Eclipse plugins installed? Also, a full log with errors may help to determine what may cause the issue.

**Comment by gnl42** [comment]
Don't know what you mean by 'non-standard'?
dbeaver was working up until this version so it's something with this new release.

`!ENTRY org.eclipse.equinox.registry 4 0 2023-07-27 15:42:59.346

!MESSAGE Error instantiating adapter factory for "org.eclipse.swt.widgets.Control" declared by "org.jkiss.dbeaver.erd.ui".

!STACK 1

org.eclipse.core.runtime.CoreException: Plug-in org.jkiss.dbeaver.erd.ui was unable to load class org.jkiss.dbeaver.erd.ui.editor.ERDEditorAdapter.

at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)

at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)

at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)

at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)

at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)

at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$4(AdapterFactoryProxy.java:84)

at org.eclipse.core.internal.adapter.AdapterFactoryProxy.loadFactory(AdapterFactoryProxy.java:157)

at org.eclipse.core.internal.runtime.AdapterManager.lambda$11(AdapterManager.java:296)

at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)

at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)

at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)

at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)

at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)

at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)

at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)

at org.eclipse.core.internal.expressions.AdaptExpression.evaluate(AdaptExpression.java:102)

at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)

at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)

at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)

at org.eclipse.core.expressions.AndExpression.evaluate(AndExpression.java:36)

at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:79)

at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:109)

at org.eclipse.ui.internal.services.EvaluationReference.changed(EvaluationReference.java:103)

at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)

at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:358)

at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:374)

at org.eclipse.ui.internal.services.EvaluationService$1.changed(EvaluationService.java:79)

at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)

at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:358)

at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:374)

at org.eclipse.e4.core.commands.ExpressionContext.addVariable(ExpressionContext.java:87)

at org.eclipse.ui.internal.services.EvaluationService.changeVariable(EvaluationService.java:149)

at org.eclipse.ui.internal.services.EvaluationService$3.sourceChanged(EvaluationService.java:125)

at org.eclipse.ui.AbstractSourceProvider.fireSourceChanged(AbstractSourceProvider.java:84)

at org.eclipse.ui.internal.menus.FocusControlSourceProvider.focusIn(FocusControlSourceProvider.java:109)

at org.eclipse.ui.internal.menus.FocusControlSourceProvider$1.focusGained(FocusControlSourceProvider.java:79)

at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:143)

at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1071)

at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2940)

at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2321)

at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5424)

at org.eclipse.swt.widgets.Control.windowProc(Control.java:4815)

at org.eclipse.swt.widgets.Text.windowProc(Text.java:2687)

at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)

at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)

at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1091)

at org.eclipse.swt.widgets.Control.setFocus(Control.java:3439)

at com.genuitec.eclipse.inlinesearch.editor.findreplace.FindReplaceBar.createControl(FindReplaceBar.java:1003)

at com.genuitec.eclipse.inlinesearch.editor.findreplace.FindReplaceBar.createSearchBar(FindReplaceBar.java:574)

at com.genuitec.eclipse.inlinesearch.core.InlineSearchManager.showEditorFindReplaceBar(InlineSearchManager.java:110)

at com.genuitec.eclipse.inlinesearch.handlers.ShowFindReplaceBarHandler.execute(ShowFindReplaceBarHandler.java:52)

at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)

at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:568)

at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)

at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:309)

at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:243)

at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)

at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)

at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)

at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)

at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)

at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)

at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)

at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:655)

at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)

at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)

at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1286)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)

at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)

at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)

at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1594)

at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4865)

at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)

at org.eclipse.swt.widgets.Control.windowProc(Control.java:4743)

at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)

at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)

at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)

at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)

at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:568)

at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.jkiss.dbeaver.erd.ui (1358).

at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)

at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)

at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)

at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)

at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)

at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)

at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)

at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)

at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)

at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$4(AdapterFactoryProxy.java:84)

at org.eclipse.core.internal.adapter.AdapterFactoryProxy.loadFactory(AdapterFactoryProxy.java:157)

at org.eclipse.core.internal.runtime.AdapterManager.lambda$11(AdapterManager.java:296)

at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)

at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)

at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)

at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)

at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)

at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)

at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)

at org.eclipse.core.internal.expressions.AdaptExpression.evaluate(AdaptExpression.java:102)

at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)

at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)

at org.eclipse.ui.internal.handlers.HandlerActivation.evaluate(HandlerActivation.java:91)

at org.eclipse.ui.internal.handlers.LegacyHandlerService$HandlerSelectionFunction.compute(LegacyHandlerService.java:122)

at org.eclipse.e4.core.internal.contexts.ValueComputation.get(ValueComputation.java:70)

at org.eclipse.e4.core.internal.contexts.EclipseContext.internalGet(EclipseContext.java:243)

at org.eclipse.e4.core.internal.contexts.EclipseContext.get(EclipseContext.java:230)

at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.lookUpHandler(HandlerServiceImpl.java:103)

at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:75)

at org.eclipse.core.commands.Command.setEnabled(Command.java:856)

at org.eclipse.ui.menus.CommandContributionItem.isEnabled(CommandContributionItem.java:916)

at org.eclipse.ui.menus.CommandContributionItem.updateMenuItem(CommandContributionItem.java:531)

at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:484)

at org.eclipse.jface.action.MenuManager.update(MenuManager.java:858)

at org.eclipse.jface.action.MenuManager.update(MenuManager.java:858)

at org.eclipse.ui.internal.Workbench.updateActiveWorkbenchWindowMenuManager(Workbench.java:3138)

at org.eclipse.ui.internal.Workbench.lambda$0(Workbench.java:3120)

at org.eclipse.jface.bindings.BindingManager.fireBindingManagerChanged(BindingManager.java:901)

at org.eclipse.jface.bindings.BindingManager.setActiveBindings(BindingManager.java:2181)

at org.eclipse.jface.bindings.BindingManager.recomputeBindings(BindingManager.java:1767)

at org.eclipse.jface.bindings.BindingManager.contextManagerChanged(BindingManager.java:691)

at org.eclipse.core.commands.contexts.ContextManager.fireContextManagerChanged(ContextManager.java:164)

at org.eclipse.core.commands.contexts.ContextManager.setEventCaching(ContextManager.java:323)

at org.eclipse.core.commands.contexts.ContextManager.deferUpdates(ContextManager.java:85)

at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:781)

at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.switchPerspective(PartServiceImpl.java:640)

at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:102)

at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)

at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:64)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)

at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)

at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)

at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)

at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)

at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)

at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:658)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)

at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)

... 20 more

Caused by: org.osgi.framework.BundleException: Exception in org.jkiss.dbeaver.erd.ui.internal.ERDUIActivator.start() of bundle org.jkiss.dbeaver.erd.ui.

at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)

at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)

at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)

at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)

at org.eclipse.osgi.container.Module.doStart(Module.java:605)

at org.eclipse.osgi.container.Module.start(Module.java:468)

at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)

at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)

... 96 more

Caused by: java.lang.NoClassDefFoundError: org/eclipse/gef/internal/InternalImages

at org.jkiss.dbeaver.erd.ui.internal.ERDUIActivator.start(ERDUIActivator.java:70)

at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)

at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)

at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)

... 103 more

Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.gef (1061).

at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)

at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)

at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)

at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)

at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)

at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

... 108 more

Caused by: org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="3.14.0.202305312117"; osgi.identity="org.eclipse.gef"; singleton:="true" [id=1061]

at org.eclipse.osgi.container.Module.doStart(Module.java:614)

at org.eclipse.osgi.container.Module.start(Module.java:468)

at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)

at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)

... 116 more

Caused by: java.lang.NoClassDefFoundError: org/eclipse/draw2d/ColorProvider

at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)

at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)

at java.base/java.lang.Class.getConstructor0(Class.java:3578)

at java.base/java.lang.Class.getConstructor(Class.java:2271)

at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:801)

at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:753)

at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)

at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)

at org.eclipse.osgi.container.Module.doStart(Module.java:605)

... 119 more

Caused by: java.lang.ClassNotFoundException: org.eclipse.draw2d.ColorProvider cannot be found by org.eclipse.gef_3.14.0.202305312117

at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)

at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)

at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

... 128 more`

**Comment by gnl42** [comment]
I rebuilt Eclipse (with the same plugins) and it works now.
