### ISSUE TITLE
TransactionEndConfirmDialog uses 100% CPU until the dialog becomes visible

### ISSUE THREAD

**Issue by gyoetam** [dbeaver/dbeaver#20938]
### Description

I'm running dbeaver on linux with a multiple desktop layout, e.g. dbeaver left running on desktop 2 while I'm doing something else on desktop 1 (i.e. desktop 2 with dbeaver in it is not currently visible on the screen).

When dbeaver decides that it wants to close the connection due to inactivity, it shows a pop-up dialog with a confirmation choice to keep the connection alive, with the button showing a countdown from 10 seconds once it becomes visible.

However, the countdown only starts when the pop-up actually becomes visible, which only happens if and when I change my screen to show desktop 2, where dbeaver is placed. In the meantime, dbeaver hogs the CPU with 100% usage.

As soon as I switch to that desktop, CPU usage drops to near zero.

I took stack traces with jcmd before and after switching to dbeaver's desktop, this is where I saw the main thread (common methods ommitted):

before becoming visible:
```
"main" #1 prio=6 os_prio=0 cpu=226755.24ms elapsed=934.84s tid=0x00007fdd48016100 nid=0x4c7c2 runnable  [0x00007fdd4cbfd000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:2973)
	at org.eclipse.swt.widgets.Shell.open(Shell.java:2032)
	at org.eclipse.jface.window.Window.open(Window.java:795)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:609)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler$TransactionEndConfirmDialog.open(DataSourceHandler.java:405)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler$TransactionEndConfirmer.run(DataSourceHandler.java:357)
```
after becoming visible:
```
"main" #1 prio=6 os_prio=0 cpu=270254.95ms elapsed=983.86s tid=0x00007fdd48016100 nid=0x4c7c2 runnable  [0x00007fdd4cbfd000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.gtk.OS.Call(Native Method)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:5641)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:824)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:609)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler$TransactionEndConfirmDialog.open(DataSourceHandler.java:405)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler$TransactionEndConfirmer.run(DataSourceHandler.java:357)
```

### DBeaver Version

Community Edition 23.1.4.202308061649

### Operating System

linux with Xfce 4.18 and GTK 3.24.38

### Database and driver

seems irrelevant to the bug

### Steps to reproduce

See description:
1. connect to database with default settings (maybe relevant property: automatically end long idle transactions: 1800)
2. leave dbeaver alone, switch to different desktop
3. wait for timeout to occur, observe CPU usage spiking and staying at 100% indefinitely
4. switch back to desktop with dbeaver on it, pop-up dialog appears and starts countdown
5. observe CPU usage dropping instantly

### Additional context

see description

**Comment by E1izabeth** [comment]
@Destrolaric couldn't reproduce on KDE

**Comment by Destrolaric** [comment]
Confirmed for XFCE 

https://github.com/dbeaver/dbeaver/assets/20579256/4dd9bcf9-3532-41fd-ab8e-43b079b5ae79

**Comment by ssttaarr** [comment]
I confirm the same issue on my Linux machine 

OS: Linux Mint 21.3 x86_64 
Kernel: 6.8.0-60-generic
DE: Xfce 4.18
WM: Xfwm4 

running DBeaver 25.1.2 on openjdk version 21.0.7 directly on the host (no VM). The dialog in question is like

<img width="694" height="208" alt="Image" src="https://github.com/user-attachments/assets/d2db20c5-c690-4b93-bcf1-d055812e32cd" />

It usually happens when I forget to commit/rollback transaction and switch to another workspace, and after a while I notice
CPU cooler fan goes wild.

**Comment by gyoetam** [comment]
@ssttaarr thanks for confirming! 

This also seems to be triggered by an active screen lock, i.e. dbeaver is open in the currently used workspace, but the screen is locked: after the transaction timeout kicks in, CPU usage spikes.
