### ISSUE TITLE
ClickHouse Array Map

### ISSUE THREAD

**Issue by BlackTrade** [dbeaver/dbeaver#20958]
### Description

I have column type array map and can't see values in Dbeaver and see such text

java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.util.Collection (java.util.LinkedHashMap and java.util.Collection are in module java.base of loader 'bootstrap')
	at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.makeValue(ClickhouseTypeParser.java:88)
	at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.makeValue(ClickhouseTypeParser.java:61)
	at org.jkiss.dbeaver.ext.clickhouse.model.data.ClickhouseStructValueHandler.getValueFromObject(ClickhouseStructValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:428)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:838)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:632)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3937)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5142)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

23.1.5.202308201919

**Comment by E1izabeth** [comment]
Hi, @BlackTrade. Thank you for bug report. Could you provide DDL to reproduce your issue?

**Comment by E1izabeth** [comment]
Could you also provide your database and driver version? You can find this information by clicking on "Test connection" button in connection settings.

**Comment by Sceosasciba** [comment]
Hey, I had the same issue. 

DBeaver version: 23.2.0.202309041200
Clickhouse database version: ClickHouse 23.6.2.18
Clickhouse driver version: ClickHouse JDBC Driver 0.4.6 (revision: dd91e17)

You can reproduce it by using the following query:
`SELECT 'test' as testColumn, array(map('key1', 1))`

In DBeaver this would give that "LinkedHashMap cannot be cast to class Collection" error (in the array fields, the testColumn is fine).
However, when I run this in Python I get the wanted results, using clickhouse_connect 0.5.23:
`[('test', [{'key1': 1}])]`

I also got a (I think related) error in some of the fields where it would say: _java.lang.ClassCastException: class java.util.Collections$EmptyMap cannot be cast to class java.util.Collection (java.util.Collections$EmptyMap and java.util.Collection are in module java.base of loader 'bootstrap')"_
I don't have a way to easily reproduce this yet but with my data it looks it was indeed trying to convert a Map that was empty to a Collection and it couldn't. 

Feel free to tag me if more info is needed.

**Comment by E1izabeth** [comment]
Thank you. I reproduced the issue.
