### ISSUE TITLE
Not able to open and create sql file  - Failed to create the part's controls

### ISSUE THREAD

**Issue by 150170410** [dbeaver/dbeaver#20981]
### Description

Not able to open existed sql script at the new build Version 23.1.5.202308201919

### DBeaver Version

Version 23.1.5.202308201919

### Operating System

Windows

**Comment by bceschi** [comment]
I also have this issue, Downgrading DBeaver to 23.1.4 resolved the problem for me.

**Comment by 150170410** [comment]
More info
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "originalImage" is null
	at org.eclipse.jface.resource.ImageDataImageDescriptor.<init>(ImageDataImageDescriptor.java:41)
	at org.eclipse.jface.resource.ImageDescriptor.createFromImage(ImageDescriptor.java:127)
	at org.jkiss.dbeaver.ui.DBIconBinary.<init>(DBIconBinary.java:44)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.refreshEditorIconAndTitle(SQLEditor.java:2921)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.onDataSourceChange(SQLEditor.java:2838)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.lambda$27(SQLEditor.java:3067)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:278)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)


eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by 150170410** [comment]
Cannot invoke "Object.getClass()" because "originalImage" is null

**Comment by LonwoLonwo** [comment]
Thanks for the report

**Comment by uslss** [comment]
@150170410 @bceschi could you provide the steps on how you open the script?

**Comment by 150170410** [comment]
> @150170410 @bceschi could you provide the steps on how you open the script?

Usually, I kept the SQL scripts opened all the times when launched and closed the DBeaver app to save my time to open it. 
So ,when I upgraded to the latest DBeaver, all opened the scripts will be automatically opened , but unluckily, all scripts reported the same issue. 
Then, I did try to go to SQL Editor> New SQL script, I saw the same error on console.

**Comment by aldebaranbm** [comment]
Same problem here. All scripts are affected, both new and existing. I downgraded to version 23.1.4 to temporarily resolve this issue. I'm using Linux Debian 11 (x86-64) with Cinnamon interface. This is my [DBeaver screen](https://pasteboard.co/ain0I76EXSqj.png) as soon as the program starts.

**Comment by LonwoLonwo** [comment]
Hello!

Could you please test the latest DBeaver version Early Access? https://dbeaver.io/files/ea/
I hope this issue is fixed there.

**Comment by aldebaranbm** [comment]
@LonwoLonwo is fixed in EA dated with 2023-08-25 09:22:46 (dbeaver-ce_23.1.5_amd64.deb md5: b4c137046e77c93651aac265fc8c3d4d)

**Comment by LonwoLonwo** [comment]
@aldebaranbm Thank you for your answer!
