### ISSUE TITLE
Properties tab not showing columns until after an element resize

### ISSUE THREAD

**Issue by SoraDevin** [dbeaver/dbeaver#21001]
### Description

After double clicking a table and navigating to the properties tab I get a blank view with no data. If I resize the inner frame that has the columns, constraints, foreign keys etc. menu in it through any means (arrows, click and drag) then all the elements appear. The grid headings also only appear after the resize. If I navigate from Columns to say Constraints, the same behaviour is present for that data grid.

### DBeaver Version

23.1.3

### Operating System

Linux Mint

### Database and driver

Postgres 14

### Steps to reproduce

1. Connect to database
2. navigate to table and double click to open
3. navigate to properties tab
4. Verify no information shown, then drag the inner frame or click the max/min arrows
5. Verify information is now shown.
6. Optionally, repeat on another data menu item like _Constraints_

**Comment by danielheramb** [comment]
Same issue except resizing doesn't ever populate the tab for me.

DBeaver version: 23.1.5
OS: macOS 12.6.8
Server: PostgreSQL 13.10
Driver: PostgreSQL JDBC Driver 42.2.5

**Comment by SoraDevin** [comment]
@danielheramb does resizing work after an F5 refresh?

**Comment by E1izabeth** [comment]
That's very strange, but I can't reproduce it. Could someone record a video of what's going on?

**Comment by danielheramb** [comment]
> @danielheramb does resizing work after an F5 refresh?

No. Refreshing doesn't help.  Though, after re-reading your initial report, I'm not 100% sure that my issue is the same as yours.  When I click on any "Properties" tab (database, schema, table, ...), the view is completely blank.  For schemas and tables, I am able to see the "ER Diagram" tab (which works fine).  However, for tables, the "Data" tab is also a completely blank view.

<img width="961" alt="image" src="https://github.com/dbeaver/dbeaver/assets/30296294/94fd81d0-0be7-48ed-b6f2-b88c87ad611c">

**Comment by E1izabeth** [comment]
Could you also send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by danielheramb** [comment]
I'm in the process of uninstalling/reinstalling via .dmg. (Already tried via brew.) Trying to figure out if it's a setting that somehow got changed.  Next guess is that I'll try to wipe the ~/Library/DBeaverData folder to have that be recreated unless you think this error related to the theme is the culprit, and you have an idea as to how to fix it.)

Here's the last entry in dbeaver-debug.log:  
2023-08-28 16:09:47.343 - java.lang.NullPointerException: Cannot invoke "org.eclipse.e4.ui.css.swt.theme.IThemeEngine.getActiveTheme()" because the return value of "org.eclipse.ui.IWorkbench.getService(java.lang.Class)" is null
	at org.jkiss.dbeaver.ui.UIStyles.isHighContrastTheme(UIStyles.java:55)
	at org.jkiss.dbeaver.ui.UIStyles.isDarkHighContrastTheme(UIStyles.java:59)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.<init>(ResultSetViewer.java:264)
	at org.jkiss.dbeaver.ui.editors.data.AbstractDataEditor.createResultSetView(AbstractDataEditor.java:116)
	at org.jkiss.dbeaver.ui.editors.data.AbstractDataEditor.setFocus(AbstractDataEditor.java:202)
	at org.eclipse.ui.part.MultiPageEditorPart.setFocus(MultiPageEditorPart.java:1071)
	at org.eclipse.ui.part.MultiPageEditorPart.setFocus(MultiPageEditorPart.java:1054)
	at org.eclipse.ui.part.MultiPageEditorPart.pageChange(MultiPageEditorPart.java:800)
	at org.jkiss.dbeaver.ui.editors.MultiPageAbstractEditor.pageChange(MultiPageAbstractEditor.java:162)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.pageChange(EntityEditor.java:706)
	at org.eclipse.ui.part.MultiPageEditorPart.lambda$1(MultiPageEditorPart.java:271)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3253)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1892)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:332)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:278)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by E1izabeth** [comment]
Could you try early access version?
https://dbeaver.io/files/ea/
Judging by the logs, most probably we've already fixed it.

**Comment by danielheramb** [comment]
@SoraDevin After removing my DBeaverData folder (where all the settings and configurations are stored), I was able to see everything in a new install.  This led me to believe it was something to do with the theme I was using.  I think my employer's software management application may have done something to the theme files, because everything worked fine again once I re-enabled theming and used the default "Light" theme.  (Preferences -> User Interface -> Appearance)

Hope this helps.

**Comment by ShadelessFox** [comment]
I believe the issue has been solved already. Please feel free to comment if the issue still appears.
