### ISSUE TITLE
[OceanBase] Can't create view through UI

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#21039]
### Description

Dbeaver doesn't allow creating view through UI because it thinks the view with this name already exists (temporary view appears in Navigator during creation process)

### DBeaver Version

23.2.0

### Operating System

Any

### Database and driver

MySQL 5.7.25
MySQL Connector Java mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )

### Steps to reproduce

1. Right-click on views folder and select `create new view`
2. Type anything into source tab and click save, then persist

**Expected:** View is created
**Actual:** DDL query isn't even sent and error shows that the view with this name already exists

### Additional context

```
org.jkiss.dbeaver.model.exec.DBCException: View with name 'NewView123342' already exists. Choose another name
	at org.jkiss.dbeaver.ext.mysql.edit.MySQLViewManager$1.beforeExecute(MySQLViewManager.java:141)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.executePersistAction(DBExecUtils.java:357)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:40)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:206)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:122)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:384)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:382)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1253)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14427)
- Test [View](https://web.testquality.com/site/dbeaver/project/8805/runs/182306?resultId=3441833) in Run [23.2.0 OceanBase CE](https://web.testquality.com/site/dbeaver/project/8805/runs/182306) (linked to Cycle [CE MySQL](https://web.testquality.com/site/dbeaver/project/8805/cycles/21919)).
