### ISSUE TITLE
Cannot open external editor using context menu for BLOB/CLOB columns

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21040]
### Description

Error appears when trying to open external editor for BLOB/CLOB using context menu [Edit - Open in External Editor].
Works ok on Shift + Enter.

https://github.com/dbeaver/dbeaver/assets/31996417/6ad797fd-f531-4786-8227-e54c7c88260c

### DBeaver Version

23.2.0

### Operating System

win10

### Database and driver

SQLite, Sybase

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 30 13:40:20 CEST 2023
Cannot invoke "org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor.getStreamEditor()" because "this.val$activeEditor" is null

java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor.getStreamEditor()" because "this.val$activeEditor" is null
	at org.jkiss.dbeaver.ui.data.managers.ContentValueManager$2.run(ContentValueManager.java:105)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:278)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)


```

**Comment by uslss** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14428)

**Comment by ShadelessFox** [comment]
Looks like it's only reproducible against NULL BLOBs.

**Comment by uslss** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14428)
- Test [Data Editor: editing BLOB/CLOB](https://web.testquality.com/site/dbeaver/project/8805/runs/182307?resultId=3441946) in Run [23.2.0 Sybase CE](https://web.testquality.com/site/dbeaver/project/8805/runs/182307) (linked to Cycle [CE Sybase](https://web.testquality.com/site/dbeaver/project/8805/cycles/21959)).
- Test [Data Editor: GIS data](https://web.testquality.com/site/dbeaver/project/8805/runs/182307?resultId=3441956) in Run [23.2.0 Sybase CE](https://web.testquality.com/site/dbeaver/project/8805/runs/182307) (linked to Cycle [CE Sybase](https://web.testquality.com/site/dbeaver/project/8805/cycles/21959)).
