### ISSUE TITLE
NPE appears on Ctrl+Click on reference link in resultset

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21044]
### Description

NPE appears on Ctrl+Click on reference link in resultset

https://github.com/dbeaver/dbeaver/assets/31996417/5e54df4a-1cac-416e-8e97-ec82a2e67cab

### DBeaver Version

23.2.0

### Operating System

win10

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 30 13:58:42 CEST 2023
Cannot invoke "org.jkiss.dbeaver.model.sql.SQLScriptElement.getOriginalText()" because the return value of "org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.getQuery()" is null

java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.sql.SQLScriptElement.getOriginalText()" because the return value of "org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.getQuery()" is null
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.notifyOnDataListeners(SQLEditor.java:4825)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.onModelPrepared(SQLEditor.java:4103)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.fireResultSetModelPrepared(ResultSetViewer.java:4779)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:836)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$1(ResultSetDataReceiver.java:194)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:278)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)


```

**Comment by uslss** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14432)
- Test [SQL Editor: ResultSet](https://web.testquality.com/site/dbeaver/project/8805/runs/182307?resultId=3441957) in Run [23.2.0 Sybase CE](https://web.testquality.com/site/dbeaver/project/8805/runs/182307) (linked to Cycle [CE Sybase](https://web.testquality.com/site/dbeaver/project/8805/cycles/21959)).
