### ISSUE TITLE
[Sybase] Error appears on attemp to open Table Statistic Tab

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#21051]
### Description

Error appears on attemp to open Table Statistic Tab

### DBeaver Version

23.2.0

### Operating System

win10

### Database and driver

SQL Anywhere 16.0.0.2043

jConnect (TM) for JDBC (TM) jConnect (TM) for JDBC(TM)/16.0 SP03 PL02 (Build 27403)/P/EBF27518/JDK 1.6.0/jdbcmain/OPT/Mon Aug 28 18:41:14 PDT 2017

### Steps to reproduce

1. Open Table
2. Switch to statistic tab - check logs

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Aug 30 16:07:15 CEST 2023
SQL Anywhere Error -143: Column '@@maxpagesize' not found

com.sybase.jdbc4.jdbc.SybSQLException: SQL Anywhere Error -143: Column '@@maxpagesize' not found
	at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4201)
	at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3318)
	at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:302)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:284)
	at com.sybase.jdbc4.jdbc.SybStatement.queryLoop(SybStatement.java:2655)
	at com.sybase.jdbc4.jdbc.SybStatement.executeQuery(SybStatement.java:2641)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeQuery(SybPreparedStatement.java:274)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerGenericTable.readTableStats(SQLServerGenericTable.java:194)
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerGenericTable.getTableSize(SQLServerGenericTable.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$0(ObjectPropertyDescriptor.java:414)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:412)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:382)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

**Comment by LonwoLonwo** [comment]
Duplicate (or part) of https://github.com/dbeaver/dbeaver/issues/18718
