### ISSUE TITLE
[OceanBase] Execution plan is not shown because of an error

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#21063]
### Description

Pressing execution plan button leads to an error. It seems as something goes wrong with parsing of the JSON because manually executing `EXPLAIN FORMAT=JSON select * from table;` wroks.

### DBeaver Version

23.2.0

### Operating System

Any

### Steps to reproduce

1. Type a simple select in SQL Editor
2. Click `explain execution paln`

**Expected:** Execution plan is shown
**Actual:** Error is shown

### Additional context

```
java.io.EOFException: End of input at line 1 column 2 path $.
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1457)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:503)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at org.jkiss.dbeaver.ext.oceanbase.model.plan.OceanbasePlanJSON.<init>(OceanbasePlanJSON.java:57)
	at org.jkiss.dbeaver.ext.oceanbase.model.plan.OceanbasePlanAnalyzer.explain(OceanbasePlanAnalyzer.java:58)
	at org.jkiss.dbeaver.ext.oceanbase.model.plan.OceanbasePlanAnalyzer.planQueryExecution(OceanbasePlanAnalyzer.java:103)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:408)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:402)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=14435)
