### ISSUE TITLE
Aliases proposals for table with join

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#21077]
### Description

I see only `caai` alias proposal for this query
```
SELECT Id, Age, FirstName, LastName, Email, Phone
FROM Demo.dbo.CUSTOMERS caa
join Sales caai on ca|
```

### DBeaver Version

DBeaver 23.1.5

**Comment by E1izabeth** [comment]
Also I caught NPE
```
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "token" is null
	at org.jkiss.dbeaver.model.sql.parser.SQLIdentifierDetector.isQuoted(SQLIdentifierDetector.java:105)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.createCompletionProposal(SQLCompletionAnalyzer.java:1585)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromQueryParts(SQLCompletionAnalyzer.java:714)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:362)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:126)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:110)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:348)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
while testing this query
```
SELECT
 id AS MET_clienteRetornoBaseTempo
FROM
 CUSTOMERS sc_p
 LEFT JOIN Sales s_p ON s_p.id = sc_p.Id
 LEFT JOIN (
  SELECT
   *
  FROM MyTable mp
   LEFT JOIN db_backupoperator p ON p.codprod = mp.codprod
   LEFT JOIN sub_categorias sc ON sc.codscat = p.codscat
  WHERE sc.codscat = '02DN0U6K6F' --Coletar apenas ONUs
  ORDER BY mp.data_hora DESC
      ) mvp ON mvp.ID_servicoCliente = sc.codsercli
  where m|
```
