### ISSUE TITLE
Windows user folder with name containing space 

### ISSUE THREAD

**Issue by damianozucconi** [dbeaver/dbeaver#21102]
### Description

With latest version of DBeaver I get the following exception on startup:
!ENTRY org.eclipse.osgi 4 0 2023-09-04 09:14:40.327
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.jkiss.dbeaver.ui.app.standalone was unable to load class org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.jkiss.dbeaver.ui.app.standalone (265).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 13 more
Caused by: org.osgi.framework.BundleException: Exception in org.jkiss.dbeaver.ui.app.standalone.internal.CoreApplicationActivator.start() of bundle org.jkiss.dbeaver.ui.app.standalone.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 22 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 22: 
**file:/C:/Users/Damiano Zucconi.ISIPC/.eclipse/org.eclipse.equinox.security/secure_storage**
	at java.base/java.net.URI$Parser.fail(URI.java:2970)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3141)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3223)
	at java.base/java.net.URI$Parser.parse(URI.java:3171)
	at java.base/java.net.URI.<init>(URI.java:620)
	at java.base/java.net.URL.toURI(URL.java:1057)
	at org.jkiss.dbeaver.ui.app.standalone.internal.CoreApplicationActivator.useCustomSecretStorage(CoreApplicationActivator.java:174)
	at org.jkiss.dbeaver.ui.app.standalone.internal.CoreApplicationActivator.start(CoreApplicationActivator.java:107)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 29 more

all because my user folder contains a space in name. No problems with previous versions of DBeaver

### DBeaver Version

Community edition 23.2.0

### Operating System

Windows 11

**Comment by copierrj** [comment]
Workaround:

Create a text file at location $APPDATA/DBeaverData/secure/secure_storage with the following content:
`org.eclipse.equinox.security.preferences.version=1`

**Comment by Destrolaric** [comment]
Similar to https://github.com/dbeaver/dbeaver/issues/21099 closing as the duplicate, you can track issue resolution in the linked issue
