### ISSUE TITLE
The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by RobbertDM** [dbeaver/dbeaver#21117]
### Description

When connecting to Snowflake using the `externalbrowser` authenticator, DBeaver tells me "The BROWSE action is not supported on the current platform". There's no browser window popping up.

### DBeaver Version

23.2.0 CE (installed through snap)

### Operating System

Ubuntu 22.04 LTS with kernel 6.2.0-26-generic

### Database and driver

Snowflake driver 3.13.6 

### Steps to reproduce

1. Add new Snowflake connector
2. Fill in host, port, warehouse, username, role
3. For authenticator, select `externalbrowser`
4. Click `test connection`, or `ok` and try to connect

### Additional context

Stack trace:
```
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
2023-09-04 18:17:06.286 - The BROWSE action is not supported on the current platform!
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at net.snowflake.client.core.SessionUtilExternalBrowser$DefaultAuthExternalBrowserHandlers.openBrowser(SessionUtilExternalBrowser.java:62)
	at net.snowflake.client.core.SessionUtilExternalBrowser.authenticate(SessionUtilExternalBrowser.java:227)
	at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:371)
	at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:284)
	at net.snowflake.client.core.SFSession.open(SFSession.java:446)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:104)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:237)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:250)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:269)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:120)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeDataSource.<init>(SnowflakeDataSource.java:47)
	at org.jkiss.dbeaver.ext.snowflake.SnowflakeDataSourceProvider.openDataSource(SnowflakeDataSourceProvider.java:97)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1278)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2535)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

_Originally posted by @RobbertDM in https://github.com/dbeaver/dbeaver/issues/18949#issuecomment-1705508067_

**Comment by LonwoLonwo** [comment]
Hello @RobbertDM 

I'm not sure that we can help you from DBeaver side.
I see advice on the Internet like this one: https://stackoverflow.com/a/18004334
But you can see in the stack trace that method for browser opening is on the driver side:

> at net.snowflake.client.core.SessionUtilExternalBrowser$DefaultAuthExternalBrowserHandlers.openBrowser(SessionUtilExternalBrowser.java:62)

Also, I can see that they have something Linux-related in the code:

https://github.com/snowflakedb/snowflake-jdbc/blob/1e92087beb9733173554065f94cfe098f8b202f8/src/main/java/net/snowflake/client/core/SessionUtilExternalBrowser.java#L74

Could you please try to update your driver version?

You can do it in your Connection Settings -> Driver Settings -> Libraries -> Update

![2023-09-05 11_49_45-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/ff895dd9-31c4-4cf7-86b2-49cb1d1cb1f4)

**Comment by RobbertDM** [comment]
Thank you @LonwoLonwo for your fast and clear response :smile: 
I didn't notice there were newer versions. I updated to `3.14.1`, but the issue remains.
As you can see, I opened a new issue at the Snowflake JDBC repo, let's close this one :) Thanks a lot for your help!
