### ISSUE TITLE
Dbeaver would NOT start on RHEL 8 with SWT library issues

### ISSUE THREAD

**Issue by daxuyin** [dbeaver/dbeaver#21115]
### Description

DBeaver-ce has been installed on RHEL 8.8 kernel Linux 4.18.0-477.21.1.el8_8.x86_64, with snap, as described at https://snapcraft.io/install/dbeaver-ce/rhel

DBeaver wouldn't start and threw error such as:

!ENTRY org.eclipse.osgi 4 0 2023-09-04 08:56:03.023
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (153).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:362)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:338)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:182)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
       at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
        /home/ec2-user/.eclipse/org.jkiss.dbeaver.product_23.2.0_634681369_linux_gtk_x86_64/configuration/org.eclipse.osgi/143/0/.cp/libswt-gtk-4960r6.so: /home/ec2-user/.e
clipse/org.jkiss.dbeaver.product_23.2.0_634681369_linux_gtk_x86_64/configuration/org.eclipse.osgi/143/0/.cp/libswt-gtk-4960r6.so: failed to map segment from shared object
        no swt-gtk in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        no swt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        /home/ec2-user/.swt/lib/linux/x86_64/libswt-gtk-4960r6.so: /home/ec2-user/.swt/lib/linux/x86_64/libswt-gtk-4960r6.so: failed to map segment from shared object
        Can't load library: /home/ec2-user/.swt/lib/linux/x86_64/libswt-gtk.so
        Can't load library: /home/ec2-user/.swt/lib/linux/x86_64/libswt.so
        /home/ec2-user/.swt/lib/linux/x86_64/libswt-gtk-4960r6.so: /home/ec2-user/.swt/lib/linux/x86_64/libswt-gtk-4960r6.so: failed to map segment from shared object

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
        at org.eclipse.swt.internal.C.<clinit>(C.java:19)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:169)
        at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
        at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
        ... 31 more

I couldn't find corresponding packages/libraries such as libswt-gtk ... in RHEL 8 we have though.

Could anyone kindly help? Many thanks,

### DBeaver Version

23.2.0

### Operating System

RHEL 8.8

### Database and driver

N/A

### Steps to reproduce

Follow the steps described at:

https://snapcraft.io/install/dbeaver-ce/rhel

**Comment by riednyko** [comment]
Hi!
Is the EPEL repository added for rhel version 8 and not for 7?
Try to `yum update`
Also, please check the `libswt-gtk.so` library location

**Comment by arhayka** [comment]
It’s been a while since an update here. If the issue is still happening, please let us know and provide additional information.
