### ISSUE TITLE
Fix NPE on server output

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#21138]
### Description

When I execute the following in sql editor and Server Output is hidden from the bottom editor toolbar
```
do $$
begin
	RAISE debug 'debug';
	RAISE log 'log';
	RAISE notice 'notice';
	RAISE warning 'warning';
	RAISE info 'info';
end $$;
```
, I see the error
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolItem.getSelection()" because "toolItem" is null
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$ServerOutputReader.lambda$dumpOutput$0(SQLEditor.java:4756)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
```

### DBeaver Version

DBeaver 23.2.0

**Comment by E1izabeth** [comment]
Duplicate of #21086
