### ISSUE TITLE
Unable to open database file with dot-folder name in path

### ISSUE THREAD

**Issue by gary-1959** [dbeaver/dbeaver#21135]
### Description

My database file path is /home/gary/.somefolder/database.db
In the create connection dialogue .folders can not be accessed. Furthermore, typing the full path name leads to [SQLITE_CANTOPEN] Unable to open the database file (unable to open database file) error.

### DBeaver Version

Version 23.2.0.202309040911

### Operating System

ubuntu

### Database and driver

SQLite

### Steps to reproduce

Copy an SQLite database to a path with .folder in the path
Try and make a connection

### Additional context

Not a problem with Version 22.1.5

**Comment by Destrolaric** [comment]
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by eskatos** [comment]
Hi,
I stumbled upon what looks like the same problem. The sqlite file I'm trying to open is in `~/.something/`.

Here's what I get in the `dbeaver-debug.log`:
```
2024-01-19 18:28:47.768 - Connect with 'application.db' (sqlite_jdbc-18d22bd55fa-5ddb84aff5134451)
2024-01-19 18:28:47.768 - Execution context opened (application.db; Main; 1)
2024-01-19 18:28:47.778 - [SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)
org.sqlite.SQLiteException: [SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:81)
        at org.sqlite.core.DB.open(DB.java:216)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:287)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:106)
        at org.sqlite.JDBC.connect(JDBC.java:79)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:159)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:124)
        at org.jkiss.dbeaver.ext.sqlite.model.SQLiteDataSource.<init>(SQLiteDataSource.java:50)
        at org.jkiss.dbeaver.ext.sqlite.model.SQLiteMetaModel.createDataSourceImpl(SQLiteMetaModel.java:153)
        at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1315)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1163)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:960)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
        at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2486)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:226)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I can confirm that if I move the file outside this folder in a folder with no dot in the path, DBeaver successfully opens it.

I'm on Linux BTW.
Using Version 23.3.2.202401072024

FWIW I tried so use a symlink but that doesn't work around the problem. A hard link does obviously.

@E1izabeth, @n5a5, @Destrolaric, could you please consider reopening this issue?

**Comment by LonwoLonwo** [comment]
Hello @gary-1959

What driver version do you use? Looks like a driver issue. 
You can change it (downgrade or upgrade) manually like this:

![2024-01-25 16_35_52-DBeaver Ultimate 23 3 3 - InvoiceLine](https://github.com/dbeaver/dbeaver/assets/45152336/f04f4e34-c0b2-44cf-b113-c12fbc7128de)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
