### ISSUE TITLE
Deleting multiple databases causes ConcurrentModificationException

### ISSUE THREAD

**Issue by neoncik** [dbeaver/dbeaver#21150]
### Description

When deleting multiple DB (Postgres), ConcurrentModificationException is thrown sever times during deletion.

### DBeaver Version

23.2.0.202309041200

### Operating System

Windows 10

### Database and driver

Database - PostgreSQL 15.2
Driver - PostgreSQL JDBC Driver

### Steps to reproduce

Select many (like 10) DB and try to delete them.

**Comment by LonwoLonwo** [comment]
Hello @neoncik 

I can not reproduce it for now.

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by neoncik** [comment]
2023-09-07 17:16:10.362 - Connected (postgres-jdbc-187ac3b0c48-14e15491d6db31e4, PostgreSQL JDBC Driver [42.5.0])
2023-09-07 17:16:17.087 - java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.jkiss.dbeaver.runtime.jobs.KeepAlivePingJob.run(KeepAlivePingJob.java:55)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-09-07 17:16:22.915 - java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.jkiss.dbeaver.runtime.jobs.KeepAlivePingJob.run(KeepAlivePingJob.java:55)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment]
Thank you for bug report.

**Comment by E1izabeth** [comment]
I believe `databaseCache` for `PostgreDataSource` is not well synchronized. According to the code, it's possible that `clearCache` or `setCache` and reading are executed at the same time resulting.
