### ISSUE TITLE
[BigQuery] Error when SQL script task execute

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#21171]
### Description

1. create script for BigQuery, in my case it is a table creation script:
```sql
CREATE TABLE `dbeaver-db.mydataset.table`
(
  id INT64
)
OPTIONS(
  expiration_timestamp=TIMESTAMP "2023-11-09T22:51:45.698Z"
)
```
this script can be successfully executed from SQL Editor.
2. execute the script task

Error log:
```
2023-09-11 13:34:37.243 - SQL Scripts Execute
2023-09-11 13:34:37.245 - > Execute script [Scripts/Script-44.sql] in [BigQuery]
2023-09-11 13:34:37.245 - > Default catalog: dbeaver-db
2023-09-11 13:34:37.246 - 	Set JDBC connection auto-commit false
2023-09-11 13:34:37.247 - Execute queries (1)
2023-09-11 13:34:37.248 - -----------------> Execute query
CREATE TABLE `dbeaver-db.mydataset.element`
(
  element_id INT64
)
OPTIONS(
  expiration_timestamp=TIMESTAMP "2023-11-09T22:51:45.698Z"
)
2023-09-11 13:34:37.905 - -----------------> Time: 0ms
2023-09-11 13:34:37.905 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [100032] [HY000]: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: EXEC_JOB_EXECUTION_ERR
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeStatement(SQLScriptProcessor.java:229)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.lambda$0(SQLScriptProcessor.java:196)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.executeSingleQuery(SQLScriptProcessor.java:193)
	at org.jkiss.dbeaver.model.sql.exec.SQLScriptProcessor.runScript(SQLScriptProcessor.java:119)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.processScript(SQLScriptExecuteHandler.java:149)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:126)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.lambda$0(SQLScriptExecuteHandler.java:79)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:136)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeWithSettings(SQLScriptExecuteHandler.java:77)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeTask(SQLScriptExecuteHandler.java:66)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:131)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:97)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

23.2.0 EE

### Operating System

win10

**Comment by LonwoLonwo** [comment]
Probably, it is again transaction restriction as here was: https://github.com/dbeaver/pro/issues/1879
