### ISSUE TITLE
MySQL: Cannot connect - "Name is null"

### ISSUE THREAD

**Issue by thmsklngr** [dbeaver/dbeaver#21185]
### Description

Currently I experience a problem I can't explain myself. I try to connect to a MySQL5 Server and always get the error 'Internal error connecting to <Connection Name> -  Name is null'.
I tried both variants, MySQL5 and MySQL using the latest connector library 8.1, but no success so far. Using the mysql client from the command line is no problem and works. The connection is pretty straight forward, just IP, port and username, no SSL or other things in use.
Any ideas what I could try?

### DBeaver Version

Community edition  23.2.0.202309031556

### Operating System

Ubuntu 20.04

### Database and driver

5.7.6 CData MySQL Remoting

MySQL Connector 5.1.44
MySQL Connector 8.0.29
MySQL Connector 8.1.0

### Steps to reproduce

1. Configured the database connection (regardless if option URL or Hostname)
2. Connect to database

### Additional context

None

**Comment by E1izabeth** [comment]
Could you send the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by thmsklngr** [comment]
Hi,
here's the related part from the debug log:
```
2023-09-13 09:40:18.931 - Connect with 'jdbc:mysql://172.16.64.75:3306/' (mysql8-18a8d7bda67-1ef335e6594b3995)
2023-09-13 09:40:18.933 - Execution context opened (jdbc:mysql://172.16.64.75:3306/; Main; 3)
2023-09-13 09:40:20.159 - Can't get column 'ENGINE': Column 'ENGINE' not found.
2023-09-13 09:40:20.160 - Can't get column 'COMMENT': Column 'COMMENT' not found.
2023-09-13 09:40:20.160 - Can't get column 'SUPPORT': Column 'SUPPORT' not found.
2023-09-13 09:40:20.160 - Error initializing datasource
java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine$Support.valueOf(MySQLEngine.java:1)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.loadInfo(MySQLEngine.java:66)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.<init>(MySQLEngine.java:53)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initialize(MySQLDataSource.java:303)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1285)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-09-13 09:40:20.211 - Execution context closed (jdbc:mysql://172.16.64.75:3306/, 3)
2023-09-13 09:40:20.243 - Name is null
java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine$Support.valueOf(MySQLEngine.java:1)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.loadInfo(MySQLEngine.java:66)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.<init>(MySQLEngine.java:53)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.initialize(MySQLDataSource.java:303)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1285)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-09-13 09:40:32.086 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
```

**Comment by LonwoLonwo** [comment]
Hello @thmsklngr 

Could you please try to use the Old Connector, and if it is working - provide me a result of the 

`SHOW ENGINES`

query. 

I will use this info to fix

`at org.jkiss.dbeaver.ext.mysql.model.MySQLEngine.loadInfo(MySQLEngine.java:66)`

Thanks!

**Comment by LonwoLonwo** [comment]
Old connector:

![2023-09-13 11_20_03-DBeaver Ultimate 23 2 0 - _MySQL 5 5 1_ Script-83](https://github.com/dbeaver/dbeaver/assets/45152336/cf84b583-1107-4849-929f-8b36c5970961)

**Comment by thmsklngr** [comment]
Hi there,
I already wanted to reply that it works with SquirrelSQL 4.6.0.
The desired output is:
mysql_native_password	ACTIVE	AUTHENTICATION	GPL	

Btw, it is not a native MySQL database, it's a MySQL Connector:
MySQL Connector/J mysql-connector-j-8.1.0 (Revision: 7b6f9a337afe6ccb41823df485bf848ca7952b09)

And: the connection works properly with the old connector (the one shown above).

Regards, Thomas

**Comment by LonwoLonwo** [comment]
Could you please also provide results from this query:

`select SUPPORT from information_schema.ENGINES`

I'm trying to understand, what the unusual value in the SUPPORT column has in your database. I can't find anything in the documentation.

**Comment by thmsklngr** [comment]
Hi,
well, the output is not very promising:
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1003] [HY000]: The SQL statement 'SELECT [ENGINES].[SUPPORT] FROM [information_schema].[ENGINES] AS [ENGINES]' is not supported.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3940)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5142)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: The SQL statement 'SELECT [ENGINES].[SUPPORT] FROM [information_schema].[ENGINES] AS [ENGINES]' is not supported.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```
As mentioned earlier, it is not a real database, it's a connector acting like a MySQL DB. This piece of software is a translator between normal SQL and NoSQL and gets its data from a MongoDB.

Regards, Thomas

**Comment by LonwoLonwo** [comment]
Ok, thanks.

**Comment by LonwoLonwo** [comment]
Hello @thmsklngr 

Could you please check your case in the latest Early Acces DBeaver version https://dbeaver.io/files/ea/ ?

**Comment by thmsklngr** [comment]
I'm so sorry, I haven't had time to test the release you asked me for. But I guess this is obsolete now due to the official release of 23.2.1, right?

**Comment by E1izabeth** [comment]
@thmsklngr yes
