### ISSUE TITLE
SSL cert error on macOs connection to postgresql

### ISSUE THREAD

**Issue by RaulJMCD** [dbeaver/dbeaver#21253]
### Description

I can't connect to a remote postgresql database.
I can do it fine with pgAdmin but I can't do it with dBeaver.

This is the error log:
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_ES
Framework arguments:  -keyring /Users/rauljm/.eclipse_keyring -eclipse.keyring /Users/rauljm/Library/DBeaverData/secure/secure_storage
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/rauljm/.eclipse_keyring
```

org.jkiss.dbeaver.model
Error
Wed Sep 20 12:35:16 CEST 2023
Received fatal alert: handshake_failure
```

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:620)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:191)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.access$100(Driver.java:61)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:344)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### DBeaver Version

Version 23.2.0.202309041200

### Operating System

macOs Ventura Version 13.5.2

### Database and driver

1- postgresql 15
2- jdbc driver 
<img width="495" alt="image" src="https://github.com/dbeaver/dbeaver/assets/140697229/01874e44-cdf6-4a6c-b03b-e2039131151a">

### Steps to reproduce

1. Create an ssh connection with the terminal to open a port in local to access remote postgresql database
2. check the SHH connection is fine on itself. IT also works fine in configured in dbeaver when doing a test ssh connection.
3. create a simple postgresql conection to served port in local
4. get described error

**Comment by Destrolaric** [comment]
@RaulJMCD Hi, is your ssl certificate self-signed?

**Comment by RaulJMCD** [comment]
> @RaulJMCD Hi, is your ssl certificate self-signed?

Sorry for my lack of knowledge but, how can I know where to find the ssl certificate used in this workflow?

**Comment by Destrolaric** [comment]
@RaulJMCD Could you tell me which ssl mode is used for connection? It can be found on SSL configuration page
![image](https://github.com/dbeaver/dbeaver/assets/20579256/872d8ba0-5f03-4401-abc7-96e82bf00ac0)

**Comment by RaulJMCD** [comment]
It was empty, as in your picture.
But I selected the word allow and now is working!!!

this is my page right now.
![image](https://github.com/dbeaver/dbeaver/assets/140697229/037794b9-caec-4ede-9edf-390db81bca47)

Thanks a lot @Destrolaric , I tried very hard before posting this 😭

**Comment by Destrolaric** [comment]
@RaulJMCD, glad that helped. You can additionally ask your SysAdmin/DevOps(if you have one) regarding certificates for the DB. Closing the ticket for now.
