### ISSUE TITLE
NPE while generating DDL/ER diagram for more than 2/3 tables- Spanner - DBeaver Version 23.2.0.202309041200

### ISSUE THREAD

**Issue by venkyms** [dbeaver/dbeaver#21286]
### Description

Description 
NPE while generating DDL or creating ER diagram by selecting more than 3 tables. 

DB - Google spanner

Stacktrace while generating DDL
2023-09-22 19:29:45.697 - java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTable(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, String)" because "container" is null
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.findTable(GenericDataSource.java:647)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.fetchObject(ForeignKeysCache.java:131)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.fetchObject(ForeignKeysCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:351)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAssociations(GenericTableBase.java:282)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.sortTableList(DBStructUtils.java:234)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.generateTableListDDL(DBStructUtils.java:136)
	at org.jkiss.dbeaver.model.sql.generator.SQLGeneratorDDL.run(SQLGeneratorDDL.java:65)
	at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorDialog$1.lambda$0(SQLGeneratorDialog.java:119)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.generator.SQLGeneratorDialog$1.run(SQLGeneratorDialog.java:118)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Stacktrace while creating ER
2023-09-22 19:34:41.035 - Cannot invoke "org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTable(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, String)" because "container" is null
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTable(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, String)" because "container" is null
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.findTable(GenericDataSource.java:647)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.fetchObject(ForeignKeysCache.java:131)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.fetchObject(ForeignKeysCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:351)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAssociations(GenericTableBase.java:282)
	at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllAssociations(DBVUtils.java:329)
	at org.jkiss.dbeaver.erd.model.ERDContentProviderDefault.fillEntityFromObject(ERDContentProviderDefault.java:71)
	at org.jkiss.dbeaver.erd.ui.model.ERDContentProviderDecorated.fillEntityFromObject(ERDContentProviderDecorated.java:58)
	at org.jkiss.dbeaver.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:132)
	at org.jkiss.dbeaver.erd.model.ERDDiagram.fillEntities(ERDDiagram.java:288)
	at org.jkiss.dbeaver.erd.ui.navigator.DiagramCreateWizard$DiagramCreator.run(DiagramCreateWizard.java:175)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1658)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### DBeaver Version

Community edition 23.2.0

### Operating System

Macos Ventura 13.5.2

### Database and driver

Database name - Google Spanner
JDBC driver version - spanner_jdbc_official-1894501ec9f-639ab622aad85fd1, com.google.cloud.spanner.jdbc.JdbcDriver [2.0]

### Steps to reproduce

1. connect to the spanner DB
2. once the session is connected expand the table's sections
3. select at least 3 tables, right click -> generate SQL -> DDL -> error will popup
4. if not able to reproduce, select as many tables as possible and repeat step 3
5. Same way, select multiple tables -> right click ->  create new ER diagram -> error will popup

**Comment by LonwoLonwo** [comment]
Hello @venkyms 

Can you please provide footage showing your issue? Thank you.

**Comment by LonwoLonwo** [comment]
Ok, I see the reason. Then we read FK keys from the driver - DBeaver, expecting any schema name.
But it is empty for Spanner.
Probably, empty needs to be == DEFAULT for Spanner in DBeaver's code.

![2023-09-25 14_42_08-DBeaver Ultimate 23 2 1 - _Google Cloud Spanner - cloudspanner-sample_ Script-14](https://github.com/dbeaver/dbeaver/assets/45152336/845920b2-927b-4526-ae80-a44d24dc3a5f)

**Comment by venkyms** [comment]
Thanks, Team!
