### ISSUE TITLE
CE 23.2.1 Breaks Wayland support on Linux

### ISSUE THREAD

**Issue by Eonfge** [dbeaver/dbeaver#21299]
### Description

The latest version of DBeaver seems to have inadvertently regressed. Suddenly, X11 has become a hard dependency, although X11 is itself deprecated technology and it will be faced out over time.

```
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:302)
	at org.jkiss.awt.injector.ProxyInjector.injectBrowseInteraction(ProxyInjector.java:31)
	at org.jkiss.dbeaver.core.DBeaverActivator.injectProxyPeer(DBeaverActivator.java:80)
	at org.jkiss.dbeaver.core.DBeaverActivator.start(DBeaverActivator.java:74)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 30 more
```

[CE_23.2.1_CrashLogWayland.txt](https://github.com/dbeaver/dbeaver/files/12712082/CE_23.2.1_CrashLogWayland.txt)

The log has two start-ups: First with the default Wayland-first configuration, and then with wayland disabled.

### DBeaver Version

Community Edition 23.2.1

### Operating System

Fedora Linux 38, Flatpak

### Database and driver

Not applicable

### Steps to reproduce

Take the latest test-build from Flathub:
- https://github.com/flathub/io.dbeaver.DBeaverCommunity/pull/187
- Start on a Wayland-enabled platform
- Witness the crash
- (Optional) disable Wayland support and enable X11, see it start

**Comment by Destrolaric** [comment]
@Eonfge Thanks for the report. It was indeed unexpected behavior, and we are going to make a hotfix.

**Comment by Eonfge** [comment]
@Destrolaric Great to hear that you're this quick to fix the problem. 

I'm holding off the Flathub release for CE 23.2.1 so that none of your customers will experience any disruption.

**Comment by Eonfge** [comment]
32.2.2 has been released. Everything seems to be fine :+1:
