### ISSUE TITLE
Error Dump Database

### ISSUE THREAD

**Issue by Julien699** [dbeaver/dbeaver#21313]
### Description

Hello I have a bug which started since update 23.1.5 so I downgraded to version 23.1.4 the versions later than 23.1.5 we also have this problem it is still not resolved

Screenshot of the problem : https://snipboard.io/VqtlBn.jpg
![image](https://github.com/dbeaver/dbeaver/assets/28875055/e4a9d86f-d287-4f87-b090-b643e1c42e76)

### DBeaver Version

23.1.4

### Operating System

Windows 10 Pro 22H2 build : 19045.3448

### Database and driver

Database = MariaDB

Local Client : MySQL Binaries 8.0.19

library : mariadb-java-client.2.4.3.jar

Windows 10 Pro 22H2 build : 19045.3448

### Steps to reproduce

Just dump database with normal(no lock) at the end of the dump the error appears

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Julien699** [comment]
[logdbeaver.log](https://github.com/dbeaver/dbeaver/files/12716162/logdbeaver.log)

**Comment by E1izabeth** [comment]
Thank you.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.beep()" because the return value of "org.eclipse.swt.widgets.Display.getCurrent()" is null
	at org.jkiss.dbeaver.core.DesktopUI.notifyAgent(DesktopUI.java:164)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.notifyToolFinish(AbstractNativeToolHandler.java:251)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:291)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:85)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by henryka0** [comment]
Please is the above issue resolved? I just took a dump and i still get that error

**Comment by E1izabeth** [comment]
This issue was resolved. The fix will be available in the next release.

**Comment by henryka0** [comment]
okay will be on standby
