### ISSUE TITLE
DBeaver Community Edition Cannot Connect to DuckDB

### ISSUE THREAD

**Issue by mattgiles** [dbeaver/dbeaver#21353]
### Description

When connecting to a DuckDB database using DBeaver CE, upon "Test Connection..." I get the following error:

```
Invalid Error: TransactionContext Error: Failed to commit: INTERNAL Error: Unsupported catalog type for ToSQL()
```

### DBeaver Version

Community Edition 23.2.1.202309260508

### Operating System

macOS 13.3.1 (a) (22E772610a)

### Database and driver

1. DuckDB v0.9.0 (0d84ccf478)
2. DuckDB JDBC Driver 0.9.0

### Steps to reproduce

1. Launch the "Connect to a database" dialogue
2. Select DuckDB
3. Select DuckDB db file
4. Press "Test Connection..."

**Comment by LonwoLonwo** [comment]
Hello @mattgiles 

I can't reproduce it, for now. Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide the log files.

**Comment by kafran** [comment]
Upgrading to DBeaver 23.2.3 fix the problem.

**Comment by yoonghm** [comment]
I am using duckdb 0.10.2 and DBeaver community edition 24.1.0.202406021658.
I understand that duckdb version 0.10 have different file format before its version. See https://duckdb.org/docs/internals/storage.html

I have this error:

java.sql.SQLException: Serialization Error: Failed to deserialize: expected end of object, but found field id: 103
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:48)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:38)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:159)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:124)
	at org.jkiss.dbeaver.ext.duckdb.model.DuckDBDataSource.<init>(DuckDBDataSource.java:38)
	at org.jkiss.dbeaver.ext.duckdb.model.DuckMetaModel.createDataSourceImpl(DuckMetaModel.java:155)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1381)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1245)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1035)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2505)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:94)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:78)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


I tried new connection to a `:memory:` and an empty file database, and both are working. Then, the issue is linked to the data itself. How could I troubleshoot then?
