### ISSUE TITLE
Dbeaver crashes at startup after running a long script failed

### ISSUE THREAD

**Issue by sskandhaprasad** [dbeaver/dbeaver#21428]
### Description

When I open DBeaver, i see the splash screen for a few seconds and then it crashes. I have pasted the debug logs below. Before it got crashed, i was running a long MySQL script (~22mb) and DBeaver was midway through finishing that script. The script had a couple of errors in between and i kept skipping the errors. After I skipped the third time, DBeaver was completely frozen and the only thing i could do was closing it after waiting for about 5 mins.

From the next time i opened, DBeaver doesn't startup and shows the same startup error. I also tried restarting my windows machine without any luck. Post this, i tried installing the latest version - 23.2.1 and it didn't solve my problem.

Can i please get some help here? I have over 50 database server connections in dbeaver and cannot afford to lose them. I am not really interested in recovering the unsaved script (as per the log below). Is there a way to reset / remove the unsaved file so that DBeaver restarts without trying to recover that file?

![image](https://github.com/dbeaver/dbeaver/assets/1020753/2185c350-ba8b-46b1-a0b0-718ae3b19b34)

```!SESSION 2023-10-04 20:03:09.651 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2023-10-04 20:03:13.144
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.osgi 4 0 2023-10-04 20:03:54.747
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1278)
	at org.eclipse.swt.widgets.Display.internal_new_GC(Display.java:2711)
	at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:268)
	at org.eclipse.swt.graphics.TextLayout.getLineCount(TextLayout.java:1918)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:1270)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:908)
	at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:298)
	at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:7833)
	at org.eclipse.swt.custom.StyledText.setForeground(StyledText.java:8807)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeViewerColors(AbstractTextEditor.java:3920)
	at org.eclipse.ui.texteditor.AbstractTextEditor.handlePreferenceStoreChanged(AbstractTextEditor.java:4537)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.handlePreferenceStoreChanged(AbstractDecoratedTextEditor.java:905)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.handlePreferenceStoreChanged(SQLEditorBase.java:245)
	at org.eclipse.ui.texteditor.AbstractTextEditor$PropertyChangeListener.propertyChange(AbstractTextEditor.java:720)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:325)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:322)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.lambda$0(ScopedPreferenceStore.java:171)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:841)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:844)
	at org.eclipse.core.internal.preferences.EclipsePreferences.remove(EclipsePreferences.java:951)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1448)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1442)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.lambda$0(PartRenderingEngine.java:1431)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
	at org.eclipse.swt.widgets.Display.release(Display.java:3691)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:324)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:340)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	Suppressed: org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.addDisposeListener(org.eclipse.swt.events.DisposeListener)" because the return value of "org.eclipse.ui.IWorkbenchWindow.getShell()" is null)
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
		at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
		at org.eclipse.swt.widgets.Display.release(Display.java:3720)
		... 14 more
	Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.addDisposeListener(org.eclipse.swt.events.DisposeListener)" because the return value of "org.eclipse.ui.IWorkbenchWindow.getShell()" is null
		at org.jkiss.dbeaver.core.WorkbenchContextListener.listenWindowEvents(WorkbenchContextListener.java:103)
		at org.jkiss.dbeaver.core.WorkbenchContextListener.<init>(WorkbenchContextListener.java:61)
		at org.jkiss.dbeaver.core.WorkbenchContextListener.registerInWorkbench(WorkbenchContextListener.java:265)
		at org.jkiss.dbeaver.core.DesktopUI$1.lambda$0(DesktopUI.java:140)
		at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
		... 17 more
	Suppressed: org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
		at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
		at org.eclipse.swt.widgets.Display.release(Display.java:3720)
		... 14 more
	Caused by: org.eclipse.swt.SWTException: Widget is disposed
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.SWT.error(SWT.java:4804)
		at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
		at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
		at org.eclipse.swt.widgets.Control.removePaintListener(Control.java:2853)
		at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.setInput(DatabaseNavigatorTree.java:316)
		at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.lambda$0(NavigatorViewBase.java:110)
		at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:68)
		at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
		... 17 more
	Suppressed: org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
		at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
		at org.eclipse.swt.widgets.Display.release(Display.java:3720)
		... 14 more
	Caused by: org.eclipse.swt.SWTException: Widget is disposed
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.SWT.error(SWT.java:4804)
		at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
		at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
		at org.eclipse.swt.custom.CTabFolder.setFont(CTabFolder.java:2697)
		at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyCurrentPresentationThemeSettings(ResultSetViewer.java:452)
		at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$4(ResultSetViewer.java:450)
		at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
		at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
		at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
		... 17 more
	Suppressed: org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.custom.StyledText.setFont(org.eclipse.swt.graphics.Font)" because the return value of "org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutputConsoleViewer.getTextWidget()" is null)
		at org.eclipse.swt.SWT.error(SWT.java:4918)
		at org.eclipse.swt.SWT.error(SWT.java:4833)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
		at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
		at org.eclipse.swt.widgets.Display.release(Display.java:3720)
		... 14 more
	Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.custom.StyledText.setFont(org.eclipse.swt.graphics.Font)" because the return value of "org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutputConsoleViewer.getTextWidget()" is null
		at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutputConsoleViewer.refreshStyles(SQLEditorOutputConsoleViewer.java:125)
		at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutputViewer.refreshStyles(SQLEditorOutputViewer.java:122)
		at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.reloadSyntaxRules(SQLEditor.java:3202)
		at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.onDataSourceChange(SQLEditor.java:2765)
		at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:68)
		at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
		at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
		... 17 more

!ENTRY org.jkiss.dbeaver.model 2 0 2023-10-04 20:03:54.907
!MESSAGE Listener 'org.jkiss.dbeaver.ui.actions.datasource.DataSourceToolbarHandler@35e3da2d' is not unregistered from DBM model

!ENTRY org.jkiss.dbeaver.model 2 0 2023-10-04 20:03:54.911
!MESSAGE Some project listeners are still register: [org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchWindowAdvisor@64d1c30b]

!ENTRY org.jkiss.dbeaver.model 2 0 2023-10-04 20:03:54.913
!MESSAGE Some datasource registry listeners are still registered: [org.jkiss.dbeaver.ui.actions.datasource.DataSourceToolbarHandler@35e3da2d]

!ENTRY org.eclipse.core.jobs 2 2 2023-10-04 20:03:56.426
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.runtime.jobs.ConnectJob```

### DBeaver Version

23.0.2

### Operating System

Windows 11

### Database and driver

_No response_

### Steps to reproduce

_No response_

### Additional context

### Extensions: ###

I have not installed any extensions other than ones that came with the official installation.

**Comment by sskandhaprasad** [comment]
I finally managed to sort this out. I do not know what caused this and do not know the file where the unsaved scripts are stored, i did the below to restore, in case someone else stumbles on to the same problem:

1. Copied %AppData%/DBeaverData to a different folder.
2. Removed %AppData%/DBeaverData
3. Started DBeaver. It launched successfully this time. It also recreated the DBeaverData folder. I then closed DBeaver
5. I then copied the following folders from my backup to the new DBeaverData folder:
4.1 `drivers`
4.2 `workspace6/General/.dbeaver`
4.3 `workspace6/General/Scripts`
4.4 `workspace6/General/.dbeaver-data-sources.xml`
4.5 `workspace6/General/Diagrams`
4.6 `workspace6/.metadata/.config`

Doing this restored all the connections and drivers. It still wouldn't show the list of scripts and diagrams within the tool. I had to go to Projects View (Windows - Show View - Projects) -> Expand the project -> Right click on scripts (and diagrams) -> Refresh. Doing this also populated the scripts.

**Comment by serjiokov** [comment]
Require to fix NPE first.

**Comment by sagitarriuss** [comment]
For me, just a deletion of this file has resolved the DBeaver crash:
C:\Users\<user>\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi

All my app settings were preserved except the recent editors list and previously opened work files/tables.

**Comment by saifobeidat** [comment]
Fixed by deleting `C:\Users<user>\AppData\Roaming\DBeaverData`
