### ISSUE TITLE
Receiving error when connecting to Salesforce

### ISSUE THREAD

**Issue by cvoge** [dbeaver/dbeaver#21430]
### Description

We are receiving an error when trying to connect to Salesforce. Using the Reliersoft driver

Cannot connect to url, exception: java.sql.SQLException: Update check failed for sforce-jdbc-0.4.203.

![image](https://github.com/dbeaver/dbeaver/assets/9285531/b6e7f01c-3876-4667-b29f-08d62ae27d70)

### DBeaver Version

23.2.1.202309260508

### Operating System

Windows 10

### Database and driver

Reliersoft driver.  sforce-jdbc.jar
[sforce-jdbc.zip](https://github.com/dbeaver/dbeaver/files/12806487/sforce-jdbc.zip)

### Steps to reproduce

Add Reliersoft driver through Driver Manager. 
![image](https://github.com/dbeaver/dbeaver/assets/9285531/f524b2ca-c206-4d60-8cd7-21d3ae02508f)

Add New DB Connection using new driver.
Entered Salesforce credentials and clicked Test Connection.

### Additional context

Stacktrace:

java.sql.SQLException: Cannot connect to url, exception: java.sql.SQLException: Update check failed for sforce-jdbc-0.4.203.
	at com.reliersoft.sforce.jdbc.f.<init>(Unknown Source)
	at com.reliersoft.sforce.jdbc.Driver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:237)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:250)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:269)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:120)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1278)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ShadelessFox** [comment]
Hello @cvoge,

Judging by the stack trace, something is wrong on the driver side. Additionally, you're using a third-party driver that is not available in DBeaver.

Try googling the error or contact the driver's developer.
