### ISSUE TITLE
Can't Establish a new Athena connection from dBeaver CE

### ISSUE THREAD

**Issue by adbdkb** [dbeaver/dbeaver#21446]
### Description

I am trying to set-up a new Athena connection from dBeaver CE on my Mac.  I am behind a proxy.

How can I setup the connection so I can use dBeaver to connect to Athena ?

I have added these properties under Driver Properties Tab. 

Ref:https://github.com/dbeaver/dbeaver/issues/3918#issuecomment-511484596

> - AwsCredentialsProviderClass to com.simba.athena.amazonaws.auth.profile.ProfileCredentialsProvider
> - AwsCredentialsProviderArguments

<img width="500" alt="image" src="https://github.com/dbeaver/dbeaver/assets/26495406/70a520bc-6a29-4b0b-82ae-dad415a90cf3">

When I do Test Connection I get the following error

[Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: Connection reset [Execution ID not available]
  Unable to execute HTTP request: Connection reset
  Unable to execute HTTP request: Connection reset
    Connection reset
    Connection reset

Thanks

### DBeaver Version

dBeaver Community Edition Version 23.2.1.202309260508 

### Operating System

macOS Ventura 13.6 (22G120)

### Database and driver

DB - AWS Athena 
Driver- com.simba.athena.jdbc42.Driver

<img width="913" alt="Screenshot 2023-10-05 at 7 28 01 PM" src="https://github.com/dbeaver/dbeaver/assets/26495406/a2e8138a-7948-4c0b-84ac-45d3de2c94a3">

### Additional context

Behind a proxy

**Comment by adbdkb** [comment]
Sorry, the driver is - com.simba.athena.jdbc42.Driver

<img width="913" alt="Screenshot 2023-10-05 at 7 28 01 PM" src="https://github.com/dbeaver/dbeaver/assets/26495406/875fceb7-d56a-461e-8e38-cdc21b4e76d4">

**Comment by LonwoLonwo** [comment]
Hello @adbdkb 

Did you try to configure something in the Proxy tab?

![2023-10-06 08_46_28-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/1fcc9458-f6fb-424c-b621-33b44fb8dccc)

**Comment by adbdkb** [comment]
Yes, I had.  But my tab loos a little different.  it doesn't have the checkboxes you have in the above image.

This is what I get

![image](https://github.com/dbeaver/dbeaver/assets/26495406/09cb5f9a-ed4c-45f0-80e8-1784600cd6db)

**Comment by adbdkb** [comment]
Also, just realised where I can get more details for the error below.

```
[Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: Connection reset [Execution ID not available]
  Unable to execute HTTP request: Connection reset
  Unable to execute HTTP request: Connection reset
    Connection reset
    Connection reset
```

This is what I saw in the log tab for the error - if this gives any clue

```
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at com.simba.athena.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.simba.athena.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.simba.athena.amazonaws.http.conn.$Proxy32.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.simba.athena.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.doInvoke(AmazonAthenaClient.java:2570)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2537)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2526)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.executeStartQueryExecution(AmazonAthenaClient.java:2050)
	at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.startQueryExecution(AmazonAthenaClient.java:2019)
	at com.simba.athena.athena.api.AJClient.executeQuery(Unknown Source)
	at com.simba.athena.athena.api.AJClient.checkAthenaConnection(Unknown Source)
	at com.simba.athena.athena.api.AJClient.<init>(Unknown Source)
	at com.simba.athena.athena.core.AJConnection.connect(Unknown Source)
	at com.simba.athena.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.simba.athena.jdbc.common.AbstractDriver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:237)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:250)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:269)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:120)
	at org.jkiss.dbeaver.ext.athena.model.AthenaDataSource.<init>(AthenaDataSource.java:40)
	at org.jkiss.dbeaver.ext.athena.AthenaDataSourceProvider.openDataSource(AthenaDataSourceProvider.java:57)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1278)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by adbdkb** [comment]
@LonwoLonwo LonwoLonwo - Any update on this?  Is there anything else I can try?

Thanks

**Comment by hrimthrusa** [comment]
Hi, could you try to use another port apart from 8080. Make sure is it open while you're at it.

[Here](https://github.com/dbeaver/dbeaver/wiki/Proxy-configuration) is the wiki page on this matter.

**Comment by adbdkb** [comment]
Hi, I tried to read the doc, but have a question.  I am presuming the port needs to be open on the proxy server, correct?  How can I check what port is open on that server ?  

Thanks

**Comment by flambchap** [comment]
@adbdkb It depends on the OS you use on your proxy server. What OS do you use?

**Comment by adbdkb** [comment]
Operating System

macOS Ventura 13.6 (22G120)

**Comment by ShadelessFox** [comment]
Is your proxy configuration system-wide, or do you need to explicitly specify its settings in applications you would like to use that proxy? Can you please provide more information about your environment?

**Comment by adbdkb** [comment]
The proxy is systemwide.  What other information should I provide?  Let me know and I will add it here

Thanks

**Comment by Matvey16** [comment]
@adbdkb This seems to be a problem with the proxy itself. I've tried replicating it on our athena instance with additional proxy and wasn't able to reproduce it. Have you tried connecting to your server using other tools with the same proxy?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
