### ISSUE TITLE
Oracle 8 connection support

### ISSUE THREAD

**Issue by javifelices** [dbeaver/dbeaver#21451]
### Description

We have an environment of many computers with their respective databases in Oracle 11 and Oracle 8.

We are able to connect to the Oracle 11 ones without any problem, but not to the Oracle 8 ones, the following message appears

![photo_2023-10-06_11-04-20](https://github.com/dbeaver/dbeaver/assets/3685015/91aca4a4-1cc4-4628-aff8-7203a147edee)

Attached is a concrete log.

```
2023-10-06 10:52:04.860 - Auth model 'native' was replaced by 'oracle_native'
2023-10-06 10:52:04.876 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2023-10-06 10:52:27.295 - Connect with 'jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.17.7.1 )(PORT = 1521)) ) (CONNECT_DATA = (SERVICE_NAME = TP ) ) )' (oracle_thin-18b04302a0d-1f3f9a20f4e56070)
2023-10-06 10:52:27.295 - Execution context opened (jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.17.7.1 )(PORT = 1521)) ) (CONNECT_DATA = (SERVICE_NAME = TP ) ) ); Main; 32)
2023-10-06 10:52:27.869 - Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
  at oracle.jdbc.driver.T4C8TTIdty.<init>(T4C8TTIdty.java:550)
  at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1542)
  at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
  at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
  at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
  at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:237)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:250)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:269)
  at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:176)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:123)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:107)
  at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
  at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:94)
  at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:143)
  at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1278)
  at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1117)
  at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
  at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
  at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
  at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I also include logs of two machines with Oracle 11 that connect without problems

```
2023-10-06 11:14:22.267 - Connect with 'stp0001' (oracle_thin-1895d73ed13-39d0f2f427db551f)
2023-10-06 11:14:22.268 - Execution context opened (stp0001; Main; 35)
2023-10-06 11:14:22.533 - Connected (oracle_thin-1895d73ed13-39d0f2f427db551f, Oracle JDBC driver [12.2.0.1.0])
2023-10-06 11:14:35.231 - Execution context closed (stp0001, 35)
2023-10-06 11:14:35.231 - Disconnected (oracle_thin-1895d73ed13-39d0f2f427db551f)
2023-10-06 11:14:39.909 - Connect with 'stp0227' (oracle_thin-1895d7cb0ef-4e000a5831103d9e)
2023-10-06 11:14:39.910 - Execution context opened (stp0227; Main; 36)
2023-10-06 11:14:40.902 - Connected (oracle_thin-1895d7cb0ef-4e000a5831103d9e, Oracle JDBC driver [12.2.0.1.0]
```

Thank you very much for your attention.

### DBeaver Version

Communi Edition 23.2.1

### Operating System

Windows 10 x64 Pro

### Database and driver

There are machines with Oracle 11, where there are no connection problems, there are machines with Oracle 8.

### Steps to reproduce

I pass on these two screenshots.

I made a copy of a connection, changed the host and ip, from a machine with oracle 11 and another one with oracle 8 as well.

### Additional context

We use VPN, but as I say, with Oracle 11, no problems.

**Comment by Matvey16** [comment]
@javifelices Hello. Can you specify if you can't connect to any Oracle 8 instance from any machine, but can connect to Oracle 11 from those machines? Also have you checked if those servers are accessible by other means for example cmd?

**Comment by javifelices** [comment]
@Matvey16 

I can connect from my local machine with sqlplusw to Oracle 8 and Oracle 11 machines without problems.

The directory structure I have, is a folder called Oracle, inside C:, and then 3 subfolders, the Oracle 11 instant client, Oracle 8.1 and a folder with Scripts

c:\oracle
|
| ------ instanclient_11_2
|
| ------ Ora81
|
| ------ SCRIPTS
|

We could say that it is a portable installation, with its respective changes in the environment variables.

Thank you very much

**Comment by LonwoLonwo** [comment]
Hello @javifelices 

What driver version do you use? You can check it it your connection settings -> Test connection

**Comment by javifelices** [comment]
Hello @LonwoLonwo

The driver used is Oracle

oracle.jdbc.OracleDriver

Thank you very much for the work and the trouble.

I attach this screenshot in case it provides more information

![photo_2023-10-19_17-35-56](https://github.com/dbeaver/dbeaver/assets/3685015/cf2d148e-6cc6-4254-82f7-7ca7f63e2639)

**Comment by LonwoLonwo** [comment]
Did you check that you have the correct Service Name/SID for your connection?

Also, maybe driver changing can help? 

![2023-10-19 12_35_56-DBeaver 23 2 3 - ZSYTAB2605](https://github.com/dbeaver/dbeaver/assets/45152336/8dbb1599-3ebb-4ae1-9306-965e20145de6)

**Comment by javifelices** [comment]
I don't know if you were able to see the screenshot before editing my comment, I'm putting it back.

I attach some more data, removing the sensitive data :)

With Oracle 11 DBs everything works without problems, only with Oracle 8 DBs, there is no problem, I could try some other driver without problem, I will see the multiple options and I will comment if I get any of them to work.

If I think I can contribute some more information or data I will do it with pleasure.

![photo_2023-10-19_17-35-56](https://github.com/dbeaver/dbeaver/assets/3685015/83556da4-e6be-4a39-8d92-534674bc331a)

![photo_2023-10-19_18-34-45](https://github.com/dbeaver/dbeaver/assets/3685015/0a6b3852-105c-4ff0-b79f-c8076ea527d4)

![dbeaver-driver](https://github.com/dbeaver/dbeaver/assets/3685015/82695e40-462d-442a-97c1-16d168dbd8a4)

**Comment by javifelices** [comment]
To add some more information, I have tried other types of drivers without success, it may also be a configuration problem, because in a couple of them, I configured port 1521, but when I did the test it indicated port 1443, I will continue to do some testing.

I leave some more screenshots of how we connected.

![dbeaver_sLqZ7Pk3gY](https://github.com/dbeaver/dbeaver/assets/3685015/3733fbf3-9f93-4b0c-b4e3-8b0d9ce96f3c)

**Comment by LonwoLonwo** [comment]
DBeaver tries to support all available database server versions. Yes. But sometimes, it takes work to support ancient versions. 

It is tough to do this when the vendor himself and his drivers support the old versions of their servers only partially. We have allocated a certain amount of resources to solve this issue now. Still, our resources are also limited, and we want to understand how relevant this issue is for our community. Therefore, I hang on to this ticket with the "Wait for votes" label. All interested in this issue can vote with any emoji on the original message.
