### ISSUE TITLE
I'm unable to use GPT getting multiple error message when I click translate

### ISSUE THREAD

**Issue by IrshadSalik** [dbeaver/dbeaver#21554]
### Description

![image](https://github.com/dbeaver/dbeaver/assets/79840486/7351e70e-9915-44e3-bf0e-8b0c0702e203)

### DBeaver Version

Community Edition 23.2.2.202310081633

### Operating System

Windows 10

### Database and driver

Microsoft SQL Server

### Steps to reproduce

1. I created MS SQL database & connected to my database
2. Installed GPT extension
3. Clicked GPT Icon, provided text
4. Clicked Translate

**Comment by LonwoLonwo** [comment]
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by E1izabeth** [comment]
Is the database you're trying to work with huge or tiny?

**Comment by IrshadSalik** [comment]
> Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank yo

I need sometime to provide comments. Thanks.

**Comment by IrshadSalik** [comment]
> Is the database you're trying to work with huge or tiny?

It's huge.

**Comment by IrshadSalik** [comment]
> Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

[.log](https://github.com/dbeaver/dbeaver/files/12987720/default.log)
Kindly find attached log file for your reference.

**Comment by E1izabeth** [comment]
Thank you.

The most interesting parts of the log:
```

!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-16 17:26:23.187
!MESSAGE Cannot invoke "String.length()" because "<parameter1>" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
	at java.base/java.lang.AbstractStringBuilder.<init>(Unknown Source)
	at java.base/java.lang.StringBuilder.<init>(Unknown Source)
	at org.jkiss.dbeaver.model.ai.completion.AbstractAICompletionEngine.processCompletion(AbstractAICompletionEngine.java:141)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.requestCompletion(OpenAICompletionEngine.java:180)
	at org.jkiss.dbeaver.model.ai.completion.AbstractAICompletionEngine.performQueryCompletion(AbstractAICompletionEngine.java:50)
	at org.jkiss.dbeaver.ui.editors.sql.ai.internal.AITranslateHandler.lambda$0(AITranslateHandler.java:172)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$17(UIUtils.java:1815)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
	
	. . .
	
!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-16 17:30:53.617
!MESSAGE HTTP 400 
!STACK 0
retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:218)
	at com.theokanning.openai.service.OpenAiService.createChatCompletion(OpenAiService.java:93)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.getCompletionChoices(OpenAICompletionEngine.java:360)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.callCompletion(OpenAICompletionEngine.java:244)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.requestCompletion(OpenAICompletionEngine.java:176)
	at org.jkiss.dbeaver.model.ai.completion.AbstractAICompletionEngine.performQueryCompletion(AbstractAICompletionEngine.java:50)
	at org.jkiss.dbeaver.ui.editors.sql.ai.internal.AITranslateHandler.lambda$0(AITranslateHandler.java:172)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$17(UIUtils.java:1815)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
 
 . . .
 
!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-16 17:31:47.521
!MESSAGE NullPointerException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-10-16 17:31:47.521
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException

. . . 

!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-16 17:33:26.620
!MESSAGE HTTP 400 
!STACK 0
retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:218)
	at com.theokanning.openai.service.OpenAiService.createChatCompletion(OpenAiService.java:93)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.getCompletionChoices(OpenAICompletionEngine.java:360)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.callCompletion(OpenAICompletionEngine.java:244)
	at org.jkiss.dbeaver.model.ai.openai.OpenAICompletionEngine.requestCompletion(OpenAICompletionEngine.java:176)
	at org.jkiss.dbeaver.model.ai.completion.AbstractAICompletionEngine.performQueryCompletion(AbstractAICompletionEngine.java:50)
	at org.jkiss.dbeaver.ui.editors.sql.ai.internal.AITranslateHandler.lambda$0(AITranslateHandler.java:172)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$17(UIUtils.java:1815)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
	
. . . 
	
!ENTRY org.eclipse.ui 4 0 2023-10-17 11:59:18.966
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkParent(Widget.java:299)
	at org.eclipse.swt.widgets.Widget.<init>(Widget.java:165)
	at org.eclipse.swt.widgets.Item.<init>(Item.java:76)
	at org.eclipse.swt.widgets.TreeItem.<init>(TreeItem.java:178)
	at org.eclipse.swt.widgets.TreeItem.<init>(TreeItem.java:145)
	at org.jkiss.dbeaver.ui.editors.sql.ai.popup.AISuggestionPopup$ScopeConfigDialog.lambda$0(AISuggestionPopup.java:437)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.AbstractPopupPanel.open(AbstractPopupPanel.java:93)
	at org.jkiss.dbeaver.ui.editors.sql.ai.internal.AITranslateHandler.execute(AITranslateHandler.java:135)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

. . . 

!ENTRY org.eclipse.ui 4 0 2023-10-17 11:59:54.220
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Tree.getItems(Tree.java:3391)
	at org.jkiss.dbeaver.ui.editors.sql.ai.popup.AISuggestionPopup$ScopeConfigDialog$2.lambda$0(AISuggestionPopup.java:396)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	
```

**Comment by serge-rider** [comment]
It is a bug in 23.2.2

**Comment by MashaKorax** [comment]
@IrshadSalik , we fixed it and now you can download the AI ​​plugin from the early access link https://dbeaver.io/files/ea/update/ce/

**Comment by IrshadSalik** [comment]
> @IrshadSalik , we fixed it and now you can download the AI ​​plugin from the early access link https://dbeaver.io/files/ea/update/ce/

It's working for small database but for huge database getting error 
"This model's maximum context length is 4097 tokens. However, your messages resulted in 12837 tokens. Please reduce the length of the messages.
  HTTP 400 
  HTTP 400 
"
