### ISSUE TITLE
DBeaver connect to clickhouse server error

### ISSUE THREAD

**Issue by caopeng-pacvue** [dbeaver/dbeaver#21582]
### Description

I used clickhouse driver version 0.4.6
![clickhouse驱动版本](https://github.com/dbeaver/dbeaver/assets/131741625/569f34fd-7e92-4ab2-be1c-58a6a1dd2ed8)
An error occurred while testing the connection
![connect_error](https://github.com/dbeaver/dbeaver/assets/131741625/8204fd73-caa9-4214-989d-2cdac303e407)

### DBeaver Version

23.1.0

### Operating System

Windows11

### Database and driver

1. clickhouse server version 21.13+
2. clickhouse driver version  com.clickhouse.xxx. 0.4.6

**Comment by LonwoLonwo** [comment]
Hello @caopeng-pacvue 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by caopeng-pacvue** [comment]
Hi LonwoLonwo，here is log
!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-19 18:28:31.486
!MESSAGE Unexpected end of file from server
!STACK 0
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:116)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:200)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:168)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseDataSource.<init>(ClickhouseDataSource.java:71)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseMetaModel.createDataSourceImpl(ClickhouseMetaModel.java:55)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1206)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1071)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-10-19 18:29:27.577
!MESSAGE Unexpected end of file from server
!STACK 0
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:116)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:200)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:168)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:242)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:274)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseDataSource.<init>(ClickhouseDataSource.java:71)
	at org.jkiss.dbeaver.ext.clickhouse.model.ClickhouseMetaModel.createDataSourceImpl(ClickhouseMetaModel.java:55)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1206)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1071)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2023-10-19 19:07:08.790 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by LonwoLonwo** [comment]
As I can see here - It can be anything https://stackoverflow.com/questions/19824339/java-simple-code-java-net-socketexception-unexpected-end-of-file-from-server

Are you sure that this is DBeaver issue? Did you try to connect via cli or other tools?

**Comment by caopeng-pacvue** [comment]
Yes, I saw the blog too, but I was able to connect using DataGrip with the same parameters, but not dbeaver.

**Comment by LonwoLonwo** [comment]
Ok. Please provide a screen from your connection settings page.

**Comment by caopeng-pacvue** [comment]
Now that I've dropped dbeaver to 22.1.3, it works fine, but when I see a clickhouse table field with a Bool value, I get a hint that it's an unsupported type, so I want to upgrade dbeaver. You can't connect to clickhouse server after upgrading to a higher version (e.g. 23.1.0/23.2.2)
![main-setting](https://github.com/dbeaver/dbeaver/assets/131741625/6abfe891-5f7d-4b1c-8dea-5154539a1931)
![driver-setting](https://github.com/dbeaver/dbeaver/assets/131741625/2fb67af8-0e82-467b-8d8a-93878930d92b)

**Comment by LonwoLonwo** [comment]
Could you please try to downgrade your driver then? To 0.4.2 or lower. And connect again.

![2023-10-19 12_35_56-DBeaver 23 2 3 - ZSYTAB2605](https://github.com/dbeaver/dbeaver/assets/45152336/85aa8ff9-4d36-4381-91fe-bc433a4a82c5)

(picture for DB2i, but the meaning is the same)

**Comment by caopeng-pacvue** [comment]
Yes, but it doesn't seem to be working. Maybe you can simulate an environment that connects to clickhouse?

**Comment by LonwoLonwo** [comment]
> Yes, but it doesn't seem to be working.

Could you provide more details? What driver versions did you try?

> Maybe you can simulate an environment that connects to clickhouse?

Sorry, I do not understand your request. Please provide more details.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
