### ISSUE TITLE
Disable syntax analyzing for Session Manager

### ISSUE THREAD

**Issue by jbarotin** [dbeaver/dbeaver#21607]
### Description

When I display Session Manager when my server has about 14 active query currently executed, the GUI is frozen immediately

### DBeaver Version

Community Edition 23.2.2.202310081633

### Operating System

Ubuntu 22.04

### Database and driver

1. MariaDB 10.11.5
2. MariaDB JDBC driver 3.0.7 (tested with 3.1.4 too)

### Steps to reproduce

Have a server with more than 10 active query.
Display the Session Manager
Click on a line
Then Dbeaver is freezed

You can find the dbeaver stack below :
[stack.log](https://github.com/dbeaver/dbeaver/files/13054894/stack.log)

### Additional context

SSH tunnel is enabled

**Comment by Matvey16** [comment]
@jbarotin 
What type of installation for DBeaver do you use? IS it a standalone version or a snap/flatpack package?

**Comment by jbarotin** [comment]
@Matvey16  I'm using the deb installation.

Nevertheless, I identified the cause of the issue. It's due to the size of the query currently executed on my MariaDB Server. The query is very huge (cause of a bug on our side), so huge that it makes dbeaver freeze. 

You can find an example of the query here :
[query_ano.zip](https://github.com/dbeaver/dbeaver/files/13205429/query_ano.zip)

Is that possible to limit size of extracted query in session manager ?

**Comment by uslss** [comment]
cannot reproduce on win10

**Comment by LonwoLonwo** [comment]
Could you please try to generate a thread dump during freeze and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by jbarotin** [comment]
@E1izabeth yes issue is still here, it's easy to reproduce, I tried to open query_ano.sql (you can find it here : [query_ano.zip](https://github.com/dbeaver/dbeaver/files/13205429/query_ano.zip) ) in DBeaver CE version 23.3.5 under Ubuntu 23.10. 

Editor freeze immediately.

**Comment by E1izabeth** [comment]
@jbarotin Could you please try to generate a thread dump during freeze and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

**Comment by jbarotin** [comment]
@E1izabeth here you go
[stack.txt](https://github.com/dbeaver/dbeaver/files/14404803/stack.txt)

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
@jbarotin does dbeaver freezes after some concrete action or immediately after script opening?

**Comment by jbarotin** [comment]
@E1izabeth Immediately after script opening

**Comment by E1izabeth** [comment]
@jbarotin Could you try turning Semantic analysis off?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/44263050-d255-4eb8-b2f5-af3ffd5ccf7c)

**Comment by jbarotin** [comment]
> Could you try turning Semantic analysis off?

Done. It still freezes DBeaver.

I tried renaming the file with ".txt", DBeaver is not freezing, but we can't edit file.

**Comment by serjiokov** [comment]
Agreed:
Disable syntax analizing for Session Manager based on the log details
```
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.reloadSyntaxRules(SQLEditorBase.java:754)
	at org.jkiss.dbeaver.ui.views.session.SessionManagerViewer.updateSQL(SessionManagerViewer.java:407)
	at org.jkiss.dbeaver.ui.views.session.SessionManagerViewer.updatePreview(SessionManagerViewer.java:275)
	at org.jkiss.dbeaver.ui.views.session.SessionManagerViewer.onSessionSelect(SessionManagerViewer.java:356)
	at org.jkiss.dbeaver.ext.mysql.ui.editors.MySQLSessionEditor$1.onSessionSelect(MySQLSessionEditor.java:94)
	at org.jkiss.dbeaver.ui.views.session.SessionManagerViewer.lambda$2(SessionManagerViewer.java:131) 
```
