### ISSUE TITLE
Refresh in metadata editor loses all PostgreSQL enum values in Source tab

### ISSUE THREAD

**Issue by vpetryaev** [dbeaver/dbeaver#21726]
### Description

Refresh in metadata editor loses all PostgreSQL enum values in Source tab.
For example. Before refresh:
CREATE TYPE public.test_tp AS ENUM (
	'first',
	'second');

After refresh:
CREATE TYPE public.test_tp AS ENUM (
);

### DBeaver Version

Community Edition Version 23.2.3.202310221533

### Operating System

Ubuntu 20.04.6 LTS

### Database and driver

PostgreSQL 12.4
PostgreSQL JDBC Driver 42.5.2

### Steps to reproduce

1. Create any enum in PostgreSQL database. For example: CREATE TYPE public.test_tp AS ENUM ('first','second');
2. Refresh data in Database Navigator
3. Find created enum and open it in metadata editor (F4 - View Data Type)
4. Go to Source tab. All enum elements exists.
5. Press F5 or click on Refresh button. All enum elements now disappear.

**Comment by LonwoLonwo** [comment]
Hello @vpetryaev 

Could you please provide a video of your issue? Because I can't reproduce it by your steps. And it is important to know - in which place do you push the Refresh button in the Navigator tree and in the Properties tab.

**Comment by vpetryaev** [comment]
Video attached

https://github.com/dbeaver/dbeaver/assets/22563740/e1319a3b-ad4e-43fd-af8c-4c2bfe9d2330

**Comment by uslss** [comment]
Cannot reproduce on windows

https://github.com/dbeaver/dbeaver/assets/31996417/35d3f25f-10d2-4d5d-abe7-f7ba1f27f017

**Comment by LonwoLonwo** [comment]
I also can not reproduce your steps.

Could you please restart or redownload DBeaver?

**Comment by vpetryaev** [comment]
> Could you please restart or redownload DBeaver?

diff ./dbeaver-ce_23.2.3_amd64.deb ./dbeaver-ce_23.2.3_amd64.deb.bak -> no differences
sudo apt-get install ./dbeaver-ce_23.2.3_amd64.deb -> no issues

All enum elements still disappear after refresh. The same issue.

java --version
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by ShadelessFox** [comment]
Can you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thanks.

**Comment by vpetryaev** [comment]
> Can you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thanks.

```
2023-11-10 00:19:36.522 - DBeaver 23.2.3.202310221533 is starting
2023-11-10 00:19:36.523 - OS: Linux 5.15.0-88-generic (amd64)
2023-11-10 00:19:36.523 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2023-11-10 00:19:36.523 - Install path: '/usr/share/dbeaver-ce'
2023-11-10 00:19:36.523 - Instance path: 'file:/home/ptr/.local/share/DBeaverData/workspace6/'
2023-11-10 00:19:36.524 - Memory available 64Mb/1024Mb
2023-11-10 00:19:36.542 - Create display
2023-11-10 00:19:36.710 - Initializing DBeaver 23.2.3
2023-11-10 00:19:36.711 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.2.3.202310221533
2023-11-10 00:19:36.712 - Initialize desktop platform...
2023-11-10 00:19:36.943 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.100.v20230717-1727]
> Start Core Resource Management [org.eclipse.core.resources 3.19.100.v20230814-1312]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.117.202310221533]
> Start Team Support Core [org.eclipse.team.core 3.10.100.v20230726-0617]
2023-11-10 00:19:37.270 - Initialize base platform...
2023-11-10 00:19:37.309 - Platform initialized (597ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.117.202310221533]
2023-11-10 00:19:37.344 - Starting instance server at http://localhost:38341
2023-11-10 00:19:37.355 - Run workbench
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.132.202310221533]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.100.v20230727-0604]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.100.v20230708-0809]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.100.v20230630-1554]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.100.v20230727-0604]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.100.v20230630-1554]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.100.v20230630-1554]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.35.0.v20230801-1141]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.100.v20230727-0604]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.100.v20230727-0604]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.100.v20230801-1255]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.0.v20230429-1914]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.100.v20230727-0604]
2023-11-10 00:19:39.813 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.107.202310221533]
2023-11-10 00:19:40.052 - Total database drivers: 107 (107)
> Start Help System Core [org.eclipse.help 3.10.100.v20230726-0617]
2023-11-10 00:19:40.160 - Create actions
2023-11-10 00:19:40.165 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-11-10 00:19:40.166 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-11-10 00:19:40.166 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2023-11-10 00:19:40.712 - Initialize workbench window
2023-11-10 00:19:40.720 - Finish initialization
> Start Default Text Editor [org.eclipse.ui.editors 3.17.0.v20230821-1342]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.100.v20230821-0745]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.117.202310221533]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.117.202310221533]
> Start DBeaver SQL Terminal [org.jkiss.dbeaver.ui.editors.sql.terminal 1.0.93.202310221533]
> Start Core Compare Support [org.eclipse.compare.core 3.8.100.v20230726-0617]
> Start jna [com.sun.jna 5.13.0.v20230812-1000]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.100.v20230726-0617]
> Start Internet Connection Management [org.eclipse.core.net 1.5.100.v20230630-1232]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.154.202310221533]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.123.202310221533]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.14.0.202308311129]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.15.0.202308311129]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.77.202310221533]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.77.202310221533]
2023-11-10 00:19:44.077 - java.nio.file.NoSuchFileException: /home/ptr/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.model.sql/variables
java.nio.file.NoSuchFileException: /home/ptr/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.model.sql/variables
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.base/java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.base/java.nio.file.Files.list(Unknown Source)
        at org.jkiss.dbeaver.model.sql.registry.SQLVariablesRegistry.loadVariables(SQLVariablesRegistry.java:84)
        at org.jkiss.dbeaver.model.sql.registry.SQLVariablesRegistry.getInstance(SQLVariablesRegistry.java:74)
        at org.jkiss.dbeaver.model.sql.SQLScriptContext.loadVariables(SQLScriptContext.java:329)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.onDataSourceChange(SQLEditor.java:2934)
        at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
        at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
        at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
        at org.jkiss.dbeaver.ui.UIUtils.syncExec(UIUtils.java:1873)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.fireDataSourceChange(SQLEditor.java:2868)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.setDataSourceContainer(SQLEditor.java:472)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.updateDataSourceContainer(SQLEditor.java:502)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.lambda$19(SQLEditor.java:2199)
        at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:68)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:280)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
> Start Console [org.eclipse.ui.console 3.13.0.v20230726-0617]
> Start Debug Core [org.eclipse.debug.core 3.21.100.v20230731-1425]
2023-11-10 00:19:44.772 - Connect with 'elis_delta' (postgres-jdbc-17f418fe3b1-473ecffbeb49e2b2)
> Start DBeaver JDBC Model [org.jkiss.dbeaver.model.jdbc 1.0.10.202310221533]
> Start DBeaver PostgreSQL Model [org.jkiss.dbeaver.ext.postgresql 2.1.190.202310221533]
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.141.202310221533]
2023-11-10 00:19:45.126 - Open [https://dbeaver.io/product/version.xml]
2023-11-10 00:19:45.679 - Execution context opened (elis_delta; Main <elis_delta>; 0)
2023-11-10 00:19:45.679 - Initiate connection to PostgreSQL database [elis_delta@msk-optsql104.corp.suek.ru] for Main <elis_delta>
2023-11-10 00:19:46.403 - Execution context opened (elis_delta; Metadata <elis_delta>; 1)
2023-11-10 00:19:46.404 - Initiate connection to PostgreSQL database [elis_delta@msk-optsql104.corp.suek.ru] for Metadata <elis_delta>
2023-11-10 00:19:47.664 - Connected (postgres-jdbc-17f418fe3b1-473ecffbeb49e2b2, PostgreSQL JDBC Driver [42.5.2])
2023-11-10 00:19:47.685 - Execution context opened (elis_delta; SQLEditor <Script-50.sql>; 2)
2023-11-10 00:19:47.688 - Initiate connection to PostgreSQL database [elis_delta@msk-optsql104.corp.suek.ru] for SQLEditor <Script-50.sql>
> Start DBeaver Tasks - Native Tools UI [org.jkiss.dbeaver.tasks.native.ui 1.0.95.202310221533]
> Start DBeaver PostgreSQL UI [org.jkiss.dbeaver.ext.postgresql.ui 1.0.93.202310221533]
> Start DBeaver Tasks - General UI [org.jkiss.dbeaver.tasks.ui 1.0.95.202310221533]
```

**Comment by Destrolaric** [comment]
Can't reproduce on Debian
![image](https://github.com/dbeaver/dbeaver/assets/20579256/b49cf678-ff12-4fa8-89fb-b79b8bdc32d6)

**Comment by Destrolaric** [comment]
@vpetryaev Hi, there should be a new major version increment on Monday, could you try to test if the issue will still be reproducible for you?

**Comment by vpetryaev** [comment]
Of course, I'll test this

**Comment by vpetryaev** [comment]
> @vpetryaev Hi, there should be a new major version increment on Monday, could you try to test if the issue will still be reproducible for you?

The same issue (

**Comment by LonwoLonwo** [comment]
Did you try to refresh the data type node in the navigator tree? Or the whole schema? Will only reconnect return your values?

**Comment by vpetryaev** [comment]
> Did you try to refresh the data type node in the navigator tree? Or the whole schema? Will only reconnect return your values?

Enum values disappear only after refresh in the Editor tab (Refresh button in right low corner). Closing and reopening this tab solve issue.
But, then the Editor tab shown old metadata, I need close tab, refresh in the navigation tree and reopen Editor.

Sorry, update. Enum values disappear also after refresh Enum (not folder!) in the navigation tree when Editor tab opened.

**Comment by LonwoLonwo** [comment]
Could you please check one more time in the newest DBeaver version?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by vpetryaev** [comment]
https://youtu.be/MOz_OR5xWPg

**Comment by E1izabeth** [comment]
Thank you for update

**Comment by vpetryaev** [comment]
Version 24.0.0.202403031740 - still the same issue

**Comment by regisbsb** [comment]
![image](https://github.com/user-attachments/assets/934771c4-0cc0-49c0-b1f5-455853f9c5fd)
![image](https://github.com/user-attachments/assets/a75ce711-0f4e-4bb1-9261-8156ae74a532)
Same issue here 
![image](https://github.com/user-attachments/assets/c747edeb-91cb-4c9b-8ee9-0a53b163a23a)
24.2.2.202410061621

I'm on windows.
