### ISSUE TITLE
on loading mysql views got ArrayIndexOutOfBoundsException error

### ISSUE THREAD

**Issue by Alireza-Rajabzadeh** [dbeaver/dbeaver#21760]
### Description

Hi
i use dbeaver on linux (Ubuntu 22.04.2 LTS ) , I have database with views .
now I want to open those in dbeaver but got this error 

ArrayIndexOutOfBoundsException
SQL Error [S1000]
  SQLException
  java.sql.SQLException
    ArrayIndexOutOfBoundsException
    java.lang.ArrayIndexOutOfBoundsException

I use this views in my code and even open them in another database tool correctly  .
all db tables are ok even tables that I combine in view. I only have problem with views that defined before because I create new view in dbeaver and its looks ok . 

thnaks

### DBeaver Version

Version 23.1.3.202307231901

### Operating System

Linux Ubuntu 22.04.2 LTS

### Database and driver

MySql 

### Steps to reproduce

when click to open view data or properties I got this error : 
 ArrayIndexOutOfBoundsException
SQL Error [S1000]
  SQLException
  java.sql.SQLException
    ArrayIndexOutOfBoundsException
    java.lang.ArrayIndexOutOfBoundsException

**Comment by ShadelessFox** [comment]
Hello @Alireza-Rajabzadeh,

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Alireza-Rajabzadeh** [comment]
@ShadelessFox I hope its be helpful

if you need some thing else let me know .
thanks .

```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.777
!MESSAGE Error reading property 'checkOption' from bitstream_oss.view_cartable_cra
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.778
!MESSAGE SQL Error [S1000]: Index 8 out of bounds for length 7
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.778
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.loadAdditionalInfo(MySQLView.java:199)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.getAdditionalInfo(MySQLView.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:392)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:224)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:173)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:365)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.785
!MESSAGE Error reading property 'updatable' from bitstream_oss.view_cartable_cra
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.785
!MESSAGE SQL Error [S1000]: Index 8 out of bounds for length 7
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.785
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.loadAdditionalInfo(MySQLView.java:199)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.getAdditionalInfo(MySQLView.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:392)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:224)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:173)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:365)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.823
!MESSAGE Error reading property 'definer' from bitstream_oss.view_cartable_cra
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.823
!MESSAGE SQL Error [S1000]: Index 8 out of bounds for length 7
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.823
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.loadAdditionalInfo(MySQLView.java:199)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.getAdditionalInfo(MySQLView.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:392)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:224)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:173)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:365)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.834
!MESSAGE Error reading property 'algorithm' from bitstream_oss.view_cartable_cra
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.834
!MESSAGE SQL Error [S1000]: Index 8 out of bounds for length 7
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:57.834
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.loadAdditionalInfo(MySQLView.java:199)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.getAdditionalInfo(MySQLView.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:392)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:224)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:173)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:365)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm$6.evaluate(TabbedFolderPageForm.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:58.045
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLTableBase.getAttributes(MySQLTableBase.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:964)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1036)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:464)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:308)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-11 11:09:58.310
!MESSAGE Index 8 out of bounds for length 7
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:103)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:83)
	at com.mysql.cj.protocol.a.ResultsetRowReader.read(ResultsetRowReader.java:42)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1651)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:87)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:665)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:893)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.loadAdditionalInfo(MySQLView.java:199)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLView.getAdditionalInfo(MySQLView.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:79)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:392)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:382)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ShadelessFox** [comment]
What driver and its version are you using? What server and its version are you connecting to?

**Comment by Alireza-Rajabzadeh** [comment]
@ShadelessFox 
deriver name : MySQL                   GNU LIBRARY GENERAL PUBLIC LICENSE   Version 2, June 1991

by now I dont have access to server informations unfortunately but If I find out will let yo know

**Comment by ShadelessFox** [comment]
This is a weird driver name. Please show contents of this page (expand all subfolders):

![image](https://github.com/dbeaver/dbeaver/assets/35821147/9cc46ac6-7744-4bd4-bc4d-3ae9b7adaf12)

**Comment by Alireza-Rajabzadeh** [comment]
![Screenshot from 2023-11-13 17-13-17](https://github.com/dbeaver/dbeaver/assets/39335148/f2b332af-92ce-4513-8af2-6a9adc457948)

**Comment by ShadelessFox** [comment]
Have you tried using the MariaDB driver instead?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by Alireza-Rajabzadeh** [comment]
@ShadelessFox  sorry about Delay in response  I didt check this out lately .
If you trust me  :sweat_smile:   I tried MariaDB before and it dosent work but know I test again and yes ... its seems ok 
thanks for your time 
@E1izabeth thank you too .
