### ISSUE TITLE
No enum constant com.clickhouse.data.ClickHouseFormat.LowCardinality

### ISSUE THREAD

**Issue by xeivier** [dbeaver/dbeaver#21776]
### Description

Every time I try to create a table with type LowCardinality(String) I get this error.

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:583)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:492)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:499)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:947)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4057)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5164)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:295)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.clickhouse.data.ClickHouseFormat.LowCardinality
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at com.clickhouse.data.ClickHouseFormat.valueOf(ClickHouseFormat.java:9)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:112)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	... 13 more
```

### DBeaver Version

DBeaver Community Edition 23.2.4.202311051706

### Operating System

macOS Monterey 12.7

### Database and driver

Server: ClickHouse 23.9.2.56
Driver: ClickHouse JDBC Driver 0.4.6
Driver: ClickHouse JDBC Driver 0.5.0 

### Steps to reproduce

1. I try to create a table with columns having a LowCardinality(String) type
2. I get the error

**Comment by LonwoLonwo** [comment]
Hello @JaviKx2 

I can't reproduce it with driver versions 0.4.6/0.5.0

![2023-11-07 15_01_44-DBeaver Ultimate 23 2 4 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/66305d80-031c-498d-8c1c-aa4b89eeaf68)

Could you please provide more clear steps to reproduce? And a query, for example.

**Comment by xeivier** [comment]
I got to solve it! I didn't notice a column was named _format_ and was causing conflicts.
Just changed _format LowCardinality(String),_ to _\'format\` LowCardinality(String),_

**Comment by LonwoLonwo** [comment]
Thaks for the update
