### ISSUE TITLE
Fix parsing error for Trino SQL routines

### ISSUE THREAD

**Issue by mosabua** [dbeaver/dbeaver#21808]
### Description

It seems like DBeaver is incorrectly assuming end of SQL statement in a SQL routine declaration for Trino. This prevents it from being submitted through the JDBC driver and therefore be actually created. The same works fine in the Trino CLI and the JDBC driver does support receiving statements.

### DBeaver Version

Community edition Version 23.2.4.202311051706

### Operating System

macos ventura

### Database and driver

Trino JDBC driver 432

### Steps to reproduce

The following steps work 

* Use Trino 431 or newer via docker or tarball
* Connect to Trino in DBeaver
* use the SQL console

Try this statement

```
WITH
  FUNCTION abc(x integer)
    RETURNS integer
    RETURN x * 2
SELECT abc(21);
```

It will work and return 42.

Now try this 

```
WITH FUNCTION simple_case(a bigint)
                RETURNS varchar
                BEGIN
                  CASE a
                    WHEN 0 THEN RETURN 'zero';
                    WHEN 1 THEN RETURN 'one';
                    WHEN DECIMAL '10.0' THEN RETURN 'ten';
                    WHEN 20.0E0 THEN RETURN 'twenty';
                    ELSE RETURN 'other';
                  END CASE;
                  RETURN NULL;
                END
                SELECT simple_case(10), simple_case(0);
```

It should return one row with two values.

 _col0 | _col1
-------+-------
 ten   | zero

I get the following stacktrace as error message in Dbeaver. The problem might be that Dbeaver is trying to parse the statement and is not aware of the fact that the ; in the function declaration are NOT the end of the statement.

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1]: Query failed (#20231109_052048_00141_t7x8y): line 1:1: mismatched input 'END'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UPDATE', 'USE', 'WITH', <query>
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:583)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:492)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:499)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:947)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4057)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5164)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20231109_052048_00141_t7x8y): line 1:1: mismatched input 'END'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UPDATE', 'USE', 'WITH', <query>
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:318)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: io.trino.sql.parser.ParsingException: line 1:1: mismatched input 'END'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UPDATE', 'USE', 'WITH', <query>
	at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
	at io.trino.grammar.sql.SqlBaseParser.statement(SqlBaseParser.java:2943)
	at io.trino.grammar.sql.SqlBaseParser.singleStatement(SqlBaseParser.java:345)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:172)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:125)
	at io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:90)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:54)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:191)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:160)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at io.trino.$gen.Trino_432____20231108_165447_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LonwoLonwo** [comment]
Hello @mosabua 

Thanks for the report.

You can highlight your entire query and execute it as a workaround for now.

**Comment by mosabua** [comment]
Oh .. thanks for letting me know @LonwoLonwo  .. didnt even think about highlighting the whole statement. So used to the convenience of CTRL - RETURN

**Comment by mosabua** [comment]
Btw here is the logic to figure out the details from the Trino CLI https://github.com/trinodb/trino/blob/master/client/trino-cli/src/main/java/io/trino/cli/lexer/StatementSplitter.java

**Comment by delloncba** [comment]
Any update on this?
