### ISSUE TITLE
OutOfMemoryError occurred

### ISSUE THREAD

**Issue by cw-eclipse** [dbeaver/dbeaver#21885]
### Description

I needed to build a large Java project in Eclipse.
After several builds, an OutOfMemoryError occurred.
After analyzing the Dump file, we found a huge instance of org.jkiss.dbeaver.model.navigator.DBNModel that was over 1GByte.
This problem occurs with dbeaver version 4.2.2 and above.
Speculation,
DBNEvent is accumulated in eventCache in org.jkiss.dbeaver.model.navigator.DBNModel$EventProcessingJob, which makes it OOME.
DBNModel.java has been refactored in 4.2.2 to add the internal class EventProcessingJob.
It seems that if you build a Java project after 4.2.2, the eventCache will continue to accumulate DBNEvents.
Commit ID: dbe4097035c407ab276e621773eed924c814f291
https://github.com/dbeaver/dbeaver/commit/dbe4097035c407ab276e621773eed924c814f291
What can I provide to help resolve this issue?

### DBeaver Version

23.1.0

### Operating System

Windows10 22H2

**Comment by serjiokov** [comment]
Hello @cw-eclipse,  huge projects are memory expensive and really might lead to OutOfMemoryError, for this purpose try to increase amount of memory through dbeaver.ini file using the option: 
-Xmx1024m to -Xmx4096m

**Comment by cw-eclipse** [comment]
Thx for respnce @serjiokov .
OutOfMemoryError occurred after repeated builds due to memory leakage even with 4GB of Eclipse memory.
Would you fix the plugin?

**Comment by LonwoLonwo** [comment]
Hello.

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by cw-eclipse** [comment]
[.log](https://github.com/dbeaver/dbeaver/files/13481961/default.log)
Is this OK?

**Comment by MashaKorax** [comment]
Am I correct that DBeaver is installed as an Eclipse plugin?
In that case, is increased memory consumption happening only during and after java build?

**Comment by cw-eclipse** [comment]
Yes, it is an Eclipse plugin.
Memory begins to increase during the build and will increase by about 100Mbytes after the build is finished.
Otherwise, it does not increase.

**Comment by serjiokov** [comment]
Hi @cw-eclipse,
Generally, I see a lot of errors unrelated to dbeaver bundles 
```
ENTRY org.eclipse.core.jobs 4 2 2023-11-24 16:10:56.680
!MESSAGE 処理不可能なエラーです
!STACK 0
java.lang.OutOfMemoryError: Java ヒープ・スペース
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at org.eclipse.core.internal.jobs.JobManager.now(JobManager.java:1260)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:248)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

!ENTRY org.eclipse.core.jobs 4 2 2023-11-24 16:11:02.117
!MESSAGE 処理不可能なエラーです
!STACK 0
java.lang.OutOfMemoryError: Java ヒープ・スペース
	at java.base/java.util.HashMap.newNode(HashMap.java:1901)
	at java.base/java.util.HashMap.putVal(HashMap.java:629)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at org.eclipse.core.internal.jobs.JobManager.changeState(JobManager.java:464)
	at org.eclipse.core.internal.jobs.JobManager.nextJob(JobManager.java:1238)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1743)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

!ENTRY org.eclipse.core.jobs 4 2 2023-11-24 16:11:09.555
!MESSAGE 内部エラーが発生しました: "装飾計算"。
!STACK 0
java.lang.OutOfMemoryError: Java ヒープ・スペース
	at org.eclipse.core.internal.watson.ElementTreeIterator.requestPath(ElementTreeIterator.java:168)
	at org.eclipse.core.internal.resources.MarkerManager.lambda$1(MarkerManager.java:601)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.MarkerManager.visitorFindMarkers(MarkerManager.java:605)
	at org.eclipse.core.internal.resources.MarkerManager.doFindMarkers(MarkerManager.java:284)
	at org.eclipse.core.internal.resources.MarkerManager.findMarkers(MarkerManager.java:268)
	at org.eclipse.core.internal.resources.Resource.findMarkers(Resource.java:997)
	at org.eclipse.dltk.ui.ProblemsLabelDecorator.getErrorTicksFromMarkers(ProblemsLabelDecorator.java:248)
	at org.eclipse.dltk.ui.ProblemsLabelDecorator.computeAdornmentFlags(ProblemsLabelDecorator.java:223)
	at org.eclipse.dltk.internal.ui.navigator.TreeHierarchyLayoutProblemsDecorator.computeAdornmentFlags(TreeHierarchyLayoutProblemsDecorator.java:67)
	at org.eclipse.php.ui.PHPElementProblemsLabelDecorator.computeAdornmentFlags(PHPElementProblemsLabelDecorator.java:36)
	at org.eclipse.dltk.ui.ProblemsLabelDecorator.decorate(ProblemsLabelDecorator.java:419)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:257)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.queue(DecorationScheduler.java:419)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:397)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Nothing we do with generic eclipse behavior.
From Dbeaver side we are manage to fix only NPE
`java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.app.DBPWorkspace.getMetadataFolder()" because the return value of "org.jkiss.dbeaver.registry.BasePlatformImpl.getWorkspace()" is null`

**Comment by cw-eclipse** [comment]
Thank you for your answer.
I get the situation as shown in this image, does it mean that you cannot fix this problem?
![1](https://github.com/dbeaver/dbeaver/assets/92078918/251eaad9-8387-41e1-b798-969854ff34ed)
![2](https://github.com/dbeaver/dbeaver/assets/92078918/81102f48-df4d-4ecb-8d8b-bf4f27309e18)
![3](https://github.com/dbeaver/dbeaver/assets/92078918/62243b07-74dc-4ad5-b00a-37f97c6ce367)
![4](https://github.com/dbeaver/dbeaver/assets/92078918/00cf284e-78a2-4166-9571-92640d5d8e9b)
![5](https://github.com/dbeaver/dbeaver/assets/92078918/3eb2afcd-1bdd-438e-998c-66a69a02815b)

**Comment by Matvey16** [comment]
@cw-eclipse Thank you for the report.
