### ISSUE TITLE
can not export data

### ISSUE THREAD

**Issue by wang1597538789** [dbeaver/dbeaver#21897]
### Description

can not export data

### DBeaver Version

23.2.5.202311191730

### Operating System

windows 7

### Database and driver

1. Database name and version: sql server 2014
2. Driver name and version: MS SQL Server / SQL Server 9.2.0

### Additional context

!SESSION 2023-11-20 11:59:02.350 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Framework arguments:  -eclipse.keyring C:\Users\Administrator\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2023-11-20 11:59:36.546

!ENTRY org.jkiss.dbeaver.model 4 0 2023-11-20 11:59:36.546
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2023-11-20 11:59:36.546
!MESSAGE com.google.gson.stream.MalformedJsonException: Unexpected value at line 5 column 17 path $..description
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2023-11-20 11:59:36.546
!MESSAGE Unexpected value at line 5 column 17 path $..description
!STACK 0
com.google.gson.stream.MalformedJsonException: Unexpected value at line 5 column 17 path $..description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:573)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:129)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1107)
	at org.jkiss.dbeaver.model.data.json.JSONUtils.parseMap(JSONUtils.java:289)
	at org.jkiss.dbeaver.registry.task.TaskManagerImpl.loadConfiguration(TaskManagerImpl.java:337)
	at org.jkiss.dbeaver.registry.task.TaskManagerImpl.<init>(TaskManagerImpl.java:75)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.getTaskManager(BaseProjectImpl.java:214)
	at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard$DataTransferWizardExecutor.<init>(DataTransferWizard.java:595)
	at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.performFinish(DataTransferWizard.java:330)
	at org.jkiss.dbeaver.ui.dialogs.MultiPageWizardDialog.buttonPressed(MultiPageWizardDialog.java:364)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:232)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.openWizard(DataTransferWizard.java:641)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.processQueries(SQLEditor.java:3644)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processQueries(SQLEditor.java:2755)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.exportDataFromQuery(SQLEditor.java:2579)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerExportData.execute(SQLEditorHandlerExportData.java:50)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:300)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:280)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

**Comment by wang1597538789** [comment]
is there some config files wrong?

**Comment by LonwoLonwo** [comment]
Hello @wang1597538789 

Yes, there is something wrong with your tasks.json file.

Could you please check your file? You can find it in: `...AppData\Roaming\DBeaverData\workspace6\<your_project_name>\.dbeaver\tasks.json`

Something about:  Unexpected value at line 5 column 17 path $..description

**Comment by LonwoLonwo** [comment]
As a workaround for now - you can create another project, copy your connection there, and export again.

**Comment by wang1597538789** [comment]
i delete tasks.json then it works

**Comment by LonwoLonwo** [comment]
Ok. 
So, the issue is not actual anymore?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by wang1597538789** [comment]
您好，您的邮件我已收到，我会尽快给您回复。
