### ISSUE TITLE
No ssh tab use mysql

### ISSUE THREAD

**Issue by derekzhan** [dbeaver/dbeaver#21961]
### Description

I cannot see ssh tab when i connecting to mysql server. The following figure： 
<img width="690" alt="image" src="https://github.com/dbeaver/dbeaver/assets/2375460/b5a0e21a-937a-4eda-a045-2b10daaaca0f">

### DBeaver Version

Version 23.2.5.202311191730

### Operating System

macos 14.0

**Comment by LonwoLonwo** [comment]
Hello @derekzhan 

Did you try to reinstall DBeaver?

**Comment by derekzhan** [comment]
Yes , The problem still exists @LonwoLonwo

**Comment by LonwoLonwo** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by derekzhan** [comment]
> Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.
```java
2023-11-23 16:37:36.268 - DBeaver 23.2.5.202311191730 is starting
2023-11-23 16:37:36.268 - OS: Mac OS X 14.0 (aarch64)
2023-11-23 16:37:36.268 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2023-11-23 16:37:36.268 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2023-11-23 16:37:36.268 - Instance path: 'file:/Users/zhanweichun/Library/DBeaverData/workspace6/'
2023-11-23 16:37:36.268 - Memory available 120Mb/1024Mb
2023-11-23 16:37:36.270 - Create display
2023-11-23 16:37:36.375 - Initializing DBeaver 23.2.5
2023-11-23 16:37:36.375 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 23.2.5.202311191730
2023-11-23 16:37:36.375 - Initialize desktop platform...
2023-11-23 16:37:36.437 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.100.v20230717-1727]
> Start Core Resource Management [org.eclipse.core.resources 3.19.100.v20230814-1312]
> Start Team Support Core [org.eclipse.team.core 3.10.100.v20230726-0617]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.119.202311191730]
2023-11-23 16:37:36.856 - Initialize base platform...
2023-11-23 16:37:36.866 - Platform initialized (491ms)
2023-11-23 16:37:36.886 - Starting instance server at http://localhost:59120
2023-11-23 16:37:36.890 - Run workbench
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.134.202311191730]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.100.v20230727-0604]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.100.v20230708-0809]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.100.v20230630-1554]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.100.v20230727-0604]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.100.v20230630-1554]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.100.v20230630-1554]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.35.0.v20230801-1141]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.100.v20230727-0604]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.100.v20230801-1255]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.0.v20230429-1914]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.100.v20230727-0604]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.100.v20230727-0604]
> Start Eclipse SDK Themes [org.eclipse.ui.themes 1.2.2300.v20230807-1354]
2023-11-23 16:37:37.753 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.109.202311191730]
2023-11-23 16:37:37.809 - Total database drivers: 106 (106)
> Start Help System Core [org.eclipse.help 3.10.100.v20230726-0617]
2023-11-23 16:37:37.840 - Create actions
2023-11-23 16:37:37.842 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2023-11-23 16:37:37.843 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2023-11-23 16:37:37.843 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2023-11-23 16:37:38.049 - Initialize workbench window
2023-11-23 16:37:38.052 - Finish initialization
> Start Default Text Editor [org.eclipse.ui.editors 3.17.0.v20230821-1342]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.100.v20230821-0745]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.119.202311191730]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.119.202311191730]
> Start DBeaver SQL Terminal [org.jkiss.dbeaver.ui.editors.sql.terminal 1.0.95.202311191730]
> Start Core Compare Support [org.eclipse.compare.core 3.8.100.v20230726-0617]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.100.v20230726-0617]
> Start Internet Connection Management [org.eclipse.core.net 1.5.100.v20230630-1232]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.156.202311191730]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.125.202311191730]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.14.0.202308311129]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.15.0.202308311129]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.79.202311191730]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.79.202311191730]
> Start Console [org.eclipse.ui.console 3.13.0.v20230726-0617]
> Start Debug Core [org.eclipse.debug.core 3.21.100.v20230731-1425]
2023-11-23 16:37:39.600 - Connect with '192.168.0.230' (mariaDB-18bfafc4f45-486805c1083cd126)
> Start DBeaver SSH Tunnels [org.jkiss.dbeaver.net.ssh 1.0.140.202311191730]
> Start DBeaver JDBC Model [org.jkiss.dbeaver.model.jdbc 1.0.12.202311191730]
> Start DBeaver MySQL Support [org.jkiss.dbeaver.ext.mysql 2.1.204.202311191730]
> Start DBeaver SSH implementation (SSHJ) [org.jkiss.dbeaver.net.ssh.sshj 1.0.140.202311191730]
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.129.202311191730]
> Start jna [com.sun.jna 5.13.0.v20230812-1000]
2023-11-23 16:37:39.614 - pageant connect exception
com.jcraft.jsch.AgentProxyException: PageantConnector only available on Windows.
        at com.jcraft.jsch.PageantConnector.<init>(PageantConnector.java:59)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:111)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:85)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1113)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2023-11-23 16:37:40.032 - SSH: Connected with ssh-agent
2023-11-23 16:37:40.041 - Security Provider class 'org.bouncycastle.jce.provider.BouncyCastleProvider' not found
2023-11-23 16:37:40.041 - BouncyCastle not registered, using the default JCE provider
2023-11-23 16:37:40.048 - Creating new SecureRandom.
> Start JSch Core [org.eclipse.jsch.core 1.5.100.v20230726-0617]
2023-11-23 16:37:40.197 - Client identity string: SSH-2.0-SSHJ_0.34.0
2023-11-23 16:37:40.253 - Server identity string: SSH-2.0-OpenSSH_7.4
2023-11-23 16:37:40.684 - Set port forwarding :48540 -> 192.168.0.230:3306
2023-11-23 16:37:40.687 - Listening on localhost/127.0.0.1:48540
2023-11-23 16:37:40.704 - Execution context opened (192.168.0.230; Main; 0)
> Start DBeaver GIS Support [org.jkiss.dbeaver.data.gis 1.0.143.202311191730]
2023-11-23 16:37:41.082 - Execution context opened (192.168.0.230; Metadata; 1)
2023-11-23 16:37:41.810 - Connected (mariaDB-18bfafc4f45-486805c1083cd126, MariaDB Connector/J [3.0.7])
2023-11-23 16:37:41.812 - Execution context opened (192.168.0.230; SQLEditor <Script-25.sql>; 2)
> Start DBeaver Tasks - Native Tools UI [org.jkiss.dbeaver.tasks.native.ui 1.0.97.202311191730]
> Start DBeaver MySQL UI Support [org.jkiss.dbeaver.ext.mysql.ui 1.0.111.202311191730]
> Start DBeaver Tasks - General UI [org.jkiss.dbeaver.tasks.ui 1.0.97.202311191730]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.110.202311191730]
2023-11-23 16:37:49.197 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
```

**Comment by E1izabeth** [comment]
@derekzhan 
Could you try opening wizard for creating a new connection to see if all tabs are there or missing?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4e1c5c73-e335-4173-ac3f-265bae47b120)

**Comment by serjiokov** [comment]
@derekzhan Could you try to open DataBase->DriverManger dialog and check that "Embedded" is not set on Settings tab.
![image](https://github.com/dbeaver/dbeaver/assets/32031248/0d70cb09-0f6d-4afc-9c11-03020f485e91)

**Comment by derekzhan** [comment]
> @derekzhan Could you try to open DataBase->DriverManger dialog and check that "Embedded" is not set on Settings tab. ![image](https://user-images.githubusercontent.com/32031248/285238994-0d70cb09-0f6d-4afc-9c11-03020f485e91.png)

@serjiokov  "Embedded" is not set then ssh tab is appeared, thanks very much.
<img width="690" alt="image" src="https://github.com/dbeaver/dbeaver/assets/2375460/11624e12-11d9-47ee-ba6e-e44261a6824a">

**Comment by derekzhan** [comment]
<img width="690" alt="image" src="https://github.com/dbeaver/dbeaver/assets/2375460/0a579565-8dba-4c50-b6cb-bee7baba3a4e">
