### ISSUE TITLE
SSH Agent authentication 

### ISSUE THREAD

**Issue by duuri-mollinen** [dbeaver/dbeaver#22009]
### Description

Agent authentication to ssh tunnel host does not work. Connection fails with available authentication methods exhausted error. Connection works with  23.2.3 series

### DBeaver Version

Community edition   23.2.4 and  23.2.5

### Operating System

MacOS 14.1.1 

### Database and driver

MariaDB
Postgres

### Steps to reproduce

1. Have ssh agent managed private key used for conneting to ssh tunnel server
2. Have connection details defined in connection profile
3. Open connection to database that is using the ssh tunnel connection profile
4. Connection fails

### Additional context

Apple keychain managed private key password

**Comment by LonwoLonwo** [comment]
Hello @duuri-mollinen 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by duuri-mollinen** [comment]
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_FI
Framework arguments:  -keyring /Users/*****/.eclipse_keyring -eclipse.keyring /Users/*****/Library/DBeaverData/secure/secure_storage
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/****/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Tue Nov 28 08:21:15 EET 2023
Exhausted available authentication methods

net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:142)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:136)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:85)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1113)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:950)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:115)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2486)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


----------------------------

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_FI
Framework arguments:  -keyring /Users/****/.eclipse_keyring -eclipse.keyring /Users/******/Library/DBeaverData/secure/secure_storage
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/*******/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Tue Nov 28 08:21:55 EET 2023
Exhausted available authentication methods

net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:142)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:136)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:85)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$9.execute(SSHTunnelConfiguratorUI.java:353)
	at org.jkiss.dbeaver.runtime.AbstractTrackingJob.run(AbstractTrackingJob.java:48)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment]
Could you change ssh implementation to JSch? Does it help?

![image](https://github.com/dbeaver/dbeaver/assets/28875055/fe3c9f2f-6f20-4419-9365-e28add182e43)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by duuri-mollinen** [comment]
Same result with both available ssh clients. JSch does not make any difference. Feature still broken

**Comment by serjiokov** [comment]
@duuri-mollinen After proper setup of '.config' and 'ssh-agent' to manage your private key  
please specify the agent option on this form. 
<img width="890" alt="Screenshot 2024-03-07 at 14 56 19" src="https://github.com/dbeaver/dbeaver/assets/32031248/4e91dcce-3373-4219-a430-6a9488d6eb5f">

Connection should be successful

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
