### ISSUE TITLE
SSH Algorithm negotiation fail - "ssh-dss"

### ISSUE THREAD

**Issue by bersipy** [dbeaver/dbeaver#22042]
### Description

This morning I've updated the community client to the latest version.
After the update, I cannot enstablish a new connection to my usual machine due to obsolete algorithm in use (ssh-dss as shown below).

To fix, I've changed the SSH library from JSch to SSHJ, but I'm sure it is a temporary fix (until you'll disable it on this too, maybe).

Related issue:
https://github.com/dbeaver/dbeaver/issues/14749

I've commented this related issue also:
https://github.com/dbeaver/dbeaver/issues/19568

**Error log:**
```
Can't initialize tunnel
  Cannot establish tunnel to <PRIVATE_IP>:<port>
  Cannot establish tunnel to <PRIVATE_IP>:<port>
    Algorithm negotiation fail: algorithmName="server_host_key" jschProposal="ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa" serverProposal="ssh-dss"
    Algorithm negotiation fail: algorithmName="server_host_key" jschProposal="ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa" serverProposal="ssh-dss"
```

As suggested on the related issue, we will probably need a way to enable "legacy" algorithms, since well enstablished companies usually are resilient to protocols change.

### DBeaver Version

23.2.5.202311191730 CE

### Operating System

Ubuntu 22.04.3 LTS x86_64

**Comment by Destrolaric** [comment]
Thanks for the report we should probably do the same as for ssh-rsa.

**Comment by macwinnie** [comment]
Hi =)

Strange behavior at my side – not sure if directly connected but coming from #14749 I assume any connection.

My SSH key works on a connection to one server – another server, set up the same way (same Ansible playbooks and same Ubuntu 20.04) declines connections. No change if using `rsa` key or `ed25519` key, both work on the one server, the other declines ...

Log:

```
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:363)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:128)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:136)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:85)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI$9.execute(SSHTunnelConfiguratorUI.java:353)
	at org.jkiss.dbeaver.runtime.AbstractTrackingJob.run(AbstractTrackingJob.java:48)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

and yes ... the simple `ssh -i <path-to-key-file>` command works fine with both files on both servers =D

Any idea what's going wrong here?

Edit: what probably to mention – but doesn't make the behavior less strange: I'm on a M1 Mac ...
