### ISSUE TITLE
Error exporting Oracle Spatial Data between DBs

### ISSUE THREAD

**Issue by sivelasco** [dbeaver/dbeaver#22057]
### Description

When you try to export a table with some MDSYS.GDO_GEOMETRY column data type (Oracle DB), export task can't be executed due to an internal error. Guess it won't work either if destiny DB is a MySQL or PostreSQL, but I faced this issue when using same origin and destiny DB type and version.

Log error:
java.sql.SQLException: Fail to convert to internal representation: 
	at oracle.sql.STRUCT.toSTRUCT(STRUCT.java:459)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:8454)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:7991)
	at oracle.jdbc.driver.OraclePreparedStatement.setObject(OraclePreparedStatement.java:8559)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:225)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.setObject(JDBCPreparedStatementImpl.java:435)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCStructValueHandler.bindParameter(JDBCStructValueHandler.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:64)
	at org.jkiss.dbeaver.model.impl.data.ExecuteInsertBatchImpl.bindStatement(ExecuteInsertBatchImpl.java:105)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:169)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.lambda$0(DatabaseTransferConsumer.java:456)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:454)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:510)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:216)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:270)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:187)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### DBeaver Version

Community edition 23.2.5

### Operating System

Windows 10

### Database and driver

DB: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0
Driver: Oracle JDBC driver 12.2.0.1.0

### Steps to reproduce

1- Connect to origin and destiny DBs
2- Right click on the table with spatial columns you want to transfer -> Export Data
3- Select Export target as DB and after this point -> Next, next, next, finish. (Same happens if you create the table before or just now, if you use a separate transaction...)

### Additional context

This happens from a long time ago, no new issue, but i just restore my Github account to report the bug.

**Comment by Matvey16** [comment]
@sivelasco Thank you for the report. This is not a bug, Oracle geometry is more comlex than ordinary string based geometry like postgres. Export of this data for Oracle is not supported in Community edition. But it works in Pro versions.
