### ISSUE TITLE
Exception when executing a query in the SQL editor

### ISSUE THREAD

**Issue by Fang3s** [dbeaver/dbeaver#22052]
### Description

`DO BEGIN  FOR ...  END FOR END`
![Execute](https://github.com/dbeaver/dbeaver/assets/6383616/da65248c-c0b0-43e6-a06b-7876f505f38d)

#### Disable SQL syntax parser is checked

Execute the following SQL so that it will report an error if disabling SQL syntax parser.

Exception
![Exception](https://github.com/dbeaver/dbeaver/assets/6383616/7247c1e3-5b52-409c-af7e-1ca52502c729)

![image](https://github.com/dbeaver/dbeaver/assets/6383616/38a4ea14-d23c-4bf5-99dc-2bed66eaff32)

![Exception after clicking Execute SQL query when disabling SQL syntax parser](https://github.com/dbeaver/dbeaver/assets/6383616/d528dd81-c945-4147-90b7-3f3ca7928d82)

If selecting the entire SQL (DO BEGIN .. END) statement to execute, it still failed with the same error.
![selecting the entire SQL statement to execute](https://github.com/dbeaver/dbeaver/assets/6383616/b1344cc1-a7e7-4c00-8a85-03eba4ad9ed9)

#### Disable SQL syntax parser is unchecked

It did nothing after clicking the triangle arrow button "Execute SQL query" with "Disable SQL syntax parser" unchecked.
```sql
DO BEGIN
DECLARE VAR_0 TABLE(ID INTEGER);
DECLARE VAR_1 INTEGER;
DECLARE VAR_2 INTEGER;
DECLARE VAR_3 INTEGER;
FOR VAR_1 IN 0..0 DO INSERT INTO :VAR_0 VALUES(:VAR_1); END FOR;
END
```

But , the following SQL could be executed if commenting out the `FOR ... END FOR;` line with "Disable SQL syntax parser" unchecked.

```sql
DO BEGIN
DECLARE VAR_0 TABLE(ID INTEGER);
DECLARE VAR_1 INTEGER;
DECLARE VAR_2 INTEGER;
DECLARE VAR_3 INTEGER;
-- FOR VAR_1 IN 0..0 DO INSERT INTO :VAR_0 VALUES(:VAR_1); END FOR;
END
```
![DO BEGIN without FOR](https://github.com/dbeaver/dbeaver/assets/6383616/10fca6d7-0a27-4346-8928-dbd1ae45e737)

### DBeaver Version

Version 23.2.5.202311191730 (November 20, 2023)

### Operating System

Windows 10

### Database and driver

![ngdbc-2.13.9.jar](https://github.com/dbeaver/dbeaver/assets/6383616/2d2c4bc8-7fb9-43ca-a776-309b0c29ad76)

### Steps to reproduce

1. Execute the following HANA SQL statement in the SQL script editor
	```sql
	DO BEGIN
	DECLARE VAR_0 TABLE(ID INTEGER);
	DECLARE VAR_1 INTEGER;
	DECLARE VAR_2 INTEGER;
	DECLARE VAR_3 INTEGER;
	FOR VAR_1 IN 0..0 DO INSERT INTO :VAR_0 VALUES(:VAR_1); END FOR;
	END
	```
2. It will fail to execute and raise the following exception,
	```
	org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [257] [HY000]: SAP DBTech JDBC: [257] (at 34): sql syntax error: line 2 col 24 (at pos 34)
		at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
		at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:607)
		at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:510)
		at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
		at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:517)
		at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:971)
		at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
		at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
		at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
		at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
		at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
		at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	aused by: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257] (at 34): sql syntax error: line 2 col 24 (at pos 34)
		at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209)
		at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42)
		at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:837)
		at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:195)
		at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
		at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:5436)
		at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:2528)
		at com.sap.db.jdbc.StatementSapDB._executeDirect(StatementSapDB.java:2249)
		at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:2223)
		at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:2184)
		at com.sap.db.jdbc.StatementSapDB.execute(StatementSapDB.java:696)
		at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
		at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
		... 12 more
	```

### Additional context

Debug it

![Debug DBeaver with VSCode](https://github.com/dbeaver/dbeaver/assets/6383616/c7f2a0f0-b2a6-476c-b91c-7c1252260809)

**Comment by LonwoLonwo** [comment]
Hello @Fang3s 

Please, check your issue in our latest Early Access version https://dbeaver.io/files/ea/
I hope it is fixed there already.

**Comment by Fang3s** [comment]
> Hello @Fang3s
> 
> Please, check your issue in our latest Early Access version https://dbeaver.io/files/ea/ I hope it is fixed there already.
It was fixed if executing the selected SQL,
![It was fixed if executing the selected SQL](https://github.com/dbeaver/dbeaver/assets/6383616/573ed99e-a62b-44f2-b289-c80de929e0e2)

But it was not fixed if executing the SQL where the cursor stayed without any selection, and it reported "Empty query string".
![It was not fixed if executing the SQL where the cursor stayed without any selection](https://github.com/dbeaver/dbeaver/assets/6383616/96872b35-f38e-4f67-b0b5-eed18168264f)


```
org.jkiss.dbeaver.model.sql.parser.SQLScriptParser#extractScriptQueries
org.jkiss.dbeaver.model.sql.parser.SQLScriptParser#extractActiveQuery
public static List<SQLScriptElement> extractScriptQueries(SQLParserContext parserContext, int startOffset, int length, boolean scriptMode, boolean keepDelimiters, boolean parseParameters)
public static SQLScriptElement extractActiveQuery(@NotNull SQLParserContext context, @NotNull IRegion[] regions) 
```
