### ISSUE TITLE
Autosuggester popup doesn't dissapear after selecting option and multiple autosuggester popups present one over another

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#22078]
### Description

Initially everything works fine, but after editing certain complex SQLs containing subqueries, the autosuggester  popup doesn't close anymore. I click on it and press Esc, and the focus goes back to the editor, but the popup remains. 
I noticed that after clicking the popup again and then escape (multiple times, maybe 4-5), finally it disappears, as if there were multiple popups one over another. The bad popups stay visible over other apps after alt-tab!!!

When this happens, the problem is present only on the current editor. Reconnecting to the db doesn't solve the problem, but dBeaver restart does solve it.

The log shows some BadLocationException:

!ENTRY org.jkiss.dbeaver.model 2 0 2023-12-04 01:58:07.348
!MESSAGE Error parsing query
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2023-12-04 01:58:07.348
!MESSAGE BadLocationException
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.get(AbstractDocument.java:958)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.get(SynchronizableDocument.java:130)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.parseQuery(SQLScriptParser.java:298)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.extractScriptQueries(SQLScriptParser.java:908)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.extractScriptQueries(SQLEditorBase.java:883)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.extractQueries(SQLReconcilingStrategy.java:284)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:218)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:100)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:74)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/5fc29858-dc11-4c8b-810f-f0820c49119c)
![image](https://github.com/dbeaver/dbeaver/assets/19900533/e061f69b-eeab-4237-b41e-85af0768d6b2)

### DBeaver Version

23.3.0.202312031432

### Operating System

Linux Mint 20.3

### Database and driver

PostgreSQL 12.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
driver 42.5.2

### Additional context

no tunnels, no ssh

**Comment by Destrolaric** [comment]
@alesc2000 Hi, it looks like providing a query example may help. Can you provide any query after which you encounter following behavior?

**Comment by alesc2000** [comment]
I'm trying to find the action that triggered the problem... So far, today I couldn't find it. I'll let you know when I do.

**Comment by alesc2000** [comment]
I couldn't reproduce the issue. From what I read in the logs it might have also been a network connection issue. I attached the log containing only the period when I had the problems. 
Thanks!
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/13552188/dbeaver.log)

**Comment by E1izabeth** [comment]
Most Probably here is the reason:
```
!ENTRY org.jkiss.dbeaver.model 2 0 2023-12-04 01:31:14.324
!MESSAGE Can't properly handle statement close

!ENTRY org.eclipse.ui 4 0 2023-12-04 01:31:24.994
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.contentassist.ContentAssistant$Closer.focusLost(org.eclipse.swt.events.FocusEvent)" because "this.fCloser" is null
	at org.eclipse.jface.text.contentassist.ContentAssistant.popupFocusLost(ContentAssistant.java:1684)
	at org.eclipse.jface.text.contentassist.PopupCloser.lambda$0(PopupCloser.java:156)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:280)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```
and it happened because of connection issue:
```
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectLookupCache.reloadObject(JDBCObjectLookupCache.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectLookupCache.getObject(JDBCObjectLookupCache.java:59)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getEventTrigger(PostgreDatabase.java:496)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getChild(PostgreDatabase.java:822)
	at org.jkiss.dbeaver.model.DBUtils.findNestedObject(DBUtils.java:374)
	at org.jkiss.dbeaver.model.sql.SQLSearchUtils.findObjectByPath(SQLSearchUtils.java:151)
	at org.jkiss.dbeaver.model.sql.SQLSearchUtils.findObjectByFQN(SQLSearchUtils.java:105)
	at org.jkiss.dbeaver.model.sql.SQLSearchUtils.findObjectByFQN(SQLSearchUtils.java:65)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.getTableFromAlias(SQLCompletionAnalyzer.java:1014)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:340)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:132)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:116)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:348)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	...
```
