### ISSUE TITLE
Clickhouse: IllegalArgumentException: Only groupMap is supported at this point

### ISSUE THREAD

**Issue by ddxv** [dbeaver/dbeaver#22082]
### Description

I encountered this error when querying the destination table for materialized view. Opening `clickhouse-client` the query goes through successfully.

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:607)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:517)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:971)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4135)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:45)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.ClickHouseResultSet.<init>(ClickHouseResultSet.java:136)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.updateResult(ClickHouseStatementImpl.java:393)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:130)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:476)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:464)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.getDeserializer(ClickHouseRowBinaryProcessor.java:511)
	at com.clickhouse.data.ClickHouseDataProcessor$DefaultSerDe.<init>(ClickHouseDataProcessor.java:89)
	at com.clickhouse.data.ClickHouseDataProcessor.getInitializedSerDe(ClickHouseDataProcessor.java:288)
	at com.clickhouse.data.ClickHouseDataProcessor.getColumns(ClickHouseDataProcessor.java:455)
	at com.clickhouse.client.ClickHouseStreamResponse.getColumns(ClickHouseStreamResponse.java:121)
	at com.clickhouse.jdbc.ClickHouseResultSet.<init>(ClickHouseResultSet.java:
```
	
	

### DBeaver Version

Community Edition 23.3.0

### Operating System

Ubuntu 23.10

### Database and driver

Database: ClickHouse server version 23.10.5.20 (official build).
Driver: Official ClickHouse driver (server version 21.3+)

### Steps to reproduce

```sql
SELECT * from offending_table;
```
Will throw the error in dbeaver. Connecting to `clickhouse-client` and running the same query does not throw any error.

### Additional context

The `offending_table` was created by:

```sql
CREATE TABLE offending_table                                                                        
(                                                                                                  
    on_date Date,                                                                                  
     network LowCardinality(String),                                                                
     impressions SimpleAggregateFunction(sum, UInt64),                                              
     clicks SimpleAggregateFunction(sum, UInt64),                                                   
) ENGINE = AggregatingMergeTree ORDER BY (on_date,  network )                                                                                    
```

And it is populated by:
```sql
CREATE MATERIALIZED VIEW daily_mv 
TO offending_table                                 
AS                                                
SELECT                                            
    toDate(event_time) AS on_date,                
    network,                                      
    count() AS clicks                             
FROM                                              
    clicks                                        
GROUP BY                                          
    toDate(event_time) AS on_date,                
    network
;                                                 
```

**Comment by LonwoLonwo** [comment]
Hello @ddxv 

Could you please provide 

```
FROM                                              
    clicks   
```

`clicks` DDL?

**Comment by ddxv** [comment]
@LonwoLonwo apologies, I also cannot seem to recreate this issue anymore from the above. I have this issue over an hour yesterday through several iterations of the above DDLs. The only results I found on the internet were about a driver, but it seemed unrelated to me. At some point, without having done anything obvious, it went away.  

I'll have to say this is not an issue anymore and will close. If I encounter it again I'll be quick to find a way to make it more reproducible. 

Thanks

**Comment by ddxv** [comment]
@LonwoLonwo Actually, I hit the issue again, this time while running a very straight forward example:

```
CREATE DATABASE IF NOT EXISTS analytics;

CREATE TABLE analytics.hourly_data
(
    `domain_name` String,
    `event_time` DateTime,
    `count_views` UInt64
)
ENGINE = Null;


CREATE TABLE analytics.monthly_aggregated_data
(
    `domain_name` String,
    `month` Date,
    `sumCountViews` AggregateFunction(sum, UInt64)
)
ENGINE = AggregatingMergeTree
ORDER BY (domain_name, month)




CREATE MATERIALIZED VIEW analytics.monthly_aggregated_data_mv
TO analytics.monthly_aggregated_data
AS
SELECT
    toDate(toStartOfMonth(event_time)) AS month,
    domain_name,
    sumState(count_views) AS sumCountViews
FROM analytics.hourly_data
GROUP BY
    domain_name,
    month
;    

INSERT INTO analytics.hourly_data (domain_name, event_time, count_views)
VALUES ('clickhouse.com', '2019-01-01 10:00:00', 1),
       ('clickhouse.com', '2019-02-02 00:00:00', 2),
       ('clickhouse.com', '2019-02-01 00:00:00', 3),
       ('clickhouse.com', '2020-01-01 00:00:00', 6)
;

-- This query triggers: ERROR Only groupMap is supported at this point
SELECT sumCountViews FROM analytics.monthly_aggregated_data;
```

edit: the above comes from the first 5 or 6 DDLs from this documentation:
https://clickhouse.com/docs/en/guides/developer/cascading-materialized-views#source-table-for-the-materialized-views

**Comment by ghost** [comment]
I'm experiencing the same issue on a table that is like 117GiB big.
I noticed that the exception is thrown only when I do a SELECT of AggregateFunction data types.
For strings, integers and so forth, no complaints.

`org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: java.lang.IllegalArgumentException: Only groupMap is supported at this point`

I'm running DBeaver CE 23.3.1 with jdbc Clickhouse driver version 0.5.0 on a Ubuntu Server 22.04 LTS machine with XFCE, 2CPU and 4GiB of RAM.

Do I need to configure something on the driver settings to enable the AggregateFunction type??

**Comment by simolesux** [comment]
I got the same error both on Ubuntu 22.0.4 than on Windows 10, I've tried different version of DBEaver withouu any success.
When I try to make a query "Read data in SQL Console" on a aggregated table bigger than a few gigabytes the software return this non explainable error:

`!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-10 09:20:05.590
!MESSAGE Errore SQL: java.lang.IllegalArgumentException: Only groupMap is supported at this point
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-01-10 09:20:05.590
!MESSAGE java.lang.IllegalArgumentException: Only groupMap is supported at this point
!STACK 0
java.sql.SQLException: java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:45)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.ClickHouseResultSet.<init>(ClickHouseResultSet.java:136)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.updateResult(ClickHouseStatementImpl.java:391)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:130)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4093)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.getDeserializer(ClickHouseRowBinaryProcessor.java:511)
	at com.clickhouse.data.ClickHouseDataProcessor$DefaultSerDe.<init>(ClickHouseDataProcessor.java:89)
	at com.clickhouse.data.ClickHouseDataProcessor.getInitializedSerDe(ClickHouseDataProcessor.java:288)
	at com.clickhouse.data.ClickHouseDataProcessor.getColumns(ClickHouseDataProcessor.java:455)
	at com.clickhouse.client.ClickHouseStreamResponse.getColumns(ClickHouseStreamResponse.java:121)
	at com.clickhouse.jdbc.ClickHouseResultSet.<init>(ClickHouseResultSet.java:130)
	... 18 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2024-01-10 09:20:05.590
!MESSAGE Only groupMap is supported at this point
!STACK 0
java.lang.IllegalArgumentException: Only groupMap is supported at this point
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.getDeserializer(ClickHouseRowBinaryProcessor.java:511)
	at com.clickhouse.data.ClickHouseDataProcessor$DefaultSerDe.<init>(ClickHouseDataProcessor.java:89)
	at com.clickhouse.data.ClickHouseDataProcessor.getInitializedSerDe(ClickHouseDataProcessor.java:288)
	at com.clickhouse.data.ClickHouseDataProcessor.getColumns(ClickHouseDataProcessor.java:455)
	at com.clickhouse.client.ClickHouseStreamResponse.getColumns(ClickHouseStreamResponse.java:121)
	at com.clickhouse.jdbc.ClickHouseResultSet.<init>(ClickHouseResultSet.java:130)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.updateResult(ClickHouseStatementImpl.java:391)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:130)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:582)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:934)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4093)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

Depiste that, other collegues, with the same version and same operative system, can successfully complete the query.

I got no idea how to fix this.

**Comment by LonwoLonwo** [comment]
I see this string in [limitations](https://github.com/ClickHouse/metabase-clickhouse-driver#known-limitations):

> As the underlying JDBC driver version does not support columns with AggregateFunction type, these columns are excluded from the table metadata and data browser result sets to prevent sync or data browsing errors.

**Comment by ghost** [comment]
> I see this string in [limitations](https://github.com/ClickHouse/metabase-clickhouse-driver#known-limitations):
> 
> > As the underlying JDBC driver version does not support columns with AggregateFunction type, these columns are excluded from the table metadata and data browser result sets to prevent sync or data browsing errors.

Thanks, that's the answer I was looking for.

**Comment by SteZe85** [comment]
Is there a fix for this error? I am getting it using Clickhouse 24.10. and DBeaver 5.0.0.202503021833 with JDBC 0.6.5

**Comment by adnanjpg** [comment]
hi, how would we get around this? 
I'm getting this error with `Clickhouse 25.1.8.25` using both db tools `DataGrip 2024.1.4 Build #DB-241.17890.24` and `DBeaver Version 25.0.0.202503021833`
