### ISSUE TITLE
Database navigator - Detection of foreign keys (and related features like ER diagrams) doesn't work for duckdb

### ISSUE THREAD

**Issue by sullivanrs** [dbeaver/dbeaver#22136]
### Description

When a foreign key is created in a table using duckdb, it is not recognised by the database navigator. Related features like foreign key dictionaries and presentation of relationships in ER diagram also not working.

**Example**
1. Create following schema:

```
CREATE TABLE table1(id INTEGER PRIMARY KEY, fruit TEXT);

CREATE TABLE table2(
	id INTEGER PRIMARY KEY, 
	table1_id INTEGER, 
	FOREIGN KEY (table1_id) REFERENCES table1(id));
 
INSERT INTO table1(id, fruit) VALUES (1, 'apple'), (2, 'banana');
INSERT INTO table2(id, table1_id) VALUES (1, 1), (2, 1), (3, 2);
```

2. Viewing `table2` in database navigator, no foreign keys are detected.

<img width="726" alt="image" src="https://github.com/dbeaver/dbeaver/assets/4974928/2b21f224-c707-4a53-9308-f559d6482633">

3. Also no relationship detected between tables in ER diagram

<img width="411" alt="image" src="https://github.com/dbeaver/dbeaver/assets/4974928/1ab4206a-53f0-4df3-b784-ff90bd8caef2">

### DBeaver Version

Community version 23.3.0.202312031432

### Operating System

Windows 11

### Database and driver

duckdb JDBC driver v0.9.2

**Comment by sullivanrs** [comment]
Also see https://github.com/duckdb/duckdb-java/issues/149

**Comment by LonwoLonwo** [comment]
Hello @tui-rob 

As I can see, it is not supported by the driver:

```
java.sql.SQLFeatureNotSupportedException: getImportedKeys
	at org.duckdb.DuckDBDatabaseMetaData.getImportedKeys(DuckDBDatabaseMetaData.java:947)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getImportedKeys(JDBCDatabaseMetaDataImpl.java:1206)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareForeignKeysLoadStatement(GenericMetaModel.java:765)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.prepareObjectsStatement(ForeignKeysCache.java:78)
	at org.jkiss.dbeaver.ext.generic.model.ForeignKeysCache.prepareObjectsStatement(ForeignKeysCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:298)
```

We can wait for the answer from DuckDB side (in your ticket). And after that, we can decide - do we need to implement foreign keys reading in our code (the duckdb_constraints contains all necessary info, probably) or DuckDB driver will be updated.

**Comment by E1izabeth** [comment]
We're waiting for changes in DuckDB driver.

**Comment by OmarAshkar** [comment]
I faced this issue also. I think DuckDB driver is updated now https://duckdb.org/docs/stable/sql/constraints.html

**Comment by serge-rider** [comment]
This feature was implemented in DuckDB JDBC driver.
As far as I see in https://github.com/duckdb/duckdb-java/blob/main/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java getExportedKeys is implemented and working.

<img width="1296" height="268" alt="Image" src="https://github.com/user-attachments/assets/67a40fe3-1449-4547-be31-7c28b307dbe1" />

So it is not clear why to fix it from DBeaver side.
