### ISSUE TITLE
XML import is stuck on mapping stage

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#22215]
### Description

Can't import XML files becase there are no columns on mapping page

### DBeaver Version

23.3.0

### Operating System

Win11

### Database and driver

Any

### Steps to reproduce

1. Export any data with DBeaver to XML
2. Start import and select that XML file
3. Go to mapping page

**Expected:** Columns are shown
**Actual:** No columns can bee seen

### Additional context

```
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jkiss.utils.xml.SAXReader.parse(SAXReader.java:112)
	at com.dbeaver.data.importer.DataImporterXML.readColumnsInfo(DataImporterXML.java:64)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamProducerSettings.updateProducerSettingsFromStream(StreamProducerSettings.java:145)
	at org.jkiss.dbeaver.tools.transfer.ui.pages.stream.StreamProducerPageSettings.lambda$11(StreamProducerPageSettings.java:416)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by Destrolaric** [comment]
We probably should add a checkbox to allow importing from XML files with defined DOCTYPE, as a option disabled by default
