### ISSUE TITLE
Could not initialize class com.sun.jna.platform.win32.Advapi32 

### ISSUE THREAD

**Issue by serjiokov** [dbeaver/dbeaver#22223]
### Description

Require to cover by try/catch initialization of class com.sun.jna.platform.win32.Advapi32

Log:
20-12-2023 17:02:00.091 [DBeaver: Task [Data export] runner - Export AWS RDS to GCP storage] DEBUG o.j.dbeaver.registry.task.TaskRunJob - Task 'Export AWS RDS to GCP storage' (c86edcb6-5cb6-4b1a-8c8b-8ee5b2ba1e5d) started
20-12-2023 17:02:00.092 [DBeaver: Task [Data export] runner - Export AWS RDS to GCP storage] ERROR o.j.dbeaver.registry.task.TaskRunJob - Task fatal error
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.Advapi32
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:625)
	at com.sun.jna.platform.win32.Advapi32Util.registryKeyExists(Advapi32Util.java:608)
	at org.jkiss.dbeaver.registry.BasePolicyDataProvider.getRegistryPolicyValue(BasePolicyDataProvider.java:89)
	at org.jkiss.dbeaver.registry.BasePolicyDataProvider.getPolicyValue(BasePolicyDataProvider.java:74)
	at org.jkiss.dbeaver.registry.BasePolicyDataProvider.isPolicyEnabled(BasePolicyDataProvider.java:52)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerExport.executeTask(DTTaskHandlerExport.java:47)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:131)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:97)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

TE  20-12-2023 

### Operating System

Linux

### Steps to reproduce

Export AWS RDS to GCP storage] DEBUG o.j.dbeaver.registry.task.TaskRunJob - Task 'Export AWS RDS to GCP storage' (c86edcb6-5cb6-4b1a-8c8b-8ee5b2ba1e5d)

**Comment by ShadelessFox** [comment]
Caused by https://github.com/dbeaver/pro/issues/2065, already reverted
