### ISSUE TITLE
PostgreSQL: Array type text doesn't have a component type

### ISSUE THREAD

**Issue by ibaraki-douji** [dbeaver/dbeaver#22232]
### Description

It might be related to this issue : https://github.com/dbeaver/dbeaver/issues/13657

I was using NestJS ORM and after setting up a string array column (`@Column('text', {array: true, default: '{"User"}'})`) 

The API work just fine, logging the string array work and i can update from NestJS without any issue.

But on DBeaver i have this nice error :
```
org.jkiss.dbeaver.model.exec.DBCException: Array type text doesn't have a component type
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:74)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:60)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.fetchColumnValue(PostgreArrayValueHandler.java:56)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:203)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5150)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

 i can't see the column content and this is the column according to DBeaver :
![image](https://github.com/dbeaver/dbeaver/assets/72337875/59b18afb-1c62-4d4f-ac24-c307d46803c0)

### DBeaver Version

CE 23.3.0

### Operating System

Ubuntu 20.04

### Database and driver

Server : PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg20.04+1)
Driver : PostgreSQL JDBC Driver 42.5.2

**Comment by ShadelessFox** [comment]
Hello @ibaraki-douji,

The database type is supposed to be `text[]` or `_text`. I'm not sure how the mentioned ORM managed to create such a table.

Can you please try using the `pg_dump` application to retrieve a complete DDL of that table and send it here?

**Comment by ibaraki-douji** [comment]
me neither i used the NestJS docs

there you go :
[db.txt](https://github.com/dbeaver/dbeaver/files/13746043/db.txt)

**Comment by ShadelessFox** [comment]
Thank you for the quick response.

I don't see anything suspicious. Moreover, the actual data type shown in the DDL is indeed `text[]`.

The only thing I noticed is that you are using PostgreSQL 16. We haven't tested this version heavily, so it might be possible that something was changed on the database side.

We will investigate the issue.

**Comment by ibaraki-douji** [comment]
Hi,
So i think it was a NestJS problem, this morning after i relaunched NestJS the roles column worked fine on the UI.
![image](https://github.com/dbeaver/dbeaver/assets/72337875/7d818579-e185-49ff-b111-7712321b209a)
![image](https://github.com/dbeaver/dbeaver/assets/72337875/b1f2c432-da99-4068-8f70-2cf89eec5f5b)
So i mark this as resolved ;)
