### ISSUE TITLE
Error downloading driver libraries

### ISSUE THREAD

**Issue by kczx3** [dbeaver/dbeaver#22259]
### Description

I updated to 23.3.1.202312241705 today and noticed in the release notes that there was a newer Oracle library version being used.  When DBeaver started, it attempted to download the libraries but I receive an error message (seen below).

> Error downloading driver libraries
> 
> Reason:
> Error resolving dependencies
>   Index 0 out of bounds for length 0

<details>
<summary>Log from .log:</summary>

```
!ENTRY org.jkiss.dbeaver.model 4 0 2023-12-26 13:23:21.481
!MESSAGE Index 0 out of bounds for length 0
!STACK 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.getFileURL(MavenArtifact.java:309)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.getRemotePOMLocation(MavenArtifactVersion.java:252)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.cachePOM(MavenArtifactVersion.java:259)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.loadPOM(MavenArtifactVersion.java:277)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.<init>(MavenArtifactVersion.java:101)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.makeLocalVersion(MavenArtifact.java:345)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:424)
	at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:204)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:226)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:185)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getArtifactVersion(DriverLibraryMavenArtifact.java:202)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:339)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:130)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.jkiss.dbeaver.model 2 0 2023-12-26 13:24:51.989
!MESSAGE Can't load driver properties
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2023-12-26 13:24:51.989
!MESSAGE Error creating driver 'Oracle' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'oracle.jdbc.OracleDriver'
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2023-12-26 13:24:51.989
!MESSAGE oracle.jdbc.OracleDriver
!STACK 0
java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1243)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1176)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:716)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSourceProvider.getConnectionProperties(JDBCDataSourceProvider.java:63)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.loadDriverProperties(ConnectionPropertiesControl.java:164)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.makeProperties(ConnectionPropertiesControl.java:85)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage.lambda$0(DriverPropertiesDialogPage.java:89)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
</details>

<details>
<summary>Log from dbeaver-debug.log:</summary>

```
2023-12-26 13:23:19.427 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2023-12-26 13:23:21.229 - Open [https://repo1.maven.org]
2023-12-26 13:23:21.472 - Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.getFileURL(MavenArtifact.java:309)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.getRemotePOMLocation(MavenArtifactVersion.java:252)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.cachePOM(MavenArtifactVersion.java:259)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.loadPOM(MavenArtifactVersion.java:277)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.<init>(MavenArtifactVersion.java:101)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.makeLocalVersion(MavenArtifact.java:345)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:424)
	at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:204)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:226)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:185)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getArtifactVersion(DriverLibraryMavenArtifact.java:202)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:339)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:130)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2023-12-26 13:24:51.986 - Can't load driver properties
org.jkiss.dbeaver.DBException: Error creating driver 'Oracle' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'oracle.jdbc.OracleDriver'
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1245)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1176)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:716)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSourceProvider.getConnectionProperties(JDBCDataSourceProvider.java:63)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.loadDriverProperties(ConnectionPropertiesControl.java:164)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.makeProperties(ConnectionPropertiesControl.java:85)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage.lambda$0(DriverPropertiesDialogPage.java:89)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1243)
	... 8 more
```
</details>

### DBeaver Version

23.3.1.202312241705

### Operating System

Windows 10.0.19045.3803

### Database and driver

oracle.jdbc.OracleDriver
23.2.0.0

### Steps to reproduce

Attempt to connect to an Oracle database without the necessary drivers installed yet.

### Additional context

I thought maybe it was a proxy issue but entering credentials for my organization's proxy didn't improve the situation.

**Comment by kczx3** [comment]
I got it to work by manually downloading the new jar and also deleting all the maven libraries from the Driver configuration.  No idea if that should be necessary though.

**Comment by Destrolaric** [comment]
@kczx3 Hi, do you have a configuration similar to this
![image](https://github.com/dbeaver/dbeaver/assets/20579256/91264510-c1c7-4cfb-a593-e1c055b34b4c)
I can't reproduce the issue

**Comment by kczx3** [comment]
@Destrolaric Yes, if I go to edit the driver and click Restore Defaults, then I get four libraries.  One of them is the one in your screenshot and clicking Edit shows a similar window as yours.

![image](https://github.com/dbeaver/dbeaver/assets/15206020/2dfc6912-b5de-4886-9257-33c8555daf23)

But then if I click Download/Update it tries and I get the below error:
![image](https://github.com/dbeaver/dbeaver/assets/15206020/a4c6c76d-9843-4fca-8d41-5aed4d4f3470)

**Comment by Destrolaric** [comment]
@kczx3 Will download still fail if xdb6 is excluded?

**Comment by kczx3** [comment]
I tried removing it and downloading but received the same error.  I then removed the rest one-by-one and each time I tried downloading I got the same error.

**Comment by Destrolaric** [comment]
Please send me a screenshot of the `Connections -> Drivers -> Maven` repository settings.

**Comment by kczx3** [comment]
I don't think I've changed anything here but honestly can't remember.

![image](https://github.com/dbeaver/dbeaver/assets/15206020/41aef829-3a56-4121-8dbc-f8c12ba95141)

**Comment by Destrolaric** [comment]
Thanks for the screenshots, it looks like there may, indeed be a bug.
As a workaround: Can you try to lower the Sonatype snapshot repo to the bottom?

**Comment by thomas-gantenbein-tga** [comment]
I'm having the same issue. I lowered the Sonatype snapshot repo to the bottom. Now it's saying

```
!MESSAGE Maven artifact 'maven:/com.oracle.database.jdbc:ojdbc11:RELEASE' not found
!STACK 0
java.io.IOException: Maven artifact 'maven:/com.oracle.database.jdbc:ojdbc11:RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:341)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
```

But maybe that's a different/additional issue.

**Comment by thomas-gantenbein-tga** [comment]
Update: Moving down the Sonatype snapshot repo _did_ work and I got rid of the other error by creating a new workspace. Don't know what the problem was with the existing one, but with a fresh workspace and the moved snapshot repository, it works fine now.

**Comment by kczx3** [comment]
Moving the Sonatype repo to the bottom of the list appears to have worked for me.  I did that, then went to the Driver Manager and reset the Oracle libraries to the default and then clicked the Download/Update button.  Everything worked smoothly then.

**Comment by alexey-emr** [comment]
Just updated to 23.3.2 and having the same issue. Moving the Sonatype repo to the bottom did not work for me.

**Comment by landy8530** [comment]
> Just updated to 23.3.2 and having the same issue. Moving the Sonatype repo to the bottom did not work for me.

Same issues for me, details see https://github.com/dbeaver/dbeaver/issues/22853

**Comment by landy8530** [comment]
> I don't think I've changed anything here but honestly can't remember.
> 
> ![image](https://private-user-images.githubusercontent.com/15206020/293214337-41aef829-3a56-4121-8dbc-f8c12ba95141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDAyNzIsIm5iZiI6MTcwODM5OTk3MiwicGF0aCI6Ii8xNTIwNjAyMC8yOTMyMTQzMzctNDFhZWY4MjktM2E1Ni00MTIxLThkYmMtZjhjMTJiYTk1MTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAzMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzRhZWE4MzMyMGJjM2ZmMGUyN2Y4OGMwNDdiNzdlMWQ1MDQwMTkxMDA0Y2RkODBkNGIxZWVlODA1Y2IyY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUH4eBeTx7eTd7nWiYVMTPYtdVveLIHxqIGspjVPPjQ)

Where is the screenshot?

**Comment by kanxinqing147** [comment]
I reinstalled the dbeaver, and I encountered the same problem, but I solved it.  
Go to the setting `Connections -> Drivers`，and see if `Local folder` is empty, please set a path. The right setting is shown in the screenshot below.  
<img width="437" alt="屏幕截图 2024-02-23 202520" src="https://github.com/dbeaver/dbeaver/assets/70000323/99c66d9e-9ba0-4e63-990c-d1eabb70b7b3">
I'm very sure that in previous versions this setting wasn't empty, there should have a default path.

**Comment by Marco-Sulla** [comment]
I had the same problem. I navigated to `Window - Preferences -> Connections -> Drivers -> Maven` and I pressed `Restore defaults`. After that it worked. Notice that I never touched the DBeaver settings.
