### ISSUE TITLE
Task problem due to org.jkiss.dbeaver.DBException: Error executing script '/General/Scripts'

### ISSUE THREAD

**Issue by fyuan549** [dbeaver/dbeaver#22304]
### Description

I have a script created under /General/Scripts, and schedule a task for it. When executing it I keep getting error below. 

2024-01-02 10:03:03.783 - No SQL dialect specified for data source provider 'informix'. Use default.
2024-01-02 10:03:03.791 - Loading user drivers configuration from 'C:\Users\FYuan\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.jkiss.dbeaver.core\drivers.xml'
2024-01-02 10:03:03.802 - Total database drivers: 97 (97)
2024-01-02 10:03:03.819 - SQL Scripts Execute
2024-01-02 10:03:03.823 - org.jkiss.dbeaver.DBException: Error executing script '/General/Scripts/Script-3.sql'
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:136)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.lambda$0(SQLScriptExecuteHandler.java:78)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:124)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeWithSettings(SQLScriptExecuteHandler.java:76)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeTask(SQLScriptExecuteHandler.java:65)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:119)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/General/Scripts/Script-3.sql' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:330)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:204)
	at org.eclipse.core.internal.resources.File.getContents(File.java:273)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:101)
	... 8 more
Caused by: java.lang.Exception: Resource '/General/Scripts/Script-3.sql' does not exist.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	... 12 more
2024-01-02 10:03:03.844 - SQL script execute completed

### DBeaver Version

Enterprise version 7.3.0.202012061950

### Operating System

windows server 2019 datacenter

**Comment by ShadelessFox** [comment]
Hello @fyuan549,

Are you sure the script "Script-3.sql" exists under the "Scripts" directory?

**Comment by fyuan549** [comment]
it is. I closed the app and reopened it. It works now.

**Comment by ShadelessFox** [comment]
Glad the issue was resolved. I will close the ticket for now. Please feel free to reopen if you manage to reproduce the issue again.
