### ISSUE TITLE
Tuple typed rows in Cassandra db not showing correct value

### ISSUE THREAD

**Issue by abalteaux** [dbeaver/dbeaver#2231]
tried with multiple tables, rows defined as tuples always show null value instead of their correct value.

corresponding stacktrace:

> org.jkiss.dbeaver.model.exec.DBCException: Unsupported struct type: com.datastax.driver.core.TupleValue
at com.dbeaver.ent.cassandra.data.handlers.CasContentValueHandler.getValueFromObject(CasContentValueHandler.java:65)
at com.dbeaver.ent.cassandra.data.handlers.CasContentValueHandler.fetchValueObject(CasContentValueHandler.java:48)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
at com.dbeaver.ent.cassandra.model.CasTableBase.readData(CasTableBase.java:143)
at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Please post sample table definition with some data insert.
And what is your Cassandra version?

**Comment by tati-kru** [comment]
hi @abalteaux 
Are there any updates about this ticket?

**Comment by normenmueller** [comment]
I'm interested in this too. Recently purchased DBeaver EE.

Is there currently at least a workaround to view the values of a "tuple column"?

**Comment by serge-rider** [comment]
Please check the fix in EA version (https://dbeaver.com/files/ea/)
