### ISSUE TITLE
DataExporterXLSX generate an error when 0 rows fetched

### ISSUE THREAD

**Issue by RoiSoleil** [dbeaver/dbeaver#22370]
### Description

DataExporterXLSX generate an error when 0 rows fetched

2024-01-08 09:16:31.952 - 	0 rows fetched
2024-01-08 09:16:31.952 - Error while exporting table footer
java.lang.IllegalArgumentException: Sheet index (0) is out of range (no sheets)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1491)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetAt(XSSFWorkbook.java:1193)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.getSheetAt(SXSSFWorkbook.java:799)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.exportFooter(DataExporterXLSX.java:503)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.exportFooterInFile(StreamTransferConsumer.java:263)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.finishTransfer(StreamTransferConsumer.java:624)
	at org.jkiss.dbeaver.tools.transfer.IDataTransferConsumer.finishTransfer(IDataTransferConsumer.java:78)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.finishTransfer(StreamTransferConsumer.java:618)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTrans

### DBeaver Version

DBeaver 23.3.2

### Additional context

Office Extensions

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.

**Comment by RoiSoleil** [comment]
Have you tried to open the resulting XLSX ?

**Comment by E1izabeth** [comment]
I see the bug. We will fix it.
