### ISSUE TITLE
23.3.2 custom unique key no response

### ISSUE THREAD

**Issue by Doublefire-Chen** [dbeaver/dbeaver#22383]
### Description

Today morning, I just updated my DBeaver from [23.3.1] to [23.3.2], and I was operating a new table. I did not set an unique key, so when I tried to save my edits, it failed and remind me set an unique key. When I click the button "custom unique key", it is no response. Even though I set it using SQL command in console, it still was not effective. After I downgraded into [23.3.1], everything worked fine.

### DBeaver Version

Community Edition 23.3.2

### Operating System

macOS Sonoma 14.0 (23A344)

### Database and driver

1. Database name and version: PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
2. Driver name and version: PostgreSQL 14.10 (Homebrew)

### Steps to reproduce

1. create a new table
2. edit some data
3. try to save
4. it will pop up a window remindering you to set a unique key, just click it and nothing will happen

**Comment by LonwoLonwo** [comment]
Thanks for the bug report @Doublefire-Chen 

The error log:

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.updateMessage()" because "this.container" is null
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.setErrorMessage(BaseObjectEditPage.java:51)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.validateProperties(BaseObjectEditPage.java:59)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditConstraintPage.createContentsBeforeColumns(EditConstraintPage.java:174)
	at org.jkiss.dbeaver.ui.editors.object.struct.AttributesSelectorPage.createPageContents(AttributesSelectorPage.java:150)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditConstraintPage.createPageContents(EditConstraintPage.java:95)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditConstraintPage.createPageContents(EditConstraintPage.java:1)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.createControl(BaseObjectEditPage.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.virtual.EditVirtualEntityDialog.createUniqueKeysPage(EditVirtualEntityDialog.java:232)
	at org.jkiss.dbeaver.ui.controls.resultset.virtual.EditVirtualEntityDialog.createDialogArea(EditVirtualEntityDialog.java:136)
	at org.jkiss.dbeaver.ui.controls.resultset.virtual.EditVirtualEntityDialog.createDialogArea(EditVirtualEntityDialog.java:1)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:767)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.createContents(BaseDialog.java:74)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.create(BaseDialog.java:89)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.editEntityIdentifier(ResultSetViewer.java:4719)
	at org.jkiss.dbeaver.ui.controls.resultset.ValidateUniqueKeyUsageDialog.editCustomKey(ValidateUniqueKeyUsageDialog.java:87)
	at org.jkiss.dbeaver.ui.controls.resultset.ValidateUniqueKeyUsageDialog.buttonPressed(ValidateUniqueKeyUsageDialog.java:76)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:609)
	at org.jkiss.dbeaver.ui.controls.resultset.ValidateUniqueKeyUsageDialog.validateUniqueKey(ValidateUniqueKeyUsageDialog.java:145)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.lambda$1(ResultSetPersister.java:572)
	at org.jkiss.dbeaver.ui.UITask$1.runTask(UITask.java:42)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:25)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:34)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at org.jkiss.dbeaver.ui.UIUtils.syncExec(UIUtils.java:1950)
	at org.jkiss.dbeaver.ui.UITask.execute(UITask.java:31)
	at org.jkiss.dbeaver.ui.UITask.run(UITask.java:44)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.checkEntityIdentifiers(ResultSetPersister.java:572)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.createDataPersister(ResultSetViewer.java:4403)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.saveChanges(ResultSetViewer.java:4315)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:4303)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.ResultSetHandlerMain.execute(ResultSetHandlerMain.java:329)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:99)
	at jdk.internal.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:298)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:232)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:287)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```
