### ISSUE TITLE
Failed to Execute the request while Configuring DBeaver 

### ISSUE THREAD

**Issue by raghavraj112** [dbeaver/dbeaver#22438]
### Description

Failed to Execute the request while configuring DBeaver for Salesforce.
Failed to get Config from server, Failed to execute the request
![Screenshot (3)](https://github.com/dbeaver/dbeaver/assets/156401071/bdc8a8f2-18d2-473e-8c19-03588e11c044)

### DBeaver Version

Version 23.3.2.202401072024

### Operating System

Windows 11

### Database and driver

Salesforce 
![Screenshot (4)](https://github.com/dbeaver/dbeaver/assets/156401071/c26ac5a0-0934-44e5-baab-59dd4ae3dfe6)

### Steps to reproduce

I Tried to connect New DB
Salesforce
Entered User name and Password
Added Jar file under libraries 
Entered Driver Properties and values for them 
Click on test connection.

getting error Message ( Failed to get Config from server, Failed to execute the request)

**Comment by LonwoLonwo** [comment]
Hello @raghavraj112 

Are you trying to connect to Salesforce or Salesforce CDP? Because they have different connectors.

You can read more about how to connect to Salesforce (not CDP) here: https://github.com/dbeaver/dbeaver/wiki/Database-driver-Salesforce

**Comment by raghavraj112** [comment]
I'm trying to connect to Salesforce CDP, Please help me with that.

**Comment by LonwoLonwo** [comment]
Ok.
Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by raghavraj112** [comment]
Please look into log file


!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-16 19:01:32.994
!MESSAGE failed to execute the request.
!STACK 0
java.io.IOException: failed to execute the request.
	at com.salesforce.cdp.queryservice.interceptors.RetryInterceptor.intercept(RetryInterceptor.java:64)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.salesforce.cdp.queryservice.interceptors.MetadataCacheInterceptor.intercept(MetadataCacheInterceptor.java:46)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getResponse(QueryExecutor.java:129)
	at com.salesforce.cdp.queryservice.util.QueryExecutor.getQueryConfig(QueryExecutor.java:109)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.getQueryConfigResponse(QueryServiceConnection.java:463)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.isValid(QueryServiceConnection.java:354)
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.<init>(QueryServiceConnection.java:78)
	at com.salesforce.cdp.queryservice.QueryServiceDriver.connect(QueryServiceDriver.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:159)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:124)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1315)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1163)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:960)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
What driver version did you use? You can check this info in your connection settings -> driver settings -> libraries.

Also, are you sure that you can connect with your login/password in other places, and this is DBeaver issue?

**Comment by raghavraj112** [comment]
Salesforce-CDP-jdbc-1.19.2-java8 is the jar file.

Yes those credentials are working fine for everyone in a team.

**Comment by ShadelessFox** [comment]
Hello @raghavraj112,

Are you sure you're using the same driver version as your colleagues?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
