### ISSUE TITLE
Error occurred during desktop platform initialization, unable to find tree element.

### ISSUE THREAD

**Issue by Jinkes-li** [dbeaver/dbeaver#22529]
### Description

1.When multiple users are using DBeaver on a Windows 2019 Server, an error of not finding the tree element occurs at regular intervals.

2. The logs are as follows

!ENTRY org.eclipse.osgi 4 0 2023-09-14 14:19:01.073
!MESSAGE application error
!STACK 1
java.lang.IllegalStateException: Error initializing desktop platform
   at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:109)
   at org.jkiss.dbeaver.core.DesktopPlatform.getInstance(DesktopPlatform.java:85)
   at org.jkiss.dbeaver.core.DesktopAdapterFactory.getAdapter(DesktopAdapterFactory.java:33)
   at org.eclipse.core.internal.runtime.AdapterManager.lambda$13(AdapterManager.java:302)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
   at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
   at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
   at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
   at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
   at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
   at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
   at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
   at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
   at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:304)
   at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:328)
   at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:743)
   at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:718)
   at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:733)
   at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:45)
   at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.initDebugWriter(DBeaverApplication.java:631)
   at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:238)
   at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
   at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
   at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
   at org.jkiss.dbeaver.core.DesktopPlatform.initialize(DesktopPlatform.java:155)
   at org.jkiss.dbeaver.core.DesktopPlatform.createInstance(DesktopPlatform.java:105)
   ... 34 more
Caused by: java.lang.ClassNotFoundException: Automatically activated bundle org.eclipse.core.resources Error occurred during（45）。
   at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
   at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
   at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
   at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
   at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
   at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:484)
   at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
   at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
   at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
   ... 36 more
Caused by: org.osgi.framework.BundleException: Unexpected issue in org.eclipse.core.resources.ResourcesPlugin. Method start() in bundle org.eclipse.core.resources.
   at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
   at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:762)
   at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
   at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
   at org.eclipse.osgi.container.Module.doStart(Module.java:605)
   at org.eclipse.osgi.container.Module.start(Module.java:468)
   at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
   at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
   ... 44 more
Caused by: org.eclipse.core.internal.dtree.ObjectNotFoundException: Unable to find tree element“/General/Scripts/Script-2.sql”。
   at org.eclipse.core.internal.dtree.AbstractDataTree.handleNotFound(AbstractDataTree.java:260)
   at org.eclipse.core.internal.dtree.DeltaDataTree.getData(DeltaDataTree.java:599)
   at org.eclipse.core.internal.dtree.DataDeltaNode.asBackwardDelta(DataDeltaNode.java:54)
   at org.eclipse.core.internal.dtree.NoDataDeltaNode.asBackwardDelta(NoDataDeltaNode.java:63)
   at org.eclipse.core.internal.dtree.NoDataDeltaNode.asBackwardDelta(NoDataDeltaNode.java:63)
   at org.eclipse.core.internal.dtree.DataDeltaNode.asBackwardDelta(DataDeltaNode.java:51)
   at org.eclipse.core.internal.dtree.DeltaDataTree.asBackwardDelta(DeltaDataTree.java:91)
   at org.eclipse.core.internal.dtree.DeltaDataTree.reroot(DeltaDataTree.java:835)
   at org.eclipse.core.internal.dtree.DeltaDataTree.reroot(DeltaDataTree.java:834)
   at org.eclipse.core.internal.dtree.DeltaDataTree.reroot(DeltaDataTree.java:834)
   at org.eclipse.core.internal.dtree.DeltaDataTree.reroot(DeltaDataTree.java:811)
   at org.eclipse.core.internal.watson.ElementTree.immutable(ElementTree.java:522)
   at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:731)
   at org.eclipse.core.internal.resources.SaveManager.startup(SaveManager.java:1555)
   at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2482)
   at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2233)
   at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:475)
   at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:813)
   at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
   at java.base/java.security.AccessController.doPrivileged(Native Method)
   at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:805)
   ... 51 more

### DBeaver Version

22.0.2

### Operating System

Windows 2019 Server 

### Database and driver

1. Database name and version : clickhouse 23.7.3.14. Driver name and version ：Yandex ClickHouse driver (server version 21.3+)

### Steps to reproduce

In a multi-user scenario, the issue tends to reoccur approximately every month. The temporary workaround is to remove the 'workspace6' directory under AppData\Roaming\DBeaverData.

### Additional context

Not using a tunnel or other.

**Comment by harin** [comment]
I'm having the same problem. Seems like its the same problem as https://github.com/dbeaver/dbeaver/issues/22101 (which was closed without a working solution)

In my case, it's not on a server but my personal laptop with a single user.

**Comment by Matvey16** [comment]
@Jinkes-li Thank you for the report. This seems like an eclipse issue that happens on many different applications based on eclipse. Current workaround is to delete `workspace6/.metadata/.plugins/org.eclipse.core.resources`. You don't need to delete the whole workspace. We will investigate if we can change something to resolve this issue in DBeaver specifically

**Comment by Matvey16** [comment]
Can you also try updating DBeaver to the latest version? This issue may have been already fixed by Eclipse themselves.

**Comment by Jinkes-li** [comment]
@Matvey16 Thank you very much for your advice. I have updated to the latest version, and everything is fine now.

**Comment by Jinkes-li** [comment]
@harin Currently, I have upgraded to the latest version, and recently, I haven't encountered any issues using it. However, I am not sure if there are still any problems that may arise in the future.

**Comment by serjiokov** [comment]
@harin Thanks for the report, if there is no issue using the last version I suggest closing this ticket.

**Comment by harin** [comment]
@serjiokov I think you should ask @Jinkes-li to close the issue instead?

I think the issue have resolved itself on my end as well. (I think I reinstalled the program)
