### ISSUE TITLE
The outline view throws an `UnsupportedOperationException` when saving a console

### ISSUE THREAD

**Issue by ShadelessFox** [dbeaver/dbeaver#22550]
### Description

```
java.lang.UnsupportedOperationException
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage$2.updateElement(SQLEditorOutlinePage.java:135)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:1014)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:259)
```

### DBeaver Version

DBeaver 23.3.3

### Steps to reproduce

1. Make sure the outline view is open
2. Open a new console
3. Write something in it
4. Hit Ctrl+S to save it as a script

### Additional context

This error keeps popping up when making changes. The only way to stop it is to reopen the script.

**Comment by ShadelessFox** [comment]
Duplicate of https://github.com/dbeaver/pro/issues/2364
