### ISSUE TITLE
Can't download MS SQL driver

### ISSUE THREAD

**Issue by Pepan7** [dbeaver/dbeaver#22574]
### Description

I want connect to MS SQL database, but I can't.
From log file:
```
2024-01-24 12:18:38.209 - Open [https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/12.4.2.x64/mssql-jdbc_auth-12.4.2.x64.pom]
2024-01-24 12:18:39.370 - Error loading version info: Can't open 'https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/12.4.2.x64/mssql-jdbc_auth-12.4.2.x64.pom': Not Found
2024-01-24 12:18:39.388 - Open [https://repo1.maven.org]
2024-01-24 12:18:40.567 - Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.getFileURL(MavenArtifact.java:309)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.getRemotePOMLocation(MavenArtifactVersion.java:252)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.cachePOM(MavenArtifactVersion.java:259)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.loadPOM(MavenArtifactVersion.java:277)
	at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.<init>(MavenArtifactVersion.java:101)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.makeLocalVersion(MavenArtifact.java:345)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:424)
	at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:204)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:226)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:185)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getArtifactVersion(DriverLibraryMavenArtifact.java:202)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:339)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:247)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:130)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2024-01-24 12:18:42.518 - Error creating driver 'MS SQL Server / SQL Server' instance.
Most likely required jar files are missing.
```
![image](https://github.com/dbeaver/dbeaver/assets/23340536/c3ee66fb-5cbb-4b10-a954-36e8bea90927)
![image](https://github.com/dbeaver/dbeaver/assets/23340536/a98942f1-33d5-4e1c-b30e-32ff86519534)

### DBeaver Version

Community Edition 23.3.3

### Operating System

Windows 10

**Comment by E1izabeth** [comment]
Indeed. Thank you for reporting
mssql-jdbc_auth-12.4.2.x64.pom file disappeared  from here https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth

**Comment by E1izabeth** [comment]
@Pepan7 have you manually changed the driver version? By default, the driver version we use is 12.4.1 and it works fine with this version

**Comment by E1izabeth** [comment]
To solve your issue, you can do the following steps.

1. Open the Driver Manager
![image](https://github.com/dbeaver/dbeaver/assets/28875055/255a6aa8-83c0-4543-aefb-5df862d6c226)

2. Find your database and press `Edit`
![image](https://github.com/dbeaver/dbeaver/assets/28875055/cd2b1c5c-f8af-4a7b-925a-263417aa2cda)

3. Remove artifacts with driver version12.4.2
![image](https://github.com/dbeaver/dbeaver/assets/28875055/ccc5370b-d584-4002-8291-bd10201eca82)

4. Go to the maven repository of mssql and download the artifacts you see here, but of another version.
https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.1.jre11/mssql-jdbc-12.4.1.jre11.jar
https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/12.4.1.x64/mssql-jdbc_auth-12.4.1.x64.dll

5. Use `Add file` button to add these files as driver files.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/5ac10b5e-f2df-46c7-9ac1-7942f45c8527)

**Comment by Pepan7** [comment]
It's worked, but I want use the newest version and I want dowload drivers in program and don't manual dowload and copy to program.

**Comment by E1izabeth** [comment]
It's not a DBeaver issue that the maven artifact of the version 12.4.2 of mssql driver is broken https://github.com/microsoft/mssql-jdbc/issues/2263#issuecomment-1849467585. Unfortunately, we can do nothing here.

**Comment by martinschilliger** [comment]
Is it possible, that this happend again with 12.7.0?

**Comment by E1izabeth** [comment]
@martinschilliger here is the issue https://github.com/dbeaver/dbeaver/issues/34949
You can download Early Access version with fix https://dbeaver.io/files/ea/

**Comment by martinschilliger** [comment]
Ah, thank you! 
I solved it with completly manually installing the driver, but forwarded the link to a colleague. 👍
