### ISSUE TITLE
Create a way to export database tasks

### ISSUE THREAD

**Issue by LawrenceLau2020** [dbeaver/dbeaver#22579]
A way to export database tasks would be great. That way we can share tasks with other users who are working in different environments.

Have a way to export tasks, that other users can "import" using a json file.

Right now, there is a workaround, but it involves manually copying the tasks.json file in: C:\Users\userDirectory\AppData\Roaming\DBeaverData\workspace6\General\.dbeaver

**Comment by LonwoLonwo** [comment]
Hello @LawrenceLau2020 

Thanks for the idea.

**Comment by slanglade** [comment]
Can't agree more  : that's a good idea. I created a task to be used by support teams, and it's going to be hazadous to have them recreate the task from scratch.

**Comment by sompote-pi** [comment]
Bump up this topic, it's must-have feature

**Comment by LonwoLonwo** [comment]
You can vote for the main topic with the :+1: emoji, then.

**Comment by Blueglassornament** [comment]
Excellent idea!

**Comment by E1izabeth** [comment]
Tasks should be exported with the project export. Let's check if it works so.

**Comment by MashaKorax** [comment]
@E1izabeth, it works, but you need to improve cross-platform export-import  (Windows-MacOs), when you have native tasks : MySQL backup- restore, MySQL script, etc.
STR:
-On Windows app create MySql restore task
-Export project with this task
-Import this project on Mac app
-Open tasks
-Try to open task for editing

https://github.com/user-attachments/assets/d772fd89-afaa-4d64-9be7-cb46b6d513a3

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.DBPDataSourceContainer.getConnectionConfiguration()" because the return value of "org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolSettings.getDataSourceContainer()" is null
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeToolWizard.readLocalClientInfo(AbstractNativeToolWizard.java:149)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeToolWizard.initializeWizard(AbstractNativeToolWizard.java:142)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.createDialogArea(TaskConfigurationWizardDialog.java:135)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.jkiss.dbeaver.ui.dialogs.MultiPageWizardDialog.createContents(MultiPageWizardDialog.java:149)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.createContents(TaskConfigurationWizardDialog.java:256)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerEdit.execute(TaskHandlerEdit.java:56)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:385)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:801)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$7(CommandContributionItem.java:778)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1392)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
```
