### ISSUE TITLE
Snowflake Dynamic Table properties panel triggers error message

### ISSUE THREAD

**Issue by Thomas-LEILLET-Sanofi** [dbeaver/dbeaver#22601]
### Description

When displaying properties of Snowflake Dynamic Table, it displays following error on "Keys" and "Foreign Keys" : 
![image](https://github.com/dbeaver/dbeaver/assets/130557869/7ec66b1a-a932-4845-8f77-530c22e70bc3)

Not sure if the other properties panel "Reference" works correctly either.

### DBeaver Version

CE Version 23.3.3.20240121183

### Operating System

Win11 23H2 (Build 22631.2715)

### Database and driver

Snowflake JDBC 3.13.29

**Comment by LonwoLonwo** [comment]
Hello @Thomas-LEILLET-Sanofi 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Thomas-LEILLET-Sanofi** [comment]
This is the trace generated at the exact event of the error : (and exact content of ".log" file.
Do you need the log history too ?


```
!SESSION 2024-01-27 20:51:10.472 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -eclipse.keyring C:\Users\Thoma\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\Thoma\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2024-01-27 20:52:39.885

!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-27 20:52:39.885
!MESSAGE SQL compilation error: show [constraint] command doesnt support this domain.
!STACK 0
net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error: show [constraint] command doesnt support this domain.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:130)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:70)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:133)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.executeAndReturnEmptyResultIfNotFound(SnowflakeDatabaseMetaData.java:3435)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getPrimaryKeys(SnowflakeDatabaseMetaData.java:2067)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getPrimaryKeys(JDBCDatabaseMetaDataImpl.java:1197)
	at org.jkiss.dbeaver.ext.snowflake.model.SnowflakeMetaModel.prepareUniqueConstraintsLoadStatement(SnowflakeMetaModel.java:172)
	at org.jkiss.dbeaver.ext.generic.model.ConstraintKeysCache.prepareObjectsStatement(ConstraintKeysCache.java:58)
	at org.jkiss.dbeaver.ext.generic.model.ConstraintKeysCache.prepareObjectsStatement(ConstraintKeysCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:298)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getConstraints(GenericTableBase.java:251)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getConstraints(GenericTableBase.java:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:981)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1053)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:596)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:465)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:228)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:308)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by LonwoLonwo** [comment]
I'm not sure that dynamic tables can have keys. I do not see this part in the documentation: https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table

We need probably to keep dynamic tables in a separate folder and not add keys folders to them.

**Comment by LonwoLonwo** [comment]
Thanks for the report.

**Comment by Thomas-LEILLET-Sanofi** [comment]
> I'm not sure that dynamic tables can have keys. I do not see this part in the documentation: https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table
> 
> We need probably to keep dynamic tables in a separate folder and not add keys folders to them.

As a matter of fact, it seems they can, as adding a PK constraint to a Dynamic table makes the PK appear at least in the `show primary keys` listing... However their DDL does not seem changed. Maybe an unfinished stuff Snowflake-side.
Depending on how DBeaver list PK from a Dynamic Table, it should anyway not trigger an error.
