### ISSUE TITLE
Error when importing CSV - tab delimited - into Oracle

### ISSUE THREAD

**Issue by Vichman67** [dbeaver/dbeaver#22612]
### Description

Hello,

When trying to import the attached CSV UTF-8 tab delimited files into an Oracle database table the field called ALIAS throws an exception. In the case of Test1.csv there is only that ALIAS field (for the sake of simplicity) and the import proceeds without warnings but the resulting field imported into the Oracle table contains just ")".

But in the case of Test2.csv the importing process ends on error and no filed gets imported. The error log shown is as follows:

```
Error transfering data from Test2.csv to IID.AAA_TEST_VH2 [Existing]
An exception stack trace is not available.
Cannot invoke "String.trim()" because "line[i]" is null
java.lang.NullPointerException: Cannot invoke "String.trim()" because "line[i]" is null
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:259)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:161)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:113)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:86)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```
[Test1.csv](https://github.com/dbeaver/dbeaver/files/14081909/Test1.csv)
[Test2.csv](https://github.com/dbeaver/dbeaver/files/14081910/Test2.csv)

The fact is theat when trying to import those two files with other database client software (e.g. Toad for Oracle) the process ends on success.

Is it a bug from DBeaver?

### DBeaver Version

Enterprise Edition r. 23.3.0.202312121701

### Operating System

Windows 10 64-bit r. 22H2

### Database and driver

Database name: Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
Dirver name: oracle_thin (Oracle JDBC driver) bundled with DBeaver

### Steps to reproduce

1. Connect to database from DBeaver.
2. Under database navigator, "Tables" section, right click to "Import data" with these parameters:
3. Import source: CSV.
4. Select test CSV file.
5. Relevant importer settings: 
```
6. Encoding: utf-8
7. Column delimiter: \t
8. Header position: top
9. Quote char: none
10. Escape char: \NULL value mark: none
11. Set empty strings to NULL: true
```

**Comment by LonwoLonwo** [comment]
Hello @Vichman67 

Just to be clear - you are importing in a new table, not in the existing one?

**Comment by Vichman67** [comment]
Hello,

I'm importing onto a new table.

Thanks!

**Comment by ShadelessFox** [comment]
I was able to reproduce your issue. Thank you for the report.

I also want to point out that the "Test2.csv" is, in fact, malformed. Some values are separated using multiple tab symbols, which is something DBeaver doesn't support (it treats every separator symbol separately and treats empty values as nulls). This is an expected behavior, and we don't want to change it. If you know that duplicated tabs are supposed to be there, there are still too few values compared to the header (row values start missing after the column `EXPRESSION_UNO`).

**Comment by Vichman67** [comment]
Sorry for the errors on "Test2.csv", it was due to a faulty copy & paste. Please focus your analysis on "Test1.csv", which serves  for the purpose. Thanks!
