### ISSUE TITLE
Error resolving data type Point in clickhouse

### ISSUE THREAD

**Issue by vsgudko** [dbeaver/dbeaver#22647]
### Description

I get error "Error resolving data type" when I select columns with datatype Point

### DBeaver Version

23.3.0.202312122044

### Operating System

Windows 10

### Database and driver

ClickHouse 23.7.4.5 and ClickHouse JDBC Driver 0.6.0 (revision: cb8e198)

### Steps to reproduce

CREATE TABLE geo_point 
(p Point) 
ENGINE = Memory();
INSERT INTO geo_point VALUES((10, 10));
SELECT p, toTypeName(p) FROM geo_point;
<img width="238" alt="clickhouse jdbc" src="https://github.com/dbeaver/dbeaver/assets/134942092/cabc43c6-fe54-49de-b0d1-0881a35c428d">
<img width="250" alt="dbeaver select" src="https://github.com/dbeaver/dbeaver/assets/134942092/92b44c46-89d9-42d2-ba16-fb19f6f1cce2">

**Comment by LonwoLonwo** [comment]
Hello @vsgudko 

Sorry for the late response.
Thanks for the report.

Log:

```
2024-03-28 17:47:32.190 - Can't read column 'p' value
org.jkiss.dbeaver.model.exec.DBCException: Error resolving data type
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:251)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:880)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:664)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:505)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:524)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:976)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4155)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: Cannot invoke "com.clickhouse.data.ClickHouseColumn.getDataType()" because the return value of "com.clickhouse.jdbc.ClickHouseArray.getBaseColumn()" is null
	at com.clickhouse.jdbc.ClickHouseArray.getBaseTypeName(ClickHouseArray.java:35)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:243)
```

**Comment by Hubbitus** [comment]
Hello.
Am I right, issue is confirmed and will be fixed soon?

**Comment by LonwoLonwo** [comment]
The issue is confirmed.
But there is no guarantee that it will be fixed soon. 
We are always open for contributions: https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code

**Comment by JGKle** [comment]
Also running into this still in 24.1.5. Hoping it gets fixed soon...
