### ISSUE TITLE
SQLServer - Trigger Deletion

### ISSUE THREAD

**Issue by WildLlama** [dbeaver/dbeaver#22650]
### Description

Working on a filtered SQLServer database connection, if you try to delete one or more trigger via UI if results in a object null exception
This doesn't happen if no filter is applied on the "Database" selected connection folder
Also this seems to be an issue for not all database types, I'm working with MySQL and SQLServer and only the SQLServer one faces this bug

![immagine_2024-01-31_143303774](https://github.com/dbeaver/dbeaver/assets/61920578/6a11c355-0b5b-4420-83d2-824dd6b19292)

Log report:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-01-31 14:20:27.806
!MESSAGE Cannot invoke "org.jkiss.dbeaver.model.struct.DBSObject.getDataSource()" because "object" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.struct.DBSObject.getDataSource()" because "object" is null
	at org.jkiss.dbeaver.model.DBUtils.getQuotedIdentifier(DBUtils.java:96)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerTableTriggerManager.addObjectDeleteActions(SQLServerTableTriggerManager.java:94)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectDeleteCommand.getPersistActions(SQLObjectEditor.java:476)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:177)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:122)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectBase$ObjectSaver.run(NavigatorHandlerObjectBase.java:296)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:58)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

Community Edition   23.3.3.202401211839

### Operating System

Windows 10 Pro

### Database and driver

SQL Server 15.0.0 - Driver mssql-jdbc 12.4.1.jre11

### Steps to reproduce

1. Connect to a SQLServer database
2. Ensure that the selected schema has at least one trigger
3. Configure the database filter
![immagine_2024-01-31_144019887](https://github.com/dbeaver/dbeaver/assets/61920578/c75e7a98-dfb3-4fb9-9fc0-47450e445351)
4. Open the trigger folder and delete the trigger using the object deletion window

**Comment by LonwoLonwo** [comment]
Hello @WildLlama 

Thanks for the bug report.

**Comment by yehudacohen** [comment]
@LonwoLonwo wanted to check in. Do you have any update as to the status of this issue?

**Comment by LonwoLonwo** [comment]
Ok, I can do it.
