### ISSUE TITLE
[Postgres] NPE when creating a new table from ui

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#22685]
### Description

STR

1. Connect to postgres or greenplum
2. Right mouse click on Schema name -> create table

https://github.com/dbeaver/dbeaver/assets/84867187/f0aef27c-36e0-4c06-af04-021bb6a89452

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.runtime.DBRProgressMonitor.isCanceled()" because "monitor" is null
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:92)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:74)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:1)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:154)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getRoleById(PostgreDatabase.java:387)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getOwner(PostgreTableBase.java:173)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$1(ObjectPropertyDescriptor.java:431)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:460)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:224)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:173)
	at org.jkiss.dbeaver.ui.controls.CustomFormEditor.createPropertyEditor(CustomFormEditor.java:134)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm.refreshProperties(TabbedFolderPageForm.java:325)
	at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageForm.createControl(TabbedFolderPageForm.java:146)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.createPropertyBrowser(ObjectPropertiesEditor.java:171)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.lambda$1(ObjectPropertiesEditor.java:345)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4367)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3990)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```

### DBeaver Version

23.3.4

### Operating System

mac M1 Sonoma

**Comment by LonwoLonwo** [comment]
We can create a table and the issue is only in the logs, so major changed to normal.
