### ISSUE TITLE
mac Unsupported data type: Bool  and  windows is ok

### ISSUE THREAD

**Issue by dibrother** [dbeaver/dbeaver#22702]
### Description

* mac Intel Sonoma 14.1.1
* DBeaver  23.3.3
<img width="316" alt="image" src="https://github.com/dbeaver/dbeaver/assets/95730552/3c219b33-752d-42d7-a4cf-17b562b76a50">
* data count  229882804

org.jkiss.dbeaver.DBException: Unsupported data type: Bool
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:250)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Unsupported data type: Bool
	at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1055)
	at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:882)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.deserialize(ClickHouseRowBinaryProcessor.java:459)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.readNextRow(ClickHouseRowBinaryProcessor.java:521)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:551)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$Records.next(ClickHouseRowBinaryProcessor.java:496)
	at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:716)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:180)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	... 4 more

### DBeaver Version

23.3.3

### Operating System

Sonoma 14.1.1

### Database and driver

Yandex ClickHouse driver (server version 21.3+)

**Comment by serjiokov** [comment]
Hello @dibrother, 
Could you please provide DDL for particular case?

**Comment by dibrother** [comment]
### The DDL is as follows:
```sql
CREATE TABLE testdb.ts_kv_kafka
(
    `testa_id` UUID,
    `key` String,
    `ts` Int64,
    `something_id` String,
    `bool_v` Nullable(Bool),
    `str_v` Nullable(String),
    `dbl_v` Nullable(Decimal(32,16))
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '192.168.10.10:9092,
192.168.10.11:9092,
192.168.10.12:9092',
 kafka_topic_list = 'test_kv_ck',
 kafka_group_name = 'test_kv_ck_consumer',
 kafka_format = 'JSONEachRow',
 kafka_num_consumers = 1,
 kafka_poll_timeout_ms = 25;


 CREATE TABLE testdb.ts_kv_local
(
    `testa_id` UUID,
    `key` String,
    `ts` Int64,
    `something_id` String,
    `bool_v` Nullable(Bool),
    `str_v` Nullable(String),
    `dbl_v` Nullable(Decimal(32,16))
)
ENGINE = ReplacingMergeTree
PARTITION BY formatDateTime(fromUnixTimestamp64Milli(ts),'%Y_%m')
PRIMARY KEY (testa_id,ts,key)
ORDER BY (testa_id,ts,key)
SETTINGS index_granularity = 8192;

CREATE MATERIALIZED VIEW testdb.ts_kv_mv TO testdb.ts_kv_local
(
    `testa_id` UUID,
    `key` String,
    `ts` Int64,
    `something_id` String,
    `bool_v` Nullable(Bool),
    `str_v` Nullable(String),
    `dbl_v` Nullable(Decimal(32,16))
) AS
SELECT
    testa_id,
    key,
    ts,
    something_id,
    bool_v,
    str_v,
    dbl_v
FROM testdb.ts_kv_kafka;
```

Report error occurred when executing a statement like :
```sql
select * from testdb.ts_kv_local limit 10;
```

**Comment by LonwoLonwo** [comment]
Hello @dibrother 

What connector do you use? Legacy or usual? You can check it in your connection settings:

![2024-02-08 10_39_54-Connection _default_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/f6b2532b-471f-4fcb-8355-786c1de55f34)

Also, what driver version do you use? Connection settings -> Test connection.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
