### ISSUE TITLE
Dbeaver crashes when importing CSV instead of showing error

### ISSUE THREAD

**Issue by eros-ciabattoni-td** [dbeaver/dbeaver#22705]
### Description

If I try to import from a CSV file containing an error (e.g. a value that exceeds the field length), Dbeaver crashes instead of showing the error.

### DBeaver Version

23.3.4

### Operating System

Windows 10

### Database and driver

1. Database name and version: PostgreSQL 13.12

### Steps to reproduce

- Create a table as follows:
`
CREATE TABLE app_tipart (
	flgart numeric(1) NULL,
	keyart varchar(10) NULL,
	tipart varchar(3) NULL
);
`
- Import a CSV file, even with 1 row, where the "tipart" column has more than 3 characters, with the following settings:
![import1](https://github.com/dbeaver/dbeaver/assets/70574028/92007732-cce4-4bf5-9fca-0813230560fe)
![import2](https://github.com/dbeaver/dbeaver/assets/70574028/903d4c1b-c76b-4d43-ace5-b86d74c01831)
![import3](https://github.com/dbeaver/dbeaver/assets/70574028/581f9849-62c1-404f-8249-3b5808bfc55a)

- The import remains stuck and I need to kill the app
![crash](https://github.com/dbeaver/dbeaver/assets/70574028/8440b3d0-bf85-4937-a01c-93fc820d885c)

### Log

!ENTRY org.jkiss.dbeaver.model 4 0 2024-02-05 11:38:18.988
!MESSAGE Error inserting row
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-02-05 11:38:18.988
!MESSAGE Errore SQL [22001]: ERRORE: il valore è troppo lungo per il tipo character varying(3)
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2024-02-05 11:38:18.988
!MESSAGE ERRORE: il valore è troppo lungo per il tipo character varying(3)
!STACK 0
org.postgresql.util.PSQLException: ERRORE: il valore è troppo lungo per il tipo character varying(3)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:310)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:178)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.lambda$0(DatabaseTransferConsumer.java:456)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:454)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:510)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:290)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:161)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:110)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:82)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2024-02-05 11:39:11.791 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -eclipse.keyring C:\Users\e.ciabattoni\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2024-02-05 11:39:13.731
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.jkiss.dbeaver.model 4 0 2024-02-05 11:39:14.099
!MESSAGE Error accessing instance server: java.net.ConnectException

!ENTRY org.eclipse.ui 2 2 2024-02-05 11:39:16.916
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

**Comment by LonwoLonwo** [comment]
Hello @eros-ciabattoni-td 

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by LonwoLonwo** [comment]
Also, please provide more specific steps info. I can't reproduce it for now.

**Comment by eros-ciabattoni-td** [comment]
Hi @LonwoLonwo,

I've added the log and the steps to reproduce.

**Comment by LonwoLonwo** [comment]
Thanks!

**Comment by LonwoLonwo** [comment]
Fixed. The fix will be available in the next release 23.3.5.
Or you can try our Early Access version: https://dbeaver.io/files/ea/
