### ISSUE TITLE
MariaDB SSL connection not working using MariaDB driver

### ISSUE THREAD

**Issue by balajiboopathi1997** [dbeaver/dbeaver#22724]
### Description

We are using separate keystore for making connection to database using SSL. The connection was made properly while using MySQL jar.

But I got an error while making connection to the database through SSL using MariaDB Jar.

"java.sql.SQLNonTransientConnectionException: (conn=61) Failed to read keyStore file. Option keyStore=file:E:\MariaDB\....\Cert\key.keystore
"

### DBeaver Version

Maria DB 11.2

### Operating System

Windows 10

### Database and driver

Maria DB Database
mariadb-java-client-3.3.2.jar

**Comment by LonwoLonwo** [comment]
Hello @balajiboopathi1997 

Could you please provide a screen from your SSL connection page (you can hide/fake all sensitive data)? Or how exactly did you enable SSL?

Additionally, please provide the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

And please specify DBeaver version.

**Comment by balajiboopathi1997** [comment]
Hi,
      Actually I'm using standalone java program to connect the MariaDB
database using SSL. I will attach the java file. While making connection
I'm getting the "Failed to read keyStore file" error message. Please help
me to solve this issue.

Thanks and Regards,
Balaji B

**Comment by LonwoLonwo** [comment]
> Actually I'm using standalone java program to connect the MariaDB

What kind of program?

You can't attach files via e-mail, unfortunately, you need to attach it on this GitHub page

**Comment by balajiboopathi1997** [comment]
It is a standalone Java program. I'm trying to connect the MariaDB database with SSL using MariaDB jar (mariadb-java-client-3.3.2.jar). But I'm unable to connect the database. I'm getting the "java.sql.SQLNonTransientConnectionException: (conn=61) Failed to read keyStore file. Option keyStore=file:E:\MariaDB....\Cert\key.keystore
" error. 

**Error Traces :** 

java.sql.SQLNonTransientConnectionException: (conn=86) Failed to read keyStore file. Option keyStore=file:E:\MariaDB\....\Cert\key.keystore
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:300)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:366)
	at org.mariadb.jdbc.plugin.tls.main.DefaultTlsSocketPlugin.loadClientCerts(DefaultTlsSocketPlugin.java:57)
	at org.mariadb.jdbc.plugin.tls.main.DefaultTlsSocketPlugin.getSocketFactory(DefaultTlsSocketPlugin.java:157)
	at org.mariadb.jdbc.client.impl.ConnectionHelper.sslWrapper(ConnectionHelper.java:351)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:156)
	at org.mariadb.jdbc.Driver.connect(Driver.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:95)
	at org.mariadb.jdbc.Driver.connect(Driver.java:26)
	at ConnectMySQLUsingMariaDBJar.main(ConnectMySQLUsingMariaDBJar.java:34)
Caused by: java.io.FileNotFoundException: file:E:\MariaDB\....\Cert\key.keystore (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
[ConnectMySQLUsingMariaDBJar.txt](https://github.com/dbeaver/dbeaver/files/14189103/ConnectMySQLUsingMariaDBJar.txt)
[ConnectMySQLUsingMariaDBJar.txt](https://github.com/dbeaver/dbeaver/files/14189104/ConnectMySQLUsingMariaDBJar.txt)

	at org.mariadb.jdbc.plugin.tls.main.DefaultTlsSocketPlugin.loadFromUrl(DefaultTlsSocketPlugin.java:66)
	at org.mariadb.jdbc.plugin.tls.main.DefaultTlsSocketPlugin.loadClientCerts(DefaultTlsSocketPlugin.java:42)
	... 7 more


Attaching the standalone java code. Please check and help me to solve this issue.

**Comment by LonwoLonwo** [comment]
I think you need to check the path to your file.

> Caused by: java.io.FileNotFoundException: file:E:\MariaDB....\Cert\key.keystore (The filename, directory name, or volume label syntax is incorrect)

**Comment by LonwoLonwo** [comment]
Maybe you will find here anything helpful

https://github.com/dbeaver/dbeaver/blob/ec9495d8d21ccab277cd15fde70d13ae6b0c29f5/plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLDataSource.java#L179-L225
