### ISSUE TITLE
[SQL Server] Broken highlighting

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#22744]
### Description

Broken highlighting in the SQL Script associated with a non-default database.

### DBeaver Version

DBeaver 23.3.4

### Database and driver

Microsoft SQL Server 15.00.2000

### Steps to reproduce

1. Open script associated with non-default database. With any selection from a non-default database.

My script was:

```sql
SELECT DepartmentID, Name, GroupName, CAST(ModifiedDate AS DATE) ModifiedDate
FROM AdventureWorks2017.HumanResources.Department;

select 1;
select 1 as A into #t
raiserror('Test', 16, 1)
```

```
024-02-07 13:17:20.678 - java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema.getTableType(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, long)" because the return value of "org.jkiss.dbeaver.ext.mssql.model.SQLServerDataType.getSysSchema(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor)" is null
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.ext.mssql.model.SQLServerSchema.getTableType(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, long)" because the return value of "org.jkiss.dbeaver.ext.mssql.model.SQLServerDataType.getSysSchema(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor)" is null
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataType.getAttributes(SQLServerDataType.java:477)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.context.SQLQueryExprType.forTypedObjectImpl(SQLQueryExprType.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.context.SQLQueryExprType.forTypedObjectImpl(SQLQueryExprType.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.context.SQLQueryExprType.forTypedObject(SQLQueryExprType.java:111)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsTableDataModel.obtainColumnType(SQLQueryRowsTableDataModel.java:93)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsTableDataModel.lambda$1(SQLQueryRowsTableDataModel.java:85)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsTableDataModel.prepareResultColumnsList(SQLQueryRowsTableDataModel.java:86)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsTableDataModel.propagateContextImpl(SQLQueryRowsTableDataModel.java:115)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsSourceModel.propagateContext(SQLQueryRowsSourceModel.java:48)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsProjectionModel.propagateContextImpl(SQLQueryRowsProjectionModel.java:97)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQueryRowsSourceModel.propagateContext(SQLQueryRowsSourceModel.java:48)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.model.SQLQuerySelectionModel.propagateContex(SQLQuerySelectionModel.java:58)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLQueryModelRecognizer.recognizeQuery(SQLQueryModelRecognizer.java:616)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob.doWork(SQLBackgroundParsingJob.java:408)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob$1.run(SQLBackgroundParsingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
```

**Comment by hanshulll** [comment]
Hello All,

### Description

Facing error while running the script using below command after cloning the repository i.e facing test failures
```
sh ./build.sh
```
### Error Screenshot

![Screenshot 2024-02-07 at 9 28 03 PM](https://github.com/dbeaver/dbeaver/assets/56799372/bd72e7aa-fdd5-4069-a7f9-40c5d2189abf)

Even when I run the below command I am getting the same error message

```
mvn clean instal
```

But when I only run the following command I got build success
```
mvn package
```
![Screenshot 2024-02-07 at 9 58 03 PM](https://github.com/dbeaver/dbeaver/assets/56799372/06d5829a-6c79-4760-a34b-66ceec55168a)

Am I doing something wrong? Your response will be very helpful for me to set up my local environment and go through the code.

Best Regards,
Hanshul
