### ISSUE TITLE
Can't connect to Informix with CLIENT_LOCALE and NEWCODESET params

### ISSUE THREAD

**Issue by hyperstown** [dbeaver/dbeaver#22760]
### Description

I have an issue when I try to connect to informix database using this connection string:
`jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384`
When I try to connect I get an error: 
`Error getting JDBC meta data`

<details>
<summary>Log </summary>

```
2024-02-08 18:14:42.479 - Connect with 'jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384' (687448E1-6EAB-6CDE-72EC-F03129EE87EB-18d89b6e9ab-4b1d0dabee47882f)
2024-02-08 18:14:42.481 - Execution context opened (jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384; Main; 24)
2024-02-08 18:14:42.667 - java.sql.SQLException: System error java.nio.charset.UnsupportedCharsetException: mazovia
java.sql.SQLException: System error java.nio.charset.UnsupportedCharsetException: mazovia
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:492)
        at com.informix.jdbc.IfxSqli.handleSocketException(IfxSqli.java:8013)
        at com.informix.jdbc.IfxSqli.sendPrepare(IfxSqli.java:1347)
        at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1266)
        at com.informix.jdbc.IfxPreparedStatement.setupExecutePrepare(IfxPreparedStatement.java:315)
        at com.informix.jdbc.IfxPreparedStatement.processSQL(IfxPreparedStatement.java:296)
        at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:185)
        at com.informix.jdbc.IfxSqliConnect.createPreparedStmt(IfxSqliConnect.java:6449)
        at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2608)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:260)
        at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.determineSelectedEntity(GenericExecutionContext.java:102)
        at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.refreshDefaults(GenericExecutionContext.java:356)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:225)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:162)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:124)
        at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
        at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1297)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1145)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:964)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.charset.UnsupportedCharsetException: mazovia
        at java.base/java.nio.charset.Charset.forName(Charset.java:543)
        at com.informix.lang.JavaToIfxType.doConversion(JavaToIfxType.java:800)
        at com.informix.lang.JavaToIfxType.getConvertedBytes(JavaToIfxType.java:146)
        at com.informix.lang.JavaToIfxType.JavaToIfxChar(JavaToIfxType.java:161)
        at com.informix.asf.IfxDataOutputStream.getJavaToIfxChar(IfxDataOutputStream.java:254)
        at com.informix.jdbc.IfxSqli.getJavaToIfxCharBytes(IfxSqli.java:8055)
        at com.informix.jdbc.IfxSqli.sendPrepare(IfxSqli.java:1307)
        ... 24 more
2024-02-08 18:14:42.667 - Error initializing datasource
org.jkiss.dbeaver.DBException: Error getting JDBC meta data
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:496)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:468)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1304)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1145)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:964)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Connection not established
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
        at com.informix.jdbc.IfxSqliConnect.getMetaData(IfxSqliConnect.java:2860)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getMetaData(JDBCConnectionImpl.java:350)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:478)
        ... 8 more
2024-02-08 18:14:42.678 - Execution context closed (jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384, 24)
2024-02-08 18:14:42.691 - Connection not established
java.sql.SQLException: Connection not established
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
        at com.informix.jdbc.IfxSqliConnect.getMetaData(IfxSqliConnect.java:2860)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.getMetaData(JDBCConnectionImpl.java:350)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:478)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:468)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1304)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1145)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:964)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

</details>

I added mazovia in driver settings libraries as a file and as an artifact, neither worked:

![image](https://github.com/dbeaver/dbeaver/assets/64496017/0a30d8f8-5399-435e-8bd3-9145252d5e0d)

I tried newest driver and version 4.10.8.1 which is a version that I can confirm works since I managed to connect to database outside dbeaver. 

### DBeaver Version

Community Edition 23.3.1 (flatpak)

### Operating System

Fedora 39

### Database and driver

Database: informix 11.5
Driver: JDBC informix 4.10.8.1

### Steps to reproduce

1. Try to connect to database selecting informix.
2. Pprovide this config: `jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384`
3. Click test connection.
4. See an error.
![image](https://github.com/dbeaver/dbeaver/assets/64496017/48012035-6ed4-453a-9986-d498615099e0)

**Comment by LonwoLonwo** [comment]
Hello @hyperstown 

Are you sure that you can use these parameters in the JDBC URL string? Do you have any documentation links?
You can try to use your parameters not just in the URL String, but in driver parameters in your connections settings. You need to add it like new custom parameters:

![2024-02-09 11_06_29-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/f62dda3b-444a-470b-b5cd-c4d21220962d)

**Comment by hyperstown** [comment]
Hi @LonwoLonwo, thanks for the reply.

> Are you sure that you can use these parameters in the JDBC URL string?

I managed to connect to database with this URL string in python so I guess it should be valid?
```py
self.connection = jaydebeapi.connect(jclassname, url, driver_args, jars)
```
where prams are:
```py
jclassname='com.informix.jdbc.IfxDriver'
url='jdbc:informix-sqli://localhost:8510/tests:INFORMIXSERVER=test_server;CLIENT_LOCALE=pl_pl.57384;NEWCODESET=mazovia,mazovia,57384'
driver_args=['username', 'password']
jars=['/path/to/drivers/jdbc-4.10.8.1.jar', '/path/to/drivers/mazovia.jar']
```
Also jaydebeapi describes this params as:
```
jclassname: Full qualified Java class name of the JDBC driver.
url: Database url as required by the JDBC driver.
driver_args: Dictionary or sequence of arguments to be passed to
       the Java DriverManager.getConnection method. Usually
       sequence of username and password for the db. Alternatively
       a dictionary of connection arguments (where `user` and
       `password` would probably be included). See
       http://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html
       for more details
jars: Jar filename or sequence of filenames for the JDBC driver
libs: Dll/so filenames or sequence of dlls/sos used as shared
      library by the JDBC driver
```

> Do you have any documentation links?

Yes. Here:
- [NEWCODESET](https://www.ibm.com/docs/en/informix-servers/12.10?topic=SSGU8G_12.1.0/com.ibm.jfoun.doc/ids_jfoun_018.html)
- [CLIENT_LOCALE](https://www.ibm.com/docs/en/informix-servers/14.10?topic=environment-client-locale)

> You can try to use your parameters not just in the URL String, but in driver parameters in your connections settings.

I tried that but it didn't work. The same error:

![image](https://github.com/dbeaver/dbeaver/assets/64496017/448bdb1f-ffda-4e1c-8a38-9c2adc9b9c1c)

![image](https://github.com/dbeaver/dbeaver/assets/64496017/a4fd1175-802a-4422-a32a-1c49eaf0bdcc)

(`java.sql.SQLException: System error java.nio.charset.UnsupportedCharsetException: mazovia`)

I also tried removing for example `NEWCODESET` param but it returns error `Locale not supported.`
And if I remove `CLIENT_LOCALE` or both it returns: `Unable to load locale categories.  IfxASFRemoteException`

**Comment by LonwoLonwo** [comment]
Thanks for the report. We care about each of our users, and the current issue requires a sufficient amount of time to invest and revise.
For this reason, I will add the "wait for votes" label to this ticket. And then we will see how many users struggling with this particular issue.

**Comment by kamilDawidowski** [comment]
Hi, i have the same problem. Do you have solition  @hyperstown ?

**Comment by hyperstown** [comment]
> Hi, i have the same problem. Do you have solition [@hyperstown](https://github.com/hyperstown) ?

Unfortunately the only thing I can recommend is to use something other than dbeaver. I managed to connect with [squirrelsql](http://www.squirrelsql.org/).
