### ISSUE TITLE
SQL parser can't handle some query

### ISSUE THREAD

**Issue by kosiodg** [dbeaver/dbeaver#22773]
### Description

SQL Editor connected to Postgres db while parsing the file in the Outline view doesn't parse or crashes on the following query:

select * from account_invoice i order by i.*;

If order by i.* is changed to: order by i.id, the problem disappears.
If a crash occurs (when the file is big, containing many queries) I have to forcefully shutdown the Eclipse.

### DBeaver Version

Community Edition 23.3.4

### Operating System

Windows 10 Pro

### Database and driver

PostgreSQL 9.5

### Steps to reproduce

1. Open SQL file containing the query:
select * from table_name i order by i.*;
2. Open the Outline view
3. the query doesn't show or Eclipse crashes

**Comment by E1izabeth** [comment]
Thank you for the bug report.
I can reproduce that Outline is not following and the highlighting disappears as our parser doesn't support such construction in `order by` clause. However, I can't reproduce the crash.
Could you reproduce the crash and send log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by kosiodg** [comment]
The only errors I have in the log file are of the type:

!ENTRY org.eclipse.ui.ide 4 4 2024-02-09 15:44:02.990
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:240)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage$OutlineScriptNode.getImage(SQLEditorOutlinePage.java:477)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage$SQLOutlineLabelProvider.getImage(SQLEditorOutlinePage.java:281)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:198)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:171)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:124)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:134)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:146)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:983)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:130)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1058)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2116)
	at org.eclipse.jface.viewers.TreeViewer.replace(TreeViewer.java:459)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage$2.updateChildNode(SQLEditorOutlinePage.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage$2.updateElement(SQLEditorOutlinePage.java:139)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:1014)
	at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:710)
	at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:718)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:685)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1964)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1921)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1907)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$2(StructuredViewer.java:1468)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1397)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1358)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1468)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1422)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorOutlinePage.lambda$2(SQLEditorOutlinePage.java:204)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
Could I ask you to reproduce the case with a big script when DBeaver is freezing so you have to kill it and make a thread dump before killing? It will help a lot.
Here is a guide how to make a thread dump. It will not take a lot of time.
https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump

**Comment by kosiodg** [comment]
Here it is
[dbeaver-thread-dump.txt](https://github.com/dbeaver/dbeaver/files/14223283/dbeaver-thread-dump.txt)

**Comment by E1izabeth** [comment]
Thank you so much

**Comment by kosiodg** [comment]
I have another query at the end of the file which is very big and is not parsed fully.
I don't know which one is the problem, the crash happens when I'm scrolling fast.

**Comment by E1izabeth** [comment]
Hmm.. Is it possible for you to send your huge query to me on email?

**Comment by kosiodg** [comment]
done

**Comment by E1izabeth** [comment]
@kosiodg 
We fixed issues with crash and supported `order by i.*`. It will be available in the next release 23.3.5 on Monday.

I'll keep this issue open as we also need to support the query that was send me to the email.

**Comment by kosiodg** [comment]
I confirm crash is not occurring anymore :)

**Comment by E1izabeth** [comment]
Thank you
