### ISSUE TITLE
Error deleting directory C:\Temp\.dbeaver-temp13605039736636582033

### ISSUE THREAD

**Issue by GeriZ** [dbeaver/dbeaver#22787]
### Description

Hi,

every time I start DBeaver on Windows an additional directory like C:\Temp\.dbeaver-temp13605039736636582033 will be created . As long as DBeaver is running there is another additional directory C:\Temp\.dbeaver-temp13605039736636582033\dnd-files with no files in it. When I close Dbeaver the subdirectory dnd-files will be deleted but the empty directory C:\Temp\.dbeaver-temp13605039736636582033 is still there. In C:\Users\XXXXXXX\AppData\Roaming\DBeaverData\workspace6\.metadata\.log I see these two messages:

!SESSION 2024-02-12 11:17:16.082 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\XXXXXXX\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui 2 2 2024-02-12 11:17:21.049
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.model 2 0 2024-02-12 11:21:50.526
!MESSAGE Error deleting file C:\TEMP\.dbeaver-temp13605039736636582033
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2024-02-12 11:21:50.526
!MESSAGE C:\TEMP\.dbeaver-temp13605039736636582033
!STACK 0
java.nio.file.DirectoryNotEmptyException: C:\TEMP\.dbeaver-temp13605039736636582033
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at org.jkiss.dbeaver.utils.ContentUtils.deleteFileRecursive(ContentUtils.java:350)
	at org.jkiss.dbeaver.core.DesktopPlatform.dispose(DesktopPlatform.java:187)
	at org.jkiss.dbeaver.core.DBeaverActivator.shutdownCore(DBeaverActivator.java:137)
	at org.jkiss.dbeaver.core.DBeaverActivator.stop(DBeaverActivator.java:99)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:875)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:867)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1893)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1768)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Unknown Source)

!ENTRY org.jkiss.dbeaver.model 2 0 2024-02-12 11:21:50.528
!MESSAGE Can not delete temp folder 'C:\TEMP\.dbeaver-temp13605039736636582033'

Because of !MESSAGE Invalid preference category path: I already deleted 
C:\Users\XXXXXXX\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi but I didn't help. 

Anyone knows what the problem is?

Regards
Geri

### DBeaver Version

Community Edition 23.3.4

### Operating System

Windows 10

### Database and driver

DB2

### Steps to reproduce

Start Dbeaver
Do something
Stop it
Check the directory C:\Temp for remaining .dbeaver-tempxxxxxxxxxxxxxxxxxxx directories

### Additional context

The Office extension is installed

**Comment by E1izabeth** [comment]
@GeriZ 
We can't reproduce your issue, but made some fixes that may solve it, Could you try our early access version to check if the issue is not reproducible anymore? You can download it here https://dbeaver.io/files/ea/

**Comment by GeriZ** [comment]
Hi E1izabeth,

thank you! This has fixed the issue. During the start of DBeaver only one directory will be created now but only once and always the same with the same files. These two files are becoming a new timestamp at every start. I think this is normal and would not be a problem. 

 Directory of C:\Temp\jna-1499165686

14.02.2024  12:51    <DIR>          .
14.02.2024  12:51    <DIR>          ..
14.02.2024  12:51           254.464 jna6511064604590822262.dll
14.02.2024  12:51                 0 jna6511064604590822262.dll.x

Regards
Geri
