### ISSUE TITLE
Dropping tables into a script doesn't work on linux

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#22889]
### Description

On linux open script and dnd any table on it 

https://github.com/dbeaver/dbeaver/assets/84867187/32f7a684-cd01-494a-9cc0-254d34ea77e8

```
org.eclipse.swt.SWTException: Data does not have correct format for type
at org.eclipse.swt.dnd.DND.error(DND.java:291)
at org.eclipse.swt.dnd.DND.error(DND.java:241)
at org.eclipse.swt.dnd.FileTransfer.javaToNative(FileTransfer.java:74)
at org.eclipse.swt.dnd.DragSource.dragGetData(DragSource.java:538)
at org.eclipse.swt.dnd.DragSource.DragGetData(DragSource.java:322)
at org.eclipse.swt.internal.gtk3.GTK3.gtk_drag_get_data(Native Method)
at org.eclipse.swt.dnd.DropTarget.drag_drop(DropTarget.java:425)
at org.eclipse.swt.dnd.DropTarget.Drag_Drop(DropTarget.java:264)
at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4513)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:665)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:602)
at org.eclipse.equinox.launcher.Main.run(Main.java:1486)
at org.eclipse.equinox.launcher.Main.main(Main.java:1459)
Suppressed: org.eclipse.swt.SWTException: Data does not have correct format for type
```

### DBeaver Version

23.3.5

### Operating System

Linux ubuntu

**Comment by januszrut** [comment]
Hi,

I have experienced the same problem (Ubuntu 20.04 LTE with standard gnome environment).
Doesn't work under KDE either.
However the feature works perfectly with Wayland.

Brgds
Janusz
