### ISSUE TITLE
Clickhouse sql query (UNION ALL) produces SQL Error [1002] [07000]: Connection reset

### ISSUE THREAD

**Issue by aamsur-933** [dbeaver/dbeaver#22908]
### Description

Helo dbeaver team, i have strange error from dbeaver when querying to Clickhouse using `UNION ALL` syntax.

Example query like
![Screenshot from 2024-02-22 13-44-31](https://github.com/dbeaver/dbeaver/assets/74174455/a51ba359-7a90-47a9-9d2c-138b9e8a82f4)

will produces error
`SQL Error [1002] [07000]: Connection reset, server ClickHouseNode [uri=http:/...`

i have tested that the query should not produce any error

Also, a query like
![Screenshot from 2024-02-22 13-58-38](https://github.com/dbeaver/dbeaver/assets/74174455/e23aa1fa-c176-429d-b7bd-65d4b0590d19)

will produces a same error. could anyone help me?

### DBeaver Version

Version 23.3.5.202402181738

### Operating System

Ubuntu 20.04

### Database and driver

Driver version: ClickHouse JDBC Driver 0.5.0 (revision: d384444)
Server : ClickHouse 23.3.13.6

### Additional context

1. The query will works if you changes the syntax to

![Screenshot from 2024-02-22 13-51-06](https://github.com/dbeaver/dbeaver/assets/74174455/b73d72a9-97c6-4f35-9d20-95c5f88bb820)

2. if you **Use SSH Tunnel**, you will get a little bit different errors

3. the query will work properly if i run **Format SQL** (ctrl + shfit + F) first before executing the query.

**Comment by LonwoLonwo** [comment]
Hello @aamsur-933 

Unfortunately, I can't reproduce it.

![2024-02-22 12_56_04-DBeaver Ultimate 23 3 5 - _default 1_ Script-126](https://github.com/dbeaver/dbeaver/assets/45152336/64d25969-41fc-4d68-b571-f75acf368788)

Could you please provide the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. 

And your driver version. You can find this info in your connections settings -> test connection button

Thank you.

**Comment by aamsur-933** [comment]
Hai @LonwoLonwo thanks for reply.

Driver version: ClickHouse JDBC Driver 0.5.0 (revision: d384444)
Server : ClickHouse 23.3.13.6

log files:
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/14381265/dbeaver-debug.log)

**Comment by LonwoLonwo** [comment]
```
2024-02-23 10:00:10.415 - SQL Error [1002] [07000]: Connection reset, server ClickHouseNode [uri=http://**,default, options={socket_timeout=300000,use_server_time_zone=false,use_time_zone=false}]@-1901958450
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1002] [07000]: Connection reset, server ClickHouseNode [uri=http://***/default, options={socket_timeout=300000,use_server_time_zone=false,use_time_zone=false}]@-1901958450
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:601)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:504)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:511)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:963)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Connection reset, server ClickHouseNode [uri=http://***/default, options={socket_timeout=300000,use_server_time_zone=false,use_time_zone=false}]@-1901958450
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:122)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

I do not see anything special in the logs.

So. You can try to increase timeout properties in your driver properties:

![2024-02-23 10_34_18-Connection _default 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/6a314580-32fd-407b-8f93-d19d64975982)

And also you can upgrade your driver version (till 0.6 as an example):

![2024-02-23 10_35_40-Connection _default 1_ configuration](https://github.com/dbeaver/dbeaver/assets/45152336/ed92458b-ee2e-4099-ab4f-104593d7f068)

**Comment by aamsur-933** [comment]
I just upgrade the driver to 0.6.0 and still no luck

![Screenshot from 2024-02-23 15-59-27](https://github.com/dbeaver/dbeaver/assets/74174455/32550362-302e-41aa-a57b-922592bf377d)


```
java.sql.SQLException: The target server failed to respond, server ClickHouseNode [uri=http://127.0.0.1:52215/default, options={socket_timeout=600000,use_server_time_zone=false,use_time_zone=false}]@-1282798443
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:122)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:601)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:504)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:511)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:963)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.clickhouse.client.internal.apache.hc.core5.http.NoHttpResponseException: The target server failed to respond
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:301)
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:712)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123)
	at com.clickhouse.client.http.ApacheHttpConnectionImpl.post(ApacheHttpConnectionImpl.java:241)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:118)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:878)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:120)
	... 16 more
```

**Comment by LonwoLonwo** [comment]
And now I'm out of ideas.
You can also ask here https://github.com/ClickHouse/ClickHouse or here https://github.com/ClickHouse/clickhouse-java/issues

**Comment by aamsur-933** [comment]
hai @LonwoLonwo 

are you using the latest dbeaver version to reproduce it?

**Comment by LonwoLonwo** [comment]
> are you using the latest dbeaver version to reproduce it?

Yes. And I'm still thinking that this issue depends on server configurations.

**Comment by aamsur-933** [comment]
![Screenshot from 2024-02-23 16-50-13](https://github.com/dbeaver/dbeaver/assets/74174455/eaa8cb08-9cef-45ed-9200-ff4cb4ff4a96)

the query will works properly if i run **Format SQL** (ctrl + shfit + F) first before executing the query.


> And now I'm out of ideas. You can also ask here https://github.com/ClickHouse/ClickHouse or here https://github.com/ClickHouse/clickhouse-java/issues

I cannot reproduce it in clickhouse-client (clickhouse cli on the server), because the clickhouse-client will reformat the query automatically like we use **Format SQL** in the dbeaver editor.

**Comment by LonwoLonwo** [comment]
Ok, thanks for the report.

**Comment by E1izabeth** [comment]
Is the issue still relevant for the latest DBeaver version?

**Comment by E1izabeth** [comment]
We haven't received a response. So, I suppose the issue is not actual anymore. So, I'm closing it.
