### ISSUE TITLE
[Eclipse] Event loops when open sqript

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#23004]
### Description

STR:

1. Install Eclipse 2023-12
2. Install DBeaver extension from EA https://dbeaver.io/files/ea/update/ce/
3. Create connection to any db (Tested on MYSQl / Postgres)
4. Open SQL script for connecrtion
5. Open error log
Actual result - see multiple errors
```
java.lang.ClassCastException: class org.jkiss.dbeaver.ui.app.DBeaverPluginApplication cannot be cast to class org.jkiss.dbeaver.model.app.DBPApplicationDesktop (org.jkiss.dbeaver.ui.app.DBeaverPluginApplication is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4f5ebce; org.jkiss.dbeaver.model.app.DBPApplicationDesktop is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @39089dbf)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.getTransactionStatusText(SQLEditor.java:5496)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.updateStatusField(SQLEditor.java:1169)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$TransactionStatusUpdateJob.lambda$0(SQLEditor.java:5482)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

https://github.com/dbeaver/dbeaver/assets/84867187/14bbe085-e78b-4084-a755-b354a2324887

### DBeaver Version

DBeaver 24.0.0

### Operating System

windows 10

**Comment by MashaKorax** [comment]
verified
