### ISSUE TITLE
[RisingWave] Disable backup/restore

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#23013]
### Description

throws 
```
C:\Users\Даша\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\15\pg_dump.exe --verbose --host=db9.dev.dbeaver.com --port=4566 --username=root --format=c --file C:\Users\Даша/dump-dev-202402291955.sql -n "public" dev
Task 'PostgreSQL dump' started at Thu Feb 29 19:55:03 AMT 2024
pg_dump: error: query failed: ERROR:  Failed to run the query
Caused by these errors (recent errors listed first):
  1: Failed to get/set session config
  2: Invalid value `off` for `synchronize_seqscans`
  3: provided string was not `true` or `false`
pg_dump: detail: Query was: SET synchronize_seqscans TO off
Task 'PostgreSQL dump' finished at Thu Feb 29 19:55:04 AMT 2024
2024-02-29 19:55:04.743 - IO error: Process failed (exit code = 1). See error log.
2024-02-29 19:55:04.744 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

### DBeaver Version

24.0.0

### Operating System

win10

**Comment by LonwoLonwo** [comment]
https://github.com/risingwavelabs/risingwave/issues/11470#issuecomment-1980131291
Answer from RisingWave about the pg_dump support
