### ISSUE TITLE
Discrepancy with Driver file names after update

### ISSUE THREAD

**Issue by ramon-san** [dbeaver/dbeaver#23034]
### Description

I'm reposting this conversation from issue #18677 based on a request from @ShadelessFox.

It looks like I'm having the same problem as shown in issue #18677 with the following driver: `com.mysql.cj.jdbc.Driver`

The DBeaver error log is the following:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-03-01 17:14:40.636
!MESSAGE Error creating driver 'MySQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.mysql.cj.jdbc.Driver'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-03-01 17:14:40.636
!MESSAGE com.mysql.cj.jdbc.Driver
!STACK 0
java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1272)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1205)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:745)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:717)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createDriverInstance(JDBCDataSource.java:282)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:198)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:464)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:104)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:99)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1385)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1229)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1015)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
        at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2488)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

## Other Information
I originally installed DBeaver through `brew`, but I updated DBeaver through the GUI yesterday. Also did an OS update earlier today so not exactly sure which of the two things triggered this problem (I think it was the DBeaver update). Also checked Maven access through my network and it seems to be working just fine.

<img width="1123" alt="image" src="https://github.com/dbeaver/dbeaver/assets/65260209/5132777b-8d6f-4a77-8094-552f19fccd7a">

Here is an image of my _DBeaver > Driver Manger > MySQL_.

# SOLVED

To solve this I simply went to `~/Library/DBeaverData/drivers/maven/maven-central/com.mysql` and changed the `.pom` file name to what DBeaver was expecting. For some reason, there was a discrepancy here.

File name in the directory was `mysql-connector-j-8.2.0.pom` and DBeaver was expecting `mysql-connector-cj-8.2.0.pom`. Also before doing this change I removed all other drivers, not sure if this made any difference (don't think so).

### DBeaver Version

23.3.5.202402181738

### Operating System

macOS 14.3.1

### Database and driver

Database name: MySQL 8
Driver: MySQL

**Comment by ShadelessFox** [comment]
As the issue is solved, I will close the ticket.
