### ISSUE TITLE
Fetch Limit not added to any query for DB2 Database

### ISSUE THREAD

**Issue by ldsalomone** [dbeaver/dbeaver#23123]
### Description

I recently have been experiencing an issue the seems related to #22345 #21936 and #21940 but those mention some strange functions and a possible issue with the parser. 

I think this issue is unrelated as my queries originate from 'main' in "View Table" or "View View"

I'm expecting to see LIMIT 200 added to all my queries, but that doesn't seem to be happening for any of them.

One of our Views is particularly large and without the LIMIT being added to the SQL, the query times out and is unable to return any results (self-canceled in the examples below but would be timed out if I let them run).

Settings:
![image](https://github.com/dbeaver/dbeaver/assets/7832023/e86e9aea-b9b8-4c23-ad9d-3936061afbb8)

![image](https://github.com/dbeaver/dbeaver/assets/7832023/27f77ccd-a7c6-4d34-b22c-0ddddbcad9ef)

### DBeaver Version

Community Edition 23.3.0.202312031432

### Operating System

Microsoft Windows 10 Enterprise

### Database and driver

1. IBM DB2 v11.5.8.0
2. Driver Name: DB2 for Linux/Unix/Windows driver
3. IBM Data Server Driver for JDBC and SQLJ V4.19 

### Steps to reproduce

1. Select "Read data in SQL console" or "View Table"/"View View"
2. Expect to see "LIMIT 200" added to the SQL Query in Query Manager"

### Additional context

sql.log: 
```
!ENTRY org.jkiss.dbeaver.model 1 22 2024-03-13 12:09:44.651
!MESSAGE SELECT x.* FROM ECW_V.CLAIM_HEADER x
!SUBENTRY 1 org.jkiss.dbeaver.model 4 -952 2024-03-13 12:11:15.324
!MESSAGE Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29

!ENTRY org.jkiss.dbeaver.model 1 24 2024-03-13 12:26:30.502
!MESSAGE SELECT x.* FROM ECW_V.CLAIM_HEADER x
!SUBENTRY 1 org.jkiss.dbeaver.model 4 -952 2024-03-13 12:28:36.453
!MESSAGE Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
```
.log:
```
!ENTRY org.jkiss.dbeaver.model 2 0 2024-03-13 12:11:15.454
!MESSAGE SQL Warning (DataSource: ECWPROD; Code: 0; State: 00000): Statement processing was successful.. SQLCODE=0, SQLSTATE=00000, DRIVER=4.21.29

!ENTRY org.jkiss.dbeaver.model 4 0 2024-03-13 12:11:15.938
!MESSAGE SQL Error [57014]: Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-03-13 12:11:15.938
!MESSAGE Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
!STACK 0
com.ibm.db2.jcc.am.SqlTimeoutException: Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
	at com.ibm.db2.jcc.am.kd.a(kd.java:812)
	at com.ibm.db2.jcc.am.kd.a(kd.java:66)
	at com.ibm.db2.jcc.am.kd.a(kd.java:140)
	at com.ibm.db2.jcc.am.ResultSet.completeSqlca(ResultSet.java:4194)
	at com.ibm.db2.jcc.am.ResultSet.earlyCloseComplete(ResultSet.java:4176)
	at com.ibm.db2.jcc.t4.bb.a(bb.java:929)
	at com.ibm.db2.jcc.t4.bb.p(bb.java:894)
	at com.ibm.db2.jcc.t4.bb.k(bb.java:261)
	at com.ibm.db2.jcc.t4.bb.d(bb.java:55)
	at com.ibm.db2.jcc.t4.p.c(p.java:44)
	at com.ibm.db2.jcc.t4.vb.j(vb.java:157)
	at com.ibm.db2.jcc.am.sp.mb(sp.java:2234)
	at com.ibm.db2.jcc.am.sp.a(sp.java:3303)
	at com.ibm.db2.jcc.am.sp.e(sp.java:1111)
	at com.ibm.db2.jcc.am.sp.execute(sp.java:1090)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2024-03-13 12:28:36.537
!MESSAGE SQL Error [57014]: Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-03-13 12:28:36.537
!MESSAGE Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
!STACK 0
com.ibm.db2.jcc.am.SqlTimeoutException: Processing was cancelled due to an interrupt.. SQLCODE=-952, SQLSTATE=57014, DRIVER=4.21.29
	at com.ibm.db2.jcc.am.kd.a(kd.java:812)
	at com.ibm.db2.jcc.am.kd.a(kd.java:66)
	at com.ibm.db2.jcc.am.kd.a(kd.java:140)
	at com.ibm.db2.jcc.am.ResultSet.completeSqlca(ResultSet.java:4194)
	at com.ibm.db2.jcc.am.ResultSet.earlyCloseComplete(ResultSet.java:4176)
	at com.ibm.db2.jcc.t4.bb.a(bb.java:929)
	at com.ibm.db2.jcc.t4.bb.p(bb.java:894)
	at com.ibm.db2.jcc.t4.bb.k(bb.java:261)
	at com.ibm.db2.jcc.t4.bb.d(bb.java:55)
	at com.ibm.db2.jcc.t4.p.c(p.java:44)
	at com.ibm.db2.jcc.t4.vb.j(vb.java:157)
	at com.ibm.db2.jcc.am.sp.mb(sp.java:2234)
	at com.ibm.db2.jcc.am.sp.a(sp.java:3303)
	at com.ibm.db2.jcc.am.sp.e(sp.java:1111)
	at com.ibm.db2.jcc.am.sp.execute(sp.java:1090)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5151)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Matvey16** [comment]
@ldsalomone Hello. I can't reproduce it. Can you show me driver properties for this connection?
![image](https://github.com/dbeaver/dbeaver/assets/82543000/5975b0e2-4e89-488a-a72e-d340a3e50356)

Also would the result be the same if you disable these two options

![image](https://github.com/dbeaver/dbeaver/assets/82543000/d800f836-fba1-4fbb-8157-99bbcad5aa5b)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
