### ISSUE TITLE
Azure SQL: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by Aileron79** [dbeaver/dbeaver#23199]
### Description

I have been using dbeaver with Azure SQL quite a while, the day before yesterday it stopped working with this error message when trying to connect with my Active Directory user:

![image](https://github.com/dbeaver/dbeaver/assets/16278437/8c969afa-0896-4dcf-b573-54c96d02b27e)

In the browser window which usually says "Authentication complete, you can now close this window" I just get this:

![image](https://github.com/dbeaver/dbeaver/assets/16278437/033422e7-1a8e-4cb6-8fe9-594d249af239)

Edit:
The issue appeared simultaneously on multiple machines. Note that I also tried older versions, back to 23.3.0, the issue persists. Also, these versions used to work. My assumption is that maybe MS changed something in their authentication flow. which is not captured by the driver. 

My default browser is Chrome which usually is opened by dbeaver. I also tried to use the internal browser for authentication, but with that one I always ended up in an authorization loop, this has not changed. 

Edit 2:
Seems to be Chrome-related since it works flawlessly when setting my default browser to Edge. Still, dbeaver will open the default browser even though I selected Microsoft Edge in the preferences.

### DBeaver Version

24.0.0

### Operating System

Windows 10 and 11

### Database and driver

Azure SQL, Microsoft JDBC Driver for SQL Server

### Steps to reproduce

Try to connect to an Azure SQL database not using database credentials but Azure identities as recommended by MS.

### Additional context

I am tunnelling the connection through Azure VPN but that should not have any impact whatsoever.

**Comment by Destrolaric** [comment]
Hi,
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Viittis** [comment]
FYI, I can confirm the same issue. Similar issue is also repeated with SQL Server Management Studio 19 (I'm not using the latest version), so it suggests that perhaps a Chrome updated causes this issue.

Using dbeaver I can't connect at all, it just opens multiple new tabs on Chrome. Using SSMS19 I get access but the page is left open with an error message.

Hope info this helps with the issue

**Comment by Destrolaric** [comment]
@Viittis Hi, JDBC driver has buggy behavior when it creates multiple pages of OAuth during retry attempts. So something else is probably leading to being unable to connect. https://github.com/microsoft/mssql-jdbc/issues/2237
Logs, might help.
Could you please send me the log files? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by Viittis** [comment]
This works for me now, with both Dbeaver and SSMS19. I guess it was MS after all as I didnt update chrome in the last few hours.

**Comment by E1izabeth** [comment]
@Aileron79 is this issue still actual for you?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by msandovalsto** [comment]
![image](https://github.com/user-attachments/assets/0e538794-5f22-44e7-b228-30f309280a05)

I have the same problem 


Log error: 

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es
Framework arguments:  -eclipse.keyring C:\Users\STOCK-LAP310\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Nov 22 14:17:19 CST 2024
No Authorization code was returned from the server

java.lang.RuntimeException: No Authorization code was returned from the server
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenInteractive(SQLServerMSAL4JUtils.java:183)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4632)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4497)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4460)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5332)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4006)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:214)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:84)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:137)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1395)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1266)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by msandovalsto** [comment]
I have a possible solution 

The problem seems to be jdbc driver version 

1. Go to **database** > **driver manager**
2. found **azure** > **azure sql server** and click on edit 
3. click on **libreries** > **download/update** 

Once finished you can reconfigure the connection
