### ISSUE TITLE
Cannot connect multiple DB configured with SSH tunnel

### ISSUE THREAD

**Issue by frederic-pierre** [dbeaver/dbeaver#23238]
### Description

Since version 24.0.1, I can't connect at the same time to multiple DB configured with an SSH tunnel.

I have this error message, after one DB is connected and I try to connect another one : 

```
FATAL: password authentication failed for user "XXX"
```

### DBeaver Version

Community Edition 24.0.1

### Operating System

Debian GNU/Linux 11 (bullseye)

### Database and driver

1. PostgreSQL 14.10
2. PostgreSQL JDBC Driver 42.2.5

### Steps to reproduce

1. I connect a database A configured with an SSH tunnel configured
2. Connection is established correctly
3. I try to connect another database B configured with an SSH tunnel configured (same host/same key)
4. Connection is not established : eeror message :point_right: `FATAL: password authentication failed for user "XXX"`
5. If I disconnect database A and I retry to connect database B, no errror, and connection is established correctly

### Additional context

It was working smoothly with previous DBeaver versions. A collegue, tried with version Community Edition 24.0.0 and the same configurations. There is no problem.

**Comment by ShadelessFox** [comment]
Hello @frederic-pierre,

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files

**Comment by frederic-pierre** [comment]
Here is an extract of the debug log file, when I reproduce the error. Is it enough ? I cannot share with you the entire log file without removing all sensitive information. 
```log
2024-03-26 14:54:47.414 - Connect with 'foobar' (postgres-jdbc-XXXX-XXXX)
2024-03-26 14:54:47.417 - SSHSessionController: Set up port forwarding :52988 <- data-base-host.com:37666
2024-03-26 14:54:47.418 - Listening on localhost/127.0.0.1:52988
2024-03-26 14:54:47.419 - Execution context opened (foobar; Main <foobar>; 24)
2024-03-26 14:54:47.420 - Initiate connection to PostgreSQL database [foobar@127.0.0.1] for Main <foobar>
2024-03-26 14:54:47.592 - SSHSessionController: Remove port forwarding :52988 <- data-base-host.com:37666
2024-03-26 14:54:47.592 - Closing listener on localhost/127.0.0.1:52988
2024-03-26 14:54:47.592 - SSHSessionController: Releasing session for foobar [PostgreSQL]
2024-03-26 14:54:47.592 - FATAL: password authentication failed for user "foobar"
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "foobar"
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:565)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:278)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:108)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1402)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1239)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1025)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2488)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2024-03-26 14:54:47.596 - <<copyDone>> woke to: java.net.SocketException: Socket closed
```

**Comment by ShadelessFox** [comment]
I need the complete logs that include information about the first initiated connection to understand why the second one fails.

You can delete existing log files and reproduce the issue from the beginning. Logs should contain a minimum amount of sensitive information, so removing it all should be fairly easy.

Speaking of privacy, we have a ticket regarding hiding sensitive information in log files: #17088

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by frederic-pierre** [comment]
Hello, sorry for the delay, here is the log file for this issue that is still actual : 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15081199/dbeaver-debug.log)

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce the issue.

**Comment by ShadelessFox** [comment]
Please try upgrading to the latest version and let me know if your issue still reproduces there: https://dbeaver.io/download/

**Comment by frederic-pierre** [comment]
I am already using _DBeaver Community 24.0.3_. The last logfile correspond to that version.

**Comment by ShadelessFox** [comment]
I didn't notice that from the logs; my bad. I don't see anything suspicious in the logs.

I'm connecting to two PostgreSQL databases on the same host through the same SSH tunnel but bound to different ports and using different credentials. Both connections were established fine without any issues.

Can you please try turning off this option on both connections (or in the profile) to see if it has any effect?

![image](https://github.com/dbeaver/dbeaver/assets/35821147/6800abd5-5c69-4c11-8fdd-970b8448df0e)

**Comment by frederic-pierre** [comment]
It's working now that I disabled tunnel sharing ! Thanks a lot @ShadelessFox

**Comment by ShadelessFox** [comment]
It's not a solution, unfortunately. It's supposed to work with that option enabled. I'm not sure what else can be provided to help us understand what causes this behavior.

**Comment by frederic-pierre** [comment]
In our case, we try to connect to two DB configured with the same tunnel SSH (same host / same port) but the DB host are different.

**Comment by ShadelessFox** [comment]
So the hostnames are not `localhost`, and both point to different IP addresses even though you have an SSH tunnel configured?

**Comment by frederic-pierre** [comment]
Exactly :
- for DB `A` : host is `app-A.foobar.com` and port `XXXX` 
- for DB `B` : host is `app-B.foobar.com` and port `YYYY`

**Comment by ShadelessFox** [comment]
Thanks for the info.

**Comment by borkor** [comment]
> It's working now that I disabled tunnel sharing ! Thanks a lot @ShadelessFox

Definitely works after disabling tunnel sharing. Thanks.

**Comment by ShadelessFox** [comment]
Can you please confirm that you have the exact case as described here https://github.com/dbeaver/dbeaver/issues/23238#issuecomment-2079019450? @borkor

**Comment by borkor** [comment]
> Can you please confirm that you have the exact case as described here [#23238 (comment)](https://github.com/dbeaver/dbeaver/issues/23238#issuecomment-2079019450)? @borkor

Exactly the same issue. Multiple hosts, which are not `localhost` and the same connection data for tunne.

**Comment by ShadelessFox** [comment]
Thank you! This info will help us reproduce the issue.

**Comment by ShadelessFox** [comment]
Unfortunately, we were unable to reproduce the issue.

I have two databases accessible via different IPs, ports, and credentials over the same SSH tunnel. Connections are established without any issues in any order; revalidation also works.

Can you please confirm that you don't have explicit port forwarding configured in the advanced settings? https://github.com/dbeaver/dbeaver/issues/23238#issuecomment-2077596466 Maybe there are some other deviations from the default configuration?

Are you using an SSH tunnel via profiles or configure SSH tunnels separately for each connection?

@frederic-pierre @borkor

**Comment by frederic-pierre** [comment]
I have the issue with the SSH tunnel configured via a profile as well as separately, and I do not have port forwarding configured in the advanced settings.

**Comment by ShadelessFox** [comment]
Thanks for the information.

**Comment by borkor** [comment]
> Unfortunately, we were unable to reproduce the issue.
> 
> I have two databases accessible via different IPs, ports, and credentials over the same SSH tunnel. Connections are established without any issues in any order; revalidation also works.
> 
> Can you please confirm that you don't have explicit port forwarding configured in the advanced settings? [#23238 (comment)](https://github.com/dbeaver/dbeaver/issues/23238#issuecomment-2077596466) Maybe there are some other deviations from the default configuration?
> 
> Are you using an SSH tunnel via profiles or configure SSH tunnels separately for each connection?
> 
> @frederic-pierre @borkor

I am configuring ssh tunnel for each connection. I do not use profiles (did not know something like this existed)

**Comment by E1izabeth** [comment]
Unfortunately, I can't reproduce this issue too

**Comment by uslss** [comment]
Also, I cannot reproduce the issue

**Comment by dario-nuro** [comment]
I don't mean to hijack the issue, but it sounds very similar to my own.
I have quite a few remote DBs (all MariaDB) that I connect to via ssh tunnel.
At the same time I am running my local development environment as docker containers with a couple of databases that are exposed to the host on port 3306 and 3307. I don't have a MariaDB server running in `localhost`.
Before DBeaver version 24.3.2, I was able to connect to the containers (using the 2 ports above on localhost) and open several tunnels at the same time.
Using more recent versions this is not possible anymore.
If the containers are running (and the ports in use), all the tunnels (that worked as they are defined now) are stuck in "Loading..." and force me to quit DBeaver.

I can reproduce by using `nc -l 3306 &` before running DBeaver.

I attach the debug.log that shows a first attempt (with port 3306 in use) and a second attempt after stopping the `nc` above, both using the same tunnel definition.

... after further investigation, it seems the problem seems limited to connections using an SSH Profile.

I hope this helps

[dbeaver-debug.log](https://github.com/user-attachments/files/19169047/dbeaver-debug.log)
