### ISSUE TITLE
Looks like a database disconnected after some manipulations with metadata, but it's not

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#23251]
### Description
This state of sqlite editor occurs in many cases, but no messages like 'Disconnected from _database_' in the Query manager
![Untitled](https://github.com/dbeaver/dbeaver/assets/43252954/3d43d229-d14c-41ed-8dfe-5636e4acb938)
1. For example after importing into table from a table 
- Create a copy of some table in sqlite
- Import data from tablename to tablename_copy table

logs from data transfer:
```
2024-03-27 10:57:27.163 - Task 'd6b4de6' (622f80d5-1162-484f-b4c4-bf939a32cef8) started
2024-03-27 10:57:27.173 - Perform data transfer
2024-03-27 10:57:27.173 - Transfer data from "Genre" into "import_task_source [Existing]"
2024-03-27 10:57:27.174 - Transfer table data
2024-03-27 10:57:27.174 -       Read data
2024-03-27 10:57:27.174 -       Fetch table data
2024-03-27 10:57:27.175 -       Set JDBC connection auto-commit false
2024-03-27 10:57:27.196 -       Commit changes
2024-03-27 10:57:27.209 -       Set JDBC connection auto-commit true
2024-03-27 10:57:27.212 -       Refresh database mappings
2024-03-27 10:57:27.386 - Remove unregistered meta node object Tables
2024-03-27 10:57:27.387 - Remove unregistered meta node object Views
2024-03-27 10:57:27.390 - Remove unregistered meta node object Indexes
2024-03-27 10:57:27.390 - Task 'd6b4de6' (622f80d5-1162-484f-b4c4-bf939a32cef8) finished in 222 ms
2024-03-27 10:57:27.392 - Remove unregistered meta node object Sequences
2024-03-27 10:57:27.394 - Remove unregistered meta node object Table Triggers
2024-03-27 10:57:27.395 - Remove unregistered meta node object Data Types
2024-03-27 10:57:27.543 - Error evaluating expression 'object.externalTable' on node '[NULL]': 1:1 undefined variable object.externalTable
2024-03-27 10:57:27.544 - Error evaluating expression 'object.abstractTable' on node '[NULL]': 1:1 undefined variable object.abstractTable
2024-03-27 10:57:27.544 - Error evaluating expression 'object.sharedTable' on node '[NULL]': 1:1 undefined variable object.sharedTable
2024-03-27 10:57:27.546 - Error evaluating expression 'object.externalTable' on node '[NULL]': 1:1 undefined variable object.externalTable
2024-03-27 10:57:27.546 - Error evaluating expression 'object.abstractTable' on node '[NULL]': 1:1 undefined variable object.abstractTable
2024-03-27 10:57:27.546 - Error evaluating expression 'object.sharedTable' on node '[NULL]': 1:1 undefined variable object.sharedTable
2024-03-27 10:57:27.546 - Error evaluating expression 'object.externalTable' on node '[NULL]': 1:1 undefined variable object.externalTable
2024-03-27 10:57:27.546 - Error evaluating expression 'object.abstractTable' on node '[NULL]': 1:1 undefined variable object.abstractTable
2024-03-27 10:57:27.547 - Error evaluating expression 'object.sharedTable' on node '[NULL]': 1:1 undefined variable object.sharedTable
> Start DBeaver Tasks - Native Tools [org.jkiss.dbeaver.tasks.native 1.0.105.202403262209]
2024-03-27 10:57:27.750 - Event loop exception
org.eclipse.swt.SWTException: Widget is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
        at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3662)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateToolbar(ResultSetViewer.java:1619)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.lambda$2(ResultSetViewer.java:5288)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:295)
        at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:34)
        at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:129)
        at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:44)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

2. When changing table name from the metadata editor.

Open table's metadata editor. Start typing new symbols in the 'Table Name' text box
https://github.com/dbeaver/dbeaver/assets/43252954/d26c1b95-8b6e-40dc-92a5-b37c1f5eb644
nothing in log

3. Adding a new column to an existing table leads to another error

https://github.com/dbeaver/dbeaver/assets/43252954/73593aa1-5b57-4d2e-9599-de7c0361c262
log:
```
org.jkiss.dbeaver.DBException: Can't find node corresponding to new object
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob.openNewObject(NavigatorHandlerObjectCreateBase.java:306)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob$1.lambda$0(NavigatorHandlerObjectCreateBase.java:265)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:295)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:646)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:606)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1463)

```
- 
### DBeaver Version

24.0.1 CE/UE/...

### Operating System

win10

### Database and driver
Not dependent

**Comment by DariaMarkaryan** [comment]
also this behaviour reproduced while trying to change table's name (nothing special into log and query manager)

https://github.com/dbeaver/dbeaver/assets/43252954/a1795fdb-45da-41a9-860a-f491d36303a8
