### ISSUE TITLE
DBeaver Enterprise 24.0 stuck on startup

### ISSUE THREAD

**Issue by SAPJens** [dbeaver/dbeaver#23254]
### Description

I have upgraded DBeaver Enterprise to 24.0
It failed to start and I uninstalled it and installed again.
Still it is stuck on starting in step "Total database drivers (141)" in the Splash Screen.
The last entry in the debug log file is:
2024-03-27 09:12:16.409 - QMDB connected
2024-03-27 09:12:16.461 - --> Call: https://dbeaver.com:443/lmp/checkLicense
2024-03-27 09:12:16.665 - 	Check QMDB deployment
2024-03-27 09:12:16.686 - 	QMDB server started (H2 2.1.214 (2022-06-13))

Debug log is attached.
[dbeaver-debug - Copy.log](https://github.com/dbeaver/dbeaver/files/14770224/dbeaver-debug.-.Copy.log)

### DBeaver Version

Enterprise 24.0

### Operating System

Windows 11

### Database and driver

SAP HANA

**Comment by LonwoLonwo** [comment]
Hello @SAPJens 

Could you please generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/
Thank you.

**Comment by SAPJens** [comment]
@LonwoLonwo Here is the thread dump.
Thanks,
Jens
[dbeaver_thread_dump.txt](https://github.com/dbeaver/dbeaver/files/14770871/dbeaver_thread_dump.txt)

**Comment by LonwoLonwo** [comment]
Do you have a project or master password?
Did you see the dialog for it?

```
DBeaver: Load registry" #38 prio=5 os_prio=0 cpu=0.00ms elapsed=3612.12s tid=0x000001c4d7f84f30 nid=0xadc waiting on condition  [0x000000ae61dfe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x0000000083392610> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.Semaphore.tryAcquire(java.base@17.0.6/Unknown Source)
	at org.eclipse.ui.internal.PendingSyncExec.acquire(PendingSyncExec.java:39)
	at org.eclipse.ui.internal.PendingSyncExec.waitUntilExecuted(PendingSyncExec.java:88)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:142)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4802)
	at org.jkiss.dbeaver.ui.UIUtils.syncExec(UIUtils.java:1983)
	at com.dbeaver.ee.runtime.ui.security.UIServiceSecurityImpl.askForPassword(UIServiceSecurityImpl.java:57)
	at com.dbeaver.ee.runtime.LocalProjectAdvanced.acquireSecretKey(LocalProjectAdvanced.java:93)
	at com.dbeaver.ee.runtime.LocalProjectAdvanced.getLocalSecretKey(LocalProjectAdvanced.java:70)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.loadConfigFile(DataSourceSerializerModern.java:332)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.readSecureCredentials(DataSourceSerializerModern.java:851)
	at org.jkiss.dbeaver.registry.DataSourceSerializerModern.parseDataSources(DataSourceSerializerModern.java:424)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:841)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:767)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:739)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:98)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:91)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.createDataSourceRegistry(BaseProjectImpl.java:215)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.lambda$0(BaseProjectImpl.java:197)
	- locked <0x000000008190e2b8> (a java.lang.Object)
	at org.jkiss.dbeaver.registry.BaseProjectImpl$$Lambda$735/0x000000010068b798.run(Unknown Source)
	at org.jkiss.dbeaver.registry.BaseProjectImpl.lambda$1(BaseProjectImpl.java:207)
	at org.jkiss.dbeaver.registry.BaseProjectImpl$$Lambda$736/0x000000010068b9b8.run(Unknown Source)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:722)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:264)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I see one of the processes is waiting for a password.

**Comment by SAPJens** [comment]
@LonwoLonwo Yes, I have a master password. And no, I do not get a popup to enter it.

**Comment by LonwoLonwo** [comment]
Okey, here is the list of possible solutions:

1. You can reset your workspace https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings. It looks like one of your previous editors is open and waiting for the password
2. You can check our latest Early Access version: https://dbeaver.com/files/ea/. Some of the issues with the master password we fixed already.
3. You can return to the previous version. Here is the list of previous versions: https://dbeaver.com/files/

**Comment by SAPJens** [comment]
@LonwoLonwo Thanks, you are right: a previous editors was open!
I did go back to 23.x and closed it.
Now it opens with 24.0.1.
Is this something you can improve?

**Comment by LonwoLonwo** [comment]
>I did go back to 23.x and closed it.

Could you please say what exactly did you close? Which editor? For our testing.

**Comment by SAPJens** [comment]
Yes, I did close the editor!

**Comment by SAPJens** [comment]
Actually, it were two editors!

**Comment by LonwoLonwo** [comment]
> Actually, it were two editors!

Which editors?

**Comment by SAPJens** [comment]
This is how it looked.
I have multiple projects, each with a password.
I had one sql script open from project A.
And a folder from project B.
In DBEaver 23.x this resulted in multiple popups on startup.
![image](https://github.com/dbeaver/dbeaver/assets/128074122/5d2902e3-f22c-4d42-9e44-6c4b502539a0)

**Comment by LonwoLonwo** [comment]
Thanks for your investigation @SAPJens

**Comment by puphan** [comment]
> Okey, here is the list of possible solutions:
> 
> 1. You can reset your workspace https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings. It looks like one of your previous editors is open and waiting for the password
> 2. You can check our latest Early Access version: https://dbeaver.com/files/ea/. Some of the issues with the master password we fixed already.
> 3. You can return to the previous version. Here is the list of previous versions: https://dbeaver.com/files/

It work for me. Thank you.
