### ISSUE TITLE
Explain Execution Plan fails with incorrect error for simple MySQL query

### ISSUE THREAD

**Issue by webereinc** [dbeaver/dbeaver#23278]
### Description

When attempting to run a syntactically correct MySQL query of

select count(*) from employees;

clicking on the icon to Explain Execution Plan, the program incorrectly reports:

(conn=10) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select count(*) from employees' at line 1

There is no SQL syntax error.

The Exception Stack Trace shows the following:

java.sql.SQLSyntaxErrorException: (conn=10) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select count(*) from employees' at line 1
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
	at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:288)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanClassic.<init>(MySQLPlanClassic.java:42)
	at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser.explain(MySQLPlanAnalyser.java:64)
	at org.jkiss.dbeaver.ext.mysql.model.plan.MySQLPlanAnalyser.planQueryExecution(MySQLPlanAnalyser.java:84)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:408)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:402)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

Community Version 24.0.1.202403241413

### Operating System

Windows 10 Pro 22H2

### Database and driver

Database: MySQL 8.0.21
Driver: MariaDB Connector/J 3.0.7

### Steps to reproduce

Using the Employees sample database;
Create a query to "Select count(*) from employees;"
The query runs and returns a single row with a count of 300,024 records.
Click on the Explain Execution Plan icon and the error occurs.
Alternatively, add the keyword 'explain' in front of the actual statement such as 'Explain Select count(*) from employees;' and the explain runs and returns an explain row which indicates that there are only 299,645 rows?!

The bug appears to be with how the icon tool incorrectly prepends the 'explain' keyword to the rest of the sql query syntax.

**Comment by LonwoLonwo** [comment]
Hello @webereinc 

> Driver: MariaDB Connector/J 3.0.7

Do you have any specific reasons to use MariDB connector? Did you try to use the MySQL connector in DBeaver? It is the best choice for version 8.

![2024-03-29 22_17_50-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/5e2c3679-6784-46de-8e01-68d5dd941af6)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by voidreader** [comment]
well, I'm using 24.0.3 
I can't execute mysql's some keywords like  `show variables;` or `explain select a.* from some_table a`

I think this version has some issues because the older version they worked.

**Comment by webereinc** [comment]
Hey Gameless,

I believe what you are discovering is not the same thing that I was originally describing. Rather, what you are describing is a problem with the overall parser that seems to have troubles with blank lines and will incorrectly report normally working queries as being syntax errors.
This does appear to be a new bug introduced in version 23.0.3 which is not the same as my original issue. 

The fix that I found for this new issue is to go into the preferences, the SQL editor, and Then change the drop-down list for handling blank lines as delimiters to “Never”. The other options of “Smart” and “Always” seem to have broken the way the parser processes normal delimiters and blank lines.

I hope this is helpful.

- Ed

Ed Weber, President 
***@***.***

PS - Sent via phone… Please pardon any auto-correct errors, abbreviations, or typos.

**Comment by E1izabeth** [comment]
It has nothing to do with this issue. The fix for this bug will be included in DBeaver 24.0.4.
Also you can try Early Access version with fix https://dbeaver.io/files/ea/ now.
