### ISSUE TITLE
Test Connection doesn't work

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#23297]
### Description

Click on Test Connection button in connection configuration shell throws **Invalid thread access**

https://github.com/dbeaver/dbeaver/assets/43252954/d28a659e-b236-48f9-a2c3-c7e97f6bddd8

```
!ENTRY org.eclipse.ui 2 2 2024-04-01 23:14:16.443
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)

!ENTRY org.jkiss.dbeaver.core 4 2 2024-04-01 23:15:00.645
!MESSAGE Problems occurred when invoking code from plug-in: "org.jkiss.dbeaver.core".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:288)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:381)
	at org.eclipse.jface.window.Window.createShell(Window.java:487)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.create(BaseDialog.java:89)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$1.done(ConnectionWizard.java:192)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:160)
	at org.eclipse.core.internal.jobs.JobListeners.sendEventsAsync(JobListeners.java:140)
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:80)
	at org.eclipse.core.internal.jobs.JobManager.withWriteLock(JobManager.java:550)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:751)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)

```

### DBeaver Version

24.0.1

### Operating System

win10

### Database and driver

not depended

**Comment by serge-rider** [comment]
Cause and fix in https://github.com/dbeaver/dbeaver/issues/23135
