### ISSUE TITLE
Oracle XMLTYPE preview panel is broken

### ISSUE THREAD

**Issue by LeonardoDarkVinchi** [dbeaver/dbeaver#23310]
### Description

Describe the problem you're observing:

When previewing a large XML field, an "Error loading text value" error appears on the bottom and the value tab in the preview panel is empty.
When the XML is small (I guessed less than 4.000 chars) the preview works just fine.

### DBeaver Version

24.0.1.202403241413

### Operating System

Windows 10 19045.4170

### Database and driver

- Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
- Oracle drivers (xdb6.jar - 18.3.0.0 , ojdbc11.jar - 23.2.0.0, orai18n.jar - 23.2.0.0, xmlparserv2.jar - 18.3.0.0)

### Steps to reproduce

Query a table with an XMLTYPE column with more than 4.000 chars. Open the preview panel, observe that it's empty and you get error.

### Additional context

java.nio.file.FileSystemException: C:\Users\DEBI-1\AppData\Local\Temp\.dbeaver-temp5409765200481778748\.lob\fp-bcs-cc.XMLAGG(XMLELEMENT(E,UNSORTED.CRONOS__';')).EXTRACT('__TEXT()')--,--XMLAGG(XMLELEMENT(E,UNSORTED.FPS,',').EXTRACT('__TEXT()')).GETCLOBVAL(),--XMLAGG(XMLELEMENT(E,UNSORTED.HNTR,',').EXTRACT('__TEXT()')).GETCLOBVAL(),--XMLAGG(XMLELEMENT(E,UNSORTED.AFS,',').E-1712143219368.data: Синтаксическая ошибка в имени файла, имени папки или метке тома
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.createFile(Unknown Source)
	at org.jkiss.dbeaver.utils.ContentUtils.makeTempFile(ContentUtils.java:80)
	at org.jkiss.dbeaver.utils.ContentUtils.createTempContentFile(ContentUtils.java:60)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditorInput.prepareContent(ContentEditorInput.java:230)
	at org.jkiss.dbeaver.ui.editors.content.ContentEditorInput.<init>(ContentEditorInput.java:104)
	at org.jkiss.dbeaver.ui.data.managers.AbstractTextPanelEditor.showRegularContent(AbstractTextPanelEditor.java:346)
	at org.jkiss.dbeaver.ui.data.managers.AbstractTextPanelEditor.primeEditorValue(AbstractTextPanelEditor.java:321)
	at org.jkiss.dbeaver.ui.data.managers.AbstractTextPanelEditor.primeEditorValue(AbstractTextPanelEditor.java:1)
	at org.jkiss.dbeaver.ui.data.editors.ContentPanelEditor$StreamValueLoadService.lambda$0(ContentPanelEditor.java:574)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:296)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:641)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:601)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1458)

**Comment by MashaKorax** [comment]
Hello @LeonardoDarkVinchi 
You can increase the size of content representation in the value panel using this configuration. 
Please let me know if it was helpful.
![iScreen Shoter - 20240413152922633](https://github.com/dbeaver/dbeaver/assets/84867187/bf9faced-4a6c-42ed-b0aa-74a696433748)

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
