### ISSUE TITLE
[CrateDB] Functions folder shouldn't appear in the navigator

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#23328]
### Description

CrateDB doesn't support stored procedures so functions folder shouldn't exist in the navigator or Schema metadata tab. Opening them will lead to an error. This is also applicable to a foreign keys folder inside a table node.

### DBeaver Version

24.0.2

### Operating System

Any

### Database and driver

CrateDB 5.3.3 (built a0a52be/2023-06-26T19:53:14Z, Linux 5.4.0-122-generic amd64, OpenJDK 64-Bit Server VM 19.0.2+7)

PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

Expand functions folder for any schema in the navigator

### Additional context

```
org.postgresql.util.PSQLException: ERROR: Unknown function: pg_catalog.pg_get_expr(p.proargdefaults, 0), no overload found for matching argument types: (object_array, integer). Possible candidates: pg_catalog.pg_get_expr(text, integer):text, pg_catalog.pg_get_expr(text, integer, boolean):text
  Where: io.crate.metadata.Functions.raiseUnknownFunction(Functions.java:357)
io.crate.metadata.Functions.resolveFunctionBySignature(Functions.java:247)
io.crate.metadata.Functions.get(Functions.java:148)
io.crate.metadata.Functions.get(Functions.java:126)
io.crate.analyze.expressions.ExpressionAnalyzer.allocateBuiltinOrUdfFunction(ExpressionAnalyzer.java:1178)
io.crate.analyze.expressions.ExpressionAnalyzer.allocateBuiltinOrUdfFunction(ExpressionAnalyzer.java:1135)
io.crate.analyze.expressions.ExpressionAnalyzer.convertFunctionCall(ExpressionAnalyzer.java:305)
io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitFunctionCall(ExpressionAnalyzer.java:505)
io.crate.analyze.expressions.ExpressionAnalyzer$InnerExpressionAnalyzer.visitFunctionCall(ExpressionAnalyzer.java:443)
io.crate.sql.tree.FunctionCall.accept(FunctionCall.java:84)
io.crate.analyze.expressions.ExpressionAnalyzer.convert(ExpressionAnalyzer.java:244)
io.crate.analyze.relations.select.SelectAnalysis.toSymbol(SelectAnalysis.java:63)
io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:63)
io.crate.analyze.relations.select.SelectAnalyzer$InnerVisitor.visitSingleColumn(SelectAnalyzer.java:59)
io.crate.sql.tree.SingleColumn.accept(SingleColumn.java:78)
io.crate.analyze.relations.select.SelectAnalyzer.lambda$analyzeSelectItems$0(SelectAnalyzer.java:54)
java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
io.crate.analyze.relations.select.SelectAnalyzer.analyzeSelectItems(SelectAnalyzer.java:54)
io.crate.analyze.relations.RelationAnalyzer.visitQuerySpecification(RelationAnalyzer.java:440)


	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)

	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)

	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)

	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)

	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)

	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)

	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:110)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:74)

	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getProcedures(PostgreSchema.java:361)

	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema.getProcedures(PostgreSchema.java:1)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:984)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1056)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:599)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:468)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:229)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)

	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:91)

	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:308)

	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:89)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:73)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by Matvey16** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/dbeaver/project/8805?defectId=15220)
