### ISSUE TITLE
Error setting default catalog/schema for new connection

### ISSUE THREAD

**Issue by pauloandre2** [dbeaver/dbeaver#23365]
### Description

Whenever I open dbeaver it shows this message, also if I change tab:

Error setting default catalog/schema for new connection
SQL Error [1064] [42000]: (conn=181) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 'dbo'' at line 1

### DBeaver Version

Community Edition 24.0.2

### Operating System

Windows 11

### Database and driver

MariaDB 10.11.2
Driver MariaDB Connector/J 3.3.3

### Steps to reproduce

Just open dbeaver with a script open

### Additional context

Log contents:
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -eclipse.keyring C:\Users\paulo\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Tue Apr 09 11:36:19 WEST 2024
(conn=186) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 'dbo'' at line 1

java.sql.SQLSyntaxErrorException: (conn=186) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 'dbo'' at line 1
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:172)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:915)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:854)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:773)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:697)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
	at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:276)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.getObject(JDBCStructLookupCache.java:62)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getChild(MySQLCatalog.java:418)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getChild(MySQLCatalog.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:413)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:764)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by LonwoLonwo** [comment]
Hello @pauloandre2 

Does it mean that you have the "dbo" database, and you try to set it as a default database in the navigator tree?

**Comment by pauloandre2** [comment]
no, I don't have dbo on the DB, in fact that is only for sql server databases (I also have connections for those, but what is selected is a mariadb database).
Here are the list of  catalog/schemas selectable:
![image](https://github.com/dbeaver/dbeaver/assets/19745207/40fdeba7-2236-4192-b1b1-206839505a65)
and here are the configurations on the connection settings:
![image](https://github.com/dbeaver/dbeaver/assets/19745207/d013c5ba-3155-453f-8ccf-d13859e37ed1)


Is there any way to access what query it's trying to do? maybe that would give some ideas what the problem is, but the log shows nothing

**Comment by LonwoLonwo** [comment]
Do you have anything in the initialization section in your connection settings? Default catalog name?

**Comment by pauloandre2** [comment]
No, nothing there, only "nick"

However, I noticed something interesting. This only happened to me in scripts I had open for a very long time (I have autosave on). I usually keep these scripts open across upgrades, sometimes for months.
I created new sql scripts, copied the text into those and closed the old ones. The problem disappeared, so I'm closing the issue.

**Comment by LonwoLonwo** [comment]
Thanks for the update @pauloandre2
