### ISSUE TITLE
SQL Error: Internal jdbc driver error

### ISSUE THREAD

**Issue by lubakka** [dbeaver/dbeaver#23386]
### Description

When I want to open a table with many records. First it shows loading, I wait about 10 seconds or more and it crashes showing an error. But not on every table, but on a specific one. And in it I have a history of changes. The table has more than 10 million records

### DBeaver Version

Community Edition 24.0.2.202404071654

### Operating System

Ubuntu 22.04.3 LTS

### Database and driver

1. Database name and version: MariaDB 10.3.39-MariaDB-1:10.3.39+maria~ubu2004
2. Driver name and version: MariaDB Connector/J 3.3.2

### Steps to reproduce

1. I connect to database 
2. I'll open the table "changes"
3. I go to Data tab
4. See an error 'SQL Error: Internal jdbc driver error'
5. Details >> 'org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:185)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5152)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:295)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space
'

**Comment by ShadelessFox** [comment]
What fetch size is specified down there?
![image](https://github.com/dbeaver/dbeaver/assets/35821147/be66825a-4a1f-4c99-9d91-347022bcefa6)

If it's relatively small, then you can try turning on this option:
![image](https://github.com/dbeaver/dbeaver/assets/35821147/6488b6b4-631b-4d4b-9491-f72f7f1dfa38)

Please let me know if it helps.

**Comment by lubakka** [comment]
@ShadelessFox 
This does not fix the problem with and without this option it does not work. 
I have had this problem for quite some time. I'm using version 23.3.0 to be able to work.

**Comment by ShadelessFox** [comment]
This might be the culprit: #22689

Try downgrading the driver version to the previous `3.0.7` (or upgrade to the latest `3.3.3`) to see if it works:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/bee38812-8b6a-47fe-9be0-cb6a51f54785)

**Comment by lubakka** [comment]
@ShadelessFox 
Changing drivers doesn't help either. I changed MariaDB Connector/J from 3.3.3 to 2.6.0 and it keeps giving the same error.

**Comment by ShadelessFox** [comment]
Just ensuring we're not missing something, did the "update driver" dialog show after changing the version and reconnecting to the database?

**Comment by lubakka** [comment]
@ShadelessFox 

Yes

![image](https://github.com/dbeaver/dbeaver/assets/5030587/c17f0696-1d86-4d8a-8ad1-1492c28370e2)


![image](https://github.com/dbeaver/dbeaver/assets/5030587/ae3ba47e-bb2e-4389-8e13-6e2013646e2a)

**Comment by lubakka** [comment]
@ShadelessFox 

As I said it above with 23.3.0.202312122044 anything goes. After this version the problems start. And with this old version I am with 3.0.7 version of the driver

**Comment by Destrolaric** [comment]
@lubakka, Hi, could you see what query is sent to database, you can open it in `Window -> View -> Query Manager`.


![Image](https://github.com/dbeaver/dbeaver/assets/20579256/2b4e77e5-2716-4a64-9f33-b91ed5c5aef9)

**Comment by lubakka** [comment]
@Destrolaric 
Yes, of course you can see. The error is there both with and without the setting for "Use SQL to limit fetch size"

![image](https://github.com/dbeaver/dbeaver/assets/5030587/33d4800c-3463-4df3-bc8c-b630ad419a35)

**Comment by lubakka** [comment]
@Destrolaric 

any solution ? i have the same error , and nothing helps me

**Comment by E1izabeth** [comment]
@lubakka could you send a screenshot of this page of the Connection Settings?
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fd590f93-3417-4037-b47b-9192d32baf3a)

**Comment by lubakka** [comment]
@E1izabeth 
Yes,

For connection
![image](https://github.com/dbeaver/dbeaver/assets/5030587/1bafb8e1-0297-44b4-9e76-bc43005498a4)


And my global connection settigns
![image](https://github.com/dbeaver/dbeaver/assets/5030587/9d9b5dcb-8a09-452b-bc96-938ee9977556)

**Comment by ShadelessFox** [comment]
Can you please try reproducing the issue again and send log files afterward? https://github.com/dbeaver/dbeaver/wiki/Log-files#log-files

**Comment by lubakka** [comment]
@ShadelessFox 
Yes of course


[dbeaver-debug.log.txt](https://github.com/user-attachments/files/15721351/dbeaver-debug.log.txt)
[log.txt](https://github.com/user-attachments/files/15721356/log.txt)

**Comment by Destrolaric** [comment]
@lubakka Hi, is it possible for you to provide a table DDL?

**Comment by lubakka** [comment]
@Destrolaric 
Yes of course.

I hope you find a solution soon that I can't work.

====================================================================================
CREATE TABLE `changes` (
  `_changesID` int(11) NOT NULL AUTO_INCREMENT,
  `DataID` int(11) NOT NULL DEFAULT 0,
  `DataTabelle` varchar(255) DEFAULT '',
  `Aktion` varchar(255) DEFAULT '',
  `GrundDataID` int(11) NOT NULL DEFAULT 0,
  `GrundDataTabelle` varchar(255) NOT NULL DEFAULT '',
  `Aenderung` text DEFAULT NULL,
  `Nutzername` varchar(255) DEFAULT '',
  `Zeitpunkt` datetime DEFAULT '0000-00-00 00:00:00',
  `_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `_updatedby` varchar(32) DEFAULT '',
  `_created` datetime DEFAULT '0000-00-00 00:00:00',
  `_createdby` varchar(32) DEFAULT '',
  PRIMARY KEY (`_changesID`),
  KEY `idx2` (`DataTabelle`) USING BTREE,
  KEY `idx4` (`GrundDataTabelle`) USING BTREE,
  KEY `idx5` (`Aktion`) USING BTREE,
  KEY `idx6` (`Zeitpunkt`) USING BTREE,
  KEY `idx1` (`DataID`) USING BTREE,
  KEY `idx3` (`GrundDataID`) USING BTREE,
  KEY `idx7` (`_created`) USING BTREE,
  KEY `idx8` (`_createdby`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10907639 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=FIXED;

**Comment by serjiokov** [comment]
Hello @lubakka,
Generally, the issue with details of `Caused by: java. lang.OutOfMemoryError: Java heap space` cause of 'eating' all memory specifically for your case. I would recommend increasing memory allocation in the 'dbeaver.ini' file. 
Open dbeaver.ini file in product directory 
modify max heap size value to  
 -Xmx4096m
https://eclipse.dev/openj9/docs/xms/

**Comment by serjiokov** [comment]
@lubakka On another side the limitation option  (fetch size) works fine for the same table on my machine,
One point, please set the option to enable on your page (currently it is disabled) 
![image](https://github.com/dbeaver/dbeaver/assets/32031248/c81f5f0c-62e4-4ee2-b926-44c0164e50f9)
to
![image](https://github.com/dbeaver/dbeaver/assets/32031248/21f1bf58-be3a-43c3-ac33-6f64701c54ab)

**Comment by lubakka** [comment]
@serjiokov 
this solution does not solve 100% this problem. Yes there is a slight improvement, but only if I want to view the records from ID 1 to 2000 and more by scrolling. But when only 100 records per page show. In the following case, if I increase it to 200 rows to show per page, then it still shows error. If I decide to reverse the sort from the largest ID to the smallest. But with 100 records per page. I manage to see the first page and then after the first scroll and it shows the same error again. 

So, this to me is not a solution to the problem. ;(

Separately, I don't want only 100 results displayed for each table. 

Sorry for my late reply, but I'm on vacation and didn't have much time.

**Comment by ShadelessFox** [comment]
Hello @lubakka,

Sorry for the long wait. Unfortunately, we're out of ideas.

As the last resort, could you provide a screenshot of your driver from the driver manager? I suspect that it might've gotten corrupted and become a "generic driver". This might result in a variety of different issues.

You can also try deleting and restoring the driver there as well as change the connection's driver by selecting your connection first and using "Database -> Change Connection(-s) Driver".

**Comment by E1izabeth** [comment]
Unfortunately, we have not been able to reproduce the reported behavior. Therefore, I am closing this issue. If we receive a similar report from another user or can reproduce the issue in the future, we will reopen it.

**Comment by ycaosbiann** [comment]
SQL Error: Internal jdbc driver error

Fix this problem pls

**Comment by evelyn9191** [comment]
I can confirm this is happening to me as well, for every new version above 23.3.0 - I had to downgrade to that one.

Operating System
macOS Sequoia 15.3.1

Database and driver
Database name and version: PostgreSQL 14.6
Driver name and version: net.snowflake.client.jdbc.SnowflakeDriver

Same error message as @lubakka reported.

**Comment by ShadelessFox** [comment]
@evelyn9191, your issue is definitely different, as you're using a completely different driver and database. Please create a new issue and provide as many details as possible there.
