### ISSUE TITLE
SQL Error [08S01]: Communications link failure

### ISSUE THREAD

**Issue by derekzhan** [dbeaver/dbeaver#23447]
### Description

I can't execute update/delete when i use update or delete sql, it appears following errors, I use datagrip and navicat is ok.
![image](https://github.com/dbeaver/dbeaver/assets/2375460/33d4c234-40cd-4d1d-86d8-624ef983e622)

### DBeaver Version

Version 24.0.1.202403241413

### Operating System

macos 14.0

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by derekzhan** [comment]
> Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/. @E1izabeth 

2024-04-17 17:36:41.681 - Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:576)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:762)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:701)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:157)
	at com.mysql.cj.NativeSession.queryServerVariable(NativeSession.java:593)
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1356)
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1349)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkReadOnlySafeStatement(ClientPreparedStatement.java:291)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:301)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:310)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:178)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:757)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$2(ResultSetPersister.java:707)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:706)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:644)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by E1izabeth** [comment]
I want to know if there some other error(s) in the logs

**Comment by derekzhan** [comment]
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/15009238/dbeaver-debug.log)  This is a whole log file  @E1izabeth

**Comment by E1izabeth** [comment]
OK, thank you

**Comment by derekzhan** [comment]
do you have any progress? @E1izabeth

**Comment by E1izabeth** [comment]
Currently your issue doesn't look like a DBeaver issue for me.
What database do you use?

**Comment by derekzhan** [comment]
> Currently your issue doesn't look like a DBeaver issue for me. What database do you use?

Mysql 8.0.27,  select sql is ok, only update/delete sql is not work

**Comment by E1izabeth** [comment]
Does insert works for you? Can you update or delete rows in Data tab, not through SQL statement execution in SQL Editor?
Also we would kindly ask you to check access rights of your user.

**Comment by BenRacicot** [comment]
Hi @E1izabeth I just reran my local docker MySQL `docker-compose up -d` and am having the same issue. It does appear to be a bug because the databases and their tables are in fact connected. But the errors from this story persist whenever I try any form of query, even the "calculate total row count" button causes the error.

Restarting everything doesnt fix yet both Docker and Dbeaver are running and connecting without errors.

Looks like the same in https://github.com/dbeaver/dbeaver/issues/12138

> Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

**Comment by BenRacicot** [comment]
Whoa, this... cost me my afternoon. According [MariaDB](https://logiqx.github.io/tech-docs/Services/Databases/MariaDB/) 

So we need to proportionally increase the `innodb-log-file-size` to `innodb-buffer-pool-size`. 

Here's the calculation:
Current ratio: innodb-log-file-size = 512M, innodb-buffer-pool-size = 2G

`Ratio = 512M / 2G = 0.25 (25%)`

Applying the same ratio to the new innodb-buffer-pool-size of 16G:

New innodb-log-file-size = 16G * 0.25 = 4G

But numbers that high didnt work either. Kept attempting lower numbers until I ended up with a functional `docker-compose up -d` with:
```
command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=4G --innodb-log-file-size=1G
```

**Comment by MashaKorax** [comment]
So, can we close your issue?

**Comment by BenRacicot** [comment]
Well yes, I hope I've provided guidance that this is not a DBeaver issue. 
However, your users are likely to come across this since its not clear and took a weird amount of research to find the cause.

Thanks for replying!
