### ISSUE TITLE
Oracle - Alter table - Persists

### ISSUE THREAD

**Issue by fraxen** [dbeaver/dbeaver#2600]
I am using DBeaver (4.2.6) installed through the Eclipse (4.7.1a) Marketplace, on Windows 7. The database is Oracle 11g (11.2.0.4.0) and the driver at 11.2.0.4.0 (JDBC).

Everything works very nicely, except when performing any _ALTER TABLE_. A box pops up the _DDL_ code, which is fine, but when I click _Persist_ I get an error, and I have to force close Eclipse - see attachment.

![image](https://user-images.githubusercontent.com/429171/33596867-ab7cb7e2-d99d-11e7-83e8-eb0884c1a988.png)

The workspace log says...
```!ENTRY org.eclipse.ui.workbench.texteditor 4 2 2017-12-05 09:11:22.845
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench.texteditor".
!STACK 0
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Color.getRGB(Color.java:315)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.defensiveCopy(ImageDrawer.java:113)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.prepareColorAttribute(ImageDrawer.java:109)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.setBackground(ImageDrawer.java:53)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageUpdate.setBackground(ImageUpdate.java:38)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ClickControl.setBackground(ClickControl.java:96)
	at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.setBackground(FlatScrollBar.java:237)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayoutFactory.setBackgroundColor(ScrollableLayoutFactory.java:142)
	at com.codeaffine.eclipse.swt.widget.scrollable.StyledTextAdapter.setBackgroundColor(StyledTextAdapter.java:973)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ColorReconciliation.run(ColorReconciliation.java:32)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.resume(Reconciliation.java:84)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWhileSuspended(Reconciliation.java:64)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayout.layout(ScrollableLayout.java:54)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1363)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1774)
	at org.eclipse.swt.widgets.Canvas.WM_SIZE(Canvas.java:492)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4918)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2555)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5743)
	at org.eclipse.swt.widgets.Canvas.WM_WINDOWPOSCHANGED(Canvas.java:499)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4931)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:1137)
	at org.eclipse.swt.widgets.Control.getBoundsInPixels(Control.java:1264)
	at org.eclipse.swt.widgets.Control.getBounds(Control.java:1260)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.updateAdapterBounds(LayoutActor.java:73)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.lambda$0(LayoutActor.java:52)
	at com.codeaffine.eclipse.swt.util.OperationWithRedrawSuspension.execute(OperationWithRedrawSuspension.java:20)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.layout(LayoutActor.java:50)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1363)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1348)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:702)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:653)
	at org.eclipse.jface.text.source.CompositeRuler.layoutTextViewer(CompositeRuler.java:595)
	at org.eclipse.jface.text.source.CompositeRuler.removeDecorator(CompositeRuler.java:578)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport$2.run(AbstractTextEditor.java:1657)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.removeColumn(AbstractTextEditor.java:1661)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.dispose(AbstractTextEditor.java:1750)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor$2.dispose(AbstractDecoratedTextEditor.java:785)
	at org.eclipse.ui.texteditor.AbstractTextEditor.dispose(AbstractTextEditor.java:4428)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.dispose(AbstractDecoratedTextEditor.java:382)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.dispose(BaseTextEditor.java:115)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.dispose(SQLEditorBase.java:338)
	at org.jkiss.dbeaver.ui.dialogs.sql.BaseSQLDialog$2.widgetDisposed(BaseSQLDialog.java:118)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:124)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:836)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:929)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:839)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:929)
	at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:171)
	at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:808)
	at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:1368)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:839)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:460)
	at org.eclipse.swt.widgets.Decorations.dispose(Decorations.java:460)
	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:737)
	at org.eclipse.jface.window.Window.close(Window.java:330)
	at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:990)
	at org.jkiss.dbeaver.ui.dialogs.sql.ViewSQLDialog.buttonPressed(ViewSQLDialog.java:115)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$ChangesPreviewer.run(EntityEditor.java:889)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4889)
	at org.jkiss.dbeaver.core.DBeaverUI.syncExec(DBeaverUI.java:314)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.showChanges(EntityEditor.java:415)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.doSave(EntityEditor.java:241)
	at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:154)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:259)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:158)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3917)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3931)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:287)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:527)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:577)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:385)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:331)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:88)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1271)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4962)
	at org.eclipse.swt.widgets.Table.WM_CHAR(Table.java:6123)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:6118)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)```

**Comment by serge-rider** [comment]
Not reproducible. Please reopen if this will happen again in fresh version.
