### ISSUE TITLE
Error for any table operations (refresh, change column order, etc)

### ISSUE THREAD

**Issue by a-locatelli** [dbeaver/dbeaver#26850]
### Description

A popup error message appear each time i try to do some operation on table/column using the gui tools provided.

For example, when i try to re-order a column:
![image](https://github.com/dbeaver/dbeaver/assets/92114556/e2e34a36-2d35-4622-9f75-f70d1962f150)

Or if i refresh the table tab:
![image](https://github.com/dbeaver/dbeaver/assets/92114556/8869d467-6317-4dbe-8d42-de744886df4e)

Tipically the error does not affect the success the operation.
The problem occurs with every table, the one of the images is for example only

logs:

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/ale/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /home/ale/[omitted]/dbeaver/sei/.metadata/.bak_1.log
Created Time: 2024-04-26 10:35:39.749

org.jkiss.dbeaver.model
Error
Fri Apr 26 10:53:07 CEST 2024
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 'event_queue'' at line 1

java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 'event_queue'' at line 1
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:289)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.refreshObject(JDBCStructLookupCache.java:85)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLTableBase.refreshObject(MySQLTableBase.java:139)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.refreshObject(MySQLTable.java:699)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:362)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:360)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:189)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

24.0.3

### Operating System

Ubuntu 20.04

### Database and driver

mariadb 3.3.2

### Steps to reproduce

1. have a database
2. have a table and columns
3. some actions that cause the error:
  3a. change the datatype of some column and save
  3b. change the position of columns (using icons) and save
  3c. refresh the table (F5 or refresh button)

**Comment by E1izabeth** [comment]
Does your database name contain non-latin characters?

**Comment by a-locatelli** [comment]
> Does your database name contain non-latin characters?

No

**Comment by serjiokov** [comment]
Can you please provide details from the "test connection"?

**Comment by E1izabeth** [comment]
Please provide driver and server version. You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/be8bb33e-b264-4244-ab6e-9a744767b2e9)

**Comment by Destrolaric** [comment]
@a-locatelli Hi, could you open the Query Manager and give me information on the screenshot from it after the failed query?
https://dbeaver.com/docs/dbeaver/Query-Manager/

**Comment by a-locatelli** [comment]
> Please provide driver and server version. You can get this information by clicking `Test connection...` button in the `Connection configuration` dialog. ![image](https://private-user-images.githubusercontent.com/28875055/332941359-be8bb33e-b264-4244-ab6e-9a744767b2e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzU3NzcsIm5iZiI6MTcxNjUzNTQ3NywicGF0aCI6Ii8yODg3NTA1NS8zMzI5NDEzNTktYmU4YmIzM2UtYjI2NC00MjQ0LWFiNmUtOWE3NDQ3NjdiMmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDQ3NTQ2MDVkNDFiYzczMTdjNzA5NjJhNTM0MzNmY2U1ZjkxY2UwYTQ3YjMzNTYwYTgwYTM5ZWRlNTNiNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.loC4AjP1I7ZIRtuilGXhxImYXwiqmDWooizhSfLYafA)

Hi, here the screenshot of 'Test Connection' dialog:

![image](https://github.com/dbeaver/dbeaver/assets/92114556/befe8c8c-d13f-4ed4-aafc-e42a8154e04e)

**Comment by a-locatelli** [comment]
> @a-locatelli Hi, could you open the Query Manager and give me information on the screenshot from it after the failed query? https://dbeaver.com/docs/dbeaver/Query-Manager/

Hi,
i didn't know the Query Manager, thank you.

Here the screenshot. Is taken after a refresh on Table view (Properties tab)
![image](https://github.com/dbeaver/dbeaver/assets/92114556/7a76427c-238f-47fc-bcbf-cbd96b2c7208)

'smart3' is the schema name

**Comment by E1izabeth** [comment]
Thank you for providing more information

**Comment by E1izabeth** [comment]
Please try turning off this setting
![image](https://github.com/dbeaver/dbeaver/assets/28875055/638cdde4-d992-4086-a4d8-a6cad1590f0d)

**Comment by a-locatelli** [comment]
> Please try turning off this setting ![image](https://private-user-images.githubusercontent.com/28875055/335194903-638cdde4-d992-4086-a4d8-a6cad1590f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzYyMDYsIm5iZiI6MTcxNzA3NTkwNiwicGF0aCI6Ii8yODg3NTA1NS8zMzUxOTQ5MDMtNjM4Y2RkZTQtZDk5Mi00MDg2LWE0ZDgtYTZjYWQxNTkwZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDgyOGIwYTdmYjMwYjc5YWVhZjZmYTZiZWI3NTUzYTE0NDlmYTRjNmFhYTJmNTVkNzdkNTgwZjg5MGMzMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1W8gRA3C2DYwdBWlWe0X9X9rT5Zweb91JrBMcGQYxw)

My flag was already unchecked. 
I've tried enabling it and now the error does not appear anymore....
