### ISSUE TITLE
Unable to open cell editor after repeated opens/closes

### ISSUE THREAD

**Issue by svrana** [dbeaver/dbeaver#2805]
I can't nail down the repo steps. But I've been making many changes to a particular cell, closing the cell editor, saving the results, and starting over. Editor works fine for a while and then eventually the exception occurs and it stops working.

This exception is from a master build with sha 2930bbae2a.

(postgres, this was from the text editor on a json field, but happens on the json editor too)

2018-01-17 20:07:16.448 - Event loop exception
org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Widget is disposed
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:287)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:527)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:577)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:385)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:331)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:88)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1653)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1347)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
        at org.eclipse.swt.widgets.Control.traverse(Control.java:6006)
        at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:5984)
        at org.eclipse.swt.widgets.Composite.translateTraversal(Composite.java:1705)
        at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3543)
        at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:785)
        at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1977)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:6188)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:5608)
        at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:160)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4533)
        at org.eclipse.swt.SWT.error(SWT.java:4448)
        at org.eclipse.swt.SWT.error(SWT.java:4419)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:487)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:424)
        at org.eclipse.swt.custom.CTabItem.getControl(CTabItem.java:163)
        at org.eclipse.ui.part.MultiPageEditorPart.getControl(MultiPageEditorPart.java:593)
        at org.jkiss.dbeaver.ui.editors.content.ContentEditor.getControl(ContentEditor.java:476)
        at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.openValueEditor(SpreadsheetPresentation.java:803)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetCommandHandler.execute(ResultSetCommandHandler.java:174)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
        ... 54 more

**Comment by serge-rider** [comment]
I can't reproduce this but I see how this may happen.
Please check the fix in the next version.
Thanks for report.
