### ISSUE TITLE
Null pointer exception opening content editor

### ISSUE THREAD

**Issue by svrana** [dbeaver/dbeaver#2880]
This one is odd and I cannot reproduce at will. But sometimes while editing contents in the editor, the editor closes by itself (as if I saved contents). When trying to reopen it, I see the NPE dialog and this appears on the console.

018-01-26 10:19:03.532 - > Start org.jkiss.dbeaver.core [4.3.2]
2018-01-26 10:19:03.536 - DBeaver Enterprise 4.3.2 is starting
...
2018-01-26 10:13:41.767 - > Start org.eclipse.compare.core [3.6.100.v20170516-0820]
Warning: NLS unused message: XMLPresentation_e_create_xml in: com.dbeaver.ee.runtime.internal.ui.resultset.resultset_messages
Warning: NLS unused message: XMLPresentation_e_create_xml_new in: com.dbeaver.ee.runtime.internal.ui.resultset.resultset_messages
2018-01-26 10:13:59.077 - Can't detect image type: Unsupported or unrecognized format
2018-01-26 10:14:06.511 - Can't detect image type: Unsupported or unrecognized format
2018-01-26 10:14:06.585 - null
java.lang.NullPointerException
        at org.eclipse.e4.ui.internal.workbench.PartActivationHistory.activate(PartActivationHistory.java:53)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:746)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:676)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1186)
        at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
        at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
        at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
        at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
        at org.jkiss.dbeaver.ui.editors.content.ContentEditor.openEditor(ContentEditor.java:87)
        at org.jkiss.dbeaver.ui.data.managers.ContentValueManager.openContentEditor(ContentValueManager.java:94)
        at org.jkiss.dbeaver.ui.data.managers.ContentValueManager.createEditor(ContentValueManager.java:157)
        at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.openValueEditor(SpreadsheetPresentation.java:862)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetCommandHandler.execute(ResultSetCommandHandler.java:174)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:287)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:527)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:577)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:385)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:331)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:88)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1653)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1347)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
        at org.eclipse.swt.widgets.Control.traverse(Control.java:6006)
        at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:5984)
        at org.eclipse.swt.widgets.Composite.translateTraversal(Composite.java:1705)
        at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3543)
        at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:785)
        at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1977)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:6188)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:5608)
        at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)

**Comment by serge-rider** [comment]
Can't reproduce (looks like some Eclipse internal bug. But perhaps it is still caused by some DBeaver issue).

What happens after next content editor re-open? Do you need to restart DBeaver to get rid of this null pointer error?

**Comment by svrana** [comment]
Yeah, not able to load the content editor again and the NPE above is what happens when I do. I'm not able to reopen the content editor again without restarting dbeaver. (I've switched back to 4.3.0 as I haven't seen this on that version, we'll see what happens). Feel free to close if you think it's an eclipse issue. :)

**Comment by serge-rider** [comment]
Even if this is Eclipse issue we still can find some workaround from DBeaver side.
What kind of content editor do you open most often? Images, XMLs, binaries, huge binaries?

**Comment by svrana** [comment]
json, always json

**Comment by svrana** [comment]
Also, had the 'auto save' configuration option enabled when content editor is dirty. Took me a while to figure out this what was causing the content editor to disappear.

**Comment by serge-rider** [comment]
Thanks for details. Will try to catch this..

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
