### ISSUE TITLE
Virtual Foreign key: Reference table container selector doesn't work

### ISSUE THREAD

**Issue by kseniaguzeeva** [dbeaver/dbeaver#29318]
### Description

Reference table container selector doesn't work

### DBeaver Version

Version 24.0.4.202405021119

### Operating System

Win10

### Database and driver

MySQL and PostgreSQL have been tested

### Steps to reproduce

1. Open a table and go to the Virtual tab in Properties
2. Press Add for Virtual FOreign key
3. Look at the Reference table container and try to change it

AR: the selector is empty, no visible changes on pressing "Choose" button
ER: the selector shows the current schema name, you can choose another schema by pressing "Choose" button

https://github.com/dbeaver/dbeaver/assets/112612526/f39383b1-d754-4e21-be5f-599147b900e6

Note: It worked at least in 24.0.0

**Comment by E1izabeth** [comment]
```
2024-05-03 19:02:54.723 - Can't create schema selector
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.app.DBPProject.getName()" because "this.project" is null
	at org.jkiss.dbeaver.ui.controls.ObjectContainerSelectorPanel.loadHistory(ObjectContainerSelectorPanel.java:265)
	at org.jkiss.dbeaver.ui.controls.ObjectContainerSelectorPanel.<init>(ObjectContainerSelectorPanel.java:174)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage$11.<init>(EditForeignKeyPage.java:619)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage.createContainerSelector(EditForeignKeyPage.java:619)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage.createPageContents(EditForeignKeyPage.java:324)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage.createPageContents(EditForeignKeyPage.java:1)
	at org.jkiss.dbeaver.ui.editors.object.struct.BaseObjectEditPage.createControl(BaseObjectEditPage.java:101)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditForeignKeyPage.createControl(EditForeignKeyPage.java:282)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.createDialogArea(EditObjectDialog.java:99)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.createDialogArea(EditObjectDialog.java:1)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.jkiss.dbeaver.ui.editors.object.struct.EditObjectDialog.createContents(EditObjectDialog.java:110)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.jkiss.dbeaver.ui.dialogs.BaseTitleDialog.create(BaseTitleDialog.java:77)
```
