### ISSUE TITLE
Endless errors while working with tables with composite FK

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/dbeaver#29326]
### Description

1. Create tables (example was taken from https://www.sqlite.org/foreignkeys.html)
```
CREATE TABLE album(
  albumartist TEXT,
  albumname TEXT,
  albumcover BINARY,
  PRIMARY KEY(albumartist, albumname)
);

CREATE TABLE song(
  songid     INTEGER,
  songartist TEXT,
  songalbum TEXT,
  songname   TEXT,
  FOREIGN KEY(songartist, songalbum) REFERENCES album(albumartist, albumname)
);
```
2. Open References panel
3. Press `insert new row` button 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/0d65278b-f78f-4e20-ad2f-7fc7a75f527d)
4. Get error on any action after that
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c6e6e0af-dab3-415a-9f4f-9dab4e14eca7)
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-05-03 19:55:24.464
!MESSAGE Entity [song] association [SONG_FK1] columns differ from referenced constraint [MYALBUM_PK] (1<>2)
!STACK 0
org.jkiss.dbeaver.DBException: Entity [song] association [SONG_FK1] columns differ from referenced constraint [MYALBUM_PK] (1<>2)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateReference(ResultSetViewer.java:3595)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$4.run(ReferencesResultsContainer.java:422)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

### DBeaver Version

DBeaver 24.0.4

### Database and driver

![image](https://github.com/dbeaver/dbeaver/assets/28875055/2134be0f-eb61-49d8-9a2d-77ae27995a7d)

**Comment by E1izabeth** [comment]
I get this bug trying to reproduce #29309
I suppose these issues should be solved together.
