### ISSUE TITLE
Oracle dblink error

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#2964]
Hello,

I'm not able to run remote queries with private dblink , the follwing error occurs

SQL Error [2019] [42000]: ORA-02019: connection description for remote database not found

Knowing that the same queries work correctly on Toad and SQuirrel Sql

My current Config:
Dbeaver CE 4.3.4
Oracle 11g
Java 8
Ojdbc6.jar
Windows 7 x64

please find below the log file:

```
2018-02-12 14:30:17.273 - DBeaver 4.3.4 is starting
2018-02-12 14:30:17.276 - Install path: 'C:\dbeaver'
2018-02-12 14:30:17.277 - Instance path: 'file:/C:/Users/user/.dbeaver4/'
2018-02-12 14:30:17.282 - Memory available 981Mb/981Mb
2018-02-12 14:30:17.301 - Starting RMI server at 29273
2018-02-12 14:30:17.446 - Run workbench
2018-02-12 14:30:20.048 - Initializing DBeaver 4.3.4
2018-02-12 14:30:20.054 - Host plugin: org.jkiss.dbeaver.core.application 4.3.4
2018-02-12 14:30:20.061 - Initialize Core...
2018-02-12 14:30:20.373 - Core initialized (312ms)
2018-02-12 14:30:20.378 - Configure workbench window
2018-02-12 14:30:20.465 - Create actions
2018-02-12 14:30:20.469 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-02-12 14:30:20.477 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2018-02-12 14:30:21.233 - Initialize workbench window
2018-02-12 14:30:21.245 - Finish initialization
2018-02-12 14:30:28.158 - Connect with 'RTXP' (oracle_thin-15b33888ccf-657965254db0677e)
2018-02-12 14:31:11.513 - Connected (oracle_thin-15b33888ccf-657965254db0677e, Oracle JDBC driver [12.2.0.1.0])
2018-02-12 14:31:25.023 - Error binding callable statement parameters from metadata: Unsupported feature: checkValidIndex
2018-02-12 14:31:25.028 - Error extracting parameters meta data
java.sql.SQLFeatureNotSupportedException: Unsupported feature: checkValidIndex
	at oracle.jdbc.driver.OracleParameterMetaData.checkValidIndex(OracleParameterMetaData.java:196)
	at oracle.jdbc.driver.OracleParameterMetaData.getParameterMode(OracleParameterMetaData.java:394)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.<init>(JDBCCallableStatementImpl.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createCallableStatement(JDBCFactoryDefault.java:48)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createCallableStatementImpl(JDBCConnectionImpl.java:706)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareCall(JDBCConnectionImpl.java:233)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.getErrorPosition(OracleDataSource.java:618)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.scrollCursorToError(SQLEditorBase.java:1122)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.processQueryResult(SQLEditor.java:2205)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.lambda$4(SQLEditor.java:2187)
	at org.jkiss.dbeaver.core.DBeaverUI$2.runInUIThread(DBeaverUI.java:155)
	at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:41)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.jkiss.dbeaver.ui.UIUtils.waitJobCompletion(UIUtils.java:1507)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor.computeCompletionProposals(SQLCompletionProcessor.java:143)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:2007)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:560)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$7(CompletionProposalPopup.java:555)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:489)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener$1.run(ContentAssistant.java:377)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:160)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
2018-02-12 14:31:25.269 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [2019] [42000]: ORA-02019: connection description for remote database not found

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:401)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:800)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1943)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLSyntaxErrorException: ORA-02019: connection description for remote database not found

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4646)
	at oracle.jdbc.driver.OracleStatement.doScrollStmtExecuteQuery(OracleStatement.java:4762)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1741)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 6 more
Caused by: Error : 2019, Position : 19, Sql = SELECT 1 FROM dual@rtx_to_bscs_link, OriginalSql = SELECT 1 FROM dual@rtx_to_bscs_link, Error Msg = ORA-02019: connection description for remote database not found

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 23 more
```

-----------------
thanks

**Comment by serge-rider** [comment]
Looks like Oracle TNS names misconfiguration. Actually this is very famous error: https://www.google.com/search?q=ORA-02019

The error happens in Oracle JDBC driver, this is definitely not a DBeaver issue.
In any case - if this worked in SQuirrel then it should work in DBeaver as well, you just need to configure dblink properly.

**Comment by fayca121** [comment]
You're right, I've just tried a direct connection and it worked perfectly, so the problem is in my TNS configuration.

Thank you for your support.
