### ISSUE TITLE
Bug in connection MS SQL Server

### ISSUE THREAD

**Issue by wesleipatrik** [dbeaver/dbeaver#2973]
When I open a sql editor on a Sql Server connection the app brokes, I attached a gif with the representation of the bug, and the log file, apparently, there is a error with the connection, some procedure not exists, and dbeaver dies, I suggest a treatment to this exception.
![ice_video_20180214-113422_edit_0](https://user-images.githubusercontent.com/24531607/36207368-cdea735c-117c-11e8-9ae4-ea2e0974977f.gif)
[log.txt](https://github.com/dbeaver/dbeaver/files/1724181/log.txt)
Probably this exception is the error:
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-02-09 17:08:56.222
!MESSAGE Could not find stored procedure 'master..sp_who0'.
!STACK 0
java.sql.SQLException: Could not find stored procedure 'master..sp_who0'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:677)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:787)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:229)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:401)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:800)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1943)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by serge-rider** [comment]
I can't reproduce that. Error you posted is not related.

Are there any native crash log files with thread? 
Usually thread dump remains in current directory.
It should have name like hs_err_XXX.log.

**Comment by wesleipatrik** [comment]
I can't find the crash log files, the log file doesn't help? I thought is missing a treatment for exception.

**Comment by wesleipatrik** [comment]
Looking at stacktrace, I can imagine it is a exception from database, but, the application should not broke.

**Comment by serge-rider** [comment]
Error log file contains just some regular errors (SQL errors and a couple of internal Eclipse errors whoch shouldn't affect UI behavior).
In your case whole process (Java) dies. This can't be tracked in regular log files, only system crash logs can help :(

**Comment by uslss** [comment]
There is no update on the ticket for more than a year.
If the issue is still reproducible for you - feel free to reopen the ticket and add some details that could help to reproduce the issue or create the new one.
