### ISSUE TITLE
Auto tests hangs up: NullPointerException: Cannot enter synchronized block because "this.lockObject" is null

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#29885]
### Description

Autotests sometimes hangs up on SQL generation from the data editor (in SQLite) and when switching between folders in metadata editor (in MariaDB). Can't reproduce it manually, but DBeaver freezes during tests execution.
Error log:
```
Exception in thread "org.eclipse.jface.text.reconciler.MonoReconciler" java.lang.NullPointerException: Cannot enter synchronized block because "this.lockObject" is null
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy$SpellingProblemCollector.endCollecting(SQLReconcilingStrategy.java:463)
	at org.eclipse.ui.texteditor.spelling.SpellingService.check(SpellingService.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:278)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLReconcilingStrategy.reconcile(SQLReconcilingStrategy.java:108)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
2024-05-04 01:50:10.913 - Dying because - Broken transport; encountered EOF
2024-05-04 01:50:10.914 - Disconnected - UNKNOWN
```

### DBeaver Version

24.0.4

### Steps to reproduce

1. Open data editor
2. select data
3. in the context menu select Generate SQL
DBeaver freeze here

or
1. open metadata editor for a table
2. switch between folders with the shortcut Ctrl+Shift+Alt+PgDown
DBeaver freeze here

**Comment by serge-rider** [comment]
Fixed in `devel`

**Comment by DariaMarkaryan** [comment]
Verified
