### ISSUE TITLE
How does DBeaver encode the data transferred via JDBC

### ISSUE THREAD

**Issue by nudles** [dbeaver/dbeaver#29926]
### Description

I am using DBeaver to connect ClickHouse.
When I tried to import a CSV file (UTF8 encoded), the insert statement (got from WireShark) is like 
```
/* ApplicationName=DBeaver 24.0.1 - Data transfer consumer */ INSERT INTO test.demo_sales (������,������,������������,������������,������������,������������,������,���������,���������,������,���������)
	VALUES ('2020-01-01',x'7d7102',x'534d44424a3138303030303130',x'7d71e8',x'9a28be',x'd13d9a283234356d6d',x'09e801',641.03,435.89,30,1076.92),('2020-01-01',x'64e802',x'534d44424a3138303030303134',x'64e8e8',x'89a0',x'09683936306776e6ed34',x'aee65f01',998.56,1462.98,120,2461.54),
```

I compared the insert statement for another database that works successfully. The difference is at the `VALUES(`  part, e.g., `x'7d7102',`.

I found that DBeaver would encode the data https://github.com/dbeaver/dbeaver/blob/9ce8e5b48bc80b19d658ef72cb0092956c87d205/plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumer.java#L376
But I do not know how is this encoding property set?
Is it based on some value like collation or charset returned from ClickHouse?
Could anyone help clarify it? What's the SQL used to retrieve the encoding from ClickHouse? Thank you!

### DBeaver Version

Community Edition 24.0.1

### Operating System

MacOS 14.0

### Database and driver

Database ClickHouse.
Driver: JDBC.

**Comment by serge-rider** [comment]
It looks like hex encoding of binary data. Most likely the query you see in the log is generated by the driver itself.

What is the problem with this query? Is there any error during data transfer?

**Comment by nudles** [comment]
@serge-rider  There is no error in data transfer.
But ClickHouse cannot parse the received data correctly and thus throws errors.
I guess DBeaver gets the encoding from ClickHouse, but ClickHouse returned an invalid encoding. 
if I know the SQL DBeaver used to get the encoding, then I can let ClickHouse return the correct encoding.

Here is the call stack from DBeaver
```
<!--StartFragment--></meta><style><!--br {mso-data-placement:same-cell;}--> td {white-space:nowrap;border:1px solid #dee0e3;font-size:10pt;font-style:normal;font-weight:normal;vertical-align:middle;word-break:normal;word-wrap:normal;}</style><byte-sheet-html-origin data-id="1715066935417" data-version="4" data-is-embed="false" data-grid-line-hidden="false" data-importRangeRawData-spreadSource="https://bytedance.sg.larkoffice.com/sheets/GbvOsXyxshEh2qtLwzElUmQBgee" data-importRangeRawData-range="Errors!E63:E63">
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [62] [HY000]: Code: 62, e.displayText() = DB::Exception: Syntaxerror: failed at position 30 ('<EF><BF><BD>') (line 1, col 30): <E6><97><A5><E6><9C><9F>,<E5><9F><8E><E5><B8><82>,<E5><8D><95><E6><8D><AE><E7><BC><96><E5><8F><B7>,<E9><97><A8><E5><BA><97><E5><90><8D><E7><A7><B0>,<E5><95><86><E5><93><81><E<E7><B1><BB><E5><88><AB>,<E5><95><86><E5><93><81><E5><90><8D><E7><A7><B0>,<E7><9C><81><E4><BB><BD>,<E6><88><90><E6><9C><AC><E9><A2><9D>,<E6><AF><88><A9><E9><A2><9D>,<E6><95><B0><E9><87><8F>,<E9><94><80><E5><94><AE><E9><A2><9D>)        VALUES ('2020-01-01',x'7d7102',x'534d44424a31383. Unrecognized token: '<EF><BF><BD>' SQLSTATE: 42000 (version 21.8.7.1)        at 
org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:155)        at 
org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:290)        at 
org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:212)        at 
org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:81)        at 
org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.lambda$0(DatabaseTransferConsumer.java:456)        at 
org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:191)        at 
org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:454)        at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:401)        at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:278)        at 
org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:161)        at 
org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)        at 
org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:119)        at 
org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:91)        at 
org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)        at 
org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
--


</byte-sheet-html-origin><!--EndFragment-->
```
