### ISSUE TITLE
DB metadata search throws java.lang.NullPointerException 

### ISSUE THREAD

**Issue by svinotavr** [dbeaver/dbeaver#2996]
Hi,

I keep getting java.lang.NullPointerException when searching for tables (CTRL-H -> DB Metadata) on DBeaver version 4.3.4. The error appears with any setting for name match (Starts with/Contains/Like) when I try searching in multiple schemas at once. The search works OK when looking inside one schema.  

Best regards,
Vlad

**Comment by serge-rider** [comment]
I can't reproduce this.
Please post error stacktrace (you can get it in Error Log view or in log files: https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by svinotavr** [comment]
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.core.jobs
Error
Mon Feb 19 13:02:40 EET 2018
An internal error occurred during: "%client%".

java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreStructureAssistant$1.resolveObject(PostgreStructureAssistant.java:169)
	at org.jkiss.dbeaver.ui.search.metadata.SearchMetadataQuery.run(SearchMetadataQuery.java:118)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:92)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by serge-rider** [comment]
Thanks for details
