### ISSUE TITLE
[PostgreSQL] 'Select login possible values' has encountered a problem. Error when editing data.

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3039]
When editing text data of a table where a column has a FK reference I get this error:

![dbeaver-error](https://user-images.githubusercontent.com/11840364/36641543-62a19176-1a31-11e8-874d-d9e844f65bef.png)

This is the minimum test case in order to reproduce this:

```
CREATE TABLE public.users (
	id serial NOT NULL,
	login varchar NOT NULL,
	password text NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT users_login_key UNIQUE (login)
)
WITH (
	OIDS=FALSE
) ;

CREATE TABLE public.user_has_permission (
	login varchar NOT NULL,
	permission text NOT NULL,
	CONSTRAINT user_has_permission_pk PRIMARY KEY (login, permission),
	CONSTRAINT user_has_permission_users_fk FOREIGN KEY (login) REFERENCES users(login) ON UPDATE CASCADE ON DELETE CASCADE
)
WITH (
	OIDS=FALSE
) ;

INSERT INTO users
(id, login, password)
VALUES(1, 'admin', '123');
INSERT INTO users
(id, login, password)
VALUES(2, 'admin2', '123');

INSERT INTO user_has_permission
(login, permission)
VALUES('admin2', 'ROLE_REPORT');
INSERT INTO user_has_permission
(login, permission)
VALUES('admin', 'ROLE_DELETE');
```

Then go to the user_has_permission table and try to edit the login column. When trying to change the value from admin to admin2 or vice versa I get this error after pressing Enter. I can save the data without problems but the error is worrying nevertheless.

**Comment by serge-rider** [comment]
Please attache error stacktrace from Error Log view (or log file: https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by lemon-juice** [comment]
```
!SESSION 2018-02-25 13:50:57.751 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2018-02-25 13:51:32.149
!MESSAGE org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
!STACK 0
java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderJob.run(ReferenceValueEditor.java:389)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.jkiss.dbeaver.model 4 0 2018-02-25 13:51:32.149
!MESSAGE org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
!STACK 0
java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderJob.run(ReferenceValueEditor.java:389)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.jkiss.dbeaver.model 4 0 2018-02-25 13:52:20.062
!MESSAGE org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
!STACK 0
java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderJob.run(ReferenceValueEditor.java:389)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.jkiss.dbeaver.model 4 0 2018-02-25 13:52:20.077
!MESSAGE org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
!STACK 0
java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderJob.run(ReferenceValueEditor.java:389)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```

**Comment by serge-rider** [comment]
Thanks for report

**Comment by lemon-juice** [comment]
:thumbsup:
