### ISSUE TITLE
NullPointerException after closing result set with auto refresh

### ISSUE THREAD

**Issue by rscs** [dbeaver/dbeaver#3048]
Bug related to #2050.

If I have auto refresh set on a result set and I close that tab without first stopping the auto refresh, I get a NullPointerException popup the next time the refresh would have run.

![npe-error](https://user-images.githubusercontent.com/7612149/36743548-88cc412e-1bb8-11e8-9280-dcdd4661ca76.png)

This does not happen when closing a "Sessions" tab with auto refresh; only when closing a normal table result set that has auto refresh.

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view or in log files: https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by rscs** [comment]
```
!ENTRY org.jkiss.dbeaver.model 4 0 2018-02-27 12:39:03.303
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.runtime.jobs.DataSourceJob.<init>(DataSourceJob.java:40)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobAbstract.<init>(ResultSetJobAbstract.java:33)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.<init>(ResultSetJobDataRead.java:52)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.runDataPump(ResultSetViewer.java:2637)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.refreshData(ResultSetViewer.java:2512)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$0(ResultSetViewer.java:206)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshJob.run(AutoRefreshJob.java:40)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by rscs** [comment]
Steps to reproduce:
- Perform a query on any table
- Set an auto refresh interval on that result set
- Close the result set tab without stopping the auto refresh

**Comment by serge-rider** [comment]
Thanks for testing it 👍

**Comment by rscs** [comment]
The NPE has gone away and it has been replaced with a new popup saying "Widget is disposed":

```!ENTRY org.jkiss.dbeaver.model 4 0 2018-03-01 23:25:46.057
!MESSAGE Widget is disposed
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Control.getShell(Control.java:1589)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.runDataPump(ResultSetViewer.java:2622)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.refreshData(ResultSetViewer.java:2512)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$0(ResultSetViewer.java:206)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshJob.run(AutoRefreshJob.java:42)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by serge-rider** [comment]
@rscs Yep, also fixed
