### ISSUE TITLE
cannot  generate mock data in postgresql db :java.lang.NullPointerException: 

### ISSUE THREAD

**Issue by pradeepkpc** [dbeaver/dbeaver#3065]
genrating mock data displays  :java.lang.NullPointerException: 

created a simple table in postgres

CREATE TABLE users
(
  id bigserial NOT NULL,
  employee_id integer NOT NULL,
  username character varying(50) NOT NULL,
  password character varying NOT NULL,
  active boolean DEFAULT true,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT unique_user UNIQUE (employee_id, username)
);

and tried to generate mock data
dbeaver displays

![mock_error](https://user-images.githubusercontent.com/36982872/36888027-b88a57b2-1e19-11e8-8da2-324a6b599b20.png)

2018-03-02 12:30:46.733 - Connected (postgres-jdbc-161e582b4d0-2f0e3f306c0481ba, PostgreSQL JDBC Driver [42.2.0.jre7])
2018-03-02 12:30:59.225 - Can't get column 'rolbypassrls': The column name rolbypassrls was not found in this ResultSet.
2018-03-02 12:37:49.233 - null
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:231)
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:1)
	at org.jkiss.dbeaver.ui.dialogs.tools.AbstractToolWizard.run(AbstractToolWizard.java:253)
	at org.jkiss.dbeaver.core.DBeaverUI$1.run(DBeaverUI.java:104)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-03-02 12:38:34.834 - null

**Comment by efradkin** [comment]
The fix will be in the next DBeaver version. @pradeepkpc Now, as a workaround, you have to manually specify Text generator "Max Length" parameter value.
