### ISSUE TITLE
Bug report: cannot show sql editor (F3)

### ISSUE THREAD

**Issue by sirber** [dbeaver/dbeaver#3095]
dbeaver: 5.0.0
OS: Windows 10

I right-click on the database in the left menu, show sql editor. dBeaver loose the focus and no window shows.

**Comment by sirber** [comment]
4.3.4 shows the same behavior.

**Comment by anodynos** [comment]
F3 doesn't work on my 4.3.5 on Kubuntu Linux 16.04 - but `Right click -> Read data in SQL console` works fine.

**Comment by sirber** [comment]
On Ubuntu 17.10 and dBeaver 5.0, the shortcut is CTEL+[ and it works. It also works from the menus.

**Comment by rmainseas** [comment]
I can't see the SQL editor either. If I right click on a table and click "Read data in SQL console" I get a grey/beige screen where the SQL editor should be

Like so:

 
![image](https://user-images.githubusercontent.com/50675045/64983368-57b5d200-d88e-11e9-9c6b-b66b2d2c8953.png)

**Comment by rmainseas** [comment]
I can type in the SQL editor. I just can't actually see what I'm writing...

![sql](https://user-images.githubusercontent.com/50675045/64984849-a9ac2700-d891-11e9-931f-3dbbded74355.gif)

Looking in my terminal, I see a few stack traces from GTK

    (DBeaver:27251): Gdk-CRITICAL **: The window 0x7fd781580ca0 already has a drawing context. You cannot call gdk_window_begin_draw_frame() without calling gdk_window_end_draw_frame() first.
    2019-09-16 14:52:28.922 - Event loop exception
    org.eclipse.swt.SWTError: No more handles
      at org.eclipse.swt.SWT.error(SWT.java:4725)
      at org.eclipse.swt.SWT.error(SWT.java:4614)
      at org.eclipse.swt.SWT.error(SWT.java:4585)
      at org.eclipse.swt.widgets.Widget.error(Widget.java:532)
      at org.eclipse.swt.widgets.Control.drawBackground(Control.java:235)
      at org.eclipse.swt.widgets.Control.windowProc(Control.java:6800)
      at org.eclipse.swt.widgets.Display.windowProc(Display.java:6132)
      at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
      at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4166)
      at org.eclipse.swt.widgets.Display.eventProc(Display.java:1429)
      at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
      at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1585)
      at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4661)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
      at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
      at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
      at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
      at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
      at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:246)
      at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
      at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
      at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
      at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by uslss** [comment]
is it still actual?

**Comment by sirber** [comment]
I'v been good for a while. Closed!

**Comment by rmainseas** [comment]
Just coming back here to add that it seems to be related to my locale. Is this now fixed @sirber ?

**Comment by sirber** [comment]
I don't know. YOu should open a new ticket for a new issue.
The original issue is long fixed since we are at 6.3.x now.
