### ISSUE TITLE
clicking on tables in db navigator results in ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3142]
happens in version 435 and 5

<pre>
2018-03-14 11:39:23.265 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [942] [42000]: ORA-00942: table or view does not exist

        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getObject(JDBCObjectCache.java:79)
        at org.jkiss.dbeaver.ext.oracle.model.OracleUtils.resolveLazyReference(OracleUtils.java:276)
        at org.jkiss.dbeaver.ext.oracle.model.OracleTablespace.resolveTablespaceReference(OracleTablespace.java:322)
        at org.jkiss.dbeaver.ext.oracle.model.OracleTablePhysical.getTablespace(OracleTablePhysical.java:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:235)
        at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:350)
        at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
        at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
        ... 16 more
Caused by: Error : 942, Position : 18, Sql = SELECT * FROM SYS.DBA_TABLESPACES ORDER BY TABLESPACE_NAME, OriginalSql = SELECT * FROM SYS.DBA_TABLESPACES ORDER BY TABLESPACE_NAME, Error Msg = ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
        ... 32 more
</pre>

**Comment by yanOnGithub** [comment]
Similar problem for SYS.DBA_TRIGGERS click I would like to view triggers. Can you plz use USER_TRIGGERS instead of DBA_TRIGGERS?

![20180320t142500](https://user-images.githubusercontent.com/25423046/37639036-ce626dba-2c4a-11e8-9d70-d78bc5c61244.png)

<pre>
org.jkiss.dbeaver.DBException: SQL Error [942] [42000]: ORA-00942: table or view does not exist

        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1513)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:486)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:409)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:200)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:574)
        at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:204)
        at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [942] [42000]: ORA-00942: table or view does not exist

        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:69)
        at org.jkiss.dbeaver.ext.oracle.model.OracleTableBase.getTriggers(OracleTableBase.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:801)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:782)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:862)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1485)
        ... 11 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
        at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
        ... 23 more
Caused by: Error : 942, Position : 18, Sql = SELECT *
FROM SYS.DBA_TRIGGERS WHERE TABLE_OWNER=:1  AND TABLE_NAME=:2
ORDER BY TRIGGER_NAME, OriginalSql = SELECT *
FROM SYS.DBA_TRIGGERS WHERE TABLE_OWNER=? AND TABLE_NAME=?
ORDER BY TRIGGER_NAME, Error Msg = ORA-00942: table or view does not exist
</pre>

**Comment by serge-rider** [comment]
DBeaver reads triggers from ALL_TRIGGERS view. It uses DBA_TRIGGERS only if you have DBA role.

**Comment by serge-rider** [comment]
However looks like we need to check whether DBA views are actually available before querying them.

**Comment by yanOnGithub** [comment]
I DO NOT have DBA role. The following SQL fails with ORA-00942: table or view does not exist

<pre>
select * from dba_role_privs where granted_role='DBA';
</pre>

**Comment by serge-rider** [comment]
DBeaver checks DBS role by executing
```sql
SELECT 'YES' FROM USER_ROLE_PRIVS WHERE GRANTED_ROLE='DBA'
```
