### ISSUE TITLE
Excel export issue

### ISSUE THREAD

**Issue by danieleangellotti** [dbeaver/dbeaver#3223]
Hi Serge,
after updating DBeaver to version 5.0.1 I can no longer extract datasets in Excel. I'm using DBeaver on Windows with PostgreSQL connection.
Below is the stacktrace of the error from the `.dbeaver4/.metadata/.log` file:

```
!ENTRY org.jkiss.dbeaver.model 4 0 2018-03-27 09:27:28.194
!MESSAGE Error while exporting table row
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Error while exporting table row
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:819)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1981)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:130)
	at org.jkiss.dbeaver.data.office.handlers.OpenSpreadsheetHandler$1.run(OpenSpreadsheetHandler.java:98)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Error while exporting table row
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1513)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:384)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:814)
	... 5 more
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Error while exporting table row
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:159)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:459)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:386)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1485)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.apache.poi.ss.util.SheetUtil.getCellWidth(SheetUtil.java:153)
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.updateColumnWidth(AutoSizeColumnTracker.java:367)
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.updateColumnWidths(AutoSizeColumnTracker.java:333)
	at org.apache.poi.xssf.streaming.SXSSFSheet.flushOneRow(SXSSFSheet.java:1905)
	at org.apache.poi.xssf.streaming.SXSSFSheet.flushRows(SXSSFSheet.java:1881)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:145)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:62)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.exportRow(DataExporterXLSX.java:443)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:155)
	... 11 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-03-27 09:27:28.200
!MESSAGE Error while exporting table row
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2018-03-27 09:27:28.200
!MESSAGE Error while exporting table row
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2018-03-27 09:27:28.200
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.apache.poi.ss.util.SheetUtil.getCellWidth(SheetUtil.java:153)
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.updateColumnWidth(AutoSizeColumnTracker.java:367)
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.updateColumnWidths(AutoSizeColumnTracker.java:333)
	at org.apache.poi.xssf.streaming.SXSSFSheet.flushOneRow(SXSSFSheet.java:1905)
	at org.apache.poi.xssf.streaming.SXSSFSheet.flushRows(SXSSFSheet.java:1881)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:145)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:62)
	at org.jkiss.dbeaver.data.office.export.DataExporterXLSX.exportRow(DataExporterXLSX.java:443)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:155)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:721)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:459)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:386)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1485)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:384)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:814)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1981)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:130)
	at org.jkiss.dbeaver.data.office.handlers.OpenSpreadsheetHandler$1.run(OpenSpreadsheetHandler.java:98)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

Thank you!

**Comment by serge-rider** [comment]
It is a known issue and it was already fixed.
If you use EE then you can download Early Access version with this fix (http://dbeaver.com/files/ea), CE 5.0.2 will be released on Monday.
