### ISSUE TITLE
Trying to view a Trigger in MySQL 5.0

### ISSUE THREAD

**Issue by temporaryaccount** [dbeaver/dbeaver#3250]
I'm getting an error when trying to view a trigger:

/* ERROR WHILE READING SOURCE:

SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER mydb.records_before_insert' at line 1
*/

Here are the logs:

    !ENTRY org.jkiss.dbeaver.model 4 0 2018-04-03 11:59:56.395
    !MESSAGE SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
    !STACK 0
    org.jkiss.dbeaver.DBException: SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1517)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:384)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:198)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
    Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:442)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:386)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1489)
        ... 4 more
    Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
        ... 7 more
    !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-04-03 11:59:56.395
    !MESSAGE SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
    !SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2018-04-03 11:59:56.395
    !MESSAGE You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
    !STACK 0
    com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records_before_insert' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:442)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:386)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1489)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:384)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:198)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by serge-rider** [comment]
Can't reproduce.
DBeaver executes following query to read trigger body:
```sql
SHOW CREATE TRIGGER trigger_schema.trigger_name
```
- Does it work in your case?
- What MySQL server version do you use?

**Comment by temporaryaccount** [comment]
I have a `records` table with a `records_before_insert trigger`.

This query:

    use prod_db;

    SHOW CREATE TRIGGER records.records_before_insert;

Results to this error message:


    SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records.records_before_insert' at line 1
    SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records.records_before_insert' at line 1
      SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records.records_before_insert' at line 1
        You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records.records_before_insert' at line 1
        You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER records.records_before_insert' at line 1

MySQL version is 5.0.95 from an old RHEL 5 server. I agree that this is an old and rarely used MySQL version and maybe this is a non-issue. Anyway, if there is an easy workaround there to view the triggers on those versions of MySQL maybe we could implement it. Thank you.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
