### ISSUE TITLE
Java error on launch: Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by elramus** [dbeaver/dbeaver#3253]
Been using Dbeaver extensively for several months and loving it, then had to wipe my machine clean and start over for reasons unrelated. After reinstalling Dbeaver, I now face the following error: 

`
See the log file
/Applications/Dbeaver.app/Contents/Eclipse/configuration/XXXXXXXXXX.log
`

Opening said log file tells me:
```
!SESSION Tue Apr 03 12:02:52 GMT-06:00 2018 ------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2018-04-03 12:02:52.828
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/adaptor/EclipseStarter : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:650)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

I have installed legacy Java from here: https://support.apple.com/kb/DL1572, as suggested during Dbeaver install. 
Also installed the latest version of Java from here just in case: https://java.com/en/download/
Working on a 2017 MacBook Pro w/ High Sierra 10.13.4.

Any thoughts? Thanks!

**Comment by serge-rider** [comment]
You need to install Java 8 or Java 9. Best option is to use MacOS PKG installer (which is already bundled with Java).

**Comment by elramus** [comment]
Awesome, thanks @serge-rider! I had also downloaded the JRE separately before too, and it didn't seem to help. But using your PKG installer solved it. Thanks!

**Comment by joostfontein** [comment]
Same problem here! What is meant by "using PKG installer". I downloaded JRE and just double clicked on .dmg and then on the .pkg ... Still got same issue..

**Comment by elramus** [comment]
Instead of downloading and installing java from java's website, go to Dbeaver's download page and grab the PKG installer + JRE from there instead.

https://dbeaver.jkiss.org/download/

**Comment by joostfontein** [comment]
Works! Thanks!

**Comment by michaellenahan** [comment]
Alternatively, ```brew cask install java``` will provide an up-to-date java version on mac.
