### ISSUE TITLE
[Eclipse] Errors when creating new column

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#32966]
### Description

STR

1. Install DBeaver IDE plug-in 
2. Open Error panel
3. Create new column for table via ui
Actual result - see errors in log

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:598)
	at org.eclipse.swt.widgets.MenuItem.setText(MenuItem.java:848)
	at org.eclipse.ui.menus.CommandContributionItem.updateMenuItem(CommandContributionItem.java:525)
	at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:486)
	at org.eclipse.ui.menus.CommandContributionItem.setText(CommandContributionItem.java:897)
	at org.eclipse.ui.menus.CommandContributionItem$1.setText(CommandContributionItem.java:702)
	at org.jkiss.dbeaver.ui.editors.entity.handlers.UndoChangesHandler.updateElement(UndoChangesHandler.java:62)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:433)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:124)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:43)
	at org.eclipse.ui.internal.commands.CommandService$1.run(CommandService.java:261)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.commands.CommandService.refreshElements(CommandService.java:265)
	at org.eclipse.ui.internal.commands.SlaveCommandService.refreshElements(SlaveCommandService.java:215)
	at org.jkiss.dbeaver.ui.editors.SimpleCommandContext.refreshCommandState(SimpleCommandContext.java:39)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.addCommand(AbstractCommandContext.java:389)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:116)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:336)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

https://github.com/dbeaver/dbeaver/assets/84867187/38984c98-0d3d-49cb-a5f6-6b3d5fb745ba

### DBeaver Version

24.0.5 eclipse extension

### Operating System

mac M1 Sonoma

**Comment by MashaKorax** [comment]
verified
