### ISSUE TITLE
Sql Dump error 

### ISSUE THREAD

**Issue by sequencerr** [dbeaver/dbeaver#33277]
### Description

long await with no response when dumping over ssh. I had to refresh connection and it fixed the issue. but error when I stop task is confusing 
```
D:\Programs\MySQL\mariadb-11.3.2-winx64\bin\mysqldump.exe --skip-lock-tables --routines --skip-add-drop-table --disable-keys --extended-insert -u root --host=127.0.0.1 --port=23311 dbname
Task 'MySQL dump' started at Tue May 21 17:23:09 CEST 2024
2024-05-21 17:38:25.180 - IO error: Process failed (exit code = 1). See error log.
2024-05-21 17:38:25.180 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Task 'MySQL dump' finished at Tue May 21 17:38:25 CEST 2024
```

### DBeaver Version

CE 24.0.1

### Operating System

win 10

### Database and driver

mariadb

**Comment by LonwoLonwo** [comment]
Hello @sequencerr 

This error code is from the backup tool you used. It can be anything, and we do not have more information about the problem. Only that native tool returns to us.

**Comment by sequencerr** [comment]
Yeah, I see.
I noticed that dumping is much faster done with
ssh into server and running dump binary (kinda instantaneous 100mb)
and scp from host machine is taking longest.

would great to see in the dbeaver dialog window that it actually downloading (now it's just incrementing bytes an idk what it is doing overall)
