### ISSUE TITLE
Eclipse Active Catalog/Schema width is short for databases with long name

### ISSUE THREAD

**Issue by mmrd2007** [dbeaver/dbeaver#3376]
please increase the width of   Active Catalog/Schema to display the database name completely

![screenshot_20180424_153306](https://user-images.githubusercontent.com/9788125/39190413-d838c352-47d4-11e8-8e33-be64d4a1a04c.png)

**Comment by serge-rider** [comment]
Do you have any clue how to make it better? Resizing this control isn't the best solution (this will re-layout main toolbar one every connection switch).

I can add tooltip. What else?

**Comment by maffe** [comment]
I have the same problem. In my case the most important information is at the end.
![grafik](https://user-images.githubusercontent.com/515302/48132533-3fe7e780-e294-11e8-8aad-e5b72de757e2.png)

I think the most intuitive way for the user is being able to resize using the mouse:
![grafik](https://user-images.githubusercontent.com/515302/48132955-707c5100-e295-11e8-966c-9c5276d81006.png)

**Comment by p91paul** [comment]
There is an option somewhere in preferences that lets you set this, you have to write the number of pixel instead of mouse resize, but it works!

**Comment by maffe** [comment]
> There is an option somewhere in preferences that lets you set this, you have to write the number of pixel instead of mouse resize, but it works!

Thank you. It’s quite hard to find—filtering the options for toolbar, catalog, schema, selector or width does not show it. The path is Window → Preferences → Database → Editors → Schema selector width.

I still think resizing using the mouse would be much easier (also the preferences window could be slightly less overwhelming with the width settings removed).

Not sure if this is related, but in my case after changing the setting DBeaver didn’t start anymore. `%userprofile%\.dbeaver4\.metadata\.log` shows
```
!SESSION 2018-11-08 12:09:35.898 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui.workbench 4 2 2018-11-08 12:09:40.060
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.getLastMigration(MigrationSupport.java:236)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.baseChangedSinceLastPresentationOfWizard(MigrationSupport.java:197)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.performMigration(MigrationSupport.java:77)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.earlyStartup(AutomaticUpdateScheduler.java:78)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2714)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2018-11-08 12:09:40.060
!MESSAGE Während "Workbench early startup" ist ein interner Fehler aufgetreten.
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:350)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:270)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:772)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:72)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:78)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2714)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I had to delete `%userprofile%\.dbeaver4\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi` to make DBeaver start again.
