### ISSUE TITLE
[PostgresQL] Hyphen in the database name

### ISSUE THREAD

**Issue by burningalchemist** [dbeaver/dbeaver#3391]
It is pretty similar to #2494 .

When I am trying to set a schema as an active object (Ctrl+Shift+A) in database with hyphen(-) in the name, I get the following error:

```
Error setting search path
  ERROR: syntax error at or near "-"
  Position: 44
  ERROR: syntax error at or near "-"
  Position: 44
```

**Reproduce steps:**
1. Create a database named "hyphen-test";
2. Create a schema named "testschema";
3. Create a table named "testtable" in that schema with some columns;
4. Try to perform "Set Active Object" operation on the created schema (by default, public schema is active).

DBeaver: 5.0.3
OS: Linux, Windows
PostgresQL: 10.3

* * *
- Just to mention it, in psql client to avoid errors with hyphen-like names I have to wrap it with double quotes.

**Comment by burningalchemist** [comment]
Sure thing. Here is the log:

```2018-04-28 15:10:23.877 - Connected (postgres-jdbc-163025635e4-28e92474d7bd057, PostgreSQL Native Driver [PostgreSQL 9.4.1212.jre7])
2018-04-28 15:10:29.589 - null
org.jkiss.dbeaver.model.exec.DBCException: Error setting search path
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.setSearchPath(PostgreDatabase.java:464)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.setDefaultObject(PostgreDatabase.java:426)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerSetActiveObject$1.run(NavigatorHandlerSetActiveObject.java:53)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:60)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "-"
  Position: 33
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:259)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeSQL(JDBCUtils.java:576)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.setSearchPath(PostgreDatabase.java:462)
	... 5 more```

**Comment by serge-rider** [comment]
Thanks for details. 
Now I can reproduce that (it fails if original default schema has hyphen in the name).
