### ISSUE TITLE
java.lang.IndexOutOfBoundsException when handling complex structures in Clickhouse

### ISSUE THREAD

**Issue by italodamato** [dbeaver/dbeaver#34283]
### Description

Not sure what's happening here but if I get a `java.lang.IndexOutOfBoundsException` error if I create a table where the keys of the named tuple doesn't contain any numbers. Everything renders correctly if I add a number to any tuple value name.

### DBeaver Version

Community Edition 24.1.0.202406021658 (also tested on enterprise)

### Operating System

macOS Sonoma 14.5 

### Database and driver

https://github.com/ClickHouse/clickhouse-java/releases/tag/v0.5.0

### Steps to reproduce

```sql
CREATE TABLE default.test
(
    `id` String,
    `column1` Array(Tuple(key String, val Map(String, Float64)))
)
ENGINE = MergeTree
ORDER BY (id);
INSERT INTO default.test
VALUES
	('id', array(tuple('aaa', map('key1', 1, 'key2', 2)), tuple('bbb', map('key1', 1, 'key2', 2))))
;
SELECT * FROM default.test;
```
This returns the following error in the column1 cells:
```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.makeValue(ClickhouseTypeParser.java:94)
	at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.makeValue(ClickhouseTypeParser.java:94)
	at org.jkiss.dbeaver.ext.clickhouse.ClickhouseTypeParser.makeValue(ClickhouseTypeParser.java:67)
	at org.jkiss.dbeaver.ext.clickhouse.model.data.ClickhouseStructValueHandler.getValueFromObject(ClickhouseStructValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:448)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:428)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.fetchColumnValue(JDBCArrayValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:126)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:881)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:665)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:506)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:525)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:977)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4155)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
<img width="1095" alt="image" src="https://github.com/dbeaver/dbeaver/assets/45588475/40d59c19-ec0c-4dd2-ba11-28e82d25f361">

This works correctly instead (renamed key to key1):
```sql
CREATE TABLE default.test
(
    `id` String,
    `column1` Array(Tuple(key1 String, val Map(String, Float64)))
)
ENGINE = MergeTree
ORDER BY (id);
INSERT INTO default.test
VALUES
	('id', array(tuple('aaa', map('key1', 1, 'key2', 2)), tuple('bbb', map('key1', 1, 'key2', 2))))
;
SELECT * FROM default.test;
```
<img width="537" alt="image" src="https://github.com/dbeaver/dbeaver/assets/45588475/4d46a184-714e-4766-afcd-4a788abdc24a">

**Comment by ShadelessFox** [comment]
Thanks for the bug report

**Comment by MashaKorax** [comment]
Hello @italodamato, Could you please clarify your server and driver version?

**Comment by italodamato** [comment]
> Hello @italodamato, Could you please clarify your server and driver version?

I'm using the latest version of ClickHouse v24.5.1.1763. I've specified the driver and DBeaver version in my post.

**Comment by ShadelessFox** [comment]
I was able to reproduce the issue against ClickHouse v24.5.
