### ISSUE TITLE
Can't setup light theme, Ubuntu Mint

### ISSUE THREAD

**Issue by AlexanderMakarov** [dbeaver/dbeaver#34311]
### Description

Can't setup good looking theme.

Tried to customize fonts but too many of them to setup separately.

![image](https://github.com/dbeaver/dbeaver/assets/2630978/ca424d56-9907-4eef-91a7-08c38b81fe03)

with all settings reset-ed to defaults and after DBeaver restart.

![image](https://github.com/dbeaver/dbeaver/assets/2630978/63671d38-b3aa-433e-a9e5-4ff9a95332ed)

----

Literally can't choose white font background - see how it looks with relevant Preferences page (even after restart):

![image](https://github.com/dbeaver/dbeaver/assets/2630978/e3bd3454-1eff-4b34-b5cc-83eb0b8a95aa)

Therefore was able to configure DBeaver only with Dark theme and with "Color and font scheme"=default, other configurations make fonts unreadable.

### DBeaver Version

Version 24.1.0.202406021658

### Operating System

Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy; Xfce 4.18.1; Gtk 3.24.33 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 dm: LightDM 1.30.0

### Database and driver

Any

### Steps to reproduce

Looks like applies only on OS Linux Mint with Lxde windows environment.

1. Go to Preferences, "User interface -> Appearance".
2. Choose Theme=Light. Press "Apply", restart DBeaver as it wants.
3. Check "SQL Editor" (main content) and "Connections" view (left side panel) font background color.

Expected: white or somehow light.
Actual: dark (same as with Theme=Dark).

**Comment by E1izabeth** [comment]
Is it the fist DBeaver installation or it happened after version update?
Have you tried resetting UI settings https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings?

**Comment by AlexanderMakarov** [comment]
1. *Is it the fist DBeaver installation or it happened after version update?* - it was updated several times.
2. *Have you tried resetting UI settings https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings?* - thanks, hadn't known about this way, but it didn't help :disappointed: 

![image](https://github.com/dbeaver/dbeaver/assets/2630978/5fdbeecb-6300-43a6-b322-fd0da6903ccb)

**Comment by E1izabeth** [comment]
Are Light and Classic themes OK? Does it reproducible only with Dark theme?

**Comment by E1izabeth** [comment]
Could you provide the log files? You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by E1izabeth** [comment]
Another issue about this bug #34328
All themes are affected.

**Comment by AlexanderMakarov** [comment]
@E1izabeth 
- *Are Light and Classic themes OK? Does it reproducible only with Dark theme?* - No, exactly Light and Classic don't work. I.e. (all after restarts):
### Dark - here it looks OK.
![image](https://github.com/dbeaver/dbeaver/assets/2630978/a4813247-d8cc-454b-97c4-f849e9d68794)

### Light - not "light" at the background and therefore fonts are barely readable.
![image](https://github.com/dbeaver/dbeaver/assets/2630978/d22df013-48f2-493c-8a07-b9094052c459)

### Classic - it renders as "Dark" but with font colors from the "Light".
![image](https://github.com/dbeaver/dbeaver/assets/2630978/eef48df6-89d8-42a5-ac3a-b4891ea41186)

While taking these screenshots have noticed that if choose "Color and font theme=Reduced Palette" then before "Restart DBeaver" action it looks really as "reduced" but after restart goes back to "full" with a lot of red fonts (on my SQL script).

- *Could you provide the log files?* -
[log.log](https://github.com/user-attachments/files/15799160/log.log), 
[dbeaver-debug.log](https://github.com/user-attachments/files/15799185/dbeaver-debug.log) (in the last one replaced sensitive information with "SENSITIVE" placeholder).

**Comment by E1izabeth** [comment]
Thank you.
Error from logs:
```
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.setForeground(GC.java:3305)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer.drawText(StatisticsNavigatorNodeRenderer.java:276)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer.renderDataSourceHostName(StatisticsNavigatorNodeRenderer.java:270)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer.paintNodeDetails(StatisticsNavigatorNodeRenderer.java:128)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.onPaintItem(DatabaseNavigatorTree.java:272)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.lambda$1(DatabaseNavigatorTree.java:179)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
	at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:3401)
	at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:3139)
	at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1716)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:58)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:444)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:442)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:464)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)

```

**Comment by E1izabeth** [comment]
Could you try uninstalling DBeaver, deleting the folder, where it was installed, and deleting `$XDG_DATA_HOME/DBeaverData`? And then installing Early Access version from here https://dbeaver.io/files/ea/?

**Comment by AlexanderMakarov** [comment]
> Could you try uninstalling DBeaver, deleting the folder, where it was installed, and deleting `$XDG_DATA_HOME/DBeaverData`? And then installing Early Access version from here https://dbeaver.io/files/ea/?

No, sorry, I need in my setup on the daily basis and can't switch to unstable version.

**Comment by E1izabeth** [comment]
OK
For now, we can't reproduce the issue. We'll keep investigating

**Comment by E1izabeth** [comment]
Could you try installing Early Access version from here https://dbeaver.io/files/ea/ without uninstalling the previous version? You won't loose any of your configuration - the process will be the same as when updating the version.
Another person with the same issue confirmed that it helps.

**Comment by AlexanderMakarov** [comment]
Downloaded [dbeaver-ce_24.1.1_amd64.deb](https://dbeaver.io/files/ea/dbeaver-ce_24.1.1_amd64.deb), installed it in my Linux Mint without any other actions. **Issue is still here** - Theme=Light renders as black.

After installation haven't noted changes except of new "24.1.1-202406132322" folder appeared in "/home/SENSITIVE/.local/share/DBeaverData/install-data/org.jkiss.dbeaver.product/". In logs see only
```
SESSION 2024-06-14 14:14:20.260 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/SENSITIVE/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2024-06-14 14:14:25.497
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2024-06-14 14:14:51.901 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/SENSITIVE/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2024-06-14 14:14:56.056
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2024-06-14 14:15:15.997 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/SENSITIVE/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2024-06-14 14:15:20.887
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
!SESSION 2024-06-14 14:19:01.296 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/SENSITIVE/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui 2 2 2024-06-14 14:19:05.982
!MESSAGE Invalid preference category path: org.eclipse.debug.ui.ConsolePreferencePage (bundle: org.eclipse.ui.console, page: org.eclipse.ui.internal.console.ansi.preferences.AnsiConsolePreferencePage)
```

**Comment by Destrolaric** [comment]
Hi, for people experiencing the issue, DBeaver can't properly render if the DBeaver theme is significantly different from the system one, to avoid the issue similar color scheme should be used.

**Comment by AlexanderMakarov** [comment]
> Hi, for people experiencing the issue, DBeaver can't properly render if the DBeaver theme is significantly different from the system one, to avoid the issue similar color scheme should be used.

@Destrolaric could you please explain - how to check this difference from my side? I am using default DBeaver color scheme. In my OS "Settings -> Appearance -> Style" is chosen "Mint-Y-Dark-Teal" and I can't edit or even see it.

**Comment by AlexanderMakarov** [comment]
FYI: corrected bug description with
>Therefore was able to configure DBeaver only with Dark theme and with "Color and font scheme"=default, other configurations make fonts unreadable.

**Comment by Destrolaric** [comment]
@AlexanderMakarov Hi, this is a long-running issue with Eclipse theming on Linux. If the theme on the Linux desktop differs from DBeaver theme in color palette this leads to the parts of app being not properly colored. 
There are two ways to avoid the issue:
1. Use the same type of theme in Linux and DBeaver. 
2. Passing GTK_THEME launch argument to DBeaver 
https://askubuntu.com/questions/1149986/eclipse-looks-terrible-with-linux-dark-theme
https://github.com/eclipse-platform/eclipse.platform.ui/issues/629

**Comment by AlexanderMakarov** [comment]
@Destrolaric thank you for the solution - `GTK_THEME=Adwaita dbeaver` helped me:

![image](https://github.com/dbeaver/dbeaver/assets/2630978/1626b844-2b6f-4895-ae14-493c8873c701)

Issue may be closed :bow:

**Comment by nkilm** [comment]
Thank you all! `GTK_THEME=Adwaita dbeaver` worked for me!

![Image](https://github.com/user-attachments/assets/4719b21a-5f4b-4faf-a8b3-6f25a0201da1)

In my case, the `.desktop` file name was different as you can see in above screenshot. I guess `dbeaver-ce` stands for community edition.

**Comment by jacekgajek** [comment]
I had to find this page and use the same workaround to make the light theme work. How come this issues is closed? I'm on KDE/Wayland.

```
Operating System: Fedora Linux 42
KDE Plasma Version: 6.5.2
KDE Frameworks Version: 6.20.0
Qt Version: 6.9.3
Kernel Version: 6.17.7-200.fc42.x86_64 (64-bit)
Graphics Platform: Wayland
```
