### ISSUE TITLE
When we cancel a long query ... DBeaver looks frozen and never comeback.  We need to kill the process.

### ISSUE THREAD

**Issue by RickTrder** [dbeaver/dbeaver#34316]
### Description

When we cancel a long query ... DBeaver looks frozen and never comeback.  We need to kill the process.

And we lost unsaved works by the same.

### DBeaver Version

 23.3.0.202312201943

### Operating System

Windows 10 Entreprise 22H2

### Database and driver

SnowFlake JDBC 3.13.30

### Steps to reproduce

Start query that could return 1M of lines ... and press "Cancel" during the launch of query

**Comment by E1izabeth** [comment]
Please try latest DBeaver version 24.1.0

**Comment by RamonCar66** [comment]
Hello,
I've experienced the same on version 24.1.1, when working with Oracle databases. I know Oracle has limitations on query cancellation, depending on the stage of the query execution. However, the client should always be able to drop the connection and free the resources associated, and return the control to the user interface.

In the first screenshot there is a query that is taking too long.

![image](https://github.com/dbeaver/dbeaver/assets/65061885/08b2a3a1-8046-4b3a-a172-5021ee3efedc)

In the second screenshot, I've pressed "Cancel", the cancel operation has timedout on the server (this is not due to dbEaver, rather to Oracle). And the background task associated is still running, and there is no way to remove it. In addition CPU used by dbEaver rise up to 25% (normally it is between 5-10 %)

![image](https://github.com/dbeaver/dbeaver/assets/65061885/c5490715-c8fc-4524-b9e8-7f52c3cf4e9a)

And this is the stack trace that appears when "Details" button is pressed on the previous screen:

```
org.jkiss.dbeaver.model.exec.DBCException: Cancel operation timed out
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead$PumpVisualizer.runInUIThread(ResultSetJobDataRead.java:185)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4058)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)

```

**Comment by E1izabeth** [comment]
Hi, @RamonCar66 
Thank you for providing more information regarding this issue.

**Comment by E1izabeth** [comment]
I can't reproduce the issue on 24.1.1. Please try the latest version.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by RamonCar66** [comment]
Hello,
Behaviour keeps happening version 24.1.3. For me is / maybe OK that Oracle does not cancel the query.
However it seems that dbEaver gets frozen when trying to close the JDBC connection. IMO, dbEaver should be able to create a new JDBC connection and launch the query again on it.

![image](https://github.com/user-attachments/assets/c1386958-0ff7-493b-b772-febcc656fefb)


org.jkiss.dbeaver.model.exec.DBCException: Cancel operation timed out
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead$PumpVisualizer.runInUIThread(ResultSetJobDataRead.java:190)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4058)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)

**Comment by RamonCar66** [comment]
In addition, after this error happens, Background tasks seems active:

![image](https://github.com/user-attachments/assets/691526b9-2a10-403a-9515-2acf06fe127f)

and uses CPU higher than normal:

![image](https://github.com/user-attachments/assets/0b11fbc0-3e7e-4789-9adf-490bb53db7d0)

Invalidating connections does not solve the problem, the only way is to restart dbEaver.

However, if you know some actions that could workaround the problem, I would appreciate.

Thanks in advance for your help

**Comment by E1izabeth** [comment]
Thank you for update, @RamonCar66 
As a workaround, you can try turning on the following setting `Connection configuration->Metadata->Do not read tables information in SQL and data editors`. Does it help?

![image](https://github.com/user-attachments/assets/990bd416-6960-43f8-b17a-13470928d140)

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide the answer to the question.

**Comment by RamonCar66** [comment]
Hello, I've been running with this issue for long time.
Today I discovered a parameter on Oracle driver named **oracle.net.disableOob**, keeping it to **false** (which is default) gives more chance to effectively cancel the long running query on server side. Indeed, the Cancel operations have always worked for me since I changed it to false,

You can find that parameter on the "Driver Properties" in Connection Settings:

<img width="751" height="125" alt="Image" src="https://github.com/user-attachments/assets/c2fbfaad-25f9-47e2-8d6a-3f738dcb99d8" />

Honestly, I don't know why it was to true in my installation, probably it was like that when I received the connection profiles from a colleague.

Just commenting it here for the case is helps to somebody.
Kind regards
