### ISSUE TITLE
Connection reset error when connecting to PostgreSQL database

### ISSUE THREAD

**Issue by aobregonmx** [dbeaver/dbeaver#34342]
### Description

After entering the username, password, server address and database name, I get a "**connection reset**" error when I try to connect to my PostgreSQL database. This is the complete error trace
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-06-12 20:46:25.444
!MESSAGE SSL error: Connection reset
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-06-12 20:46:25.444
!MESSAGE Connection reset
!STACK 0
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:43)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:625)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:195)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
	at org.postgresql.Driver.makeConnection(Driver.java:446)
	at org.postgresql.Driver.access$100(Driver.java:63)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:355)
	at java.base/java.lang.Thread.run(Unknown Source)
```

<img width="1194" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49104974/23545d32-9a64-4631-9d23-72f36625e320">

### DBeaver Version

Version 24.0.5.202405191503

### Operating System

macOS Sonoma Version 14.2.1 

### Database and driver

1. PostgreSQL 12.18 (Ubuntu 12.18-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit"

### Steps to reproduce

1. I fill in the data of _Host_, _Database_, Username, Password
2. I try out, click on button Test Connection
3. I get this message Connection reset and details : 
```
SSL error: Connection reset
  Connection reset
  Connection reset
```

### Additional context

Share Session Data
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_MX
Framework arguments:  -keyring /Users/xxxxxx/.eclipse_keyring -eclipse.keyring /Users/xxxxxx/Library/DBeaverData/secure/secure_storage
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/xxxxxx/.eclipse_keyring
```

**Comment by LonwoLonwo** [comment]
Hello @aobregonmx 

`at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:625)`

Did you configure your SSL properties? Or, maybe, you accidentally checked the "enable SSL' setting?

**Comment by aobregonmx** [comment]
`sslmode` property in the configuration was without value, I assigned it to **false** and the **connection was possible without any problems**. 

Thank you very much for the support and an apology in advance, the solution was simple but sometimes so much time trying different ways blinds you.

Share configuration image
<img width="759" alt="image" src="https://github.com/dbeaver/dbeaver/assets/49104974/66a0d92f-bdd1-473d-849d-1b7380d85974">
