### ISSUE TITLE
Error with MariaDB (No enum constant org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType.PACKAGE)

### ISSUE THREAD

**Issue by MeboGit** [dbeaver/dbeaver#3435]
#Hi,

I'm getting error trying to open package in MariaDB:

set sql_mode = 'oracle'

CREATE OR REPLACE PACKAGE test.employee_tools AS
  FUNCTION getSalary(eid INT) RETURN DECIMAL(10,2);
  PROCEDURE raiseSalary(eid INT, amount DECIMAL(10,2));
  PROCEDURE raiseSalaryStd(eid INT);
  PROCEDURE hire(ename TEXT, esalary DECIMAL(10,2));
END;

When making a refresh in Database Navigator:
Can't read procedures
  Can't read procedures
    No enum constant org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType.PACKAGE
    No enum constant org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType.PACKAGE

Since MariaDB Oracle Packages is a very interesting feature it would be great if DBeaver could handle those. 

Kind Regards

Michael

**Comment by serge-rider** [comment]
Definitely a bug but I can't reproduce it.

Could you post this error stacktrace (it is in Error Log view) or error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by MeboGit** [comment]
Hi,

below you find the error log. I've seen that I work with MariaDB 10.3.6 and processing oracle-style-packages seams to be a new feature in this release. Anyhow the possibility working with oracle-style-packages outside Oracle is very interesting so it would be great if I could edit those within DBeaver.

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed May 09 01:42:33 CEST 2018
Can't read procedures

org.jkiss.dbeaver.DBException: Can't read procedures
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1545)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:406)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:575)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Can't read procedures
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:812)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:779)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:859)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1517)
	... 11 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType.PACKAGE
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.jkiss.dbeaver.model.struct.rdb.DBSProcedureType.valueOf(DBSProcedureType.java:1)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.loadInfo(MySQLProcedure.java:77)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.<init>(MySQLProcedure.java:69)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.fetchObject(MySQLCatalog.java:614)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.fetchObject(MySQLCatalog.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:69)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getProcedures(MySQLCatalog.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:798)
	... 15 more

Regards

Michael

**Comment by serge-rider** [comment]
Thanks for detail

**Comment by serge-rider** [comment]
We'll add MariaDB packages support in the next version.
