### ISSUE TITLE
Cannot invoke "org.eclipse.swt.widgets.Display.dispose()"

### ISSUE THREAD

**Issue by CarlosLosTopografos** [dbeaver/dbeaver#34436]
### Description

After installing newest version of dbeaver I get the following message. Installed on Windows Server for all users. Setup ran successfully.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.dispose()" because "this.display" is null
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:327)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
```

### DBeaver Version

Community Edition 24.1.1

### Operating System

Windows Server 2012 R2 Standardr

### Database and driver

PostgreSQL 13

### Steps to reproduce

Just starting the dbeaver

**Comment by E1izabeth** [comment]
Does the application works for you or run failed?

**Comment by CarlosLosTopografos** [comment]
It doesnt run at all. When starting I get an error message "please look at the logfile" and then the dbeaver is closed. The text above is what ist written into the logfile.

I just reinstalled the old 24.0.1 that i used before from the archive and the old version runs fine again.

**Comment by E1izabeth** [comment]
DBeaver don't support Windows Server 2012 anymore. We updated system requirements here https://dbeaver.io/download/
Also looks similar to #34034, so I'll close it as a duplicate.

**Comment by Pymancer** [comment]
> DBeaver don't support Windows Server 2012 anymore. We updated system requirements here https://dbeaver.io/download/ Also looks similar to #34034, so I'll close it as a duplicate.

Dbeaver snap version doesn't start on Ubuntu 24.04 with same error, it has nothing to do with Windows Server 2012

```sh
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/py/snap/dbeaver-ce/309/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2024-06-25 16:54:48.571
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.dispose()" because "this.display" is null
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:327)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
        at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
        at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
        at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)
```

**Comment by E1izabeth** [comment]
Please provide log files. This one error doesn't say a lot. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Pymancer** [comment]
That was entry form the log file (./snap/dbeaver-ce/309/.local/share/DBeaverData/workspace6/.metadata/.log) and it is the same every launch after the last update or even reinstall. 
This is from ./snap/dbeaver-ce/309/.local/share/DBeaverData/workspace6/.metadata/dbeaver-debug.log (slightly mangled):
```sh
2024-06-25 17:25:09.436 - DBeaver 24.1.1.202406231636 is starting
2024-06-25 17:25:09.437 - OS: Linux 6.8.0-35-generic (amd64)
2024-06-25 17:25:09.437 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2024-06-25 17:25:09.437 - Install path: '/snap/dbeaver-ce/309/usr/share/dbeaver-ce'
2024-06-25 17:25:09.437 - Instance path: 'file:/.../snap/dbeaver-ce/309/.local/share/DBeaverData/workspace6/'
2024-06-25 17:25:09.438 - Memory available 107Mb/1024Mb
2024-06-25 17:25:09.439 - Create display
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4948)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1200)
	at org.eclipse.swt.widgets.Display.create(Display.java:1124)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:633)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:624)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:737)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:557)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:475)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:255)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)
Error updating splash shell
2024-06-25 17:25:09.461 - Initialize desktop platform...
2024-06-25 17:25:09.667 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.400.v20240426-1040]
> Start Core Resource Management [org.eclipse.core.resources 3.20.200.v20240513-1323]
> Start Team Support Core [org.eclipse.team.core 3.10.400.v20240413-1529]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.133.202406231636]
2024-06-25 17:25:09.816 - 
2024-06-25 17:25:09.816 - 	Refreshing workspace.
2024-06-25 17:25:09.817 - Refreshing workspace contents
2024-06-25 17:25:09.846 - Initialize base platform...
2024-06-25 17:25:09.857 - Platform initialized (396ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.133.202406231636]
2024-06-25 17:25:09.876 - Starting instance server at http://localhost:42423
2024-06-25 17:25:09.885 - Run workbench
2024-06-25 17:25:09.885 - Create display
2024-06-25 17:25:09.885 - Internal error in workbench lifecycle
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4948)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1200)
	at org.eclipse.swt.widgets.Display.create(Display.java:1124)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:633)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:624)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:737)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:557)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:289)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1432)
2024-06-25 17:25:09.886 - DBeaver is stopping
2024-06-25 17:25:09.886 - Stop instance server
2024-06-25 17:25:10.888 - Instance server has been stopped
2024-06-25 17:25:10.898 - DBeaver shutdown completed
```

**Comment by E1izabeth** [comment]
Thank you

**Comment by Matvey16** [comment]
@Pymancer Do you use Wayland on your OS and also how many monitors do you have?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by CarlosLosTopografos** [comment]
Just got it again under 24.1.3

```
!ENTRY org.jkiss.dbeaver.model 2 0 2024-08-01 11:48:25.944
!MESSAGE Some data source listeners are still registered: org.jkiss.dbeaver.model.navigator.DBNProjectDatabases:node://xxx/datasources
!SESSION 2024-08-01 11:49:16.409 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de
Framework arguments:  -eclipse.keyring C:\Users\administrator.xxx\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\DBeaver

!ENTRY org.eclipse.osgi 4 0 2024-08-01 11:49:21.160
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.dispose()" because "this.display" is null
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:328)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)

```

**Comment by CarlosLosTopografos** [comment]
Now I am back to 24.0.1. Maybe I am going to try the 24.1.4

Unfortunately I do not have permanent access to this server. BTW. It's a virtual server. Access via RDP

**Comment by CarlosLosTopografos** [comment]
As graphic processor I find here "Microsoft Hyper-V-Video". Don't know whether these information help.

**Comment by Matvey16** [comment]
@CarlosLosTopografos Does that happen with one version every time and is 100% resolved with downgrading to an earlier version?

**Comment by CarlosLosTopografos** [comment]
Yeah, with the last two  versions. every time. The downgrade always helps.

**Comment by CarlosLosTopografos** [comment]
Update: It happened to me again on one more computer with the current 24.2.1 i turned back to the previous 24.2.0 which works fine

**Comment by E1izabeth** [comment]
It looks like Eclipse issue
