### ISSUE TITLE
Java Runtime Exception

### ISSUE THREAD

**Issue by Ninjiner** [dbeaver/dbeaver#3472]
A few days ago I made a clean install of Kubuntu 18.04 on my PC. Before this dbeaver worked just fine.
But now if I try to download mysql drivers I get the following error:
![dbeaver_java_error](https://user-images.githubusercontent.com/29404715/40054060-ce321eb0-5843-11e8-9667-fe8d7aa58322.png)
I installed the test database and tried to download the SQLite drivers. This allsow worked for me.
Am I missing something?

**Comment by serge-rider** [comment]
Looks like yet another issue with MySQL 8 driver.
We'll update MySQL driver config in the next version.

As a workaround you could set trustAnchors driver parameter in connection properties dialog.

**Comment by serge-rider** [comment]
Also check last comments in #1042

**Comment by serge-rider** [comment]
Just realized that this issue is not about connectivity but about driver files download.
Could you post error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Adobe-Android** [comment]
I'm having this issue too. I can post logs.

**Comment by serge-rider** [comment]
Seems to be Java 10 related issue. Thanks for logs.

**Comment by serge-rider** [comment]
The error happens when DBeaver tries to download database drivers from Maven central (over https protocol).
https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

Workarounds (besides the ones specified above):
- Use http for Maven (configured in Preferences->Database->Drivers->Maven->disable https repository)
- Download driver jars manually and add them into driver library list

**Comment by Ninjiner** [comment]
Here are my logs to to be sure that I have got the same error:
Sorry for the plain insert, upload didnt worked.

2018-05-28 13:35:04.201 - DBeaver 5.0.5 is starting
2018-05-28 13:35:04.202 - Install path: '/usr/share/dbeaver'
2018-05-28 13:35:04.202 - Instance path: 'file:/home/mla/.dbeaver4/'
2018-05-28 13:35:04.202 - Memory available 64Mb/1024Mb
2018-05-28 13:35:04.220 - Starting RMI server at 29686
2018-05-28 13:35:04.280 - Run workbench
2018-05-28 13:35:05.756 - Initializing DBeaver 5.0.5
2018-05-28 13:35:05.761 - Host plugin: org.jkiss.dbeaver.core.application 5.0.5
2018-05-28 13:35:05.763 - Initialize Core...
2018-05-28 13:35:05.939 - Core initialized (176ms)
2018-05-28 13:35:05.942 - Configure workbench window
2018-05-28 13:35:05.986 - Create actions
2018-05-28 13:35:05.988 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-05-28 13:35:05.990 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2018-05-28 13:35:06.342 - Initialize workbench window
2018-05-28 13:35:06.352 - Finish initialization
2018-05-28 13:35:09.843 - Open [https://dbeaver.jkiss.org/product/version.xml]
2018-05-28 13:35:10.136 - javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1974)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1926)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1909)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1436)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:78)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:41)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:50)
	at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:89)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:330)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:180)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:192)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1098)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	... 10 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
	... 25 more
2018-05-28 13:35:33.602 - DBeaver is stopping
2018-05-28 13:35:33.602 - Stop RMI server

**Comment by serge-rider** [comment]
This is definitely a PostgreSQL server config error. It rejects connection from you local machine.
Generally rules are the same for pgAdmin. Are you running it on the same machine?

**Comment by serge-rider** [comment]
Closing as this is not DBeaver issue but some Java misconfiguration.
If this problem will be reported by other people we'll try to add some workaround from DBeaver side.

**Comment by Adobe-Android** [comment]
Yes it is on the same machine which is why I was confused.

**Comment by Ninjiner** [comment]
I got it finally also fixed with your workaround, thank you very much your help guys
