### ISSUE TITLE
[Vertica] Cannot edit array datatype value via UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#34893]
### Description

Values in array column cannot be edited using UI

### DBeaver Version

24.1.3

### Operating System

win11

### Database and driver

Vertica Database 23.04.0002
vertica.jar 24.02.0002

### Steps to reproduce

1. Create table
```sql
CREATE TABLE array_test
(
    f1 int NOT NULL,
    f2 array[varchar(80), 10],
    f3 ARRAY[ARRAY[int], 10],
    CONSTRAINT array_test_pk PRIMARY KEY (f1) DISABLED
);
```
2. Try to edit array data - value cannot be added. The warning is shown in Log

![image](https://github.com/user-attachments/assets/24aea3a2-f655-4832-bff4-fc077418c68e)

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Thu Jul 18 19:04:58 CEST 2024
Can't determine array element data type: Array[Varchar]

org.jkiss.dbeaver.model.exec.DBCException: Can't determine array element data type: Array[Varchar]
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.createNewValueObject(JDBCArrayValueHandler.java:92)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.addNewRow(ResultSetViewer.java:4518)
	at org.jkiss.dbeaver.ui.controls.resultset.handler.ResultSetHandlerMain.execute(ResultSetHandlerMain.java:271)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:444)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:442)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:464)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)


```

**Comment by Ploki72** [comment]
I am experiencing the same issue. The last working version is 24.1.0. Starting from version 24.1.1, the number of items is no longer displayed. The database used is Postgres.

In version 24.1.0 and earlier, the application displays the number of items correctly, as shown in the screenshot below:
![2410](https://github.com/user-attachments/assets/52ce920b-989b-4dc2-b691-6488261bcfe3)

In version 24.1.5, there are two ways the results are displayed:
If there is only one column, it displays all items inline.
![2415_1](https://github.com/user-attachments/assets/4c8cb2fd-b552-4fea-a89f-7d1d9703bf46)

If there are additional columns (before or after), it only shows the first item.
![2415_21](https://github.com/user-attachments/assets/fa0ae0f4-6b5e-4c8a-ade1-76ea7c360cbb)

There is a small arrow to expand the items, and the number of array items is only displayed after expanding.
![2415_22](https://github.com/user-attachments/assets/7da710ba-becd-4e1b-8d7a-5dfb7604fa12)

**Comment by uslss** [comment]
Still actual in 24.2.2

**Comment by kseniaguzeeva** [comment]
vertica.jar 23.03.0000
actual in 25.2.2. Also the arrays can't be expanded in the Data Editor:

https://github.com/user-attachments/assets/b680f24e-1605-4cbb-bb03-331ef273c082
