### ISSUE TITLE
Bug: DBeaver freezes when trying to fetch PostgreDataTypeCache

### ISSUE THREAD

**Issue by clounie** [dbeaver/dbeaver#3490]
Two issues:
1. It freezes when I try to fetch PostgreDataTypeCache
2. If I cancel the loading of PostgreDataTypeCache, it throws a NullPointerExcetion when I try to read the columns of a table (by double-clicking on the table)

All I do is try to connect to the database. Normally it freezes trying to load PostgreDataTypeCache.

I used to be able to stop the connection at the point where it tried to load PostgreDataTypeCache, and then continue using DBeaver like normal.

Now, whenever i stop PostgreDataTypeCache in the middle of loading, it allows that, but throws a NullPointerException whenever I try to read a table. (I can list schemas, list tables, but just can't read the table's columns -- that's when I get the attribute data type 26 error)

DBeaver 5.0.4 Community

Session data:
```eclipse.buildId=unknown
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

Logs:

```
The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
(no stack trace)
```
--
```
Attribute data type '26' not found. Use varchar
(no stack trace)
```
--
```
Can't read attributes
org.jkiss.dbeaver.DBException: Can't read attributes
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1545)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:406)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:575)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:204)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Can't read attributes
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:812)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:779)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:859)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1517)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:111)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:74)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:36)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:521)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:798)
	... 15 more
```

**Comment by clounie** [comment]
Gotcha, that'd be great. We do have a lot of tables, but we have a fiber connection so it's probably just the first.

**Comment by serge-rider** [comment]
Lazy (postponed) data type resolution will be added in 5.0.6.
