### ISSUE TITLE
CE 24.1.3 Breaks Wayland support on Linux

### ISSUE THREAD

**Issue by Eonfge** [dbeaver/dbeaver#34929]
### Description

The latest version of DBeaver seems to have inadvertently regressed. Suddenly, X11 has become a hard dependency, although X11 is itself deprecated technology and it will be faced out over time.

This happened once before, with https://github.com/dbeaver/dbeaver/issues/21299

```
2024-07-22 12:25:44.106 - Internal error in workbench lifecycle
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:302)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.postStartup(ApplicationWorkbenchAdvisor.java:270)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2813)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1108)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

[CE_24.1.3_CrashLogWayland.txt](https://github.com/user-attachments/files/16331604/CE_24.1.3_CrashLogWayland.txt)

### DBeaver Version

24.1.3

### Operating System

Fedora Linux 40, Flatpak

### Database and driver

Not applicable

### Steps to reproduce

- https://github.com/flathub/io.dbeaver.DBeaverCommunity/pull/275
- Start on a Wayland-enabled platform
- Witness the crash
- (Optional) disable Wayland support and enable X11, see it start

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by Destrolaric** [comment]
Hi, thank you for the report. This was, indeed, an unexpected regression

**Comment by serjiokov** [comment]
Hi @Eonfge Could you please try
This is a workaround:
```
cd dbeaver/product/folder
export GDK_BACKEND=x11;
./dbeaver 
```
Taken from https://github.com/eclipse-platform/eclipse.platform.swt/issues/381

**Comment by Eonfge** [comment]
```
[kevin@fedora ~]$ flatpak run --env=GDK_BACKEND=x11 io.dbeaver.DBeaverCommunity 
WARNING: Using incubator modules: jdk.incubator.vector
Dbeaver: Cannot open display: 
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.15.300.v20240418-0734]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.4.300.v20240419-2334]
> Start DBeaver Application Standalone [org.jkiss.dbeaver.ui.app.standalone 24.1.3.202407211303]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.400.v20240416-0658]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.22.200.v20240524-2010]
> Start jna [com.sun.jna 5.14.0.v20231211-1200]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.150.202407211303]
> Start Expression Language [org.eclipse.core.expressions 3.9.400.v20240413-1529]
> Start DBeaver Usage Statistics [org.jkiss.dbeaver.ui.statistics 1.0.31.202407211303]
> Start DBeaver Desktop Application Core [org.jkiss.dbeaver.core 24.1.3.202407211303]
2024-07-23 13:47:07.958 - DBeaver 24.1.3.202407211303 is starting
2024-07-23 13:47:07.959 - OS: Linux 6.9.9-200.fc40.x86_64 (amd64)
2024-07-23 13:47:07.959 - Java version: 21.0.4 by Flathub (64bit)
2024-07-23 13:47:07.959 - Install path: '/app/dbeaver'
2024-07-23 13:47:07.959 - Instance path: 'file:/home/kevin/.local/share/DBeaverData/workspace6/'
2024-07-23 13:47:07.960 - Memory available 66Mb/1024Mb
2024-07-23 13:47:07.966 - Create display
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4948)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1200)
	at org.eclipse.swt.widgets.Display.create(Display.java:1124)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:633)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:624)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:737)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:565)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.updateSplashHandler(DBeaverApplication.java:476)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:256)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Error updating splash shell
2024-07-23 13:47:07.971 - Initialize desktop platform...
2024-07-23 13:47:07.975 - send collected statistics
2024-07-23 13:47:08.052 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.400.v20240426-1040]
> Start Core Resource Management [org.eclipse.core.resources 3.20.200.v20240513-1323]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.135.202407211303]
> Start Team Support Core [org.eclipse.team.core 3.10.400.v20240413-1529]
2024-07-23 13:47:08.135 - Initialize base platform...
2024-07-23 13:47:08.148 - Platform initialized (177ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.135.202407211303]
2024-07-23 13:47:08.160 - Starting instance server at http://localhost:36103
2024-07-23 13:47:08.163 - Run workbench
2024-07-23 13:47:08.163 - Create display

(java:21): Gdk-CRITICAL **: 13:47:08.163: gdk_threads_set_lock_functions: assertion 'gdk_threads_lock == NULL && gdk_threads_unlock == NULL' failed
2024-07-23 13:47:08.163 - Internal error in workbench lifecycle
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4948)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1200)
	at org.eclipse.swt.widgets.Display.create(Display.java:1124)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:633)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:624)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:737)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getDisplay(DBeaverApplication.java:565)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:290)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
2024-07-23 13:47:08.164 - DBeaver is stopping
2024-07-23 13:47:08.164 - Stop instance server
2024-07-23 13:47:09.166 - Instance server has been stopped
2024-07-23 13:47:09.178 - DBeaver shutdown completed
2024-07-23 13:47:09.190 - Shutdown desktop platform...
2024-07-23 13:47:09.190 - send collected statistics
2024-07-23 13:47:09.204 - Platform shutdown completed (14ms)
Dbeaver: Cannot open display: 
Dbeaver:
An error has occurred. See the log file
/home/kevin/.local/share/DBeaverData/workspace6/.metadata/.log.
```

Different error, but reasonable because Fedora 40 and many other distributions no longer use X11 by default.

**Comment by Destrolaric** [comment]
@Eonfge Hi, we did the fix. unfortunately, it will only be present in the next version.

**Comment by Eonfge** [comment]
In that case, I'll skip the release this release for distribution. Flathub has close to half a million DBeaver users and I don't want all of these users to be stuck with a non-functional product.

24.1.4 would be the next release in two weeks.

**Comment by Eonfge** [comment]
24.1.4 will now be released. No problems with Wayland

**Comment by E1izabeth** [comment]
Thank you
