### ISSUE TITLE
Process failed  (exit code = 12) when restoring MySQL database

### ISSUE THREAD

**Issue by ongdk** [dbeaver/dbeaver#34926]
### Description

Unable to restore Mysql database. 

Log file:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-07-22 12:01:55.349
!MESSAGE Process failed (exit code = 12). See error log.
!STACK 0
java.io.IOException: Process failed (exit code = 12). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

### DBeaver Version

Community Edition 23.2.5.202311191730

### Operating System

macOS Sonoma Version 14.5 Apple M3 Pro

### Database and driver

Database: `10.2.44-MariaDB-1:10.2.44+maria~bionic`
Driver: `mysql-client/8.3.0`

### Steps to reproduce

1. right click db -> tools -> restore database
2. select sql file
3. start

### Additional context

dump sql:
```
-- MySQL dump 10.13  Distrib 8.3.0, for macos14.2 (arm64)
--
-- Host: 127.0.0.1    Database: testprod
-- ------------------------------------------------------
-- Server version	5.5.5-10.2.44-MariaDB-1:10.2.44+maria~bionic

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `NewTable`
--

DROP TABLE IF EXISTS `NewTable`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `NewTable` (
  `Column1` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `NewTable`
--

LOCK TABLES `NewTable` WRITE;
/*!40000 ALTER TABLE `NewTable` DISABLE KEYS */;
INSERT INTO `NewTable` VALUES ('hello'),('world');
/*!40000 ALTER TABLE `NewTable` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping routines for database 'testprod'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-07-22 10:40:42
```

**Comment by E1izabeth** [comment]
What log level do you use here?
![image](https://github.com/user-attachments/assets/f0689a7f-b24e-45ec-be19-7a5939e6b4bc)

**Comment by ongdk** [comment]
I used "Debug"

**Comment by E1izabeth** [comment]
Switching to other log level mode solves the issue for me.

**Comment by E1izabeth** [comment]
We want to switch default log level to normal (or figure out the roots of the issue and try fixing it).

**Comment by serge-rider** [comment]
Error/output log dump was broken. We'll fix it

Actual error is: `Option 'debug-info' was used, but is disabled.`
https://stackoverflow.com/questions/37451677/mysqlslap-error-mysqlslap-option-debug-info-used-but-is-disabled
