### ISSUE TITLE
RedShift Connection Error - SSL - Connection Reset

### ISSUE THREAD

**Issue by uwbadgerdev** [dbeaver/dbeaver#34947]
### Description

When connecting to an Amazon RedShift database server * with * SSL / TLS turned on I am unable to get the connection to be established. 

A window comes up with 

SSL error: Connection reset
  Connection reset 

The error in the logs is:

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.amazon.redshift.ssl.MakeSSL.convert(MakeSSL.java:36)
	at com.amazon.redshift.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:606)
	at com.amazon.redshift.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:123)
	at com.amazon.redshift.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:239)
	at com.amazon.redshift.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:351)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:483)
	at com.amazon.redshift.Driver.access$100(Driver.java:68)
	at com.amazon.redshift.Driver$ConnectThread.run(Driver.java:392)
	at java.base/java.lang.Thread.run(Unknown Source)

### DBeaver Version

Community Edition Version 24.1.3.202407211303

### Operating System

Windows 10

### Database and driver

RedShift
com.amazon.redshift.jdbc42.Driver  v2.1.0.29
com.amazonaws:aws-java-sdk-core:1.12.557
com.amazonaws:aws-java-sdk-redshift:1.12.557
com.amazonaws:aws-java-sdk-redshiftserverless:1.12.557
com.amazonaws:aws-java-sdk-sts:1.12.557

### Steps to reproduce

Open DBeaver.
Create new connection.
Select RedShift
Enter in host instance.
Enter in Port.
Enter in Database.
Enter in Username and Password.
Go to SSL Tab.
Check SSL Box.
Click Test Connection... Button.

**Comment by E1izabeth** [comment]
Following the provided steps I see that you haven't filled the required fields for SSL. Just checking the checkbox is not enough.

**Comment by uwbadgerdev** [comment]
The User Interface explicitly says "All SSL parameters are optional" on the SSL tab. Therefore, I have indeed filled in all required fields for SSL. If more are required, then the User Interface is incorrect.

![dbeaver](https://github.com/user-attachments/assets/6f4288ee-c9c3-459b-98a6-545f5c9e8ac9)

**Comment by E1izabeth** [comment]
You're right, it might be so that you don't need to fill any fields. However, it depends on your server configuration.
I can only suppose something about your configuration according to the error you get.

**Comment by Destrolaric** [comment]
Hi @uwbadgerdev could you try to specify the AWS CA certificate, docs and links about it can be found here:
https://docs.aws.amazon.com/privateca/latest/userguide/PCACertInstall.html

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
