### ISSUE TITLE
NPEx on refresh in DB Navigator

### ISSUE THREAD

**Issue by pzygielo** [dbeaver/dbeaver#34969]
### Description

On refreshing in _Database Navigator_ pane I got dialog with:
```
Error refreshing node

Reason:
Cannot invoke "org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMetaContext(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor)" because the return value of "org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDefaultInstance()" is null
```

### DBeaver Version

Community 24.1.3.202407211303

### Operating System

GNU/Linux fc40

### Additional context

I guess it happened at
https://github.com/dbeaver/dbeaver/blob/0d326aa112032931ec134156d89caa757fa64c13/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCDataSource.java#L481

But here
https://github.com/dbeaver/dbeaver/blob/0d326aa112032931ec134156d89caa757fa64c13/plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCDataSource.java#L440-L441
the possible `null` is considered.

**Comment by E1izabeth** [comment]
Could you provide full stacktrace?
You can find it in log files https://dbeaver.com/docs/wiki/Log-files/.

**Comment by pzygielo** [comment]
```
ava.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMetaContext(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor)" because the return value of "org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDefaultInstance()" is null
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:481)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:469)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.refreshObject(GenericDataSource.java:609)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.refreshObject(DataSourceDescriptor.java:784)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.lambda$0(DBNDatabaseNode.java:361)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:359)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:275)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:189)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.model.struct.DBSInstance.getDefaultContext(org.jkiss.dbeaver.model.runtime.DBRProgressMonitor, boolean)" because the return value of "org.jkiss.dbeaver.model.DBPDataSource.getDefaultInstance()" is null
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.addSetDefaultObjectAction(NavigatorUtils.java:307)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.addStandardMenuItem(NavigatorUtils.java:271)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.lambda$0(NavigatorUtils.java:254)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:467)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:494)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:272)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:290)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:5107)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4508)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

**Comment by E1izabeth** [comment]
Thank you!

**Comment by Matvey16** [comment]
@pzygielo That doesn't reproduce on any connection. Can you please add what database connection it is? Does that happen with any connection? On what node (connection/database/table) do you click refresh?

**Comment by pzygielo** [comment]
> That doesn't reproduce on any connection.

I've also seen it only once.

> Does that happen with any connection? On what node (connection/database/table) do you click refresh?

IIRC, it was not on any node, but right-click on empty space below the last connection, then select _Refresh_.

I reported as `NPEx` deserved it. As it happened - it was possible.

**Comment by pzygielo** [comment]
Thanks for checking.

Feel free to close as non-reproducible.

:crossed_fingers: to never happen again :smile:
