### ISSUE TITLE
Exception error 1

### ISSUE THREAD

**Issue by milroyf** [dbeaver/dbeaver#34981]
### Description

While trying to connect to db2 database I'm getting the following error. Could you please help me to find a  solution for this issue?
com.ibm.db2.jcc.am.StandbyServerSQLException: 1
	at com.ibm.db2.jcc.am.b4.a(b4.java:63)
	at com.ibm.db2.jcc.am.b4.a(b4.java:140)
	at com.ibm.db2.jcc.am.Connection.completeSqlca(Connection.java:5325)
	at com.ibm.db2.jcc.t4.y.q(y.java:865)
	at com.ibm.db2.jcc.t4.y.p(y.java:721)
	at com.ibm.db2.jcc.t4.y.l(y.java:542)
	at com.ibm.db2.jcc.t4.y.d(y.java:153)
	at com.ibm.db2.jcc.t4.b.k(b.java:1555)
	at com.ibm.db2.jcc.t4.b.b(b.java:1467)
	at com.ibm.db2.jcc.t4.b.a(b.java:6932)
	at com.ibm.db2.jcc.t4.b.b(b.java:977)
	at com.ibm.db2.jcc.t4.b.a(b.java:890)
	at com.ibm.db2.jcc.t4.b.a(b.java:458)
	at com.ibm.db2.jcc.t4.b.a(b.java:431)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:369)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:259)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:215)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:491)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.db2.model.DB2DataSource.openConnection(DB2DataSource.java:286)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.db2.model.DB2DataSource.<init>(DB2DataSource.java:133)
	at org.jkiss.dbeaver.ext.db2.DB2DataSourceProvider.openDataSource(DB2DataSourceProvider.java:101)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1385)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1229)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1015)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:117)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2488)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:227)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseN

### DBeaver Version

Community edition 24

### Operating System

Windows10

### Database and driver

DB2

**Comment by E1izabeth** [comment]
Please provide information about your connection configuration. The error code doesn't say a lot, as it comes from DB2 driver.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
