### ISSUE TITLE
Ubuntu DBeaver 24.1.4 Snap - cannot backup PGSQL database - Utility 'pg_dump' not found in client home

### ISSUE THREAD

**Issue by martinarisk** [dbeaver/dbeaver#35123]
### Description

When Click PostgreSQL dump:

```
2024-08-08 10:03:19.489 - IO error: Utility 'pg_dump' not found in client home '/run/user/1001/doc/167724b3/bin' (/run/user/1001/doc/167724b3/bin)
2024-08-08 10:03:19.489 - java.io.IOException: Utility 'pg_dump' not found in client home '/run/user/1001/doc/167724b3/bin' (/run/user/1001/doc/167724b3/bin)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:149)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreNativeToolHandler.fillProcessParameters(PostgreNativeToolHandler.java:54)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseBackupHandler.fillProcessParameters(PostgreDatabaseBackupHandler.java:104)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseBackupHandler.getCommandLine(PostgreDatabaseBackupHandler.java:159)
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseBackupHandler.getCommandLine(PostgreDatabaseBackupHandler.java:1)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:217)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

### DBeaver Version

DBeaver 24.1.4

### Operating System

Ubuntu 24.04 LTS

### Steps to reproduce

1. install DBeaver from ubuntu snap
2. Connect to db
3. Try to backup database
4. Local client cannot be configured to real folder, such as /usr/bin, only /run/user/1001/doc/167724b3/bin
5. When I backup it don't find pg_dump

**Comment by martinarisk** [comment]
When I copy the real pg_dump (perl script) from /usr/share/postgresql-common/pg_wrapper into /usr/bin/pg_dump I get different error:
```
2024-08-08 10:17:10.636 - IO error: Cannot run program "/run/user/1001/doc/167724b3/bin/pg_dump" (in directory "/run/user/1001/doc/167724b3/bin"): error=13, Permission denied
2024-08-08 10:17:10.636 - java.io.IOException: Cannot run program "/run/user/1001/doc/167724b3/bin/pg_dump" (in directory "/run/user/1001/doc/167724b3/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:226)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```

**Comment by E1izabeth** [comment]
Thank you for bug report.
We have such issue with snap installations #19055 
Please try installing DBeaver with tar.gz https://dbeaver.io/download/
I'm closing this issue as a duplicate.
