### ISSUE TITLE
NPE when table name is invalid

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#35138]
### Description

STR

1. Open SQL editor
2. Type query with invalid table name
3. Open error log - see error

https://github.com/user-attachments/assets/9e43ffae-f018-4e70-8d84-f3c53896962e

```
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "this.otherItemNames" is null
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:384)
	at net.sf.jsqlparser.schema.Table.accept(Table.java:213)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:348)
	at net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:317)
	at net.sf.jsqlparser.util.TablesNamesFinder.visit(TablesNamesFinder.java:254)
	at net.sf.jsqlparser.statement.select.Select.accept(Select.java:395)
	at net.sf.jsqlparser.statement.Statement.accept(Statement.java:18)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1277)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromObject(SQLCompletionAnalyzer.java:1229)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:1139)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.makeDataSourceProposals(SQLCompletionAnalyzer.java:925)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:349)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:121)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:105)
	at org.jkiss.dbeaver.model.sql.completion.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:396)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

24.1.5

### Operating System

mac M1 Sonoma

### Database and driver

Any

**Comment by serge-rider** [comment]
PR merged into https://github.com/dbeaver/pro/issues/3140 fix
