### ISSUE TITLE
Ошибка в поле типа "date" при отображении данных внешнего сервера

### ISSUE THREAD

**Issue by TheCHIM** [dbeaver/dbeaver#35152]
### Description

При попытке выборки данных(` SELECT * FROM "RandomData" rd `) стороннего сервера(MSSQL) подключённого через tds_fdw, происходит ошибка "неверный синтаксис для типа date: "May 12 1970 12:00:00:AM""
![2024-08-11_11-07-08](https://github.com/user-attachments/assets/26ce484c-e15a-4e7a-80c0-73eebecd4d59)
![2024-08-11_11-06-59](https://github.com/user-attachments/assets/88c49012-3bfa-4159-88ed-d182a3940fde)
![2024-08-11_11-02-11](https://github.com/user-attachments/assets/2bcea9da-f615-4fae-b20c-3727694b58bf)
![2024-08-11_10-54-19](https://github.com/user-attachments/assets/b3b5467d-674e-42bd-b6f1-ced92f1d3a08)

### DBeaver Version

24.1.4

### Operating System

Windows 10 Pro x64

### Database and driver

1. Имя и версия базы данных приёмника данных: PostgreSQL PRO 16.3
2. Имя и версия базы источника данных(внешний сервер): MSSQL Server Developer (64-bit) version 16

### Steps to reproduce

Создал таблицу в mssql server со всеми типами полей. Далее через расширение tds_fdw делаю следующие настройки:
1. в файле freetds.conf следующие настройки
`[ms_server]
	host = 192.168.1.57
	port = 1433
	tds version = 7.3
	instance = ms_server`
2. Далее выполняем SQL:
`CREATE SERVER srv FOREIGN DATA WRAPPER tds_fdw OPTIONS (servername 'ms_server', database 'test', msg_handler 'notice');
CREATE USER MAPPING FOR postgres SERVER srv OPTIONS (username 'test', password 'test');   
IMPORT FOREIGN SCHEMA dbo FROM SERVER srv  INTO ms_test OPTIONS (import_default 'true');`
3. После пытаемся выполнить обычную выборку данных:
` SELECT * FROM "RandomData" rd `
4. Получаем ошибку: 
`org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [22007]: ОШИБКА: неверный синтаксис для типа date: "May 12 1970 12:00:00:AM"
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:615)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:506)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:525)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:977)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4195)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5160)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ОШИБКА: неверный синтаксис для типа date: "May 12 1970 12:00:00:AM"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more`

**Comment by ShadelessFox** [comment]
Hello @TheCHIM,

Please write your next ticket in English.

Judging by the error message, this is a server-side issue. After some googling, I came across a similar issue: https://github.com/tds-fdw/tds_fdw/issues/271.

Try following the proposed solution here: https://github.com/tds-fdw/tds_fdw/issues/271#issuecomment-731581415

**Comment by TheCHIM** [comment]
> [ShadelessFox](/ShadelessFox)
Thank you! Your advice helped!
