### ISSUE TITLE
[Informix] Grouping panel doesn't work

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#35223]
### Description

Grouping panel doesn't work for informix.
![image](https://github.com/user-attachments/assets/af0f69af-98a2-466f-a381-3ab996fe17a9)

### DBeaver Version

24.1.5

### Operating System

win11

### Database and driver

Informix Dynamic Server 14.10.FC9W1DE
Informix JDBC Driver for Informix Dynamic Server 4.50.JC10W1

### Additional context

```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Framework arguments:  -eclipse.keyring C:\Users\Dziyana\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Aug 15 16:06:52 CEST 2024
A syntax error has occurred.

java.sql.SQLSyntaxErrorException: A syntax error has occurred.
	at com.informix.util.IfxErrMsg.buildExceptionWithMessage(IfxErrMsg.java:416)
	at com.informix.util.IfxErrMsg.buildIsamException(IfxErrMsg.java:403)
	at com.informix.jdbc.IfxSqli.addException(IfxSqli.java:3023)
	at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3274)
	at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2269)
	at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2194)
	at com.informix.jdbc.IfxSqli.executeExecute(IfxSqli.java:2104)
	at com.informix.jdbc.IfxResultSet.executeExecute(IfxResultSet.java:302)
	at com.informix.jdbc.IfxStatement.executeImpl(IfxStatement.java:1017)
	at com.informix.jdbc.IfxStatement.executeImpl(IfxStatement.java:997)
	at com.informix.jdbc.IfxStatement.executeBody(IfxStatement.java:745)
	at com.informix.jdbc.IfxStatement.execute(IfxStatement.java:687)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.grouping.GroupingDataContainer.readData(GroupingDataContainer.java:129)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5160)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

**Comment by LonwoLonwo** [comment]
```
@Override
    public boolean supportsAliasInSelect() {
        return true;
    }
```
