### ISSUE TITLE
Eclipse errors on start and missing .xlsx import since update from 24.0 to 24.1.4

### ISSUE THREAD

**Issue by ekludt** [dbeaver/dbeaver#35232]
### Description

After upgrading from 24.0 to 24.1.4 i started to get errors in the log and i can not select .xlsx files to import data anymore. I have tried to downgrade back to 24.0 and also upgrading to 24.2. Also i removed the java folder from dbeaver folder and installed the most recent java jdk.
[DBeaver_Starting_Erros.log](https://github.com/user-attachments/files/16634553/DBeaver_Starting_Erros.log)

### DBeaver Version

Community and EE Edition 24.1.4 and 24.2

### Operating System

Windows 10 Enterprise

### Database and driver

MS SQL Server

### Steps to reproduce

Each start of DBeaver commutiy or EE version

**Comment by E1izabeth** [comment]
From logs:

```
java.io.IOException: Unable to resolve plug-in "org.eclipse.egit.ui".
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:63)
	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:296)
	at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:219)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:267)
	at org.eclipse.jface.resource.URLImageDescriptor$URLImageFileNameProvider.getImagePath(URLImageDescriptor.java:64)
	at org.eclipse.swt.internal.DPIUtil.lambda$3(DPIUtil.java:570)
	at org.eclipse.swt.internal.DPIUtil.getElementAtZoom(DPIUtil.java:579)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImagePathAtZoom(DPIUtil.java:570)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:684)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:306)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:229)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)

```
```
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(platform:/plugin/org.eclipse.egit.ui/icons/eview16/repo_rep.png)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:231)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:95)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:208)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:228)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImage(SWTPartRenderer.java:238)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.createTab(StackRenderer.java:980)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.processContents(LazyStackRenderer.java:203)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
```
```
java.io.IOException: Unable to resolve plug-in "com.dbeaver.model.tableau".
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:63)
	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:296)
	at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:219)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:267)
	at org.eclipse.jface.resource.URLImageDescriptor$URLImageFileNameProvider.getImagePath(URLImageDescriptor.java:64)
	at org.eclipse.swt.internal.DPIUtil.lambda$3(DPIUtil.java:570)
	at org.eclipse.swt.internal.DPIUtil.getElementAtZoom(DPIUtil.java:579)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImagePathAtZoom(DPIUtil.java:570)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:684)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:306)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:229)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:95)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:208)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:228)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImage(SWTPartRenderer.java:238)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.createTab(StackRenderer.java:980)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.processContents(LazyStackRenderer.java:203)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)

```

```
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(platform:/plugin/com.dbeaver.model.tableau/icons/tableau.png)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:231)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:95)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:208)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:228)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImage(SWTPartRenderer.java:238)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.createTab(StackRenderer.java:980)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.processContents(LazyStackRenderer.java:203)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)

```

**Comment by serge-rider** [comment]
It looks like something is broken in product installation.
How to you install it?

All PRO extensions are disabled (like Git or Office). Are you sure that you install proper version of DBeaver?

**Comment by sagitarriuss** [comment]
The same error (Unable to resolve plug-in "org.eclipse.egit.ui") after upgrading to DBeaver CE 2.1.5, all Eclipse plugins are not loaded (2.1.4 worked with those plugins, but didn't display the User Interface > Editors preferences page). The plugins were installed by the Eclipse Marketplace Client plugin (1.10.3.v20240228-1000): AnyEdit Tools, Mesfavoris. All of them are not loaded on 2.1.5.

**Comment by E1izabeth** [comment]
For Community version, you need to install plugins again after version update. Here is an issue about it #5317

**Comment by ekludt** [comment]
I had both versions (CE and EE) installed from installer in parallel. It worked without problems up to the update of Community to 24.1.4 with the upgrade message. 
Now I deinstalled both and reinstalled just EE alone. Now everything works without error messages. Thank you for explaining of the errors!

**Comment by E1izabeth** [comment]
Updating CE version doesn't affect EE product. All optional plugins are included in EE version by default. So, for me this issue is still not clear.
I'm happy that it's resolved with reinstalling. Please let me know if you encounter the issues again.
