### ISSUE TITLE
MariaDB updates driver

### ISSUE THREAD

**Issue by dreibh** [dbeaver/dbeaver#35242]
### Description

I set up a MariaDB test DB, with proper TLS setup, using some test scripting that sets everything up from scratch (https://github.com/dreibh/hipercontracer/tree/dreibh/udpping/src/TestDB). The TLS certificate is signed by a 4-level CA hierarchy.

With OpenSSL, trying to connect with TLS certificate validation is fine:
echo "" | openssl s_client -showcerts -connect mariadb.domain.test:3306 -CAfile /etc/ssl/TestLevel1/certs/TestLevel1.crt -starttls mysql
Output is attached: [bugreport-openssl.txt](https://github.com/user-attachments/files/16639392/bugreport-openssl.txt)

Connecting DBeaver CE (Ubuntu Snap) works fine with the **MySQL** driver. From data-sources.json:
`                "mariaDB-19156a48cc7-6447def30cb02b8c": {
                        "provider": "mysql",
                        "driver": "mariaDB",
                        "name": "maintainer@mariadb.domain.test:3306/testonly MariaDB",
                        "save-password": true,
                        "configuration": {
                                "host": "mariadb.domain.test",
                                "port": "3306",
                                "database": "testonly",
                                "url": "jdbc:mariadb://mariadb.domain.test:3306/testonly",
                                "configurationType": "MANUAL",
                                "type": "dev",
                                "closeIdleConnection": true,
                                "auth-model": "native",
                                "handlers": {
                                        "mysql_ssl": {
                                                "type": "CONFIG",
                                                "enabled": true,
                                                "save-password": true,
                                                "properties": {
                                                        "ssl.ca.cert": "/home/nornetpp/TestLevel1.crt",
                                                        "ssl.client.cert": "",
                                                        "ssl.client.key": "",
                                                        "ssl.method": "CERTIFICATES",
                                                        "ssl.require": "true",
                                                        "ssl.verify.server": "true",
                                                        "ssl.public.key.retrieve": "false",
                                                        "ssl.cipher.suites": ""
                                                }
                                        }
                                }
                        }
                },
`

Now, trying the same with the MariaDB driver, the certificate validation reproducibly fails, i.e.:
`                "mariaDB-19156a48cc7-6447def30cb02b8c": {
                        "provider": "mysql",
                        "driver": "mariaDB",
                        "name": "maintainer@mariadb.domain.test:3306/testonly MariaDB",
                        "save-password": true,
                        "configuration": {
                                "host": "mariadb.domain.test",
                                "port": "3306",
                                "database": "testonly",
                                "url": "jdbc:mariadb://mariadb.domain.test:3306/testonly",
                                "configurationType": "MANUAL",
                                "type": "dev",
                                "closeIdleConnection": true,
                                "auth-model": "native",
                                "handlers": {
                                        "mysql_ssl": {
                                                "type": "CONFIG",
                                                "enabled": true,
                                                "save-password": true,
                                                "properties": {
                                                        "ssl.ca.cert": "/home/nornetpp/TestLevel1.crt",
                                                        "ssl.client.cert": "",
                                                        "ssl.client.key": "",
                                                        "ssl.method": "CERTIFICATES",
                                                        "ssl.require": "true",
                                                        "ssl.verify.server": "true",
                                                        "ssl.public.key.retrieve": "false",
                                                        "ssl.cipher.suites": ""
                                                }
                                        }
                                }
                        }
                }
`

Error message is "(conn=18) Could not connect to mariadb.domain.test:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

On the console:
`2024-08-16 09:37:05.166 - Connect with 'maintainer@mariadb.domain.test:3306/testonly MariaDB' (mariaDB-19156a48cc7-6447def30cb02b8c)
2024-08-16 09:37:05.167 - Execution context opened (maintainer@mariadb.domain.test:3306/testonly MariaDB; Main; 6)
2024-08-16 09:37:05.201 - (conn=23) Could not connect to mariadb.domain.test:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.jkiss.dbeaver.model.exec.DBCConnectException: (conn=23) Could not connect to mariadb.domain.test:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:266)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:488)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:120)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:104)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:123)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:118)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1406)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1276)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1061)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:109)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:114)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
        at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2414)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:159)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:226)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=23) Could not connect to mariadb.domain.test:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:300)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:366)
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:225)
        at org.mariadb.jdbc.Driver.connect(Driver.java:69)
        at org.mariadb.jdbc.Driver.connect(Driver.java:95)
        at org.mariadb.jdbc.Driver.connect(Driver.java:26)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:222)
        ... 27 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.mariadb.jdbc.client.impl.ConnectionHelper.sslWrapper(ConnectionHelper.java:358)
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:156)
        ... 33 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at java.base/sun.security.validator.Validator.validate(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 47 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 52 more
`

Since the certificate, chain and CA should be fine (as tested with OpenSSL, as well as the MySQL driver), I assume that something is wrong with the MariaDB driver.

### DBeaver Version

24.1.4.202408041450 (Snap version in Ubuntu)

### Operating System

Ubuntu 24.04

### Database and driver

MariaDB from the Ubuntu repositories, i.e.:
`nornetpp@localhost:~$ apt-show-versions | grep mariadb
libmariadb-dev:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
libmariadb3:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-backup:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-client:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-client-core:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-common:all/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-plugin-provider-bzip2:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-plugin-provider-lz4:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-plugin-provider-lzma:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-plugin-provider-lzo:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-plugin-provider-snappy:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-server:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
mariadb-server-core:amd64/noble-security 1:10.11.8-0ubuntu0.24.04.1 uptodate
`

In DBeaver CE:
- MySQL driver v8.2.0
- MariaDB driver v3.3.2

### Steps to reproduce

1. Configure DBeaver, to connect to the database with the MySQL driver -> works fine
2. Configure DBeaver, to connect to the database with the MariaDB driver -> fails
3. Change the MariaDB connection to not validate the certificate -> this works, but of course makes TLS security mostly useless

**Comment by dreibh** [comment]
The test scripts to generate the CA hierarchy and certificates are available here: https://github.com/dreibh/hipercontracer/tree/dreibh/udpping/src/TestDB .

**Comment by HocKu7** [comment]
@dreibh Hi. Thank you for your report. Please check if your issue is still present with the last version of the mariaDb driver. Just take the release version of the maria db driver from maven [repo](https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client/3.4.1) and put it there in the folder instead of the .jar. Let me know about any news
![image](https://github.com/user-attachments/assets/7651390a-91e2-4556-8c29-4dbdc6f570a4)

**Comment by dreibh** [comment]
The MariaDB Java Client driver version 3.4.1 fixes the issue. The Ubuntu Snap of DBeaver still installs the broken version 3.3.0; installing the new version 3.4.1 in the Driver Manager fixes the problem. The Ubuntu Snap needs an update to use the new driver.

**Comment by dreibh** [comment]
I just tried the current Ubuntu Snap (DBeaver 25.0.1.202503231807), which installs MariaDB driver version "org.mariadb.jdbc:mariadb-java-client:RELEASE [3.5.2]". Trying to connect to a TLS-configured server now fails with:
`Received fatal alert: protocol_version`
The MySQL driver works fine for connecting to this MariaDB server.

Trying a non-TLS server, both drivers work. So, the issue appears only when TLS is used.

**Comment by dreibh** [comment]
The problem still exists:
- DBeaver 25.3.0 (current Ubuntu Snap)
- org.mariadb.jdbc:mariadb-java-client:RELEASE [3.5.2]

`Received fatal alert: protocol_version`

A connection to a TLS-secured MariaDB server seems to be impossible using the MariaDB driver. However, the MySQL driver just works fine. Also, there is no problem connecting the MariaDB shell client to the database.

I am using DBeaver in test setups for [HiPerConTracer](https://www.nntb.no/~dreibh/hipercontracer/), with support for different database backends to storage measurement data. If there is need for test setups to reproduce the issue, there are VirtualBox VM images with database and DBeaver available here: [https://packages.nntb.no/hipercontracer/latest/](https://packages.nntb.no/hipercontracer/latest/).
