### ISSUE TITLE
After successful connect to sybase no tables are shown

### ISSUE THREAD

**Issue by tk-2018** [dbeaver/dbeaver#3528]
I got a problem using the current version of dbeaver when connecting to a sybase db. The last time I had to use this connection was with an older version of dbeaver (4.x) where this problem does not occur.  After successful connecting I cannot see any tables. With a double-click on tables I get a listing of all tables, but cannot open one of them. I think the problem is that my user is not the owner of the tables.

I get these messages in dbeaver log:
```
!MESSAGE SQL Error [2706] [42W33]: SQL Anywhere Error -141: Table 'NC_Workstation' not found
!SUBENTRY 4 org.jkiss.dbeaver.model 4 0 2018-05-28 12:53:57.162
!MESSAGE SQL Anywhere Error -141: Table 'NC_Workstation' not found
!STACK 0
```

**Comment by serge-rider** [comment]
Could you post debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)
There were some changes in schema loading for Sybase, maybe it works incorrectly with some server versions.

**Comment by tk-2018** [comment]
Ok, here is the part of the current log:
```
2018-05-28 13:52:34.146 - Connect with 'Sybase jConnect - zenworks_ZCM11' (sybase_jconn-163a65d83c0-50cbb18addf8be92)
2018-05-28 13:52:34.459 - Connected (sybase_jconn-163a65d83c0-50cbb18addf8be92, jConnect (TM) for JDBC (TM) [jConnect (TM) for JDBC(TM)/7.07 ESD #5 (Build 26792)/P/EBF20686/JDK 1.6.0/jdbcmain/OPT/Mon Oct 15 11:36:14 PDT 2012])
2018-05-28 13:52:44.802 - Can't get column 'IS_GENERATEDCOLUMN': S0022: Ung?ltiger Spaltenname 'IS_GENERATEDCOLUMN'.
2018-05-28 13:53:03.459 - SQL Warning (DataSource: Sybase jConnect - zenworks_ZCM11; Code: 0; State: 010SK): 010SK: Datenbank kann Option SET_READONLY_TRUE nicht setzen.
2018-05-28 13:53:03.490 - null
org.jkiss.dbeaver.DBException: SQL Error [2706] [42W33]: SQL Anywhere Error -141: Table 'NC_Workstation' not found
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1552)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [2706] [42W33]: SQL Anywhere Error -141: Table 'NC_Workstation' not found
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:823)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1989)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1524)
	... 3 more
Caused by: org.jkiss.dbeaver.DBException: SQL Error [2706] [42W33]: SQL Anywhere Error -141: Table 'NC_Workstation' not found
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1552)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:388)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:818)
	... 6 more
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [2706] [42W33]: SQL Anywhere Error -141: Table 'NC_Workstation' not found
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:446)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1524)
	... 8 more
Caused by: java.sql.SQLException: SQL Anywhere Error -141: Table 'NC_Workstation' not found
	at com.sybase.jdbc4.jdbc.SybConnection.getAllExceptions(SybConnection.java:2780)
	at com.sybase.jdbc4.jdbc.SybStatement.handleSQLE(SybStatement.java:2665)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:295)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:272)
	at com.sybase.jdbc4.jdbc.SybStatement.executeLoop(SybStatement.java:2594)
	at com.sybase.jdbc4.jdbc.SybStatement.execute(SybStatement.java:2581)
	at com.sybase.jdbc4.jdbc.SybStatement.execute(SybStatement.java:1293)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 11 more
```

**Comment by serge-rider** [comment]
I can't figure out what is wrong right now, will test this with SAP ASE.
BTW did you try another driver (jTDS)?

**Comment by tk-2018** [comment]
I've just reinstalled Version 4.2.6 of DBeaver and now I see the difference. With this version I first get a list of db users including dbo, sys, zenadmin etc. So in the past I've opened the user "zenadmin" and then opened a table in the list. In newer versions of DBeaver there is no such userlist. I only get the tables and when I try to open one, the owner, in this case "zenadmin", is missing and so the table cannot be found. Is this maybe something that can be configured in the driver?

**Comment by serge-rider** [comment]
I can't reproduce this with SAP ASE.
What DBeaver version do you use? There were some issues with SQL Server metadata reading a few version ago but they were resolved.
If you use the most recent version of DBeaver and it still doesn't work - please say what Sybase server do you use.

**Comment by tk-2018** [comment]
I use the current version 5.0.6. The sybase server seems to be very old, version 12.0.1.3873.

**Comment by serge-rider** [comment]
Please try jTDS driver (`Sybase`, not `Sybase jConnect`)

**Comment by tk-2018** [comment]
I have just installed the new version 5.1. With jTDS driver I still can't see any tables. But with the sybase driver jconn4.jar I see all tables. This is ok for me, thank you very much.

**Comment by serge-rider** [comment]
Great. Thanks for info
