### ISSUE TITLE
Error while analyzing query text

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35356]
### Description

Since Postgres allows to execute this query successfully, it seems to be exception is excessive here (just take the first name of a column).

- execute the code:
```
    select 1 as s1
    union all
    select 2 as s2
    
```
- open `%APPDATA%\DBeaverData\workspace6\.metadata\dbeaver-debug.log`
- see the error in logs:

```
2024-08-26 18:55:36.428 - Error while analyzing query text: select 1 as s1
    union all
    select 2 as s2
java.lang.UnsupportedOperationException: Cannot treat different symbols as one ('s1' and 's2')
	at org.jkiss.dbeaver.model.sql.semantics.SQLQuerySymbol.merge(SQLQuerySymbol.java:100)
	at org.jkiss.dbeaver.model.sql.semantics.model.select.SQLQueryRowsSetCorrespondingOperationModel.propagateContextImpl(SQLQueryRowsSetCorrespondingOperationModel.java:107)
	at org.jkiss.dbeaver.model.sql.semantics.model.select.SQLQueryRowsSourceModel.propagateContext(SQLQueryRowsSourceModel.java:81)
	at org.jkiss.dbeaver.model.sql.semantics.model.select.SQLQueryRowsSourceModel.applyContext(SQLQueryRowsSourceModel.java:69)
	at org.jkiss.dbeaver.model.sql.semantics.model.SQLQueryModel.propagateContext(SQLQueryModel.java:76)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.recognizeQuery(SQLQueryModelRecognizer.java:153)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.recognizeQuery(SQLQueryModelRecognizer.java:747)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob.doWork(SQLBackgroundParsingJob.java:545)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob$1.run(SQLBackgroundParsingJob.java:90)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by E1izabeth** [comment]
Thank you for bug report. It's fixed with https://github.com/dbeaver/dbeaver/pull/35293 and will be available in version 24.2.0
