### ISSUE TITLE
BufferOverflowException With Oracle and Kerberos principal authentication

### ISSUE THREAD

**Issue by lxwagno** [dbeaver/dbeaver#35390]
### Description

A java.nio.BufferOverflowException occurs in either Windows/Linux when connecting to an Oracle database with Kerberos authentication for principal user.  Not sure if this is a bug in java or DBeaver.

Note that when generating a kerberos ticket using a keytab for a functional account, this error behavior does not exist.

2024-08-29 07:18:42.289 - BufferOverflowException
java.nio.BufferOverflowException
	at java.base/java.nio.HeapByteBuffer.put(Unknown Source)
	at java.base/java.nio.ByteBuffer.put(Unknown Source)
	at oracle.net.ano.AnoCommNIO.sendRaw(AnoCommNIO.java:150)
	at oracle.net.ano.AuthenticationService.run(AuthenticationService.java:874)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at oracle.net.ano.AuthenticationService.activateAuthenticatorPhase2(AuthenticationService.java:541)
	at oracle.net.ano.Ano.negotiation(Ano.java:274)
	at oracle.net.ns.NSProtocol.initializeAno(NSProtocol.java:579)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:360)
	at oracle.jdbc.driver.T4CConnection.connectNetworkSessionProtocol(T4CConnection.java:3411)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:1016)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1178)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:105)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:886)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:693)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:94)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:143)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1315)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1163)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:960)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

Community Edition 23.3.3.202401211839

### Operating System

Red Hat Enterprise Linux release 8.9

### Database and driver

Oracle Database 19c Enterprise Edition 19.22.0.0.0
oracle.jdbc.Oracle driver 23.4.0.24.05 (ojdbc11-23.4.0.24.05.jar)

### Steps to reproduce

1. Add the following to dbeaver.ini or config.ini:
    - sun.security.krb5.debug=true
    - java.security.krb5.conf={path to krb5.ini}
    - oracle.jdbc.javaNetNio=false
2. Launch DBeaver
3. Create new Oracle db connection with required TNS info.  Authentication: OS Authentication
4. Driver Settings / Libraries - delete all and add ojdbc11-23.4.0.24.05.jar
5. Driver properties - update the following:
    - oracle.net.authentication_services: KERBEROS5
    - oracle.net.kerberos5_cc_name: {path to krb5cc file}
    - oracle.net.kerberos5_mutual_authentication: true
6. Generate Kerberos authentication ticket with kinit
7. Test Connection = Recieve error

**Comment by Destrolaric** [comment]
@lxwagno Hi, it looks like it might be a driver side issue. We found the similar issue on oracle board
https://support.oracle.com/knowledge/Middleware/2720963_1.html

**Comment by lxwagno** [comment]
Hello, @Destrolaric  - sorry for the delay in response.  After more troubleshooting, I can indeed confirm it is a third party issue as it is also occurring in Oracle SQL Developer.  Does the support article you mentioned ([https://support.oracle.com/knowledge/Middleware/2720963_1.html](https://support.oracle.com/knowledge/Middleware/2720963_1.html)) provide any suggested resolution?  I'm unable to view the article.  Thanks

**Comment by E1izabeth** [comment]
Unfortunately, there is no solution provided by that link
