### ISSUE TITLE
DB CE 24.1.5 Win32.x86_64 SWTError: No more handles

### ISSUE THREAD

**Issue by cowbert** [dbeaver/dbeaver#35392]
### Description
This is on the portable/ZIP Windows version of CE 24.1.5

With multiple windows, but fewer than 10 SQL Editor tabs per window, switching tabs intermittently throws org.eclipse.swt.SWTError: No more handles.

Here is a stacktrace from the log for the initial exception. This then drives Unhandled Loop Exceptions throughout the rest of the application requiring application shutdown. 

We're also using the following SQLEditor config lines in org.jkiss.dbeaver.core.prefs:
```
SQLEditor.ContentAssistant.auto.activation.enable=false
SQLEditor.ContentAssistant.auto.keystrokes.activation=false
SQLEditor.ContentAssistant.autocompletion.tab=false
SQLEditor.ContentAssistant.insert.single.proposal=false
SQLEditor.Highlighting.advanced.enable=false
SQLEditor.autoSaveOnClose=true
SQLEditor.format.activeQuery=false
```

Stacktrace sample:
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2024-08-29 10:38:07.674
!MESSAGE No more handles
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4948)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:488)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:674)
	at org.eclipse.swt.widgets.Scrollable.createHandle(Scrollable.java:145)
	at org.eclipse.swt.widgets.Composite.createHandle(Composite.java:298)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:700)
	at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:160)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:121)
	at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:85)
	at org.eclipse.swt.widgets.Composite.<init>(Composite.java:103)
	at org.eclipse.swt.widgets.Canvas.<init>(Canvas.java:81)
	at org.jkiss.dbeaver.ui.controls.VerticalFolder.<init>(VerticalFolder.java:43)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.<init>(ResultSetViewer.java:303)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.<init>(SQLEditor.java:4050)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$MultiTabsQueryResultsContainer.<init>(SQLEditor.java:4449)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$MultiTabsQueryProcessor.createQueryResultsContainer(SQLEditor.java:3905)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.createResultsProvider(SQLEditor.java:3609)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryProcessor.<init>(SQLEditor.java:3601)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$MultiTabsQueryProcessor.<init>(SQLEditor.java:3899)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.createQueryProcessor(SQLEditor.java:3442)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.createResultTabs(SQLEditor.java:1317)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.createPartControl(SQLEditor.java:1025)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:977)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:939)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:312)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:90)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:59)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:711)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1389)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:84)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4814)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:206)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:131)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:73)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:168)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:187)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.lambda$28(StackRenderer.java:1160)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1184)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1169)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:841)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3259)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1898)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:333)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:291)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:648)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:608)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1459)
```

!ENTRY org.eclipse.equinox.event 4 0 2024-08-29 10:38:07.713
!MESSAGE Exception while dispatching event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/ElementContainer/selectedElement/SET] {ChangedElement=org.eclipse.e4.primaryDataStack=org.eclipse.e4.ui.model.application.ui.basic.impl.PartStackImpl@d2708a7 (tags: [org.eclipse.e4.primaryDataStack, EditorStack, active], contributorURI: null) (widget: CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@194b1ad7], renderer: org.jkiss.dbeaver.ui.e4.DBeaverStackRenderer@5cfe28e1, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null), org.eclipse.e4.data={ChangedElement=org.eclipse.e4.primaryDataStack=org.eclipse.e4.ui.model.application.ui.basic.impl.PartStackImpl@d2708a7 (tags: [org.eclipse.e4.primaryDataStack, EditorStack, active], contributorURI: null) (widget: CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@194b1ad7], renderer: org.jkiss.dbeaver.ui.e4.DBeaverStackRenderer@5cfe28e1, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null), AttName=selectedElement, EventType=SET, OldValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@216372b7 (tags: [Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor, active], contributorURI: null) (widget: ContributedPartRenderer$1 {} [layout=FillLayout {type=SWT.VERTICAL}], renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@4cc28ad0, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: CompatibilityPart [partId=org.eclipse.e4.ui.compatibility.editor, properties=[], tags=[Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor, active], wrapped=class org.jkiss.dbeaver.ui.editors.sql.SQLEditor, legacyPart=class org.jkiss.dbeaver.ui.editors.sql.SQLEditor, beingDisposed=false, alreadyDisposed=false], context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.jkiss.dbeaver.ui.editors.sql.SQLEditor (<redacted> Script-87) Context, variables: [], label: <redacted> Script-87, iconURI: platform:/plugin/org.jkiss.dbeaver.model/icons/tree/script.png, tooltip: null, dirty: false, closeable: true, description: null), Widget=CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@194b1ad7], NewValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@14b4340c (tags: [Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor], contributorURI: null) (widget: ContributedPartRenderer$1 {} [layout=FillLayout {type=SWT.VERTICAL}], renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@4cc28ad0, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: null, context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.jkiss.dbeaver.ui.editors.sql.SQLEditor (<redacted> Script-138) Context, variables: [], label: <redacted> Script-138, iconURI: platform:/plugin/org.jkiss.dbeaver.model/icons/tree/script.png, tooltip: null, dirty: false, closeable: true, description: null)}, AttName=selectedElement, EventType=SET, OldValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@216372b7 (tags: [Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor, active], contributorURI: null) (widget: ContributedPartRenderer$1 {} [layout=FillLayout {type=SWT.VERTICAL}], renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@4cc28ad0, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: CompatibilityPart [partId=org.eclipse.e4.ui.compatibility.editor, properties=[], tags=[Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor, active], wrapped=class org.jkiss.dbeaver.ui.editors.sql.SQLEditor, legacyPart=class org.jkiss.dbeaver.ui.editors.sql.SQLEditor, beingDisposed=false, alreadyDisposed=false], context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.jkiss.dbeaver.ui.editors.sql.SQLEditor (<redacted> Script-87) Context, variables: [], label: <redacted> Script-87, iconURI: platform:/plugin/org.jkiss.dbeaver.model/icons/tree/script.png, tooltip: null, dirty: false, closeable: true, description: null), Widget=CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@194b1ad7], NewValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@14b4340c (tags: [Editor, removeOnHide, org.jkiss.dbeaver.ui.editors.sql.SQLEditor], contributorURI: null) (widget: ContributedPartRenderer$1 {} [layout=FillLayout {type=SWT.VERTICAL}], renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@4cc28ad0, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: null, context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.jkiss.dbeaver.ui.editors.sql.SQLEditor (<redacted> Script-138) Context, variables: [], label: <redacted> Script-138, iconURI: platform:/plugin/org.jkiss.dbeaver.model/icons/tree/script.png, tooltip: null, dirty: false, closeable: true, description: null)} to handler org.eclipse.e4.ui.services.internal.events.UIEventHandler@f7bad57
!STACK 0
org.eclipse.swt.SWTError: No more handles
...

```
!ENTRY org.eclipse.ui 4 0 2024-08-29 10:38:09.034
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
```
```
!ENTRY org.eclipse.ui 4 0 2024-08-29 10:38:09.035
!MESSAGE Error occurred during status handling
!STACK 0
org.eclipse.swt.SWTError: No more handle
```
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-08-29 10:38:09.037
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-08-29 10:38:09.037
!MESSAGE No more handles
!STACK 0
org.eclipse.swt.SWTError: No more handles
```
```
!ENTRY org.eclipse.ui 4 0 2024-08-29 10:38:10.295
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
```
```
!ENTRY org.jkiss.dbeaver.model 4 0 2024-08-29 10:38:10.298
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-08-29 10:38:10.298
!MESSAGE No more handles
!STACK 0
org.eclipse.swt.SWTError: No more handles
```

### DBeaver Version

Community Edition 24.1.5

### Operating System

Windows 10 22H2 Build 19045.4651

### Additional context

dbeaver.ini:

```
-startup
plugins/org.jkiss.dbeaver.launcher_1.0.11.202408181605.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.1000.v20240507-1834
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Dosgi.requiredJavaVersion=17
-Dfile.encoding=UTF-8
--add-modules=ALL-SYSTEM
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.nio.charset=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.nio.fs=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
--add-opens=java.base/sun.security.action=ALL-UNNAMED
--add-opens=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.jgss=ALL-UNNAMED
--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.sql/java.sql=ALL-UNNAMED
-Xms64m
-Xmx1024m
-Ddbeaver.distribution.type=zip
-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
```

org.jkiss.dbeaver.core.prefs

```
SQLEditor.ContentAssistant.auto.activation.enable=false
SQLEditor.ContentAssistant.auto.keystrokes.activation=false
SQLEditor.ContentAssistant.autocompletion.tab=false
SQLEditor.ContentAssistant.insert.single.proposal=false
SQLEditor.Highlighting.advanced.enable=false
SQLEditor.autoSaveOnClose=true
SQLEditor.format.activeQuery=false
dataformat.profile.country=US
dataformat.profile.language=en
dataformat.type.number.useGrouping=false
driver.selector.orderBy=score
eclipse.preferences.version=1
org.jkiss.dbeaver.core.confirm.drop_sql=always
sample.database.canceled=true
tipOfTheDayInitializer.notFirstRun=true
ui.auto.update.check.time=1724163044610
```

**Comment by Destrolaric** [comment]
@cowbert Hi, how many windows do you have open. It really might be an issue with the amount of native resources taken by them.

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
