### ISSUE TITLE
Suddenly can't connect to MS Access database

### ISSUE THREAD

**Issue by horacebischoff** [dbeaver/dbeaver#35418]
### Description

I have an MS Access database, and I'm on Ubuntu 22.04. I was able to connect to and interact with it (run queries, browser Data, view diagram, etc.) in DBeaver two days ago with no issues. 

Today, it **can** connect, but when I click the arrow to show the database objects I get this:
![image](https://github.com/user-attachments/assets/2a8eeb63-e7b5-4a99-bb0c-cbb9dc2bfa91)

The error message doesn't give me any information as to what the problem is.

I received this .mdb file in a .zip. I extracted the .mdb file again into a different folder, and DBeaver can interact with that version with no issues. I don't understand why it can't interact with the original version.

### DBeaver Version

Version 24.1.5.202408181605

### Operating System

Ubuntu 22.04

### Database and driver

Database: MS Access (unknown version)
Driver: ucanaccess

### Steps to reproduce

1. click new > DBeaver > Database Connection > Next
2. Select MS Access (UCanAccess)
3. In the path, select the .mdb file & click finish (it has no password)
4. In the database navigator, click the arrow next to the "FILE.mdb" to try to expand out the Tables/Views/etc.
5. observe the "error" message in the screenshot.

**Comment by MashaKorax** [comment]
Can you please provide log files, as described here? https://github.com/dbeaver/dbeaver/wiki/Log-files#dbeaver-log-files

**Comment by horacebischoff** [comment]
Here is the log:

2024-09-06 23:12:30.845 - DBeaver 24.2.0.202409011551 is starting
2024-09-06 23:12:30.845 - OS: Linux 6.8.0-40-generic (amd64)
2024-09-06 23:12:30.845 - Java version: 17.0.6 by Eclipse Adoptium (64bit)
2024-09-06 23:12:30.845 - Install path: '/snap/dbeaver-ce/322/usr/share/dbeaver-ce'
2024-09-06 23:12:30.845 - Instance path: 'file:/home/bob/snap/dbeaver-ce/322/.local/share/DBeaverData/workspace6/'
2024-09-06 23:12:30.846 - Memory available 127Mb/1024Mb
2024-09-06 23:12:30.854 - Create display
2024-09-06 23:12:30.946 - Initialize desktop platform...
2024-09-06 23:12:31.198 - BounceCastle bundle found. Use JCE provider BC
> Start Core File Systems [org.eclipse.core.filesystem 1.10.400.v20240426-1040]
> Start Core Resource Management [org.eclipse.core.resources 3.20.200.v20240513-1323]
> Start Team Support Core [org.eclipse.team.core 3.10.400.v20240413-1529]
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.138.202409011551]
2024-09-06 23:12:31.325 - Initialize base platform...
2024-09-06 23:12:31.338 - Platform initialized (392ms)
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.138.202409011551]
2024-09-06 23:12:31.362 - Starting instance server at http://localhost:33605
2024-09-06 23:12:31.373 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.17.400.v20240425-0840]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.4.400.v20240413-1529]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.6.300.v20231201-1637]
> Start Eclipse e4 Progress View [org.eclipse.e4.ui.progress 0.4.400.v20240424-0956]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.14.400.v20240321-1245]
> Start Eclipse e4 core commands [org.eclipse.e4.core.commands 1.1.400.v20240424-0444]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.37.0.v20231208-1346]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.14.400.v20240424-0956]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.5.400.v20240416-0658]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.16.400.v20240418-1547]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.18.300.v20240413-1529]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.15.400.v20240321-1245]
> Start Eclipse SDK Themes [org.eclipse.ui.themes 1.2.2400.v20240213-1133]
> Start Default Text Editor [org.eclipse.ui.editors 3.17.300.v20240524-2010]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.17.400.v20240524-2010]
2024-09-06 23:12:32.276 - Configure workbench window
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.128.202409011551]
2024-09-06 23:12:32.370 - Total database drivers: 118 (118)
> Start Help System Core [org.eclipse.help 3.10.400.v20240415-0528]
2024-09-06 23:12:32.410 - Create actions
2024-09-06 23:12:32.414 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2024-09-06 23:12:32.414 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2024-09-06 23:12:32.414 - Disable Eclipse action set 'org.eclipse.ui.actionSet.openFiles'
2024-09-06 23:12:32.414 - Create workbench actions
2024-09-06 23:12:32.696 - Initialize workbench window
2024-09-06 23:12:32.699 - Finish initialization
> Start Internet Connection Management UI [org.eclipse.ui.net 1.5.400.v20240413-1529]
> Start Internet Connection Management [org.eclipse.core.net 1.5.400.v20240413-1529]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.138.202409011551]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.138.202409011551]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.175.202409011551]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.144.202409011551]
> Start GEF Classic Draw2d [org.eclipse.draw2d 3.16.0.202405290843]
> Start GEF Classic GEF (MVC) [org.eclipse.gef 3.18.0.202405290843]
> Start DBeaver ERD UI [org.jkiss.dbeaver.erd.ui 3.0.98.202409011551]
> Start DBeaver ERD Model [org.jkiss.dbeaver.erd.model 1.0.98.202409011551]
> Start DBeaver Dashboard UI [org.jkiss.dbeaver.ui.dashboard 1.0.135.202409011551]
> Start DBeaver Dashboards Model [org.jkiss.dbeaver.model.dashboard 1.0.11.202409011551]
2024-09-06 23:12:34.055 - Node 'msaccess_ucanaccess-191a98df871-34518025b79c4632' not found in parent node 'node://General/datasources'.
Allowed children: [MTG.mdb [MS Access (UCanAccess)]]
2024-09-06 23:12:34.056 - Node node://General/datasources/msaccess_ucanaccess-191a98df871-34518025b79c4632 not found for browse view
2024-09-06 23:12:34.056 - Connect with 'MTG.mdb' (msaccess_ucanaccess-191a99276f8-b0e946734cffe03)
> Start DBeaver JDBC Model [org.jkiss.dbeaver.model.jdbc 1.0.31.202409011551]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.224.202409011551]
2024-09-06 23:12:34.091 - Execution context opened (MTG.mdb; Main; 0)
2024-09-06 23:12:34.382 - Node 'msaccess_ucanaccess-191a98df871-34518025b79c4632' not found in parent node 'node://General/datasources'.
Allowed children: [MTG.mdb [MS Access (UCanAccess)]]
2024-09-06 23:12:34.382 - Node node://General/datasources/msaccess_ucanaccess-191a98df871-34518025b79c4632 not found for browse view
2024-09-06 23:12:36.096 - Open [https://dbeaver.io/product/version.xml]
2024-09-06 23:12:40.151 - Catalog list not supported: Feature not supported.
2024-09-06 23:12:40.152 - Can't read schema list: Feature not supported.
2024-09-06 23:12:40.156 - Connected (msaccess_ucanaccess-191a99276f8-b0e946734cffe03, Ucanaccess [5.0.1])
2024-09-06 23:12:41.701 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view qLatestNTR : object name already exists: ID in statement [CREATE VIEW QLATESTNTR AS  select  *  FROM Objects INNER JOIN Nontraditional ON Objects.CardID=Nontraditional.ID WHERE Objects.SetID=769 AND Objects.Object=3 ORDER BY Nontraditional.Name, Objects.LangID]
2024-09-06 23:12:41.701 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view qLatestCards : object name already exists: ID in statement [CREATE VIEW QLATESTCARDS AS  select  *  FROM Objects INNER JOIN Oracle ON Objects.CardID=Oracle.ID WHERE Objects.SetID=876 And Objects.Object=1 ORDER BY Oracle.Name, Objects.Version, Objects.LangID]
2024-09-06 23:12:41.701 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view qOraclePart : user lacks privilege or object not found: FROM
2024-09-06 23:12:41.701 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view Gatherer_Changed_Text : object name already exists: TEXT in statement [CREATE VIEW GATHERER_CHANGED_TEXT AS  select Name,Text,Text  FROM Z_GathererNew AS GN, Z_GathererOld AS GO WHERE GN.Name=GO.Name AND (GN.Text<>GO.Text) ORDER BY GN.Name]
2024-09-06 23:12:41.702 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view Rulings_Changed : object name already exists: ORCLID in statement [CREATE VIEW RULINGS_CHANGED AS  select  *  FROM Z_RulingsNew AS GN, Z_RulingsOld AS GO WHERE GN.OrclID=GO.OrclID AND GN.Gatherer<>GO.Gatherer]
2024-09-06 23:12:41.702 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view Gatherer_Changed_Cost : object name already exists: COST in statement [CREATE VIEW GATHERER_CHANGED_COST AS  select Name,Cost,Cost  FROM Z_GathererNew AS GN, Z_GathererOld AS GO WHERE GN.Name=GO.Name AND (GN.Cost<>GO.Cost) ORDER BY GN.Name]
2024-09-06 23:12:41.702 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view qMergeDiff : unexpected token: ]
2024-09-06 23:12:41.702 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load view qFillFrameType : user lacks privilege or object not found: OBJECTS.FRAMETYPE
2024-09-06 23:12:41.702 - SQL Warning (DataSource: MTG.mdb; Code: 0; State: null): Cannot load procedure oUpdate_NE_BL user lacks privilege or object not found: DLOOKUP in statement [UPDATE Objects
SET Name = DLookup('Name','Objects','CardID=' || CardID || 'AND SetID=786 AND LangID=' || LangID), Type = DLookup('Type','Objects','CardID=' || CardID || 'AND SetID=786 AND LangID=' || LangID)
WHERE Rarity='L' AND LangId<>1 AND SetId=889;]
> Start DBeaver UI Editors - Connections [org.jkiss.dbeaver.ui.editors.connection 1.0.129.202409011551]
> Start DBeaver Generic UI Plug-in [org.jkiss.dbeaver.ext.generic.ui 1.0.114.202409011551]
2024-09-06 23:13:34.044 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2024-09-06 23:16:07.955 - Connect with 'MTG.mdb 2' (msaccess_ucanaccess-191ca790333-1c12cd93ef18f3ec)
2024-09-06 23:16:07.955 - Execution context opened (MTG.mdb 2; Main; 1)
2024-09-06 23:16:08.031 - UCAExc:::5.0.1 /mnt/easystore_shared/docs/mtg/MTG.mdb
org.jkiss.dbeaver.model.exec.DBCConnectException: UCAExc:::5.0.1 /mnt/easystore_shared/docs/mtg/MTG.mdb
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:267)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:160)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:121)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:125)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:92)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1406)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1276)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1061)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:122)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2414)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:159)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:226)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::5.0.1 /mnt/easystore_shared/docs/mtg/MTG.mdb
	at net.ucanaccess.jdbc.UcanaccessDriver.connect(UcanaccessDriver.java:231)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	... 25 more
Caused by: java.nio.file.AccessDeniedException: /mnt/easystore_shared/docs/mtg/MTG.mdb
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at java.base/java.nio.channels.FileChannel.open(Unknown Source)
	at com.healthmarketscience.jackcess.impl.DatabaseImpl.openChannel(DatabaseImpl.java:507)
	at com.healthmarketscience.jackcess.impl.DatabaseImpl.open(DatabaseImpl.java:395)
	at com.healthmarketscience.jackcess.DatabaseBuilder.open(DatabaseBuilder.java:267)
	at net.ucanaccess.jdbc.DefaultJackcessOpener.open(DefaultJackcessOpener.java:37)
	at net.ucanaccess.jdbc.DBReference.<init>(DBReference.java:171)
	at net.ucanaccess.jdbc.DBReferenceSingleton.loadReference(DBReferenceSingleton.java:51)
	at net.ucanaccess.jdbc.UcanaccessDriver.connect(UcanaccessDriver.java:91)
	... 28 more
2024-09-07 09:33:39.419 - Execution context closed (MTG.mdb, 0)
2024-09-07 09:33:39.420 - Disconnected (msaccess_ucanaccess-191a99276f8-b0e946734cffe03)

**Comment by ivgag** [comment]
Perhaps, the root cause of the issue is the lack of permission to read the database file since the log has `java.nio.file.AccessDeniedException`—no Dbeaver fault.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
