### ISSUE TITLE
How to disable the dump progress output

### ISSUE THREAD

**Issue by lionslair** [dbeaver/dbeaver#35421]
### Description

The scrolling dump progress output in 24.2.0 appears to break exports on all databases for me

mysqldump: Got errno 32 on write

Task 'MySQL dump' finished at Mon Sep 02 08:38:46 AWST 2024
2024-09-02 08:38:46.607 - IO error: Process failed (exit code = 5). See error log.
2024-09-02 08:38:46.607 - java.io.IOException: Process failed (exit code = 5). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

### DBeaver Version

CE 24.2.0

### Operating System

pop os 22.04

### Database and driver

mysqldump  Ver 10.19 Distrib 10.6.18-MariaDB, for debian-linux-gnu (x86_64)

### Steps to reproduce

connect to database
Export database to file

### Additional context

mysqldump: Got errno 32 on write

Task 'MySQL dump' finished at Mon Sep 02 08:38:46 AWST 2024
2024-09-02 08:38:46.607 - IO error: Process failed (exit code = 5). See error log.
2024-09-02 08:38:46.607 - java.io.IOException: Process failed (exit code = 5). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

**Comment by serge-rider** [comment]
Probably it is a side effect of #34926

**Comment by E1izabeth** [comment]
@lionslair thannk you for bug report. Does it happen on any table? Or only on the specific ones? What settings have you set on Export configuration page in MySQL dump wizard?

**Comment by lionslair** [comment]
Tried multiple different databases and all are doing the same thing. I had to rollback to previous version to continue working

**Comment by lionslair** [comment]
> Probably it is a side effect of #34926

Tried that too and same output
