### ISSUE TITLE
Default Context not found

### ISSUE THREAD

**Issue by JoBuCa** [dbeaver/dbeaver#35495]
### Description

We are trying to export approx. 1000 tables from an Oracle Database into SQL Server. Before the process starts the Wizard stops working. The Wizard freezes at some point and stops working. In the log window I can see a message "Default Context not found"

![image](https://github.com/user-attachments/assets/f6bbbef5-152a-48d0-a310-c8f2fd3638c5)

### DBeaver Version

Community Edition 24.1.4

### Operating System

Windows

### Database and driver

Oracle JDBC driver 23.2.0.0.0
Oracle Oracle Database 10.2.0.4.0 

### Steps to reproduce

1. Create an new Data Export task
2. Select the tables 
3. Select database and target container -> Then it will take a lot of time and the Wizard stops working as shown in the screenshot

### Additional context

When selecting less tables e.g. 20 tables it will work without any issues.

**Comment by E1izabeth** [comment]
Your screenshot shows that the wizard is still loading table information. The information about the current state says, "Sorting table list: Load SynonymCache." Also, there is an error message that says, "Set all tables mappings." Probably not all tables are loaded, or some mappings haven't been set automatically and require your attention.

![image](https://github.com/user-attachments/assets/e2600392-a8d3-42d2-96dd-b40ae68169b3)

**Comment by E1izabeth** [comment]
Please send us log files. You can collect them to archive automatically with `Help->Collect Diagnostic Info`
![image](https://github.com/user-attachments/assets/51c7ca2e-6be2-489e-b495-028b9aa0e386)

**Comment by JoBuCa** [comment]
Thanks for your reply. The popup dialog is frozen. I am not able to click on anything. It stays in the status of my first screenshot. I can only stop it using the task manager. There is no process active, no network activity anymore which I can monitor. I run it for 5 days but nothing changed, so I guess that it stopped working. Is there anything I can check or test?

**Comment by E1izabeth** [comment]
You can find log files on your file system.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory.
Here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)
Thank you.

**Comment by JoBuCa** [comment]
Thanks for your reply. It produces log files with almost the same message during displaying the "Sorting table list: Load SynonymCache" status -> is there a specific setting available where I can set the Default Context?

```
2024-10-07 12:41:24.175 - org.jkiss.dbeaver.model.exec.DBCException: Default context not found
	at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1694)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:300)
	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:1016)
	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:122)
	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.getAssociations(OracleTable.java:346)
	at org.jkiss.dbeaver.model.struct.DBStructUtils.sortTableList(DBStructUtils.java:275)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.sortDataPipes(DataTransferSettings.java:537)
	at org.jkiss.dbeaver.tools.transfer.ui.pages.database.DatabaseConsumerPageMapping.lambda$12(DatabaseConsumerPageMapping.java:1000)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

**Comment by E1izabeth** [comment]
Hi, @JoBuCa! We tried a lot but failed to reproduce this issue. Could you please reproduce the issue once again? After you reproduce the issue, please send us the DBeaver log files.
The log files are generated automatically and called .log and .dbeaver-debug.log exactly. They are located in the %APPDATA%\DBeaverData\workspace6\\.metadata directory. In case your OS isn't Windows, here is our wiki page on this matter: [dbeaver.com/docs/wiki/Log-files/#log-files](http://dbeaver.com/docs/wiki/Log-files/#log-files)

Also, a thread dump would be very useful. Could you please generate a thread dump and attach it here? Here is the instruction: https://dbeaver.com/docs/wiki/Making-a-thread-dump/

Thank you.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide thread dump.

**Comment by JTMosaic** [comment]
I'm experiencing this as well. The error pops up when clicking on objects in the tree

2025-09-11 10:00:01.033 - Default context not found
org.jkiss.dbeaver.model.exec.DBCException: Default context not found
	at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1727)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:111)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:76)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:157)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:1057)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1129)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:664)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:475)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:229)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:94)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

[dbeaver_thread_dump.txt](https://github.com/user-attachments/files/22277762/dbeaver_thread_dump.txt)

**Comment by liosc** [comment]
Having the same problem trying to refresh table list.

<img width="609" height="210" alt="Image" src="https://github.com/user-attachments/assets/65650ab2-f6b9-4174-9686-bec36dd02e65" />

**Comment by SolovevAnton** [comment]
Thank you for your report. Could you please download the latest EA version and see if the issue is gone there?
https://dbeaver.com/files/ea/

**Comment by liosc** [comment]
It has been a while. I already updated the version, maybe more than one time. The issue seems solved. Thanks.

**Comment by E1izabeth** [comment]
Thanks! That's a good news!
