### ISSUE TITLE
Column Search throws NullPointerException

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#3550]
In Table Property Page Search column name throws NullPointerException

**Comment by serge-rider** [comment]
Can't reproduce. Please post error stacktrace (you can get it in Error Log view or in log file: https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by ramrasi** [comment]
![image](https://user-images.githubusercontent.com/6615196/40902725-a1882378-67f2-11e8-9eae-2ae1b341d229.png)

![image](https://user-images.githubusercontent.com/6615196/40902863-135cf654-67f3-11e8-9d46-5d3396fa44ce.png)



!ENTRY org.eclipse.ui 4 4 2018-06-04 12:27:01.064
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.NullPointerException
        at org.jkiss.dbeaver.ui.controls.ProgressPageControl.performSearch(ProgressPageControl.java:492)
        at org.jkiss.dbeaver.ui.controls.ProgressPageControl$3.runInUIThread(ProgressPageControl.java:397)
        at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:160)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
(END)

**Comment by serge-rider** [comment]
Thanks, now I can reproduce it.

Workaround: click on some column (or in empty space in column list) and then perform search .

**Comment by ramrasi** [comment]
Thanks a lot.
