### ISSUE TITLE
Unable to link folder

### ISSUE THREAD

**Issue by jgfet** [dbeaver/dbeaver#3565]
Bug occurred when trying to connect to remote drive
I have MBP with High Sierra.
On it is a VMWare Fusion setup with Windows 2012 RC2 where the IDE resides.
I am able to connect out to Dropbox via a Shared folder.
However when I try and create link to shared folder it bombs.
To me it looks like there is an OS bug - trying to reference Windows paths as Unix..

> /RemoteSystemsTempFiles/Scripts 

```
Unable to link folder F/RemoteSystemsTempFiles/Scripts with location [Ljava.nio.file.Path;@37b70b7c
	at org.jkiss.dbeaver.runtime.ide.ui.handlers.CreateLinkHandler$1.execute(CreateLinkHandler.java:85)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.runtime.internal.ide.core.CreateLinkedFoldersRunnable.createLink(CreateLinkedFoldersRunnable.java:50)
	at org.jkiss.dbeaver.runtime.internal.ide.core.CreateLinkedResourcesRunnable.run(CreateLinkedResourcesRunnable.java:67)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2224)
	at org.jkiss.dbeaver.runtime.ide.core.WorkspaceResources.createLinkedFolders(WorkspaceResources.java:69)
	at org.jkiss.dbeaver.runtime.internal.ide.ui.handlers.LinkFolderHandler.createLink(LinkFolderHandler.java:51)
	at org.jkiss.dbeaver.runtime.ide.ui.handlers.CreateLinkHandler$1.execute(CreateLinkHandler.java:79)
	... 5 more
```

```
eclipse.buildId=3.9.4.201804120921-RELEASE-e47
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide
```

```
C:\Users\administrator>java -version
Picked up _JAVA_OPTIONS: -Duser.home=C:\Users\administrator
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
spring-tool-suite-3.9.4.RELEASE-e4.7.3a-win32-x86_64.zip
DBeaver 5.1.0
C:\Users\administrator>
<img width="390" alt="screen shot 2018-06-04 at 16 53 41" src="https://user-images.githubusercontent.com/28791001/40927939-f798ac72-6817-11e8-9e21-aae134f995a9.png">
<img width="832" alt="screen shot 2018-06-04 at 16 53 04" src="https://user-images.githubusercontent.com/28791001/40927954-019c3dce-6818-11e8-907b-33f0af356573.png">

**Comment by jgfet** [comment]
Note. I have been able to create a link using Microsoft Remote Desktop using Windows 2012 RC2 out to the same Dropbox SQL folder. I can confirm things were ok with Spring Tool Suite 3.9.2 (64-bit)
Version: 3.9.2.RELEASE
Build Id: 201712210947
Platform: Eclipse Oxygen.2 (4.7.2)
With DBeaver 5.1
I think I am going to try and find the zip for that version and use in on my VM instead.
So this may be an issue for Spring Tool Suite - not the DBeaver Plugin itself.

**Comment by jgfet** [comment]
Well it's odd. I added same older STS version, and I get same issue. Must be something about Eclipse getting confused over VMWare Share vs Microsoft Remote Desktop Share.. Any pointers welcome...

**Comment by jgfet** [comment]
From doing a bit of digging I see that the workspace folder contains a .project file in the RemoteSystemTempFiles folder.
That has a name and location that appears to be set. But the system doesn't seem to be able to read it again when you reload Eclipse.

**Comment by jgfet** [comment]
Whilst my Microsoft Remote Desktop session appear to work earlier, it is now exhibiting the same behaviour. I also can't even link a local Directory like the Desktop either...

**Comment by serge-rider** [comment]
I'm not sure that it is even possible to link remote folder in Eclipse (e.g. in Java IDE).
I.e. you can do this but then you can't see that folder contents.

I've fixed the bug with NPE but don't know how to handle remote folders so far..
