### ISSUE TITLE
Provide means to disable the dictionary view when editing a column that is an association

### ISSUE THREAD

**Issue by jassuncao** [dbeaver/dbeaver#35671]
When using the grid view and a cell that is a foreign key is selected, the value panel will be filled with possible values. The values seem to be retrieved using a background task/query that can have a serious impact if the target the association has a large number of rows due to the type of query used.
A production server was severely impacted when dbeaver executed the following query in a table with a few millions of rows, in this case due to the order by desc.
`SELECT id dbvrvalue, id FROM tzc_corerepository."transaction" WHERE id < $1 ORDER BY id DESC`

**Describe the solution you'd like**
A option to disable this feature when the column in question is an association.

**Comment by E1izabeth** [comment]
Thank you for request

**Comment by kczx3** [comment]
This is HUGE.  It ends up running multiple queries that can return hundreds of millions, if not billions of rows of data.  This is just not realistic to have for large systems.

**Comment by E1izabeth** [comment]
@jassuncao @kczx3 
For now, we can't reproduce the issue. Please provide clear steps to reproduce it, at least table DDL, and tell us what database it is.

**Comment by jassuncao** [comment]
Consider the following tables in PostgreSQL:
```
CREATE TABLE "transaction" (
	id int8 NOT NULL,	
	CONSTRAINT "PK_transaction" PRIMARY KEY (id)
);

CREATE TABLE "event" (
	id bigserial NOT NULL,
	evt_type varchar(3) NOT NULL,	
	transaction_id int8 NULL,	
	CONSTRAINT "PK_event" PRIMARY KEY (id),
	);

ALTER TABLE tzc_corerepository."event" ADD CONSTRAINT "FK_transaction_id" FOREIGN KEY (transaction_id) REFERENCES "transaction"(id) ON DELETE SET NULL;
```
And that `transaction` contains 2 millions rows.
if you edit the `transaction_id` field in a `event` using the grid view , dbeaver will try to fill the dictionary view with values from `transaction` because it will consider it a lookup table. That will trigger a `SELECT id dbvrvalue, id FROM "transaction" WHERE id < $1 ORDER BY id DESC`.

**Comment by E1izabeth** [comment]
Thank you. What database is it?

**Comment by kczx3** [comment]
In my case, it is Oracle and I have no control over the schema. I merely read from the database.

**Comment by E1izabeth** [comment]
Thanks. Will try to reproduce again

**Comment by E1izabeth** [comment]
I got the provided DDL and generated 2 million rows. However, it took less than a second for me
![image](https://github.com/user-attachments/assets/73c9a381-a449-44d7-9fa2-3b74aceca432)

**Comment by E1izabeth** [comment]
Do you have the same value for the dictionary page as me?
![image](https://github.com/user-attachments/assets/bea66efb-a6fa-4bf8-8ca5-553121346b38)

Could you send me the query from Query Manager that is executed when you open the dictionary?
It will help us understand your issue. You can open Query Manager here
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

**Comment by jassuncao** [comment]
I had the page size in the Dictionary panel settings set to 0 and this resulted in an out of memory. 
I changed the value to 200 and the out of memory didn't occur anymore. 
The auxiliary queries also run immediately:
![image](https://github.com/user-attachments/assets/57db03b8-350b-4d34-844a-6d14b70a9ffd)

When the page size was set to 0, dbeaver would try to load the entire table:

```
2025-01-09 15:30:28.381 UTC [24255] LOG:  duration: 23828.763 ms  execute <unnamed>: SELECT id dbvrvalue, id FROM tzc_corerepository."transaction" WHERE id >= $1 ORDER BY id ASC
2025-01-09 15:30:28.381 UTC [24255] DETAIL:  parameters: $1 = '162157'
```


```
Exception in thread "HTTP-Dispatcher" Exception in thread "idle-timeout-task" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Connect thread 192.168.40.60 session" java.lang.OutOfMemoryError: Java heap space
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.lambda$run$0(ServerImpl.java at jdk.httpserver/      at java.base/java.lang.Throwable.fillInStackTrace:484)
sun.net.httpserver.ServerImpl$IdleTimeoutTask.run(ServerImpl.java:1(    at java.base005)
        at java.base/java.util.TimerThreadNative Method)
        at java.base/java.lang.Throwable./java.util.Collection.toArray(.mainLoop(Timer.java:602<init>(Throwable.java:90)
Collection.java:413)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run)
        at java.base/java.util.TimerThread.     at java.base/java.lang.Throwable.<init>((ServerImpl.java:484)
        at java.base/java.lang.Threadrun(Timer.java:542)Throwable.java:101)
2025-01-09 15:32:23.406 - java.lang.OutOfMemoryError: Java heap space
.run(Thread.java:16
        at java.base/java.lang.Exception.<init>(Exception.java:java.lang.OutOfMemoryError: Java heap space
39)67)
        at java.base/
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:1java.io.IOException.<init>(IOException.java:5753)
        at org.eclipse.swt.widgets.TableItem.setText)
        at java.base/(TableItem.java:1345java.io.InterruptedIOException.)
        at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor.updateDictionarySelector(ReferenceValueEditor.java<init>(InterruptedIOException.java:63)
:500)
        at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderVisualizer      at java.base/java.net.SocketTimeoutException.<init>(SocketTimeoutException.java.completeLoading(ReferenceValueEditor.java:771:44)
        at java.base/)
        at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderVisualizer.sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:27completeLoading(ReferenceValueEditor.java:1)
        at 8)
        at java.base/sun.nio.ch.NioSocketImpl.org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(implRead(NioSocketImpl.java:304)LoadingJob.java:
128)
        at org.eclipse.swt.widgets.RunnableLock.        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:run(RunnableLock.java:40)
        at 345)
        at java.baseorg.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java2)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(:794)
        at java.baseDisplay.java:5040)
/java.net.Socket$SocketInputStream.read(Socket.java:1   at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4025)
        at com.jcraft.jsch.IO.520)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.getByte(IO.java:93)
run(PartRenderingEngine.java:1151       at com.jcraft.jsch.Session.read(Session.java:1)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java074)
        at com.jcraft.jsch.Session.:339)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEnginerun(Session.java:1643.run(PartRenderingEngine.java:10)
        at java.base/java.lang.Thread.run42)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(Thread.java:1639)(E4Workbench.java:153)

        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
JVMDUMP032I JVM requested Snap dump using '/home/jassuncao/usr/dbeaver/Snap.20250109.153033.26808.0013.trc' in response to an event

```

**Comment by kczx3** [comment]
If I run a query and then click on a value in a column that is a foreign key to a different VERY large table, it sits and loads the dictionary for several minutes.  The dictionary query doesn't show in the Query Manager though.  When I checked the dictionary query in the Background Tasks window, it looked like it was perhaps trying to get a count of all rows on the foreign table.  If that's true, and its doing a full table scan to get that count then I could see why it would take forever.  Maybe you should query table stats instead?  Just guessing

**Comment by E1izabeth** [comment]
You can check all these query types to see everything in Query Manager
![image](https://github.com/user-attachments/assets/372615f0-1d24-4452-b9cb-f42544400fef)

**Comment by kczx3** [comment]
![image](https://github.com/user-attachments/assets/fb1df195-61c3-4f29-a741-6e992d8c3052)

**Comment by E1izabeth** [comment]
Thanks

**Comment by E1izabeth** [comment]
@kczx3 could you check if you have 200 in the preferences here?
![image](https://github.com/user-attachments/assets/81ef5a6b-ec59-4431-8834-0ec556161017)

**Comment by alexyarovoy** [comment]
@E1izabeth 

I have the same issue. Clicking on a field which is a reference to a table with 90.000.000+ records halts application for several very long seconds. DB is PostgreSQL, I have setting "Maximum amount of elements" set to 200. And it would be great to at least disable this functionality.

Query Manager shows subsecond query (two queries at a time for some reason), but app halts definitely longer than that. And for some reason Query Manager shows 100 records loaded, not 200.

<img width="901" alt="image" src="https://github.com/user-attachments/assets/c749410e-5131-4dda-8ea8-7c265715cf35" />

<img width="975" alt="image" src="https://github.com/user-attachments/assets/7e3ea37b-d259-4228-b603-289d42e27b52" />

**Comment by kczx3** [comment]
@E1izabeth that setting is set to 200 for me.  It is not modified at the Datasource level.  I tried setting it to 100 at the Datasource level and it takes just as long.  This is the execution plan for the query that gets ran to load the dictionary values.

![image](https://github.com/user-attachments/assets/6ab9c366-92b5-45d8-835f-ac0e44236f7b)

If I add modify the query to include a qualification on ROWNUM then it returns very quickly.
```sql
SELECT PERSON_ID, FT_ENTITY_NAME FROM V500.PERSON WHERE PERSON_ID < 11111111 AND rownum < 100 ORDER BY PERSON_ID DESC;
```
![image](https://github.com/user-attachments/assets/ea5528db-20b5-4ce0-bfe3-202c34be309b)

Not really sure why inclusion of ROWNUM causes it to use the index as PERSON_ID is the primary key on the table.  All I think of is because of how large the table is and the primary key that we are basing on that Oracle deems a full table scan is needed.

I also tried it with `FETCH FIRST n ROWS ONLY` instead of ROWNUM but the execution plan showed high cardinality compared to ROWNUM.

**Comment by E1izabeth** [comment]
Thanks

**Comment by kczx3** [comment]
@E1izabeth Should I open another issue then to actually make the dictionary view function properly?  I see you allowed disabling of it however it seems like it would work well if a ROWNUM qualification was used (at least for Oracle databases).

**Comment by E1izabeth** [comment]
Yes, you can create a separate issue about your case
