### ISSUE TITLE
Problem with change datatype 

### ISSUE THREAD

**Issue by ramrasi** [dbeaver/dbeaver#3569]
I am Using Postgres . When i am change int4 to serial it throws an error as 

"SQL Error [42704]: ERROR: type "serial" does not exist
  Position: 77
  ERROR: type "serial" does not exist
  Position: 77
  ERROR: type "serial" does not exist
  Position: 77
"

![image](https://user-images.githubusercontent.com/6615196/40969718-48fb8116-68d6-11e8-8892-7424d5a4f21f.png)

==================================
Error Log
==================================
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-06-05 15:36:39.404
!MESSAGE ERROR: type "serial" does not exist
  Position: 77
!STACK 0
org.postgresql.util.PSQLException: ERROR: type "serial" does not exist
  Position: 77
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
        at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:46)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:178)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:95)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:298)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:288)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:954)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

=======================================
Debug log
=======================================

2018-06-05 15:36:39.400 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42704]: ERROR: type "serial" does not exist
  Position: 77
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
        at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:46)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:178)
        at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:95)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:298)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:288)
        at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:954)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.postgresql.util.PSQLException: ERROR: type "serial" does not exist
  Position: 77
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
        ... 8 more

**Comment by serge-rider** [comment]
This is not DBeaver  issue, it is PG-specific behavior: https://stackoverflow.com/questions/16474720/alter-data-type-of-a-column-to-serial

**Comment by ramrasi** [comment]
ok thanks.
