### ISSUE TITLE
Informix - open declaration for procedures fail

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#35817]
### Description

When try to open the object declaration using the F4 shortcut or ctrl+mouse click over the **procedure** name , they open the wrong object properties.
Always open the first object on the procedure tree list 

### DBeaver Version

CE 24.2.1.202409221725

### Operating System

Windows 10

### Database and driver

IBM Informix 4.50.10.1

### Steps to reproduce

1. put the cursor over the proc name and press f4 OR move the mouse cursor over the name holding ctrl and click

![image](https://github.com/user-attachments/assets/7508c099-2e81-49b1-898f-abd0642ef098)

2. They always open the first proc in the tree list , here is the internal database proc called addtoset2_combine 
 
![image](https://github.com/user-attachments/assets/269c6cf3-d757-4f45-a657-4add1537e1bf)

**Comment by E1izabeth** [comment]
Thanks for the bug report. I reproduced the issue

![image](https://github.com/user-attachments/assets/c5b92148-24f0-4f7c-8b3e-444a46d66070)
```
org.jkiss.dbeaver.DBException: Can't find procedure 'addtoset_iter' (null)' in 'informix'
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant$ProcedureReference.resolveObject(GenericStructureAssistant.java:249)
	at org.jkiss.dbeaver.ui.editors.entity.EntityHyperlink$ObjectFinder.run(EntityHyperlink.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by amivanovano** [comment]
DBeaver Version - СЕ 26.1
OS - Windows 11
Server - IDS 12.10.FC12
Driver - IBM Informix 15.0.1.2  
- the same bug
