### ISSUE TITLE
Informix -Autocomplete - insert table aliases not working

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#35816]
### Description

Since a few versions ago the autocomplete , insert table aliases stopped to work for Informix database connections.
For Oracle , SQL Server , Mysql , still working

![dbeaver automcomplete](https://github.com/user-attachments/assets/0d97ea38-a774-4f48-9862-790e9583c8b8)

### DBeaver Version

CE 24.2.1.202409221725

### Operating System

Windows 10

### Database and driver

IBM Informix 4.50.10.1

### Steps to reproduce

1. write  a simple sql like : select * from table
2. press ctrl+space to open the autocomplete window or complete automatically
3

**Comment by MashaKorax** [comment]
Thanks for your report.

**Comment by ceinmart** [comment]
Hi, I noticed this problem wasn't reproducible. 
If need any logs or active some kind of debug to get more information, please, let me know how to do and share here.

**Comment by ceinmart** [comment]
Complementing... 
What I do. 

Started dbeaver with args: `dbeaver.exe -vmargs "-Ddbeaver.trace.enabled=true"`

With a cygwin session, at folder `AppData/Roaming/DBeaverData/workspace6/.metadata` , I ran ` tail -f dbeaver-debug.log`

On dbeaver open a new SQL console, connected to the database , wrote a simple `select * from <tabname>` and completed it with ctrl+space. 

Isn't exactly in sync  , appears this error on debug log. 
Not sure if related with de probelm.

```
2024-10-07 10:50:30.832 - org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
org.jkiss.dbeaver.model.exec.DBCException: Progress sub task without start
        at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.subTask(DefaultProgressMonitor.java:97)
        at org.jkiss.dbeaver.model.runtime.DefaultProgressMonitor.startBlock(DefaultProgressMonitor.java:126)
        at org.jkiss.dbeaver.model.impl.AbstractSession.<init>(AbstractSession.java:49)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.<init>(JDBCConnectionImpl.java:53)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.createConnection(JDBCDataSource.java:416)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:241)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.openSession(JDBCExecutionContext.java:1)
        at org.jkiss.dbeaver.model.DBUtils.openMetaSession(DBUtils.java:1735)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:111)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.getObject(JDBCStructLookupCache.java:63)
        at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTable(GenericObjectContainer.java:164)
        at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant$TableReference.resolveObject(GenericStructureAssistant.java:213)
        at org.jkiss.dbeaver.ui.editors.sql.dialogs.SuggestionInformationControl$1.run(SuggestionInformationControl.java:130)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by ceinmart** [comment]
sorry, closed by accident... already reopened

**Comment by ceinmart** [comment]
Hi @E1izabeth  , 
I've recorded the issue when using the default mode, with new autocomplete works.
I want to use the new autocomplete engine, however it have other problems where I will open other case.

![dbeaver aliases](https://github.com/user-attachments/assets/2417bef4-7607-4b39-8168-5580e0aeef71)

**Comment by E1izabeth** [comment]
Thanks
