### ISSUE TITLE
postgres - java.lang.ClassNotFoundException: com.ongres.scram.common.exception.ScramException

### ISSUE THREAD

**Issue by ikzelf** [dbeaver/dbeaver#35909]
### Description

connection to postgres database using ssl and password fails. The request reaches the database server and in the postgresql.log a 'FATAL:  canceling authentication due to timeout' is written for this client.

2024-10-11 09:17:12.162 - Connect with 'jdbc:postgresql://dbserver.my.domain.nl:5432/postgres' (PostgreSQL-1927a704952-653c02c6ee0b759)
2024-10-11 09:17:12.163 - Execution context opened (jdbc:postgresql://dbserver.my.domain:5432/postgres; Main <postgres>; 21)
2024-10-11 09:17:12.164 - Initiate connection to PostgreSQL database [postgres@localhost] for Main <postgres>
2024-10-11 09:17:12.221 - com.ongres.scram.common.exception.ScramException
java.lang.ClassNotFoundException: com.ongres.scram.common.exception.ScramException
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.postgresql.core.v3.ConnectionFactoryImpl.lambda$doAuthentication$5(ConnectionFactoryImpl.java:864)
        at org.postgresql.core.v3.AuthenticationPluginManager.withPassword(AuthenticationPluginManager.java:82)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:851)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:576)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:235)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:122)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:293)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:188)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:96)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:109)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1406)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1276)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1061)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

Community Edition Version 24.2.1.202409221725

### Operating System

Microsoft Windows [Version 10.0.17763.6292]

### Database and driver

1) Postgres 15.7
2) postgresql-42.7.4 JDBC driver

### Steps to reproduce

create connection
test connection

### Additional context

using the psql client:
C:\Users\myuser>psql -h dbserver.my.domain.nl postgres testje
Password for user testje:
psql (16.3, server 15.7)
WARNING: Console code page (850) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

testje@postgres dbserver>
The psql client works as meant to be from the same host.

I am not sure where this issue belongs to. Could be dbeaver, could also be the postgres jdbc driver.

**Comment by ikzelf** [comment]
Also tested with the C:\Program Files\OpenLogic\jre-21.0.4.7-hotspot after removing the dbeaver internal jre directory.
Same error.
Since I have no idea where this problem belongs to I also opened an issue in pgjdbc [https://github.com/pgjdbc/pgjdbc/issues/3404](https://github.com/pgjdbc/pgjdbc/issues/3404)

**Comment by ikzelf** [comment]
issue solved by replacing the postgresql-42.7.4.jar with the download from https://jdbc.postgresql.org/download/postgresql-42.7.4.jar The one I got from the GitHub releases missed a few bits .....
