### ISSUE TITLE
postgres - kerberos connection fails

### ISSUE THREAD

**Issue by ikzelf** [dbeaver/dbeaver#35917]
### Description

2024-10-11 14:00:44.841 - Connect with 'jdbc:postgresql://?service=my-service&user=postgres&dbname=mydb' (PostgreSQL-1927b73e11e-68983189d2773447)
2024-10-11 14:00:44.842 - Execution context opened (jdbc:postgresql://?service=my-service&user=postgres&dbname=mydb; Main <?service=my-service&user=postgres&dbname>; 22)
2024-10-11 14:00:44.843 - Initiate connection to PostgreSQL database [?service=my-service&user=postgres&dbname@localhost] for Main <?service=my-service&user=postgres&dbname>
2024-10-11 14:00:44.898 - Configuration Error:
        No such file or directory
java.io.IOException: Configuration Error:
        No such file or directory
        at java.base/sun.security.provider.ConfigFile$Spi.init(Unknown Source)
        at java.base/sun.security.provider.ConfigFile$Spi.init(Unknown Source)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(Unknown Source)
        at java.base/sun.security.provider.ConfigFile.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at java.base/javax.security.auth.login.Configuration$2.run(Unknown Source)
        at java.base/javax.security.auth.login.Configuration$2.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/javax.security.auth.login.Configuration.getConfiguration(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext$1.run(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext.init(Unknown Source)
        at java.base/javax.security.auth.login.LoginContext.<init>(Unknown Source)
        at org.postgresql.gss.MakeGSS.authenticate(MakeGSS.java:146)
        at org.postgresql.core.v3.ConnectionFactoryImpl.lambda$doAuthentication$4(ConnectionFactoryImpl.java:833)
        at org.postgresql.core.v3.AuthenticationPluginManager.withPassword(AuthenticationPluginManager.java:82)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:832)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:576)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:235)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:122)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:293)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:188)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:96)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:109)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:115)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1406)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1276)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1061)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

Community Edition Version 24.2.1.202409221725

### Operating System

Microsoft Windows [Version 10.0.17763.6292]

### Database and driver

1) Postgres 15.7
2) postgresql-42.7.4 JDBC driver

### Steps to reproduce

configure pgservicesfile and add it to vm args ( -Dorg.postgresql.pgservicefile=\\fileserver\directory\Shared\pg_service.jdbc.conf)
configure java.security with login.config.url.1=file:c:\admin\dbeaver\java.login.config with contents
pgjdbc {
com.sun.security.auth.module.Krb5LoginModule required
doNotPrompt=true
useTicketCache=true
renewTGT=true
debug=true
client=true;
};

configure connection jdbc:postgresql://?service=my-service&user=postgres&dbname=mydb
test connection

### Additional context

using the psql binary from the same windows client:
C:\Users\myuser>psql "postgresql://?service=my-service&user=postgres&dbname=mydb"
psql (16.3, server 15.7)
WARNING: Console code page (850) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

postgres@mydb dbserver# \q
The psql client works as intended from the same windows client.

I have no idea what exactly is missing. 
I am also not sure if this is a dbeaver or pgjdbc problem (or maybe just pebkac (in that case, please enlighten me))

**Comment by ikzelf** [comment]
After installing C:\Program Files\OpenLogic\jre-21.0.4.7-hotspot\
renaming C:\Program Files\dbeaver\jre to C:\Program Files\dbeaver\no-jre
configuring %JAVA_HOME%\conf\security\java.security to include the pgjdbc login configuration the Kerberos connection started to work again.
Could it be that the included JRE is not complete?

**Comment by LonwoLonwo** [comment]
Hello @ikzelf 

First of all, we have better Kerberos support in our PRO projects: https://github.com/dbeaver/dbeaver/wiki/Kerberos-Authentication
You can try it for free: https://dbeaver.com/trial/

And about your case: Yes, it can be an issue with our JRE incompletion. We plan to update our Java to version 21. We will try to take your case into account during the migration. Thanks.

**Comment by ikzelf** [comment]
With a recent JRE I got it all up and running again.
Problem solved.
