### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by aenon83** [dbeaver/dbeaver#3591]
When I try to open dBeaver it closes right after splash screen. The last thing I did was adding a 64 bit odbc connection but I was able to log in and do some queries. I got the following log:

    !SESSION 2018-06-07 09:47:48.713 -----------------------------------------------
    eclipse.buildId=unknown
    java.version=1.8.0_77
    java.vendor=Oracle Corporation
    BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
    Command-line arguments:  -os win32 -ws win32 -arch x86_64
    
    !ENTRY org.eclipse.core.resources 2 10035 2018-06-07 09:47:49.966
    !MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
    
    !ENTRY org.jkiss.dbeaver.model 4 0 2018-06-07 09:47:52.190
    !MESSAGE Error determining server version
    !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-06-07 09:47:52.190
    !MESSAGE 
    !STACK 0
    java.lang.UnsupportedOperationException
    	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
    	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:141)
    	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:363)
    	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:395)
    	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:758)
    	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:192)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:136)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
    	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by serge-rider** [comment]
Well, this error is just a warning, I believe it appeared once you connected to ODBC database.
So issue with startup is caused by something else.
Try to delete log and restart. Also you coudl check debug log.

**Comment by aenon83** [comment]
Log:
    !SESSION 2018-06-07 13:53:50.147 -----------------------------------------------
    eclipse.buildId=unknown
    java.version=1.8.0_77
    java.vendor=Oracle Corporation
    BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
    Command-line arguments:  -os win32 -ws win32 -arch x86_64
    
    !ENTRY org.eclipse.core.resources 2 10035 2018-06-07 13:53:51.351
    !MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
    
    !ENTRY org.jkiss.dbeaver.model 4 0 2018-06-07 13:53:53.558
    !MESSAGE Error determining server version
    !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-06-07 13:53:53.558
    !MESSAGE 
    !STACK 0
    java.lang.UnsupportedOperationException
    	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
    	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:141)
    	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:363)
    	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:395)
    	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:758)
    	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:192)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:136)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
    	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
    
    Debug log:
    2018-06-07 13:53:51.002 - DBeaver 5.0.6 is starting
    2018-06-07 13:53:51.004 - Install path: 'file:/C:/Program Files (x86)/DBeaver/'
    2018-06-07 13:53:51.006 - Instance path: 'file:/C:/Users/Borja/.dbeaver4/'
    2018-06-07 13:53:51.008 - Memory available 61Mb/910Mb
    2018-06-07 13:53:51.017 - Starting RMI server at 46640
    2018-06-07 13:53:51.085 - Run workbench
    2018-06-07 13:53:52.381 - Initializing DBeaver 5.0.6
    2018-06-07 13:53:52.385 - Host plugin: org.jkiss.dbeaver.core.application 5.0.6
    2018-06-07 13:53:52.388 - Initialize Core...
    2018-06-07 13:53:52.546 - Core initialized (158ms)
    2018-06-07 13:53:52.548 - Configure workbench window
    2018-06-07 13:53:52.617 - Create actions
    2018-06-07 13:53:52.619 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
    2018-06-07 13:53:52.623 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
    2018-06-07 13:53:53.014 - Initialize workbench window
    2018-06-07 13:53:53.023 - Finish initialization
    2018-06-07 13:53:53.330 - Connect with 'ODBC - brsgestion' (odbc-163068e035a-42e2339667ae2e8a)
    2018-06-07 13:53:53.535 - Error determining server version
    java.lang.UnsupportedOperationException
    	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
    	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:141)
    	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:363)
    	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:395)
    	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:758)
    	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:192)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:136)
    	at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
    	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
    	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
    2018-06-07 13:53:53.805 - Can't get column 'TABLE_CAT': Column not found

Since the problem seems it is because of the odbc connection, there is a way to remove that connection wihout entering in the app?

**Comment by serge-rider** [comment]
If so then there is a bug in DBeaver. Any issues with connection shouldn't block app start.

Anyhow, you can edit connections without starting DBeaver. All connections configuration is stored in `${home}/.dbeaver4/General/.dbeaver-data-sources.xml` file.

**Comment by aenon83** [comment]
Anything I can help before removing the configuration?

**Comment by serge-rider** [comment]
I can't say because there could be too many reasons.

For instance maybe previous instance of DBeaver hanged out and new instance just can't start. Log file doesn't contain anything useful. Looks like DBeaver is starting and at some moment (after last warning) something happens. Is this full log?

**Comment by aenon83** [comment]
Before running the app again I deleted both logs and I printed here the content of both after it crashed. I renamed the sources.xml file to sources.xml.old and tried to run it again. It worked without problems. I close the app, rename the file again and when I click to open a connection with ODBC crashes again.

I think the problem is with the DB, it's Multibase and in Windows it requires an specific dll to use ODBC connections. Maybe the JDBC driver can't "translate" it?

**Comment by serge-rider** [comment]
Yes, this is possible. It may just crush without any notifications.

Usually, if Java process was terminated unexpectedly then there should be hs_XXX log file (near dbeaver.exe or in temporary folder). It may contain a clue what did actually happen.

**Comment by aenon83** [comment]
No, there isn't a file named like that

**Comment by serge-rider** [comment]
Thanks for details anyway. 
Unfortunately we can't isolate native ODBC drivers, any crash in native dll leads to DBeaver crash.. :(

**Comment by aenon83** [comment]
Yes, I understand it. It's a very specific database, DBeaver loaded it once, but only allowed me to launch queries and tables definitions. I couldn't use the ER Diagram or other things.

Thanks anyway
