### ISSUE TITLE
Switch presentation from Grid to Text does not work on DBeaver 5.1.0

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#3593]
DBeaver - **Version 5.1.0 CE**
DBeaver JDBC driver: **Microsoft**
Operating System: **Windows 7** / **Windows 8.1** /  **Windows 10**
Database Server: **Microsoft SQL Express 2014**

If I try to switch from **Grid** presentation to **Text** presentation, I receive an error:

&nbsp;&nbsp;**Can't switch presentation**
&nbsp;&nbsp;**Reason:**
&nbsp;&nbsp;**Widget is disposed**

This worked without any trouble in _DBeaver ver 5.0.0_

**To reproduce:**

**o** Select to view a table contents in **Grid** presentation (the default in my case)
**o** Click on the **Text** button on the _DBeaver_ statusbar.
**o** The error message above is displayed, and the presentation is not switch to **Text**.

**PS.** In case you don't get the error message, try to press **Grid**, **Text**, **Grid**, **Text**, ... until error occur.

**PPS.** Seems to be an intermitent misbehaviour. Sometimes I get the error each time I switch. Other times I can switch presentation back and forth and I hardly ever get the error.

**Comment by serge-rider** [comment]
Please post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by rzhilkibaev** [comment]
Having the same issue on DBeaver 5.1.2 CE. Happens every time you switch from Grid to Text.
```
eclipse.buildId=unknown
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/***/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/***/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Mon Jul 02 12:56:56 PDT 2018
Widget is disposed

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:800)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:589)
	at org.eclipse.swt.widgets.Tree.getSelectionCount(Tree.java:1850)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.aggregate.AggregateColumnsPanel$RemoveFunctionAction.isEnabled(AggregateColumnsPanel.java:368)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:798)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:705)
	at org.jkiss.dbeaver.ui.UIUtils.updateContributionItems(UIUtils.java:677)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateToolbar(ResultSetViewer.java:1092)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updateEditControls(ResultSetViewer.java:1079)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.clearValue(ValueViewerPanel.java:307)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:161)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.activatePanel(ValueViewerPanel.java:135)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePanel(ResultSetViewer.java:863)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.activatePanel(ResultSetViewer.java:826)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.activateDefaultPanels(ResultSetViewer.java:852)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSetViewer.java:628)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.switchPresentation(ResultSetViewer.java:690)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$8(ResultSetViewer.java:686)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$6.widgetSelected(ResultSetViewer.java:572)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by serge-rider** [comment]
Thanks for log. This bug will be fixed in the next version.
