### ISSUE TITLE
can't connect to the localhost:3306

### ISSUE THREAD

**Issue by neo952702** [dbeaver/dbeaver#35957]
### Description

localhost install  mysql 8.4.2。dbeaver cann't connect to the mysql,and the error log were:

java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:58)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:72)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:54)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:36)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:587)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:517)
	at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:412)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1334)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:153)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:969)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:513)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:121)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:96)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:123)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:118)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1406)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1276)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1061)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:109)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:122)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:87)
	at org.jkiss.dbeaver.model.DBUtils.initDataSource(DBUtils.java:2456)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:159)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:226)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:92)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

but，use navicat，beekeeper studio，tableplus all other tools could connect the database...

### DBeaver Version

Community  24.2.2.202410061621

### Operating System

macOS Sequoia 15.0.1

### Database and driver

mysql version:mysql 8.4.2

i try to use the latest connector ,but still didnt work
mysql-connector-j-9.0.0.jar
mysql-connector-j-8.4.0.jar

### Steps to reproduce

just add any new database from localhost,still can't connet..i already upload the config.

### Additional context

<img width="1476" alt="image" src="https://github.com/user-attachments/assets/d892de54-8717-414b-8bd0-241dc918801f">
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/050da279-2c37-4d69-a7e6-1a5333344cb9">
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/17bab9ee-38b2-4a82-98f2-5ceaab4dc850">
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/f1aeaf2c-864c-4a74-9071-446853d04ce1">
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/7e49dbeb-f661-45df-a340-b801c3c0854d">
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/224e32ef-cf84-4f35-87bb-d5f6b0258ba0">
<img width="1490" alt="image" src="https://github.com/user-attachments/assets/311339b4-07cd-4ed5-9c81-77e6ca480d4b">
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/9d9fbe6c-8443-41b6-99c1-e73ddf6b00ce">

**Comment by ShadelessFox** [comment]
Hello @neo952702,

Why did you change all these bold properties in the driver properties? Are these changes necessary?

Please ensure the hostname and port are correct, as well as the credentials. Additionally, please provide a screenshot of the Main page.

Are you connecting to a MySQL database using a MySQL driver? Are you sure your database is not a MariaDB?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide answers to our questions.
