### ISSUE TITLE
[Oracle] 'SQL command not properly ended' when execute query with AS in alias

### ISSUE THREAD

**Issue by EvgeniaBzzz** [dbeaver/dbeaver#35952]
### Description

Execute query with AS in FROM clause.
It works as expected without AS.

![image](https://github.com/user-attachments/assets/88c8fc17-9c3a-4458-afdf-bb46a54981a7)

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [933] [42000]: ORA-00933: SQL command not properly ended


	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:631)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:522)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:541)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:1001)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4231)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5160)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended


	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:702)

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)

	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1335)

	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)

	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)

	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:533)

	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:176)

	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:1050)

	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1318)

	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1197)

	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1721)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1518)

	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2557)

	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2506)

	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:334)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:332)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)

	... 12 more

Caused by: Error : 933, Position : 35, SQL = SELECT

  *

FROM

  EVGENIA.USERS AS u, Original SQL = SELECT

  *

FROM

  EVGENIA.USERS AS u, Error Message = ORA-00933: SQL command not properly ended


	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)

	... 28 more

```

### DBeaver Version
24.2.3

**Comment by TB-HunBoka** [comment]
Having **as** for table alias is illegal on Oracle servers. It is allowed on many other servers like MySQL, Postgre..., but not on Oracle. Simple remove the **as** from the query.

Source:
https://www.techonthenet.com/oracle/alias.php#:~:text=table_name%20alias_name
