### ISSUE TITLE
SQL Error: Value Outside of Valid Range for java.lang.Long in DBeaver

### ISSUE THREAD

**Issue by 3ks** [dbeaver/dbeaver#36034]
### Description

I encountered an error when selecting my database in DBeaver. The error log indicates that a value is outside the valid range for the type java.lang.Long.

### DBeaver Version

CE24.2.3

### Operating System

Windows10 24H1

### Database and driver

MySQL 8.0.2
Driver JDBC mysql-connector-j-9.1.0

### Steps to reproduce

1. connection db with driver
2. select my db
3. see error

!ENTRY org.jkiss.dbeaver.model 4 0 2024-10-23 12:15:55.394
!MESSAGE SQL 错误 [22003]: Value '18,446,744,080,552,116,223' is outside of valid range for type java.lang.Long
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-10-23 12:15:55.394
!MESSAGE Value '18,446,744,080,552,116,223' is outside of valid range for type java.lang.Long
!STACK 0
com.mysql.cj.exceptions.NumberOutOfRange: Value '18,446,744,080,552,116,223' is outside of valid range for type java.lang.Long
at com.mysql.cj.result.LongValueFactory.createFromBigDecimal(LongValueFactory.java:71)
at com.mysql.cj.result.LongValueFactory.createFromBigDecimal(LongValueFactory.java:44)
at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDecimal(MysqlTextValueDecoder.java:154)
at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:124)
at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:244)
at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1266)
at com.mysql.cj.jdbc.result.ResultSetImpl.getLong(ResultSetImpl.java:852)
at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getLong(JDBCResultSetImpl.java:380)
at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getDatabaseSize(MySQLCatalog.java:278)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$1(ObjectPropertyDescriptor.java:431)
at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.lambda$2(ObjectPropertyDescriptor.java:450)
at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:448)
at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstractPropertyValueLoadService.evaluate(PropertySourceAbstract.java:383) at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstractPropertyValueLoadService.evaluate(PropertySourceAbstract.java:383)atorg.jkiss.dbeaver.runtime.properties.PropertySourceAbstractPropertyValueLoadService.evaluate(PropertySourceAbstract.java:1)
at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

![image](https://github.com/user-attachments/assets/cb60c877-8706-4879-9b46-29eae816cfba)

### Additional context

I am using the latest JDBC driver version 9.1.0.
The error log does not contain specific table or column names.

18,446,744,080,552,116,223 does exceed the upper limit of Long, but I don't know where this value comes from, and heidisql works fine

Could you please provide guidance on how to troubleshoot this issue further? Specifically, if I can obtain more detailed information such as table or column names, how should I proceed to resolve this problem?

Thank you for your assistance.

**Comment by E1izabeth** [comment]
IF you encounter it again or can reproduce it, please perform the following steps. It will help us understanding your issue
1. Open Query Manager
![image](https://github.com/user-attachments/assets/f505f676-a578-4af2-a786-ba6c1273c17f)

2. Turn on showing of all types of queries 
![image](https://github.com/user-attachments/assets/8065c206-dad8-4457-b597-daeb1c2f0616)

3. Identify failed query (it's highlighted with red) and send to us. The log says that the issue happen when DBeaver execute the query. Probably, it's some of the queries for fetching metadata information

**Comment by 3ks** [comment]
Thank you very much for your suggestion. I successfully found the problematic SQL:

```
SELECT SUM((DATA_LENGTH+INDEX_LENGTH)) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dhg'
```

<img width="722" alt="352ea25547bb387738fc6206fab6b74" src="https://github.com/user-attachments/assets/be55f5e0-f048-4d90-b318-a90fb08930c7">


Executing the SQL directly does not cause an error; there is only a warning when opening the database.

<img width="657" alt="f79d57038b9d9494054cb80c7b100c0" src="https://github.com/user-attachments/assets/545ae61f-ac36-4a00-80ae-ffd6a3205096">


This doesn't seem to affect my normal use of the database. I hope this information can help you locate the issue.

![8a7fdd74538c1a1f798b2d85b55e6c5](https://github.com/user-attachments/assets/73bd5277-ebad-4995-978a-dfb764e5f54e)

**Comment by ShadelessFox** [comment]
Hello @3ks,

It looks like the metadata of your database is corrupted somehow. Please execute the following query and look for negative/big values:

```sql
select data_length, index_length from information_schema.tables where table_schema='dhg';
```

**Comment by 3ks** [comment]
![image](https://github.com/user-attachments/assets/887484fa-8b69-40a3-ad08-25ef3f2f17f6)

I found the table with the anomaly, which seems to be caused by my data synchronization tool. 

It created a temporary table t_per_orgs for the per_orgs table, with the engine set to FEDERATED. However, after the synchronization ended, the data synchronization tool did not properly delete the temporary table, leading to the issue.

 I deleted the temporary table to resolve the problem. 

![a14d2a91e3eca9f452409c1bb635755](https://github.com/user-attachments/assets/2cad591e-d5f5-450c-ade5-5c7e1341277d)

By the way, may I ask why the actual length of the per_orgs table is 196608, but the t_per_orgs data length is so large? Is it related to the FEDERATED engine, or is it an issue with the data synchronization tool?  (https://github.com/alibaba/DataX)

@ShadelessFox @E1izabeth  Thank you for help. Have a wonderful day!

**Comment by ShadelessFox** [comment]
That big number you see is actually supposed to be "-1" for some bizarre reason - the column cannot be negative because to its data type. I think it might be a bug of the tool you mentioned.

Since the issue is resolved, I'll close the ticket now. Feel free to ask any follow up questions.
