### ISSUE TITLE
Client does not support authentication protocol

### ISSUE THREAD

**Issue by holden321** [dbeaver/dbeaver#36137]
### Description

DBeaver can't connect to MariaDB

Via MariaDB driver:

`Client does not support authentication protocol requested by server. plugin type was = ''`

Via MySQL driver:

`!AuthenticationProvider.BadAuthenticationPlugin!`

When using the server terminal everything is ok

```
~:$ mysql testdb -p
Enter password: 
Welcome to the MariaDB monitor....
```
When using `phpMyAdmin`, everything is ok as well.

MariaDB driver version
`3.5.0`

MySQL driver version
`8.2.0`

MariaDB version on server
`10.3.39-MariaDB-0+deb10u1-log`

SHOW GRANTS;
`GRANT USAGE ON *.* TO user@localhost IDENTIFIED BY PASSWORD '*12345'`

### DBeaver Version

24.2.3

### Operating System

Windows 10

**Comment by HocKu7** [comment]
@holden321 Thank you for your report. Could you please provide the following additional information, such as connection parameters and logs? You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by holden321** [comment]
The connection use ssh tunnel.
The button "Test tunnel configuration" returns success.

Server Host: localhost
Database: testdb
Username: __user__
Password: __password__

All other parameter fields have default values.


```
2024-11-04 19:35:32.137 - Connect with 'jdbc:mariadb://localhost:3306/testdb' (mariaDB-192f8081475-362c68bea2ee9aa0)
2024-11-04 19:35:32.138 - SSHSessionController: Creating new session to l*****s@k*****o:22
2024-11-04 19:35:32.138 - SSHSessionController: Connecting session to l*****s@k*****o:22
2024-11-04 19:35:32.138 - Creating new SecureRandom.
2024-11-04 19:35:32.152 - Client identity string: SSH-2.0-SSHJ_0.34.0
2024-11-04 19:35:32.165 - Server identity string: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u4
2024-11-04 19:35:32.284 - SSHSessionController: Set up port forwarding *****:21067 <- l*****t:3306
2024-11-04 19:35:32.285 - Listening on localhost/127.0.0.1:21067
2024-11-04 19:35:32.286 - Execution context opened (jdbc:mariadb://localhost:3306/testdb; Main; 4)
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
2024-11-04 19:35:32.481 - SSHSessionController: Remove port forwarding *****:21067 <- l*****t:3306
2024-11-04 19:35:32.482 - Closing listener on localhost/127.0.0.1:21067
2024-11-04 19:35:32.482 - SSHSessionController: Releasing session for jdbc:mariadb://localhost:3306/testdb [MariaDB]
2024-11-04 19:35:32.482 - SSHSessionController: Disconnecting session to l*****s@k*****o:22
2024-11-04 19:35:32.482 - Disconnected - BY_APPLICATION
2024-11-04 19:35:32.483 - <<copyDone>> woke to: net.schmizz.sshj.transport.TransportException: [BY_APPLICATION] Disconnected
2024-11-04 19:35:32.565 - Client does not support authentication protocol requested by server. plugin type was = ''
java.sql.SQLException: Client does not support authentication protocol requested by server. plugin type was = ''
	at org.mariadb.jdbc.plugin.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:48)
	at org.mariadb.jdbc.client.impl.StandardClient.authenticationHandler(StandardClient.java:287)
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:227)
	at org.mariadb.jdbc.Driver.connect(Driver.java:68)
	at org.mariadb.jdbc.Driver.connect(Driver.java:92)
	at org.mariadb.jdbc.Driver.connect(Driver.java:26)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:211)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:513)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:123)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:118)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1395)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1266)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
2024-11-04 19:22:32.623 - Connect with 'jdbc:mysql://localhost:3306/testdb' (mysql8-192f7fc2f7c-bfeb4e7dc914b)
2024-11-04 19:22:32.624 - SSHSessionController: Creating new session to l*****s@k*****o:22
2024-11-04 19:22:32.624 - SSHSessionController: Connecting session to l*****s@k*****o:22
2024-11-04 19:22:32.624 - Creating new SecureRandom.
2024-11-04 19:22:32.645 - Client identity string: SSH-2.0-SSHJ_0.34.0
2024-11-04 19:22:32.653 - Server identity string: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u4
2024-11-04 19:22:32.775 - SSHSessionController: Set up port forwarding *****:31404 <- l*****t:3306
2024-11-04 19:22:32.776 - Listening on localhost/127.0.0.1:31404
2024-11-04 19:22:32.777 - Execution context opened (jdbc:mysql://localhost:3306/testdb; Main; 3)
2024-11-04 19:22:32.852 - SSHSessionController: Remove port forwarding *****:31404 <- l*****t:3306
2024-11-04 19:22:32.852 - Closing listener on localhost/127.0.0.1:31404
2024-11-04 19:22:32.853 - SSHSessionController: Releasing session for jdbc:mysql://localhost:3306/testdb [MySQL]
2024-11-04 19:22:32.853 - SSHSessionController: Disconnecting session to l*****s@k*****o:22
2024-11-04 19:22:32.853 - Disconnected - BY_APPLICATION
2024-11-04 19:22:32.906 - !AuthenticationProvider.BadAuthenticationPlugin!
com.mysql.cj.exceptions.WrongArgumentException: !AuthenticationProvider.BadAuthenticationPlugin!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:494)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:215)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1428)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:211)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:130)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:513)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:119)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:123)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:118)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:154)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1395)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1266)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by HocKu7** [comment]
@holden321 When you are connecting to db like that

> ~:$ mysql testdb -p
Enter password: 
Welcome to the MariaDB monitor....

It uses the username from the OS. Is it the same username that you wrote for the DBeaver connection configuration?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and answer the question.

**Comment by speakradmin** [comment]
Still an issue. Connecting to a percona server. I can log in with root in the cli. Is there a parameter that can be added to the Driver properties to work around this issue?

**Comment by speakradmin** [comment]
Nevermind, I managed to get this working using the mysql driver instead of the mariadb driver
I'm guessing it works because of the defaults in the driver properties
`defaultAuthenticationPlugin = mysql_native_password`

I also had to change `allowPublicKeyRetrieval` to true for it to work
