### ISSUE TITLE
File Scripts/sql/createDataBase.sql is not found in project 

### ISSUE THREAD

**Issue by coderfresh** [dbeaver/dbeaver#36184]
### Description

2024-11-07 15:41:35.648 - Task 'test' (4bd35d0a-aa7d-4bdd-a715-9d608f62b10b) started
2024-11-07 15:41:35.651 - SQL Scripts Execute
2024-11-07 15:41:35.658 - org.jkiss.dbeaver.DBException: Error executing script 'Scripts/sql/createDataBase.sql'
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:147)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.lambda$0(SQLScriptExecuteHandler.java:96)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:157)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeWithSettings(SQLScriptExecuteHandler.java:94)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.executeTask(SQLScriptExecuteHandler.java:75)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:143)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:104)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: File Scripts/sql/createDataBase.sql is not found in project General
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.readScriptContents(SQLScriptExecuteHandler.java:189)
	at org.jkiss.dbeaver.tools.sql.task.SQLScriptExecuteHandler.runScripts(SQLScriptExecuteHandler.java:120)
	... 8 more
2024-11-07 15:41:35.662 - SQL script execute completed
2024-11-07 15:41:35.663 - Task 'test' (4bd35d0a-aa7d-4bdd-a715-9d608f62b10b) finished with errors in 11 ms

### DBeaver Version

Community Edition 24.2.3

### Operating System

windows10

**Comment by uslss** [comment]
@coderfresh could you provide steps to reproduce the issue?

**Comment by coderfresh** [comment]
add external sql script to General Scirpts， and create task to excute script on connection 

> @coderfresh could you provide steps to reproduce the issue?

Add an external sql script under General Scripts, then right-click under Connection to create a task, select External Script Execution for the task, and this error will be reported. If the script is executed directly from the command line, there will be no errors.

**Comment by uslss** [comment]
Unfortunately, I still cannot reproduce the issue.
You can probably provide some videos or screenshots with STR. Thanks in advance, and sorry for the late response

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide a video showing the issue.

**Comment by ngyyuusora** [comment]
> Unfortunately, I still cannot reproduce the issue. You can probably provide some videos or screenshots with STR. Thanks in advance, and sorry for the late response

reproduce:

- link folder in project panel
- create task select sql files
- excute
- then failed, checking the created task, specified sql files gone, not display and throw error result.

**Comment by ngyyuusora** [comment]
![Image](https://github.com/user-attachments/assets/3d7a0724-a488-4fc5-9e2b-d2e8387b9957)

![Image](https://github.com/user-attachments/assets/d4f1db41-5eb6-47d5-a1b4-6a6510f7a681)

![Image](https://github.com/user-attachments/assets/33133512-7a0c-427a-b4d8-32ba47284131)

![Image](https://github.com/user-attachments/assets/c30c2086-bd76-4c61-b717-b667ff297b9e)

![Image](https://github.com/user-attachments/assets/a99e8f1a-0a2f-4ddc-b1ec-bb8a76d634c2)

![Image](https://github.com/user-attachments/assets/321f80ee-7b69-45e9-a5c8-bad5a4ca7110)

![Image](https://github.com/user-attachments/assets/3fbebfc9-cf4f-4e9d-8286-0945b05fef09)

**Comment by ngyyuusora** [comment]
https://github.com/user-attachments/assets/f982548c-200e-4fce-b5e3-ee6529e047f2

**Comment by ubils** [comment]
The process shown works with version 23, from version 24 the issue occurs.

**Comment by therimalaya** [comment]
This bug is not fixed in version 25 also. I have the same issue :(

**Comment by E1izabeth** [comment]
The new issue was created #37907, so we won't reopen this one.

**Comment by doningleb** [comment]
> This bug is not fixed in version 25 also. I have the same issue :(

I overcame this by creating a new script (run_it_all.sql) within the project folder and putting there several @include commands with full paths for the needed external scripts, ala:
@include "c:\users\mymother\...\sql_external_script_1.sql"
@include "c:\users\mymother\...\sql_external_script_2.sql"

Then I created a new task with only one script (run_it_all.sql). 

Hope that helps a bit.
