### ISSUE TITLE
Dameng execute comment sql error

### ISSUE THREAD

**Issue by daihy8759** [dbeaver/dbeaver#36239]
### Description

2024-11-14 10:04:01.899 - SQL 错误 [42000]: 第 20 行, 第 1 列[COMMENT]附近出现错误: 
语法分析出错
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [42000]: 第 20 行, 第 1 列[COMMENT]附近出现错误: 
语法分析出错
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:631)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:522)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:1001)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4231)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5160)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### DBeaver Version

24.2.0

### Operating System

macos 15.0

### Database and driver

DM DBMS 8.1.3.162
dm.jdbc.driver.DmDriver 8.1.3.62

### Steps to reproduce

1. execute sql
```sql
DROP TABLE IF EXISTS "test";
CREATE TABLE "test"(
    "id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);

COMMENT ON TABLE test IS 'test';
COMMENT ON COLUMN test."id" IS 'primary id';
```

**Comment by E1izabeth** [comment]
Please clarify why do you think it's a DBeaver issue. The error you show is the response from the database

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. If the issue is still relevant, please provide additional information.

**Comment by flywalker** [comment]
in version 23.1.2, the same SQL script executes without error returns. However, errors occur in version 23.2.5 and newer versions, likely due to an issue introduced between these versions

**Comment by flywalker** [comment]
i test result:  
can execute: latest version 23.2.1 and older version
return error: from 23.2.2 to newest 25.2.3

**Comment by flywalker** [comment]
Perhaps it's because 23.2.2 version has added new features:
Dameng database extension was added (thanks to @Stkai)

but the extension contain syntax analysis donot compatible COMMENT ON
