### ISSUE TITLE
Create new connection. Driver error !

### ISSUE THREAD

**Issue by andersonfrazao** [dbeaver/dbeaver#36313]
[Erro Dbeaver.zip](https://github.com/user-attachments/files/17845802/Erro.Dbeaver.zip)
### Description
A new attachment with the error in more detail.

When I try to make a new connection, for example, in Oracle. An error appears that drivers (libraries) are missing. However, when Dbeaver itself tries to download, an error also occurs that it was unable to download the necessary library. I see that this problem started appearing about 6 months ago.
[Erro Dbeaver.zip](https://github.com/user-attachments/files/17845527/Erro.Dbeaver.zip)

### DBeaver Version

24.2.5

### Operating System

Windows 11

### Database and driver

Oracle ojdbc11-23.2.0.0.jar

### Steps to reproduce

1. I try to connect to data base.
2. Dbeaver try download the libs
3. An error occurs
4. Does not complete the connection successfully

**Comment by ShadelessFox** [comment]
Hello @andersonfrazao,

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by andersonfrazao** [comment]
@ShadelessFox 

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_BR
Framework arguments:  -eclipse.keyring C:\Users\afraz\AppData\Roaming\DBeaverData\secure\secure_storage
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Nov 21 19:03:32 BRT 2024
Invalid number format for port number (CONNECTION_ID=mpDexURwRwqmAm4l06nyJQ==)

oracle.net.ns.NetException: Invalid number format for port number (CONNECTION_ID=mpDexURwRwqmAm4l06nyJQ==)
	at oracle.net.resolver.HostnameNamingAdapter.resolve(HostnameNamingAdapter.java:229)
	at oracle.net.resolver.NameResolver.resolveName(NameResolver.java:153)
	at oracle.net.resolver.AddrResolution.resolveTNSAddress(AddrResolution.java:760)
	at oracle.net.resolver.AddrResolution.initConnStrategy(AddrResolution.java:570)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:612)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:965)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:351)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2652)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:669)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1095)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:733)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:649)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:214)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:133)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:197)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:110)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:143)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1395)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1266)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1056)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:78)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
![log_erro_dbeaver](https://github.com/user-attachments/assets/b8fc4b80-2ca5-45ae-820f-420af38b8747)

**Comment by ShadelessFox** [comment]
Judging by the message, the driver is downloaded but the specified database port is incorrect.
> Invalid number format for port number

What's on your connection page?

**Comment by andersonfrazao** [comment]
Hello @ShadelessFox,

Work for me now !
I remove all "native" libs and installed manual lib. 
Thanks for attention.

![driver-manual](https://github.com/user-attachments/assets/2c18ffb7-b1c5-469a-946d-b67191806960)

**Comment by ShadelessFox** [comment]
I assume the ticket can be closed now.
