### ISSUE TITLE
Excluding pg% schemas in a postgresql connection prevents column type recognition and the refresh of metadata

### ISSUE THREAD

**Issue by mattywausb** [dbeaver/dbeaver#36336]
### Description

When using the "filter schema" feature in the connection for getting the "pg_" schemas out of sight, the display or refresh of column type does not work anymore.

With this setting
![grafik](https://github.com/user-attachments/assets/bf7d1219-623e-4bb1-8396-3a8e8d37196e)

I get this:

![grafik](https://github.com/user-attachments/assets/d78d0e43-241a-43c9-94a0-42cd718bcef5)

The details pages of the tables do not show any columns.

When trying to refresh the metadata on table level the following message is displayed:
```
Error refreshing node

Reason:
Cannot invoke "String.endsWith(String)" because "typeName" is null

```
In the dbeaver dbug log, there are tons of:
```
2024-11-22 17:29:47.864 - Can't resolve data type 'varchar' in database 'Willibald'
2024-11-22 17:29:47.865 - Can't resolve data type 1043
org.jkiss.dbeaver.DBException: Schema 11 not found for data type 1043
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.resolveDataType(PostgreDataTypeCache.java:239)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getDataType(PostgreDatabase.java:954)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:157)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:53)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.createTableColumn(PostgreTableBase.java:323)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:915)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:212)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:1047)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1119)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:664)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:475)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:914)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:512)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:914)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:398)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:373)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:188)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Making pg schemas visible again, solves the problem.

### DBeaver Version

Community Edition Version 24.2.5.202411171748

### Operating System

Windows 10

### Database and driver

PostgresSQL Server 16

Driver:

org.jkiss.dbeaver.ext.postgresql, Version: 2.1.216.202411171748

### Steps to reproduce

1. Change DB Connection to exclude "pg%" schemas
2. Connect to Database 
3. Open the column display -> column types are not displayed
4. doublick on a table to look an the details -> no columns listed

**Comment by E1izabeth** [comment]
Thank you for bug report. I reproduced the issue.
It should be fixed together with #35990
