### ISSUE TITLE
App becomes unusable when popup appears while dragging a UI element

### ISSUE THREAD

**Issue by jocot** [dbeaver/dbeaver#36364]
### Description

Cannot click on anything after a popup appears while you're dragging a UI element.

Sequence of events:
1. Drag a UI element
2. A popup window appears (eg. database connection failure) while you're dragging 
3. Can not click anything or close the popup

### DBeaver Version

Community edition 24.2.5

### Operating System

Fedora 40

### Database and driver

PostgresSQL, but should occur with any connection

### Steps to reproduce

This has been observed and repeatable on Fedora 40, I assume it would also apply to other platforms.

To reproduce:
1. Open dbeaver and open a number of tabs and connections
2. Close dbeaver leaving tabs open
3. Shutdown one of the databases or disconnect internet (if remote connection) - anything that would cause a connection failure.
4. Open dbeaver and immediately click and hold a tab to rearrange it, once the "Can't connect to database" popup appears, you can no longer click on anything, it seems its getting stuck in that drag mode. I notice when I move the mouse around the borders of the main window highlight but I cannot click anything and am forced to terminate the process via my OS.

**Comment by E1izabeth** [comment]
Thank you for the bug report.
I don't have Fedora to reproduce it, but I went through the steps on Windows and got the following state
![image](https://github.com/user-attachments/assets/114881b8-d298-4ad3-bba0-972f9e29143f)
On Windows, I can click on the buttons on the pop-up window. However, I believe that on some Unix systems, they might be unclickable.

**Comment by E1izabeth** [comment]
After closing all tabs, I still can't get rid of these gray frames.
![image](https://github.com/user-attachments/assets/524b5893-9d45-49e6-8031-a970f0e8c47e)

Also, I get this error in the logs
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.IWorkbenchWindow.getActivePage()" because the return value of "org.eclipse.ui.IWorkbenchPartSite.getWorkbenchWindow()" is null
	at org.jkiss.dbeaver.ui.editors.ProgressEditorPart$InitNodeVisualizer.lambda$completeLoading$0(ProgressEditorPart.java:202)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4099)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3715)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:347)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput$1.runTask(DatabaseLazyEditorInput.java:269)
	at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput$1.runTask(DatabaseLazyEditorInput.java:265)
	at org.jkiss.dbeaver.ui.UITask.runWithResult(UITask.java:27)
	at org.jkiss.dbeaver.model.runtime.RunnableWithResult.run(RunnableWithResult.java:40)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4099)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3715)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
	at com.dbeaver.application.DBeaverApplicationAdvanced.start(DBeaverApplicationAdvanced.java:101)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1434)
```
