### ISSUE TITLE
A CallableStatement was executed with nothing returned

### ISSUE THREAD

**Issue by Shassk** [dbeaver/dbeaver#36362]
### Description

A really strange case when if I call my procedure before first `drop table if exists + create temp table` call it gives said error. Doesn't happen when I do `drop`→`call`→`create` or `drop`→`create`→`call`, only `call`→`create` without `drop`, or any subsequent `drop`/`create` for that matter.

P. S. Also sometimes when I've tried different order of calls on a larger query (not just `drop+create`) I could get `Unhandled event loop exception` with `Index out of bounds`.

### DBeaver Version

Community Edition 24.2.2.202410061621

### Operating System

Windows 10 21H2

### Database and driver

PostgreSQL 16.4, JDBC 42.7.2

### Steps to reproduce

Create procedure:
```sql
create or replace procedure _debug_start_time_logging()
language plpgsql
as $$
begin
	create table if not exists _debug_execution_timelog (
		stage	text not null,
		time	timestamp not null default clock_timestamp()
	);
	insert into _debug_execution_timelog(stage) values ('start');
end;
$$;
```

Call this:
```sql
call _debug_start_time_logging();
drop table if exists tmp_vars;
create temp table tmp_vars (
	par_session_id int,
	par_inverse    int,
	par_operation  text
);
```

Get the error:
```
SQL Error [02000]: A CallableStatement was executed with nothing returned.
-------------------------------------
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [02000]: A CallableStatement was executed with nothing returned.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:339)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:631)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:522)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:1001)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4238)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:128)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:126)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5166)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: A CallableStatement was executed with nothing returned.
	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:99)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 13 more
```

**Comment by uslss** [comment]
unfortunately, cannot reproduce the issue on PG 16.6, dbeaver 24.3.2
