### ISSUE TITLE
Question: PostgreSQL query having CASE WHEN does not allow data updates

### ISSUE THREAD

**Issue by GITMichaelK** [dbeaver/dbeaver#36381]
### Description

My query to cut out text between "{xxx}" as condition

```
SELECT "ID", "Titel", "Name"
FROM "Scheme"."TableName"
WHERE "Name" NOT LIKE CONCAT("Series", 
CASE WHEN "Titel"LIKE '%{%}' THEN CONCAT(LEFT("Titel", POSITION ('{' IN "Titel") - 2), RIGHT("Titel", LENGTH("Titel") - POSITION ('}' IN "Titel"))) ELSE "Titel" END
);

```
works fine, but does not allow updates in any column. Without the CASE WHEN-line, updates are possible. My goal is to check, that FileName contains Titel except the string in "{}".
Why this and how to work around it?

### DBeaver Version

Community 24.2.0

### Operating System

Manjaro

### Database and driver

Postgresql 14; JDBC

**Comment by GITMichaelK** [comment]
Just now I checked my query with LibreOffice BASE: **It delivers the relevant records and allows edits in any column**.  So i guess there is a Bug in dBeaver.

**Comment by ShadelessFox** [comment]
Hello @GITMichaelK

Can you please provide log files? You can find instructions here: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by GITMichaelK** [comment]
Thanks @ShadelessFox, Here you are:
```
2024-11-28 17:10:18.544 - Error while analyzing query text: 
SELECT "ID-Vid", 
(SELECT "Sre" FROM "SchemeName"."T MEDIA SEL Sre" WHERE "ID-VidSre" = "ID-Sre_fkey") AS "Ŝerie",
"Title", 
"ID-Sre_fkey", "Sta", "Fol", "FolTot", "FileName"
FROM "SchemeName"."T MEDIA Daten"
WHERE "Art" = 'V Video' AND "ID-Sre_fkey" IS NOT NULL AND
"FileName" NOT LIKE CONCAT(
CASE WHEN (SELECT "Sre GivenName" FROM "SchemeName"."T MEDIA SEL Sre" WHERE "ID-VidSre" = "ID-Sre_fkey") IS NULL THEN
   (SELECT "Sre" FROM "SchemeName"."T MEDIA SEL Sre" WHERE "ID-VidSre" = "ID-Sre_fkey") 
   ELSE (SELECT "Sre GivenName" FROM "SchemeName"."T MEDIA SEL Sre" WHERE "ID-VidSre" = "ID-Sre_fkey") END, 
'%<', 
   CASE WHEN "Sta" = 0   THEN '-- ~ '                                          ELSE CONCAT(RIGHT(To_Char("Sta",   '00'),2), ' ~ ') END, 
   CASE WHEN "Fol" >= 1000 THEN CONCAT(RIGHT(To_Char("Fol", '0000'),4), ' ~')  ELSE CONCAT(RIGHT(To_Char("Fol",  '000'),3), ' ~') END,
   To_Char("FolTot", '0000'),
   '> | ', 
   CASE WHEN "Title"LIKE '%{%}' THEN CONCAT(LEFT("Title", POSITION ('{' IN "Title") - 2), RIGHT("Title", LENGTH("Title") - POSITION ('}' IN "Title"))) ELSE "Title" END,
   -- "Title",
   '%'
)
ORDER BY (SELECT "Sre" FROM "SchemeName"."T MEDIA SEL Sre" WHERE "ID-VidSre" = "ID-Sre_fkey") ASC,
"Sta", "Fol", "FolTot", "Title"
java.lang.UnsupportedOperationException: Value reference expression expected while facing with error
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.collectValueReferenceExpression(SQLQueryModelRecognizer.java:650)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.collectValueReferenceExpression(SQLQueryModelRecognizer.java:649)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.collectKnownValueExpression(SQLQueryModelRecognizer.java:565)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.collectValueExpression(SQLQueryModelRecognizer.java:528)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryExpressionMapper.lambda$5(SQLQueryExpressionMapper.java:272)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryTreeMapper$MapperDataPendingNodeFrame.doWork(SQLQueryTreeMapper.java:96)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryTreeMapper.translate(SQLQueryTreeMapper.java:149)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.collectQueryExpression(SQLQueryModelRecognizer.java:278)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.recognizeQuery(SQLQueryModelRecognizer.java:125)
	at org.jkiss.dbeaver.model.sql.semantics.SQLQueryModelRecognizer.recognizeQuery(SQLQueryModelRecognizer.java:748)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob.doWork(SQLBackgroundParsingJob.java:583)
	at org.jkiss.dbeaver.ui.editors.sql.semantics.SQLBackgroundParsingJob$1.run(SQLBackgroundParsingJob.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

Hope this helps.

**Comment by ShadelessFox** [comment]
It does help, thank you.

**Comment by E1izabeth** [comment]
I reproduced the issue
![image](https://github.com/user-attachments/assets/60dc82da-a70d-4edf-8553-a4f6b29ed19a)

```
SELECT a.actor_id as aactor_id, a.last_name as alast_name, a.first_name as afirst_name 
FROM actor as a WHERE a.last_name NOT LIKE CONCAT(a.age , 
CASE WHEN a.first_name LIKE '%{%}' THEN CONCAT(LEFT(a.first_name, POSITION ('{' IN a.first_name) - 2), RIGHT(a.first_name, LENGTH(a.first_name) - POSITION ('}' IN a.first_name))) ELSE a.first_name END
);
```

**Comment by GITMichaelK** [comment]
Thank you @E1izabeth for your work!
I'm a bit concerned about the message `Unique Key`. In my query, the first column `SELECT "ID-Vid" ...` is the primary key of the table.

**Comment by E1izabeth** [comment]
Yes. It look like a bug
