### ISSUE TITLE
Search through DB Metadata using "Search in definition" option returns error SQL Error [904] [42000]: ORA-00904: "V"."TEXT_VC": Invalid Identifier

### ISSUE THREAD

**Issue by samuele555** [dbeaver/dbeaver#36396]
### Description

While searching for a string using DB Metadata search, ticking both TABLE and "Search in definition" option, returns an error
![image](https://github.com/user-attachments/assets/eac676d6-6bbe-4260-8627-121238d7902b)
![image](https://github.com/user-attachments/assets/1d99802e-2be7-4907-864a-b76140d5d785)

From .log file:

```
`!ENTRY org.jkiss.dbeaver.model 4 0 2024-11-28 09:36:22.654
!MESSAGE SQL Error [904] [42000]: ORA-00904: "V"."TEXT_VC": identificativo non valido

!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2024-11-28 09:36:22.654
!MESSAGE Error : 904, Position : 367, SQL = SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','PACKAGE','PACKAGE BODY','CONSTRAINT','FOREIGN KEY','INDEX','PROCEDURE','FUNCTION','SEQUENCE','TRIGGER') AND UPPER(OBJECT_NAME) LIKE :1 UNION ALL SELECT OWNER, VIEW_NAME, 'VIEW' AS OBJECT_TYPE FROM ALL_VIEWS v WHERE UPPER(v."TEXT_VC") LIKE :2 UNION ALL SELECT DISTINCT owner, name, type FROM ALL_SOURCE WHERE UPPER(text) LIKE :3 )
ORDER BY OBJECT_NAME, Original SQL = SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','PACKAGE','PACKAGE BODY','CONSTRAINT','FOREIGN KEY','INDEX','PROCEDURE','FUNCTION','SEQUENCE','TRIGGER') AND UPPER(OBJECT_NAME) LIKE ?  UNION ALL SELECT OWNER, VIEW_NAME, 'VIEW' AS OBJECT_TYPE FROM ALL_VIEWS v WHERE UPPER(v."TEXT_VC") LIKE ? UNION ALL SELECT DISTINCT owner, name, type FROM ALL_SOURCE WHERE UPPER(text) LIKE ?)
ORDER BY OBJECT_NAME, Error Message = ORA-00904: "V"."TEXT_VC": identificativo non valido

!STACK 0
Error : 904, Position : 367, SQL = SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','PACKAGE','PACKAGE BODY','CONSTRAINT','FOREIGN KEY','INDEX','PROCEDURE','FUNCTION','SEQUENCE','TRIGGER') AND UPPER(OBJECT_NAME) LIKE :1 UNION ALL SELECT OWNER, VIEW_NAME, 'VIEW' AS OBJECT_TYPE FROM ALL_VIEWS v WHERE UPPER(v."TEXT_VC") LIKE :2 UNION ALL SELECT DISTINCT owner, name, type FROM ALL_SOURCE WHERE UPPER(text) LIKE :3 )
ORDER BY OBJECT_NAME, Original SQL = SELECT  DISTINCT OWNER,OBJECT_NAME,OBJECT_TYPE FROM (
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS WHERE OBJECT_TYPE IN ('TABLE','VIEW','PACKAGE','PACKAGE BODY','CONSTRAINT','FOREIGN KEY','INDEX','PROCEDURE','FUNCTION','SEQUENCE','TRIGGER') AND UPPER(OBJECT_NAME) LIKE ?  UNION ALL SELECT OWNER, VIEW_NAME, 'VIEW' AS OBJECT_TYPE FROM ALL_VIEWS v WHERE UPPER(v."TEXT_VC") LIKE ? UNION ALL SELECT DISTINCT owner, name, type FROM ALL_SOURCE WHERE UPPER(text) LIKE ?)
ORDER BY OBJECT_NAME, Error Message = ORA-00904: "V"."TEXT_VC": identificativo non valido

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:710)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:608)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1248)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1041)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:443)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:518)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:251)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1059)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1205)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1135)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1472)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3728)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3832)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1099)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.oracle.model.OracleStructureAssistant.searchAllObjects(OracleStructureAssistant.java:308)
	at org.jkiss.dbeaver.ext.oracle.model.OracleStructureAssistant.findObjectsByMask(OracleStructureAssistant.java:116)
	at org.jkiss.dbeaver.ext.oracle.model.OracleStructureAssistant.findObjectsByMask(OracleStructureAssistant.java:1)
	at org.jkiss.dbeaver.ui.search.metadata.SearchMetadataQuery.run(SearchMetadataQuery.java:96)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Inside Dbeaver Log view:
![image](https://github.com/user-attachments/assets/5760545b-424a-4702-9a14-e4568cb17e35)

### DBeaver Version

Version 24.0.0.202403091004 [Community]

### Operating System

Windows 23H2

### Database and driver

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 using Oracle JDBC Driver ojdbc11 23.2.0.0

### Steps to reproduce

1. Click on Search dropdown menu 
2. Click on "Search..."
3. Choose connection
4. Type any string in textbox
5. Match type: contains
6. Max results 500
7. Case-insensitive: FALSE
8. Search in comments: FALSE
9. Search in definitions: FALSE
10. Object type must have TABLE selected (the combination that provokes the error is TABLE + "Search in definitions"
11. Run the search, the error should be presented instantly

**Comment by E1izabeth** [comment]
Thank you for the bug report.
I can't reproduce it on Oracle 12.2. Probably, it's reproducible on Oracle 11 and older versions only

**Comment by samuele555** [comment]
I saw that the query it shows in log:

```
SELECT DISTINCT OWNER, OBJECT_NAME, OBJECT_TYPE
FROM(
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
FROM ALL_OBJECTS
WHERE OBJECT_TYPE IN ('TABLE', 'VIEW', 'PACKAGE', 'PACKAGE BODY', 'CONSTRAINT', 'FOREIGN KEY', 'INDEX', 'PROCEDURE', 'FUNCTION', 'SEQUENCE', 'TRIGGER')
AND UPPER(OBJECT_NAME) LIKE '%FOO%'
UNION ALL SELECT OWNER, VIEW_NAME, 'VIEW' AS OBJECT_TYPE
FROM ALL_VIEWS v
WHERE UPPER(v."TEXT_VC") LIKE '%FOO%'
UNION ALL SELECT DISTINCT OWNER, name, TYPE
FROM ALL_SOURCE
WHERE UPPER(TEXT) LIKE '%FOO%')

```
does look for V.TEXT_VC while this field does not exist on catalog view ALL_VIEWS, but it has "TEXT" instead.
Is it possible that the query run by DBeaver upon search has been changed?

I've tried with Oracle v 19c 19.22 and it does not happen.

![image](https://github.com/user-attachments/assets/4406516b-22fd-489d-87df-39df0abbaef1)

![image](https://github.com/user-attachments/assets/14c9caf1-f1cc-4868-9ea0-b2319de6f6bd)

**Comment by E1izabeth** [comment]
We haven't changed this query for a long time.
Thanks for your investigation! We will modify this query for old Oracle versions
