### ISSUE TITLE
Composite types are handled incorrectly (the solution is presented)

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#36415]
### Description

https://github.com/user-attachments/assets/6eb2ce3c-1024-495b-9024-68444127503b

Actual query:
```
SELECT "f.title", COUNT(*) FROM (
select f
from film as f
) src
GROUP BY "f.title"
```

Expected query:
```
SELECT (src.f).title, COUNT(*)
FROM (
    select f
    from film as f
) src
GROUP BY (src.f).title
```

### DBeaver Version

Enterprise Edition 24.3.0-202411230022

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.4

**Comment by ask9** [comment]
The similar issue appears with Filter by value:

https://github.com/user-attachments/assets/eb939b99-9049-44c5-8d28-06ca0ff8a7f8

Actual query:
```
SELECT * FROM (
select f
from film as f

) z_q WHERE f.title IN ('Grosse Wonderful')
```


Expected query:

```
SELECT *
FROM (
    select f
    from film as f
) z_q
WHERE (z_q.f).title IN ('Grosse Wonderful')
```

**Comment by ask9** [comment]
If you have automated tests, I suggest adding additional test case for queries with composite types for all existing features.

**Comment by E1izabeth** [comment]
Thanks for the bug report

**Comment by E1izabeth** [comment]
Also if I put the cursor on Filter option in the context menu, I get exception 
![image](https://github.com/user-attachments/assets/3cb65ab5-663f-42ca-8a22-57a1283edaf6)

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeArrayString(JDBCCollection.java:147)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.toString(JDBCCollection.java:128)
	at org.jkiss.dbeaver.model.impl.data.formatters.NumberDataFormatter.formatValue(NumberDataFormatter.java:143)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.getValueDisplayString(JDBCNumberValueHandler.java:85)
	at org.jkiss.dbeaver.ui.controls.resultset.FilterByAttributeAction.translateFilterPattern(FilterByAttributeAction.java:64)
	at org.jkiss.dbeaver.ui.controls.resultset.FilterByAttributeAction.<init>(FilterByAttributeAction.java:36)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.fillFiltersMenu(ResultSetViewer.java:3453)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$fillContextMenu$24(ResultSetViewer.java:2799)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:467)
```
