### ISSUE TITLE
View cannot be created via UI(when trying to create table)

### ISSUE THREAD

**Issue by hun-meta** [dbeaver/dbeaver#36424]
### Description

System information:
Operating system (distribution) and version - Mac 14.7.1
DBeaver version - 24.3.0.202412011650
Connection specification:
Database name - PostgreSQL
Press - Create new Table

Expected: the window to create new table appears
Actual result: error appears: Can't find node corresponding to new object

### DBeaver Version

Community edition 24.3.0.202412011650

### Operating System

Mac 14.7.1

### Database and driver

PostgreSQL 16

### Steps to reproduce

Expected: the window to create new table appears
Actual result: error appears: Can't find node corresponding to new object

**Comment by HocKu7** [comment]
@hun-meta Please send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Also,
can you please provide footage showing your issue? Thank you.

**Comment by hun-meta** [comment]
> @hun-meta Please send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Also, can you please provide footage showing your issue? Thank you.

not sure what is footage?
maybe error message like this? -> "Can't find node corresponding to new object"

logs that i found is under this phrase:
```
org.jkiss.dbeaver.DBException: Can't find node corresponding to new object
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob.openNewObject(NavigatorHandlerObjectCreateBase.java:307)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$CreateJob$1.lambda$0(NavigatorHandlerObjectCreateBase.java:267)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4382)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4005)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
```
```
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=ko_KR
Framework arguments:  -eclipse.keyring /Users/hun/Library/DBeaverData/secure/secure_storage
Command-line arguments:  -os macosx -ws cocoa -arch aarch64

```

**Comment by E1izabeth** [comment]
Thanks for providing the part of the log.
Is it stable and reproducible for you, or has it happened just once? 

How exactly did you press Create new table? I provided two screenshots with two ways of creating a new table from Navigator. Which one did you use?
1.
![image](https://github.com/user-attachments/assets/31dd8da6-f030-4cd5-bd11-5f340d0e413d)
2.
![image](https://github.com/user-attachments/assets/e01f1573-8e0a-40b1-9573-00fc4fdd8b61)

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide requested information.
