### ISSUE TITLE
SSHJ connection refused

### ISSUE THREAD

**Issue by vaindil** [dbeaver/dbeaver#3643]
This is DBeaver 5.1.0 on Windows 10 with SSHJ 1.0.6. I'm able to connect just fine using JSch for my SSH tunnel. When I keep my settings exactly the same but switch to SSHJ instead, I get a connection refused error. I'm not changing my key, host, port, anything--all I change is the dropdown to switch from JSch to SSHJ.

My debug log is below. I've included the successful connection under JSch, then my unsuccessful attempt with SSHJ is below that.

```
2018-06-17 10:15:40.785 - Connect with 'jdbc:postgresql://localhost:5432/mydbname' (postgres-jdbc-1640e19f9c5-2229d24238340c6b)
2018-06-17 10:15:40.921 - Instantiate SSH tunnel
2018-06-17 10:15:40.929 - Connect to tunnel host
2018-06-17 10:15:40.930 - SSH INFO: Connecting to XX.XX.XX.XX port XX
2018-06-17 10:15:40.970 - SSH INFO: Connection established
2018-06-17 10:15:41.004 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
2018-06-17 10:15:41.006 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2018-06-17 10:15:41.008 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2018-06-17 10:15:41.023 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2018-06-17 10:15:41.079 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-06-17 10:15:41.083 - SSH INFO: SSH_MSG_KEXINIT sent
2018-06-17 10:15:41.084 - SSH INFO: SSH_MSG_KEXINIT received
2018-06-17 10:15:41.086 - SSH INFO: kex: server: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
2018-06-17 10:15:41.088 - SSH INFO: kex: server: ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256
2018-06-17 10:15:41.089 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
2018-06-17 10:15:41.092 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
2018-06-17 10:15:41.095 - SSH INFO: kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
2018-06-17 10:15:41.098 - SSH INFO: kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
2018-06-17 10:15:41.102 - SSH INFO: kex: server: none,zlib@openssh.com
2018-06-17 10:15:41.103 - SSH INFO: kex: server: none,zlib@openssh.com
2018-06-17 10:15:41.104 - SSH INFO: kex: server: 
2018-06-17 10:15:41.105 - SSH INFO: kex: server: 
2018-06-17 10:15:41.106 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2018-06-17 10:15:41.110 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-06-17 10:15:41.112 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-06-17 10:15:41.115 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-06-17 10:15:41.118 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-06-17 10:15:41.120 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-06-17 10:15:41.121 - SSH INFO: kex: client: none
2018-06-17 10:15:41.122 - SSH INFO: kex: client: none
2018-06-17 10:15:41.123 - SSH INFO: kex: client: 
2018-06-17 10:15:41.124 - SSH INFO: kex: client: 
2018-06-17 10:15:41.125 - SSH INFO: kex: server->client aes128-ctr hmac-sha2-256 none
2018-06-17 10:15:41.127 - SSH INFO: kex: client->server aes128-ctr hmac-sha2-256 none
2018-06-17 10:15:41.140 - SSH INFO: SSH_MSG_KEX_DH_GEX_REQUEST(1024<2048<2048) sent
2018-06-17 10:15:41.142 - SSH INFO: expecting SSH_MSG_KEX_DH_GEX_GROUP
2018-06-17 10:15:41.186 - SSH INFO: SSH_MSG_KEX_DH_GEX_INIT sent
2018-06-17 10:15:41.188 - SSH INFO: expecting SSH_MSG_KEX_DH_GEX_REPLY
2018-06-17 10:15:41.232 - SSH INFO: ssh_rsa_verify: signature true
2018-06-17 10:15:41.236 - SSH WARN: Permanently added 'XX.XX.XX.XX' (RSA) to the list of known hosts.
2018-06-17 10:15:41.238 - SSH INFO: SSH_MSG_NEWKEYS sent
2018-06-17 10:15:41.240 - SSH INFO: SSH_MSG_NEWKEYS received
2018-06-17 10:15:41.243 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2018-06-17 10:15:41.274 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2018-06-17 10:15:41.306 - SSH INFO: Authentications that can continue: publickey
2018-06-17 10:15:41.308 - SSH INFO: Next authentication method: publickey
2018-06-17 10:15:41.684 - SSH INFO: Authentication succeeded (publickey).
2018-06-17 10:15:42.956 - Connected (postgres-jdbc-1640e19f9c5-2229d24238340c6b, PostgreSQL JDBC Driver [42.2.0.jre7])
2018-06-17 10:15:43.016 - SSH INFO: Disconnecting from XX.XX.XX.XX port XX
2018-06-17 10:15:43.020 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2018-06-17 10:15:43.066 - Disconnected (postgres-jdbc-1640e19f9c5-2229d24238340c6b)
2018-06-17 10:15:47.047 - Connect with 'jdbc:postgresql://localhost:5432/mydbname' (postgres-jdbc-1640e1a124d-32a6b25c22e75dd4)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2018-06-17 10:15:48.798 - Connection failed (postgres-jdbc-1640e1a124d-32a6b25c22e75dd4)
2018-06-17 10:15:48.857 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:740)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
    at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:216)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
    at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:88)
    at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:125)
    at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:70)
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:738)
    ... 4 more
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at net.schmizz.sshj.SocketClient.connect(SocketClient.java:126)
    at net.schmizz.sshj.SocketClient.connect(SocketClient.java:117)
    at org.jkiss.dbeaver.model.net.ssh.SSHImplementationSshj.setupTunnel(SSHImplementationSshj.java:67)
    ... 7 more
```

**Comment by serge-rider** [comment]
Can't reproduce (in our test environment these both implementations usually works, main different is encryption algorithms).

The strange part is that SSHJ fails in the very beginning (before any authentication, key exchange, etc). It just can't connect over SSH port. JSch and SSHJ have different ways operating sockets but this part almost identical.

Is there anything special about your server/DNS resolution?

**Comment by razav002** [comment]
I got the same error, what port number I should use ? I  have Host with Private key file  in SSh Tunnel  in DBeaver - Version 6.3.2.202001051908
