### ISSUE TITLE
Keyboard Vertical Scolling (Ctrl + Arrow Up/Down) Suddenly Stops Working

### ISSUE THREAD

**Issue by pieter-irsan** [dbeaver/dbeaver#36466]
### Description

Upon initially starting up my PC and opening DBeaver, I can do some vertical scrolling through the script editor using my keboard (Ctrl + Arrow up/down). The issue is that after some time, vertical scroll using keyboard suddenly stops working. I press Ctrl + Arrow up/down and nothing happens.

What confuses me even further is that I don't see a specific pattern that leads up to this. I have tried to reproduce the bug before, but have gotten no success. I mostly operate DBeaver using my keyboards. I have tried switching applications (Alt + Tab), switching DBeaver tabs (Ctrl + Pg Dn), opening database objects using Ctrl + Shift + D, etc. and the keyboard vertical scrolling would this work. But then it would stop working just when you weren't thinking of it.

I'm curious if anyone else if experiencing this or am I missing something?

n.b. this issue has happened on versions earlier than 24.2.1

### DBeaver Version

Community Edition 24.2.1

### Operating System

Windows 11 Pro 23H2

### Database and driver

1. Database name and version: PostgreSQL 14.12
2. Driver name and version: PostgreSQL standard JDBC driver

### Steps to reproduce

1. Open DBeaver
2. Run some queries, do tasks on other apps, etc.
3. Vertical scroll using keyboard (Ctrl + Arrow up/down) suddenly doesn't work anymore

**Comment by HocKu7** [comment]
@pieter-irsan, it is currently hard to reproduce. If you are able to catch this behavior next time, please add a comment about what exactly happened before that and send the log files. You can find instructions here: https://dbeaver.com/docs/wiki/Log-files/. Thank you.

**Comment by pieter-irsan** [comment]
[.log](https://github.com/user-attachments/files/18178475/default.log)

Here are the log files for my last session. I have redacted the column and table names. I have no clue but I think it might be the `SWT Resource was not properly disposed` lines that are causing the problem? 

IIRC, the keyboard vertical scrolling happened three times throughout the day and I almost immediately restarted DBeaver just to try and reproduce the error, but to no avail. Anyways, let me know if there is something I missed or if you need any more information.

**Comment by Destrolaric** [comment]
Hi, do you have a search bar opened during alt-tabbing?

**Comment by pieter-irsan** [comment]
Hello, do you mean a search bar as in Ctrl + F?

I tried to recreate the error by opening a search bar and then doing an Alt + Tab, but the Ctrl + Arrow Up/Down still works fine.

IIRC, I usually close the search bar right after using it, so I don't think I usually have a search bar opened during Alt + Tab.

**Comment by E1izabeth** [comment]
Could you try resetting settings or creating new DBeaver workspace and see if it happen again?
Please use `Switch workspace` to try on a new workspace
![image](https://github.com/user-attachments/assets/faefa318-e04b-4aa1-8d26-0f113e111e6d)


And you can reset settings through this dialog
![image](https://github.com/user-attachments/assets/e1289c25-1189-4d77-9221-61a3447510dd)

![image](https://github.com/user-attachments/assets/d4017b8f-150a-4b62-b7eb-2e39041b9af1)

**Comment by pieter-irsan** [comment]
> Could you try resetting settings or creating new DBeaver workspace and see if it happen again? Please use `Switch workspace` to try on a new workspace

Firstly I tried to switch to a new empty workspace with all the default settings and config. I didn't change any settings except these keybindings to collapse and expand the text foldings (same thing I did in my regular workspace):

- Collapse: `Ctrl + ;`
- Collapse All: `Ctrl + Shift + ;`
- Expand: `Ctrl + '`
- Expand All: `Ctrl + Shift + '`

But after a while Ctrl + Arrow Up/Down stopped working.

Not long after it stopped working, I immediately reset the settings just like you showed. After restarting, it worked initially, but eventually stopped working again.

This is the .log file from the new workspace in case it could be of any help
[log.txt](https://github.com/user-attachments/files/18434523/log.txt)

**Comment by E1izabeth** [comment]
Thank you

**Comment by E1izabeth** [comment]
Error from the provided logs that might be relevant:
```
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.TextLayout.<init>(TextLayout.java:302)
	at org.eclipse.jface.viewers.StyledCellLabelProvider.getSharedTextLayout(StyledCellLabelProvider.java:207)
	at org.eclipse.jface.viewers.StyledCellLabelProvider.measure(StyledCellLabelProvider.java:276)
	at org.eclipse.jface.viewers.OwnerDrawLabelProvider$OwnerDrawListener.handleEvent(OwnerDrawLabelProvider.java:58)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4326)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1174)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1198)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1183)
	at org.eclipse.swt.widgets.Table.sendMeasureItemEvent(Table.java:3647)
	at org.eclipse.swt.widgets.Table.hitTestSelection(Table.java:2834)
	at org.eclipse.swt.widgets.Table.showItem(Table.java:5318)
	at org.eclipse.swt.widgets.Table.showSelection(Table.java:5411)
	at org.eclipse.swt.widgets.Table.setSelection(Table.java:5017)
	at org.eclipse.ui.internal.FilteredTableBaseHandler.openDialog(FilteredTableBaseHandler.java:224)
	at org.eclipse.ui.internal.FilteredTableBaseHandler.execute(FilteredTableBaseHandler.java:129)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:569)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:644)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1198)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1183)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1225)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1221)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1704)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4849)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:347)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4727)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:342)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5091)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3710)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:293)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)

```

**Comment by arhayka** [comment]
Unfortunately, we can't reproduce this. However, this is quite an important functionality, and we need to be sure it works.
We'll keep an eye on this issue and try to find something similar.
