### ISSUE TITLE
DBeaver not launching after install on RHEL 9.5

### ISSUE THREAD

**Issue by thomaspmorgan** [dbeaver/dbeaver#36563]
### Description

DBeaver does not launch after install, get this error in the logs:

```
!SESSION 2024-12-16 14:33:16.778 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -eclipse.keyring /home/tpmorgan@fog.local/.local/share/DBeaverData/secure/secure_storage
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2024-12-16 14:33:26.815
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (166).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:854)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:775)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1057)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:387)
	at org.eclipse.osgi.container.Module.doStart(Module.java:639)
	at org.eclipse.osgi.container.Module.start(Module.java:498)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:528)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:620)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:348)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:377)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:353)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:192)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.invokeFramework(DBeaverLauncher.java:650)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.basicRun(DBeaverLauncher.java:610)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.run(DBeaverLauncher.java:1461)
	at org.jkiss.dbeaver.launcher.DBeaverLauncher.main(DBeaverLauncher.java:1434)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/home/tpmorgan@fog.local/.local/share/DBeaverData/install-data/org.jkiss.dbeaver.product/24.3.0-202412011650/org.eclipse.osgi/156/0/.cp/libswt-gtk-4966r5.so: /home/tpmorgan@fog.local/.local/share/DBeaverData/install-data/org.jkiss.dbeaver.product/24.3.0-202412011650/org.eclipse.osgi/156/0/.cp/libswt-gtk-4966r5.so: failed to map segment from shared object
	no swt-gtk in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	/home/tpmorgan@fog.local/.swt/lib/linux/x86_64/libswt-gtk-4966r5.so: /home/tpmorgan@fog.local/.swt/lib/linux/x86_64/libswt-gtk-4966r5.so: failed to map segment from shared object
	Can't load library: /home/tpmorgan@fog.local/.swt/lib/linux/x86_64/libswt-gtk.so
	Can't load library: /home/tpmorgan@fog.local/.swt/lib/linux/x86_64/libswt.so
```

### DBeaver Version

Community Edition 24.3.0

### Operating System

RHEL 9

### Additional context

SELinux enforcing, FIPS mode enabled, RHEL 9.5 (Plow), 64-bit

**Comment by gepbird** [comment]
Similar to https://github.com/dbeaver/dbeaver/issues/36562

**Comment by ShadelessFox** [comment]
Hello @thomaspmorgan,

Can you please try installing Eclipse (the platform DBeaver is built on) to see if it runs on your machine?

You can download it here: https://www.eclipse.org/downloads/packages/release/2024-12/r/eclipse-ide-java-developers

**Comment by E1izabeth** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
