### ISSUE TITLE
Update Snappy and Jennifer drivers

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#36668]
### Description

![изображение](https://github.com/user-attachments/assets/070e124e-4b63-48f7-bd27-40f7b83b7434)

java.lang.ClassNotFoundException: org.apache.log4j.Layout
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.gemstone.gemfire.internal.shared.ClientSharedUtils.<clinit>(ClientSharedUtils.java:296)
	at io.snappydata.jdbc.ClientDriver.useThriftProtocol(ClientDriver.java:103)
	at com.pivotal.gemfirexd.jdbc.ClientDRDADriver.connect(ClientDRDADriver.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCConnectionOpener.run(JDBCConnectionOpener.java:83)

![изображение](https://github.com/user-attachments/assets/90d07ea1-eb3c-4acc-9a61-3eb0a47a9261)

```
java.lang.ClassNotFoundException: jennifer.jdbc.driver.JenniferDriver
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1333)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:1263)
```

### DBeaver Version

Dbeaver CE 24.3.2

### Operating System

Windows

**Comment by arhayka** [comment]
- We have the latest version of Snappy — we are using the latest version
- Jennifer hasn't been updated for 4 last years — there is no new version

We should delete them.

**Comment by ShadelessFox** [comment]
The `gemfire_xd` database seems to be dead as well.

**Comment by serge-rider** [comment]
Why delete Jennifer?
gemfire_xd is not dead, we can download driver and probably some installations are still there.
