### ISSUE TITLE
Communication link failure

### ISSUE THREAD

**Issue by webian** [dbeaver/dbeaver#3669]
When I try to connect to my server via SSH tunnel I get error:
````
Communication link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
````
If I test only the SSH tunnel it succeed. If I connect to the server via SSH terminal and then connect to mysql with same parameters of "Connection settings" it succeed.
Instead the error appear when I try to connect with Dbeaver or I "Test connection..."

I like this program and I would like to use it via SSH tunnel... any idea please?

This is the log:
````
2018-06-21 12:38:37.649 - Instantiate SSH tunnel
2018-06-21 12:38:37.650 - Connect to tunnel host
2018-06-21 12:38:37.651 - SSH INFO: Connecting to masked.host port 2222
2018-06-21 12:38:37.689 - SSH INFO: Connection established
2018-06-21 12:38:37.726 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1p1
2018-06-21 12:38:37.729 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2018-06-21 12:38:37.731 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2018-06-21 12:38:37.734 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2018-06-21 12:38:37.761 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-06-21 12:38:37.763 - SSH INFO: SSH_MSG_KEXINIT sent
2018-06-21 12:38:37.764 - SSH INFO: SSH_MSG_KEXINIT received
2018-06-21 12:38:37.765 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2018-06-21 12:38:37.769 - SSH INFO: kex: server: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
2018-06-21 12:38:37.770 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2018-06-21 12:38:37.775 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2018-06-21 12:38:37.779 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2018-06-21 12:38:37.786 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2018-06-21 12:38:37.794 - SSH INFO: kex: server: none,zlib@openssh.com
2018-06-21 12:38:37.795 - SSH INFO: kex: server: none,zlib@openssh.com
2018-06-21 12:38:37.796 - SSH INFO: kex: server: 
2018-06-21 12:38:37.797 - SSH INFO: kex: server: 
2018-06-21 12:38:37.798 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2018-06-21 12:38:37.801 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-06-21 12:38:37.803 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-06-21 12:38:37.806 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-06-21 12:38:37.809 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-06-21 12:38:37.810 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-06-21 12:38:37.812 - SSH INFO: kex: client: none
2018-06-21 12:38:37.812 - SSH INFO: kex: client: none
2018-06-21 12:38:37.813 - SSH INFO: kex: client: 
2018-06-21 12:38:37.814 - SSH INFO: kex: client: 
2018-06-21 12:38:37.815 - SSH INFO: kex: server->client aes128-ctr hmac-md5 none
2018-06-21 12:38:37.816 - SSH INFO: kex: client->server aes128-ctr hmac-md5 none
2018-06-21 12:38:37.824 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2018-06-21 12:38:37.825 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2018-06-21 12:38:37.866 - SSH INFO: ssh_rsa_verify: signature true
2018-06-21 12:38:37.869 - SSH INFO: Host 'masked.host' is known and matches the RSA host key
2018-06-21 12:38:37.872 - SSH INFO: SSH_MSG_NEWKEYS sent
2018-06-21 12:38:37.873 - SSH INFO: SSH_MSG_NEWKEYS received
2018-06-21 12:38:37.875 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2018-06-21 12:38:37.908 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2018-06-21 12:38:37.942 - SSH INFO: Authentications that can continue: publickey
2018-06-21 12:38:37.945 - SSH INFO: Next authentication method: publickey
2018-06-21 12:38:38.048 - SSH INFO: Authentication succeeded (publickey).
2018-06-21 12:38:38.852 - Connection failed (mysql5-16421ecb240-26038bc8558c0b6)
2018-06-21 12:38:38.856 - SSH INFO: Disconnecting from masked.host port 2222
2018-06-21 12:38:38.860 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2018-06-21 12:38:38.906 - org.jkiss.dbeaver.model.exec.DBCConnectException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
org.jkiss.dbeaver.model.exec.DBCConnectException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:384)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:112)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:84)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:123)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:752)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:216)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:632)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1016)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2191)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:155)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:261)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:207)
	... 2 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:567)
	... 18 more
````

**Comment by webian** [comment]
I close this because is not a bug. I thought that the server was running in default port 3306 but instead it was a different port. Sorry for the noise.

**Comment by Pranavoo7** [comment]
use full
