### ISSUE TITLE
Comment causing SQL Error (Snowflake JDBC)

### ISSUE THREAD

**Issue by derek-rak** [dbeaver/dbeaver#3689]
I'm experiencing the following error:
```
SQL Error
  java.sql.SQLFeatureNotSupportedException: 
```

when using the "Execute SQL Script" on the following query in DBeaver 5.1.1 using Snowflake JDBC Driver version 3.6.4:

```
-- Call metrics
SELECT * 
FROM ts.journey 
LIMIT 100;
```

When I change the comment from 
`-- Call metrics`

to 

`-- Calls metrics`

The error no longer occurs.

Edit: Simplified the sample query (as the error occurs with any query)

**Comment by serge-rider** [comment]
I'm quite sure that this is Snowflake-specific issue, in fact driver throws this error. I think they make some SQL preparsing on client side and then evaluate comments.
Anyhow, we can't fix this from DBeaver side.

**Comment by DSouzaM** [comment]
Hello,
I reproduced this issue and checked out the logs - it looks like DBeaver is invoking `prepareCall` which the Snowflake driver currently does not support. Here's a snippet of the stacktrace:
```
org.jkiss.dbeaver.DBException: SQL Error
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1567)
	...
Caused by: org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:193)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:1034)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1005)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:425)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1539)
	... 8 more
Caused by: java.sql.SQLFeatureNotSupportedException
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.prepareCall(SnowflakeConnectionV1.java:350)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareCall(JDBCConnectionImpl.java:237)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:113)
	... 14 more
```

I noticed that the sql text being prepared by JDBC contain the comments above the actual command. For example, the above query has text `"-- Call metrics\nSELECT *..."`. It looks like [`SqlUtils.isExecQuery`](https://github.com/dbeaver/dbeaver/blob/aa2fb8cd678704cc7564c3650db213434e641bc7/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLUtils.java#L653) then parses the first keyword to be `CALL`, which is why it executes `prepareCall` instead of `prepareStatement`. The same error is reproduced if you replace `Call` with `Exec`.
