### ISSUE TITLE
Filtering result set on remote connection fails when loading values

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#3695]
Using the "Filter by value" button on each column very often fails with the following error in the debug log:

	java.sql.SQLException: Resultset esaurito
		at oracle.jdbc.driver.OracleResultSetImpl.getObject(OracleResultSetImpl.java:1035)
		at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
		at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:152)
		at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
		at org.jkiss.dbeaver.model.virtual.DBVUtils.readDictionaryRows(DBVUtils.java:183)
		at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn.getValueEnumeration(JDBCTableColumn.java:192)
		at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$2.readEnumeration(GenericFilterValueEdit.java:204)
		at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:312)
		at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

After this error I have to invalidate/reconnect. Connection is remote but usually stable (I mean, if I don't use the filter functionality). It seems to be triggered by me starting to search filter values (using the text box at the bottom of the search modal) before values load is complete.

**Comment by serge-rider** [comment]
I can't reproduce this. What Oracle driver version do you use? Did you try Oracle 12 drivers?

**Comment by serge-rider** [comment]
But I have a guess. Please check how it works in 5.1.2

**Comment by p91paul** [comment]
I did some tests this morning and looks like it worked. If it happens again I will try upgrading to oracle 12 drivers before reopening... good job!!
