### ISSUE TITLE
NPE when filtering items in "Goto database object"

### ISSUE THREAD

**Issue by Azenet** [dbeaver/dbeaver#3727]
Since 5.1.1 (I think), there is a NullPointerException when using the Ctrl-Shift-D "Goto database object" window, when the focused window is a result view or a query. This used to work to filter on the view's datasource, now it is required to click on the datasource in the "Navigate" view. When doing Ctrl-Shift-D, the title of the goto dialog shows the view's datasource.

Exception:
```
java.lang.NullPointerException
        at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:132)
        at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2050)
        at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1998)
        at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1970)
        at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1957)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by serge-rider** [comment]
Thanks for bug report
