### ISSUE TITLE
New dbeaver installation: Error connection to Postgresql missing net.postgis:postgis-jdbc:RELEASE[2.2.1]

### ISSUE THREAD

**Issue by mpniel** [dbeaver/dbeaver#3780]
I have a new dbeaver 5.0.6 installation.
I am trying to connect to postgresql on windows.
I click on new connection then on driver propertied
I get error resolving dependencies: 
         Maven artifact 'maven:/org.postgresql:postgresql:RELEASE not found
         Maven artifact 'maven:/org.postgresql:postgresql:RELEASE not found
Then I get in driver settings: 
Files required by driver:
net.postgis:postgis-jdbc:RELEASE  2.1.1
net.postgis:postgis-jdbc-jtsparser:RELEASE  2.1.1

Can you help?

**Comment by serge-rider** [comment]
Are you behind some corporate firewall? DBeaver downloads drivers from Maven Central and thus needs internet access.

**Comment by mpniel** [comment]
The computer doesn't have internet access.
I have an other installation in a computer with internet connection.
What files should I download and to what location should I copy them to the other computer?

**Comment by serge-rider** [comment]
By default all driver files are in %HOME/.dbeaver-drivers. Or you can download them official PostgreSQL web site. Or get them from DBeaver Enterprise (which is bundled with all drivers out of the box).

You need to copy PostgreSQL jars somewhere on your computer. You need 3 jars: 
- postgresql-42.2.0.jre7.jar
- postgis-jdbc-2.2.1.jar
- postgis-jdbc-jtsparser-2.2.1.jar

(Version may differ). Then add these jars in driver editors dialog (click on Add File button). And remove all Maven artifacts from there (otherwise it will try to download drivers every time you connect).

**Comment by ILTB** [comment]
Hello! Please help me.

Manjaro Linux
DBeaver v5.1.0
Internet connection without proxy

```
2018-07-11 13:46:15.086 - Error resolving artifact version
java.io.IOException: Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.isSecureDownload(DriverLibraryMavenArtifact.java:133)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.downloadLibraryFiles(DriverDownloadAutoPage.java:162)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.access$0(DriverDownloadAutoPage.java:153)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage$3.run(DriverDownloadAutoPage.java:142)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-07-11 13:46:15.712 - Error resolving artifact version
java.io.IOException: Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.isSecureDownload(DriverLibraryMavenArtifact.java:133)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.downloadLibraryFiles(DriverDownloadAutoPage.java:162)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.access$0(DriverDownloadAutoPage.java:153)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage$3.run(DriverDownloadAutoPage.java:142)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

```

**Comment by zdavidlnx** [comment]
Same here with Manjaro Linux and DBeaver v5.1.0 trying to use prostgrsql

**Comment by serge-rider** [comment]
Could you post full error/debug log? 
There should be some errors before that message.

**Comment by mpniel** [comment]
THANKS VERY MUCH!
It worked ok for me after deleting all files and adding these 3 jar files to the driver.
BTW there are 2 types of Posgresql connections: what is the difference? one legacy and the other postgresql.

**Comment by ILTB** [comment]
`2018-07-12 17:06:17.220 - Create display
2018-07-12 17:06:17.887 - DBeaver 5.1.0 is starting
2018-07-12 17:06:17.889 - OS: Linux 4.14.39-1-MANJARO (amd64)
2018-07-12 17:06:17.889 - Java version: 1.8.0_172 by Oracle Corporation (64bit)
2018-07-12 17:06:17.890 - Install path: '/usr/lib/dbeaver'
2018-07-12 17:06:17.890 - Instance path: 'file:/home/vasiliy/.dbeaver4/'
2018-07-12 17:06:17.890 - Memory available 61Mb/910Mb
2018-07-12 17:06:17.926 - Starting RMI server at 22535
2018-07-12 17:06:18.167 - Run workbench
2018-07-12 17:06:22.926 - Initializing DBeaver 5.1.0
2018-07-12 17:06:22.932 - Host plugin: org.jkiss.dbeaver.core.application 5.1.0
2018-07-12 17:06:22.936 - Initialize Core...
2018-07-12 17:06:23.369 - Core initialized (433ms)
2018-07-12 17:06:23.372 - Configure workbench window
2018-07-12 17:06:23.489 - Create actions
2018-07-12 17:06:23.493 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-07-12 17:06:23.498 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2018-07-12 17:06:24.374 - Initialize workbench window
2018-07-12 17:06:24.413 - Finish initialization
2018-07-12 17:06:29.198 - Open [https://dbeaver.io/product/version.xml]
2018-07-12 17:06:53.029 - Connect with 'jdbc:postgresql://localhost:5432/postgres' (postgres-jdbc-1648ed0e85b-4b8a4b9b9e20d648)
[Fatal Error] :1:1: Premature end of file.
2018-07-12 17:06:53.331 - Error loading version info: Error parsing POM
2018-07-12 17:06:53.332 - Error loading version info: /usr/lib/dbeaver/maven-local/org/postgresql/postgresql/42.2.0.jre7/postgresql-42.2.0.jre7.pom (Нет такого файла или каталога)
2018-07-12 17:06:53.333 - Maven artifact 'org.postgresql:postgresql:42.2.0.jre7' not found in any available repository.
2018-07-12 17:06:53.338 - Error resolving library 'org.postgresql:postgresql:RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/org.postgresql:postgresql:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:196)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree$3.run(DriverDependenciesTree.java:126)
        at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-07-12 17:06:53.361 - null
org.jkiss.dbeaver.DBException: Error resolving dependencies
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:91)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree$3.run(DriverDependenciesTree.java:126)
        at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.io.IOException: Maven artifact 'maven:/org.postgresql:postgresql:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:196)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
        ... 3 more
[Fatal Error] :1:1: Premature end of file.
2018-07-12 17:06:58.272 - Error loading version info: Error parsing POM
2018-07-12 17:06:58.273 - Error loading version info: /usr/lib/dbeaver/maven-local/net/postgis/postgis-jdbc/2.2.1/postgis-jdbc-2.2.1.pom (Нет такого файла или каталога)
2018-07-12 17:06:58.274 - Maven artifact 'net.postgis:postgis-jdbc:2.2.1' not found in any available repository.
2018-07-12 17:06:58.274 - Error resolving artifact version
java.io.IOException: Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.isSecureDownload(DriverLibraryMavenArtifact.java:133)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.downloadLibraryFiles(DriverDownloadAutoPage.java:162)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.access$0(DriverDownloadAutoPage.java:153)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage$3.run(DriverDownloadAutoPage.java:142)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-07-12 17:07:01.365 - Error resolving artifact version
java.io.IOException: Maven artifact 'maven:/net.postgis:postgis-jdbc:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.isSecureDownload(DriverLibraryMavenArtifact.java:133)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.downloadLibraryFiles(DriverDownloadAutoPage.java:162)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.access$0(DriverDownloadAutoPage.java:153)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage$3.run(DriverDownloadAutoPage.java:142)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
[Fatal Error] :1:1: Premature end of file.
2018-07-12 17:07:02.999 - Error loading version info: Error parsing POM
2018-07-12 17:07:03.000 - Error loading version info: /usr/lib/dbeaver/maven-local/net/postgis/postgis-jdbc-jtsparser/2.2.1/postgis-jdbc-jtsparser-2.2.1.pom (Нет такого файла или каталога)
2018-07-12 17:07:03.001 - Maven artifact 'net.postgis:postgis-jdbc-jtsparser:2.2.1' not found in any available repository.
2018-07-12 17:07:03.001 - Error resolving artifact version
java.io.IOException: Maven artifact 'maven:/net.postgis:postgis-jdbc-jtsparser:RELEASE' not found
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:285)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.isSecureDownload(DriverLibraryMavenArtifact.java:133)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.downloadLibraryFiles(DriverDownloadAutoPage.java:162)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage.access$0(DriverDownloadAutoPage.java:153)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDownloadAutoPage$3.run(DriverDownloadAutoPage.java:142)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-07-12 17:07:04.113 - File missing in net.postgis:postgis-jdbc
2018-07-12 17:07:04.114 - File missing in net.postgis:postgis-jdbc-jtsparser
2018-07-12 17:07:04.118 - Connection failed (postgres-jdbc-1648ed0e85b-4b8a4b9b9e20d648)
2018-07-12 17:07:04.120 - org.jkiss.dbeaver.DBException: Internal error connecting to jdbc:postgresql://localhost:5432/postgres
org.jkiss.dbeaver.DBException: Internal error connecting to jdbc:postgresql://localhost:5432/postgres
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:807)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:216)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadLibraries(DriverDescriptor.java:919)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:877)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:866)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:535)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:638)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:122)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:379)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:112)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:77)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:89)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:752)
        ... 4 more
`

**Comment by serge-rider** [comment]
That's weird. 

It tries to save maven artifacts in /usr/lib/dbeaver/maven-local/ (and I believe it just fails with permission denied).
Did you change default settings? E.g. drivers location (preferences->Database->Drivers->Local folder)?

**Comment by ILTB** [comment]
No. Fresh install.
![screenshot_20180718_140533](https://user-images.githubusercontent.com/10111903/42877923-ecad1fca-8a93-11e8-937d-bbd898b07a05.png)

**Comment by ILTB** [comment]
New errors:

```
2018-07-19 15:40:14.556 - Create display
2018-07-19 15:40:14.749 - DBeaver 5.1.0 is starting
2018-07-19 15:40:14.750 - OS: Linux 4.14.39-1-MANJARO (amd64)
2018-07-19 15:40:14.751 - Java version: 1.8.0_172 by Oracle Corporation (64bit)
2018-07-19 15:40:14.751 - Install path: '/usr/lib/dbeaver'
2018-07-19 15:40:14.752 - Instance path: 'file:/home/vasiliy/.dbeaver4/'
2018-07-19 15:40:14.752 - Memory available 77Mb/910Mb
2018-07-19 15:40:14.764 - Starting RMI server at 24980
2018-07-19 15:40:14.869 - Run workbench
2018-07-19 15:40:17.179 - Initializing DBeaver 5.1.0
2018-07-19 15:40:17.186 - Host plugin: org.jkiss.dbeaver.core.application 5.1.0
2018-07-19 15:40:17.189 - Initialize Core...
2018-07-19 15:40:17.391 - Core initialized (202ms)
2018-07-19 15:40:17.394 - Configure workbench window
2018-07-19 15:40:17.465 - Create actions
2018-07-19 15:40:17.468 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-07-19 15:40:17.472 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2018-07-19 15:40:18.033 - Initialize workbench window
2018-07-19 15:40:18.054 - Finish initialization
2018-07-19 15:40:21.965 - Open [https://dbeaver.io/product/version.xml]
2018-07-19 15:40:31.152 - Connect with 'jdbc:postgresql://localhost:5432/postgres' (postgres-jdbc-164b28e5aa7-1844c44f6913d8b7)
2018-07-19 15:40:31.306 - Open [https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.0.jre7/postgresql-42.2.0.jre7.pom]
2018-07-19 15:40:31.872 - null
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:64)
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:57)
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:51)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.cachePOM(MavenArtifactVersion.java:232)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.loadPOM(MavenArtifactVersion.java:242)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.<init>(MavenArtifactVersion.java:93)
        at org.jkiss.dbeaver.registry.maven.MavenArtifact.makeLocalVersion(MavenArtifact.java:293)
        at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:365)
        at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:193)
        at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:224)
        at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:183)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getArtifactVersion(DriverLibraryMavenArtifact.java:151)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:283)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:196)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree$3.run(DriverDependenciesTree.java:126)
        at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
2018-07-19 15:40:36.646 - Connection failed (postgres-jdbc-164b28e5aa7-1844c44f6913d8b7)
2018-07-19 15:40:36.648 - org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:124)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:379)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:112)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:77)
        at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:89)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:752)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:216)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.jkiss.dbeaver.DBException: Can't load driver class 'org.postgresql.Driver'
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:890)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:866)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:535)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:638)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:122)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:887)
        ... 16 more
2018-07-19 15:40:46.498 - Connect with 'jdbc:postgresql://localhost:5432/postgres' (postgres-jdbc-164b28e969e-1860edccc454a3ae)
[Fatal Error] :1:1: Premature end of file.
2018-07-19 15:40:46.605 - Error loading version info: Error parsing POM
2018-07-19 15:40:46.606 - Open [http://central.maven.org/maven2/org/postgresql/postgresql/42.2.0.jre7/postgresql-42.2.0.jre7.pom]
2018-07-19 15:40:46.874 - null
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:64)
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:57)
        at org.jkiss.utils.IOUtils.fastCopy(IOUtils.java:51)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.cachePOM(MavenArtifactVersion.java:232)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.loadPOM(MavenArtifactVersion.java:242)
        at org.jkiss.dbeaver.registry.maven.MavenArtifactVersion.<init>(MavenArtifactVersion.java:93)
        at org.jkiss.dbeaver.registry.maven.MavenArtifact.makeLocalVersion(MavenArtifact.java:293)
        at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:365)
        at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:193)
        at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:224)
        at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:183)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getArtifactVersion(DriverLibraryMavenArtifact.java:151)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:283)
        at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:196)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
        at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
        at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree$3.run(DriverDependenciesTree.java:126)
        at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by serge-rider** [comment]
@ILTB this was resolved in 5.1.3. It is Java 9 related issue.

**Comment by cortopy** [comment]
I'm using 5.1.3 in Manjaro Linux and experiencing the same issue

```
Error resolving dependencies
  Maven artifact 'maven:/org.postgresql:postgresql:RELEASE' not found
  Maven artifact 'maven:/org.postgresql:postgresql:RELEASE' not found

```

**Comment by cortopy** [comment]
I fixed it by removing `.dbeaver4` from $HOME and reinstalling

**Comment by mpniel** [comment]
I fix it by downloading the files

**Comment by CraigRaelHarris** [comment]
For Windows install, run dbeaver as admin

**Comment by AndrusGerman** [comment]
I have a fairly similar error **Manjaro KDE** (flatpak)  
**Erro:**  
```
Error resolving dependencies Maven artifact 'maven:/org.postgresql:postgresql:RELEASE'
```
**My basic configuration:**  
- I have no internet problems
- my firewalls are off
- The package is installed with flatpak

_My solution in **Manjaro** (flatpak):_ 

1. Install package `flatpak install flathub io.dbeaver.DBeaverCommunity`
2. Run the application `flatpak run io.dbeaver.DBeaverCommunity`
> Now we close it, we just wanted its configuration files
3. Delete the corrupt configuration:  
`rm -rf $HOME/.var/app/io.dbeaver.DBeaverCommunity/`

**Comment by dushmar** [comment]
Hello, I am currently experiencing the same issues with a Redshift connection (I am using 7.1.0 Community edition):

![image](https://user-images.githubusercontent.com/56891594/84874709-4bf97500-b085-11ea-86de-339e3cdc1c11.png)

when I click "OK" in this popup, I get this window, which usually lists all drivers required but I have none in the list: 
![image](https://user-images.githubusercontent.com/56891594/84874904-8d8a2000-b085-11ea-9f7d-04a1f2c20847.png)

NOTE: the windows states that I should check my Internet connection, but I have no internet problems, and I've tried this with firewalls on and off. 

If I remove the Maven artifact and download the jar files locally, the connection just times out:

![image](https://user-images.githubusercontent.com/56891594/84875396-333d8f00-b086-11ea-83f0-c50c3f22a727.png)

![image](https://user-images.githubusercontent.com/56891594/84875641-87e10a00-b086-11ea-85fb-447a2ee34543.png)

![image](https://user-images.githubusercontent.com/56891594/84875665-90394500-b086-11ea-9ac9-3b3c3c7f5dc7.png)

**Comment by tonio-m** [comment]
I'm having the same issue as @dushmar on Dbeaver 7.0.3. 

Maybe the redshift driver is missing from maven repositories?
How do I add a new maven repository source on Settings?

**Comment by IronKnight36** [comment]
Having the same issue with Community Edition 7.1.0. Error is reading "Error resolving driver libraries Reason: Error resolving dependencies"

How do we resolve this?

**Comment by aliceliunz** [comment]
Download the Redshift JDBC drvier from the highlight website on the Driver Manager, then add the file in the libraries and remove the default driver to resolve the dependencies error. 

![image](https://user-images.githubusercontent.com/20604667/85355258-57a2db00-b560-11ea-8346-60c5161aa750.png)

**Comment by dushmar** [comment]
I wanted to follow-up with the solution which worked for me (and my specific setup)
I tried the solution @aliceliunz proposed before my previous comment, and it didn't work for me, at least not before my elastic IP was whitelisted towards my specific DB connection (I'm working on an AWS WorkSpace). After my IP was whitelisted by the DB admin, the solution above worked as intended.

**Comment by gigatexal** [comment]
> 
> 
> Download the Redshift JDBC drvier from the highlight website on the Driver Manager, then add the file in the libraries and remove the default driver to resolve the dependencies error.
> 
> ![image](https://user-images.githubusercontent.com/20604667/85355258-57a2db00-b560-11ea-8346-60c5161aa750.png)

This fixed it for me.

**Comment by mosesontheweb** [comment]
I had about the same issue, the path to the driver directory pointed to `/usr/share/dbeaver`. I changed it to my local directory `$HOME/.dbeaver-drivers` and all problems have gone. I'm now able to download and install drivers again. I'm working with Ubuntu 20.04.

Regards, Thomas

**Comment by popovserhii** [comment]
Only fresh installation helped me.

**Comment by jmada** [comment]
> I had about the same issue, the path to the driver directory pointed to `/usr/share/dbeaver`. I changed it to my local directory `$HOME/.dbeaver-drivers` and all problems have gone. I'm now able to download and install drivers again. Maybe try to set a directory which is writable with your user, if the drivers are needed by others as well.
> 
> Regards, Thomas

Thank you, this worked for me.

**Comment by nishkra** [comment]
add https://mvnrepository.com in download configuration and it works for me

**Comment by lleeoo** [comment]
> For Windows install, run dbeaver as admin

After the driver installation completes, you can close DBeaver and restart as regular user and it should work fine.

**Comment by benIT** [comment]
> add https://mvnrepository.com in download configuration and it works for me

![image](https://user-images.githubusercontent.com/2970652/155488538-9e800be1-5761-479c-9080-f847fe57a7c9.png)

This one works for me !

Thanks @nishkra

**Comment by iguanito** [comment]
Faced the same issue today but on Ubuntu with snap installation. (dbeaver v22.1.4)

Actually, the problem was solved by updating the local folder to store drivers:
Windows -> Preferences -> Connections -> Drivers -> Edit local folder with actually existing path

![image](https://user-images.githubusercontent.com/4182403/186741475-be8d89bd-ffd9-4f1f-b231-0bbdd24a9b55.png)

**Comment by domonkosbalogh-seon** [comment]
> Faced the same issue today but on Ubuntu with snap installation. (dbeaver v22.1.4)
> 
> Actually, the problem was solved by updating the local folder to store drivers: Windows -> Preferences -> Connections -> Drivers -> Edit local folder with actually existing path
> 
same issue, updating the folder from 204 to 211 solved it

**Comment by holiq** [comment]
> By default all driver files are in %HOME/.dbeaver-drivers. Or you can download them official PostgreSQL web site. Or get them from DBeaver Enterprise (which is bundled with all drivers out of the box).
> 
> You need to copy PostgreSQL jars somewhere on your computer. You need 3 jars:
> 
> * postgresql-42.2.0.jre7.jar
> * postgis-jdbc-2.2.1.jar
> * postgis-jdbc-jtsparser-2.2.1.jar
> 
> (Version may differ). Then add these jars in driver editors dialog (click on Add File button). And remove all Maven artifacts from there (otherwise it will try to download drivers every time you connect).

i had the same issue and i tried deleting one of those files and it worked, thanks mate

**Comment by chanchancheers** [comment]
I have just reinstalled Dbeaver, and all problems fixed.

**Comment by nabekabebe** [comment]
> I have a fairly similar error **Manjaro KDE** (flatpak) **Error:**
> 
> ```
> Error resolving dependencies Maven artifact 'maven:/org.postgresql:postgresql:RELEASE'
> ```
> 
> **My basic configuration:**
> 
> * I have no internet problems
> * my firewalls are off
> * The package is installed with flatpak
> 
> _My solution in **Manjaro** (flatpak):_
> 
> 1. Install package `flatpak install flathub io.dbeaver.DBeaverCommunity`
> 2. Run the application `flatpak run io.dbeaver.DBeaverCommunity`
> 
> > Now we close it, we just wanted its configuration files
> 
> 3. Delete the corrupt configuration:
>    `rm -rf $HOME/.var/app/io.dbeaver.DBeaverCommunity/`
> 4. It's time to run and install the drivers

just removing old config file[3] fixed the issue for me on Manjaro 6.1.1. Thanks @AndrusGerman

**Comment by knightq** [comment]
@nishkra solution worked for me as well.
I already had `https://mvnrepository.com/` (with the final `/`) present in the repo list and by adding the same url, but without the final slash it worked!

**Comment by neto-developer** [comment]
> > add https://mvnrepository.com in download configuration and it works for me
> 
> ![image](https://user-images.githubusercontent.com/2970652/155488538-9e800be1-5761-479c-9080-f847fe57a7c9.png)
> 
> This one works for me !
> 
> Thanks @nishkra

Thanks! This solved my problem!
