### ISSUE TITLE
add support run stores procedure for ProfileBD/FIS

### ISSUE THREAD

**Issue by Bsplesk** [dbeaver/dbeaver#3785]
Feature request/Bug report

adding of support of performing store procedures for ProfileBD/FES
[wiki FIS_(company)](https://en.wikipedia.org/wiki/FIS_(company))
[wiki GT.M is a high-throughput key-value database/MUMPS](https://en.wikipedia.org/wiki/GT.M)
(support JDBC driver)

at the moment
```sql
CALL NAME_PROCEDURE(Param1, Param2, 'ParamX');
```

result

>**java.sql.SQLException: Not supported for anything other than Aggregate Message Service Class.
	at sanchez.jdbc.driver.ScCallableStatement.execute(Unknown Source)**
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:259)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:203)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.executeStatement(JDBCCallableStatementImpl.java:229)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:445)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1539)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:387)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:818)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2276)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1539)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

work example java
```java       
        connection = dataSource.getConnection();
        callableStatement = connection.prepareCall( "{call NAME_PROCEDURE (Param1,?,?)}" );
        callableStatement.setInt(1, 1);  // Param 2
        callableStatement.setString(2, xml); // Param 3
        callableStatement.registerOutParameter(1, java.sql.Types.VARCHAR);
        resultSet = callableStatement.executeQuery();
```
base
 **connection.prepareCall( "{call NAME_PROCEDURE (Param1,?,?)}" );**

DBeaver 5.1.2/Arch Linux/Windows 10

**Comment by serge-rider** [comment]
This seems to be driver-specific issue.
Could you try to execute it as 
```sql
{ CALL NAME_PROCEDURE(Param1, Param2, 'ParamX'); }
```
?

**Comment by Bsplesk** [comment]
Perhaps it will be useful:
[**documentation driver** and driver](https://master.dl.sourceforge.net/project/pip/PIP/V0.1/PIP_V01_JDBC.zip)
[+ The YottaDB GitHub project (fork GT.M), uses this driver](https://raw.githubusercontent.com/YottaDB/PIP/master/ScJDBC.jar)

dbeaver 5.1.4 (30 july git )

`{call mrpc(param, param, param)};`

> Error:
> Not supported for anything other than Aggregate Message Service Class.

**Comment by serge-rider** [comment]
I need access to a live instance of this db server to fix this. 
Or somebody's assistance. Please write me on serge@jkiss.org
