### ISSUE TITLE
dbeaver (5.1.3) doesn't start with openjdk 11

### ISSUE THREAD

**Issue by tigerfoot** [dbeaver/dbeaver#3842]
With rolling release distribution like openSUSE Tumbleweed we now have openjdk-11 as default java.

OS : openSUSE Tumbleweed 20180721-0
openjdk used 

```
S  | Name                        | Type    | Version         | Arch   | Repository
---+-----------------------------+---------+-----------------+--------+-----------
i+ | java-11-openjdk             | package | 11.0.0.0~20-1.1 | x86_64 | oss
i+ | java-11-openjdk-devel       | package | 11.0.0.0~20-1.1 | x86_64 | oss
i+ | java-11-openjdk-headless    | package | 11.0.0.0~20-1.1 | x86_64 | oss
```

Error found launching dbeaver 

```
dbeaver 
2018-07-23 16:35:52.981 - Create display
2018-07-23 16:35:53.338 - DBeaver 5.1.3 is starting
2018-07-23 16:35:53.340 - OS: Linux 4.17.6-1-default (amd64)
2018-07-23 16:35:53.340 - Java version: 11-internal by Oracle Corporation (64bit)
2018-07-23 16:35:53.341 - Install path: '/usr/share/dbeaver'
2018-07-23 16:35:53.341 - Instance path: 'file:/ioda/home/bruno/.dbeaver4/'
2018-07-23 16:35:53.341 - Memory available 77Mb/1024Mb
2018-07-23 16:35:53.350 - Starting RMI server at 61870
2018-07-23 16:35:53.403 - Run workbench
2018-07-23 16:35:53.436 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 25 more
2018-07-23 16:35:53.447 - DBeaver is stopping
2018-07-23 16:35:53.448 - null
java.lang.IllegalStateException: Workbench has not been created yet.
        at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.shutdown(DBeaverApplication.java:320)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:171)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
``` 

If you have any ideas that I can try to help making dbeaver working with openjdk 11 just tell me the steps

**Comment by tigerfoot** [comment]
dbeaver start and work (basics function) with java-11 if it is rebuild see #3861

**Comment by Foorack** [comment]
Java 11 is now released and DBeaver does not run correctly. It's missing javax/xml/bind/DatatypeConverter

**Comment by Foorack** [comment]
Temporary fix: ```
-vm
/usr/lib/jvm/java-10-openjdk-amd64/bin/java
```
add that **just right before** -vmargs in dbeaver.ini

**Comment by tigerfoot** [comment]
> Temporary fix:
> 
> ```
> -vm
> /usr/lib/jvm/java-10-openjdk-amd64/bin/java
> ```
> 
> add that **just right before** -vmargs in dbeaver.ini

With that you tell dbeaver to use openjdk-10 :-) Which obviously is not openjdk-11

**Comment by Foorack** [comment]
@tigerfoot I know, that's exactly why it works. 😉https://openjdk.java.net/jeps/320

**Comment by p91paul** [comment]
I believe java 11 support was released like yesterday :) did you upgrade to 5.2.3?

**Comment by Foorack** [comment]
@p91paul @tigerfoot Upgraded to 5.2.4 today. Does still not work with Java 11.

Java: openjdk version "11.0.1" 2018-10-16
OS: Ubuntu 18.04

![ekrankopio de 2018-11-09 09-39-44](https://user-images.githubusercontent.com/5008081/48252140-38475080-e404-11e8-906c-3b65d7ca0911.png)

Happens when trying to connect to a MSSQL database.

**Comment by tigerfoot** [comment]
Actually 5.2.4 compiled yesterday is working for me (connected to Oracle and PostgreSQL DB)

Attached full info 
[dbeaver.txt](https://github.com/dbeaver/dbeaver/files/2565523/dbeaver.txt)

**Comment by programus** [comment]
The problem seems come back with v5.3.0 released Dec 10.

**Comment by OnnoH** [comment]
Logfile (/var/log/system.log)
```
Dec 10 13:14:19 myhost dbeaver[1520]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
```

**Comment by serge-rider** [comment]
Yes, unfortunately we had to downgrade to Eclipse Oxygen which doesn't support Java 11. Because Latest Eclipse release was too unstable.

Workaround (config patch): #4308

also on Windows and MacOS you could use installers which are already bundled with proper Java version.

**Comment by programus** [comment]
> 
> 
> Yes, unfortunately we had to downgrade to Eclipse Oxygen which doesn't support Java 11. Because Latest Eclipse release was too unstable.
> 
> Workarounds: #4765 and #4308
> 
> Also on Windows and MacOS you could use installers which are already bundled with proper Java version.

Thank you! The workarounds work here.

**Comment by Danny3** [comment]
I'm waiting for a new release.
I don't have time to mess with workarounds.

**Comment by Foorack** [comment]
I agree, a warning next time to stop people running Linux and Java 11 from upgrading would have been nice, also a visual crash error. The workarounds posted does not work on Ubuntu.
