### ISSUE TITLE
DBeaver unexpectedly closes

### ISSUE THREAD

**Issue by CoconutTherapy** [dbeaver/dbeaver#3847]
Hello,

Since last update my DBeaver unexpectedly and randomly closes, usually after SQL syntax errors or databases errors. There is no specified error messages, the soft simply freezes for a second and closes without saving anything.

Here are last few lines of logs before it crashes and when I reopen it.

```
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-07-24 10:44:33.063
!MESSAGE [Amazon](500310) Invalid operation: syntax error at or near ")" 
Position: 1699;
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2018-07-24 10:44:33.063
!MESSAGE [Amazon](500310) Invalid operation: syntax error at or near ")" 
Position: 1699;
!STACK 0
com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: syntax error at or near ")" 
Position: 1699;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getBindComplete(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario1(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrors(Unknown Source)
	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadata(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(Unknown Source)
	at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.amazon.jdbc.common.SStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:341)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:445)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1549)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:387)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:818)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2315)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1549)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
!SESSION 2018-07-24 10:44:45.017 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2018-07-24 10:44:46.476
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

```

I'm considering rolling back to a previous version. Any pointer?
Thanks

**Comment by hugorn** [comment]
I'm having this same problem after upgrading to the latest version when syntax error occurs in sql, so sometimes the application crashes without saving the job.
![problem](https://user-images.githubusercontent.com/9035153/43162979-140ec7d4-8f63-11e8-89e5-dcefe50d1a4c.gif)

**Comment by serge-rider** [comment]
What is your OS?

Could you make a thread dump once  it will freeze again? (https://github.com/dbeaver/dbeaver/wiki/Making-a-thread-dump)

**Comment by CoconutTherapy** [comment]
Since last release I have not had the issue again.

I'm on Windows 10 32bit. The freeze lasts ~2sec max and then DBeaver closes itself. I'll try my best if things go south again.
