### ISSUE TITLE
NullPointerException after dragging a table from oracle to ER diagram

### ISSUE THREAD

**Issue by yanOnGithub** [dbeaver/dbeaver#3857]
It only happen at that table.

eclipse.buildId=unknown
java.version=1.8.0_161
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.jface 4 2 2018-07-26 19:02:15.436
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.erd.part.AssociationPart.setConnectionRouting(AssociationPart.java:109)
	at org.jkiss.dbeaver.ext.erd.part.AssociationPart.createFigure(AssociationPart.java:90)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:494)
	at org.eclipse.gef.editparts.AbstractConnectionEditPart.activateFigure(AbstractConnectionEditPart.java:92)
	at org.eclipse.gef.editparts.AbstractConnectionEditPart.addNotify(AbstractConnectionEditPart.java:99)
	at org.eclipse.gef.editparts.AbstractConnectionEditPart.setParent(AbstractConnectionEditPart.java:268)
	at org.eclipse.gef.editparts.AbstractConnectionEditPart.setTarget(AbstractConnectionEditPart.java:300)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addTargetConnection(AbstractGraphicalEditPart.java:291)
	at org.jkiss.dbeaver.ext.erd.part.PropertyAwarePart.handleInputChange(PropertyAwarePart.java:142)
	at org.jkiss.dbeaver.ext.erd.part.PropertyAwarePart.propertyChange(PropertyAwarePart.java:101)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.jkiss.dbeaver.ext.erd.model.ERDObject.firePropertyChange(ERDObject.java:87)
	at org.jkiss.dbeaver.ext.erd.model.ERDEntity.addReferenceAssociation(ERDEntity.java:132)
	at org.jkiss.dbeaver.ext.erd.model.ERDAssociation.<init>(ERDAssociation.java:88)
	at org.jkiss.dbeaver.ext.erd.model.ERDDecoratorDefault.createAutoAssociation(ERDDecoratorDefault.java:204)
	at org.jkiss.dbeaver.ext.erd.model.ERDEntity.resolveRelations(ERDEntity.java:266)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.resolveRelations(EntityDiagram.java:153)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.addEntity(EntityDiagram.java:137)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.addEntity(EntityDiagram.java:112)
	at org.jkiss.dbeaver.ext.erd.command.EntityAddCommand.execute(EntityAddCommand.java:98)
	at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:228)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.handleDrop(AbstractTransferDropTargetListener.java:339)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.drop(AbstractTransferDropTargetListener.java:183)
	at org.eclipse.jface.util.DelegatingDropAdapter$3.run(DelegatingDropAdapter.java:219)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.util.DelegatingDropAdapter.drop(DelegatingDropAdapter.java:216)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:91)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.dnd.DropTarget.Drop(DropTarget.java:464)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(DropTarget.java:398)
	at org.eclipse.swt.dnd.DropTarget$1.method6(DropTarget.java:262)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:119)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:371)
	at org.eclipse.swt.dnd.DragSource.lambda$0(DragSource.java:172)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by serge-rider** [comment]
This happens with self-referencing tables.
thanks for bug report
