### ISSUE TITLE
Autocomplete not working on 5.1.4

### ISSUE THREAD

**Issue by dtogneri** [dbeaver/dbeaver#3911]
After upgrade from 5.1.3 to 5.1.4, autocomplete column or table names are not working.

![image](https://user-images.githubusercontent.com/11077216/43592746-9bcf0090-964c-11e8-9684-e556b8e531ec.png)

**Comment by ltnakPa1g0w** [comment]
Happening to me as well

**Comment by globalqss** [comment]
Same here - any workaround, I think that's one of the most important features  :(

Also zooming to table/view definition with control-click from editor is not working.

**Comment by dtogneri** [comment]
"Also zooming to table/view definition with control-click from editor is not working."

Yes, same here.

**Comment by globalqss** [comment]
Thanks @serge-rider - OS here is Ubuntu 16.04.5 LTS

**Comment by globalqss** [comment]
Tested the 5.1.5 EA in my Ubuntu 16.04.5 LTS and still doesn't work.  Back to 5.1.3

**Comment by dtogneri** [comment]
I am using Windows10. Tested with to PostgreSQL databases.

**Comment by serge-rider** [comment]
Can't reproduce this in EA on Ubuntu 16.
What is your database?

**Comment by serge-rider** [comment]
@dtogneri Maybe it is something more complicated. Can you reproduce this with system object? Set pg_catalog as active schema and type 'select * from` <kbd>ctrl+space</kbd>. Does it show system tables?

**Comment by dtogneri** [comment]
@serge-rider . With system object works!

![image](https://user-images.githubusercontent.com/11077216/43685990-a7199894-9894-11e8-9485-820ae05fffc3.png)

**Comment by serge-rider** [comment]
Ok. Then something is wrong with regular tables.
Could you check error/debug for any related errors/warnings? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by dtogneri** [comment]
After tested with system objects, I can't reproduce the error. Its working again. :) thanks!

**Comment by dtogneri** [comment]
Maybe that was the error?

!ENTRY org.jkiss.dbeaver.model 4 0 2018-08-03 16:27:25.585
!MESSAGE Error reading property 'subTables' from public.saving
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-08-03 16:27:25.585
!MESSAGE SQL Error [08003]: This connection has been closed.
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [08003]: This connection has been closed.
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getSubInheritance(PostgreTable.java:293)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getSubTables(PostgreTable.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:239)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:229)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract.getPropertyValue(PropertySourceAbstract.java:178)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$PropertiesReader.run(SQLContextInformer.java:338)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer.makeObjectDescription(SQLContextInformer.java:254)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer.readAdditionalProposalInfo(SQLContextInformer.java:261)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProposal.getAdditionalProposalInfo(SQLCompletionProposal.java:248)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$2$1.run(AdditionalInfoController.java:113)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1621)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:415)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:229)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getSubInheritance(PostgreTable.java:264)
	... 14 more

**Comment by serge-rider** [comment]
Yes, this may be the error. Thanks for checking.

If connection is dead then auto-completion doesn't work (silently).
This is not the first time when such behavior confuses users. So I've add connection auto-recover function in SQL completion procedure.

**Comment by globalqss** [comment]
PostgreSQL 9.6.9 + Ubuntu 16.04.5 LTS

Still not solved here.

@serge-rider - what you wrote above is a good clue, but the behavior is still wrong in EA 5.1.5.201808042217

The thing is thi:
- **when I open DBeaver** - it shows me the last SQL editor that I used - and in the active schema it shows <None>@idempiere

I can change the schema to my intended schema, and then it works.

The thing is that the schema selector is just shown when I open DBeaver.
If I open a new connection, or I close the SQL Editor and open it again, then the schema editor is not even visible in the toolbar, and I'm back to problems with auto-select.

Right click in toolbar and selected "Restore Hidden Toolbar Entries" did nothing.

So, unfortunately, back to 5.1.3 again.

Regards,

Carlos Ruiz

**Comment by serge-rider** [comment]
Yeah, now I can reproduce this. The problem is in schema selector which doesn't work if option "Show non default databases" was turned off.
(Workaround is to turn it on).

Thanks for details.

**Comment by serge-rider** [comment]
New EA was published

**Comment by globalqss** [comment]
Thanks @serge-rider - it's working fine with latest EA

**Comment by xhafan** [comment]
On DBeaver 6.0 and Postgresql 11.2 I had to expand the list of tables and hit F5. Not sure if the next step is needed, I also expanded Columns for one of the tables, and hit F5. After this, autocomplete started working for me.
