### ISSUE TITLE
Cannot establish tunnel to MySQL

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3917]
When trying to connect to SSH Tunnel with JSch I get this error:

```
Cannot establish tunnel
  Auth fail
  Auth fail
```

The debug log says:

```
2018-08-02 22:06:50.857 - Connect with 'xxx.yyy' (mysql5-163d6635589-2983690c749436c8)
2018-08-02 22:06:50.857 - Instantiate SSH tunnel
2018-08-02 22:06:50.857 - Connect to tunnel host
2018-08-02 22:06:50.873 - SSH INFO: Connecting to xxx.yyy port 22
2018-08-02 22:06:50.919 - SSH INFO: Connection established
2018-08-02 22:06:50.966 - SSH INFO: Remote version string: SSH-2.0-OpenSSH
2018-08-02 22:06:50.966 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2018-08-02 22:06:50.966 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2018-08-02 22:06:50.982 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2018-08-02 22:06:51.123 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-08-02 22:06:51.123 - SSH INFO: SSH_MSG_KEXINIT sent
2018-08-02 22:06:51.123 - SSH INFO: SSH_MSG_KEXINIT received
2018-08-02 22:06:51.123 - SSH INFO: kex: server: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2018-08-02 22:06:51.138 - SSH INFO: kex: server: ssh-dss,ssh-rsa,ssh-dss
2018-08-02 22:06:51.138 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr
2018-08-02 22:06:51.138 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr
2018-08-02 22:06:51.138 - SSH INFO: kex: server: hmac-sha1,hmac-ripemd160
2018-08-02 22:06:51.138 - SSH INFO: kex: server: hmac-sha1,hmac-ripemd160
2018-08-02 22:06:51.138 - SSH INFO: kex: server: none,zlib@openssh.com
2018-08-02 22:06:51.138 - SSH INFO: kex: server: none,zlib@openssh.com
2018-08-02 22:06:51.154 - SSH INFO: kex: server: 
2018-08-02 22:06:51.154 - SSH INFO: kex: server: 
2018-08-02 22:06:51.154 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2018-08-02 22:06:51.154 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2018-08-02 22:06:51.169 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-08-02 22:06:51.169 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2018-08-02 22:06:51.169 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-08-02 22:06:51.169 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2018-08-02 22:06:51.185 - SSH INFO: kex: client: none
2018-08-02 22:06:51.185 - SSH INFO: kex: client: none
2018-08-02 22:06:51.185 - SSH INFO: kex: client: 
2018-08-02 22:06:51.185 - SSH INFO: kex: client: 
2018-08-02 22:06:51.185 - SSH INFO: kex: server->client aes128-ctr hmac-sha1 none
2018-08-02 22:06:51.185 - SSH INFO: kex: client->server aes128-ctr hmac-sha1 none
2018-08-02 22:06:51.201 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2018-08-02 22:06:51.201 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2018-08-02 22:06:51.248 - SSH INFO: ssh_rsa_verify: signature true
2018-08-02 22:06:51.248 - SSH INFO: Host 'xxx.yyy' is known and matches the RSA host key
2018-08-02 22:06:51.248 - SSH INFO: SSH_MSG_NEWKEYS sent
2018-08-02 22:06:51.248 - SSH INFO: SSH_MSG_NEWKEYS received
2018-08-02 22:06:51.248 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2018-08-02 22:06:51.279 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2018-08-02 22:06:51.326 - SSH INFO: Disconnecting from xxx.yyy port 22
2018-08-02 22:06:51.326 - Connection failed (mysql5-163d6635589-2983690c749436c8)
2018-08-02 22:06:51.404 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:733)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:657)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:147)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:195)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:77)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:125)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:70)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:731)
	... 14 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:69)
	... 17 more
```

I'm trying to connect with a password and I'm sure the credentials are OK. I can connect fine with Putty or with HeidiSQL (but the latter uses Putty for SSH so it's the same). I'm on Windows. Can you figure out from the log what may be wrong? I tried to use the SSHJ plugin but the installation fails with an error every time.

**Comment by serge-rider** [comment]
Can't reproduce.
Are you using public/private key auth or password?

**Comment by lemon-juice** [comment]
I'm using password. The problem is certainly not about credentials - even when I enter wrong password or wrong login DBeaver reports the same error. This must be something specific about the server I'm connecting to but I don't even know what info I should give you and how to get the necessary info about the server - so far I only know it's Debian 5.

I can connect with Putty without problems so if you know some SSH commands to get necessary info I can run them.

**Comment by serge-rider** [comment]
Seems to be the same issue as #298 and #3284
Could you try SSHJ instead of JSch (Help->Install New Software->https://dbeaver.io/update/sshj/latest/)?

**Comment by lemon-juice** [comment]
Yes, I've already gone through the other two related issues but I didn't find any solution there so that's why I created a new issue. If this would help you identify the problem I can create an SSH account for you on this server and send you credentials via PM.

---
As to SSHJ, as I wrote earlier I can't install it for some reason, DBeaver says 'Installing Software' has encountered a problem:
```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.batik.constants,1.9.1.v20180227-1645
No repository found containing: osgi.bundle,org.apache.batik.css,1.9.1.v20180313-1559
No repository found containing: osgi.bundle,org.apache.batik.i18n,1.9.1.v20180227-1645
No repository found containing: osgi.bundle,org.apache.batik.util,1.9.1.v20180227-1645
No repository found containing: osgi.bundle,org.apache.commons.cli,1.3.1
No repository found containing: osgi.bundle,org.apache.felix.scr,2.0.14.v20180117-1452
No repository found containing: osgi.bundle,org.apache.xmlgraphics,2.2.0.v20180410-1551
No repository found containing: osgi.bundle,org.eclipse.compare,3.7.200.v20180418-1233
No repository found containing: osgi.bundle,org.eclipse.compare.core,3.6.200.v20180312-1255
No repository found containing: osgi.bundle,org.eclipse.core.commands,3.9.100.v20180404-1234
No repository found containing: osgi.bundle,org.eclipse.core.contenttype,3.7.0.v20180426-1644
No repository found containing: osgi.bundle,org.eclipse.core.databinding,1.6.200.v20180509-1517
No repository found containing: osgi.bundle,org.eclipse.core.databinding.observable,1.6.200.v20180424-1922
No repository found containing: osgi.bundle,org.eclipse.core.databinding.property,1.6.200.v20180403-0944
No repository found containing: osgi.bundle,org.eclipse.core.expressions,3.6.100.v20180426-1644
No repository found containing: osgi.bundle,org.eclipse.core.filebuffers,3.6.200.v20180512-1137
No repository found containing: osgi.bundle,org.eclipse.core.filesystem,1.7.100.v20180304-1102
No repository found containing: osgi.bundle,org.eclipse.core.jobs,3.10.0.v20180427-1454
No repository found containing: osgi.bundle,org.eclipse.core.net,1.3.200.v20180515-0858
No repository found containing: osgi.bundle,org.eclipse.core.resources,3.13.0.v20180512-1138
No repository found containing: osgi.bundle,org.eclipse.core.runtime,3.14.0.v20180417-0825
No repository found containing: osgi.bundle,org.eclipse.core.variables,3.4.100.v20180509-0959
No repository found containing: osgi.bundle,org.eclipse.debug.core,3.12.0.v20180509-0959
No repository found containing: osgi.bundle,org.eclipse.debug.ui,3.13.0.v20180514-0621
No repository found containing: osgi.bundle,org.eclipse.e4.core.commands,0.12.200.v20180427-0801
No repository found containing: osgi.bundle,org.eclipse.e4.core.contexts,1.7.0.v20180514-1409
No repository found containing: osgi.bundle,org.eclipse.e4.core.di,1.7.0.v20180427-1454
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.annotations,1.6.100.v20180427-1454
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.extensions,0.15.100.v20180403-1008
No repository found containing: osgi.bundle,org.eclipse.e4.core.di.extensions.supplier,0.15.100.v20180427-1454
No repository found containing: osgi.bundle,org.eclipse.e4.core.services,2.1.100.v20180427-1454
No repository found containing: osgi.bundle,org.eclipse.e4.emf.xpath,0.2.100.v20180403-0944
No repository found containing: osgi.bundle,org.eclipse.e4.ui.bindings,0.12.100.v20180509-1220
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.core,0.12.200.v20180417-2309
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt,0.13.100.v20180515-1637
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt.theme,0.12.0.v20180403-0944
No repository found containing: osgi.bundle,org.eclipse.e4.ui.di,1.2.200.v20180403-0945
No repository found containing: osgi.bundle,org.eclipse.e4.ui.model.workbench,2.1.0.v20180429-1333
No repository found containing: osgi.bundle,org.eclipse.e4.ui.services,1.3.100.v20180403-0945
No repository found containing: osgi.bundle,org.eclipse.e4.ui.widgets,1.2.100.v20180403-0945
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench,1.6.0.v20180516-2019
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.addons.swt,1.3.100.v20180516-2019
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.renderers.swt,0.14.200.v20180516-2019
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench.swt,0.14.200.v20180516-2019
No repository found containing: osgi.bundle,org.eclipse.e4.ui.workbench3,0.14.100.v20180403-0945
No repository found containing: osgi.bundle,org.eclipse.ecf,3.9.0.v20180402-2015
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.core.feature,1.5.0.v20180426-1936
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.core.ssl.feature,1.1.100.v20180301-0201
No repository found containing: osgi.bundle,org.eclipse.ecf.filetransfer,5.0.100.v20180301-0132
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.feature,3.14.0.v20180306-0429
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.httpclient4.feature,3.14.0.v20180301-0132
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.httpclient4.ssl.feature,1.1.100.v20180301-0132
No repository found containing: org.eclipse.update.feature,org.eclipse.ecf.filetransfer.ssl.feature,1.1.100.v20180301-0132
No repository found containing: osgi.bundle,org.eclipse.ecf.identity,3.9.0.v20180426-1936
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer,3.2.400.v20180306-0429
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient4,1.1.300.v20180301-0132
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient4.ssl,1.1.100.v20180301-0132
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.ssl,1.0.100.v20180301-0132
No repository found containing: osgi.bundle,org.eclipse.ecf.ssl,1.2.100.v20180301-0132
No repository found containing: osgi.bundle,org.eclipse.emf.common,2.14.0.v20180527-1134
No repository found containing: osgi.bundle,org.eclipse.emf.ecore,2.14.0.v20180529-1144
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.change,2.12.0.v20180125-1130
No repository found containing: osgi.bundle,org.eclipse.emf.ecore.xmi,2.14.0.v20180129-1548
No repository found containing: osgi.bundle,org.eclipse.equinox.app,1.3.500.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.bidi,1.1.100.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.common,3.10.0.v20180412-1130
No repository found containing: osgi.bundle,org.eclipse.equinox.concurrent,1.1.100.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.ds,1.5.100.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.event,1.4.200.v20180426-0845
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin,2.1.0.v20180131-0638
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin.equinox,1.1.0.v20180512-1128
No repository found containing: osgi.bundle,org.eclipse.equinox.launcher,1.5.0.v20180512-1130
No repository found containing: osgi.bundle,org.eclipse.equinox.launcher.win32.win32.x86_64,1.1.700.v20180518-1200
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.artifact.repository,1.2.0.v20180413-0846
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.console,1.1.0.v20180130-1836
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.core,2.5.0.v20180512-1128
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature,1.5.0.v20180515-1348
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director,2.4.0.v20180302-1057
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.engine,2.6.0.v20180409-1209
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.garbagecollector,1.1.0.v20180103-0918
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.jarprocessor,1.1.0.v20180512-1128
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata,2.4.0.v20180320-1220
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata.repository,1.3.0.v20180302-1057
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.operations,2.5.0.v20180302-1057
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature,1.4.0.v20180515-1348
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository,2.4.0.v20180512-1128
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.eclipse,2.2.0.v20180302-1057
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.natives,1.3.0.v20180512-1128
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.transport.ecf,1.2.0.v20180222-0922
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui,2.5.100.v20180425-1343
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk,1.1.0.v20180103-0918
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.scheduler,1.4.0.v20180302-1057
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.updatechecker,1.2.0.v20180302-1057
No repository found containing: osgi.bundle,org.eclipse.equinox.preferences,3.7.100.v20180510-1129
No repository found containing: osgi.bundle,org.eclipse.equinox.registry,3.8.0.v20180426-1327
No repository found containing: osgi.bundle,org.eclipse.equinox.security,1.2.400.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.security.ui,1.2.0.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.security.win32.x86_64,1.1.0.v20171221-2204
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator,1.3.0.v20180502-1828
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator.manipulator,2.1.0.v20180103-0918
No repository found containing: osgi.bundle,org.eclipse.equinox.util,1.1.0.v20180419-0833
No repository found containing: osgi.bundle,org.eclipse.help,3.8.100.v20180512-1136
No repository found containing: osgi.bundle,org.eclipse.jface,3.14.0.v20180423-0714
No repository found containing: osgi.bundle,org.eclipse.jface.databinding,1.8.200.v20180403-0945
No repository found containing: osgi.bundle,org.eclipse.jface.text,3.13.0.v20180527-1819
No repository found containing: osgi.bundle,org.eclipse.jsch.core,1.3.100.v20180309-1840
No repository found containing: osgi.bundle,org.eclipse.jsch.ui,1.3.100.v20180418-1233
No repository found containing: osgi.bundle,org.eclipse.ltk.core.refactoring,3.9.0.v20180220-2105
No repository found containing: osgi.bundle,org.eclipse.ltk.ui.refactoring,3.9.100.v20180425-1219
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.core,3.24.0.v20170629-1728
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.core,1.16.0.v20170629-1728
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.ui,1.16.0.v20170629-1728
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.screenshots,3.24.0.v20170629-1728
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.ui,3.24.0.v20170629-1728
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.workbench,3.24.0.v20180613-1658
No repository found containing: osgi.bundle,org.eclipse.osgi,3.13.0.v20180409-1500
No repository found containing: osgi.bundle,org.eclipse.osgi.compatibility.state,1.1.100.v20180331-1743
No repository found containing: osgi.bundle,org.eclipse.osgi.services,3.7.0.v20180223-1712
No repository found containing: osgi.bundle,org.eclipse.osgi.util,3.5.0.v20180219-1511
No repository found containing: osgi.bundle,org.eclipse.platform,4.8.0.v20180611-0500
No repository found containing: osgi.bundle,org.eclipse.search,3.11.200.v20180503-1856
No repository found containing: osgi.bundle,org.eclipse.swt,3.107.0.v20180611-0422
No repository found containing: osgi.bundle,org.eclipse.swt.win32.win32.x86_64,3.107.0.v20180611-0422
No repository found containing: osgi.bundle,org.eclipse.team.core,3.8.200.v20180309-1840
No repository found containing: osgi.bundle,org.eclipse.team.ui,3.8.100.v20180418-1233
No repository found containing: osgi.bundle,org.eclipse.text,3.6.300.v20180430-1330
No repository found containing: osgi.bundle,org.eclipse.ui,3.109.100.v20180426-0903
No repository found containing: osgi.bundle,org.eclipse.ui.cheatsheets,3.5.200.v20180418-0908
No repository found containing: osgi.bundle,org.eclipse.ui.console,3.8.0.v20180413-0859
No repository found containing: osgi.bundle,org.eclipse.ui.editors,3.11.100.v20180512-1137
No repository found containing: osgi.bundle,org.eclipse.ui.forms,3.7.200.v20180512-1133
No repository found containing: osgi.bundle,org.eclipse.ui.ide,3.14.0.v20180517-1842
No repository found containing: osgi.bundle,org.eclipse.ui.ide.application,1.2.100.v20180416-2050
No repository found containing: osgi.bundle,org.eclipse.ui.intro,3.5.200.v20180328-0550
No repository found containing: osgi.bundle,org.eclipse.ui.navigator,3.7.100.v20180524-1240
No repository found containing: osgi.bundle,org.eclipse.ui.navigator.resources,3.6.100.v20180427-1355
No repository found containing: osgi.bundle,org.eclipse.ui.net,1.3.200.v20171208-1604
No repository found containing: osgi.bundle,org.eclipse.ui.themes,1.2.100.v20180514-1547
No repository found containing: osgi.bundle,org.eclipse.ui.views,3.9.100.v20180427-1355
No repository found containing: osgi.bundle,org.eclipse.ui.views.log,1.2.200.v20180512-1206
No repository found containing: osgi.bundle,org.eclipse.ui.views.properties.tabbed,3.8.100.v20180427-1355
No repository found containing: osgi.bundle,org.eclipse.ui.workbench,3.111.0.v20180524-1156
No repository found containing: osgi.bundle,org.eclipse.ui.workbench.texteditor,3.11.0.v20180419-2011
No repository found containing: osgi.bundle,org.eclipse.update.configurator,3.4.0.v20180512-1141
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.feature,5.1.4
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ce.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application,5.1.4
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.application.nls,5.1.4
No repository found containing: osgi.bundle,org.jkiss.dbeaver.core.nls,5.1.4
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.db2.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.db2.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.derby.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.erd.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.exasol.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.exasol.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.firebird.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.generic.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.generic.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.h2.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.hsqldb.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.import_config.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.informix.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mockdata.nls,1.0.0
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mssql.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.mysql.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.mysql.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.netezza.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.oracle.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.oracle.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.phoenix.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.postgresql.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database,1.0.26
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sample.database.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.sqlite.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.teradata.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.ui.locks.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.vertica.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ext.wmi.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.ext.wmi.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.model.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.feature,2.1.64
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.rcp.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.runtime.ide.core.nls,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.runtime.nls.feature,1.0.21
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.feature,5.1.4
No repository found containing: org.eclipse.update.feature,org.jkiss.dbeaver.standalone.nls.feature,1.0.21
No repository found containing: osgi.bundle,org.jkiss.dbeaver.ui.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.utils.nls,1.0.21
No repository found containing: osgi.bundle,org.jkiss.wmi.nls,1.0.21
No repository found containing: osgi.bundle,org.objectweb.asm,6.1.1.v20180414-0329
No repository found containing: osgi.bundle,org.tukaani.xz,1.8.0.v20180207-1613
```

**Comment by serge-rider** [comment]
I think this would make much sense (as I don't have access to problem SSH servers at the moment and can't reproduce this issue). Please write me on serge@jkiss.org.

In regards to SSHJ install - you need to do this under admin permissions (https://github.com/dbeaver/dbeaver/wiki/Optional-extensions) or install DBeaver in some non-default directory.

**Comment by lemon-juice** [comment]
I've sent you account details for testing.

I've managed to install SSHJ under admin permissions. DBeaver then connects to SSH but can't connect to the db:

```
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
    Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
```

**Comment by serge-rider** [comment]
Well, the problem is in auth methods. Server supports only `publickey` and `keyboard-interactive`. I.e. it can't auth with plain password. Will see how to handle this (I believe we can use keyboard-interactive somehow).

**Comment by serge-rider** [comment]
Ok, I've resolved the problem with JSch. now it works as good as SSHJ with keyboard-interactive.

Now solving problem with the driver connection ("Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost").

**Comment by serge-rider** [comment]
Finally I figured this out.
Check this: https://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql

Shortly: connection to localhost doesn't work, you need to set domain name or real IP address in database connection settings. Because MySQL configuration rejects connections from localhost/127.0.0.1.

I've been able to connect to the server by setting proper host name.
I'll make new EA version today later. For now you could try this with SSHJ implementation - it works as well.

**Comment by lemon-juice** [comment]
Thank you, it's great you figured this out!

> Shortly: connection to localhost doesn't work, you need to set domain name or real IP address in database connection settings. Because MySQL configuration rejects connections from localhost/127.0.0.1.
> 
> I've been able to connect to the server by setting proper host name.

My bad, I actually missed that part because I forgot that our providers indeed has a dedicated internal host name for database connections instead of localhost so I should have known better. The SSH host name works as well just as you found out.

Therefore, SSHJ already works for me, if JSch will be fixed then that's great, too.
