### ISSUE TITLE
Start dbeaver via java -jar ....?

### ISSUE THREAD

**Issue by gjaaf** [dbeaver/dbeaver#3925]
Hi, 
I've used dbeaver some time ago on FreeBSD, by starting it like java -jar .... In the current version the application to start is a binary, which is linux specific and which does not work on FreeBSD. Is there  a correct way to start dbeaver without using the binary, by specifying the correct parameters to the java command? I'm aware that this is not officially supported, but if possible I'd like to be able to use it again.

The linux binary dumps this as an error message:

ELF binary type "0" not known.
ELF binary type "0" not known.
Dbeaver:
JVM terminated. Exit code=8
/usr/local/bin/java
-XX:+IgnoreUnrecognizedVMOptions
-Xms64m
-Xmx1024m
-jar /home/xxx/development/dbeaver/dbeaver/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar
-os linux
-ws gtk
-arch x86
-showsplash
-launcher /home/xxx/development/dbeaver/dbeaver/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86/dbeaver/dbeaver
-name Dbeaver
--launcher.library /home/xxx/development/dbeaver/dbeaver/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_1.1.700.v20180518-1200/eclipse_1705.so
-startup /home/xxx/development/dbeaver/dbeaver/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar
--launcher.overrideVmargs
-exitdata 11001d
-vm /usr/local/bin/java
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
-Xms64m
-Xmx1024m
-jar /home/xxx/development/dbeaver/dbeaver/product/standalone/target/products/org.jkiss.dbeaver.core.product/linux/gtk/x86/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.0.v20180512-1130.jar 

For those familiar with the linux compatibility on FreeBSD: yes, the binary was signed as  a linux binary.

So I tried to start the application using the indicated jars, but get this in the logs:

!SESSION 2018-08-05 11:12:44.186 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=unknown, ARCH=x86_64, WS=unknown, NL=en_US

!ENTRY org.eclipse.osgi 4 0 2018-08-05 11:12:47.859
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.workbench (153).
!STACK 0
org.osgi.framework.BundleException: Error starting module.
	at org.eclipse.osgi.container.Module.doStart(Module.java:590)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:466)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:187)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:931)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:60)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:191)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/swt/SWTError
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:763)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:716)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.111.0.v20180524-1156
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

Anyway to get dbeaver running again? I can succesfully build the application using mvn clean install.

Cheers,

GJ

**Comment by serge-rider** [comment]
You can start DBeaver from command line.
It is described in #3747 (particular jar versions depends on DBeaver version, check them in plugins folder).

However we do not support FreeBSD officially. But I know that some guys are able to run Eclipse there so this should be also possible for DBeaver.

Error `java.lang.ClassNotFoundException: org.eclipse.swt.SWTError` means that platform was failed to load SWT plugin which depends on native binaries (ELF so).

**Comment by gjaaf** [comment]
Installing eclipse & running dbeaver as a plugin makes dbeaver work in FreeBSD
