### ISSUE TITLE
OrientDB 3.0 driver cannot connect

### ISSUE THREAD

**Issue by sjurco** [dbeaver/dbeaver#3934]
I am unable to connect to OrientDB using 3.0.x jdbc version. 

Driver info:
--------------

Name: **OrientDB 3.0**
Driver Type: **Generic**
Class Name: **com.orientechnologies.orient.jdbc.OrientJdbcDriver**
URL Template: **jdbc:orient:remote:{host}:{port}/{database}**
Artifact Group Id: **com.orientechnologies**
Artifact Id: **orientdb-jdbc**
Artifact Version: **3.0.5**

Connection to orientdb using official docker image: orientdb:3.0.5

Connection fails with 2 gui dialogs:
   1. Connect to 'OrientDB 3.0 - test - localhost': Null connection returned
   2. Problem Occured: 'Opening database connection' has encountered a problem. jdk/nashorn/api/scripting/ScriptObjectMirror

Info from console:
```
2018-08-06 16:46:10.165 - Connect with 'OrientDB 3.0 - test - localhost' (53CA7854-AFCB-6FDB-141D-7F3E544653E1-164cbb864b9-4e54cf192d6ceef)
2018-08-06 16:46:10.174 - null
java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror
	at com.orientechnologies.orient.core.command.script.OJavascriptScriptExecutor.<init>(OJavascriptScriptExecutor.java:14)
	at com.orientechnologies.orient.core.command.script.OScriptManager.lambda$new$0(OScriptManager.java:70)
	at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:99)
	at com.orientechnologies.orient.core.Orient.<init>(Orient.java:75)
	at com.orientechnologies.orient.core.Orient.startUp(Orient.java:199)
	at com.orientechnologies.orient.core.Orient.instance(Orient.java:185)
	at com.orientechnologies.orient.core.db.OrientDBInternal.remote(OrientDBInternal.java:88)
	at com.orientechnologies.orient.core.db.OrientDB.<init>(OrientDB.java:166)
	at com.orientechnologies.orient.jdbc.OrientJdbcConnection.<init>(OrientJdbcConnection.java:62)
	at com.orientechnologies.orient.jdbc.OrientJdbcDriver.connect(OrientJdbcDriver.java:52)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:147)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:271)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:217)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
2018-08-06 16:46:10.216 - Connection failed (53CA7854-AFCB-6FDB-141D-7F3E544653E1-164cbb864b9-4e54cf192d6ceef)
2018-08-06 16:46:10.217 - org.jkiss.dbeaver.model.exec.DBCException: Null connection returned
org.jkiss.dbeaver.model.exec.DBCException: Null connection returned
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:104)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:67)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:130)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:745)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

It's still possible to connect to db using old driver and run queries, but there were significant changes in some parts of communication protocol especially error reporting which now fails using the old driver.

Is there anything I could change in driver/connection settings to make it work?

**Comment by sjurco** [comment]
Thank you. It works.

There's one other problem that it does not work with URL Template containing port **jdbc:orient:remote:{host}:{port}/{database}**. But I assume it's a problem with orientdb-jdbc library itself.

In case there is no problem for dbeaver and/or other drivers it would be great to have it working out of the box.

**Comment by serge-rider** [comment]
Perhaps we need two different OrientDB drivers (for older and newer versions).
Do you have working driver configuration for 3.x driver? Could you post it?

**Comment by serge-rider** [comment]
We need to:
1. Update bundled Java to the most recent Java 1.8 version
2. Make sure that extension jar is available for DBeaver

**Comment by EliYk** [comment]
I'm working with another JDBC driver that uses nashorn for json parsing. I understand it is relatively fast, and avoids a few Mb of dependencies carrying along Jackson or anther library.

Is it feasible to somehow allow DBeaver to recognize JDK 8 libraries?

**Comment by E1izabeth** [comment]
The issue is not actual anymore. I can connect with the latest driver version using special connection type for OrientDB
![image](https://github.com/user-attachments/assets/36521e73-4ea7-4ceb-bcac-fdb29a1f79f9)
