### ISSUE TITLE
Can't install SSHJ - Error reading signed content

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#3996]
I tried installing SSHJ plugin from https://dbeaver.io/update/sshj/latest/ but I can't do it in 5.1.5 (worked in 5.1.4), I receive this error:

```
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.bouncycastle_1.59.0
```
I start DBeaver as administrator, of course.

**Comment by serge-rider** [comment]
Can't reproduce (as well as #3997). 
What Windows version do you use? Do you have internet aaccess or you are behind some proxy? 
Could you post full error log?

**Comment by lemon-juice** [comment]
I use Windows 10 Home Premium 64-bit, OS Build 17134.191. I don't use any proxy. My internet access seems fine, I've tried installing SSHJ 3 times in the last 2 days but I got the same error every time.

Log:
```
!SESSION 2018-08-14 19:19:35.448 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.equinox.p2.engine 4 4 2018-08-14 19:20:38.520
!MESSAGE An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2018-08-14 19:20:38.520
!MESSAGE session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2018-08-14 19:20:38.520
!MESSAGE Error reading signed content.
!STACK 0
java.io.IOException: Exception in opening zip file: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.bouncycastle_1.59.0
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:321)
	at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:212)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:74)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:55)
	at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:52)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:252)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:102)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:47)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:77)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:45)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:175)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:73)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.io.FileNotFoundException: C:\Program Files\DBeaver\plugins\org.jkiss.bundle.bouncycastle_1.59.0 (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:304)
	... 13 more
```

**Comment by serge-rider** [comment]
Could you t ry to re-install DBeaver? Maybe plugin files were corrupted during download (reinstalling sshj won't help because it is cached and not downloaded on second attempt).

**Comment by lemon-juice** [comment]
I uninstalled DBeaver and installed again (without resetting user data) and installation of SSHJ succeeded. Thanks for your help. But perhaps it would be a good idea to make it a bit more user friendly, for example in case of an error offer an option to clear the plugin files without the need to reinstall DBeaver?

**Comment by serge-rider** [comment]
Agreed. The problem is that we are using standard Eclipse p2 update framework. Sometimes it fails to download artifacts and it doesn't has any recovery UI. IT is quite uneasy to fix this from DBeaver side..

**Comment by serge-rider** [comment]
Yep, this makes sense.
