### ISSUE TITLE
java.lang.NullPointerException while opening ssh tunnel

### ISSUE THREAD

**Issue by krilim** [dbeaver/dbeaver#4017]
I have a _java.lang.NullPointerException_ while opening ssh tunnel

"Test tunnel configuration" runs ok but when I open the database the null pointer exception is returned.

DBever v5.1.5.201808130751

The tunnel config is the same as previous version

Console error is:

`2018-08-17 17:17:15.704 - SSH INFO: Connecting to XXXXX port 22
2018-08-17 17:17:15.709 - Connection failed (mysql5-1574bb9e2c8-629fe0c048a1d356)
2018-08-17 17:17:15.762 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:739)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:658)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:147)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:195)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:81)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:125)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:72)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:734)
        ... 14 more
Caused by: com.jcraft.jsch.JSchException: java.lang.NullPointerException
        at com.jcraft.jsch.Util.createSocket(Util.java:394)
        at com.jcraft.jsch.Session.connect(Session.java:215)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationJsch.setupTunnel(SSHImplementationJsch.java:73)
        ... 17 more
Caused by: java.lang.NullPointerException
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.matchesParameters(SSHTunnelImpl.java:86)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.findConnectionContext(DBExecUtils.java:75)
        at org.jkiss.dbeaver.runtime.net.GlobalProxySelector.select(GlobalProxySelector.java:66)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at java.base/java.net.Socket.connect(Socket.java:540)
        at java.base/java.net.Socket.<init>(Socket.java:436)
        at java.base/java.net.Socket.<init>(Socket.java:213)
        at com.jcraft.jsch.Util$1.run(Util.java:362)
        at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by serge-rider** [comment]
I can see how this may happen in theory but I can't reproduce it.
Looks like there is no host name in your target database socket URI.
Anyhow, I'll add the fix.

Please check this in EA version (https://dbeaver.io/files/ea/)

**Comment by krilim** [comment]
With the EA version it runs ok and open the ssh tunnel as expected.

Thank you for fast service :-)

**Comment by serge-rider** [comment]
Thanks for testing :)
