### ISSUE TITLE
Can not copy explain result

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4054]
Running `explain ...` query in psql I can copy result:

```
 CTE Scan on tree  (cost=132.81..134.83 rows=101 width=556)
   CTE tree
     ->  Recursive Union  (cost=0.14..132.81 rows=101 width=556)
           ->  Index Scan using resource_type_idx_parent_resource_type_id on resource_type  (cost=0.
                 Index Cond: (parent_resource_type_id IS NULL)
           ->  Hash Join  (cost=0.33..12.26 rows=10 width=556)
                 Hash Cond: (rt.parent_resource_type_id = tree_1.id)
                 ->  Seq Scan on resource_type rt  (cost=0.00..11.30 rows=130 width=524)
                 ->  Hash  (cost=0.20..0.20 rows=10 width=36)
                       ->  WorkTable Scan on tree tree_1  (cost=0.00..0.20 rows=10 width=36)
(10 rows)
```

When I click right mouse button on result in dbeaver and select `Copy` menu item. I get no result.
`Advanced copy` also do nothing

**Comment by KES777** [comment]
Actually if text is selectable and `copy` is available in menu 
I expect it text is copied into clipboard.

![delete1](https://user-images.githubusercontent.com/799021/45358938-bdb0af00-b5d3-11e8-8cec-cef445e5e8af.jpg)

**Comment by serge-rider** [comment]
Yes, and copy actually works.
But in explain plan view it copies only current selected cell value.

**Comment by KES777** [comment]
no, it does not work

see video: 
[Kazam_screencast_00000.mp4.tar.gz](https://github.com/dbeaver/dbeaver/files/2374361/Kazam_screencast_00000.mp4.tar.gz)

**Comment by serge-rider** [comment]
Weird. Must be something GTK-specific. Or maybe a bug. Could you check error/debug logs for any related  messages? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by KES777** [comment]
```
!ENTRY org.eclipse.ui 4 4 2018-09-13 13:30:04.966
!MESSAGE Failed to execute item null
!STACK 0
org.eclipse.core.commands.NotEnabledException: Trying to execute the disabled command org.eclipse.ui.edit.copy
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:485)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:393)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:820)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:797)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:162)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by KES777** [comment]
#4033

**Comment by uslss** [comment]
cannot reproduce on 6.0.2. (Ubuntu 18.04)
