### ISSUE TITLE
OutOfMemoryError error when trying to export data to the TXT format

### ISSUE THREAD

**Issue by NekoKoneko** [dbeaver/dbeaver#4096]
Exporting Postgres table data (or a select resultset) to TXT raises java.lang.OutOfMemoryError.

**Steps to reproduce:**

1. Create and fill the table
```
CREATE TABLE public.t1 (a TEXT);
INSERT INTO public.t1 SELECT * FROM generate_series(1, 10);
SELECT * FROM public.t1;
```
2. Select "Export Resultset" from the context menu.
3. In the Data Transfer window select TXT format and press Next 4 times, then Finish.
4. The window closes and after 2 or 3 seconds an error message box is shown: Java heap space

**Exception stack trace:**
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT.printHeader(DataExporterTXT.java:118)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterTXT.exportHeader(DataExporterTXT.java:85)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchStart(StreamTransferConsumer.java:114)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:676)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:462)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob$$Lambda$334/498306255.run(Unknown Source)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1559)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:387)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:819)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2346)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataContainer.readData(ResultSetDataContainer.java:110)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:146)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:114)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Environment:**
DBeaver 5.1.6 x64
Windows 7 x64
PostgreSQL 10.5 on Ubuntu 18.04 amd64

**Comment by serge-rider** [comment]
This happens because of huge TEXT column lengths.
Thanks for the bug report.
