### ISSUE TITLE
SQL Server: Error while executing Stored Procedure through UI

### ISSUE THREAD

**Issue by ascendhans** [dbeaver/dbeaver#4113]
DBeaver - Version 5.1.6 CE
Operating System: Windows 10
JDBC Driver: jTDS 1.3.1
Database: Microsoft SQL Server Database

When i use the following command in SQL Editor, I am able to add values for each parameter through UI. But when i press OK button i get the error pop up. Even though the values are correct and tested using other SQL Server Management Studio.
EXEC dbo.[uspGetAverage](:pClassID, :pInstitutionID) 

The error pop up is:
![image](https://user-images.githubusercontent.com/38669892/44802370-2bdf8580-ab81-11e8-9331-2db9e61bdc3f.png)

If i execute the same Stored Procedure in the following way, mentioned below. I am able to get the results back.
EXEC dbo.[uspGetAverage] 16129,2775

**Comment by fuadmuhtaz** [comment]
Try this:
EXEC dbo.[uspGetAverage] :pClassID, :pInstitutionID

If you not sure how to run procedure, try right click procedure name > Execute Stored Procedure

**Comment by ascendhans** [comment]
EXEC dbo.[uspGetAverage] :pClassID, :pInstitutionID
This runs correctly, but when i do an autocomplete with CTRL+SPACE for a stored procedure name uspGetAverage, I am getting the following, which does not get executed. I have to format it the way you have stated.

EXEC dbo.[uspGetAverage;1](:@pClassID, :@pInstitutionID)

**Comment by ascendhans** [comment]
Can we please have an update on this bug @serge-rider ?

**Comment by serge-rider** [comment]
I can't reproduce that. What SQL Server driver do you use? 
Old drivers (jTDS or MS) may work incorrectly in some cases.

**Comment by ascendhans** [comment]
I am using MS SQL Driver. I have tried this with JTDS also. I see the same behaviour.
When i execute the following stored procedure:
EXEC uspGetApiAccess(:@pClassID, :@pRole, :@pUserID)

I get the following exception:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [102] [S0001]: Incorrect syntax near ':'.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2727)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ':'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 11 more

**Comment by ascendhans** [comment]
@serge-rider  To recreate this issue, you can have a sample stored procedure in your database.

Step 1: Type EXEC and then space
Step 2: Type CTRL + ENTER to get auto complete options. This will show you list of Stored procedures.
Step 3: Select one of the Stored procedure suggested by the autocomplete
Step 4: Run the stored procedure. It should ask for inputs for the parameters defined inside stored procedure.
Step 5: After entering these parameters, click OK and you will get the exception you see in the above comment.

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on ticket more than a month. 
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
