### ISSUE TITLE
Can not initialize cryptographic mechanism and more

### ISSUE THREAD

**Issue by GuiBCa** [dbeaver/dbeaver#4136]
After open, this error returns:

```shell
2018-08-31 14:35:24.964 - Run workbench
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.emf.ecore.xmi.impl.XMLHandler (file:/usr/share/dbeaver/plugins/org.eclipse.emf.ecore.xmi_2.13.0.v20170609-0707.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.eclipse.emf.ecore.xmi.impl.XMLHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-08-31 14:35:30.916 - Initializing DBeaver 5.1.6.201808262133
2018-08-31 14:35:30.925 - Host plugin: org.jkiss.dbeaver.core.application 5.1.6.201808262133
2018-08-31 14:35:30.932 - Initialize Core...
2018-08-31 14:35:30.950 - Can't find BC security provider. Use default JCE.
2018-08-31 14:35:30.951 - BouncyCastle not registered, using the default JCE provider
2018-08-31 14:35:31.662 - Project 'General' not found in registry
2018-08-31 14:35:32.024 - Core initialized (1092ms)
2018-08-31 14:35:32.025 - Configure workbench window
2018-08-31 14:35:32.226 - Create actions
2018-08-31 14:35:32.244 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2018-08-31 14:35:32.246 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2018-08-31 14:35:33.623 - Open [https://dbeaver.io/product/version.xml]
2018-08-31 14:35:34.007 - null
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2613)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2635)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:603)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:575)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(CipherSuite.java:461)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:1075)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(SSLContextImpl.java:354)
	at java.base/sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:42)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:590)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1848)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:81)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:49)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:44)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:51)
	at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:89)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
	... 32 more
Caused by: java.lang.SecurityException: Couldn't parse jurisdiction policy files in: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:355)
	at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
```
Some days ago, I installed another Java SDK for work Netbeans 8.2, is that possibly caused to conflict within?
If, what SDK version do I need to use for work both?

**Comment by serge-rider** [comment]
This seems to be Java9 SDK related. Kind of SDK configuration corruption.
Check this issue for workaround ): https://github.com/zaproxy/zaproxy/issues/3757#issuecomment-333407059
