### ISSUE TITLE
Question / clickhouse driver / ErrMsg "ClickHouse response without column names"

### ISSUE THREAD

**Issue by heyciao** [dbeaver/dbeaver#4142]
Hi
I installed Clickhouse 18.6.0 & 18.10.3 (same issue with both) and I can connect and do stuff with e.g. ...
___
clickhouse-client -h <my_external_ip_address> -u <my_user> --password <my_pwd>
use clkhs01
select * from dummy;
___
...but with dbeaver (5.1.0) I keep getting the following error message when trying to connect:
___
Unexpected driver error occurred while connecting to database
  ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: <hostname_mapped_to_external_ip_address>, port: 8123; ClickHouse response without column names
    ClickHouse exception, code: 1002, host: <hostname_mapped_to_external_ip_address>, port: 8123; ClickHouse response without column names
      ClickHouse response without column names
      ClickHouse response without column names
___
What do I have to do to successfully establish a connection?
I downloaded all drivers from Dbeaver iself - it was all automated (AKA innocent bystander, hehe).
Thx

**Comment by serge-rider** [comment]
I can't reproduce this. 
At least latest client driver (0.1.42) works fine with latest Clickhouse server (18.10.3). no any issues with connect.
Do you use Clickouse client on the same machine as DBeaver?

**Comment by heyciao** [comment]
The Clickhouse client does work fine on the same machine on which I run DBeaver (and as well on the machine on which I run the Clickhouse server).
On the same machine which runs DBeaver I can successfully connect as well using "curl" (e.g. with the command "curl 'http://myuser:mypwd@quad:8123/test01?query=SELECT%201' ") and as well using the DB-client "HouseOps" (and I'm using everywhere the same combo of user & pwd & target database).

I have downloaded the latest version of DBeaver (5.1.6 Community Edition) but I'm having as well there the same problem.

I'm using the Clickhouse driver 0.1.41 => from where can I get 0.1.42?
Not sure what else I could try... .

Here is the full output I get in the console from DBeaver when the connection fails:

```
2018-09-03 21:02:40.223 - Connect with 'ClickHouse - test01' (yandex_clickhouse-165a07b92dd-539b72e8fa6dca7a)
2018-09-03 21:02:40.275 - Connection failed (yandex_clickhouse-165a07b92dd-539b72e8fa6dca7a)
2018-09-03 21:02:40.275 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:177)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:126)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:84)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:104)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:67)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:130)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:751)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: quad, port: 8123; ClickHouse response without column names
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:91)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:75)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:50)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:32)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:147)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:259)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:205)
	... 2 more
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: quad, port: 8123; ClickHouse response without column names
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:88)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:134)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:94)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:89)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:86)
	... 9 more
Caused by: java.lang.IllegalArgumentException: ClickHouse response without column names
	at ru.yandex.clickhouse.response.ClickHouseResultSet.<init>(ClickHouseResultSet.java:78)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:122)
	... 13 more
```

**Comment by serge-rider** [comment]
Sorry, it was a typo, driver is 0.1.41.

Well, I'm a bit frustrated. Actual error happens inside Clickhouse driver. It doesn't like server response by some reason. I can't catch the same error although I tried to change various client settings.

Maybe it is something in server configuration (I believe you didn't change default driver settings in DBeaver).

Maybe it is a bug in client driver. You could try some older client driver version (you can change driver version in driver editor dialog->Libraries->Download/Update->Click on the driver version column).

**Comment by heyciao** [comment]
Ha! Now it works, yuhuu :)
I started changing all kind of options and I now see that I can connect if in the driver properties of DBeaver I change the "**compress**" option to "**false**". Absolutely no clue why that causes problems.
Thanks a lot anyway for your replies and compliments for DBeaver - it's absolutely fantastic :)

**Comment by abhid** [comment]
The latest version of DataGrip from Jetbrains seems to use this driver and setting Compression to false in the advanced settings resolves the issue.
