### ISSUE TITLE
Can't browse tables in AWS Redshift with 5.1.6

### ISSUE THREAD

**Issue by trwrt** [dbeaver/dbeaver#4150]
Since upgrading from 5.1.5 I can no longer browse tables in the navigator on AWS Redshift.  I can open a database and see the list of schemas under it, but when I open one and click the '>' next to Tables to expand it I just get an empty list.

**Comment by serge-rider** [comment]
What Redshift version do you use? Are there any error in error/debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by hoenie-ams** [comment]
Getting the same error in DBeaver version 5.2.2 when connecting to AWS Redshift (com.amazon.redshift.jdbc42.Driver). 

Error log ('xxxxxxx' to hide name):
com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: External schema "mkbbrandstofdemo" cannot be set in search_path;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario2ForPrepareExecution(Unknown Source)
	at com.amazon.redshift.client.PGClient.handleErrorsPrepareExecute(Unknown Source)
	at com.amazon.redshift.client.PGClient.executePreparedStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.executePreparedStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeSQL(JDBCUtils.java:583)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.setSearchPath(PostgreDatabase.java:603)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.setDefaultObject(PostgreDatabase.java:550)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar$6.run(DataSourceManagementToolbar.java:661)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)

**Comment by serge-rider** [comment]
This seems to be related to external tables #4265.

**Comment by hoenie-ams** [comment]
The weird thing is, it does work on my colleagues Mac. He is running DBeaver 5.1.5. I installed that version too but that didn't make a difference. It seems to be a local problem on my Mac.

**Comment by hoenie-ams** [comment]
Just tried it again with version 5.2.4 and the issue no longer exists. Thanks!
