### ISSUE TITLE
5.2.1 on Mac will not start

### ISSUE THREAD

**Issue by hobbyman** [dbeaver/dbeaver#4276]
Mac OSX 10.12.6

> java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Error Log:
!SESSION Tue Sep 25 06:59:24 CDT 2018 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2018-09-25 06:59:24.932
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/adaptor/EclipseStarter : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:650)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by hobbyman** [comment]
Sorry, maybe it's a non-issue. The first time I downloaded the .dmg and moved the App into /Applications.

Then I downloaded the .pkg, ran the installer and the applications launches as expected.

**Comment by serge-rider** [comment]
You need Java 1.8 to run DBeaver. Use pkg installer or install Java 8 separately.

**Comment by jeveloper** [comment]
Used to work on Java 10 , Java 11 its crashing , just an update @serge-rider

**Comment by matthieumota** [comment]
+1 Dbeaver no longer works with Java 11 on macOS

**Comment by serge-rider** [comment]
Eclipse platform (4.7.) doesn't support Java 11. Waiting for platform patch. 
Please use PKG installer, it is the easiest way to solve any problems with Java versions.

**Comment by neverfox** [comment]
I have multiple java versions available via homebrew versions and normally manage them through jenv, but how can I tell DBeaver to just use Java 8 (when launching from program icon, not shell)?
