### ISSUE TITLE
SQL Workbench/j formatter error

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#4346]
Hi,

I'm trying to configure Sql workbench/j formatter as SQL formarter.
I'm using DBeaver 5.2.2 under Linux Mint 19, with Java 8

I've downloaded and unzip SQL Workbench/j (latest version).
In DBeaver preferences, I select "Sql workbench/j formatter" as formatter and point the directory containing SQL Workbench/J jar file in "SQL Workbench/J path".
When I click on the "Apply" button, I get the following error message:
Error formatting with SQL Workbench/J

Motif:
Error calling SQL Workbench/J formatter

Here is the log entry associated with this error:
2018-10-08 08:29:01.348 - null
org.jkiss.dbeaver.DBException: Error calling SQL Workbench/J formatter
	at org.jkiss.dbeaver.ext.format.sqlworkbenchj.SQLWorkbenchJManager.format(SQLWorkbenchJManager.java:94)
	at org.jkiss.dbeaver.ext.format.sqlworkbenchj.SQLWorkbenchJFormatter.format(SQLWorkbenchJFormatter.java:46)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLFormattingStrategy.format(SQLFormattingStrategy.java:63)
	at org.eclipse.jface.text.formatter.ContentFormatter.format(ContentFormatter.java:501)
	at org.eclipse.jface.text.formatter.ContentFormatter.formatRegion(ContentFormatter.java:412)
	at org.eclipse.jface.text.formatter.ContentFormatter.format(ContentFormatter.java:364)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:992)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1378)
	at org.jkiss.dbeaver.ui.preferences.PrefPageSQLFormat.formatSQL(PrefPageSQLFormat.java:306)
	at org.jkiss.dbeaver.ui.preferences.PrefPageSQLFormat.performApply(PrefPageSQLFormat.java:259)
	at org.eclipse.jface.preference.PreferencePage.lambda$1(PreferencePage.java:286)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.handlers.ShowPreferencePageHandler.execute(ShowPreferencePageHandler.java:59)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.format.sqlworkbenchj.SQLWorkbenchJManager.format(SQLWorkbenchJManager.java:75)
	... 65 more

Thanks in advance for your help,
Cedric

**Comment by p91paul** [comment]
This issue happens in the preference page, but also while formatting a script which is not on an open connection (none or a disconnected one). In the preferences page, while apply throws this error, "Apply and close" seems to work correctly.

Line 75 of SQLWorkbenchJManager does this:

    String driverClassName = dataSource.getContainer().getDriver().getDriverClassName();

Which throws a NPE if there is no open connection.
