### ISSUE TITLE
BIG Oracle Issue: Timestamp fields always NULL in result

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#4348]
Hi Serge,

I am running most recent version 5.2.2.

It seems that when using Oracle, all Timestamp fields are displayed as NULL in the result set.

**Comment by JamesInform** [comment]
Had a look into the previous versions:

5.2.0 worked fine, 5.2.1 also displays NULL when timestamp field.

So this bug seems to be introduced in version 5.2.1

**Comment by serge-rider** [comment]
If you have Oracle 11 then this bug was fixed #4270.
So 5.2.2 should contains this fix.

- Please check how `SELECT current_timestamp FROM dual` works
- Please check debug.log (https://github.com/dbeaver/dbeaver/wiki/Log-files) for any related errors

**Comment by serge-rider** [comment]
Also please post exact DBeaver version (from About dialog)

**Comment by JamesInform** [comment]
Hi,

`SELECT current_timestamp FROM dual`

give NULL.

Please see attached screenshot for version info and more, as well as the attached log files.
Hope that helps!

![screenshot_dbeaver522](https://user-images.githubusercontent.com/38714600/46629488-47a35780-cb41-11e8-9b95-6fb700996f42.png)
[log.log](https://github.com/dbeaver/dbeaver/files/2457434/log.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2457436/dbeaver-debug.log)

**Comment by JamesInform** [comment]
By the way. 

The problem exists under Windows 10 as well as Mac OS X High Sierra!

**Comment by serge-rider** [comment]
Yeah, it is a different issue. Internal Oracle timestamp with time zone representation.
I've added yet another fix. Could you test this in new Early Access version (https://dbeaver.io/files/ea)?

**Comment by JamesInform** [comment]
Hi Serge,

thank you for your effor. I have tested the early access version.

But still getting NULL.

Now I am getting 
`!ENTRY org.jkiss.dbeaver.model 2 0 2018-10-08 23:07:06.253
!MESSAGE Unrecognized type 'oracle.sql.TIMESTAMPLTZ' - can't convert to date/time value` 
in the log file.

The problem seems to be related to the TIMESTAMPLTZ (Timestamp with LOCAL timezone).
[log.log](https://github.com/dbeaver/dbeaver/files/2457905/log.log)

**Comment by serge-rider** [comment]
You are right. Could you try it one more time? Now it should handle all oracle.sql.TIMESTAMP* types.

**Comment by JamesInform** [comment]
Now it throws an exception.

See attached log.
![screenshot](https://user-images.githubusercontent.com/38714600/46634866-b5a44a80-cb52-11e8-8d9b-b4b11124e803.png)
[log.log](https://github.com/dbeaver/dbeaver/files/2458044/log.log)

**Comment by serge-rider** [comment]
Arrgh. Too bad that I can't reproduce this on my side. It is some combination of server/client versions + server configuration.

I'll build new EA tomorrow morning.

**Comment by serge-rider** [comment]
New EA is ready (5.2.3, https://dbeaver.io/files/ea)

**Comment by JamesInform** [comment]
Hi Serge,

ALL THUMBS UP !!!!

Now it works like a charm!

Thank you very much for your effort!

**Comment by serge-rider** [comment]
Good, thanks for testing )

**Comment by stwessels** [comment]
Hi, I can confirm this error and the fix for TIMESTAMPLTZ in the early access version (5.2.3.201810101600 curiously built at 22nd October).

However, I still get the exception when executing:
`SELECT current_timestamp FROM dual;`
->
`DBCException: Error extracting Oracle TIMESTAMP value`

```
eclipse.buildId=unknown
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Wed Oct 10 16:29:09 UTC 2018


java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getTimestampReadMethod(OracleTimestampValueHandler.java:84)
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getValueFromObject(OracleTimestampValueHandler.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:729)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:465)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2385)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by serge-rider** [comment]
@stwessels Thank you for the bug report. Still can't reproduce so testing in a blind mode :)

**Comment by jsmtslch** [comment]
@serge-rider - I am seeing this issue after I updated to DBeaver 5.3. Attaching a screenshot.
![timestampissue](https://user-images.githubusercontent.com/15079071/50249300-98d68f80-03ab-11e9-9bd7-7a80a01a4a53.png)
