### ISSUE TITLE
SSH Tunnel tab not available

### ISSUE THREAD

**Issue by acguglielmo** [dbeaver/dbeaver#4371]
Hello,

Today I updated DBeaver to version 5.2.1.201809240911 and I can't find the tab "SSH Tunnel" under "Edit Connection" >> "Connection Settings" >> "Network". Was it removed? If yes, how can I configure the SSH Tunnel settings for new connections?

P.S.: The old connections configured using SSH Tunnels still work, but don't show this tab anymore.

![ssh tunnel tab not showing](https://user-images.githubusercontent.com/7442816/46764123-01b9d100-ccb2-11e8-9ba9-05b87bd162c5.png)

**Comment by serge-rider** [comment]
Wow. That's weird. Seems to be some kind of glitch.
Could you upgrade to 5.2.2 to be on the same page?

Then please send debug/error log - maybe something is failing in background. (https://github.com/dbeaver/dbeaver/wiki/Log-files).

**Comment by acguglielmo** [comment]
Hi @serge-rider,

I closed and opened DBeaver again, without updating to 5.2.2, and now the tab is appearing normally. 

I believe that I did an "apt update" followed by "apt upgrade" with DBeaver running earlier today (I use DBeaver's PPA repository). This could have caused this issue.

But by curiosity, I inspected the logs and found this: 

`!ENTRY org.jkiss.dbeaver.model 4 0 2018-10-10 17:23:46.174
!MESSAGE Can't create network configurator 'ssh_tunnel'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-10-10 17:23:46.174
!MESSAGE Can't load class 'org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI'
!STACK 0
org.jkiss.dbeaver.DBException: Can't load class 'org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI'
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:154)
	at org.jkiss.dbeaver.registry.configurator.UIPropertyConfiguratorDescriptor.createConfigurator(UIPropertyConfiguratorDescriptor.java:53)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetwork.createHandlerTab(ConnectionPageNetwork.java:104)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetwork.activatePage(ConnectionPageNetwork.java:150)
	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
	at org.jkiss.dbeaver.ui.dialogs.MultiPageWizardDialog.changePage(MultiPageWizardDialog.java:248)
	at org.jkiss.dbeaver.ui.dialogs.MultiPageWizardDialog.showPage(MultiPageWizardDialog.java:302)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard.openSettingsPage(ConnectionWizard.java:322)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.openSettingsPage(ConnectionPageSettings.java:307)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageAbstract$1.widgetSelected(ConnectionPageAbstract.java:150)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1488)
	at org.eclipse.swt.widgets.Link.gtk_button_release_event(Link.java:384)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1957)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5608)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9282)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1328)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4181)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openConnectionEditor(NavigatorHandlerObjectOpen.java:268)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:144)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:131)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.openNavigatorNode(NavigatorUtils.java:620)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.execute(NavigatorHandlerObjectOpen.java:97)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
`
