### ISSUE TITLE
SOCKS proxy is ignored for localhost connections

### ISSUE THREAD

**Issue by ghuname** [dbeaver/dbeaver#4413]
Hi,

I have reported an issue https://github.com/dbeaver/dbeaver/issues/3592
but looks like it is partially solved.

With socks5 enabled, when I execute select, execute query starts, than invalidate connections of [connection name], than set connection defaults, and finally the select is executed properly. Also dbeaver shows a notification: "Datasource was invalidated, live connection count: 2/2"

Because of invalidation of the connection, query is 10 seconds slower than it should be.
Looks like this problem is partially solved by issue 3592.

Can you please check?

**Comment by serge-rider** [comment]
I can't reproduce this. Generally this sounds like some problem in proxy server configuration (connection invalidation happens if actual socket connection was broken by some reason).
What proxy server do you use? Is there anything special about its configuration?
I'm testing SOCKS5 with 3proxy utility on local machine.

**Comment by ghuname** [comment]
I will try to explain the setup.

In ~/.ssh/config I have a proxy (please notice that connection from my computer to 100.240.150.110 goes over 100.243.150.240 proxy):

Host my_host
HostName 100.240.150.110 (fake IP)
ProxyCommand ssh proxy_user@100.243.150.240 nc %h %p
User user

by using ssh my_host I am (paswordless) connected to the my_host, so ssh works.

Now I have executed:
autossh -M 0 -q -f -N -g -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" my_host -D9871

I have created a new clickhouse connection, populate host as localhost, port as 8123, than I have clicked on "Network settings (SSH, SSL, Proxy, ...)", Tab SOCKS proxy, turned on Use SOKCS Proxy, then for host I have set localhost and for port 9871.

Test connection works.

If I execute "show tables from default", each time I am getting sequence:
1. execute query
2. invalidate connections of [connection name]
3. set connection defaults
4. select returned all rows
5. notification: "Datasource was invalidated, live connection count: 2/2"

At the end, I am getting good result, but queries took around 10 seconds more because of the first three steps.

**Comment by serge-rider** [comment]
So far I don't have a clue what causes this. By some reason connection is broken right after query execution. 
This might be because of SOCKS proxy, SSH tunnel, DBeaver proxy selector, Clickhouse driver, some network misconfiguration, anything.

- Does this happen with all queries?
- Did you try to to configure SSH in DBeaver?
- Could you try another version of Clickhouse driver?

**Comment by ghuname** [comment]
As I can see it happens with all queries.

At the moment I am using autossh -M 0 -q -f -N -g -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" server -L 2001:localhost:8123 
and than in dbeaver I am using localhost and port 2001 which works well.

Socks5 proxy works well with FoxyProxy in chrome.

I haven't tried another version of the Clickhouse driver. Current version is 0.42

**Comment by ghuname** [comment]
Is there debug log or something which I could use to diagnose the problem?

**Comment by serge-rider** [comment]
Sure: https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ghuname** [comment]
Does this help?

`2018-10-22 15:16:04.808 - Invalidate datasource 'Grab 1 - socks5' connections...
2018-10-22 15:16:06.837 - Use SOCKS proxy [localhost/127.0.0.1:9871]
2018-10-22 15:16:08.916 - Use SOCKS proxy [localhost/127.0.0.1:9871]
2018-10-22 15:16:08.971 - Operation failed. Retry count remains = 1
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1002]: ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:140)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:448)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
        at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2385)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect, host: localhost, port: 8123; Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:62)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:529)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:105)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:89)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:165)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
        ... 11 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8123 [localhost/0:0:0:0:0:0:0:1, localhost/127.0.0.1] failed: Connection refused: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:510)
        ... 17 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        ... 27 more
2018-10-22 15:16:09.056 - Table 'system.tables' not found in metadata catalog`

**Comment by ghuname** [comment]
This is the log for executing "show databases". I just want to say that "show databases" returned correct data.

**Comment by serge-rider** [comment]
Umm. I'll need to reproduce this locally.
Thanks for the logs. I have a couple of lcues but not the solution yet..

**Comment by ghuname** [comment]
I there anything new about this subject?

**Comment by gangh** [comment]
any new ?

**Comment by uslss** [comment]
hi @ghuname ,
is issue still actual for you?
