### ISSUE TITLE
Eclipse: multiple java.lang.NullPointerException

### ISSUE THREAD

**Issue by catonymous** [dbeaver/dbeaver#4443]
.log

> !ENTRY org.eclipse.ui.workbench 4 2 2018-10-19 16:39:29.045
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLInformationProvider.update(SQLInformationProvider.java:90)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLInformationProvider$EditorWatcher.partActivated(SQLInformationProvider.java:54)
	at org.eclipse.ui.internal.PartService$1.run(PartService.java:86)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.PartService.partActivated(PartService.java:83)
	at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3083)
	at org.eclipse.ui.internal.WorkbenchPage$3.run(WorkbenchPage.java:5058)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:5055)
	at org.eclipse.ui.internal.WorkbenchPage.access$3(WorkbenchPage.java:5040)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:214)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:253)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:250)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:775)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:97)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.lambda$0(ContributedPartRenderer.java:63)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1624)
	at org.eclipse.swt.widgets.Control.sendMouseEvent(Control.java:3502)
	at org.eclipse.swt.widgets.Tree.sendMouseEvent(Tree.java:2791)
	at org.eclipse.swt.widgets.Control.mouseEvent(Control.java:2607)
	at org.eclipse.swt.widgets.Composite.mouseEvent(Composite.java:930)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2616)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2114)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5962)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2414)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6086)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5325)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5477)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3730)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

Java version:

>java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Eclipse version:

>Eclipse Java EE IDE for Web Developers.
>
>Version: 2018-09 (4.9.0)
Build id: 20180917-1800

DBeaver Eclipse Plugin version:

>DBeaver Universal Database Manager
>
>Version: 5.2.2.201810071756
>
>(c) Copyright 2010-2016 JKISS (dbeaver@jkiss.org).
>
>Visit https://dbeaver.io/

**Comment by serge-rider** [comment]
It is a known issue, it happens only in the latest Eclipse. It will be fixed in 5.2.3.
Thanks for the bug report anyway.
