### ISSUE TITLE
Oracle unsupported verifier type

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#4514]
Recently my client changed authentication type for our oracle database. Instead of using a single database user for all connections, each person has to use his own personal user. SQLDeveloper Just Works (tm), I changed the previous user with my own and it connects.

DBeaver fails instead with the following exception. Possibly the driver is requiring some additional steps to use this kind of authentication. I don't know the technical details unfortunately, but I'm open to using custom builds to provide more detailed logs if you need so.

```
2018-10-31 11:51:58.246 - Connect with 'jdbc:oracle:thin:@//XXXXX' (oracle_thin-166c9c05991-6dce11b88967a7d6)
2018-10-31 11:51:58.416 - Connection failed (oracle_thin-166c9c05991-6dce11b88967a7d6)
2018-10-31 11:51:58.421 - org.jkiss.dbeaver.model.exec.DBCConnectException: unsupported verifier type
org.jkiss.dbeaver.model.exec.DBCConnectException: unsupported verifier type
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:85)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:130)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:768)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:230)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: unsupported verifier type
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:647)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:359)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:531)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:221)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:503)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 14 more
```

**Comment by serge-rider** [comment]
Could you try this workaround: http://oracle.erkansaka.org/2012/11/javasqlsqlexception-unsupported.html (you can add cli parameter in dbeaver.ini)

**Comment by p91paul** [comment]
Thanks I'll try it out and let you know!

**Comment by p91paul** [comment]
It works! Connection can now be established. Looks like standard connections continue to work too, so this parameter could be enabled by default. However I have no idea of the implications.

**Comment by serge-rider** [comment]
Not sure we should add this by default. Leaving this for those who will find it in google:
You need to add following line in the end of dbeaver.ini file:
```
-Doracle.jdbc.thinLogonCapability=o3
```

**Comment by p91paul** [comment]
I confirm enabling this by default is a bad idea, I just found another database where this options breaks connection. I don't know where the issue lies tough...would be good to know how SQLDeveloper handles this, it is jdbc-based as well as DBeaver.

**Comment by p91paul** [comment]
Just discovered this can be set in connection properties as well:
![immagine](https://user-images.githubusercontent.com/2157006/48471198-a2406b00-e7f3-11e8-8c75-760f3913fd9c.png)

**Comment by p91paul** [comment]
Additional information for anyone stumbling onto this page: after migrating the database to EUS\OUD from EUS\CDM, I had to remove that connection setting to avoid getting `ORA-28274: No ORACLE password attribute corresponding to user nickname exists.`
See https://wiki.loopback.org/display/KB/EUS+Migration+from+OID+to+OUD
