### ISSUE TITLE
Generating Table DDL does not generate complete SAP HANA  DDL

### ISSUE THREAD

**Issue by mradeschnig** [dbeaver/dbeaver#4518]
Generating Table DDL does not generate complet SAP HANA  DDL.
e.g. the column tag is ammited as well the SAP HANA special data types are not considered.

**Comment by serge-rider** [comment]
For HANA we support only views/procedures source code reading. DBeaver generates DDL on client side.
Do you know any system table/function in HANA which returns native table DDL.

**Comment by mradeschnig** [comment]
The following call will do that:
call get_object_definition (<schema_name>, object_name);
The result will be an array with OBJECT_CREATION_STATEMENT being the DDL (as CLOB).
It works at least for tables and views.

**Comment by serge-rider** [comment]
I've added this call but I can't validate that its actually working. Could you test it in Early Access  version (https://dbeaver.io/files/ea).
If it won't show native DDL please check error/debug logs (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by mradeschnig** [comment]
The version 5.3.3 does not retuirn the version of DDL that the function would create, I would say it did not change at all since last version.
I tries it to generate DDL on the object navigation with right click on table > SQL generieren> DDL.
As well with double click on table and inside the DDL sub-tab it does not show the correct version. I would say the **call get_object_definition (<schema_name>, <object_name>)** has not been executed and still the old function call is in place.

**Comment by serge-rider** [comment]
Could you check log files? There may be some warnings/errors related to DDL reading.

**Comment by mradeschnig** [comment]
Here we go with the log-file:

2019-01-17 14:42:51.421 - DBeaver 5.3.3.201901170929 is starting
2019-01-17 14:42:51.425 - OS: Windows 10 10.0 (amd64)
2019-01-17 14:42:51.432 - Java version: 1.8.0_77 by Oracle Corporation (64bit)
2019-01-17 14:42:51.437 - Install path: 'C:\Users\n.noname\AppData\Local\DBeaver'
2019-01-17 14:42:51.442 - Instance path: 'file:/C:/Users/n.noname/.dbeaver4/'
2019-01-17 14:42:51.447 - Memory available 61Mb/910Mb
2019-01-17 14:42:51.471 - Starting RMI server at 27683
2019-01-17 14:42:51.760 - Run workbench
2019-01-17 14:42:51.784 - > Start org.eclipse.e4.ui.workbench.swt [0.14.300.v20180906-1121]
2019-01-17 14:42:51.791 - > Start org.eclipse.e4.core.services [2.1.200.v20180817-1215]
2019-01-17 14:42:51.795 - > Start org.eclipse.e4.core.contexts [1.7.100.v20180817-1215]
2019-01-17 14:42:51.814 - > Start org.eclipse.e4.ui.services [1.3.200.v20180906-1121]
2019-01-17 14:42:51.895 - > Start org.eclipse.e4.ui.di [1.2.300.v20180906-1121]
2019-01-17 14:42:51.978 - > Start com.ibm.icu.base [58.2.0.v20170418-1837]
2019-01-17 14:42:51.981 - > Start org.eclipse.emf.common [2.15.0.v20180723-1316]
2019-01-17 14:42:52.014 - > Start org.eclipse.emf.ecore [2.15.0.v20180722-1159]
2019-01-17 14:42:52.106 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-01-17 14:42:52.419 - > Start org.eclipse.core.filesystem [1.7.200.v20180828-0158]
2019-01-17 14:42:52.548 - > Start org.eclipse.core.resources [3.13.100.v20180828-0158]
2019-01-17 14:42:52.808 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.200.v20180828-0227]
2019-01-17 14:42:52.827 - > Start org.eclipse.core.expressions [3.6.200.v20180817-1401]
2019-01-17 14:42:52.857 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.300.v20180828-0227]
2019-01-17 14:42:53.098 - > Start org.eclipse.e4.ui.bindings [0.12.200.v20180828-0227]
2019-01-17 14:42:53.204 - > Start org.eclipse.e4.core.di.extensions [0.15.200.v20180817-1215]
2019-01-17 14:42:53.221 - > Start org.eclipse.ui.ide [3.14.100.v20180828-1350]
2019-01-17 14:42:54.180 - > Start org.eclipse.e4.ui.css.swt [0.13.200.v20180828-0227]
2019-01-17 14:42:54.311 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.100.v20180828-0227]
2019-01-17 14:42:54.988 - Initializing DBeaver 5.3.3
2019-01-17 14:42:54.992 - Host plugin: org.jkiss.dbeaver.core.application 5.3.3.201901170929
2019-01-17 14:42:54.996 - Initialize Core...
2019-01-17 14:42:55.005 - Can't find BC security provider. Use default JCE.
2019-01-17 14:42:55.009 - BouncyCastle not registered, using the default JCE provider
2019-01-17 14:42:55.221 - > Start org.eclipse.team.core [3.8.300.v20180827-1041]
2019-01-17 14:42:55.248 - > Start org.jkiss.dbeaver.ui.navigator [1.0.1.201901170929]
Warning: NLS unused message: dialog_text_view_open_editor in: org.jkiss.dbeaver.core.CoreResources
Warning: NLS unused message: dialog_text_view_open_editor_tip in: org.jkiss.dbeaver.core.CoreResources
2019-01-17 14:42:55.423 - Total database drivers: 68 (68)
2019-01-17 14:42:55.461 - > Start org.eclipse.equinox.security [1.2.500.v20180827-1235]
2019-01-17 14:42:55.479 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-01-17 14:42:55.482 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-01-17 14:42:55.485 - > Start org.eclipse.core.net [1.3.300.v20180827-1041]
2019-01-17 14:42:55.488 - Core initialized (492ms)
2019-01-17 14:42:55.490 - Configure workbench window
2019-01-17 14:42:55.504 - > Start org.eclipse.help [3.8.200.v20180821-0700]
2019-01-17 14:42:56.916 - Create actions
2019-01-17 14:42:56.921 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-01-17 14:42:56.927 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
Warning: NLS unused message: IDEApplication_workspaceInUse_Cancel in: org.eclipse.ui.internal.ide.messages
2019-01-17 14:42:57.032 - > Start org.eclipse.ui.editors [3.11.200.v20180822-1511]
2019-01-17 14:42:57.037 - > Start org.eclipse.core.filebuffers [3.6.300.v20180822-1339]
2019-01-17 14:42:57.937 - > Start org.eclipse.search [3.11.300.v20180822-1339]
2019-01-17 14:42:58.003 - > Start org.eclipse.ui.workbench.texteditor [3.11.100.v20180824-1030]
2019-01-17 14:42:58.220 - Initialize workbench window
2019-01-17 14:42:58.292 - Finish initialization
2019-01-17 14:42:58.397 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.1.201901170929]
2019-01-17 14:42:58.522 - > Start org.jkiss.dbeaver.ext.erd [2.0.103.201901170929]
2019-01-17 14:42:58.723 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.1.201901170929]
2019-01-17 14:42:59.009 - > Start org.eclipse.debug.core [3.13.0.v20180821-1744]
2019-01-17 14:42:59.059 - > Start org.eclipse.debug.ui [3.13.100.v20180827-0649]
2019-01-17 14:43:00.723 - > Start org.eclipse.compare.core [3.6.300.v20180827-1041]
2019-01-17 14:43:00.870 - > Start org.jkiss.dbeaver.ui.editors.data [1.0.1.201901170929]
Warning: NLS unused message: sql_editor_resultset_filter_panel_btn_config_refresh in: org.jkiss.dbeaver.ui.controls.resultset.internal.ResultSetMessages
Warning: NLS unused message: sql_editor_resultset_filter_panel_btn_stop_refresh in: org.jkiss.dbeaver.ui.controls.resultset.internal.ResultSetMessages
2019-01-17 14:43:02.044 - > Start org.eclipse.ui.views.log [1.2.300.v20180827-1331]
2019-01-17 14:43:03.401 - > Start org.eclipse.equinox.p2.core [2.5.100.v20180822-1532]
2019-01-17 14:43:03.409 - > Start org.eclipse.equinox.p2.operations [2.5.100.v20180822-1302]
2019-01-17 14:43:03.422 - > Start org.eclipse.equinox.p2.engine [2.6.100.v20180822-1302]
2019-01-17 14:43:03.436 - > Start org.eclipse.equinox.p2.metadata [2.4.100.v20180822-1302]
2019-01-17 14:43:03.471 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.100.v20180827-1122]
2019-01-17 14:43:03.475 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-01-17 14:43:03.486 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-01-17 14:43:03.503 - > Start org.eclipse.equinox.p2.repository [2.4.100.v20180822-1354]
2019-01-17 14:43:04.139 - > Start org.jkiss.dbeaver.ext.sample.database [1.0.38.201901170929]
2019-01-17 14:43:04.145 - > Start org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.7.201901170929]
2019-01-17 14:43:04.174 - Event loop exception
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.ui.tipoftheday.ShowTipOfTheDayHandler.loadTips(ShowTipOfTheDayHandler.java:80)
	at org.jkiss.dbeaver.ext.ui.tipoftheday.ShowTipOfTheDayHandler.showTipOfTheDay(ShowTipOfTheDayHandler.java:49)
	at org.jkiss.dbeaver.ext.ui.tipoftheday.TipOfTheDayInitializer.initializeWorkbenchWindow(TipOfTheDayInitializer.java:16)
	at org.jkiss.dbeaver.core.application.ApplicationWorkbenchWindowAdvisor$4.run(ApplicationWorkbenchWindowAdvisor.java:244)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
2019-01-17 14:43:04.286 - > Start org.eclipse.equinox.p2.ui [2.5.200.v20180822-1357]
2019-01-17 14:43:04.306 - Connect with 'SAP - saphana01 - test' (sap_hana-163f904f033-68908b39783256ba)
Warning: NLS unused message: model_navigator_Connections in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_navigator_resource_exception_already_exists in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_project_Script in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_project_Scripts in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_project_bookmarks_folder in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_project_cant_open_bookmark in: org.jkiss.dbeaver.model.messages.ModelResources
Warning: NLS unused message: model_project_open_bookmark in: org.jkiss.dbeaver.model.messages.ModelResources
2019-01-17 14:43:04.354 - > Start org.jkiss.dbeaver.ext.generic [2.3.87.201901170929]
2019-01-17 14:43:04.373 - > Start org.jkiss.dbeaver.ext.hana [1.0.30.201901170929]
2019-01-17 14:43:04.921 - Connected (sap_hana-163f904f033-68908b39783256ba, HDB [1.111.05-bfe01c5fddc5adffd5b6c7ac53c3606585225210])
2019-01-17 14:43:14.877 - > Start org.eclipse.gef [3.11.0.201606061308]
2019-01-17 14:43:26.332 - Error reading DDL from HANA server
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257]: sql syntax error: line 1 col 30 (at pos 30)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.createException(SQLExceptionSapDB.java:345)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.generateDatabaseException(SQLExceptionSapDB.java:185)
	at com.sap.db.jdbc.packet.ReplyPacket.buildExceptionChain(ReplyPacket.java:101)
	at com.sap.db.jdbc.ConnectionSapDB.execute(ConnectionSapDB.java:1059)
	at com.sap.db.jdbc.CallableStatementSapDB.sendCommand(CallableStatementSapDB.java:1832)
	at com.sap.db.jdbc.StatementSapDB.sendSQL(StatementSapDB.java:947)
	at com.sap.db.jdbc.CallableStatementSapDB.doParse(CallableStatementSapDB.java:228)
	at com.sap.db.jdbc.CallableStatementSapDB.constructor(CallableStatementSapDB.java:181)
	at com.sap.db.jdbc.CallableStatementSapDB.<init>(CallableStatementSapDB.java:126)
	at com.sap.db.jdbc.CallableStatementSapDBFinalize.<init>(CallableStatementSapDBFinalize.java:31)
	at com.sap.db.jdbc.ConnectionSapDB.prepareCall(ConnectionSapDB.java:1264)
	at com.sap.db.jdbc.trace.Connection.prepareCall(Connection.java:328)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareCall(JDBCConnectionImpl.java:256)
	at org.jkiss.dbeaver.ext.hana.model.HANAMetaModel.getTableDDL(HANAMetaModel.java:103)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getObjectDefinitionText(GenericTable.java:314)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$1.generateSQL(GenerateSQLContributor.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$1.generateSQL(GenerateSQLContributor.java:1)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$SQLGenerator.run(GenerateSQLContributor.java:413)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$11(UIUtils.java:1520)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:440)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:356)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$3(WorkbenchWindow.java:2254)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2252)
	at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1123)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$26(ProgressManager.java:1000)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:147)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4594)
	at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:1000)
	at org.jkiss.dbeaver.ui.UIUtils.runInUI(UIUtils.java:1519)
	at org.jkiss.dbeaver.ui.UIUtils.runInUI(UIUtils.java:1532)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$GenerateSQLDialog.createDialogArea(GenerateSQLContributor.java:628)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$GenerateSQLDialog.createDialogArea(GenerateSQLContributor.java:1)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:771)
	at org.jkiss.dbeaver.ui.editors.sql.dialogs.ViewSQLDialog.createContents(ViewSQLDialog.java:75)
	at org.eclipse.jface.window.Window.create(Window.java:429)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.create(BaseDialog.java:72)
	at org.eclipse.jface.window.Window.open(Window.java:786)
	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$8.run(GenerateSQLContributor.java:601)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
2019-01-17 14:43:26.979 - Can't get column 'IS_GENERATEDCOLUMN': SAP DBTech JDBC: Invalid column index IS_GENERATEDCOLUMN.
2019-01-17 14:43:34.642 - DBeaver is stopping
2019-01-17 14:43:34.648 - Stop RMI server

**Comment by serge-rider** [comment]
Thanks for the logs.

I've fixed the query which reads DDL, could you test it again (new EA has been published).
It may require a few extra tests as I have to code this in blind mode :(

**Comment by mradeschnig** [comment]
Sorry but obfuscation was required to not show all detials of my stuctures.

**Comment by mradeschnig** [comment]
It works now, it shows the same content like SAP HANA Studio except formation (which is poor in HANA Studio). I think it is anyway possible to paste the DDL in a Editor Tab and format it.
Thank you - this helps me a lot.

**Comment by serge-rider** [comment]
We can apply auto-formatting for DDL (we already do this for MySQL view for example).

But this makes sense only if DDL is never formatted properly (i.e. server doesn't keep user's formatting).

**Comment by mradeschnig** [comment]
Actually there is one line per command: e.g
CREATE TABLE ..
COMMENT ON ...
COMMENT ON ..

**Comment by serge-rider** [comment]
Could you post an example?

**Comment by mradeschnig** [comment]
Here is one example:
![grafik](https://user-images.githubusercontent.com/1084030/51432388-29b4bb00-1c37-11e9-987c-86db52afafc5.png)

**Comment by serge-rider** [comment]
Yes, you can change formatter in preferences and DDL will be formatted with new formatter.

Good, thanks for testing.
