### ISSUE TITLE
 Error freeing BLOB: java.sql.SQLRecoverableException: Closed Connection

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#4536]
Error freeing BLOB: java.sql.SQLRecoverableException: Closed Connection
```
java.lang.NoSuchMethodError: org.jkiss.dbeaver.ext.oracle.model.OracleSchema$IndexCache.getObjects(Lorg/jkiss/dbeaver/model/runtime/DBRProgressMonitor;Lorg/jkiss/dbeaver/model/struct/DBSObject;Lorg/jkiss/dbeaver/model/struct/DBSObject;)Ljava/util/Collection;
	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema.cacheStructure(OracleSchema.java:361)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.lambda$0(ERDEditorEmbedded.java:208)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.collectDatabaseTables(ERDEditorEmbedded.java:206)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:190)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:174)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:149)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
```

see http://www.thatjeffsmith.com/archive/2014/05/exporting-multiple-blobs-with-oracle-sql-developer/

thanks

**Comment by serge-rider** [comment]
This looks like corrupted DBeaver installation.
Try to reinstall DBeaver and make sure that previous version was removed completely.

And I think that #4548 has the same nature.
