### ISSUE TITLE
Dbeaver crash at launch 

### ISSUE THREAD

**Issue by ylepors** [dbeaver/dbeaver#4539]
Hi,

Since Mojave installation, DBeaver crash at launch w/ blank Eclipse SDK window.
My conf:
- Mac OS X: 10.14
- java.version=1.8.0_191
- DBeaver 5.2.3

log file (extract):
!SESSION 2018-11-05 14:34:19.102 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  -keyring /Users/ylepors/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/ylepors/.eclipse_keyring

!ENTRY org.eclipse.ui.workbench 4 2 2018-11-05 14:34:21.847
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
	at org.eclipse.jface.wizard.ProgressMonitorPart.initialize(ProgressMonitorPart.java:244)
	at org.eclipse.jface.wizard.ProgressMonitorPart.<init>(ProgressMonitorPart.java:141)
	at org.eclipse.jface.wizard.ProgressMonitorPart.<init>(ProgressMonitorPart.java:106)
	at org.eclipse.ui.splash.BasicSplashHandler$AbsolutePositionProgressMonitorPart.<init>(BasicSplashHandler.java:53)
	at org.eclipse.ui.splash.BasicSplashHandler.getBundleProgressMonitor(BasicSplashHandler.java:141)
	at org.jkiss.dbeaver.core.application.DBeaverSplashHandler.init(DBeaverSplashHandler.java:69)
	at org.eclipse.ui.internal.Workbench$2.run(Workbench.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:849)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:600)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

!ENTRY org.eclipse.ui 4 0 2018-11-05 14:34:21.851
!MESSAGE Could not instantiate splash
!STACK 0
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:138)
	at org.eclipse.jface.wizard.ProgressMonitorPart.initialize(ProgressMonitorPart.java:244)
	at org.eclipse.jface.wizard.ProgressMonitorPart.<init>(ProgressMonitorPart.java:141)
	at org.eclipse.jface.wizard.ProgressMonitorPart.<init>(ProgressMonitorPart.java:106)
	at org.eclipse.ui.splash.BasicSplashHandler$AbsolutePositionProgressMonitorPart.<init>(BasicSplashHandler.java:53)
	at org.eclipse.ui.splash.BasicSplashHandler.getBundleProgressMonitor(BasicSplashHandler.java:141)
	at org.jkiss.dbeaver.core.application.DBeaverSplashHandler.init(DBeaverSplashHandler.java:69)
	at org.eclipse.ui.internal.Workbench$2.run(Workbench.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:849)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:600)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
[...]

It seems that this type of problem was solved in previous versions of DBeaver, but none of the proposed resolutions I tested worked.

Thanks,
Yves

**Comment by serge-rider** [comment]
Can't reproduce. However it is clearly a bug in splashscreen handler.
You could try to remove line `-showsplash` from dbeaver.ini.

**Comment by ylepors** [comment]
Hi Serge.

Done in /Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini, which is now:
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.800.v20180827-1352
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m
-XstartOnFirstThread

The splashscreen is still displayed and the same error occurs.

**Comment by serge-rider** [comment]
Ok, thanks for checking this.
Could you try to remove file `~/.dbeaver4/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` then? It keeps UI configurations. Maybe it become corrupted after version upgrade.

**Comment by ylepors** [comment]
Done. Still same behaviour:
- splashscreen
- blank window Eclipse SDK
- log file indicates same error

**Comment by serge-rider** [comment]
Ok, then something else is guilty.

I see that your Java version differs from the Java bndled in pkg.
How do you install DBeaver? DMG, zip, or thru some 3rd party package manager?

Could you try to install using PKG (download it from dbeaver.io or GitHub)?

**Comment by serge-rider** [comment]
This is weird (I can't reproduce this on two Macs with Mojave).
Anyhow - please test this on the Early Access version (https://dbeaver.io/files/ea/) - it contains the fix of splash screen handler.

**Comment by ylepors** [comment]
Hello Serge.

Done with both releases (DMG and PKG).
Same behavior: crash at launch after the splashscreen, now no empty or blank window.

You will find attached the debug log files for both releases.
[debug log.zip](https://github.com/dbeaver/dbeaver/files/2552497/debug.log.zip)

**Comment by serge-rider** [comment]
Oops, the archive is password protected

**Comment by ylepors** [comment]
Oops, sorry.
[Debug log.zip](https://github.com/dbeaver/dbeaver/files/2553296/Debug.log.zip)

**Comment by serge-rider** [comment]
Apparently I've made a mistake during Early Access publishing (it is still old). Could you test the latest one (https://dbeaver.io/files/ea/)

**Comment by ylepors** [comment]
Same :/
[debug log-20181106-1454.zip](https://github.com/dbeaver/dbeaver/files/2553402/debug.log-20181106-1454.zip)

**Comment by serge-rider** [comment]
This is a bug in Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540357
I hope they'll find a solution in near days.

This error happens because DBeaver tries to switch to Dark theme (I assume that you using Mojave with dark theme).

Please try this workaround: add line `-nosplash` in dbeaver.ini (before -vmargs line).

**Comment by ylepors** [comment]
I have modified the dbeaver.ini as you suggested (-nospash parameter)
Much better, I have now a clean Eclipse window but I cannot create a new connection and database driver manager is empty (as .dbeaver-driver folder).

Still have NullPointerException 
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/2554198/dbeaver-debug.log)

**Comment by lalato** [comment]
I am experiencing the same issue.  Upgraded to Mojave and suddenly DBeaver no longer works.  Upon start, I see the following as normal...

<img width="619" alt="image" src="https://user-images.githubusercontent.com/9371670/48446266-a5811b80-e74d-11e8-916f-c9c353946e3f.png">

However, after this loads, I see the menu bar options, but the actual editor windows do not open...

<img width="642" alt="image" src="https://user-images.githubusercontent.com/9371670/48446230-8b473d80-e74d-11e8-8558-d5fbd39a116c.png">

Tried adding -nosplash to DBeaver.ini, but that didn't do anything.

**Comment by serge-rider** [comment]
@lalato could you also post debug and error logs?

**Comment by lalato** [comment]
> @lalato could you also post debug and error logs?

Edited original post with debug log

**Comment by lalato** [comment]
Just tried the trick of holding down the Ctrl key during launch.  This seems to be working for me.

**Comment by serge-rider** [comment]
@lalato thanks for details.
> Just tried the trick of holding down the Ctrl key during launch. This seems to be working for me.

Wow. That's unusual. Thanks a lot for the information :)

**Comment by vialrogo** [comment]
> Just tried the trick of holding down the Ctrl key during launch. This seems to be working for me.

Hold down control worked for me. That was weird. Besides, the -nosplash option worked for 5.2.4 but not for 5.2.5. I am using Windows with the new dark theme. I think that is the same issue.

**Comment by greyshine** [comment]
Solved the issue for me:
My problem was that I also installed Java11 in the mean time.  
I do not know if I ever really shut down dbeaver since installation.  
I did the macos latest updates inbetween and it failed as well. Only showing the splash screen and then quitting with a reference to some log file.  
Since I installed Java11 inbetween and that probably installed itself as the main java version on the os I told dbeaver to use the java8 vm:

_/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini_

    -vm
    /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    -startup
    ../Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
    --launcher.library
    ../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.550.v20170928-1359
    -showsplash
    -vmargs
    --add-modules=ALL-SYSTEM
    -Duser.language=en
    -Xms64m
    -Xmx1024m
    -XstartOnFirstThread

I only did add the first two lines with _-vm_ and _/Library/Java/..._ to the existing file.  
!!! Do place it in two lines otherwise eclipse won't properly start with that setting as I understood.

**Comment by tati-kru** [comment]
Thank you for the info @greyshine

**Comment by GayanSandaruwan** [comment]
> Solved the issue for me:
> My problem was that I also installed Java11 in the mean time.
> I do not know if I ever really shut down dbeaver since installation.
> I did the macos latest updates inbetween and it now failed as well. Only showing the splash screen and then quitting with a reference to some log file.
> Since I installed Java11 in between and that probably installed itself as the main java version on the OS I told dbeaver to use the java8 vm:
> 
> _/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini_
> 
> ```
> -vm
> /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
> -startup
> ../Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
> --launcher.library
> ../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.550.v20170928-1359
> -showsplash
> -vmargs
> --add-modules=ALL-SYSTEM
> -Duser.language=en
> -Xms64m
> -Xmx1024m
> -XstartOnFirstThread
> ```
> 
> I only did add the first two lines with _-vm_ and _/Library/Java/..._ to the existing file.
> !!! Do place it in two lines otherwise eclipse won't properly start with that setting as I understood.

@greshyine s method works. I can confirm it.
