### ISSUE TITLE
NullPointerException launching DBeaver 

### ISSUE THREAD

**Issue by jesanfafon** [dbeaver/dbeaver#4545]
DBeaver version 5.2.3 installed via `choco`

Launching DBeaver shows the splash screen, then the process exits. 

The log file contains:

```
!SESSION 2018-11-05 11:28:17.544 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.apache.batik.util.gui 2 0 2018-11-05 11:28:19.518
!MESSAGE Could not resolve module: org.apache.batik.util.gui [16]
  Unresolved requirement: Import-Package: org.apache.batik.util.resources; version="1.8.0"


!ENTRY org.eclipse.osgi.compatibility.state.nls 2 0 2018-11-05 11:28:19.519
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nls [322]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.core.filesystem.win32.x86_64.nls 2 0 2018-11-05 11:28:19.520
!MESSAGE Could not resolve module: org.eclipse.core.filesystem.win32.x86_64.nls [238]
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64


!ENTRY org.eclipse.osgi 4 0 2018-11-05 11:28:19.526
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.getMessageCount(Display.java:2029)
	at org.eclipse.swt.widgets.Display.foregroundIdleProc(Display.java:1317)
	at org.eclipse.swt.internal.win32.OS.VtblCall(Native Method)
	at org.eclipse.swt.widgets.Display.init(Display.java:2711)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:144)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:472)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:463)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:749)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:163)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.getDisplay(DBeaverApplication.java:182)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:115)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
```

**Comment by serge-rider** [comment]
This looks like some installation corruption.
Please make sure that:
- Previous DBeaver version was removed completely.
- If it won't help then try to delete folder .eclipse in your user home directory

**Comment by serge-rider** [comment]
Perhaps duplicate of #4539

**Comment by jesanfafon** [comment]
Ran `choco uninstall dbeaver` and deleted both my .dbeaver4 and .eclipse directories.
Reinstalled dbeaver from Chocolately, and am still running into the same exception.

**Comment by jesanfafon** [comment]
Did a scan for `*dbeaver*` and `*eclipse*` and removed everything dbeaver or java related and reinstalled, but have wound up in the same state.

**Comment by serge-rider** [comment]
Maybe this is a bug in choco package. 

Log complains about org.apache.batik.util.gui bundle dependencies. This file was removed in 5.2.4 but it was used by previous versions (5.2.3). The weird part is that I can't reproduce this (DBeaver runs ok after choco install).

Anyway, 5.2.4 was released today but Choco package is still 5.2.3.
You could try to delete file "c:\program files\dbeaver\plugins\org.apache.batik.util.gui_1.8.0.v20170214-1941.jar".

**Comment by jesanfafon** [comment]
I cleaned up my choco install, and installed 5.2.4 from the downloads page.

```
!SESSION 2018-11-05 13:07:25.944 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.filesystem.win32.x86_64.nls 2 0 2018-11-05 13:07:28.190
!MESSAGE Could not resolve module: org.eclipse.core.filesystem.win32.x86_64.nls [234]
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64
  Unresolved requirement: Fragment-Host: org.eclipse.core.filesystem.win32.x86_64


!ENTRY org.eclipse.osgi.compatibility.state.nls 2 0 2018-11-05 13:07:28.191
!MESSAGE Could not resolve module: org.eclipse.osgi.compatibility.state.nls [317]
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state
  Unresolved requirement: Fragment-Host: org.eclipse.osgi.compatibility.state


!ENTRY org.eclipse.osgi 4 0 2018-11-05 13:07:28.208
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.getMessageCount(Display.java:2029)
	at org.eclipse.swt.widgets.Display.foregroundIdleProc(Display.java:1317)
	at org.eclipse.swt.internal.win32.OS.VtblCall(Native Method)
	at org.eclipse.swt.widgets.Display.init(Display.java:2711)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:144)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:472)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:463)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:749)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:163)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.getDisplay(DBeaverApplication.java:182)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:115)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
```
As far as I can tell, I'm getting the same error as before, minus the batik reference.

Could this be because I'm on a Windows Insider build of Windows?

**Comment by serge-rider** [comment]
This is Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540762

Here is some pretty weird workaround: https://stackoverflow.com/questions/53102860/eclipse-an-error-has-occurred-see-the-log-file-windows-x64 
(you can try to run DBeaver while keeping Ctrl pressed).

**Comment by jesanfafon** [comment]
That works! What a strange work-around!

**Comment by hismayilov** [comment]
Eclipse:
Eclipse Platform

Version: 2020-03 (4.15)
Build id: I20200305-0155

DBeaver:
DBeaver IDE	7.0.1.202003211804	org.jkiss.dbeaver.ide.feature.feature.group	JKISS

I have 2 different workspace, A and B.
I installed DBeaver in B and it works in B, 
then i open my work space A and opened DBeaver perspective, here we go, I am stuck on error message "java.lang.NullPointerException"
