### ISSUE TITLE
AWS Redshift driver not available

### ISSUE THREAD

**Issue by yesisg** [dbeaver/dbeaver#4560]
AWS Redshift connection type not available and breaking existing connections. Error first occurred on 5.2.1 and continued on every version up to current, 5.2.4.

<img width="325" alt="dbeaver-driver-error" src="https://user-images.githubusercontent.com/44388071/48077983-6f67f880-e19d-11e8-80b2-2bf37e995f18.png">

<img width="502" alt="dbeaver-connection-type" src="https://user-images.githubusercontent.com/44388071/48078185-c077ec80-e19d-11e8-98ba-e2f106955b88.png">

Mac - 5.2.4 - AWS Redshift

dbeaver-debug.log
```
Reason: can't load driver class 'ds-redshift.......redshift.amazonaws.com'
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:844)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:822)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:502)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:601)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:115)
	... 10 more
Caused by: java.lang.ClassNotFoundException: ds-redshift......redshift.amazonaws.com
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:842)
	... 14 more
```

**Comment by serge-rider** [comment]
Are you behind some corporate firewall? IF so then you need to download Redshift driver manually from https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html and the nadd jars into DBeaver driver config (libs)

**Comment by yesisg** [comment]
I have downloaded .jar file manually. Tried connection with both dbeaver file and manual file. Is the following configuration incorrect?

![dbeaver-edit-driver-a](https://user-images.githubusercontent.com/44388071/48099256-de604400-e1d3-11e8-8443-3b0121b7ebff.png)

> Are you behind some corporate firewall? IF so then you need to download Redshift driver manually from https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html and the nadd jars into DBeaver driver config (libs)

**Comment by serge-rider** [comment]
Just delete old library.

I see that you have changed class name and URL template values. Generally they are not supposed to be changed (all configuration should be done on connection level).
So i think that maybe your changes breaks the connection. Driver class must be a valid java class name (the list of valid values is at the bottom)

**Comment by yesisg** [comment]
Reset to Defaults + update to 5.2.4 - Everything is working now. Thanks for the help!

![screen shot 2018-11-07 at 10 33 30 am](https://user-images.githubusercontent.com/44388071/48152448-c5f63500-e278-11e8-80c9-8e39c931c49d.png)

**Comment by serge-rider** [comment]
Good
