### ISSUE TITLE
[Oracle] unable to return xml

### ISSUE THREAD

**Issue by jackse7en** [dbeaver/dbeaver#4565]
DBeaver 5.2.4
Oracle DB 11g 11.2.0.4

![image](https://user-images.githubusercontent.com/15628830/48107226-c0e5b580-e279-11e8-83d5-82048b388ed2.png)

java.lang.NoClassDefFoundError: oracle/xml/binxml/BinXMLMetadataProvider
	at oracle.xdb.XMLTypeFactory.create(XMLTypeFactory.java:78)
	at oracle.sql.OPAQUE.toClass(OPAQUE.java:383)
	at oracle.sql.OPAQUE.toJdbc(OPAQUE.java:333)
	at oracle.sql.OPAQUE.toJdbc(OPAQUE.java:314)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1194)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1103)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:52)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:729)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:465)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2489)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: oracle.xml.binxml.BinXMLMetadataProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

![image](https://user-images.githubusercontent.com/15628830/48106783-eb367380-e277-11e8-8391-aa46b728ac46.png)

**Comment by serge-rider** [comment]
Looks like incorrect driver config. 
Class `BinXMLMetadataProvider` resides in xmlparserv2.jar. It think it is not foudn in your case becayse you have both ojdbc5 and ojdbc6 in the list. Basically I'd suggest to download the most recent ojdbc8 driver from ORacle web site. However ojdbc6 should also work. Just try to remove ojdbc5 from the list.

**Comment by naihil** [comment]
I have similar problem with DBeaver 6.2.2
`
!ENTRY org.jkiss.dbeaver.model 2 0 2019-10-08 10:08:56.973
!MESSAGE Can't read column 'META' value
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-10-08 10:08:56.973
!MESSAGE oracle/xml/parser/v2/XMLParseException
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2019-10-08 10:08:56.973
!MESSAGE oracle.xml.parser.v2.XMLParseException
!STACK 0
java.lang.ClassNotFoundException: oracle.xml.parser.v2.XMLParseException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at oracle.xdb.XMLTypeFactory.create(XMLTypeFactory.java:78)
	at oracle.sql.OPAQUE.toClass(OPAQUE.java:383)
	at oracle.sql.OPAQUE.toJdbc(OPAQUE.java:333)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1220)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1119)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:613)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:52)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:119)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:669)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:482)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:394)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:764)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2928)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3427)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
All jars from ojdbc-full added
![oracle](https://user-images.githubusercontent.com/771630/66374862-a13c9d00-e9b4-11e9-9a5b-830421149846.png)

**Comment by serge-rider** [comment]
I've reproduced this problem on one of our servers.
Indeed it caused by wrong XML parser version.

You can download proper version from here (e.g. for main driver 12.2.0.1)
https://mvnrepository.com/artifact/com.oracle.database.xml/xmlparserv2/12.2.0.1

**Comment by serge-rider** [comment]
@uslss please check this issue in CE

**Comment by uslss** [comment]
verified
