### ISSUE TITLE
Error exec calculating total row count

### ISSUE THREAD

**Issue by ITNaming** [dbeaver/dbeaver#4652]
Hi, I get an "Error exec" when pushing "Calculate total row count" button when there is an "ORDER" clause in the query,

Working example:
`SELECT *
FROM test001 AS t
`

Not working example:
`SELECT *
FROM test001 AS t
ORDER BY t.Campo1 ASC`

```
_2018-11-20 13:09:31.658 - null
org.jkiss.dbeaver.model.exec.DBCException: Error executing row count
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:2605)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:2728)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$21(ResultSetViewer.java:2717)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$7$1.evaluate(ResultSetViewer.java:1251)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$7$1.evaluate(ResultSetViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1033] [S0001]: La cl�usula ORDER BY no es v�lida en vistas, funciones insertadas, tablas derivadas, subconsultas ni expresiones de tabla com�n, salvo que se especifique tambi�n TOP o FOR XML.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:207)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.countData(SQLEditor.java:2574)
	... 8 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: La cl�usula ORDER BY no es v�lida en vistas, funciones insertadas, tablas derivadas, subconsultas ni expresiones de tabla com�n, salvo que se especifique tambi�n TOP o FOR XML.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:493)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:204)
	... 9 more_
```

**Comment by uslss** [comment]
Issue is reproducible only in case [result-fetch size > table row count]

**Comment by serge-rider** [comment]
Fixed (we'll remove all ORDER BY elements from source query)

**Comment by ITNaming** [comment]
> Fixed (we'll remove all ORDER BY elements from source query)

Thanks!!
