### ISSUE TITLE
Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .

### ISSUE THREAD

**Issue by ngyebi** [dbeaver/dbeaver#4676]
I added the ff to dbeaver.ini 
-Djavax.security.auth.useSubjectCredsOnly=false
-Djava.security.krb5.conf="/etc/krb5.conf"
-Djava.security.auth.login.config=~/jaas.conf

and created jaas.conf with the ff entries
Client {
      com.sun.security.auth.module.Krb5LoginModule required
      useKeyTab=true
      doNotPrompt=true
      keyTab="~/myuser.keytab"
      debug=true
      useTicketCache=true
      renewTGT=true
      principal="myuser@FOO.COM";
   };

but still getting the following error:
Caused by: com.cloudera.hiveserver2.support.exceptions.GeneralException: [Cloudera][HiveJDBCDriver](500168) Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
        ... 10 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain Principal Name for authentication
        at com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:841)
        at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:704)
        at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at com.cloudera.hiveserver2.jdbc.kerberos.Kerberos.getSubjectViaTicketCache(Unknown Source)
        at com.cloudera.hiveserver2.hivecommon.api.HiveServer2ClientFactory.createTransport(Unknown Source)
        at com.cloudera.hiveserver2.hivecommon.api.ServiceDiscoveryFactory.createClient(Unknown Source)
        at com.cloudera.hiveserver2.hivecommon.core.HiveJDBCCommonConnection.establishConnection(Unknown Source)
        at com.cloudera.hiveserver2.jdbc.core.LoginTimeoutConnection.connect(Unknown Source)
        at com.cloudera.hiveserver2.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
        at com.cloudera.hiveserver2.jdbc.common.AbstractDriver.connect(Unknown Source)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:147)
        at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:271)
        at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:217)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by ngyebi** [comment]
Can any help me on the steps to used to configure hive connection using kerberos authentication?

**Comment by serge-rider** [comment]
Did you find a way to connect?

**Comment by playersons** [comment]
Has this ticket been closed without any comments regarding the solution or non-solution? Would be very kind and highly appreciated if the world could learn from the outcome.
