### ISSUE TITLE
Oracle TIMESTAMP extract problem

### ISSUE THREAD

**Issue by rmundkowsky** [dbeaver/dbeaver#4719]
I am getting the below Exception for all ORACLE timestamps displayed in the results.

I have tried using the ojdbc7.jar and ojdbc8.jar drivers and I get the same error.

I am using Dbeaver 5.2.5.201811181655 .

org.jkiss.dbeaver.model.exec.DBCException: Error extracting Oracle TIMESTAMP value
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getValueFromObject(OracleTimestampValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:100)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:729)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:465)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2532)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@711e9103
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getTimestampReadMethod(OracleTimestampValueHandler.java:76)
	at org.jkiss.dbeaver.ext.oracle.data.OracleTimestampValueHandler.getValueFromObject(OracleTimestampValueHandler.java:58)
	... 14 more

**Comment by serge-rider** [comment]
Thanks for the bug report.
Please reopen if it will happen after 5.3 release
