### ISSUE TITLE
InfluxDB error w/non-root user: "Can't read users - unable to parse authentication credentials"

### ISSUE THREAD

**Issue by swhiteman** [dbeaver/dbeaver#4731]
Longtime InfluxDB user here, with local and remote hosted installs for the past 2 years.

DBeaver's support is an exciting addition to the (otherwise nonexistent) InfluxDB UI ecosystem.

And it works fine with my local dev environment, browsing metadata + data without a hitch.

But doesn't work with my hosted InfluxDB services at Aiven. It connects OK but then throws the error "Can't read users - unable to parse authentication credentials" when trying to drill into any data. Both Databases and Users nodes give this error.

Now, I think I know *why* this is happening.  Aiven doesn't give out a true root user, but rather a modified user that can create entire databases (presumably without conflict) but not create users. This obviously has something to do with the way they enable multitenant InfluxDB without containers.  Or something like that. The point is that I have to issue a 'use {database}' from the InfluxDB CLI when connecting to Aiven. From there, everything is smooth sailing; if I don't do that I'm refused access to do anything. I think that DBeaver is missing the ability to perform the equivalent pre-step using the Java library. It's not the same as setting a default database (already doing that, doesn't fix it).

**Comment by serge-rider** [comment]
Please post full error stacktrace (main menu Window->Show View->Error Log, double click on the error and copy-paste stacktrace).

Do you specify database name on Influx connection page?

**Comment by swhiteman** [comment]
> Do you specify database name on Influx connection page?

Yes, as I said, issuing `use {database}` from the CLI is "not the same as setting default database" in the DBeaver UI. I am specifying the DBeaver `Database` value.

Here's the stacktrace:

```
1908 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:10:08.984
1909 !MESSAGE Error initializing datasource
1910 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:10:08.984
1911 !MESSAGE unable to parse authentication credentials
1912 !STACK 0
1913 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
1914     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
1915     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
1916     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
1917     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
1918     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
1919     at com.dbeaver.ee.influxdb.model.InfluxDataSource.initialize(InfluxDataSource.java:105)
1920     at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:775)
1921     at org.jkiss.dbeaver.ui.editors.DatabaseLazyEditorInput.initializeRealInput(DatabaseLazyEditorInput.java:192)
1922     at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:137)
1923     at org.jkiss.dbeaver.ui.editors.entity.ProgressEditorPart$InitNodeService.evaluate(ProgressEditorPart.java:1)
1924     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
1925     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
1926     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
1927     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
1928 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:11:22.031
1929 !MESSAGE Error initializing datasource
1930 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:11:22.031
1931 !MESSAGE unable to parse authentication credentials
1932 !STACK 0
1933 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
1934     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
1935     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
1936     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
1937     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
1938     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
1939     at com.dbeaver.ee.influxdb.model.InfluxDataSource.initialize(InfluxDataSource.java:105)
1940     at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:775)
1941     at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
1942     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
1943     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
1944 !ENTRY org.eclipse.jface 2 0 2018-12-03 18:11:47.671
1945 !MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
1946 !SUBENTRY 1 org.eclipse.jface 2 0 2018-12-03 18:11:47.671
1947 !MESSAGE A conflict occurred for CTRL+D:
1948 Binding(CTRL+D,
1949     ParameterizedCommand(Command(org.eclipse.ui.edit.text.delete.line,Delete Line,
1950         Delete a line of text,
1951         Category(org.eclipse.ui.category.textEditor,Text Editing,Text Editing Commands,true),
1952         org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@24ce5d4c,
1953         ,,true),null),
1954     org.eclipse.ui.defaultAcceleratorConfiguration,
1955     org.eclipse.ui.textEditorScope,,,system)
1956 Binding(CTRL+D,
1957     ParameterizedCommand(Command(org.jkiss.dbeaver.core.navigator.bookmark.add,Add Bookmark,
1958         Add Bookmark,
1959         Category(org.jkiss.dbeaver.core.navigator,Database Navigator,Database Navigator Commands,true),
1960         org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@24fc9aa5,
1961         ,,true),null),
1962     org.eclipse.ui.defaultAcceleratorConfiguration,
1963     org.jkiss.dbeaver.ui.context.navigator,,,system)
1964 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:12:06.484
1965 !MESSAGE Can't read users
1966 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:12:06.484
1967 !MESSAGE unable to parse authentication credentials
1968 !STACK 0
1969 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
1970     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
1971     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
1972     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
1973     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
1974     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
1975     at com.dbeaver.ee.influxdb.model.InfluxDataSource$UserCache.getAllObjects(InfluxDataSource.java:335)
1976     at com.dbeaver.ee.influxdb.model.InfluxDataSource.getUsers(InfluxDataSource.java:324)
1977     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1978     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
1979     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
1980     at java.lang.reflect.Method.invoke(Method.java:498)
1981     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:809)
1982     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:790)
1983     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:870)
1984     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
1985     at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
1986     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
1987     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:406)
1988     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
1989     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
1990     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
1991     at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
1992     at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
1993     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
1994     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
1995     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
1996     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
1997 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:12:41.796
1998 !MESSAGE Error initializing datasource
1999 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:12:41.796
2000 !MESSAGE unable to parse authentication credentials
2001 !STACK 0
2002 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
2003     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
2004     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
2005     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
2006     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
2007     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
2008     at com.dbeaver.ee.influxdb.model.InfluxDataSource.initialize(InfluxDataSource.java:105)
2009     at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:775)
2010     at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
2011     at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
2012     at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
2013     at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:663)
2014     at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:147)
2015     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:195)
2016     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
2017     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
2018     at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
2019     at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
2020     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
2021     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
2022     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
2023     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2024 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:13:08.359
2025 !MESSAGE Can't execute query - no active database
2026 !STACK 0
2027 org.jkiss.dbeaver.model.exec.DBCException: Can't execute query - no active database
2028     at com.dbeaver.ee.influxdb.exec.InfluxSelectStatement.executeStatement(InfluxSelectStatement.java:61)
2029     at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:448)
2030     at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
2031     at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
2032     at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
2033     at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
2034     at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2384)
2035     at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
2036     at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
2037     at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
2038     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
2039     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2040 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:13:16.187
2041 !MESSAGE Can't read users
2042 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:13:16.187
2043 !MESSAGE unable to parse authentication credentials
2044 !STACK 0
2045 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
2046     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
2047     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
2048     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
2049     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
2050     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
2051     at com.dbeaver.ee.influxdb.model.InfluxDataSource$UserCache.getAllObjects(InfluxDataSource.java:335)
2052     at com.dbeaver.ee.influxdb.model.InfluxDataSource.getUsers(InfluxDataSource.java:324)
2053     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2054     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2055     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2056     at java.lang.reflect.Method.invoke(Method.java:498)
2057     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:809)
2058     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:790)
2059     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:870)
2060     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
2061     at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
2062     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
2063     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:406)
2064     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
2065     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
2066     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
2067     at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:204)
2068     at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
2069     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
2070     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
2071     at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
2072     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2073 !ENTRY org.jkiss.dbeaver.model 4 0 2018-12-03 18:14:09.515
2074 !MESSAGE Can't read users
2075 !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2018-12-03 18:14:09.515
2076 !MESSAGE unable to parse authentication credentials
2077 !STACK 0
2078 org.influxdb.InfluxDBException$UnableToParseException: unable to parse authentication credentials
2079     at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:140)
2080     at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166)
2081     at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690)
2082     at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:680)
2083     at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:507)
2084     at com.dbeaver.ee.influxdb.model.InfluxDataSource$UserCache.getAllObjects(InfluxDataSource.java:335)
2085     at com.dbeaver.ee.influxdb.model.InfluxDataSource.getUsers(InfluxDataSource.java:324)
2086     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2087     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2088     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2089     at java.lang.reflect.Method.invoke(Method.java:498)
2090     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:809)
2091     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:790)
2092     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:870)
2093     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
2094     at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
2095     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
2096     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:406)
2097     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
2098     at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
2099     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:564)
2100     at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:204)
2101     at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
2102     at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
2103     at org.jkiss.dbeaver.ui.LoadingJob.syncRun(LoadingJob.java:109)
2104     at org.jkiss.dbeaver.ui.controls.itemlist.ObjectListControl.loadData(ObjectListControl.java:336)
2105     at org.jkiss.dbeaver.ui.editors.entity.properties.TabbedFolderPageNode.refreshPart(TabbedFolderPageNode.java:172)
2106     at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.refreshPart(ObjectPropertiesEditor.java:413)
2107     at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.refreshPart(EntityEditor.java:797)
2108     at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:177)
2109     at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:131)
2110     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.openNavigatorNode(NavigatorUtils.java:620)
2111     at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.execute(NavigatorHandlerObjectOpen.java:97)
2112     at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
2113     at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
2114     at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
2115     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2116     at java.lang.reflect.Method.invoke(Method.java:498)
2117     at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
2118     at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
2119     at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
2120     at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
2121     at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
2122     at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
2123     at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
2124     at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
2125     at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:390)
2126     at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:377)
2127     at org.jkiss.dbeaver.ui.ActionUtils.runCommand(ActionUtils.java:265)
2128     at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.executeNodeAction(NavigatorUtils.java:249)
2129     at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.lambda$0(NavigatorViewBase.java:177)
2130     at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831)
2131     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
2132     at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
2133     at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
2134     at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828)
2135     at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1459)
2136     at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258)
2137     at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249)
2138     at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247)
2139     at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306)
2140     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
2141     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
2142     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
2143     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
2144     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
2145     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
2146     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
2147     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
2148     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
2149     at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
2150     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
2151     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
2152     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
2153     at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
2154     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
2155     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
2156     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
2157     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
2158     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
2159     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2160     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2161     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2162     at java.lang.reflect.Method.invoke(Method.java:498)
2163     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
2164     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
2165     at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by swhiteman** [comment]
Also, happy to spin up a small empty Aiven instance and give you the credentials to test (privately).

**Comment by serge-rider** [comment]
No clues so far.

>Also, happy to spin up a small empty Aiven instance 

Please write me on serge@jkiss.org

**Comment by giantjunkbox** [comment]
Getting the exact same error message. Looking at the network trace InfluxDB is returning back a HTTP/1.1 401 Unauthorized message with a body of {"error":"unable to parse authentication credentials"}.

The username is being passed as part of the request, the password is NOT being passed - despite entering it in a number of times.

Looking at the driver configuration I see that the InfluxDB driver has a check mark next to 'No authentication', not sure if this is related...
![image](https://user-images.githubusercontent.com/17022073/49411010-0cc23800-f71c-11e8-86e9-0d1d7eff4d8f.png).

I believe the default configuration of InfluxDB is to allow anonymous users to connect, which is of course brain damaged. It could be when this feature was being tested, it was not tested with a secured instance.

**Comment by swhiteman** [comment]
Thanks for the updates. As for not requiring auth by default, well, same with Redis, to be fair. :)

Relevantly the [underlying Java lib](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/InfluxDBFactory.java) has a couple of overloaded `connect` methods that require a non-empty string for both `username` and `password`, but not all the variations do.

**Comment by serge-rider** [comment]
Please check the fix in Early Access (https://dbeaver.com/files/ea/)

**Comment by giantjunkbox** [comment]
Testing the 5.3.0.201812051335 EA release.

This appears to work if you save the password in the connection profile.

If you do NOT check the option to save the password and you connect, you are NOT prompted for a password and get the same 'unable to parse authentication credentials' error.

This is a big improvement, but I think it still needs a bit more work.

Thank you

**Comment by serge-rider** [comment]
@giantjunkbox Well, this is because that mentioned option "No authentication". It is set for databases for which it is unusual to specify a password (e.g. SQLite). 
It was set for Influx because I never worked with secured Influx till this moment. Probably we should turn this option off.

**Comment by swhiteman** [comment]
Unfortunately, the latest EA doesn't work for me. 

As also communicated privately, it (a) corrupts the Eclipse UI (other windows partially shown, etc.) though still sort-of works *on the first open of a brand new workspace* and (b) breaks the UI completely on the second and subsequent opens of the WS (nothing can be viewed but title bar).

**Comment by serge-rider** [comment]
@swhiteman yep, I still keep looking into it. This seems to be Windows 7 + something else specific..

**Comment by serge-rider** [comment]
@giantjunkbox new EA version is ready
@swhiteman perhaps I'll try to build a version based on previous Eclipse version to see whether it will help in your case. We have quite many Windows 7 users after all :)

**Comment by swhiteman** [comment]
Thank you, looking forward to it -- with the auth fixed it's very enticing.

**Comment by swhiteman** [comment]
The new EA based on Oxygen fixed it.
