### ISSUE TITLE
Error executing Stored Prodecure in Teradata

### ISSUE THREAD

**Issue by geuss** [dbeaver/dbeaver#4745]
- Bug report (I've the last Teradata JDBC Drivers)

After the execution of a Stored Procedure in Teradata, DBeaver returns an error for all out parameter of the procedure

ex.
CALL EBIL_AREE.PRC_PFM_OUT_USERS(a,b);

"a" and "b"  are two undeclared variables that store the results (out_sql_code and out_sql_message) of the Stored procedure:

DDL:

REPLACE PROCEDURE EBIL_AREE.PRC_PFM_OUT_USERS
(
OUT out_sql_code INTEGER,
OUT out_sql_message VARCHAR(10000)
)
(...)

The error is (for each parameter):
org.jkiss.dbeaver.model.exec.DBCException: Errore SQL [301] [HY000]: [Teradata JDBC Driver] [TeraJDBC 16.00.00.32] [Error 301] [SQLState HY000] Invalid output parameter number: 1
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:729)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:465)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:392)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:390)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:822)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2532)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1598)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 16.00.00.32] [Error 301] [SQLState HY000] Invalid output parameter number: 1
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:95)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:70)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:99)
	at com.teradata.jdbc.jdbc_4.ParameterProperties.verifyOutParam(ParameterProperties.java:665)
	at com.teradata.jdbc.jdbc_4.TDPreparedStatement.getInt(TDPreparedStatement.java:2886)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCCallableStatementImpl.getInt(JDBCCallableStatementImpl.java:335)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetCallable.getInt(JDBCResultSetCallable.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:116)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	... 13 more
![image](https://user-images.githubusercontent.com/26387091/49588647-9285f380-f967-11e8-8c6f-48e0d61a14b2.png)

Using Teradata SQL Assistant (with ODBC or Native Teradata Drivers), the error doesn't occour.

Thanks!!

**Comment by geuss** [comment]
Resolved in early versions
