### ISSUE TITLE
Error connecting to azure data warehouse

### ISSUE THREAD

**Issue by keanrawr** [dbeaver/dbeaver#4776]
When connecting to an azure data warehouse the connection goes through, even showing shemas and tables. However when trying to run a query I get:

SQL Error [46706] [S0001]: Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.

Is there a problem with the driver I'm using?

This problem is for DBeaver 5.2.5

**Comment by serge-rider** [comment]
What driver do you use? SQL Server, Azure SQL Database?
Could you post full error stacktrace (you can get it in Error Log view, main menu Window->Show view)?

Also debug log would be helpful (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by aobotelho** [comment]
Hi, I know I was not the one who posted the question but I'm having more or less the same issues. 
One extra thing that I noticed is that when I run "Select top 10 * from <table>" works fine but when I run "Select * from <table>" it throws the same error. 


Dbeaver 5.3.3
Using Both Azure SQL Database and SQL Server drivers

org.jkiss.dbeaver.model
Error
Thu Jan 24 13:15:00 UTC 2019
Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.

com.microsoft.sqlserver.jdbc.SQLServerException: Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1614)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteCursored(SQLServerStatement.java:2007)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:835)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:759)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7206)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2909)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:739)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:835)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2593)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:103)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by novusnick** [comment]
I'm able to connect to Azure SQL Data Warehouse, however, it automatically connects to the master database.  When I try switching to my database, I get the following error:
SQL Error [40508] [S0001]: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
USE statement is not supported to switch between databases. Use a new connection to connect to a different database.

I get this error also when I right click on the database and try to set it to active

**Comment by serge-rider** [comment]
@novusnick can you set another database in connection settings dialog? Does it work?

**Comment by novusnick** [comment]
@serge-rider If I'm understanding what you're saying, I believe the answer is yes.  When I'm on regular sql server that's not in Azure, I'm able to switch databases without an issue.  I was also able to change the default database in the connections too.

**Comment by novusnick** [comment]
@serge-rider I still can't change databases in Azure Data Warehouse, but I'm able to connect to the right database.  When I try to run a query though, I get the original error of this thread:
SQL Error [46706] [S0001]: Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.

Thanks again for your help with this.

**Comment by priveros** [comment]
@aobotelho thanks for posting the TOP workaround, Just in case it helps wrapping the query in a WITH statement also works for me.
`
WITH t1 as (
	select * FROM schema.table
 )
select * FROM t1 
`

**Comment by novusnick** [comment]
@priveros That works.  Thanks for the heads up

**Comment by serge-rider** [comment]
@priveros @novusnick You can enable option "Use SQL to limit fetch size". In this case DBeaver will insert TOP X clause in all select queries (including raw data reading in table editors).
![Screenshot 2019-08-23 at 13 51 14](https://user-images.githubusercontent.com/6398845/63587605-1ee74d80-c5ad-11e9-8deb-c2e4171f48e1.png)

**Comment by serge-rider** [comment]
Version 6.2 will support SQL Data Warehouse server without any extra settings. You can test it in Early Access version (https://dbeaver.io/files/ea)
