### ISSUE TITLE
crash after update to latest stable version(DBeaver 5.3.0.201812092025) on MacOS Mojave

### ISSUE THREAD

**Issue by dc-avasilev** [dbeaver/dbeaver#4781]
```
2018-12-11 14:08:09.237 - DBeaver 5.3.0.201812092025 is starting
2018-12-11 14:08:09.237 - OS: Mac OS X 10.14.1 (x86_64)
2018-12-11 14:08:09.238 - Java version: 11.0.1 by Oracle Corporation (64bit)
2018-12-11 14:08:09.238 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2018-12-11 14:08:09.239 - Instance path: 'file:/Users/user_name/.dbeaver4/'
2018-12-11 14:08:09.240 - Memory available 81Mb/1024Mb
2018-12-11 14:08:09.279 - Starting RMI server at 43257
2018-12-11 14:08:09.348 - Run workbench
2018-12-11 14:08:09.359 - > Start org.eclipse.e4.ui.workbench.swt [0.14.101.v20170710-1119]
2018-12-11 14:08:09.361 - > Start org.eclipse.e4.core.services [2.1.0.v20170407-0928]
2018-12-11 14:08:09.363 - > Start org.eclipse.e4.core.contexts [1.6.0.v20170322-1144]
2018-12-11 14:08:09.373 - > Start org.eclipse.e4.ui.services [1.3.0.v20170307-2032]
2018-12-11 14:08:09.395 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 24 more
2018-12-11 14:08:09.416 - DBeaver is stopping
2018-12-11 14:08:09.417 - Stop RMI server
```

java -version
```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

systeminfo
```
 OS: 64bit Mac OS X 10.14.1 18B75
 Kernel: x86_64 Darwin 18.2.0
 Uptime: 1d 2h 37m
 Packages: 394
 Shell: zsh 5.6.2
 Resolution: 2880x1800 1920x1080 1080x1920
 DE: Aqua
 WM: Quartz Compositor
 WM Theme: Graphite
 CPU: Intel Core i7-7820HQ @ 2.90GHz
 GPU: Intel HD Graphics 630 / Radeon Pro 560
 RAM: 8376MiB / 16384MiB
```

crash after update to latest stable version!

if i start it from console command "/Applications/DBeaver.app/Contents/MacOS/dbeaver" starts normally

**Comment by tati-kru** [comment]
Yes, unfortunately we had to downgrade to Eclipse Oxygen which doesn't support Java 11. Because Latest Eclipse release was too unstable.

Workarounds: #4765 and #4308

Also on Windows and MacOS you could use installers which are already bundled with proper Java version.

**Comment by dc-avasilev** [comment]
> Because Latest Eclipse release was too unstable.
this is sad

**Comment by tati-kru** [comment]
The next Eclipse release with Java 11 support will be soon. We hope, it will be better. We will try to implement it as soon as it will be released.
