### ISSUE TITLE
Table with empty name could be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4967]
#### System information: 
- Win 10 x64
- DBeaver version 5.3.2

#### Connection specification:
- PostgreSQL 10, Oracle
![2019-01-10_11h06_49](https://user-images.githubusercontent.com/31996417/50962734-fc9c3600-14db-11e9-95c5-70202ad3e1c6.gif)
![2019-01-06_18h30_14](https://user-images.githubusercontent.com/31996417/50963134-e80c6d80-14dc-11e9-8c99-38f176563163.gif)

**Comment by uslss** [comment]
NPE appears in that case in 6.3.0 

```
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.model.DBUtils.findObject(DBUtils.java:421)
> 	at org.jkiss.dbeaver.model.DBUtils.findObject(DBUtils.java:407)
> 	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectCreateCommand.validateCommand(SQLObjectEditor.java:333)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$5(EntityEditor.java:476)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified.
