### ISSUE TITLE
ClassCastException when connecting to vertica

### ISSUE THREAD

**Issue by dabocla** [dbeaver/dbeaver#4984]
#### System information: 
- Operating system (distribution) and version
Windows 10
- DBeaver version
5.2.3
- Java version 
1.8.0_51
- Additional extensions
None

#### Connection specification:
- Database name and version
Vertica/8.1.1
- Driver name
vertica-jdbc-8.1.1-18.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
This doesn't seem to be affecting me directly, but this stack trace keeps appearing at an extremely frequent rate.
#### Steps to reproduce, if exist:
It seems to happen as I am casually typing a query, reliably so.

#### Include any warning/errors/backtraces from the logs
**Sometimes the exception below is under a parent item with this content:**
eclipse.buildId=unknown
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean

org.jkiss.dbeaver.model
Error
Fri Jan 11 13:17:33 CST 2019
Can't read flex table list

**Exception is below:**
java.lang.ClassCastException: org.jkiss.dbeaver.ext.generic.model.GenericDataSource$DataSourceObjectContainer cannot be cast to org.jkiss.dbeaver.ext.vertica.model.VerticaSchema
	at org.jkiss.dbeaver.ext.vertica.model.VerticaMetaModel.prepareTableLoadStatement(VerticaMetaModel.java:73)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:86)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.getObject(JDBCStructLookupCache.java:61)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTable(GenericObjectContainer.java:143)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getChild(GenericObjectContainer.java:387)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getChild(GenericDataSource.java:609)
	at org.jkiss.dbeaver.model.DBUtils.findNestedObject(DBUtils.java:372)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLSearchUtils.findObjectByPath(SQLSearchUtils.java:79)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLSearchUtils.findObjectByFQN(SQLSearchUtils.java:54)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.getTableFromAlias(SQLCompletionAnalyzer.java:498)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:154)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:85)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.run(SQLCompletionAnalyzer.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1627)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:367)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by dabocla** [comment]
Here's an update.  I am using search_path as a custom driver property, and I was also using schema filtering for the two schemas I am working with.  Maybe there's a case sensitivity issue?

**Comment by serge-rider** [comment]
I can't reproduce this.
Potentially this can be related to schema filter (when just one schema remains and . 
Could you try to disable it and try again?
Also could you post a screenshot of your navigator tree? (under Vertica connection)

**Comment by dabocla** [comment]
I just added the configuration back, and am not getting errors at the moment.  Go ahead and close, and I'll open another if I see it again.

**Comment by serge-rider** [comment]
Ok, thank for checking
