### ISSUE TITLE
Cannot find content.xml from update site using RDi eclipse

### ISSUE THREAD

**Issue by w-ti** [dbeaver/dbeaver#5001]
Hi @ll,

I got this message when I try to install dBeaver-Plugin from Marketplace in IBM Rational Developer for i (System i/AS400).
There exists already an issue from 2016 without any solution.

When I check the folder https://dbeaver.io/update/latest I found content.xml.xz - changed on 07.01.2019 - and a new file content.jar - from 07.01.2019

I need a solution for installing dBeaver as plugin in RDi.

thx

**Comment by serge-rider** [comment]
Please post full error message + stacktrace (you can get it in Error Log view)

**Comment by w-ti** [comment]
Unfortunately I can't attach a file :(
___

Das Repository bei https://dbeaver.io/update/latest/content.xml kann nicht gelesen werden.


java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:220)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at com.ibm.jsse2.a.a(a.java:134)
	at com.ibm.jsse2.a.a(a.java:219)
	at com.ibm.jsse2.as.a(as.java:648)
	at com.ibm.jsse2.as.i(as.java:895)
	at com.ibm.jsse2.as.a(as.java:283)
	at com.ibm.jsse2.as.startHandshake(as.java:115)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)


eclipse.buildId=unknown
java.fullversion=JRE 1.8.0 IBM J9 2.8 Windows 7 amd64-64 Compressed References 20150630_255633 (JIT enabled, AOT enabled)
J9VM - R28_jvm.28_20150630_1742_B255633
JIT  - tr.r14.java_20150625_95081.01
GC   - R28_jvm.28_20150630_1742_B255633_CMPRSS
J9CL - 20150630_255633
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product com.ibm.rational.developer.ibmi.product.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.ibm.rational.developer.ibmi.product.ide

**Comment by serge-rider** [comment]
Maybe you are behind some kind of corporate firewall?
If so then you configure HTTPS proxy in Preferences:
![image](https://user-images.githubusercontent.com/6398845/51133408-f5f82080-1845-11e9-9524-ea3a116eb09a.png)

**Comment by w-ti** [comment]
Probably it's a bug with https in RDi 9.5
With RDi 9.6 we get the following error:

Die Installation kann nicht vollständig ausgeführt werden, weil eines oder mehrere erforderliche Elemente nicht gefunden wurden.
  Installierte Software: DBeaver Debug 5.3.2.201901062110 (org.jkiss.dbeaver.debug.feature.feature.group 5.3.2.201901062110)
  Fehlende Voraussetzung: Für DBeaver UI 5.1.15.201901062110 (org.jkiss.dbeaver.ui 5.1.15.201901062110) ist 'bundle org.eclipse.mylyn.commons.ui 0.0.0' erforderlich, wurde jedoch nicht gefunden.
  Abhängigkeit wird nicht erfüllt:
    Aus: DBeaver Core 5.3.2.201901062110 (org.jkiss.dbeaver.core.feature.feature.group 5.3.2.201901062110)
    In: org.jkiss.dbeaver.ui [5.1.15.201901062110]
  Abhängigkeit wird nicht erfüllt:
    Aus: DBeaver Debug 5.3.2.201901062110 (org.jkiss.dbeaver.debug.feature.feature.group 5.3.2.201901062110)
    In: org.jkiss.dbeaver.core.feature.feature.group 0.0.0

**Comment by w-ti** [comment]
We stop installing dBeaver as a plugin in Rational Developer for i and install it as a stand alone Version
:(
