### ISSUE TITLE
5.3.3 not working as eclipse(mars) plugin ?

### ISSUE THREAD

**Issue by PGcritter** [dbeaver/dbeaver#5061]
It appears version 5.3.3 is still not working as a plugin under eclipse mars 
see previous bug reports (#4599 & #4667)
One can open driver manager and driver properties but not edit connection (not even open the dialog from the menu entry, worse than 5.25 IIRC)

But where is the config kept when used as a plugin ? Even though i temporarily moved .dbeaver-drivers and .dbeaver4 from %UserProfile%, the driver-manager still shows an entry i added previously, so not sure i am starting cleanly and this could influence testting.

I have tried both from updating 5.25 and with a fresh mars copy, same outcome.

**Comment by serge-rider** [comment]
Please post error/debug logs.
I'm afraid this gonna be a long story. 

Perhaps we should test this locally. But as i understand you have not just plain E4 Mars but some 3rd party tool based on it..

**Comment by PGcritter** [comment]
I have pydev and vrapper installed. 

Since nobody else seems to bother, perhaps you could just document the minimal eclipse version known to work ?

I do not use eclipse *that* much but it seems installing too many plugins makes the whole setup more brittle (although something else seems at work here). I will try later from home, with a vanilla mars platform.

**Comment by PGcritter** [comment]
Pleas find in attachemnt a short log from just opening mars, invoking the driver manager (apparently OK), invoking "create connection" (KO) then closing down. HTH.[](url)
[20190121.zip](https://github.com/dbeaver/dbeaver/files/2778798/20190121.zip)

**Comment by serge-rider** [comment]
Thanks.

This is a yet another problem of Eclipse APIs incompatibility (this whole issue is a result of "improvements" in https://bugs.eclipse.org/bugs/show_bug.cgi?id=477779 which broke backward compatibility).

Fixed this in DBeaver. As a workaround you can use drop-down menu in the toolbar:
![image](https://user-images.githubusercontent.com/6398845/51476028-50890380-1d95-11e9-9014-1473e6278a29.png)

**Comment by PGcritter** [comment]
Ah yes, via the button rather than the menu entry, it works !

Is there an easy way to import all the connection definitions i created with the stand-alone DBeaver into the plugin version ?
I'd then try to work with it a while to test further ...

**Comment by PGcritter** [comment]
Should I copy the whole "General" folder ?

**Comment by serge-rider** [comment]
As you wish. .dbeaver-data-sources.xml has all connections. If you need scripts, bookmarks and other stuff - you can copy it as well

**Comment by PGcritter** [comment]
Connections do show up (after copying just the xml file) but I keep getting "PostgreSQL server type '' not found " errors.
I tried copying drivers.xml as well but that did not help.
it'll have to wait until i find a little more time i am afraid.

**Comment by serge-rider** [comment]
Please post error log with this error.

**Comment by jmiguel77** [comment]
Version 5.3.3 is not working in Eclipse IDE for Java Developers, Version: 2018-12 (4.10.0), Build id: 20181214-0600

It even prevents the context menu from appearing right clicking always yields this error log

!ENTRY org.eclipse.e4.ui.workbench.renderers.swt 4 2 2019-01-21 14:55:40.022
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.renderers.swt".
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.IllegalStateException: No DBeaver application was defined
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:84)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:865)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:179)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.canExecuteItem(HandledContributionItem.java:459)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$1.run(AbstractContributionItem.java:516)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.updateItemEnablement(AbstractContributionItem.java:557)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolItemUpdater.run(ToolItemUpdater.java:87)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4046)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3166)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.lang.IllegalStateException: No DBeaver application was defined
	at org.jkiss.dbeaver.model.impl.app.ApplicationRegistry.getApplication(ApplicationRegistry.java:103)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductName(GeneralUtils.java:282)
	at org.jkiss.dbeaver.utils.GeneralUtils.getProductTitle(GeneralUtils.java:277)
	at org.jkiss.dbeaver.core.DBeaverCore.createInstance(DBeaverCore.java:128)
	at org.jkiss.dbeaver.core.DBeaverCore.getInstance(DBeaverCore.java:120)
	at org.jkiss.dbeaver.core.DBeaverCoreAdapterFactory.getAdapter(DBeaverCoreAdapterFactory.java:52)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:338)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:365)
	at org.jkiss.dbeaver.utils.GeneralUtils.queryAdapterManager(GeneralUtils.java:682)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:661)
	at org.jkiss.dbeaver.utils.GeneralUtils.adapt(GeneralUtils.java:676)
	at org.jkiss.dbeaver.runtime.DBWorkbench.getPlatform(DBWorkbench.java:43)
	at org.jkiss.dbeaver.ui.actions.GlobalPropertyTester.test(GlobalPropertyTester.java:42)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:61)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:103)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:55)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:81)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:228)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.setEnabled(E4HandlerProxy.java:134)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 36 more  

The same happens when i switch to the DBeaver perspective

**Comment by serge-rider** [comment]
@jmiguel77 I can't reproduce this. 
Looks like corrupted installation (plugin org.jkiss.dbeaver.core.eclipse.jar seems to be missing).
Did you use marketplace or direct install (Install new software)? Did you upgrade from older version or it was a fresh install? And it is better to create separate ticket because this one is about legacy Eclipse versions.

**Comment by jmiguel77** [comment]
@serge-rider i used the marketplace to install, and after some time of working fine, an upgrade of the plugin caused the problems

It is not a legacy eclipse version, i downloaded one of the Eclipse 2018-12 R Packages, this one more precisely https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2018-12/R/eclipse-jee-2018-12-R-win32-x86_64.zip

**Comment by jmiguel77** [comment]
I uninstalled the plugin from eclipse via the marketplace tool, and the problem stopped. That was a few days ago.
Today i tried to install it again, via marketplace. The problem is happening again.

This is the list of the files i found in the plugins folder

01/21/2019  09:44 AM            14,515 org.jkiss.dbeaver.core.eclipse_5.3.3.201901202008.jar
01/21/2019  09:44 AM         1,228,187 org.jkiss.dbeaver.core_5.3.3.201901202008.jar
01/21/2019  09:44 AM            13,918 org.jkiss.dbeaver.data.gis_1.0.25.201901202008.jar
01/21/2019  09:44 AM           323,722 org.jkiss.dbeaver.data.transfer_1.0.11.201901202008.jar
01/21/2019  09:44 AM            63,261 org.jkiss.dbeaver.debug.core_1.0.30.201901202008.jar
01/21/2019  09:44 AM            84,547 org.jkiss.dbeaver.debug.ui_1.0.30.201901202008.jar
01/21/2019  09:44 AM            48,114 org.jkiss.dbeaver.ext.athena_1.0.7.201901202008.jar
01/21/2019  09:44 AM            54,461 org.jkiss.dbeaver.ext.bigquery_1.0.7.201901202008.jar
01/21/2019  09:44 AM            10,561 org.jkiss.dbeaver.ext.clickhouse_1.0.6.201901202008.jar
01/21/2019  09:44 AM            41,490 org.jkiss.dbeaver.ext.db2.zos_1.0.4.201901202008.jar
01/21/2019  09:44 AM           587,424 org.jkiss.dbeaver.ext.db2_2.1.86.201901202008.jar
01/21/2019  09:44 AM            10,115 org.jkiss.dbeaver.ext.derby_1.1.86.201901202008.jar
01/21/2019  09:44 AM           329,247 org.jkiss.dbeaver.ext.erd_2.0.103.201901202008.jar
01/21/2019  09:44 AM            28,203 org.jkiss.dbeaver.ext.es.ui_1.0.12.201901202008.jar
01/21/2019  09:44 AM           369,792 org.jkiss.dbeaver.ext.exasol_1.0.59.201901202008.jar
01/21/2019  09:44 AM            82,521 org.jkiss.dbeaver.ext.firebird_1.0.102.201901202008.jar
01/21/2019  09:44 AM            11,747 org.jkiss.dbeaver.ext.format.sqlworkbenchj_1.0.8.201901202008.jar
01/21/2019  09:44 AM           839,937 org.jkiss.dbeaver.ext.generic_2.3.87.201901202008.jar
01/21/2019  09:44 AM            68,795 org.jkiss.dbeaver.ext.greenplum_1.0.2.201901202008.jar
01/21/2019  09:44 AM             9,281 org.jkiss.dbeaver.ext.h2_1.0.56.201901202008.jar
01/21/2019  09:44 AM            11,531 org.jkiss.dbeaver.ext.hana_1.0.30.201901202008.jar
01/21/2019  09:44 AM            12,280 org.jkiss.dbeaver.ext.hive_1.0.7.201901202008.jar
01/21/2019  09:44 AM            17,829 org.jkiss.dbeaver.ext.hsqldb_1.0.48.201901202008.jar
01/21/2019  09:44 AM            66,741 org.jkiss.dbeaver.ext.import_config_2.1.64.201901202008.jar
01/21/2019  09:44 AM            12,331 org.jkiss.dbeaver.ext.informix_1.0.92.201901202008.jar
01/21/2019  09:44 AM            99,077 org.jkiss.dbeaver.ext.mockdata_1.0.27.201901202008.jar
01/21/2019  09:45 AM            89,576 org.jkiss.dbeaver.ext.mssql.ui_1.0.0.201901202008.jar
01/21/2019  09:45 AM           228,223 org.jkiss.dbeaver.ext.mssql_1.0.95.201901202008.jar
01/21/2019  09:45 AM           442,816 org.jkiss.dbeaver.ext.mysql_2.1.86.201901202008.jar
01/21/2019  09:44 AM             9,576 org.jkiss.dbeaver.ext.netezza_1.0.66.201901202008.jar
01/21/2019  09:45 AM           618,214 org.jkiss.dbeaver.ext.oracle_2.1.86.201901202008.jar
01/21/2019  09:45 AM            12,788 org.jkiss.dbeaver.ext.phoenix_1.0.70.201901202008.jar
01/21/2019  09:45 AM            46,063 org.jkiss.dbeaver.ext.postgresql.debug.core_1.0.30.201901202008.jar
01/21/2019  09:45 AM            23,076 org.jkiss.dbeaver.ext.postgresql.debug.ui_1.0.30.201901202008.jar
01/21/2019  09:45 AM           832,909 org.jkiss.dbeaver.ext.postgresql_2.1.74.201901202008.jar
01/21/2019  09:45 AM            46,961 org.jkiss.dbeaver.ext.snowflake.core_1.0.21.201901202008.jar
01/21/2019  09:45 AM            17,928 org.jkiss.dbeaver.ext.snowflake.ui_1.0.21.201901202008.jar
01/21/2019  09:45 AM            30,208 org.jkiss.dbeaver.ext.sqlite_1.0.50.201901202008.jar
01/21/2019  09:45 AM             9,860 org.jkiss.dbeaver.ext.teradata_1.0.69.201901202008.jar
01/21/2019  09:45 AM             7,020 org.jkiss.dbeaver.ext.ui.colortheme_1.0.8.201901202008.jar
01/21/2019  09:45 AM            47,034 org.jkiss.dbeaver.ext.ui.locks_1.0.46.201901202008.jar
01/21/2019  09:45 AM            54,432 org.jkiss.dbeaver.ext.vertica_2.0.31.201901202008.jar
01/21/2019  09:45 AM         1,474,664 org.jkiss.dbeaver.model_1.0.90.201901202008.jar
01/21/2019  09:45 AM            12,948 org.jkiss.dbeaver.net.ssh.jsch_1.1.11.201901202008.jar
01/21/2019  09:45 AM            19,692 org.jkiss.dbeaver.net.ssh.ui_1.0.22.201901202008.jar
01/21/2019  09:45 AM            21,378 org.jkiss.dbeaver.net.ssh_1.0.22.201901202008.jar
01/21/2019  09:45 AM           231,086 org.jkiss.dbeaver.ui.editors.base_1.0.1.201901202008.jar
01/21/2019  09:45 AM             6,574 org.jkiss.dbeaver.ui.editors.content_1.0.1.201901202008.jar
01/21/2019  09:45 AM           944,295 org.jkiss.dbeaver.ui.editors.data_1.0.1.201901202008.jar
01/21/2019  09:45 AM             5,505 org.jkiss.dbeaver.ui.editors.entity_1.0.1.201901202008.jar
01/21/2019  09:45 AM           169,117 org.jkiss.dbeaver.ui.editors.hex_1.0.1.201901202008.jar
01/21/2019  09:45 AM            37,417 org.jkiss.dbeaver.ui.editors.image_1.0.1.201901202008.jar
01/21/2019  09:45 AM           763,847 org.jkiss.dbeaver.ui.editors.sql_1.0.1.201901202008.jar
01/21/2019  09:45 AM            29,087 org.jkiss.dbeaver.ui.editors.xml_1.0.1.201901202008.jar
01/21/2019  09:45 AM           533,644 org.jkiss.dbeaver.ui.navigator_1.0.1.201901202008.jar
01/21/2019  09:45 AM           843,131 org.jkiss.dbeaver.ui_5.1.16.201901202008.jar
01/21/2019  09:45 AM            86,125 org.jkiss.utils_2.1.84.201901202008.jar

**Comment by serge-rider** [comment]
@jmiguel77 Just tested with fresh install of JEE and fresh install of DBeaver from Marketplace. Worka with no issues.

Do you have any other Eclipse extensions installed but DBeaver (potentially there can be some conflicts)?
What is your OS?

**Comment by jmiguel77** [comment]
I am using windows 10
I have installed:
- Enide (Studio) 2015 - Node.js, JavaScript, Java and Web Tools 1.0.2
- Team Explorer Everywhere 14.134.0

**Comment by rdobda-gaia** [comment]
I am no longer able to open any connections to my PostGres (generic) servers. They stopped working totally, and i can't create any new connections to postgres either. i tried reinstalling dbeaver also with no effect. I even updated to the latest Java 8 version (update 201).

macOS Mojave
DBeaver 5.3.3 enterprise (not as plugin, just actual app)
Java 8 version (update 201).

I get this error when trying to open a new connection:
Internal error when opening new connection wizard
Reason:
PostgreSQL server type '' not found

error log data:
java.lang.IllegalStateException: PostgreSQL server type '' not found
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getServerType(PostgreUtils.java:492)
	at org.jkiss.dbeaver.ext.postgresql.ui.PostgreConnectionPage.loadSettings(PostgreConnectionPage.java:184)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.activatePage(ConnectionPageSettings.java:116)
	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1223)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:579)
	at org.eclipse.jface.window.Window.create(Window.java:429)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.eclipse.jface.window.Window.open(Window.java:786)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.open(CreateConnectionDialog.java:83)
	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:80)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

session data:
eclipse.buildId=unknown
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/rdobda/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/rdobda/.eclipse_keyring

**Comment by serge-rider** [comment]
@rdobda-gaia it is a bug in recent versions. Generic driver still makes sense in some cases. Thanks for the bug report.
