### ISSUE TITLE
SQL Error [207] [S0001]: Invalid column name 'database_id' on SQL Server

### ISSUE THREAD

**Issue by lzkill** [dbeaver/dbeaver#5069]
#### System information: 
- macOS Sierra
- DBeaver version 5.3.3
- Java version 1.8.0_191-b12

#### Connection specification:
- Target: SQL Server 2008 R2
- Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver (7.0.0.jre8)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When I expand _Administration->Sessions_ an error is shown:

````
SQL Error [207] [S0001]: Invalid column name 'database_id'.
  Invalid column name 'database_id'.
````

#### Include any warning/errors/backtraces from the logs
````
org.jkiss.dbeaver.DBException: SQL Error [207] [S0001]: Invalid column name 'database_id'.
	at org.jkiss.dbeaver.ext.mssql.model.session.SQLServerSessionManager.getSessions(SQLServerSessionManager.java:76)
	at org.jkiss.dbeaver.ui.views.session.SessionTable$LoadSessionsService.evaluate(SessionTable.java:126)
	at org.jkiss.dbeaver.ui.views.session.SessionTable$LoadSessionsService.evaluate(SessionTable.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'database_id'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:434)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:232)
	at org.jkiss.dbeaver.ext.mssql.model.session.SQLServerSessionManager.getSessions(SQLServerSessionManager.java:67)
	... 6 more

````

**Comment by P4Ks** [comment]
Same problem for me: SQL Server 2008 R2, driver version 7.1.4.jre8-preview
