### ISSUE TITLE
PostgreSQL - Data import from CSV file into a table - skip column fails

### ISSUE THREAD

**Issue by ced75** [dbeaver/dbeaver#513]
The data import tool works fine with PostgreSQL when performing a complete matching between source table and destination table.
But when I try to skip columns, I get an error message at the beginning of data transfert on the first skipped column:

Target attribute for [type] wasn't resolved

org.jkiss.dbeaver.model.exec.DBCException: Target attribute for [type] wasn't resolved
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:100)
    at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:206)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:113)
    at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
    at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
    at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by uslss** [comment]
Issue isn't reproducible on 6.0.3
