### ISSUE TITLE
Nothing (?) happens when attempting to use DB2 drivers for new connection

### ISSUE THREAD

**Issue by JonFP** [dbeaver/dbeaver#5137]
System information:
Mac OS - 10.13.6

DBeaver version - 5.3.3 from Eclipse Marketplace
Java version - unsure - IBM Java 7 ?
Attempting to use DBeaver within IBM Rational Developer for i 

Having resolved my earlier install issues I have been happily using DBeaver but ...

At the weekend I had to do a new install.  I added DBeaver with no problems but when I try to create a new connection, when select a DB2 driver from the list and press "Next" nothing happens. It jts sits there with no error messages, nothing.  If I select MySQL and press "Next" it works as it whould and I am presented with the next screen.  

Only difference I can see is that the version that worked was 5.3.1 - now at 5.3.3 but ...

Any ideas?  Log files? Anything?

**Comment by serge-rider** [comment]
Look like the same issue as in #4893 . 
You need to install Mylin plugin first.

**Comment by JonFP** [comment]
Sorry Serge but in what way is a failure to install similar to a failure to connect?  Besides as implied in my original post ("I added DBeaver with no problems") Mylin _is_ installed because DBeaver will not install at all without it.  This appears to be purely a plug-in issue as the stand-alone DBeaver is working just fine on the same machine.

**Comment by serge-rider** [comment]
Ah, sorry. I've missed the ticket.
It has to be #5061 (old Eclipse version support). It is already fixed, you can check the fix after 5.3.4 release.

**Comment by JonFP** [comment]
More information.

It appears that the bug that causes this may also appear in the stand-alone version but in that case it does not seem to interfere with the operation.  This is (I think) the relevant part of the log when using the plug-in 


!ENTRY org.eclipse.ui 4 0 2019-01-29 12:06:51.158
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.jface.resource.ImageDescriptor.getImageData(I)Lorg/eclipse/swt/graphics/ImageData;
at org.jkiss.dbeaver.ext.generic.views.GenericConnectionPage.loadSettings(GenericConnectionPage.java:347)
at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.activatePage(ConnectionPageSettings.java:116)
at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1215)
at org.eclipse.jface.wizard.WizardDialog.lambda$2(WizardDialog.java:1185)

Using the plug-in also seems to cause that error when using other components in the workbench but they do not seem to be affected. Only the DBeaver connection dialog.

This is a similar (?) event that appears to occur when using the new connection dailog in the stand-alone version.

java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4576)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.custom.DefaultContent.error(DefaultContent.java:682)
	at org.eclipse.swt.custom.DefaultContent.getLineAtOffset(DefaultContent.java:575)
	at org.eclipse.swt.custom.StyledText.getPointAtOffset(StyledText.java:5497)
	at org.eclipse.swt.custom.StyledText.insertBlockSelectionText(StyledText.java:5708)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2469)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6014)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6045)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5743)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1549)
	at org.eclipse.swt.widgets.Control.insertText(Control.java:2129)
	at org.eclipse.swt.widgets.Canvas.insertText(Canvas.java:290)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6131)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:71)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:604)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5966)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2414)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6086)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5325)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5477)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3730)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by serge-rider** [comment]
Yeah, Generic driver connection page is also has to be fixed, thanks for the log.

Second error isn't related, looks like some internal Eclipse error during text rendering - it shouldn't make any real harm.
