### ISSUE TITLE
DBCException by postgresql, can not parse binary geojson

### ISSUE THREAD

**Issue by NetDim** [dbeaver/dbeaver#5144]
#### System information: 
- Operating system: **SMP Debian 4.18.6-1 (2018-09-06) x86_64 GNU/Linux** 
- DBeaver version : **5.3.3 comunity**
- Java version: **openjdk version "10.0.2"** 
- Additional extensions

#### Connection specification:
- Database name and version: **postgres 9.4.19**
- Driver name: **PostgreSQL JDBC Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **YES**

#### Steps to reproduce, if exist:
I transform value as follow: 
```
ST_Transform(ST_SetSRID(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates":[[
                                            [9.174168437719345, 47.664844542810044],
                                            [9.174206357449293, 47.66483663990649],
                                            [9.174187246710062, 47.66479509322842],
                                            [9.174149326980114, 47.664802996131975]
                                  ]]}'), 4326), 3857)
```
DB works properly, only in DBeaver in the column following text to see: **DBCException: SQL-Fehler: Error parsing SQL data:java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring**

#### Include any warning/errors/backtraces from the logs
```
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler: Error parsing SQL data:java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromString(PostgreGeometryValueHandler.java:90)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.getValueFromObject(PostgreGeometryValueHandler.java:74)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.fetchColumnValue(PostgreGeometryValueHandler.java:46)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:103)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:101)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Error parsing SQL data:java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.postgis.jts.JtsGeometry.geomFromString(JtsGeometry.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jkiss.utils.BeanUtils.invokeStaticMethod(BeanUtils.java:363)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromString(PostgreGeometryValueHandler.java:86)
	... 10 more
```

**Comment by drowzeenico** [comment]
@NetDim Hi there. I've just faced with this problem. You just have to "close" the polygon with the start point.

`ST_Transform(ST_SetSRID(ST_GeomFromGeoJSON('{"type": "Polygon","coordinates":[[
     [9.174168437719345, 47.664844542810044],
     [9.174206357449293, 47.66483663990649],
     [9.174187246710062, 47.66479509322842],
     [9.174149326980114, 47.664802996131975],
     [9.174168437719345, 47.664844542810044]
]]}'), 4326), 3857)`

But it's strange why this query performs at all, cause it should returns an error due this polygon is incorrect (cause it's unclosed)

**Comment by NetDim** [comment]
Yes, you have right, the start and end point must be the same. In any way, it works by reading from DB - so postgres accepts it and Leaflet has no problem with wrong polygon to show it on the map. I corrected my polygon and DBeaver can interpret it now. May be would be a good idea to catch such wrong polygons and get warning instead of java exception.

**Comment by dragonxtek** [comment]
I found a case where DBeaver can't recognize a valid geom. I tested in both, version 7.3 and in the lastest 21.0
![Selection_999(1402)](https://user-images.githubusercontent.com/10552658/109736080-9f273f80-7ba2-11eb-9976-2bb3f2c3cd46.png)

I tested the same query in pgAdmin4 without issues
![Selection_999(1400)](https://user-images.githubusercontent.com/10552658/109736122-b23a0f80-7ba2-11eb-8897-cac2d8ecb971.png)

Here is the query to replicate it:

```
with figure as(
SELECT st_makevalid(ST_GeomFromText('POLYGON((0.036200040058986 51.7484344250884,0.036436767660039 51.7484305512964,0.036673241767248 51.7484189340685,0.036909209158215 51.7483995858446,
0.037144417153148 51.7483725273435,0.037378613885434 51.7483377875399,0.037611548571347 51.7482954036342,0.03784297177859 51.7482454210121,
0.038072635693397 51.7481878931962,0.038300294385896 51.7481228817888,0.038525704073455 51.7480504564056,0.038748623381736 51.7479706946017,
0.038968813603161 51.747883681788,0.039186038952523 51.7477895111399,0.03940006681948 51.7476882834978,0.039610668017629 51.7475801072587,
0.039817617029934 51.7474650982605,0.040020692250207 51.7473433796577,0.040219676220418 51.7472150817895,0.040414355863545 51.7470803420407,
0.040604522711753 51.7469393046939,0.040789973129615 51.7467921207753,0.04097050853218 51.7466389478933,0.041145935597616 51.7464799500692,
0.041316066474229 51.7463152975618,0.041480718981614 51.7461451666852,0.041639716805742 51.7459697396197,0.04179288968776 51.7457892042172,
0.04194007360631 51.7456037537993,0.042081110953166 51.7454135869511,0.042215850702003 51.745218907308,0.042344148570124 51.7450199233378,0.042465867172959 51.7448168481175,0.042580876171178 51.7446098991052,0.042689052410265 51.744399297907,0.042790280052395 51.7441852700401,0.042884450700472 51.7439680446907,0.042971463514208 51.7437478544693,0.043051225318102 51.743524935161,0.043123650701218 51.7432995254734,0.04318866210864 51.7430718667809,0.043246189924526 51.7428422028661,0.043296172546649 51.7426107796589,0.043338556452365 51.742377844973,0.043373296255927 51.7421436482407,0.043400354757083 51.7419084402458,0.043419702980912 51.7416724728548,0.043431320208851 51.7414359987476,0.043435194000882 51.7411992711465,0.043431320208851 51.7409625435455,0.043419702980912 51.7407260694383,0.043400354757083 51.7404901020473,0.043373296255927 51.7402548940524,0.043338556452365 51.7400206973201,0.043296172546649 51.7397877626342,0.043246189924526 51.7395563394269,0.04318866210864 51.7393266755121,0.043123650701218 51.7390990168196,0.043051225318102 51.7388736071321,0.042971463514208 51.7386506878238,0.042884450700472 51.7384304976024,0.042790280052395 51.738213272253,0.042689052410265 51.737999244386,0.042580876171178 51.7377886431879,0.042465867172959 51.7375816941756,0.042344148570124 51.7373786189553,0.042215850702003 51.7371796349851,0.042081110953166 51.736984955342,0.04194007360631 51.7367947884938,0.04179288968776 51.7366093380759,0.041639716805742 51.7364288026733,0.041480718981614 51.7362533756079,0.041316066474229 51.7360832447313,0.041145935597616 51.7359185922239,0.04097050853218 51.7357595943998,0.040789973129615 51.7356064215178,0.040604522711753 51.7354592375992,0.040414355863545 51.7353182002524,0.040219676220418 51.7351834605035,0.040020692250207 51.7350551626354,0.039817617029934 51.7349334440326,0.039610668017629 51.7348184350343,0.03940006681948 51.7347102587952,0.039186038952523 51.7346090311531,0.038968813603161 51.734514860505,0.038748623381736 51.7344278476913,0.038525704073455 51.7343480858874,0.038300294385896 51.7342756605043,0.038072635693397 51.7342106490969,0.03784297177859 51.734153121281,0.037611548571347 51.7341031386589,0.037378613885434 51.7340607547532,0.037144417153148 51.7340260149496,0.036909209158215 51.7339989564484,0.036673241767248 51.7339796082246,0.036436767660039 51.7339679909967,0.036200040058986 51.7339641172046,0.035963312457933 51.7339679909967,0.035726838350724 51.7339796082246,0.035490870959758 51.7339989564484,0.035255662964825 51.7340260149496,0.035021466232538 51.7340607547532,0.034788531546626 51.7341031386589,0.034557108339382 51.734153121281,0.034327444424575 51.7342106490969,0.034099785732077 51.7342756605043,0.033874376044517 51.7343480858874,0.033651456736236 51.7344278476913,0.033431266514812 51.734514860505,0.033214041165449 51.7346090311531,0.033000013298492 51.7347102587952,0.032789412100343 51.7348184350343,0.032582463088039 51.7349334440326,0.032379387867765 51.7350551626354,0.032180403897555 51.7351834605035,0.031985724254427 51.7353182002524,0.03179555740622 51.7354592375992,0.031610106988358 51.7356064215178,0.031429571585793 51.7357595943998,0.031254144520356 51.7359185922239,0.031084013643743 51.7360832447313,0.030919361136359 51.7362533756079,0.030760363312231 51.7364288026733,0.030607190430212 51.7366093380759,0.030460006511662 51.7367947884938,0.030318969164807 51.736984955342,0.030184229415969 51.7371796349851,0.030055931547848 51.7373786189553,0.029934212945014 51.7375816941756,0.029819203946795 51.7377886431879,0.029711027707707 51.737999244386,0.029609800065578 51.738213272253,0.029515629417501 51.7384304976024,0.029428616603765 51.7386506878238,0.02934885479987 51.7388736071321,0.029276429416755 51.7390990168196,0.029211418009332 51.7393266755121,0.029153890193447 51.7395563394269,0.029103907571324 51.7397877626342,0.029061523665608 51.7400206973201,0.029026783862046 51.7402548940524,0.02899972536089 51.7404901020473,0.028980377137061 51.7407260694383,0.028968759909122 51.7409625435455,0.028964886117091 51.7411992711465,0.028968759909122 51.7414359987476,0.028980377137061 51.7416724728548,0.02899972536089 51.7419084402458,0.029026783862046 51.7421436482407,0.029061523665608 51.742377844973,0.029103907571324 51.7426107796589,0.029153890193447 51.7428422028661,0.029211418009332 51.7430718667809,0.029276429416755 51.7432995254734,0.02934885479987 51.743524935161,0.029428616603765 51.7437478544693,0.029515629417501 51.7439680446907,0.029609800065578 51.7441852700401,0.029711027707707 51.744399297907,0.029819203946795 51.7446098991052,0.029934212945014 51.7448168481175,0.02998525343904 51.7449020040372,0.0297866894758 51.7448080902768,0.029569416619142 51.7447138990335,0.029349178242003 51.7446268671901,0.029126210181155 51.7445470879422,0.028900751196381 51.7444746467196,0.028673042714809 51.7444096210942,0.028443328572386 51.7443520806969,0.028395081283785 51.7443416602813,0.028471454265684 51.7441483946797,0.028551215975459 51.7439254756345,0.028623641273113 51.7437000662129,0.028688652603822 51.7434724077891,0.028746180351825 51.7432427441452,0.028796162914968 51.7430113212111,0.028838546770671 51.7427783868,0.02887328653324 51.7425441903441,0.028900345002467 51.7423089826267,0.028919693203465 51.7420730155142,0.028931310417696 51.741836541686,0.028935184205156 51.7415998143643,0.028931310417696 51.7413630870426,0.028919693203465 51.7411266132144,0.028900345002467 51.7408906461019,0.02887328653324 51.7406554383845,0.028838546770671 51.7404212419286,0.028796162914968 51.7401883075175,0.028746180351825 51.7399568845834,0.028688652603822 51.7397272209396,0.028623641273113 51.7394995625157,0.028551215975459 51.7392741530941,0.028471454265684 51.7390512340489,0.028384441554623 51.7388310440873,0.028290271017667 51.7386138189942,0.028189043494986 51.7383997913798,0.028080867383547 51.7381891904302,0.027965858521039 51.7379822416621,0.027844140061832 51.7377791666815,0.027715842345102 51.737580182946,0.027581102755258 51.7373855035326,0.027440065574826 51.7371953369088,0.027292881829953 51.7370098867098,0.027139709128679 51.7368293515203,0.026980711492168 51.7366539246618,0.026816059179074 51.736483793986,0.026645928503215 51.7363191416729,0.026470501644783 51.7361601440364,0.02628996645525 51.7360069713351,0.026104516256219 51.7358597875902,0.025914349632409 51.7357187504098,0.025719670219003 51.7355840108199,0.025520686483594 51.7354557131032,0.025317611502949 51.735333994644,0.025110662734844 51.7352189857815,0.024900061785204 51.7351108096701,0.024686034170801 51.7350095821474,0.024468809077764 51.7349154116104,0.024248619116164 51.7348283988994,0.024025700070928 51.7347486371896,0.023800290649352 51.7346762118919,0.02357263222549 51.7346112005612,0.023342968581687 51.7345536728132,0.023111545647523 51.7345036902501,0.022878611236473 51.7344613063944,0.022644414780539 51.7344265666318,0.022409207063152 51.7343995081626,0.022173239950626 51.7343801599616,0.021936766122457 51.7343685427474,0.021700038800742 51.7343646689599,0.021463311479028 51.7343685427474,0.021226837650859 51.7343801599616,0.020990870538333 51.7343995081626,0.020755662820946 51.7344265666318,0.020521466365012 51.7344613063944,0.020288531953962 51.7345036902501,0.020057109019798 51.7345536728132,0.019827445375994 51.7346112005612,0.019599786952133 51.7346762118919,0.019374377530557 51.7347486371896,0.019151458485321 51.7348283988994,0.018931268523721 51.7349154116104,0.018714043430684 51.7350095821474,0.01850001581628 51.7351108096701,0.01828941486664 51.7352189857815,0.018082466098536 51.735333994644,0.017879391117891 51.7354557131032,0.017680407382482 51.7355840108199,0.017485727969076 51.7357187504098,0.017295561345266 51.7358597875902,0.017110111146235 51.7360069713351,0.016929575956702 51.7361601440364,0.016754149098269 51.7363191416729,0.016584018422411 51.736483793986,0.016419366109316 51.7366539246618,0.016260368472806 51.7368293515203,0.016107195771531 51.7370098867098,0.015960012026658 51.7371953369088,0.015818974846227 51.7373855035326,0.015684235256382 51.737580182946,0.015555937539653 51.7377791666815,0.015448889414257 51.7379577656888,0.015251284566761 51.7380284698338,0.015031079645514 51.7381154884565,0.014813839794261 51.7382096653914,0.014599797638878 51.7383108997914,0.014389182381066 51.7384190832523,0.014182219552917 51.7385340999285,0.013979130775412 51.7386558266572,0.0137801335211 51.7387841330905,0.013585440881227 51.7389188818345,0.013395261337547 51.739059928597,0.013209798539078 51.7392071223414,0.013029251084032 51.7393603054492,0.012853812307145 51.739519313888,0.012683670072654 51.7396839773875,0.012519006573125 51.739854119622,0.012359998134357 51.7400295583989,0.01220681502657 51.740210105854,0.012059621282072 51.7403955686524,0.011918574519612 51.7405857481961,0.011783825775596 51.740780440836,0.011655519342353 51.7409794380903,0.011533792613627 51.7411825268678,0.011418775937447 51.7413894896959,0.011310592476551 51.7416001049538,0.011209358076499 51.7418141471091,0.011115181141622 51.7420313869604,0.011028162518941 51.7422515918816,0.010948395390176 51.7424745260719,0.010875965171967 51.7426999508078,0.010810949424405 51.7429276246987,0.010753417767983 51.7431573039458,0.010703431809037 51.7433887426027,0.010661045073786 51.7436216928393,0.010626302951007 51.7438559052065,0.010599242643435 51.7440911289038,0.010579893127925 51.7443271120479,0.010568275124424 51.744563601942,0.01056440107378 51.7448003453469,0.010568275124424 51.7450370887518,0.010579893127925 51.745273578646,0.010599242643435 51.74550956179,0.010626302951007 51.7457447854874,0.010661045073786 51.7459789978546,0.010703431809037 51.7462119480911,0.010753417767983 51.7464433867481,0.010810949424405 51.7466730659952,0.010875965171967 51.7469007398861,0.010948395390176 51.7471261646219,0.011028162518941 51.7473490988122,0.011115181141622 51.7475693037335,0.011209358076499 51.7477865435847,0.011310592476551 51.7480005857401,0.011418775937447 51.7482112009979,0.011533792613627 51.7484181638261,0.011655519342353 51.7486212526036,0.011783825775596 51.7488202498579,0.011918574519612 51.7490149424978,0.012059621282072 51.7492051220414,0.01220681502657 51.7493905848399,0.012359998134357 51.749571132295,0.012519006573125 51.7497465710718,0.012683670072654 51.7499167133063,0.012853812307145 51.7500813768059,0.013029251084032 51.7502403852446,0.013209798539078 51.7503935683524,0.013395261337547 51.7505407620969,0.013585440881227 51.7506818088594,0.0137801335211 51.7508165576034,0.013979130775412 51.7509448640366,0.014182219552917 51.7510665907654,0.014389182381066 51.7511816074415,0.014599797638878 51.7512897909024,0.014813839794261 51.7513910253025,0.015031079645514 51.7514852022374,0.015251284566761 51.75157222086,0.015474218757058 51.7516519879888,0.015699643492891 51.751724418207,0.015927317383805 51.7517894339546,0.016156996630895 51.751846965611,0.016388435287872 51.7518969515699,0.016621385524424 51.7519393383052,0.016855597891603 51.751974080428,0.017090821588941 51.7520011407356,0.017326804733009 51.7520204902511,0.017563294627147 51.7520321082546,0.017800038032053 51.7520359823052,0.017800038032053 51.7520359823052,0.01803678143696 51.7520321082546,0.018273271331098 51.7520204902511,0.018509254475166 51.7520011407356,0.018744478172504 51.751974080428,0.018978690539683 51.7519393383052,0.019211640776235 51.7518969515699,0.019443079433212 51.751846965611,0.019575878738704 51.7518137011167,0.019578795676857 51.7518730767568,0.019598148132152 51.7521090957539,0.019625212551016 51.752344355189,0.019659959952191 51.7525786031402,0.019702353127289 51.7528115887691,0.019752346680637 51.7530430625887,0.019809887077886 51.7532727767311,0.019874912703336 51.7535004852127,0.01994735392592 51.7537259441974,0.020027133173762 51.7539489122583,0.020114165017245 51.7541691506354,0.020208356260492 51.7543864234921,0.020309606041158 51.7546004981671,0.020417805938445 51.7548111454238,0.020532840089191 51.755018139696,0.020654585311946 51.7552212593289,0.020782911238877 51.755420286817,0.020917680455366 51.7556150090367,0.021058748647162 51.7558052174744,0.021205964754911 51.7559907084504,0.021359171135917 51.7561712833362,0.021518203732951 51.7563467487676,0.021682892249924 51.7565169168519,0.021853060334247 51.7566816053689,0.022028525765673 51.7568406379659,0.022209100651423 51.7569938443469,0.022394591627387 51.7571410604547,0.022584800065181 51.7572821286465,0.022779522284847 51.757416897863,0.022978549772953 51.7575452237899,0.023181669405882 51.7576669690126,0.023388663678042 51.7577820031634,0.023599310934781 51.7578902030607,0.023813385609742 51.7579914528413,0.024030658466401 51.7580856440846,0.024250896843539 51.7581726759281,0.024473864904388 51.7582524551759,0.024699323889162 51.7583248963985,0.024927032370733 51.758389922024,0.025156746513156 51.7584474624212,0.025388220332774 51.7584974559745,0.025621205961622 51.7585398491496,0.025855453912854 51.7585745965508,0.026090713347896 51.7586016609697,0.026326732345053 51.758621013425,0.02656325816927 51.7586326331936,0.026800037542771 51.7586365078328,0.026800037542771 51.7586365078328,0.027036816916272 51.7586326331936,0.02727334274049 51.758621013425,0.027509361737646 51.7586016609697,0.027744621172688 51.7585745965508,0.02797886912392 51.7585398491496,0.028211854752768 51.7584974559745,0.028443328572386 51.7584474624212,0.028673042714809 51.758389922024,0.028900751196381 51.7583248963985,0.029126210181155 51.7582524551759,0.029349178242003 51.7581726759281,0.029569416619142 51.7580856440846,0.0297866894758 51.7579914528413,0.030000764150761 51.7578902030607,0.030211411407501 51.7577820031634,0.030418405679661 51.7576669690126,0.030621525312589 51.7575452237899,0.030820552800696 51.757416897863,0.031015275020361 51.7572821286465,0.031205483458156 51.7571410604547,0.03139097443412 51.7569938443469,0.03157154931987 51.7568406379659,0.031747014751296 51.7566816053689,0.031917182835619 51.7565169168519,0.032081871352591 51.7563467487676,0.032240903949625 51.7561712833362,0.032394110330631 51.7559907084504,0.03254132643838 51.7558052174744,0.032682394630176 51.7556150090367,0.032817163846666 51.755420286817,0.032945489773597 51.7552212593289,0.033067234996352 51.755018139696,0.033182269147098 51.7548111454238,0.033290469044384 51.7546004981671,0.033391718825051 51.7543864234921,0.033485910068297 51.7541691506354,0.03357294191178 51.7539489122583,0.033652721159622 51.7537259441974,0.033725162382206 51.7535004852127,0.033790188007657 51.7532727767311,0.033847728404905 51.7530430625887,0.033897721958253 51.7528115887691,0.033940115133352 51.7525786031402,0.033974862534526 51.752344355189,0.03400192695339 51.7521090957539,0.034021279408686 51.7518730767568,0.034032899177319 51.7516365509326,0.03403677381655 51.7513997715591,0.034032899177319 51.7511629921856,0.034021279408686 51.7509264663613,0.03400192695339 51.7506904473642,0.033974862534526 51.7504551879291,0.033940115133352 51.7502209399779,0.033897721958253 51.7499879543491,0.033847728404905 51.7497564805294,0.033790188007657 51.749526766387,0.033725162382206 51.7492990579055,0.033652721159622 51.7490735989207,0.03357294191178 51.7488506308598,0.033485910068297 51.7486303924827,0.033391718825051 51.748413119626,0.033290469044384 51.7481990449511,0.033182269147098 51.7479883976943,0.033067234996352 51.7477814034222,0.03301593445859 51.7476958136457,0.033214041165449 51.7477895111399,0.033431266514812 51.747883681788,0.033651456736236 51.7479706946017,0.033874376044517 51.7480504564056,0.034099785732077 51.7481228817888,0.034327444424575 51.7481878931962,0.034557108339382 51.7482454210121,0.034788531546626 51.7482954036342,0.035021466232538 51.7483377875399,0.035255662964825 51.7483725273435,0.035490870959758 51.7483995858446,0.035726838350724 51.7484189340685,0.035963312457933 51.7484305512964,0.036200040058986 51.7484344250884))'
)) geom)
select ST_IsClosed(geom),ST_MinimumBoundingCircle(geom) from figure
```

**Comment by uslss** [comment]
Reproducible
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Thu Mar 11 11:15:51 MSK 2021
Points of LinearRing do not form a closed linestring

java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:90)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:85)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:356)
	at org.locationtech.jts.io.WKTReader.readLinearRingText(WKTReader.java:879)
	at org.locationtech.jts.io.WKTReader.readPolygonText(WKTReader.java:917)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:818)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:785)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:233)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:214)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromWKT(PostgreGeometryValueHandler.java:176)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.makeGeometryFromPGGeometry(PostgreGeometryValueHandler.java:155)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.getValueFromObject(PostgreGeometryValueHandler.java:114)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreGeometryValueHandler.fetchColumnValue(PostgreGeometryValueHandler.java:53)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:717)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:540)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3233)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:167)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4522)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ShadelessFox** [comment]
Hello @dragonxtek,

The library we're using refuses to parse this data, and we can't really do much about it, unfortunately.

I believe there's the same issue with your geometry data too. It's strange for me that PostgreSQL accepts these values in first place.

**Comment by aleksandaratanasov** [comment]
I also just encountered this issue, while working with both DBeaver and pgadmin. In DBeaver the polygon was invalid. Initially the message was rather obscure (see #18861). After upgrading to 23.1.0 I now get a better description of the issue and this is what led me here. pgadmin didn't complain at all and could display my polygon either way. I had to add an additional endpoint that was also the same as the starting point and it fixed the issue in DBeaver too. Here is a working example:

```
insert into public.test_map (geometry, prop_name, prop_description)
values (
	ST_GeomFromGeoJSON('{
		"type": "Polygon",
		"coordinates": [
			[
				[8.450718, 48.993596],
				[8.494663, 48.993145],
				[8.495522, 48.971733],
				[8.451061, 48.972184],
				[8.450718, 48.993596]
			]
		]
	}'),
	'GeoJSON Polygon',
	'This entry was inserted using ST_GeomFromGeoJSON()'
);
```
