### ISSUE TITLE
Decimal in ClickHouse show as NumberFormatException initially

### ISSUE THREAD

**Issue by atellier** [dbeaver/dbeaver#5147]
#### System information: 
- MacOSX Mojave 10.14.2
- DBeaver 5.3.3.201901202008
- Java 1.8 

#### Connection specification:
- Server: ClickHouse  19.1.6
- Driver: Yandex ClickHouse 0.1.50

#### Describe the problem you're observing:

I created a very simple table with a DateTime and a Decimal64(4) and added some sample data. When retrieving the data, the Decimal column shows values as "NumberFormatException". Scrolling to the bottom and getting a second page of data fixes the issue, and the numbers then show up actual numbers

#### Steps to reproduce, if exist:

Create a table, add some random data (~1000) and retrieve the data, the scroll to paginate:

CREATE TABLE Test (
	timestamp DateTime,
	Test Decimal64(4)
) ENGINE = MergeTree() ORDER BY (timestamp) SETTINGS index_granularity = 8192

![2019-01-29_09-35-53](https://user-images.githubusercontent.com/889679/51928927-df0c0f00-23ab-11e9-8846-c05fb8175830.png)
![2019-01-29_09-36-21](https://user-images.githubusercontent.com/889679/51928932-e206ff80-23ab-11e9-95d7-7484dda398be.png)
![2019-01-29_09-37-06](https://user-images.githubusercontent.com/889679/51928933-e4695980-23ab-11e9-812b-b7365aa220b2.png)

**Comment by serge-rider** [comment]
Can't reproduce. Could you post error log with stacktrace? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by atellier** [comment]
Of course - here you go!
Thanks

```!ENTRY org.jkiss.dbeaver.model 2 0 2019-01-29 11:40:12.665
!MESSAGE Can't read column 'Test' value
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-01-29 11:40:12.665
!MESSAGE For input string: "4536.0000"
!STACK 0
java.lang.NumberFormatException: For input string: "4536.0000"
        at ru.yandex.clickhouse.response.ByteFragmentUtils.parseLong(ByteFragmentUtils.java:120)
        at ru.yandex.clickhouse.response.ClickHouseResultSet.getLong(ClickHouseResultSet.java:359)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getLong(JDBCResultSetImpl.java:379)
        at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:165)
        at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
        at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:103)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:101)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)```

![2019-01-29_11-40-54](https://user-images.githubusercontent.com/889679/51935597-18984680-23bb-11e9-9988-b5ab98dc21da.png)

**Comment by serge-rider** [comment]
I can't reproduce this (There is no Decimal64 data type in my Clickhouse instance maybe because I've upgraded it from earlier version). But it looks like Clickhouse server provides incorrect data type information.
Anyhow, I've added a workaround. You can test it in Early Access version: https://dbeaver.io/files/ea

**Comment by atellier** [comment]
Decimal were introduced in version 19.x I think. Your work around works, Thanks!

BTW, *Create a new Table* fails in ClickHouse, because the DDL code misses an ENGINE (and potentially ORDER BY) parameter.

`Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 51 (end of query) (line 3, col 2): . Expected one of: ENGINE, storage definition, e.what() = DB::Exception`

Thanks again for the hard work and quick fix!
