### ISSUE TITLE
Teradata DBC.UDTInfo error from column information

### ISSUE THREAD

**Issue by foxcoding** [dbeaver/dbeaver#5159]
#### System information: 
Windows 7 64bit
- DBeaver version: CE-5.3.3
- Java version 1.8

#### Connection specification:
- Teradata 15.10.7.14
- Teradata jdbc 16.20.00.10
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Trying to view column information in the Database Navigator, or generating a select statement give sthis error:

Dialog box:
SQL Error [5315] [HY000]: [Teradata Database] [TeraJDBC 16.10.00.07] [Error 5315] [SQLState HY000] The user does not have SELECT access to DBC.UDTInfo.TypeName.
  [Teradata Database] [TeraJDBC 16.10.00.07] [Error 5315] [SQLState HY000] The user does not have SELECT access to DBC.UDTInfo.TypeName.
  [Teradata Database] [TeraJDBC 16.10.00.07] [Error 5315] [SQLState HY000] The user does not have SELECT access to DBC.UDTInfo.TypeName.

For users who do not have permissions to DBC.UDTInfo, only to DBC.UDTInfoV, Columns information cannot be expanded in the navigator.

The DBA's claim that access to the table is not necessary (can cause locking), and in any other Eclipse based IDE, (Teradata Studio) this is not a problem.

Running the latest drivers, this happens to everyone in our user-group.

#### Steps to reproduce, if exist:
On the server, make sure that the account for testing does not have permissions to DBC.UDTInfo, only to DBC.UDTInfoV
#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Wed Jan 30 15:21:53 EST 2019
[Teradata Database] [TeraJDBC 16.10.00.07] [Error 5315] [SQLState HY000] The user does not have SELECT access to DBC.UDTInfo.TypeName.

java.sql.SQLException: [Teradata Database] [TeraJDBC 16.10.00.07] [Error 5315] [SQLState HY000] The user does not have SELECT access to DBC.UDTInfo.TypeName.
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDatabaseSQLException(ErrorFactory.java:309)
	at com.teradata.jdbc.jdbc_4.statemachine.ReceiveInitSubState.action(ReceiveInitSubState.java:103)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.subStateMachine(StatementReceiveState.java:311)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:200)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:137)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.run(StatementController.java:128)
	at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:389)
	at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:331)
	at com.teradata.jdbc.jdbc_4.TDStatement.doNonPrepExecuteQuery(TDStatement.java:319)
	at com.teradata.jdbc.jdbc_4.TDStatement.executeQuery(TDStatement.java:1121)
	at com.teradata.jdbc.TeraDatabaseMetaData.getColumns(TeraDatabaseMetaData.java:3413)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1152)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:126)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:222)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getAttributes(GenericTable.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:824)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:805)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:885)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:421)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:206)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by faibistes** [comment]
Same thing here, trying to export a Postgresql resultset to Teradata

**Comment by serge-rider** [comment]
This is Teradata JDBC-driver specific issue: https://www-01.ibm.com/support/docview.wss?uid=swg21973669

Looks like you still need this permission to read view columns.
I'm not aware about any workarounds.
