### ISSUE TITLE
Editing enum array within GUI doesn't work

### ISSUE THREAD

**Issue by byt3pool** [dbeaver/dbeaver#5224]
#### System information: 
- _Operating system:_ Windows 10 Pro, 1803 
- _DBeaver version:_ 5.3.4.201902031804
- _Java version:_ Openjdk version "1.8.0_192" (Amazon Coretto, but also tested with the Oracle version)

#### Connection specification:
- _Database name and version:_ PostgreSQL 10.6
- _Driver name:_ PostgreSQL JDBC Driver 42.2.5 & Postgis JDBC 2.2.1
- _Do you use tunnels or proxies (SSH, SOCKS, etc)?_ No

#### Problemdescription
I just initialized a new simple database project with a bunch of tables and noticed that i couldn't edit a row with type _myenum (array of enum values).

Myenum is an enum type generated via
`CREATE TYPE myenum AS ENUM ('dds', 'dcs');`

When I try to insert values (inline) per hand into columns of this type it only shows [NULL] for the value, no matter what I have tried, it won't let me choose out of my defined values of the enum.
For column with type myenum (no array), I can choose from the values of the enum.

Other array types, e.g. _bool everything works as expected.

#### Steps to reproduce:

1. Create custom enum type 'myenum'
2. Use it in column as array '_myenum'
3. Try to insert values into this column per hand (inline) with GUI

#### Logs
When editing the column, following error appears in the logs:

**1. org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType cannot be cast to org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute**

`java.lang.ClassCastException: org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType cannot be cast to org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreEnumValueManager.getEnumValues(PostgreEnumValueManager.java:39)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:109)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:58)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.showEditor(ComplexObjectEditor.java:303)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.access$12(ComplexObjectEditor.java:289)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$AddElementAction.run(ComplexObjectEditor.java:724)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:439)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)`

**2. Unhandled event loop exception**

`java.lang.ClassCastException: org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType cannot be cast to org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreEnumValueManager.getEnumValues(PostgreEnumValueManager.java:39)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:109)
	at org.jkiss.dbeaver.ui.data.managers.EnumValueManager$EnumInlineEditor.createControl(EnumValueManager.java:1)
	at org.jkiss.dbeaver.ui.data.editors.BaseValueEditor.createControl(BaseValueEditor.java:58)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.showEditor(ComplexObjectEditor.java:303)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor.access$12(ComplexObjectEditor.java:289)
	at org.jkiss.dbeaver.ui.data.dialogs.ComplexObjectEditor$AddElementAction.run(ComplexObjectEditor.java:724)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:439)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)`

**Comment by serge-rider** [comment]
Thanks for the bug report
