### ISSUE TITLE
Debugging in dbeaver 5.3.4 and PostgreSQL 10.6

### ISSUE THREAD

**Issue by gallifabio** [dbeaver/dbeaver#5230]
Hi,

unfortunately I cannot start debugging from DBeaver. With the latest version of PGAdmin (v. 4.2 at the moment of writing) debugging works fine so I assume I've installed everything correctly on the Postgres side. First some info about my pc:

Windows 7 SP1 64bit

Firewall: off

DBeaver 5.3.4 unzipped from zip archive (I haven't used the installer) with debugger plugin:

![image](https://user-images.githubusercontent.com/3372532/52407207-df08bf00-2acf-11e9-8e84-7bd8b4b5d625.png)

java -version
openjdk version "1.8.0_181-1-redhat"
OpenJDK Runtime Environment (build 1.8.0_181-1-redhat-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

My Postgres instance is running in a Docker container:

PostgreSQL 10.6 (Debian 10.6-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

I've installed the debugger plugin inside the container and it's active:

![image](https://user-images.githubusercontent.com/3372532/52407030-76b9dd80-2acf-11e9-8870-fa158cea8568.png)

The first strange thing about my local DBeaver is that I can't find the DEBUG menu even if I open the source tab in the DEBUG perspective:

![image](https://user-images.githubusercontent.com/3372532/52407963-f9439c80-2ad1-11e9-8cee-f8c62ba861e7.png)

So I've created a debug configuration to start the debugging:

![image](https://user-images.githubusercontent.com/3372532/52408093-58091600-2ad2-11e9-973e-d4731b422d4f.png)

When I hit the debug button the background task starts:

![image](https://user-images.githubusercontent.com/3372532/52408253-c77f0580-2ad2-11e9-851a-ac76f77406fc.png)

But after some seconds I receive the following error:

![image](https://user-images.githubusercontent.com/3372532/52408263-d2399a80-2ad2-11e9-8b85-af7bfc4d0071.png)

Can you please help me to enable the debugger? Please let me know if you need more info about my local or postgres installation. TIA,

**Comment by serge-rider** [comment]
We have wiki article about that - https://github.com/dbeaver/dbeaver/wiki/PGDebugger

It is a bit outdated but instructions for server-side config should be up-to-date.

**Comment by toninomanzi** [comment]
I have the same issue of Fabio Galli, I followed the article but nothing

**Comment by EldarCM** [comment]
I also have the same error as OP. I have followed all server-side instructions and debugger seems to works fine in pgadmin, but I get the following error in dbeaver:

> Error opening debug session
> Unable to rcv port number

I know that connection couldn't be established, but I couldn't find any documentation that could help me solve this problem and I'm kinda stuck here.

Logfile:
`!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-19 18:28:40.730
!MESSAGE Error opening debug session
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-08-19 18:28:40.730
!MESSAGE Unable to rcv port number
!STACK 0
org.jkiss.dbeaver.debug.DBGException: Unable to rcv port number
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.waitPortNumber(PostgreDebugSession.java:312)
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.attachLocal(PostgreDebugSession.java:394)
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.attach(PostgreDebugSession.java:469)
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugController.createSession(PostgreDebugController.java:51)
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugController.createSession(PostgreDebugController.java:1)
	at org.jkiss.dbeaver.debug.DBGBaseController.openSession(DBGBaseController.java:71)
	at org.jkiss.dbeaver.debug.core.model.DatabaseDebugTarget.connect(DatabaseDebugTarget.java:181)
	at org.jkiss.dbeaver.debug.core.DatabaseLaunchDelegate.launch(DatabaseLaunchDelegate.java:56)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1020)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by abhijithss2010** [comment]
I am facing the same issue.
Does anybody have a solution?

**Comment by serge-rider** [comment]
Do you use local or global debug?

Looks like Local debug is broken but Global should work..

**Comment by flambchap** [comment]
Unfortunately, global breakpoints don't work. We'll disable them in 7.3.2, but we plan to make them work again sometime in the future. I also updated the wiki page about debugging, now it's up to date. If you do still have any problems with debugging, please comment down below. I also would like you to provide your PostgreSQL version and _full_ [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) (_dbeaver-debug.log_ file).

**Comment by sudipdind** [comment]
I was also getting the same error while debugging Procedure with 3 parameter. 
Fncname(1,2,3) error
Then pass the parameter as Fncname('1','2','3')  solved

**Comment by Cye3s** [comment]
Same error here, but work fine with Navicat 15 for PostgreSQL and pgAdmin4
![QQ截图20210707145256](https://user-images.githubusercontent.com/2126873/124713840-9f11c480-df33-11eb-9e8b-81339ff5b0ec.png)

**Comment by Cye3s** [comment]
Same error here, but work fine in Navicat 15 for PostgreSQL and pgAdmin4
![QQ截图20210707145256](https://user-images.githubusercontent.com/2126873/124714264-1fd0c080-df34-11eb-87c2-95a01e1f8de9.png)
