### ISSUE TITLE
Occasional Sql Server Error Masking with MS JDBC Driver

### ISSUE THREAD

**Issue by zippyjason** [dbeaver/dbeaver#5233]
#### System information: 
- Operating system Ubuntu 16.04.5 LTS
- DBeaver version 5.3.4
- Java version openjdk-8
- Additional extensions - None

#### Connection specification:
- Database name and version - Sql Server 2008 R2
- Driver name - Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
DBeaver is reporting success in certain instances where an update query has failed

#### Steps to reproduce, if exist:
-- This reliably fails for me
-- SETUP

create table t0_type
(
  id int,
  type_lookup varchar(10)
);

insert into t0_type values (1, 'excellent');

create table t0_test
(
  id int identity primary key not null,
  version int not null,
  type_id int not null,
  type_lookup varchar(10),
  label varchar(10)
);

create table t0_test_bak 
(
  id int not null,
  version int not null,
  label varchar(10),
  type_id varchar(10),
  type_lookup varchar(10),
  constraint pk_test_bak primary key clustered (id, version)
);

create procedure sp_test_backup
@id int
as begin
  insert into t0_test_bak (id, version, type_id, type_lookup, label)
  select id, version, type_id, type_lookup, label from t0_test where id = @id
end;

create trigger tiu_test on t0_test for insert, update as
begin
  declare @id int, @type_id int, @type_lookup varchar(10)
  select @id = inserted.id, @type_id = inserted.type_id from inserted
  select @type_lookup = type_lookup from t0_type where id = @type_id
  -- this looks innocent, but this line makes all the difference -- used to denormalize a much needed value
  update t0_test set type_lookup = @type_lookup where id = @id 
  exec sp_test_backup @id
end;

insert into t0_test values (1, 1, null, 'hello');

-- PROBLEM
-- EXPECTED BEHAVIOR: primary key violation error message
-- OBSERVED BEHAVIOR: silent fail
update t0_test set label = 'hello!!' where id = 1;

select * from t0_test

#### Include any warning/errors/backtraces from the logs
.dbeaver4/.metadata/.log shows correct error:
!ENTRY org.jkiss.dbeaver.model 4 0 2019-02-07 07:49:52.811
!MESSAGE SQL Error [2627] [23000]: Violation of PRIMARY KEY constraint 'pk_test_bak'. Cannot inser$
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-02-07 07:49:52.811
!MESSAGE Violation of PRIMARY KEY constraint 'pk_test_bak'. Cannot insert duplicate key in object $
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'pk_test_bak'$
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerExceptio$
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1$
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getMoreResults(SQLServerStatement.java:$
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.nextResults(JDBCStatementImpl.$
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:$
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.jav$
        at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:835)
        at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.jav$
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataR$
        at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.j$
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

# I also see a lot of these:

!ENTRY org.jkiss.dbeaver.model 4 0 2019-02-07 07:49:52.843
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-02-07 07:49:52.843
!MESSAGE
!STACK 0
java.lang.NullPointerException
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSet$
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetVie$
        at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataRec$
        at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
        at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
        at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.$
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.ja$
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:161)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppL$
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.j$
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

!ENTRY org.jkiss.dbeaver.model 2 0 2019-02-07 07:52:39.764
!MESSAGE Datasource user 'org.jkiss.dbeaver.ui.editors.sql.SQLEditor@263f6e96' already registered $

NOTE:

this does not happen with the older JTDS driver.

**Comment by serge-rider** [comment]
Thanks for the bug report
