### ISSUE TITLE
Can't execute query - no active database on InfluxDB

### ISSUE THREAD

**Issue by brunowego** [dbeaver/dbeaver#5281]
#### System information: 
- Operating system OS X and version is Mojave
- DBeaver version 5.3.5
- Java version 11.0.2

#### Connection specification:
- Database InfluxDB and version is 1.7.2
- Driver name InfluxDB

#### Describe the problem you're observing:

```
Query execution failed

Reason:
Can't execute query - no active database
```

```
eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/brunowego/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/brunowego/.eclipse_keyring

org.jkiss.dbeaver.model
Error
Thu Feb 14 09:42:16 BRST 2019
Can't execute query - no active database

org.jkiss.dbeaver.model.exec.DBCException: Can't execute query - no active database
	at com.dbeaver.ee.influxdb.exec.InfluxSelectStatement.executeStatement(InfluxSelectStatement.java:61)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1635)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:839)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2691)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1635)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by serge-rider** [comment]
You need to set active database. You can specify it on the connection page (to make it default) or you can change it from context menu:

![image](https://user-images.githubusercontent.com/6398845/52821908-4ec70d00-30c1-11e9-9c39-b241271f2b2f.png)

![image](https://user-images.githubusercontent.com/6398845/52822000-8fbf2180-30c1-11e9-875a-fa77697c2a27.png)

**Comment by brunowego** [comment]
Thanks @serge-rider. I have not seen it.

**Comment by arLevi** [comment]
I have both, and I still see the error, moreover, the "set active" is not found in my version (5.3.2)

**Comment by grodriguezVS** [comment]
> I have both, and I still see the error, moreover, the "set active" is not found in my version (5.3.2)

![image](https://user-images.githubusercontent.com/45537591/60707802-8997d900-9eda-11e9-8322-3c4f3c6bfb0a.png)
I was experiencing the same, however I noticed in my toolbar there was, still, no connection selected. So I selected it from the dropdown and it worked.
![image](https://user-images.githubusercontent.com/45537591/60707898-c368df80-9eda-11e9-829b-7e026d94b87b.png)
