### ISSUE TITLE
Informix - data type : bson

### ISSUE THREAD

**Issue by nemdaz** [dbeaver/dbeaver#5285]
Error : Select data type bson. Informix Server

Dbeaver version: 5.3.4 (last update) | Community.

![14-02-2019 05-00-05 p-m-](https://user-images.githubusercontent.com/6315069/52820540-426b9180-307a-11e9-9608-dcd6a6839739.png)

Full error

`org.jkiss.dbeaver.model.exec.DBCException: SQL Error [IX000]: A customized type map is required for this data type.
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:742)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:475)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:835)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2690)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: A customized type map is required for this data type.
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
	at com.informix.jdbc.IfxUDT.toObject(IfxUDT.java:118)
	at com.informix.jdbc.IfxUDT.toObject(IfxUDT.java:85)
	at com.informix.jdbc.IfxResultSet.getObject(IfxResultSet.java:1520)
	at com.informix.jdbc.IfxResultSet.getObject(IfxResultSet.java:809)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCObjectValueHandler.fetchColumnValue(JDBCObjectValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	... 13 more`

**Comment by serge-rider** [comment]
This is Informix-specific driver issue. I'm afraid we can't resolve this on DBeaver side (or at least I don't know how can we do it).

See workaround here: https://stackoverflow.com/questions/14642281/how-to-show-informix-sysprocedures-paramtypes-column-via-jdbc

**Comment by brian-hughes** [comment]
If you can upgrade the JDBC driver, it should work.  I just tested it showed the bson column output.  The JDBC driver for Informix shipping with DBeaver is pretty old.  You can find the newest driver here on maven central
https://search.maven.org/artifact/com.ibm.informix/jdbc/4.50.1/jar

You can do this manually, but it would be great if the default repo was updated with the newer driver?
