### ISSUE TITLE
Can't open Sybase IQ procedures (Sybase ASE is OK now)

### ISSUE THREAD

**Issue by inigomp** [dbeaver/dbeaver#5306]
#### System information: 
- Windows 7
- DBeaver 5.3.5

#### Connection specification:
- Sybase IQ 15
- Sybase jConnect
- Do you use tunnels or proxies (SSH, SOCKS, etc) No

#### Describe the problem you're observing:

Can't read or edit stored procedures. When I try to get the procedures list, it appears a warn window:

![image](https://user-images.githubusercontent.com/47743019/52948135-f15ce580-3378-11e9-9109-10e9558709f0.png)

SQL Error [207] [52003]: SQL Anywhere Error -143: Column 'loginame' not found
  SQL Anywhere Error -143: Column 'loginame' not found
  SQL Anywhere Error -143: Column 'loginame' not found

#### Include any warning/errors/backtraces from the logs

[error.log](https://github.com/dbeaver/dbeaver/files/2875381/error.log)

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Feb 18 12:29:13 CET 2019
SQL Error [207] [52003]: SQL Anywhere Error -143: Column 'loginame' not found

-------------------------------------------------------------------------------------------------

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=es_ES
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Feb 18 12:29:13 CET 2019
SQL Anywhere Error -143: Column 'loginame' not found

com.sybase.jdbc4.jdbc.SybSQLException: SQL Anywhere Error -143: Column 'loginame' not found
	at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4201)
	at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3318)
	at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:302)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:284)
	at com.sybase.jdbc4.jdbc.SybStatement.queryLoop(SybStatement.java:2655)
	at com.sybase.jdbc4.jdbc.SybStatement.executeQuery(SybStatement.java:2641)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeQuery(SybPreparedStatement.java:274)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:232)
	at org.jkiss.dbeaver.ext.mssql.model.generic.SQLServerMetaModel.loadProcedures(SQLServerMetaModel.java:106)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:413)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getProcedures(GenericObjectContainer.java:287)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getProceduresOnly(GenericObjectContainer.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:824)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:805)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:885)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1635)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:421)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:206)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by inigomp** [comment]
Hi, why is this bug report closed? Are you working on it or it still being
a bug?
