### ISSUE TITLE
string conversion

### ISSUE THREAD

**Issue by datamodeler** [dbeaver/dbeaver#5312]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by datamodeler** [comment]
running EE 5.3 on Windows 10
keep getting message re conversion of java string to integer
there are NO strings in the columns for which I am attempting to generate data

**Comment by serge-rider** [comment]
Please post error stacktrace ( https://github.com/dbeaver/dbeaver/wiki/Log-files )
Perhaps this is a result of some misconfiguration or a bug but I can;t say without additional information.

**Comment by datamodeler** [comment]
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Feb 18 09:37:44 EST 2019
java.lang.String cannot be cast to java.lang.Integer

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.dbeaver.ee.mockdata.adv.generator.NumericAdvancedGenerator.init(NumericAdvancedGenerator.java:51)
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:213)
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:1)
	at org.jkiss.dbeaver.ui.dialogs.tools.AbstractToolWizard.run(AbstractToolWizard.java:287)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$8(UIUtils.java:1429)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by serge-rider** [comment]
Thanks for the logs.
It is a bug in mock data generator, will be fixed in the next release.
