### ISSUE TITLE
SQL Error [S1000]: Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR

### ISSUE THREAD

**Issue by douglasdtc** [dbeaver/dbeaver#5353]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version 5.3.5

#### Connection specification:
- Database name and version Intersystems Caché 2017.2
- Driver name Cache
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### The problem:
We have a field on the Database which is a GlobalCharacterStream (the same type of field of this issue [https://github.com/dbeaver/dbeaver/issues/469](url)). When trying to edit the field inline, we get an error: SQL Error [S1000]: Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR

#### Steps to reproduce:
Run a SELECT on the table with that type of column
Click the cell of the desired column to edit
Change the data on the panel that appears on the right (saving to file and then loading from file generates the same error)
Click on Save
The following error appears:
```
Error synchronizing data with database

Reason:
SQL Error [S1000]: Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR
```

#### Log
```
!ENTRY org.jkiss.dbeaver.model 4 0 2019-02-25 10:27:15.314
!MESSAGE SQL Error [S1000]: Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-02-25 10:27:15.314
!MESSAGE Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR
!STACK 0
java.sql.SQLException: Unsupported type conversion: byte[] to java.sql.Types.LONGVARCHAR
	at com.intersys.jdbc.CachePreparedStatement.setBytes(CachePreparedStatement.java:348)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.setBytes(JDBCPreparedStatementImpl.java:362)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentBytes.bindParameter(JDBCContentBytes.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.bindParameter(JDBCContentValueHandler.java:121)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:64)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:458)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:79)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:596)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:490)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1635)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:489)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:440)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

If there's any additional information need, please let me know. Thank you.

**Comment by uslss** [comment]
hi @douglasdtc , is it still actual for you?
unfortunately i've got no env to test.
sorry for the late response

**Comment by douglasdtc** [comment]
Hello @uslss , yes, this is still happening on version 7.0.0

**Comment by uslss** [comment]
@douglasdtc unfortunately, we've got no env to test.
Could you please check if it is still actual against 21.1.3?
thanks in advance.

**Comment by douglasdtc** [comment]
@uslss , yes, just updated and tested it, it's still happening on version 21.1.3.202107181810. If you want to, we can provide an environment with a database set up so you can test it.
Thank you for your help.

![image](https://user-images.githubusercontent.com/19532943/126365097-651d4c58-1c33-4c22-be89-acd9c20228a5.png)

**Comment by douglasdtc** [comment]
Hello @uslss , thank you for your response. Unfortanetly we cannot test it, since there's a new bug regarding GlobalCharacterStreams on Intersystems Caché in recent DBeaver versions. The issu is still open here https://github.com/dbeaver/dbeaver/issues/11899 . I've just updated to the 21.1.3 version and tested it and it still presents the value as `[CacheInputStream]`.
If you need to, we can provide and envrionment with an Intersystems Caché installed and a database with the minimum data to reproduce this error.

**Comment by LonwoLonwo** [comment]
Hello @douglasdtc 

I see that in Dbeaver we are using the old driver version.

Could you please check your issue with the latest driver version? 
https://www.cachemonitor.de/intersystems-documentation-cache-jdbc-driver/

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
