### ISSUE TITLE
Throws error while clicking on tables with Elasticsearch 6.6: request [/_xpack/sql] contains unrecognized parameter: [mode]

### ISSUE THREAD

**Issue by Getty** [dbeaver/dbeaver#5359]
#### System information: 
- Windows 10
- DBeaver Enterprise 5.3.3
- JavaSE Runtime 1.8.0_191

#### Connection specification:
- Elasticsearch 6.6.0 (in Docker)
- Driver of DBeaver
- No tunnels, just that the traffic goes through docker-proxy

#### Describe the problem you're observing:

Clicking on tables of the Elasticsearch connection leads to this error:

Server sent bad type [illegal_argument_exception]. Original type was [request [/_xpack/sql] contains unrecognized parameter: [mode]]. [java.lang.IllegalArgumentException: request [/_xpack/sql] contains unrecognized parameter: [mode]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:92)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:240)
	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:336)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:174)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:551)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:137)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

#### Steps to reproduce, if exist:

Clicking on tables ;)

#### Include any warning/errors/backtraces from the logs

If needed, please say so

**Comment by Getty** [comment]
Oh! I just came to the info that i need to add the xpack extra to the driver, didn't saw the Elasticsearch info page about DBeaver yet, so that would explain it probably. Closing if successful with that

**Comment by serge-rider** [comment]
Perhaps will be resolved by https://github.com/dbeaver/dbeaver/pull/5171

**Comment by tati-kru** [comment]
Please test with 6.0

**Comment by songhanlin** [comment]
## System information: 
### OSX 10.14.5
### DBeaver Enterprise 6.0
### Elasticsearch 6.6.0
still have this error
```
Error caching database model

原因：
 SQL 错误 [bad_server]: Server sent bad type [invalid_index_name_exception]. Original type was [Invalid index name [_xpack], must not start with '_']. [[_xpack] InvalidIndexNameException[Invalid index name [_xpack], must not start with '_']
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:148)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:431)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreateIndexService.java:95)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:190)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]
```

**Comment by adamczi** [comment]
People in #5171 report that error still occurs and I can confirm - using latest DBeaver 6.1.3 from "https://dbeaver.io/debs/dbeaver-ce" apt repo on Ubuntu 18.04 and ES v.7.2.0. Any chance to reopen? :thinking: I basically connect to ES which is inside container. ES itself is almost fresh with a little amount of test data inside and I wasn't able to open _any_ of existing tables. Thanks in advance.

**Comment by serge-rider** [comment]
Please try to updage elastic driver to the most recent version (6,7.2).
- Open driver editor for Elasticsearch driver
- Remove existing library from library list
- Add artifact:
   - Group id: org.elasticsearch.plugin
   - Artifact id: x-pack-sql-jdbc
   - Classifier: (leave empty)
   - Versin 6.7.2
- Click Download/Update button

Now you can try to connect with new version

**Comment by adamczi** [comment]
Thanks for your respose. Following the instructions, when tried to connect to ES I received an error:

> This version of the JDBC driver is only compatible with Elasticsearch version v6.7.2 [56c6e48], attempting to connect to a server version 7.2.0

printscreen of my settings here: https://i.imgur.com/vWiSujI.png and my DBeaver version is 6.1.3.201907211943

**Comment by serge-rider** [comment]
Thanks for testing. We'll update default ES driver version in the next version.
