### ISSUE TITLE
 Null pointer exception  with BIGQUERY (some SQL formatting) 

### ISSUE THREAD

**Issue by satygupta** [dbeaver/dbeaver#5409]
Hi,

I am connecting to bigquery using community edition of dbeaver.
I am getting Null pointer exception when I try to execute the following SQL (if executed as is if I reformat it to reduce no of lines then it works ). To replicate the issue I have used public dataset of bigquery.

select
  mailing_id
,   mailing_nm as link_campaign2
from
(
    select
        * 
      , row_number() over 
            ( partition by 
                                    mailing_id
                        order by
                    update_ts desc
                    ) as row_mailing_id
from (select author.email as mailing_id,author.name as mailing_nm,	author.date as update_ts from 	`bigquery-public-data.github_repos.sample_commits`)
) as mailing
where mailing.row_mailing_id = 1

Below is the error

SQL Error [HY000]: [Simba][JDBC](11380) Null pointer exception.
  [Simba][JDBC](11380) Null pointer exception.
  [Simba][JDBC](11380) Null pointer exception.
    
    java.lang.NullPointerException

Information: 
- Operating system (distribution) and version Windows 7 and 10
- DBeaver version :5.3.4
-Google BigQuery driver 
https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.1.8.1010.zip

Please let me know if you need further information.

Regards,
Sat

**Comment by serge-rider** [comment]
I can't reproduce this but most likely it is a bug in Simba driver. 
Could you post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files) ?

**Comment by satygupta** [comment]
Below is the error stack

java.lang.NullPointerException
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:835)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2690)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
We'll update BQ driver version to the most recent (1.2.0.1000) in the next version.
You may need to update it manually (go to driver settings -> download/update)

**Comment by uslss** [comment]
The issue is still reproducible. Seems to be Simba driver issue.

**Comment by alphafer** [comment]
I noticed that queries in Dbeaver when you apply formatting Ctrl + Shift + F the query will return 'Null pointer exception'. But if you manually apply indentation the query will run fine.
