### ISSUE TITLE
DBeaver didn't support ORACLE sys. xml_type ?

### ISSUE THREAD

**Issue by helloCount** [dbeaver/dbeaver#5454]
#### System information: 
- Operating system (distribution) and version
- DBeaver version 6.0.0
- Java version 1.8.0_172
- Additional extensions

#### Connection specification:
- Database name and version ORACLE_11g
- Driver name oracle.jdbc.OracleDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
when I select a table (id varchar(100), xmlrecord SYS.XMLTYPE(2000)) from oracle database(ORALCE_11g), I found 'xmlrecord ' field throws exception :
java.lang.NullPointerException
	at oracle.jdbc.driver.SQLUtil.makeDatum(SQLUtil.java:642)
	at oracle.jdbc.driver.ScrollableResultSet.getCachedDatumValueAt(ScrollableResultSet.java:2527)
	at oracle.jdbc.driver.ScrollableResultSet.getOracleObject(ScrollableResultSet.java:634)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1142)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1088)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:635)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:52)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:746)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:475)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:839)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
#### Steps to reproduce, if exist:
select a ORACLE table that at least one filed is ORALCE SYS.XMLTYPE

**Comment by maln0ir** [comment]
It support XMLTYPE, but you need to install additional jars. See #171
