### ISSUE TITLE
Script files deleted on the disk still show in DBeaver

### ISSUE THREAD

**Issue by APMMMatthews** [dbeaver/dbeaver#5471]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.0.0
- Java version: Installed with DB Beaver
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Scripts deleted from .dbeaver4\General\Scripts\ manually still show up in DBeaver.  They cannot be deleted from using the delete button. 
How can I clear out these records?

I get the following error: 
2019-03-12 15:17:26.164 - Can't obtain content description for 'AAUsers.sql'
org.eclipse.core.internal.resources.ResourceException(/General/Scripts/AAUsers.sql)[368]: java.io.FileNotFoundException: C:\Users\mmatthews\.dbeaver4\General\Scripts\AAUsers.sql (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:404)
	at org.eclipse.core.internal.resources.ContentDescriptionManager$LazyFileInputStream.ensureOpened(ContentDescriptionManager.java:159)
	at org.eclipse.core.internal.resources.ContentDescriptionManager$LazyFileInputStream.read(ContentDescriptionManager.java:176)
	at java.io.InputStream.read(InputStream.java:101)
	at org.eclipse.core.internal.content.LazyInputStream.loadBlock(LazyInputStream.java:104)
	at org.eclipse.core.internal.content.LazyInputStream.ensureAvailable(LazyInputStream.java:68)
	at org.eclipse.core.internal.content.LazyInputStream.read(LazyInputStream.java:127)
	at org.eclipse.core.internal.content.Util.getByteOrderMark(Util.java:122)
	at org.eclipse.core.internal.content.TextContentDescriber.describe(TextContentDescriber.java:46)
	at org.eclipse.core.internal.content.ContentType.describe(ContentType.java:182)
	at org.eclipse.core.internal.content.ContentType.internalGetDescriptionFor(ContentType.java:473)
	at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:408)
	at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:412)
	at org.eclipse.core.internal.content.ContentTypeMatcher.getDescriptionFor(ContentTypeMatcher.java:82)
	at org.eclipse.core.internal.resources.ContentDescriptionManager.readDescription(ContentDescriptionManager.java:455)
	at org.eclipse.core.internal.resources.ContentDescriptionManager.getDescriptionFor(ContentDescriptionManager.java:364)
	at org.eclipse.core.internal.resources.File.getContentDescription(File.java:266)
	at org.jkiss.dbeaver.registry.ResourceHandlerDescriptor.canHandle(ResourceHandlerDescriptor.java:148)
	at org.jkiss.dbeaver.registry.ProjectRegistry.getResourceHandler(ProjectRegistry.java:213)
	at org.jkiss.dbeaver.model.navigator.DBNResource.makeNode(DBNResource.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNResource.readChildNodes(DBNResource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:143)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:219)
	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
#### Steps to reproduce, if exist:
Enter: .dbeaver4\General\Scripts\ and delete a file. 
Then open DBBeaver and attempt to remove the file form DBBeaver and it fails.

**Comment by serge-rider** [comment]
You can refresh DBeaver workspace or just one folder using F5 button (or context menu). 
On refresh DBeaver will synchronize virtual filesystem with native OS filesystem.

**Comment by APMMMatthews** [comment]
The problem arises for folders that no longer exist. IT ops move the location of a mounted drive and I can’t get rid of the listing for the file.

**Comment by uslss** [comment]
still reproducible in 7.0.4

**Comment by uslss** [comment]
probably, will be fixed in the scope of #6398

**Comment by APMMMatthews** [comment]
Thanks

**Comment by NikRom5531** [comment]
Unable to reproduce on DBeaver 26.2.1.
- Script deleted while the app is running disappears after clicking on it or shortly after - expected behavior.
- Script deleted before app startup does not appear in the list.
Issue not confirmed.
