### ISSUE TITLE
DBCException reading Oracle CLOB

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#5503]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: CE 6.0.0
- Java version: bundled
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Oracle 11
- Driver name: ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
The following error appears while loading CLOB:
```
org.jkiss.dbeaver.model.exec.DBCException: IO error while copying content
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentCLOB.getContents(JDBCContentCLOB.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.getValueFromObject(JDBCContentValueHandler.java:201)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:746)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:475)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:839)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2696)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: ORA-22922: nonexistent LOB value

	at oracle.jdbc.driver.OracleClobReader.needChars(OracleClobReader.java:264)
	at oracle.jdbc.driver.OracleClobReader.read(OracleClobReader.java:195)
	at java.io.Reader.read(Reader.java:140)
	at org.jkiss.dbeaver.utils.ContentUtils.copyStreams(ContentUtils.java:182)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCContentCLOB.getContents(JDBCContentCLOB.java:112)
	... 17 more
Caused by: java.sql.SQLException: ORA-22922: nonexistent LOB value

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385)
	at oracle.jdbc.driver.T4C8TTILob.processError(T4C8TTILob.java:790)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8TTIClob.read(T4C8TTIClob.java:245)
	at oracle.jdbc.driver.T4CConnection.getChars(T4CConnection.java:4142)
	at oracle.sql.CLOB.getChars(CLOB.java:517)
	at oracle.jdbc.driver.OracleClobReader.needChars(OracleClobReader.java:245)
	... 21 more
```

#### Steps to reproduce, if exist:
Open session browser. See a large **parallel** query (large as in long text)
Get the query run by the session browser from the query manager
Execute the same query in a sql editor
Look at the SQL_FULLTEXT CLOB field: during a parallel query (/*+parallel(16)*/ hint) the very same query would be replicated many times. The first row of the resultset contains the query, and it is readable. For all the other replicas, the cell contains the above exception and is highlighted in purple.
Unfortunately I believe this is not fully reproducible; maybe sometimes Oracle returns the same LOB reference for all the rows, and after one is closed the others cannot be read. But that's just speculating.
The session browser itself works fine, it's just standard resultset which is broken.

**Comment by serge-rider** [comment]
This seems to be a bug in Oracle 11.
https://support.oracle.com/knowledge/More%20Applications%20and%20Technologies/2194741_1.html

**Comment by serge-rider** [comment]
But if the same works in some other UI client then maybe we can make some workaround in DBeaver.

**Comment by p91paul** [comment]
awesome... well it works in DBeaver if using session browser instead of resultset, so maybe there's hope of finding a workaround.
