### ISSUE TITLE
Cannot open DBeaver in windows any more after 6.0.0

### ISSUE THREAD

**Issue by biellls** [dbeaver/dbeaver#5517]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows 10 Enterprise Version	10.0.17134 Build 17134
- DBeaver version: 6.0.0.201903101945
- Java version: Bundled JRE
- Additional extensions: None

#### Describe the problem you're observing:
DBeaver won't open at all, though the splashscreen does show.

#### Include any warning/errors/backtraces from the logs
I ran it with DBeaver CLI, but I can see the same error in ~/.debeaver4/.metadata
```
.\dbeaver-cli.exe
2019-03-18 12:00:24.519 - Create display
2019-03-18 12:00:24.712 - > Start org.jkiss.dbeaver.core [6.0.0.201903101945]
2019-03-18 12:00:24.727 - DBeaver 6.0.0.201903101945 is starting
2019-03-18 12:00:24.730 - OS: Windows 10 10.0 (amd64)
2019-03-18 12:00:24.731 - Java version: 1.8.0_77 by Oracle Corporation (64bit)
2019-03-18 12:00:24.734 - Install path: 'file:/C:/Program Files/DBeaver/'
2019-03-18 12:00:24.737 - Instance path: 'file:/C:/Users/gllobera/.dbeaver4/'
2019-03-18 12:00:24.739 - Memory available 245Mb/3616Mb
2019-03-18 12:00:24.769 - Starting RMI server at 25142
2019-03-18 12:00:24.836 - Run workbench
2019-03-18 12:00:24.852 - > Start org.eclipse.e4.ui.workbench.swt [0.14.300.v20180906-1121]
2019-03-18 12:00:24.859 - > Start org.eclipse.e4.core.services [2.1.200.v20180817-1215]
2019-03-18 12:00:24.860 - > Start org.eclipse.e4.core.contexts [1.7.100.v20180817-1215]
2019-03-18 12:00:24.874 - > Start org.eclipse.e4.ui.services [1.3.200.v20180906-1121]
2019-03-18 12:00:24.933 - > Start org.eclipse.e4.ui.di [1.2.300.v20180906-1121]
2019-03-18 12:00:24.994 - > Start org.eclipse.emf.common [2.15.0.v20180723-1316]
2019-03-18 12:00:25.023 - > Start org.eclipse.emf.ecore [2.15.0.v20180722-1159]
2019-03-18 12:00:25.164 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-03-18 12:00:25.371 - < Stop org.eclipse.core.resources [3.13.100.v20180828-0158]
2019-03-18 12:00:25.383 - Internal error in workbench lifecycle
java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
        at org.eclipse.emf.ecore.plugin.EcorePlugin.getWorkspaceRoot(EcorePlugin.java:1149)
        at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.<clinit>(ExtensibleURIConverterImpl.java:393)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getURIConverter(ResourceSetImpl.java:499)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:369)
        at org.eclipse.e4.ui.internal.workbench.ResourceHandler.getResource(ResourceHandler.java:285)
        at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadResource(ResourceHandler.java:261)
        at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:168)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:381)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:256)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:587)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.core.resources (40).
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:557)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:39)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 26 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.core.resources.ResourcesPlugin.start() of bundle org.eclipse.core.resources.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:803)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
        at org.eclipse.osgi.container.Module.doStart(Module.java:584)
        at org.eclipse.osgi.container.Module.start(Module.java:452)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        ... 35 more
Caused by: org.eclipse.core.internal.resources.ResourceException: Incompatible file format. Workspace was saved with an incompatible version: 0.
        at org.eclipse.core.internal.resources.WorkspaceTreeReader.getReader(WorkspaceTreeReader.java:62)
        at org.eclipse.core.internal.resources.WorkspaceTreeReader.getReader(WorkspaceTreeReader.java:70)
        at org.eclipse.core.internal.resources.SaveManager.restoreTree(SaveManager.java:1042)
        at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:705)
        at org.eclipse.core.internal.resources.SaveManager.startup(SaveManager.java:1561)
        at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2451)
        at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2208)
        at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:489)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:782)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:775)
        ... 42 more
Caused by: java.lang.Exception: Incompatible file format. Workspace was saved with an incompatible version: 0.
        at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
        at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
        ... 54 more
2019-03-18 12:00:25.597 - DBeaver is stopping
2019-03-18 12:00:25.598 - Stop RMI server
2019-03-18 12:00:25.664 - < Stop org.jkiss.dbeaver.ext.mssql.ui [1.0.3.201903101945]
```

**Comment by biellls** [comment]
Fixed by deleting `%HOMEPATH%/.dbeaver/.metadata/.plugins/org.eclipse.core.resources` as specified in https://dbeaver.io/forum/viewtopic.php?f=2&t=1662. There wasn't any .snap file. It's a little annoying to lose the script associations but I guess it's Eclipse's fault and not DBeaver's.

**Comment by Vincetroid** [comment]
When open dbeaver, appeared a little screen and I would find the error on the dbeaver logs: 

**Incompatible file format. Workspace was saved with an incompatible version: 0.** 

@biellls instruction solved the issue, thanks.

**Comment by coldenol** [comment]
For me deleting the folder `org.eclipse.core.resources` did not solve the issue. If the whole folder `.plugins` is deleted then most UI settings are being reset. In my case deleting the folder `org.eclipse.e4.workbench` solved the issue and I did not lose my settings.
Just FYI.

**Comment by Alastair-L** [comment]
I had the same issue and this fixed it: https://github.com/dbeaver/dbeaver/issues/5517#issuecomment-473872921. Just wanted to add that for me that folder was instead at:
`%HOMEPATH%\AppData\Roaming\DBeaverData\workspace6\.metadata\.plugins`. Not sure if that should have been obvious but I spent some time searching for it...

**Comment by kamilkozak** [comment]
@Alastair-L You saved me day.

**Comment by ctoposup** [comment]
Fixed by deleting %HOMEPATH%/.dbeaver/.metadata/.plugins/ all files
