### ISSUE TITLE
Value panel crash

### ISSUE THREAD

**Issue by Crutchmaster** [dbeaver/dbeaver#5569]
Crash to desktop after select value linked to another table by foreign key.
Usually log is empty, but sometimes I can get error: 
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [960] [42000]: ORA-00960: ambiguous column naming in select list

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [960] [42000]: ORA-00960: ambiguous column naming in select list

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:207)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableConstraint.readKeyEnumeration(JDBCTableConstraint.java:342)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableConstraint.getKeyEnumeration(JDBCTableConstraint.java:124)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderService.evaluate(ReferenceValueEditor.java:495)
	at org.jkiss.dbeaver.ui.data.editors.ReferenceValueEditor$SelectorLoaderService.evaluate(ReferenceValueEditor.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.sql.SQLSyntaxErrorException: ORA-00960: ambiguous column naming in select list

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:260)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:204)
	... 8 more
Caused by: Error : 960, Position : 56, Sql = SELECT ID, ID FROM sometable WHERE ID >= :1  ORDER BY ID, OriginalSql = SELECT ID, ID FROM sometable WHERE ID >= ? ORDER BY ID, Error Msg = ORA-00960: ambiguous column naming in select list

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 24 more

```
Mint 17.3 x64. java version "1.8.0_151",  Oracle JDBC driver [12.2.0.1.0] DBeaver 6.0.0
In enterprise version also work.
//
Узнал, что Вы таки понимаете по русски. Так вот, чтобы не ломать Вам мозг: падает, зараза, при попытках показать данные из связанной таблицы в оракле. Если закрываешь панельку value - не падает. В логах тишина, но некоторыми телодвижениями можно вызвать исключение, что описал выше. Проявляться стало внезапно, до этого работало нормально. Грешу на старый минт и, немного, на свои кривые руки. Где хранятся конфиги, которые говорят, что использовать при показе данных из связанных таблиц? Баг у меня работает также и в интерпрайз версии.
А еще она подтормаживает (жрет cpu) в окне просмотра свойств таблицы и там нету горизонтальной прокрутки. Есть какой-нибудь гайд по коду что где искать и что как там внутри? Я бы поковырял.

**Comment by uslss** [comment]
cannot reproduce an issue against recent version.
if it is still reproducible for you - feel free to reopen the ticket
