### ISSUE TITLE
V6.0.1 on Ubuntu18.04 can't edit value by double click or Enter

### ISSUE THREAD

**Issue by MukuroSama** [dbeaver/dbeaver#5575]
Only Shift+Enter can let me to edit the value in a new window.
I have reinstalled V6.0.0

**Comment by weswaldix** [comment]
Same here on Fedora 29 with DBeaver Version: 6.0.1.201903251040. 

When I start dbeaver in the shell and then click on a field to edit, the following error message appears: 

`2019-03-26 08:40:24.015 - Event loop exception
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:928)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:207)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1758)
	at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1546)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetCellEditor.layout(SpreadsheetCellEditor.java:294)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetCellEditor.setEditor(SpreadsheetCellEditor.java:265)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.showCellEditor(Spreadsheet.java:404)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.openValueEditor(SpreadsheetPresentation.java:965)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.handleEvent(Spreadsheet.java:292)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5663)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
`

**Comment by marcgise** [comment]
Same here on Ubuntu 18.04.2 LTS

**Comment by marcgise** [comment]
The same occurs for example when adding a Filter to the connection. For instance a catalog filter in a postgresql database:
![image](https://user-images.githubusercontent.com/4680243/55007141-319a2e00-4fdf-11e9-8cb3-a8dd7e2a3699.png)

**Comment by rudmer** [comment]
on Ubuntu 18.10 the same happens when trying to fill in bind parameter: 
![image](https://user-images.githubusercontent.com/8223430/55014306-04ec1380-4feb-11e9-8b3e-1881bf065277.png)

top part stack trace:
```
2019-03-26 17:16:14.944 - Event loop exception
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:1069)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:888)
	at org.eclipse.swt.custom.ControlEditor.layout(ControlEditor.java:218)
	at org.eclipse.swt.custom.TableEditor.layout(TableEditor.java:266)
	at org.eclipse.swt.custom.ControlEditor.setEditor(ControlEditor.java:246)
```

**Comment by psygnoser** [comment]
same issue on Fedora 29 with DBeaver v6.0.1

**Comment by qgillet** [comment]
same issue on Linux Mint 19.1 with DBeaver 6.0.1

**Comment by serge-rider** [comment]
Thanks for the bug report.
Looks like all "inline" editors were broken after migrating to Eclipse 2018-12.

**Comment by serge-rider** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=542940

**Comment by serge-rider** [comment]
Please test Early Access version (https://dbeaver.io/files/ea/) - it contains fix of this issue.

**Comment by marcgise** [comment]
> Please test Early Access version (https://dbeaver.io/files/ea/) - it contains fix of this issue.

I can confirm that it works fine now, Serge. Thanks for your effort ;)

**Comment by rudmer** [comment]
I can also confirm it works again!
thanks for the quick response :tada:

**Comment by weswaldix** [comment]
Works again :) 
Thank you.

**Comment by psygnoser** [comment]
Editing works but in v6.0.2 I now have a completely different issue: 

When using a connection to MySQL without having the Database specified in the connection settings, and trying to open any table I get "SQL Error [1046] [3D000]: No database selected". It only works if I actually specify the database in the top in the "Choose catalog/schema" modal. But even then only for tables that are in that DB. So If I try to open a table in another DB I get the same error. 
Before v6.0.2 it implicitly switched the current DB depending on what table you opened.

**Comment by serge-rider** [comment]
@psygnoser thanks for the bug report. Indeed it is a completely different and related to MySQL API refactoring.

**Comment by serge-rider** [comment]
@psygnoser New EA version has been published

**Comment by psygnoser** [comment]
> @psygnoser New EA version has been published

Ok the latest build seems to have fixed the issue. Thanks.

**Comment by uslss** [comment]
verified

**Comment by nitzien** [comment]
Finding same issue on 16.04 LTS, Dbeaver 6.3.5.

![image](https://user-images.githubusercontent.com/531632/75220614-d0b63f80-57c5-11ea-8354-a7105d090651.png)
