### ISSUE TITLE
Can't connect to Pervasive 64-bit ODBC source

### ISSUE THREAD

**Issue by strider72** [dbeaver/dbeaver#5615]
I'm having an issue identical to that reported in #522 . This is especially an issue now that you've discontinued the 32-bit version of DBeaver.

32-bit DBeaver works with a 32-bit ODBC connection.  64-bit DBeaver refuses to work with 64-bit ODBC connection with error: `[PSQL][ODBC Client Interface]Parameter number out of range.`

The DB on the other end is Pervasive SQL. ODBC should not need any username/password to connect.  I tried checking "No authentication" in driver settings but it made no difference.

This source DOES successfully connect when I test it in the Windows 64-bit ODBC Connection Manager

Here is my dbeaver-debug.log :

```
2019-03-28 18:01:31.875 - DBeaver 6.0.1.201903251040 is starting
2019-03-28 18:01:31.875 - OS: Windows 10 10.0 (amd64)
2019-03-28 18:01:31.891 - Java version: 1.8.0_77 by Oracle Corporation (64bit)
2019-03-28 18:01:31.891 - Install path: 'file:/C:/Program Files/DBeaver/'
2019-03-28 18:01:31.891 - Instance path: 'file:/C:/Users/srider/.dbeaver4/'
2019-03-28 18:01:31.891 - Memory available 61Mb/910Mb
2019-03-28 18:01:31.906 - Starting RMI server at 20488
2019-03-28 18:01:31.969 - Run workbench
2019-03-28 18:01:31.969 - > Start org.eclipse.e4.ui.workbench.swt [0.14.400.v20181022-1348]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.core.services [2.1.300.v20180930-0910]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.core.contexts [1.7.100.v20180817-1215]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.ui.services [1.3.300.v20180920-1522]
2019-03-28 18:01:32.031 - > Start org.eclipse.e4.ui.di [1.2.400.v20180920-1522]
2019-03-28 18:01:32.073 - > Start com.ibm.icu.base [58.2.0.v20170418-1837]
2019-03-28 18:01:32.074 - > Start org.eclipse.emf.common [2.15.0.v20180914-1817]
2019-03-28 18:01:32.089 - > Start org.eclipse.emf.ecore [2.16.0.v20181124-0637]
2019-03-28 18:01:32.167 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-03-28 18:01:32.308 - > Start org.eclipse.core.filesystem [1.7.200.v20180828-0158]
2019-03-28 18:01:32.355 - > Start org.eclipse.core.resources [3.13.200.v20181121-1020]
2019-03-28 18:01:32.480 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.300.v20181102-1042]
2019-03-28 18:01:32.496 - > Start org.eclipse.core.expressions [3.6.200.v20180817-1401]
2019-03-28 18:01:32.527 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.400.v20181112-1716]
2019-03-28 18:01:32.621 - > Start org.eclipse.e4.ui.bindings [0.12.300.v20180913-1535]
2019-03-28 18:01:32.667 - > Start org.eclipse.e4.core.di.extensions [0.15.200.v20180817-1215]
2019-03-28 18:01:32.983 - > Start org.eclipse.e4.ui.css.swt [0.13.300.v20181030-1443]
2019-03-28 18:01:33.057 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.100.v20180828-0227]
2019-03-28 18:01:33.791 - Initializing DBeaver 6.0.1
2019-03-28 18:01:33.791 - Host plugin: org.jkiss.dbeaver.core.application 6.0.1.201903251040
2019-03-28 18:01:33.791 - Initialize Core...
2019-03-28 18:01:33.791 - Can't find BC security provider. Use default JCE.
2019-03-28 18:01:33.791 - BouncyCastle not registered, using the default JCE provider
2019-03-28 18:01:33.900 - > Start org.eclipse.team.core [3.8.400.v20181109-0825]
2019-03-28 18:01:33.916 - > Start org.jkiss.dbeaver.ui.navigator [1.0.5.201903251040]
2019-03-28 18:01:34.010 - Total database drivers: 71 (71)
2019-03-28 18:01:34.025 - > Start org.eclipse.equinox.security [1.3.0.v20181115-0746]
2019-03-28 18:01:34.041 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-03-28 18:01:34.041 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-03-28 18:01:34.041 - Core initialized (250ms)
2019-03-28 18:01:34.041 - Configure workbench window
2019-03-28 18:01:34.041 - > Start org.eclipse.core.net [1.3.400.v20181030-1645]
2019-03-28 18:01:34.057 - > Start org.eclipse.help [3.8.200.v20180821-0700]
2019-03-28 18:01:34.088 - Create actions
2019-03-28 18:01:34.088 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-03-28 18:01:34.104 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-03-28 18:01:34.135 - > Start org.eclipse.ui.editors [3.11.300.v20180914-0606]
2019-03-28 18:01:34.135 - > Start org.eclipse.core.filebuffers [3.6.400.v20181028-0633]
2019-03-28 18:01:34.603 - > Start org.eclipse.search [3.11.400.v20181028-0633]
2019-03-28 18:01:34.619 - > Start org.eclipse.ui.workbench.texteditor [3.11.200.v20181108-1458]
2019-03-28 18:01:34.641 - Initialize workbench window
2019-03-28 18:01:34.641 - Finish initialization
2019-03-28 18:01:34.672 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.5.201903251040]
2019-03-28 18:01:34.782 - > Start org.jkiss.dbeaver.ext.erd [2.0.107.201903251040]
2019-03-28 18:01:34.875 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.5.201903251040]
2019-03-28 18:01:35.657 - > Start org.eclipse.equinox.p2.core [2.5.100.v20180822-1532]
2019-03-28 18:01:35.672 - > Start org.eclipse.equinox.p2.operations [2.5.200.v20180928-1359]
2019-03-28 18:01:35.688 - > Start org.eclipse.equinox.p2.engine [2.6.100.v20180822-1302]
2019-03-28 18:01:35.688 - > Start org.eclipse.equinox.p2.metadata [2.4.200.v20181102-0649]
2019-03-28 18:01:35.703 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.200.v20181102-0649]
2019-03-28 18:01:35.703 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-03-28 18:01:35.719 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-03-28 18:01:35.719 - > Start org.eclipse.equinox.p2.repository [2.4.200.v20181005-1131]
2019-03-28 18:01:35.750 - > Start org.jkiss.dbeaver.ui.editors.data [1.0.5.201903251040]
2019-03-28 18:01:35.844 - > Start org.eclipse.equinox.p2.ui [2.5.400.v20181113-1303]
2019-03-28 18:01:35.907 - > Start org.jkiss.dbeaver.ext.sample.database [1.0.42.201903251040]
2019-03-28 18:01:35.907 - > Start org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.11.201903251040]
2019-03-28 18:01:42.622 - > Start org.jkiss.dbeaver.ext.generic [2.3.91.201903251040]
2019-03-28 18:01:49.375 - Connect with 'jdbc:odbc:FOSDATA' (odbc-169c689bcaf-601dcda38da69361)
2019-03-28 18:01:49.515 - Connection failed (odbc-169c689bcaf-601dcda38da69361)
2019-03-28 18:01:49.515 - org.jkiss.dbeaver.model.exec.DBCConnectException: [PSQL][ODBC Client Interface]Parameter number out of range.
org.jkiss.dbeaver.model.exec.DBCConnectException: [PSQL][ODBC Client Interface]Parameter number out of range.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:67)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:232)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [PSQL][ODBC Client Interface]Parameter number out of range.
	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6964)
	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
	at sun.jdbc.odbc.JdbcOdbc.SQLGetDataInteger(JdbcOdbc.java:3818)
	at sun.jdbc.odbc.JdbcOdbcResultSet.getDataInteger(JdbcOdbcResultSet.java:5637)
	at sun.jdbc.odbc.JdbcOdbcResultSet.getInt(JdbcOdbcResultSet.java:582)
	at sun.jdbc.odbc.JdbcOdbcConnection.buildTypeInfo(JdbcOdbcConnection.java:1513)
	at sun.jdbc.odbc.JdbcOdbcConnection.initialize(JdbcOdbcConnection.java:381)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:174)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 13 more
2019-03-28 18:01:58.835 - DBeaver is stopping
2019-03-28 18:01:58.835 - Stop RMI server
```

**Comment by Lonniebiz** [comment]
I've been having to use the 32 bit version of Dbeaver ever since I reported #522 .

I too noticed today that version 6.0 will be the last version of Dbeaver offered in 32bit.

I never wanted to use 32bit and have always wanted to use the 64bit version, but I can't until I figure out a way around issue #522 .

**Comment by strider72** [comment]
In the original issue use @serge-rider passingly mentioned to use JDBC instead, but gave no clue as to how to do that.  When I create a new connection in DBeaver, the list of Database types does not include JDBC.

> By the way, why are you trying to use ODBC driver + bridge? Pervasive has JDBC driver, which is much more native for DBeaver.
> Just tested it and at least it doesn't have connectivity problems.

Perhaps this is the way to go, but how do I do it??

**Comment by Lonniebiz** [comment]
I don't know. I always have trouble setting up those types of things. When I get it working, I just use the same thing until it stops working. For example, I'd really like to use Pervasive Database with Node.js on a Linux Server, but I can't figure out how to get the database driver working. Database drivers eat my lunch.

**Comment by strider72** [comment]
One way or the other, the 32-bit DBeaver can do it, and the 64-bit DBeaver can't.  That tells me that on some level there's an issue with 64-bit DBeaver.

For that matter, my PHP project is using ODBC to connect to the same database, and it's slow as anything. If there's a faster way via JDBC, I'd love to see it.  (I use DBeaver to write and test my queries, and view the DB, and then actually use the queries in a PHP web site.)

**Comment by Lonniebiz** [comment]
@strider72 Send me an email at lonniebest (@) startport.com

I'll delete this message soon, but I'd like to have your contact info; we have a lot in common and I suspect we'll be able to help each other. I've written a lot of queries for pervasive. I'd like to know more about your project and the business system you work with using Pervasive.

**Comment by serge-rider** [comment]
I think that the problem is in outdated ODBC-JDBC bridge driver (which we took from Java7 package).

But as far as I see there IS JDBC driver for Pervasive: (https://docs.actian.com/psql/PSQLv11/jdbc/wwhelp/wwhimpl/common/html/wwhelp.htm#href=jdbc_gd.1.3.html&single=true)
There is a bunch of different articles about it on the net. However I'm not sure how to obtain the driver itself, most likely it is included in the product distribution (which is now named PSQL?).

Anyhow, if you could test this - please do. We'll include Pervasive driver configuration in the default DBeaver distribution if it will work.

@Lonniebiz thanks :)

**Comment by strider72** [comment]
@lonniebiz check this out

https://stackoverflow.com/q/55408891/339440

**Comment by strider72** [comment]
@serge-rider not at my computer but appears to be a typo in commit:  “pervasice”

I’ll try this Monday when I’m back at work. (I tried to look for those articles you mention but I guess my google-foo failed me)

**Comment by strider72** [comment]
The following worked for me!
![Pervasive JDBC connection](https://user-images.githubusercontent.com/786481/55340468-5fadc100-546a-11e9-89d3-2758ef2e3c46.png)

**Comment by strider72** [comment]
Note: On some systems (older installs?) the path to the drivers is `C:\Program Files (x86)\Pervasive Software\PSQL\bin\`.  Note "Pervasive Software", rather than "Actian"

**Comment by Lonniebiz** [comment]
@strider72  Ok, I'm going to try to do this from scratch. What did you choose on the first step? Pervasive is not listed; I see OCBC, but not JDBC.

![Screenshot](https://i.imgur.com/BUNJYz3.png)

**Comment by Lonniebiz** [comment]
@strider72  Wow! Many Thanks. I got it working now too.

I just chose ODBC on that first step then I edited the driver details to be like your screenshots. I added the same 3 files you did located here:
![files](https://i.imgur.com/pl9TZIH.png)

**Comment by strider72** [comment]
I didn't select one. I went to Database >Driver Manager and clicked "New"

**Comment by serge-rider** [comment]
@Lonniebiz driver configuration will be added in 6.0.2.

**Comment by uslss** [comment]
Driver is added.
Closed without testing

**Comment by strider72** [comment]
Just for the record: The built-in configuration added in 6.0.2 does NOT work for me, but the custom config described in this thread still works fine.  Possibly because the application we have uses Pervasive 11, but I have no way to test this.

**Comment by Lonniebiz** [comment]
After installing Dbeaver onto Kubuntu 20.04, I tried to connect to a Pervasive 13 database, but Dbeaver didn't offer the ability to automatically download the driver.

Ultimately, I found the driver here:
https://dbschema.com/jdbc-driver/Pervasive.html

I post this only because I hope you can make that driver available for auto-download when someone else sets up a Pervasive DB connection for the first time. These drivers on sometimes difficult to find and auto-providing this will ease the burden on the next guy.

There may be a more authoritative place where this driver file is hosted, but the link above is where I got it, and so far it is working flawlessly.
