### ISSUE TITLE
Spreadsheet (Grid) display

### ISSUE THREAD

**Issue by hAzUpL8** [dbeaver/dbeaver#5679]
Hi 
In latest update of DBeaver eclipse plugin query results in Grid does't display any more. Only query results in formatted text works.

Version of eclipse is:
Eclipse Platform
Version: 4.6.3.v20170301-0400
Build id: M20170301-0400

DBeaver Core: 6.0.2.201904071344
DBeaver Runtime: 6.0.2.201904071344
![dbeaver](https://user-images.githubusercontent.com/33866210/55716408-2e4b6d00-59f7-11e9-92f4-cf9b2d0b9df7.jpg)

**Comment by danieletas** [comment]
Exactly the same issue for me working on H2 DB and impossible to insert data
Eclipse Java EE IDE for Web Developers.

Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
DBeaver Core: 6.0.2.201904071344
DBeaver Runitme: 6.0.2.201904071344

**Comment by danieletas** [comment]
More details to investigate from WorkSpce Log each time i try to open Data Tab on any table
java.lang.NoSuchMethodError: org.eclipse.swt.graphics.FontMetrics.getAverageCharacterWidth()D
	at org.jkiss.dbeaver.ui.TextUtils.getShortString(TextUtils.java:127)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridRowRenderer.paint(GridRowRenderer.java:113)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onPaint(LightGrid.java:2229)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:231)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1570)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4900)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by serge-rider** [comment]
This happens only with older versions of Eclipse (for now it works with Eclipse 2018-09 or later). Will fix this in the next version.

Thanks for the bug report.

**Comment by uslss** [comment]
closed without tests
