### ISSUE TITLE
Sphinx support

### ISSUE THREAD

**Issue by miniBill** [dbeaver/dbeaver#5687]
#### System information: 
- Operating system (distribution) and version: irrelevant (Windows)
- DBeaver version: 6.0.2
- Java version: irrelevant (1.8.0_77)
- Additional extensions: none

#### Connection specification:
- Database name and version: Sphinx 3.1.1
- Driver name: MariaDB (MySQL just fails on connection saying CLIENT_PLUGIN_AUTH is required)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Upon expanding the connection tree the following error is emitted:

    sphinxql: syntax error, unexpected IN, expecting '=' near 'in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')'
    Query is : SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')

#### Steps to reproduce, if exist:
Create a new connection to a Sphinx FTSE.

#### Include any warning/errors/backtraces from the logs
Irrelevant

#### Possible solutions
While of course specializing the driver for Sphinx would be cleanest it would be a lot of work.
Something much simpler might be to run the query:

    show variables where variable_name = 'storage_engine'

If it returns a single result then it's maria/mysql, if it returns multiple results it's something else (in this case, sphinx).

Other differences are:
* Sphinx has no databases, just "tables" (actually, indexes)
* The DESCRIBE output columns are different from an actual mysql/mariadb instance (sphinx provides Field, Type, Properties and Key instead of Field, Type, Null, Key, Default and Extra)

**Comment by serge-rider** [comment]
Could you post error/debug log?  DBeaver doesn't execute such queries, this looks like internal driver issue..

**Comment by miniBill** [comment]
Relevant log lines:
```
2019-04-10 10:07:57.690 - Connect with 'XXX' (mariaDB-16a019059ac-670742b6661271f5)
2019-04-10 10:07:57.697 - > Start org.jkiss.dbeaver.ext.mysql [2.1.91.201904071344]
2019-04-10 10:07:58.531 - Connection failed (mariaDB-16a019059ac-670742b6661271f5)
2019-04-10 10:07:58.531 - org.jkiss.dbeaver.model.exec.DBCConnectException: sphinxql: syntax error, unexpected IN, expecting '=' near 'in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')'
Query is : SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')
org.jkiss.dbeaver.model.exec.DBCConnectException: sphinxql: syntax error, unexpected IN, expecting '=' near 'in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')'
Query is : SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:408)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:80)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:126)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:108)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:68)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:204)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: sphinxql: syntax error, unexpected IN, expecting '=' near 'in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')'
Query is : SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:134)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91)
	at org.mariadb.jdbc.Driver.connect(Driver.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 24 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: sphinxql: syntax error, unexpected IN, expecting '=' near 'in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')'
Query is : SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet', 'system_time_zone', 'time_zone', 'sql_mode')
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:137)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.loadServerData(AbstractConnectProtocol.java:669)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:402)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
	... 26 more
```

**Comment by serge-rider** [comment]
Yes, it is internal error of MariaDB driver.
You could try to use regular MySQL driver (not MySQL 8+) or MySQL 3.x driver.
