### ISSUE TITLE
Cannot connect to Apache Ignite: Missing 

### ISSUE THREAD

**Issue by alfredopalhares** [dbeaver/dbeaver#5738]
#### System information: 
- **Operating system:** Arch Linux (up to date)
- **DBeaver version**: 6.0.1.201903291936
- java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+4)
OpenJDK 64-Bit Server VM (build 11.0.3+4, mixed mode)

#### Connection specification:
- **Database:** Apache Ignite 2.7.0
Driver details: 
![Screenshot from 2019-04-15 17-41-23](https://user-images.githubusercontent.com/223763/56193359-5c990000-6028-11e9-9e42-b685bade36c8.png)
- Do you use tunnels or proxies: No

#### Describe the problem you're observing:
I cannot connect to the server, i get this error:
```
Can't create driver instance
  Error creating driver 'Apache Ignite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.ignite.IgniteJdbcThinDriver'
  Error creating driver 'Apache Ignite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.ignite.IgniteJdbcThinDriver'
    
    java.lang.ExceptionInInitializerError
      jdk.internal.misc.JavaNioAccess class is unavailable.
      jdk.internal.misc.JavaNioAccess class is unavailable.
        class org.apache.ignite.internal.util.GridUnsafe cannot access class jdk.internal.misc.SharedSecrets (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @1c027a51
        class org.apache.ignite.internal.util.GridUnsafe cannot access class jdk.internal.misc.SharedSecrets (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @1c027a51
```
#### Steps to reproduce, if exist:

Just connect to the server

#### Include any warning/errors/backtraces from the logs

From `.dbeaver/.metadata/dbeaver-debug.log`:
```
2019-04-16 09:20:01.707 - Connect with 'Apache Ignite - 10.0.14.79' (apache_ignite-16a21c91ffb-4f8e3ce088abcda1)
2019-04-16 09:20:01.829 - Connection failed (apache_ignite-16a21c91ffb-4f8e3ce088abcda1)
2019-04-16 09:20:01.829 - org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:117)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
        at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:67)
        at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:95)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:108)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:665)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:147)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:204)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Error creating driver 'Apache Ignite' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.apache.ignite.IgniteJdbcThinDriver'
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:872)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:850)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.getDriverInstance(DriverDescriptor.java:530)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.getDriverInstance(JDBCDataSource.java:607)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:115)
        ... 23 more
Caused by: java.lang.ExceptionInInitializerError
        at org.apache.ignite.internal.util.IgniteUtils.<clinit>(IgniteUtils.java:795)
        at org.apache.ignite.lang.IgniteProductVersion.fromString(IgniteProductVersion.java:305)
        at org.apache.ignite.internal.IgniteVersionUtils.<clinit>(IgniteVersionUtils.java:71)
        at org.apache.ignite.IgniteJdbcThinDriver.<clinit>(IgniteJdbcThinDriver.java:141)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.jkiss.dbeaver.registry.driver.DriverDescriptor.loadDriver(DriverDescriptor.java:870)
        ... 27 more
Caused by: java.lang.RuntimeException: jdk.internal.misc.JavaNioAccess class is unavailable.
        at org.apache.ignite.internal.util.GridUnsafe.javaNioAccessObject(GridUnsafe.java:1453)
        at org.apache.ignite.internal.util.GridUnsafe.<clinit>(GridUnsafe.java:112)
        ... 34 more
Caused by: java.lang.IllegalAccessException: class org.apache.ignite.internal.util.GridUnsafe cannot access class jdk.internal.misc.SharedSecrets (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @1c027a51
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
        at java.base/java.lang.reflect.Method.invoke(Method.java:558)
        at org.apache.ignite.internal.util.GridUnsafe.javaNioAccessObject(GridUnsafe.java:1450)
        ... 35 more
```

Yet, a quick look arount it proves that files are there:
```
-> % tree .dbeaver-drivers
.dbeaver-drivers
└── maven
    └── maven-central
        ├── javax.cache
        │   └── cache-api-1.0.0.jar
        ├── org.apache.ignite
        │   └── ignite-core-2.7.0.jar
        ├── org.gridgain
        │   └── ignite-shmem-1.0.0.jar
        └── org.jetbrains
            └── annotations-13.0.jar

6 directories, 4 files
```

Any help would be aprecciated.

Regards,
Alfredo Palhares

**Comment by serge-rider** [comment]
Looks like some issue with your local JDK.
Could you try to add following lines in the `dbeaver.ini` file (after --add-modules parameter):
```
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED 
```

**Comment by yanqingkai** [comment]
@alfredopalhares have you fix this? It appear again to me

**Comment by rob-64** [comment]
getting it too.. 

windows 10
oracle jdk 8

**Comment by ctrongduc** [comment]
I got the same issue and followed @serge-rider helps. Thank you!

**Comment by iliadmitriev** [comment]
Got the same issue on my MacOS Monterrey with `DBeaver 22.1.2`

adding line:
```ini
--add-opens=java.base/java.nio=ALL-UNNAMED
```
to `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`

worked for me

**Comment by hasanunlukilinc** [comment]
> Got the same issue on my MacOS Monterrey with `DBeaver 22.1.2`
> 
> adding line:
> 
> ```ini
> --add-opens=java.base/java.nio=ALL-UNNAMED
> ```
> 
> to `/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini`
> 
> worked for me

It worked for me also Macos Monteray 12.6 and Dbeaver Version 22.2.1.202209251341
