### ISSUE TITLE
Active Directory MSI Authentication

### ISSUE THREAD

**Issue by dam1960** [dbeaver/dbeaver#5740]
#### System information: 
Xubuntu 18.04 LTS
DBeaver version  6.0.2
Java Version 1.8.0_144

#### Connection specification:
MSSQL
com.microsoft.sqlserver.jdbc.SQLServerDriver

- Do you use tunnels or proxies (SSH, SOCKS, etc)? no 

#### Describe the problem you're observing:
Trying to connect with Active Directory MSI Authentication throws error

#### Steps to reproduce, if exist:
Create new connection and choose Active Directory MSI Authentication for authentication

#### Include any warning/errors/backtraces from the logs
2019-04-16 11:32:26.181 - Connection failed (microsoft-16a27350053-3f06f43afc557d8)
2019-04-16 11:32:26.182 - org.jkiss.dbeaver.model.exec.DBCConnectException: The authentication value "ActiveDirectoryMSI" is not valid.
org.jkiss.dbeaver.model.exec.DBCConnectException: The authentication value "ActiveDirectoryMSI" is not valid.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:65)
	at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:128)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:237)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The authentication value "ActiveDirectoryMSI" is not valid.
	at com.microsoft.sqlserver.jdbc.SqlAuthentication.valueOfString(SQLServerDriver.java:86)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1530)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1120)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:700)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)

**Comment by serge-rider** [comment]
In order to use MSI authentication you have to have SQL Server driver 7.2+.
You can update driver in driver edit dialog->Download/Update->
![image](https://user-images.githubusercontent.com/6398845/56303405-821b2c00-6144-11e9-951b-2c859eba9334.png)

**Comment by dam1960** [comment]
Thanks.
