### ISSUE TITLE
Data view does not display 'bit' values correctly.

### ISSUE THREAD

**Issue by rkubes** [dbeaver/dbeaver#5755]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.2 LTS
- DBeaver version: 6.0.2
- Java version: openjdk 11.0.2 2019-01-15

#### Connection specification:
- Database version: mysql  Ver 15.1 Distrib 10.1.37-MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
There is a column with data type BIT(7), but the data view fails to display correctly.

#### Steps to reproduce, if exist:
Create a table with a column of data type BIT(7).
Add a row with value "127" (0b1111111)
Add a row with value "7" (0b0000111)

Open the table in DBeaver.
First row shows value: b'1001111'  (instead of b'1111111')
Second row shows an error instead of any value.

Confirm values are correct in DB:
SELECT CAST(days_of_week AS UNSIGNED) AS dow FROM the_table;
Result set row 1 has value "127" (as expected)
Result set row 2 has value "7" (as expected)

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 2 0 2019-04-18 17:46:13.529
!MESSAGE Can't read column 'days_of_week' value
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-04-18 17:46:13.529
!MESSAGE SQL Error [1264] [22003]: Out of range value for column 'days_of_week' : value  is not in Long range
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2019-04-18 17:46:13.529
!MESSAGE Out of range value for column 'days_of_week' : value  is not in Long range
!STACK 0
java.sql.SQLException: Out of range value for column 'days_of_week' : value  is not in Long range
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.parseLong(MariaSelectResultSet.java:3279)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getLong(MariaSelectResultSet.java:1064)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getLong(MariaSelectResultSet.java:1048)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getLong(JDBCResultSetImpl.java:386)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:144)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:207)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
````

**Comment by rkubes** [comment]
I see this was labeled as "can't reproduce"

Here is another, more thorough example. I can reproduce this 100% of the time. When it shows the value in the "bit" form, I would expect 127 to equal '1111111'. You can see when I cast the column to INT, it shows the correct value 127.

Any bit-wise logic on the value works correctly, because it is actually stored in the DB as 127 (b'1111111'). It's just a display issue in DBeaver (apparently on my system) that it displays the wrong bit value. I'm not sure if there's anything else I can provide for further review.

```
> SHOW COLUMNS FROM switch_events;

Field         |Type            |Null|Key|Default   |Extra|
--------------|----------------|----|---|----------|-----|
switch_id     |int(11)         |NO  |PRI|          |     |
at_time       |time            |NO  |PRI|          |     |
value         |tinyint(1)      |NO  |   |          |     |
skip_init     |tinyint(1)      |YES |   |          |     |
start_date    |date            |NO  |   |          |     |
end_date      |date            |YES |   |          |     |
event_interval|int(10) unsigned|NO  |   |          |     |
days_of_week  |bit(7)          |NO  |   |b'1111111'|     |
```
```
> SELECT *, CAST(days_of_week AS INT) AS 'int_days_of_week' FROM switch_events;

switch_id|at_time |value|skip_init|start_date|end_date|event_interval|days_of_week|int_days_of_week|
---------|--------|-----|---------|----------|--------|--------------|------------|----------------|
        1|01:00:00|    0|         |2019-04-18|        |             1|     1001111|             127|
        1|13:00:00|    1|         |2019-04-18|        |             1|     1001111|             127|
        2|00:58:00|    1|         |2019-04-18|        |             1|     1001111|             127|
        2|13:02:00|    0|         |2019-04-18|        |             1|     1001111|             127|
        3|00:00:00|    0|         |2019-04-18|        |             1|     1001111|             127|
        3|14:00:00|    1|         |2019-04-18|        |             1|     1001111|             127|
```

**Comment by uslss** [comment]
hi @rkubes , sorry for the late response.
unfortunately, the issue is still not reproducible for me against recent version of dbeaver.
is it still actual for you?

**Comment by uslss** [comment]
there is no updates for a month. ticket closed
