### ISSUE TITLE
Error appears when trying to create db trigger

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5764]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.0.3

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Error appears when trying to create db trigger
![image](https://user-images.githubusercontent.com/31996417/56461781-f2ce7c80-63c0-11e9-9daf-fa01147ff8f9.png)

#### Include any warning/errors/backtraces from the logs
`eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sat Apr 20 23:06:21 MSK 2019
Can't create object here.
Wrong container type: MySQLCatalog

java.lang.IllegalArgumentException: Can't create object here.
Wrong container type: MySQLCatalog
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:85)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:1)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:293)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

`

**Comment by uslss** [comment]
verified
