### ISSUE TITLE
v6.0.3 Redshift Spectrum queries not returning results

### ISSUE THREAD

**Issue by toddljones** [dbeaver/dbeaver#5771]
#### System information: 
- OS: CentOS Linux release 7.5.1804 (Core)
- DBeaver version: 6.0.3
- Java version: 
```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```
- Additional extensions: vrapper

#### Connection specification:
- Database name and version: Redshift/PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.7078
- Driver name: com.amazon.redshift:redshift-jdbc42/1.2.20.1043
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
- Some Redshift Spectrum queries not returning results
- Also, the ctrl-enter shortcut would no longer run queries

#### Steps to reproduce, if exist:
- Run multiple queries, notice that subsequent queries do not return results

#### Include any warning/errors/backtraces from the logs
- From $HOME/.dbeaver4/.metadata/dbeaver-debug.log
```
Apr 22, 2019 11:19:03 AM org.apache.commons.jexl2.JexlEngine invocationFailed
WARNING: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![8,28]: 'context.supportsAttributes();' method invocation error
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.getDataKind(PostgreAttribute.java:190)
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingMeta.getDataKind(DBDAttributeBindingMeta.java:125)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetContextImpl.supportsAttributes(ResultSetContextImpl.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.jexl2.internal.MethodExecutor.execute(MethodExecutor.java:64)
	at org.apache.commons.jexl2.internal.AbstractExecutor$Method.invoke(AbstractExecutor.java:327)
	at org.apache.commons.jexl2.Interpreter.call(Interpreter.java:1068)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1100)
	at org.apache.commons.jexl2.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1317)
	at org.apache.commons.jexl2.parser.ASTReference.jjtAccept(ASTReference.java:18)
	at org.apache.commons.jexl2.Interpreter.interpret(Interpreter.java:232)
	at org.apache.commons.jexl2.ExpressionImpl.evaluate(ExpressionImpl.java:65)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.appliesTo(AbstractDescriptor.java:176)
	at org.jkiss.dbeaver.model.impl.AbstractContextDescriptor.appliesTo(AbstractContextDescriptor.java:73)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPresentationDescriptor.supportedBy(ResultSetPresentationDescriptor.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPresentationRegistry.getAvailablePresentations(ResultSetPresentationRegistry.java:103)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:553)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataReceiver.java:179)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4582)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:187)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

Apr 22, 2019 11:19:03 AM org.apache.commons.jexl2.JexlEngine invocationFailed
WARNING: org.jkiss.dbeaver.model.impl.AbstractDescriptor.parseExpression@58![8,28]: 'context.supportsAttributes();' method invocation error
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.getDataKind(PostgreAttribute.java:190)
	at org.jkiss.dbeaver.model.data.DBDAttributeBindingMeta.getDataKind(DBDAttributeBindingMeta.java:125)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetContextImpl.supportsAttributes(ResultSetContextImpl.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.jexl2.internal.MethodExecutor.execute(MethodExecutor.java:64)
	at org.apache.commons.jexl2.internal.AbstractExecutor$Method.invoke(AbstractExecutor.java:327)
	at org.apache.commons.jexl2.Interpreter.call(Interpreter.java:1068)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1100)
	at org.apache.commons.jexl2.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18)
	at org.apache.commons.jexl2.Interpreter.visit(Interpreter.java:1317)
	at org.apache.commons.jexl2.parser.ASTReference.jjtAccept(ASTReference.java:18)
	at org.apache.commons.jexl2.Interpreter.interpret(Interpreter.java:232)
	at org.apache.commons.jexl2.ExpressionImpl.evaluate(ExpressionImpl.java:65)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.appliesTo(AbstractDescriptor.java:176)
	at org.jkiss.dbeaver.model.impl.AbstractContextDescriptor.appliesTo(AbstractContextDescriptor.java:73)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPresentationDescriptor.supportedBy(ResultSetPresentationDescriptor.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPresentationRegistry.getAvailablePresentations(ResultSetPresentationRegistry.java:103)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:553)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataReceiver.java:179)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4582)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:187)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

```

**Comment by serge-rider** [comment]
Thanks for the bug report.
Could you test the fix in the Early Access version? (https://dbeaver.io/files/ea)

**Comment by toddljones** [comment]
Thanks for the quick reply. But I forgot to test this today. Will test it out tomorrow.

**Comment by toddljones** [comment]
@serge-rider -- I was able to run quite a few queries this morning with success. I will keep using the Early Access version today and let you know if I encounter other issues. FWIW I am using 6.0.3.201904221816. Thanks for all your help.

**Comment by serge-rider** [comment]
Thanks for testing

**Comment by uslss** [comment]
verified
