### ISSUE TITLE
Variable of variable

### ISSUE THREAD

**Issue by ramunozp** [dbeaver/dbeaver#5788]
#### System information: 
- Operating system (distribution) and version: OSX 10.14.4
- DBeaver version: 6.0.3
- Java version : jdk 8
- Additional extensions: none

#### Connection specification:
- Database name and version: ibm as400
- Driver name: JT400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : none

#### Describe the problem you're observing:
What I want is to define one variable of another, to have a numeric and another character for the like

#### Steps to reproduce, if exist:
```
@set OC = 11223355
@set sOC = CONCAT('%',CONCAT(CAST(:OC, char(10),'%'))
```
**SQL:**
`SELECT * FROM <TABLE> WHERE <ATTRIBUTE> LIKE :sOC;`

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42618]: [SQL0312] Variable OC no definida o no utilizable.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2720)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0312] Variable OC no definida o no utilizable.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:891)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:692)
	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1836)
	at com.ibm.as400.access.AS400JDBCStatement.execute(AS400JDBCStatement.java:2032)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 11 more

**Comment by JMarkMurphy** [comment]
`@set sOC = CONCAT('%',CONCAT(CAST(:OC, char(10),'%'))`

should be

`@set sOC = CONCAT('%',CONCAT(CAST(:OC, char(10)),'%'))`

**Comment by ramunozp** [comment]
sigue el error:

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42618]: [SQL0312] Variable OC no definida o no utilizable.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2720)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0312] Variable OC no definida o no utilizable.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:891)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:692)
	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1836)
	at com.ibm.as400.access.AS400JDBCStatement.execute(AS400JDBCStatement.java:2032)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 11 more
```

**Comment by ramunozp** [comment]
...

**Comment by uslss** [comment]
If issue is still reproducible, feel free to reopen the ticket
