### ISSUE TITLE
Cannot export resultset after upgrade to 6.0.3 (osx)

### ISSUE THREAD

**Issue by nhblock** [dbeaver/dbeaver#5822]
**System information:**

- Operating system (distribution) and version: OSX Sierra 10.12.6
- DBeaver version: 6.0.3

**Describe the problem you're observing:**
Previously I could right-click in the query results table and a dialog box appears allowing me to export the resultset to CSV. After upgrading to 6.0.3, no dialog box appears and I can't locate another way to export.

**Steps to reproduce**
Perform a query and right click inside results window.

**Comment by serge-rider** [comment]
Nothing was changed in data export in 6.0.3.
Please check Error Log view for any related error/warnings (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by nhblock** [comment]
I closed and restarted DBeaver and the issue resolved.

For posterity, here are the errors generated when I right clicked and the context menu was not generating:

`!ENTRY org.jkiss.dbeaver.model 4 0 2019-04-30 09:26:14.337
!MESSAGE Can't determine object class 'com.vividsolutions.jts.geom.Geometry'
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-04-30 09:26:14.337
!MESSAGE Could not create bundle file.
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-04-30 09:26:14.337
!MESSAGE The file "/Applications/DBeaver.app/Contents/Eclipse/plugins/org.jkiss.dbeaver.data.gis.view_1.0.1.201904071344.jar" does not exist
!STACK 0
java.io.IOException: The file "/Applications/DBeaver.app/Contents/Eclipse/plugins/org.jkiss.dbeaver.data.gis.view_1.0.1.201904071344.jar" does not exist
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.<init>(ZipBundleFile.java:70)
	at org.eclipse.osgi.storage.Storage.createBundleFile(Storage.java:1083)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getBundleFile(BundleInfo.java:104)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.addStandardClassPathEntry(ClasspathManager.java:210)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.addClassPathEntry(ClasspathManager.java:205)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:188)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:167)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:96)
	at org.eclipse.osgi.internal.loader.EquinoxClassLoader.<init>(EquinoxClassLoader.java:46)
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:343)
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:260)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:643)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$1.run(EquinoxBundle.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getModuleClassLoader(EquinoxBundle.java:636)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:608)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor.getObjectClass(AbstractDescriptor.java:309)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor.getObjectClass(AbstractDescriptor.java:302)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.getObjectClass(AbstractDescriptor.java:153)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.getObjectClass(AbstractDescriptor.java:144)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.matchesType(AbstractDescriptor.java:208)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerDescriptor.supportsType(ValueManagerDescriptor.java:143)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findManager(ValueManagerRegistry.java:89)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.getManager(ValueManagerRegistry.java:73)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findValueManager(ValueManagerRegistry.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetValueController.getValueManager(ResultSetValueController.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.fillContextMenu(ResultSetViewer.java:2056)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.fillContextMenu(SpreadsheetPresentation.java:773)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.Spreadsheet.lambda$2(Spreadsheet.java:334)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:342)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:473)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:468)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:500)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1516)
	at org.eclipse.swt.widgets.Menu.menuWillOpen(Menu.java:808)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6142)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSMenu.popUpContextMenu(NSMenu.java:80)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:270)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:4227)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:184)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)`
