### ISSUE TITLE
Problem azure ms sql after update

### ISSUE THREAD

**Issue by aobotelho** [dbeaver/dbeaver#5825]
Hello,

I'm having a problem after I updated DBeaver to version 6.0.3 (previously using 5.2)
Now all my queries using both "MS SQL Server / Azure SQL Server" or "MS SQL Server / SQL Server" drivers fail UNLESS i put "top N" on it, i.e. "select top 10 * from tableName" works but "select * from tableName" does not.

I have to use "MS SQL Server / SQL Server (Old driver, MS)"  in order for my queries to work

The error message:
_org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [46706] [S0001]: Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2720)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cursor support is not an implemented feature for SQL Server Parallel DataWarehousing TDS endpoint.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteCursored(SQLServerStatement.java:2000)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:835)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:759)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:739)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 11 more_

**Comment by serge-rider** [comment]
This is quite strange.
In 6.x versions we add implicit TOP N clause to all SELECT queries DBeaver executes. So you `SELECT * from table` will be converted to `select top n * from table` automatically. Unless query already have TOP N or it is not a SELECT query.

So I think that TOP N conversion somehow breaks the query. Could you open Query Manager view and see what exactly query was executed by DBeaver? Maybe this will give some hint and we'll be able to solve this.

Anyhow, you can disable this behavior in preferences:
![image](https://user-images.githubusercontent.com/6398845/56967960-eb4e6680-6b6a-11e9-8d55-d8201e724837.png)
