### ISSUE TITLE
[DB2/i] Schema filter in connection-configuration is not working anymore since 6.0.2

### ISSUE THREAD

**Issue by JanDuo** [dbeaver/dbeaver#5830]
#### System information: 
- Windows 7
- DBeaver 6.0.2 and 6.0.3
- Java (included JRE)

#### Connection specification:
- DB2 for i V7R3
- jt400.jar
- No tunnels or proxies used 

#### Describe the problem you're observing:
I've installed version 6.0.2 over 6.0.1. When I open a connection created under 6.0.1 all my predefined schema's seem to be missing. Under the connection-name I see in Projects "Tables, Views, Indexes, Procedures and Data Types" where I expected to see my schema names and under each schema this Tables, Views...
Going to the Connection-configuration-General-schema's/users I still see my predefined set of schema's, but this filter does not seem to be working anymore.
So I've installed 6.0.1 again after which I got my schema's back.
Next attempt was to see if this was solved in 6.0.3. Unfortunately the issue is still there. Schema names are included in the filter, but they won't show up in de Projects tab.

#### Steps to reproduce, if exist:
Install 6.0.1 define connection with a filter on schema.
Update to 6.0.2 (or 6.0.3) and sign on. Schema missing in Projects tab.
Install 6.0.1 again: schema name is back.

#### Include any warning/errors/backtraces from the logs
2019-05-01 08:27:54.069 - Connect with 'DB2 - GP9 GAT' (db2_iseries-16928ae13c7-6871d94535926867)
2019-05-01 08:27:54.209 - > Start org.jkiss.dbeaver.ext.generic [2.3.93.201904211926]
2019-05-01 08:27:54.256 - > Start org.eclipse.equinox.p2.ui [2.5.500.v20190220-1158]
2019-05-01 08:28:01.038 - Can't read schema list
java.lang.AbstractMethodError: Method com/ibm/as400/access/AS400JDBCDatabaseMetaData.getSchemas(Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet; is abstract
	at com.ibm.as400.access.AS400JDBCDatabaseMetaData.getSchemas(AS400JDBCDatabaseMetaData.java)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:197)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:503)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:778)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2019-05-01 08:28:01.381 - Connected (db2_iseries-16928ae13c7-6871d94535926867, AS/400 Toolbox for Java JDBC Driver [7.4])
2019-05-01 08:28:29.053 - > Start org.jkiss.dbeaver.ext.generic.ui [1.0.0.201904211926]
2019-05-01 08:33:14.006 - Disconnected (db2_iseries-16928ae13c7-6871d94535926867)
2019-05-01 08:33:14.006 - Connect with 'DB2 - GP9 GAT' (db2_iseries-16928ae13c7-6871d94535926867)
2019-05-01 08:33:14.288 - Can't read schema list
java.lang.AbstractMethodError: Method com/ibm/as400/access/AS400JDBCDatabaseMetaData.getSchemas(Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet; is abstract
	at com.ibm.as400.access.AS400JDBCDatabaseMetaData.getSchemas(AS400JDBCDatabaseMetaData.java)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:197)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:129)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:503)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:778)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2019-05-01 08:33:14.522 - Connected (db2_iseries-16928ae13c7-6871d94535926867, AS/400 Toolbox for Java JDBC Driver [7.4])

**Comment by JanDuo** [comment]
Found the cause of the problem. I used an old version of the jt400.jar. 
Via [https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/tcws_toolbox.html](url) I found a new version. Changed the jar-file in driver settings and now the schema's are shown again in the Projects tab.
