### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by windong** [dbeaver/dbeaver#5851]
#### System information: 
- Operating system (distribution) and version
  Windows 2008 64Bit
- DBeaver version
  6.0.3
- Java version 
1.8.0_131
- Additional extensions

#### Connection specification:
- Database name and version
   Mysql
- Driver name
   Mysql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
   No

#### Describe the problem you're observing:
Out of memory when the query result over 50000 rows, about 100MB.

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.model.exec.DBCException: GC overhead limit exceeded
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:854)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2720)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: GC overhead limit exceeded
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1719)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	... 6 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at org.jkiss.dbeaver.core.application.DBeaverApplication$ProxyPrintStream.write(DBeaverApplication.java:495)
	at java.io.OutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
	at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
	at java.io.OutputStreamWriter.flushBuffer(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at java.io.PrintStream.print(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at java.lang.Throwable$WrappedPrintStream.println(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at org.jkiss.dbeaver.Log.debugMessage(Log.java:151)
	at org.jkiss.dbeaver.Log.writeExceptionStatus(Log.java:220)
	at org.jkiss.dbeaver.Log.warn(Log.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:145)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob$$Lambda$469/172992725.run(Unknown Source)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1684)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2720)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead$$Lambda$466/1321237997.run(Unknown Source)

**Comment by serge-rider** [comment]
By default maximum allowed memory for DBeaver CE is 1Gb. 
100Mv of raw data can easily eat more than 500Mb of memory.

If you need to work with large amount of data in data editor then you can increase maximum memory size (in dbeaver.ini or by passing command line parameters)
https://github.com/dbeaver/dbeaver/wiki/Command-Line
