### ISSUE TITLE
MongoDB Atlas support

### ISSUE THREAD

**Issue by devcovato** [dbeaver/dbeaver#5905]
#### System information: 
- Operating system (distribution) and version: macOS Mojave 10.14.4
- DBeaver version: EE 6.0
- Java version: built-in
- Additional extensions: none

#### Connection specification:
- Database name and version: MongoDB Atlas 3.6
- Driver name: org.jkiss.jdbc.mongodb.mongodbDriver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I cannot connect to MongoDB Atlas in Replica Type. Robo3T connects successfully. The difference is the creation of a Self-Signed Certificate.

#### Steps to reproduce, if exist:

A MongoDB Cluster in Replica Type on Atlas.

#### Include any warning/errors/backtraces from the logs

```txt
2019-05-14 17:23:07.729 - Connect with 'mongo://XXXXX-shard-00-00-XXXXX:99999/test' (cql-16ab6f0ae4b-14738808ecc6faa1)
2019-05-14 17:23:12.821 - Connection failed (cql-16ab6f0ae4b-14738808ecc6faa1)
2019-05-14 17:23:12.824 - org.jkiss.dbeaver.model.exec.DBCException: Error connecting to Mongo instance [XXXXX-shard-00-00-XXXXX]
org.jkiss.dbeaver.model.exec.DBCException: Error connecting to Mongo instance [XXXXX-shard-00-00-XXXXX:99999]
	at com.dbeaver.ee.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:85)
	at com.dbeaver.ee.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:73)
	at com.dbeaver.ee.mongodb.model.MongoDataSource.<init>(MongoDataSource.java:99)
	at com.dbeaver.ee.mongodb.MongoDataSourceProvider.openDataSource(MongoDataSourceProvider.java:115)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:232)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Error connecting to Mongo instance [XXXXX-shard-00-00-XXXXX]
	at com.dbeaver.ee.mongodb.exec.MongoExecutionContext.reconnect(MongoExecutionContext.java:288)
	at com.dbeaver.ee.mongodb.exec.MongoExecutionContext.connect(MongoExecutionContext.java:82)
	... 8 more
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@2fe71625. Client view of cluster state is {type=REPLICA_SET, servers=[{address=XXXXX-shard-00-02-XXXXX:99999, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}, {address=XXXXX-shard-00-00-XXXXX:99999, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}, {address=XXXXX-shard-00-01-XXXXX:99999, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:401)
	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:120)
	at com.mongodb.internal.connection.MultiServerCluster.selectServer(MultiServerCluster.java:54)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:138)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:182)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:151)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:146)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:136)
	at com.dbeaver.ee.mongodb.exec.MongoExecutionContext.reconnect(MongoExecutionContext.java:285)
	... 9 more
```

**Comment by marcinzelent** [comment]
I have the same issue. It seems DBeaver is using URL with mongo://, while Atlas URL is mongodb+srv://. Is there any way around it?

**Comment by serge-rider** [comment]
I made it to work with Atlas using self-signed SSL certificates. You can test this using Early Access version (https://dbeaver.com/files/ea)

1. On Mongo settings page enter first host name from the list in Atlas URL (you can enter all host names but it is not needed).
1. Set valid database name (`test` by default)
1. Set Replica Set (from Atlas URL)
1. Set proper user name/password and user Source database (usually `admin`)
1. Use `SCRAM-SHA-1` authentication mechanism 
1. Enable "Use self-signed certificate" on Network->SSL page (only if you don't have proper certificate files!)

Required disclaimer: using self-signed certificates with Atlas is very non-secure approach (SSL itself makes very little sense in this case). 
I strongly recommend to use valid CA/server certificates.

![image](https://user-images.githubusercontent.com/6398845/58387324-7b21ec00-8015-11e9-93df-6bb4488c1413.png)
![image](https://user-images.githubusercontent.com/6398845/58387326-81b06380-8015-11e9-8289-c892e9bee72d.png)

**Comment by marcinzelent** [comment]
@serge-rider Works perfectly now. Thank you for the quick response!

**Comment by devcovato** [comment]
Hi @serge-rider,

Unfortunately, my trial license is expired, and I cannot test. I tried to regenerate from the app, and I got the error message "License Error: Can't generate trial license :
 Email 'email@example.com' cannot be used for anonymous trial license generation. Please request the trial license on the web site.". Also, I tried from the site as suggested, but there isn't a way to do it.

As you can guess I tried before to buy. Anyway, thanks for your promptly fix.

**Comment by uslss** [comment]
verified
