### ISSUE TITLE
DBeaver 6.0.4.201905052017 needs update for Netezza JDBC 7.2.1.8

### ISSUE THREAD

**Issue by mosin44** [dbeaver/dbeaver#5914]
#### System information: 
- Operating system (distribution) and version Windows 10 Enterprise (1709)
- DBeaver version 6.0.4.201905052017
- Java version java version "1.8.0_211"
- Additional extensions

#### Connection specification:
- Database name and version IBM PureData for Analytics (Netezza)
- Driver name org.netezza.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Using version 7.2.1.8 of the JDBC driver results in error "Unexpected driver error occurred while connecting to database...  java.lang.NullPointerException".

However, version 7.2.0.0 connects properly

#### Steps to reproduce, if exist:
1. Using Driver Manager, configure the Netezza driver using the 7.2.0.0 JAR
2. Define a connection to Netezza & test (success)
3. Using Driver Manager, configure the Netezza driver using the 7.2.1.8 JAR
4. Test the same connection (fail)

#### Include any warning/errors/backtraces from the logs

Error message: "Error determinig server version"

Stack Trace: java.lang.UnsupportedOperationException
	at sun.jdbc.odbc.JdbcOdbcDatabaseMetaData.getDatabaseMajorVersion(JdbcOdbcDatabaseMetaData.java:4030)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getDatabaseMajorVersion(JDBCDatabaseMetaDataImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:348)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:426)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:782)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:108)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:68)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:205)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:593)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
It is Netezza driver issue, please see workaround here: https://community.microstrategy.com/s/article/Failed-to-Connect-to-IPS-with-the-IBM-Netezza-7-2-1-JDBC-Driver-in-MicroStrategy-2019-and-2020?language=en_US

**Comment by stogdan** [comment]
I can confirm what @serge-rider points out that this is a driver issue with some revisions of the 7.2.x driver. I have tested latest IPS and Netezza driver towards IPS + several generations of PDA (Netezza) and it works with latest version of DBeaver as of March 31 2020 (7.0.1).
