### ISSUE TITLE
Navigate reference throws DBException on DB2 database

### ISSUE THREAD

**Issue by ashtonbatty** [dbeaver/dbeaver#5916]
When connected to a DB2 11.1 database, using Navigate References (Ctrl+1 or right clicking on a key) then selecting a Table Reference shows an exception dialog.

> Problem Occured
'Navigate reference' has encountered a problem.
Can't obtain association 'TABLE2_TABLE1_FK' target constraint (table TABLE2)
OK    Details >>

the .metadata/.log contains

```
!ENTRY org.jkiss.dbeaver.model 4 0 2019-05-16 14:00:22.031
!MESSAGE Can't obtain association 'TABLE2_TABLE1_FK' target constraint (table TABLE2)
!STACK 0
org.jkiss.dbeaver.DBException: Can't obtain association 'TABLE2_TABLE1_FK' target constraint (table TABLE2)
                at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateReference(ResultSetViewer.java:2681)
                at org.jkiss.dbeaver.ui.controls.resultset.ResultSetReferenceMenu$2$1.run(ResultSetReferenceMenu.java:185)
                at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Selecting from the Table Foreign Keys works fine, as does Navigate link (Alt+Space).
Tested in DBeaver 6.0.4 using latest db2jcc4.jar driver.

Reproduce with the following schema:
```SQL
CREATE SCHEMA TEST;
 
CREATE TABLE "TEST"."TABLE1" ( 
    "TABLE1_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SOMETEXT" VARCHAR(50));
 
ALTER TABLE  "TEST"."TABLE1" 
    ADD CONSTRAINT "TABLE1_PK" 
    PRIMARY KEY ("TABLE1_ID") ;
 
CREATE TABLE "TEST"."TABLE2" ( 
    "TABLE2_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TABLE1_ID" BIGINT NOT NULL);
 
ALTER TABLE "TEST"."TABLE2" 
    ADD CONSTRAINT "TABLE2_PK" 
    PRIMARY KEY ("TABLE2_ID") ;
 
ALTER TABLE "TEST"."TABLE2" 
    ADD CONSTRAINT "TABLE2_TABLE1_FK" 
    FOREIGN KEY ("TABLE1_ID") 
    REFERENCES "TEST"."TABLE1" ("TABLE1_ID");
```

and data:
``` 
INSERT INTO TEST.TABLE1 (SOMETEXT)
       VALUES('test1'), ('test2'),  ('test3'), ('test4'),  ('test5');
 
INSERT INTO TEST.TABLE2 (TABLE1_ID)
       VALUES(1), (2), (3), (4), (5);
```

Session Data:
>eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by uslss** [comment]
cannot reproduce an issue.
Ticket closed.
If the issue still actual for you feel free to reopen the ticket.
