### ISSUE TITLE
NullPointerException when open Version 6.0.4

### ISSUE THREAD

**Issue by Wendele** [dbeaver/dbeaver#5924]
!ENTRY org.eclipse.ui.workbench 4 2 2019-05-17 12:42:35.039
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.getLastMigration(MigrationSupport.java:236)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.isFirstTimeRunningThisSharedInstance(MigrationSupport.java:140)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.performMigration(MigrationSupport.java:59)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.earlyStartup(AutomaticUpdateScheduler.java:78)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2019-05-17 12:42:35.060
!MESSAGE An internal error occurred during: "Executing the early startup extensions".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:344)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:286)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:772)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:72)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:78)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
It is a platform error. Looks like some issue with workspace structure.
What you can do:
- Try to download 6.0.5 EA (https://dbeaver.io/files.ea)
- Try to reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)
