### ISSUE TITLE
can't open dbeaver on Ubuntu 19.4

### ISSUE THREAD

**Issue by wamarobert** [dbeaver/dbeaver#5942]
#### System information: Ubuntu 19.4
- Operating system (distribution) and version:-> Linux 5.0.0-13-generic (amd64)
- DBeaver version:-> DBeaver 6.0.4.201905052017
- Java version:-> 11.0.3 by Ubuntu (64bit)
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name postgresql
- Do you use tunnels or proxies (SSH, SOCKS, etc)?:-> NO

#### Describe the problem you're observing:
I have done an installing of Dbeaver-community and was working well but after upgrading and reinstallation a couple of time still it can't open after clicking on the icon (lame man explanation)

#### Steps to reproduce, if exist:
Here is my ~/.dbeaver4/.metadata/*

product-version=6.0.4.201905052017
workspace-id=DLEEYAGPYS3XQ
product-name=DBeaver

#### Include any warning/errors/backtraces from the logs

2019-05-19 19:56:50.245 - DBeaver 6.0.4.201905052017 is starting
2019-05-19 19:56:50.246 - OS: Linux 5.0.0-13-generic (amd64)
2019-05-19 19:56:50.246 - Java version: 11.0.3 by Ubuntu (64bit)
2019-05-19 19:56:50.247 - Install path: '/usr/share/dbeaver'
2019-05-19 19:56:50.247 - Instance path: 'file:/home/username/.dbeaver4/'
2019-05-19 19:56:50.247 - Memory available 66Mb/1024Mb
2019-05-19 19:56:50.267 - Starting RMI server at 63172
2019-05-19 19:56:50.330 - Run workbench
2019-05-19 19:56:50.340 - > Start org.eclipse.e4.ui.workbench.swt [0.14.500.v20190214-0851]
2019-05-19 19:56:50.342 - > Start org.eclipse.e4.core.services [2.1.400.v20181215-2145]
2019-05-19 19:56:50.344 - > Start org.eclipse.e4.core.contexts [1.8.0.v20190214-1713]
2019-05-19 19:56:50.355 - > Start org.eclipse.e4.ui.services [1.3.400.v20190212-2214]
2019-05-19 19:56:50.386 - > Start org.eclipse.e4.ui.di [1.2.500.v20190214-1316]
2019-05-19 19:56:50.425 - > Start org.eclipse.emf.common [2.15.0.v20181220-0846]
2019-05-19 19:56:50.444 - > Start org.eclipse.emf.ecore [2.17.0.v20190116-0940]
2019-05-19 19:56:50.527 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-05-19 19:56:50.673 - > Start org.eclipse.core.filesystem [1.7.300.v20190218-2054]
2019-05-19 19:56:50.704 - > Start org.eclipse.core.resources [3.13.300.v20190218-2054]
2019-05-19 19:56:50.864 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.400.v20190224-1542]
2019-05-19 19:56:50.875 - > Start org.eclipse.core.expressions [3.6.300.v20190218-1215]
2019-05-19 19:56:50.886 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.500.v20190220-1002]
2019-05-19 19:56:51.004 - > Start org.eclipse.e4.ui.bindings [0.12.400.v20190131-1604]
2019-05-19 19:56:51.057 - > Start org.eclipse.e4.core.di.extensions [0.15.300.v20190213-1308]
2019-05-19 19:56:51.428 - > Start org.eclipse.e4.ui.css.swt [0.13.400.v20190223-1254]
2019-05-19 19:56:51.501 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.200.v20190212-2214]
2019-05-19 19:56:51.552 - > Start org.jkiss.dbeaver.ui [5.1.23.201905052017]
2019-05-19 19:56:51.852 - Initializing DBeaver 6.0.4
2019-05-19 19:56:51.853 - Host plugin: org.jkiss.dbeaver.core.application 6.0.4.201905052017
2019-05-19 19:56:51.853 - Initialize Core...
2019-05-19 19:56:51.869 - Can't find BC security provider. Use default JCE.
2019-05-19 19:56:51.870 - BouncyCastle not registered, using the default JCE provider
2019-05-19 19:56:51.872 - > Start org.jkiss.dbeaver.registry [1.0.2.201905052017]
2019-05-19 19:56:51.939 - > Start org.eclipse.team.core [3.8.500.v20190216-2155]
2019-05-19 19:56:51.958 - > Start org.jkiss.dbeaver.ui.navigator [1.0.8.201905052017]
2019-05-19 19:56:52.068 - Total database drivers: 72 (72)
2019-05-19 19:56:52.093 - > Start org.eclipse.equinox.security [1.3.100.v20190215-2139]
2019-05-19 19:56:52.103 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-05-19 19:56:52.105 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-05-19 19:56:52.105 - > Start org.eclipse.core.net [1.3.400.v20181030-1645]
2019-05-19 19:56:52.108 - Core initialized (255ms)
2019-05-19 19:56:52.108 - Configure workbench window
2019-05-19 19:56:52.117 - > Start org.eclipse.help [3.8.300.v20190216-1017]
2019-05-19 19:56:52.302 - Create actions
2019-05-19 19:56:52.303 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-05-19 19:56:52.304 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-05-19 19:56:52.389 - > Start org.eclipse.ui.editors [3.11.400.v20190218-1547]
2019-05-19 19:56:52.392 - > Start org.eclipse.core.filebuffers [3.6.500.v20190218-1547]
2019-05-19 19:56:52.792 - > Start org.eclipse.search [3.11.500.v20190218-2126]
2019-05-19 19:56:52.955 - > Start org.eclipse.ui.workbench.texteditor [3.11.300.v20190218-2126]
2019-05-19 19:56:52.963 - Initialize workbench window
2019-05-19 19:56:52.968 - Finish initialization
2019-05-19 19:56:53.026 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.8.201905052017]
2019-05-19 19:56:53.095 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.8.201905052017]
2019-05-19 19:56:53.101 - > Start org.jkiss.dbeaver.ext.erd [2.0.110.201905052017]
2019-05-19 19:57:04.754 - Internal error in workbench lifecycle
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jface.text.TextViewer.applyTextPresentation(TextViewer.java:4681)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4733)
	at org.eclipse.jface.text.presentation.PresentationReconciler.applyTextRegionCollection(PresentationReconciler.java:562)
	at org.eclipse.jface.text.presentation.PresentationReconciler.processDamage(PresentationReconciler.java:551)
	at org.eclipse.jface.text.presentation.PresentationReconciler.access$3(PresentationReconciler.java:547)
	at org.eclipse.jface.text.presentation.PresentationReconciler$InternalListener.inputDocumentChanged(PresentationReconciler.java:121)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2746)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2787)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:663)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:613)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3972)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3442)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:452)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.createPartControl(BaseTextEditor.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.createPartControl(SQLEditorBase.java:275)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.createPartControl(SQLEditor.java:715)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:156)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:102)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:367)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1001)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:966)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:411)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:333)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
2019-05-19 19:57:04.765 - DBeaver is stopping
2019-05-19 19:57:04.765 - Stop RMI server

**Comment by serge-rider** [comment]
You could try to Reset workspace (https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by wamarobert** [comment]
Thank you, works fine now.
