### ISSUE TITLE
Can't execute procedures on Sybase IQ

### ISSUE THREAD

**Issue by inigomp** [dbeaver/dbeaver#5959]
#### System information: 
- Windows 7
- DBeaver 6.0.5

#### Connection specification:
- Sybase IQ 15
- Sybase jConnect
- Do you use tunnels or proxies (SSH, SOCKS, etc) No

#### Describe the problem you're observing:

Can't execute procedures or BEGIN ... END querys. It stops on first ";" with an error.

![image](https://user-images.githubusercontent.com/47743019/53358101-ad954d80-392f-11e9-8cbd-c1cdc098a662.png)

SQL Error [102] [42W04]: SQL Anywhere Error -131: Syntax error near 'SELECT' on line 2
  SQL Anywhere Error -131: Syntax error near 'SELECT' on line 2

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2019-05-21 14:54:45.593
!MESSAGE Error executing query
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-05-21 14:54:45.593
!MESSAGE SQL Error [102] [42W04]: SQL Anywhere Error -131: Syntax error near 'BEGIN' on line 1
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-05-21 14:54:45.593
!MESSAGE SQL Anywhere Error -131: Syntax error near 'BEGIN' on line 1
!STACK 0
com.sybase.jdbc4.jdbc.SybSQLException: SQL Anywhere Error -131: Syntax error near 'BEGIN' on line 1
	at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4201)
	at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3318)
	at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:302)
	at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:284)
	at com.sybase.jdbc4.jdbc.SybStatement.executeLoop(SybStatement.java:2842)
	at com.sybase.jdbc4.jdbc.SybStatement.execute(SybStatement.java:2829)
	at com.sybase.jdbc4.jdbc.SybStatement.execute(SybStatement.java:1459)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2727)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ASk1** [comment]
same issue
SQL Error [102] [42W04]: SQL Anywhere Error -131: Syntax error near 'END' on line 2 
If I manually select all statements - it works. Also it works in ODBC connection

**Comment by LonwoLonwo** [comment]
As a workaround - you can highlight all procedure text and use ctrl+Enter

**Comment by inigomp** [comment]
Yes, thank you, but I can't develop a new procedure:

[image: image.png]

**Comment by inigomp** [comment]
sorry, my fault. It works

**Comment by LonwoLonwo** [comment]
Can't reproduce against DBeaver 23.0.3

![2023-04-24 17_35_33-Event](https://user-images.githubusercontent.com/45152336/234029507-c1c5b4c9-7a33-4416-b793-323c9f956bb5.png)

Feel free to create a new ticket if problem will appear again.
