### ISSUE TITLE
dbeaver 6.0.5 on Ubuntu 19.04 can't create new connections

### ISSUE THREAD

**Issue by unusualmutant** [dbeaver/dbeaver#5968]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.04 (with Wayland)
- DBeaver version: 6.0.5 CE
- Java version: 11.0.2 (Oracle)

#### Connection specification:
- Database name and version: All
- Driver name: Any
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
When clicking "New Database Connection" or selecting a specific database from the dropdown, nothing happens.

#### Steps to reproduce, if exist:
Downloaded and installed Java 11 (Oracle) and set it to default
Downloaded and installed dbeaver-ce_6.0.5_amd64.deb
"New Database Connection" does nothing out of the box

#### Include any warning/errors/backtraces from the logs
[dbeaver.log](https://github.com/dbeaver/dbeaver/files/3206255/dbeaver.log)

**Comment by serge-rider** [comment]
Please see the workaround in #5593

**Comment by unusualmutant** [comment]
Thank you, I just tried it, but unfortunately I still have the same issue and the same errors show up in the log.

**Comment by serge-rider** [comment]
Please check Early Access version (https://dbeaver.io/files/ea). It doesn't fixes this problem in general but perhaps will help of connection dialog. In any case error log should be different.

**Comment by unusualmutant** [comment]
Thanks again for trying to help. I get the initial "choose connection type" screen, which is new, but the moment I select the type, I get the same/similar error:

eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue May 28 11:10:03 CEST 2019
No more handles

org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:217)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:3014)
	at org.jkiss.dbeaver.ui.controls.ObjectViewerRenderer.<init>(ObjectViewerRenderer.java:66)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer$1.<init>(PropertyTreeViewer.java:138)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer.<init>(PropertyTreeViewer.java:138)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPropertiesControl.<init>(ConnectionPropertiesControl.java:52)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage.createControl(DriverPropertiesDialogPage.java:140)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.createProviderPage(ConnectionPageSettings.java:211)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.activatePage(ConnectionPageSettings.java:108)
	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1223)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:579)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.dialogs.connection.CreateConnectionDialog.open(CreateConnectionDialog.java:83)
	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:80)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

**Comment by uslss** [comment]
Hi @unusualmutant , is issue still actual for you on recent version?

**Comment by unusualmutant** [comment]
I just tried again on 6.2.2, and I get the modal to select the driver, but
no matter what I select, clicking "Next" does nothing.

**Comment by uslss** [comment]
cannot reproduce issue on 6.3.1 (ubuntu 19.04)
ticket closed
