### ISSUE TITLE
Error after correcting and re-running a query

### ISSUE THREAD

**Issue by DeBaum** [dbeaver/dbeaver#5973]
#### System information: 
- Operating system (distribution) and version: Windows10 1809
- DBeaver version: 6.0.5.201905192012
- Java version: OpenJDK 12.0.1 2019-04-16 (JRE: 12.0.1+12)
- Additional extensions: Darkest Dark Theme

#### Connection specification:
- Database name and version: MySQL 5.7.10
- Driver name: mysql-connector-java-5.1.44
- Do you use tunnels or proxies (SSH, SOCKS, etc): no

#### Describe the problem you're observing:

Error "Graphic is disposed" pops up after running a successful query after running an unsuccessful query.

#### Steps to reproduce, if exist:

1. Run a query with a syntax-error or abort a log running query. (Error message is shown in result window)
2. Run a query which completes and shows a resultset
3. Error is shown in a dialog box

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.eclipse.ui.workbench.texteditor 4 2 2019-05-22 11:29:14.298
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench.texteditor".
!STACK 0
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4699)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.graphics.Color.getRGB(Color.java:318)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.defensiveCopy(ImageDrawer.java:113)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.prepareColorAttribute(ImageDrawer.java:109)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.setBackground(ImageDrawer.java:53)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageUpdate.setBackground(ImageUpdate.java:38)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ClickControl.setBackground(ClickControl.java:96)
	at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.setBackground(FlatScrollBar.java:242)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayoutFactory.setBackgroundColor(ScrollableLayoutFactory.java:142)
	at com.codeaffine.eclipse.swt.widget.scrollable.StyledTextAdapter.setBackgroundColor(StyledTextAdapter.java:974)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ColorReconciliation.run(ColorReconciliation.java:32)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.resume(Reconciliation.java:84)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWhileSuspended(Reconciliation.java:64)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayout.layout(ScrollableLayout.java:54)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1368)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1346)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:704)
	at org.eclipse.jface.text.source.CompositeRuler.layoutTextViewer(CompositeRuler.java:590)
	at org.eclipse.jface.text.source.CompositeRuler.removeDecorator(CompositeRuler.java:573)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport$2.run(AbstractTextEditor.java:1647)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.removeColumn(AbstractTextEditor.java:1651)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.dispose(AbstractTextEditor.java:1740)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor$2.dispose(AbstractDecoratedTextEditor.java:792)
	at org.eclipse.ui.texteditor.AbstractTextEditor.dispose(AbstractTextEditor.java:4416)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.dispose(AbstractDecoratedTextEditor.java:390)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.dispose(BaseTextEditor.java:99)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.dispose(SQLEditorBase.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.UIServiceSQLImpl.lambda$0(UIServiceSQLImpl.java:103)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:127)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:812)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:931)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:815)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:429)
	at org.jkiss.dbeaver.ui.UIUtils.disposeChildControls(UIUtils.java:1833)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSetViewer.java:657)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:590)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataReceiver.java:179)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

!ENTRY org.eclipse.ui.workbench.texteditor 4 2 2019-05-22 11:29:14.355
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench.texteditor".
!STACK 0
java.lang.IllegalStateException: ImageDrawer is disposed.
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.checkDisposed(ImageDrawer.java:99)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.setBackground(ImageDrawer.java:51)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageUpdate.setBackground(ImageUpdate.java:38)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ClickControl.setBackground(ClickControl.java:96)
	at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.setBackground(FlatScrollBar.java:242)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayoutFactory.setBackgroundColor(ScrollableLayoutFactory.java:142)
	at com.codeaffine.eclipse.swt.widget.scrollable.StyledTextAdapter.setBackgroundColor(StyledTextAdapter.java:974)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ColorReconciliation.run(ColorReconciliation.java:32)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.resume(Reconciliation.java:84)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWhileSuspended(Reconciliation.java:64)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayout.layout(ScrollableLayout.java:54)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1763)
	at org.eclipse.swt.widgets.Canvas.WM_SIZE(Canvas.java:452)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5687)
	at org.eclipse.swt.widgets.Canvas.WM_WINDOWPOSCHANGED(Canvas.java:459)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4856)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:1138)
	at org.eclipse.swt.widgets.Control.getBoundsInPixels(Control.java:1265)
	at org.eclipse.swt.widgets.Control.getBounds(Control.java:1261)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.updateAdapterBounds(LayoutActor.java:73)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.lambda$0(LayoutActor.java:52)
	at com.codeaffine.eclipse.swt.util.OperationWithRedrawSuspension.execute(OperationWithRedrawSuspension.java:20)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.layout(LayoutActor.java:50)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1346)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:704)
	at org.eclipse.jface.text.source.CompositeRuler.layoutTextViewer(CompositeRuler.java:590)
	at org.eclipse.jface.text.source.CompositeRuler.removeDecorator(CompositeRuler.java:573)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport$2.run(AbstractTextEditor.java:1647)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.removeColumn(AbstractTextEditor.java:1651)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.dispose(AbstractTextEditor.java:1740)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor$2.dispose(AbstractDecoratedTextEditor.java:792)
	at org.eclipse.ui.texteditor.AbstractTextEditor.dispose(AbstractTextEditor.java:4416)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.dispose(AbstractDecoratedTextEditor.java:390)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.dispose(BaseTextEditor.java:99)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.dispose(SQLEditorBase.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.UIServiceSQLImpl.lambda$0(UIServiceSQLImpl.java:103)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:127)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:812)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:931)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:815)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:429)
	at org.jkiss.dbeaver.ui.UIUtils.disposeChildControls(UIUtils.java:1833)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSetViewer.java:657)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:590)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataReceiver.java:179)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
```

**Comment by ranasrule** [comment]
same issue here on version 6.1.4

**Comment by serge-rider** [comment]
I can't reproduce this.
You described a very standard use-case, I think I did this thousands of times and nevr saw such error.
Maybe there are some other things involved.

I see some "codeaffine" component in the stacktrace. And I believe it casues this problem. Could you verify?

**Comment by Thoschman** [comment]
Same here on DBeaver Enterprise 6.1.0
`
!ENTRY org.eclipse.ui.workbench.texteditor 4 2 2019-08-28 15:30:57.891
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench.texteditor".
!STACK 0
java.lang.IllegalStateException: ImageDrawer is disposed.
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.checkDisposed(ImageDrawer.java:99)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageDrawer.setBackground(ImageDrawer.java:51)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ImageUpdate.setBackground(ImageUpdate.java:38)
	at com.codeaffine.eclipse.swt.widget.scrollbar.ClickControl.setBackground(ClickControl.java:96)
	at com.codeaffine.eclipse.swt.widget.scrollbar.FlatScrollBar.setBackground(FlatScrollBar.java:242)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayoutFactory.setBackgroundColor(ScrollableLayoutFactory.java:142)
	at com.codeaffine.eclipse.swt.widget.scrollable.StyledTextAdapter.setBackgroundColor(StyledTextAdapter.java:974)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ColorReconciliation.run(ColorReconciliation.java:32)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.resume(Reconciliation.java:84)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWhileSuspended(Reconciliation.java:64)
	at com.codeaffine.eclipse.swt.widget.scrollable.ScrollableLayout.layout(ScrollableLayout.java:54)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1763)
	at org.eclipse.swt.widgets.Canvas.WM_SIZE(Canvas.java:452)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:91)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5687)
	at org.eclipse.swt.widgets.Canvas.WM_WINDOWPOSCHANGED(Canvas.java:459)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4856)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:1138)
	at org.eclipse.swt.widgets.Control.getBoundsInPixels(Control.java:1265)
	at org.eclipse.swt.widgets.Control.getBounds(Control.java:1261)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.updateAdapterBounds(LayoutActor.java:73)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.lambda$0(LayoutActor.java:52)
	at com.codeaffine.eclipse.swt.util.OperationWithRedrawSuspension.execute(OperationWithRedrawSuspension.java:20)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.LayoutActor.layout(LayoutActor.java:50)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1361)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1346)
	at org.eclipse.swt.widgets.Composite.layout(Composite.java:704)
	at org.eclipse.jface.text.source.CompositeRuler.layoutTextViewer(CompositeRuler.java:590)
	at org.eclipse.jface.text.source.CompositeRuler.removeDecorator(CompositeRuler.java:573)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport$2.run(AbstractTextEditor.java:1647)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.removeColumn(AbstractTextEditor.java:1651)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ColumnSupport.dispose(AbstractTextEditor.java:1740)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor$2.dispose(AbstractDecoratedTextEditor.java:792)
	at org.eclipse.ui.texteditor.AbstractTextEditor.dispose(AbstractTextEditor.java:4416)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.dispose(AbstractDecoratedTextEditor.java:390)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.dispose(BaseTextEditor.java:99)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.dispose(SQLEditorBase.java:486)
	at org.jkiss.dbeaver.ui.editors.sql.UIServiceSQLImpl.lambda$0(UIServiceSQLImpl.java:103)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:127)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:812)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:931)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:815)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:429)
	at org.jkiss.dbeaver.ui.UIUtils.disposeChildControls(UIUtils.java:1833)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.setActivePresentation(ResultSetViewer.java:657)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.updatePresentation(ResultSetViewer.java:590)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.lambda$0(ResultSetDataReceiver.java:179)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:61)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
`

**Comment by serge-rider** [comment]
Particular error is caused by Darkest Dark theme plugin. However we should handle this glitch in DBeaver to avoid dummy and confusing error dialogs.

**Comment by kseniiaguzeeva** [comment]
Verified
