### ISSUE TITLE
Feature request: SQLite regexp

### ISSUE THREAD

**Issue by icegood** [dbeaver/dbeaver#6002]
Already described in the forum:
https://dbeaver.io/forum/viewtopic.php?f=2&t=1699
For this moment JDBC driver returns:
jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such function: REGEXP)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2727)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)"

Please, track appropriate issue https://github.com/xerial/sqlite-jdbc/issues/429
and merge it in project whenever possible.

**Comment by muraii** [comment]
I apologize if this is the wrong place for this question, but is there a plug-in/extension that provides this functionality? I've looked through the Eclipse Marketplace and didn't find one but perhaps I overlooked it.

**Comment by r0bis** [comment]
I would also much appreciate such functionality. At the moment I need to go to `sqlite3` command line tool and there issue a dot-command `.load /usr/lib/sqlite3/pcre.so`
Maybe this is another solution, could DBeaver execute dot-commands?

**Comment by bobhy** [comment]
There are good sqlite extensions which already implement regexp (and related) functions, see, for example:  https://sqlpkg.org/?q=regex.  You might not need an enhancement request.

The trick is to get DBeaver to load a sqlite extension shared library.  DBeaver sqlite driver has documentation about  specifying  the extensions to load, documented [here](https://dbeaver.com/docs/dbeaver/Database-driver-SQLite/#sqlite-extensions), but I can't get it to work (on linux, in DBeaver-ce, current version...), see #34475.  

If anyone has better luck, I'd like to hear about it!

**Comment by r0bis** [comment]
I remeber I solved this problem with a bash script to execute predefined queries. The script loaded regexp extension while running the query. No reason why query could not be defined as a parameter to the script.
