### ISSUE TITLE
DBeaver Crashes on start (Ubuntu 18.04.2)

### ISSUE THREAD

**Issue by nsk7even** [dbeaver/dbeaver#6014]
#### System information: 
- Ubuntu 18.04.2 LTS
- DBeaver 5.2.0
- Java openjdk 11.0.2 2019-01-15 

#### Describe the problem you're observing:
DBeaver shows splash screen at start, but then quits with error message, refering to the log file.

#### Steps to reproduce, if exist:
Simply starting dbeaver

#### Include any warning/errors/backtraces from the logs
2019-05-28 14:04:51.391 - DBeaver 5.2.0 is starting
2019-05-28 14:04:51.393 - OS: Linux 4.15.0-47-generic (amd64)
2019-05-28 14:04:51.394 - Java version: 11.0.2 by Oracle Corporation (64bit)
2019-05-28 14:04:51.395 - Install path: '/usr/share/dbeaver'
2019-05-28 14:04:51.395 - Instance path: 'file:/home/nsk/.dbeaver4/'
2019-05-28 14:04:51.395 - Memory available 64Mb/1024Mb
2019-05-28 14:04:51.421 - Starting RMI server at 24477
2019-05-28 14:04:51.485 - Run workbench
2019-05-28 14:04:51.535 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
2019-05-28 14:04:51.549 - DBeaver is stopping
2019-05-28 14:04:51.549 - null
java.lang.IllegalStateException: Workbench wurde noch nicht erstellt.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.shutdown(DBeaverApplication.java:286)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

I have seen a lot of similar issues regarding this problem, but all of them look different.

**Comment by uslss** [comment]
Hi @nsk7even ,
it seems that your problem is similar to #5723 . Hope it helps to resolve the issue.

**Comment by nsk7even** [comment]
I don't have this assistive error in my log and additionally I get this error message popup which the author of the other issue didn't mentioned.
But I will try the workaround explained there and post back the result here.
Thanks for this hint.

**Comment by nsk7even** [comment]
> Hi @nsk7even ,
> it seems that your problem is similar to #5723 . Hope it helps to resolve the issue.

Tried this, but it didn't worked for me.

**Comment by uslss** [comment]
hi @nsk7even ,
is it still actual for you against recent version of dbeaver?

**Comment by nsk7even** [comment]
> hi @nsk7even ,
> is it still actual for you against recent version of dbeaver?

Hi @uslss , recently I tried it again and it still failed. I didn't checked whether it is the same error in the logs, though. I will have to see what version it is right now, when I am back in the office. But I am still running on the current Ubuntu 18.x LTS, if this already answers the version quest for you.

**Comment by nsk7even** [comment]
Just checked this out, it is still the version 5.2.0 here on Ubuntu 18.04.4 LTS.

**Comment by uslss** [comment]
@nsk7even could you try it against recent version (7.0.2)?

**Comment by nsk7even** [comment]
ok will try it

**Comment by nsk7even** [comment]
DBeaver 7.0.2 works, thank you!
