### ISSUE TITLE
Presto Connector can't extract Array : org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from JDBC array

### ISSUE THREAD

**Issue by emhlbmc** [dbeaver/dbeaver#6025]
#### System information: 
- Operating system (distribution) and version
macOS high sierra
- DBeaver version
6.0.5.201905192012
- Java version 
1.8.0_162
- Additional extensions

#### Connection specification:
- Database name and version
presto 0.219
- Driver name
PrestoDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no
#### Describe the problem you're observing:

SQL:
```
select split('apache presto','e') as string_split; 
```

ERROR:
```
org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from JDBC array
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:62)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2727)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL error: getResultSet not supported
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:224)
	... 17 more
Caused by: java.sql.SQLFeatureNotSupportedException: getResultSet not supported
	at com.facebook.presto.jdbc.PrestoArray.getResultSet(PrestoArray.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromResultSet(JDBCCollection.java:313)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:222)
	... 17 more

```

**Comment by serge-rider** [comment]
I still can't reproduce this. I need to setup proper Presto node.If anybody could help with this (e.g. you have some test Prestor node where I can reproduce this problem) - please let me know 9here or on serge@jkiss.org).

**Comment by elonlo** [comment]
![image](https://user-images.githubusercontent.com/5669148/62056734-d6a86a00-b250-11e9-8334-eafc3a88c930.png)
![image](https://user-images.githubusercontent.com/5669148/62056782-ed4ec100-b250-11e9-8a23-215cf1cbc3f2.png)
I also encountered, can not parse json double-layer array

**Comment by serge-rider** [comment]
Please test this in 6.1.4. 
We did several very similar bug fixes for Hive.

**Comment by kdonavin** [comment]
Upgrading to 6.1.4 did not solve this issue for me: 
![image](https://user-images.githubusercontent.com/16674499/62648140-657f4b80-b90f-11e9-8828-204fa12d524e.png)

- OS: OSX Mojave - 10.14.6 (18G87)
- DBeaver version:  DBeaver Community Edition	6.1.4.201908041900
- Java Version: openjdk version 1.8.0_222
- Presto Driver: JDBC 315
- Database: Hadoop 

However! I do think it solved a related issue, where displaying arrays often threw `NullPointerException`s. This used to break and does not in version 6.1.4

```select sequence(0, 60);```

**Comment by serge-rider** [comment]
@emhlbmc @elonlo @kdonavin thanks for details.
I've reproduced this problem on AWS EMR Presto. The actul problem was in wrong JDBC array data type (it was in form "VARCHAR(13)" while it must be simply "VARCHAR".

Anyway, I've added a workaround and now arrays are parsed correctly. Please check it, maybe it'll fail some more complicated cases.
Early Access version: https://dbeaver.io/files/ea

**Comment by uslss** [comment]
verified
![image](https://user-images.githubusercontent.com/31996417/62838876-a3bb9880-bc8a-11e9-89a9-58f915b39191.png)
