### ISSUE TITLE
NPE in creating new DB

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6042]
#### System information: 
- Operating system (distribution) and version: windows 10
- DBeaver version: 6.0.4
- Java version: 8 
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgresql 11.2
- Driver name: n/a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no 

#### Steps to reproduce, if exist:
Connect to DB called qwe. This will be your default DB.
Add second DB called asdf.
Set asdf as active DB.
Remove qwe DB.
Refresh --> Error message appears:
![image](https://user-images.githubusercontent.com/6930846/58803964-59c68e80-8619-11e9-8869-3fd3bc938659.png)
It's correct, but DBeaver displays that connection to this DB is still active (green icon is present in project tree).
Try to create new DB --> Error message appears:
![image](https://user-images.githubusercontent.com/6930846/58804079-a611ce80-8619-11e9-86ff-078e06dbdce8.png)

#### Include any warning/errors/backtraces from the logs
`2019-06-03 16:01:32.241 - > Start org.eclipse.gef [3.11.0.201606061308]
2019-06-03 16:03:54.722 - Initiate connection to PostgreSQL database [asdf@localhost] for Main
2019-06-03 16:03:54.754 - Initiate connection to PostgreSQL database [asdf@localhost] for Metadata
2019-06-03 16:04:04.144 - null
org.jkiss.dbeaver.model.exec.DBCConnectException: FATAL: database "qwe" does not exist
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:360)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.refreshObject(PostgreDataSource.java:251)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.refreshObject(DataSourceDescriptor.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:335)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:272)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:154)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: FATAL: database "qwe" does not exist
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 9 more
2019-06-03 16:04:30.653 - null
org.jkiss.dbeaver.model.exec.DBCConnectException: FATAL: database "qwe" does not exist
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:360)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:120)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.refreshObject(PostgreDataSource.java:251)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.refreshObject(DataSourceDescriptor.java:595)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:335)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.refreshNode(DBNDataSource.java:272)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:154)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: FATAL: database "qwe" does not exist
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 9 more
2019-06-03 16:06:56.947 - null
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.ui.PostgreCreateDatabaseDialog$5.run(PostgreCreateDatabaseDialog.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`
If you disconnect, you won't see this error, but you won't be able to connect to this db either. (Because you have just removed it).

My suggestion is to add a confirmation dialog when user tries to remove default DB. And drop connection right after deletion.

**Comment by uslss** [comment]
The issue isn't reproducible anymore (6.3.2).
Ticket closed.
If issue is still actual for you - feel free to reopen the ticket
