### ISSUE TITLE
NPE during execution of bootstrap query while connecting to Oracle

### ISSUE THREAD

**Issue by abutic** [dbeaver/dbeaver#6089]
#### System information: 
- Operating system (distribution) and version Windows 10
- DBeaver version 6.1.0
- Java version build 1.8.0_77-b03
- Additional extensions

#### Connection specification:
- Database name and version Oracle 12.1.0.2.0
- Driver name Oracle JDBC driver [12.1.0.2.0]
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
NPE while trying to execute bootstrap query while connecting to DB.
#### Steps to reproduce, if exist:
In Database Navigator, right click to connection -> Edit Connection.
Connection settings -> Initialization -> Bootstrap queries -> Configure -> Add
Enter
  ALTER SESSION SET NLS_COMP=BINARY
and click OK. Click OK again to save bootstrap SQL queries.

Try connecting to database using "Test Connection ..." action. This raises an NPE, as shown in lower stacktrace extracted from dbeaver-debug.log.

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.model.exec.DBCException: Error executing bootstrap query: ALTER SESSION SET NLS_COMP=BINARY
	at org.jkiss.dbeaver.model.impl.AbstractExecutionContext.initContextBootstrap(AbstractExecutionContext.java:104)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMetaContext(JDBCRemoteInstance.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:343)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initialize(OracleDataSource.java:386)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:785)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleSQLDialect.isDisableScriptEscapeProcessing(OracleSQLDialect.java:399)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.impl.AbstractExecutionContext.initContextBootstrap(AbstractExecutionContext.java:96)
	... 8 more

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
