### ISSUE TITLE
Unable to generate MockData for table that is referenced by another table

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6097]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.1.0 EE
- Java version: n\a
- Additional extensions: no

#### Connection specification:
- Database name and version: PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Driver name: n\a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
I'm trying to generate mock data for the table and observe an exception:
![image](https://user-images.githubusercontent.com/6930846/59430628-77e77800-8deb-11e9-9af5-fe7da224918d.png)
But address_aud table is empty.

#### Steps to reproduce, if exist:
Create table called address_aud.
Create table revinfo.
Add foreign key from address_aud to revinfo.
Double click on revinfo table in Database Navigator. 
Select Data tab.
Click Generate Mock Data button.
Check Remove old Data combobox.
Click Start button.

#### Include any warning/errors/backtraces from the logs
`2019-06-13 14:56:22.009 - Error removing the data: 
SQL Error [0A000]: ERROR: cannot truncate a table referenced in a foreign key constraint
  Detail: Table "address_aud" references "revinfo".
  Hint: Truncate table "address_aud" at the same time, or use TRUNCATE ... CASCADE.
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [0A000]: ERROR: cannot truncate a table referenced in a foreign key constraint
  Detail: Table "address_aud" references "revinfo".
  Hint: Truncate table "address_aud" at the same time, or use TRUNCATE ... CASCADE.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.truncateData(JDBCTable.java:557)
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:176)
	at org.jkiss.dbeaver.ext.mockdata.MockDataExecuteWizard.executeProcess(MockDataExecuteWizard.java:1)
	at org.jkiss.dbeaver.ui.dialogs.tools.AbstractToolWizard.run(AbstractToolWizard.java:311)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$8(UIUtils.java:1499)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot truncate a table referenced in a foreign key constraint
  Detail: Table "address_aud" references "revinfo".
  Hint: Truncate table "address_aud" at the same time, or use TRUNCATE ... CASCADE.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	... 6 more`

**Comment by uslss** [comment]
duplicates #4611
