### ISSUE TITLE
DBeaver can not work with embended H2 DB

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6098]
#### System information: 
- Windows 10
- DBeaver version: 6.1.0 EE
- Java version: n\a
- Additional extensions: no

#### Connection specification:
- H2 emended mode
- n\a
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
DBeaver does not see anything in DB, but can connect to it.

#### Steps to reproduce, if exist:
I start h2 in memory mode and use for it spring boot test. 
When I create a connection and test it in DBeaver - everything is fine. I can see schemes, but nothing else:
![image](https://user-images.githubusercontent.com/6930846/59445532-83956780-8e08-11e9-9d1a-c437fb2a3e53.png)

#### Include any warning/errors/backtraces from the logs
`2019-06-13 18:12:41.075 - Can't read generic functions
org.h2.jdbc.JdbcSQLException: Feature not supported: "getFunctions" [50100-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:374)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3134)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctions(JDBCDatabaseMetaDataImpl.java:229)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadProcedures(GenericMetaModel.java:292)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:413)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPackages(GenericObjectContainer.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:825)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:806)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:886)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:499)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:422)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:207)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:68)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by serge-rider** [comment]
It is not clear what exactly is wrong.
Embedded 'mem' mode creates new databases every time you connect. All database contents is purged after disconnect.
If you want to use persistent database in embedded mode then use default driver config (`jdbc:h2:{database}`)

**Comment by tchibatron** [comment]
I use h2 in my unit tests. I set break point somewhere in the code, so the connection is still alive, I suppose. But when I connect to my db with DBeaver at the same time I don't see tables.

**Comment by p91paul** [comment]
h2 database, while working "in memory" exists solely on your process memory. Since your unit test and DBeaver are different processes, if they both use an h2 mem db they get 2 different databases, one in the memory of each process. I'm not aware of a way in which one process can connect to the h2 db of another project. If you are debugging you should temporarily switch to persistent mode in your unit test; your test will probably write a file somewhere and you can try to access that from DBeaver.

**Comment by tchibatron** [comment]
@p91paul Thank you for the explanation. I see the point now.

**Comment by istibekesi** [comment]
You can start a server for the H2 database in your application at startup:
`org.h2.tools.Server server = org.h2.tools.Server.createTcpServer().start();`

Then H2 *server* connection works seamlessly, displaying the same tables your application uses: 
![image](https://user-images.githubusercontent.com/5990010/121651236-b11a5780-ca9a-11eb-8d5a-fa3a93a047f2.png)

**Comment by istibekesi** [comment]
@PXNX did you start H2 in server mode? Default port supposed to be 9092 in that case.
