### ISSUE TITLE
hot key assignment seems to be pasted in SQL statement

### ISSUE THREAD

**Issue by fft1010** [dbeaver/dbeaver#6120]
#### System information: 
- MacOS Mojave 10.14.5, DBeaver Community, 6.1.0 for mac
- Java version 
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

- Additional extensions
Non in DBeaver

#### Connection specification:
- MySQL, no idea which verison I assume "actual"
- Driver name ? No idea, sorry. 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes, SSH tunnel.

By filling this out, I have the idea, to have a "copy paste" in DBeaver, where you find all those informations. I saw "Help->Installation information" but do not think, that all Infos there are needed.

#### Describe the problem you're observing:
This morning a tipp came up, that I can redefine and use keyboard shortcuts. Cool feature I thought and assigned the <ctrl>-e to the "export results to a file" in the SQL editor.
The key assigment does work fine, the export dialog is started the same way as if I klick on the "export button, the "up arrow in the small open box". But when the export starts I get an error like the following:
SQL-Fehler [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE startIssue.`issuenum` = 19843
ORDER BY tickets.`issuenum`,AK.`issuenum` AS' at line 1

I first though it is an error in my SQL, but it is NOT as the "klick on the export button" does a fine export.
I than noticed, that the error line changes, depending on where the cursor is located short before I press <ctrl>-e
So I personally assume, that the keypress is somehow "transferred" into the SQL export statement, and than the SQL engine does not know what to do with this funny "CTRL-E" in the mid of the SQL statement.
I can reproduce it every time.

#### Include any warning/errors/backtraces from the logs
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE startIssue.`issuenum` = 19843
ORDER BY tickets.`issuenum`,AK.`issuenum` AS' at line 1

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE startIssue.`issuenum` = 19843
ORDER BY tickets.`issuenum`,AK.`issuenum` AS' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:790)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:675)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:69)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:178)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:116)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=unknown
java.version=12.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -keyring /Users/ry90/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/myuser/.eclipse_keyring

**Comment by uslss** [comment]
Seems that some part of statement was highlighted when export was started, so DBeaver was trying to export this highlighted part only
