### ISSUE TITLE
Print ERD button isn't working in case when search isn't empty

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6124]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version EA 6.1.1
#### Describe the problem you're observing:
Print ERD button isn't working in case when search isn't empty
#### Steps to reproduce, if exist:
1. Open any ERD
2. Try to search something
3.  Tap print button
#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/31996417/59790736-484bda80-92d9-11e9-9516-2fca1aed3c49.png)
`eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Wed Jun 19 21:26:35 MSK 2019
Failed to execute item null

org.eclipse.core.commands.NotHandledException: There is no handler to execute for command org.eclipse.ui.file.print
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:510)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:403)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:824)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:801)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)`

**Comment by serge-rider** [comment]
Print action doesn't work if diagram panel is not focused. It is not related to search directly.
Anyway, won't fix this now because of too big effect and too small improvement.

**Comment by kseniiaguzeeva** [comment]
https://dbeaver.testquality.com defect [D44](https://dbeaver.testquality.com/project/8805/result/1760397/defect/6098). Do not remove or edit.
