### ISSUE TITLE
NPE appears when trying to open ERD

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6149]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.1.1

#### Connection specification:
- Database name and version Greenplum

#### Describe the problem you're observing:
NPE appears when trying to open ERD
#### Steps to reproduce, if exist:
1. Open schema or table
2. Try to open erd 
#### Include any warning/errors/backtraces from the logs
```eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/.dbeaver4/

org.jkiss.dbeaver.model
Error
Tue Jun 25 00:21:08 MSK 2019


java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:250)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:112)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getAllObjects(JDBCCompositeCache.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getAllObjects(JDBCCompositeCache.java:1)
	at org.jkiss.dbeaver.model.impl.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:80)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getReferences(PostgreTable.java:167)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.collectDatabaseTables(ERDEditorEmbedded.java:267)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:190)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:174)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:149)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)```

**Comment by uslss** [comment]
verified
