### ISSUE TITLE
6.1.1: Unexpected driver error occurred while connecting to database: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by Walkeer** [dbeaver/dbeaver#6151]
Hello,

I am using DBeaver with gooddada ADS driver (wrapper over vertica JDBC) for 3 years now. After today update to DBeaver 6.1.1, I am getting this error:

Unexpected driver error occurred while connecting to database
  javax/xml/bind/DatatypeConverter

Tried on both JDK8 and JDK11. The only working combination is 6.1.0 with oracle JDK 8, it does not work with openJDK 11.

debug.log:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-06-25 08:23:18.049 - Connection failed (F4DD66D6-4E83-F07B-6A15-B0E059AC4B3E-16ae503801c-cb9e62eb51031b)
2019-06-25 08:23:18.052 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:185)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:88)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:68)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:778)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.gooddata.datawarehouse.jdbc.driver.RestClient$BasicAuthentication.authenticate(RestClient.java:267)
	at com.gooddata.datawarehouse.jdbc.driver.RestClient$BasicAuthentication.addAuthenticationHeaders(RestClient.java:260)
	at com.gooddata.datawarehouse.jdbc.driver.RestClient.httpGet(RestClient.java:138)
	at com.gooddata.datawarehouse.jdbc.driver.RestClient.getInstanceEndpointsLink(RestClient.java:125)
	at com.gooddata.datawarehouse.jdbc.driver.RestClient.readEndpointsInfo(RestClient.java:119)
	at com.gooddata.datawarehouse.jdbc.driver.RestClient.getEndpointsInfo(RestClient.java:114)
	at com.gooddata.datawarehouse.jdbc.driver.ConnectionFactory.resolveJdbcProxies(ConnectionFactory.java:119)
	at com.gooddata.datawarehouse.jdbc.driver.ConnectionFactory.createAuthenticatedClient(ConnectionFactory.java:165)
	at com.gooddata.datawarehouse.jdbc.driver.ConnectionFactory.createConnection(ConnectionFactory.java:84)
	at com.gooddata.datawarehouse.jdbc.driver.DatawarehouseDriver.connect(DatawarehouseDriver.java:78)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 12 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more


```

**Comment by dorbae** [comment]
I don't know why it didn't operate in JDK8. However, since JDK9, 'java.xml.bind' package has been not involved in JRE basically. Therefore, how about trying to do likes below?

※ Suppose AWS REDSHIFT connection is equal to your GOODDATA_DATAWAREHOUSE connection.

![스크린샷 2019-06-25 15 55 00](https://user-images.githubusercontent.com/25657896/60076816-76ab3900-9763-11e9-8f8e-5a7115ed30ab.png)

![스크린샷 2019-06-25 15 57 53](https://user-images.githubusercontent.com/25657896/60076818-76ab3900-9763-11e9-9080-1a4b13e4bdc6.png)

![스크린샷 2019-06-25 16 07 56](https://user-images.githubusercontent.com/25657896/60076820-76ab3900-9763-11e9-87dc-543dbfb1793c.png)

**Comment by Walkeer** [comment]
I will try your suggestion, howeve I just asked our developpers and turned out our JDBC driver is not ready for JDK11, which is now part of Dbeaver and cannot be ommited during installation (there used to be JDK option during installation)

**Comment by Walkeer** [comment]
it works! many thanks

**Comment by dorbae** [comment]
Your welcome :)

**Comment by serge-rider** [comment]
Thanks for the bug report. We'll fix Redshift driver config in the next version

**Comment by dorbae** [comment]
Actually, Redshift driver doesn't need javax.xml.bind package.
I just showed the example of how to add an external library for 'Walkeer' by Redshift. Because I had no gooddada ADS driver.
Therefore, I think you don't have to add it in bug report and milestone.
Thank you.

@serge-rider

**Comment by serge-rider** [comment]
@dorbae Ok, thanks for the information. Closing.
