### ISSUE TITLE
Silent crash by startup 

### ISSUE THREAD

**Issue by medickse** [dbeaver/dbeaver#6166]
#### System information: 
- Operating system Mac OS 10.12.6 (16G2016)
- DBeaver version 6.1.1
- Java version 8 update 191 (build 1.8.0_191-b12)
- Additional extensions

#### Connection specification:
- Database name and version Oracle PL/SQL 12C

- Driver name ojdbc8.jar 12.2.0.1.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Dbeaver used to run properly. I shut it down as usual, since then it won't start (splash screen shows for a moment, goes away).
#### Steps to reproduce, if exist:
Removed and reinstalled, updated, problem persists. 
#### Include any warning/errors/backtraces from the logs
Running from CMDline:
`OSX-MedicksE:~ medickse$ /Applications/DBeaver.app/Contents/MacOS/dbeaver 
2019-06-26 15:24:50.854 - Create display
2019-06-26 15:24:51.220 - > Start org.jkiss.dbeaver.core [6.1.1.201906240635]
2019-06-26 15:24:51.223 - DBeaver 6.1.1.201906240635 is starting
2019-06-26 15:24:51.223 - OS: Mac OS X 10.12.6 (x86_64)
2019-06-26 15:24:51.223 - Java version: 1.8.0_191 by Oracle Corporation (64bit)
2019-06-26 15:24:51.223 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2019-06-26 15:24:51.224 - Instance path: 'file:/Users/medickse/.dbeaver4/'
2019-06-26 15:24:51.224 - Memory available 77Mb/910Mb
2019-06-26 15:24:51.234 - Starting RMI server at 22472
2019-06-26 15:24:51.303 - Run workbench
2019-06-26 15:24:51.308 - > Start org.eclipse.e4.ui.workbench.swt [0.14.500.v20190214-0851]
2019-06-26 15:24:51.309 - > Start org.eclipse.e4.core.services [2.1.400.v20181215-2145]
2019-06-26 15:24:51.310 - > Start org.eclipse.e4.core.contexts [1.8.0.v20190214-1713]
2019-06-26 15:24:51.316 - > Start org.eclipse.e4.ui.services [1.3.400.v20190212-2214]
2019-06-26 15:24:51.343 - > Start org.eclipse.e4.ui.di [1.2.500.v20190214-1316]
2019-06-26 15:24:51.373 - > Start org.eclipse.emf.common [2.15.0.v20181220-0846]
2019-06-26 15:24:51.387 - > Start org.eclipse.emf.ecore [2.17.0.v20190116-0940]
2019-06-26 15:24:51.432 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-06-26 15:24:51.552 - > Start org.eclipse.core.filesystem [1.7.300.v20190218-2054]
2019-06-26 15:24:51.580 - > Start org.eclipse.core.resources [3.13.300.v20190218-2054]
2019-06-26 15:24:51.691 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.400.v20190224-1542]
2019-06-26 15:24:51.699 - > Start org.eclipse.core.expressions [3.6.300.v20190218-1215]
2019-06-26 15:24:51.709 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.500.v20190220-1002]
2019-06-26 15:24:51.797 - > Start org.eclipse.e4.ui.bindings [0.12.400.v20190131-1604]
2019-06-26 15:24:51.834 - > Start org.eclipse.e4.core.di.extensions [0.15.300.v20190213-1308]
2019-06-26 15:24:52.111 - > Start org.eclipse.e4.ui.css.swt [0.13.400.v20190223-1254]
2019-06-26 15:24:52.538 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.200.v20190212-2214]
2019-06-26 15:24:52.636 - > Start org.jkiss.dbeaver.ui [5.1.26.201906240635]
2019-06-26 15:24:52.806 - > Start org.eclipse.equinox.p2.core [2.6.0.v20190215-2242]
2019-06-26 15:24:52.807 - > Start org.eclipse.equinox.p2.operations [2.5.300.v20190202-1801]
2019-06-26 15:24:52.810 - > Start org.eclipse.equinox.p2.engine [2.6.200.v20190215-2242]
2019-06-26 15:24:52.814 - > Start org.eclipse.equinox.p2.metadata [2.4.300.v20190215-2242]
2019-06-26 15:24:52.822 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.200.v20181102-0649]
2019-06-26 15:24:52.823 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-06-26 15:24:52.827 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-06-26 15:24:52.827 - > Start org.eclipse.equinox.p2.repository [2.4.300.v20190215-2242]
2019-06-26 15:24:52.839 - DBeaver is stopping
2019-06-26 15:24:52.839 - Stop RMI server
2019-06-26 15:24:52.890 - < Stop org.jkiss.dbeaver.ext.mssql.ui [1.0.10.201906240635]
2019-06-26 15:24:52.890 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.105.201906240635]
2019-06-26 15:24:52.890 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.96.201906240635]
2019-06-26 15:24:52.890 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.17.201906240635]
OSX-MedicksE:~ medickse$ 
`

LOG info:

`!ENTRY org.eclipse.core.jobs 4 2 2019-06-26 15:24:52.917
!MESSAGE An internal error occurred during: "Executing the early startup extensions".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:344)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:286)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:772)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:72)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:78)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

Any help will be appreciated.

**Comment by serge-rider** [comment]
Please try to reset workspace- https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
This may happen after series of version upgrades or unsafe program shutdowns.

**Comment by medickse** [comment]
> Please try to reset workspace- https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
> This may happen after series of version upgrades or unsafe program shutdowns.

This worked! Thank you very much.
