### ISSUE TITLE
SELECT generates errors on zOS DB2

### ISSUE THREAD

**Issue by MocniMax** [dbeaver/dbeaver#6169]
#### System information: 
- MS Windows Server 208 R2
- DBeaver 6.1.1
- Java bundled with DBeaver installation
- No Additional extensions

#### Connection specification:
- DB2 for z/OS V11 
- Driver: DB2 for z/OS from IBM Data Studio 4.1.3 - com.ibm.datatools.db2_2.2.201.v20170814_2141 
- No  tunnels or proxies used

#### Describe the problem you're observing:
Simple SELECT * generates one of two errors:
1. SQL Error [58009]: [jcc][t4][2034][11148][3.69.56] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [58009]: [jcc][t4][2034][11148][3.69.56] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.DisconnectRecoverableException: [jcc][t4][2034][11148][3.69.56] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009
	at com.ibm.db2.jcc.am.gd.a(Unknown Source)
	at com.ibm.db2.jcc.am.gd.a(Unknown Source)
	at com.ibm.db2.jcc.t4.y.j(Unknown Source)
	at com.ibm.db2.jcc.t4.y.c(Unknown Source)
	at com.ibm.db2.jcc.t4.y.v(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.b(Unknown Source)
	at com.ibm.db2.jcc.t4.p.a(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.i(Unknown Source)
	at com.ibm.db2.jcc.am.yo.ib(Unknown Source)
	at com.ibm.db2.jcc.am.yo.a(Unknown Source)
	at com.ibm.db2.jcc.am.yo.e(Unknown Source)
	at com.ibm.db2.jcc.am.yo.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 6 more

2. SQL Error: Internal jdbc driver error

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:306)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 6 more
Caused by: java.nio.charset.UnsupportedCharsetException: Cp1141
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.ibm.db2.jcc.am.q.<init>(Unknown Source)
	at com.ibm.db2.jcc.am.p.a(Unknown Source)
	at com.ibm.db2.jcc.am.Agent.getByteToCharConverter(Unknown Source)
	at com.ibm.db2.jcc.t4.gc.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.n(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.j(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.d(Unknown Source)
	at com.ibm.db2.jcc.t4.p.c(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.j(Unknown Source)
	at com.ibm.db2.jcc.am.yo.kb(Unknown Source)
	at com.ibm.db2.jcc.am.yo.a(Unknown Source)
	at com.ibm.db2.jcc.am.yo.e(Unknown Source)
	at com.ibm.db2.jcc.am.yo.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	... 7 more

#### Steps to reproduce, if exist:
Double click on any table or execute SELECT *

#### Include any warning/errors/backtraces from the logs
Here are both log files
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3333798/dbeaver-debug.log)
[log.log](https://github.com/dbeaver/dbeaver/files/3333801/log.log)

Unfortunately, DBeaver 6.1 is still unusable for z/OS DB2 usage. Latest working DBeaver version is 6.0.1

Best regards

**Comment by serge-rider** [comment]
Basically all selects (including metadata reading) fail with the same error `UnsupportedCharsetException: Cp1141`. However this encoding must be supported.

If it worked in dbeaver before 6.1.1 version then you could try Early Access version (https://dbeaver.io/files/ea) which contains improved Java SDK. no other ideas so far..

**Comment by MocniMax** [comment]
Looks better with 6.1.2 EA. Will wait until it is released to make complete test.

Thanks.

**Comment by uslss** [comment]
closed without testing
