### ISSUE TITLE
Error in Postgres parameter binding (syntax near "c32")

### ISSUE THREAD

**Issue by daevidvincent** [dbeaver/dbeaver#6179]
#### System information: 
- Windows 10
- DBeaver version 6.1.1.201906240635

#### Connection specification:
- PostgreSQL JDBC Driver
- No tunnels or proxies (SSH, SOCKS, etc)? Connect from Windows host to local guest virtualbox VM and docker postgres container

#### Describe the problem you're observing:

Was super excited to see you had parameters, then very sad to see they didn't work...

#### Steps to reproduce, if exist:

Pass in parameters to a stored procedure that is known to work without them. Get prompt for values. DBeaver throws exception.

#### Include any warning/errors/backtraces from the logs
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ERROR: syntax error at or near "c32"
  Position: 52

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "c32"
  Position: 52

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)

	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)

	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
```
![image](https://user-images.githubusercontent.com/20825058/60305053-32996f00-98f0-11e9-9027-bda6c68f6fb0.png)

**Comment by aonnikov** [comment]
@daevidvincent you can pass enquoted parameters when needed, i.e. `'e8615680-4379-49de-84f6-3e62987b2cdb'`
