### ISSUE TITLE
!MESSAGE Se produjo un error interno durante: "Executing the early startup extensions".

### ISSUE THREAD

**Issue by AngelGiraldoS** [dbeaver/dbeaver#6183]
HI when i try to open the dbeaver, basically it doesn't open. When i check the file .log in the .metada folder and it shows this error:

!SESSION 2019-06-28 08:50:49.389 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_CO
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.ui.workbench 4 2 2019-06-28 08:50:51.251
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.p2.ui.ProvisioningUI.getDefaultUI(ProvisioningUI.java:60)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.rememberMigrationCompleted(MigrationSupport.java:228)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.performMigration(MigrationSupport.java:88)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.earlyStartup(AutomaticUpdateScheduler.java:78)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2019-06-28 08:50:51.252
!MESSAGE Se produjo un error interno durante: "Executing the early startup extensions".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:344)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:286)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:772)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:72)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:78)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

-I'm using Linux Mint.

**Comment by serge-rider** [comment]
This may happen if you upgraded from some old version. Or in case of workspace corruption (e.g. after unexpected reboot).
Please try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by AngelGiraldoS** [comment]
Thanks, it's working now
