### ISSUE TITLE
Cp037 Error in version 6.1.1 with install + jre

### ISSUE THREAD

**Issue by mkhouse8** [dbeaver/dbeaver#6197]
When connecting to DB2 on Z/OS the install + JRE package causes an internal error to be generated. This error does not happen when using DBeaver in the zip archive install. 

If you rename the install jre folder to jre-old DBeaver will perform as expected. 

Installation Machine - DBeaver 6.1.1, Microsoft Windows [Version 10.0.17763.557]
C:\>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
---------
DBeaver JRE 
C:\Program Files\DBeaver\jre\bin>java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
---------
Logs:
!ENTRY org.jkiss.dbeaver.model 2 0 2019-06-26 13:24:45.228
!MESSAGE Project [P/General] already added
!SESSION 2019-07-01 08:46:25.439 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-01 08:47:03.863
!MESSAGE Error executing query
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-01 08:47:03.863
!MESSAGE SQL Error: Internal jdbc driver error
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-07-01 08:47:03.863
!MESSAGE Internal jdbc driver error
!STACK 0
java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:306)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.charset.UnsupportedCharsetException: Cp037
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.ibm.db2.jcc.am.r.<init>(Unknown Source)
	at com.ibm.db2.jcc.am.q.a(Unknown Source)
	at com.ibm.db2.jcc.am.Agent.getByteToCharConverter(Unknown Source)
	at com.ibm.db2.jcc.t4.gc.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.n(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.j(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.d(Unknown Source)
	at com.ibm.db2.jcc.t4.p.c(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.j(Unknown Source)
	at com.ibm.db2.jcc.am.fp.mb(Unknown Source)
	at com.ibm.db2.jcc.am.fp.a(Unknown Source)
	at com.ibm.db2.jcc.am.fp.e(Unknown Source)
	at com.ibm.db2.jcc.am.fp.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	... 12 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2019-07-01 08:47:03.863
!MESSAGE Cp037
!STACK 0
java.nio.charset.UnsupportedCharsetException: Cp037
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.ibm.db2.jcc.am.r.<init>(Unknown Source)
	at com.ibm.db2.jcc.am.q.a(Unknown Source)
	at com.ibm.db2.jcc.am.Agent.getByteToCharConverter(Unknown Source)
	at com.ibm.db2.jcc.t4.gc.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.n(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.j(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.d(Unknown Source)
	at com.ibm.db2.jcc.t4.p.c(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.j(Unknown Source)
	at com.ibm.db2.jcc.am.fp.mb(Unknown Source)
	at com.ibm.db2.jcc.am.fp.a(Unknown Source)
	at com.ibm.db2.jcc.am.fp.e(Unknown Source)
	at com.ibm.db2.jcc.am.fp.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-01 08:48:02.512
!MESSAGE Close active transactions - error
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-01 08:48:02.513
!MESSAGE SQL Error [58009]: [jcc][t4][2034][11148][4.19.26] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-07-01 08:48:02.513
!MESSAGE [jcc][t4][2034][11148][4.19.26] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009
!STACK 0
com.ibm.db2.jcc.am.DisconnectRecoverableException: [jcc][t4][2034][11148][4.19.26] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009
	at com.ibm.db2.jcc.am.kd.a(Unknown Source)
	at com.ibm.db2.jcc.am.kd.a(Unknown Source)
	at com.ibm.db2.jcc.t4.y.j(Unknown Source)
	at com.ibm.db2.jcc.t4.y.c(Unknown Source)
	at com.ibm.db2.jcc.t4.y.v(Unknown Source)
	at com.ibm.db2.jcc.t4.z.c(Unknown Source)
	at com.ibm.db2.jcc.t4.n.c(Unknown Source)
	at com.ibm.db2.jcc.t4.b.readLocalRollback_(Unknown Source)
	at com.ibm.db2.jcc.am.Connection.readRollback(Unknown Source)
	at com.ibm.db2.jcc.am.Connection.flowRollback(Unknown Source)
	at com.ibm.db2.jcc.t4.b.flowRollback(Unknown Source)
	at com.ibm.db2.jcc.am.Connection.rollbackX(Unknown Source)
	at com.ibm.db2.jcc.am.Connection.rollback(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.rollback(JDBCExecutionContext.java:401)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler$EndTransactionTask.run(DataSourceHandler.java:290)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:285)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:212)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Please check how it works in EarlyAccess version (https://dbeaver.io/files/ea) - it contains fixed JDK..

**Comment by mkhouse8** [comment]
> Please check how it works in EarlyAccess version (https://dbeaver.io/files/ea) - it contains fixed JDK..

I did receive the same issue as before with the EarlyAccess version. 
I downloaded a copy of the jre from https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#x64_win-jre 
and replaced the version in the install folder and this resolved the issue. 

Not satisfied with the answer. After a reinstalling and moving files and folders over to the jre folder by hand a few at a time, I was able to determine the culprit file is DBeaver\jre\lib\modules file

I reinstalled DBeaver once more and tested if the query failed, it did as expected. I then copied the modules file from the openjdk folder I downloaded and replaced the one modules file in the installed jre\lib folder. Tested the query again and it completed successfully. 

I hope this aids in your efforts.
Thanks.
--------
Log:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:306)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 11 more
Caused by: java.nio.charset.UnsupportedCharsetException: Cp037
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.ibm.db2.jcc.am.r.<init>(Unknown Source)
	at com.ibm.db2.jcc.am.q.a(Unknown Source)
	at com.ibm.db2.jcc.am.Agent.getByteToCharConverter(Unknown Source)
	at com.ibm.db2.jcc.t4.gc.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.a(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.n(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.j(Unknown Source)
	at com.ibm.db2.jcc.t4.bb.d(Unknown Source)
	at com.ibm.db2.jcc.t4.p.c(Unknown Source)
	at com.ibm.db2.jcc.t4.vb.j(Unknown Source)
	at com.ibm.db2.jcc.am.fp.mb(Unknown Source)
	at com.ibm.db2.jcc.am.fp.a(Unknown Source)
	at com.ibm.db2.jcc.am.fp.e(Unknown Source)
	at com.ibm.db2.jcc.am.fp.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	... 12 more

**Comment by serge-rider** [comment]
Thanks for the investigation. Bundled JDK misses jdk.charset module (specifically designed to support additional charsets).
just added it in the bundle. Could you test new DBeaver Early Access build?

**Comment by mkhouse8** [comment]
I can confirm that the latest Early Access build (01-Jul-2019 17:26) did not resolve the issue. 

Looking at the 2 modules files. 
The one included in the Early Access package has a size of 23,608 KB
The one included in the OpenJDK11U-jre_x64...11.0.3_7 has a size of 91,049 KB
Interestingly to me I do not find a modules file Oracle Java installation so it must be specific to the OpenJDK software.

![Capture](https://user-images.githubusercontent.com/33190780/60456084-ec991f80-9bfd-11e9-970c-f3122c41b90c.PNG)

**Comment by serge-rider** [comment]
@mkhouse8 thanks for validating. My bad, I've published wrong JRE bundle again. 
Could you test it one more time?

**Comment by mkhouse8** [comment]
YAY!!! That works! Thanks.

**Comment by mkhouse8** [comment]
Also interesting to note that modules file is still considerably smaller than the openJDK version, but it works :-)

**Comment by serge-rider** [comment]
Great, thanks for testing 👍 

Yes, bundled JDK significantly smaller than original. That is the point of Java modules. DBeaver doesn't need most of packages included in JDK (dev tools, most of UI, JavaFX, AOT and different enterprise packages).

And 90% of driver also don't need this. If some of them will need some legacy stuff then we'll add it as a separate dependency.
