### ISSUE TITLE
clickhouse array(float64) error

### ISSUE THREAD

**Issue by ghbarrie** [dbeaver/dbeaver#6201]
System information:
Operating system (distribution) and version
![image](https://user-images.githubusercontent.com/52424799/60463014-baf67780-9c42-11e9-9cc8-76dce7be2b7f.png)

DBeaver version
![image](https://user-images.githubusercontent.com/52424799/60463037-c9dd2a00-9c42-11e9-81c3-62ee704ea6b5.png)

Connection specification:
Database name and version
[root@dt_ae1 ~]# clickhouse server --version
ClickHouse server version 19.6.2.1.

![image](https://user-images.githubusercontent.com/52424799/60463069-e4170800-9c42-11e9-8b8c-9f4402c7f111.png)

Describe your question:

Hi, I have seen a similar issue:
clickhouse array support #5598

But still I have an issue.

I installed the latest version of DBeaver:
![image](https://user-images.githubusercontent.com/52424799/60461946-f2aff000-9c3f-11e9-9d7a-9f9010f7b301.png)

I have the latest version of Java (just in case):
![image](https://user-images.githubusercontent.com/52424799/60462028-27bc4280-9c40-11e9-9c37-ed9c079c8704.png)

I have the latest clickhouse driver:
![image](https://user-images.githubusercontent.com/52424799/60462062-3dca0300-9c40-11e9-8e89-0bef02813b36.png)

But when I run a query with Array(Float64) and Array(Int32)/Array(Int64) columns, I get the following error:
	org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from JDBC array
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:62)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: SQL Error
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:224)
	... 17 more
Caused by: java.sql.SQLFeatureNotSupportedException
	at ru.yandex.clickhouse.ClickHouseArray.getResultSet(ClickHouseArray.java:70)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromResultSet(JDBCCollection.java:313)
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:222)
	... 17 more

![image](https://user-images.githubusercontent.com/52424799/60462317-e11b1800-9c40-11e9-899f-c067f795fac7.png)

![image](https://user-images.githubusercontent.com/52424799/60462377-0576f480-9c41-11e9-80b4-ebf00167c4e5.png)

I have played with the driver settings, I have also played in all the connection settings (and there are plenty), but just can't seem to find a way to view these arrays?

**Lastly, I know this is possible, one of our BI guys can see the array's, but he does not recall what he did to be able to see it. (we compared drivers, as well as connection settings, and found nothing significant).**

In sqlworkbench I can see Array(string) at least, but same problem with all the other arrays. 
I tried dbeaver EE, but has the same problem.
I tried installing all eclipse db libraries, and still did not work. 

Please help.

#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by serge-rider** [comment]
I can't reproduce this bug. I can read Float64 arrays without any issues. Server and driver versions are the same.

Please post table DDL + INSERT statement to reproduce this. Maybe it is something specific to data itself.

**Comment by ghbarrie** [comment]
> I can't reproduce this bug. I can read Float64 arrays without any issues. Server and driver versions are the same.
> 
> Please post table DDL + INSERT statement to reproduce this. Maybe it is something specific to data itself.

I tried to export, but exports the array's as NULL.

I know it works, as one of my co-workers can see the array's. However I can't.

Same drivers, same versions.

There must be a setting somewhere (mine are all at default after install), that is probably causing this?

Any advise?

**Comment by serge-rider** [comment]
The problem is definitely not in the table declaration but in data itself.
Could you write some INSERT statement (1 row)which will produce such error?

**Comment by ghbarrie** [comment]
> The problem is definitely not in the table declaration but in data itself.
> Could you write some INSERT statement (1 row)which will produce such error?

The data is fine. The person sitting next to me can see the data. It must be one of my DBeaver settings, or Clickhouse connection settings.

**Comment by serge-rider** [comment]
I've mistaken, you have more fesh driver. It returns arrays in a different format, will check it.
Workaround: downgrade driver version to 0.1.50 (you can do this in driver editor dialog)

**Comment by serge-rider** [comment]
Well, in the latest driver versions they changed data type system. Now driver returns plan Java type names instead of Clickhouse type names.
Ok, we can handle this. I've improved fetch of numeric arrays in Clickhouse. But driver 0.1.54 is broken and not capable to read String arrays at all (it fails with internal error once you try to fetch them).
Maybe it makes sense to post a bug report to https://github.com/yandex/clickhouse-jdbc

Till next fixed Clickhouse driver version release I'd recommmend to use 0.1.50 version.

**Comment by ghbarrie** [comment]
> Well, in the latest driver versions they changed data type system. Now driver returns plan Java type names instead of Clickhouse type names.
> Ok, we can handle this. I've improved fetch of numeric arrays in Clickhouse. But driver 0.1.54 is broken and not capable to read String arrays at all (it fails with internal error once you try to fetch them).
> Maybe it makes sense to post a bug report to https://github.com/yandex/clickhouse-jdbc
> 
> Till next fixed Clickhouse driver version release I'd recommmend to use 0.1.50 version.

Thank you. Much appreciated!

**Comment by uslss** [comment]
verified
