### ISSUE TITLE
PostgreSQL: partitions create/drop/edit

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6203]
We need to add support of:
- Partition create
- Partition drop
- Partition properties edit/save

All this can be implemented in PGPartitionManager

**Comment by uslss** [comment]
Reopen.
Error when trying to create partition.
`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Dziyana/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Dziyana\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-08 22:18:24.170

org.jkiss.dbeaver.model
Error
Thu Aug 08 22:28:47 MSK 2019
class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema (org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular and org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3ac5e34e)

java.lang.ClassCastException: class org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular cannot be cast to class org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema (org.jkiss.dbeaver.ext.postgresql.model.PostgreTableRegular and org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3ac5e34e)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getSchema(PostgreTableBase.java:180)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableReal.getConstraints(PostgreTableReal.java:163)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableManager.getChildObjects(PostgreTableManager.java:66)
	at org.jkiss.dbeaver.ext.postgresql.edit.PostgreTableManager.getChildObjects(PostgreTableManager.java:1)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLStructEditor.createObjectReferences(SQLStructEditor.java:77)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:94)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:300)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
Partitions could be created (for already partitioned tables only), edited and deleted.
verified.
Created ticket #6494
