### ISSUE TITLE
Silent error performing "Export Data..." to CSV from an existing result query.

### ISSUE THREAD

**Issue by jamesbond3142** [dbeaver/dbeaver#6210]
#### System information: 
- OS: Fatdog64 Linux 803 (glibc 2.27, kernel 4.19.44)
- DBeaver: DBeaver 6.1.1 but I have tested this with 6.1.0 and 6.0.5 - same problem
- Java: JDK 1.8 update 151
- Extensions: None.

#### Connection specification:
- Database: Postgresql 9.1 on Debian Linux
- Driver name: PostgreSQL Native Driver [PostgreSQL 9.4.1212.jre7]) - this is the driver that DBeaver auto-downloads and auto-installs for me
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No. this is a direct database connection

#### Describe the problem you're observing:
- Unable to perform "Export Data..." to CSV from an existing result query.

#### Steps to reproduce, if exist:
1. Run an SQL query in SQL editor.
2. One the resultset is available, right click on the top-right corner and choose "Export Data..."
3. Fill in the parameters (export to CSV in my case) and click "Finish" to produce the report.
4. Expected result: CSV file produced.
5. Actual result: Nothing happens.

Note1: whether or not "open new connection" is checked, the result is the same.
Note2: the resultset itself is produced correctly. Only the export process fails.
Note3: I have changed the connection's "isolation level" but it has no impact.

Running dbeaver from console produces the following error messages.

```
2019-07-03 13:12:57.327 - Initiate connection to PostgreSQL database [portaldb@portal1] for Data transfer producer
2019-07-03 13:13:02.542 - org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.getTransactionIsolation(JDBCExecutionContext.java:261)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceAutoCommitHandler.updateElement(DataSourceAutoCommitHandler.java:94)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:454)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:124)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:46)
	at org.eclipse.ui.internal.commands.CommandService$1.run(CommandService.java:274)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.commands.CommandService.refreshElements(CommandService.java:278)
	at org.jkiss.dbeaver.ui.ActionUtils.lambda$0(ActionUtils.java:376)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4582)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
```

**Comment by jamesbond3142** [comment]
This seems to be postgresql jdbc problem. I replaced PostgreSQL 9.4.1212.jre7 with the latest one 42.2.6.jre7 and export works. However, it seems that the latest version of postgis (2.3.0) still pulls in 9.4.1208; so now I have two Postgresql JDBC driver, which is probably a bad idea.

If you can advise on how to handle this, it would be much appreciated. 

Thank you for dbeaver.

**Comment by serge-rider** [comment]
You don't need to add PostgreSQL driver jar manually - just change Maven artifact version:
![image](https://user-images.githubusercontent.com/6398845/60821800-8cc5ea00-a1a4-11e9-97cb-223d9e54fbd3.png)
Simply click on the cell with version number

**Comment by jamesbond3142** [comment]
Hi serge,

Thanks for the info. It's good to know.

The problem starts happening again for me now, even with the latest 42.2.6 driver, on dbeaver 6.1.5.

I have no idea on the innards of dbeaver, but tracing where the error message comes from brings me to here: [https://fossies.org/linux/dbeaver/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCExecutionContext.java](url) line 240 (method name: getTransactionIsolation) and it seems that you wait for TXN_INFO_READ_TIMEOUT (which has the value of 5000 - I suppose 5000ms, or 5 seconds?) before failing.

Now I have no idea whether 5s is reasonable enough delay (perhaps it is, except in most extreme cases?), but would it help to:
a) make the value configurable? and/or
b) instead of failing, return a sort of "default" isolation level (perhaps assuming the worst)?

Thank you.

**Comment by serge-rider** [comment]
This makes sense. However it is not clear why this problem with transaction isolation happens. Could you send full debug log, maybe it contains some clues. https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by jamesbond3142** [comment]
Log file attached.

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3520869/dbeaver-debug.log)

To be very clear, this is how I did it:
1. Launch dbeaver, which automatically opens the SQL editor with my script on it.
2. In the SQL Editor, I press Ctrl-Enter to execute the script. This takes a very long while (it is a heavy script) and during this time there is no error in the debug log.
3. Finally I can see the result set, and I can scroll through it. There is no error in the debug log as well.
4. Then I right-click the top-left corner of the result set, and choose "Export Data". The relevant option is I unchecked the "open a new connection" (I want to re-use the current connection with the hope that the data export will use the existing result set instead of re-running the query again that takes a long time).
5. I navigated through the "Export Data" dialog and as soon as I clicked "FInish", I've got the timeout error in the debug log. And the exported file is never created in the target location.

**Comment by jamesbond3142** [comment]
After this first timeout error, I can trigger the same error just by looking at the transaction control icon (the one where you can choose to do manual commit or auto-commit), and the log looks similar (this is a continuation from the log file above)

(This is while the result viewer still shows the result of the query).

```
2019-08-20 23:40:23.079 - org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.getTransactionIsolation(JDBCExecutionContext.java:261)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceAutoCommitHandler.updateElement(DataSourceAutoCommitHandler.java:91)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:434)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:122)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:45)
	at org.eclipse.ui.internal.commands.CommandService.registerElement(CommandService.java:314)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElement(SlaveCommandService.java:239)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForCommand(SlaveCommandService.java:231)
	at org.eclipse.ui.menus.CommandContributionItem.establishReferences(CommandContributionItem.java:698)
	at org.eclipse.ui.menus.CommandContributionItem.fill(CommandContributionItem.java:415)
	at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:64)
	at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:146)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:728)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:805)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:473)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:466)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:498)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1426)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1405)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:220)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:5180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4653)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

Thank you for looking into this.

**Comment by uslss** [comment]
seems issue is obsolete. If it is still actual - feel free to reopen it
