### ISSUE TITLE
DBeaver crashes during SQL script export with "Error reading Windows registry" NullPointerException

### ISSUE THREAD

**Issue by michaeljtbrooks** [dbeaver/dbeaver#6259]
#### System information: 
- Operating system (distribution) and version: Windows Server 2019
- DBeaver version 6.12.201907061627
- Java version 11.0.3+12-LTS
- Additional extensions MSSQL, MySQL connectors

#### Connection specification:
- Database name and version: Microsoft SQL Server 2017 Developer
- Driver name Microsoft JDBC Driver for SQL Server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Nope

#### Describe the problem you're observing:
Random crash of DBeaver during export of several database tables as SQL.

#### Steps to reproduce, if exist:
1) Open a MSSQL database. Right click several (>4) tables > Export Data > SQL.
2) Start the export
3) All of a sudden DBeaver will disappear. 

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 2 0 2019-07-10 17:21:25.758
!MESSAGE Error reading Windows registry
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-07-10 17:21:25.758
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.utils.WinRegistry8.readStringSubKeys(WinRegistry8.java:329)
	at org.jkiss.dbeaver.utils.WinRegistry8.readStringSubKeys(WinRegistry8.java:155)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.findLocalClients(MySQLDataSourceProvider.java:192)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.findLocalClientLocations(MySQLDataSourceProvider.java:135)
	at org.jkiss.dbeaver.ui.dialogs.connection.ClientHomesSelector.populateHomes(ClientHomesSelector.java:115)
	at org.jkiss.dbeaver.ui.dialogs.tools.ToolWizardDialog$NativeClientConfigDialog.createDialogArea(ToolWizardDialog.java:115)
	at org.jkiss.dbeaver.ui.dialogs.tools.ToolWizardDialog$NativeClientConfigDialog.createDialogArea(ToolWizardDialog.java:1)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:771)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.create(BaseDialog.java:72)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.dialogs.tools.ToolWizardDialog.openClientConfiguration(ToolWizardDialog.java:93)
	at org.jkiss.dbeaver.ui.dialogs.tools.ToolWizardDialog.buttonPressed(ToolWizardDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.mysql.tools.MySQLToolExport.execute(MySQLToolExport.java:40)
	at org.jkiss.dbeaver.ui.actions.common.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.ui.actions.common.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:334)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

**Comment by michaeljtbrooks** [comment]
Just reproduced this again. However, the logfile is showing a different set of errors:

!SESSION 2019-07-10 18:20:30.641 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2019-07-10 18:20:35.681
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-10 18:32:48.074
!MESSAGE SQL Error: The connection is closed.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-10 18:32:48.074
!MESSAGE The connection is closed.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1088)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.checkClosed(SQLServerStatement.java:1058)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.checkClosed(SQLServerResultSet.java:447)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:979)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:269)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:202)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:178)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:116)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-10 18:32:51.027
!MESSAGE SQL Error: The connection is closed.
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-10 18:32:51.027
!MESSAGE The connection is closed.
!STACK 0
com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1088)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.checkClosed(SQLServerStatement.java:1058)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.checkClosed(SQLServerResultSet.java:447)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:979)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:269)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:202)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:178)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:116)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.059
!MESSAGE Error formatting date
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.059
!MESSAGE Index 129 out of bounds for length 13
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 129 out of bounds for length 13
	at java.base/sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(Unknown Source)
	at java.base/java.util.GregorianCalendar.computeFields(Unknown Source)
	at java.base/java.util.GregorianCalendar.computeFields(Unknown Source)
	at java.base/java.util.Calendar.setTimeInMillis(Unknown Source)
	at java.base/java.util.Calendar.setTime(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.SimpleDateFormat.format(Unknown Source)
	at java.base/java.text.DateFormat.format(Unknown Source)
	at java.base/java.text.Format.format(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.getValueDisplayString(JDBCDateTimeValueHandler.java:180)
	at org.jkiss.dbeaver.model.sql.SQLUtils.convertValueToSQL(SQLUtils.java:611)
	at org.jkiss.dbeaver.model.sql.SQLUtils.convertValueToSQL(SQLUtils.java:598)
	at org.jkiss.dbeaver.tools.transfer.stream.exporter.DataExporterSQL.exportRow(DataExporterSQL.java:198)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:167)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:207)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:178)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:116)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:68)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.365
!MESSAGE Error formatting date
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.365
!MESSAGE 
!STACK 0
java.lang.ArrayIndexOutOfBoundsException

!ENTRY org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.389
!MESSAGE Error formatting date
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-07-10 18:33:03.389
!MESSAGE 
!STACK 0
java.lang.ArrayIndexOutOfBoundsException

**Comment by serge-rider** [comment]
How does it crash - the whole process dies or just current active operation is interrupted?

**Comment by michaeljtbrooks** [comment]
The entire DBeaver application crashes. It closes (the window vanishes) without any alert or error message displayed. Only examining the logs reveals the cause.

**Comment by serge-rider** [comment]
Could you try it in 6.1.4 version. Please use installer - it will setup Java 11 which will (should) fix the problem with Windows registry.

**Comment by serge-rider** [comment]
This should be fixed in 6.1.4 and later (there was an incorrect Java version detection and wrong native registry class was used)
Please reopen if it still happens.
