### ISSUE TITLE
JedisCluster Class For Redis Cluster - JedisMovedDataException

### ISSUE THREAD

**Issue by ktersius** [dbeaver/dbeaver#6267]
We are using an AWS Redis Cluster and are getting the JedisMovedDataException on retrieval of some of the KEYS. As I understand we need to be using the Cluster option to connect to the cluster.

How do we setup a connection to a cluster or is this managed for us already?

```
org.jkiss.dbeaver.model.exec.DBCException: MOVED 11169 172.31.12.48:6379
	at com.dbeaver.ee.redis.exec.RedisBaseStatement.handleExecuteError(RedisBaseStatement.java:157)
	at com.dbeaver.ee.redis.exec.RedisKeyGetStatement.executeStatement(RedisKeyGetStatement.java:79)
	at com.dbeaver.ee.redis.model.RedisKey.readData(RedisKey.java:253)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 11169 172.31.12.48:6379
	at redis.clients.jedis.Protocol.processError(Protocol.java:115)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:259)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:248)
	at redis.clients.jedis.Jedis.get(Jedis.java:153)
	at com.dbeaver.ee.redis.exec.RedisKeyGetStatement.executeStatement(RedisKeyGetStatement.java:60)
	... 6 more

```

**Comment by serge-rider** [comment]
Redis cluster support will be added in the next version. 
Note: you need to have direct access to cluster nodes. It may cause problem if you connecting thru SSH tunnel.

**Comment by ktersius** [comment]
I've downloaded the latest version 6.2 and I've updated my redis configuration for cluster mode. Unfortunately if I tick the cluster option I'm just getting a timeout when connecting to the cluster. If I untick it I can at least connect to the cluster and view the keys.

```
Error scanning Redis keys
  Could not get a resource from the pool
  Could not get a resource from the pool
    Failed connecting to host 172.31.28.113:6379
    Failed connecting to host 172.31.28.113:6379
      connect timed out
      connect timed out
```
