### ISSUE TITLE
NullPointerException when starting plpgsql debugger

### ISSUE THREAD

**Issue by TimoStolz** [dbeaver/dbeaver#6273]
#### System information: 
- Ubuntu 19.04
- tested with 5.3.3, 6.0.0, 6.1.2 (both community- and enterprise-edition)
- tested with openjdk 8, openjdk 11

#### Connection specification:
- tested with PostgresSQL 10.9 and 11.4
- database name was ilajnafsy, all tests were done as superuser
- org.postgresql.Driver
- No tunnels, no SSH. Tested with local and remote hosts.

#### Describe the problem you're observing:
- When starting the debug extension for PostgreSQL, there is a NullPointerException popping up. The following stack trace is found in the logs. (This is the current early access enterprise edition, but it's almost the same in the other tested versions.)
 ```
!ENTRY org.eclipse.core.jobs 4 2 2019-07-12 21:21:50.144
!MESSAGE Während "Neue_Konfiguration wird gestartet" ist ein interner Fehler aufgetreten.
!STACK 0
java.lang.NullPointerException
        at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.attachGlobal(PostgreDebugSession.java:434)
        at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.attach(PostgreDebugSession.java:464)
        at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugController.createSession(PostgreDebugController.java:51)
        at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugController.createSession(PostgreDebugController.java:1)
        at org.jkiss.dbeaver.debug.DBGBaseController.openSession(DBGBaseController.java:71)
        at org.jkiss.dbeaver.debug.core.model.DatabaseDebugTarget.connect(DatabaseDebugTarget.java:181)
        at org.jkiss.dbeaver.debug.core.DatabaseLaunchDelegate.launch(DatabaseLaunchDelegate.java:56)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

#### Steps to reproduce, if exist:
- install latest dbeaver (e.g. from eclipse marketplace)
- install latest debug extension for plpgsql (e.g. from eclipse marketplace)
- create a database (e.g. named ilajnafsy)
- connect to this database using dbeaver
- create some plpgsql function
- click on the debug icon and add a new debug configuration. All optional settings go with the defaults. For the required settings, choose your database, choose "function" (instead of trigger), choose "global" (instead of local), then finally choose your function.

**Comment by serge-rider** [comment]
This happens only in case of global attachment during session logging.
Thanks for the bug report.
