### ISSUE TITLE
version 6.1.2  on Manjaro+KDE，I meet the issue about GUI 

### ISSUE THREAD

**Issue by iminto** [dbeaver/dbeaver#6299]
This issue looks like this [https://github.com/dbeaver/dbeaver/issues/5593](https://github.com/dbeaver/dbeaver/issues/5593)，but i can't resolve it by its method.

Manjaro 18.0.4 Illyria
DE: KDE 5.60.0 / Plasma 5.16.3
GTK Theme: Breath [GTK2/3]
JDK: 8 or 12

the interface looks like these:
![sc_20190718224719](https://user-images.githubusercontent.com/284101/61467403-20ba6180-a9ae-11e9-9d3f-559c0ee2f105.png)
![sc_20190718224745](https://user-images.githubusercontent.com/284101/61467643-8c043380-a9ae-11e9-8e7b-944afe96ed11.png)

**I can't input SQL in the script widows ,and even can't quit the application.The window turns gray and cannot be interacted**

this is the error:
```
(DBeaver:2490): Gtk-WARNING **: 22:52:56.642: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
2019-07-18 22:52:56.847 - > Start org.jkiss.dbeaver.core [6.1.2.201907061627]
2019-07-18 22:52:56.850 - DBeaver 6.1.2.201907061627 is starting
2019-07-18 22:52:56.851 - OS: Linux 4.19.59-1-MANJARO (amd64)
2019-07-18 22:52:56.851 - Java version: 1.8.0_201 by Oracle Corporation (64bit)
2019-07-18 22:52:56.851 - Install path: '/soft/dbeaver'
2019-07-18 22:52:56.851 - Instance path: 'file:/home/koudai/.dbeaver4/'
2019-07-18 22:52:56.851 - Memory available 109Mb/910Mb
2019-07-18 22:52:56.858 - Starting RMI server at 41472
2019-07-18 22:52:56.944 - Run workbench

(DBeaver:1922): Gdk-CRITICAL **: 22:47:07.673: The window 0x7fcfce20dc80 already has a drawing context. You cannot call gdk_window_begin_draw_frame() without calling gdk_window_end_draw_frame() first.
2019-07-18 22:47:07.675 - Event loop exception
org.eclipse.swt.SWTError: No more handles
        at org.eclipse.swt.SWT.error(SWT.java:4725)
        at org.eclipse.swt.SWT.error(SWT.java:4614)
        at org.eclipse.swt.SWT.error(SWT.java:4585)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:530)
        at org.eclipse.swt.widgets.Control.drawBackground(Control.java:219)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:6751)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:6035)
        at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4135)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1407)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1584)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4577)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:201)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

```

**Comment by uslss** [comment]
is it still actual?

**Comment by iminto** [comment]
Now I use   DBeaver  with version 7.0.0.202003021717，It works.
