### ISSUE TITLE
Can't read date column value with zero month

### ISSUE THREAD

**Issue by FlorjanCamlek** [dbeaver/dbeaver#6301]
#### System information: 
- Operating system (distribution) and version:  Windows 10 10.0 (amd64)
- DBeaver version:  DBeaver 6.1.2.201907061627 
- Java version: 11.0.3 by Oracle Corporation (64bit)
- Additional extensions: NA

#### Connection specification:
- Database name and version: mysql  Ver 15.1 Distrib 10.2.17-MariaDB, for Linux (x86_64)
- Driver name: MYSQL 8+
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Dates with a zero month are not displayed/read properly, throwing the exception attached below (the same may be true for '0' years and days?). This exception also prevents exporting of data from DBeaver. I have tried changing the connection zeroDateTimeBehaviour from EXCEPTION to ROUND, but the exception still occurs. I notice there is also a 'set to null' option. Is it possible to just display the date as is, even if it is invalid?

#### Steps to reproduce, if exist:
Create  table with a date field. Enter a 'zero' month e.g. 1920-00-18 (may need to do this outside DBeaver). Look at table in DBeaver, hopefully you will see the error.

#### Include any warning/errors/backtraces from the logs
2019-07-19 11:26:59.009 - Can't read column 'date_of_birth' value
java.lang.IllegalArgumentException: MONTH
	at java.base/java.util.GregorianCalendar.computeTime(Unknown Source)
	at java.base/java.util.Calendar.updateTime(Unknown Source)
	at java.base/java.util.Calendar.getTimeInMillis(Unknown Source)
	at com.mysql.cj.result.SqlDateValueFactory.createFromDate(SqlDateValueFactory.java:72)
	at com.mysql.cj.result.SqlDateValueFactory.createFromDate(SqlDateValueFactory.java:44)
	at com.mysql.cj.result.ZeroDateTimeToNullValueFactory.createFromDate(ZeroDateTimeToNullValueFactory.java:45)
	at com.mysql.cj.result.BaseDecoratingValueFactory.createFromDate(BaseDecoratingValueFactory.java:50)
	at com.mysql.cj.result.BaseDecoratingValueFactory.createFromDate(BaseDecoratingValueFactory.java:50)
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDate(MysqlTextValueDecoder.java:72)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:76)
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:233)
	at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:628)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getDateOrTimestampValueFromRow(ResultSetImpl.java:641)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getDate(ResultSetImpl.java:786)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getDate(JDBCResultSetImpl.java:405)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCDateTimeValueHandler.fetchValueObject(JDBCDateTimeValueHandler.java:97)
	at org.jkiss.dbeaver.ext.mysql.data.MySQLDateTimeValueHandler.fetchValueObject(MySQLDateTimeValueHandler.java:70)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2778)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
it seems that issue isn't reproducible anymore. 
ticket closed
![image](https://user-images.githubusercontent.com/31996417/76635270-3fcabc80-6558-11ea-82d3-1df06a6986a8.png)
