### ISSUE TITLE
Exasol Kerberos authentification

### ISSUE THREAD

**Issue by GriGrim** [dbeaver/dbeaver#6319]
#### System information: 
- DBeaver version: 6.1.3
- OS: Windows 7 6.1 (amd64)
- Java version: 11.0.3 by Oracle Corporation (64bit)

#### Connection specification:
- Database name and version: Exasol 6.1.2
- Driver name: com.exasol:exasol-jdbc:RELEASE (version 6.1.3)
- kerberoshostname: exasol.example.com
- kerberosrealm: EXAMPLE.COM
- kerberosservicename: exasol
- kerberosusername: danila

#### Describe the problem you're observing:
I can connect to Exasol using Kerberos from ExaPlus.
I can connect to Exasol using login/passord from DBeaver.
Bu I cannot connect to Exasol using Kerberos from DBeaver.
I get following error:

> Unexpected driver error occurred while connecting to database
>   com/sun/jna/platform/win32/Win32Exception
>   com/sun/jna/platform/win32/Win32Exception
>     com.sun.jna.platform.win32.Win32Exception
>     com.sun.jna.platform.win32.Win32Exception

#### Include any warning/errors/backtraces from the logs
```
2019-07-22 15:57:16.111 - DBeaver 6.1.3.201907211943 is starting
2019-07-22 15:57:16.112 - OS: Windows 7 6.1 (amd64)
2019-07-22 15:57:16.113 - Java version: 11.0.3 by Oracle Corporation (64bit)
2019-07-22 15:57:16.115 - Install path: 'file:/C:/Program Files/DBeaver/'
2019-07-22 15:57:16.117 - Instance path: 'file:/C:/Users/danila/AppData/Roaming/DBeaverData/workspace6/'
2019-07-22 15:57:16.120 - Memory available 64Mb/1024Mb
2019-07-22 15:57:16.128 - > Start org.jkiss.dbeaver.core [6.1.3.201907211943]
2019-07-22 15:57:16.131 - > Start org.jkiss.dbeaver.registry [1.0.7.201907211943]
2019-07-22 15:57:16.416 - > Start org.eclipse.core.filesystem [1.7.300.v20190218-2054]
2019-07-22 15:57:16.456 - > Start org.eclipse.core.resources [3.13.300.v20190218-2054]
2019-07-22 15:57:16.470 - Starting RMI server at 23585
2019-07-22 15:57:16.554 - Run workbench
2019-07-22 15:57:16.583 - > Start org.eclipse.e4.ui.workbench.swt [0.14.500.v20190214-0851]
2019-07-22 15:57:16.585 - > Start org.eclipse.e4.core.services [2.1.400.v20181215-2145]
2019-07-22 15:57:16.587 - > Start org.eclipse.e4.core.contexts [1.8.0.v20190214-1713]
2019-07-22 15:57:16.607 - > Start org.eclipse.e4.ui.services [1.3.400.v20190212-2214]
2019-07-22 15:57:16.648 - > Start org.eclipse.e4.ui.di [1.2.500.v20190214-1316]
2019-07-22 15:57:16.682 - > Start com.ibm.icu.base [58.2.0.v20170418-1837]
2019-07-22 15:57:16.684 - > Start org.eclipse.emf.common [2.15.0.v20181220-0846]
2019-07-22 15:57:16.719 - > Start org.eclipse.emf.ecore [2.17.0.v20190116-0940]
2019-07-22 15:57:16.799 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-07-22 15:57:17.040 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.400.v20190224-1542]
2019-07-22 15:57:17.084 - > Start org.eclipse.core.expressions [3.6.300.v20190218-1215]
2019-07-22 15:57:17.123 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.500.v20190220-1002]
2019-07-22 15:57:17.269 - > Start org.eclipse.e4.ui.bindings [0.12.400.v20190131-1604]
2019-07-22 15:57:17.368 - > Start org.eclipse.e4.core.di.extensions [0.15.300.v20190213-1308]
2019-07-22 15:57:17.832 - > Start org.eclipse.e4.ui.css.swt [0.13.400.v20190223-1254]
2019-07-22 15:57:17.898 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.200.v20190212-2214]
2019-07-22 15:57:17.966 - > Start org.jkiss.dbeaver.ui [5.1.28.201907211943]
2019-07-22 15:57:18.407 - Initializing DBeaver 6.1.3
2019-07-22 15:57:18.409 - Host plugin: org.jkiss.dbeaver.core.application 6.1.3.201907211943
2019-07-22 15:57:18.412 - Initialize Core...
2019-07-22 15:57:18.432 - Can't find BC security provider. Use default JCE.
2019-07-22 15:57:18.434 - BouncyCastle not registered, using the default JCE provider
2019-07-22 15:57:18.585 - > Start org.jkiss.dbeaver.ui.navigator [1.0.13.201907211943]
2019-07-22 15:57:18.588 - > Start org.eclipse.equinox.security [1.3.100.v20190215-2139]
2019-07-22 15:57:18.596 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-07-22 15:57:18.601 - Core initialized (189ms)
2019-07-22 15:57:18.602 - Configure workbench window
2019-07-22 15:57:18.609 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-07-22 15:57:18.613 - > Start org.eclipse.core.net [1.3.400.v20181030-1645]
2019-07-22 15:57:18.626 - > Start org.eclipse.help [3.8.300.v20190216-1017]
2019-07-22 15:57:18.781 - Create actions
2019-07-22 15:57:18.788 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-07-22 15:57:18.791 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-07-22 15:57:18.920 - > Start org.eclipse.ui.editors [3.11.400.v20190218-1547]
2019-07-22 15:57:18.966 - > Start org.eclipse.core.filebuffers [3.6.500.v20190218-1547]
2019-07-22 15:57:19.655 - > Start org.eclipse.ui.workbench.texteditor [3.11.300.v20190218-2126]
2019-07-22 15:57:19.666 - Initialize workbench window
2019-07-22 15:57:19.673 - Finish initialization
2019-07-22 15:57:19.710 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.13.201907211943]
2019-07-22 15:57:19.716 - > Start org.jkiss.dbeaver.ext.erd [2.0.115.201907211943]
2019-07-22 15:57:20.002 - Total database drivers: 76 (76)
2019-07-22 15:57:20.263 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.13.201907211943]
2019-07-22 15:57:20.374 - > Start org.eclipse.ui.views.log [1.2.500.v20190218-0617]
2019-07-22 15:57:20.857 - > Start org.eclipse.equinox.p2.core [2.6.0.v20190215-2242]
2019-07-22 15:57:20.860 - > Start org.eclipse.equinox.p2.operations [2.5.300.v20190202-1801]
2019-07-22 15:57:20.907 - > Start org.eclipse.equinox.p2.engine [2.6.200.v20190215-2242]
2019-07-22 15:57:20.930 - > Start org.jkiss.dbeaver.ui.editors.data [1.0.13.201907211943]
2019-07-22 15:57:21.011 - > Start org.eclipse.equinox.p2.metadata [2.4.300.v20190215-2242]
2019-07-22 15:57:21.033 - > Start org.jkiss.dbeaver.ext.sample.database [1.0.50.201907211943]
2019-07-22 15:57:21.034 - > Start org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.19.201907211943]
2019-07-22 15:57:21.045 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.200.v20181102-0649]
2019-07-22 15:57:21.047 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-07-22 15:57:21.078 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-07-22 15:57:21.080 - > Start org.eclipse.equinox.p2.repository [2.4.300.v20190215-2242]
2019-07-22 15:57:21.442 - > Start org.eclipse.equinox.p2.ui [2.5.500.v20190220-1158]
2019-07-22 15:57:26.230 - Connect with 'Exasol - 192.168.1.102..108' (exasol-16c14c0fefb-586a133d53bc2eaf)
2019-07-22 15:57:27.319 - > Start org.jkiss.dbeaver.ext.exasol [1.0.71.201907211943]
2019-07-22 15:57:27.381 - Connection failed (exasol-16c14c0fefb-586a133d53bc2eaf)
2019-07-22 15:57:27.383 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:185)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:88)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.exasol.model.ExasolDataSource.<init>(ExasolDataSource.java:128)
	at org.jkiss.dbeaver.ext.exasol.ExasolDataSourceProvider.openDataSource(ExasolDataSourceProvider.java:114)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:812)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Win32Exception
	at com.exasol.jdbc.AbstractEXAConnection.connectAndLogin(AbstractEXAConnection.java:1944)
	at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1309)
	at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1198)
	at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:437)
	at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:38)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:165)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.Win32Exception
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
```

**Comment by GriGrim** [comment]
Can anyone advice something?

**Comment by serge-rider** [comment]
This happens because of missing jna library.
You can download jna libraries (jar files) from https://github.com/java-native-access/jna (both kna and jna platform) and add them into Exasol driver libraries in DBeaver.

**Comment by GriGrim** [comment]
Thanks. Now I get different error.
> Kerberos authentication failed: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))

Logs:
```
2019-08-01 18:14:24.623 - Connect with 'jdbc:exa:192.168.1.102..108:8563;clientname=DBeaver;clientversion=6.1.4.201907291754;querytimeout=600;connecttimeout=0' (exasol-16c4dbf16e2-3a72071193a838ff)
Kerberos username [danila]: 2019-08-01 18:14:25.595 - Connection failed (exasol-16c4dbf16e2-3a72071193a838ff)
2019-08-01 18:14:25.596 - org.jkiss.dbeaver.model.exec.DBCConnectException: Kerberos authentication failed: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
org.jkiss.dbeaver.model.exec.DBCConnectException: Kerberos authentication failed: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:88)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.exasol.model.ExasolDataSource.<init>(ExasolDataSource.java:128)
	at org.jkiss.dbeaver.ext.exasol.ExasolDataSourceProvider.openDataSource(ExasolDataSourceProvider.java:114)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:812)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:250)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.exasol.jdbc.LoginRefused: Kerberos authentication failed: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
	at com.exasol.jdbc.AbstractEXAConnection.connectAndLogin(AbstractEXAConnection.java:1960)
	at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1309)
	at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1198)
	at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:437)
	at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:38)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:165)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 13 more
```

**Comment by GriGrim** [comment]
Problem was solved when I switched JDBC driver that was used by DBeaver by default to JDBC driver from Exasol website.
![dbeaver_jdbc](https://user-images.githubusercontent.com/2479756/62463653-39d75680-b793-11e9-803a-68ed01c7ed7f.png)

**Comment by Sargul** [comment]
See https://www.exasol.com/portal/questions/50139411/dbeaver-kerberos-connection
