### ISSUE TITLE
Generated DDL omits WHERE clause in CREATE UNIQUE INDEX statement

### ISSUE THREAD

**Issue by krkhnh** [dbeaver/dbeaver#6326]
#### System information: 
- Operating system (distribution) and version: Windows 10 v1903
- DBeaver version: 6.1.3
- Java version: OpenJDK v11.0.2
- Additional extensions: None

#### Connection specification:
- Database name and version: SQL Server v11.0.2218.0
- Driver name: SQL Server
![image](https://user-images.githubusercontent.com/5172480/61679117-1dbdc900-ad40-11e9-966a-169d6efe9946.png)

- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
Generated DDL omits WHERE clause in CREATE UNIQUE INDEX statement

#### Steps to reproduce, if exist:

1. Create a table with a filtered unique index. Here is the DDL that generated from SSMS v18.1
```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_Foo](
	[seq] [bigint] NOT NULL,
	[id] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Foo] PRIMARY KEY CLUSTERED 
(
	[seq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE UNIQUE NONCLUSTERED INDEX [UIX_Foo_id] ON [dbo].[TB_Foo]
(
	[id] ASC
)
WHERE ([id] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```

2. Generate [TB_Foo] table's DDL using DBeaver. This is my result.
```
-- Drop table

-- DROP TABLE test.dbo.TB_Foo GO

CREATE TABLE TB_Foo (
	seq bigint NOT NULL,
	id varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	CONSTRAINT PK_Foo PRIMARY KEY (seq)
) GO
CREATE UNIQUE INDEX UIX_Foo_id ON TB_Foo (id) GO;
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by serge-rider** [comment]
Good point.
I'll use index definition script from https://gallery.technet.microsoft.com/scriptcenter/SQL-Server-Generate-Index-fa790441

**Comment by uslss** [comment]
Reopened
When trying to create the same table using DDL generated by Dbeaver - error appears

`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.eclipse.e4.ui.workbench
Error
Thu Aug 08 22:58:57 MSK 2019
Failed to evaluate: WithExpression [variable=activePart, children=[<test property="running" plug-in activation: lazy/>]]
org.eclipse.core.runtime.CoreException: No property tester contributes a property org.jkiss.dbeaver.runtime.process.running to type class org.jkiss.dbeaver.ui.editors.sql.SQLEditor
    at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:130)
    at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:55)
    at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:81)
    at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:74)
    at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:100)
    at org.eclipse.ui.internal.services.EvaluationService.requestEvaluation(EvaluationService.java:290)
    at org.eclipse.ui.internal.handlers.DirtyStateTracker.update(DirtyStateTracker.java:48)
    at org.eclipse.ui.internal.handlers.DirtyStateTracker.propertyChanged(DirtyStateTracker.java:110)
    at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:123)
    at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6366)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.updateDirtyFlag(SQLEditor.java:3183)
    at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.lambda$4(SQLEditor.java:3078)
    at org.jkiss.dbeaver.ui.UIUtils$6.runInUIThread(UIUtils.java:1544)
    at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:41)
    at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1468)`

**Comment by uslss** [comment]
[log.txt](https://github.com/dbeaver/dbeaver/files/3489003/log.txt)
![image](https://user-images.githubusercontent.com/31996417/62823461-b86c3380-bb99-11e9-8369-0c37290c81a6.png)

**Comment by uslss** [comment]
Verified
