### ISSUE TITLE
Internal jdbc driver error on DB2 z/OS connection

### ISSUE THREAD

**Issue by lhimo** [dbeaver/dbeaver#6329]
#### System information: 
- Windows 10
- DBeaver 6.1.1.201906240635

#### Connection specification:
- DB2 z/OS

#### Behaviour:
When I open a table the following errors appear, alternatively:

```
org.jkiss.dbeaver.model.sql.DBSQLException: Errore SQL: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:306)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 6 more
Caused by: java.nio.charset.UnsupportedCharsetException: Cp500
	at java.base/java.nio.charset.Charset.forName(Unknown Source)
	at com.ibm.db2.jcc.am.t.<init>(t.java:13)
	at com.ibm.db2.jcc.am.s.a(s.java:12)
	at com.ibm.db2.jcc.am.o.a(o.java:428)
	at com.ibm.db2.jcc.t4.cc.a(cc.java:2398)
	at com.ibm.db2.jcc.t4.cb.a(cb.java:3407)
	at com.ibm.db2.jcc.t4.cb.a(cb.java:1982)
	at com.ibm.db2.jcc.t4.cb.a(cb.java:1913)
	at com.ibm.db2.jcc.t4.cb.m(cb.java:749)
	at com.ibm.db2.jcc.t4.cb.i(cb.java:252)
	at com.ibm.db2.jcc.t4.cb.c(cb.java:54)
	at com.ibm.db2.jcc.t4.q.c(q.java:44)
	at com.ibm.db2.jcc.t4.rb.j(rb.java:147)
	at com.ibm.db2.jcc.am.jn.kb(jn.java:2047)
	at com.ibm.db2.jcc.am.jn.a(jn.java:3033)
	at com.ibm.db2.jcc.am.jn.e(jn.java:1036)
	at com.ibm.db2.jcc.am.jn.execute(jn.java:1020)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	... 7 more
```
and 

```
org.jkiss.dbeaver.model.sql.DBSQLException: Errore SQL [58009]: [jcc][t4][2034][11148][4.11.77] L'esecuzione non è riuscita a causa di un errore relativo al protocollo di distribuzione che ha determinato l'interruzione del collegamento.
È stato rilevato un errore di sintassi del flusso di dati DRDA.  Codice: 0x3. ERRORCODE=-4499, SQLSTATE=58009
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:192)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.DisconnectRecoverableException: [jcc][t4][2034][11148][4.11.77] L'esecuzione non è riuscita a causa di un errore relativo al protocollo di distribuzione che ha determinato l'interruzione del collegamento.
È stato rilevato un errore di sintassi del flusso di dati DRDA.  Codice: 0x3. ERRORCODE=-4499, SQLSTATE=58009
	at com.ibm.db2.jcc.am.gd.a(gd.java:317)
	at com.ibm.db2.jcc.am.gd.a(gd.java:365)
	at com.ibm.db2.jcc.t4.z.k(z.java:944)
	at com.ibm.db2.jcc.t4.z.c(z.java:394)
	at com.ibm.db2.jcc.t4.z.v(z.java:1147)
	at com.ibm.db2.jcc.t4.cb.a(cb.java:39)
	at com.ibm.db2.jcc.t4.q.a(q.java:32)
	at com.ibm.db2.jcc.t4.rb.i(rb.java:135)
	at com.ibm.db2.jcc.am.jn.ib(jn.java:1996)
	at com.ibm.db2.jcc.am.jn.a(jn.java:3030)
	at com.ibm.db2.jcc.am.jn.e(jn.java:1036)
	at com.ibm.db2.jcc.am.jn.execute(jn.java:1020)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 6 more
```

**Comment by serge-rider** [comment]
This issue was fixed in 6.1.3 (broken JRE configuration)
Thanks for the bug report anyway
