### ISSUE TITLE
SetpOver - NullPointer exception on debug postgresql procedure

### ISSUE THREAD

**Issue by jairperrut** [dbeaver/dbeaver#6408]
I'm trying to debug a procedure on postgres but when I press F6 (step over) this below exception occurs:

**System information:**

* DBeaver version 6.1.3.201907211943.
* Postgres 10.7 (Ubuntu 10.7-1.pgdg18.04+1)

**Log Message**

```
eclipse.buildId=unknown
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=pt_BR
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.jobs
Error
Thu Aug 01 17:36:18 BRT 2019
An internal error occurred during: "Execute Debug Command".

java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.execStep(PostgreDebugSession.java:597)
	at org.jkiss.dbeaver.ext.postgresql.debug.internal.impl.PostgreDebugSession.execStepOver(PostgreDebugSession.java:566)
	at org.jkiss.dbeaver.debug.core.model.DatabaseDebugTarget.stepOver(DatabaseDebugTarget.java:459)
	at org.jkiss.dbeaver.debug.core.model.DatabaseThread.stepOver(DatabaseThread.java:117)
	at org.jkiss.dbeaver.debug.core.model.DatabaseStackFrame.stepOver(DatabaseStackFrame.java:86)
	at org.eclipse.debug.internal.core.commands.StepOverCommand.step(StepOverCommand.java:31)
	at org.eclipse.debug.internal.core.commands.StepCommand.doExecute(StepCommand.java:39)
	at org.eclipse.debug.core.commands.AbstractDebugCommand$1.run(AbstractDebugCommand.java:209)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by serge-rider** [comment]
- Do you use local or global session?
- Could you send debug log? (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by jairperrut** [comment]
> Do you use local or global session?

In global session.

> Could you send debug log?

[Untitled.log](https://github.com/dbeaver/dbeaver/files/3462793/Untitled.log)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it.
