### ISSUE TITLE
NPE when tryiung to create Check constraint

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6429]
#### System information: 
- Operating system (distribution) and version win 10x64
- DBeaver version 6.1.4

#### Connection specification:
- Database name and version MS SQL 7.2.2jre11

#### Describe the problem you're observing:
NPE when trying to create check constraints
![image](https://user-images.githubusercontent.com/31996417/62425017-f4f1e800-b6de-11e9-9380-b52f40bd2b49.png)
`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Sun Aug 04 17:39:39 MSK 2019

java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetString(JDBCUtils.java:66)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerTableCheckConstraint.<init>(SQLServerTableCheckConstraint.java:45)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerCheckConstraintManager.createDatabaseObject(SQLServerCheckConstraintManager.java:61)
	at org.jkiss.dbeaver.ext.mssql.edit.SQLServerCheckConstraintManager.createDatabaseObject(SQLServerCheckConstraintManager.java:1)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor.createNewObject(SQLObjectEditor.java:81)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase$ObjectCreator.run(NavigatorHandlerObjectCreateBase.java:300)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`

**Comment by uslss** [comment]
verified.
check constraint disabled
