### ISSUE TITLE
HIVE Different Windows execute different scripts reporting errors

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6449]
In different Windows to execute different script directly error, stop execution, if a single execution script, execution, and then execute another window script, normal execution, hope can be executed in different Windows, no need to wait!thank you!

eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 09:07:29 CST 2019
SQL 错误 [08S01]: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response

eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 09:07:29 CST 2019
org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response

java.sql.SQLException: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:311)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.run(SQLQueryJob.java:213)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:76)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_GetOperationStatus(TCLIService.java:409)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.GetOperationStatus(TCLIService.java:396)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:280)
	... 9 more
eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 09:07:28 CST 2019
SQL 错误 [08S01]: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
eclipse.buildId=unknown
java.version=1.8.0_73
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Tue Aug 06 09:07:28 CST 2019
org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!

java.sql.SQLException: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:458)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.run(SQLQueryJob.java:213)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
	at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:456)
	at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
	at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_ExecuteStatement(TCLIService.java:225)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.ExecuteStatement(TCLIService.java:212)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:253)
	... 9 more

**Comment by serge-rider** [comment]
Try to set option "Open separate connection for each editor":
![image](https://user-images.githubusercontent.com/6398845/62532350-77e08300-b844-11e9-9d87-f8928589c422.png)

**Comment by parisni** [comment]
hi,

i have the same error. In my experience with one connection only, everything goes well until a concurrent process (with an other client such pyhive) on the hive side produces an error.

I have the feeling that dbeaver is affected by external errors. The pyhive connection don´t suffer this problem
