### ISSUE TITLE
SQL Error [IX000]: Blob not found

### ISSUE THREAD

**Issue by dattila23** [dbeaver/dbeaver#6454]
Blob rtf file read error in Informix database, This is good in dbeaver 5.2.4 version but wrongs in 6.1.4.

Error:
SQL Error [IX000]: Blob not found

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [IX000]: Blob not found
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:755)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:484)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3271)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Blob not found
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:413)
	at com.informix.jdbc.IfxResultSet.blobCheck(IfxResultSet.java:1741)
	at com.informix.jdbc.IfxResultSet.a(IfxResultSet.java:701)
	at com.informix.jdbc.IfxResultSet.b(IfxResultSet.java:641)
	at com.informix.jdbc.IfxResultSet.getObject(IfxResultSet.java:1511)
	at com.informix.jdbc.IfxResultSet.getObject(IfxResultSet.java:809)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:613)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:76)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	... 14 more
Caused by: java.sql.SQLException: System or internal error java.security.PrivilegedActionException: java.io.IOException: A hozzáférés megtagadva
	at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:532)
	at com.informix.jdbc.IfxTmpFile.<init>(IfxTmpFile.java:95)
	at com.informix.jdbc.IfxSqli.executeFetchBlob(IfxSqli.java:5215)
	at com.informix.jdbc.IfxResultSet.blobCheck(IfxResultSet.java:1734)
	... 22 more
Caused by: java.security.PrivilegedActionException: java.io.IOException: A hozzáférés megtagadva
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.informix.jdbc.IfxTmpFile.<init>(IfxTmpFile.java:76)
	... 24 more
Caused by: java.io.IOException: A hozzáférés megtagadva
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(Unknown Source)
	at com.informix.jdbc.IfxTmpFile$1.run(IfxTmpFile.java:81)
	... 26 more

I refreshed java 8.

**Comment by serge-rider** [comment]
It fails with Access denied error in system call File.createTempFile.
Seems to be this ticket: https://www-01.ibm.com/support/docview.wss?uid=swg21232363

> Resolving the problem  
>
> Specify a specific directory for Informix's temporary files by opening the data source on the WebSphere Administrative Console; then open the link for the data source custom properties; create a new custom property called ifxJDBCTEMP for your Informix data source. The value for the ifxJDBCTEMP property must be set to an absolute path name (For example; c:\temp or \opt\temp).

You need to set driver property ifxJDBCTEMP in connection settings.
Although it is not clear why it happens only in 6.x+. Maybe it is because now DBeaver is bundled with new Java 11.

**Comment by dattila23** [comment]
Thanks for your reply. Unfortunately, it's still bad. I noticed that not all rtf files have a problem with larger sizes only. I tried to make the BLOB chache big, but it's not good either.

**Comment by ADegele** [comment]
I had the same problem: the property was apparently renamed to JDBCTEMP. When I set it to C:\temp I can now see blobs larger than 16384 bytes.
https://www.ibm.com/support/pages/error-79701-blob-not-found-while-retrieving-blobs-problem-creating-temporary-files
