### ISSUE TITLE
SSH connection Issue with Duo Unix setup

### ISSUE THREAD

**Issue by Nisarg10** [dbeaver/dbeaver#6457]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro
- DBeaver version: 6.1.3
- Java version 1.8.0_151
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 9.6
- Driver name org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  SSH

#### Describe the problem you're observing:
I have setup DUO for two step authentication on the database server, I am not able to connect to the database server via DBeaver.
When i click on Test tunnel configuration the SSH tunnel is getting connected successfully, but when i click on test connection it says the connection attempt failed.

#### Include any warning/errors/backtraces from the logs

Connect with 'jdbc:postgresql://localhost:5432/databasename' (postgres-jdbc-15e2ceba014-40738ee0324e56c)
2019-08-06 15:57:01.113 - Instantiate SSH tunnel
2019-08-06 15:57:01.113 - Connect to tunnel host
2019-08-06 15:57:01.113 - SSH INFO: Connecting to 0.0.0.0 port 22
2019-08-06 15:57:01.164 - SSH INFO: Connection established
2019-08-06 15:57:01.198 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1
2019-08-06 15:57:01.198 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.53
2019-08-06 15:57:01.198 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2019-08-06 15:57:01.200 - SSH INFO: aes256-ctr is not available.
2019-08-06 15:57:01.200 - SSH INFO: aes192-ctr is not available.
2019-08-06 15:57:01.200 - SSH INFO: aes256-cbc is not available.
2019-08-06 15:57:01.201 - SSH INFO: aes192-cbc is not available.
2019-08-06 15:57:01.201 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2019-08-06 15:57:01.251 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2019-08-06 15:57:01.252 - SSH INFO: SSH_MSG_KEXINIT sent
2019-08-06 15:57:01.252 - SSH INFO: SSH_MSG_KEXINIT received
2019-08-06 15:57:01.252 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2019-08-06 15:57:01.253 - SSH INFO: kex: server: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2019-08-06 15:57:01.253 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2019-08-06 15:57:01.253 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2019-08-06 15:57:01.254 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2019-08-06 15:57:01.254 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2019-08-06 15:57:01.254 - SSH INFO: kex: server: none,zlib@openssh.com
2019-08-06 15:57:01.254 - SSH INFO: kex: server: none,zlib@openssh.com
2019-08-06 15:57:01.254 - SSH INFO: kex: server: 
2019-08-06 15:57:01.255 - SSH INFO: kex: server: 
2019-08-06 15:57:01.255 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2019-08-06 15:57:01.255 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2019-08-06 15:57:01.256 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2019-08-06 15:57:01.256 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2019-08-06 15:57:01.256 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2019-08-06 15:57:01.256 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2019-08-06 15:57:01.257 - SSH INFO: kex: client: none
2019-08-06 15:57:01.257 - SSH INFO: kex: client: none
2019-08-06 15:57:01.257 - SSH INFO: kex: client: 
2019-08-06 15:57:01.257 - SSH INFO: kex: client: 
2019-08-06 15:57:01.257 - SSH INFO: kex: server->client aes128-ctr hmac-md5 none
2019-08-06 15:57:01.257 - SSH INFO: kex: client->server aes128-ctr hmac-md5 none
2019-08-06 15:57:01.266 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2019-08-06 15:57:01.266 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2019-08-06 15:57:01.301 - SSH INFO: ssh_rsa_verify: signature true
2019-08-06 15:57:01.301 - SSH INFO: Host '0.0.0.0' is known and matches the RSA host key
2019-08-06 15:57:01.302 - SSH INFO: SSH_MSG_NEWKEYS sent
2019-08-06 15:57:01.302 - SSH INFO: SSH_MSG_NEWKEYS received
2019-08-06 15:57:01.303 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2019-08-06 15:57:01.341 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2019-08-06 15:57:01.385 - SSH INFO: Authentications that can continue: publickey
2019-08-06 15:57:01.385 - SSH INFO: Next authentication method: publickey
2019-08-06 15:57:01.578 - SSH INFO: Authentication succeeded (publickey).
2019-08-06 15:57:01.613 - Connection failed (postgres-jdbc-15e2ceba014-40738ee0324e56c)
2019-08-06 15:57:01.616 - org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
    at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
    at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:355)
    at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
    at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
    at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:77)
    at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:96)
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:644)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
    at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:227)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
    at org.postgresql.Driver$ConnectThread.getResult(Driver.java:358)
    at org.postgresql.Driver.connect(Driver.java:282)
    at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:162)
    ... 10 more
Caused by: java.io.EOFException
    at org.postgresql.core.PGStream.receiveChar(PGStream.java:285)
    at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:424)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:220)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:218)
    at org.postgresql.Driver.makeConnection(Driver.java:407)
    at org.postgresql.Driver.access$100(Driver.java:55)
    at org.postgresql.Driver$ConnectThread.run(Driver.java:317)
    at java.lang.Thread.run(Unknown Source)

**Comment by serge-rider** [comment]
Are you sure your PG server is running and host/port settings are correct?
In case of SSH tunnel database host/port must be accessible from SSH machine. 
If SSH host and PG server host are the same then specify `localhost` as database host name.

**Comment by Nisarg10** [comment]
> Are you sure your PG server is running and host/port settings are correct?
> In case of SSH tunnel database host/port must be accessible from SSH machine.
> If SSH host and PG server host are the same then specify `localhost` as database host name.

Yes. PG server is running and host/port are correct.
When I do Test tunnel connection. It is successful.
SSH host and PG server host are the same and I have specified `localhost` as database host name.

**Comment by serge-rider** [comment]
So, can you connect to Postgres from that machine with the same parameters/credentials? 
Does `telnet localhost 5432` work?

**Comment by Nisarg10** [comment]
Yes, I can connect to Postgres from that machine with same parameters.

Yes. `telnet localhost 5432` shows connected to localhost.

**Comment by serge-rider** [comment]
Hmm. I never tried Duo auth with PostgreSQL. Need to google a bit..
