### ISSUE TITLE
Running SQL copied from Visual Studio Code crashes RDS instance 

### ISSUE THREAD

**Issue by J-C-Betts** [dbeaver/dbeaver#6461]
**Software versions:**
Windows 10 Pro OS version 1803
Visual Studio Code 1.36.1
DBeaver 6.13.2 release date 22nd July 2019
MariaDB driver version 2.4.2
MariaDB database hosted on Amazon RDS

**Observed problem**
I am maintaining a MariaDB database hosted on an AWS RDS instance through an SQL codebase written in Visual Studio Code (VSCode). A variety of queries when copied and pasted from VSCode into a DBeaver script editor connected to said database, immediately crash the database instance. Whilst a code snippet is provided below, enough testing has been done to raise suspicion that it is not the specific SQL being run that is causing the trouble. 
Nevertheless in the interest of full disclosure I provide the following code snippet (with specifics obfuscated for obvious reasons):
WITH group_status AS (
            SELECT   source_column
            ,        GROUP_CONCAT(CASE WHEN measure > 5 THEN queue_name END SEPARATOR ', ') list
            ,        MIN(CASE WHEN measure > 5  THEN 0 ELSE 1 END) status
            FROM    $$TABLE$$
            WHERE    source_column = $$SOME_SOURCE$$
            GROUP BY source_column
        )
        SELECT   MD5(CONCAT('LIST_MESSAGE|sqs-', lower(source_column), '-prod|', source_column)) dedupe_key
        ,        'CATEGORY' incident_category
        ,        CONCAT('sqs-', lower(source_column, '-prod') incident_name
        ,        source_column
        ,        status
        ,        CONCAT('Queues out of control: ', queues_out_of_control) description
        FROM     group_status

**DBeaver side Error Logs**
!ENTRY org.jkiss.dbeaver.model 2 0 2019-08-06 15:19:27.567
!MESSAGE Can't read execution warnings
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-08-06 15:19:27.567
!MESSAGE SQL Error: Cannot do an operation on a closed statement
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2019-08-06 15:19:27.567
!MESSAGE Cannot do an operation on a closed statement
!STACK 0
java.sql.SQLException: Cannot do an operation on a closed statement
	at org.mariadb.jdbc.MariaDbStatement.checkClose(MariaDbStatement.java:1447)
	at org.mariadb.jdbc.MariaDbStatement.getWarnings(MariaDbStatement.java:925)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getWarnings(JDBCStatementImpl.java:576)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getStatementWarnings(JDBCStatementImpl.java:606)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:533)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-06 15:19:28.846
!MESSAGE Operation failed. Retry count remains = 1
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-08-06 15:19:28.846
!MESSAGE SQL Error [08]: (conn=19787) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-08-06 15:19:28.846
!MESSAGE (conn=19787) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
!STACK 0
java.sql.SQLNonTransientConnectionException: (conn=19787) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:240)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:248)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:338)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:389)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLNonTransientConnectionException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:1925)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1437)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:228)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)
	... 14 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:246)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:215)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1435)
	... 17 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2019-08-06 15:19:28.846
!MESSAGE unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
!STACK 0
java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:246)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:215)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1435)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:228)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:332)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:389)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
I don't think that we can do anything from DBeaver side. Sometimes MariaDB/MySQL server just crashes during some fancy queries execution. Probably a good bug report for MariaDB dev team.

**Comment by J-C-Betts** [comment]
Ok I'll have a poke around over there, thanks for your help!
