### ISSUE TITLE
Oracle SQL Error [1722] [42000]: ORA-01722: invalid number (runs well on SQL Developer)

### ISSUE THREAD

**Issue by jpfmeneses** [dbeaver/dbeaver#6513]
**System information:** 
- Windows 10 pro (EN)
- DBeaver 6.1.4
- Without additional extensions

**Connection specification:**
- Oracle 12

**Describe the problem you're observing:**
Running a query were I'm multiplying 2 varchar (one of them converted to_numeric) returns me the error "SQL Error [1722] [42000]: ORA-01722: invalid number". The same query runs well on SQL Developer.

Columns configuration:
![image](https://user-images.githubusercontent.com/6529477/62959872-64f42280-bdf1-11e9-9d46-e83d736dcb4f.png)

Columns on query:
![image](https://user-images.githubusercontent.com/6529477/62959892-70474e00-bdf1-11e9-95df-ba98df97449f.png)

Execution of the same query in SQL Developer:

![image](https://user-images.githubusercontent.com/6529477/62960580-d84a6400-bdf2-11e9-9951-210f07415210.png)

Erro Detail:

![image](https://user-images.githubusercontent.com/6529477/62960329-58bc9500-bdf2-11e9-8c1a-3a1e3ad0e306.png)

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1722] [42000]: ORA-01722: invalid number

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3271)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.sql.SQLSyntaxErrorException: ORA-01722: invalid number

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:872)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4721)
	at oracle.jdbc.driver.OracleStatement.doScrollStmtExecuteQuery(OracleStatement.java:4854)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1920)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1878)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by serge-rider** [comment]
Generally it works fine in DBeaver
`SELECT to_number('123') * '3' FROM dual`
shows 369 in results. So problem is definitely not in multiplying numbers. Perhaps some of varchars is not actually a number.

**Comment by cerebel** [comment]
@jpfmeneses
 select  to_number(' 123'||4)   as Ok 
         ,  to_number(' 123 '||4)  as Error  from dual 

try to find 
select option_3  from  <table> where   not REGEXP_LIKE(option_3, '^[ ]*[+,-]*[0-9]*[.]?[0-9]*$')

**Comment by jpfmeneses** [comment]
Thanks for your reply @cerebel and @serge-rider 

![image](https://user-images.githubusercontent.com/6529477/63006707-083b4b00-be77-11e9-9113-23986fcc8e33.png)
I taked the suggestion from @cerebel but for field option_4. And I got all the table rows returning on query result. This happened because the numberes were saved with comma instead of dot for decimal separator.

I know that this is not a normal "valid" operation, but way it works on Oracle SQL Developer and in DBeaver returns error? The Oracle Connection Driver is the same.

**Comment by p91paul** [comment]
the difference might be in language settings. sqldeveloper changes many oracle session options that affect how numbers/dates are interpreted.

**Comment by cerebel** [comment]
@jpfmeneses  about dot/comma of decimal separator - checks 
`
select * from v$nls_parameters where parameter ='NLS_NUMERIC_CHARACTERS'
`
 [oracle say v10 by example](https://docs.oracle.com/cd/B19306_01/server.102/b14237/initparams129.htm#REFRN10126)
`
NLS_NUMERIC_CHARACTERS ="decimal_character group_separator"
`
so, find which application changes nls_param.. ( try sqplus, sqlDevelopper, dbeaver)
In dbeaver:queryManger (enable all options in preferences/general/queryMangery:queryTypes, and open view of queryManger)- this param is not changed.

**Comment by jpfmeneses** [comment]
@cerebel thanks for your feedback.

SQL Developer:
![image](https://user-images.githubusercontent.com/6529477/63024442-1ef59800-be9f-11e9-943a-cbd0dd8b99e6.png)

DBeaver:
![image](https://user-images.githubusercontent.com/6529477/63024481-32a0fe80-be9f-11e9-8ced-4ac778a3e924.png)

I went into Dbeaver to run that query first, after that opened the SQL Developer and go back to Dbeaver and verified that the parameter stayed with the same values, but different from SQL Developer. There is any DBeaver option that I can consider to change this parameter?

**Comment by cerebel** [comment]
@jpfmeneses  will set [,] as decimal separator (at session level)
`
databaseNavigator->editConnection ->connectionSettings-> initialization->bootstrapQueries  
 ALTER SESSION SET NLS_NUMERIC_CHARACTERS=',.'
`
or execute upper sql, in editor ..

[src](https://stackoverflow.com/questions/32117625/nls-setting-in-sql-developer-to-change-the-number-format)
_In SQL Developer, Preferences->Database-> NLS, if you change the Decimal Separator setting, you also need to make sure that your new setting doesn't conflict with the existing Group Separator setting.
In this case, you needed to change Decimal Separator to a period ., but also change the Group Separator setting from a period to a comma , to avoid a setting conflict.
or, in editor, run upper sql .._

Better to redefine which decimal separator will be used in yours option_X columns, because at database level - it is [.], not [,] .
