### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6521]
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-14 11:01:14.535

org.jkiss.dbeaver.model
错误
Wed Aug 14 11:41:28 CST 2019
Java heap space

java.lang.OutOfMemoryError: Java heap space
	at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:379)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_GetTables(TCLIService.java:317)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.GetTables(TCLIService.java:304)
	at org.apache.hive.jdbc.HiveDatabaseMetaData.getTables(HiveDatabaseMetaData.java:654)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findTablesByMask(GenericStructureAssistant.java:100)
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:83)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLContextInformer$TablesFinderJob.run(SQLContextInformer.java:335)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

![image](https://user-images.githubusercontent.com/26621087/62993064-805e3c80-be88-11e9-86ce-84b11a34b744.png)

**Comment by serge-rider** [comment]
It is not a bug. DBeaver was out of memory 
Most likely you are reading too big amount of data in DBeaver (e.g. millions of rows) or you are using embedded hadoop driver or doing some other memory-eager operation (in this particular case it happened during table list reading - is it possible that you database has too many of them?).

You can increase maximum amount of memory available for DBeaver, please check this article: https://github.com/dbeaver/dbeaver/wiki/Command-Line

By default DBeaver CE memory limit set to 1Gb.
