### ISSUE TITLE
Unable to open DBeaver version 6.1.4 & 6.1.3

### ISSUE THREAD

**Issue by kamal-1** [dbeaver/dbeaver#6531]
I upgraded to version 6.1.4 last week and it worked quite well for a few days. Today it didn't open at all. Here are the log messages I saw. I am using the JVM included version.

!SESSION 2019-08-15 17:05:42.670 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui.workbench 4 2 2019-08-15 17:05:49.914
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.getLastMigration(MigrationSupport.java:236)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.baseChangedSinceLastPresentationOfWizard(MigrationSupport.java:197)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.migration.MigrationSupport.performMigration(MigrationSupport.java:77)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.earlyStartup(AutomaticUpdateScheduler.java:78)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:80)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:56)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2019-08-15 17:05:49.921
!MESSAGE An internal error occurred during: "Executing the early startup extensions".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:344)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:286)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:772)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:72)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:78)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2707)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Try to remove current version completely (use Uninstall program or remove dbeaver folder manually) and then install it again.
If this won't help the try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by kamal-1** [comment]
> Try to remove current version completely (use Uninstall program or remove dbeaver folder manually) and then install it again.
> If this won't help the try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

I did uninstall and remove the folder several times but it didn't work. I will try out reset workspace and see if it works.

**Comment by kamal-1** [comment]
> > Try to remove current version completely (use Uninstall program or remove dbeaver folder manually) and then install it again.
> > If this won't help the try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-workspace
> 
> I did uninstall and remove the folder several times but it didn't work. I will try out reset workspace and see if it works.

I reset the workspace as suggested and it did fix the issue. Thanks for the quick response.
