### ISSUE TITLE
org.jkiss.dbeaver.DBException: Can't find table 

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6537]
![image](https://user-images.githubusercontent.com/26621087/63204333-2f895680-c0c9-11e9-8347-317073996785.png)
The HIVE query cannot locate the library, while the IMPALA query works fine

dbeaver version=6.15
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.DBException: Can't find table 
 'b2b_zcsx_dlcj_new' in '`Apache Hive - default`' at org.jkiss.
 dbeaver.ext.generic.model.
 GenericStructureAssistant$TableReference.resolveObject
 (GenericStructureAssistant.java:204) at org.jkiss.dbeaver.
 model.DBInfoUtils.makeObjectDescription(DBInfoUtils.java:
 42) at org.jkiss.dbeaver.model.sql.completion.
 SQLCompletionHelper.readAdditionalProposalInfo
 (SQLCompletionHelper.java:50) at org.jkiss.dbeaver.model.
 sql.completion.SQLCompletionProposalBase.
 getAdditionalInfo(SQLCompletionProposalBase.java:224) at 
 org.jkiss.dbeaver.ui.editors.sql.syntax.
 SQLCompletionProposal.getAdditionalProposalInfo
 (SQLCompletionProposal.java:129) at org.eclipse.jface.text.
 contentassist.AdditionalInfoController$Timer$2$1.run
 (AdditionalInfoController.java:116) at org.eclipse.core.
 internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
I can't reproduce this. 
Please write any additional information which may help.

**Comment by Pengchenghua** [comment]
> 我无法重现这一点。
> 请写下任何可能有用的其他信息。
com/google/common/primitives/Doubles
![image](https://user-images.githubusercontent.com/26621087/63233696-44e6b800-c264-11e9-8316-03e29fe58bd8.png)

eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

This is a continuation of log file C:\Users\Administrator\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_0.log
Created Time: 2019-08-19 09:29:47.987

org.eclipse.e4.ui.workbench
错误
Mon Aug 19 09:30:25 CST 2019
Failed to evaluate: WithExpression [variable=activePart, children=[<test property="running" plug-in activation: lazy/>]]

org.eclipse.core.runtime.CoreException: 属性测试对象未将 org.jkiss.dbeaver.runtime.process.running 属性添加至 class org.jkiss.dbeaver.ui.editors.sql.SQLEditor 类型
	at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:130)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:55)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:81)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:74)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:100)
	at org.eclipse.ui.internal.services.EvaluationReference.changed(EvaluationReference.java:94)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:109)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.services.EvaluationService$1.changed(EvaluationService.java:79)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:109)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:364)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:379)
	at org.eclipse.ui.internal.WorkbenchPage.updateActivePartSources(WorkbenchPage.java:345)
	at org.eclipse.ui.internal.WorkbenchPage.updateActivations(WorkbenchPage.java:312)
	at org.eclipse.ui.internal.WorkbenchPage.access$2(WorkbenchPage.java:305)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:213)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:253)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:250)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:775)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:97)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.lambda$0(ContributedPartRenderer.java:63)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1510)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1473)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2966)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2235)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5410)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:445)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4827)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1110)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3451)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1101)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setFocus(AbstractTextEditor.java:6210)
	at org.eclipse.ui.texteditor.StatusTextEditor.setFocus(StatusTextEditor.java:147)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.setFocus(SQLEditor.java:1522)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:222)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:326)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:248)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:147)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:808)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.setFocus(ContributedPartRenderer.java:106)
	at org.eclipse.swt.custom.CTabItem.setFocus(CTabItem.java:343)
	at org.eclipse.swt.custom.CTabFolder.setFocus(CTabFolder.java:2637)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:1065)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:3962)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3181)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3189)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1876)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:330)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by Pengchenghua** [comment]
> 我无法重现这一点。
> 请写下任何可能有用的其他信息。

[.bak_0.log](https://github.com/dbeaver/dbeaver/files/3513896/default.bak_0.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3513901/dbeaver-debug.log)

**Comment by uslss** [comment]
is it still actual?

**Comment by uslss** [comment]
there is no update on ticket more than a month.
Ticket closed.
If issue still actual for you - feel free to reopen the ticket
