### ISSUE TITLE
Unexpected driver error occurred while connecting to database: invalid null input

### ISSUE THREAD

**Issue by tschallacka** [dbeaver/dbeaver#6582]
#### System information: 
- Operating system (distribution) and version  Windows 10 pro x64
- DBeaver version 6.1.5.201908191349
- Additional extensions none

#### Connection specification:
- Database name and version 10.2.20-MariaDB-10.2.20+maria~xenial mariadb.org binary distribution
- Driver name MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No, direct LAN connection

#### Describe the problem you're observing:

I have a mariaDB server set up on ubuntu, I can connect to it with mysql workbench, php driver using SSL certificates. Only with dbbeaver I get the error invalid null input without any logs or other helpful information what exactly is null.

![image](https://user-images.githubusercontent.com/8638425/63433349-4f02e500-c423-11e9-8363-c1f1efa19b29.png)

#### Steps to reproduce, if exist:

Set up mariadb on ubuntu via https://www.cyberciti.biz/faq/how-to-setup-mariadb-ssl-and-secure-connections-from-clients/ to generate certificates

Use those certificates to connect DBbeaver to the mariadb server.

#### Include any warning/errors/backtraces from the logs
!SESSION 2019-08-21 13:47:32.502 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2019-08-21 14:45:07.671
!MESSAGE Error running job 'Create new database object with DataSourceDescriptorManager' execution:

**Comment by serge-rider** [comment]
Can't reproduce.
Please send error/debug log file (https://github.com/dbeaver/dbeaver/wiki/Log-files).
Perhaps some config parameters are wrong but it is impossible to say which exactly. Or maybe it is driver internal error (you could try to use another driver version (change it in the driver editor dialog->Download/Update)

**Comment by fournet94** [comment]
Hello, I have the same issue as reported by tschallacka, OS is Windows 10 64 bits, DBeaver Enterprise 6.2.0.201909091348, and the same error occurs when trying to use SSL on a MariaDB server. Parameters modified are "UseSSL" checkbox, "CA certificate", "SSL certificate" and "SSL certificate key" pathes. Please note that the error doesn't occur with non-SSL connections. Here is my dbeaver-debug.log content

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3635033/dbeaver-debug.log)

I tried to use latest MariaDB java client driver (2.4.4) without effect on the error. Tried to force Cipher suite, useSSL driver property and enableSslCipherSuites driver property without success.

Thanks for you help

**Comment by karthicraghupathi** [comment]
I'm running into the same issue with SSL connections on the MariaDb driver.

Here is my setup:

DBeaver CE  6.3.2.202001051908
Windows 10 Pro Version 1903 (Build 18362.30)
MariaDB 10.2.30 on Ubuntu 18

For now I'm getting around this by using the Mysql 8.0+ drivers.

**Comment by tgross35** [comment]
A bit late to the party but it seems like I'm coming across the same problem

```
2020-03-24 13:56:35.708 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to the database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to the database
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:216)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:375)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:92)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:55)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:110)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:85)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:127)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:812)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: invalid null input
	at java.base/java.security.KeyStore$PrivateKeyEntry.<init>(Unknown Source)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(Unknown Source)
	at java.base/sun.security.util.KeyStoreDelegator.engineGetEntry(Unknown Source)
	at java.base/java.security.KeyStore.getEntry(Unknown Source)
	at org.mariadb.jdbc.internal.protocol.tls.MariaDbX509KeyManager.<init>(MariaDbX509KeyManager.java:97)
	at org.mariadb.jdbc.internal.protocol.tls.SslFactory.loadClientCerts(SslFactory.java:91)
	at org.mariadb.jdbc.internal.protocol.tls.SslFactory.getSslSocketFactory(SslFactory.java:46)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:712)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:415)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1128)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:620)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:175)
	at org.mariadb.jdbc.Driver.connect(Driver.java:92)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:160)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:184)
	... 14 more
```

**Comment by uslss** [comment]
is it still actual against the recent version?

**Comment by fournet94** [comment]
Hello, I can confirm the issue is not present anymore in version 7.1.1.202006231904 CE.

Thanks a lot, nice job !
