### ISSUE TITLE
Many UI Rendering issues

### ISSUE THREAD

**Issue by chris-pauley** [dbeaver/dbeaver#6640]
#### System information: 
- Operating system (distribution) and version
Ubuntu 19.04
- DBeaver version
6.1.5.201908191349
- Additional extensions
None

#### Connection specification:
- Database name and version
MySQL 8
- Driver name
?
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Many of the UI elements fail to render properly, the data view is completely unusable. Sometimes other elements (buttons on the toolbars, elements from the database navigator, the entirety of the main pane) will either disappear or partially render or render incorrectly.

No other applications have rending issues. I'm using a quadro p2000 with nvidia drivers. Reinstalling the application has not worked (even removing what local files I could find). Turning off themes made the problem worse. Changing my OS theme to default did not resolve the problem either.

Example data view rendering, there should be many lines of data here:
![image](https://user-images.githubusercontent.com/3710617/63867333-b1f3ff00-c982-11e9-965f-25f5e22a5c6f.png)

#### Steps to reproduce, if exist:
Load any database, any table, and go to the data view

**Comment by serge-rider** [comment]
Most likely it is some GTK-specific issue.
Please post debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by chris-pauley** [comment]
```
2019-08-29 10:37:30.834 - DBeaver 6.1.5.201908191349 is starting
2019-08-29 10:37:30.834 - OS: Linux 5.0.0-25-generic (amd64)
2019-08-29 10:37:30.834 - Java version: 1.8.0_222 by Private Build (64bit)
2019-08-29 10:37:30.835 - Install path: '/usr/share/dbeaver'
2019-08-29 10:37:30.835 - Instance path: 'file:/home/chris/.local/share/DBeaverData/workspace6/'
2019-08-29 10:37:30.836 - Memory available 77Mb/910Mb
2019-08-29 10:37:30.838 - > Start org.jkiss.dbeaver.registry [1.0.9.201908191349]
2019-08-29 10:37:30.928 - > Start org.eclipse.core.filesystem [1.7.400.v20190518-1151]
2019-08-29 10:37:31.003 - > Start org.eclipse.core.resources [3.13.400.v20190505-1655]
2019-08-29 10:37:31.010 - Starting RMI server at 21331
2019-08-29 10:37:31.028 - Run workbench
2019-08-29 10:37:31.033 - > Start org.eclipse.e4.ui.workbench.swt [0.14.600.v20190513-2118]
2019-08-29 10:37:31.034 - > Start org.eclipse.e4.core.services [2.1.400.v20181215-2145]
2019-08-29 10:37:31.035 - > Start org.eclipse.e4.core.contexts [1.8.100.v20190518-1217]
2019-08-29 10:37:31.041 - > Start org.eclipse.e4.ui.services [1.3.500.v20190513-2118]
2019-08-29 10:37:31.061 - > Start org.eclipse.e4.ui.di [1.2.600.v20190510-1100]
2019-08-29 10:37:31.089 - > Start org.eclipse.emf.common [2.16.0.v20190528-0845]
2019-08-29 10:37:31.103 - > Start org.eclipse.emf.ecore [2.18.0.v20190528-0845]
2019-08-29 10:37:31.146 - > Start org.eclipse.emf.ecore.xmi [2.16.0.v20190528-0725]
2019-08-29 10:37:31.349 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.500.v20190513-2118]
2019-08-29 10:37:31.357 - > Start org.eclipse.core.expressions [3.6.400.v20190518-1240]
2019-08-29 10:37:31.368 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.700.v20190517-1525]
2019-08-29 10:37:31.450 - > Start org.eclipse.e4.ui.bindings [0.12.500.v20190510-1100]
2019-08-29 10:37:31.486 - > Start org.eclipse.e4.core.di.extensions [0.15.300.v20190213-1308]
2019-08-29 10:37:31.785 - > Start org.eclipse.e4.ui.css.swt [0.13.500.v20190513-2118]
2019-08-29 10:37:31.834 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.300.v20190510-1100]
2019-08-29 10:37:31.876 - > Start org.jkiss.dbeaver.ui [5.1.30.201908191349]
2019-08-29 10:37:32.127 - Initializing DBeaver 6.1.5
2019-08-29 10:37:32.128 - Host plugin: org.jkiss.dbeaver.core.application 6.1.5.201908191349
2019-08-29 10:37:32.128 - Initialize Core...
2019-08-29 10:37:32.139 - Can't find BC security provider. Use default JCE.
2019-08-29 10:37:32.140 - BouncyCastle not registered, using the default JCE provider
2019-08-29 10:37:32.201 - > Start org.jkiss.dbeaver.ui.navigator [1.0.15.201908191349]
2019-08-29 10:37:32.210 - > Start org.eclipse.equinox.security [1.3.200.v20190516-1504]
2019-08-29 10:37:32.219 - > Start org.eclipse.ui.net [1.3.400.v20190519-2354]
2019-08-29 10:37:32.220 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-08-29 10:37:32.220 - > Start org.eclipse.core.net [1.3.500.v20190519-2354]
2019-08-29 10:37:32.222 - Core initialized (94ms)
2019-08-29 10:37:32.222 - Configure workbench window
2019-08-29 10:37:32.237 - > Start org.eclipse.help [3.8.400.v20190423-0921]
2019-08-29 10:37:32.374 - Create actions
2019-08-29 10:37:32.375 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-08-29 10:37:32.376 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-08-29 10:37:32.435 - > Start org.eclipse.ui.editors [3.11.500.v20190519-2344]
2019-08-29 10:37:32.437 - > Start org.eclipse.core.filebuffers [3.6.600.v20190519-2344]
2019-08-29 10:37:32.742 - > Start org.eclipse.ui.workbench.texteditor [3.12.0.v20190519-2344]
2019-08-29 10:37:32.750 - Initialize workbench window
2019-08-29 10:37:32.755 - Finish initialization
2019-08-29 10:37:32.778 - > Start org.jkiss.dbeaver.ext.erd [2.0.117.201908191349]
2019-08-29 10:37:32.786 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.15.201908191349]
2019-08-29 10:37:32.923 - Total database drivers: 76 (76)
2019-08-29 10:37:33.067 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.15.201908191349]
2019-08-29 10:37:33.140 - Connect with 'MySQL 8+ - prospector' (mysql8-16c0ae4885c-2879eea59e029988)
2019-08-29 10:37:33.144 - > Start org.jkiss.dbeaver.ext.mysql [2.1.100.201908191349]
2019-08-29 10:37:33.239 - > Start org.eclipse.ui.views.log [1.2.600.v20190519-1034]
2019-08-29 10:37:33.592 - > Start org.eclipse.equinox.p2.core [2.6.0.v20190215-2242]
2019-08-29 10:37:33.593 - > Start org.eclipse.equinox.p2.operations [2.5.400.v20190408-2008]
2019-08-29 10:37:33.596 - > Start org.eclipse.equinox.p2.engine [2.6.300.v20190318-1320]
2019-08-29 10:37:33.601 - > Start org.eclipse.equinox.p2.metadata [2.4.400.v20190409-0548]
2019-08-29 10:37:33.609 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.200.v20181102-0649]
2019-08-29 10:37:33.610 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-08-29 10:37:33.614 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-08-29 10:37:33.615 - > Start org.eclipse.equinox.p2.repository [2.4.400.v20190318-1320]
2019-08-29 10:37:33.731 - > Start org.eclipse.equinox.p2.ui [2.5.500.v20190220-1158]
2019-08-29 10:37:33.845 - > Start org.jkiss.dbeaver.ui.editors.data [1.0.15.201908191349]
2019-08-29 10:37:33.934 - > Start org.jkiss.dbeaver.ext.sample.database [1.0.52.201908191349]
2019-08-29 10:37:33.935 - > Start org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.21.201908191349]
2019-08-29 10:37:34.533 - Connected (mysql8-16c0ae4885c-2879eea59e029988, MySQL Connector/J [mysql-connector-java-8.0.11 (Revision: 6d4eaa273bc181b4cf1c8ad0821a2227f116fedf)])
2019-08-29 10:37:34.831 - > Start org.eclipse.gef [3.11.0.201606061308]
2019-08-29 10:37:34.844 - > Start org.eclipse.draw2d [3.10.100.201606061308]
2019-08-29 10:37:35.320 - Event loop exception
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:532)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:235)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6800)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6132)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4166)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1429)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1585)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
2019-08-29 10:37:35.371 - Event loop exception
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:532)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:235)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6800)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6132)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4166)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1429)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1585)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
2019-08-29 10:37:35.408 - Event loop exception
[The above error repeats 135 more times]
```

**Comment by serge-rider** [comment]
It is a known issue with Eclipse apps on some linuxes.
There are several possible ways to fix GTK config.
Please check this one: https://superuser.com/questions/1455397/debian-9-org-eclipse-swt-swterror-no-more-handles-immediately-after-opening-ec
(run `im-config`)

Or this one: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546061
```sh
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
```

Or this one: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545425

**Comment by chris-pauley** [comment]
@serge-rider is exactly right, this is an issue with my GTK config. Thanks so much for the help

**Comment by sxc731** [comment]
FWIW I had terrible issues with the tree views widgets not rendering properly on Ubuntu 19.10 (regular GNOME flavour) with DBeaver 6.3.2.202001051908 installed from Eclipse Marketplace on top of Eclipse 2019-09.

Expanding a node would result in the pixels from the newly expanded node somehow clobbering the data that was already underneath that node before expansion; this would fix itself after several (> 10 seconds). 

I tried all the workarounds mentioned above to no avail.  In the end, I upgraded my Eclipse installation from 2019-09 to 2019-12 and this solved all my rendering issues.

I did not encounter `SWTError: No more handles` in the logs so this was likely a different issue; apologies for hijacking this ticket but it's title and date are applicable and perhaps this will help someone else.

**Comment by SenCodeMaker** [comment]
Still having this issue, tried all the solution exports, im-config set to cvjks and then set to ibus, back to default, login/logout at each time still having no handles error. Also tried to downgrade from 21.1.5 to 21.0.5 or 7.3.5 no one is working. I'm on ubuntu 16 LTS this is the logs:


!ENTRY org.eclipse.ui 4 0 2021-08-21 23:08:37.581
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4915)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
	at org.eclipse.swt.widgets.FileDialog.openNativeChooserDialog(FileDialog.java:345)
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:329)
	at org.jkiss.dbeaver.ui.dialogs.DialogUtils.openFileDialog(DialogUtils.java:136)
	at org.jkiss.dbeaver.ui.dialogs.DialogUtils.openFile(DialogUtils.java:98)
	at org.jkiss.dbeaver.ext.mysql.tools.MySQLScriptExecuteWizardPageSettings.chooseInputFile(MySQLScriptExecuteWizardPageSettings.java:128)
	at org.jkiss.dbeaver.ext.mysql.tools.MySQLScriptExecuteWizardPageSettings.access$1(MySQLScriptExecuteWizardPageSettings.java:126)
	at org.jkiss.dbeaver.ext.mysql.tools.MySQLScriptExecuteWizardPageSettings$2.widgetSelected(MySQLScriptExecuteWizardPageSettings.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.mysql.tools.MySQLToolImport.execute(MySQLToolImport.java:43)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:366)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:265)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

I'm trying to open file browser to choose mysql home
