### ISSUE TITLE
Error transforming column

### ISSUE THREAD

**Issue by zlisten** [dbeaver/dbeaver#6671]
#### System information: 
- WIN7
- DBeaver version：6.1.5.201908191349
- Additional extensions：none

#### Connection specification:
- Database name and version：mysql 5.7.23
- Driver name：default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? ：NO

#### Describe the problem you're observing:
I have a column bigint(20) . When I try to use "column view -> Set "xxx" format -> Epoch Time ",
it give me a NullPoint Exception.
![图片](https://user-images.githubusercontent.com/12082706/64163335-a6697200-ce73-11e9-9e46-e0b921f631a6.png)

**Comment by serge-rider** [comment]
Can't reproduce.
Please post error stacktrace (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by zlisten** [comment]
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.resultset.TransformerSettingsDialog.updateTransformerInfo(TransformerSettingsDialog.java:219)
	at org.jkiss.dbeaver.ui.controls.resultset.TransformerSettingsDialog.createDialogArea(TransformerSettingsDialog.java:104)
	at org.jkiss.dbeaver.ui.controls.resultset.TransformerSettingsDialog.createDialogArea(TransformerSettingsDialog.java:1)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:771)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.jkiss.dbeaver.ui.dialogs.BaseDialog.create(BaseDialog.java:72)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$11.run(ResultSetViewer.java:2581)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by serge-rider** [comment]
Thanks

**Comment by zlisten** [comment]
My pleasure.

**Comment by uslss** [comment]
verified
