### ISSUE TITLE
Incompatability between bundled jre and Denodo 7 JDBC driver

### ISSUE THREAD

**Issue by jkaetz** [dbeaver/dbeaver#6678]
#### System information: 
- Operating system (distribution) and version:  Windows 10 1903
- DBeaver version: 6.1.1 to present
- Java version: 8
- Additional extensions: Denodo JDBC driver

#### Connection specification:
- Database name and version:  Denodo 7
- Driver name:  Denodo 7 JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?: No

#### Describe the problem you're observing:
Unhandled exception when attempting to use the Denodo JDBC driver.  This appears to be a problem with the bundled jre starting with version 6.1.1.  The jre in version 6.1.0 works.  The driver will also work with version 6.1.1 and beyond if the jre folder is replaced with the jre from 6.1.0 or removed all together and the standalone jre is available.  

#### Steps to reproduce, if exist:
Install Dbeaver Community using the executable.  Add the Denodo JDBC driver in the driver manager.  Open the new connection dialog and select the Denodo driver.  Click test connection and the exception will be thrown.

#### Include any warning/errors/backtraces from the logs
2019-09-04 12:29:24.529 - Connect with 'Denodo Dev' (A2F4D67E-B637-31DE-477D-01C65B3F2FA7-165007a4e52-5e5a570e15646860)
2019-09-04 12:29:24.547 - > Start org.jkiss.dbeaver.ext.generic [2.3.101.201908191349]
2019-09-04 12:29:24.629 - Connection failed (A2F4D67E-B637-31DE-477D-01C65B3F2FA7-165007a4e52-5e5a570e15646860)
2019-09-04 12:29:24.632 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:185)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:88)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:69)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:843)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:68)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:69)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: sun/rmi/transport/proxy/RMISocketInfo
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.denodo.vdb.vdbinterface.client.VDBProxy.a3(Unknown Source)
	at com.denodo.vdb.vdbinterface.client.VDBProxy.openClientConnection(Unknown Source)
	at com.denodo.vdb.vdbinterface.common.connection.VDBConnection.<init>(Unknown Source)
	at com.denodo.vdb.vdbinterface.common.datasource.VDBDataSource.getConnection(Unknown Source)
	at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.connect(DAOVDBProxy.java:201)
	at com.denodo.vdb.jdbcdriver.VDBJDBCConnection.getConnection(VDBJDBCConnection.java:132)
	at com.denodo.vdb.jdbcdriver.VDBJDBCDriver.connect(VDBJDBCDriver.java:208)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 23 more
Caused by: java.lang.ClassNotFoundException: sun.rmi.transport.proxy.RMISocketInfo
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

**Comment by serge-rider** [comment]
Denodo driver depends on deprecated internal API which was removed in Java 11 (default bundled Java version).
Workaround: 
- install Java 8 on your machine (and make it default if you have multiple Java versions)
- install DBeaver from zip archive or delete folder "jre" in DBeaver installation folder.

**Comment by jkaetz** [comment]
Thanks.  I suspected it was on the Denodo end but couldn't exactly pin it down.  Your workarounds are also what I found.

**Comment by rbeiroa** [comment]
The Denodo JDBC Driver starting denodo-vdp-jdbcdriver-7.0-update-20190903 addresses this incompatibility.
Therefore, to resolve the issue it is necessary to do the following:
-  Update Denodo 7.0 to 20190903 or newer and.
-  Use the JDBC driver (denodo-vdp-jdbcdriver-7.0-update-20190903) or newer.

**Comment by jkaetz** [comment]
The new driver does indeed resolve the issue.  Thank you!
