### ISSUE TITLE
java.lang.NullPointerException at org.jkiss.dbeaver.registry.ResourceHandlerDescriptor.getDefaultRoot(ResourceHandlerDescriptor.java:186)

### ISSUE THREAD

**Issue by rindeal** [dbeaver/dbeaver#6693]
#### System information: 
- Operating system (distribution) and version
custom Linux
- DBeaver version
6.1.5
- Additional extensions
none

#### Connection specification:
- Database name and version
none
- Driver name
none
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
exception in the log
#### Steps to reproduce, if exist:
trying to save some configuration, click "apply", observe exception

#### Include any warning/errors/backtraces from the logs

```
<redacted> - Event loop exception
java.lang.NullPointerException
        at org.jkiss.dbeaver.registry.ResourceHandlerDescriptor.getDefaultRoot(ResourceHandlerDescriptor.java:186)
        at org.jkiss.dbeaver.ui.project.PrefPageProjectResourceSettings.performOk(PrefPageProjectResourceSettings.java:209)
        at org.eclipse.jface.preference.PreferencePage.performApply(PreferencePage.java:457)
        at org.eclipse.jface.preference.PreferencePage.lambda$1(PreferencePage.java:289)
        at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at org.eclipse.ui.internal.handlers.PropertyDialogHandler.execute(PropertyDialogHandler.java:49)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:245)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

**Comment by serge-rider** [comment]
Can't reproduce.
I've fixed the NPE but it is not clear what exactly can lead to this problem.

**Comment by rindeal** [comment]
Clicking on ` File > Properties` now gives a popup saying: `No property pages for .`

**Comment by serge-rider** [comment]
I can't reproduce this either. 
Does it fail for any file?
Could you send full error log?

**Comment by rindeal** [comment]
There are no errors in the log anymore. All steps to reproduce are as follows:

- remove all saved data (`~/.local/share/DBeaverData/`)
- install DBeaver
- run DBeaver
- when asked for a database, just close the window
- click `File > Properties`

If I set up a db connection, it works, so what I'm suspecting this to be, is that the button should not be clickable, if no database is set up.

**Comment by serge-rider** [comment]
I see. This is quite hard to fix this issue because it behavior controlled by Eclipse platform.
