### ISSUE TITLE
Error reading datasources configuration

### ISSUE THREAD

**Issue by Pengchenghua** [dbeaver/dbeaver#6751]
![image](https://user-images.githubusercontent.com/26621087/64940628-03fbb680-d897-11e9-86b0-9bc9ac17be3f.png)

eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/Administrator/AppData/Roaming/DBeaverData/workspace6/

eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
错误
Mon Sep 16 15:30:30 CST 2019
锁定资源树以便进行修改。

java.lang.Exception: 锁定资源树以便进行修改。
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2243)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1542)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:556)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.refreshConfig(DataSourceRegistry.java:474)
	at org.jkiss.dbeaver.model.navigator.DBNProject.handleChildResourceChange(DBNProject.java:198)
	at org.jkiss.dbeaver.model.navigator.DBNResource.handleResourceChange(DBNResource.java:413)
	at org.jkiss.dbeaver.model.navigator.DBNModel.resourceChanged(DBNModel.java:580)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by amatosg** [comment]
> Steps to reproduce, if exist:
could you please specify what are the steps to reproduce the issue?

**Comment by Pengchenghua** [comment]
在切换数据库时，出现报错

**Comment by amatosg** [comment]
what?

**Comment by Pengchenghua** [comment]
An error occurred while switching the database

**Comment by amatosg** [comment]
you have to be more specific. In order to help you, you have to tell exactly what steps you followed that make the software show this error, otherwise nobody will be able to find the actual error and fix it.

**Comment by Pengchenghua** [comment]
I used version 6.21. When switching the data source, it was unable to switch and the data source was empty

**Comment by p91paul** [comment]
maybe you can try recording your screen with screen2gif to showcase this!

**Comment by NickVanderPyle** [comment]
I can reproduce this.

#### Session Data
```
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/nickv/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/nickv/.eclipse_keyring
```

#### Last error in Error Log

##### Message: The resource tree is locked for modifications.
```
java.lang.Exception: The resource tree is locked for modifications.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:122)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2243)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1542)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:556)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.refreshConfig(DataSourceRegistry.java:474)
	at org.jkiss.dbeaver.model.navigator.DBNProject.handleChildResourceChange(DBNProject.java:198)
	at org.jkiss.dbeaver.model.navigator.DBNResource.handleResourceChange(DBNResource.java:413)
	at org.jkiss.dbeaver.model.navigator.DBNModel.resourceChanged(DBNModel.java:580)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

#### Steps to reproduce:

1. Open DBeaver
2. Click to select a connection in Database Navigator (Doesn't matter which one)
3. Press ```Control+]``` to open a new editor
4. Wait a few seconds

#### I've tried...

* Removing w/ AppCleaner and reinstalling
* Deleting everything in ~/Library/DBeaverData
* Deleting all connections. They don't stay deleted

Here's a recording. Notice that the Database Navigator and currently open connection are both cleared just a few seconds after the editor opens.

![dbeaver](https://user-images.githubusercontent.com/96394/65252395-e6149880-dac6-11e9-8aa8-e304811d7bfd.gif)

**Comment by NickVanderPyle** [comment]
I downgraded from 6.2 to 6.1 and the problem does not occur.

**Comment by uslss** [comment]
is it still reproducible with 6.3.0?

**Comment by NickVanderPyle** [comment]
@uslss I cannot reproduce the bug after updating to 6.3.0.
This appears to be fixed. :)
