### ISSUE TITLE
Unable to run Dbeaver 6.2 on Amazon Linux 

### ISSUE THREAD

**Issue by abrakhan** [dbeaver/dbeaver#6753]
When I try to run Dbeaver on Amazon Linux - I get this error:

[ec2-user@ip-0-0-0-0 dbeaver]$ ./dbeaver &
[1] 1725
[ec2-user@ip-0-0-0-0 dbeaver]$ 2019-09-16 23:34:04.906 - > Start org.jkiss.dbeaver.core.application [6.2.0.201909081341]
2019-09-16 23:34:04.916 - > Start org.eclipse.e4.ui.model.workbench [2.1.400.v20190513-2118]
2019-09-16 23:34:05.029 - < Stop org.eclipse.osgi [3.14.0.v20190517-1309]
2019-09-16 23:34:05.040 - < Stop org.jkiss.dbeaver.ext.mssql.ui [1.0.15.201909081341]
2019-09-16 23:34:05.045 - < Stop org.jkiss.dbeaver.ext.mssql [1.0.110.201909081341]
2019-09-16 23:34:05.046 - < Stop org.jkiss.dbeaver.ext.oracle.ui [1.0.3.201909081341]
2019-09-16 23:34:05.047 - < Stop org.jkiss.dbeaver.ext.oracle [2.1.101.201909081341]
2019-09-16 23:34:05.048 - < Stop org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.22.201909081341]
2019-09-16 23:34:05.048 - < Stop org.jkiss.dbeaver.core.application [6.2.0.201909081341]
Dbeaver:
An error has occurred. See the log file
/home/ec2-user/.local/share/DBeaverData/workspace6/.metadata/.log.

The log file has this exception:
[ec2-user@ip-0-0-0-0 ~]$ more /home/ec2-user/.local/share/DBeaverData/workspace6/.metadata/.log
!SESSION 2019-09-16 23:34:03.030 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_222
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2019-09-16 23:34:05.021
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.gtk.OS._cachejvmptr()V
        at org.eclipse.swt.internal.gtk.OS._cachejvmptr(Native Method)
        at org.eclipse.swt.internal.gtk.OS.cachejvmptr(OS.java:492)
        at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:91)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
        at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:161)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:193)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

I have updated the JDK to Java 1.8:
[ec2-user@ip-0-0-0-0 ~]$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

Any suggestions to get around this error?

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
