### ISSUE TITLE
Attempting to navigate from a column with multi-value reference fails with 'Navigate association' has encountered a problem. error

### ISSUE THREAD

**Issue by dbrennan** [dbeaver/dbeaver#6754]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04 
- DBeaver version: 6.1.5
- Additional extensions: none

#### Connection specification:
- Database name and version: Postgres 10.5
- Driver name. JDBC 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing: I have a table with fk references that contains two values, eg:

FOREIGN KEY (foo, bar) REFERENCES table2 (foo, bar)

make sure no single references on foo or bar exists

#### Steps to reproduce, if exist:

1. populate data confirming to this scheme
2. open data view of source table in dbeaver
3. click on navigate link icon

result: Error dialog reading:

Problem Occured
'Navigation association' has encountered a problem.
Broken association (referenced constraint missing)
Details >>
Broken association (referenced constraint missing)
  Broken association (referenced constraint missing)

(yes, last two lines are repeated)

I can select a row from the foreign table using the two keys, so I know target value exists. 

#### Include any warning/errors/backtraces from the logs

Each failure results in 3 log entries.

eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Sep 16 22:24:52 PDT 2019
Broken association (referenced constraint missing)

org.jkiss.dbeaver.DBException: Broken association (referenced constraint missing)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateAssociation(ResultSetViewer.java:2731)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$6.run(SpreadsheetPresentation.java:1049)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Sep 16 22:24:52 PDT 2019
Error during job 'Navigate association' execution

eclipse.buildId=unknown
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Mon Sep 16 22:24:52 PDT 2019
Broken association (referenced constraint missing)

org.jkiss.dbeaver.DBException: Broken association (referenced constraint missing)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateAssociation(ResultSetViewer.java:2731)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$6.run(SpreadsheetPresentation.java:1049)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
cannot reproduce it anymore.

**Comment by idryzhov** [comment]
Seeing this problem on Version 22.0.5.202205220912.

**Comment by maxk096** [comment]
The issue is present on Version 22.3.2.202301060755.

SQL to reproduce:

```sql
CREATE TABLE campaigns (
	id bigserial NOT NULL,
	company_id int4 NOT NULL,
	PRIMARY KEY (
		company_id,
		id
	)
)

CREATE TABLE ads (
	id bigserial NOT NULL,
	company_id int4 NOT NULL, 
	campaign_id int4 NOT NULL,
	PRIMARY KEY (
		company_id,
		id
	),
	FOREIGN KEY (
		campaign_id,
		company_id
	)
	REFERENCES campaigns (
		id,
		company_id
	)
)

-- Test data
INSERT
	INTO
	campaigns (company_id)
VALUES(5)

INSERT
	INTO
	ads (
		company_id,
		campaign_id
	)
VALUES(
	5,
	1
)
```

Then open the `ads` table data view, and click on the reference icon in either the `company_id` or `campaign_id` column, and the error message will appear.

```
Broken association (referenced constraint missing)
Broken association (referenced constraint missing)
```

Error logs

```
null
org.jkiss.dbeaver.model
Error
Mon Jan 16 12:14:04 UTC 2023
Broken association (referenced constraint missing)

org.jkiss.dbeaver.DBException: Broken association (referenced constraint missing)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateAssociation(ResultSetViewer.java:3425)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$7.run(SpreadsheetPresentation.java:1296)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)



null
org.jkiss.dbeaver.model
Error
Mon Jan 16 12:14:04 UTC 2023
Broken association (referenced constraint missing)

org.jkiss.dbeaver.DBException: Broken association (referenced constraint missing)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.navigateAssociation(ResultSetViewer.java:3425)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$7.run(SpreadsheetPresentation.java:1296)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

Also, if you navigate `ads` table properties view, in DDL section, the foreign key is broken:

```sql
ALTER TABLE public.ads ADD CONSTRAINT ads_campaign_id_company_id_fkey FOREIGN KEY (campaign_id,company_id) REFERENCES <?>();
```

What I've noticed, is that it only happens when the columns in the foreign key & reference are swapped relatively to what to the primary key definition in referenced `campaigns` table. With the following DDL, there's no error:

```sql
CREATE TABLE ads (
	id bigserial NOT NULL,
	company_id int4 NOT NULL, 
	campaign_id int4 NOT NULL,
	PRIMARY KEY (
		company_id,
		id
	),
        -- Notice that the columns are swapped(eg. same as in primary key of the campaigs table)
	FOREIGN KEY (
		company_id,
		campaign_id
	)
	REFERENCES campaigns (
		company_id,
		id
	)
)
```

**Comment by E1izabeth** [comment]
@maxk096 thank you for steps and investigation. I can reproduce it.

**Comment by E1izabeth** [comment]
Still reproducible on DBeaver 23.0.5

**Comment by Gabriel-A-Rocha** [comment]
Issue persists on version 23.3.3.202401211839.

As @maxk096 spotted, the issue happens when the composite foreign key reference uses a swapped version of the columns initially declared as primary keys in the target table. The workaround is to check the original table first and declare the foreign key in the same order.
