### ISSUE TITLE
db2: Unique Key couldn't be created.

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6787]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.1 CE

#### Connection specification:
- Database name and version db2/zOS

#### Describe the problem you're observing:
Error appears when trying to create unique key.
#### Steps to reproduce, if exist:
1. Open table
2. Create Unique Key and save it -> error appears.

`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.jkiss.dbeaver.model
Error
Sat Sep 21 20:33:08 MSK 2019
An unexpected token "KEY" was found following "NEWTABLE_1_UN UNIQUE".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.26.14
com.ibm.db2.jcc.am.SqlSyntaxErrorException: An unexpected token "KEY" was found following "NEWTABLE_1_UN UNIQUE".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:810)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2824)
	at com.ibm.db2.jcc.am.k4.d(k4.java:2808)
	at com.ibm.db2.jcc.am.k4.b(k4.java:2168)
	at com.ibm.db2.jcc.t4.ab.k(ab.java:446)
	at com.ibm.db2.jcc.t4.ab.c(ab.java:104)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.av.h(av.java:124)
	at com.ibm.db2.jcc.am.k4.ak(k4.java:2163)
	at com.ibm.db2.jcc.am.k4.a(k4.java:3366)
	at com.ibm.db2.jcc.am.k4.e(k4.java:1131)
	at com.ibm.db2.jcc.am.k4.execute(k4.java:1110)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:48)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:189)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:111)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:325)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:323)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:307)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1057)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by serge-rider** [comment]
You must use DB2 LUW driver
