### ISSUE TITLE
ORA-00933: SQL command not properly ended when using text literals

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#6800]
#### System information: 
- Windows 10, 1803
- DBeaver 6.2.0
- No additional extensions

#### Connection specification:
- Oracle 12.2
- Oracle thin driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Certain queries using text literals fail when executing with the cursor inside the statement, but succeed when the entire statement is selected first

#### Steps to reproduce, if exist:

Type in a SQL editor:

`SELECT q'{'}' || t.dummy || q'{'}' FROM sys.dual t;`

Hit Ctrl-Enter with cursor somewhere inside the statement. Statement returns error "ORA-00933: SQL command not properly ended"

Highlight the entire statement before hitting Ctrl-Enter and the statement succeeds, returning the value 'X'.

#### Include any warning/errors/backtraces from the logs

```

!ENTRY org.jkiss.dbeaver.model 4 0 2019-09-23 09:26:15.371
!MESSAGE Error executing query
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-09-23 09:26:15.371
!MESSAGE SQL Error [933] [42000]: ORA-00933: SQL command not properly ended

!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2019-09-23 09:26:15.371
!MESSAGE Error : 933, Position : 50, Sql = SELECT q'{'}' || t.dummy || q'{'}' FROM sys.dual t;
, OriginalSql = SELECT q'{'}' || t.dummy || q'{'}' FROM sys.dual t;
, Error Msg = ORA-00933: SQL command not properly ended

!STACK 0
Error : 933, Position : 50, Sql = SELECT q'{'}' || t.dummy || q'{'}' FROM sys.dual t;
, OriginalSql = SELECT q'{'}' || t.dummy || q'{'}' FROM sys.dual t;
, Error Msg = ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1737)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:473)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:412)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:865)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2833)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3356)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
not reproducible anymore. ticket closed
