### ISSUE TITLE
Unable to start DBeaver as normal user in windows 10

### ISSUE THREAD

**Issue by JaccodeZwart** [dbeaver/dbeaver#6834]
Hi there,

I have installed DBeaver CE 6.2.1 in Windows 10 Enterprise 1809 (build 737). Due to seccurity setting (company policy) I have to install it as user that has more privileges.

This all goes fine. But when I was to execute DBeaver as normal user I get an error message. This message is 'There was a problem loading the shared libary and finding the entry point'. In the file
C:\Users\<myUserName>\AppData\Roaming\DBeaverData\workspace6\.metadata

I can see the entry : 
!SESSION 2019-09-26 09:42:35.324 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=nl_NL
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2019-09-26 09:42:37.402
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.C.PTR_sizeof()I
	at org.eclipse.swt.internal.C.PTR_sizeof(Native Method)
	at org.eclipse.swt.internal.C.<clinit>(C.java:22)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:143)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:193)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

I can start DBeaver as the administrator user that installed DBeaver.

What can be wrong ?

Thanks in advance,

Jacco

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the issue with DBeaver 7.0.3. Is it still actual for you?

**Comment by JaccodeZwart** [comment]
Kseniia,

Not it is no longer relevant.

The problem was that our company has a tool that white-lists applications when connected to the network. The white-list doesn’t work over VPN. So when connected via VPN DBeaver wasn’t white-listed and could not start.

Thanks for replying anyway.

Jacco


Van: Kseniia <notifications@github.com>
Verzonden: donderdag 23 april 2020 10:49
Aan: dbeaver/dbeaver <dbeaver@noreply.github.com>
CC: J. de Zwart <j.dezwart@erasmusmc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [dbeaver/dbeaver] Unable to start DBeaver as normal user in windows 10 (#6834)


I cannot reproduce the issue with DBeaver 7.0.3. Is it still actual for you?

**Comment by kseniiaguzeeva** [comment]
I'm glad the problem is solved
