### ISSUE TITLE
Oracle: NPE appears on hover on data grid

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#6840]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.2 
issue isn't reproducible on MySQL and PostgreSQL
#### Describe the problem you're observing:
NPE appears on hover on data grid
#### Steps to reproduce, if exist: please, watch attached file
![npe_dg](https://user-images.githubusercontent.com/31996417/65728863-f3341780-e0c4-11e9-99bb-3bd58e39abde.gif)

#### Include any warning/errors/backtraces from the logs
`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.eclipse.ui
Error
Thu Sep 26 22:19:49 MSK 2019
Unhandled event loop exception
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.getCellToolTip(LightGrid.java:4291)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleCellHover(LightGrid.java:3785)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.handleHovering(LightGrid.java:3352)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseMove(LightGrid.java:3191)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:246)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)`

**Comment by serge-rider** [comment]
I can't reproduce this. But I've added extra checking in tooltip render function, hope this will help

**Comment by uslss** [comment]
verified. issue isn't reproducible anymore
