### ISSUE TITLE
"Unable to read repository" error

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#6996]
#### System information: 
- OS: Windows 10.0.17763.720
- DBeaver version: 6.2.3.201910122038
- Additional extensions: None

#### Describe the problem you're observing:

Following error shows up when trying to install any extension:

```
Unable to read repository at https://dbeaver.io/update/ce/latest/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

#### Steps to reproduce, if exist:

Go to Help->Install New Software... and try to install something.

**Comment by serge-rider** [comment]
Looks like Java version/config issue.
Do you use Windows installer or you have your own Java preiinstalled and you use zip archive?

**Comment by maln0ir** [comment]
I use Windows installer downloaded from releases page.

**Comment by maln0ir** [comment]
I found that this url: https://dbeaver.io/update/ce/latest/content.xml returns 404. I don't know how Eclipse updates works, but may this be caused by fact that server contains `content.xml.xz` file instead of `content.xml`?

**Comment by serge-rider** [comment]
We have https://dbeaver.io/update/ce/latest/content.jar instead.
I still can't reproduce this issue. Could you post error or debug log? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by maln0ir** [comment]
It seems to me DBeaver don't use system certs store and can't communicate with repo server when I am behind https proxies. I could fix it by myself just by adding cert, but I don't know how to do that.

Messages from debug log:

```
2019-10-25 13:14:40.979 - Open [https://dbeaver.io/product/version.xml]
2019-10-25 13:14:41.644 - javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:102)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:47)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:42)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:53)
	at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 27 more
2019-10-25 13:14:48.113 - > Start Equinox Provisioning Platform Update Support [org.eclipse.equinox.p2.ui.sdk 1.1.200.v20181214-0802]
2019-10-25 13:14:48.278 - > Start Equinox Provisioning ECF based Transport [org.eclipse.equinox.p2.transport.ecf 1.2.100.v20180822-1354]
2019-10-25 13:14:48.289 - > Start ECF Filetransfer API [org.eclipse.ecf.filetransfer 5.0.100.v20180301-0132]
2019-10-25 13:14:48.332 - > Start ECF Core API [org.eclipse.ecf 3.9.3.v20190423-0625]
2019-10-25 13:14:48.398 - > Start ECF Filetransfer Provider [org.eclipse.ecf.provider.filetransfer 3.2.400.v20180306-0429]
2019-10-25 13:14:48.423 - > Start Equinox Concurrent API [org.eclipse.equinox.concurrent 1.1.300.v20190514-1046]
2019-10-25 13:14:48.443 - > Start ECF Identity Core API [org.eclipse.ecf.identity 3.9.1.v20181107-1749]```

**Comment by maln0ir** [comment]
I solved it by myself by importing certs in this way: https://stackoverflow.com/a/26183328

**Comment by geomorillo** [comment]
2022 still an issue

**Comment by IvanSnetkov** [comment]
2022 still an issue

**Comment by p91paul** [comment]
@geomorillo @IvanSnetkov did you try @ghost suggestion? this issue cannot be fixed by the DBeaver team, it's something caused by bad MITM https proxies that corporations use. So if it really is this issue, everyone must solve it on its own computer depending on how your corporate proxy works.
