### ISSUE TITLE
Error appears when trying to switch Active Schema/DB

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7039]
### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.3

#### Connection specification:
- Database name and version Mysql, Oracle

#### Describe the problem you're observing:
Error appears when trying to switch active DB/Schema usind context menu or shortcut
![image](https://user-images.githubusercontent.com/31996417/67215312-ed162a00-f429-11e9-9836-3b5e5f97ec85.png)
```eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\Users\Dziyana\AppData\Roaming\DBeaverData\workspace6
org.jkiss.dbeaver.model
Error
Mon Oct 21 17:40:39 MSK 2019
Invalid object type: Schemas
java.lang.IllegalArgumentException: Invalid object type: Schemas
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.setDefaultObject(OracleDataSource.java:500)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerSetActiveObject.lambda$1(NavigatorHandlerSetActiveObject.java:63)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerSetActiveObject.lambda$0(NavigatorHandlerSetActiveObject.java:61)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:58)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
