### ISSUE TITLE
IntelliJ Debugging

### ISSUE THREAD

**Issue by ishmum123** [dbeaver/dbeaver#7049]
I tried to follow the Idea debugging steps strictly but keep on bumping into the following issues -

1) IntelliJ Can't Find the JUnit Library

2) Application stops when I try to run it with the following exception - 

java.lang.NullPointerException
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.getExtensionFiles(FrameworkExtensionInstaller.java:171)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent0(FrameworkExtensionInstaller.java:123)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent(FrameworkExtensionInstaller.java:94)
	at org.eclipse.osgi.storage.Storage.installExtensions(Storage.java:309)
	at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:179)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:72)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:34)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:306)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
An error has occurred. See the log file
null.

**Comment by uslss** [comment]
if issue is still actual for you - feel free to reopen the ticket
