### ISSUE TITLE
GraphML support (draw.io, gephi)

### ISSUE THREAD

**Issue by Eddie-Hartman** [dbeaver/dbeaver#7067]
### System information: 
- Windows 10
- 6.2.3
- Additional extensions: Darkest Dark Theme (Also tried without the theme enabled)

#### Connection specification:
- SQL Server 2017
- MS SQL Server / SQL Server
- No

#### Describe the problem you're observing:

When exporting an ERD to GraphML format, dbeaver throws this error:
![image](https://user-images.githubusercontent.com/14089997/67314223-505b9700-f4d2-11e9-9bb2-a4a96d499a77.png)

#### Steps to reproduce, if exist:

Spend hours creating an ERD in the application, then try to export via GraphML.
When opening the file, nodes and text are out of place.

#### Include any warning/errors/backtraces from the logs
Log:
!SESSION 2019-10-22 13:30:37.773 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  C:\Users\Eddie.Hartman.NAOU22829\Downloads\Test.graphml
Command-line arguments:  -os win32 -ws win32 -arch x86_64 C:\Users\Eddie.Hartman.NAOU22829\Downloads\Test.graphml

!ENTRY org.eclipse.osgi 4 0 2019-10-22 13:30:38.554
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by serge-rider** [comment]
I can't reproduce this.
This error may occur during application startup but not during diagram save.

Could you write a bit more details.
- What program do you use to view GraphML files?
- What exactly is wrong with diagram?
- If any error happens during diagram save - please make a screenshot and post it here.

**Comment by Eddie-Hartman** [comment]
I tried opening the file in draw.io and in gephi. Both had the same issue. The output looked like this:
![image](https://user-images.githubusercontent.com/14089997/67777182-bba7ea80-fa37-11e9-87c4-d9a90890a1d6.png)

The error is happening during diagram save. The screenshot I posted above is the error I get.

I thought that it had something to do with the size of graph I'm trying to save, but I tried a small custom one and still got this error as well:
![image](https://user-images.githubusercontent.com/14089997/67777384-09bcee00-fa38-11e9-9943-22afef582d2b.png)

And opening the file looks like this:
![image](https://user-images.githubusercontent.com/14089997/67777510-37a23280-fa38-11e9-97e0-6f61caf0e6f5.png)

Some additional notes, I'm using a dark theme so the ERD coming out dark is expected.
I also installed to just my user. I did not install for all users.
I tried running the application as admin and get the same errors.

Here is a sample file that I made using my installation. I just added one table and note. (Can't upload the file, so just save this as Test.graphml)
`<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd" xmlns:y="http://www.yworks.com/xml/graphml">
	<key for="node" id="nodegraph" yfiles.type="nodegraphics"/>
	<key for="edge" id="edgegraph" yfiles.type="edgegraphics"/>
	<graph edgedefault="directed" id="G">
		<node id="n1">
			<data key="nodegraph">
				<y:GenericNode configuration="com.yworks.entityRelationship.big_entity">
					<y:Geometry height="131" width="144" x="312" y="172"/>
					<y:Fill color="#000000" transparent="false"/>
					<y:BorderStyle color="#FFFFFF" type="line" width="1.0"/>
					<y:NodeLabel alignment="center" autoSizePolicy="content" configuration="com.yworks.entityRelationship.label.name" fontFamily="Courier" fontSize="12" fontStyle="plain" hasLineColor="false" modelName="internal" modelPosition="t" backgroundColor="#000000" textColor="#FFFFFF" visible="true" height="22" width="140" x="314" y="174">sysdiagrams</y:NodeLabel>
					<y:NodeLabel alignment="left" autoSizePolicy="content" configuration="com.yworks.entityRelationship.label.attributes" fontFamily="Courier" fontSize="12" fontStyle="plain" hasLineColor="false" modelName="custom" modelPosition="t" backgroundColor="#404040" textColor="#FFFFFF" visible="true" height="81" width="140" x="314" y="220">name: sysname
principal_id: int
diagram_id: int
version: int
definition: varbinary						<y:LabelModel>
							<y:ErdAttributesNodeLabelModel/>
						</y:LabelModel>
						<y:ModelParameter>
							<y:ErdAttributesNodeLabelModelParameter/>
						</y:ModelParameter>
					</y:NodeLabel>
				</y:GenericNode>
			</data>
		</node>
	</graph>
</graphml>`

If there is anything else that you need from me, please let me know. I appreciate what you do. Thank you.

**Comment by serge-rider** [comment]
@Eddie-Hartman could you attach error (NullPointerException) stacktrace? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by serge-rider** [comment]
At the moment DBeaver supports only yWorks format of GraphML. As far as I know draw.io doesn't support it.
Looks like we need to add support of other GraphML "dialects".

**Comment by Eddie-Hartman** [comment]
Sorry, I saw your second reply, but didn't see your first reply until today.

I was unable to reproduce the null pointer exception unfortunately... I spent a good amount of time going back through my steps and trying. I DO still have the error in my original post whenever I try to save as graphml. Perhaps the "Presentation 'results.chart' not found." message below will be a dead giveaway to you.

Also, one of the reasons I chose to export to graphml is that I thought it was an open standard so other applications would be compatible. As opposed to passing around the dbeaver .erd files.

Here is my test case:
I just made a simple test graph and went to export it in graphml format.
![image](https://user-images.githubusercontent.com/14089997/68775943-458db100-05fd-11ea-9a15-be4c701f278f.png)

This appears to be the relevant log entry for this test case, as it's the only entry for today:

> !SESSION 2019-11-13 10:03:04.603 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

>!ENTRY org.eclipse.core.resources 2 10035 2019-11-13 10:03:06.913
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

>!ENTRY org.jkiss.dbeaver.model 2 0 2019-11-13 10:03:15.644
!MESSAGE Presentation 'results.chart' not found. 

For the following tests, I used a large ERD.

RESOLVED: Running out of heap space when exporting to png:

>!ENTRY org.jkiss.dbeaver.model 4 0 2019-11-13 10:16:38.786
!MESSAGE Java heap space
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:452)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:263)
	at org.jkiss.dbeaver.ui.ImageUtils.get8BitPaletteImageData(ImageUtils.java:264)
	at org.jkiss.dbeaver.ui.ImageUtils.makeWebImageData(ImageUtils.java:238)
	at org.jkiss.dbeaver.ext.erd.export.ERDExportRasterImage.exportDiagram(ERDExportRasterImage.java:81)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.saveDiagramAs(ERDEditorPart.java:677)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.doSaveAs(ERDEditorPart.java:289)
	at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:45)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:392)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:783)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:760)
	at org.eclipse.ui.menus.CommandContributionItem$$Lambda$478/0x0000000100802040.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)

(I suggest adding something to the output if possible to indicate that allowing dbeaver to use more memory may alleviate the problem with a link to how this is done. I added -vmargs -Xmx1000m -Xmx4000m then exported beautifully.)

**Comment by Eddie-Hartman** [comment]
I saw that this got backlogged and added to the 7.1.1 milestone, but then got removed and is no longer in the backlog. Just making sure it doesn't get lost. Thanks. 😄

**Comment by uslss** [comment]
verified

**Comment by Eddie-Hartman** [comment]
@SA357 @serge-rider @uslss 
Looks great. Thank you so much.

My next suggestion is supporting the export of notes as well with the ERD.
If you'd like me to create a new issue let me know.

Example before export:
![image](https://user-images.githubusercontent.com/14089997/91755708-9032e680-eb99-11ea-9af8-0329c3c7bc4f.png)

After Export:
![image](https://user-images.githubusercontent.com/14089997/91755788-ae98e200-eb99-11ea-8d29-d2ea48c6af45.png)

You can see how preserving this data is important to how I'm organizing my work.

**Comment by uslss** [comment]
@Eddie-Hartman thanks for the feedback :)
it would be great if you'll create new issue. Thanks in advance
