### ISSUE TITLE
Could not export large data,Error on exporting large data from DBeaver.

### ISSUE THREAD

**Issue by gokulpriyasuresh** [dbeaver/dbeaver#7089]
I am using Dbeaver and connect SQL , and Cassandra databases.
Most of table has more number of records(probably more than 1 lakh record), so when i try to export the records(either by query or directly the complete table) as CSV , i am not able to get the complete table data to my report.
**For Example :**
One of my table has 1,04,136 records i could fetch it by executing query in dbeaver , but when i try to export as CSV i am getting only 4949 records to my CSV file.
**On further researching on this i could see the error log as below,**
!ENTRY org.jkiss.dbeaver.model 2 0 2019-10-24 14:06:05.658
!MESSAGE Error closing stream
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2019-10-24 14:06:05.658
!MESSAGE Stream Closed
!STACK 0
java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.jkiss.dbeaver.utils.ContentUtils.close(ContentUtils.java:238)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.closeExporter(StreamTransferConsumer.java:272)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.finishTransfer(StreamTransferConsumer.java:302)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:108)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
**My Connection details are as follows:**
![image](https://user-images.githubusercontent.com/46569946/67517406-2c5da880-f6c0-11e9-80cb-65ddd68dc894.png)

**Error Details**
![image](https://user-images.githubusercontent.com/46569946/67516970-33d08200-f6bf-11e9-8fbe-a993988d7b93.png)

**Comment by gokulpriyasuresh** [comment]
Hi Serge,

Yes I do have a enough disk space...even today I totally deleted all unwanted data and tried exporting but still not getting complete data. Still getting the same "stream closed" error please help me out with this.

Regards,
Priya
________________________________

**Comment by serge-rider** [comment]
According to the log file I see that you are using very old version of DBeaver. 
Please upgrade to the recent version (6.2.3 is preferred) and try again.

**Comment by gokulpriyasuresh** [comment]
Can you please help me with the process of updating the tool... should I need to uninstall and reinstall the new version if I do so will all my connections will be lost??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tati-kru** [comment]
You don't need to uninstall the old version, just download a new one (https://dbeaver.io/download/) and install it. If you don't want to loose your connection settings, won't forget to migrate your settings during the first run (DBeaver will suggest to do this right after run).
