### ISSUE TITLE
Postgres: Semicolon terminates statement from inside string constant

### ISSUE THREAD

**Issue by sauntimo** [dbeaver/dbeaver#7099]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro v1903 build 18362.418
- DBeaver version: 6.2.3.201910191000
- Additional extensions: n/a

#### Connection specification:
- Database name and version: PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
- Driver name org.postgresql:postgresql:RELEASE [42.2.5] net.postgis:postgis-jdbc:RELEASE [2.2.1]
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
A semicolon inside a string constant is terminating a statement

#### Steps to reproduce, if exist:
- Run a select statement similar to the following
```sql
SELECT * FROM api.snippet s WHERE s."content" ILIKE '%amp;%';
```

- This results in the following error
```
SQL Error [42601]: Unterminated string literal started at position 52 in SQL SELECT * FROM api.snippet s WHERE s."content" ILIKE '%amp. Expected  char
```

- However, it runs correctly in psql so it looks like DBeaver is allowing the semicolon to terminate the statement despite being inside a string, and then complaining that the string it is in, isn't terminated. 

#### Include any warning/errors/backtraces from the logs

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: Unterminated string literal started at position 52 in SQL SELECT * FROM api.snippet s WHERE s."content" ILIKE '%amp. Expected  char
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:468)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:399)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:769)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2854)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3429)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Unterminated string literal started at position 52 in SQL SELECT * FROM api.snippet s WHERE s."content" ILIKE '%amp. Expected  char
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1275)
	at org.postgresql.core.Parser.parseSql(Parser.java:1182)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:1126)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:314)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:285)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
```

**Comment by sauntimo** [comment]
The following simplified repro might be useful: the same error can be triggered by running the following query
```sql
SELECT ';';
```

![image](https://user-images.githubusercontent.com/2720466/67854057-92568f80-fb07-11e9-83f9-84b15eb4de43.png)
