### ISSUE TITLE
Liquibase changelog: Migrate button causes NPE

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7100]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.3

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
Migrate button in changelog causes NPE
#### Steps to reproduce, if exist:
1, Compare/Migrate - Liquibase changelog
2. Choose any item - Generate Changelog
3. Click Migrate button - Check
![image](https://user-images.githubusercontent.com/31996417/67671866-c3a85180-f987-11e9-93ea-643c9e2b98e5.png)
`eclipse.buildId=unknown
java.version=11.0.3
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.jkiss.dbeaver.model
Error
Mon Oct 28 12:27:36 MSK 2019
```
java.lang.NullPointerException
	at com.dbeaver.ee.scmp.ui.wizard.SchemaMigration.runMigration(SchemaMigration.java:52)
	at com.dbeaver.ee.scmp.ui.wizard.SchemaComparePageDiff.performMigration(SchemaComparePageDiff.java:547)
	at com.dbeaver.ee.scmp.ui.wizard.SchemaComparePageDiff.lambda$4(SchemaComparePageDiff.java:530)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`
```

**Comment by uslss** [comment]
Reopened.
Still reproducible

**Comment by serge-rider** [comment]
`Migrate` button removed.

**Comment by uslss** [comment]
verified
