### ISSUE TITLE
Postgres String index out of range: -<number> when using bind variable

### ISSUE THREAD

**Issue by snuyanzin** [dbeaver/dbeaver#7119]
#### System information: 
- Operating system (distribution) and version: Ubuntu 19.10
- DBeaver version: 6.2.3
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11.5
- Driver name: org.postgresql:postgresql:RELEASE, 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
1. There should be a query with bind variable
2. The number of rows should exceed the result-set fetch size
3. An attempt to scroll for the next portion of data fails with the exception below

#### Steps to reproduce, if exist:
It was reproduced with any query with bind variable (but value of result-set fetch size should be lower than the number of rows in db for that query) e.g.
```
select * from public.pg_stat_statements where userid = :userid
```
then scroll again.
#### Include any warning/errors/backtraces from the logs
```
org.jkiss.dbeaver.DBException: String index out of range: -2
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:198)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3429)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.base/java.lang.String.substring(String.java:1841)
	at org.jkiss.dbeaver.model.sql.SQLUtils.fillQueryParameters(SQLUtils.java:1104)
	at org.jkiss.dbeaver.model.sql.SQLScriptContext.fillQueryParameters(SQLScriptContext.java:175)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:353)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:769)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2854)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	... 4 more
```

**Comment by uslss** [comment]
Hi, could you try if issue is reproducible for you on 6.2.4?

**Comment by uslss** [comment]
there is no update more than a month. Ticket closed.
If issue is still actual feel free to reopen the ticket or create a new one.
