### ISSUE TITLE
Sap Hana: Unique Key creation fails

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7140]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.2.4

#### Connection specification:
- Database name and version SAP Hana

#### Describe the problem you're observing:
Unique Key creation is impossible - when trying to save changes it fails. Primary Key is created successfully

`eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
org.jkiss.dbeaver.model
Error
Fri Nov 01 20:59:46 MSK 2019
SAP DBTech JDBC: [257] (at 67): sql syntax error: incorrect syntax near "KEY": line 1 col 67 (at pos 67)
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257] (at 67): sql syntax error: incorrect syntax near "KEY": line 1 col 67 (at pos 67)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:195)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:45)
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:844)
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:165)
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4189)
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1667)
	at com.sap.db.jdbc.StatementSapDB._executeDirect(StatementSapDB.java:1648)
	at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1622)
	at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1583)
	at com.sap.db.jdbc.StatementSapDB.execute(StatementSapDB.java:518)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:48)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:189)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:111)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:331)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:306)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by uslss** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D10. Do not remove or edit.` [D10](https://dbeaver.testquality.com/project/8805/result/1593211/defect/5725)

**Comment by kai-morich** [comment]
not reproducible with dbeaver 7.0.2 + hana 2sps04. unique key is created correctly.

related issue: the created unique key is not shown in 'unique keys' section. I am preparing a fix

**Comment by uslss** [comment]
verified
