### ISSUE TITLE
[Snowflake] Multi-statement SQL execution in Snowflake

### ISSUE THREAD

**Issue by chiman-wend** [dbeaver/dbeaver#7173]
Recently, in version v3.10.1 of the Snowflake JDBC driver the support for multi-statement SQL was introduced. The updated documentation can be found here:

https://docs.snowflake.net/manuals/user-guide/jdbc-using.html#multi-statement-jdbc

Is it possbile to integreate this into Dbeaver?

Currently, when executing two (or more) SQL statements in a single command, for instance 

`USE DATABASE TESTDB;`
`USE ROLE SYSADMIN;`

the output is:

> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [8] [0A000]: Actual statement count 2 did not match the desired statement count 1.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:419)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:781)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2852)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Actual statement count 2 did not match the desired statement count 1.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:152)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:77)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:495)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:372)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:506)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:250)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:188)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:797)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:309)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:373)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by DGempler** [comment]
+1

**Comment by FailureTowne** [comment]
+1

**Comment by ReginaldHopkins** [comment]
+1000

**Comment by ReginaldHopkins** [comment]
In the mean time you can execute multiple snowflake statements as per:
https://github.com/dbeaver/dbeaver/issues/2244

**Comment by adde-rishimehta** [comment]
Has anyone figured this out yet?

**Comment by Rishi91991** [comment]
Has anyone figured this out via Dbeaver? Thanks.

**Comment by Rishi91991** [comment]
You can execute using command `Option+X` in MacOS.
