### ISSUE TITLE
SQLCommandInclude Error when trying to source 'some.sql'

### ISSUE THREAD

**Issue by mnott** [dbeaver/dbeaver#7176]
#### System information: 
- Operating system (distribution) and version: MacOS Catalina
- DBeaver version: 6.2.4.201911031605
- Additional extensions: All

#### Connection specification:
- Database name and version MySQL 8
- Driver name MySQL 8 driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

I cannot run the following command:

SOURCE some.sql;

#### Steps to reproduce, if exist:

Create a file some.sql. Create some other.sql. Inside that other.sql, try to source the some.sql.

It works if done right out of the mysql client, but doesn't work from within DBeaver.

#### Include any warning/errors/backtraces from the logs

org.jkiss.dbeaver.model.exec.DBCException: Can't load class 'org.jkiss.dbeaver.runtime.sql.commands.SQLCommandInclude'
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:786)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2852)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Can't load class 'org.jkiss.dbeaver.runtime.sql.commands.SQLCommandInclude'
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:186)
	at org.jkiss.dbeaver.ui.editors.sql.registry.SQLCommandHandlerDescriptor.createHandler(SQLCommandHandlerDescriptor.java:68)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeControlCommand(SQLQueryJob.java:567)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:316)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:781)
	... 7 more

**Comment by mnott** [comment]
@include "some.sql" 

works.

**Comment by antongorodezkiy** [comment]
It seems the bug is still there
