### ISSUE TITLE
Unsupported object type: oracle.sql.OPAQUE

### ISSUE THREAD

**Issue by ursabig** [dbeaver/dbeaver#7210]
Hi! I've been looking at previous issues, but I haven't found the same.

My table shows a warning: «Unsupported object type: oracle.sql.OPAQUE»

Stacktrace:
`org.jkiss.dbeaver.model.exec.DBCException: Unsupported object type: oracle.sql.OPAQUE
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:84)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:123)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:200)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
#### System information
- Windows 10 Pro
- DBeaver version: 6.2.4.201911031605

#### Connection specification
- Database orcl10
- Driver Oracle
- Don't use tunnels or proxies
---
Thanks :)

![dbeaver_xmltype](https://user-images.githubusercontent.com/57089536/68670986-54be2180-055f-11ea-9efd-21168237e8d4.png)

**Comment by uslss** [comment]
could you clarify what the type of the column where error appears? or maybe you could provide ddl?

**Comment by ursabig** [comment]
Sorry, of course — xmltype.

`  CREATE TABLE "ACPS"."XMLCALLCARDS" 
   (	"F_PID" NUMBER(19,0) NOT NULL ENABLE, 
	"CALLCARDID" NUMBER(19,0), 
	"CALLCARDNUM" NUMBER(19,0), 
	"CREATETIME" TIMESTAMP (6), 
	"PDFTIME" TIMESTAMP (6), 
	"SIGNATURETIME" TIMESTAMP (6), 
	"XML" "ACPS"."XMLTYPE", 
	"XMLTIME" TIMESTAMP (6), 
	"PDF" BLOB, 
	"SIGNATURE" BLOB, 
	 PRIMARY KEY ("F_PID")`

Driver Oracle ojdbc6-11.2.0.2.0.jar installed.

**Comment by serge-rider** [comment]
You need to add xdb.jar in the driver classpath configuration.
