### ISSUE TITLE
[help] runtime error: IllegalArgumentException

### ISSUE THREAD

**Issue by ngxlua** [dbeaver/dbeaver#7216]
system:
```
Ubuntu 16.04 KDE
```

error:
```
2019-11-13 11:19:59.408 - java.lang.IllegalArgumentException: No enum constant org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn.KeyType.key
java.lang.IllegalArgumentException: No enum constant org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn.KeyType.key
 at java.lang.Enum.valueOf(Enum.java:238)
 at org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn$KeyType.valueOf(MySQLTableColumn.java:1)
 at org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn.loadInfo(MySQLTableColumn.java:129)
...
```

During the use of a lot of this kind of error, may I ask how to solve, thank you

**Comment by ngxlua** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/31426367/68757352-c624cf80-0646-11ea-854b-b51cc3aa924e.png">

Also, this error occurs when I hold down the CTRL key and mouse over the database table name

**Comment by serge-rider** [comment]
@ngxlua What is your database? It seems to be MySQL based but not pure MySQL.

Could you post error log for the second error?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by ngxlua** [comment]
@serge-rider 

Thank you for your reply. I found the reason, which was caused by the incompatibility of our mysql proxy.
