### ISSUE TITLE
er diagram feils to open on start

### ISSUE THREAD

**Issue by jernejkubuntu** [dbeaver/dbeaver#7301]
#### System information: 
- Operating system (distribution) and version
kubuntu 19.10
- DBeaver version
6.2.5
- Additional extensions

#### Connection specification:
- Database name and version
postgresql 10

#### Steps to reproduce, if exist:
1. create diagram and link to connection
2. open diagram
3. close dbever and live the diagram open
4. reopen/rerun dbever
5. the diagram is empty and an error in the log.
 
if you close an reopen the er diagram, it displays ok.
the connection to the db is automatically established in the back ground.

#### Include any warning/errors/backtraces from the logs
[log.txt](https://github.com/dbeaver/dbeaver/files/3895424/log.txt)

!MESSAGE Invalid thread access
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	.....
	at org.jkiss.dbeaver.ui.SharedTextColors.getColor(SharedTextColors.java:55)
	at org.jkiss.dbeaver.ui.UIUtils.getSharedColor(UIUtils.java:1716)
	at org.jkiss.dbeaver.ext.erd.model.DiagramLoader.loadNodeVisualInfo(DiagramLoader.java:700)
......
org.jkiss.dbeaver.ext.erd.editor.ERDEditorStandalone$1.evaluate(ERDEditorStandalone.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
cannot reproduce it anymore in 7.0.3
if it is still actual for you - feel free to reopen the ticket
