### ISSUE TITLE
Oracle: Error appears when trying to create Data Type

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7318]
#### System information:  
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.0 EA

#### Connection specification:
- Database name and version Oracle

#### Describe the problem you're observing:
Error appears when trying to create new Data type
#### Steps to reproduce, if exist:
1. Open Connection - Global Metadata - Type
2. Try to create new Data Type
![image](https://user-images.githubusercontent.com/31996417/69903481-ed033580-13aa-11ea-89f6-702fa68866e3.png)

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Sat Nov 30 19:50:23 MSK 2019
> Can't determine child element type for container 'Types'
> 
> org.jkiss.dbeaver.DBException: Can't determine child element type for container 'Types'
> 	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase.createNewObject(NavigatorHandlerObjectCreateBase.java:76)
> 	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:96)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
> 
```

**Comment by serge-rider** [comment]
How do you call this action? It was removed recently:
![image](https://user-images.githubusercontent.com/6398845/69903762-f2627f00-13ae-11ea-9670-db2554231b6f.png)

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/69903786-584f0680-13af-11ea-8ec8-e4328bf46511.png)

**Comment by uslss** [comment]
@serge-rider the same issue is reproducible for the Table triggers 
![image](https://user-images.githubusercontent.com/31996417/69904189-dbbf2680-13b4-11ea-862e-9869bb97cc65.png)
![image](https://user-images.githubusercontent.com/31996417/69904200-01e4c680-13b5-11ea-84ad-18a0955a9261.png)

**Comment by serge-rider** [comment]
Fixed (for both types and triggers)

**Comment by uslss** [comment]
verified
