### ISSUE TITLE
Oracle: Constraint for the view couldn't be created

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7319]
#### System information:  
- Operating system (distribution) and version win 10 
- DBeaver version 6.3.0 EA

#### Connection specification:
- Database name and version Oracle
#### Describe the problem you're observing:
Constraint for the view couldn't be created - error appears
#### Steps to reproduce, if exist:
Try to create and save any constraint for the View
![image](https://user-images.githubusercontent.com/31996417/69903582-7b2beb80-13ac-11ea-927f-c28952e2b663.png)

```
> 2019-11-30 20:01:34.159 - Error evaluating expression 'object.system' on node 'Schemas': 1:7 unsolvable property 'system'
> 2019-11-30 20:01:34.290 - Error evaluating expression 'object.system' on node 'Schemas': 1:7 unsolvable property 'system'
> 2019-11-30 20:03:21.289 - Error evaluating expression 'object.system' on node 'Schemas': 1:7 unsolvable property 'system'
> 2019-11-30 20:03:26.799 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [942] [42000]: ORA-00942: table or view does not exist
> 
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:48)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:189)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:111)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:333)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:331)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:306)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1073)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
> 
> 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
> 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
> 	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
> 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
> 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
> 	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
> 	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
> 	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
> 	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:896)
> 	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
> 	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1737)
> 	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1692)
> 	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:300)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	... 10 more
> Caused by: Error : 942, Position : 0, Sql = ALTER TABLE HR.EMP_DETAILS_VIEW ADD CONSTRAINT EMP_DETAILS_VIEW_PK PRIMARY KEY (EMPLOYEE_ID) ENABLE, OriginalSql = ALTER TABLE HR.EMP_DETAILS_VIEW ADD CONSTRAINT EMP_DETAILS_VIEW_PK PRIMARY KEY (EMPLOYEE_ID) ENABLE, Error Msg = ORA-00942: table or view does not exist
> 
> 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
> 	... 24 more
> 
```

**Comment by serge-rider** [comment]
View constraints are rare and use different DDL syntax.
https://dbaora.com/constraints-on-views-in-oracle/

It is a feature request actually.

**Comment by serge-rider** [comment]
Done

**Comment by uslss** [comment]
verified
