### ISSUE TITLE
PostgreSQL can't edit JSONB fields

### ISSUE THREAD

**Issue by gennari-dkt** [dbeaver/dbeaver#7331]
#### System information: 
- Windows 10 build 1909
- DBeaver version: 6.30

#### Connection specification:
- PostgreSQL 10
- PostgreSQL JDBC 42.2.6
- No tunnels

#### Describe the problem you're observing:
If I open a table, I can not edit column of type JSONB (I can not try a JSON column at the moment) and I can not view data value panel.

#### Steps to reproduce, if exist:
Open a table an try to edit JSONB column

#### Include any warning/errors/backtraces from the logs
![Annotation 2019-12-02 090840](https://user-images.githubusercontent.com/54432250/69940790-600fc780-14e3-11ea-92db-bd27a304251e.png)

Very kind regards.

Ale

**Comment by r-da** [comment]
Same on linux. If you run dbeaver from the command line, you can see the following java exception:

```
2019-12-02 12:31:04.814 - Can't determine object class 'org.jkiss.dbeaver.ui.data.managers.ContentValueManager'
java.lang.ClassNotFoundException: org.jkiss.dbeaver.ui.data.managers.ContentValueManager cannot be found by org.jkiss.dbeaver.ext.postgresql.ui_1.0.0.201912011827
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:514)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:620)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor.getObjectClass(AbstractDescriptor.java:310)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor.getObjectClass(AbstractDescriptor.java:303)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.getObjectClass(AbstractDescriptor.java:149)
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:189)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerDescriptor.getInstance(ValueManagerDescriptor.java:116)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findManager(ValueManagerRegistry.java:90)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.getManager(ValueManagerRegistry.java:71)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findValueManager(ValueManagerRegistry.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetValueController.getValueManager(ResultSetValueController.java:210)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:214)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:188)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$1(ValueViewerPanel.java:115)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:243)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$37(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:219)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1221)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseDown(LightGrid.java:3007)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.access$2(LightGrid.java:2816)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid$1.mouseDown(LightGrid.java:2723)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4926)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4420)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
2019-12-02 12:31:04.817 - Event loop exception
java.lang.IllegalStateException: Can't instantiate value manager 'org.jkiss.dbeaver.ui.data.managers.ContentValueManager'
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerDescriptor.getInstance(ValueManagerDescriptor.java:119)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findManager(ValueManagerRegistry.java:90)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.getManager(ValueManagerRegistry.java:71)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerRegistry.findValueManager(ValueManagerRegistry.java:98)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetValueController.getValueManager(ResultSetValueController.java:210)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.viewValue(ValueViewerPanel.java:214)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.refreshValue(ValueViewerPanel.java:188)
	at org.jkiss.dbeaver.ui.controls.resultset.panel.valueviewer.ValueViewerPanel.lambda$1(ValueViewerPanel.java:115)
	at org.jkiss.dbeaver.ui.controls.resultset.AbstractPresentation.fireSelectionChanged(AbstractPresentation.java:243)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation.access$37(SpreadsheetPresentation.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.spreadsheet.SpreadsheetPresentation$1.widgetSelected(SpreadsheetPresentation.java:219)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1221)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseDown(LightGrid.java:3007)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.access$2(LightGrid.java:2816)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid$1.mouseDown(LightGrid.java:2723)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4926)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4420)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: org.jkiss.dbeaver.DBException: Can't load class 'org.jkiss.dbeaver.ui.data.managers.ContentValueManager'
	at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:191)
	at org.jkiss.dbeaver.ui.data.registry.ValueManagerDescriptor.getInstance(ValueManagerDescriptor.java:116)
	... 48 more
```

**Comment by felipebraga** [comment]
Same here.

**Comment by serge-rider** [comment]
This is the same issue as in #7333
Already fixed. EA will be published shortly. Maybe we will even release hotfix version.
