### ISSUE TITLE
Firebird 3 Array Datatype

### ISSUE THREAD

**Issue by dogriz** [dbeaver/dbeaver#7338]
**Is your feature request related to a problem? Please describe.**

DBeaver 6.3.0 is unable to display array datatype for Firebird 3 database (Jaybird 3.0.8).
For example, when you try to open table JOB (employee database), message:

> SQL Error [0A000]: Types.ARRAY: SQL type for this field is not yet supported.

is shown.

`org.jkiss.dbeaver.model.exec.DBCException: SQL Error [0A000]: Types.ARRAY: SQL type for this field is not yet supported.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:171)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3429)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.firebirdsql.jdbc.FBDriverNotCapableException: Types.ARRAY: SQL type for this field is not yet supported.
	at org.firebirdsql.jdbc.field.FBField.createField(FBField.java:305)
	at org.firebirdsql.jdbc.field.FBField.createField(FBField.java:244)
	at org.firebirdsql.jdbc.AbstractResultSet.prepareVars(AbstractResultSet.java:265)
	at org.firebirdsql.jdbc.AbstractResultSet.<init>(AbstractResultSet.java:130)
	at org.firebirdsql.jdbc.FBResultSet.<init>(FBResultSet.java:45)
	at org.firebirdsql.jdbc.FBStatement.getResultSet(FBStatement.java:888)
	at org.firebirdsql.jdbc.FBStatement.getResultSet(FBStatement.java:868)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getResultSet(JDBCStatementImpl.java:598)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:168)
	... 8 more`

**Comment by mkgrgis** [comment]
Firebird 3 Array ≈ PostgreSQL [ ] array. Pg-array code may be useful for this feature.

**Comment by mrotteveel** [comment]
Jaybird (Firebird JDBC driver) doesn't support arrays, and as DBeaver needs Jaybird for this, it can't do this.

Arrays in Firebird are more an historic artifact from its Interbase-legacy. They predate its support for the SQL query language and manipulation of arrays through SQL is extremely limited. It is unlikely that I'll ever implement support for arrays in Jaybird.

The ticket to add support is [JDBC-109](http://tracker.firebirdsql.org/browse/JDBC-109). As mentioned there, I'm willing to accept pull requests, but I don't think I'll do it myself.
