### ISSUE TITLE
Unable to create or alter mysql event 

### ISSUE THREAD

**Issue by samwelll** [dbeaver/dbeaver#7363]
#### System information: 
- Operating system (distribution) and version: macOS Mojave 10.14.6
- DBeaver version: 6.3.0
- Additional extensions: SSHJ

#### Connection specification:
- Database name and version : InnoDB
- Driver name: mariadb
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : Yes on some connections but bug is reproduced on both types of connection.
- User has event rights (create, alter, drop and execute).

#### Describe the problem you're observing:
At event creation, the fields in details tab are not editables. When modifying and saving the code in source tab the header is duplicated and genrates an error.
At event alteration, the modification is not taken into account. 
#### Include any warning/errors/backtraces from the logs
2019-12-04 13:39:14.386 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1064] [42000]: (conn=82828) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'null
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:48)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:189)
	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:111)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:333)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:331)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:306)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1073)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: (conn=82828) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'null
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:248)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:338)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:389)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 10 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'null
DISABLE ON SLAVE
DO CREATE EVENT fix_deliv
ON SCHEDULE EVERY 1 DAY
DISABLE ' at line 3
Query is: CREATE EVENT fix_deliv
ON SCHEDULE EVERY null null
DISABLE ON SLAVE
DO CREATE EVENT fix_deliv
ON SCHEDULE EVERY 1 DAY
DISABLE ON SLAVE
DO SELECT 1
#### I apologize in advance if I misunderstood something in the dbeaver behaviour.,Thank you to the team for the great job done already.

**Comment by DevJackSmith** [comment]
Same issue, no errors in error log. on 10.15.2 MacOS and 6.3.0 DBeaver.

To easily replicate open existing event for editing, change something, save, refresh.
Expected result that the change persists, actual result that the change reverts.

**Comment by serge-rider** [comment]
Fixed (both cases)

**Comment by uslss** [comment]
verified
