### ISSUE TITLE
Execution plan: "Print" Window can't be opened via context menu

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7378]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version DBeaver 6.3.0 EE

#### Connection specification:
- Database name and version MySQL

#### Describe the problem you're observing:
Execution plan: "Print" Window can't be opened via context menu. But shortcut "Ctrl+P" works properly.

#### Steps to reproduce, if exist:
Click "print" in Execution plan context menu.

Actual result: 
1.No window appears after clicking "print"
 2. An error is displayed in "Error log" Window

#### Include any warning/errors/backtraces from the logs
at org.eclipse.graphiti.ui.internal.editor.GFCommandStack.execute(GFCommandStack.java:136)
	at org.eclipse.graphiti.ui.internal.action.PrintGraphicalViewerAction.executeOnCommandStack(PrintGraphicalViewerAction.java:144)
	at org.eclipse.graphiti.ui.internal.action.PrintGraphicalViewerAction.run(PrintGraphicalViewerAction.java:127)

**Comment by kseniiaguzeeva** [comment]
moved to EE
