### ISSUE TITLE
Import task editing: btn "Next" doesn't work on step "settings" of Wizard

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7379]
#### System information:  
- Operating system (distribution) and version Windows 10
- DBeaver version 6.3.0 EE

#### Connection specification:
- Database name and version Mysql

#### Describe the problem you're observing:
Btn "Next" doesn't work on step "settings" of Wizard, if an import task was opened for editing and Target table was changed.
#### Steps to reproduce, if exist:
Precondition:
An import task is created.
Steps:
Select "Edit" in the task context menu> 
change the table in "Import into">press "Next" btns in Wizard steps.

Actual result: btn "Next" doesn't work on step "settings" of Wizard.

**Comment by serge-rider** [comment]
Are there any logs?

**Comment by kseniiaguzeeva** [comment]
Please see:
null
org.jkiss.dbeaver.model
Error
Sat Dec 07 09:20:37 MSK 2019
Event loop exception
![2MPRTUys2P](https://user-images.githubusercontent.com/51405061/70370010-edcc2800-18d2-11ea-96ea-d4283d7ab23b.gif)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/3934800/dbeaver-debug.log)
[.log](https://github.com/dbeaver/dbeaver/files/3934802/default.log)

**Comment by serge-rider** [comment]
Still can't reproduce. From the log I see that task config become corrupted somehow but I can't realize how.
Could you make a video from the very beginning of task edit? Perhaps you did some other changes.

**Comment by ghanmikarim** [comment]
I have the same issue when i backup a database,  there are a NullpointerException : 
!ENTRY org.jkiss.dbeaver.model 4 0 2019-12-23 15:18:04.891
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-12-23 15:18:04.891
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskWizardExecutor.runTask(TaskWizardExecutor.java:48)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskProcessorUI.executeTask(TaskProcessorUI.java:67)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.runTask(TaskConfigurationWizard.java:186)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.performFinish(TaskConfigurationWizard.java:166)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractToolWizard.performFinish(AbstractToolWizard.java:267)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractImportExportWizard.performFinish(AbstractImportExportWizard.java:99)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizard.performFinish(PostgreBackupWizard.java:159)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:122)
	at org.jkiss.dbeaver.tasks.ui.nativetool.ToolWizardDialog.buttonPressed(ToolWizardDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreToolBackup.execute(PostgreToolBackup.java:39)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by serge-rider** [comment]
@ghanmikarim this seems to be dup of #7462

**Comment by kseniiaguzeeva** [comment]
Still can reproduce with little changes: btns "Next" and "Start" are not active in "Preview Data Import" of the wizard
![dbeaver_bb0kc6qPvZ](https://user-images.githubusercontent.com/51405061/72047737-445ec480-32cc-11ea-9436-c17d46d96c3a.png)

Steps are the same:
Precondition:
An import task is created.
Steps:
Select "Edit" in the task context menu>
change the table in "Import into">go through the Wizard.

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce anymore
