### ISSUE TITLE
SSH agent does not work

### ISSUE THREAD

**Issue by bgarret** [dbeaver/dbeaver#7424]
#### System information: 
- Operating system (distribution) and version : Arch Linux
- DBeaver version : 6.3.0
- Additional extensions

#### Describe the problem you're observing:

I have the following error message when trying to use the SSH agent method : `Unable to initialize SSH agent`, even though ssh-agent is running.

I traced it down to the following issue in jsch-agent-proxy : https://github.com/ymnk/jsch-agent-proxy/issues/31

To fix this on Arch Linux, install the `openbsd-netcat` instead of `gnu-netcat`.

This is not really a bug in DBeaver per se, but I thought I'd document it in case someone hits the same problem.

#### Include any warning/errors/backtraces from the logs

Error log

```
!SESSION 2019-12-16 10:20:26.572 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2019-12-16 10:20:46.417
!MESSAGE Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
```

Debug log

```
2019-12-16 10:26:26.014 - Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found
2019-12-16 10:26:29.293 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
	at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:115)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:73)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:182)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$13(UIUtils.java:1657)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2019-12-16 10:26:29.297 - ssh-agent connection exception
com.jcraft.jsch.agentproxy.AgentProxyException: netcat does not support -U option.
	at com.jcraft.jsch.agentproxy.usocket.NCUSocketFactory.<init>(NCUSocketFactory.java:70)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:122)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:73)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:182)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$13(UIUtils.java:1657)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by maratkalibek** [comment]
Now it should work. In ssh agent implementation, nc (netcat) is changed to jna unix sockets.

**Comment by uslss** [comment]
Hi @bgarret ,
you could test fix in EA version (https://dbeaver.com/files/ea/) :)
Please write back if it works or not for you.

**Comment by bgarret** [comment]
Works for me, tested with the Community Edition : https://dbeaver.io/files/ea/

**Comment by zmoginas** [comment]
> Works for me, tested with the Community Edition : https://dbeaver.io/files/ea/

This worked for me too. Thanks!
