### ISSUE TITLE
java.lang.NumberFormatException in Result tab

### ISSUE THREAD

**Issue by EugeneGunichev** [dbeaver/dbeaver#7459]
#### System information: 
- Operating system (distribution) and version: Windows 7 Enterprise, SP1, 64-bit
- DBeaver version: 6.3.1.201912221734
- Java version: java.runtime.name=OpenJDK Runtime Environment, java.runtime.version=11.0.5+10
- Additional extensions: absent

#### Connection specification:
- Database name and version: PostgreSQL 12.0, compiled by Visual C++ build 1914, 64-bit
- Driver name: PostgreSQL JDBC Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
I get a NumberFormatException when rendering result with a user defined type that contains field of type that extends built-in float data type.

#### Steps to reproduce, if exist:
For example.
create domain my_amount as float8 check (value >= 0 and value <= 999999999999);
create domain my_currency as text check(length(value) <= 10);

create type my_price as (
  amount my_amount,
  currency my_currency
);

select (123.45, 'USD')::my_price; -- result is not rendered due to mentioned error

Stacktrace:
java.lang.NumberFormatException: For input string: "123.45"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.convertStringToValue(PostgreUtils.java:497)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:118)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:123)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:676)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:500)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:420)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:412)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:771)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2843)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3434)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Thanks for the bug report.
This issue was caused by wrong metadata reading for domain data types.

**Comment by EugeneGunichev** [comment]
No problem. I'm happy to help improve such a great product.
Thank you.

**Comment by uslss** [comment]
verified
