### ISSUE TITLE
Error: unterminated dollar quote started at position xxx

### ISSUE THREAD

**Issue by HannesMas** [dbeaver/dbeaver#7460]
#### System information: 
- OS: windows 10
- DBeaver version: 6.3.1
- Additional extensions: none

#### Connection specification:
- PG version: PostgreSQL 9.6.9 on x86_64-pc-linux-gnu (Debian 9.6.9-2.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
- Driver name: PostgreSQL standard driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Next error is thrown when executing do block with an if statement inside:
'Unterminated dollar quote started at position 22 in SQL'. This used to work using DBeaver version 6.3.0. 
Actually, when selecting the code prior to running it, the sql is executed correctly. Only when putting cursor inside the do block and hitting 'ctrl + enter', the error message appears.

#### Steps to reproduce, if exist:
This block works:

```sql
do
$block$
    declare
        i integer[] := array[5,10, 11, 21];
        tmp_number int;
    begin
        foreach tmp_number IN array i
        loop
            raise notice '%', tmp_number;
        end loop;
    end;
$block$;
```

This does not work:

```sql
do
$block$
    declare
        i integer[] := array[5,10, 11, 21];
        tmp_number int;
    begin
        foreach tmp_number IN array i
        loop
            if tmp_number = 5
            then
                raise notice 'high %!', tmp_number;
            end if;
            raise notice '%', tmp_number;
        end loop;
    end;
$block$;
```

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: Unterminated dollar quote started at position 22 in SQL -- this does not
do
$block$
    declare
        i integer[] := array[5,10, 11, 21];
        tmp_number int;
    begin
        foreach tmp_number IN array i
        loop
            if tmp_number = 5
            then
                raise notice 'high %!', tmp_number;
            end if;
            RAISE NOTICE '%', tmp_number;
        END LOOP;
    end. Expected terminating $$
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:481)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:420)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:412)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:771)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2843)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3434)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 22 in SQL -- this does not
do
$block$
    declare
        i integer[] := array[5,10, 11, 21];
        tmp_number int;
    begin
        foreach tmp_number IN array i
        loop
            if tmp_number = 5
            then
                raise notice 'high %!', tmp_number;
            end if;
            RAISE NOTICE '%', tmp_number;
        END LOOP;
    end. Expected terminating $$
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1275)
	at org.postgresql.core.Parser.parseSql(Parser.java:1174)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:1126)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:314)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:285)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by serge-rider** [comment]
Fixed.
@uslss please test it with different PgSQL scripts (see linked tickets).

**Comment by timneedham** [comment]
Hi, Great to see this fix so quickly... thanks!
I'm sure you're all over this, but thought it might be worth mentioning: this issue also exhibits itself with  `CASE` ... `END CASE;` blocks (not just `IF` and `LOOP`)?

**Comment by uslss** [comment]
verified
