### ISSUE TITLE
Backup from PostgreSQL database doesn't work

### ISSUE THREAD

**Issue by savoierider** [dbeaver/dbeaver#7462]
## System information: 
- Windows 10 (15063.1387)
- DBeaver version :   6.3.1.201912221734
- Java version : 11.0.5

#### Connection specification:
- Database name and version : PostgreSQL 9.6
- Driver name
- No tunnel nor proxy

 (reproduce on Windows server 2016 whith same version of DBeaver and same version of Java)

#### My problem
If you want to backup a schema on PostgreSQL, the wizard open and you can chose your options.
When you click on "start" nothing append.

#### My logs
```
!ENTRY org.eclipse.ui 4 0 2019-12-23 16:38:10.925
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskWizardExecutor.runTask(TaskWizardExecutor.java:48)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskProcessorUI.executeTask(TaskProcessorUI.java:67)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.runTask(TaskConfigurationWizard.java:186)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.performFinish(TaskConfigurationWizard.java:166)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractToolWizard.performFinish(AbstractToolWizard.java:267)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractImportExportWizard.performFinish(AbstractImportExportWizard.java:99)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizard.performFinish(PostgreBackupWizard.java:159)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:122)
	at org.jkiss.dbeaver.tasks.ui.nativetool.ToolWizardDialog.buttonPressed(ToolWizardDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreToolBackup.execute(PostgreToolBackup.java:39)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.jkiss.dbeaver.model 4 0 2019-12-23 16:38:10.927
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2019-12-23 16:38:10.927
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskWizardExecutor.runTask(TaskWizardExecutor.java:48)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskProcessorUI.executeTask(TaskProcessorUI.java:67)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.runTask(TaskConfigurationWizard.java:186)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.performFinish(TaskConfigurationWizard.java:166)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractToolWizard.performFinish(AbstractToolWizard.java:267)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractImportExportWizard.performFinish(AbstractImportExportWizard.java:99)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizard.performFinish(PostgreBackupWizard.java:159)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:122)
	at org.jkiss.dbeaver.tasks.ui.nativetool.ToolWizardDialog.buttonPressed(ToolWizardDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreToolBackup.execute(PostgreToolBackup.java:39)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

**Comment by serge-rider** [comment]
Probably it is a result of #6972 and #7444 

We'll publish Early Access version with the fix on this week.

**Comment by savoierider** [comment]
Thanks for your answer. 
I'll wait, it's not a big problem sincė it's Christmas holliday.
And by the way, thank you very much for this amazing soft!

**Comment by marcelorccarvalho** [comment]
Backup do not start with postgresql V12 (Windows 10)
Last used folder information missing on  "Output folder" option.

**Comment by uslss** [comment]
verified
