### ISSUE TITLE
Timeout running queries on AWS Athena

### ISSUE THREAD

**Issue by workin-at-the-car-walsh** [dbeaver/dbeaver#7466]
#### System information: 
- WIndows 6.1.7601
- DBeaver 6.2.2 also reproduced on 6.3
- Java version 1.8.0_231
- JRE 1.8.0_231-b11

#### Connection specification:
- AWS athena database
- com.simba.athena.jdbc.Driver
- AthenaJDBC42_2.0.7

#### Describe the problem you're observing:

Connecting to Athena database on AWS using the above system described. Raised a case with AWS and the iam permissions do not seem to be the issue. Connection can be established with the database however when trying to execute a query, the query times out and returns the following error

SQL Error [100122] [HY000]: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.

Caused by: java.sql.SQLException: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.
	at com.simba.athena.athena.dataengine.AJStreamResultSet.<init>(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:475)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:414)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:406)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:765)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2848)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3429)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
Caused by: com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.
	... 17 more

AWS provided the following information and suggestions

These queries were successful in Athena side, although it seems DBeaver never made GetQueryResults API to Athena to fetch the results of these queries. In fact, Dbeaver seemed to be continually polling Athena query status using GetQueryExecution API in order to verify the completion of query. Repetition of these requests can be observed in the CloudTrail events. And since these polling requests were repeated too fast, some of them even got throttled by Athena. This could be the reason why Dbeaver error'ed out with mentioned exception before getting the results. 

Here's the expected workflow for Athena query:
1. Client starts Athena query using StartQueryExecution API, which returns the query ID
2. Client polls Athena to get the status of above query by using GetQueryExecution API [2] with query ID
3. If the query status in GetQueryExecution response is successful, client executes GetQueryResults [3] to get the results of query. Else, it continues polling by retrying GetQueryExecution API. If these retries are too fast, it could cause throttling and cause issues in client-side if error isn't handled properly.
4. Client displays the results or error of query to user

To reproduce this, I also tested my query in DBeaver (community edition and version 6.3.1.201912221734) and SQL Workbench (Build 125). Even though my query took multiple minutes, both clients seem to get and display the query results successfully. So, could you also confirm your DBeaver version and upgrade it if it isn't the latest one? Running the same query with same IAM user from other clients like SQL Workbench or AWS CLI or Console could also help to narrow this down. For DBeaver specific issue, you could also try increasing timeout and retry wait period in client application to backoff when Athena throttles GetQueryExecution requests [1]. Additionally, consulting DBeaver support or forum can be another helpful option.

I cannot figure out how to increase the retry wait period. This may be a quick fix
My colleagues can execute queries without fail using similar config to mine
Any other suggestions would be much appreciated

#### Include any warning/errors/backtraces from the logs
from dbeaver-debug folder

2019-12-24 09:43:27.944 - Connect with 'Athena - ouput' (aws_athena_jdbc_simba-16f30ba2b04-2cbcba8ba22ef623)
2019-12-24 09:43:29.331 - Connected (aws_athena_jdbc_simba-16f30ba2b04-2cbcba8ba22ef623, Simba Athena JDBC Driver [02.00.07.1012])
2019-12-24 09:45:30.230 - Error executing query
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [100122] [HY000]: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:463)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:394)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:764)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2928)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3427)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.
	at com.simba.athena.athena.dataengine.AJStreamResultSet.<init>(Unknown Source)
	at com.simba.athena.athena.dataengine.AJQueryExecutor.execute(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.execute(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:463)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:394)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:764)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2928)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:148)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3427)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
Caused by: com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100122) An error has occurred. Details: Exception during column initialization: com.simba.athena.support.exceptions.GeneralException: AWS_CLIENT_ERR.
	... 17 more

**Comment by serge-rider** [comment]
Please try latest dbeaver version, Athena driver was upgraded there.
If it won't help you could try to downgrade, e.g. to https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/AthenaJDBC41_2.0.2.jar

**Comment by moveout2** [comment]
I'm having basically the same problem. I can authenticate and execute a query, but the results are never returned. If I look in Athena's history, I see that my query returned very quickly with the proper results.

DBeaver continues to spin, as if it's waiting for results, until it finally times out.

Is there some JDBC or DBeaver setting that I'm missing?

**Comment by moveout2** [comment]
Okay, I fixed my problem: I needed to add the following directly into the jdbc url:

`S3OutputLocation=s3://aws-athena-query-results-[your_aws_account_number]-[your_aws_region]`

Adding this info into the DBeaver "S3 location" dialog box for my connection didn't work, but manually adding it to the URL did. 

I hope someone else finds this useful.

**Comment by karanrn** [comment]
I was not able to edit the URL, I tried modifying the URL Template but it was not picked up for the actual URL.
