### ISSUE TITLE
Problem with backup on version 6.3.1

### ISSUE THREAD

**Issue by DaniloMLisboa** [dbeaver/dbeaver#7493]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.3 LTS
- DBeaver version 6.3.1.201912221734
- Java version 1.8.0_191

#### Connection specification:
- Database name and version PostgreSQL 10.3
- Driver name postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing: 
When trying to backup a schema or table nothing happens after click on button start. On the console I get the error message "Event loop exception java.lang.NullPointerException" and a stack trace that doesn't show any cause.

#### Steps to reproduce, if exist: 
Right click on table/schema -> Tools -> Backup -> Start

#### Include any warning/errors/backtraces from the logs

Event loop exception
java.lang.NullPointerException
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskWizardExecutor.runTask(TaskWizardExecutor.java:48)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskProcessorUI.executeTask(TaskProcessorUI.java:67)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.runTask(TaskConfigurationWizard.java:186)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.performFinish(TaskConfigurationWizard.java:166)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractToolWizard.performFinish(AbstractToolWizard.java:267)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractImportExportWizard.performFinish(AbstractImportExportWizard.java:99)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreBackupWizard.performFinish(PostgreBackupWizard.java:159)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:122)
	at org.jkiss.dbeaver.tasks.ui.nativetool.ToolWizardDialog.buttonPressed(ToolWizardDialog.java:83)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4926)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4420)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ext.postgresql.tools.PostgreToolBackup.execute(PostgreToolBackup.java:39)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5667)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4926)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4420)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by pelado1605** [comment]
I get the same error when try to restore a database.

Ubuntu 16.04 LTS
Java version 1.8.0_201
DBeaver version 6.3.1.201912221734
Postrgresql version 11.4

**Comment by DaniloMLisboa** [comment]
Today I downgraded to version 5.x.x and noticed that this feature is working fine. I reinstalled version 6.3.1 to make sure the installation  would proceed with no issues and It did. But the backup feature doesn't work anyway.

**Comment by anbezi** [comment]
I get the same error when try to backup and restore a database.

Ubuntu 19.10
Java version 13.0.1
DBeaver version 6.3.1.201912221734
PostrgresSQL version 11.4

**Comment by lisaak1** [comment]
Same error with backup and restore on:

Debian 10
Java 1.8.0_231 by Oracle Corporation (64bit)
DBeaver 6.3.1.201912221734
PostgreSQL 11.5

Working version for me is DBeaver 6.2.3 (but some newer may work too, don't remember which I used for backup/restore as last).

**Comment by kseniiaguzeeva** [comment]
Most probably the ticket duplicates https://github.com/dbeaver/dbeaver/issues/7462

**Comment by serge-rider** [comment]
Please try new Early Access version (https://dbeaver.io/files/ea).

**Comment by tonifirnandes** [comment]
> Please try new Early Access version (https://dbeaver.io/files/ea).

Hi, thanks for the updates @serge-rider , but unfortunately the application cannot be opened.

OS Version: macOS Catalina Version 10.15.2

<img width="419" alt="Screenshot 2020-01-04 at 19 51 22" src="https://user-images.githubusercontent.com/3122029/71765830-96e65c80-2f2b-11ea-9104-33a79f9cb54d.png">

I think we will wait for the next release 6.3.2 for fixing toos->backup/restore feature.

Regards,
Toni

**Comment by krazibit** [comment]
fixed in 6.3.2 for me

**Comment by Obiwanbde** [comment]
I have tried with 6.3.3 and no problems

**Comment by dafranklin** [comment]
I was in version 6.x.x (6.1.x i think) and upgraded to this version and backup was working fine and now nothing happens when i click on the start button.

**Comment by Jacquers** [comment]
The Postgresql backup works in 6.2.4, but it's broken in 6.3.3 (I think since 6.3.x). The start button just does nothing when I click it.

Something else I noticed: When I select the objects (tables) to include in the first 'tab' of the backup screen, click next and then click back, the choice made is lost, like I never selected anything. The client binaries was also set to blank when I first tried it.

**Comment by dafranklin** [comment]
In my case, I've "solved" the "do nothing" part. I don't really know how but now i can do a backup but only in sql files. I think i checked and unchecked the "Use SQL INSERT instead of COPY for rows" box.
I also changed the Output folder to an existing folder, as it was set by default to an nonexistent folder.
Then the start works for me now.

However, when i try to backup it always backup the whole database, even thoug i only want to backup 1 table.
Very frustrating.

**Comment by Jacquers** [comment]
Changing the output folder to an existing one worked for me. Somehow the new version appended a dbeaver folder to the output folder setting that was previously saved.

I also had to change the output file pattern from .sql to .backup (which it previously was)
