### ISSUE TITLE
View couldn't be edited

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7531]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.2

#### Connection specification:
- Database name and version hadoop hive

#### Describe the problem you're observing:
View couldn't be edited - error appears
![image](https://user-images.githubusercontent.com/31996417/71782532-22272700-2fec-11ea-9e38-ae6e7425b21a.png)

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
> Framework arguments:  -runTask @General:y
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -runTask @General:y
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 05 18:49:17 MSK 2020
> org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
> 	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:363)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:864)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:872)
> 	at org.apache.hadoop.hive.ql.exec.DDLTask.createView(DDLTask.java:4607)
> 	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:396)
> 	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
> 	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
> 	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
> 	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
> 	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
> 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
> 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1232)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:255)
> 	... 11 more
> Caused by: AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42052)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42038)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:41964)
> 	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1199)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1185)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2399)
> 	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table_with_environment_context(SessionHiveMetaStoreClient.java:93)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:752)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:740)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
> 	at com.sun.proxy.$Proxy34.createTable(Unknown Source)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2330)
> 	at com.sun.proxy.$Proxy34.createTable(Unknown Source)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:857)
> 	... 22 more
> 
> 
> java.sql.SQLException: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
> 	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:363)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:864)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:872)
> 	at org.apache.hadoop.hive.ql.exec.DDLTask.createView(DDLTask.java:4607)
> 	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:396)
> 	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:199)
> 	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
> 	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2183)
> 	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1839)
> 	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1526)
> 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
> 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1232)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:255)
> 	... 11 more
> Caused by: AlreadyExistsException(message:Table newview3 already exists)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42052)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42038)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:41964)
> 	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1199)
> 	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1185)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2399)
> 	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.create_table_with_environment_context(SessionHiveMetaStoreClient.java:93)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:752)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:740)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:173)
> 	at com.sun.proxy.$Proxy34.createTable(Unknown Source)
> 	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2330)
> 	at com.sun.proxy.$Proxy34.createTable(Unknown Source)
> 	at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:857)
> 	... 22 more
> 
> 	at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:354)
> 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:245)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractObjectManager.executePersistAction(AbstractObjectManager.java:48)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.executeCommands(AbstractCommandContext.java:189)
> 	at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:111)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$1(EntityEditor.java:333)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:331)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$0(EntityEditor.java:306)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:1073)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
```

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D54](https://dbeaver.testquality.com/project/8805/result/1761730/defect/6109). Do not remove or edit.

**Comment by serge-rider** [comment]
What exactly SQL do you execute?

**Comment by uslss** [comment]
something like 
> CREATE VIEW `retail_demo.newview_1` AS
> SELECT
>     `email_addresses_dim_hive`.`customer_id`
> FROM
>     `retail_demo`.`email_addresses_dim_hive`

so i try to edit existing view (e.g. newview_1) and save it

**Comment by serge-rider** [comment]
Fixed (patched view DDL)

**Comment by uslss** [comment]
verified
