### ISSUE TITLE
Navigate -> Row Count doesn't work for hive

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7532]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version  6.3.2

#### Connection specification:
- Database name and version Hadoop Hive

#### Describe the problem you're observing:
**Navigate -> Row Count** doesn't work for hive - error appears

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
> Framework arguments:  -runTask @General:b
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -runTask @General:b
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 05 19:00:54 MSK 2020
> org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask
> 	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
> 	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:363)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 
> java.sql.SQLException: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask
> 	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
> 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
> 	at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
> 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:363)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 	at org.apache.hive.jdbc.HiveStatement.waitForOperationToComplete(HiveStatement.java:354)
> 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:245)
> 	at org.apache.hive.jdbc.HivePreparedStatement.execute(HivePreparedStatement.java:98)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.countData(JDBCTable.java:260)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$32(ResultSetViewer.java:3338)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.readRowCount(ResultSetViewer.java:3333)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.access$19(ResultSetViewer.java:3326)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$8$1.evaluate(ResultSetViewer.java:1608)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$8$1.evaluate(ResultSetViewer.java:1)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
> 	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
```

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D55](https://dbeaver.testquality.com/project/8805/result/1761631/defect/6110). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D59](https://dbeaver.testquality.com/project/8805/result/1761709/defect/6114). Do not remove or edit.

**Comment by serge-rider** [comment]
It doesn't work with TEZ engine.
```
set hive.execution.engine=mr;
```
will help
