### ISSUE TITLE
Import and db-db export isn't possible

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7534]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.2

#### Connection specification:
- Database name and version hadoop hive

#### Describe the problem you're observing:
Import and db-db export isn't possible - errors like 'Can't insert row' and 'Error inserting row' appears,

```
> 2020-01-05 20:17:22.957 - Error transfering data from email_addresses_dim_hive_202001052008.csv to `default`.test
> org.jkiss.dbeaver.model.exec.DBCException: Can't insert row
> 	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:236)
> 	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:266)
> 	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:206)
> 	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:140)
> 	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
> 	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:108)
> 	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:77)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> Caused by: org.jkiss.dbeaver.model.exec.DBCException: Error creating struct
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCComposite.getStructValue(JDBCComposite.java:144)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCStructValueHandler.bindParameter(JDBCStructValueHandler.java:98)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:64)
> 	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$1.bindStatement(JDBCTable.java:374)
> 	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
> 	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
> 	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:228)
> 	... 8 more
> Caused by: java.sql.SQLException: Method not supported
> 	at org.apache.hive.jdbc.HiveConnection.createStruct(HiveConnection.java:917)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.createStruct(JDBCConnectionImpl.java:671)
> 	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCComposite.getStructValue(JDBCComposite.java:139)
> 	... 14 more
```

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D60](https://dbeaver.testquality.com/project/8805/result/1761696/defect/6115). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D61](https://dbeaver.testquality.com/project/8805/result/1761697/defect/6116). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D62](https://dbeaver.testquality.com/project/8805/result/1761693/defect/6117). Do not remove or edit.

**Comment by uslss** [comment]
https://dbeaver.testquality.com defect [D63](https://dbeaver.testquality.com/project/8805/result/1761721/defect/6118). Do not remove or edit.

**Comment by serge-rider** [comment]
What table are you trying to import? Hive doesn't support struct data types (at least thru jdbc).

**Comment by uslss** [comment]
probably error with struct appears due to incorrect mapping (table 'test')
anyway, any attempt of import results with error
[tr_log.log](https://github.com/dbeaver/dbeaver/files/4031073/tr_log.log)

**Comment by serge-rider** [comment]
Error caused by tez engine in our test env.
Try to add 
`set hive.execution.engine=mr;`
in connection bootstrap queries.
