### ISSUE TITLE
DBeaver EE - SQL Error [200015] [58030]: JDBC driver encountered communication error. Message: HTTP status=407

### ISSUE THREAD

**Issue by VXTSchwab** [dbeaver/dbeaver#7562]
#### System information: 
- Operating system (distribution) and version
	Windows 10 - Build 1909 - English
- DBeaver version
	DBeaver Enterprise Edition 6.3.0.201912081802 
- Additional extensions
	None

#### Connection specification:
- Database name and version
	Snowflake  (current version)
- Driver name
	Snowflake JDBC 3.10.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
	None
	We are not using any proxies and the setting was disabled in DBeaver
	
#### Describe the problem you're observing:
When we try to connect to Snowflake we get the following error:
SQL Error [200015] [58030]: JDBC driver encountered communication error. Message: HTTP status=407.

We tried a clean installation but this did not help. We could only solve this problem to return to the 6.2 version of DBeaver.
Strangly this is only happening on one PC. The other 4 are working perfectly with the new DBeaver Enterprise Edition 6.3.0.201912081802 

#### Include any warning/errors/backtraces from the logs
`2019-12-16 16:02:15.573 - Can't read schema list
net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=407.
	at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:530)
	at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:445)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:362)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:517)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:261)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:199)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:808)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:259)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:167)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.executeAndReturnEmptyResultIfNotFound(SnowflakeDatabaseMetaData.java:3299)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getSchemas(SnowflakeDatabaseMetaData.java:2954)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getSchemas(SnowflakeDatabaseMetaData.java:1660)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSchemas(JDBCDatabaseMetaDataImpl.java:1125)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadSchemas(GenericMetaModel.java:150)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:502)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:843)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Dec 16, 2019 4:02:15 PM net.snowflake.client.jdbc.RestRequest execute
SEVERE: Error response: HTTP Response code: 407, request: POST https://XXXreplace_AccNameXXX.snowflakecomputing.com:443/queries/v1/query-request?requestId=04173fdb-1247-4a2c-89ad-7c6f9796e5a9 HTTP/1.1
Dec 16, 2019 4:02:15 PM net.snowflake.client.core.HttpUtil executeRequestInternal
SEVERE: Error executing request: POST https://XXXreplace_AccNameXXX.snowflakecomputing.com:443/queries/v1/query-request?requestId=04173fdb-1247-4a2c-89ad-7c6f9796e5a9 HTTP/1.1
Dec 16, 2019 4:02:15 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
SEVERE: Response status line reason: Proxy Authorization Required
Dec 16, 2019 4:02:15 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
2019-12-16 16:02:15.614 - net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=407.
net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=407.
	at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:530)
	at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:445)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:362)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:517)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:261)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:199)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:808)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:259)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:171)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.determineSelectedEntity(GenericDataSource.java:784)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:514)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:843)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2019-12-16 16:02:15.617 - Connected (snowflake_jdbc-16f0e413aae-38451976e10b1553, Snowflake [3.11.0])
Dec 16, 2019 4:02:20 PM net.snowflake.client.jdbc.RestRequest execute
SEVERE: Error response: HTTP Response code: 407, request: POST https://XXXreplace_AccNameXXX.snowflakecomputing.com:443/queries/v1/query-request?requestId=1481e9e9-fe70-4f9f-b286-ac84e2e7a294 HTTP/1.1
Dec 16, 2019 4:02:20 PM net.snowflake.client.core.HttpUtil executeRequestInternal
SEVERE: Error executing request: POST https://XXXreplace_AccNameXXX.snowflakecomputing.com:443/queries/v1/query-request?requestId=1481e9e9-fe70-4f9f-b286-ac84e2e7a294 HTTP/1.1
Dec 16, 2019 4:02:20 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
SEVERE: Response status line reason: Proxy Authorization Required
Dec 16, 2019 4:02:20 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
SEVERE: Response content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

2019-12-16 16:02:20.576 - org.jkiss.dbeaver.DBException: SQL Error [200015] [58030]: JDBC driver encountered communication error. Message: HTTP status=407.
org.jkiss.dbeaver.DBException: SQL Error [200015] [58030]: JDBC driver encountered communication error. Message: HTTP status=407.
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:74)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:136)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:815)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:796)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:846)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:200)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:69)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=407.
	at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:530)
	at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:445)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:362)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:517)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:261)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:199)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:808)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:259)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:167)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.executeAndReturnEmptyResultIfNotFound(SnowflakeDatabaseMetaData.java:3299)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getTables(SnowflakeDatabaseMetaData.java:1594)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:459)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:86)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:104)
	... 24 more
2019-12-16 16:02:20.579 - org.jkiss.dbeaver.DBException: SQL Error [200015] [58030]: JDBC driver encountered communication error. Message: HTTP status=407.
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:135)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:74)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getTables(GenericObjectContainer.java:136)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPhysicalTables(GenericObjectContainer.java:119)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.getPhysicalTables(GenericDataSource.java:349)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:815)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:796)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:846)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:200)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:69)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver encountered communication error. Message: HTTP status=407.
	at net.snowflake.client.core.HttpUtil.executeRequestInternal(HttpUtil.java:530)
	at net.snowflake.client.core.HttpUtil.executeRequest(HttpUtil.java:445)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:362)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:517)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:261)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:199)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:808)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:259)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery(SnowflakeStatementV1.java:167)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.executeAndReturnEmptyResultIfNotFound(SnowflakeDatabaseMetaData.java:3299)
	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData.getTables(SnowflakeDatabaseMetaData.java:1594)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:459)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:86)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.prepareObjectsStatement(JDBCStructLookupCache.java:134)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:104)
	... 24 more`

Thanks,

**Comment by uslss** [comment]
cannot reproduce it for now.
if issue is still actual for you - feel free to reopen it
