### ISSUE TITLE
Unable to modify PL/SQL Code : regression on 6.3.1

### ISSUE THREAD

**Issue by shagr4th** [dbeaver/dbeaver#7569]
#### System information: 
- Operating system (distribution) and version : Windows
- DBeaver version : 6.3.1 / 6.3.2

#### Connection specification:
- Database name and version : Oracle 11g

#### Describe the problem you're observing:

Since version 6.3.1 (it's working fine on 6.3.0), I can't save and persist any modifications on a PL/SQL code block. Dbeaver generate the following message box: "Couldn't generate alter script" (followed by a NullPointerException)

#### Include any warning/errors/backtraces from the logs

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.oracle.model.OracleUtils.addSchemaChangeActions(OracleUtils.java:215)
	at org.jkiss.dbeaver.ext.oracle.edit.OraclePackageManager.createOrReplaceProcedureQuery(OraclePackageManager.java:122)
	at org.jkiss.dbeaver.ext.oracle.edit.OraclePackageManager.addObjectModifyActions(OraclePackageManager.java:77)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectChangeCommand.getPersistActions(SQLObjectEditor.java:293)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$5(EntityEditor.java:485)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by shagr4th** [comment]
Well, just looked at the recent modifications and if I set an active schema on my connection, all is well. Is this action required now ?

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by uslss** [comment]
verified
