### ISSUE TITLE
 the memory to reach 1024MB

### ISSUE THREAD

**Issue by jyoisamu** [dbeaver/dbeaver#7583]
#### System information: 
- Operating system (distribution) and version
WIN１０　HOME
- DBeaver version
6.323202001051908
- Additional extensions
excel　export
#### Connection specification:
- Database name and version
MYSQL　5.3
- Driver name
MYSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
NO
#### Describe the problem you're observing:
Updating the display of data in a table regularly causes the memory to reach 1024MB

#### Steps to reproduce, if exist:
Updating the display of data in a table

**Comment by serge-rider** [comment]
How many rows are you fetching? 
What is the actual problem with this? 
Does dbeaver crash or you got some errors?

**Comment by jyoisamu** [comment]
> How many rows are you fetching?
The fitler was set,and only 3 rows.

> What is the actual problem with this?
The fitler was set and updated.
The computer operationbecame very heavy.

> Does dbeaver crash or you got some errors?
No crash,No errors.

**Comment by serge-rider** [comment]
Please attach error or debug log.
I still don't understand the nature of the problem.
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by jyoisamu** [comment]
> Please attach error or debug log.
> I still don't understand the nature of the problem.
> https://github.com/dbeaver/dbeaver/wiki/Log-files

!ENTRY org.eclipse.core.jobs 4 2 2020-01-09 16:23:31.656
!MESSAGE Unhandled error
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.eclipse.ui 4 0 2020-01-09 16:23:31.662
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-09 16:23:31.668
!MESSAGE Error while finishing result set fetch
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-01-09 16:23:31.668
!MESSAGE Java heap space
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-09 16:23:31.677
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-01-09 16:23:31.677
!MESSAGE Java heap space
!STACK 0
java.lang.OutOfMemoryError: Java heap space
!SESSION 2020-01-09 17:45:28.128 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by wp4nuv** [comment]
I believe my error is the same as the OP. I'm trying to import a 489MB file. I'm using version 6.3.5
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.setDocumentContent(FileStoreTextFileBuffer.java:536)
	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.initializeFileBufferContent(FileStoreTextFileBuffer.java:319)
	at org.eclipse.core.internal.filebuffers.FileStoreFileBuffer.create(FileStoreFileBuffer.java:66)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.connectFileStore(TextFileBufferManager.java:150)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.createFileInfo(TextFileDocumentProvider.java:571)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.connect(TextFileDocumentProvider.java:481)
	at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4212)
	at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:260)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1484)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.doSetInput(BaseTextEditor.java:96)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.doSetInput(SQLEditorBase.java:355)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.doSetInput(SQLEditor.java:1473)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3179)
	at org.eclipse.ui.texteditor.AbstractTextEditor$$Lambda$669/0x0000000100976440.run(Unknown Source)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2419)
	at org.eclipse.ui.internal.WorkbenchWindow$$Lambda$670/0x0000000100975c40.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2417)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3196)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3221)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.init(SQLEditor.java:1446)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:353)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:340)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

**Comment by raptr55** [comment]
same issue, cant export a single row with  this plugin:

Errore SQL: Internal jdbc driver error
  Internal jdbc driver error
  Internal jdbc driver error
    Java heap space
    Java heap space

**Comment by raptr55** [comment]
the difference between a table a can export and one i can't is a timestamp column in the table i can't export

possible? :mumble

**Comment by uslss** [comment]
cannot reproduce it for now.
if it is still actual - feel free to reopen an issue or create a new one.
