### ISSUE TITLE
Bind parameter :var isn't working properly

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7608]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version PostgreSQL

#### Describe the problem you're observing:
An error appears when trying to use parameter like **:var**
![image](https://user-images.githubusercontent.com/31996417/72220712-9ae63000-3564-11ea-8f5e-0b176ada77e1.png)

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
> Framework arguments:  -runTask @General:y
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -runTask @General:y
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 12 14:52:57 MSK 2020
> ERROR: syntax error at or near ":"
>   Position: 44
> 
> org.postgresql.util.PSQLException: ERROR: syntax error at or near ":"
>   Position: 44
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
> 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:486)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:424)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:416)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:776)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2861)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:110)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:108)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3452)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
verified
