### ISSUE TITLE
NPE on Hive get query columns

### ISSUE THREAD

**Issue by Hubbitus** [dbeaver/dbeaver#7634]
#### System information: 
- Fedora Linux 31
- DBeaver version: 6.3.2
- Additional extensions: none

#### Connection specification:
- Database name and version: Hive
- Driver name

#### Describe the problem you're observing:
Try to create table:
```sql
CREATE TABLE model_entityabstract2__ids_from_mssql__tmp (
	entityid bigint
)
```
and then expand columns in tree. Got exception:

```
CREATE TABLE model_entityabstract2__ids_from_mssql__tmp (
	entityid bigint
)
```
Screenshot:
![image](https://user-images.githubusercontent.com/720349/72365846-13d2bc80-370a-11ea-9df5-f731735c7de0.png)

**Comment by pijoter** [comment]
maybe linux specific problem
on windows 10 no problems here, 

Dbeaver 6.3.3.202001121117, 
Apache Hive 1.2.1000.2.6.4.0-91,
https://github.com/timveil/hive-jdbc-uber-jar/releases/download/v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar

**Comment by serge-rider** [comment]
Could you send error stacktrace (or log file)?

https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by Hubbitus** [comment]
[~/.local/share/.DBeaverData/workspace6/.metadata/dbeaver-debug.log                                                                                                                                                   [^]
 1Help                  2Menu                  3View                   4Edit](https://github.com/dbeaver/dbeaver/files/4066379/dbeaver-debug.log)
By some reason it placed in `~/.local/share/.DBeaverData`, not `~/.local/share/DBeaverData` as stated in doc.

Stacktrace:
```
2020-01-15 20:43:37.800 - org.jkiss.dbeaver.DBException: SQL Error: java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:149)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:815)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:796)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:846)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:200)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.hive.service.cli.HiveSQLException: java.lang.NullPointerException
	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:279)
	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:270)
	at org.apache.hive.jdbc.HiveDatabaseMetaData.getColumns(HiveDatabaseMetaData.java:220)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1152)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:133)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:96)
	... 23 more
Caused by: org.apache.hive.service.cli.HiveSQLException: java.lang.NullPointerException
	at org.apache.hive.service.cli.operation.GetColumnsOperation.runInternal(GetColumnsOperation.java:213)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:320)
	at org.apache.hive.service.cli.session.HiveSessionImpl.getColumns(HiveSessionImpl.java:678)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78)
	at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36)
	at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59)
	at com.sun.proxy.$Proxy43.getColumns(Unknown Source)
	at org.apache.hive.service.cli.CLIService.getColumns(CLIService.java:385)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.GetColumns(ThriftCLIService.java:622)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetColumns.getResult(TCLIService.java:1557)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetColumns.getResult(TCLIService.java:1542)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.hive.service.cli.operation.GetColumnsOperation.runInternal(GetColumnsOperation.java:173)
	... 24 more
```

**Comment by serge-rider** [comment]
I can't reproduce this on Windows as well.
Are you sure that you use the same driver on Linux?

Anyhow this is definitely not a bug in DBeaver but some misconfiguration issue with Hive.

**Comment by Hubbitus** [comment]
I use DBeaver version 6.3.2.202001051908
And driver: v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar

Why it is not the but of DBeaver if unhanded `NullPointerException` happened in their class `org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren` method?

**Comment by serge-rider** [comment]
Exceptions happens in 
`org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:279)`
while original NPE error is at
`org.apache.hive.service.cli.operation.GetColumnsOperation.runInternal(GetColumnsOperation.java:173)`
DBeaver just re-throws it.

**Comment by Hubbitus** [comment]
Can it be catched and handled?
I am sure it works some time ago. Can't say exactly on which DBeaver version.

**Comment by uslss** [comment]
cannot reproduce. is it still actual for you?

**Comment by uslss** [comment]
there is no update on ticket for a long time. if issue is still actual for you - feel free to reopen the ticket
