### ISSUE TITLE
NPE appears when trying to close Event pop-up from Query Manager

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7661]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3
#### Describe the problem you're observing:
When trying to close Event pop-up using OK button (Transaction only)  - NPE appears and window doesn't close
![image](https://user-images.githubusercontent.com/31996417/72533295-39c8a000-3875-11ea-9414-5dae7bdce250.png)
[transaction_NPE.log](https://github.com/dbeaver/dbeaver/files/4071779/transaction_NPE.log)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
still reproducible
Ok button do nothing, NPE appears
```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui
> Error
> Mon Jan 20 17:04:45 MSK 2020
> Unhandled event loop exception
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.editors.sql.dialogs.BaseSQLDialog.okPressed(BaseSQLDialog.java:165)
> 	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
> 	at org.jkiss.dbeaver.ui.editors.sql.dialogs.BaseSQLDialog.buttonPressed(BaseSQLDialog.java:159)
> 	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
> 	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.jkiss.dbeaver.ui.controls.querylog.QueryLogViewer.showEventDetails(QueryLogViewer.java:460)
> 	at org.jkiss.dbeaver.ui.controls.querylog.QueryLogViewer.access$18(QueryLogViewer.java:458)
> 	at org.jkiss.dbeaver.ui.controls.querylog.QueryLogViewer$10.widgetDefaultSelected(QueryLogViewer.java:416)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
> 
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
