### ISSUE TITLE
Filtering on foreign key column causes "ambiguous column naming in select list" error

### ISSUE THREAD

**Issue by finchie** [dbeaver/dbeaver#7673]
#### System information: 
- OS: **_Windows 10 Enterprise N - version 1809 (OS build 17763.805)_**
- DBeaver version: **_6.3.2.202001051908_**
- Additional extensions: **_none_**

#### Connection specification:
- Database name and version: _**Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production**_
- Driver name: **_Oracle - ojdbc6.jar_**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **_No_**

#### Describe the problem you're observing:
I'm trying to filter a foreign key column in the "Data" tab of a table by clicking the filter icon on the column header.
![011_click_filter_icon](https://user-images.githubusercontent.com/1968170/72602690-924c7b80-390f-11ea-9ff5-456ecccfcdba.png)

However, instead of displaying the "Filter by" dialog, an error dialog is displayed.
![022_error_dialog](https://user-images.githubusercontent.com/1968170/72603028-29193800-3910-11ea-918a-bbd62f919cd2.png)

#### Steps to reproduce, if exist:
I can deliberately reproduce the issue by doing these actions:
- click the filter icon
- click "Define Description" in the "Filter by" dialog
- choose the primary key column as the description

However, it appears that with some tables the "Define Description" configuration is set to the foreign key table's primary key by default and the error occurs as soon as I click the filter icon. Perhaps that is due to an algorithm being unable to automatically deduce a suitable column to use as the description?

Use the following SQL to set up the tables to deliberately invoke the error:
```SQL
-- create reference table
CREATE TABLE reference_table (
    ref_id NUMBER(10,0) PRIMARY KEY,
    number_col NUMBER(10,0) NOT NULL,
    another_number_col NUMBER(10,0) NOT NULL
    )
;

-- create table with foreign key
CREATE TABLE foreign_key_table (
    id NUMBER(10,0) PRIMARY KEY,
    ref_id NUMBER(10,0) NOT NULL,
    another_col NUMBER(10,0) NOT NULL
    )
;
-- add foreign key constraint
ALTER TABLE foreign_key_table ADD CONSTRAINT MY_FK FOREIGN KEY (ref_id)
    REFERENCES reference_table(ref_id);

-- insert data
INSERT INTO reference_table (ref_id, number_col, another_number_col)
    SELECT  level, (100 + level), 10000 + (111 * level)
    FROM    dual
    CONNECT BY
            level <= 10000
;
INSERT INTO foreign_key_table (id, ref_id, another_col)
    SELECT  level * 10, level, (111 * level) - 99
    FROM    dual
    CONNECT BY
            level <= 10000
;
```

Issue #6694 appears similar but in that case the issue was not reproducible.

#### Include any warning/errors/backtraces from the logs
The error log contains the following error:
```
java.sql.SQLSyntaxErrorException: ORA-00960: ambiguous column naming in select list

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:882)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3714)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1378)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readKeyEnumeration(JDBCTable.java:816)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.getDictionaryEnumeration(JDBCTable.java:563)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$3.readEnumeration(GenericFilterValueEdit.java:240)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.GenericFilterValueEdit$KeyLoadJob.run(GenericFilterValueEdit.java:434)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Session data:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```

**Comment by EdenYoung1** [comment]
I noticed that there is an similar problem at this issue https://github.com/dbeaver/dbeaver/issues/5569 . They are both related to selecting value in the foreign key column.  Perhaps we can refer to this issue to find more context about the bug or the cause of the bug ?

**Comment by uslss** [comment]
not reproducible against 7.3.4
