### ISSUE TITLE
Extra connection variables

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7681]
We need additional connection variables: `project.name` and `project.path` to be able to refer project resources in connection properties.
E.g. for ssh key files.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/72669631-6cc18e00-3a45-11ea-9024-8ebe11393a77.png)

Also now we have fancy variables dialog (click on hint label).

**Comment by uslss** [comment]
Reopened.
NPE appears when trying to use a variable on connection creating and then try to test connection
Values like localhost, port and others are shown only after connection saving
![image](https://user-images.githubusercontent.com/31996417/72887797-7127c880-3d1d-11ea-8e63-6f40a95514fc.png)

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui.workbench
> Error
> Wed Jan 22 13:42:06 MSK 2020
> Unhandled event loop exception
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.loadSettings(SSHTunnelConfiguratorUI.java:292)
> 	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.loadSettings(SSHTunnelConfiguratorUI.java:1)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetworkHandler.updateProfileList(ConnectionPageNetworkHandler.java:216)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetworkHandler.propertyChange(ConnectionPageNetworkHandler.java:256)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.firePropertyChange(ConnectionPageSettings.java:331)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetworkHandler.setConnectionConfigProfile(ConnectionPageNetworkHandler.java:186)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetworkHandler.access$3(ConnectionPageNetworkHandler.java:169)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageNetworkHandler$2.widgetSelected(ConnectionPageNetworkHandler.java:125)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:108)
> 	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceCreateHandler.execute(DataSourceCreateHandler.java:32)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

**Comment by serge-rider** [comment]
NPE was fixed.

> Values like localhost, port and others are shown only after connection saving

Yes, it is a limitation of this dialog. Not a bug.

**Comment by uslss** [comment]
verified
