### ISSUE TITLE
Error appears on Creating New Reference (from existing reference)

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7686]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Snowflake

#### Describe the problem you're observing:
Error appears when trying to create new reference from UI
![image](https://user-images.githubusercontent.com/31996417/72682142-1c950b00-3adb-11ea-98a0-e31153585a1e.png)

```

> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Sun Jan 19 16:43:19 MSK 2020
> Can't determine child element type for container 'References'
> 
> org.jkiss.dbeaver.DBException: Can't determine child element type for container 'References'
> 	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateBase.createNewObject(NavigatorHandlerObjectCreateBase.java:76)
> 	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerObjectCreateNew.execute(NavigatorHandlerObjectCreateNew.java:96)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:232)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

```

**Comment by serge-rider** [comment]
This happens with all datasources, not just snowflake.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
