### ISSUE TITLE
postgres: Can't load class 'org.jkiss.dbeaver.ext.postgresql.tools.maintenance.PostgreToolExtensionUninstall'

### ISSUE THREAD

**Issue by mweirauch** [dbeaver/dbeaver#7692]
#### System information: 
- Operating system (distribution) and version: Fedora 30
- DBeaver version: 6.3.2
- Additional extensions: -

#### Connection specification:
- Database name and version: postgres:9.6-alpine
- Driver name: -
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:
Can't load class 'org.jkiss.dbeaver.ext.postgresql.tools.maintenance.PostgreToolExtensionUninstall'

#### Steps to reproduce, if exist:
* browse to the 'Available Extensions" entry in the tree-table
* select an installed extension -> Tools -> Uninstall
* see afforementioned error

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-19 17:13:52.649
!MESSAGE Can't load class 'org.jkiss.dbeaver.ext.postgresql.tools.maintenance.PostgreToolExtensionUninstall'
!STACK 0
org.jkiss.dbeaver.DBException: Can't load class 'org.jkiss.dbeaver.ext.postgresql.tools.maintenance.PostgreToolExtensionUninstall'
        at org.jkiss.dbeaver.model.impl.AbstractDescriptor$ObjectType.createInstance(AbstractDescriptor.java:192)
        at org.jkiss.dbeaver.tools.registry.ToolDescriptor.createTool(ToolDescriptor.java:90)
        at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:58)
        at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
        at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
        at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:232)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by serge-rider** [comment]
Thanks for the bug report. This tool is still under development, I'll remove it from the menu in the next version.

**Comment by uslss** [comment]
verified
