### ISSUE TITLE
IllegalArgumentException on Export from Query

### ISSUE THREAD

**Issue by softcraft-development** [dbeaver/dbeaver#7712]
#### System information: 
- MacOS 10.14.6 (Mojave)
- DBeaver 6.3.3.202001191557
- java 13 2019-09-17

#### Connection specification:
- DB: Hive 1.2.1
- Driver: DBeaver Hive Default
- No tunnels or proxies

#### Describe the problem you're observing:
When I use the "Export from Query" flow, I get a "Task Execution Failed" error message.

Prior to upgrading to DBeaver 6.3.3, I would regularly export data from queries to a CSV file. Since the upgrade, this process is no longer working. After I go through the various export dialogs and click "Start", I immediately get an error message with "Task Execution Failed"

One interesting thing I found: the error message details (posted below) reference a file: `/Users/cwalker/.eclipse_keyring`. This file does not exist on my system.

The query is a simple one:

    select * from userdb_cwalker.cdh_contacts_combined;

I can execute this query & get results from the main DB window just fine; it's the export that's failing.

#### Steps to reproduce, if exist:
This happens 100% of the time for me, but I don't know what circumstances are necessary for others to reproduce it. I select my query, choose "Execute from Query" from the contextual menu, step through the dialogs, click "Start", and then get the error message.

#### Include any warning/errors/backtraces from the logs
In the Error pane, I see error messages logged for every attempt. Here's the details from the most useful one:
* Plug-In: org.jkiss.dbeaver.model
* Severity: Error
* Message: [none]
* Stack trace:
    java.lang.IllegalArgumentException: 
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:50)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.checkRange(TPRuleBasedScanner.java:116)
	at org.jkiss.dbeaver.model.text.parser.TPRuleBasedScanner.setRange(TPRuleBasedScanner.java:88)
	at org.jkiss.dbeaver.model.sql.parser.SQLScriptParser.parseParameters(SQLScriptParser.java:524)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:93)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:214)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:159)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

* Session data:
eclipse.buildId=unknown
java.version=13
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CA
Framework arguments:  -keyring /Users/cwalker/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/cwalker/.eclipse_keyring

**Comment by uslss** [comment]
seems that issue is similar to #7694 .
will be fixed in 6.3.4
anyway thanks for the bug report :)

**Comment by softcraft-development** [comment]
Confirmed that this is working for me in 6.3.4. Thank you!
