### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by jyoisamu** [dbeaver/dbeaver#7724]
#### System information: 
- Operating system (distribution) and version
WIN　１０　HOME
- DBeaver version

- Additional extensions

#### Connection specification:
- Database name and version
dbeaver-ce-6.3.3
- Driver name
MYSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
NO
#### Describe the problem you're observing:
When　I　install the one form a old version, Cannot start.
The startup screen appears and disappears.

#### Steps to reproduce, if exist:
install the one form a old version.

#### Include any warning/errors/backtraces from the logs

!SESSION 2020-01-23 15:01:37.821 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_231
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.ui.workbench 4 2 2020-01-23 15:01:46.151
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.core.helpers.ServiceHelper.getService(ServiceHelper.java:43)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.updateRoamingProfile(SimpleProfileRegistry.java:162)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.updateSelfProfile(SimpleProfileRegistry.java:153)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfileMap(SimpleProfileRegistry.java:380)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.internalGetProfile(SimpleProfileRegistry.java:257)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.getProfile(SimpleProfileRegistry.java:186)
	at org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdateScheduler.earlyStartup(AutomaticUpdateScheduler.java:81)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:79)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench$41.run(Workbench.java:2729)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2020-01-23 15:01:46.155
!MESSAGE "Executing the early startup extensions" 荳ｭ縺ｫ蜀��Κ繧ｨ繝ｩ繝ｼ縺檎匱逕溘＠縺ｾ縺励◆縲�
!STACK 0
java.lang.NullPointerException
	at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:361)
	at org.eclipse.core.runtime.Plugin.getLog(Plugin.java:237)
	at org.eclipse.ui.internal.WorkbenchPlugin.log(WorkbenchPlugin.java:742)
	at org.eclipse.ui.internal.EarlyStartupRunnable.handleException(EarlyStartupRunnable.java:71)
	at org.eclipse.core.runtime.SafeRunner.handleException(SafeRunner.java:74)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$41.run(Workbench.java:2729)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment]
Hi,
cannot reproduce. Which driver do you use to connect? What's your MySQL version?
![pksXPL6fn4](https://user-images.githubusercontent.com/51405061/72967764-1c468980-3dd3-11ea-8d89-09e403c3fc90.png)

**Comment by jyoisamu** [comment]
> Hi,
> cannot reproduce. Which driver do you use to connect? What's your MySQL version?

Hi,
MySQL version is 5.3.
But what happened when the application started.
I think that unrelated to version.

**Comment by kseniiaguzeeva** [comment]
Most probably it is an installation mistake. Please remove DBeaver completely (including registry cleanup and files). Then perform clean install from scratch.

**Comment by jyoisamu** [comment]
Removed ,  and del the registry what I researched.
At last,Installed it. 
But nothing changes.
@kseniiaguzeeva 

Help me!

**Comment by kseniiaguzeeva** [comment]
Please try to reset workspace. It looks like the same problem here: https://github.com/dbeaver/dbeaver/issues/5924

**Comment by jyoisamu** [comment]
@kseniiaguzeeva 
THANKS!

I was able to solve this by removing [DBeaverData],
It is solved.

I think the uninstall has room for improvement.

**Comment by uslss** [comment]
@jyoisamu if you have any proposals that could help to make dbeaver better, feel free to open new tickets.
It seems that issue from this ticket is solved.
Ticket closed
