### ISSUE TITLE
Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by s-e1** [dbeaver/dbeaver#7733]
- Operating system (distribution) and version -windows 10
- DBeaver version - 6.3.3
-
I'm trying to use it for a maria db. The program asks to install something. Then when I press on the > next to the projects name it alerts "Index 1 out of bounds for length 1".
Also when I create a new connection with maria db, it adds it and shows the pop up.

**Comment by kseniiaguzeeva** [comment]
Please tell where do you do this:  "Then when I press on the > next to the projects name"
Could you also send logs?

**Comment by s-e1** [comment]
This is what my screen looks like when I open the app before I do anything.
In the left of the names of the db's you can see the ">" symbols to expand the contents.
![Screenshot (9)](https://user-images.githubusercontent.com/49290335/73125789-903f8800-3fb3-11ea-9874-57a3a9f73e12.png)

**Comment by serge-rider** [comment]
Please check logs for any errors: https://github.com/dbeaver/dbeaver/wiki/Log-files

This may be MariaDB driver issue or dbeaver issue.

**Comment by s-e1** [comment]
How do I find the logs?

**Comment by s-e1** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/49290335/73125913-10b2b880-3fb5-11ea-9d70-af7c8a6ed7ef.png)

**Comment by serge-rider** [comment]
Please send it as text file (there is a button `Open log` in the toolbar).

**Comment by serge-rider** [comment]
If it is too big then please send it to serge@jkiss.org.

**Comment by s-e1** [comment]
This is a fraction of the error log, it didn't allow me to post the full error log since it's too long.
!SESSION 2020-01-23 21:25:46.786 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-23 21:27:44.828
!MESSAGE Service 'org.jkiss.dbeaver.runtime.ui.UIServiceSecurity' not found

!ENTRY org.apache.felix.scr 4 0 2020-01-23 21:41:36.792
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.io.IOException: Exception in opening zip file: D:\Program Files\DBeaver\plugins\org.apache.felix.scr_2.1.14.v20190123-1619.jar
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:340)
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:48)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:128)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:261)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathEntry.findEntry(ClasspathEntry.java:195)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:622)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:608)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:588)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:567)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:476)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.felix.scr.impl.AbstractExtender.destroyExtension(AbstractExtender.java:211)
	at org.apache.felix.scr.impl.AbstractExtender.bundleChanged(AbstractExtender.java:132)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.doStop(Module.java:656)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: D:\Program Files\DBeaver\plugins\org.apache.felix.scr_2.1.14.v20190123-1619.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:322)
	... 31 more

!ENTRY org.apache.felix.scr 4 0 2020-01-23 21:41:36.802
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: org/apache/felix/scr/impl/AbstractExtender$1
	at org.apache.felix.scr.impl.AbstractExtender.destroyExtension(AbstractExtender.java:211)
	at org.apache.felix.scr.impl.AbstractExtender.bundleChanged(AbstractExtender.java:132)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.doStop(Module.java:656)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.felix.scr.impl.AbstractExtender$1 cannot be found by org.apache.felix.scr_2.1.14.v20190123-1619
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:514)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

**Comment by uslss** [comment]
@s-e1 is it still actual for you?

**Comment by s-e1** [comment]
No.

**Comment by skannan-maf** [comment]
We encountered when trying to connect to Vertica DB (via VPN) on MAC (M1)
I checked using "nc" to see if the Host and port are accessible. They are.
But vertica jdbc Driver (and hence outside scope of Jkiss....) would simply throw this error at "clInit" function that is called from some function related to "versions"... I dont have stacktrace with me... But this is all I could gather in a Teams call. 
Does this ring a bell anybody?

**Comment by padraic-mcatee** [comment]
@skannan-maf I am having the same issue here.

**Comment by skannan-maf** [comment]
@padraic-mcatee  I think this means a "network reachability" issue. I think "nc" has 2 types of test. One with "zero data" and other with "data".... Try telnetting into the port and check if the port is really accessible. It could be a firewall blocking stuff. You may want to investigate that angle. Good luck!

**Comment by padraic-mcatee** [comment]
Port is reachable by telnet.

**Comment by skannan-maf** [comment]
Ah! Thats surprising! I remember trying a downgraded version of their driver and it clearly mentioned something on 'Network connectivity'...... Try a lower version of the driver and you will see a change of error msg... That might give you some clue. Good luck!

**Comment by padraic-mcatee** [comment]
That worked. Thank you!

I was using 11.0.x - downgrading to vertica jdbc version 9.0.x fixed it for me! I noticed this when I tried the connection using a separate SQL client which automatically downloaded version 9 over the later ones.
