### ISSUE TITLE
null artifact version when adding waffle-jna to PostgresSQL driver

### ISSUE THREAD

**Issue by nazar554** [dbeaver/dbeaver#7744]
#### System information: 
- Windows 10 Pro x64 1909 18363.592
- DBeaver 6.3.3.202001191557

#### Connection specification:
- PostgreSQL 12.1
- org.postgresql:postgresql:42.2.9
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

In order to use SSPI connection support with postgres driver I need to add `waffle-jna` library.
After adding the artifact through Maven `Add artifact` button the IDE fails to download the jars. I think the issue is inside one of dependencies ([org.checkerframework/checker-qual](https://mvnrepository.com/artifact/org.checkerframework/checker-qual)).

Dependency Group ID `com.github.waffle`
Artifact ID `waffle-jna`
Version `2.1.1`

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/12029825/73137129-ba4d8480-405d-11ea-8a70-490039044214.png)

If I continue I get this error:
```
Driver file download failed.
Do you want to retry?

Reason:
Can't open 'https://repo1.maven.org/maven2/org/checkerframework/checker-qual/null/checker-qual-null.jar': Not Found
```

After clicking abort & `Test Connection`:

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-01-26 16:40:34.482
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.getVersion(MavenArtifact.java:282)
	at org.jkiss.dbeaver.registry.maven.MavenArtifact.resolveVersion(MavenArtifact.java:361)
	at org.jkiss.dbeaver.registry.maven.MavenRepository.findArtifact(MavenRepository.java:193)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findInRepositories(MavenRegistry.java:206)
	at org.jkiss.dbeaver.registry.maven.MavenRegistry.findArtifact(MavenRegistry.java:183)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:213)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:127)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by nazar554** [comment]
BTW: Using `waffle-jna` version `1.9.1` works because it doesn't have the `checker-qual` dependency

**Comment by serge-rider** [comment]
Fixed. The bug was in XML parser. It parsed element body incorrectly if body contained some comments besides text.

**Comment by serge-rider** [comment]
@nazar554 Thanks for the bug report

**Comment by uslss** [comment]
verified
