### ISSUE TITLE
With Sybase jTDS, keywords are put in square brackets instead of quotation marks

### ISSUE THREAD

**Issue by maffe** [dbeaver/dbeaver#7755]
Columns which names are keywords are put in square brackets instead of quotation marks.

#### System information: 
- Windows 10 64 Bit
- DBeaver 6.3.3.202001191557

#### Connection specification:
- Sybase Adaptive Server Enterprise/12.0.0.7/P/EBF 10869 ROLLUP/Sun_svr4/OS 5.6/1996/32bit/FBO/Fri Feb 21 03:19:58 2003
- Driver: jTDS 1.3.1

#### Steps to reproduce, if exist:
- Create a table with columns named `date` and `action`
- Open the table’s context menu in the navigator and select “Read data in SQL console”
- Created query is `SELECT [date], [action] FROM foo.bar.baz;` and a “Confirm query execution” prompt appears

What should happen:
- Created query is `SELECT "date", "action" FROM foo.bar.baz;`, “Confirm query execution” prompt does not appear (actually the quotation marks are not necessary in this case)

#### Include any warning/errors/backtraces from the logs
Debug log:
```
2020-01-28 17:48:40.127 - Error while initializing context state
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:577)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
	... 6 more
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
It is a strange error as square brackets is a standard and the most typical way to quote identifiers in Sybase and SQL Server.
Maybe it is not supported in very old versions (Sybase 12 is almost 20 years old). Or it may be some database system setting.

@maffe could you provide any additional info?

**Comment by maffe** [comment]
It seems there is an option `quoted_identifier` which makes `"foo"` to be parsed as an identifier instead of a string. I don’t know how to query it directly, but as I can query columns using `"foo"` I assume it’s set to `ON`.

```
SELECT DISTINCT "type", 'type'
FROM orders
ORDER BY 1;
```
```
1	type
2	type
3	type
4	type
5	type
```
And when I try to use `[type]`, I get _SQL-Fehler [102] [37000]: Incorrect syntax near '['._

**Comment by serge-rider** [comment]
@maffe thanks for investigation.
Apparently square brackets support was added in Sybase 12.5.1+

I'll the fix in the next version.

**Comment by serge-rider** [comment]
BTW you could test the fix in EA version (https://dbeaver.io/files/ea)

**Comment by maffe** [comment]
> BTW you could test the fix in EA version (https://dbeaver.io/files/ea)

Thanks for the quick change. Now, after selecting “Read data in SQL console”, the editor uses quotation marks. However, I get two of these error messages:

![grafik](https://user-images.githubusercontent.com/515302/74245403-380ec280-4ce3-11ea-8b6e-e86161e0212e.png)
and the result area stays empty. When I try to execute the query using Ctrl+Return, I also get this message, even though the query in the editor doesn’t contain `[`.

**Comment by serge-rider** [comment]
@maffe Please send error/debug  log
https://github.com/dbeaver/dbeaver/wiki/Log-files

Also could you check Query Manager view for actual failed query.

**Comment by maffe** [comment]
I see there are `use` queries when selecting “Read data in SQL console” which use `[]`, for example `use [mydb]`. These `use` queries fail in 6.3.3 and 6.3.5 EA.

In 6.3.5 EA each time when trying to execute `SELECT "type" FROM mydb.dbo.orders`, query manager shows two failed `use [mydb]` queries and no `SELECT` query. Somehow there are always two `use` queries and only one error message window.

In 6.3.3, after replacing `[column]` manually with `"column"`, I can execute the query and the query manager shows the `SELECT` query and no `use` query.

6.3.5 EA debug log:

```
2020-02-13 15:33:06.019 - Create display
> Start Eclipse IDE UI-Anwendung [org.eclipse.ui.ide.application 1.3.500.v20191122-2109]
2020-02-13 15:33:06.144 - DBeaver 6.3.5.202002101953 is starting
2020-02-13 15:33:06.144 - OS: Windows 10 10.0 (amd64)
2020-02-13 15:33:06.144 - Java version: 1.8.0_181 by Oracle Corporation (64bit)
2020-02-13 15:33:06.144 - Install path: 'C:\Users\johndoe\AppData\Local\Temp\dbeaver-ce-6.3.5-win32.win32.x86_64\dbeaver'
2020-02-13 15:33:06.144 - Instance path: 'file:/C:/Users/johndoe/AppData/Roaming/DBeaverData/workspace6/'
2020-02-13 15:33:06.144 - Memory available 61Mb/910Mb
> Start Kern des Dateisystems [org.eclipse.core.filesystem 1.7.600.v20191122-2104]
> Start Kernressourcenverwaltung [org.eclipse.core.resources 3.13.600.v20191122-2104]
2020-02-13 15:33:06.378 - Starting RMI server at 44235
2020-02-13 15:33:06.425 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.800.v20190930-1643]
> Start Eclipse Anwendungsdienste [org.eclipse.e4.core.services 2.2.100.v20191122-2104]
> Start Eclipse Kontexte [org.eclipse.e4.core.contexts 1.8.300.v20191017-1404]
> Start Eclipse UI Anwendungsdienste [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start Eclipse BO Abhängigkeitsinjektion [org.eclipse.e4.ui.di 1.2.700.v20191114-0830]
> Start EMF - Allgemein [org.eclipse.emf.common 2.17.0.v20190920-0401]
> Start EMF-Ecore [org.eclipse.emf.ecore 2.20.0.v20190920-0401]
> Start EMF-XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse e4-Workbanch-Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.700.v20191030-1314]
> Start Ausdruck Sprache [org.eclipse.core.expressions 3.6.600.v20191122-2104]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.900.v20191114-0715]
> Start Eclipse Bindungsunterstützung [org.eclipse.e4.ui.bindings 0.12.700.v20191105-1310]
> Start Eclipse Abhängigkeitsinjizierungserweiterungen [org.eclipse.e4.core.di.extensions 0.15.400.v20191122-2104]
> Start Eclipse CSS SWT Unterstützung [org.eclipse.e4.ui.css.swt 0.13.700.v20191113-1031]
> Start Eclipse CSS SWT Themenunterstützung [org.eclipse.e4.ui.css.swt.theme 0.12.500.v20191125-1011]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.42.202002101953]
2020-02-13 15:33:08.379 - Initializing DBeaver 6.3.5
2020-02-13 15:33:08.379 - Host plugin: org.jkiss.dbeaver.core.application 6.3.5.202002101953
2020-02-13 15:33:08.379 - Initialize Core...
2020-02-13 15:33:08.379 - Can't find BC security provider. Use default JCE.
2020-02-13 15:33:08.379 - BouncyCastle not registered, using the default JCE provider
2020-02-13 15:33:08.535 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.27.202002101953]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.400.v20191008-0645]
> Start Benutzeroberfläche für die Verwaltung der Internetverbindungen [org.eclipse.ui.net 1.3.600.v20190925-1021]
> Start Verwaltung der Internetverbindungen [org.eclipse.core.net 1.3.700.v20191122-2107]
2020-02-13 15:33:08.582 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2020-02-13 15:33:08.582 - Core initialized (203ms)
2020-02-13 15:33:08.582 - Configure workbench window
> Start Hilfesystem - Core [org.eclipse.help 3.8.600.v20191123-0656]
2020-02-13 15:33:09.519 - Create actions
2020-02-13 15:33:09.535 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2020-02-13 15:33:09.535 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
Warning: NLS unused message: OpenWorkspaceAction_errorTitle in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: OpenWorkspaceAction_errorMessage in: org.eclipse.ui.internal.ide.messages
Warning: NLS unused message: IDEApplication_workspaceInUse_Cancel in: org.eclipse.ui.internal.ide.messages
> Start Standardtexteditor [org.eclipse.ui.editors 3.13.0.v20191203-1122]
> Start Dateipuffer [org.eclipse.core.filebuffers 3.6.800.v20191122-2108]
Warning: NLS unused message: QuickAccess_EnterSearch in: org.eclipse.ui.internal.quickaccess.messages
> Start Texteditor-Framework [org.eclipse.ui.workbench.texteditor 3.14.0.v20191122-2108]
2020-02-13 15:33:10.316 - Initialize workbench window
2020-02-13 15:33:10.332 - Finish initialization
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.27.202002101953]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.17.202002101953]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.27.202002101953]
> Start Team-Unterstützungskern [org.eclipse.team.core 3.8.800.v20191122-2107]
> Start Basiskomponente Vergleich [org.eclipse.compare.core 3.6.700.v20191122-2107]
> Start Equinox Versorgungskern [org.eclipse.equinox.p2.core 2.6.200.v20191014-1220]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.600.v20191016-0507]
> Start Equinox - Bereitstellung automatischer Aktualisierungen (EPP Automatic Update) [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.500.v20191016-0512]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.600.v20191002-0702]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.200.v20190701-1309]
> Start Eclipse Updateunterstützung [org.eclipse.equinox.p2.engine 2.6.500.v20191014-1645]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.300.v20191002-0702]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.600.v20191016-0510]
2020-02-13 15:33:12.707 - Total database drivers: 81 (81)
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.27.202002101953]
> Start Eclipse Updateunterstützung Benutzeroberfläche [org.eclipse.equinox.p2.ui 2.5.700.v20190930-1517]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.64.202002101953]
> Start DBeaver Tip des Tages [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.33.202002101953]
> Start DBeaver ER Diagramm [org.jkiss.dbeaver.ext.erd 2.0.129.202002101953]
> Start Konsole [org.eclipse.ui.console 3.9.0.v20191126-0912]
Warning: NLS unused message: sql_editor_resultset_filter_panel_btn_config_refresh in: org.jkiss.dbeaver.ui.controls.resultset.internal.ResultSetMessages
Warning: NLS unused message: sql_editor_resultset_filter_panel_btn_stop_refresh in: org.jkiss.dbeaver.ui.controls.resultset.internal.ResultSetMessages
2020-02-13 15:33:14.191 - Connect with 'Sybase mydb' (sybase_jtds-1636e214583-7f092db88ba25d0f)
> Start DBeaver SQL Server Support [org.jkiss.dbeaver.ext.mssql 1.0.121.202002101953]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.113.202002101953]
2020-02-13 15:33:14.269 - Execution context opened (Sybase mydb; Main; 0)
2020-02-13 15:33:14.426 - Execution context opened (Sybase mydb; Metadata; 1)
2020-02-13 15:33:14.629 - Connected (sybase_jtds-1636e214583-7f092db88ba25d0f, jTDS Type 4 JDBC Driver for MS SQL Server and Sybase [1.3.1])
2020-02-13 15:33:14.769 - Execution context opened (Sybase mydb; SQLEditor <Script-9.sql>; 2)
2020-02-13 15:33:14.863 - Error while initializing context state
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
	... 6 more
2020-02-13 15:33:19.863 - Can't get column 'schema_id': Invalid column name schema_id.
2020-02-13 15:33:25.535 - Can't get column 'IS_GENERATEDCOLUMN': Invalid column name IS_GENERATEDCOLUMN.
2020-02-13 15:33:26.332 - Execution context opened (Sybase mydb; SQLEditor <Script-10.sql>; 3)
2020-02-13 15:33:26.410 - Error while initializing context state
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
	... 6 more
2020-02-13 15:33:26.426 - org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:241)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:367)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:328)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:584)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:237)
	... 6 more
2020-02-13 15:33:37.004 - Execution context opened (Sybase mydb; SQLEditor <Script-10.sql>; 4)
2020-02-13 15:33:37.066 - Error while initializing context state
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
	... 6 more
2020-02-13 15:33:37.082 - org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:241)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:367)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:328)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:584)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:237)
	... 6 more
2020-02-13 15:33:49.582 - Execution context opened (Sybase mydb; SQLEditor <Script-10.sql>; 5)
2020-02-13 15:33:49.660 - Error while initializing context state
org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:160)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:188)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.initDefaultsFrom(GenericExecutionContext.java:156)
	... 6 more
2020-02-13 15:33:49.660 - org.jkiss.dbeaver.model.exec.DBCException: SQL-Fehler [102] [37000]: Incorrect syntax near '['.

	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:241)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.changeDefaultObject(DBExecUtils.java:367)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.setExecutionContextDefaults(DBExecUtils.java:328)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:584)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Incorrect syntax near '['.

	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultCatalog(GenericExecutionContext.java:237)
	... 6 more
2020-02-13 15:34:47.254 - Execution context closed (Sybase mydb, 2)
2020-02-13 15:34:47.597 - DBeaver is stopping
2020-02-13 15:34:47.597 - Stop RMI server
2020-02-13 15:34:47.660 - DBeaver shutdown completed
```

`.log` file was not generated.

**Comment by serge-rider** [comment]
Thanks for the details. `use [database]` clause was hardcoded. Now fixed.

**Comment by serge-rider** [comment]
New EA is ready

**Comment by maffe** [comment]
It seems only `use mydb` without any delimiters works with our Sybase system, at least I have not found any working delimiters. With the new EA version I get

> Can't open editor connection
> 
> Ursache:
> SQL-Fehler [911] [08004]: Attempt to locate entry in sysdatabases for database '"mydb"' by name failed - no entry found under that name. Make sure that name is entered properly.

**Comment by serge-rider** [comment]
Ugh. Legacy databases are weird.

**Comment by maffe** [comment]
6.3.5 release works fine, thank you!
