### ISSUE TITLE
Slow db info reads for snowflake

### ISSUE THREAD

**Issue by rpatkennyiii** [dbeaver/dbeaver#7778]
#### System information
- Operating system (distribution) and version: Windows 10 Enterprise V1803 
- DBeaver version: Version: 6.3.3.202001191557
- Additional extensions: 
    
#### Connection specification:
- Database name and version:
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  DBeaver Git support	1.0.6.201910072100
  Marketplace Client	1.8.1.v20191106-1317
  Vrapper	0.74.0
#### Describe the problem you're observing:
Queries run quickly, but reading table information from snowflake takes several mins.

#### Steps to reproduce, if exist:
Simple query on snowflake:
`select * from pat_ds.AIHHPatientData
limit 10;`

#### Include any warning/errors/backtraces from the logs
Error while initializing context state

SQL Error [2043] [02000]: SQL compilation error:
Object does not exist, or operation cannot be performed.

SQL compilation error:
Object does not exist, or operation cannot be performed.

net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Object does not exist, or operation cannot be performed.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:152)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:77)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:495)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:372)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:506)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:250)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:188)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:797)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:309)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.execute(SnowflakePreparedStatementV1.java:506)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.setDefaultSchema(GenericExecutionContext.java:280)
	at org.jkiss.dbeaver.ext.generic.model.GenericExecutionContext.refreshDefaults(GenericExecutionContext.java:296)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initializeContextState(GenericDataSource.java:190)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMetaContext(JDBCRemoteInstance.java:98)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:369)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:434)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:819)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Can't reproduce.
Please check what query dbeaver executes during table info reading.
You can do it in Query Manager view - https://github.com/dbeaver/dbeaver/wiki/Query-Manager (just enable metadata query types).

**Comment by rpatkennyiii** [comment]
sorry for the slow reply, my github email wasn't being sent to junk. I clicked on the metadata query option for query manager. Here is what I'm seeing: 
![DBeaver 6 3 5](https://user-images.githubusercontent.com/4820919/75471145-69c89000-5957-11ea-848f-82a6a7219027.gif)
