### ISSUE TITLE
Null Pointer Exception from convertStringToStruct()

### ISSUE THREAD

**Issue by timneedham** [dbeaver/dbeaver#7799]
#### System information: 
- Operating system (distribution) and version: `Ubuntu 18.04.3 LTS`
- DBeaver version: `6.3.3.2`
- Additional extensions: `None`

#### Connection specification:
- Database name and version: `PostgreSQL 11.6`
- Driver name: `PostgreSQL JDBC Driver`
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  `No`

#### Describe the problem you're observing:

DBeaver becomes unstable (throws null pointer exceptions and sometimes crashes) when viewing table data if (it seems) a type is in a different schema than the table.

#### Steps to reproduce, if exist:

``` sql
CREATE SCHEMA schema_a;

CREATE TYPE schema_a.bookmark AS (
  target_url varchar,
  link_text varchar
);

CREATE SCHEMA schema_b;

CREATE TABLE schema_b.orgs (
  id uuid NOT NULL,
  bookmarks schema_a.bookmark[]
);

INSERT INTO schema_b.orgs (id,bookmarks) VALUES 
('06374133-44d8-11ea-969d-9cb6d09a79f1', ARRAY[('https://google.com/', 'Some words')]::schema_a.bookmark[]),
('06374172-44d8-11ea-969d-9cb6d09a79f1', ARRAY[('https://github.com/', 'Words')]::schema_a.bookmark[]);
```
Then looking at the data in the `schema_a.orgs` table:

![type-issue-pic](https://user-images.githubusercontent.com/1216632/73595185-823abb80-450d-11ea-8590-230fe8845ad4.png)

* One weird thing, if the `Some words` text in the first row is inserted as just a single word, it seems to work OK?
* Also seems to work if the type is in the same schema as the table.
* And also seems fine if the data is returned via a `SELECT`.

#### Include any warning/errors/backtraces from the logs

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.convertStringToStruct(PostgreStructValueHandler.java:111)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreStructValueHandler.getValueFromObject(PostgreStructValueHandler.java:95)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.convertStringToSimpleValue(PostgreUtils.java:513)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.convertStringToValue(PostgreUtils.java:502)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.convertStringToCollection(PostgreArrayValueHandler.java:98)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:74)
	at org.jkiss.dbeaver.ext.postgresql.model.data.PostgreArrayValueHandler.getValueFromObject(PostgreArrayValueHandler.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetUtils.bindAttributes(ResultSetUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchEnd(ResultSetDataReceiver.java:163)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:213)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:110)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:159)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:108)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3454)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by serge-rider** [comment]
It is a bug in array parser.
PG driver returns arrays in string form. There were two issues which lead to this bug:
1. JDBC driver doesn't provide correct type info (Types.OBJECT instread of Types.ARRAY)
1. DBeaver parsed arrays of struct types incorrectly.

Fixed

**Comment by uslss** [comment]
verified
