### ISSUE TITLE
Select from DB2 z/OS SQL Error: Required character converter is not available

### ISSUE THREAD

**Issue by gitbernoire** [dbeaver/dbeaver#7897]
System information: 
- Operating system: Windows 10 
- DBeaver version: 5.3.4

Connection specification:
- Database name and version: DB2 z/OS - v11 NFM (z/OS 2.2)

Describe your question:
Hi
I'm getting this error in the output window for character fields (not numeric fields).  I've looked through existing issues and think it may have to do with a missing entry perhaps in the dbeaver.ini file - however wanted to see what the experts think.  This is the first time I've used DBeaver and just using it to verify some data on the DB2 side for a short project.
Thank you
Bernadette.

![DBeaverError](https://user-images.githubusercontent.com/60977386/74362035-d708ec80-4dbf-11ea-9676-c323d1e31b8a.png)

org.jkiss.dbeaver.model.exec.DBCException: SQL Error: [jcc][t4][10199][10462][4.0.100] Required character converter is not available. ERRORCODE=-4220, SQLSTATE=null
            at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
            at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
            at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:742)
            at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:475)
            at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:402)
            at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
            at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:400)
            at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:835)
            at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2690)
            at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
            at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1633)
            at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
            at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:101)
            at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.a.SqlException: [jcc][t4][10199][10462][4.0.100] Required character converter is not available. ERRORCODE=-4220, SQLSTATE=null
            at com.ibm.db2.jcc.a.yc.a(yc.java:55)
            at com.ibm.db2.jcc.a.yc.a(yc.java:119)
            at com.ibm.db2.jcc.a.dc.a(dc.java:1788)
            at com.ibm.db2.jcc.a.dc.a(dc.java:550)
            at com.ibm.db2.jcc.a.dc.o(dc.java:528)
            at com.ibm.db2.jcc.a.dc.R(dc.java:1714)
            at com.ibm.db2.jcc.a.mk.e(mk.java:1173)
            at com.ibm.db2.jcc.a.mk.getObject(mk.java:1155)
            at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
            at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCStringValueHandler.fetchColumnValue(JDBCStringValueHandler.java:51)
            at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
            ... 13 more

**Comment by Sargul** [comment]
this issue is not DBeaver related.

It seems that you are querying a unicode table on DB2 zOS that contains invalid characters for ccsid 1208 (utf8).

You can try to set -Ddb2.jcc.charsetDecoderEncoder=3 in the DBeaver.ini which will however cause that the invalid characters will be replace by the substitution character.

The better option is to let your database administrator know of this issue and fix the problem in the data

**Comment by Sargul** [comment]
you could also try to upgrade to the newest jdbc driver

https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads

**Comment by gitbernoire** [comment]
> you could also try to upgrade to the newest jdbc driver
> 
> https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads

That did it!
Thanks v much for the suggestion.  For some reason the default driver was quite old.

**Comment by gitbernoire** [comment]
Thanks for the speedy response & help!
