### ISSUE TITLE
DBeaver hangs on startup

### ISSUE THREAD

**Issue by gzsombor** [dbeaver/dbeaver#7898]
#### System information: 
- Operating system (distribution) and version: **Linux, Ubuntu 19.10**
- DBeaver version **6.3.4.202002011957**	
- Additional extensions

#### Connection specification:
- Database name and version: **NA**
- Driver name:  **NA**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? :  **NA**

#### Describe the problem you're observing:

Starting Eclipse with DBeaver installed in a particular workspace hangs the whole IDE. From the stack dump - it seems that DBeaver tries to execute a 'refresh resource' call from the main UI thread, which blocks the UI. However, this doesn't seem to be a dead-lock, as the main thread is inside a wait() method, waiting for a notification - which never come.

#### Include any warning/errors/backtraces from the logs
````
"main" #1 prio=6 os_prio=0 cpu=10589,47ms elapsed=295,05s tid=0x00007fadbc017000 nid=0x9af in Object.wait()  [0x00007fadc2c94000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.6/Native Method)
	- waiting on <no object reference available>
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:318)
	- waiting to re-lock in wait() <0x00000000c1e10810> (a java.lang.Object)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:205)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:298)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2242)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1549)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:585)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.<init>(DataSourceRegistry.java:81)
	at org.jkiss.dbeaver.registry.ProjectMetadata.getDataSourceRegistry(ProjectMetadata.java:191)
	- locked <0x00000000c5a9daa0> (a java.lang.Object)
	at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:149)
	at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:143)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getChildren(DBNProject.java:137)
	at org.jkiss.dbeaver.model.navigator.DBNProject.getDatabases(DBNProject.java:58)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorView.getRootNode(DatabaseNavigatorView.java:75)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.lambda$0(NavigatorViewBase.java:109)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase$$Lambda$474/0x00000001008b9c40.run(Unknown Source)
	at org.jkiss.dbeaver.ui.UIExecutionQueue.executeInUI(UIExecutionQueue.java:52)
	at org.jkiss.dbeaver.ui.UIExecutionQueue$$Lambda$475/0x00000001008b9040.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	- locked <0x00000000c78c6580> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4910)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4432)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.ui.internal.Workbench$$Lambda$189/0x00000001003ac440.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.6/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.6/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.6/Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by serge-rider** [comment]
Most likely it is the same bug as in #7965

**Comment by gzsombor** [comment]
In #7965 the stack trace is different, there the org.jkiss.dbeaver.registry.BaseWorkspaceImpl.handleResourceChange(BaseWorkspaceImpl.java:661) is waiting for a lock, which is acquired by a background task org.jkiss.dbeaver.registry.ProjectMetadata$ProjectSyncJob.run(ProjectMetadata.java:530), which is waiting for another thread to finish - and notify it. In this case, I suspect, there was an exception, which prevented the completion of that background task.

 Here, the 'main', UI thread is blocked inside org.jkiss.dbeaver.registry.DataSourceRegistry.loadDataSources(DataSourceRegistry.java:585).

**Comment by serge-rider** [comment]
@gzsombor could you post full thread dump? It is very hard to say what exactly happens without a dump.

**Comment by serge-rider** [comment]
And could you test the fix in Early Access version? (https://dbeaver.io/files/ea)

**Comment by gzsombor** [comment]
Yes, here is 3 dumps from 3 different starts - https://gist.github.com/gzsombor/8c027ce57bd4bf1b04739981f197fa0c - it was fairly reproducible. I had to uninstall dbeaver from a different workspace, I will try to reproduce it with the EA version
