### ISSUE TITLE
Oracle: Export from Query Gives "Not All Variables Bound" Error

### ISSUE THREAD

**Issue by j-coates** [dbeaver/dbeaver#7929]
#### System information: 
- Operating system (distribution) and version
Windows 7 Enterprise
- DBeaver version
6.3.5 (also occurred on 6.3.4)
- Additional extensions
DevStyle

#### Connection specification:
- Database name and version
Oracle 11G
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
Executing a query with a bind variable will work. Exporting from query with a bind variable will not work. It just gives an error: ORA-01008: not all variables bound. The screens all come up correctly and the preview of the query will the variables substituted is correct.

#### Include any warning/errors/backtraces from the logs

	2020-02-17 13:14:15.262 - Data transfer initiated
	2020-02-17 13:14:15.298 - Initialize data transfer sources
	2020-02-17 13:14:15.360 - Execution context opened (PROD; Data transfer producer; 8)
	2020-02-17 13:14:15.553 - Null current schema
	2020-02-17 13:14:15.648 - Execution context closed (PROD, 8)
	2020-02-17 13:14:15.649 - Error transfering data from "SELECT *
	FROM S3PROD.ITEMMAST ITE
	WHERE ITEM = :ITEM
	" to ITEMMAST_202002171314.txt
	org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1008] [72000]: ORA-01008: not all variables bound
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:122)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:214)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at 	org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
	Caused by: java.sql.SQLException: ORA-01008: not all variables bound

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:849)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1267)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 9 more
	2020-02-17 13:14:15.659 - Data transfer completed
	2020-02-17 13:14:15.802 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1008] [72000]: ORA-01008: not all variables bound

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.model.sql.data.SQLQueryDataContainer.readData(SQLQueryDataContainer.java:122)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:214)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
	Caused by: java.sql.SQLException: ORA-01008: not all variables bound

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:849)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1267)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 9 more

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
