### ISSUE TITLE
PosgreSQL dump missing parameter

### ISSUE THREAD

**Issue by lrweck** [dbeaver/dbeaver#7942]
#### System information: 
- Windows 10
- 6.3.5

#### Connection specification:
- PostgreSQL 12
- DBeaver JDBC
- Connection via SSH

#### Describe the problem you're observing:

I've created a task to dump a remote PG database on my computer, which I connect via SSH. However, DBeaver doesn't use the output parameter for the dump, resulting in a error.

#### Steps to reproduce, if exist:
Create a task to dump a remote database in the Directory format. 

#### Include any warning/errors/backtraces from the logs
```
2020-02-18 10:49:06.125 - Load database object list
2020-02-18 10:49:06.126 - 	Load postgres-jdbc-1702056f266-25404489fbf7255e/crm
2020-02-18 10:49:06.127 - PostgreSQL dump
2020-02-18 10:49:06.127 - 	PostgreSQL dump
2020-02-18 10:49:06.128 - PostgreSQL dump
2020-02-18 10:49:06.128 - 	Start native tool
C:\Users\luisroberto\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\pg_dump.exe --verbose --host=127.0.0.1 --port=20036 ****** --format=d --compress=9 -n "public" crm
Task 'dump_crm' started at Tue Feb 18 10:49:06 BRT 2020
2020-02-18 10:49:06.393 - 	Executing
pg_dump: [directory archiver] no output directory specified
Task 'dump_crm' finished at Tue Feb 18 10:49:06 BRT 2020
2020-02-18 10:49:06.595 - IO error: Process failed (exit code = 1). See error log.
2020-02-18 10:49:06.595 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:124)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeTask(AbstractNativeToolHandler.java:44)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:119)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (parameter --file added)

**Comment by kseniiaguzeeva** [comment]
verified
