### ISSUE TITLE
disconnect database during the work

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#7953]
#### System information: 
- Operating system (distribution) and version WINDOWS 10 64bit
- DBeaver version 6.3.0 EE

#### Describe the problem you're observing:
2 database on my server. I am working with database1.
Then i click on database2 on the left objects tree 15 minutes ago, then go to the db scheme, then click on table name tabledb2.

DBeaver show me modal window 
--------
Connection with  database2 lost
Reason:
the connection has already been closed

with button
RECONNECT OK DESCRIPTION
--------

Nevertheless under this window i can see that DBeaver reconnecting herself and show correct data from this table tabledb2.

I do not need this modal window and 
i do not need a RECONNECT button!! This should be done automatically.

This modal window show for me every 2-3 hours

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2020-02-19 14:59:34.863
!MESSAGE Operation failed. Retry count remains = 5
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-02-19 14:59:34.863
!MESSAGE SQL Error [08003]: Соединение уже было закрыто
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2020-02-19 14:59:34.863
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.prepareChildrenStatement(PostgreSchema.java:571)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.prepareChildrenStatement(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:188)
	at jdk.internal.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:815)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:796)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:846)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:200)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:69)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:246)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by detkliff** [comment]
is actual for 7.0.1 version

**Comment by uslss** [comment]
Issue can be resolved by changing Keep-Alive value to non-zero in connection properties
![image](https://user-images.githubusercontent.com/31996417/101414246-ce594800-38f6-11eb-9853-df5f2a5c7c90.png)
