### ISSUE TITLE
Error refreshing node

### ISSUE THREAD

**Issue by detkliff** [dbeaver/dbeaver#7955]
#### System information: 
- Operating system (distribution) and version WINDOWS 10 64 bit
- DBeaver version 6.3.0 EE

#### Describe the problem you're observing:
Periodicaly show up modal window with error message "Error refreshing node. Error object loading metadata from database" . 

#### Steps to reproduce, if exist:
Open DBeaver
Open table1, table2, table3 from database on three tabs.
Open SQL editor for any select in fourth tab.
After 10-15 minutes i click on tab with table1->properties->indexes
Create index and click on save button. 
Show up this error window!

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2020-02-19 16:43:08.870
!MESSAGE Error loading object metadata from database
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-02-19 16:43:08.870
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.prepareLookupStatement(PostgreSchema.java:529)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.prepareLookupStatement(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.refreshObject(JDBCStructLookupCache.java:78)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.refreshObject(PostgreTableBase.java:249)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:324)
	at org.jkiss.dbeaver.ui.navigator.actions.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:154)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
hi @detkliff ,
sorry for the late response. is it still actual for you against recent version (7.0)?

**Comment by detkliff** [comment]
yes it is

**Comment by serge-rider** [comment]
Generally this issue happens because server closes idle connection. Workaround: set keep-alive settings for connection.

I'll add connection recovery to metadata refresh function so this particular error won't happen.

**Comment by uslss** [comment]
verified
