### ISSUE TITLE
MSSQL - DB connection is closed when canceling a query, and no results are displayed

### ISSUE THREAD

**Issue by eksla** [dbeaver/dbeaver#7993]
#### System information: 
- Operating system (distribution) and version : Windows10 Pro 1903
- DBeaver version : 6.3.5
- Additional extensions

#### Connection specification:
- Database name and version : Microsoft SQL Server 2016 (SP2-GDR) (KB4505220) - 13.0.5101.9 (X64)
- Driver name : mssql-jdbc:RELEASE 7.4.1.jre8
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  NO

#### Describe the problem you're observing:
Connect to MSSQL and cancel while executing the query, the connection with database will be disconnected.
In version 6.1.5, the results obtained just before the cancellation were displayed and the connection to the DB was maintained.
Also, when connecting to DB2, this problem did not occur even with version 6.3.5.

#### Steps to reproduce, if exist:
See description above?

#### Include any warning/errors/backtraces from the logs

There is no error log in MSSQL. Exists for DB2.
The following is a runtime error.

org.jkiss.dbeaver.model.exec.DBCException: SQL Error: The connection is closed.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.nextResults(JDBCStatementImpl.java:208)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:536)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:424)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:416)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:774)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2914)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:110)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:108)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3421)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1090)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.checkClosed(SQLServerStatement.java:1058)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getMoreResults(SQLServerStatement.java:1339)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.nextResults(JDBCStatementImpl.java:206)
	... 12 more

**Comment by uslss** [comment]
hi @eksla ,
unfortunately, cannot reproduce. could you post e.g. a video that could help to investigate an issue?

**Comment by serge-rider** [comment]
@eksla Also please post example of  query which cannot be canceled.

**Comment by uslss** [comment]
there is no update on issue almost a month.
if issue is still reproducible for you - feel free to reopen the ticket

**Comment by mateusviccari** [comment]
https://user-images.githubusercontent.com/8275175/120313893-0099a000-c2b1-11eb-9c65-c4e3b6fabd8f.mp4

I'm facing the same problem when running certain queries  with MSSQL connection, not sure why. Here's a video showing the problem.

I have almost exactly the same settings from the OP but I'm running SQL Server 2008.
