### ISSUE TITLE
Use of implicit cursors results in ORA-17283: No resultset available

### ISSUE THREAD

**Issue by JMPSequeira** [dbeaver/dbeaver#8026]
#### System information: 
- Windows 10
- DBeaver 6.3.5

#### Connection specification:
- Oracle 19c
- 19.3 Oracle JDBC Thin driver(ojdbc10.jar) 

#### The problem:
As stated in title: Use of implicit cursors results in ORA-17283: No resultset available

As far as I can tell this is a documented issue with the JDBC drivers and has some proposed workarounds as stated in the following links:

[dzone](https://dzone.com/articles/fetching-oracle-12c-implicit-cursors-with-jdbc-and)
[stackoverflow](https://stackoverflow.com/a/47890092)
[some random guy blog](https://blog.jooq.org/2017/02/08/how-to-fetch-oracle-12c-implicit-cursors-with-jdbc-and-jooq/)

Now I'm not a java guy, nor an oracle guy, nor a db guy  for that matter. I've just stumbled on a project revolving an oracle db and roamed the web for a good ide and stumbled on yours which I find quite useful. Hope the info provided helps.

Great tool!

Error log:
```
2020-02-27 22:48:07.672 - SQL Error [17283] [99999]: No resultset available
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [17283] [99999]: No resultset available
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:171)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:1)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:499)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:424)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:416)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:774)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2914)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:110)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:164)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:108)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3421)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: No resultset available
	at oracle.jdbc.driver.OracleStatement.getResultSet(OracleStatement.java:3239)
	at oracle.jdbc.driver.OracleStatementWrapper.getResultSet(OracleStatementWrapper.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.getResultSet(JDBCStatementImpl.java:598)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.openResultSet(JDBCStatementImpl.java:168)
	... 13 more
```

**Comment by uslss** [comment]
thanks for suggestion

**Comment by serge-rider** [comment]
Fixed. Now we handle 17283 with DS-specific error code.
