### ISSUE TITLE
[ER Diagram] Unable to add table from more than 9 different databases

### ISSUE THREAD

**Issue by AlaNDGT** [dbeaver/dbeaver#8039]
#### System information: 
- MacOS Mojave 10.14.6
- DBeaver 6.3.5.202002151353
- Additional extensions

#### Connection specification:
- PostgreSQL 9.6.17 
- PostgreSQL JDBC Driver
- no tunnels/proxies 

#### Describe the problem you're observing:
Can't add tables from more than 9 databases. Getting below error:
![image](https://user-images.githubusercontent.com/3120817/75558763-bdbc9d00-5a5b-11ea-99dd-098dad252218.png)

#### Steps to reproduce, if exist:

1. Create a new ER Diagram

1. Add tables from 9 different database

1. Add one more from a different database and you should get the error

#### Include any warning/errors/backtraces from the logs

- .log
```
!ENTRY org.eclipse.jface 4 2 2020-02-28 18:55:22.431
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at org.jkiss.dbeaver.ui.UIColors.getColor(UIColors.java:44)
	at org.jkiss.dbeaver.ext.erd.figures.EntityFigure.getBorderColor(EntityFigure.java:148)
	at org.jkiss.dbeaver.ext.erd.figures.EntityFigure.<init>(EntityFigure.java:101)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigureImpl(EntityPart.java:197)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigure(EntityPart.java:178)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigure(EntityPart.java:1)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:494)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.getFigure(EntityPart.java:202)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.getFigure(EntityPart.java:1)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addChildVisual(AbstractGraphicalEditPart.java:208)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:211)
	at org.jkiss.dbeaver.ext.erd.part.PropertyAwarePart.handleChildChange(PropertyAwarePart.java:237)
	at org.jkiss.dbeaver.ext.erd.part.DiagramPart.handleChildChange(DiagramPart.java:313)
	at org.jkiss.dbeaver.ext.erd.part.PropertyAwarePart.propertyChange(PropertyAwarePart.java:96)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at org.jkiss.dbeaver.ext.erd.model.ERDObject.firePropertyChange(ERDObject.java:87)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.addEntity(EntityDiagram.java:170)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.addEntity(EntityDiagram.java:152)
	at org.jkiss.dbeaver.ext.erd.command.EntityAddCommand.execute(EntityAddCommand.java:101)
	at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:228)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.handleDrop(AbstractTransferDropTargetListener.java:339)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.drop(AbstractTransferDropTargetListener.java:183)
	at org.eclipse.jface.util.DelegatingDropAdapter$3.run(DelegatingDropAdapter.java:227)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.util.DelegatingDropAdapter.drop(DelegatingDropAdapter.java:224)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:94)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.dnd.DropTarget.drop(DropTarget.java:726)
	at org.eclipse.swt.dnd.DropTarget.performDragOperation(DropTarget.java:740)
	at org.eclipse.swt.dnd.DropTarget.dropTargetProc(DropTarget.java:454)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1146)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2150)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1138)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2633)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2117)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6076)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2401)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6200)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5426)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5586)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3807)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

- dbeaver-debug.log

```
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at org.jkiss.dbeaver.ui.UIColors.getColor(UIColors.java:44)
	at org.jkiss.dbeaver.ext.erd.figures.EntityFigure.getBorderColor(EntityFigure.java:148)
	at org.jkiss.dbeaver.ext.erd.figures.EntityFigure.<init>(EntityFigure.java:101)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigureImpl(EntityPart.java:197)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigure(EntityPart.java:178)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.createFigure(EntityPart.java:1)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:494)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.getFigure(EntityPart.java:202)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.getFigure(EntityPart.java:1)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.isSelectable(AbstractGraphicalEditPart.java:567)
	at org.eclipse.gef.editparts.AbstractEditPart.getTargetEditPart(AbstractEditPart.java:632)
	at org.jkiss.dbeaver.ext.erd.part.EntityPart.getTargetEditPart(EntityPart.java:304)
	at org.eclipse.gef.tools.MarqueeSelectionTool.isMarqueeSelectable(MarqueeSelectionTool.java:559)
	at org.eclipse.gef.tools.MarqueeSelectionTool.calculatePrimaryMarqueeSelectedEditParts(MarqueeSelectionTool.java:323)
	at org.eclipse.gef.tools.MarqueeSelectionTool.calculateMarqueeSelectedEditParts(MarqueeSelectionTool.java:278)
	at org.eclipse.gef.tools.MarqueeSelectionTool.performMarqueeSelect(MarqueeSelectionTool.java:722)
	at org.eclipse.gef.tools.MarqueeSelectionTool.handleButtonUp(MarqueeSelectionTool.java:487)
	at org.eclipse.gef.tools.AbstractTool.mouseUp(AbstractTool.java:1200)
	at org.eclipse.gef.tools.SelectionTool.mouseUp(SelectionTool.java:574)
	at org.eclipse.gef.EditDomain.mouseUp(EditDomain.java:301)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseReleased(DomainEventDispatcher.java:380)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseUp(LightweightSystem.java:548)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
2020-02-28 18:55:11.493 - Datasource 'PostgreSQL - rss [PostgreSQL]' not registered in ERD viewer
```

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by AlaNDGT** [comment]
Heyy, i can't build the source on my machine somehow, any chance you can provide me a release with the fix for that issue for Mac asap? (Don't worry if you are unable)

Oh and i'm getting the below error:
![image](https://user-images.githubusercontent.com/3120817/75566601-645b6a80-5a69-11ea-9c15-8a75cfe017ac.png)

Any idea how i can fix it?

PS: sorry for irrelevant comment here

**Comment by serge-rider** [comment]
@AlaNDGT You can check fresh Early Access version.

Can't say what exactly is wrong with your build env. Perhaps wrong Eclipse IDE package (you need RCP/RAP developers).
You can try yo build it with pure Maven.

**Comment by uslss** [comment]
verified
