### ISSUE TITLE
Support different native client versions (was: Cannot backup PostgreSQL 12.x server)

### ISSUE THREAD

**Issue by pashagolub** [dbeaver/dbeaver#8069]
```
C:\Users\pasha\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\pg_dump.exe --verbose --host=localhost --port=5432 --username=postgres --format=p -n "timetable" timetable
Task 'PostgreSQL dump' started at Tue Mar 03 17:27:47 CET 2020
pg_dump: server version: 12.1; pg_dump version: 11.2
pg_dump: aborting because of server version mismatch
Task 'PostgreSQL dump' finished at Tue Mar 03 17:27:47 CET 2020
2020-03-03 17:27:48.060 - IO error: Process failed (exit code = 1). See error log.
2020-03-03 17:27:48.060 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Workaround: specify local native PG client compatible with your server version. You can do this in connection settings.

Generally we need to support different versions of native clients. So this is a feature request.

**Comment by daevidvincent** [comment]
I was able to get around this extremely annoying issue by downloading https://www.pgadmin.org/ and pointing my `pg_dump` binary to that directory. This is a bit lighter weight than installing postgres on my windows notebook just to get a version 11. Why this "feature" doesn't have an "ignore version" checkbox or prompt me if there is a version mismatch to "spoof" the right one seems curious. I'm using DBeaver 7.1.4 if that matters...

> pg_dump: server version: 11.6; pg_dump version: 10.5

**Comment by serge-rider** [comment]
Updated PG native client to version 12.
It is backward compatible with 11 and 10 at least.

**Comment by pashagolub** [comment]
Do not forget to ship v13 soon (September) 
:)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by stefan-dan** [comment]
With the latest update version 21. This bug reappeared, when trying to back up a database on MariaDB version 10.1.
The error message:
`Task 'MySQL dump' finished at Mon Mar 01 13:06:53 EET 2021
2021-03-01 13:06:54.042 - IO error: Process failed (exit code = 7). See error log.
2021-03-01 13:06:54.043 - java.io.IOException: Process failed (exit code = 7). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)`

On DBeaver 7.3.5 everything works fine.

**Comment by rockatoo** [comment]
I have problem like above.
We have used backup function in postgreSQL13 but, error occured From April.

Error log is like this.
```
Task 'PostgreSQL dump' started at Tue May 25 15:12:44 KST 2021
pg_dump: error: server version: 13.2 (Ubuntu 13.2-1.pgdg18.04+1); pg_dump version: 12.2

pg_dump: error: aborting because of server version mismatch

Task 'PostgreSQL dump' finished at Tue May 25 15:12:44 KST 2021
2021-05-25 15:12:44.305 - IO error: Process failed (exit code = 1). See error log.
2021-05-25 15:12:44.305 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

My DBeaver version is 21.0.5 now.

**Comment by pavlexander** [comment]
For **windows**. Go to: https://www.postgresql.org/download/windows/ Find and click on :

> "Advanced users can also download a **zip archive** of the binaries, without the installer."

Unzip and go to location similar to: `C:\Users\XXX\Downloads\postgresql-14.2-2-windows-x64-binaries\pgsql\bin`. This will get you the latest version of postgres client and relevant utils (including `pg_dump`).

In separate window open: `C:\Users\XXX\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win`
In my case I had folder "13". Create folder "14". Copy contents from `bin` folder into this `14` folder.

`in Dbeaver > Database > Driver manager > Postgres -> "Edit ..." -> Native client -> "Add Home" button ->` Add newly created directory `C:\Users\XXX\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14`
![image](https://user-images.githubusercontent.com/20644772/161391215-ebdbe44c-cc05-43a5-a570-a9d757375b1b.png)
![image](https://user-images.githubusercontent.com/20644772/161391224-327d41ad-73aa-4486-92a2-2124f2094981.png)
![image](https://user-images.githubusercontent.com/20644772/161391274-ac5daa0c-e4ae-43a7-9bdb-06a66d0fffae.png)

`in Dbeaver > Find postgres connection -> Edit -> Local client ->` change value to new directory

![image](https://user-images.githubusercontent.com/20644772/161391350-c2e8236a-e0a5-468d-b261-a0aa7100c466.png)
![image](https://user-images.githubusercontent.com/20644772/161391353-3d3a6cfa-5c66-4583-b889-c7a0b65b6747.png)

Enjoy. No more errors when backing up data.. Similarly you could have multiple postgres clients installed and you could use each for different connections.. But someone said they are backwards compatible so there is that.

p.s. I also updated driver version to latest maybe it's also required..
`in Dbeaver > Database > Driver manager > Postgres -> "Edit ..." -> Libraries -> "Download/Update" button`
![image](https://user-images.githubusercontent.com/20644772/161391435-d7dc16c1-ece6-47f7-adc5-f03846a6e2b4.png)

**Comment by kitos9112** [comment]
You've saved me a few Google searches! Kudos to @pavlexander!
