### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by Vlczech** [dbeaver/dbeaver#8085]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: DBeaver 7.0
- Additional extensions: -

#### Connection specification:
- Database name and version: PostgreSQL 11
- Driver name: PostgreSQL JDBC driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Plugin: `org.eclipse.ui.workbench`
Stack Trace:
```
java.lang.IllegalStateException: No databases found on the server
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:388)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.addSetDefaultObjectAction(NavigatorUtils.java:237)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.lambda$0(NavigatorUtils.java:194)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:463)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5156)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4788)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1501)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2138)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4819)
	at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:253)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

Session Data:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```

#### Steps to reproduce, if exist:

I think, that it is related to a VPN disconnecting outage

#### Include any warning/errors/backtraces from the logs

![obrazek](https://user-images.githubusercontent.com/10884140/75879693-199c7280-5e1c-11ea-97b6-4f52720e515b.png)

**Comment by Vlczech** [comment]
This exception is in log mixed with #8086

**Comment by Vlczech** [comment]
This appeared again for this scenario after disconnected and again connected VPN: The tree of database navigator is opened to tables. I force reconnect by right click, context menu and selecting item "Invalidate/Reconnect". Then the exception occurred only when I right click for example on database...

**Comment by Vlczech** [comment]
It could be due to docker assign IP range, which has the VPN itself (becuse i couldn't connect to pgsql then). But in any case it seems, that this and the other two are unhandled exceptions.

**Comment by kevinv519** [comment]
I'm having the same issue, with the same log explanation.

The difference about the system information:
Operating system (distribution) and version: Manjaro 20.0 Lysia
Kernel: x86_64 Linux 4.19.117-1-MANJARO
DBeaver version: DBeaver 7.0.2
Additional extensions: -

However, I do think it is a docker related issue.

I'm running a SQL Server container on my host machine and every time I refresh the server it throws this exception. This does not happen with other DBMS containers  like Postgres.

It should be mention that after closing the error message I'm able to execute statements without problem. It's just really annoying the exception is thrown every time I need to refresh the server.

**Comment by serge-rider** [comment]
There were several bugfixes in connection invalidation since this bug was reported.
Please check it in the most recent version.

**Comment by uslss** [comment]
issue closed.
If it is still actual for you - feel free to reopen it

**Comment by Guiraud** [comment]
On 22.1.3, I had to close and reopen Dbeaver while the VPN was connected.
