### ISSUE TITLE
postgres driver download from maven repo gives 404

### ISSUE THREAD

**Issue by patrickmdnet** [dbeaver/dbeaver#8092]
#### System information: 
- Windows 10 x64
- DBeaver version 7..0.0-devel

#### Connection specification:
- Postgres

#### Describe the problem you're observing:
- PG Driver download fails with 404 at url https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.bundle

#### Steps to reproduce, if exist:
- Database -> Driver Manager
- open PostgresSQL
- click Download/Update

#### Include any warning/errors/backtraces from the logs

````
Initiate connection to PostgreSQL database [] for Main <>
2020-03-04 19:00:40.720 - Open [https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.pom]
2020-03-04 19:00:40.931 - Open [https://repo1.maven.org/maven2/org/postgresql/pgjdbc-core-parent/1.1.5/pgjdbc-core-parent-1.1.5.pom]
2020-03-04 19:00:41.018 - Open [https://repo1.maven.org/maven2/org/postgresql/pgjdbc-versions/1.1.5/pgjdbc-versions-1.1.5.pom]
2020-03-04 19:00:42.664 - Open [https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.bundle]
2020-03-04 19:02:33.728 - Connection failed (postgres-jdbc-170a7fe865b-9ed698e09207da)
2020-03-04 19:02:33.728 - org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
org.jkiss.dbeaver.model.exec.DBCConnectException: Can't create driver instance
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:121)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:318)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:91)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:193)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:126)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:104)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:105)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:811)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:247)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Error creating driver 'PostgreSQL' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
````
![image](https://user-images.githubusercontent.com/858798/75940829-132deb00-5e5c-11ea-821c-d87666d5d396.png)

**Comment by serge-rider** [comment]
Thanks for the bug report

**Comment by kseniiaguzeeva** [comment]
verified
