### ISSUE TITLE
"FATAL: password authentication failed for user" error in trying to connect to PostgreSQL

### ISSUE THREAD

**Issue by loop-evgeny** [dbeaver/dbeaver#8105]
#### System information: 
- Operating system (distribution) and version: Windows 7 SP1 x64
- DBeaver version: 7.0.0.202003021717
- Additional extensions: none

#### Connection specification:
- Database name and version: PostgreSQL 12.2
- Driver name: postgresql-x64-12
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

Trying to connecting using password (either SCRAM-SHA-256 or MD5) authentication with DBeaver fails with

`FATAL: password authentication failed for user "root"`

Other clients, such as psql.exe, pgAdmin 4 and Valentina Studio are able to connect with the same username and password.

#### Steps to reproduce, if exist:

Set up a PostgreSQL 12 server using SCRAM-SHA-256 authentication. Create a user with a password. Try to connect using this user with DBeaver.

#### Include any warning/errors/backtraces from the logs

DBeaver log:

```
2020-03-06 10:28:17.390 - Connect with 'ansible-test' (postgres-jdbc-170af25828d-622f71d65a5ca3c2)
2020-03-06 10:28:17.391 - Execution context opened (ansible-test; Main <postgres>; 13)
2020-03-06 10:28:17.392 - Initiate connection to PostgreSQL database [postgres@192.168.20.101] for Main <postgres>
2020-03-06 10:28:17.415 - Connection failed (postgres-jdbc-170af25828d-622f71d65a5ca3c2)
2020-03-06 10:28:17.415 - org.jkiss.dbeaver.model.exec.DBCConnectException: FATAL: password authentication failed for user "root"
org.jkiss.dbeaver.model.exec.DBCConnectException: FATAL: password authentication failed for user "root"
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:196)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:318)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:91)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:193)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:126)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:104)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:105)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:801)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:63)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:151)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:198)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "root"
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:174)
	... 25 more
```

PostgreSQL log:

```
2020-03-06 10:28:17.364 CET [28748] root@postgres FATAL:  password authentication failed for user "root"
2020-03-06 10:28:17.364 CET [28748] root@postgres DETAIL:  Connection matched pg_hba.conf line 86: "hostssl	all	all	all	scram-sha-256"
```

I've tried changing the server config to use MD5 instead of SCRAM-SHA-256 and it still fails.

**Comment by serge-rider** [comment]
I can't reproduce this.
May the problem be in pg_hba remote access config?

You could try to upgrade to the most recent driver version (Connectio nsettings->Edit Driver Settings->Download/Update->Click on the version number) but honestly I doubt that it will help.

Anyhow, dbeaver uses JDBC driver to connect. So far I don't see how it can be a dbeaver-side bug..

**Comment by loop-evgeny** [comment]
Updated to JDBC driver 42.2.10, but that didn't help. The same happens in JetBrains DataGrid, which also uses JDBC, so it likely is a JDBC bug, but from my point of view as a user that's an implementation detail. :)

**Comment by dpsspatial** [comment]
We had the same problem, but here is how we caused it and how we fixed it: 

- rename a database user account (role) to **user_** in order to turn off all access to the database
- when finished, we renamed the role back to **user** 
- QGIS - our spatial data client - has no problem getting back into the database
- DBeaver throws the 'password authentication failed for user' error, even when a new connection is created from scratch

The fix: 

simply update the password to the existing password

```
ALTER ROLE user   
WITH PASSWORD 'sameoldpassword';
```

And that was it! DBeaver can now log in (QGIS still is able to log in)

Not sure what the difference is between the two applications of the same database, or why the password needed a 'bump'...
