### ISSUE TITLE
[Hive] Error appears when trying to open Reference panel

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8114]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.0 EA

#### Connection specification:
- Database name and version Apache Hive

#### Describe the problem you're observing:
Error appears when trying to open Reference panel
![image](https://user-images.githubusercontent.com/31996417/76108026-dcd2a600-5fea-11ea-985a-72e8ee6b8283.png)
```

> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Fri Mar 06 20:40:02 MSK 2020
> Method not supported
> 
> java.sql.SQLException: Method not supported
> 	at org.apache.hive.jdbc.HiveDatabaseMetaData.getExportedKeys(HiveDatabaseMetaData.java:305)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getExportedKeys(JDBCDatabaseMetaDataImpl.java:1215)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.loadReferences(GenericTableBase.java:328)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getReferences(GenericTableBase.java:192)
> 	at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllReferences(DBVUtils.java:325)
> 	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$2.run(ReferencesResultsContainer.java:245)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 

```

**Comment by serge-rider** [comment]
Hive doesn't support references. But we shouldn't show error dialogs for it (as it is a regular behavior).

**Comment by uslss** [comment]
closed without testing
