### ISSUE TITLE
NPE appears in Reference table if there are no referenced tables

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8127]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.0.0

#### Steps to reproduce, if exist:
1. Open table without references
2. Open references panel
3. Click on dropdown - NPE appears
![2020-03-08_20h18_14](https://user-images.githubusercontent.com/31996417/76167736-07069e00-617a-11ea-9077-fbc120a5eff5.gif)

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui.workbench
> Error
> Sun Mar 08 20:18:10 MSK 2020
> Unhandled event loop exception
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$1.widgetSelected(ReferencesResultsContainer.java:96)
> 	at org.jkiss.dbeaver.ui.controls.CSmartCombo.lambda$3(CSmartCombo.java:256)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
> 	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:780)
> 	at org.jkiss.dbeaver.ui.controls.CSmartCombo.listEvent(CSmartCombo.java:719)
> 	at org.jkiss.dbeaver.ui.controls.CSmartCombo.lambda$0(CSmartCombo.java:132)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
> 
> 
```

**Comment by uslss** [comment]
verified
