### ISSUE TITLE
Comment on table/Schema couldn't be deleted using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8183]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.1 EA

#### Connection specification:
- Database name and version PostgreSQL

#### Steps to reproduce, if exist:
1. Open table in Property Viewer
2. Add comment to the table if it doesn't exist and save it
3. Delete comment and save it - Comment field is empty
4. Refresh table - comment appears again.
NOTE: Comment editing works as expected

**Comment by uslss** [comment]
NPE is thrown in the same case for schemas in exasol.
2020-03-22 15:26:32.518 - java.lang.NullPointerException
```

> 	at org.jkiss.dbeaver.ext.exasol.tools.ExasolUtils.quoteString(ExasolUtils.java:59)
> 	at org.jkiss.dbeaver.ext.exasol.manager.ExasolSchemaManager.addObjectModifyActions(ExasolSchemaManager.java:175)
> 	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectChangeCommand.getPersistActions(SQLObjectEditor.java:294)
> 	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.lambda$5(EntityEditor.java:486)
> 	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> 

```

**Comment by uslss** [comment]
issue with table description in Postgres is still reproduced.
Exasol - fixed

**Comment by uslss** [comment]
verified
