### ISSUE TITLE
Import from CSV failing with Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by nrbracke** [dbeaver/dbeaver#8194]
#### System information: 
- Operating system (distribution) and version - MAC
- DBeaver version - 7.0.0.202003021717
- Additional extensions

#### Connection specification:
- Database name and version - DB2wh
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Trying an import task from CSV
#### Steps to reproduce, if exist:
Import fails with index issue

#### Include any warning/errors/backtraces from the logs
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferResultSet.getAttributeValue(StreamTransferResultSet.java:97)
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.fetchValueObject(DefaultValueHandler.java:49)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:214)
	at org.jkiss.dbeaver.tools.transfer.stream.importer.DataImporterCSV.runImport(DataImporterCSV.java:198)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:141)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer.transferData(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:124)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeWithSettings(DTTaskHandlerTransfer.java:93)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:51)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:119)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2020-03-16 08:31:22.392 - Data transfer completed

**Comment by uslss** [comment]
Hi @nrbracke ,
unfortunately, cannot reproduce an issue? does it happen always or just in special case? maybe you could provide table ddl and csv sample? 
thanks in advance

**Comment by serge-rider** [comment]
Not reproducible anymore.
