### ISSUE TITLE
Functions and Procedures node not expanding

### ISSUE THREAD

**Issue by happytrails** [dbeaver/dbeaver#8200]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.0.202003021717

#### Connection specification:
- Database version: 11.5
- Driver name: PostgreSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Functions and Procedures node not expanding

#### Steps to reproduce, if exist:
Under Schemas, I click > button to expand one of my schemas called "customer", then click >Functions node, it doesn't expand.  Instead it displays "(...)". 
No issues with other nodes like Tables, Indexes etc.
I tried the same thing in PgAdmin and OmniDB, both display all 8 functions correctly.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.apache.felix.scr 4 0 2020-03-11 09:08:12.509
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: org/apache/felix/scr/impl/AbstractExtender$1
	at org.apache.felix.scr.impl.AbstractExtender.destroyExtension(AbstractExtender.java:211)
	at org.apache.felix.scr.impl.AbstractExtender.bundleChanged(AbstractExtender.java:132)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.doStop(Module.java:656)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1885)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1760)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:202)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by happytrails** [comment]
Never mind -- turned out there was a filter I didn't know before.
