### ISSUE TITLE
JNA loader constraint violation with PostgreSQL & waffle-jna

### ISSUE THREAD

**Issue by nazar554** [dbeaver/dbeaver#8247]
#### System information: 
- Operating system (distribution) and version: Windows 10 x64 Pro 1909
- DBeaver version: 7.0.1
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 12.1
- Driver name: org.postgresql:postgresql 42.2.11, waffle-jna 1.9.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Can't use `waffle-jna` anymore for SSPI authentication with PostgreSQL
#### Steps to reproduce, if exist:
Add postgresql:42.2.11 and waffle-jna:1.9.1 artifacts and try to connect
#### Include any warning/errors/backtraces from the logs

```
2020-03-23 12:21:50.348 - Connect with 'PostgreSQL - postgres@localhost - postgres' (postgres-jdbc-16fe248083d-7d0207adbd629573)
2020-03-23 12:21:50.606 - Connection failed (postgres-jdbc-16fe248083d-7d0207adbd629573)
2020-03-23 12:21:50.606 - org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:210)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:318)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:121)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:812)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:268)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:160)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:184)
	... 10 more
Caused by: java.lang.LinkageError: loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @2c2eb58 wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @578d2667. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @578d2667, parent loader 'platform')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.postgresql.sspi.NTDSAPIWrapper.DsMakeSpn(NTDSAPIWrapper.java:32)
	at org.postgresql.sspi.SSPIClient.makeSPN(SSPIClient.java:111)
	at org.postgresql.sspi.SSPIClient.startSSPI(SSPIClient.java:154)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:649)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:146)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:206)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.access$100(Driver.java:58)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:369)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by nazar554** [comment]
my guess that something changed in `DriverClassLoader` and it loads wrong version of JNA (the bundled one in `plugins/` folder). It worked fine before in 7.0.0

**Comment by uslss** [comment]
could you check it against 7.0.2?

**Comment by nazar554** [comment]
It seems to work fine with 7.0.2

**Comment by nazar554** [comment]
Sorry my mistake, still getting an error:

`loader constraint violation: loader org.jkiss.dbeaver.registry.driver.DriverClassLoader @479c2630 wants to load class com.sun.jna.Pointer. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @78ece301. (com.sun.jna.Pointer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @78ece301, parent loader 'platform')
`

**Comment by serge-rider** [comment]
The problem is in waffle-JNA dependencies. DBeaver already includes JNA libraries. Basically it is a part of Eclipse platform, we can't remove this very base dependency.

Workaround is to remove waffle dependencies to avoid conflicts. We already support this but not in UI.
I've added extra Maven artifact option: Ignore dependencies -
![image](https://user-images.githubusercontent.com/6398845/81081404-899da680-8efa-11ea-9968-d2fcdd4e3e2c.png)

You will need to add both waffle and caffeine artifacts separately. 
Another workaround: download them and add as jar files.

**Comment by uslss** [comment]
verified
