### ISSUE TITLE
Oracle: Can't download drivers after update to 7.0.1

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#8248]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.0.1.202003211804
- Additional extensions: None

#### Connection specification:
- Database name and version: Oracle 18c
- Driver name: jdbc driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

After update to version 7.0.1 DBeaver decided to redownload Oracle drivers, but for some reason cannot do that and throws an error:
```
Error resolving dependencies
  Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
```

![obraz](https://user-images.githubusercontent.com/20753183/77312629-a2634b80-6d02-11ea-8b1b-6854a900905b.png)

Is this somehow related to #8182?

#### Steps to reproduce, if exist:

Update to version 7.0.1 and try to download drivers for Oracle.

#### Include any warning/errors/backtraces from the logs

dbeaver-debug.log:
```
> Start Equinox Provisioning Platform Update Support [org.eclipse.equinox.p2.ui.sdk 1.1.500.v20191016-0512]
> Start Core Compare Support [org.eclipse.compare.core 3.6.700.v20191122-2107]
> Start Compare Support [org.eclipse.compare 3.7.800.v20191122-2107]
> Start Equinox Security Default UI [org.eclipse.equinox.security.ui 1.2.500.v20191003-0536]
2020-03-23 12:39:05.679 - Error resolving library 'com.oracle.database.jdbc:ojdbc8::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.jdbc:ojdbc8::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:39:05.681 - Error resolving library 'com.oracle.database.nls:orai18n::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.nls:orai18n::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:39:05.682 - Error resolving library 'com.oracle.database.xml:xdb6::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xdb6::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:39:05.684 - Error resolving library 'com.oracle.database.xml:xmlparserv2::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:39:05.717 - org.jkiss.dbeaver.DBException: Error resolving dependencies
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:91)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	... 3 more
2020-03-23 12:40:09.782 - Error resolving library 'com.oracle.database.jdbc:ojdbc8::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.jdbc:ojdbc8::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:09.783 - Error resolving library 'com.oracle.database.nls:orai18n::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.nls:orai18n::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:09.785 - Error resolving library 'com.oracle.database.xml:xdb6::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xdb6::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:09.787 - Error resolving library 'com.oracle.database.xml:xmlparserv2::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:09.817 - org.jkiss.dbeaver.DBException: Error resolving dependencies
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:91)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	... 3 more
2020-03-23 12:40:18.323 - Error resolving library 'com.oracle.database.jdbc:ojdbc8::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.jdbc:ojdbc8::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:18.325 - Error resolving library 'com.oracle.database.nls:orai18n::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.nls:orai18n::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:18.327 - Error resolving library 'com.oracle.database.xml:xdb6::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xdb6::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:18.333 - Error resolving library 'com.oracle.database.xml:xmlparserv2::RELEASE' dependencies
java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-03-23 12:40:18.356 - org.jkiss.dbeaver.DBException: Error resolving dependencies
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:91)
	at org.jkiss.dbeaver.ui.dialogs.driver.DriverDependenciesTree.lambda$1(DriverDependenciesTree.java:120)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.io.IOException: Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.resolveLocalVersion(DriverLibraryMavenArtifact.java:297)
	at org.jkiss.dbeaver.registry.driver.DriverLibraryMavenArtifact.getDependencies(DriverLibraryMavenArtifact.java:203)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:107)
	at org.jkiss.dbeaver.registry.driver.DriverDependencies.resolveDependencies(DriverDependencies.java:57)
	... 3 more
```

**Comment by serge-rider** [comment]
Recently Oracle JDBC Driver was added in Maven Central. So we changed community driver config.

Are you behind a corporate firewall which restricts Maven Central direct access? If so then you can:
1. Configure proxy settings in dbeaver preferences
1. Remove Maven artifacts from driver config (you probably already have some local jars there).

**Comment by smarano** [comment]
Same Issue! 
I am not behind firewall. 

Error resolving dependencies
  Maven artifact 'maven:/com.oracle.database.xml:xmlparserv2::RELEASE' not found

**Comment by maln0ir** [comment]
Yes, that was proxy setting issue (port was changed from 8080 to 8081 for some reason). I think it is solved.
