### ISSUE TITLE
Can't open snap app after upgrade

### ISSUE THREAD

**Issue by cpxondo** [dbeaver/dbeaver#8280]
Hi there!

I'm using Fedora 31 and the dbeaver snap app just upgraded from 6.0.3 to 7.0.1, and suddenly is not starting at all. For what I could saw from logs it appears this error:

> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.700.v20191113-1031]
2020-03-26 11:48:55.152 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4720)
	at org.eclipse.swt.SWT.error(SWT.java:4635)
	at org.eclipse.swt.SWT.error(SWT.java:4606)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$24.runWithException(Workbench.java:1803)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:146)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5786)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1797)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1643)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2821)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
2020-03-26 11:48:55.159 - DBeaver is stopping

Maybe is just missing some dependencies on my system, but I just coudn't find which one.
Thanks for the help!

Regards

**Comment by giacomofm** [comment]
I've got the same error, on Fedora 31, installed with snap, the error appears after the update to the version 7.0.1.202003211804

**Comment by galleog** [comment]
The same issue on Kubuntu 18.04

**Comment by uslss** [comment]
thanks for the bug report

**Comment by riednyko** [comment]
Verified. On Fedora 31 version 7.1.0 runs without errors
