### ISSUE TITLE
Snap fails on Ubuntu 19.10

### ISSUE THREAD

**Issue by bschofield** [dbeaver/dbeaver#8319]
#### System information: 
- Ubuntu 19.10
- snap dbeaver-ce 7.0.1.202003211804

#### Describe the problem you're observing:

Snap fails to start with AppArmor issue.

May be related to https://github.com/dbeaver/dbeaver/issues/8280, but it is hard to tell because that report doesn't contain a full startup log.

#### Steps to reproduce, if exist:

Attempt to start dbeaver.

#### Include any warning/errors/backtraces from the logs

```
Picked up _JAVA_OPTIONS: -Duser.home=/home/ben/snap/dbeaver-ce/53
> Start DBeaver Standalone [org.jkiss.dbeaver.core.application 7.0.1.202003211804]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.0.v20191120-1917]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.600.v20191106-1503]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.600.v20191122-2104]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.16.100.v20191122-2109]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.0.1.202003211804]
2020-04-02 09:29:16.919 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.196" (uid=1000 pid=30299 comm="/snap/dbeaver-ce/53/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.18" (uid=1000 pid=2473 comm="/usr/lib/gnome-session/gnome-session-binary --syst" label="unconfined")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.500.v20191122-2109]
2020-04-02 09:29:17.112 - DBeaver 7.0.1.202003211804 is starting
2020-04-02 09:29:17.112 - OS: Linux 5.3.0-45-generic (amd64)
2020-04-02 09:29:17.113 - Java version: 1.8.0_242 by Private Build (64bit)
2020-04-02 09:29:17.113 - Install path: '/snap/dbeaver-ce/53/usr/share/dbeaver'
2020-04-02 09:29:17.113 - Instance path: 'file:/home/ben/snap/dbeaver-ce/53/.local/share/DBeaverData/workspace6/'
2020-04-02 09:29:17.113 - Memory available 61Mb/910Mb
> Start Core File Systems [org.eclipse.core.filesystem 1.7.600.v20191122-2104]
> Start Core Resource Management [org.eclipse.core.resources 3.13.600.v20191122-2104]
2020-04-02 09:29:17.271 - Starting RMI server at 33255
2020-04-02 09:29:17.299 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.800.v20190930-1643]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.100.v20191122-2104]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.300.v20191017-1404]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.700.v20191114-0830]
> Start EMF Common [org.eclipse.emf.common 2.17.0.v20190920-0401]
> Start EMF Ecore [org.eclipse.emf.ecore 2.20.0.v20190920-0401]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.700.v20191030-1314]
> Start Expression Language [org.eclipse.core.expressions 3.6.600.v20191122-2104]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.900.v20191114-0715]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.700.v20191105-1310]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.400.v20191122-2104]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.700.v20191113-1031]
2020-04-02 09:29:18.322 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4720)
	at org.eclipse.swt.SWT.error(SWT.java:4635)
	at org.eclipse.swt.SWT.error(SWT.java:4606)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$24.runWithException(Workbench.java:1803)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:146)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5786)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1797)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1643)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2821)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
2020-04-02 09:29:18.341 - DBeaver is stopping
2020-04-02 09:29:18.345 - Stop RMI server
2020-04-02 09:29:18.398 - Initializing DBeaver 7.0.1
2020-04-02 09:29:18.399 - Host plugin: org.jkiss.dbeaver.core.application 7.0.1.202003211804
2020-04-02 09:29:18.399 - Initialize Core...
2020-04-02 09:29:18.399 - Can't find BC security provider. Use default JCE.
2020-04-02 09:29:18.399 - BouncyCastle not registered, using the default JCE provider
2020-04-02 09:29:18.480 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.29.202003211804]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.400.v20191008-0645]
> Start Internet Connection Management UI [org.eclipse.ui.net 1.3.600.v20190925-1021]
> Start Internet Connection Management [org.eclipse.core.net 1.3.700.v20191122-2107]
2020-04-02 09:29:18.535 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2020-04-02 09:29:18.537 - Core initialized (138ms)
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.44.202003211804]
2020-04-02 09:29:18.555 - DBeaver shutdown completed
```

**Comment by bschofield** [comment]
Installing the latest .deb direct from the website works fine. Maybe just some kind of a snap confinement issue?

**Comment by serge-rider** [comment]
This error seems to be the root cause:
`
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.196" (uid=1000 pid=30299 comm="/snap/dbeaver-ce/53/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.18" (uid=1000 pid=2473 comm="/usr/lib/gnome-session/gnome-session-binary --syst" label="unconfined")
`
AppArmor is blocking some of SWT functions in snap mode.

**Comment by bschofield** [comment]
Yes, the .deb works absolutely fine. But why provide a snap at all if you aren't going to set the confinement rules? https://snapcraft.io/docs/snap-confinement#interfaces. Otherwise it won't work at all for anyone on Ubuntu :-).

**Comment by bschofield** [comment]
https://forum.snapcraft.io/t/security-policy-and-sandboxing/554 might also help, if you do want to keep providing snaps. Although totally understand if you just tell users to install the .deb instead, that's proabbly what I would do.

**Comment by bschofield** [comment]
This is a bug in your snap build process. Check out https://forum.snapcraft.io/t/security-policy-and-sandboxing/554 if you're interested in fixing it.

**Comment by PaulCombal** [comment]
I'm getting the same error on Manjaro Linux. Is this goinf to be fixed?

**Comment by meddario** [comment]
Same error on Ubuntu 20.04

```
$ snap run dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/dbeaver-ce/61
Warning: NLS unused message: ViewsPreference_currentThemeDescription in: org.eclipse.ui.internal.messages
Warning: NLS unused message: ViewsPreference_enableAnimations in: org.eclipse.ui.internal.messages
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.300.v20200514-1625]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Meccanismo dei lavori di Eclipse [org.eclipse.core.jobs 3.10.800.v20200421-0950]
> Start UI IDE Eclipse [org.eclipse.ui.ide 3.17.100.v20200530-0835]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.2.202007051953]
> Start File system di base [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Gestione risorse principali [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-18 12:05:03.190 - Initializing DBeaver 7.1.2
2020-07-18 12:05:03.191 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953
2020-07-18 12:05:03.192 - Initialize Core...
2020-07-18 12:05:03.193 - Can't find BC security provider. Use default JCE.
2020-07-18 12:05:03.193 - BouncyCastle not registered, using the default JCE provider
2020-07-18 12:05:03.334 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.36.202007051953]
2020-07-18 12:05:03.457 - Core initialized (265ms)
2020-07-18 12:05:03.460 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.164" (uid=1000 pid=15464 comm="/snap/dbeaver-ce/61/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.49" (uid=1000pid=2115 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.700.v20200525-1456]
2020-07-18 12:05:03.688 - DBeaver 7.1.2.202007051953 is starting
2020-07-18 12:05:03.691 - OS: Linux 5.4.0-40-generic (amd64)
2020-07-18 12:05:03.691 - Java version: 1.8.0_252 by Private Build (64bit)
2020-07-18 12:05:03.691 - Install path: '/snap/dbeaver-ce/61/usr/share/dbeaver'
2020-07-18 12:05:03.691 - Instance path: 'file:/home/user/snap/dbeaver-ce/61/.local/share/DBeaverData/workspace6/'
2020-07-18 12:05:03.692 - Memory available 82Mb/910Mb
2020-07-18 12:05:03.704 - Starting RMI server at 43495
2020-07-18 12:05:03.741 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.1000.v20200514-1625]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.300.v20200422-1846]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF comune [org.eclipse.emf.common 2.19.0.v20200324-0932]
> Start EMF Ecore [org.eclipse.emf.ecore 2.22.0.v20200519-1135]
> Start EMF XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.1000.v20200517-1848]
> Start Linguaggio delle espressioni [org.eclipse.core.expressions 3.6.800.v20200319-0911]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1200.v20200529-1321]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.900.v20200513-0930]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.1000.v20200525-0806]
2020-07-18 12:05:05.755 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5795)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2793)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-07-18 12:05:05.779 - DBeaver is stopping
2020-07-18 12:05:05.783 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.51.202007051953]
2020-07-18 12:05:05.869 - DBeaver shutdown completed
2020-07-18 12:05:06.010 - Shutdown Core...
2020-07-18 12:05:06.358 - Total database drivers: 83 (83)
2020-07-18 12:05:06.551 - Shutdown completed in 541ms
```

**Comment by ChacheGS** [comment]
Same issue on Manjaro 20. Apparently the snap update to v 7.1.3.202007192031 broke it. I have tried to refresh to the "edge" version (reported to be 7.0.0.202003021717) but still the same. I haven't been able to try to go back to 7.1.2 because of the snap version naming scheme (I haven't found or figured out the build date).
```terminal
$ dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/carlos/snap/dbeaver-ce/62
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.3.202007192031]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-23 21:00:46.758 - Initializing DBeaver 7.1.3
2020-07-23 21:00:46.758 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031
2020-07-23 21:00:46.758 - Initialize Core...
2020-07-23 21:00:46.759 - Can't find BC security provider. Use default JCE.
2020-07-23 21:00:46.759 - BouncyCastle not registered, using the default JCE provider
2020-07-23 21:00:46.804 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.37.202007192031]
2020-07-23 21:00:46.838 - Core initialized (80ms)
2020-07-23 21:00:46.839 - Create display
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
2020-07-23 21:00:46.933 - DBeaver 7.1.3.202007192031 is starting
2020-07-23 21:00:46.934 - OS: Linux 5.4.52-1-MANJARO (amd64)
2020-07-23 21:00:46.934 - Java version: 1.8.0_252 by Private Build (64bit)
2020-07-23 21:00:46.934 - Install path: '/snap/dbeaver-ce/62/usr/share/dbeaver'
2020-07-23 21:00:46.934 - Instance path: 'file:/home/carlos/snap/dbeaver-ce/62/.local/share/DBeaverData/workspace6/'
2020-07-23 21:00:46.934 - Memory available 83Mb/910Mb
2020-07-23 21:00:46.938 - Starting RMI server at 59487
2020-07-23 21:00:46.950 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
2020-07-23 21:00:47.540 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4723)
        at org.eclipse.swt.SWT.error(SWT.java:4638)
        at org.eclipse.swt.SWT.error(SWT.java:4609)
        at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
        at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
        at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
        at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
        at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
        at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
        at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
        at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
        at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
        at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
        at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
        at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
        at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
        at org.eclipse.swt.widgets.Display.syncExec(Display.java:5797)
        at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
        at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
        at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2811)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-07-23 21:00:47.546 - DBeaver is stopping
2020-07-23 21:00:47.547 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.52.202007192031]
2020-07-23 21:00:47.607 - DBeaver shutdown completed
2020-07-23 21:00:47.622 - Shutdown Core...
2020-07-23 21:00:47.729 - Loading user drivers configuration from '/home/carlos/snap/dbeaver-ce/62/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2020-07-23 21:00:47.735 - Total database drivers: 84 (84)
2020-07-23 21:00:47.815 - Shutdown completed in 193ms
```

**Comment by dom3k** [comment]
You must remove font cache from locations:
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/* 
And from snap folder:
/home/dom3k/snap/dbeaver-ce/common/.cache/fontconfig

**Comment by JoaoPauloAntunes** [comment]
> You must remove font cache from locations:
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> And from snap folder:
> /home/dom3k/snap/dbeaver-ce/common/.cache/fontconfig

Wow, good! Worked for me! (I'm on Arch Linux)

**Comment by ChacheGS** [comment]
At some point in the last two months or so, Manjaro seems to have updated Java or some related setting or something (I guess) and DBeaver works again!
Thanks for the support!
