### ISSUE TITLE
Launching issue after update Dbeaver

### ISSUE THREAD

**Issue by IsmailELHa** [dbeaver/dbeaver#8408]
Hello, 

After that I tried to update DBeaver.. in vain, i'm actually unable to launch it. 
Please any help will be much appreciated.

Here are logs :

DBeaver/plugins/org.jkiss.dbeaver.ui.app.standalone_7.0.2.202004051509.pack
!STACK
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2299)
	at org.eclipse.equinox.launcher.Main.searchForSplash(Main.java:2243)
	at org.eclipse.equinox.launcher.Main.getSplashLocation(Main.java:2215)
	at org.eclipse.equinox.launcher.Main.handleSplash(Main.java:2148)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.equinox.launcher 4 0 2020-04-10 16:20:39.277
!MESSAGE Exception looking for nl\fr\splash.bmp in JAR file: c:/Users/XXXXXXXXXX/AppData/Local/DBeaver/plugins/org.jkiss.dbeaver.ui.app.standalone_7.0.2.202004051509.pack
!STACK
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2299)
	at org.eclipse.equinox.launcher.Main.searchForSplash(Main.java:2243)
	at org.eclipse.equinox.launcher.Main.getSplashLocation(Main.java:2215)
	at org.eclipse.equinox.launcher.Main.handleSplash(Main.java:2148)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.equinox.launcher 4 0 2020-04-10 16:20:39.290
!MESSAGE Exception looking for splash.bmp in JAR file: c:/Users/XXXXXXXXXX/AppData/Local/DBeaver/plugins/org.jkiss.dbeaver.ui.app.standalone_7.0.2.202004051509.pack
!STACK
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2299)
	at org.eclipse.equinox.launcher.Main.searchForSplash(Main.java:2243)
	at org.eclipse.equinox.launcher.Main.getSplashLocation(Main.java:2215)
	at org.eclipse.equinox.launcher.Main.handleSplash(Main.java:2148)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!SESSION 2020-04-10 16:20:38.771 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_231
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2020-04-10 16:20:39.481
!MESSAGE Bundle reference:file:org.eclipse.equinox.simpleconfigurator_1.3.400.v20191015-1836.jar not found.

!ENTRY org.eclipse.osgi 4 0 2020-04-10 16:20:39.497
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by uslss** [comment]
hi @IsmailELHa ,
do you install dbeaver from archive?
cannot reproduce an issue. probably you could add steps that can help to reproduce it?

**Comment by IsmailELHa** [comment]
Hi @uslss ,

No, I already had it.. it was working. 
I accept to upgrade the version and while this operation I got issues.. then cannot launch it.
I don't think that you can reproduce the issue...

**Comment by uslss** [comment]
@IsmailELHa , thanks for response.
But could you add some info about you OS and the way you install application?
Is issue always reproducible for you?

**Comment by IsmailELHa** [comment]
@uslss , 

I'm running in windows 10.  And I installed the application as an exectubale file.
I had a pressing issue, so I unistalled the application and reinstalled back.. fortunately it's working now.. 

I guess you can close the ticket. 

Thanks for your help.
