### ISSUE TITLE
NPE appears when trying to open Reference panel for Table with VFK in case Target table is removed in VFK 

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#8456]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.0.3

#### Describe the problem you're observing:
When trying to open Table with VFK in Data Viewer with opened Reference panel and target table was deleted
#### Steps to reproduce, if exist:
1. Open Table A
2. Create Foreign Key (Target Table B)
3. Delete Table B
4. Open table A and open reference table - NPE appears. (reproducible in Oracle db1.HR.actor)
#### Include any warning/errors/backtraces from the logs
```

> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.jkiss.dbeaver.model
> Error
> Thu Apr 16 14:23:50 MSK 2020
> 
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$ReferenceKey.<init>(ReferencesResultsContainer.java:389)
> 	at org.jkiss.dbeaver.ui.controls.resultset.panel.references.ReferencesResultsContainer$2.run(ReferencesResultsContainer.java:241)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> 

```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
