### ISSUE TITLE
Db2 - create PBR table space with relative pagenum option gives an error

### ISSUE THREAD

**Issue by IrynaRo** [dbeaver/dbeaver#8460]
#8214 ## System information: 
- Operating system (distribution) and version
Win10 Pro V1903
- DBeaver version
6.2.4.201911031605
- Additional extensions
N/A

#### Connection specification:
- Database name and version
Z/os Db2 V12
- Driver name
db2jcc_license_cisuz.jar
db2jcc4.jar

- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
I am running DDL statement to create tablespace. It has an option to define partitions with relative page numbering :
(PARTITION 1 DSSIZE 4G)
PAGENUM RELATIVE
I am getting an error when I execute this statement. If I remove those 2 lines above, it executes fine, also I have no problem executing it in SPUFI, meaning the statement is correct and can be executed in Db2.

#### Steps to reproduce, if exist:
DDL to run:
CREATE TABLESPACE TSNAME
IN DBNAME
USING STOGROUP SGNAME
BUFFERPOOL BP1
NUMPARTS 50
(PARTITION 1 DSSIZE 4G)
PAGENUM RELATIVE;

#### Include any warning/errors/backtraces from the logs
Error message - 
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ILLEGAL SYMBOL ". SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.21
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:419)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:781)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2852)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: ILLEGAL SYMBOL ". SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.21
	at com.ibm.db2.jcc.am.b6.a(b6.java:810)
	at com.ibm.db2.jcc.am.b6.a(b6.java:66)
	at com.ibm.db2.jcc.am.b6.a(b6.java:140)
	at com.ibm.db2.jcc.am.k3.c(k3.java:2824)
	at com.ibm.db2.jcc.am.k3.d(k3.java:2808)
	at com.ibm.db2.jcc.am.k3.b(k3.java:2168)
	at com.ibm.db2.jcc.t4.ab.k(ab.java:446)
	at com.ibm.db2.jcc.t4.ab.c(ab.java:104)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.av.h(av.java:124)
	at com.ibm.db2.jcc.am.k3.ak(k3.java:2163)
	at com.ibm.db2.jcc.am.k3.a(k3.java:3366)
	at com.ibm.db2.jcc.am.k3.e(k3.java:1131)
	at com.ibm.db2.jcc.am.k3.execute(k3.java:1110)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)

**Comment by patrickmdnet** [comment]
Same class of bug as #7821 .

Is a change needed to JSqlParser to fix this class of bug?  (DB-specific DDL that is not properly parsed.)

**Comment by IrynaRo** [comment]
> Is a change needed to JSqlParser to fix this class of bug? (DB-specific DDL that is not properly parsed.)
Patrick, if you are asking me, than sorry, I don't have an answer.

**Comment by Sargul** [comment]
Can you post the statement executed from the query manager? You might need to activate query manager in views.

**Comment by IrynaRo** [comment]
![DBeaver](https://user-images.githubusercontent.com/12518577/79590064-1099f480-809c-11ea-8c5e-08b96c58ff5a.PNG)
I attached screen shot of execution. If this is not that you were asking for, give me more details. 
Also, screenshot of log:
![image](https://user-images.githubusercontent.com/12518577/79590423-a03fa300-809c-11ea-86ad-f8bfec1502ee.png)

**Comment by patrickmdnet** [comment]
I did some testing with a z/OS DB2 V12 instance using DBeaver devel (built yesterday).  

I got some very odd results doing nothing but adding spaces around the parens.  In the below log the desired message is `DBTST IS AN UNDEFINED NAME`.  However as I add spaces I get the following errors: (I transcribed the unprintables in hex notation)

* `ILLEGAL SYMBOL ".` -- this message was truncated, perhaps a 0x00 character appeared?
* `ILLEGAL SYMBOL "\0x03". SOME SYMBOLS THAT ...`
* `ILLEGAL SYMBOL "\0x1A\0x16\0x1AP". SOME SYMBOLS THAT ...`
* `ILLEGAL SYMBOL "\0xC3\0xA2". SOME SYMBOLS THAT ...`
* `ILLEGAL SYMBOL "BPPAGENUM". SOME SYMBOLS THAT ...`

Error log attached.
[db2 parens bug.txt](https://github.com/dbeaver/dbeaver/files/4505235/db2.parens.bug.txt)

Workaround is to add a lot of space around the parentheses; this worked:

```sql
CREATE TABLESPACE TSTST
IN DBTST
USING STOGROUP SGTST
BUFFERPOOL BP1
NUMPARTS 50
(  PARTITION 1 DSSIZE 4G     )
PAGENUM RELATIVE
```

**Comment by patrickmdnet** [comment]
I was able to reproduce the above behavior with a different SQL client that uses JDBC.  So the issue may be with IBM's DB2 JDBC driver.

**Comment by IrynaRo** [comment]
Thank you, but I am getting an error when using your workaround, this time different error though.  SQL error - 644, which doesn't make sense after I checked IBM doc. 
Also, if I change 4G to 16G or 64G (double digit), I am getting error: SQL Error [42601]: ILLEGAL SYMBOL ""

**Comment by LonwoLonwo** [comment]
Hello everyone.
This issue still looks like a driver issue, not a DBeaver.

Could you execute this query in the latest DBeaver version?
Could you execute this query in any other tools or command line?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
