### ISSUE TITLE
Problem creating connections on Mac

### ISSUE THREAD

**Issue by mdahlman** [dbeaver/dbeaver#8474]
#### System information: 
- MacOS Catalina 10.15.3
- DBeaver version 7.0.2

The connection window is complete or correct in strange ways.

#### Steps to reproduce, if exist:
Here's an example:
Start by creating a connection **using this toolbar option**:
![Screen Shot 2020-04-17 at 10 58 54 AM](https://user-images.githubusercontent.com/2158311/79599660-c2382600-809a-11ea-9a86-66f2bdebb480.png)

Things look normal at first:
![Screen Shot 2020-04-17 at 10 59 01 AM](https://user-images.githubusercontent.com/2158311/79599713-d8de7d00-809a-11ea-89f3-7a002698ae2e.png)

But this is weird:
![Screen Shot 2020-04-17 at 10 59 11 AM](https://user-images.githubusercontent.com/2158311/79599750-e6940280-809a-11ea-87fa-569fdcea0e31.png)
- There is no connection name
- The selection box from the previous view shows here, but it clearly should not.

In contrast, this starting point gives different results.
![Screen Shot 2020-04-17 at 10 59 21 AM](https://user-images.githubusercontent.com/2158311/79599991-47bbd600-809b-11ea-97f2-88a2f3a315ad.png)

![Screen Shot 2020-04-17 at 10 59 32 AM](https://user-images.githubusercontent.com/2158311/79600010-4f7b7a80-809b-11ea-98c8-4b25bad2095b.png)

![Screen Shot 2020-04-17 at 10 59 42 AM](https://user-images.githubusercontent.com/2158311/79600028-55715b80-809b-11ea-8625-5b01df2667e6.png)

![Screen Shot 2020-04-17 at 10 59 50 AM](https://user-images.githubusercontent.com/2158311/79600041-5acea600-809b-11ea-90e3-0f118a6ab024.png)

Is this known? Should I send more info.

**Comment by mdahlman** [comment]
By the way, I'm getting some other strange behavior as well. My JDBC drivers are not being found sometimes. Restarting DBeaver fixes it. I have not logged this issue because I haven't been able to reproduce it systematically. But I have reproduced it multiple times on multiple machines.

I logged the above case because it's easy to reproduce, and perhaps both issues have a common cause.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
btw, @mdahlman could you clarify what selection box are you talking about?
`The selection box from the previous view shows here, but it clearly should not.`

**Comment by uslss** [comment]
NPE Appears

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui.workbench
> Error
> Mon Apr 20 17:26:35 MSK 2020
> Unhandled event loop exception
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.getSelectedNavigatorSettings(NewConnectionWizard.java:96)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.activatePage(ConnectionPageGeneral.java:132)
> 	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:57)
> 	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1252)
> 	at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1222)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1222)
> 	at org.jkiss.dbeaver.ui.dialogs.ActiveWizardDialog.showPage(ActiveWizardDialog.java:101)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard.openSettingsPage(ConnectionWizard.java:236)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.openSettingsPage(ConnectionPageSettings.java:312)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageAbstract$1.widgetSelected(ConnectionPageAbstract.java:150)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
> 	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
> 	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:73)
> 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
> 
> 
```

**Comment by serge-rider** [comment]
@uslss I believe it was fixed in #8503

**Comment by mdahlman** [comment]
Seems likely this is the same issue.
I'll confirm one way or another after the next point release is available.

**Comment by uslss** [comment]
verified
