### ISSUE TITLE
When clicking "Test Connection..." or "Finish" nothing happens

### ISSUE THREAD

**Issue by TimothyAlexisVass** [dbeaver/dbeaver#8503]
Same thing as https://github.com/dbeaver/dbeaver/issues/5971

It worked fine on a different computer using 7.0.1, so I reinstalled the older version and it works on this one too.

#### System information: 
- Ubuntu 18.04.4
- DBeaver 7.0.3

#### Connection specification:
- MariaDB 
- mariadb-java-client-2.4.3
- SSH Tunnel

#### Describe the problem you're observing:
When clicking "Test Connection..." or "Finish" nothing happens. No error, nothing.

#### Steps to reproduce, if exist:
- Create a connection.
- Set up SSH tunnel (works fine).
- Connect to database on localhost (nothing happens).

**Comment by TimothyAlexisVass** [comment]
Simply to make sure, I upgraded to 7.0.3, the connection works fine since it's already created.
The same thing happens when I try to add a new one.
Downgraded to 7.0.1 again and it works fine.

Upgraded to 7.0.3 on the other computer and it is working fine there too, which is surprising.

**Comment by TimothyAlexisVass** [comment]
So, changing the local client from MariaDB (mariadb-client-core-10.1) to MySQL (mysql-client-5.7).
Now it works in version 7.0.3

Which is a surprise.

**Comment by TrejoCode** [comment]
Same problem.

**Comment by zacaj** [comment]
Also getting this with postgres on the latest version, freshly installed

**Comment by jgarciao** [comment]
Same problem trying to create an Oracle connection on DBeaver 7.0.3 installed from [Flabhub](https://flathub.org/apps/details/io.dbeaver.DBeaverCommunity)

The previous version worked fine

```
eclipse.buildId=unknown
java.version=11.0.7
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=ca_ES
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Fri Apr 24 08:39:21 CEST 2020
Unhandled event loop exception

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.getSelectedNavigatorSettings(NewConnectionWizard.java:96)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.saveSettings(ConnectionPageGeneral.java:576)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.saveSettings(NewConnectionWizard.java:214)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.performFinish(NewConnectionWizard.java:197)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.buttonPressed(NewConnectionDialog.java:77)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:73)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:425)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:436)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

```

**Comment by uslss** [comment]
seems that issue is reproducible in case of creation connection using this context menu:
![image](https://user-images.githubusercontent.com/31996417/80225142-571ac080-8653-11ea-8fed-cda3449e5a3a.png)
If New connection button ![image](https://user-images.githubusercontent.com/31996417/80225229-7285cb80-8653-11ea-8c11-2a38723c7ad8.png) is used - issue isn't reproducible

**Comment by rcornish-chwy** [comment]
The workaround above worked for me, thanks!

**Comment by MBurchard** [comment]
Thank you for that workaround...

**Comment by serge-rider** [comment]
Probably fixed in #8511

**Comment by uslss** [comment]
now Finish button is always greyed out when connection is created using dropdown
![image](https://user-images.githubusercontent.com/31996417/80381881-40ba7200-88aa-11ea-9573-f01c3a0c98e2.png)

**Comment by serge-rider** [comment]
Missed that. Fixed

**Comment by uslss** [comment]
verified

**Comment by mhaertel** [comment]
I originally opened [#8571](https://github.com/dbeaver/dbeaver/issues/8571) which was marked as duplicate to this one. 

I found out that when using the + button in database navigator view it didn't work but when using the project view and right click on connections > create it works fine.

**Comment by fuv0000** [comment]
i am having this issue and none of these workarounds work for me. I am trying to connect hana db. any advice??

**Comment by mhaertel** [comment]
Sorry, for me the buttons work fine on the projects tab:
![image](https://user-images.githubusercontent.com/10459780/91466735-d7666200-e88f-11ea-87d3-3cb5b17f9800.png)

When creating a connection using the regular navigator it still fails in version 7.0.3.202004191823 (I didn't install latest update though)

**Comment by fuv0000** [comment]
Thanks for answering....The "Connections" section does not even appear for me under General.

**Comment by fuv0000** [comment]
this lead me to the right place though!! Got it to work now!
