### ISSUE TITLE
Autocomplete Fails with Postgresql 8.3 (Fix Included)

### ISSUE THREAD

**Issue by ironhacker** [dbeaver/dbeaver#8510]
#8214 
## System information: 
- Ubuntu 20.04
- DBeaver 7.0.3
- Java version java-8-openjdk-amd64/bin/java ( included with snap?)
- Additional extensions

#### Connection specification:
- Postgresql 8.3
- Driver name postgresq-9.4.1212.jre7.jar
- Do you use tunnels or proxies: yes - ssh 

#### Describe the problem you're observing:

Auto-complete fails as well as schema browsing for columns.

#### Steps to reproduce, if exist:
1. Open editor.
2. Type query - example "SELECT name FROM s1.people p WHERE p.
3. Auto complete fails.

This change fixes the issue.

```

--- a/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDataTypeCache.java
+++ b/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDataTypeCache.java
@@ -110,7 +110,7 @@ public class PostgreDataTypeCache extends JDBCObjectCache<PostgreSchema, Postgre
 
     private static String getBaseTypeNameClause(@NotNull PostgreDataSource dataSource) {
         if (dataSource.isServerVersionAtLeast(7, 3)) {
-            return "format_type(nullif(t.typbasetype, 0), t.typtypmod) base_type_name";
+            return "format_type(nullif(t.typbasetype, 0), t.typtypmod) AS base_type_name";
         } else {
             return "NULL base_type_name";
         }
```

#### Include any warning/errors/backtraces from the logs

org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ERROR: syntax error at or near "base_type_name"
  Position: 79
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:426)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:418)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:778)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2942)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "base_type_name"
  Position: 79

Server side I see this:

2020-04-21 13:09:45 CDT STATEMENT:  SELECT t.oid,t.*,format_type(nullif(t.typbasetype, 0), t.typtypmod) base_type_name FROM pg_catalog.pg_type t
    LEFT OUTER JOIN pg_class c ON c.oid=t.typrelid
    WHERE t.typname=$1
2020-04-21 13:09:45 CDT ERROR:  syntax error at or near "base_type_name" at character 79

**Comment by serge-rider** [comment]
Thanks for the report and for the fix!

**Comment by kseniiaguzeeva** [comment]
verified
