### ISSUE TITLE
to create new derby embedded connection fails

### ISSUE THREAD

**Issue by kaiyen8804** [dbeaver/dbeaver#8511]
#### System information: 
- Windows 8.1 Enterprise
- DBeaver 7.0.3.202004191823

#### Connection specification:
- Derby Embedded 10.15.2.0
- org.apache.derby.jdbc.EmbeddedDriver
- No tunnels or proxies 

#### Describe the problem you're observing:
To create new derby embedded connection fails when use quick menu

#### Steps to reproduce, if exist:
![Image 7](https://user-images.githubusercontent.com/13128715/79941623-4f162180-8497-11ea-8b94-22c66c895c18.png)
![Image 8](https://user-images.githubusercontent.com/13128715/79941624-4faeb800-8497-11ea-975b-ebfec5c964dd.png)

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.ui 4 0 2020-04-22 12:34:41.824
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.getSelectedNavigatorSettings(NewConnectionWizard.java:96)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.saveSettings(ConnectionPageGeneral.java:576)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.saveSettings(NewConnectionWizard.java:214)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard.testConnection(ConnectionWizard.java:140)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.testConnection(NewConnectionDialog.java:90)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.buttonPressed(NewConnectionDialog.java:74)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
	at org.jkiss.dbeaver.ui.actions.datasource.NewConnectionDriverSelectorContributor$NewConnectionAction.run(NewConnectionDriverSelectorContributor.java:73)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed.
Also new embedded database create was fixed (for Derby and HSQLDB).

**Comment by uslss** [comment]
verified
