### ISSUE TITLE
No Git repositories show up in Repository view

### ISSUE THREAD

**Issue by marcelhey** [dbeaver/dbeaver#8518]
DBeaver 7.03
Windows server 2016
Java 1.8

Git implementation is working, except the repositories overview is empty. New repositories can be added, but neither of them show up in the Git Repositories perspective.

**Comment by jonesisg1** [comment]
I have the same issue. 
I have tried reinstalling DBeaver (after uninstalling) but the issue persists. 
My environment:
DBeaver Community Edition	7.0.4.202005031953
DBeaver Git support	1.0.20.202005031953	org.jkiss.dbeaver.git.feature.feature.group
Git integration for Eclipse	5.7.0.202003110725-r	org.eclipse.egit.feature.group	Eclipse EGit
OS Name	Microsoft Windows 10 Pro
OS Version	10.0.18363 Build 18363

**Comment by uslss** [comment]
thanks for the bug report

**Comment by YoYo-Pete** [comment]
Same here.   

  DBeaver	7.1.3.202007192031	org.jkiss.dbeaver.core.product	null
  DBeaver Git support	1.0.25.202007192031	org.jkiss.dbeaver.git.feature.feature.group	DBeaver Corp
  
After 7.1.3 update, the Git Reflog started working, but the Repositories list is still blank.

**Comment by serge-rider** [comment]
Fixed.
It was a workbench config issue in the Eclipse platform (something has changed in 2020-03).

**Comment by uslss** [comment]
NPE Appears when trying to open Git Repositories tab
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/37529/AppData/Roaming/DBeaverData/workspace6/

org.eclipse.jface
Error
Tue Aug 11 15:13:39 MSK 2020
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.NullPointerException
	at org.eclipse.egit.ui.internal.repository.RepositoryTreeNodeLabelProvider.update(RepositoryTreeNodeLabelProvider.java:182)
	at org.eclipse.egit.ui.internal.repository.RepositoriesView$PathAddingLabelProvider.update(RepositoriesView.java:1340)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:954)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:121)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1032)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2108)
	at org.eclipse.jface.viewers.StructuredViewer.internalUpdate(StructuredViewer.java:2091)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2032)
	at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:545)
	at org.eclipse.ui.navigator.CommonViewer.update(CommonViewer.java:515)
	at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:1976)
	at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1155)
	at org.eclipse.ui.navigator.CommonViewer.handleLabelProviderChanged(CommonViewer.java:240)
	at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:95)
	at org.eclipse.jface.viewers.BaseLabelProvider$1.run(BaseLabelProvider.java:75)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.BaseLabelProvider.fireLabelProviderChanged(BaseLabelProvider.java:72)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.lambda$0(DecoratingStyledCellLabelProvider.java:78)
	at org.eclipse.ui.internal.decorators.DecoratorManager$1.run(DecoratorManager.java:349)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.DecoratorManager.fireListener(DecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$3.runInUIThread(DecorationScheduler.java:525)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)


```

**Comment by serge-rider** [comment]
I can't reproduce this.
It is definitely a bug in EGit and most likely it is a result of some specific Git config in your local workspace.
Unfortunately we cannot affect this.

Does it happen always? Can you see repositories after that?

**Comment by kseniiaguzeeva** [comment]
verified
