### ISSUE TITLE
PREPARE statement and transaction throw pgbouncer with transaction pooling

### ISSUE THREAD

**Issue by sgrinko** [dbeaver/dbeaver#8543]
System information:

- Windows 10
- DBeaver 7.0.3
- No additional extensions

Connection specification:

- DB: PostgreSQL 12.2
- Driver: org.postgresql:postgresql:RELEASE 42.2.5
- No tunnels or proxies
- Used pgbouncer version 1.12 with transaction pooling

Describe the problem you're observing:

```
begin;
--
update Hershel_packets set status=0 where id = 83075778;
```

I see SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:491)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:426)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:418)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:778)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2942)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: org.postgresql.util.PSQLException: ERROR: prepared statement "S_35" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:233)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreExecutionContext.refreshDefaults(PostgreExecutionContext.java:147)
	at org.jkiss.dbeaver.model.DBUtils.refreshContextDefaultsAndReflect(DBUtils.java:1747)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$10.run(SQLEditor.java:3420)
	... 2 more
```

from postgresql log...
```
2020-04-24 14:37:41.136 MSK [33781]: [1-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/47334 txid:0] [idle in transaction] ERROR:  prepared statement "S_35" does not exist
2020-04-24 14:37:46.429 MSK [33781]: [2-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-04-24 14:37:46.429 MSK [33781]: [3-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] STATEMENT:  update Hershel_packets set status=0 where id = 83075778
2020-04-24 14:37:46.463 MSK [33781]: [4-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-04-24 14:37:46.463 MSK [33781]: [5-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] STATEMENT:  update Hershel_packets set status=0 where id = 83075778
2020-04-24 14:37:46.496 MSK [33781]: [6-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-04-24 14:37:46.496 MSK [33781]: [7-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] STATEMENT:  update Hershel_packets set status=0 where id = 83075778
2020-04-24 14:37:46.530 MSK [33781]: [8-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-04-24 14:37:46.530 MSK [33781]: [9-1] user=[postgres],db=[mkgu],app=[DBeaver 7.0.3 - SQLEditor <Script-15.sql>],client=[127.0.0.1], [vxid:5/0 txid:0] [PARSE] STATEMENT:  update Hershel_packets set status=0 where id = 83075778
```

How do I configure DBeaver to be able to perform data edits within a transaction using pgboucer?

**Comment by sgrinko** [comment]
My setting

![изображение](https://user-images.githubusercontent.com/10084993/80210910-43fcf600-863d-11ea-9d1e-b13651b4d676.png)

**Comment by sgrinko** [comment]
I ask for help in solving the problem

**Comment by sgrinko** [comment]
I ask for help in solving the problem

**Comment by uslss** [comment]
Hi @sgrinko , 
at first, sorry for the late response.
It is known pgbouncer issue. Unfortunately, we cannot fix it.

**Comment by sgrinko** [comment]
Is it possible to disable the use of a PREPARE statement in DBeaver ?

**Comment by uslss** [comment]
@sgrinko Please create new tickets, if you have any proposal about dbeaver improvement.
Thanks in advance.
Close this ticket as solved
