### ISSUE TITLE
"SWTException: Widget is disposed" wenn running sql script

### ISSUE THREAD

**Issue by mseele** [dbeaver/dbeaver#8577]
#### System information: 
- Operating system (distribution) and version: Windows 10 Version 1909 (Build 18363.778)
- DBeaver version: Version 7.0.3.202004191823
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle Database 19c Enterprise Edition
- Driver name: Oracle JDBC driver 19.3.0.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

When i run the attached setup.sql via "Execute SQL Script (Alt+X)" i've got multiple of "SWTException: Widget is disposed" exceptions. Please see attached logfile.

#### Steps to reproduce, if exist:

Save the following 3 files as ".sql" (github doesn't allow .sql files to upload) in one directory and execute setup.sql as "Execute SQL Script".

[setup.sql.txt](https://github.com/dbeaver/dbeaver/files/4550754/setup.sql.txt)
[change_ids.sql.txt](https://github.com/dbeaver/dbeaver/files/4550755/change_ids.sql.txt)
[approval_ids.sql.txt](https://github.com/dbeaver/dbeaver/files/4550756/approval_ids.sql.txt)

#### Include any warning/errors/backtraces from the logs

These are the errors i get: [log.txt](https://github.com/dbeaver/dbeaver/files/4550766/log.txt)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
error appears
![2020-04-29_18h33_33](https://user-images.githubusercontent.com/31996417/80615176-04247d00-8a48-11ea-9223-4d711b7a1a74.gif)

**Comment by uslss** [comment]
```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui.workbench.texteditor
> Error
> Wed Apr 29 19:07:46 MSK 2020
> Editor could not be initialized.
> 
> java.lang.ClassCastException: class java.lang.String cannot be cast to class org.jkiss.dbeaver.model.DBPDataSourceContainer (java.lang.String is in module java.base of loader 'bootstrap'; org.jkiss.dbeaver.model.DBPDataSourceContainer is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @522ab48b)
> 	at org.jkiss.dbeaver.ui.editors.EditorUtils.getInputDataSource(EditorUtils.java:148)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.lambda$11(SQLEditor.java:1495)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.doSetInput(SQLEditor.java:1505)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3179)
> 	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
> 	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
> 	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2375)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2373)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3196)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3221)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.init(SQLEditor.java:1455)
> 	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:353)
> 	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:340)
> 	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:967)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:331)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
> 	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:107)
> 	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
> 	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
> 	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
> 	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4561)
> 	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:219)
> 	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
> 	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
> 	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
> 	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> 	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:132)
> 	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
> 	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
> 	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
> 	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
> 	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
> 	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
> 	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
> 	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:661)
> 	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:625)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:790)
> 	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1263)
> 	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
> 	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
> 	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
> 	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openSQLEditor(SQLEditorHandlerOpenEditor.java:275)
> 	at org.jkiss.dbeaver.ui.editors.sql.handlers.SQLEditorHandlerOpenEditor.openSQLConsole(SQLEditorHandlerOpenEditor.java:267)
> 	at org.jkiss.dbeaver.ui.editors.sql.commands.SQLCommandInclude.lambda$0(SQLCommandInclude.java:84)
> 	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
> 	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:171)
> 	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:139)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
> 
> 
```

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
