### ISSUE TITLE
Export Result Set to File button has inconsistent behaviour.

### ISSUE THREAD

**Issue by J-Z-C** [dbeaver/dbeaver#8584]
I have searched past issues and have not found anything that appears to be a solution to this problem, however I would be happy to learn that I have simply been making a mistake!  Issue #6210 has some similarity but has enough differences that I think this warrants a new entry.

#### System information: 
I am running DBeaver on a remote desktop using "Windows Server 2012 R2".
I believe the desktop is running on a linux server that I cannot directly access, but my best guess
is running Red Hat Enterprise Linux Server release 7.3 (Maipo).

DBeaver version is Version 7.0.1.202003211804  - released March 23 2020

#### Connection specification:
The database is MYSQL, not using SSH or proxy.
In any event getting a connection and retrieving data appears to be OK.

#### Describe the problem you're observing:
Running SQL appears normal.
The first 200 rows of data appear quickly and normally.
Additional rows of data can easily be seen by scrolling.

Here is the problem:  The "Export Result Set to File" button is almost always not active.  It appears greyed out, and produces no action.  This is a button at the bottom of the data preview panel that appears when some SQL is run in the editor.

I say almost, because the behaviour is not consistent.  Or at least I have not been able to identify any pattern, or mode of use on my part that makes a difference.

Other buttons to the left of the Export button are also often inactive.

Sometimes simply scrolling the preview up and down will cause the Export button to light up.  Other times not.  Sometimes hitting the Calculate Total Row count will cause some of the inactve buttons to light up, but not always.  

Today, the problem appeared, and I was unable to cause the Export button to work, until after waiting 20 minutes, when hitting the Calculate Total Row count button (again) caused the Fetch All Rows button to light up, as well as the "Move to" buttons.  Hitting one of the "Move to" buttons finally caused the Export button to light up, and it started behaving normally.  Exporting data worked fine.

The error log shows two entries from today - both logged an hour and a half ago.  See text at bottom for the most recent.

Oddly, when the Error Log tab appeared, various buttons greyed out, and hitting one of the "Move to" buttons brought them back again, along with the Export button.

Since this is an intermittent problem, I ran the same SQL again three times with no issues.
On the fourth trial I switched to slightly different SQL, which has previously worked, this time the Export button is greyed out again. The "Move to" buttons are lit up, as well as the Fetch all and Fetch next buttons.  

HItting the "Fetch All" button enabled preview of all the 50K rows of data I need, but still the Export button is greyed out.

Killing the preview tab and the error log tab, I re-ran the same SQL, and again the Export button is greyed out and inoperative along with the "Move to" and "Fetch" buttons.

The Error Log still shows the same two errors from earlier today, apparently not related to this issue.

Hitting a Move to button brought back the Export button this time.  I understand the logic of the "Move to" buttons, when you are looking at the top row, you can't move up, and when looking at the bottom row, you can't move down, but this appears unrelated to the Export button, and "Fetch" buttons.

All the SQL I have been testing with has been used previously, and always produces the preview rows with no issue.

If this is simply operator error, I would love to find out!  If this is a bug you have not seen before, feel free to contact me and I will be happy to work with you on it.

Thanks;
- JC

Error log entry:

eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Tue Apr 28 12:08:54 EDT 2020
Unhandled event loop exception

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4720)
	at org.eclipse.swt.SWT.error(SWT.java:4635)
	at org.eclipse.swt.SWT.error(SWT.java:4606)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:452)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:351)
	at org.eclipse.swt.widgets.Table.setRedraw(Table.java:4712)
	at org.jkiss.dbeaver.ui.UIUtils.packColumns(UIUtils.java:198)
	at org.jkiss.dbeaver.ui.controls.resultset.valuefilter.FilterValueEditPopup.lambda$5(FilterValueEditPopup.java:182)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3963)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3590)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by uslss** [comment]
hi @J-Z-C , i'm very sorry for so late response.
Unfortunately, cannot reproduce an issue.
could you check if Expord data button  is available in context menu? is issue still reproducible against 7.0.5?
![image](https://user-images.githubusercontent.com/31996417/82680414-e5836180-9c54-11ea-8532-3435532a7316.png)

**Comment by J-Z-C** [comment]
Let's call the issue closed.

I don't have control of which version is installed, so can't check 7.0.5.

Also, while the button at the bottom of the screen still does not work consistently, the context menu (right click with the cursor in the results table) does always produce a working Export function.

Thanks;

- JZC

�


On Fri, 22 May 2020 07:52:01 -0700, uslss <notifications@github.com> wrote:
�
�

hi @J-Z-C , i'm very sorry for so late response.
Unfortunately, cannot reproduce an issue.
could you check if Expord data button is available in context menu? is issue still reproducible against 7.0.5?

**Comment by williambuchanan2** [comment]
This is still happening. I am seeing the same problem.

**Comment by Sarke** [comment]
Same.

```
Unhandled event loop exception
java.lang.StackOverflowError
```

**Comment by andreas-loos-zon** [comment]
Same. Sometimes the export button is invalid. Workaround is to invalidate the connection and re-run the query.

**Comment by mhstnsc** [comment]
same here. reran the query. I have the latest version, button disabled. so annoying

**Comment by saywebsolutions** [comment]
Still happening; I was able to export using the context menu though more errors occurred during that process and it recommended to close the program. I continued with the export and it worked. Here is the log from the session:

[dbeaver-export-result-set-button-greyed-out.log](https://github.com/dbeaver/dbeaver/files/8566787/dbeaver-export-result-set-button-greyed-out.log)

**Comment by BartBaddeley** [comment]
Same problem. Updated to latest version DBeaver 22.0.4 and still getting the greyed out export results button.
On 3rd attempt after invalidating connection and ignoring errors it finally exported my results.

**Comment by khaerulumam42** [comment]
I also face same problem, but solved with [this methods](https://github.com/dbeaver/dbeaver/issues/8584#issuecomment-632732681)
