### ISSUE TITLE
"Import wizard" blocks DBeaver instead of running in background

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#8611]
#### System information: 
- Operating system (distribution) and version: Debian/Sid
- DBeaver version: 7.0.4 
- Additional extensions: AnyEditTools

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

After each update (by deb from https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb), the "Import wizard" runs to import the previously installed pluguin AnyEdit.
During this import 
a) the plugin is downloaded completely once again from its update site, despite not having changed at all from the version already installed! This seems unnecessary, why can't the alreday installed plugin not be re-used, at least as long DBEaver's underlying Eclipse version remains the same?
b) that download takes in my case a considerably long time, usually about 15-20 minutes. In the meantime, the "Import wizard" blocks DBeaver completely, rendering it unusable. That wizard needs to run in the background!

![Screenshot_20200504_101831](https://user-images.githubusercontent.com/50481865/80948482-7dc6bd00-8df2-11ea-8a23-b511a52a3df3.png)

#### Include any warning/errors/backtraces from the logs

Log is full with this stacktrace, no idea if related:

```
!ENTRY org.eclipse.core.runtime 4 0 2020-05-04 10:14:19.232
!MESSAGE Invalid input url:platform:/plugin/org.jkiss.dbeaver.core.application/icons/progress_view.png
!STACK 0
java.io.IOException: Unable to resolve plug-in "org.jkiss.dbeaver.core.application".
        at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:64)
        at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:293)
        at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:206)
        at org.eclipse.jface.resource.URLImageDescriptor.getStream(URLImageDescriptor.java:155)
        at org.eclipse.jface.resource.URLImageDescriptor.getImageData(URLImageDescriptor.java:123)
        at org.eclipse.jface.resource.URLImageDescriptor.access$3(URLImageDescriptor.java:121)
        at org.eclipse.jface.resource.URLImageDescriptor$URLImageDataProvider.getImageData(URLImageDescriptor.java:77)
        at org.eclipse.swt.internal.DPIUtil.validateAndGetImageDataAtZoom(DPIUtil.java:404)
        at org.eclipse.swt.graphics.Image.<init>(Image.java:706)
        at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:271)
        at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:264)
        at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:242)
        at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getImage(TrimStack.java:818)
        at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.updateTrimStackItems(TrimStack.java:883)
        at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.createWidget(TrimStack.java:638)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:345)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:227)
        at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:94)
        at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
        at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:37)
        at org.eclipse.e4.ui.workbench.renderers.swt.ToolControlRenderer.createWidget(ToolControlRenderer.java:129)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
        at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
        at org.eclipse.e4.ui.workbench.renderers.swt.TrimBarRenderer.processContents(TrimBarRenderer.java:134)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:547)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:531)
        at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:688)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1086)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```
and closes with these entries:

```
!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.507
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.DebugView" id and the "Debug" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.507
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.BreakpointView" id and the "Breakpoints" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.507
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.VariableView" id and the "Variables" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.508
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.ExpressionView" id and the "Expressions" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.508
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.RegisterView" id and the "Registers" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.508
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.ModuleView" id and the "Modules" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2020-05-04 10:14:20.508
!MESSAGE Removing PartDescriptorImpl with the "org.eclipse.debug.ui.MemoryView" id and the "Memory" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled
```

**Comment by 2019-05-10** [comment]
Well, and after all that hassle, the plugin isn't even installed anymore.
Just tried to convert a string to upper case letters, and it's not in the context menu nor in the list of installed plugins.

**Comment by serge-rider** [comment]
We do not support AnyEdit plugin.

Unfortunately it is not possible to fix this as it is based on Eclipse platform.
Base Eclipse version may change quite frequently (at least one per 3 months). And even in the same major Eclipse version there may be patches in minor version releases. So we reinstall all plugins in each new DBeaver version.

If you need conversion to upper/lower case you can use menu/shortcuts:
![image](https://user-images.githubusercontent.com/6398845/81062605-f60aac80-8ede-11ea-809f-648adf65b2dc.png)

**Comment by 2019-05-10** [comment]
Ah, thanks. That's the most important feature.

I don't fully understand that:

> We do not support AnyEdit plugin.
> Unfortunately it is not possible to fix this as it is based on Eclipse platform.

After installing from its Update Site the plugin is there and, as far as I can tell, fully functional.

**Comment by 2019-05-10** [comment]
Ehrm, the initial issue is as of now still unsolved.
The Import Wizard still blocks evverything and needs to be run in the background.
