### ISSUE TITLE
"SWTException: Widget is disposed" wenn running sql script

### ISSUE THREAD

**Issue by mseele** [dbeaver/dbeaver#8634]
#### System information:
- Operating system (distribution) and version: Windows 10 Version 1909 (Build 18363.778)
- DBeaver version: Version 7.0.4.202005031953
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle Database 19c Enterprise Edition
- Driver name: Oracle JDBC driver 19.3.0.0.0
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Seems that issue https://github.com/dbeaver/dbeaver/issues/8577 has not been fixed fully because i'm still getting exception running scripts with 7.0.4 like explained in https://github.com/dbeaver/dbeaver/issues/8577

#### Steps to reproduce, if exist:

Run as descriped in https://github.com/dbeaver/dbeaver/issues/8577

#### Include any warning/errors/backtraces from the logs

.log file: [log.txt](https://github.com/dbeaver/dbeaver/files/4585040/log.txt)

**Comment by uslss** [comment]
hi @mseele ,
cannot reproduce an issue. does it affect on script execution?

**Comment by mseele** [comment]
@uslss yes, please see attached screencast:

![issue](https://user-images.githubusercontent.com/15141672/81641281-ecbe9a00-9420-11ea-8862-e71caf7667db.gif)

**Comment by mseele** [comment]
@uslss i just want to let you know that this exception is still happening for me with release _7.1.0.202005311732_

**Comment by uslss** [comment]
@mseele sorry for the late response.
Unfortunately, we haven't got oracle 19 to test if issue is reproducible. Could you check it against recent version?
Thanks in advance

**Comment by mseele** [comment]
@uslss no problem, I can help with that if help is needed.
It is still happening for me with release __7.1.3.202007192031__:

```
!ENTRY org.eclipse.ui 4 4 2020-07-21 14:38:14.636
!MESSAGE An internal error has occurred.
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:432)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:351)
	at org.eclipse.swt.widgets.Control.redraw(Control.java:2417)
	at org.jkiss.dbeaver.ui.controls.VerticalFolder.redraw(VerticalFolder.java:116)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.refreshActions(SQLEditor.java:541)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.lambda$4(SQLEditor.java:3283)
	at org.jkiss.dbeaver.ui.UIUtils$8.runInUIThread(UIUtils.java:1548)
	at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:41)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

```

**Comment by uslss** [comment]
The issue isn't reproducible against 21.3.1
