### ISSUE TITLE
Firebird: Error on view open

### ISSUE THREAD

**Issue by scebotari66** [dbeaver/dbeaver#8635]
#### System information: 
- Operating system (distribution) and version: macOS Mojave Version 10.14.6 (18G4032)
- DBeaver version: Version 7.0.4.202005031953

#### Connection specification:
- Database name and version: Firebird 3.0.4
- Driver name: org.firebirdsql.jdbc:jaybird:RELEASE 4.0.0.java8

#### Describe the problem you're observing:
There is an error when opening a view. Basically, it is the same error described in #6260, but I thought I would open a new issue, since this occurs in another major version.

#### Steps to reproduce, if exist:
Open a database view

#### Include any warning/errors/backtraces from the logs
org.jkiss.dbeaver.DBException: class org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to class org.jkiss.dbeaver.ext.firebird.model.FireBirdTable (org.jkiss.dbeaver.ext.firebird.model.FireBirdView and org.jkiss.dbeaver.ext.firebird.model.FireBirdTable are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5026ac78)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:229)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3580)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassCastException: class org.jkiss.dbeaver.ext.firebird.model.FireBirdView cannot be cast to class org.jkiss.dbeaver.ext.firebird.model.FireBirdTable (org.jkiss.dbeaver.ext.firebird.model.FireBirdView and org.jkiss.dbeaver.ext.firebird.model.FireBirdTable are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5026ac78)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn.getTable(FireBirdTableColumn.java:50)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn.getDomainTypeName(FireBirdTableColumn.java:68)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn.<init>(FireBirdTableColumn.java:40)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createTableColumnImpl(FireBirdMetaModel.java:290)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:140)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:153)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readRequiredMeta(JDBCTable.java:922)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:130)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by dhebgen** [comment]
Same problem here using the same driver but Firebird 2.5 and DBeaver 7.0.5.202005171753

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
