### ISSUE TITLE
Unhandled event loop exception on New Connection

### ISSUE THREAD

**Issue by jasonKercher** [dbeaver/dbeaver#8697]
#### System information: 
- Arch Linux with XFCE; Kernel from `uname -a`: 5.5.13-arch1-1
- Deaver Version 7.0.4 (plugin)
- Eclipse Version 2020-03 (4.15.0) Build id: 20200313-1211
- I installed devstyle's darkest dark first...  Priorities.

This is mostly a fresh install of eclipse installed from the Arch Linux package manager via `pacman -S eclipse-java`.  When I attempt to create a connection, the wizard does not appear and an `Unhandled event loop exception` appears in the error log with the following back trace:

```
java.lang.NullPointerException
    at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.loadConnectionFolders(ConnectionPageGeneral.java:527)
    at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageGeneral.createControl(ConnectionPageGeneral.java:374)
    at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
    at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
    at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:635)
    at org.eclipse.jface.window.Window.create(Window.java:431)
    at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
    at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:119)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
    at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

```
Session Data:
```
eclipse.buildId=4.15.0.I20200305-0155
java.version=13.0.2
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/home/jason/eclipse-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product 
```

PS: Thank you guys.  I love DBeaver.  I use it over SQL Server Management Studio on my Windows machine as well.

**Comment by jasonKercher** [comment]
I just downloaded the standalone dbeaver client via pacman and did not run into this issue.  This may actually be an Eclipse issue.

**Comment by uslss** [comment]
hi @jasonKercher ,
cannot reproduce an issue. Wizard appears as expected. Could you write more clear steps or share a video?

**Comment by jasonKercher** [comment]
I tried to re-produce this on another machine and discovered eclipse is actually an aur package, so it needed to be installed via:
```
git clone https://aur.archlinux.org/eclipse.git
cd eclipse
makepkg -sic
```

I previously stated that it was installed via `pacman`.  That was incorrect.

After a recent change to this package, I couldn't even get Eclipse installed.  It keeps trying to install eclipse-java and eclipse-jee which is a conflict.  Anyway, since this isn't re-producible in the standalone dbeaver, this is likely more of an Eclipse issue anyway... Closing.  Thank you.

**Comment by Jitsuryoku** [comment]
I ran into a similar issue and mine was due to Darkest Dark theme.

Leaving this here. While you might not be able to reproduce your specific issue (theme got updates since then), uninstalling the theme (and plugin it comes with) could help people running into a similar one.
