### ISSUE TITLE
PostgreSQL partial function DDL shown

### ISSUE THREAD

**Issue by plotn** [dbeaver/dbeaver#8784]
- Operating system (distribution) and version: Ubuntu 20
- DBeaver version: 7.0.5
- Database: PostgreSQL 12

Sometimes (i cant reproduce exactly, but it appears from time to time) when I open function editor - i cant see the beginning of a function e.g. I see:

```
DECLARE
  res vme.v_liq_stat_data_n_d%rowtype;
BEGIN
  for res in execute p_query loop
    return next res;
  end loop;
END;
$function$
;

```
Instead of:

```
CREATE OR REPLACE FUNCTION vme.f_liquid_search_res(p_query character varying)
 RETURNS SETOF vme.v_liq_stat_data_n_d
 LANGUAGE plpgsql
AS $function$
DECLARE
  res vme.v_liq_stat_data_n_d%rowtype;
BEGIN
  for res in execute p_query loop
    return next res;
  end loop;
END;
$function$
;
```
Refresh of objects in the tree helps...

**Comment by uslss** [comment]
Hi @plotn ,
unfortunately, cannot reproduce an issue.
Probably you've got "Show header" option disable?

**Comment by plotn** [comment]
Definetely no, cause refresh of the whole tree helps. And I didnt ever new about this option before.
I cant reproduce it stable too, but it happens (under, probably some specific circumstances).
If I get some glue, I will add more details....

**Comment by plotn** [comment]
Some add info. When this happens - every function in the database become headless. When I press show/hide header code flickers, but no changes (button becomes pressed and unpressed normally).
Neighbour database shows good code - with headers, with ability to switch them on and off.
Reconnect button helps - after reconnect newly opened windows contains full text of functions.

I suspect that it can be rely on the connection, because I work with remote databases, then close notebook, then open it again. Normally bases reconnect in the background, but there is such situation....

**Comment by uslss** [comment]
still cannot reproduce it.
@plotn does issue still occur?

**Comment by plotn** [comment]
It surely have dependency with lost connection - try to play with it (even plug in and out cable physically). 
There is more interesting bug - when reconnect, some windows stays "buggy" (with no connection) and "newly created" are normal.

**Comment by uslss** [comment]
still can't reproduce it. could you try to write steps to reproduce?

**Comment by plotn** [comment]
I'll try. Dont close please.

**Comment by uslss** [comment]
@plotn any updates?
could you check if the issue is actual for you against the recent version?
thanks in advance

**Comment by plotn** [comment]
Hi! everything is the same. I cant reproduce, but I can explain.
It is surely appears, when there is something with connection. Fresh case. I have database, connection was lost, then it autoreconnected. I can make "select 1" in SQL window, it is ok.
Then I click on the function in the tree. Text appeared without header (begins with "declare .."). "Show headers" is on. I thy to switch "show headers", text blinking, but headers is not shown.
Then I press refresh (only this function) in the tree. Dialog "connection was incalidated appears", function is shown correctly with header.
Maybe you can add some specific logs?

**Comment by uslss** [comment]
Could you check logs?
https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by plotn** [comment]
ok, sure.

**Comment by plotn** [comment]
Could it be similar to truth?:

!ENTRY org.jkiss.dbeaver.model 2 0 2020-09-15 13:20:17.487
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2020-09-15 13:20:17.487
!MESSAGE Can't determine transaction isolation - timeout
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.getTransactionIsolation(JDBCExecutionContext.java:273)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceAutoCommitHandler.updateElement(DataSourceAutoCommitHandler.java:105)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:434)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:123)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:45)
	at org.eclipse.ui.internal.commands.CommandService$1.run(CommandService.java:261)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.commands.CommandService.refreshElements(CommandService.java:265)
	at org.jkiss.dbeaver.ui.ActionUtils.lambda$0(ActionUtils.java:406)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:234)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.481
!MESSAGE Error getting transaction isolation level
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.481
!MESSAGE Ошибка ввода/ввывода при отправке бэкенду
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.481
!MESSAGE Read timed out
!STACK 0
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:417)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:410)
	at org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:811)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$1(JDBCExecutionContext.java:263)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$0(JDBCExecutionContext.java:261)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:309)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:206)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.483
!MESSAGE Error getting transaction isolation level
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.483
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:743)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:405)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:417)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:410)
	at org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:811)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$1(JDBCExecutionContext.java:263)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$0(JDBCExecutionContext.java:261)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:309)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:206)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.484
!MESSAGE Error getting transaction isolation level
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-15 13:20:25.484
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:743)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:405)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:417)
	at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:410)
	at org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:811)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$1(JDBCExecutionContext.java:263)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.lambda$0(JDBCExecutionContext.java:261)
	at org.jkiss.dbeaver.utils.RuntimeUtils$MonitoringTask.run(RuntimeUtils.java:309)
	at org.jkiss.dbeaver.utils.RuntimeUtils$1.run(RuntimeUtils.java:206)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by plotn** [comment]
another issue - connection was lost. I perform sql query - it tries to reconnect, and connects succesfully.
but says: 'SQL Error [08003]: Соединение уже было закрыто'

log is:
!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:13.488
!MESSAGE Operation failed. Retry count remains = 1
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:13.488
!MESSAGE SQL Error [08003]: Соединение уже было закрыто
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:13.488
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:1349)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1317)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:481)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:436)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:423)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:804)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3008)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:120)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4425)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:14.476
!MESSAGE SQL Error [08003]: Соединение уже было закрыто
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:14.476
!MESSAGE SQL Error [08003]: Соединение уже было закрыто
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2020-09-15 15:05:14.476
!MESSAGE Соединение уже было закрыто
!STACK 0
org.postgresql.util.PSQLException: Соединение уже было закрыто
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:244)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:1349)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:1317)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:481)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:436)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:423)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:804)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3008)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:120)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4425)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
@plotn ,
could you try to change Keep-Alive value to different from null and check if issue is still persisting?
![image](https://user-images.githubusercontent.com/31996417/95058917-ddf2bf80-0700-11eb-9ace-627dab1dfed9.png)

**Comment by uslss** [comment]
there are not any updates for a long time
Issue is closed.
If it is still actual for you - feel free to reopen it
