### ISSUE TITLE
(Firebird): exception when loading table properties: org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType

### ISSUE THREAD

**Issue by MrSparc** [dbeaver/dbeaver#8793]
#### System information: 
- Operating system (distribution) and version
  Linux (openSUSE Leap 15.1) x86_64
- DBeaver version: 
  7.0.5.202005171753  (May 18, 2020)

#### Connection specification:
- Database name and version
  Firebird 2.5  (LI-V2.5.8.27089 Firebird 2.5)
- Driver name
  org.firebirdsql.jdbc:jaybird:RELEASE (4.0.0.java8)
- Do you use tunnels or proxies (SSH, SOCKS, etc): 
  No

#### Describe the problem you're observing:
DBBeaver lists the tables of a Firebird database, but when you try to expand in the explorer to list the columns of the table, or view the table to know its structure, an exception occurs.
#### Steps to reproduce, if exist:

1. Connect to a Firebird DB using the suggested jdbc driver for Firebird and default settings
2. In the Database Navigator list:
2.1. Expand the Tables node 
2.2. Expand a table node
2.3. Expand the Columns node
3. An exception happens.
The same exception happens if select a table and with F4 (View table) while loading items to show the table structure.

#### Include any warning/errors/backtraces from the logs
```
eclipse.buildId=unknown
java.version=1.8.0_252
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.jkiss.dbeaver.model
Error
Tue May 26 10:20:46 WEST 2020
org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType

java.lang.ClassCastException: org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn.<init>(FireBirdTableColumn.java:42)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createTableColumnImpl(FireBirdMetaModel.java:290)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:140)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:153)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTable.getAttributes(FireBirdTable.java:77)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getConstraints(GenericTableBase.java:181)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getConstraints(GenericTableBase.java:1)
	at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllConstraints(DBVUtils.java:287)
	at org.jkiss.dbeaver.ext.erd.model.ERDDecoratorDefault.fillEntityFromObject(ERDDecoratorDefault.java:157)
	at org.jkiss.dbeaver.ext.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:66)
	at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillEntities(EntityDiagram.java:332)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:202)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:187)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:162)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by uslss** [comment]
Hi, @MrSparc ,
unfortunately cannot reproduce an issue.
Could you check if it is still actual against EA version (https://dbeaver.io/files/ea/)?

**Comment by uslss** [comment]
there is no update on issue. if it is still actual for you - feel free to reopen it with additional info.

**Comment by cfnz** [comment]
Hi, I have this issue too.
Running against a Firebird 2.5 server. The server does not have the native concept of a Boolean type.
I have created a BOOLEAN domain which is a Char(1) type.

It seems all the tables I open that has a column with a DOMAIN of BOOLEAN specified gets this error. Other tables open fine.

This used to work, but can't recall in which version :-)...

e.g. 
```
CREATE DOMAIN BOOLEAN AS
CHAR(1) CHARACTER SET NONE
DEFAULT 'F'
NOT NULL
CHECK (Value in ('T',  'F'))
COLLATE NONE
```

then
```
CREATE TABLE TEST_TABLE (
    ID             INTEGER NOT NULL,
    TEST_BOOLEAN   BOOLEAN NOT NULL /* BOOLEAN = CHAR(1) DEFAULT 'F' NOT NULL CHECK (Value in ('T',  'F')) */,
    TEST_OTHER     VARCHAR(64) NOT NULL
);
```

Opening this table with or without data causes 
`org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType
`

Other domains are fine so seems to be with a DOMAIN named BOOLEAN (which is not a reserved word in Firebird 2.5 at least) causes issues.

Is it possible to reopen this issue?
