### ISSUE TITLE
Unable to setup SSH tunnel with SSH agent in Snap

### ISSUE THREAD

**Issue by Wouter0100** [dbeaver/dbeaver#8800]
#### System information: 
- Ubuntu 20.04
- Version 7.0.5.202005171753 (using latest snap)

#### Describe the problem you're observing:
Using a MySQL connection (haven't tested others) I'm unable to setup a SSH tunnel using a SSH agent. It seem it's blocked by snapd:
```
May 26 15:19:57 wouter0100-xps java[106397]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
May 26 15:19:57 wouter0100-xps java[106397]: message repeated 4 times: [ gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton]
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: shm_open() failed: Permission denied
May 26 15:19:57 wouter0100-xps kernel: [ 5980.614540] kauditd_printk_skb: 15 callbacks suppressed
May 26 15:19:57 wouter0100-xps kernel: [ 5980.614542] audit: type=1400 audit(1590499197.419:210): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/etc/pulse/client.conf" pid=106397 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
May 26 15:19:57 wouter0100-xps kernel: [ 5980.615267] audit: type=1400 audit(1590499197.419:211): apparmor="DENIED" operation="mknod" profile="snap.dbeaver-ce.dbeaver-ce" name="/dev/shm/pulse-shm-557037589" pid=106397 comm="java" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps kernel: [ 5980.615499] audit: type=1400 audit(1590499197.419:212): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/pulse/native" pid=106397 comm="java" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps kernel: [ 5980.708924] audit: type=1400 audit(1590499197.515:213): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/etc/pulse/client.conf" pid=106397 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
May 26 15:19:57 wouter0100-xps kernel: [ 5980.710189] audit: type=1400 audit(1590499197.515:214): apparmor="DENIED" operation="mknod" profile="snap.dbeaver-ce.dbeaver-ce" name="/dev/shm/pulse-shm-3569902338" pid=106397 comm="java" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps kernel: [ 5980.710436] audit: type=1400 audit(1590499197.515:215): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/pulse/native" pid=106397 comm="java" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps kernel: [ 5980.710653] audit: type=1400 audit(1590499197.515:216): apparmor="DENIED" operation="open" profile="snap.dbeaver-ce.dbeaver-ce" name="/etc/pulse/client.conf" pid=106397 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
May 26 15:19:57 wouter0100-xps kernel: [ 5980.711027] audit: type=1400 audit(1590499197.515:217): apparmor="DENIED" operation="mknod" profile="snap.dbeaver-ce.dbeaver-ce" name="/dev/shm/pulse-shm-1419807463" pid=106397 comm="java" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps kernel: [ 5980.711212] audit: type=1400 audit(1590499197.515:218): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/pulse/native" pid=106397 comm="java" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: message repeated 2 times: [ shm_open() failed: Permission denied]
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: 2020-05-26 15:19:57.537 - pageant connect exception
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:116)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:203)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1716)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: 2020-05-26 15:19:57.537 - ssh-agent connection exception
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: com.jcraft.jsch.agentproxy.AgentProxyException: java.io.IOException: failed to fctrl usocket: -1
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:56)
May 26 15:19:57 wouter0100-xps kernel: [ 5980.728117] audit: type=1400 audit(1590499197.531:219): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/keyring/ssh" pid=106397 comm="ModalContext" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:44)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:124)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:203)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1716)
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: #011at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
May 26 15:19:57 wouter0100-xps java[106397]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: shm_open() failed: Permission denied
May 26 15:19:57 wouter0100-xps dbeaver-ce_dbeaver-ce.desktop[106397]: shm_open() failed: Permission denied
May 26 15:19:57 wouter0100-xps java[106397]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
May 26 15:19:57 wouter0100-xps java[106397]: message repeated 2 times: [ gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton]
```
Any more specific:
```
May 26 15:19:57 wouter0100-xps kernel: [ 5980.728117] audit: type=1400 audit(1590499197.531:219): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/keyring/ssh" pid=106397 comm="ModalContext" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
```

#### Steps to reproduce, if exist:
Install dbeaver-ce using snap and try to test a SSH tunnel with a new connection.

**Comment by uslss** [comment]
hi @Wouter0100 ,
sorry for the late response. Is it still actual against the recent version?

**Comment by Wouter0100** [comment]
@uslss no worries. Sorry for me as well. I moved to the deb variant, as I was in need of DBeaver. Now I had some time to install the snap and test it again.

Unfortunately, it didn't work:

```
2020-06-27 20:19:35.743 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.NoClassDefFoundError: Could not initialize class com.jcraft.jsch.agentproxy.connector.PageantConnector$User32
	at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:68)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:116)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:206)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1716)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
2020-06-27 20:19:35.744 - ssh-agent connection exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.io.IOException: failed to fctrl usocket: -1
	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:56)
	at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:44)
	at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:124)
	at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
	at org.jkiss.dbeaver.ui.net.ssh.SSHTunnelConfiguratorUI.lambda$0(SSHTunnelConfiguratorUI.java:206)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1716)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

```
$ tail -f /var/log/syslog -n 0
Jun 27 20:20:53 wouter0100-desktop kernel: [47671.821897] audit: type=1400 audit(1593282053.381:90): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/keyring/ssh" pid=32683 comm="ModalContext" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Menus" member="Start" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Actions" member="DescribeAll" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Menus" member="Start" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Actions" member="DescribeAll" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Menus" member="End" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/14" interface="org.gtk.Menus" member="End" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Menus" member="Start" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Actions" member="DescribeAll" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Menus" member="Start" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:53 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Actions" member="DescribeAll" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:55 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Menus" member="End" name=":1.20" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7149 peer_label="unconfined"
Jun 27 20:20:55 wouter0100-desktop dbus[7008]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/canonical/unity/gtk/window/15" interface="org.gtk.Menus" member="End" name=":1.19" mask="receive" pid=32683 label="snap.dbeaver-ce.dbeaver-ce" peer_pid=7173 peer_label="unconfined"
```

This time it's on Ubuntu 16.04 though. 

Some more maybe useful information:
```
~$ snap run dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/wouter0100/snap/dbeaver-ce/60
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.0.202005311732]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.0.202005311732]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-06-27 20:18:32.056 - Initializing DBeaver 7.1.0
2020-06-27 20:18:32.056 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.0.202005311732
2020-06-27 20:18:32.056 - Initialize Core...
2020-06-27 20:18:32.057 - Can't find BC security provider. Use default JCE.
2020-06-27 20:18:32.057 - BouncyCastle not registered, using the default JCE provider

	Refreshing workspace.
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
Refreshing workspace contents
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
2020-06-27 20:18:32.282 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.34.202005311732]
2020-06-27 20:18:32.333 - Core initialized (277ms)
2020-06-27 20:18:32.334 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.1992" (uid=1000 pid=32683 comm="/snap/dbeaver-ce/60/usr/lib/jvm/java-8-openjdk-amd") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.58" (uid=1000 pid=7158 comm="/usr/lib/gnome-session/gnome-session-binary --sess")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
2020-06-27 20:18:32.525 - DBeaver 7.1.0.202005311732 is starting
2020-06-27 20:18:32.526 - OS: Linux 4.15.0-106-generic (amd64)
2020-06-27 20:18:32.526 - Java version: 1.8.0_252 by Private Build (64bit)
2020-06-27 20:18:32.526 - Install path: '/snap/dbeaver-ce/60/usr/share/dbeaver'
2020-06-27 20:18:32.526 - Instance path: 'file:/home/wouter0100/snap/dbeaver-ce/60/.local/share/DBeaverData/workspace6/'
2020-06-27 20:18:32.526 - Memory available 112Mb/910Mb
2020-06-27 20:18:32.533 - Starting RMI server at 43425
2020-06-27 20:18:32.570 - Run workbench
```

**Comment by skydiablo** [comment]
same problem, here is my output:

```
> Start DBeaver SSH tunnels [org.jkiss.dbeaver.net.ssh 1.0.55.202005311732]
> Start DBeaver SSH implementation (JSch) [org.jkiss.dbeaver.net.ssh.jsch 1.1.44.202005311732]
> Start Java Native Access [com.sun.jna 4.5.1.v20190425-1842]
2020-07-06 15:37:36.666 - pageant connect exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.lang.UnsatisfiedLinkError: Unable to load library 'user32': Native library (linux-x86-64/libuser32.so) not found in resource path (/snap/dbeaver-ce/60/usr/share/dbeaver//plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar)
        at com.jcraft.jsch.agentproxy.connector.PageantConnector.<init>(PageantConnector.java:65)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:116)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:809)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:155)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:198)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2020-07-06 15:37:36.673 - ssh-agent connection exception
com.jcraft.jsch.agentproxy.AgentProxyException: java.io.IOException: failed to fctrl usocket: -1
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:56)
        at com.jcraft.jsch.agentproxy.connector.SSHAgentConnector.<init>(SSHAgentConnector.java:44)
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:124)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:809)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:155)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:198)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2020-07-06 15:37:36.674 - Connection failed (mariaDB-173244b0fa2-4da95b90c163bc2b)
2020-07-06 15:37:36.674 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:814)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:155)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:198)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: Unable to initialize SSH agent
        at org.jkiss.dbeaver.model.net.ssh.SSHImplementationAbstract.initTunnel(SSHImplementationAbstract.java:131)
        at org.jkiss.dbeaver.model.net.ssh.SSHTunnelImpl.initializeHandler(SSHTunnelImpl.java:75)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:809)
        ... 14 more
```

**Comment by riednyko** [comment]
Snap never get access to dotfiles/directories and hidden files for safety.
We sent a request for permission to read such files/directories in the dbeaver snap package. While waiting for a response, to solve this problem, you can move the ssh key out of the /.ssh folder somewhere in homedir, or install the dbeaver-ce snap package using --devmode.

**Comment by Wouter0100** [comment]
> Snap never get access to dotfiles/directories and hidden files for safety.
> We sent a request for permission to read such files/directories in the dbeaver snap package. While waiting for a response, to solve this problem, you can move the ssh key out of the /.ssh folder somewhere in homedir, or install the dbeaver-ce snap package using --devmode.

I guess there is some confusion going on. I'm using the SSH agent option in DBeaver, I would think that DBeaver connects to my SSH agent in this case - and not read my `.ssh`-folders directly. Also, I've never entered my passphrase of my SSH-key in DBeaver.

Shouldn't it be requested in the snapstore to have access to `/run/user/1000/keyring/ssh`, as seen in my logs?

```
Jun 27 20:20:53 wouter0100-desktop kernel: [47671.821897] audit: type=1400 audit(1593282053.381:90): apparmor="DENIED" operation="connect" profile="snap.dbeaver-ce.dbeaver-ce" name="/run/user/1000/keyring/ssh" pid=32683 comm="ModalContext" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
```

**Comment by riednyko** [comment]
It also looks like snap denied access. Changes have already been added to the dbeaver snap package, but there will be no access without a response to our request. Try installing dbeaver using --devmode, this should help until the access issue is resolved.

**Comment by Wouter0100** [comment]
@riednyko indeed, snap (or more specifically - apparmor) denied access to the SSH agent socket located at `/run/user/1000/keyring/ssh`. 

Unfortunatly, it seems that no such interface exists in snap - and is requested [here](https://forum.snapcraft.io/t/ssh-agent-plug-request/1250/6). A workaround is also provided, to run a SSH agent in the snap, but this would require to enter the passphrase again which I'm not sure how that is possible.

**Comment by Wouter0100** [comment]
Thanks for fixing it! Hmm, in which version will the fix be shipped @riednyko? I tried running it, but unfortunatly - still the same error.

**Comment by riednyko** [comment]
It all depends on the response to the request from snap. Without this, changes with the interface added to the snap package configuration are pushed with an error, due to a lack of permissions. The workaround so far is to install a snap package using devmode.

**Comment by Wouter0100** [comment]
Thanks. Could you link the request or the corresponding PR? In that case I can follow the process over there. I unfortunately can't find it. Thanks!

**Comment by braindevices** [comment]
problem remains

**Comment by marcelofernandez** [comment]
This problem remains in 21.0.0.202102281712 dbeaver-ce version.

**Comment by ooobii** [comment]
Problem remains in 21.1.0.202106012023 - installed via. `snap`.

Error logs still confirm the same issue documented earlier is taking place. We have faith in a solution! :smile:

**Comment by lastperson** [comment]
Problem remains in 22.0.4.202205011839 installed via snap.

**Comment by Ogaday** [comment]
I'm also unable to use ssh-agent for ssh tunnel auth, even with devmode enabled.

```
$ snap info dbeaver-ce
name:      dbeaver-ce
summary:   Universal Database Manager and SQL Client
publisher: DBeaver (dbeaver-corp)
store-url: https://snapcraft.io/dbeaver-ce
contact:   dbeaver@jkiss.org
license:   unset
description: |
  Free multi-platform database tool for developers, SQL programmers, database administrators and
  analysts. Supports all popular databases: MySQL PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL
  Server, Sybase, MS Access, Teradata, Firebird, Derby, etc.
commands:
  - dbeaver-ce
snap-id:      3faKn1hkBHHE6SCJ1W3QDTPWRlumswc4
tracking:     latest/stable
refresh-date: today at 12:48 BST
channels:
  latest/stable:    22.0.5.202205220912 2022-05-24 (185) 267MB -
  latest/candidate: 22.0.4.202205011839 2022-05-21 (183) 265MB -
  latest/beta:      ↑                                          
  latest/edge:      7.0.0.202003021717  2020-03-16  (49) 135MB -
installed:          22.0.5.202205220912            (185) 267MB devmode
```

**Comment by sastorsl** [comment]
Workaround for now was to place the ssh key in `~/snap/dbeaver-ce/ssh`

**Comment by sastorsl** [comment]
There is a pretty old - 2+ years - Snap forum thread regarding the same.
https://forum.snapcraft.io/t/ssh-agent-plug-request/1250/7

Unfortunately they don't offer an Issues page on their github repo: https://github.com/snapcore/snapd
IMHO this is not an issue with dbeaver but with snap in it self, and there are some very valid security concerns with giving snap access to everything as running things as snaps really should isolate from the host system.

**Comment by Wouter0100** [comment]
@riednyko could you perhaps re-open this issue? That'd be lovely.

**Comment by vishal9565** [comment]
![image](https://user-images.githubusercontent.com/14247461/202969583-77b99472-7b85-4192-b306-f86f9350698b.png)
``` snap connect mysql-workbench-community:password-manager-service ```

``` snap connect mysql-workbench-community:ssh-keys ```
