### ISSUE TITLE
Check for updates fails with "Could not initialize class sun.net.www.protocol.https.DelegateHttpsURLConnection"

### ISSUE THREAD

**Issue by JThoennes** [dbeaver/dbeaver#8825]
#### System information: 
- Debian Linux 10
- DBeaver version 7.0.5

#### Connection specification:
- SQLite
- Do you use tunnels or proxies (SSH, SOCKS, etc)? -- NO

#### Describe the problem you're observing:
Automatic loading of drivers for SQLite failed with
```
Could not initialize class sun.net.www.protocol.https.DelegateHttpsURLConnection
```
So I loaded the driver manually which finally worked.
But now I click on "Help / Check for Updates" and the same error appears:
```
Could not initialize class sun.net.www.protocol.https.DelegateHttpsURLConnection
Could not initialize class sun.net.www.protocol.https.DelegateHttpsURLConnection
```
This worked all the time before. I am always in the same LAN using a desktop computer and I am not aware of firewall changes etc. But we removed the Oracle JDK 8 from the machine recently and now complete rely on the AdoptOpenJDK 8:
```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

#### Steps to reproduce, if exist:

1. Start DBeaver
2. Open menu "Help / Check for Updates"

###### Exception stack trace
```
java.lang.NoClassDefFoundError: Could not initialize class sun.net.www.protocol.https.DelegateHttpsURLConnection
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:100)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1002)
	at org.jkiss.dbeaver.runtime.WebUtils.openURLConnection(WebUtils.java:79)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:47)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:42)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:53)
	at org.jkiss.dbeaver.ui.app.standalone.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:102)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
###### Session details
```
eclipse.buildId=unknown
java.version=1.8.0_242
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

**Comment by uslss** [comment]
hi @JThoennes ,
sorry for the late response.
Is it still actual for you against the recent version?

**Comment by JThoennes** [comment]
Hi @uslss ,
in the meanwhile this issue had been resolved. DBeaver is working as expected.
Thanks for taking care of that, Jörg

**Comment by JThoennes** [comment]
BTW, any idea what may have caused this kind of issue?
