### ISSUE TITLE
Dbeaver freezing executing query every time I left it unused for 5 minutes or more

### ISSUE THREAD

**Issue by pedrogalv** [dbeaver/dbeaver#8872]
#### System information: 
- Ubuntu 18.04.4 LTS
- DBeaver version 7.1.0.202005311732
- No additional extensions 

#### Connection specification:
- MySQl  5.6
- Using the default provided driver: mysql-connector-java 5.1.44
- No tunnel or ssh

#### Describe the problem you're observing:
 The first time I open Dbeaver, the querying works smoothly. No problems there. But when I come back to execute the same or new query after few minutes, it freezes. I can't execute new queries and I can't cancel the task.

#### Steps to reproduce, if exist:
- Open dbeaver
- Execute something
- Left it aside for 5 min or more
- Try to run query again

from that point, I can't do anything. I need to force close it and open again

#### Include any warning/errors/backtraces from the logs
Application log:
```
at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-06-02 18:07:40.620 - org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.getTransactionIsolation(JDBCExecutionContext.java:273)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceAutoCommitHandler.updateElement(DataSourceAutoCommitHandler.java:105)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:434)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:123)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:45)
	at org.eclipse.ui.internal.commands.CommandService$1.run(CommandService.java:261)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.commands.CommandService.refreshElements(CommandService.java:265)
	at org.jkiss.dbeaver.ui.ActionUtils.lambda$0(ActionUtils.java:406)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4930)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4451)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-06-02 18:15:16.465 - Block cancel error
org.jkiss.dbeaver.DBException: Cancel error
	at org.jkiss.dbeaver.model.runtime.BlockCanceler.cancelBlock(BlockCanceler.java:38)
	at org.jkiss.dbeaver.model.runtime.AbstractJob$JobCanceler.run(AbstractJob.java:221)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.DBException: SQL Error [1094] [HY000]: Unknown thread id: 548058
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.cancelStatementExecute(JDBCDataSource.java:744)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.cancelBlock(JDBCStatementImpl.java:100)
	at org.jkiss.dbeaver.model.runtime.BlockCanceler.cancelBlock(BlockCanceler.java:36)
	... 2 more
Caused by: java.sql.SQLException: Unknown thread id: 548058
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.mysql.jdbc.StatementImpl.cancel(StatementImpl.java:415)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.cancel(JDBCStatementImpl.java:573)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.cancelStatementExecute(JDBCDataSource.java:741)
	... 4 more

```

Error in interface when trying to cancel, :
![Screenshot from 2020-06-02 18-15-22](https://user-images.githubusercontent.com/18317449/83571560-60bf0000-a4fe-11ea-8f03-97df7ed58713.png)

Tasks keep running no matter if I stop them.

![Screenshot from 2020-06-02 18-34-08](https://user-images.githubusercontent.com/18317449/83572356-cc559d00-a4ff-11ea-9576-2141875efb2e.png)

thread-dump:
[thread-dump.txt](https://github.com/dbeaver/dbeaver/files/4719789/thread-dump.txt)

**Comment by serge-rider** [comment]
I think there are two different problems:
- You connection is closed by the server after 5 minutes of inactivity. You can resolve this by settings Keep-Alive parameter in the connection settings to some reasonable value (e.g. 60 seconds). Open connection settings->Initialization->Keep Alive.
- "Argument is not valid" errors are caused by internal dbeaver rendering error, thanbks for the details. I've commited the fix.

**Comment by serge-rider** [comment]
I'm thinking about enabling Keep-Alive by default for some databases (driver) as quite a lot of people experience this issue..

**Comment by pedrogalv** [comment]
Setting keep-alive indeed solved the problem. Many thanks! You helped a lot!

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by fergus-screening** [comment]
@serge-rider https://stackdev.space/questions/jdbc-what-occurs-with-active-statements-when-an-application-closes
