### ISSUE TITLE
SQL tools to tasks configuration (PostgreSQL)

### ISSUE THREAD

**Issue by LonwoLonwo** [dbeaver/dbeaver#8893]
Turn tools into database tasks

**Comment by uslss** [comment]
NPE appears when trying to add some object to ANALYZE. Also NPE appears when trying to execute ANALYZE with more than 1 object

```
> eclipse.buildId=unknown
> java.version=11.0.5
> java.vendor=AdoptOpenJDK
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui.workbench
> Error
> Tue Jun 16 11:36:08 MSK 2020
> Unhandled event loop exception
> 
> java.lang.NullPointerException
> 	at org.jkiss.dbeaver.model.DBUtils.openUtilSession(DBUtils.java:1696)
> 	at org.jkiss.dbeaver.model.sql.task.SQLToolExecuteHandler.generateScript(SQLToolExecuteHandler.java:177)
> 	at org.jkiss.dbeaver.tasks.ui.sql.SQLToolTaskWizardPageSettings.generateScriptText(SQLToolTaskWizardPageSettings.java:262)
> 	at org.jkiss.dbeaver.tasks.ui.sql.SQLToolTaskWizardPageSettings.updateScriptPreview(SQLToolTaskWizardPageSettings.java:253)
> 	at org.jkiss.dbeaver.tasks.ui.sql.SQLToolTaskWizardPageSettings.refreshObjects(SQLToolTaskWizardPageSettings.java:230)
> 	at org.jkiss.dbeaver.tasks.ui.sql.SQLToolTaskWizardPageSettings.access$2(SQLToolTaskWizardPageSettings.java:227)
> 	at org.jkiss.dbeaver.tasks.ui.sql.SQLToolTaskWizardPageSettings$2.widgetSelected(SQLToolTaskWizardPageSettings.java:131)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.openNewTaskDialog(TaskConfigurationWizardDialog.java:208)
> 	at org.jkiss.dbeaver.ext.postgresql.tools.maintenance.PostgreToolAnalyze.execute(PostgreToolAnalyze.java:52)
> 	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.executeTool(ExecuteToolHandler.java:59)
> 	at org.jkiss.dbeaver.tasks.ui.ExecuteToolHandler.run(ExecuteToolHandler.java:51)
> 	at org.jkiss.dbeaver.ui.ActionUtils$1.run(ActionUtils.java:363)
> 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
> 
```

**Comment by uslss** [comment]
When executing task with vacuum function - progress isn't shown. Notification windows with successfully message even if function finish with fail
![2020-06-16_11h47_23](https://user-images.githubusercontent.com/31996417/84753183-5b19ed80-afc7-11ea-8a81-291c9f3e4200.gif)

**Comment by uslss** [comment]
verified
