### ISSUE TITLE
MongoDB quick filter by Timestamp

### ISSUE THREAD

**Issue by rustam-python** [dbeaver/dbeaver#8914]
#### System information: 
- Windows 10 (build 2004)
- 7.0.0 EE
- MongoDB server - Ubuntu 20.04

#### Connection specification:
- MongoDB 4.2
- org.jkiss.jdbc.mongodb.mongodbDriver
- No tunnels or proxies

#### Describe the problem you're observing:
I use PyMongo (3.10.1) to insert data to DB. Insertion with ```datetime.datetime.utcnow()```. If I try to use quick filter i have an error:
```
org.jkiss.dbeaver.model.exec.DBCException: Unsupported value: 2020 - 06 - 08
	at com.dbeaver.db.mongodb.MongoUtils.parseValueExpression(MongoUtils.java:292)
	at com.dbeaver.db.mongodb.MongoUtils.parseBinaryExpression(MongoUtils.java:213)
	at com.dbeaver.db.mongodb.MongoUtils.parseExpression(MongoUtils.java:198)
	at com.dbeaver.db.mongodb.MongoUtils.convertExpressionToObject(MongoUtils.java:169)
	at com.dbeaver.db.mongodb.MongoUtils.makeQueryFromFilter(MongoUtils.java:76)
	at com.dbeaver.db.mongodb.exec.MongoSelectStatement.executeStatement(MongoSelectStatement.java:47)
	at com.dbeaver.db.mongodb.model.MGCollection.readData(MGCollection.java:277)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3423)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
DB description:
![image](https://user-images.githubusercontent.com/41113512/84024961-75364900-a993-11ea-84bd-0dd73dd776e1.png)

Error in th GUI:
![image](https://user-images.githubusercontent.com/41113512/84025003-867f5580-a993-11ea-8e68-29432be8dad5.png)

#### Steps to reproduce, if exist:
Sorry, I don't know how to set english GUI - after I change language in `Settings - DBeaver - Language - Apply and restart` and restart DBeaver - GUI is still in Russian.
![image](https://user-images.githubusercontent.com/41113512/84025322-03aaca80-a994-11ea-9653-1e5db8e89704.png)

**Comment by serge-rider** [comment]
Fixed.
Function ISODate('...') is used to enclose date literals.

**Comment by uslss** [comment]
verified
