### ISSUE TITLE
ClickHouse exception, code: 1002 Error

### ISSUE THREAD

**Issue by PryAl** [dbeaver/dbeaver#8952]
#### System information: 
- Windows 10 Pro 1909 18363.900
- DBeaver version - 7.1.0.202005311732
- Additional extensions - none

#### Connection specification:
- Database name and version - ClickHouse v.19.11.4
- Driver name - ru.yandex.clickhouse:clickhouse-jdbc:RELEASE v.0.2.4
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - no

#### Describe the problem you're observing:
_While execute heavy query (over 50 s), I see correct response in "Result", but after 1 sec it closed and show an_

SQL Error [1002]: ClickHouse exception, code: 1002, host: unknown, port: -1; 

_With queries, that less than 10 sec i dont have a problem._
#### Steps to reproduce, if exist:
Run query
#### Include any warning/errors/backtraces from the logs

**Full log:**
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1002]: ClickHouse exception, code: 1002, host: unknown, port: -1; 
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:183)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:683)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:511)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:427)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:419)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:779)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2966)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3582)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: unknown, port: -1; 
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:32)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.checkValues(ClickHouseResultSet.java:206)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:180)
	... 13 more
Caused by: java.lang.Throwable: 
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 19 more

**Comment by uslss** [comment]
Cannot reproduce an issue. Is it still actual for you?

**Comment by uslss** [comment]
there isn't update on issue for a long time.
Ticket closed. If it is still reproducible for you - feel free to reopen it
