### ISSUE TITLE
Tasks: selecting Native client doesn't work for Dump and Restore

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9036]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.1 EA

#### Connection specification:
- Database name and version MySQL, PostgreSQL

#### Describe the problem you're observing:
Tasks: selecting Native client doesn't work for Dump and Restore

#### Steps to reproduce, if exist:

1 Create a dump task for a schema
2 Select Native client **MySQL (or PostgreSQL) Binaries** in dropdown menu
![dbeaver_EI14ERlvG4](https://user-images.githubusercontent.com/51405061/85122638-8e5eb580-b22f-11ea-997d-d3b45a2b3c09.png)
3 Run the task

Expected: 
the schema is dumped

Actual result:
1. error appears: Utility 'mysqldump.exe' not found in client home 'MySQL Binaries' (C:\Users\ksu2\AppData\Local\DBeaver\MySQL Binaries)
2. the task execution is failed

Workaround:
select MySQL (or PostgreSQL) Binaries in Tools menu for  Dump/Restore and execute it.
MySQL (or PostgreSQL) Binaries can be applied in tasks after it.
[log.txt](https://github.com/dbeaver/dbeaver/files/4803985/log.txt)

**Comment by akilovich** [comment]
Fixed the issue described above. Also fixed the issue when it was impossible to use local DB installation to perform database dump from the tools menu.

**Comment by kseniiaguzeeva** [comment]
Still can be reproduced for MySQL.
Steps:
1. Be sure a client is not downloaded yet
2. Create a dump task for MySQL
3. Select Narive client MySQL binaries
4. Make other task settings
5. Start the task

Expected: the task run is successfull
Actual result: the dump fails

Workaround:
- select MySQL Binaries in Tools menu for Dump/Restore and execute it.
- MySQL Binaries can be applied in tasks after it.

**Comment by kseniiaguzeeva** [comment]
[task_log.txt](https://github.com/dbeaver/dbeaver/files/5277455/task_log.txt)
[Uploading .log…]()

**Comment by kseniiaguzeeva** [comment]
verified. 
Note: Local client MySQL Server  4.1 is selected by default now in Connection settings, if MySQL 4.1 connection exists

**Comment by kseniiaguzeeva** [comment]
Reopened. If an incorrect local client is set in connection settings, Task dump/restore fails even if a correct client is selected in Task wizard.

**Comment by akilovich** [comment]
Everything appears to be working now.

**Comment by kseniiaguzeeva** [comment]
MySQL dump/restore work now.
PostgreSQL dump work, but PostgreSQL restore doesn't:
1. Nothing happens after pressing Start button at the end of backup task wizard.
![kQ0pFRKAYy](https://user-images.githubusercontent.com/51405061/94540408-1d2b9700-024f-11eb-8284-7360e5876abc.gif)
[.log](https://github.com/dbeaver/dbeaver/files/5297872/default.log)
[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/5297873/dbeaver-debug.log)

2. NPE appears in error log:
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.tasks.PostgreDatabaseRestoreSettings.saveSettings(PostgreDatabaseRestoreSettings.java:113)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeToolWizard.performFinish(AbstractNativeToolWizard.java:201)
	at org.jkiss.dbeaver.tasks.ui.nativetool.AbstractNativeImportExportWizard.performFinish(AbstractNativeImportExportWizard.java:71)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizardDialog.buttonPressed(TaskConfigurationWizardDialog.java:146)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerCreate.execute(TaskHandlerCreate.java:43)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:234)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

To reproduce use the same steps as described above.

**Comment by kseniiaguzeeva** [comment]
Closed. A separate ticket will be created for the issue above
