### ISSUE TITLE
Oracle: ORA-00904: "S"."OWNER": invalid identifier on opening schema

### ISSUE THREAD

**Issue by quiescer** [dbeaver/dbeaver#9070]
#### System information: 

- Operating system (distribution) and version : Ubuntu 18.04
- DBeaver version : 7.0.0 and higher
- Additional extensions : none

#### Connection specification:

- Database name and version : Oracle Database 11g Enterprise Edition Release 11.2.0.4.0
- Driver name : Oracle
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:

Error on opening a schema for the first time after connecting, and Tables view is empty until Schema closed and re-opened.

#### Steps to reproduce, if exist:

NB: I renamed my `~/.local/share/.DBeaverData` directory to confirm it wasn't workspace-related.

1. Set up Oracle connection.
1. Connect to Oracle connection.
1. Navigate to a schema in Database Navigator, then double click to open the schema.

If I close the schema and re-open it, I then see the list of tables as expected.

#### Include any warning/errors/backtraces from the logs

Nothing seems to be being logged for this error. I've included what I have in the Workspace Log anyway, but the time is 20 minutes earlier than when I last reproduced the issue.

```
Unhandled event loop exception
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.getConnectionURL(OracleDataSourceProvider.java:87)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageAbstract.saveConnectionURL(ConnectionPageAbstract.java:120)
	at org.jkiss.dbeaver.ext.oracle.ui.views.OracleConnectionExtraPage.saveSettings(OracleConnectionExtraPage.java:224)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionPageSettings.saveSettings(ConnectionPageSettings.java:166)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.saveSettings(NewConnectionWizard.java:220)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionWizard.performFinish(NewConnectionWizard.java:205)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.buttonPressed(NewConnectionDialog.java:77)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.open(NewConnectionDialog.java:100)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:118)
	at org.jkiss.dbeaver.ui.dialogs.connection.NewConnectionDialog.openNewConnectionDialog(NewConnectionDialog.java:108)
	at org.jkiss.dbeaver.ui.app.standalone.WorkbenchInitializerNewConnection.initializeWorkbenchWindow(WorkbenchInitializerNewConnection.java:33)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchWindowAdvisor.lambda$1(ApplicationWorkbenchWindowAdvisor.java:243)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4930)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4451)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by quiescer** [comment]
I am also seeing this issue on one Oracle 12.2.01.0 DB, but not on another. I wondered if it might be related to the number of tables in the schema, but it doesn't seem to be, as the one that works as 200 tables and one that doesn't has 196 tables.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (the problem was in table statistics read)
