### ISSUE TITLE
NPE appears if auto-refresh is applied

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9149]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.2 EA

#### Describe the problem you're observing:
NPE appears if auto-refresh is applied

#### Steps to reproduce, if exist:
1. Open a table (Oracle and MySQL were tested)
2. Press the arrow of Refresh btn
3. Select periodicity

Actual result: 
NPE appears, when the refresh time has come.
![Pd6wIwAbEc](https://user-images.githubusercontent.com/51405061/86449606-190bde00-bd21-11ea-9d0a-2bc61d659709.gif)

[dbeaver-debug.log](https://github.com/dbeaver/dbeaver/files/4868637/dbeaver-debug.log)
java.lang.NullPointerException
	at java.base/java.util.ArrayList.<init>(Unknown Source)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.runBlockCanceler(AbstractJob.java:152)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.canceling(AbstractJob.java:147)
	at org.eclipse.core.internal.jobs.JobManager.cancel(JobManager.java:332)
	at org.eclipse.core.internal.jobs.InternalJob.cancel(InternalJob.java:188)
	at org.eclipse.core.runtime.jobs.Job.cancel(Job.java:306)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshControl.cancelRefresh(AutoRefreshControl.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.runDataPump(ResultSetViewer.java:3555)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.refreshData(ResultSetViewer.java:3352)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.lambda$1(ResultSetViewer.java:264)
	at org.jkiss.dbeaver.ui.controls.autorefresh.AutoRefreshJob.run(AutoRefreshJob.java:42)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
verified
