### ISSUE TITLE
In 7.1.2 all the "File Open" actions trigger Exception - choose file dialog doesn't open.

### ISSUE THREAD

**Issue by wheredevel** [dbeaver/dbeaver#9181]
#### System information: 
- Operating system (distribution) and version
Ubuntu 16.04

- DBeaver version
7.1.2

- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
In 7.1.2 all the "File Open" actions trigger Exception - choose file dialog doesn't open.
Downgraded to 7.1.1 - everything works.

#### Steps to reproduce, if exist:
`File>Open File...` OR
`Driver Manager>Any Driver>Add File...`

#### Include any warning/errors/backtraces from the logs
Unhandled event loop exception:  
```
2020-07-07 08:56:09.822 - Event loop exception
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4749)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
	at org.eclipse.swt.widgets.FileDialog.openNativeChooserDialog(FileDialog.java:320)
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:304)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:85)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:73)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:239)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:218)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by uslss** [comment]
Sorry for the long response. Could you check if issue still reproducible for you against recent version?

**Comment by wheredevel** [comment]
In 7.2.0 it doesn't occur.

**Comment by IrribarraForcast** [comment]
Having this same issue when trying to Save file, open file in a postgresql server managed via google cloud sql proxy, using Ubuntu 16.04, Dbeaver version is 7.3.5.202102141704

**Comment by rokopi-byte** [comment]
Same here with version 2021.1 on Ubuntu 16.04 when I try to open file dialog to choose destination file for "export from query". Open issue [here](https://github.com/dbeaver/dbeaver/issues/12455)

**Comment by wardelll** [comment]
Same issue with version 21.3.2 on Mint 18.3 if I click 'Open File' from the file menu or if I click the file Browse button to add a key file in the ssh settings.
