### ISSUE TITLE
UI no longer able to resize windows within dbeaver

### ISSUE THREAD

**Issue by glw** [dbeaver/dbeaver#9196]
#### System information: 
- Operating system (distribution) and version
Ubuntu Xenial
- DBeaver version
7.1.2
- Additional extensions

#### Connection specification:
- Database name and version
None this is UI specific
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Since the most recent update, I can no longer resize windows within dbeaver. They may also be referred to as views within the program.

#### Steps to reproduce, if exist:
none
#### Include any warning/errors/backtraces from the logs

none

**Comment by uslss** [comment]
hi @glw ,
unfortunately cannot reproduce an issue. Could you post a video? Is there something in the logs?

**Comment by sd-f** [comment]
Same here. Resizing windows not possible. Video attached.

Happened after update from 7.1.1 via apt. Ubuntu 16.04 (Cinnamon Desktop)

GTK version error in startup log see `below`

[2020-07-10 15-53-46.mkv.zip](https://github.com/dbeaver/dbeaver/files/4903465/2020-07-10.15-53-46.mkv.zip)


stdout Log on startup:
`
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.300.v20200514-1625]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.10.800.v20200421-0950]
> Start Eclipse IDE UI [org.eclipse.ui.ide 3.17.100.v20200530-0835]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.2.202007051953]
> Start Core File Systems [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Core Resource Management [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-10 15:58:32.181 - Initializing DBeaver 7.1.2
2020-07-10 15:58:32.182 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953
2020-07-10 15:58:32.182 - Initialize Core...
2020-07-10 15:58:32.183 - Can't find BC security provider. Use default JCE.
2020-07-10 15:58:32.183 - BouncyCastle not registered, using the default JCE provider
2020-07-10 15:58:32.262 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.36.202007051953]
2020-07-10 15:58:32.281 - Core initialized (99ms)
2020-07-10 15:58:32.282 - Create display
***WARNING: GTK+ version too old (micro mismatch)
***WARNING: SWT requires GTK 3.20.0
***WARNING: Detected: 3.18.9

(DBeaver:28175): Gtk-WARNING **: Theme parsing error: <data>:7:18: '-gtk-key-bindings' is not a valid property name

(DBeaver:28175): Gtk-WARNING **: Theme parsing error: <data>:31:11: 'min-height' is not a valid property name
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.700.v20200525-1456]
2020-07-10 15:58:32.386 - DBeaver 7.1.2.202007051953 is starting
2020-07-10 15:58:32.387 - OS: Linux 4.15.7-041507-generic (amd64)
2020-07-10 15:58:32.387 - Java version: 11 by Oracle Corporation (64bit)
2020-07-10 15:58:32.388 - Install path: '/usr/share/dbeaver'
2020-07-10 15:58:32.388 - Instance path: 'file:/home/sheldor/.local/share/DBeaverData/workspace6/'
2020-07-10 15:58:32.388 - Memory available 64Mb/1024Mb
2020-07-10 15:58:32.407 - Starting RMI server at 60656
2020-07-10 15:58:32.464 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.1000.v20200514-1625]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.300.v20200422-1846]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF Common [org.eclipse.emf.common 2.19.0.v20200324-0932]
> Start EMF Ecore [org.eclipse.emf.ecore 2.22.0.v20200519-1135]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.1000.v20200517-1848]
> Start Expression Language [org.eclipse.core.expressions 3.6.800.v20200319-0911]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1200.v20200529-1321]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.900.v20200513-0930]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.1000.v20200525-0806]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.700.v20200527-0719]
2020-07-10 15:58:33.793 - Configure workbench window
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.51.202007051953]
> Start Help System Core [org.eclipse.help 3.8.800.v20200525-0755]
2020-07-10 15:58:33.897 - Create actions
2020-07-10 15:58:33.898 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2020-07-10 15:58:33.899 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2020-07-10 15:58:34.285 - Initialize workbench window
2020-07-10 15:58:34.293 - Finish initialization
2020-07-10 15:58:34.294 - No CSSEngine
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.700.v20200511-1530]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.5.0.v20200511-1530]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.26.202007051953]
2020-07-10 15:58:34.975 - Loading user drivers configuration from '/home/sheldor/.local/share/DBeaverData/workspace6/.metadata/.plugins/org.jkiss.dbeaver.core/drivers.xml'
2020-07-10 15:58:34.987 - Total database drivers: 83 (83)
> Start Default Text Editor [org.eclipse.ui.editors 3.13.200.v20200501-2307]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.200.v20200421-1954]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.36.202007051953]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.36.202007051953]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.36.202007051953]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.73.202007051953]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.42.202007051953]
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.138.202007051953]
> Start Team Support Core [org.eclipse.team.core 3.8.1000.v20200428-1255]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.1000.v20200409-1035]
`

**Comment by sd-f** [comment]
gtk update fixed the problem for me

I upgraded using the gnome3 ppa repos (sudo)

`
add-apt-repository ppa:gnome3-team/gnome3-staging
add-apt-repository ppa:gnome3-team/gnome3
apt update
apt upgrade
`

**Comment by glw** [comment]
> hi @glw ,
> unfortunately cannot reproduce an issue. Could you post a video? Is there something in the logs?

I will try to post a video later. Here is the latest log:

<details><summary>Log Contents</summary>

<p>
eclipse.buildId=unknown
java.version=1.8.0_252
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Tue Jul 07 16:26:20 CDT 2020
Unhandled event loop exception

java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4704)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Color.<init>(Color.java:128)
	at org.jkiss.dbeaver.ui.SharedTextColors.getColor(SharedTextColors.java:85)
	at org.jkiss.dbeaver.ui.UIUtils.getConnectionColorByRGB(UIUtils.java:1737)
	at org.jkiss.dbeaver.ui.UIUtils.getConnectionColor(UIUtils.java:1719)
	at org.jkiss.dbeaver.ui.navigator.database.DefaultNavigatorNodeRenderer.paintNodeDetails(DefaultNavigatorNodeRenderer.java:55)
	at org.jkiss.dbeaver.ui.navigator.database.StatisticsNavigatorNodeRenderer.paintNodeDetails(StatisticsNavigatorNodeRenderer.java:87)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.paintItem(DatabaseNavigatorTree.java:153)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorTree.lambda$1(DatabaseNavigatorTree.java:132)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:3302)
	at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:3079)
	at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1605)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1486)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4444)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.ui.dialogs.ConfirmationDialog.open(ConfirmationDialog.java:110)
	at org.jkiss.dbeaver.ui.dialogs.ConfirmationDialog.showConfirmDialogEx(ConfirmationDialog.java:189)
	at org.jkiss.dbeaver.ui.dialogs.ConfirmationDialog.showConfirmDialog(ConfirmationDialog.java:167)
	at org.jkiss.dbeaver.ui.dialogs.ConfirmationDialog.confirmActionWithParams(ConfirmationDialog.java:162)
	at org.jkiss.dbeaver.ui.dialogs.ConfirmationDialog.confirmAction(ConfirmationDialog.java:157)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.saveAndCleanup(ApplicationWorkbenchAdvisor.java:210)
	at org.jkiss.dbeaver.ui.app.standalone.ApplicationWorkbenchAdvisor.preShutdown(ApplicationWorkbenchAdvisor.java:191)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1073)
	at org.eclipse.ui.internal.Workbench.lambda$4(Workbench.java:1426)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1426)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1402)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:1744)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$3(WorkbenchWindow.java:1773)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1773)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1782)
	at org.eclipse.ui.internal.WorkbenchWindow$3.close(WorkbenchWindow.java:523)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.lambda$4(WBWRenderer.java:578)
	at org.eclipse.swt.events.ShellListener$2.shellClosed(ShellListener.java:102)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:102)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:684)
	at org.eclipse.swt.widgets.Shell.gtk_delete_event(Shell.java:1491)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2244)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6659)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5919)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1486)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4444)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

</p>

</details>

**Comment by glw** [comment]
seems to be fixed in the latest update. Thanks!
