### ISSUE TITLE
Mimer SQL: Previewing BLOB column shows "Error loading text value"

### ISSUE THREAD

**Issue by walter-weinmann** [dbeaver/dbeaver#9203]
#### System information: 
- Operating system (distribution) and version
   Windows 10, 2004
- DBeaver version
  7.1.2
- Additional extensions

#### Connection specification:
- Database name and version
  Mimer SQL 11.0.3C
- Driver name
  Mimer SQL TCP/IP driver mimjdbc3.jar
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
  Docker container

#### Describe the problem you're observing:
 Preview of all BLOB columns gives error: "Error loading text value"

#### Include any warning/errors/backtraces from the logs

!ENTRY org.eclipse.ui 4 0 2020-06-26 19:44:51.061
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.operations.OperationHistoryActionHandler.dispose(OperationHistoryActionHandler.java:221)
	at org.eclipse.ui.texteditor.AbstractTextEditor.registerUndoRedoAction(AbstractTextEditor.java:5655)
	at org.eclipse.ui.texteditor.AbstractTextEditor.dispose(AbstractTextEditor.java:4421)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.dispose(AbstractDecoratedTextEditor.java:391)
	at org.jkiss.dbeaver.ui.editors.text.BaseTextEditor.dispose(BaseTextEditor.java:104)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorBase.dispose(SQLEditorBase.java:484)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
!SESSION 2020-07-03 01:08:36.029 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2020-07-03 01:08:39.597
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by walter-weinmann** [comment]
Is there any progress on this issue?

**Comment by walter-weinmann** [comment]
Is there any plan to solve this problem?

Still: **IO error while copying stream**

**Comment by uslss** [comment]
hi @walter-weinmann ,
sorry for the late response.
Unfortunately, we've got no env to try to reproduce an issue.
Is it still actual?

**Comment by walter-weinmann** [comment]
In the meantime, the option to view BLOB data has unfortunately been removed.
