### ISSUE TITLE
Problem while dumping the database

### ISSUE THREAD

**Issue by BlueSenpai** [dbeaver/dbeaver#9215]
I am using Linux Ubuntu 20 , i installed DBeaver and connected to the database successfully , i was using phpmyadmin with LAMPP stack , developing a laravel app , now i have the database but when i try to dump it i get this issue:

This is the string in the Export progress log:

/opt/lampp/bin/mysqldump --routines --add-drop-table --disable-keys --extended-insert --host=localhost --port=3306 -u root laravelTest
Task 'MySQL dump' started at Thu Jul 09 18:22:22 TRT 2020
Warning: World-writable config file '/opt/lampp/etc/my.cnf' is ignored
mysqldump: Couldn't execute 'SHOW FUNCTION STATUS WHERE Db = 'laravelTest'': Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100108, now running 100411. Please use mysql_upgrade to fix this error (1558)
Task 'MySQL dump' finished at Thu Jul 09 18:22:22 TRT 2020
2020-07-09 18:22:22.278 - IO error: Process failed (exit code = 2). See error log.
2020-07-09 18:22:22.280 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:182)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:237)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

This is the error:

Error executing process
  Process failed (exit code = 2). See error log.

If anyone can help me with this i will be grateful , maybe its permission issue? or the phpmyadmin way of backup and restore is not compatible with Dbeaver? thank you

**Comment by BlueSenpai** [comment]
I found the solution , I ran `mysql_upgrade` in the terminal and then tried exporting the database again and it worked fine , importing also works fine.
