### ISSUE TITLE
Workspace not recognized after upgrading to 7.1.2

### ISSUE THREAD

**Issue by razor1973** [dbeaver/dbeaver#9253]
After upgrading to 7.1.2, DBeaver no longer recognizes my workspace. My preferences are gone, my db connections are gone, my open scripts are gone. I checked the folder where these should be saved (C:\Users\xxxxxx\AppData\Roaming\DBeaverData\workspace6\General\) and everything seems to be there. Scripts are in the \Scripts subfolder and connections are in \.dbeaver. However, DBeaver doesn't seem to "see" them. Except it does. I tried File > Switch Workspace > Other and the workspace there is the exact folder I mentioned above. In fact, if I check any of the 3 options in the "Copy Settings" section below, DBeaver warns me that the target workspace already exists and files will be overwritten. So if it knows workspace6 is there, why won't it show me the connections, scripts, etc.?

I tried upgrading to the early access 7.1.3 version with no success. No change.

Is this a known bug?

**Comment by uslss** [comment]
Hi @razor1973 , what version do you use before upgrading?
Is there something in the log?

**Comment by razor1973** [comment]
I was on either 7.1.0 or 7.1.1, don't recall now. This is the end of my log file, which I assume is C:\Users\rgutier1\AppData\Roaming\DBeaverData\workspace6\.metadata\.log (please let me know otherswise):\. I see a mention to the workspace folder:

`!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-07-14 08:54:39.629
!MESSAGE Unable to load resource file:/C:/Users/rgutier1/AppData/Roaming/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
!STACK 0
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.xml.sax.SAXParseExceptionpublicId: file:/C:/Users/rgutier1/AppData/Roaming/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi; systemId: file:/C:/Users/rgutier1/AppData/Roaming/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi; lineNumber: 1; columnNumber: 1; Premature end of file.
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.getResource(ResourceHandler.java:287)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadResource(ResourceHandler.java:263)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:169)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:384)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:579)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
Caused by: org.xml.sax.SAXParseExceptionpublicId: file:/C:/Users/rgutier1/AppData/Roaming/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi; systemId: file:/C:/Users/rgutier1/AppData/Roaming/DBeaverData/workspace6/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 23 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-07-14 08:54:39.636
!MESSAGE The persisted application model has no top-level window. Reinitializing with the default application model.
!STACK 0
java.lang.Exception
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:174)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:384)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:579)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
`

**Comment by uslss** [comment]
Could you try to reset workspace? https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

**Comment by razor1973** [comment]
> Could you try to reset workspace? https://github.com/dbeaver/dbeaver/wiki/Reset-workspace

I closed DBeaver, erased the workbench.xmi file, reopened DBeaver... Nothing. Connections and scripts aren't there.
I then closed DBeaver again, dropped the entire .metadata folder, reopened DBeaver... Nothing either. Closed DBeaver again.
I want to clarify files .data-sources.json, data-sources.json, credentials-config.json and project-metadata.json are still under C:\Users\rgutier1\AppData\Roaming\DBeaverData\workspace6\General\\.dbeaver. It's just DBeaver doesn't seem to be using them.
I then went to get the log file (.log) in the same location where I found it before (the .metadata folder) and it isn't there. The only file there is dbeaver-debug.log. These are its contents in case it helps (I don't believe it does).

```
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.600.v20200124-0005]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.52.202007102026]
> Start Help System Core [org.eclipse.help 3.8.700.v20191212-1123]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.700.v20191211-1713]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.600.v20200221-0754]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.700.v20191213-1911]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.600.v20200110-2121]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.700.v20200110-2121]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.27.202007102026]
> Start Default Text Editor [org.eclipse.ui.editors 3.13.100.v20200130-1507]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.100.v20200212-1049]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.37.202007102026]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.37.202007102026]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.37.202007102026]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.800.v20200213-1530]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.74.202007102026]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.43.202007102026]
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.139.202007102026]
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
```

**Comment by razor1973** [comment]
Any news? Thanks.

**Comment by kyleflan** [comment]
I had the same issue on both Windows 10 and Ubuntu 18.04. The only solution for me was to downgrade to 7.0.5, which was the version I was on prior to upgrading to 7.1.2.

**Comment by uslss** [comment]
could you check if issue is reproducible against 7.1.3?
thanks in advance for response

**Comment by razor1973** [comment]
> I had the same issue on both Windows 10 and Ubuntu 18.04. The only solution for me was to downgrade to 7.0.5, which was the version I was on prior to upgrading to 7.1.2.
I will be honest and admit I may have upgraded to 7.1.2 directly from 7.0.5 like you. If I had to bet, I'd say I was on 7.1.1, but now, I'm not 100% sure.

**Comment by razor1973** [comment]
> I had the same issue on both Windows 10 and Ubuntu 18.04. The only solution for me was to downgrade to 7.0.5, which was the version I was on prior to upgrading to 7.1.2.

I will be honest and admit I may have upgraded to 7.1.2 directly from 7.0.5 like you. If I had to bet, I'd say I was on 7.1.1, but now, I'm not 100% sure.

**Comment by razor1973** [comment]
> could you check if issue is reproducible against 7.1.3?
> thanks in advance for response

Yes, I mentioned that in my original post. It's an issue in 7.1.3 too. But keep in mind I upgraded to 7.1.3 after having 7.1.2 and this issue. I upgraded to 7.1.3, made sure the files are still there and DBeaver still doesn't see/use them.

**Comment by razor1973** [comment]
Any feedback? This is still tagged as "waiting for response" days later, so not sure this was reviewed. Thanks in advance.

**Comment by daoluong** [comment]
if you install it from windows store. location of workspace is "C:\Users\{{user}}\AppData\Local\Packages\DBeaverCorp.DBeaverCE_{{random}}\LocalCache\Roaming\DBeaverData"

**Comment by uslss** [comment]
cannot reproduce an issue for now.
If it is still actual for you - feel free to reopen it with additional info.
