### ISSUE TITLE
Export to sqlite error

### ISSUE THREAD

**Issue by sprintel** [dbeaver/dbeaver#927]
When I try to export a table from any source (mysql, sqlite, or flat file) to sqlite by creating a new table, I keep getting this error: "Can't start data transfer. Reason: org.jkiss.dbeaver.model.exec.DBCException: New table xxx not found in container "xxx.sqlite""

![capture](https://cloud.githubusercontent.com/assets/14018760/19906551/2a2645fc-a049-11e6-9d83-b9e83f9c2020.JPG)

However, that table is actually created successfully in sqlite. If I restart my exporting process and I select the new existing table as the target, the data will be transferred successfully.

I've tried this on different machines and they all produce the same error.

**Comment by serge-rider** [comment]
Hmm. I can't reproduce (export sees just created tables).
I see that your table contains space in it's name. Maybe it is a problem (try to use simple table name) - although I can export in table with any name.
Also pleas send full stacktrace of that error (you can get it in Error Log view).

**Comment by sprintel** [comment]
Hi serge -

Here are my steps:
1. Right click on the table that I want to export and select "Export Data".
2.  A window will pop up. Select Database.
3. Click Next and click Next.
4. Target Container: I select the sqlite database file.
5. I click the "Create New" button.
6. Click Next, click Next, and click Finish.
7. An error message will pop up (but the table is actually created).

If I restart the process and change step 5 to "Existing Table" (since the table is already created), it will transfer the data to the target table without a glitch.

Here is the error log:
2016-11-02 13:46:28.485 - org.jkiss.dbeaver.model.exec.DBCException: New table KSMismatch not found in container "SQLite - Test.sqlite"
org.jkiss.dbeaver.model.exec.DBCException: New table KSMismatch not found in container "SQLite - Test.sqlite"
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:291)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferWizard$1.run(DataTransferWizard.java:163)
	at org.jkiss.dbeaver.core.DBeaverUI$1.run(DBeaverUI.java:99)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by serge-rider** [comment]
I believe this was fixed a long time ago. Please reopen if it is still happens.

**Comment by mdahlman** [comment]
I continue to get exactly this error with PostgreSQL using the current DBeaver v6.1.4.

In GUI I see:
```
Can't start data transfer

Reason:
New table allowed_values not found in container dev5_mrc_stg
```

In PDE Log I see:
```
org.jkiss.dbeaver.model.exec.DBCException: New table allowed_values not found in container dev5_mrc_stg
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:372)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferWizard.lambda$0(DataTransferWizard.java:164)
	at org.jkiss.dbeaver.ui.UIUtils.lambda$8(UIUtils.java:1532)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Perhaps it's a regression?
Would you prefer that I open a new issue for it, or is commenting here sufficient?
