### ISSUE TITLE
Data Editor: Error appears when column format is changed to Geometry

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#9279]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.1.3 EA

#### Describe the problem you're observing:
Error appears when column format is changed to Geometry

#### Steps to reproduce, if exist:

1. Open Error log
2. Open a table with a string column
3. Select View/Format>Set format>Geometry in context menu of a string type column

Actual result:
Error appears on Error log:
ipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1046)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:760)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onMouseDown(LightGrid.java:3149)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.access$2(LightGrid.java:2955)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid$1.mouseDown(LightGrid.java:2849)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
Caused by: org.locationtech.jts.io.ParseException: Expected word but found End-of-Stream (line 1)
	at org.locationtech.jts.io.WKTReader.parseErrorWithLine(WKTReader.java:733)
	at org.locationtech.jts.io.WKTReader.parseErrorExpected(WKTReader.java:721)
	at org.locationtech.jts.io.WKTReader.getNextWord(WKTReader.java:702)
	at org.locationtech.jts.io.WKTReader.lookAheadWord(WKTReader.java:642)
	at org.locationtech.jts.io.WKTReader.getNextOrdinateFlags(WKTReader.java:615)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:792)
	at org.locationtech.jts.io.WKTReader.readGeometryTaggedText(WKTReader.java:785)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:233)
	at org.locationtech.jts.io.WKTReader.read(WKTReader.java:214)
	at org.jkiss.dbeaver.data.gis.handlers.GeometryConverter.fromWKT(GeometryConverter.java:45)
	... 48 more

**Comment by serge-rider** [comment]
What database is it?
What column data type is?
Where can we reproduce this?

**Comment by kseniiaguzeeva** [comment]
- It can be reproduced is PostgreSQL and MySQL (and not actual for Oracle)
- Column of Varchar, text type
- e.g. MySQL Kseniia.Export can be used
- 1 step is added:
1. Open Error log
2. Open a table with a string column
3. Select View/Format>Set format>Geometry in context menu of a string type column
4. Refresh the  table

**Comment by kseniiaguzeeva** [comment]
Nothing appears in Error log now.
