### ISSUE TITLE
java.net.UnknownHostException when trying to use command-line

### ISSUE THREAD

**Issue by dtseiler** [dbeaver/dbeaver#9305]
#### System information: 
- Operating system (distribution) and version: MacOS 10.15.5 & 10.15.6
- DBeaver version: 7.1.2.202007051953 & 7.1.3.202007192031
- Additional extensions: None

#### Connection specification:
- Database name and version: PostgreSQL 12.3
- Driver name: postgresql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Trying to use dbeaver to connect to a host/database purely by command-line properties (`-con`). I try specifying host/port/etc in a piped string as well as via jdbc url but in either case I get this error:

```
2020-07-17 15:03:25.960 - Execution context opened (Ext: PostgreSQL; Main <postgres>; 0)
2020-07-17 15:03:25.962 - Initiate connection to PostgreSQL database [postgres@null] for Main <postgres>
2020-07-17 15:03:25.994 - Connection failed (postgres-jdbc-1735e5fd315-1135d16e3f28d2ec)
2020-07-17 15:03:25.994 - org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:221)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:325)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:193)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:126)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:821)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	... 14 more
Caused by: java.net.UnknownHostException: {host}
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.<init>(PGStream.java:70)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It looks like it thinks I'm trying to connect to a host named "`{host}`" instead of the actual `host` value I'm passing in?

I don't see any examples so perhaps I'm calling it wrong?

#### Steps to reproduce, if exist:

```
$ /Applications/DBeaver.app/Contents/MacOS/dbeaver -con driver=postgresql|host=<FQDN_OF_MY_DB_SERVER>|port=5432|database=<MY_DB_NAME>|user=<USER>|create=false|connect=true
```

also tried:

```
$ /Applications/DBeaver.app/Contents/MacOS/dbeaver -con driver=postgresql|url="jdbc:postgresql://<FQDN_OF_MY_DB_SERVER>:5432/<MY_DB_NAME>"
```

**Comment by dtseiler** [comment]
Same results with Version 7.1.3.202007192031

**Comment by dtseiler** [comment]
I've got it working, I needed to enclose the entire con string in quotes. Otherwise zsh was using the pipes to split it into separate commands.

eg

```
$ /Applications/DBeaver.app/Contents/MacOS/dbeaver -con "driver=postgresql|host=<FQDN_OF_MY_DB_SERVER>|port=5432|database=<MY_DB_NAME>|user=<USER>|create=false|connect=true"
```

**Comment by dtseiler** [comment]
Closing this as it was PEBKAC
