### ISSUE TITLE
DBeaver snap does not start on Ubuntu 20.04

### ISSUE THREAD

**Issue by meddario** [dbeaver/dbeaver#9307]
#### System information: 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
Snap version

```
$ snap --version
snap    2.45.2
snapd   2.45.2
series  16
ubuntu  20.04
kernel  5.4.0-40-generic
```

- DBeaver version `7.1.2.202007051953`
- Additional extensions

#### Connection specification:

Doesn't apply (DBeaver doesn't start).

#### Describe the problem you're observing:

Running DBeaver shows the loading screen but then the application doesn't start.

#### Steps to reproduce, if exist:

The problem can be reproduced just running DBeaver, using the launcher or `snap run dbeaver-ce` from the command line.

#### Include any warning/errors/backtraces from the logs

```
$ snap run dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/dbeaver-ce/61
Warning: NLS unused message: ViewsPreference_currentThemeDescription in: org.eclipse.ui.internal.messages
Warning: NLS unused message: ViewsPreference_enableAnimations in: org.eclipse.ui.internal.messages
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.300.v20200514-1625]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Meccanismo dei lavori di Eclipse [org.eclipse.core.jobs 3.10.800.v20200421-0950]
> Start UI IDE Eclipse [org.eclipse.ui.ide 3.17.100.v20200530-0835]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.2.202007051953]
> Start File system di base [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Gestione risorse principali [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-18 12:05:03.190 - Initializing DBeaver 7.1.2
2020-07-18 12:05:03.191 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.2.202007051953
2020-07-18 12:05:03.192 - Initialize Core...
2020-07-18 12:05:03.193 - Can't find BC security provider. Use default JCE.
2020-07-18 12:05:03.193 - BouncyCastle not registered, using the default JCE provider
2020-07-18 12:05:03.334 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.36.202007051953]
2020-07-18 12:05:03.457 - Core initialized (265ms)
2020-07-18 12:05:03.460 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.164" (uid=1000 pid=15464 comm="/snap/dbeaver-ce/61/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.49" (uid=1000pid=2115 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.700.v20200525-1456]
2020-07-18 12:05:03.688 - DBeaver 7.1.2.202007051953 is starting
2020-07-18 12:05:03.691 - OS: Linux 5.4.0-40-generic (amd64)
2020-07-18 12:05:03.691 - Java version: 1.8.0_252 by Private Build (64bit)
2020-07-18 12:05:03.691 - Install path: '/snap/dbeaver-ce/61/usr/share/dbeaver'
2020-07-18 12:05:03.691 - Instance path: 'file:/home/user/snap/dbeaver-ce/61/.local/share/DBeaverData/workspace6/'
2020-07-18 12:05:03.692 - Memory available 82Mb/910Mb
2020-07-18 12:05:03.704 - Starting RMI server at 43495
2020-07-18 12:05:03.741 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.1000.v20200514-1625]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.300.v20200422-1846]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start ICU4J Base [com.ibm.icu.base 58.2.0.v20170418-1837]
> Start EMF comune [org.eclipse.emf.common 2.19.0.v20200324-0932]
> Start EMF Ecore [org.eclipse.emf.ecore 2.22.0.v20200519-1135]
> Start EMF XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.1000.v20200517-1848]
> Start Linguaggio delle espressioni [org.eclipse.core.expressions 3.6.800.v20200319-0911]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1200.v20200529-1321]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.900.v20200513-0930]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.16.0.v20200507-0938]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.1000.v20200525-0806]
2020-07-18 12:05:05.755 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5795)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2793)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-07-18 12:05:05.779 - DBeaver is stopping
2020-07-18 12:05:05.783 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.51.202007051953]
2020-07-18 12:05:05.869 - DBeaver shutdown completed
2020-07-18 12:05:06.010 - Shutdown Core...
2020-07-18 12:05:06.358 - Total database drivers: 83 (83)
2020-07-18 12:05:06.551 - Shutdown completed in 541ms
```

**Comment by uslss** [comment]
cannot reproduce it. Is it still actual against 7.1.3 version?

**Comment by meddario** [comment]
Hi, just tried with 7.1.3

```
$ snap run dbeaver-ce
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/dbeaver-ce/65
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031]
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Meccanismo dei lavori di Eclipse [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start UI IDE Eclipse [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.3.202007192031]
> Start Gestione risorse principali [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-07-29 00:38:23.759 - Initializing DBeaver 7.1.3
2020-07-29 00:38:23.762 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.3.202007192031
2020-07-29 00:38:23.762 - Initialize Core...
2020-07-29 00:38:23.763 - Can't find BC security provider. Use default JCE.
2020-07-29 00:38:23.764 - BouncyCastle not registered, using the default JCE provider

	Aggiornamento dello spazio di lavoro.
> Start Supporto principale per i team [org.eclipse.team.core 3.8.900.v20200211-0946]
Refreshing workspace contents
> Start File system di base [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
2020-07-29 00:38:24.082 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.37.202007192031]
2020-07-29 00:38:24.181 - Core initialized (419ms)
2020-07-29 00:38:24.183 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.108" (uid=1000 pid=5060 comm="/snap/dbeaver-ce/65/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.44" (uid=1000 pid=2224 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
2020-07-29 00:38:24.440 - DBeaver 7.1.3.202007192031 is starting
2020-07-29 00:38:24.442 - OS: Linux 5.4.0-42-generic (amd64)
2020-07-29 00:38:24.442 - Java version: 1.8.0_252 by Private Build (64bit)
2020-07-29 00:38:24.442 - Install path: '/snap/dbeaver-ce/65/usr/share/dbeaver'
2020-07-29 00:38:24.442 - Instance path: 'file:/home/user/snap/dbeaver-ce/65/.local/share/DBeaverData/workspace6/'
2020-07-29 00:38:24.443 - Memory available 112Mb/910Mb
2020-07-29 00:38:24.458 - Starting RMI server at 25171
2020-07-29 00:38:24.533 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF comune [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Linguaggio delle espressioni [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
2020-07-29 00:38:26.607 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5797)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2811)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-07-29 00:38:26.631 - DBeaver is stopping
2020-07-29 00:38:26.634 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.52.202007192031]
2020-07-29 00:38:26.785 - DBeaver shutdown completed
2020-07-29 00:38:26.887 - Shutdown Core...
2020-07-29 00:38:27.099 - Total database drivers: 84 (84)
2020-07-29 00:38:27.322 - Shutdown completed in 435ms
```

**Comment by meddario** [comment]
Hi @uslss, is there some specific test I can do / additional information that I should provide to help debug this? Thanks!

**Comment by meddario** [comment]
Hi, tested again with 7.1.4, same result:
```
Picked up _JAVA_OPTIONS: -Duser.home=/home/user/snap/dbeaver-ce/75
> Start Eclipse e4 Workbench [org.eclipse.e4.ui.workbench 1.11.200.v20200205-1503]
> Start DBeaver Standalone [org.jkiss.dbeaver.ui.app.standalone 7.1.4.202008021649]
> Start Eclipse Workbench Model [org.eclipse.e4.ui.model.workbench 2.1.700.v20200113-1422]
> Start Meccanismo dei lavori di Eclipse [org.eclipse.core.jobs 3.10.700.v20200106-1020]
> Start UI IDE Eclipse [org.eclipse.ui.ide 3.17.0.v20200217-1511]
> Start DBeaver Core Plug-in [org.jkiss.dbeaver.core 7.1.4.202008021649]
> Start File system di base [org.eclipse.core.filesystem 1.7.700.v20200110-1734]
> Start Gestione risorse principali [org.eclipse.core.resources 3.13.700.v20200209-1624]
2020-08-20 00:03:44.094 - Initializing DBeaver 7.1.4
2020-08-20 00:03:44.095 - Host plugin: org.jkiss.dbeaver.ui.app.standalone 7.1.4.202008021649
2020-08-20 00:03:44.096 - Initialize Core...
2020-08-20 00:03:44.097 - Can't find BC security provider. Use default JCE.
2020-08-20 00:03:44.097 - BouncyCastle not registered, using the default JCE provider
2020-08-20 00:03:44.306 - Initialize base platform...
> Start DBeaver UI Navigator [org.jkiss.dbeaver.ui.navigator 1.0.38.202008021649]
2020-08-20 00:03:44.403 - Core initialized (307ms)
2020-08-20 00:03:44.405 - Create display
SWT SessionManagerDBus: Failed to RegisterClient: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.158" (uid=1000 pid=17686 comm="/snap/dbeaver-ce/75/usr/lib/jvm/java-8-openjdk-amd" label="snap.dbeaver-ce.dbeaver-ce (enforce)") interface="org.gnome.SessionManager" member="RegisterClient" error name="(unset)" requested_reply="0" destination=":1.38" (uid=1000pid=2276 comm="/usr/libexec/gnome-session-binary --systemd-servic" label="unconfined")
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
2020-08-20 00:03:44.656 - DBeaver 7.1.4.202008021649 is starting
2020-08-20 00:03:44.658 - OS: Linux 5.4.0-42-generic (amd64)
2020-08-20 00:03:44.658 - Java version: 1.8.0_265 by Private Build (64bit)
2020-08-20 00:03:44.658 - Install path: '/snap/dbeaver-ce/75/usr/share/dbeaver'
2020-08-20 00:03:44.659 - Instance path: 'file:/home/user/snap/dbeaver-ce/75/.local/share/DBeaverData/workspace6/'
2020-08-20 00:03:44.659 - Memory available 114Mb/910Mb
2020-08-20 00:03:44.666 - Starting RMI server at 43624
2020-08-20 00:03:44.737 - Run workbench
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF comune [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XMI [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Linguaggio delle espressioni [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
2020-08-20 00:03:46.889 - Event loop exception
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.graphics.Font.getFontData(Font.java:192)
	at org.eclipse.swt.graphics.Device.getFontList(Device.java:454)
	at org.eclipse.jface.resource.FontRegistry.filterData(FontRegistry.java:464)
	at org.eclipse.jface.resource.FontRegistry.createFont(FontRegistry.java:498)
	at org.eclipse.jface.resource.FontRegistry.defaultFontRecord(FontRegistry.java:569)
	at org.eclipse.jface.resource.FontRegistry.defaultFontData(FontRegistry.java:580)
	at org.eclipse.jface.resource.FontRegistry.getFontData(FontRegistry.java:596)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installFont(ThemeElementHelper.java:123)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:68)
	at org.eclipse.ui.internal.Workbench$23.runWithException(Workbench.java:1793)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:36)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5797)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:94)
	at org.eclipse.ui.internal.Workbench.initializeFonts(Workbench.java:1787)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1641)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2811)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:646)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:233)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
2020-08-20 00:03:46.913 - DBeaver is stopping
2020-08-20 00:03:46.916 - Stop RMI server
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.53.202008021649]
2020-08-20 00:03:47.062 - DBeaver shutdown completed
2020-08-20 00:03:47.182 - Shutdown Core...
2020-08-20 00:03:47.379 - Total database drivers: 84 (84)
2020-08-20 00:03:47.626 - Shutdown completed in 444ms
```

**Comment by meddario** [comment]
Hi, 

besides the tests reported above, on the pc where I was experiencing the problem (with Ubuntu 20.04) I switched to the .deb version, which always worked perfectly. Today I tried to install the DBeaver snap on another (older) pc, this time running:

```
snap    2.46.1+18.04
snapd   2.46.1+18.04
series  16
ubuntu  18.04
kernel  4.15.0-118-generic
```

I experienced the same problem, so I remembered of another issue that happened to me recently:
https://github.com/snapcrafters/gimp/issues/122#issuecomment-691476359

Applying the same workaround fixed the problem on this pc. No more errors and square fonts.

For the record:
```sh
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

I'll let you know if the same works also on the 20.04 pc.

**Comment by meddario** [comment]
Hi,

i can confirm that the workaround above fixes the problem in Ubuntu 20.04 too.

**Comment by hamraa** [comment]
the workaround also work for me

**Comment by illetschko** [comment]
Yes, clearing the font cache worked for me too.
Thanks for the hint....
(Ubuntu 20.04)

**Comment by dom3k** [comment]
If above workaround does not work, try remove font cache from snap folder:
/home/USER/snap/dbeaver-ce/common/.cache/fontconfig

It is works for Manjaro installation.

**Comment by tasuki** [comment]
What the hell... thank you a whole bunch! I never would've figured this by myself!

**Comment by thalesvon** [comment]
> Hi,
> 
> besides the tests reported above, on the pc where I was experiencing the problem (with Ubuntu 20.04) I switched to the .deb version, which always worked perfectly.
> 
> Today I tried to install the DBeaver snap on another (older) pc, this time running:
> 
> ```
> snap    2.46.1+18.04
> snapd   2.46.1+18.04
> series  16
> ubuntu  18.04
> kernel  4.15.0-118-generic
> ```
> 
> I experienced the same problem, so I remembered of another issue that happened to me recently:
> [snapcrafters/gimp#122 (comment)](https://github.com/snapcrafters/gimp/issues/122#issuecomment-691476359)
> 
> Applying the same workaround fixed the problem on this pc. No more errors and square fonts.
> 
> For the record:
> 
> ```shell
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> sudo fc-cache -r
> ```
> 
> I'll let you know if the same works also on the 20.04 pc.

This also worked for me! 
Turns out I messed things up when installing new fonts.

**Comment by conrad96** [comment]
snap    2.51.4
snapd   2.51.4
series  16
ubuntu  20.04
kernel  5.11.0-27-generic

It hasn't worked for me. do i need to reinstall at this point ?

**Comment by Thenujan-0** [comment]
worked for me in manjaro

**Comment by Mikajel** [comment]
@meddario Amazing catch, I changed DBeaver to use JetBrains font, looks like it could not handle it for more than one session...

**Comment by ScriptWithSuraj** [comment]
sudo snap refresh --edge dbeaver-ce use this command to fix the issue.
