### ISSUE TITLE
Can't parse escape characters in .pgpass

### ISSUE THREAD

**Issue by acere** [dbeaver/dbeaver#9453]
#### System information: 
- Operating system (distribution) and version: macOS 10.15.6
- DBeaver version CE 7.1.4.202008021649
- Additional extensions

#### Connection specification:
- Database name and version Redshift
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
I'm using .pgpass for authentication, but I can't use any user name with special character when using DBeaver, even when social characters are escaped according to [postgresSQL documentation](https://www.postgresql.org/docs/current/libpq-pgpass.html).

This is particularly important when using IAM authentication because the user name is in the form `IAMA:<username>:<group>`

#### Steps to reproduce, if exist:

1. create user in Postgres DB with a username containing a `\` or `:`.   
E.g.: `test:user` 
1. create entry in .pgpass file to authenticate the connection to the DB with the new user.   
E.g.: `localhost:5432:dbname:test\:user:<password>`
1. configure a connection in DBeaver referencing the user entry in .pgpass
1. test connection

#### Include any warning/errors/backtraces from the logs

```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-08-05 10:32:16.726
!MESSAGE Couldn't get password from PGPASS file
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-08-05 10:32:16.726
!MESSAGE Couldn't get password from PGPASS file
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2020-08-05 10:32:16.726
!MESSAGE No matches in pgpass
!STACK 0
org.jkiss.dbeaver.DBException: No matches in pgpass
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadPasswordFromPgPass(AuthModelPgPass.java:121)
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadCredentials(AuthModelPgPass.java:53)
	at org.jkiss.dbeaver.ext.postgresql.model.AuthModelPgPass.loadCredentials(AuthModelPgPass.java:1)
	at org.jkiss.dbeaver.model.impl.auth.AuthModelDatabaseNative.loadCredentials(AuthModelDatabaseNative.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:167)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:193)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:126)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:105)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified
