### ISSUE TITLE
Unknown table 'CHECK_CONSTRAINTS' in information_schema (issue #9371) not fixed : still got error with 7.1.4

### ISSUE THREAD

**Issue by RastaTaz** [dbeaver/dbeaver#9534]
#### System information: 
- Operating system (distribution) and version : Linux - self-made, ubuntu based 18.04 LTS but also 20.04 (not LTS).
- DBeaver version : 7.1.4
- Additional extensions : -

#### Connection specification:
- Database name and version : MariaDB 10.2
- Driver name : MariaDB-java-client 2.6.2 (and previous versions tried as well)
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
Yes : SSH tunnel

#### Describe the problem you're observing:
Can't edit values when viewing tables (no error or any message of any kind : very frustrating !!) + I can still reproduce issue #9371 although it is closed....

#### Steps to reproduce, if exist:
See #9371

#### Include any warning/errors/backtraces from the logs

`
2020-08-14 12:13:25.415 - Unknown table 'CHECK_CONSTRAINTS' in information_schema
java.sql.SQLException: Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:285)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:115)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getAllObjects(JDBCCompositeCache.java:109)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.cacheStructure(MySQLCatalog.java:388)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.lambda$0(ERDEditorEmbedded.java:245)
        at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.collectDatabaseTables(ERDEditorEmbedded.java:243)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:206)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:189)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:164)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2020-08-14 12:15:23.083 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:285)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:115)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getConstraints(MySQLTable.java:234)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.loadForeignKeys(MySQLTable.java:453)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getAssociations(MySQLTable.java:280)
        at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllAssociations(DBVUtils.java:309)
        at org.jkiss.dbeaver.ext.erd.model.ERDDecoratorDefault.fillEntityFromObject(ERDDecoratorDefault.java:152)
        at org.jkiss.dbeaver.ext.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:66)
        at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillEntities(EntityDiagram.java:343)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:204)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:189)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:164)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        ... 17 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
        ... 20 more
Caused by: java.sql.SQLException: Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
        ... 21 more
2020-08-14 12:15:23.115 - Error reading table identifier
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:285)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:115)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getConstraints(MySQLTable.java:234)
        at org.jkiss.dbeaver.ext.erd.model.ERDUtils.getBestTableIdentifier(ERDUtils.java:83)
        at org.jkiss.dbeaver.ext.erd.model.ERDDecoratorDefault.fillEntityFromObject(ERDDecoratorDefault.java:168)
        at org.jkiss.dbeaver.ext.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:66)
        at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillEntities(EntityDiagram.java:343)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:204)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:189)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:164)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLSyntaxErrorException: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
        ... 15 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
        ... 18 more
Caused by: java.sql.SQLException: Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
        ... 19 more
2020-08-14 12:15:23.169 - org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [1109] [42S02]: (conn=85) Unknown table 'CHECK_CONSTRAINTS' in information_schema
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:208)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:285)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:115)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getConstraints(MySQLTable.java:234)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.loadForeignKeys(MySQLTable.java:453)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLTable.getAssociations(MySQLTable.java:280)
        at org.jkiss.dbeaver.model.virtual.DBVUtils.getAllAssociations(DBVUtils.java:309)
        at org.jkiss.dbeaver.ext.erd.model.ERDDecoratorDefault.fillEntityFromObject(ERDDecoratorDefault.java:152)
        at org.jkiss.dbeaver.ext.erd.model.ERDUtils.makeEntityFromObject(ERDUtils.java:66)
        at org.jkiss.dbeaver.ext.erd.model.EntityDiagram.fillEntities(EntityDiagram.java:343)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:204)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:189)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:164)
        at org.jkiss.dbeaver.ext.erd.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

Throwing java exceptions goes for while : I can send logfile if it is usefull, but it looks like devs already spotted the issue, just didn't fully corrected it :)

I'm opening this as the existing one seems to be closed already and I don't know if it is to be re-opened or not (I left a comment there as well), and your "bug opening rules" don't say about this situation (existing bug but in closed status).

+ Thanks for checking the issue.

**Comment by LonwoLonwo** [comment]
@RastaTaz probably fixed in other tiket #9450 in version 7.1.5
version 7.1.5 you can find here https://dbeaver.io/files/ea/

**Comment by RastaTaz** [comment]
@LonwoLonwo : thanks for fast answer !

Indeed, it seems 7.1.5 don't have the issue :
- I can't reproduce issue when viewing ER diagram
- I can now edit values again when viewing tables

=> It is fixed to me (so I close current case), but maybe initial bug should have a link to 7.1.5 instead of 7.1.4 as it doesn't actually fix the issue.

Thanks again !
