### ISSUE TITLE
PostgreSql "Show all databases" issue after 7.1.5.202008170457 upgrade

### ISSUE THREAD

**Issue by nheilbuth** [dbeaver/dbeaver#9560]
#### System information: 
- Operating system (distribution) and version: **Windows 10 (1909)**
- DBeaver version: **7.1.5.202008170457**

#### Connection specification:
- Database name and version: **PostgreSql 9.6 (also tested on version 11)**
- Driver name: **org.postgresql.Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc)? **No**

#### Describe the problem you're observing:
When enabling "Show all databases", and my user don't have access to ALL databases on the server, the connection fails with:
"Can't connect ot remote PostgreSQL server
ERROR: permission denied for database azure_maintenance"

I would expect to be able to connect to the server and list all databases (or at least all databases that I have access to).

Disabling "Show all databases" and selecting a single database that I have access to works fine

#### Steps to reproduce, if exist:
Setup connection for a database server where you have access to some of the databases, but not all.
Go to Connection properties->Connection settings->PostgreSQL->Enable "Show all databases".
Connect to the server.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2020-08-17 15:50:38.321
!MESSAGE ERROR: permission denied for database azure_maintenance
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-08-17 15:50:38.321
!MESSAGE ERROR: permission denied for database azure_maintenance
!STACK 0
org.postgresql.util.PSQLException: ERROR: permission denied for database azure_maintenance
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:150)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:113)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.loadAvailableDatabases(PostgreDataSource.java:138)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Thanks for the bug report.
This is similar to #9566 (database  statistics read may fail but it should block connection itself).

We'll include this bugfix in the hotfix version.

**Comment by serge-rider** [comment]
BTW you can test the fix in the Early Access version (https://dbeaver.io/files/ea)

**Comment by nheilbuth** [comment]
Installing the Early Access version does _not_ seem to fix the issue!
![image](https://user-images.githubusercontent.com/1744634/90471193-ce51f400-e11d-11ea-90a4-2e6f01e9b86c.png)
![image](https://user-images.githubusercontent.com/1744634/90471199-d4e06b80-e11d-11ea-9b22-cef890c96c42.png)

**Comment by pyrocks** [comment]
I have the same issue with connections to AWS RDS - had to revert to 7.1.4.
For some reason I cannot install the EA on mac - it says the file is damaged.

**Comment by serge-rider** [comment]
Could you post error stacktrace again?
I was pretty sure that this issue was caused by database statistics read (which was added in 7.1.5).

DBeaver executes `SELECT db.oid,db.* FROM pg_catalog.pg_database db` to read database list, there were no changes since 7.1.4.

**Comment by nheilbuth** [comment]
Looks like a different stacktrace

!ENTRY org.jkiss.dbeaver.model 4 0 2020-08-18 08:03:59.535
!MESSAGE ERROR: permission denied for database azure_maintenance
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-08-18 08:03:59.535
!MESSAGE ERROR: permission denied for database azure_maintenance
!STACK 0
org.postgresql.util.PSQLException: ERROR: permission denied for database azure_maintenance
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:150)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:113)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.loadAvailableDatabases(PostgreDataSource.java:138)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Thanks! I just realized that latest EA didn't include all fixes. Please try to re-download it.

If everything ok then we will release hotfix version today.

**Comment by nheilbuth** [comment]
Yup EA version works now!
Thanks a lot

**Comment by uslss** [comment]
verified

**Comment by pyrocks** [comment]
New 7.1.5 works correctly, thanks

**Comment by nheilbuth** [comment]
> New 7.1.5 works correctly, thanks

I can confirm
