### ISSUE TITLE
Cockroach database connection not possible anymore: pg_database_size is not implemented in cockroach database

### ISSUE THREAD

**Issue by streinhold** [dbeaver/dbeaver#9566]
#### System information: 
- Operating system: Windows 10
- DBeaver version: 7.1.5
- Java version: 11.0.5
- Additional extensions: none

#### Connection specification:
- Database name and version: Cockroach 19.2.4
- Driver name: org.postgresql.Driver 42.2.5
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:
Connection to a local cockroach (running in a docker container) is not possible after update to Dbeaver 7.1.5.
Error message:
Can't connect ot remote PostgreSQL server
  ERROR: unknown function: pg_database_size()

I noticed, that the call to this function has been introduced 4 days ago into [PostgreDatabase.java](https://github.com/dbeaver/dbeaver/blob/55b6d6c807ef5219aba74e7d5d00bbcdb775310c/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDatabase.java#L155) and [PostgreDataSource.java](https://github.com/dbeaver/dbeaver/blob/55b6d6c807ef5219aba74e7d5d00bbcdb775310c/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDataSource.java#L119).

According to [Cockroach issue 26398](https://github.com/cockroachdb/cockroach/issues/26398) this function is not implemented.

#### Steps to reproduce, if exist:
1. Start a local cockroach database.
2. Create a connection to the database (all defaults)
3. Connect to the database

#### Include any warning/errors/backtraces from the logs

!ENTRY org.jkiss.dbeaver.model 4 0 2020-08-17 19:05:04.976
!MESSAGE ERROR: unknown function: pg_database_size()
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-08-17 19:05:04.976
!MESSAGE ERROR: unknown function: pg_database_size()
!STACK 0
org.postgresql.util.PSQLException: ERROR: unknown function: pg_database_size()
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.loadAvailableDatabases(PostgreDataSource.java:138)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:76)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by serge-rider** [comment]
Thanks for the bug report. The same issue happens with some other PG forks.

We will release hotfix version shortly.

**Comment by serge-rider** [comment]
You can test the fix in the Early Access version (https://dbeaver.io/files/ea)

**Comment by streinhold** [comment]
I can confirm that the Early Access version fixes the problem.
