### ISSUE TITLE
IO error: Utility 'mysqldump' not found in client home '/usr' (/usr)

### ISSUE THREAD

**Issue by chrisemke** [dbeaver/dbeaver#9584]
I can't dump or restore any database. If I install dbeaver.rpm it works but flatpak doesn't.

2020-08-19 09:08:53.929 - IO error: Utility 'mysqldump' not found in client home '/usr' (/usr)
2020-08-19 09:08:53.932 - java.io.IOException: Utility 'mysqldump' not found in client home '/usr' (/usr)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getNativeClientBinary(RuntimeUtils.java:121)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.fillProcessParameters(MySQLDatabaseExportHandler.java:72)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.fillProcessParameters(MySQLDatabaseExportHandler.java:1)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.getMySQLToolCommandLine(MySQLNativeToolHandler.java:33)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.getCommandLine(MySQLDatabaseExportHandler.java:57)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLDatabaseExportHandler.getCommandLine(MySQLDatabaseExportHandler.java:1)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:158)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by uslss** [comment]
seems to be similar to #9192 
close as duplicate.
anyway, thanks for the bug report

**Comment by felix-penrose** [comment]
I've got the same issue - @uslss are you sure that other issue is similar, do you mean the file access denial part of it?

My connection in question is not via SSH, but I cannot perform a mysql dump regardless of the output folder of the .sql file. Is there a work around for this issue?

**Comment by phrane** [comment]
I'm running into this error. I'm trying to import the mysql sakila test db, and can't seem to import the schema (.sql).

**Comment by GalloisLuca** [comment]
Got the same probleme, my dbeaver is freshly installed. I don't think that's the same problème with the issues #9192, i got the same probleme with my local BDD

**Comment by junedev** [comment]
I had the same issue and this fixed it in my case: https://github.com/dbeaver/dbeaver/issues/8508#issuecomment-758028691

**Comment by domainoverflow** [comment]
Still happenning,

**Comment by koushikchoudhury0** [comment]
> seems to be similar to #9192 close as duplicate. anyway, thanks for the bug report

This is not even close to #9192

**Comment by felix-penrose** [comment]
Yep, not the same, still a bug.
