### ISSUE TITLE
sql script can not named with Chinese when connectting oracle

### ISSUE THREAD

**Issue by frozenfield** [dbeaver/dbeaver#9601]
#### System information: 
OS: Win - 10
DBeaver version - 7.1.5
Additional extensions

#### Connection specification:
- Oracle Database 10g Enterprise Edition Release 10.2.0.4.0 - 64bi
- Driver name Oracle

when I named a sql script with Chinese，I closed the file and open again，Oracle could not connect ever，and if I renamed it with English or number，It could connect aggin。I think it is a bug。

this is the log
2020-08-21 13:43:13.795 - Undefined Error
oracle.net.ns.NetException: Undefined Error
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:271)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:317)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:197)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.lambda$0(JDBCRemoteInstance.java:127)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.openIsolatedContext(JDBCRemoteInstance.java:125)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$OpenContextJob.run(SQLEditor.java:586)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce it. Which locale do you use? Can you give a name example? Do you have standalone or Eclipse DBeaver?
![dbeaver_jGIoJ7jbB8](https://user-images.githubusercontent.com/51405061/90870009-ae326700-e3a1-11ea-9188-3717438a7792.png)

**Comment by frozenfield** [comment]
> I cannot reproduce it. Which locale do you use? Can you give a name example? Do you have standalone or Eclipse DBeaver?
> ![dbeaver_jGIoJ7jbB8](https://user-images.githubusercontent.com/51405061/90870009-ae326700-e3a1-11ea-9188-3717438a7792.png)

Locale is Simple Chinese.I could not ues any Chinese word like“啊”“你好”“哈喽” and so on. I install it uesd"dbeaver-ce-7.1.5-x86_64-setup.exe".

**Comment by KMQF** [comment]
I have the same situation，at releases 7.2.0.202008302047
![1600308187(1)](https://user-images.githubusercontent.com/26564574/93411132-08edae80-f8cd-11ea-82bb-bf492204ccee.jpg)

**Comment by KMQF** [comment]
Then by Googled result, i know that the reason is *.jar file.
And Replace dbeave_self download_jar file  using orai18n.jar and xdb6.jar ,, its work!!
Good lucky~

**Comment by serge-rider** [comment]
@KMQF thanks for the workaround

**Comment by KMQF** [comment]
> @KMQF thanks for the workaround
This tool is helpful to my work. So thank you too!!!

**Comment by frozenfield** [comment]
> Then by Googled result, i know that the reason is *.jar file.
> And Replace dbeave_self download_jar file using orai18n.jar and xdb6.jar ,, its work!!
> Good lucky~


@KMQF  Thanks for your answer,and I found that the problem is different versions of Oracle need different versions of  instantclient and  different drivers，but dbeave just use the “RELEASE” or"LATEST", We can download  different  drivers from [here](https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html) to Replace default jars,it works.
<img width="672" alt="微信图片_20200921092032" src="https://user-images.githubusercontent.com/12494249/93727010-c1786280-fbeb-11ea-9f95-6fe5a06c8f06.png">
<img width="484" alt="微信图片_20200921092024" src="https://user-images.githubusercontent.com/12494249/93727016-c5a48000-fbeb-11ea-9c18-df20c839d51f.png">
<img width="349" alt="微信图片_20200921092017" src="https://user-images.githubusercontent.com/12494249/93727017-c76e4380-fbeb-11ea-9377-d70864cd29ed.png">
<img width="270" alt="微信图片_20200921092029" src="https://user-images.githubusercontent.com/12494249/93727019-c9d09d80-fbeb-11ea-923d-e766ae285c45.png">
