### ISSUE TITLE
7.1.5 broke export from sqlite to postgres remote server

### ISSUE THREAD

**Issue by mbelvadi2** [dbeaver/dbeaver#9614]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version 7.1.5
- Additional extensions - none

#### Connection specification:
- Database name and version sqlite export to:
PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit 
- Do you use tunnels or proxies (SSH, SOCKS, etc)? yes, ssh tunnel to the postgres server,

#### Describe the problem you're observing:
For the last few weeks I have been successfully using the table "export" function to copy entire tables from my sqlite database to my Postgres database, both as "create" and "existing". Suddenly after I upgraded from 7.1.4 to 7.1.5, I cannot do it anymore - every single time with every table, large and very small, I get the error: Can't init data transfer  Reason: Error starting data transfer.
I have not changed ANY of the remote connection settings (including the SSH tunneling settings, also not changed my server password) and in fact can still open and execute commands on the remote database just fine, so I know it's not a tunneling or credential problem - it's just the export table that's broken.
It is 100% reproducible - it fails every time with every table from multiple different sqlite databases, always to the same (my only) postgres database.

#### Include any warning/errors/backtraces from the logs

Here's what shows up in the error log:
Exception trace stack:
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.setPrecision(PostgreAttribute.java:125)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.generateStructTableDDL(DatabaseTransferUtils.java:247)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferUtils.generateTargetTableDDL(DatabaseTransferUtils.java:90)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetTable(DatabaseTransferConsumer.java:528)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.createTargetDatabaseObjects(DatabaseTransferConsumer.java:493)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.startTransfer(DatabaseTransferConsumer.java:462)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.lambda$1(DTTaskHandlerTransfer.java:79)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Session data:
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by kseniiaguzeeva** [comment]
Verified
