### ISSUE TITLE
Error closing plan analyser

### ISSUE THREAD

**Issue by kruzewski** [dbeaver/dbeaver#9662]
#### System information: 
-Operating system (distribution) and version: Windows 10 Enterprise Version:1809
-DBeaver version: Version 7.1.5.202008180601
-Java version: 1.8.0_131-b11
-Additional extensions

#### Connection specification:
-Database name and version: Greenplum Database 5.26.0
-Driver name: Greenplum
-Do you use tunnels or proxies (SSH, SOCKS, etc)?: None

#### Describe the problem you're observing:
When running an 'explain plan' via 'Ctrl+Shift+E', dbeaver is unable to parse the execution plan results from Greenplum.
#### Steps to reproduce, if exist:
Run 'Explain Execution Plan' from the execute context menu or 'Ctrl+Shift+E'
![image](https://user-images.githubusercontent.com/1432488/91615197-0d1f4f80-e951-11ea-85a3-0c3cea5dfdfa.png)
and the execution plan is not correctly parsed. 
![image](https://user-images.githubusercontent.com/1432488/91615253-245e3d00-e951-11ea-88b2-ba706df12e36.png)

However I am able successfully able to get a query plan result...just not correctly parsed...
![image](https://user-images.githubusercontent.com/1432488/91615387-6e472300-e951-11ea-8e80-1a6298e499ac.png)

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/1432488/91615030-b6b21100-e950-11ea-9913-03ff41dfcf57.png)

**Comment by serge-rider** [comment]
Could you send stacktrace from the error log? (https://github.com/dbeaver/dbeaver/wiki/Log-files?)
You also can get it from Error Log view (just click on the nested error).

**Comment by kruzewski** [comment]
> Could you send stacktrace from the error log? (https://github.com/dbeaver/dbeaver/wiki/Log-files?)
> You also can get it from Error Log view (just click on the nested error).

!ENTRY org.jkiss.dbeaver.model 4 0 2020-08-28 16:59:36.582
!MESSAGE Error closing plan analyser
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-08-28 16:59:36.582
!MESSAGE ERROR: prepared statement "S_1" already exists
!STACK 0
org.postgresql.util.PSQLException: ERROR: prepared statement "S_1" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755)
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:799)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.rollback(JDBCConnectionImpl.java:295)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgreExecutionPlan.explain(PostgreExecutionPlan.java:142)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgreQueryPlaner.planQueryExecution(PostgreQueryPlaner.java:68)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.lambda$0(ExplainPlanViewer.java:396)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:390)
	at org.jkiss.dbeaver.ui.editors.sql.plan.ExplainPlanViewer$ExplainPlanService.evaluate(ExplainPlanViewer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kruzewski** [comment]
Let me know if you need anything else.

**Comment by serge-rider** [comment]
Problem happens because of load balances in front of PG server (pg_bouncer). It works with JDBC prepared statements poorly.

I've replaced PreparedStatement with simple Statement for execution plan explain. Hope this will help.

**Comment by uslss** [comment]
verified
