### ISSUE TITLE
dbf file error: DANS DBF Library error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by brasio** [dbeaver/dbeaver#9680]
Hi all, I can view all the tables of a dbf file, but when I click on a table I get the above error.
(dbeaver 7.2 community).

**Comment by uslss** [comment]
could you provide database you use, clear steps and full error log text?

**Comment by brasio** [comment]
Database file example is on

https://gitlab.dane.gov.pl/otwarte-dane/mcod-backend/-/raw/fdbc3917e0fcbdbaa60f871c9622d1dd99ee13c4/data/dbf_examples/dbase_30.dbf

 Steps are: New connection -> Dbf -> path selection -> finish.
 No other parameters or configuration, just default ones.

**Comment by uslss** [comment]
thanks for the clarification and bug report

**Comment by LonwoLonwo** [comment]
[logdrivererror.txt](https://github.com/dbeaver/dbeaver/files/5170788/logdrivererror.txt)
error log

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/4335

**Comment by serge-rider** [comment]
Actual error is:
```
nl.knaw.dans.common.dbflib.CorruptedTableException: Number of field descriptions in file could not be calculated.
	at nl.knaw.dans.common.dbflib.DbfHeader.getFieldCount(DbfHeader.java:181)
	at nl.knaw.dans.common.dbflib.DbfHeader.readAll(DbfHeader.java:131)
	at nl.knaw.dans.common.dbflib.Table.open(Table.java:275)
	at nl.knaw.dans.common.dbflib.Table.open(Table.java:258)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.relique.jdbc.dbf.DbfReader.<init>(DbfReader.java:97)
	at org.relique.jdbc.csv.CsvStatement.executeParsedQuery(CsvStatement.java:378)
	at org.relique.jdbc.csv.CsvStatement.executeParsedQuery(CsvStatement.java:313)
	at org.relique.jdbc.csv.CsvStatement.executeQuery(CsvStatement.java:306)
	at org.relique.jdbc.csv.CsvDatabaseMetaData.getColumns(CsvDatabaseMetaData.java:150)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getColumns(JDBCDatabaseMetaDataImpl.java:1152)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableColumnLoadStatement(GenericMetaModel.java:592)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:83)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareChildrenStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:96)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:153)
```

This DBF driver just doesn't support this DBF format.
I'm afraid there is nothing we can do from the dbeaver side.

You could try to use some other DBF driver (there are several commercial ones).
