### ISSUE TITLE
Cannot move Blob column from DB2 to PG Bytea

### ISSUE THREAD

**Issue by rutuparna-java** [dbeaver/dbeaver#9685]
Hi,
     While using Data transfer option getting below exception

SQL Error [42804]: Batch entry 0 INSERT INTO public
was aborted: ERROR: column "bytecontent" is of type bytea but expression is of type bigint

**Comment by uslss** [comment]
thanks for the bug report

**Comment by uslss** [comment]
error appears when trying to export blob to pg bytea
![image](https://user-images.githubusercontent.com/31996417/94785455-5a6f6080-03d8-11eb-908a-cd08dfa5c144.png)
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\37529\AppData\Roaming\DBeaverData\workspace6\.metadata\.bak_1.log
Created Time: 2020-10-01 11:15:08.468

org.jkiss.dbeaver.model
Error
Thu Oct 01 11:21:34 MSK 2020
ERROR: column "picture" is of type bytea but expression is of type bigint
  Hint: You will need to rewrite or cast the expression.
  Position: 74

org.postgresql.util.PSQLException: ERROR: column "picture" is of type bytea but expression is of type bigint
  Hint: You will need to rewrite or cast the expression.
  Position: 74
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:821)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeBatch(JDBCStatementImpl.java:372)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:152)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:278)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:201)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:306)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:351)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:215)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:216)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by ShadelessFox** [comment]
Testing required for BINARY & BLOB columns transfer into SQL Server.

**Comment by uslss** [comment]
verified
