### ISSUE TITLE
NullPointerException at org.jkiss.dbeaver.model.navigator.DBNResource.getNodeItemPath

### ISSUE THREAD

**Issue by afimuc** [dbeaver/dbeaver#9726]
#### System information: 
- Operating system (distribution) and version: Windows 10 Pro, Version 10.0.18363 Build 18363
- DBeaver version: 7.2.0.202008302047
- Additional extensions: none

#### Connection specification:
- various connections (Oracle, Postgres), but error occurs even when no connection is active

#### Describe the problem you're observing:
Sporadic, random appearance of error message ("An error has occurred") with corresponding log entry (see below).
Appears every few (~5) minutes.

#### Steps to reproduce, if exist:
Cannot reproduce deterministically

#### Include any warning/errors/backtraces from the logs
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui.workbench
Fehler
Wed Sep 09 07:37:26 CEST 2020
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".

java.lang.NullPointerException
  at org.jkiss.dbeaver.model.navigator.DBNResource.getNodeItemPath(DBNResource.java:250)
  at org.jkiss.dbeaver.ui.editors.NodeEditorInputFactory.saveState(NodeEditorInputFactory.java:67)
  at org.jkiss.dbeaver.ui.editors.NodeEditorInput.saveState(NodeEditorInput.java:91)
  at org.eclipse.ui.internal.EditorHistoryItem.saveState(EditorHistoryItem.java:215)
  at org.eclipse.ui.internal.EditorHistory.saveState(EditorHistory.java:151)
  at org.eclipse.ui.internal.Workbench.saveWorkbenchState(Workbench.java:3562)
  at org.eclipse.ui.internal.Workbench.persistWorkbenchState(Workbench.java:3537)
  at org.eclipse.ui.internal.Workbench.access$11(Workbench.java:3534)
  at org.eclipse.ui.internal.Workbench$13.run(Workbench.java:1208)
  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
  at org.eclipse.ui.internal.Workbench.persist(Workbench.java:1205)
  at org.eclipse.ui.internal.Workbench.access$34(Workbench.java:1176)
  at org.eclipse.ui.internal.Workbench$41.runInUIThread(Workbench.java:2844)
  at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
  at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
  at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
  at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
  at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
  at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:234)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1447)

**Comment by uslss** [comment]
Hi @afimuc ,
please, try to reset workspace using file - Reset Workspace state or according to the [manual](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

**Comment by serge-rider** [comment]
Fixed (this happens when resource nod was disposed and workspace sync occurs).

**Comment by afimuc** [comment]
> Hi @afimuc ,
> please, try to reset workspace using file - Reset Workspace state or according to the [manual](https://github.com/dbeaver/dbeaver/wiki/Reset-workspace)

That solved it.

**Comment by uslss** [comment]
verified
