### ISSUE TITLE
BigTable: Error while using "User account" auth type

### ISSUE THREAD

**Issue by Vinicius-Almeida-94** [dbeaver/dbeaver#9758]
#### System information: 
- Operating system: macOs Catalina 10.15.6
- DBeaver version: Enterprise Version 7.2.0.202009071746

#### Connection specification:
- Database name: BigTable
- Driver name: BigTable
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Description:
I'm trying to connect to a BigTable server using "User account" auth type. But I'm receiving the error below.

#### Error log
MESSAGE Error reading credentials from stream, 'type' value 'authorized_user' not recognized. Expecting 'service_account'.
!STACK 0
java.io.IOException: Error reading credentials from stream, 'type' value 'authorized_user' not recognized. Expecting 'service_account'.
	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:311)
	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:281)
	at com.dbeaver.db.google.bigtable.model.BigTableDataSource.setupCredentials(BigTableDataSource.java:100)
	at com.dbeaver.db.google.bigtable.model.BigTableDataSource.<init>(BigTableDataSource.java:78)
	at com.dbeaver.db.google.bigtable.BigTableDataSourceProvider.openDataSource(BigTableDataSourceProvider.java:73)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

#### Steps to reproduce:
1. Login on gcloud `gcloud auth login`
2. Authenticate at the application-default `gcloud auth application-default login`
3. Get your user account credentials file `application_default_credentials.json`
4. Try to access a BigTable instance on DBeaver Enterprise using the "User account" auth type.

![Connection error](https://user-images.githubusercontent.com/17571546/93080309-c722f500-f68d-11ea-9862-573252fe04d1.png)

**Comment by serge-rider** [comment]
Fixed.
Additionally authorization with app default crednetials support added.
![image](https://user-images.githubusercontent.com/6398845/109825473-ea952880-7c4a-11eb-848d-d57bf262bbb3.png)

**Comment by serge-rider** [comment]
Fix will be included in DBeaver EE 21.0

**Comment by uslss** [comment]
verified
