### ISSUE TITLE
Class cast exception Firebird dbs when they contain a table with a BOOLEAN domain (which is not a reserved word)

### ISSUE THREAD

**Issue by cfnz** [dbeaver/dbeaver#9767]
This issue is the same as a closed issue - [8793](https://github.com/dbeaver/dbeaver/issues/8793).

I commented on that issue, but not sure if it will see the light of day, so am creating a new issue here. On the original issue the problem could not be reproduced, and the issue was waiting for a response which didn't happen so it got closed.

The exception is org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType

Running Firebird server 2.5
DB Beaver 7.2
Original issue version 7.0.5.202005171753 (May 18, 2020)

The server version does not have the native concept of a Boolean type. I have (as many users do) created a BOOLEAN domain which is a Char(1) type.

It seems all the tables I open that has a column with a DOMAIN of BOOLEAN specified gets this error. Other tables open fine.

This used to work, but can't recall in which version :-)...

e.g.

```
CREATE DOMAIN BOOLEAN AS
CHAR(1) CHARACTER SET NONE
DEFAULT 'F'
NOT NULL
CHECK (Value in ('T',  'F'))
COLLATE NONE

```
then
```
CREATE TABLE TEST_TABLE (
    ID             INTEGER NOT NULL,
    TEST_BOOLEAN   BOOLEAN NOT NULL /* BOOLEAN = CHAR(1) DEFAULT 'F' NOT NULL CHECK (Value in ('T',  'F')) */,
    TEST_OTHER     VARCHAR(64) NOT NULL
);
```
Opening this table with or without data causes
org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType

Other domains are fine so seems to be with a DOMAIN named BOOLEAN (which is not a reserved word in Firebird 2.5 at least) causes issues.

**Comment by LonwoLonwo** [comment]
@cfnz as quick workaround - i think, it might work if you name the boolean other - d_boolean, for example

**Comment by LonwoLonwo** [comment]
@cfnz can you sent [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) of error?

**Comment by LonwoLonwo** [comment]
can't reproduce on Firebird 2.1 and Firebird 2.5

**Comment by cfnz** [comment]
Strange. I again created the table and got the error. However, I was creating the table in an existing database.
Creating a new database, adding the domain and table, and it works, so it is not as clean a test case as I thought.

It is still the case however where opening other tables without that domain seems to work, but with that domain and it fails (but it works in a clean DB, sigh...). The issue is in multiple existing DBs (though they have similar content), so it is not just the one DB. I will see if I can narrow down something in those DBs over and above using the BOOLEAN domain.

Here is the .log file content:
```
!SESSION 2020-09-16 09:37:48.266 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_212
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_NZ
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2020-09-16 09:38:02.805
!MESSAGE Can't fetch database data types
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2020-09-16 09:38:02.805
!MESSAGE SQL Error [335544914] [22001]: arithmetic exception, numeric overflow, or string truncation; string right truncation [SQLState:22001, ISC error code:335544914]
!SUBENTRY 2 org.jkiss.dbeaver.model 2 0 2020-09-16 09:38:02.805
!MESSAGE arithmetic exception, numeric overflow, or string truncation; string right truncation [SQLState:22001, ISC error code:335544914]
!STACK 0
java.sql.SQLException: arithmetic exception, numeric overflow, or string truncation; string right truncation [SQLState:22001, ISC error code:335544914]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:539)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:140)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:204)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:171)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:155)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readResponse(AbstractFbWireDatabase.java:211)
	at org.firebirdsql.gds.ng.wire.version10.V10Statement.processFetchResponse(V10Statement.java:488)
	at org.firebirdsql.gds.ng.wire.version10.V10Statement.fetchRows(V10Statement.java:467)
	at org.firebirdsql.jdbc.FBStatementFetcher.fetch(FBStatementFetcher.java:196)
	at org.firebirdsql.jdbc.FBStatementFetcher.next(FBStatementFetcher.java:127)
	at org.firebirdsql.jdbc.AbstractResultSet.next(AbstractResultSet.java:363)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.next(JDBCResultSetImpl.java:272)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataTypeCache.loadObjects(FireBirdDataTypeCache.java:71)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataTypeCache.loadObjects(FireBirdDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:440)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdDataSource.initialize(FireBirdDataSource.java:125)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:844)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: arithmetic exception, numeric overflow, or string truncation
!SUBENTRY 3 org.jkiss.dbeaver.model 2 0 2020-09-16 09:38:02.805
!MESSAGE arithmetic exception, numeric overflow, or string truncation
!STACK 0
org.firebirdsql.jdbc.FBSQLExceptionInfo: arithmetic exception, numeric overflow, or string truncation
!SUBENTRY 4 org.jkiss.dbeaver.model 2 0 2020-09-16 09:38:02.806
!MESSAGE string right truncation

!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-16 09:38:20.487
!MESSAGE org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-16 09:38:20.487
!MESSAGE org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType
!STACK 0
java.lang.ClassCastException: org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCDataType cannot be cast to org.jkiss.dbeaver.ext.firebird.model.FireBirdDataType
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTableColumn.<init>(FireBirdTableColumn.java:42)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdMetaModel.createTableColumnImpl(FireBirdMetaModel.java:317)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:140)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:153)
	at org.jkiss.dbeaver.ext.firebird.model.FireBirdTable.getAttributes(FireBirdTable.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:867)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:848)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:907)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:534)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:424)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:201)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:256)
	at org.jkiss.dbeaver.ui.navigator.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The dbeaver-debug.log file is
```
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.3.600.v20200116-2127]
> Start Eclipse e4 Workbench SWT [org.eclipse.e4.ui.workbench.swt 0.14.900.v20200213-1442]
> Start Eclipse Application Services [org.eclipse.e4.core.services 2.2.200.v20200127-0814]
> Start Eclipse Contexts [org.eclipse.e4.core.contexts 1.8.400.v20191217-1710]
> Start Eclipse UI Application Services [org.eclipse.e4.ui.services 1.3.700.v20190930-1643]
> Start EMF Common [org.eclipse.emf.common 2.18.0.v20191225-1014]
> Start EMF Ecore [org.eclipse.emf.ecore 2.21.0.v20200127-1342]
> Start EMF XML/XMI Persistence [org.eclipse.emf.ecore.xmi 2.16.0.v20190528-0725]
> Start Eclipse UI Dependency Injection [org.eclipse.e4.ui.di 1.2.800.v20200128-0855]
> Start Eclipse e4 Workbench Add-ons [org.eclipse.e4.ui.workbench.addons.swt 1.3.800.v20191212-1231]
> Start Expression Language [org.eclipse.core.expressions 3.6.700.v20200212-1751]
> Start Eclipse e4 Workbench SWT Renderer [org.eclipse.e4.ui.workbench.renderers.swt 0.14.1100.v20200217-1217]
> Start Eclipse Bindings Support [org.eclipse.e4.ui.bindings 0.12.800.v20191216-0805]
> Start Eclipse Dependency Injection Extensions [org.eclipse.e4.core.di.extensions 0.15.500.v20200106-1259]
> Start Eclipse CSS SWT Support [org.eclipse.e4.ui.css.swt 0.13.900.v20200203-0840]
> Start Eclipse CSS SWT Theme Support [org.eclipse.e4.ui.css.swt.theme 0.12.600.v20200124-0005]
> Start DBeaver UI [org.jkiss.dbeaver.ui 5.1.55.202008302047]
> Start Help System Core [org.eclipse.help 3.8.700.v20191212-1123]
> Start Equinox Provisioning Core [org.eclipse.equinox.p2.core 2.6.300.v20200211-1504]
> Start Equinox Provisioning Operations API [org.eclipse.equinox.p2.operations 2.5.700.v20191211-1713]
> Start Equinox Provisioning Platform Automatic Update Support [org.eclipse.equinox.p2.ui.sdk.scheduler 1.4.600.v20200221-0754]
> Start Equinox Provisioning Metadata [org.eclipse.equinox.p2.metadata 2.4.700.v20191213-1911]
> Start Equinox Provisioning Update Checker [org.eclipse.equinox.p2.updatechecker 1.2.300.v20200222-1600]
> Start Equinox Provisioning Engine [org.eclipse.equinox.p2.engine 2.6.600.v20200110-2121]
> Start Equinox Provisioning Metadata Repository [org.eclipse.equinox.p2.metadata.repository 1.3.400.v20191211-1528]
> Start Equinox Provisioning Repository [org.eclipse.equinox.p2.repository 2.4.700.v20200110-2121]
> Start Equinox Provisioning UI Support [org.eclipse.equinox.p2.ui 2.5.800.v20200213-1530]
> Start DBeaver SQL Model [org.jkiss.dbeaver.model.sql 1.0.30.202008302047]
> Start Default Text Editor [org.eclipse.ui.editors 3.13.100.v20200130-1507]
> Start Text Editor Framework [org.eclipse.ui.workbench.texteditor 3.14.100.v20200212-1049]
> Start DBeaver UI Editors - Base [org.jkiss.dbeaver.ui.editors.base 1.0.40.202008302047]
> Start DBeaver UI Editors - SQL [org.jkiss.dbeaver.ui.editors.sql 1.0.40.202008302047]
> Start DBeaver UI Editors - Data [org.jkiss.dbeaver.ui.editors.data 1.0.40.202008302047]
> Start DBeaver Sample Database [org.jkiss.dbeaver.ext.sample.database 1.0.77.202008302047]
> Start DBeaver Tip of the day [org.jkiss.dbeaver.ext.ui.tipoftheday 1.0.46.202008302047]
> Start File Buffers [org.eclipse.core.filebuffers 3.6.900.v20200117-0616]
> Start DBeaver ER Diagram [org.jkiss.dbeaver.ext.erd 2.0.142.202008302047]
> Start Team Support Core [org.eclipse.team.core 3.8.900.v20200211-0946]
> Start DBeaver Generic Plug-in [org.jkiss.dbeaver.ext.generic 2.3.126.202008302047]
> Start DBeaver Firebird Support [org.jkiss.dbeaver.ext.firebird 1.0.141.202008302047]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.3.500.v20200114-1637]
> Start GEF (MVC) [org.eclipse.gef 3.11.0.201606061308]
> Start Draw2d [org.eclipse.draw2d 3.10.100.201606061308]
```

**Comment by cfnz** [comment]
With further testing it seems related to the size of the database structure though I have not determined when it fails, but if I half the structure (tables, procedures, etc - no data), it will work, but if if gets too big in structure, it will fail.

**Comment by cfnz** [comment]
OK, took a bit of figuring, but here is a DB script that causes the error from scratch.

Looks like the real error is the first exception (`Can't fetch database data types` as above) which is not shown to the user (unless the error log is open). You then go and open a table with, say a BOOLEAN domain, whose information was not properly loaded because of the first exception, and then you get the Class Cast exception.

A reasonably nasty looking but legit computed by column causes the issue. The computed by column uses an external function ([FreeAdhocUDF](http://freeadhocudf.org/index_eng.html)) which I don't think is the cause of the issue... I tried to remove it from the example to make it simpler, but I think it simplified and shortened it too much and it then worked.

The full DB script is shown below which causes the issue on a new DB.

```
SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'test-db:Quick_Test_8.fdb'
USER 'SYSDBA'
password 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;


/******************************************************************************/
/****                     User defined functions (UDF)                     ****/
/******************************************************************************/
DECLARE EXTERNAL FUNCTION F_ENCODEDATE
    INTEGER,
    INTEGER,
    INTEGER
    RETURNS DATE FREE_IT
    ENTRY_POINT 'encodedate' MODULE_NAME 'FreeAdhocUDF';


/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/
CREATE DOMAIN BOOLEAN AS
CHAR(1)
 DEFAULT 'F'
NOT NULL
CHECK (Value in ('T',  'F'));

CREATE DOMAIN CURRENCY AS
NUMERIC(18,2)
DEFAULT 0
NOT NULL;

CREATE DOMAIN INT_ID AS
INTEGER;

/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/
SET TERM ^ ;

CREATE PROCEDURE NWD_SEL_NUM_WORKING_DAYS (
    START_DATE_TIME TIMESTAMP NOT NULL,
    END_DATE_TIME TIMESTAMP NOT NULL,
    HOLIDAY_REGION_ID INTEGER NOT NULL)
RETURNS (
    NUM_WORKING_DAYS INTEGER NOT NULL)
AS
BEGIN
  SUSPEND;
END^

SET TERM ; ^


/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/
CREATE TABLE TABLE_THAT_CREATES_THE_FAILURE (
    BUSINESS_UNIT_ID       INT_ID NOT NULL,
    CALENDAR_YEAR          INTEGER NOT NULL,
    CALENDAR_MONTH         INTEGER NOT NULL,
    SALES                  CURRENCY,
    BUDGET                 CURRENCY,
    FORECAST               CURRENCY,
    PERCENT_THROUGH_MONTH  COMPUTED BY (iif(F_Encodedate(Calendar_Year, Calendar_Month, 1) < F_Encodedate(extract(year from current_date), extract(month from current_date), 1), 1,
    iif(F_Encodedate(Calendar_Year, Calendar_Month, 1) > F_Encodedate(extract(year from current_date), extract(month from current_date), 1), 0,
    ((select Num_Working_Days from Nwd_Sel_Num_Working_Days(F_Encodedate(Calendar_Year, Calendar_Month, 1), current_date, 2)) + 0.00) / (select Num_Working_Days from Nwd_Sel_Num_Working_Days(F_Encodedate(Calendar_Year, Calendar_Month, 1), F_Encodedate(Calendar_Year, Calendar_Month, extract(day from dateadd(1 month to F_Encodedate(Calendar_Year, Calendar_Month, 1))-1)), 2))))),
    TIME_STAMP             TIMESTAMP
);

CREATE TABLE TABLE_THAT_SHOWS_THE_FAILURE (
    ID                       INT_ID NOT NULL,
    TIME_STAMP               TIMESTAMP,
    WAS_ON_HOLD              BOOLEAN NOT NULL
);
```

**Comment by cfnz** [comment]
Confirmed it is not the external function, you can comment that out and cast the dates (replace the problem column with the below) and it still fails.
```
    PERCENT_THROUGH_MONTH  COMPUTED BY (iif(cast (Calendar_Year || '/' || Calendar_Month || '/01' as date) < cast(extract(year from current_date) || '/' || extract(month from current_date) || '/01' as date), 1,
    iif(cast(Calendar_Year || '/' || Calendar_Month  || '/01' as date) > cast(extract(year from current_date) || '/' || extract(month from current_date)  || '01/' as date), 0,
    ((select Num_Working_Days from Nwd_Sel_Num_Working_Days(cast(Calendar_Year  || '/' || Calendar_Month  || '/01' as date), current_date, 2)) + 0.00) / (select Num_Working_Days from Nwd_Sel_Num_Working_Days(cast(Calendar_Year || '/' || Calendar_Month  || '01/' as date), cast(Calendar_Year || '/' || Calendar_Month  || '/' || extract(day from dateadd(1 month to cast(Calendar_Year || '/' || Calendar_Month  || '01/' as date))-1) as date), 2))))),
```

**Comment by cfnz** [comment]
Not sure if this issue gets re-looked at after been tagged "Can't Reproduce"... should I file another request or can the "Can't Reproduce" tag be taken off given the latest info (and put back on if it still can't be reproduced - which I am hoping will not be the case)?

**Comment by LonwoLonwo** [comment]
@cfnz I still can't reproduce on our Firebird database, i will try another database... or, you can try sent here yours database test-db:Quick_Test_8.fdb

**Comment by cfnz** [comment]
Just ran the script above (with the altered PERCENT_THROUGH_MONTH so I didn't need the user defined function), tested (still fails) then zipped (not backed up) the file and attached.

I am running against a Firebird 2.5.6 database SuperClassic. Also, just downloaded Firebird 2.5.9 and installed on a fresh Ubuntu box, created the database from the script on that and still had the error.

So one other thing that could be different is the jdbc driver. I am using jaybird-4.0.1.java8.jar. (Have tried some other versions a while ago (can't recall which ones) and still had the error.)

Hopefully you can replicate, if not, I can test some more.
[Quick_Test_8.fdb.zip](https://github.com/dbeaver/dbeaver/files/5302017/Quick_Test_8.fdb.zip)

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
@cfnz thanks for the test base, it helped a lot in finding the error. I hope. you will be able to test the changes in version 7.2.2, it will be released next Monday

**Comment by cfnz** [comment]
Thanks for that, can also confirm it closes the issue :-)
