### ISSUE TITLE
[SECURITY] Why does the EXPORT needs WRITE access? Can we trust the dbeaver client performing right access check when no WRITE access are necessary?

### ISSUE THREAD

**Issue by kopax** [dbeaver/dbeaver#9783]
# BACKUP TASK CREATE INSERT IN DB !!

This sounds serious issue with the 7.2.0 dbeaver version, did I trust this software enough to corrupt the database?

#### System information: 

- Operating system (distribution) and version: Debian Buster
- DBeaver version: 7.2.0
- Additional extensions

#### Connection specification:
- Database name and version: Microsoft SQL Express Server
- Driver name: microsft sql server
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no, DB port is publicly open

#### Describe the problem you're observing:

Hello, I am on linux I want to dump a public microsfot express server database, how is that possible? I just tried dbeaver GUI client but it keep complaining during export that I do not have `INSERT` permissions on some table, making me abort the process.

#### Steps to reproduce, if exist:

Right click on DB, create a task, export DB, export as a table, then the export will complain if you have a READ-ONLY account.

#### Include any warning/errors/backtraces from the logs

Why does it tries to insert? This got me really worried, is my database now corrupted where I was having right?

How is this possible in a backup (READONLY) task?

```bash
2020-09-16 14:39:56.984 - Data transfer initiated
2020-09-16 14:39:56.985 - Initialize data transfer sources
2020-09-16 14:39:56.985 - Initialize pipes
2020-09-16 14:39:56.985 - Create necessary database objects
...etc
2020-09-16 14:39:57.006 - Create necessary database objects
2020-09-16 14:39:57.007 - Perform data transfer
2020-09-16 14:39:57.007 - Transfer data from "MY_DB.dbo.DP_IND" into "MY_DB.dbo.DP_IND [Existing]"
2020-09-16 14:39:57.008 - Execution context opened (bangleup.blc.paris; Data transfer producer; 4)
2020-09-16 14:39:57.009 - 	Connecting Data transfer producer
2020-09-16 14:39:57.121 - 	Set connection defaults
2020-09-16 14:39:57.163 - 	Set JDBC connection auto-commit false
2020-09-16 14:39:57.181 - Retrieve row count
2020-09-16 14:39:57.181 - 	Fetch table row count
2020-09-16 14:39:57.201 - Transfer table data
2020-09-16 14:39:57.201 - 	Read data
2020-09-16 14:39:57.202 - 	Fetch table data
2020-09-16 14:39:57.268 - Execution context opened (xxxxxxxx; Data transfer consumer; 5)
2020-09-16 14:39:57.268 - 	Connecting Data transfer consumer
2020-09-16 14:39:57.366 - 	Set connection defaults
2020-09-16 14:39:57.381 - 	Set JDBC connection auto-commit false
2020-09-16 14:39:57.411 - 	100 rows fetched
2020-09-16 14:39:57.412 - 	200 rows fetched
2020-09-16 14:39:57.413 - 	300 rows fetched
2020-09-16 14:39:57.413 - 	Insert rows (362)
2020-09-16 14:39:57.416 - 	Save batch (100 of 362)
2020-09-16 14:39:57.418 - 	Save batch (200 of 362)
2020-09-16 14:39:57.420 - 	Save batch (300 of 362)
2020-09-16 14:39:57.639 - Error inserting row
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [229] [S0005]: L'autorisation INSERT a été refusée sur l'objet 'DP_IND', base de données 'MY_DB', schéma 'dbo'.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:157)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.flushBatch(ExecuteBatchImpl.java:275)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:201)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.insertBatch(DatabaseTransferConsumer.java:305)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:215)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.lambda$0(DatabaseTransferProducer.java:216)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:138)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.transferData(DataTransferJob.java:109)
	at org.jkiss.dbeaver.tools.transfer.DataTransferJob.run(DataTransferJob.java:80)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:124)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeWithSettings(DTTaskHandlerTransfer.java:103)
	at org.jkiss.dbeaver.tools.transfer.task.DTTaskHandlerTransfer.executeTask(DTTaskHandlerTransfer.java:61)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.executeTask(TaskRunJob.java:119)
	at org.jkiss.dbeaver.registry.task.TaskRunJob.run(TaskRunJob.java:88)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.BatchUpdateException: L'autorisation INSERT a été refusée sur l'objet 'DP_IND', base de données 'MY_DB', schéma 'dbo'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2075)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeBatch(JDBCStatementImpl.java:387)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatementBatch(JDBCStatementImpl.java:154)
	... 19 more
```

**Comment by uslss** [comment]
Hi @kopax ,
it seems from log that you try to export your current table to another database, so it is not an issue in that case.
Probably you need another target format.

**Comment by kopax** [comment]
Hello, I stopped using dbeaver because it's not intuitive.

This was a db export. No clue why the logs are that wrong .
