### ISSUE TITLE
DBeaver stopped working (unexpected end of stream)

### ISSUE THREAD

**Issue by grted** [dbeaver/dbeaver#9799]
#### System information: 
KUbuntu 20.04
DBeaver 7.2.0

#### Connection specification:
- Database name and version
mysql  Ver 15.1 Distrib 10.3.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Driver name
MariaDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
SSH, Tunnel test is successful

#### Describe the problem you're observing:
In Linux i get "unexpected end of stream, read 0 bytes from 4 (socket was closed by server)", was working until today. Windows Version still is running (7.2.0 too).

In the connection settings port 3306 is set, but it looks like DBeaver is trying to use an Ephemeral port,

Removing .local/share/DBeaverData .eclipse/ and creating a new connection didn't change anything, neither reinstalling dbeaver

#### Steps to reproduce, if exist:
Set up connection, connect

#### Include any warning/errors/backtraces from the logs
I get in error-Details:
Could not connect to 127.0.0.1: 33116: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
  unexpected end of stream, read 0 bytes from 4 (socket was closed by server)

Console logs are:
`2020-09-17 10:23:32.750 - SSH INFO: Authentications that can continue: publickey,keyboard-interactive,password
2020-09-17 10:23:32.750 - SSH INFO: Next authentication method: publickey
2020-09-17 10:23:32.961 - SSH INFO: Authentication succeeded (publickey).
2020-09-17 10:23:32.982 - Execution context opened (MariaDB - db-server test ; Main; 0)
2020-09-17 10:23:33.088 - Connection failed (mariaDB-1748d5912bd-16377cc1021a172f)
2020-09-17 10:23:33.089 - SSH INFO: Disconnecting from server.server port 22
2020-09-17 10:23:33.092 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2020-09-17 10:23:33.140 - org.jkiss.dbeaver.model.exec.DBCConnectException: Could not connect to 127.0.0.1:33116 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
org.jkiss.dbeaver.model.exec.DBCConnectException: Could not connect to 127.0.0.1:33116 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:398)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:87)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:132)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to 127.0.0.1:33116 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:240)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1132)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:620)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:175)
        at org.mariadb.jdbc.Driver.connect(Driver.java:92)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:178)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:197)
        ... 24 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to 127.0.0.1:33116 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:240)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:101)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:772)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:415)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1128)
        ... 29 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:246)
        at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:215)
        at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:89)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:693)
        ... 31 more
2020-09-17 10:23:33.144 - unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
        at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:246)
        at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:215)
        at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:89)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:693)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:415)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1128)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:620)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:175)
        at org.mariadb.jdbc.Driver.connect(Driver.java:92)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:178)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:197)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:398)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:91)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:57)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:106)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:95)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:87)
        at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:132)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:837)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:106)
        at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:64)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:157)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:199)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:87)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2020-09-17 10:23:36.067 - DBeaver is stopping
2020-09-17 10:23:36.067 - Stop RMI server
2020-09-17 10:23:36.069 - DBeaver shutdown completed
2020-09-17 10:23:36.090 - Shutdown Core...
2020-09-17 10:23:36.248 - Shutdown completed in 158ms`

**Comment by grted** [comment]
Addition:
in linux dbeaver stopped working too, same error. Authentication is done via ssh-key-file

**Comment by grted** [comment]
Sorry, typo in config on two machines. Problem was in my config

**Comment by scollovati** [comment]
@grted I'm having your issue with ss-key-file. How you solved it?

**Comment by oradwell** [comment]
it can also happen if your server host has a protocol (e.g. "http://localhost". should be just "localhost")
