### ISSUE TITLE
Externally changed DB password leads to context menu being reduced to "Refresh" and no way to update password

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#9841]
#### System information: 
- Operating system (distribution) and version: Debian/SID
- DBeaver version 7.2.1
- Additional extensions -

#### Connection specification:
- Database name and version Postgres 12
- Driver name Postgres JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

Opened a connection to a database in DBeaver.
Then in a shell via psql I changed the password for the connection.
Back in DBeaver I right-clicked the connection and accidently selected "Refresh".
An error popup appeared with an error from Postgres.
After dismissing the error popup, the context menu now is reduced to exactly one entry: "Refresh" - which only produces the very same error popup again:
"SQL Error [28000]: FATAL: no pg_hba.conf entry for host "127.0.0.1", user "username", database "dbname", SSL off"

Connection is still shown as connected, tree can be expanded, but queries obviously only cause the very same error.
In the toolbar and "Database" menu, "Connect", "Reconnect", and "Disconnect" are all inactive for this connection as well.

Seems there's no way to update the password, disconnect, let alone delete the connection.

Closing and restarting DBeaver was the only remedy.

#### Include any warning/errors/backtraces from the logs
```
!ENTRY org.jkiss.dbeaver.model 4 0 2020-09-22 12:32:21.263
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-09-22 12:32:21.263
!MESSAGE No databases found on the server
!STACK 0
java.lang.IllegalStateException: No databases found on the server
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:417)
        at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.getDefaultInstance(PostgreDataSource.java:1)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.addSetDefaultObjectAction(NavigatorUtils.java:255)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.addStandardMenuItem(NavigatorUtils.java:219)
        at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.lambda$0(NavigatorUtils.java:202)
        at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
        at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
        at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:463)
        at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1428)
        at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:219)
        at org.eclipse.swt.widgets.Display.runPopups(Display.java:4997)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4438)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
        at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:234)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by akilovich** [comment]
Fixed.

**Comment by uslss** [comment]
verified
