### ISSUE TITLE
Unable to mysldump on Mac OS

### ISSUE THREAD

**Issue by Thomas-1985** [dbeaver/dbeaver#9894]
#### System information: 
- Operating system (distribution) and version: Mac OS 10.15.6
- DBeaver version: Version 7.2.1.202009201907
- Additional extensions: none

#### Connection specification:
- Database name and version: 10.1.44-MariaDB (same happens with 10.5.4-MariaDB)
- Driver name: org.mariadb.jdbc 2.4.3
- Do you use tunnels or proxies (SSH, SOCKS, etc)? SSH Tunnel

#### Describe the problem you're observing:
-Wanted to dump a db.
-Installed mysqdump (using brew as no native version exists for MacOS), version 8.0.21
-Tried to dump a database, but got the following exception
---
/Users/thomy/mysql/mysqldump --routines --add-drop-table --disable-keys --extended-insert --host=dev.12345.local --port=13307 -u root test_db
Task 'MySQL dump' started at Sat Sep 26 11:25:41 CEST 2020
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'test_db' AND TABLE_NAME = 'articles';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)

Task 'MySQL dump' finished at Sat Sep 26 11:25:42 CEST 2020
2020-09-26 11:25:42.430 - IO error: Process failed (exit code = 2). See error log.
2020-09-26 11:25:42.431 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:201)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:181)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:52)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
---

#### Steps to reproduce, if exist:
-same as above, can be reproduced

**Comment by TomYule** [comment]
I have the same problem; MySQL has not been installed on my computer. I installed MySQL with Docker, so I could not find mysldump when Exporting the database

**Comment by SergioSuarezGil** [comment]
same here

**Comment by flambchap** [comment]
Fixed the issue. By default, `mysqldump 8` tries to add column statistics, but only MySQL 8 stores it.

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by Thomas-1985** [comment]
Works for me in 21.0.1 (haven't tested on earlier versions). Thanks! :)
