### ISSUE TITLE
Unique and foreign keys couldn't be created using UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9942]
#### System information: 
- Operating system (distribution) and version win 10 x64
- DBeaver version 7.2.2

#### Connection specification:
- Database name and version Hive 2.3.2

#### Describe the problem you're observing:
Error appears when trying to create:
1. Unique key
Generated statement:
ALTER TABLE `default`.newtable ADD CONSTRAINT newtable_PK PRIMARY KEY (column1);
Error:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Fri Oct 02 11:48:22 MSK 2020
org.apache.hadoop.hive.ql.parse.ParseException:line 1:79 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in enable specification

java.lang.RuntimeException: org.apache.hadoop.hive.ql.parse.ParseException:line 1:79 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in enable specification
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:211)
	at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:77)
	at org.apache.hadoop.hive.ql.parse.ParseUtils.parse(ParseUtils.java:70)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:468)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1295)
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:204)
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:290)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:320)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:530)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:517)
	at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:310)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:530)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1437)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1422)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
2. Foreign Key - creation is blocked due to the impossibility of Unique Key creation

**Comment by LonwoLonwo** [comment]
related to https://github.com/dbeaver/dbeaver/issues/9943

**Comment by LonwoLonwo** [comment]
ability to create keys through UI removed

**Comment by uslss** [comment]
verified

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/10330
