### ISSUE TITLE
SQL queries using table name including hyphen or quotes produce errors.

### ISSUE THREAD

**Issue by kickthedragon** [dbeaver/dbeaver#9993]
#### System information: 
- Operating system (distribution) and version - macOS Catalina
- DBeaver version - Version 7.2.0.202009071746 Enterprise Addition
- Additional extensions

#### Connection specification:
- Database name and version - Amazon DynamoDB
- Driver name DynamoDB
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:

Trying to use a simple SQL query to grab data as described in the documentation and I get an "unexpected token error" when using a table name with a hyphen.

EXAMPLE: 1

SELECT * FROM my-table-name 
where sk = 'whatever'

If I use quotes around the table name I get "Error parsing SQL query

EXAMPLE: 2

SELECT * FROM "my-table-name"
where sk = 'whatever'

org.jkiss.dbeaver.model.exec.DBCException: Error parsing SQL query
	at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.createSelectQuery(DynamoQueryStatement.java:166)
	at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.executeStatement(DynamoQueryStatement.java:93)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:505)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:436)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:423)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:804)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3008)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:119)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4425)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.parseSelect(DynamoQueryStatement.java:195)
	at com.dbeaver.db.dynamodb.exec.DynamoQueryStatement.createSelectQuery(DynamoQueryStatement.java:161)

EXAMPLE: 3

putting single quotes around the table name produces unexpected token error.

SELECT * FROM 'my-table-name'
where sk = 'whatever'

Encountered unexpected token: "\''my-table-name\'" <S_CHAR_LITERAL>
    at line 1, column 15.

Was expecting one of:

    "("
    "ACTION"
    "ANY"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"
   .....etc.

#### Steps to reproduce, if exist:

Create a table with a hyphen and test an SQL query.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed
